format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/atmosphere/restart_dump.astart
  hashes:
    binhash: a651743a375c798614b08f0fba2a72ab
    md5: 64f3193e390955fff5664cacf73f4753
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/atmosphere/um.res.yaml
  hashes:
    binhash: 7ef755b464e84d8f327c2fa38044e3e8
    md5: b5c5b8248eba0fe7806786ce44443652
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/coupler/a2i.nc
  hashes:
    binhash: 58e6f3a9e67b68d309a06eb57d55ec62
    md5: 9a6cdf38ab464c992181967c41822d3b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/coupler/i2a.nc
  hashes:
    binhash: 72ceb7fb386ec241754afc2cc19b3c34
    md5: 1a53559418108f456aa1da6e37630fe0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/coupler/o2i.nc
  hashes:
    binhash: ba33a82cf5b3baab38eb57e32ef08f1e
    md5: 5fbc5852ef5093a8945b725822aee404
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ice/cice_in.nml
  hashes:
    binhash: 0fd62d2886eede037eb6a428370834bc
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ice/ice.restart_file
  hashes:
    binhash: c28baaa24867eabbb4a1f3bf63b4bd26
    md5: 0d4f63a0bdaa4ba3d2e01b095fc68577
work/ice/RESTART/iced.1794-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ice/iced.1794-01-01-00000.nc
  hashes:
    binhash: 198e0902d007490876927cb22e4dcaea
    md5: 96666b79835771cdae0f98c7b8a18748
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ice/mice.nc
  hashes:
    binhash: 1aa53e2b465f8e5084720c8ee98b3761
    md5: 77957cc5bd72219cab0cd0a429138a49
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_age.res.nc
  hashes:
    binhash: d1b1fa6afef04381564199dc3c0c2acc
    md5: c3b2e4fd9a6af388847d0b19dd1143ab
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8501a654b1acf46d76af908581567e64
    md5: 494f782302381126bcf06b66700505c1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f3420c1c73819550d9f113e4d47c037d
    md5: d145198097c17eac92c2629477197396
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_density.res.nc
  hashes:
    binhash: ab179571c7e128f9a47099c52b080fc2
    md5: e57f42947890fb91dc6e0fade2a474e9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b9a1954dd7984afe965cd642bf3a40b9
    md5: 1f4ff59d77bf4bb534d042d668c8e4b3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f9b58d199f5afc1f521855ffaa0a5071
    md5: 9aeb4dcfa794875209565f271e215c7d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ebed918785e358b6e9ef315aa8e27878
    md5: adf806970671d5b84d995cce333df714
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 465b01313f341cab66be26b42e0c8698
    md5: c759b05d7d458f9820984244a919331b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_sbc.res.nc
  hashes:
    binhash: db6c10e452101755dfb1c7d20fa2baf7
    md5: d0840ed638dd4f9479725a16ff80a95b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2056438784c0c33de8d6341b71af1eba
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_solo.res
  hashes:
    binhash: 9ee2857c7a415663aad683395a26c8ea
    md5: 2825eeec809e0d83224fd6ecffe2adcc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 515bef915873d29b7483e6ff51901ce3
    md5: a24ca69032ee74d723e5e69e8a095f72
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 02043162a570634c4582f4429eccc90b
    md5: 5ab9e5e520b9b43cf49629e45e897552
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_tracer.res
  hashes:
    binhash: 67013f0920f46d62b4d95e7762b30662
    md5: e6bcd284ec2f14b31f2a151e016f80db
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 53afc8bee6f5c8abdbda41c91b384f35
    md5: 6d6fb89f022887fb4e6811a5f4192fef
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 60ac5994b86145579eb7ff05ca505e9b
    md5: 116607d4db40058fb784e0363c8d9bcd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ec3788b96fc4c37d5b96bb67dbd10058
    md5: 49359adb42837a5d2f251f8d48cb2f04
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart349/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 110d52bfe9090235ad0d1a47c152c1db
    md5: d7041f9c8fd87a8328a337c2146c7d6a
