format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/atmosphere/restart_dump.astart
  hashes:
    binhash: b6a62b23c105f9659b7a68dc7098eab0
    md5: 43ffe00efc8aef8524c8477f02306bf2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/atmosphere/um.res.yaml
  hashes:
    binhash: 2ced7593d059386e7113fc4ebb5bce13
    md5: 9c8f7a95a27bee75c87ca7c4d26e9d22
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/coupler/a2i.nc
  hashes:
    binhash: 625f3929c1b90c68d3cb353de9182eb7
    md5: d8a3b0f7f16d8321315b997e1beb8fd7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/coupler/i2a.nc
  hashes:
    binhash: d657d5b30efabd89d09500ea67f76af9
    md5: adb4e6b717a7eb6f791322b912f04ebb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/coupler/o2i.nc
  hashes:
    binhash: 069a607a117a6aa8f0ba6253bce45b92
    md5: 14a3aa52a3fdddb7ef336c856a07f6e4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ice/cice_in.nml
  hashes:
    binhash: d2501a8765301f6c90ced85cdc35fe90
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ice/ice.restart_file
  hashes:
    binhash: fd4db6526f13ee576f1f424652bfe52f
    md5: c985a1ac7646eb723cfeb2a1d919bde8
work/ice/RESTART/iced.1292-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ice/iced.1292-01-01-00000.nc
  hashes:
    binhash: 4c88ded0ee57d14fd3f0be143e488a10
    md5: 7680365b7d95ea9b11aadf34c7cf420c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ice/mice.nc
  hashes:
    binhash: d1ba6ec27c2c925c7ace8c862c949d57
    md5: e3ddb35f5d6a3e92318f9851882127fb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_age.res.nc
  hashes:
    binhash: 503fde8301e04419dae07bce22acb566
    md5: 7ab1e21c1573b39b51e19c8aa9271333
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fa65fc45a64bf802520f8a2f72eb5ef7
    md5: fc66c1d498d659eee231a3c4c0dc1cee
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5fe50546cf04d6ab4ec232a2e4eb80b8
    md5: 3617e2cca5754890bfb392d9984b0d88
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_density.res.nc
  hashes:
    binhash: d08f8e2cd30e0fa18747a52e6261ef42
    md5: 85719b1ade49f3590240262b8b014df5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 528a13f29bc657ab3920837e1f053ca9
    md5: 982b2dcbfce3819188d4ba26f78a2eb7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1a07dc0da024186856800c7a9a981d85
    md5: 3877f70cfb9e90f5a1872db164009f04
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fc3cac4751de6d5faa558ad14c5373a9
    md5: f3dcf0e2ec3e9b88fd1f5682d35f9a3c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d1c4677f42f42cf9507c830f026f5b67
    md5: 9d0c2dcfcfa26d25a45d7fcbd24cc1d3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2763ee1cb975493c56cfde089ee18f8b
    md5: bdbd1590cc34479c6c9894a6efb8ce0a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 95a6e831cd98665e416d0d25921ae1ff
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_solo.res
  hashes:
    binhash: 06794ab74f37c89e84294d8593f500a5
    md5: 35e8edf38095e186b2ffbf10700703a1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c76197755306e0596098934bc710a660
    md5: 1d1044f64e88c57a8e0c6f021f76a527
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 14cf7a843bb32c1c2db7cfa76c4f5f01
    md5: 175149bc0f4a5a3894b9955b27abb544
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_tracer.res
  hashes:
    binhash: 876b919a7d6007d63677fc17a73c6fa9
    md5: 46051991465fdcfed58ce93938f6461e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7523a4ec019cfdfe0cd5632baa292532
    md5: 6f39e4bc49410229bebfa79464a0eecb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6cb245c75625f73b2da0f2dde26ad8f4
    md5: cefde82bbd090e18ea4d33d113a7827d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 599e7f5febd6fe7464f1aa14e5ab9843
    md5: d962625c5a2fb646615a03235bff2d62
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart408/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0ea3dbe65f5ec7c04f6fcdf07a0165fa
    md5: 6f400d097916a927cb895ccb13701afe
