format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/atmosphere/restart_dump.astart
  hashes:
    binhash: 3854d7ae770d2119c6911ea8e2841aa6
    md5: 2de9b1d77e2ababc1f2a964988dfb601
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/atmosphere/um.res.yaml
  hashes:
    binhash: 0f2884a2f488e2f6aecc96fbfe6cc13b
    md5: 6d6474ddb15307a9a21d48388c1485e8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/coupler/a2i.nc
  hashes:
    binhash: 1176c07eb03beae7163e5f8d983225b6
    md5: c2d65169b122844a2b1a3cb22c6cbe65
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/coupler/i2a.nc
  hashes:
    binhash: b37680a5c27f1bccb9fb4a042c71486a
    md5: 163954bd1c73f76a8578ae845bc9dd2a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/coupler/o2i.nc
  hashes:
    binhash: 61dcc2a1bc98752f92f5c500e1dd60e8
    md5: 5018cc78dca8189d300aed9128a2694d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ice/cice_in.nml
  hashes:
    binhash: 189eb4f9d1fe746b085a0fae6d3ef332
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ice/ice.restart_file
  hashes:
    binhash: 80425370b525d59db0de3b9a1053a700
    md5: 22c21143ae1d7f4b2c1a39d633d9ad75
work/ice/RESTART/iced.0978-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ice/iced.0978-01-01-00000.nc
  hashes:
    binhash: 560847ce3b1c6cc9a890530652577b16
    md5: 625cd0e364eade3d1de79861a9d52472
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ice/mice.nc
  hashes:
    binhash: 85a9b264b74fd2599a3d214f1b1c5756
    md5: 2588c3c89225fe8ee28fb8686e61db9b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_age.res.nc
  hashes:
    binhash: a0c41e74b6470efc5ae5401ad09403f3
    md5: 70abdd12e6118bf19650b49d3063fb57
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f892aaafee962b0fdf453f452f5252b1
    md5: 695d0fd24eb4794fedb9e6afbd913ff1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ad1b8be0a6d8ca60cd5fae77df6cd378
    md5: ae79668ee12af3e3cba83fdfef0ef42d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_density.res.nc
  hashes:
    binhash: 68c6dfd1eb2c0ff65dbe46a8a397e018
    md5: 7a2df93f97900eb9cd04e05884b8542c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a1b8baad65c3973ca61c9a252fe5dcdb
    md5: 6fad55a84abc89569c54b1c6cd2c5204
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3c68f403ee8a79aa4e8dc5fc7f584682
    md5: 686552f80dfd3e29f0807f3d72e996d6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cb9b0d700087c3992c2b9c78ccf67d66
    md5: 6c4cdba1e61740df22d6f96f64a654ba
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 59009a2c887d32474e22d9d8f108c344
    md5: e9c3a5d847008f8933438260c27999da
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 695f1e4b063970b15dc7769525f658c0
    md5: cdd139801001d3a40cea467493ee08ce
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8abea953c6fd61dbd93cfba869c1c108
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_solo.res
  hashes:
    binhash: 13effcce00ab8ddd6d377685a924050a
    md5: 3d5d6ba84c6f06dd219cbda19f01d407
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 450fce6eb851bb0bec7199c36a0fb28c
    md5: b006f3addcb36eae1cfcd2db0cb19cba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4aeb9977a676f210e243ff41059181c6
    md5: 4237c584f32a783613b38ba21361e8ff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_tracer.res
  hashes:
    binhash: ca2f5fee46f52c0f85e36a7533e0718f
    md5: 0ac45a2878dff2b634885ccab61d96ce
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3d412f733eb86d50e2fba22e1a88f97b
    md5: 7aaf88e4536f18500c89709b193fa3c3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 27324edb3a51b56b90c52c47a736c207
    md5: 7ddb7e8f0e373c309f595cc99df48b70
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b07256f95f6862fca2b7af9f1b67c53b
    md5: 7ef7f5466a8718fd5785c22b29d61fc6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart424/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b5215df7888db56aa600e2916519d57c
    md5: 071dc9d4cecd3bf6c0da935585468a34
