format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/atmosphere/restart_dump.astart
  hashes:
    binhash: ddde901f2432ff5bc847f4662d4772e5
    md5: ba89c63bfba568c4ee704e04b9591174
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/atmosphere/um.res.yaml
  hashes:
    binhash: eab46c735ad4ee5bf177abc065d42c6f
    md5: cd5da6888c2ae297af3129ee39a910f0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/coupler/a2i.nc
  hashes:
    binhash: b37d1fe927f9f5fa8b10fee76c349b1d
    md5: e11b796fb5521b3333f4308f95f24092
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/coupler/i2a.nc
  hashes:
    binhash: 3306672b022f5510a438e9b1ff199a5b
    md5: 9b20bbb414be9ac24fa8d8673c39ef7d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/coupler/o2i.nc
  hashes:
    binhash: 0fb5b147c1d38d03dfab578c40453833
    md5: b1f69b89cd112b00c3d2274d9aeb64c9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ice/cice_in.nml
  hashes:
    binhash: 8eedd19d16432ab3eda331ee6a711c55
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ice/ice.restart_file
  hashes:
    binhash: 0b85a23153ff17cfa411eac383b2157e
    md5: b40f771363d82ed67fd82d7a6ef1cd97
work/ice/RESTART/iced.1781-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ice/iced.1781-01-01-00000.nc
  hashes:
    binhash: 097c55f565dd2e0a59c773cfe0ca3134
    md5: 8faaf095e3a01cbd9531df6c96263e0e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ice/mice.nc
  hashes:
    binhash: 4a82c44bf70287c07c8adbc9433bfa38
    md5: 63dd895a856885749d2b975da1b89052
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_age.res.nc
  hashes:
    binhash: dfba44092526ba377e005d97760f7f2b
    md5: bddba148ee290cc824f7c4daa229f6ce
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8011074cb1cddbe2e92fd7ac1ea3ea8d
    md5: 5ecb689889c61afa555da3e04db8c282
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 940a9609e6cb4ea57d3117656943d0a0
    md5: 6d1222a6eb41029fca938000ee18e04f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_density.res.nc
  hashes:
    binhash: 7be3df2233936b3fbc18ced79a41b4d5
    md5: 6ba25c0c508c623b93f5093e28f351dd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3089b30c3ee83436201c322a291e4f11
    md5: 2eb839d8f30c6088f847284e7f2fc234
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0f1769bc0753dfa3a51fdbdfbad83462
    md5: 80643f585b85695289827a08f87a4dab
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cd86a993495fbfa8ecce82d937a9394c
    md5: 4e4c5a9b5ae91e08907c1b582976e171
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 78754f30239a4f09f2bc32f9fe6940b7
    md5: 011280f9ed3dda089680d61dd504be7b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 52ae15dab20267fdc51ba8cfff17c510
    md5: 8b8036efc2c9c660e30888086c503701
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: da9e8d2f5122b3311672c2538b45d356
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_solo.res
  hashes:
    binhash: 636ac47ac3251acbe90331cdd1af4621
    md5: 0f79b2c8ef48a73fa80194160f6d9993
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c1aceff835a976cc6d62115aef2139ed
    md5: a7f241af6dccdaa42d16bcf5245f215d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e2e17f6b208364738d67b84e3f024f9e
    md5: d38563f18edd5aaaf0fe62a8ccc4ef81
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_tracer.res
  hashes:
    binhash: 4438dbfcdd38294e3175f7d648dce0ef
    md5: c54bb260fd112374abff7951a007508f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3baf19c452911a8ef1d1a5fb80ca62cf
    md5: 77ce90b3848b012ce63a81680ddbc505
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4391e3727c287e89c9517f5a79b7970c
    md5: 2c045c91d6d076a54d0d0e6fb3bd5d12
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 38dfb0a2fea74e198e0ff3e1caee6403
    md5: 06112cfdd74101633da9fa16a810aed4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart336/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 25933dd3eec25d723e1314d4ae1ffb59
    md5: e4863ca787903001c0d0e64b971fb276
