format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/atmosphere/restart_dump.astart
  hashes:
    binhash: cccc8c453bee7db59aae733827b2985a
    md5: bf44e550890481a8262e6c38b105588c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/atmosphere/um.res.yaml
  hashes:
    binhash: 473cefb8142e2267f86cb64f99f78d7f
    md5: 891e7d21f6238bfd8ab79272ea961a73
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/coupler/a2i.nc
  hashes:
    binhash: 0cb63ca66037e6a1b1c8d6a911a439b4
    md5: 7b9c6b7ceed2a58611b5c7a3a0d68e27
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/coupler/i2a.nc
  hashes:
    binhash: 8a7b678515a61abe8b8fa82506a71800
    md5: a79cf042169a70ac7b8af69ab9975deb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/coupler/o2i.nc
  hashes:
    binhash: d2bf882fd4bd84ae7ea0105e66450fb1
    md5: 646a70825e678c97bc72832f5a549b6b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ice/cice_in.nml
  hashes:
    binhash: 3d0b441d24e283d5212cd88f1304e7f3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ice/ice.restart_file
  hashes:
    binhash: 62cc7a7167a9522ffb68b8478100617d
    md5: 9df42f763fab2ddb8df0d9e9c88fde3d
work/ice/RESTART/iced.1713-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ice/iced.1713-01-01-00000.nc
  hashes:
    binhash: bacf5e7da0e6e8c8446ffafc21d1ec7e
    md5: d2e7a5040ec7b08cb1ce136da893de66
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ice/mice.nc
  hashes:
    binhash: fa8b06a534f3b5d43e4da338fe7f18e9
    md5: 3101c28aec0344f6396f4f287a08647e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_age.res.nc
  hashes:
    binhash: 9dabd8c71ba41e7edee8e059a8e56d07
    md5: f0b4be6404c2c39cc7df495930ac22dd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d82ffb0020dd50ae3de48c966f188795
    md5: bd8faa8eed83cc82beccb54bc98e90ad
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 27746260b349a8ae81f63da79bc93001
    md5: 46a123e0bf4ba13fb4fa832c670a2ae8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_density.res.nc
  hashes:
    binhash: 4891bf9b2a1369da116e0f71669ce21f
    md5: 9d6a913eae8e4a41ff74800b76da948b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b968e633fe9756d2bbcbb529aed6c44d
    md5: 7023fcec4381997050b0d82419e3189e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7693e7ae641a200b51666a268e572942
    md5: 760894c2d8e85005668142c2f04b0a22
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0624e7af64858f534101a4614ceb535c
    md5: df01f6fadce35f381132942c5fd958cc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0b74a7bbbc2b1898067b7886056179aa
    md5: 3bc004c1c6f7776b21578209aba9ec59
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2e2b963d91efd74c3c2186e462011d02
    md5: 2903e92f18695e54453eb44d414fc22f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 156647f2a70ee651e269ba96a67e5f53
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_solo.res
  hashes:
    binhash: b5aea80030908ce75f60e69222464640
    md5: 014d7997751f0dbe6aace2b59be25de9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c7e5d35160619f73770bc0bdf6ba0fd9
    md5: f9217860005aeff572e0175768cef079
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 08b58128a1602656b7e13a4ec341dc34
    md5: 8626778827de8ec3835aafd0b55a6ed4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_tracer.res
  hashes:
    binhash: 780cf12ad95d2f6c631cc3d837b40e27
    md5: ab5317d30088ed213e47784a3bd69758
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 60713c07d74f6136792e7be62bb7bd1f
    md5: 4017916cbb8a7f993bfbfdcc9ed18ed7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7cacdea2e27a956859ca2e7ea5e842e0
    md5: a5e85529920c9f8d91bf0b96517efc55
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 846e9ea07611a90548540fa1674d63ab
    md5: c2f4348854a210615ffd4a14303287a1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart268/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0e8f8d05838aa4df55adb92654189880
    md5: f9f83bc1bc020b73c13759dae55e5cc5
