format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/atmosphere/restart_dump.astart
  hashes:
    binhash: 2397edb05e1cf30c62978c99e97f54d1
    md5: 3fc65ffc78d4a4cf15d0fbda8ceef99f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/atmosphere/um.res.yaml
  hashes:
    binhash: 6d9044a72cda6cf1c3fc64616230e70c
    md5: 708f540eb3eebd910803be5d76384254
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/coupler/a2i.nc
  hashes:
    binhash: ba2a8f37ff844902b5363e9bad02cc5c
    md5: 5a4baea74282d441a002c78f9eb77d0d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/coupler/i2a.nc
  hashes:
    binhash: 68f3de99d81bbd104925c69f6f7f9296
    md5: d4041c7dd08524ed9e7b1eea285afe54
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/coupler/o2i.nc
  hashes:
    binhash: 15fe54da11611dd434a17cb3f38d7747
    md5: 52bff6a6e7026c13eafd8f74416f9570
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ice/cice_in.nml
  hashes:
    binhash: 76bf3f5a735c73598b337452a73190c3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ice/ice.restart_file
  hashes:
    binhash: e25a96327c453755c1ad5bb7b88114c6
    md5: 252e7b3eb789dc42878265749b0b1976
work/ice/RESTART/iced.1215-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ice/iced.1215-01-01-00000.nc
  hashes:
    binhash: 6744b3fa28977c348a27a444a3da36dc
    md5: 8c8254121a10b979eefdbffdc4f2a1b0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ice/mice.nc
  hashes:
    binhash: bc52a7a0da4c6aeeddebd4720f9da12a
    md5: d99ef4b1de4213ef48f35cfb6a71a58e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_age.res.nc
  hashes:
    binhash: a36f1ad98452580c33759820ffd4bed6
    md5: 022ea45e2d83877c6849c82b78ddc0c5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 076ae3c209780f5e063e733e18b1d1f5
    md5: d4ba4cb7e65f29d7a34a12a2b0bbb37c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 779ada0b131990abda9876abb7b4464b
    md5: b66af04556597a96f70109680512c179
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_density.res.nc
  hashes:
    binhash: fd9a9084e93decb59e213a7afec404e1
    md5: 26d6e66e0e6d1dfd75f375ca235c5f2c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5774835e22f383b3794ef44e24edda3c
    md5: 0b2d9533e13132778d583e1e081f24b1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aaebff0485bfa00b9c95e021fa4407e0
    md5: 1f3d30042ac40079abf94a347f0a4d58
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57795e04bbfe4a819e3994377a5a0eec
    md5: 2025dfc9202e7829bd2472ea1acdccf4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: feaee142f2e6b7b84e52eeca23391fa5
    md5: c187e2f6bb303acdcfad68fd1190132c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b1609ba38f5a8831f2d4e167df10c66
    md5: af8782487eb6c4fc3e84f911bf34b0a8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f79365891e05c4ff219a6d28ab585f7d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_solo.res
  hashes:
    binhash: 817542b98214c7c717eb7a8dd6edca73
    md5: e2ed44056996bc9e0fb1d08efc887d83
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7ad289d9ddbd4b2c0964cf89e5110e2d
    md5: b5f2c369762ef89cdf9ab667817e8ebe
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0d0140a1ab91d97a59be71b325c1a594
    md5: 63e5a4c9f5bb367ac449078bd3e87c30
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_tracer.res
  hashes:
    binhash: e7b82e9284b582eb5f21257d502caafb
    md5: 1d0822e05910dea5298115a92538fa39
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5995025ce52746df1c8f61b6c327718e
    md5: 1c74e904223a69f3dcbb0674ddf77ecc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: df8d1f1ed854b410290264c202e0b7c4
    md5: 22b99becfa92bf959264a3b1fcfdface
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 98657efd660da6c9f3b2a0903ec61c8c
    md5: c9b11c76e27677ad13f4bcb82260008d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart331/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a23e3b49f1e62179f3c1c754eb0bfa6c
    md5: 282c46901787b81aeb9698800ad579e1
