format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/atmosphere/restart_dump.astart
  hashes:
    binhash: fec1d8d5ed0f9af02a79936e37ed96e2
    md5: 20934c2336a1ae89ea3d4808b070fd2a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/atmosphere/um.res.yaml
  hashes:
    binhash: 4d5c66b70f839f425b050c58e84964d0
    md5: 59ffaf1f04f388091ed383196e5fa213
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/coupler/a2i.nc
  hashes:
    binhash: f4c5549c01183587c65d10d61af1276e
    md5: 860e6f40a1f95211db182405cc8f9bb8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/coupler/i2a.nc
  hashes:
    binhash: 26414a62cc43f27b93fe43b6ea5c6f2c
    md5: 982d2130c2f70c014275adc12b63adb8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/coupler/o2i.nc
  hashes:
    binhash: a9699186abb22b2eb7084a017c4a88b4
    md5: 895a9c143ab91ff16b88f2dbab40071c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ice/cice_in.nml
  hashes:
    binhash: ef5487a9c71fde2bcbe325b498dcc124
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ice/ice.restart_file
  hashes:
    binhash: 01229fdef5da00955d8c601155459c16
    md5: c93a09903897965eef771bdd01773b83
work/ice/RESTART/iced.0974-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ice/iced.0974-01-01-00000.nc
  hashes:
    binhash: d97ba5744366c449cccfce4de64a1733
    md5: fd20b69831c8b670e1fa9111dc79f31b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ice/mice.nc
  hashes:
    binhash: 5e644147159923830233ed702d34243f
    md5: 2a7f3af6b1b65faed51d99dc9f794142
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_age.res.nc
  hashes:
    binhash: 8df7da34b02734411fa3540870e01d71
    md5: c57006fb1a33af6fde7c711d7a47d0d5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cff32e0972a66bfc1327fb54d4832dce
    md5: 0aa2c65e9fad442bd0149711a2efe110
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1b324e9fbee36e882f1c3b1fbf3244cd
    md5: b1f8f181bfe6cf1c5833ff61e07e9036
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_density.res.nc
  hashes:
    binhash: f77c37a0043020b4a69a29cbcd3c8c35
    md5: abb66b4f669036e6b2845c379cd713cc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 77f8a61db4085a81c05fabed7ca603d0
    md5: 2518e2bb8cf011b0a3985121afce4c0b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 987d79f1251f077c5a71116d61bd10a9
    md5: 7ea3de8d644610163704b7c2d8984115
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 30b220c610609e68482c9ff0c21ecd3a
    md5: 10122a4236fa1c417aeac41f4de61621
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e35889b66710f2cbdf1a9c2a3261e2b
    md5: 56be9dcb527fe4fdd73982af5c353f1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 41fb62d7105ab20f4ba45e64e4919d54
    md5: b085a37950a22072406453ed42d49a8b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f55a6ed30319949fcb5e249a867f0f98
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_solo.res
  hashes:
    binhash: 0eceb1d3b33b96fe61f955e548aa022f
    md5: 6c150296e9a67b0de2d6dd65b7249126
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c8a5eed104103890366bf65ab7f81549
    md5: 41eb06dd684e6424ba74f3f17f0346f5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 665a2c4c2e719c5a849023929c67f546
    md5: f413693955f5801583bd05b64259875d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_tracer.res
  hashes:
    binhash: 964a3bf807af797b97fe31445ca57df3
    md5: 6a6fc105c5d2c1bd20cb2369e1f21f95
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ceb5f0aa35bbc3a2a0de9b7b31827b9b
    md5: 0cf9cab8a943deada8741085cb637e05
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 160aa70b8d8f69e5388a8fab1cb113e7
    md5: 914e6d4b03d379b93efd4cd1cece3f41
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 011ebbe2162e13562fee528396134158
    md5: 85633cdc5c0ffbfa180a7f749d0a5721
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart420/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 892c2fe28a539dc501def6083f4e106d
    md5: 1840a0675e5095d6ef5226e537d7a89a
