format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/atmosphere/restart_dump.astart
  hashes:
    binhash: 44a0ed71adbe0550a8788babdd571e55
    md5: a64bc17897311a3318b196ad752770a1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/atmosphere/um.res.yaml
  hashes:
    binhash: 8f268be01872ecba8d153b07e93725e4
    md5: cce98ead0edac81decb8347faacca049
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/coupler/a2i.nc
  hashes:
    binhash: c483af32439905578e521a8095c2b50b
    md5: 16019527e8ab276e57ae41bd0e3381c9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/coupler/i2a.nc
  hashes:
    binhash: ef31144c291c207c04f15ff7709c189b
    md5: 44b7ee15812819d876e7fdacb8d6b197
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/coupler/o2i.nc
  hashes:
    binhash: 8c05ca91542daa413b183ad7eed567be
    md5: 09e460be3d4afdb583990b0341da6b53
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ice/cice_in.nml
  hashes:
    binhash: 3978209ce8d28173a27ee55c28c85504
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ice/ice.restart_file
  hashes:
    binhash: 0d639a7dc826d96cd16a45a1c8a3d2dd
    md5: 281de4a43a2acaa6fc223a1ae70e4719
work/ice/RESTART/iced.1759-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ice/iced.1759-01-01-00000.nc
  hashes:
    binhash: 281abadd994f26524bd75aa9ed824cc7
    md5: 3b988e3ca6fa4a019ea966c669b7b61c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ice/mice.nc
  hashes:
    binhash: f3e6a0cd976859055ae7aca5c23752e7
    md5: 4f8ee865f2ebd1aacd4109ce43738665
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_age.res.nc
  hashes:
    binhash: 09484afc13383e86ffba80bf2d949487
    md5: 30d0edc0d2adf4a91530c364f248bc2f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b722864d415dbbc25a0725f038bb317a
    md5: e0a813b135a47408f6d527e95e963ce8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 127d4ec42bc43e3d6e915cb061ac80d3
    md5: c3b41c0a6f9b3acaa56de82d935c64fb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_density.res.nc
  hashes:
    binhash: d0f3582277576d052668ade81c3f12f2
    md5: 4eb3657e6aa5473798913f494c890870
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d39cc1d516ee65ad47dbb49b79ddda01
    md5: 6d9a434fdfbeecd122a630091bbcbae3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a1ccff321b7521c0df6f351edbc334c9
    md5: 66e01ad99e62d13d5a63099d0492e14c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 163c1f303a821b6ffd063615069e1371
    md5: 99498a207aeee779359501bb475922af
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f30ab0e77576f98bd5be0575653d8ef
    md5: ece597d0d16290a085e0ae74918daf15
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_sbc.res.nc
  hashes:
    binhash: eb86902e36e3841d0ce2052c3daf1e3f
    md5: 046dfa888bce721de95541eec4448e06
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 04f5128f44956455d1e239f4d8029434
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_solo.res
  hashes:
    binhash: 899dd4b7c79835550f14d7d6af0a4fcd
    md5: e819c905e5545de3f9890c0356f754b7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 38d58f6712cf8d719b7e5ac635b3bc66
    md5: 08090e8b0b872f2b560fc41a67d6e293
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7498036670240921f9a36401499088a8
    md5: 0daf27a98c1b29afe2a8de42767bf0ff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_tracer.res
  hashes:
    binhash: 581c3b744e43afbe0a06fcf77504b978
    md5: de6871daf317ce5415af45fcae24d04c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c765600f9f5a77fc4b93e8288e893f04
    md5: 8420a2a1086c152114e3bc4b199b3751
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: abcc09db5d5e929f783e33282b330b70
    md5: cec5942099e7995cb0acd0b49fec871b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c2bbbbb7f756275a59ffe709b9f705ab
    md5: dbb1ccf761ac251d63864b578147da1b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart314/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a05cceb8366a6c926e4d7d32e60f3588
    md5: a55c05b38b9d04bc3522bba53c2a3993
