format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/atmosphere/restart_dump.astart
  hashes:
    binhash: 659e93b96bffcdce474299b2753ead18
    md5: 852925136ead5ea0113ea9de51d72104
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/atmosphere/um.res.yaml
  hashes:
    binhash: 3fe9ddae2f06eced0247812898b5ff74
    md5: b7f8c4b3b021b99c686a8ba972f9f920
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/coupler/a2i.nc
  hashes:
    binhash: 5d36c88bc53293a939fd9ccf0a3e2eee
    md5: 1a35a9f5e1b575b4f8ea90b3f9d4f44b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/coupler/i2a.nc
  hashes:
    binhash: 3a947fd96dca064e9556ba31189a90a9
    md5: 9bc44ae8e62efea87ed50c292d5e6a0b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/coupler/o2i.nc
  hashes:
    binhash: a830793e2a30d0d5a538622fa05e6667
    md5: 42b0238c63006abcd8d42b27ccecf1e5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ice/cice_in.nml
  hashes:
    binhash: a90467a99da892dcb30d2440a2998af3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ice/ice.restart_file
  hashes:
    binhash: 989ad90a715fa42722c9e3ec39ad25a1
    md5: 595ec91880d3411a1a15fe3152d915cb
work/ice/RESTART/iced.0939-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ice/iced.0939-01-01-00000.nc
  hashes:
    binhash: f7ec54aebf6c2dbe22281ea730240638
    md5: 868d56587da1bf46b9a29875baad84a7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ice/mice.nc
  hashes:
    binhash: e433e25fa7b437d441d384bcefc9c528
    md5: e633bc9355dc42a9c342c421f27a0b99
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_age.res.nc
  hashes:
    binhash: a87cfcd7ec8f987891e17f5ff50fbe5a
    md5: df78099b8854cb874bf2ea86f7d9cdb5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5e7809b5e496735f8892ba49ecbf70a1
    md5: 627fcf748a27f57bc0cd3b2fe7d10b94
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6b8a24008ff6b76d089c401f53699307
    md5: 4b661e1c1f6e2495197f9d24c5b12547
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_density.res.nc
  hashes:
    binhash: e2a44f56a6df2acc963b611efe164caf
    md5: ac8d8b7b32ecf4dd7db8682d0db018fa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f7ed23aa80e70d792b9205bbd40466cb
    md5: c40174dac1b70952204a3c654f410a9b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5c2f4ac1ab4a6b0948479b9d3fe77c93
    md5: 766665b9a337bc31f76ff147b6ea02ba
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_neutral.res.nc
  hashes:
    binhash: feee517598d22008e69fe26a566701f3
    md5: bb0389e97a708f826ab35d404b11b1a3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5916cd2da0178fa89b8b636d4abe8da3
    md5: 7ff0ebcbbcc3b1f7192140bf9592c2f8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c220a74e3804a6396f7cd726dee85a11
    md5: 3ef00c5c6642ba689dcebfceec034cdc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b0564a6d2e63e18b7cb9521352418197
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_solo.res
  hashes:
    binhash: f69a28c2b43f7468127f9027f0128ce6
    md5: f6437749a3032eadb0c3092ecd2cfe09
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2221cc12561ff14192a7a2c7b8c401d1
    md5: fb593496e9263e7534290c80b74c651a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ced778652bb1dec1212d0e6795beb03d
    md5: 2062849ecfdb0f2de72645eeb51e267c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_tracer.res
  hashes:
    binhash: ab823cd1dee7cd788e92c341ac3d9052
    md5: b8f314659db7a1f7222756401065cf36
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5a9bd2fd9512b9fb0ff17c0bbdde73c5
    md5: 34548a1b87cdc8af0157ecdd52b95af1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cb45a7230f7e9a764a9733da39164933
    md5: e4f704780b91f2b787e308301e326d09
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dc79f23d92c3dc6e3f6eb899873075a7
    md5: c93e87d14bb2c568e33bcf144b76f05b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart385/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fe63c5cd8b3a4757524a85ce6e8bc6f0
    md5: d2836d810ae25ea6cfa7298c3361b8c6
