format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/atmosphere/restart_dump.astart
  hashes:
    binhash: 75e9dd9cd2a2c0999d4e0a3b6f37db9f
    md5: e6c1f38c47a1ff169098b37bbbe7fc77
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/atmosphere/um.res.yaml
  hashes:
    binhash: c4b67218d9c049c8faa1716d07ec987c
    md5: 84c358f8ffe8c22d250b79c0dde77195
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/coupler/a2i.nc
  hashes:
    binhash: 923ce20e4cb1b53703f2fe276d85e222
    md5: 6f14ed5992b80022218eb92baaa8e197
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/coupler/i2a.nc
  hashes:
    binhash: 5e16110facab5e619a1850372ca488c9
    md5: 0311277ec8e4a658aa8da2275caaf4b4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/coupler/o2i.nc
  hashes:
    binhash: d38f2055a23c2f96c98629ad396d49ed
    md5: 10f51e6170bfd09316815edf9ee37888
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ice/cice_in.nml
  hashes:
    binhash: 62b0317878caa0ea6a9fa4a5676cc1e1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ice/ice.restart_file
  hashes:
    binhash: 69ea4e51a8c28bbcd3490b18568a40bd
    md5: 02523ec106788f8be171a040637a5c50
work/ice/RESTART/iced.0934-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ice/iced.0934-01-01-00000.nc
  hashes:
    binhash: 044dbc4496e3b583d46895e90722712a
    md5: bf4c68a7cc29dfbe9d82b2c7962b4b17
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ice/mice.nc
  hashes:
    binhash: b7734fbc066dcf5cbd5bfa24c2e2c6ee
    md5: 518736be68177ad61b2b5afd3473a273
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_age.res.nc
  hashes:
    binhash: 69a6b6619e5b2e4f5adc68b207cb8e03
    md5: c692557b6e16871bf4f94012462a0a65
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e13d5031184babfd4dbd7a07b83b644a
    md5: e04cf00bc0c4cd1e2a29f120778d98ff
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 88ae220c5e14f37e7605db654f95fcd1
    md5: 937915133d4eca2a4bb6bfd799d18c42
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_density.res.nc
  hashes:
    binhash: 439296539f69ff570d30899b4d5531d2
    md5: 9c34e3c4a1d9fa9fe6e7e97fda70a1af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 165475b1f532c86d8a7ede3eacf9bccd
    md5: b269874e8361da58e4ed113bb1d4222e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 80818315bf42d3c0811c72ce57e4de74
    md5: 77795449e7831ebe73a80eff1aa9f6af
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 97a42811f5b6369c236ad4bfcec55cd9
    md5: d11f9524d0a3ddd6d736744ef904d139
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: efb1f7d84a06de7aa878af1411f2e39d
    md5: becf4493b5fb77c76110a4287b2f2a30
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e8d701cfbfccbeb3b8b850e7163c2472
    md5: a250e86b8ef15d54d3a5f79d184da345
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: be60966e541bf568b47dd624208c3f95
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_solo.res
  hashes:
    binhash: 5cc5e0e6794fce4ca1d37fc61b050266
    md5: 845fbf30684fb61e2e21d83af7a66e2c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 984c28153f8fc896b948e6cfbbf80e82
    md5: a854b13029647a8e4a0f1071cf3ab3ae
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ab7f2ba0985f3eed61c9347118ddb376
    md5: d451e270640088ca5e6bff1bda7b409e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_tracer.res
  hashes:
    binhash: a415c3b47e537d0b5b42487cce8e0b36
    md5: 86ceec895c1dd4e454ef1d8772411c78
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aa834d9f54268c2ac3c3789cbeeb3e61
    md5: eb85e1556be07a746fef07de4007782b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d4a7ff695e2ce6f6509d7b5e025af9cb
    md5: ce9920f91ecc347baf803a22328fd014
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ea149a77371fa80648bdcff7576b7a76
    md5: 8ce91b411802210b3aa8c297f82af336
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart380/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a8ba8ce541bb2c83ec142e23132be8f3
    md5: b51e8793023ecc3e99b1e105f677c07c
