format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/atmosphere/restart_dump.astart
  hashes:
    binhash: 9e7abc1b05067f2e140b8b1ca636b2d9
    md5: 3af6e7596c3ceeacb0213f69651a9a93
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/atmosphere/um.res.yaml
  hashes:
    binhash: 306f7be7a1dfc437ecaa0a86328e48c2
    md5: 1bab48e4d691ecc461e9efc9497466eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/coupler/a2i.nc
  hashes:
    binhash: 2c92f5340cdc12223da9fcf778bf2f65
    md5: 4023253028db2b23bf4fd7be06d2ad52
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/coupler/i2a.nc
  hashes:
    binhash: 3ad3e3eb9ad6cf1aed1fd388ecdb0769
    md5: 6bfa5190f0eceda30275b13a0bddefd4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/coupler/o2i.nc
  hashes:
    binhash: cff20018f6b06067f4c18a9e78fda118
    md5: 9ac819657c0407b86c2d25d37d4ee580
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ice/cice_in.nml
  hashes:
    binhash: a01cb1ab6f0810c0d039d8b87564c262
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ice/ice.restart_file
  hashes:
    binhash: 26bfcd02e508fd4da3a586870d0f9efd
    md5: dc607adc367d8b5177290c64c897ca1d
work/ice/RESTART/iced.1714-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ice/iced.1714-01-01-00000.nc
  hashes:
    binhash: f018866f50bad7748ae6d10708e6549a
    md5: 49c17c21bbafa94111c1feaeca32f1e3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ice/mice.nc
  hashes:
    binhash: b0a47102d57a87cd15fbde9e1f624f09
    md5: bf61318f9df13752750f38fd740169e8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_age.res.nc
  hashes:
    binhash: 23ab8e8558fd0fa199f83bd973979435
    md5: b65f2939e83d03dbe0ff86490680a959
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5bb032d0bd22bd8b386775d92e5f9d4a
    md5: 6eb126d29c1c6fc2f075874e51b00cd5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 598af3448e41c843579e066bfef60765
    md5: 3fa2b1c23ede90244d871a44e2ff81b4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_density.res.nc
  hashes:
    binhash: 831f79dbfc7fb3e47f36e0728d90a7cb
    md5: 03e4a0b744fe3ac150421a3daccb1cbe
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 52020c354dc7437471289e0041081fb6
    md5: e0c14be876bba8223e8719f46ad9c725
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c781a2bf8ef24ccb79d6934d5867a668
    md5: 0263985607c15254c096ff930452cc38
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6064fdcea38071ccf0a5a7e726df682d
    md5: 50de6a08295322b0d6de17eb78dd9d6d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 884b2c6f72dd517f4fcf8551bf39a701
    md5: 5f40ebeae93ba7a511ffcdd4ef5a4cc1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 526b703b303b8ab783bff7aba76915d9
    md5: 7d6376376e0f44a0a9ebed622814efd5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c16e2b1b025b3782629bc1af44164c5c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_solo.res
  hashes:
    binhash: 00190348e76ebff982d253eb57e73cb7
    md5: b4398ef742cab958f312c577ecd0cf2c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb4c5ed8d4ab84ad9409c93ddad9bc13
    md5: 3fe848496000bf20f0032523aab96f29
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_thickness.res.nc
  hashes:
    binhash: facd3a953d158c287999da5693e44f5e
    md5: bf71ab9e8994eb338f6cd722e058ac52
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_tracer.res
  hashes:
    binhash: 24d98666464c45b5a71c76a93c8bdceb
    md5: 3b02dd0f046b9e827824f4963ba7366b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2f7777fd024b7f447b606467a84d400a
    md5: ffed8e1c5c548d22043e1a7578213d97
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5bc2823fcbe3bce77c61bfd3406371a7
    md5: 4006fa4d45c37bc29b5bf40b76362b29
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6765563d6cdbc2aec96ca9f12c184f05
    md5: 2760f6bbd077c7244aab425ba7ae9c88
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart269/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4a3821ebcf2bc957e28a413ca840ce30
    md5: 59c03c824ee0ef33761873c2139b3b42
