format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/atmosphere/restart_dump.astart
  hashes:
    binhash: b5fade1ad3b57cae58543743d8c2b913
    md5: 334aae1a700302c29e549320e912bc69
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/atmosphere/um.res.yaml
  hashes:
    binhash: 1fc5d3c54fe2e8b4828e01c1cf36fcd3
    md5: 0fb71ce2df19c44edb6d7ad9f7a0c8c1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/coupler/a2i.nc
  hashes:
    binhash: 19f8135b6632aa0c20e8ca8d2f7a2c95
    md5: 622ded2d7878ed55617eadf734a6582e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/coupler/i2a.nc
  hashes:
    binhash: 977fa8eb81accc79af3b6268e2d24e40
    md5: b40fd02cd279a5ef228882cf504d1811
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/coupler/o2i.nc
  hashes:
    binhash: b0711071178c269caac1c92d60656f6b
    md5: fa22ca4043b17b5dc031b68d4846f21d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ice/cice_in.nml
  hashes:
    binhash: 6f2f1a07b1e66c452f58fd3b0de4a01b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ice/ice.restart_file
  hashes:
    binhash: e947bd1fc87f168640db45ecbbc38bf5
    md5: faff2519b8e1c2e3848c44457e00f59c
work/ice/RESTART/iced.1738-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ice/iced.1738-01-01-00000.nc
  hashes:
    binhash: 42a7829fc7f23dce999d0f7d558c0628
    md5: 24b5ef8366c85c2b0997cd0bd3cd16fd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ice/mice.nc
  hashes:
    binhash: bb7080a786a8d7882d1b050563259c48
    md5: bc7d91e6a802f34a19a3b9ad84637788
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_age.res.nc
  hashes:
    binhash: e0f36c5876d2878bf70adba84a3ca9d1
    md5: 2387887043e3f7ba5963f69fb867a16d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 28c693afe1745d25708d53900416e2e3
    md5: df42028f44f48ce71942e659faff2df9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cc5a21176ff7f9a8fd2e5f79ca63cbab
    md5: d7e5de40fe488ecf6c0dbfeac1337df2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_density.res.nc
  hashes:
    binhash: eeacc3f46ae7d340628cef1bc75bd0f6
    md5: 27d32afbcf36e2e3c7fc0383fbe155e6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 532bb4894aac6a769ace271daf4ca62b
    md5: 9f766d4a0c6ae00ba698da0bf9236b04
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 988671a212b73d485ea5bcabf95a9cd9
    md5: 18d283d5c21c93e742249bd94511f178
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_neutral.res.nc
  hashes:
    binhash: eba82d118cd40af04e4ed16ae96a2c3c
    md5: 2bc722e2a6aecd70bff1ea58668f0dff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eb5ff3186c9a6fe0f42aa042bd5ac4ca
    md5: c26a90ddbf115fa86f6bebb031f6fc9d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 74061a1ac8ac6b0a86513488d53ea5b9
    md5: 72ec2789b61fbe04596a4929b9780f40
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 78224fba677588dd4abc9b9d0b29d57e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_solo.res
  hashes:
    binhash: 77814b2c8f41ddd340664e8bc475d0d7
    md5: fffe12931429a70b61d81adc54820232
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2994e7e4c49c1a72706a133ae016b638
    md5: e07c94706b3af2206101ec61bb5f9544
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7f499acbf8bb55aa075cd2f08c90f8f6
    md5: 4653729e58c4f7d66b4abd6f5743f88a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_tracer.res
  hashes:
    binhash: 5507612d520c7ef385fa60c6be7f9625
    md5: 482269538fc634e5ab4387e94e8263ee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dab83758231b0eb2a4443f1a74e5e961
    md5: e8ec089a326274ce3621c859d0faf0ea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dbc3de6b43ee5614b9011247d5858ec0
    md5: 1d7e673b44885279cb37cd37ff7a9bfb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 38384cf6505d4f1e23ef64bf8c550e3b
    md5: 25854118ed96c6ec972abdb6bfaa968e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart293/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 04106b63959bd8243cb55bd49febe249
    md5: cf252fa4d6a2ce03f1b267c15513e2ce
