format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/atmosphere/restart_dump.astart
  hashes:
    binhash: 248cf699cd8693952e5de6d1ce0529ac
    md5: a6122fc8b2540e3b96e3ce13838d53ce
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/atmosphere/um.res.yaml
  hashes:
    binhash: d5d694b33ccb031cbbc4b5228b200986
    md5: 231599d53acbb1760481d5483b68b90f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/coupler/a2i.nc
  hashes:
    binhash: 228d61524e3b01453b229bb540636db3
    md5: e8db20d484ba7bf250cda7168a5b648a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/coupler/i2a.nc
  hashes:
    binhash: f2a327f269ed9e36599b7689ebd3c55c
    md5: 2c649189e5532e988a91fcf8e9c1f7c0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/coupler/o2i.nc
  hashes:
    binhash: 5f3a98f7e8739c6ac08279c40ec5bb6d
    md5: 30b9d7817495824695fd4092874e3a99
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ice/cice_in.nml
  hashes:
    binhash: b5fd32307c2990261a2c40d41609dfd5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ice/ice.restart_file
  hashes:
    binhash: 150450e79729ba8b12d92fbc359bc821
    md5: d84a234ecf5bf9b5fa13dd7a5552d690
work/ice/RESTART/iced.0979-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ice/iced.0979-01-01-00000.nc
  hashes:
    binhash: 2d4196ad64ef21a5f0fbd11cf6b0a6a2
    md5: 38903b48f7ef796888392bc388598b2f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ice/mice.nc
  hashes:
    binhash: 23dc023f225f7b75979beb110b07d942
    md5: da5d2d4aab90d4b2dcafe36526b97b40
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_age.res.nc
  hashes:
    binhash: 20ccb5a6e60d60ffff284942e10792f3
    md5: 2c047887bdc4998dbe1e90fcfe2436f1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 54e479b5dd42feffba1618ec6de127fa
    md5: 111a5c0e78d4961c00deba7251a7311d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4f4b75575485e43a867e4fc29554a1f4
    md5: 4930a72269f9bd5f48699b433c87cbcd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_density.res.nc
  hashes:
    binhash: 8361129062fdeaa28638092c74480bc9
    md5: 1fd20a8a7e7e23901f5d3f81c76ce337
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_frazil.res.nc
  hashes:
    binhash: acd498c2b9c5885e95804fc30eedec68
    md5: 9db0186edf404610cee2c6ae7b449850
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1447dab280b1199ac48a69f81d724311
    md5: 050b481cd5b78ad04fda35085c42b268
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4d8ded96295e811c850a6a29ac03b146
    md5: 53fe22f64fba867da9fb172c1569934c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b5ee40ddeba3870aef6930637ccaa9d
    md5: 0e5f556c236b53332d70895878f31b96
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2e8590e854c4d8542e2c02c792744623
    md5: 008819baace074707dd94c3c707b1c9f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 37c605b4c44c5518bd8449635fd1d4d0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_solo.res
  hashes:
    binhash: db37a7e2b3f4c4f6e60f9a91fe7fc53d
    md5: 1e2da6fd47826bc50258aabb7156d0b8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c402f8d69e4fc0bd53c86d3ec5a04d62
    md5: 7ef7bbb07404e13a4800de2ef8b3a44b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bf2b6e2bb1c24322509c372ee67d0d50
    md5: af47b27d02e5c0e6fd8f373e7be70e10
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_tracer.res
  hashes:
    binhash: 02703aaa71df9865d955d95870aad348
    md5: d3f6a4aeef72f0d7c11ab7232c9c717c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d159e4fd355c6c3456cb2d68e4a2dea4
    md5: ff728676166d1c1798a543f548cb5749
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 212ac7920cb9194bbd544a5f467b1395
    md5: bbf98cb8955914da0fc598dbda46859f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 63eb4a882e90750ca249d8ad90997767
    md5: f8c95c39f8afe7500b54e015d0123b6d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart425/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b35556edf8ac786f44db05a4a8dc5599
    md5: 0932174d1199a5d79748eebb2ccdaf7c
