format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/atmosphere/restart_dump.astart
  hashes:
    binhash: 1a74375c5bfc34e2836fdd614c96c5c7
    md5: 65951db9fca9c2282a16a65cf9b6617b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/atmosphere/um.res.yaml
  hashes:
    binhash: dfa6be34f7a49edc56614e8e38ca75c9
    md5: 3435cca7d9a3b823537eb3dd48a3b438
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/coupler/a2i.nc
  hashes:
    binhash: 76799cefd2edb0c1bcfb21126e6fecd5
    md5: b956272fc0a953f1a24d53ba3ac1fde4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/coupler/i2a.nc
  hashes:
    binhash: 29e53a43d9006ee3b901ea52baa04190
    md5: 32a2a303d100c44e03ba1473b336ac6f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/coupler/o2i.nc
  hashes:
    binhash: 954a7b4f46811d0d217b7e60e5cf449f
    md5: 06e564d6f7413fdad9ce566c54781af5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ice/cice_in.nml
  hashes:
    binhash: 5f36c701f2f640e33bac2853947c2fb0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ice/ice.restart_file
  hashes:
    binhash: 32a6194f75bd041a1935dc7a33836785
    md5: 2c230636e8ecd747d3791b554c29558f
work/ice/RESTART/iced.1857-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ice/iced.1857-01-01-00000.nc
  hashes:
    binhash: b3c5dce0f360ad3b72643b36203769c5
    md5: 7eebf5d4760ca6fd86c86b6b1d7577be
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ice/mice.nc
  hashes:
    binhash: 4283c47523a20818a2b5e3547deeb607
    md5: 7fd70d3086a1addfa130e85fbd2ae92a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_age.res.nc
  hashes:
    binhash: 87a5d0175c6d079a1973a91111f4c225
    md5: 64a69083c623ecfe1468102adf989868
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 382649fa2a0ba8cca85334c07fc1284c
    md5: 3d552739609f78e2c4b6c553fb81aa60
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 77d44da3f41cfc5164b16e90dbf3eac4
    md5: 21436f77f87ce4cfb235ebc85d2477e2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_density.res.nc
  hashes:
    binhash: 6f8eb1c026fb62267a11e38732848a2a
    md5: 443f36c238904305495cde01113d0f80
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8c5135debf9b699851cc1684afd77d1b
    md5: 56b44df27b8d30569f9a6497e17c6e3a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9f7f965b2fe8fc3d8da1aa6d8f088600
    md5: 3cdd81b78d59a25ba710b3e647a0a7b1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7fc963352989607bbafb073f4549e747
    md5: 560d2aab59938534e7467b3feceaf951
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ed42e05e5cd76893ccc58b8a420833c7
    md5: 5c0e47e31b3055711619bdf971e31dc4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e3e9992ff98dc93f1729e5736b8ebf11
    md5: 13aeaef26f4128d0df83bc84e44338e3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b2f52d606a6e1b3e82fb513b7fecbc59
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_solo.res
  hashes:
    binhash: 1698b3dccfd2a22162d8b85fc96780d5
    md5: 89d9b014677a79be3c97e695bc9dd2c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b85033ce8bf73e12ffa9e4c86b5ba782
    md5: e8f924c1c0bfcb056aad7228f51e2b72
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 446623cde26828113482dec6057ee433
    md5: 06ad8c685cfb96ca86390a8ae9e4644a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_tracer.res
  hashes:
    binhash: c09b7cf7af6ed9501a42c7d02937fd97
    md5: 46baa7e4715cc97fb840f2f6b8d7fc72
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 516eebac0eec1ebdc83afd08f0e6fa71
    md5: 6186db6e4ad03a2f23d0b6969cef8c62
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f8cace81187fbff73ae610c6e22a423e
    md5: fba84636149174ec88bd24352a317871
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0a37a475e7fa8f13ce602611aece5e43
    md5: ddeb9f34c1c725d1a4da8fadba0afe5c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart412/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 28f135467abca3847f38890591088f17
    md5: 1d7f552498c7855d143968ab04127d02
