format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/atmosphere/restart_dump.astart
  hashes:
    binhash: 5c47e8d93badac89c081b121410e0919
    md5: d2a9cff6b8048fa67589de8dcf048a48
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/atmosphere/um.res.yaml
  hashes:
    binhash: e44e92414b6b10c073d2a45f9786e1b1
    md5: 52b8452de108f0cde653f8316652ef1e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/coupler/a2i.nc
  hashes:
    binhash: ae8d11bd7d04e742adc7dc900c051453
    md5: ee59b44034921638ec012077121d96c3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/coupler/i2a.nc
  hashes:
    binhash: 3447b57f85da4ccd707912be94e892b5
    md5: 2a4d85fd900f26b697da32dcca87f477
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/coupler/o2i.nc
  hashes:
    binhash: bfc3a91e113d3487404c840441c9a9c1
    md5: f2579379f7c9c96f2fba66670935b4ff
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ice/cice_in.nml
  hashes:
    binhash: e73adcd3fb7243b6e2b320d2b94bc10c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ice/ice.restart_file
  hashes:
    binhash: c8fdc68569ae3a61bea7090203db39f8
    md5: 71dfd7ab0fafa283db76120c762c5abd
work/ice/RESTART/iced.0969-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ice/iced.0969-01-01-00000.nc
  hashes:
    binhash: 5088291af691c7fca6eab476dc62c61a
    md5: 97467775713366173900bbb8543719a8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ice/mice.nc
  hashes:
    binhash: 05f3deeb7fb67f1452c1788a45faf9e9
    md5: 9d1c47efd6da85661542bfb0cb0100c8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_age.res.nc
  hashes:
    binhash: a574c160e25babebadb592f27f10bcb4
    md5: bc82b08340fd4a6b9023443e0c1e711c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 356c28a52c39a8ddd88e2cafba9dc2aa
    md5: 4fcb7ad2a5e597dee0b8a0deeb184647
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3ed0c58277f0a79599e858abf8f3a9cd
    md5: da8913deddf72911bba42b27550e9b3b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_density.res.nc
  hashes:
    binhash: 4fd69cce35f688b5040d76be01863944
    md5: fe4ec9d966578f4932f72db978039ddf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 12dec85fd219ada6ff87b1392e1e2f46
    md5: 6df08867a6c3ea5943099bf4ddc4d484
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 144076fafd65e6b72913a3e668398a65
    md5: 59d750d65ae145d73b6aaa9057d77fd2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6708c36fb679b7b722ff420a5fa7d186
    md5: 48644dc2336cfbf430014b51510c0b4f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b957be8ebeaefb6ff5c2eb9135a0ac30
    md5: 03d0212beef08257eb8e9c064f9174e1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bf6439d4e3e218f43826371cec1a59bf
    md5: 1cc71be4e58f0db89a655afc3ee6aff7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 710c1e04c9e4d9177a382f295fdeb301
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_solo.res
  hashes:
    binhash: f219ced0a8d763e26c0fdcad53f19a08
    md5: a9bf398f1c427cbc4bc150bd99e4f49a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ec7b38cc555bae6a8d667e19fac70e06
    md5: 17727f41ab369d5dda66c9bb6010a042
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a019214117296c5ac7d967d52d131b35
    md5: 24c47f430aa16c9c8c2f960b6e9098e5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_tracer.res
  hashes:
    binhash: 815875155ae312933cd077a3c03c3387
    md5: 9ca0bb061846557d2d7ff9a236861bac
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4fc1d68567be4c6ee4a61f101725cb1f
    md5: 88838445efd7daaeed0b0399dcd4c0bf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e86ea8e82167cb27522a40e50e20acc2
    md5: 0839ffba3de3f043e0cc83ef6ff403c6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 441c40e4a0562f2b59eef43f2bba9f17
    md5: f0757fa1ebb302863ef2ce1597d011b1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart415/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2dab415992005b2f637f9de331372dbc
    md5: 3f96ddf205f35c63ea7fa560f2001670
