format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/atmosphere/restart_dump.astart
  hashes:
    binhash: 63e0353a023d4beb8a8d78285ee76f4e
    md5: ec81a450a453f04c009ddb9f59aa559d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/atmosphere/um.res.yaml
  hashes:
    binhash: 79642936a0316d6b2daae33699c2ac5b
    md5: 2915ca2bfde103585035703eedfc20f9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/coupler/a2i.nc
  hashes:
    binhash: 5d92f42092b5e89ae5f2d9292ed09128
    md5: 66d100554bc179ef517be58cab915899
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/coupler/i2a.nc
  hashes:
    binhash: 95e7dff7914fa9c40a4be19964fa0362
    md5: bfeab43408bd85876132fd7cc0f64299
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/coupler/o2i.nc
  hashes:
    binhash: 5d95212fbd927fead016ef0b245ebcd2
    md5: 69ab8d65972ab5e5c72ec1f10d836382
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ice/cice_in.nml
  hashes:
    binhash: 22b55d7d5f30b0279b1ca7f1c45e8cd6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ice/ice.restart_file
  hashes:
    binhash: 7f6405a1b6e8d602a927dbf2242c994d
    md5: a947f5774a6854ffbd3454c8cc8c00bf
work/ice/RESTART/iced.1763-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ice/iced.1763-01-01-00000.nc
  hashes:
    binhash: 26ff8d59401935e877bd890593f8e27f
    md5: c03a4136060b0481c26674f188139b2a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ice/mice.nc
  hashes:
    binhash: 68898e4c9f316e6aa83d4f35dcae617e
    md5: 6e06c430cf0453c149bb109bf6ab31ad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_age.res.nc
  hashes:
    binhash: 5410b077852ee0a1439d73cba34aa527
    md5: 74192b36c32e7910b1c9b29cef1eb42a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e37c308cafac52224dacfeba8994066d
    md5: af82a018fa72ce605977a4b33094ce49
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d24aa8c946a7bd5d30e39b42550d0768
    md5: 6c1884a9c6b83d7289e4bf42de366fcf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_density.res.nc
  hashes:
    binhash: 6a4cade4972496d5238093fc44470be5
    md5: 8dd62f0c6a3f510f8eabe4306b90cfd6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 70c65c2cd7c2724401c7c8050a352089
    md5: 9642e903ec62915d7b7e46b2cb47af43
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b5ec28910a47debabcf1a2154b2d0f18
    md5: 795c3e2d364b5473b3706ef51426ab95
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 071339d5c5ef97f3ffeb7b7262768051
    md5: ee684285b053b0e1628aa29e6b7c6dfa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f3849bf3f89cf26cfa18828920ce45c6
    md5: e4ba85cdc50bd2fe42650554a88a6e4c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 26947183e04c84a75c87d79c0cf4ede7
    md5: 5a3ef423213fbce09c57883b69ebd6f4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 67a0fb7f4d9b8ccd5547f84ee9ab56a7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_solo.res
  hashes:
    binhash: ce300be8f4dcc861f511274ba6db6ce6
    md5: 2acf460207decacdfa1ef0e6f117a6c5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ce3af998d9ae23882ca8be6c0fbff165
    md5: b1a12cb8355b361db7f8f7cd1f56f18b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 535aebfe860d193e6a15332a68147f97
    md5: c49875e294d0a59ddc56dfb74a802e82
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_tracer.res
  hashes:
    binhash: 420a60f63a9b18fb778d39eace8c42f6
    md5: 9ac8dafa5e20187384e1767c21eaceb5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 055faa19de8b4561c4ccb07c1a3aaf9b
    md5: efc5b75d7682a66fb1b156b42178a993
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9bb148653a2fa604370b434f7b8546f4
    md5: ed0364841908fcbffbec7a3ede6e18c1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2c76d8fb4b2012b2b6e4700b161e719d
    md5: 2eee201a4d6b3d4ce0ae31fd7ce3ce75
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart318/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9c1e333f5849e10fb9d9dfcc4bfe0ce1
    md5: 5b9d7c1fa9731d90e983e925711a7b82
