format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/atmosphere/restart_dump.astart
  hashes:
    binhash: 3137a9a10a0c88907f00305c7788b412
    md5: bcea6cb5318539ab4635f208cef9655d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/atmosphere/um.res.yaml
  hashes:
    binhash: dee16aa407aadb7507b09df29d428fdd
    md5: 585e543aa065d4a17e3e80156ebc9cd2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/coupler/a2i.nc
  hashes:
    binhash: 74f6c2691762cb4c2c7dde9ba847fe3f
    md5: ff412412435f0c6e27b9caaa9590365b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/coupler/i2a.nc
  hashes:
    binhash: f69ab5b2780f5c227d66b98e75064eda
    md5: 0b9921b0f375a89d03665400731d9152
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/coupler/o2i.nc
  hashes:
    binhash: 069174b2dd17b7bfe914ae3cdfcd99b5
    md5: d30dd093c6a34a469dc130ea1b2e5845
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ice/cice_in.nml
  hashes:
    binhash: a96e4a8cc33f81eb018a1a0bc1a90472
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ice/ice.restart_file
  hashes:
    binhash: 249e44c8517d8efedcbee7cbbe227e36
    md5: c0d3d9a85368d8385fa21643a3eddefd
work/ice/RESTART/iced.0971-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ice/iced.0971-01-01-00000.nc
  hashes:
    binhash: 5880bcff90f77b340885bae425b606f1
    md5: 25e126a0bf6f64f6ff46d353d44638d4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ice/mice.nc
  hashes:
    binhash: 674405d7999095fa57b82cc8efde6ed2
    md5: bd68d313bcee94a50d44301534c5e06c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_age.res.nc
  hashes:
    binhash: ce9be6151c9a95b88215af10ad06e12e
    md5: b14d65ee4d5982329bba46e7187f1dd1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1af9e4236b4e2e8e86627e71638b552a
    md5: 765a323328976b40c66d2ff53b3e77b1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 142e5226aac34d96361a67ee6e17204f
    md5: 927f0e698b8a77a8039e5e12b3031377
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_density.res.nc
  hashes:
    binhash: 7dc96a0a82c57744cb4e93b8f5a8b609
    md5: 244a8f48f1beca7ce76bd4127bcaf4e4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 746a13403a503e07708bccc9e4dbe1ef
    md5: a7a56a93b54dcd97a25f01f2130a2690
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8ea06d9f7e36ee47ecf837d98ffe16e0
    md5: 5027f278372193a8843735a4d70ba73b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1ecce17e76fdbc7ce82e694c1c097331
    md5: b326597afd5c44696ae89748d5dad965
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 93d4f677693f90683fba1c4b6da61e80
    md5: c314e5241b8d009ab2188bde1685120b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 64fea6b6793a28f8b5e798f2fcdb195d
    md5: 53d93e8b7b24300badd421efbeeb9564
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ba38bf525c4c802626955bf0b1306f67
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_solo.res
  hashes:
    binhash: 536a2cf318cd3d115d999bca93ace8c7
    md5: ee53daf68e3eb2d49b99db82745174ca
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb867f223064be81c5e5ea2a2b180ccb
    md5: bfeaa848d757bebc8b0e4980000119df
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a736c0ef320c7a6aec2442f40c787e26
    md5: dccc08c147edf8a005f2b5212c56650a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_tracer.res
  hashes:
    binhash: c0ed031d92aa54d25de2ac2110b9645d
    md5: 426c61105f8074ebcdd802fe704a1574
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5fa0250691f227f5bf20e7700741b68e
    md5: f17bef86258f83ed0bed39a92adb24ba
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1ac36bc31b20e5f3a4ea1982300b4ecb
    md5: 127897f74b42c4197b157a8fe14c0728
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bc943b46443b2bcf9afed57faca4ca1c
    md5: 6b140a2aa52214a43042649813d9da2c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart417/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 491c68a8481ae4ea0dc0cb270df1c591
    md5: 1e4cfd956e47ae3c75c506c7831966a7
