format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/atmosphere/restart_dump.astart
  hashes:
    binhash: f18efc1327e2ef131ebceaf7ef157b37
    md5: 8ca0348d5426048063f43e73dcf04ca3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/atmosphere/um.res.yaml
  hashes:
    binhash: 4939acbc8b63c5f3c6b72f047a6da876
    md5: 3516fc4dcae1084b11ab2069876f910d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/coupler/a2i.nc
  hashes:
    binhash: ed1a6d15ebc262c841d76e19ae1243b6
    md5: c8b8dc61439b990b6ba15095b5f73e34
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/coupler/i2a.nc
  hashes:
    binhash: 13bad007c155c308325a29847cc494ef
    md5: f0bf9769930c39ab1a5c737c1c9b3ed3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/coupler/o2i.nc
  hashes:
    binhash: 0d9700c6f9524a6c8a22d058c160d0da
    md5: f4169b28bcefc1720f9b6ece35b9c57d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ice/cice_in.nml
  hashes:
    binhash: de2aa6ad14a5b8dbd35d0281255a66e2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ice/ice.restart_file
  hashes:
    binhash: 6acdf8e6b3b5f429237edeec59068bc9
    md5: 5d59ea1cecb25ad25b760b92c94454db
work/ice/RESTART/iced.1255-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ice/iced.1255-01-01-00000.nc
  hashes:
    binhash: 9aa37b222e50d4cd22f3853af124c1c3
    md5: 2760c0d334f17a8ea175f211b0b81819
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ice/mice.nc
  hashes:
    binhash: f0a03e9725a65f210c1a8a1911d8eab8
    md5: c39e275bd64ada523856f1ca9549cfab
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_age.res.nc
  hashes:
    binhash: ecffa965c7044be16f054ca8f31585f7
    md5: 3f3072013556487830f701ec4547d94e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4ae458cb2fc0aba6535c4f1f98451a41
    md5: d770f85ab1215c538c390174f5dd546b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0ae2d46db2ed8df069f55b9a0f39696b
    md5: 814b8e1e4621654a4fd16c344d99b424
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_density.res.nc
  hashes:
    binhash: 4aeffd5ca0ed7eb93913b2acdd430afa
    md5: e80d1ad5db3149ed948e02ece855190d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cb900a72103cd0eca97fa3dd50f16504
    md5: 3f328e275d9c8ebaabde71ec75a730d0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 795f4360a109aa5272b8a6d00734bdff
    md5: 95fc2eeb2132e09e1d8912ef77ca8b60
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 92535b331d026f66ce1e7cac32bdb15e
    md5: 05778158cb4bbbd7f416cb2596054936
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4baf326985cde32c5071014bed120924
    md5: 786c6fe281f268bd4869b7a4ef70867a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_sbc.res.nc
  hashes:
    binhash: db22bb7b570b799c5f7874afb7038b32
    md5: bf376455592e9899477621ca89177651
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c3dd76ecaaef77b16927a0d9beb022e9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_solo.res
  hashes:
    binhash: f2d0f4a7cf1eb275465b093354c14535
    md5: c42bc8b2f504967d9a419d9d5f5c95c0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d0e91b1400c0627f01024dd330fe379d
    md5: 865ad6dbbf2e19169ba4b77115474dab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 79aec3d1f2abf688e05a3d3012936cc6
    md5: 4fbcae7cd17c3b5a954c1929515634ee
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_tracer.res
  hashes:
    binhash: f7bc7a063d58c69e7fa893b9b7504e4d
    md5: 989451cc8917d6c2e49474fd9c675277
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a016bd104f288d25ceb10a46615aba3b
    md5: d2835f22e84706722eb5ca6682ef78f1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a89d78e9d04235c14f1228383cb57b37
    md5: d898945504eb9b86ac2dce059b44f451
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 32b987113ee3e72d415bb1c61deb8fae
    md5: 3f2f5cbb595c1c4b973b459fa15fb0d1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart371/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 14824b976a6f76183888928008ef10d4
    md5: 8a9ce29033956e6f5e320545b5cc73dc
