format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/atmosphere/restart_dump.astart
  hashes:
    binhash: 53ef0893da06319ed4820e603e321b10
    md5: 90b4ff096c216c0ff2d0eac2a7fdfcc1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/atmosphere/um.res.yaml
  hashes:
    binhash: 0d86f5ed6f46fbe9d3952dc349d1f548
    md5: bd84bc832fd66aa4075c8f048c7231c1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/coupler/a2i.nc
  hashes:
    binhash: 97f430170e6eacf2e267a8f59776589f
    md5: 18e9ef0113f96326fa9054c84406fd88
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/coupler/i2a.nc
  hashes:
    binhash: a5779af0b2c94e448ba98d560eab0ded
    md5: 8e17ef02e282938b8b4bd9f1df7b1ad6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/coupler/o2i.nc
  hashes:
    binhash: a03793499faa1b3fd6010bebaff2ac10
    md5: 38060e25b54641f6450c82d05f215e39
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ice/cice_in.nml
  hashes:
    binhash: 67200951ee4cfe08ef224731aba9f6e1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ice/ice.restart_file
  hashes:
    binhash: f5d9f234e038c7cbd98ad5af7fd60098
    md5: 943411903db3c6541eee0ea661f00876
work/ice/RESTART/iced.1261-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ice/iced.1261-01-01-00000.nc
  hashes:
    binhash: da5665abfb8eaed67eed97b3a31ec864
    md5: bd7fe47616fa39c6b4ea5bea3b7d3a10
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ice/mice.nc
  hashes:
    binhash: 5bdbf55a9e20f52abc4c327bd9512589
    md5: a0383c2f728470945a20f8df6bad249a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_age.res.nc
  hashes:
    binhash: 4d4eee0e1fce3572f97ea11e8d8f6306
    md5: 9d97a9742bf9ec025c3e84ded5195427
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 66fe1ceef6e062b102658a90aacbeff6
    md5: df7970252e6dd239219d1ffe9446930a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ed3e658de12412e4495169b7a03d8202
    md5: b3a82c85c50c8359b3dd998abaff38f1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_density.res.nc
  hashes:
    binhash: ee2bfef74eb37415f225e852edbffd4d
    md5: b3fa59d9b741c3e620016e7a70596625
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 62ca99024c43557abff41817c99635ec
    md5: 5b59785f3cd52c1c00c9f80d703aee21
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 35e7b3f01502a790152a4a2ade203301
    md5: 4164fcfe824ce906fb0df3b2370d92d4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e6df6b50de777b1788665e4b94c62b79
    md5: 1920c6b0a86b32f6a9a539b4c821f39c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f619fc0dadff723e5de3804b19e696ad
    md5: 06bc3cbb7468cd96a6cfaa4c0af56352
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5206f851a76613eccfbdeb112df917db
    md5: 97d3dbcaffef9b96abef1b6df1f38bbc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 93c5be39be0d5a8b371843968d052576
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_solo.res
  hashes:
    binhash: 44cdb82b17befe0c086723e1e9783120
    md5: 6c350663fe2b78194bac45098086ff04
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 042e2b846bc1ce258ba01021c722973c
    md5: 6772c3ddd9719d437c9716f024a52324
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8ad3f15038d62f651d2a1b5b6289db5f
    md5: 041e8491cec0bdd00d1b8363598ba9e7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_tracer.res
  hashes:
    binhash: 062e0be5b94eed9bbb6e63521fe206f7
    md5: d039d4107e9e8409a95a74fb417b766a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 97b179c1760fa0d9614afd45f3c97027
    md5: e89bed70ab93b5a18ce1b4988c2b842b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5fd12c56af4e820c7fc9871f83705ee6
    md5: b6aee9e8fea44dd611dd0136f63fc02a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a4aef2c37f2046207e6beb15f79c5b03
    md5: 904f4280b65bdda6070280b42e356f61
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart377/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8af234faf817784d753e4d8c18188d2b
    md5: 8440c2c7125e916fc7bb7f52847c17ed
