format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/atmosphere/restart_dump.astart
  hashes:
    binhash: 71b91c73dd6bc98622f62485c6c2b6b9
    md5: 40fa23b0b36a50139289329cc90c9f96
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/atmosphere/um.res.yaml
  hashes:
    binhash: ac50fe2382591c5707d973964c1aea43
    md5: db29f5de13c63c04f024d3149393f885
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/coupler/a2i.nc
  hashes:
    binhash: d5ee8dbc30c1f7359d97cd92342b689a
    md5: 2b57623c0298f7a2d264771312bc968d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/coupler/i2a.nc
  hashes:
    binhash: df23b0294e2d22335e994546557af82f
    md5: 4b1b9b8609a64f9ca2680ad201ee78ce
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/coupler/o2i.nc
  hashes:
    binhash: 6ba60fc415334bb42e320877cf2ae7e8
    md5: 17cc73767ecd9e136dd18b0ee0168580
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ice/cice_in.nml
  hashes:
    binhash: ba4f48fb8f628f3098567802fafd20c0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ice/ice.restart_file
  hashes:
    binhash: d68a6a6f8fb3c32a12a9748f0a1abac9
    md5: cc583686cc7c4068189d6d28bbf68111
work/ice/RESTART/iced.0944-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ice/iced.0944-01-01-00000.nc
  hashes:
    binhash: e853b69b5dc516c581cc176aaa53508d
    md5: 13b6fa1eed812ef6bcb3097eeae9170f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ice/mice.nc
  hashes:
    binhash: 44684632d8dd50a68d300f021c7475f9
    md5: b82b8d3e25cfd3113adbce1a3bb60247
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_age.res.nc
  hashes:
    binhash: c9be4bb4c556aa3c91559c4961225000
    md5: 15dfc770cfaf6658520f78f9a202c459
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f1c6b6f4740bf295958bbec22790c283
    md5: faee7b40ac6b252f1612f5ef4959289b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9f442820a4eccbea4d7a6985b0e7b371
    md5: 057b3f465ed69efaff5305dadda7d56d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_density.res.nc
  hashes:
    binhash: 137ed20574bc02d39615b2b251ac3902
    md5: 1b0e3c97bdf295018bceac5d03b0a012
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fea40917cf634c58886cac894e8bfc58
    md5: c18c035407d0cfa79219698daf128fd5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 90c6ab118170f9eb8ca1ef65e591dd2e
    md5: e3d25b4ee368db149b90007fe38f4d16
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b00adf96b3cbe934c15734aa0f8726c1
    md5: 186f78ae7b6057462e4b8facaeee9235
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6965acdf8d17e7dc1de1b9da9477e248
    md5: 0af0209b34816e5b6fe8cee2ecdb4aae
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 692151ec104005b1c93222f1a295b944
    md5: bbfb68dbc5453d39a7a05193366c4ea7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9367ef15e414e9f4e37941962dd727ae
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_solo.res
  hashes:
    binhash: 7d8daf3ada0c2b1c2ba2f80be3d498b8
    md5: 11e1ae0921aab119d6b952c8f038e85f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a75e7643d265a1c199554f1bd0590cd4
    md5: f9804d1d16b348d12114b85a2ea1dbc0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2f1796227d0c510e20ec80718dfeacc8
    md5: 8e573a781b1b74157e25deaeb4493d26
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_tracer.res
  hashes:
    binhash: f964d56a7b2445dcc0f32e592509228b
    md5: a8a04f65b76bcc69856a9f2523079f17
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 952f724309bd7708ff56aef3105dec04
    md5: 5c01b44f17831dfee0e37c76a9b54989
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 806968552b7242e06de16afa98d6f2d7
    md5: cbba9639207af047b1965411218040b0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: aef0faa1420482cf5439ec5dbd1adf0e
    md5: 5677e4390051c90909b8de3632be3bfa
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart390/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ce8faf103d19395c29e144cce9ca5d76
    md5: 555a7e082e5312c4deee6467bb63a938
