format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/atmosphere/restart_dump.astart
  hashes:
    binhash: ebf59983d950bf790b7f3de73bbbe4f1
    md5: 0ade9dce6bc912c34add7ff846bc9d61
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/atmosphere/um.res.yaml
  hashes:
    binhash: 8eefd796a20fcfb16993accaaaeb1c73
    md5: fd3184093454fd768bfbdb750da1ba02
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/coupler/a2i.nc
  hashes:
    binhash: 2baef248332820768636827483ee638e
    md5: 0fdeea20a7452310745d6da8c70f55a2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/coupler/i2a.nc
  hashes:
    binhash: a90369147485bc1eb7398ae0e13cf768
    md5: 469d3b73678e0cea56909fd18034ee7f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/coupler/o2i.nc
  hashes:
    binhash: 36726f1bc7840958529780b66c52d4cb
    md5: e4fff0fe053ad948d15fd7025c66d668
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ice/cice_in.nml
  hashes:
    binhash: fcabf08cc8ac0be2efc78196279a4b8d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ice/ice.restart_file
  hashes:
    binhash: a97a4d117fedb9505c4ff6854eff037e
    md5: d074c627cf9ad790aa3ce9ba54989b7c
work/ice/RESTART/iced.1746-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ice/iced.1746-01-01-00000.nc
  hashes:
    binhash: 2c6f95b97a2bd67c4de4c25cae5c66e2
    md5: fce0345c12dd08cf847e716219b5b118
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ice/mice.nc
  hashes:
    binhash: 68b45a19e414d31ba944cdafd6f9c686
    md5: 28e9c73310065e9f35410cc0dfb03871
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_age.res.nc
  hashes:
    binhash: 428487d1ce2b255f01e561ea8a9ba9ab
    md5: 63a3c37b0ad44a384b6d933438b9a526
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 77aaaffd00403c395c8e32fafc21274a
    md5: 5afdc929f10730672bb2f37b20cdcfe9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f7c74a9bf947176fa8068eedcdb6aaa7
    md5: 34dbc85b89d157448ceb0a3aa5f26388
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_density.res.nc
  hashes:
    binhash: 543d90b49f5867ab73450e4e62cf0bda
    md5: ff89dd9dc0c11854577726456544c17d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 78de1e2a1505727e9ef3c6afe3fe3fdf
    md5: 160b7ed266c3584a1221f82c8d12164e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 57be3a814c4afa5f1993ec7d08a72744
    md5: 3d8f1a67289ad72465d342eb7bc1c449
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aebdc975da0f0888c74a001858726567
    md5: 0c21a60cf7486fea391719520863f261
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e351fcb4bab36accbd9d3b227f057d65
    md5: 576899dd167b1b464e30e842ac4b5ab6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 075002193333f9e1b432dc154d8296b4
    md5: b250d418a45f33ccc8198d4f79b05efa
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b2d9900c593f66139a47a112f4648f03
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_solo.res
  hashes:
    binhash: 8a6d88667707964c1099b332f9c3ff58
    md5: 7838cf09919ea6c39db6e2b20afc59ff
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 65a94f6c150f7e8f72bec1cd8633ad7b
    md5: cce04c0128a54fbc536abe14df2d8fde
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dcb8a8b2d1257abc8b1250bdfce9a85a
    md5: 86b371d8fdb4a788945d2b64ce7d6a09
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_tracer.res
  hashes:
    binhash: 7d82b30a8ff77f2d7a6512302623f553
    md5: 7d5decee2c15a0956739c71949d5d7c3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2648618b938a01064fe8b5f66b04f170
    md5: a5eb9d7829e4c137ac0685582bdf828b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ce3682b0409c466e6d31ae0a7df76a65
    md5: a7d67a07cbb04514326833561170364a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4d984772807240d3b0912b4f45c5c93c
    md5: 4c38de194af79c6f4b321abb69e1a1c9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart301/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a0db86be5eb510dd5b60e69214b7b89a
    md5: 31dfed247f9a997ada9902d0014caa5a
