format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/atmosphere/restart_dump.astart
  hashes:
    binhash: 01eb28f36bd253cda93e88c05867bda0
    md5: 04c942bb8864dedd4033c29229dec08b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/atmosphere/um.res.yaml
  hashes:
    binhash: ffe208257689e2b013a8fca29b485011
    md5: a6fa2e981563e91a26b9b674e622b3af
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/coupler/a2i.nc
  hashes:
    binhash: 8078ca8eb6174f5e25e2c7e17871f95f
    md5: 9711bb9af51e0d15749a2c5e33eee0e9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/coupler/i2a.nc
  hashes:
    binhash: e53eba9529a3222b45f1b6f63ac26b6b
    md5: 0402eca93bf17146396d91207039d2fc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/coupler/o2i.nc
  hashes:
    binhash: 6cf6dd1c7792fc30eac89fb6b286d415
    md5: 1b7fa49bae3a768387f84034d9beddd2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ice/cice_in.nml
  hashes:
    binhash: 1a0c6c6d1a9d4446408d8a996d774a23
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ice/ice.restart_file
  hashes:
    binhash: 81dfd4e7287f02175f582105331e3a32
    md5: a308debd5ee8315dfeb742a157abf17a
work/ice/RESTART/iced.1260-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ice/iced.1260-01-01-00000.nc
  hashes:
    binhash: ef27027c9e8db17b58192b2cea279c73
    md5: 04823a3b82e8006d5fd32bf15af9eacd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ice/mice.nc
  hashes:
    binhash: 47f8c66d68ae622136a090b9884d4ea7
    md5: f58a73ab304a4bea5ae515d16e4aa84a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_age.res.nc
  hashes:
    binhash: bb028df9edc114181e8d1f91fa9535c5
    md5: ec8c94f9d66f49253436f89e5bf33aa3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 04419d8cf196db8a5e4a7804a59dbadb
    md5: e2240d2422008f7cda67153b256ca26f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9fe4cddb3ba6cc180a9ce8b23a76b479
    md5: c95530ed5dcd15e999587a235e02dbc0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_density.res.nc
  hashes:
    binhash: 25edbc597aa5a6c2d7bade5c2f6091b2
    md5: 5e5344c322369302296a55d17f824dbf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3b6e62ff12c10e8a608ebfb7b9074415
    md5: 0580f914ec39526ca15b3268ccd3d037
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5ceafac08110ec104136d4d92d30063c
    md5: 181513848abd9ee03df527bf705f74d2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cd6cb020368ab6f1b5a5de283425c4a2
    md5: f8ef2d8222dbdee4c5bea30d2d621d0b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0bde580c7f6fd176707f27fec9375e36
    md5: 0f7f5d4ef7568dcc6720d4781c8d0b53
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1de159977a56ea5e23392a20f69ec157
    md5: 866df306b031f08d0c88636df9a2b3ce
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dbedbb64b6b26b69773b19e84ba81733
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_solo.res
  hashes:
    binhash: 1afa6ac96448524559a9b0a642614bbc
    md5: 0335faca21c6233c9256b2e347658095
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7c12bf2ade2ed85997975d350a471f86
    md5: 42f40bafa7a6fb212e0f82a47e01c9ea
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8a441fab9436847fc15276f85d8958eb
    md5: fa56e4acf36ee1306f7774aca7909129
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_tracer.res
  hashes:
    binhash: e3d15dd10e3ddd2c0fe45e56095d4bbe
    md5: fcda5dafc5af88fb082ee0a6eec2cc78
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7fefe302a4727402eb4a22c2f331ce4b
    md5: 1c26217f5370e88dee51ade49c1f7e10
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e9acc956812aaf577b1f3db00a786c17
    md5: ae66ffda14dbd98713d5d96ca9cb2e7c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 487a41b1b60d70b6ccba604b31f222ad
    md5: 9d50bd3b4d91b4fb4622083b34048052
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart376/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 434567404957454a201972f4aec8aa0f
    md5: 8416657a4f57fb3f1789adbaa170a76a
