format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/atmosphere/restart_dump.astart
  hashes:
    binhash: 3a55c0b42792ad2ebdca4df6fbd341a1
    md5: e70942744fbce8bc97db5096703412cf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/atmosphere/um.res.yaml
  hashes:
    binhash: 8ca045fd0cf51aaa16c43e47b30bfbdd
    md5: f5d5f835ee10504691f31641accc187c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/coupler/a2i.nc
  hashes:
    binhash: 0e9ff517d65558a077ae19a1f198bbb1
    md5: e410ca49509c376dcd7270ee7031da80
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/coupler/i2a.nc
  hashes:
    binhash: 64d9c475b6d6989f1ad14f3c9ba25a8c
    md5: 3783c0f5a5379407cb035ce7968e22dd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/coupler/o2i.nc
  hashes:
    binhash: c35f55903d10aaaf36f7199e2964a671
    md5: e8c53f9bd15fee70a58957dc069d0dbf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ice/cice_in.nml
  hashes:
    binhash: 6006e614e967cee7c3cb207251c0f202
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ice/ice.restart_file
  hashes:
    binhash: 5ef63d9fd5ab81edd86e483f53ae7a55
    md5: c3ee66c2a8206a0cecf2b54e3f93fef4
work/ice/RESTART/iced.1286-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ice/iced.1286-01-01-00000.nc
  hashes:
    binhash: 18f32691db9c7239efd22a847777d870
    md5: 94618ca0a2b784d29b7c699716529d48
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ice/mice.nc
  hashes:
    binhash: e081b2854aeb37558aade4fcf8c2f2fe
    md5: 05aeadb2012ae99e8ebde44db35922ca
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_age.res.nc
  hashes:
    binhash: 67dfb76e9a5ec714d0b63d36cca8d25d
    md5: 9512ef6120a7dc74024c1346f1e49195
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b83eb31375d64d1fc60312cadaabd210
    md5: 80814d9e375b00a5d4a0009b7b32b8f2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 203420f238769948693efe7ef4506605
    md5: 600b776701c66e33db9a35200bff6244
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_density.res.nc
  hashes:
    binhash: 0db72cda0d15ca28494ea6a458c4ce01
    md5: 54c61a306d6254119582536e1dac2d72
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 759f36389023611f986db47df3e4a105
    md5: ac33442b6870a261ac9ef789837d4284
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1c992efdb5f27d5be6beaf6a7f5f8aab
    md5: 77a4105e2f3e1ec67537b3fa74a53105
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e349571f3b2fd8dd246ed817f6ac57a3
    md5: 58e3e1b62f4668c13d757e57e63ff8bf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5cfe2d3a162d631b7a7d8668ae78abf6
    md5: cd13b5fd766228a8bb35f44be433b1b3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 44042df2bab6cd72ec157b4a85e42b18
    md5: a7d4ad8ae80709f44edf187c0bdcdc41
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d60426fb158f405cee3ec25e73e678b6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_solo.res
  hashes:
    binhash: a08f9c09470ad32bc0fef4f67e80b8a2
    md5: 10857ddd02c12584be80f099e6e4a729
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 91b4580fb8830b25d7bea754e3778d6d
    md5: c28cd58fb04f70cfc9b776656ec4deb0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ef3af9874405f862f2705583f28ba106
    md5: abcabec36319d6b2e09d443110eca46d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_tracer.res
  hashes:
    binhash: 81307959348463c5d8cced92a8121b65
    md5: 32f771fa92892648e87cdeec8cc5b72c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 244cec0f62a5ab4c22b233229fffe78d
    md5: 1647e71d519a621b5b27f1d78dbf1368
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a9e958404ab3f491e1e69adda603e22b
    md5: ab1eb09529547e676b700a170433f25c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dc269a192d245a065bf3e94fd2b19c6a
    md5: 54bd00468e0555f4518ae4685e424f16
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart402/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ca84de67788ccd70f394ef45ef708936
    md5: 73095a9c3dd01a77a21da4b6783a02b9
