format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/atmosphere/restart_dump.astart
  hashes:
    binhash: 6b7264adf09ba542239d72a085405d57
    md5: 24d40b696a4bf6e76d2dfd1df177722e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/atmosphere/um.res.yaml
  hashes:
    binhash: 00f88bf2fcba1306589ecb5927a9bcda
    md5: 07e4d1475be31606c35c762fd79bbf0c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/coupler/a2i.nc
  hashes:
    binhash: 3526a04c7aa319a8a3c85a98dd1db28e
    md5: 3d7628bcc4a822b72f20afa096b11f72
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/coupler/i2a.nc
  hashes:
    binhash: 6e46299a4d941516ee4a9308e484bb6d
    md5: f992befcc87b5833a3bca16fa7a652a0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/coupler/o2i.nc
  hashes:
    binhash: ac6de65ec0fbd3894a5eec2475544e9b
    md5: 62b3aaa547b28fc97fb75bd68dff12c5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ice/cice_in.nml
  hashes:
    binhash: 7085912a7dfcc4f5293cfc476ef20cf9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ice/ice.restart_file
  hashes:
    binhash: 290f4735d5959bbab038c37215c5eac7
    md5: 13118b272721ee3f13e1b3fe67f4b243
work/ice/RESTART/iced.0899-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ice/iced.0899-01-01-00000.nc
  hashes:
    binhash: bfd18204042364b41100784670ef669b
    md5: d7f98e9ebff05bc7ee22a38db7aefafd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ice/mice.nc
  hashes:
    binhash: 0d50ede1658cb6d69c5a559184376fc1
    md5: 36670011dd478dd223d59536dbe69d53
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_age.res.nc
  hashes:
    binhash: f8c780e50146cbad2842f84cde44d022
    md5: 41293cb8f7c9da025501f37eb73e465c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 367bedcf6b016b8e3d2123ddb2f14cf7
    md5: 4cc550a0f12ea51ba0b43b6831a70e4d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 972179b007da76c575fbc52da1cfee20
    md5: cde0cf0e3120abed06aff1cd169fe7f3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_density.res.nc
  hashes:
    binhash: 0add856d5d5642a9bdcf820b8c55b7c2
    md5: 3a20ed78547d08e3047b02dd74064da8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4e50e38825f7389ac55d2624795b54c9
    md5: e06ee1b55bc7fd75a4c3847e4046a690
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6e04a26a3998eb5137fe6c32a0d1ea38
    md5: 54deeadc14f3aa210aaacd88fc2ba516
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b329381de35702977290c55be9cca4f5
    md5: 6759c508ade2bc3a042605b6f1cd9fb6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e08c668f56fc19ffc8e19f86fc56784
    md5: 5117efc3dd67d7cb583013f1496735db
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3a2501765240acc5c825bbf8ad744fd8
    md5: c9aec0455e69f246cdaa40f9a9776a99
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dcaac5983ade2ac56738a6127ed447ae
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_solo.res
  hashes:
    binhash: 429ba9068fd1c878850fc15695a93a73
    md5: 1dab182c82c74334b31aa4f1d65989fd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: eef52b610834b325a1cf51d55294fbe3
    md5: fb4503b9e20c9ad27dbb6c0d2c993064
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e0164af1d4b30796807ada77997d52f7
    md5: 6f2127358e7f53adb9e2a865637bf231
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_tracer.res
  hashes:
    binhash: 6b74b6031d4649edf4f626c2b2f12bfb
    md5: c7cd5c84ac5976b7a1092698f4861fb7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 496e30c1a72f52fa33f2bf9de7a15755
    md5: 6d6312f91e43eecd7a4e65eb60935acc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 748776ab9de6f35ecf860ef2889c9605
    md5: f64d9a212550bb8aab8c81695cbefc38
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b07428b4f0bf117a5905611a64d2c465
    md5: d9a8dccb357f78786e141e7935a511be
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart345/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: afecfd9d3b51a48b19e25cbd9e083d34
    md5: 929bf37bd9007a76aa526ac0cf96899b
