format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/atmosphere/restart_dump.astart
  hashes:
    binhash: e422d207c38a7c2090311f117dd4d928
    md5: 2467552858c4ecd7e50801499d06da4c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/atmosphere/um.res.yaml
  hashes:
    binhash: 98ed59904f92f96a5e7dcbce1542961c
    md5: 2ed0272a9d9dac99997dd7a756fecf62
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/coupler/a2i.nc
  hashes:
    binhash: 86052081125919981a7ad86acca73d38
    md5: 7cb0635e05f1b41d162cca0a86d764b5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/coupler/i2a.nc
  hashes:
    binhash: 44ac7d74bc9a4dfcc687849a659e77b9
    md5: 1a174bcb4f8ce8c2b99ea38a2d35c49f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/coupler/o2i.nc
  hashes:
    binhash: 7939cef3886e55c9ef9d122161853915
    md5: c6ac2efac899376b420763f4b9f5a462
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ice/cice_in.nml
  hashes:
    binhash: 182dc6cd803eb6c8403fcb7a83abae7e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ice/ice.restart_file
  hashes:
    binhash: 7c64803af1a26390c3824291894ea28c
    md5: 366c843be8aa25c8e0328eb6ed2c6f00
work/ice/RESTART/iced.1190-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ice/iced.1190-01-01-00000.nc
  hashes:
    binhash: 11cfccaca644990e58b8c198940b3296
    md5: b8efc5981477eee561824c12ad462bca
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ice/mice.nc
  hashes:
    binhash: fbab8b5040e25bf37c71df4f5c25a743
    md5: f3e0729e2b7c384570d9afde47f0a1ef
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_age.res.nc
  hashes:
    binhash: 152f4682104aaff49164555cc5f01661
    md5: c94be8730703c8beaca8bc34e8f5c7c0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ba5f4fe403b85b975405614cb3a12d6c
    md5: 41a962636d1f3eb2ad5bc455066cf1bf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9790dbf7db1a3c675aad7fa118f88006
    md5: 3e162ff5a97b10439e533d5d2707f06a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_density.res.nc
  hashes:
    binhash: 023daf5105d5fdf13d4a085a6a4800b2
    md5: 9fe04e50b3773ed02e6d7b1db60be9aa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bf5e3606c99ac1662e39818e336e88d9
    md5: 09b57ddeca4bf9df698c5a67625d616c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2859b8e138c1c1b6c82554457184486e
    md5: 77578e9914f83045e8e1d42e41c9f186
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c67e8d89bee8669a86ade311a16481a9
    md5: 5f3dd3fcc1855fcfdbd975535560d722
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 686bcef3fbecbdd6c5470803ec1fc338
    md5: 81672a0d619fdc44b93e4bb56e4b98c0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3e7deb19cb408116f0bc781e3eddab2d
    md5: 938a2e0f65e78e8c8b5f38f625978560
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c7222c788855efe6759282fc6fcc7ba7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_solo.res
  hashes:
    binhash: 01f4ed97a294b9cdde825a1dd27f7590
    md5: 0c6eb4e88316528a3da0c202ded1e6b0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a227e2fccae621e6987eca5f365cea21
    md5: 799d747d096e6be24b80495fcd2c94b4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dd94d0ab50540ed583e92dae42d2a878
    md5: d7d7794531c51c1c61e8d484cc01c6b6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_tracer.res
  hashes:
    binhash: 96d1832318fad21fc0f6bdcbb45cc33e
    md5: e7893486771ab0f013e2206acc3e15eb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ad20648be1ead83aed0f2ad3bddff517
    md5: ce1ee1e2f582a057d7d44f462a6506a2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1b32d5533e3dfb201daf28d51a894a34
    md5: a48a7089461c87104432d7ef01bbc52e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d5c1a877a865b44d063b8e7b581fee90
    md5: cc05d882741b235d3967affa758b5d2d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart306/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1f9354b489a762162ebdb54610ce89c4
    md5: a8f0374016767814e6925b449136ff71
