format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/atmosphere/restart_dump.astart
  hashes:
    binhash: ed21fb7c43b53a55c13f70d5f91afa3a
    md5: a31baadd2d43a875c4f3f997c42ad8e3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/atmosphere/um.res.yaml
  hashes:
    binhash: 20f8af63d5429b4d13c358c5ea1080b4
    md5: 2e70fb60ec0c473c949443ba37fa09e0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/coupler/a2i.nc
  hashes:
    binhash: 45c8f1378e3642b9e102a27d652aa8a9
    md5: 5eea32bd10f31d28a754052aa926583c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/coupler/i2a.nc
  hashes:
    binhash: 329d05d74b337d4d6029d6ebd7502a23
    md5: e1b95955efcd3a27cb113aaf5142e707
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/coupler/o2i.nc
  hashes:
    binhash: cec62f2dcc9629ea56ef417f63d3f134
    md5: c2ec4b2327e8b570668fb2b23fc9a1a7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ice/cice_in.nml
  hashes:
    binhash: 8a27cdeef422ed2472e37c26d2ce02eb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ice/ice.restart_file
  hashes:
    binhash: a3e8ba14a54bf6c67d021e9ac7c5b7f7
    md5: a5b57180699e73341d6036074ade107b
work/ice/RESTART/iced.1238-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ice/iced.1238-01-01-00000.nc
  hashes:
    binhash: bbdf5adb78ec9ad53905ae0ed0f68de6
    md5: 4295507964fc5d3d769dea0d34d2e4df
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ice/mice.nc
  hashes:
    binhash: 6916a18d2fb295c990b730c361e54d8d
    md5: e7f13a2f5f17c81a36b8b2d3f728fe65
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_age.res.nc
  hashes:
    binhash: 02bfd6120ee69153cfc77d8776b875de
    md5: a0a933e57c4eee5d30de38d36a910a8d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ecfff8e6d7995a80a910c62356bfdd3e
    md5: ecd5edf402750def622515de0fcbe2a9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f482458f6381578a125e82f1d5c4dab7
    md5: bf8f2b1fc6a1ec98a8e0d6f4d98bb8f8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_density.res.nc
  hashes:
    binhash: 6ea85855f989f7002f48af65d1122c15
    md5: 56b5e44752d065d5cde79324700e2648
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 487210adf40c7c9fe0811041dd1da69a
    md5: bbf2c4290c479f2752356911cf5a34af
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1d5f367052d4790dbe8d0a0480cedb09
    md5: b94d4badf1477b4305734b1be887f1e8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2dd0a0062da8e7e0933b17c985264496
    md5: d1d8a8df43e477dcb865b704edc12bda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9335ccc5a866ceb3fe9f371ffcfeaf92
    md5: 6754a2f8a53a556ec0372ff3cbf4ac9c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d109cb91da74a3d841e8085165e7c33d
    md5: b4b535e7b349496f4be551f277418259
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 04ab4b6c8c9640682e28ce5c2f29c295
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_solo.res
  hashes:
    binhash: 91499a9780a1e4d9f1734c4d6a05ca93
    md5: 932b8e35234f7f84aa7e855733c01921
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 47c4edcb6c78d473ccaced9e8ef168aa
    md5: 7fe73174481e5fc56b003843f910ee0c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 17823fee714e28f9ec5c6f9eefcff88e
    md5: be3baabe966289fba790e19d994dce3f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_tracer.res
  hashes:
    binhash: 3997681cdd7d764b61ce6d24f2d448b2
    md5: 97da093895466046c8688135091c8327
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e82de5bf5a322fdf00ebd3ce9e7e3c29
    md5: cdb61933c22ef9b83e18e00523c64f64
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1f0301c0ca66a6ba5c7b9c6d6ca9ca6d
    md5: 532d2279041ad9ccc4a77c8ae84b0ef7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0631afb962f0ed5ed27af55daea1038a
    md5: 5bca4edc4567278b328b80e49aef829d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart354/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fbe7bdd2cd5f4f148fc3a83209d10711
    md5: 4fe5b099b2c39ec526d8bacfd90f08b9
