format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/atmosphere/restart_dump.astart
  hashes:
    binhash: 9440b0e7a1530ceb6a13a9ddc72253b0
    md5: fa49e72e8967368fe9eadd3d7a6f0603
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/atmosphere/um.res.yaml
  hashes:
    binhash: b598053181f5270e9b20f0026894abb7
    md5: 00d603219c4d978f70fd56a43c22aa7f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/coupler/a2i.nc
  hashes:
    binhash: a29cc8aa6efbc99f039ee9c5b82b5527
    md5: d1e2d7a3fafbf625702da5d4cd99b058
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/coupler/i2a.nc
  hashes:
    binhash: 90e5f64cf858fa577f7b13a52ae8a61a
    md5: f969b019e4279a068fcf330d7c20282b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/coupler/o2i.nc
  hashes:
    binhash: b9194fe55b402221ed249d57496b9c77
    md5: 97b14f97550248efdb4036631356a327
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ice/cice_in.nml
  hashes:
    binhash: cd662773626e35d84ba243e769267d9f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ice/ice.restart_file
  hashes:
    binhash: a16c0ff66c3ff70507d1bb3a0268cdf6
    md5: 9711f39ca1f4a203eb4229f55eb19c95
work/ice/RESTART/iced.0896-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ice/iced.0896-01-01-00000.nc
  hashes:
    binhash: a9a2963604e2dd3d732479b4004d2059
    md5: 56a1c301286126a13d4024c977fcde99
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ice/mice.nc
  hashes:
    binhash: f5c6a0a147e554b1a6ed2aa3e6bc4fb9
    md5: 5c9547986e39fadfed1dcac1cb259d55
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_age.res.nc
  hashes:
    binhash: 5d914cd73c249de0a9abf5efb471237f
    md5: 8dca30a3f1c5a754e41639a0c155a586
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 987a8b8ca435557a485e4cdad9c56694
    md5: 88ac76b83fba9297f3a4e16c350ca96b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8cbc635f12662cc5e9ba565b05f9eb03
    md5: 920694139d0a14a3477c1e615cbe85e8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_density.res.nc
  hashes:
    binhash: eee225c65d2bea8933d09efdd92f6d8b
    md5: fa410c87a6aded4705d2fe22b70f18b2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 80c43606a656ba434c311f49457088b3
    md5: 0a63253dc6a336f998ba27cb2675b3f7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 36fcb8c0f2d80d186fa63633794dd002
    md5: c44a4449c74748973fcc5cfc5bd043a7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4bdaaadaf5177de5cbdc98b6dcfa69ae
    md5: 40fb4e93b985ca39f7e700df3c04a774
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6f8b2a6363b22bb9173d2a13f37cb505
    md5: 2d325eef9dfdfed16a615236ee1deb6b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 589699a6d3571cea80ad8656d8ce5bc7
    md5: 13e74707aa128b96d1ff5999ecc8e2ea
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fa35a2ad96f9dad72cb041b1af323f76
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_solo.res
  hashes:
    binhash: de3037cb82a4b1a0f75d3878429aec06
    md5: 5b6607de5ff5a652ad59fc983bba2863
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 25f8b6e0ce278666af14c2e963240fd3
    md5: 32505051ddb018721f4087c03d66befb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e295cdff6759a4a46fc26aba1e1c7446
    md5: 42b31e12f9c14bfd15d70cdabe83bc4e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_tracer.res
  hashes:
    binhash: 4c1eefae8f47bee241ca8d4a93f47df8
    md5: bfc1b908b64d7aafefc064aeae4de129
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dbd6598b99629e2d414423661200cba3
    md5: 32e8ac995a01717a739caeb2d9ec383e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e0e638a56932203bc6ed78888dc910e7
    md5: edc7d607ede64500894957dc3df21b5a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3e56b7458e9df441647625f9794acf7b
    md5: 952b66122a86dcce44d1c6a757ffddd7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart342/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 507338b0169c3b71acdacc8827dda746
    md5: dafa1738a82ea69fa18faedd93599d84
