format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/atmosphere/restart_dump.astart
  hashes:
    binhash: 29851aa23760166ac22d53fac958f1a8
    md5: 676c461e9b515296e5fa09e1e48e352c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/atmosphere/um.res.yaml
  hashes:
    binhash: 88e5654debee09867b72c205604e6e89
    md5: 3c606d4a27a2440c5fdd69dc95ffbc42
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/coupler/a2i.nc
  hashes:
    binhash: 8e4d2de5ffd20f804919d09834377ab6
    md5: 9b5fe9b93e164a43d7c5713afa239416
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/coupler/i2a.nc
  hashes:
    binhash: 31e73fe52731011cf26b392542bf82d0
    md5: 6f1e939f9fc7725d7ecec69f3b17bd29
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/coupler/o2i.nc
  hashes:
    binhash: a18f09a635434547857e09e736498acd
    md5: 1e6d8c69ab2b313ad5e44fe34797b6a3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ice/cice_in.nml
  hashes:
    binhash: d1cf40a589505f7f8c6ec9c7287766e4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ice/ice.restart_file
  hashes:
    binhash: 18a2d87df2ae292eb1fe1a674d7d5ec3
    md5: a4ad9ab941e4f5b916d39d82e9181912
work/ice/RESTART/iced.1776-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ice/iced.1776-01-01-00000.nc
  hashes:
    binhash: fea32dbb3f240587df1da5ff78211a70
    md5: cb2b34badafaa0cc5a693fb5e1098850
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ice/mice.nc
  hashes:
    binhash: dd12f7d72f3c412a80cebdb187189f80
    md5: acbc28ad12940bf45049ba82980190e5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_age.res.nc
  hashes:
    binhash: 3289bdd54e4f4df69c95ea92c5315272
    md5: ad640d6822339f84ffdb7fea21270ddc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a3a417917949b4c7431915f83d84e8c7
    md5: 927574cca06512c84397e2aa1a5c1e4b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 32af2bb8b0e311b8d3df4c2e0db62a0b
    md5: 4293f97705f116795c89928293ba6080
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_density.res.nc
  hashes:
    binhash: 54ed49214ba53471767fbe1196f6e1ca
    md5: 78033b902789f234bad9c449f662953d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 553e11ff8bc98f41c218416699f65e84
    md5: 57ebd629edd1a7d9f180639389aa1681
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b75b34931f46bd91e607a3a84614d9d8
    md5: 08a8944d1320878d098feff233244ec4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_neutral.res.nc
  hashes:
    binhash: db55e0d34b6b184277ea873889e3f08f
    md5: 3faf4c6a603f9d9eac24b344f27f0050
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7382732868cf59da66e2039def6325a8
    md5: ee77776e4d77fa2580638635df85e89e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e59e6425176df8d666aad74676e31c29
    md5: 60fca511d512e5d5567bb3a0f27c8149
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f857e7688d86662f748a67e2dc75ba4f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_solo.res
  hashes:
    binhash: 42c7e1dfc5ac100d30d3638e45f29f78
    md5: 7bc5e9477b42409b768996b6fb922e41
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 640bee8d72dc1f239e293c2ff3def4d3
    md5: ca267c91ed933f03c7ea8fa81664078b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 18883e66f8858278d3d9514c37c22cf7
    md5: 49ccceb906938c7f4dc3b79951020219
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_tracer.res
  hashes:
    binhash: 2cb80f4b7c0fc6b1c22c5c1f58459cf2
    md5: 27b3d06c551ab9197c10c96e835f603e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2c5cc7e6549034f4731b7a0acf4c2727
    md5: 43ca61f35eeb3138b2b797aa240bdda0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 61ed9191e29415cebc35e3e2d4f49ef8
    md5: c248b1a551ddcd415b43faca9e595d39
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 454c93fe8f07ab9c923aa3d60dea1bec
    md5: aea43cbe18bdf0399b2cad717bdde63c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart331/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bc892c15a08d17c825b12736d707511e
    md5: a38383870137cf96d425dc347f08b765
