format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/atmosphere/restart_dump.astart
  hashes:
    binhash: d4690432e58d7d35c7f29403a0009e7c
    md5: 0345e7ffa8f9c14bf894c77605911558
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/atmosphere/um.res.yaml
  hashes:
    binhash: 7c43dd6009ca2a36627583c408e6fd1c
    md5: 9dfa88705b04cabcdd6a506596cd58a9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/coupler/a2i.nc
  hashes:
    binhash: 2c8e0e71b148343725705357057c7965
    md5: 30d376792bb2f418563c2257343899b4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/coupler/i2a.nc
  hashes:
    binhash: 1bd8b65a4148e04df78a9f4bf2911d6d
    md5: 8cc339646d70e06c9b263702288aae3d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/coupler/o2i.nc
  hashes:
    binhash: 7d4b66603b2fe9e80adea2452aaf86f7
    md5: 44e967f1615f81feeca0be1baf678ab0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ice/cice_in.nml
  hashes:
    binhash: 9b166157a3f95985aa8c7ade8fbcafef
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ice/ice.restart_file
  hashes:
    binhash: fb250f0ee17ab06569ecd537563d064e
    md5: 8c8dd6db6c533488b3dde2aa5dfa8154
work/ice/RESTART/iced.1208-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ice/iced.1208-01-01-00000.nc
  hashes:
    binhash: 430768c3c2c51650cb19bd3993924828
    md5: 1c9f4e086e5024417be508330952c972
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ice/mice.nc
  hashes:
    binhash: e13c6ae8e6212e25e1eaec8956dc1425
    md5: 9dbd5e5a9458a3729af24e737f9bea9f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_age.res.nc
  hashes:
    binhash: bedac8e793de5fe6d963a4fa799081c6
    md5: f2c9dcd3dc78c604e112b71deeac9cc1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 90f35db8a6d88c43d90851e9008c399b
    md5: c93ef02e0dd6263cf6159903759b3cf2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 493e4ef6222df3c826f40e53d878fd13
    md5: 0b4b7a6fac85c7530f5898bd21ada669
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_density.res.nc
  hashes:
    binhash: 2d5bb22222b5394b0105bb80695b5c03
    md5: 3376970a74f9edbb2f533369acb1b051
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3c7f6b87d4620e529adcd7d6a10f06f6
    md5: 7589b308af2384c073c0a00d853070ff
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d24d98a3745e9ca319c587082c799aa0
    md5: e97488160212d93aaf33894452e2b22c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a4b9005f5aa4f0e676d97e8776f081ef
    md5: c5ab66bd1ca9ddad840b5377460d4890
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b1c48d1ccb478a77ae7abf900592ed83
    md5: 05f2110cead66a4345c27a7c66d52f9d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6d4e3649c42d51d3d08f54b1e9398847
    md5: 87c46099b6fc7da4fd4f1631c35f6122
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 64dd0aca448a10b419dc993d338d39f2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_solo.res
  hashes:
    binhash: 3ff2e0b23ddaf68ca569f9c27b358a6c
    md5: 4708f034d9720df9c0a20b627b8de4a8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d7b106aa5ecee9b6c7bee6cb3b3ca6d6
    md5: 9990da68a77117ac2e950d219a592ca1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a7e0faeb137b906f51a5e95683e09187
    md5: 9ad4aa4fb9235c3a0358631d005fd3dc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_tracer.res
  hashes:
    binhash: 8412a86866f48ebd16894742ca2b2e86
    md5: 383cc1343376fefb9368f121685b6889
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9746d413bc6e260b5e5ba234a7391dc4
    md5: 27f2a8502702e5fa185cacf4aef8866d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 54d00e09ba12247f1261d6e9f1a36796
    md5: 8292b63777a4f9473f7bd446c5af6f50
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 55928e9e3ed9b65d684a2c0870eb55cf
    md5: 6a1369ff63af24979cd63021e6e0b253
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart324/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6ff2faf0db27c7ae47ddcf1814d45d6b
    md5: 83569bffcfa54df04112093615e23628
