format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/atmosphere/restart_dump.astart
  hashes:
    binhash: 6fc50a267b0dd7e37e590686426ac8ee
    md5: d88fbf764a21963b9194a9c3590dde8b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/atmosphere/um.res.yaml
  hashes:
    binhash: 25e8a4ea050397984cd74ba8b3f91d9e
    md5: 69cc27e6f64c64f1ad15bf6920764cb7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/coupler/a2i.nc
  hashes:
    binhash: fd482da25624fdc2dfc3628d44149ce8
    md5: 7c556934af3a08ae5e68da6015fcb054
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/coupler/i2a.nc
  hashes:
    binhash: 228c342eed92ab05b937c1b77a2e4de7
    md5: c95e88d637a5c6aaec96bfbae7145a68
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/coupler/o2i.nc
  hashes:
    binhash: 148514a9a93e9115e72ac057ee86a0c5
    md5: 173acda7cabcc4f4bce846528457d1e8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ice/cice_in.nml
  hashes:
    binhash: e39928663702a17bd69f903abf431e7c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ice/ice.restart_file
  hashes:
    binhash: 90b7e944723e4fe798770e8b324da7dd
    md5: ce262517400458a3b680161bffa083a6
work/ice/RESTART/iced.0902-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ice/iced.0902-01-01-00000.nc
  hashes:
    binhash: 33d8603553b94c6e6dc498488b68f74a
    md5: 069672f6710fed596070c8b1f6792007
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ice/mice.nc
  hashes:
    binhash: b6a4aa1d2d1386996ed9f8f4432a6b51
    md5: 65b0689ff489ca7bb3f2a87a690b9c60
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_age.res.nc
  hashes:
    binhash: de5e5443890754d2682d54e6a0bcbcf6
    md5: 8856bdb0c9c236ff8245c19f472ed324
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fbea315fd7368064be8a13e01573d4ea
    md5: 9132d1df2f71bd447c7c1584c5921429
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 71b25e91f18465d499647815f5645be7
    md5: e42e043f32114b1d8e4b3f9610ba44d4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_density.res.nc
  hashes:
    binhash: 0fb0ea0540e7897a95495b16a0ec1b7f
    md5: e877815ce9916ff6b199c41e9482cb0e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9e667d4f9488956a7bac474ed3b2770a
    md5: 23f16d4615bf54981fc45e95111d00e2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3177ec3db9c0ebd1689ab281c3ce6814
    md5: 50b758d4cd75ff05223a8c857339e1ef
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 067b4b1ed621b7962005ade4ca3f03fe
    md5: 4b9b8d4df8f3cc7d9ebd62faa8b1aa4a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e39471c83b25b4589da19bd34ece75c6
    md5: 3ce841b65a5fbde1d0f2949f2a22cc6a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2ba5ead15c879db801093f7a20adc055
    md5: 8efef968a4c38c43017b64971e596554
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 22c9db116cb756e6d5178364c87345db
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_solo.res
  hashes:
    binhash: 3b7ee8523d3fea92457c2df2bf8b1f8b
    md5: 058d5b57401947ffae5e0925ad716aec
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 15c4c4834b60d17b818ad9cab9ae69d0
    md5: 21ea89effb2f28be670c832969bc0b53
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2f901e8931c0ef0806523b1cae3a9db8
    md5: 7d84f4e4a344d3bb8034f84a9d9eb9cd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_tracer.res
  hashes:
    binhash: c6120ee2a0ec8000da62235e6da9ecaa
    md5: c03483e0936423b54dcadd732042a63d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d5ced257ebb1e0e45c5a0159da93b55e
    md5: 2c0beb93397b7abfd19960bf94092be0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b90054934de6eaefb48e2ba2e011771d
    md5: 59909b001b0ceb6a9f2e782224a73e60
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 61b8dfb8ec8434f08d2162b1ace1b0f2
    md5: ce7eda18304c49aeb5246f9dd0d21434
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart348/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f30f387a87c3161e79e6448adaefe5ab
    md5: 7ca90de878f1ab38f68b585b4a4a3f21
