format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/atmosphere/restart_dump.astart
  hashes:
    binhash: 54398c456da346593e7befc3c1f00fe0
    md5: a16966a3d2494462540bd337a9c8ff20
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/atmosphere/um.res.yaml
  hashes:
    binhash: 94dea12d18c1978545ab27a1196101a9
    md5: b5b3f7bcb2a52f6890a3706ef3d0e2e5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/coupler/a2i.nc
  hashes:
    binhash: 619c7df5f69688e3c1be8cc86db79452
    md5: 70cfdfe21554f95732d758bcd78394d8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/coupler/i2a.nc
  hashes:
    binhash: 686ff28e81a4f1f679f85f68187ade59
    md5: 93d22aaea887572e85efe28d46e654d3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/coupler/o2i.nc
  hashes:
    binhash: 0f190069ad260cea1588ef839ab0b070
    md5: cf59a171124b6913ed7b995668e4cd36
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ice/cice_in.nml
  hashes:
    binhash: 86707f43d17d3232951ff043984f933d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ice/ice.restart_file
  hashes:
    binhash: 86040cc9b2ed08a9a78afae8e60b723b
    md5: 30b5f58c0a49980f0c00fa74e923ba96
work/ice/RESTART/iced.1305-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ice/iced.1305-01-01-00000.nc
  hashes:
    binhash: cfc2dd41b19085e97679f1d7380f6301
    md5: de6e1ead811a45fac67c8497fb98f363
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ice/mice.nc
  hashes:
    binhash: a02551fe51fb5c319915d3df22282d74
    md5: 5d769a19da8e87faa01ce4c102e08083
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_age.res.nc
  hashes:
    binhash: 2548b25b100c9b4d3e2cbd1039d51ce8
    md5: 26c95dbfe08cab6f8cc3ca861e063b33
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7ed0196615fb816b07a6bd3d3213b4e8
    md5: 357ed10baef274474c5dd7b6246a79b7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2743189e4145a0acf427778dfa413914
    md5: ee9c08ec68b664541605a783fa049f82
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_density.res.nc
  hashes:
    binhash: 1fd3fe2012caa34277020d2c24396a20
    md5: 88adca9a0292cc38e97d3d9730b8d3b5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6a8fdea0eea79f168f80392e5fbbe909
    md5: 2e80f1dd6343a352fd4c08eb0bb2445a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c568cba9ab9e4ecbea229fbd7969c919
    md5: bff011f77af1bd516d3576b505a251de
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aed230687d7def00c2543f97d00dd5de
    md5: b582a343c53e1de90be71f154bb14181
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cffe40382329ab7da180acb063511465
    md5: 828c20aa7f62e7d9930233ca36b23539
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 00d4e43291029f31185c423b9a003db7
    md5: 6da1280f309504dfc02a13b223d15ce7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 063000065cff0d550a66221525c0da45
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_solo.res
  hashes:
    binhash: 79fc602fa0cc31f155b3973955df6ee7
    md5: 4d2d7f75174b5ff1bb099d3111b89dcb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1fe0edcbbae15bee5d63aa1bf7d1d6f3
    md5: 06667415de7ba9d0edc4646aef848919
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 32b335d3f3052e35d886ed7fad6d23ed
    md5: b0181f80e93746354ad7df9180491d26
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_tracer.res
  hashes:
    binhash: 708927f6b11f1aca8b78c5b326e34c84
    md5: 4ed5fae25941b589c258c8fc9e9dbd28
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e5c73ad52f04e0141542aee7f3eb5cf0
    md5: 8e1349b8c3c177b8c57065184b2f801c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bc402e09a937aae55766d42a352b4ec3
    md5: 8e056f1c67a24e3d68a63a9961bae05b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 416f6515a5b06eff5e4c6b5cf9d85c1d
    md5: cd3889b8ca73fcac0165da26f5905120
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart421/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dd86334eed33f192f28237706bf29918
    md5: 297b1231a7ddb4ba19cba3a858642abe
