format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/atmosphere/restart_dump.astart
  hashes:
    binhash: 7e095866cea335d3871e147b5a9164e5
    md5: 92f6b89f7ca5a2f6f4260a9a9589bc19
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/atmosphere/um.res.yaml
  hashes:
    binhash: 7c146422adb58b7ef9763cec0aec9467
    md5: 5902441b4e8b7ebd0c34737af7588e38
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/coupler/a2i.nc
  hashes:
    binhash: fcf86764cd176ef2abb5a662399acf87
    md5: c8d442461ab6fb737cdd1e356c83dc7f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/coupler/i2a.nc
  hashes:
    binhash: c13a3fb55273a2f602926eab8378f1e6
    md5: 318793764540b29ddece48a516a7337d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/coupler/o2i.nc
  hashes:
    binhash: e0b17d63437235b961f1260604212aa9
    md5: 4a27ac1f06e1f80cb5eaaf9d014dabd2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ice/cice_in.nml
  hashes:
    binhash: c28a2dc17a9dfadc479976cad7300fea
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ice/ice.restart_file
  hashes:
    binhash: e61e01ffc635eda5e487471cff636569
    md5: 9ef31faaaa6abb79ec67d901446d552b
work/ice/RESTART/iced.0912-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ice/iced.0912-01-01-00000.nc
  hashes:
    binhash: 9dd82cf48d766505897da01173aaa27f
    md5: 6f52b688633cde7cc46140dcd9617de1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ice/mice.nc
  hashes:
    binhash: f3aaa0563e1f87e6b532b78179879188
    md5: fd456f0227f64ee8cb48686040fbbfa3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_age.res.nc
  hashes:
    binhash: 6fb1e04efdd74de04c6d77472488bf61
    md5: 2901cd39167abdf9010a72c7cd844bff
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b693bf64705252e28e43a1009a6a1376
    md5: 71bba04be03fdb36a4c2a12027578aaf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c81bb966eb67d4e40e62c19d51b1efe1
    md5: 25785c6c8d682b4d58b3253e2c74f1a8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_density.res.nc
  hashes:
    binhash: 9c0b691da6978470d2b1afdb5d6e77dc
    md5: bae7a2861b1ed8242b52571b65a7f557
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2c714234272c566e7df1a2b4f4e128c9
    md5: 64d3844203908dae8762ca9d4d237c6a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 33c4a0c5015da0bf56723328aa958ce8
    md5: 25c25d244761483e2e242e7f5a3a8672
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 71c5ce89756a6b35140cbc2c34053aa0
    md5: 9974ab912966985c9deed6b9e3b6136a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dd827b67da03c7bc40ce153d9c88746e
    md5: deb7e0c7bf992f3e5a660d2f4c1592ee
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bdca0c4010b5c4ce6e597439e67ca74c
    md5: 32a3aae2265f8d499b68c3ebdad7f73e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 19baaed04f6f54956db46be6e0f7f113
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_solo.res
  hashes:
    binhash: 67850a03c00b8d05683b42a14f480b43
    md5: d9a648536859f1c08334cfe43c4e77c2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9816c2ebb852a1e8584244c4d2feddde
    md5: a709a7fb798c35a552eb3baa24fee772
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 16ba2599ef6e150fb52a643060fd084f
    md5: 6bad3582e54f19214d0141576ab22e16
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_tracer.res
  hashes:
    binhash: e682b4edc78c20b8576babcc85d32f00
    md5: 53917d1eea0a5207b323951a4bcda5f9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5989e191bde65e707f690cbf86e08f37
    md5: dc87ef50dcfe45482387f418c26a34c2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d666c1040bb70354b97c84388216d37c
    md5: c6ebfe5764d142efa2c349cb8950ccf8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6da3fcced1fe820f50b515882f4e410f
    md5: 134c686bfb669e49ec0ebaceca8de428
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart358/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f8b677a5a51ae29db583cab85343847f
    md5: 9c601d2b04b26cdb67212beb55afa71f
