format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/atmosphere/restart_dump.astart
  hashes:
    binhash: cddb30eab00be1a80be27028c53960c7
    md5: d6545f5737eae6702e53c95afc9d9031
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/atmosphere/um.res.yaml
  hashes:
    binhash: 50fa9cdadcec5abbb288639899be8b0f
    md5: 60abfc607c1420f63dbfbfeb4ef5d305
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/coupler/a2i.nc
  hashes:
    binhash: 570ba3b32fefbb5efed26536c00e5716
    md5: 093944c62b6767a4b9e488d824e95af0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/coupler/i2a.nc
  hashes:
    binhash: 08aea5ad9c86d6f05ad593ae94ca40a0
    md5: 905ddac5c3908d93ae20f48d21cb9889
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/coupler/o2i.nc
  hashes:
    binhash: f3c7dd6953e972e0bb0535b6ff61470c
    md5: 9277edd2b556f33b324c52a0fb3ff7f8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ice/cice_in.nml
  hashes:
    binhash: a6ea92fb1542b958c70eddd519b1a10d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ice/ice.restart_file
  hashes:
    binhash: 453cc20b7393254390784bf03fb9664a
    md5: cf4468166de8c2cd7f86f98db83264b0
work/ice/RESTART/iced.1809-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ice/iced.1809-01-01-00000.nc
  hashes:
    binhash: 87a8f4d580bca6f6cb7759cefb02424f
    md5: a966e8bbfc39999616698843468e782f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ice/mice.nc
  hashes:
    binhash: 6a6d73f2f32a274deab2bccefd610c85
    md5: 4d37d735b5f8621544fdeb4f64f0d817
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_age.res.nc
  hashes:
    binhash: 75b6ef5b2e8fe816f9f40ab0e107d601
    md5: 08962f99c9dd7ff55d6889ea0ee7c5fb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c2a676c86e68e97b6bdb390ff12e0a96
    md5: 0e0a473b87636a077cb3042b7ee2e3e0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e74c61d8327fcd14ba2045466ec6bf4d
    md5: b6e7dcf0d753aa96c9c1cf236424afae
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_density.res.nc
  hashes:
    binhash: 127aead8ef160077c848491e1bba3677
    md5: cb69f13c3ea198dbf71a88469c04934e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 278f20499f9ef1d1098243ce93ce705f
    md5: e44670f805b9e16a27fa433f90184aeb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 45794683d1963360eaead89342421771
    md5: 9a1bf0aea6dd734ef13d7ee40edfcd9f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6455a30f4a9f02c3d2f2e31f4e2aa226
    md5: 09a070b21ad05fe2f798085c21779e21
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bbb1924cecf42cfd82d4a974c5a9f823
    md5: df01276f454ed62771596013f4facc95
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6517db8b2db868fa46416d7739c98f5c
    md5: 30a3f9235f89bfff76aa8438b3060721
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d6c2b71ece2478e867a0e3291201685c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_solo.res
  hashes:
    binhash: 1d1ba3c0d2cbbf37c05a3420a3c271d0
    md5: 1528136cee4689f421b391e5127b3e01
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 98f130fde4c4d2fb5f812da0fe87b2b6
    md5: fbddb88c9fc4b265aec9b53a85f8a1ad
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a681d9dbf304ff07fa8f80e0e23d829e
    md5: ef7743b40f10beff40e25e33fe54609e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_tracer.res
  hashes:
    binhash: 3139be2eb06f562ca10e6ca17178721a
    md5: daca0bd7a0b59b18b2619680a90a10c8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_velocity.res.nc
  hashes:
    binhash: df4c9313768a4a715da29f6e6aa24c47
    md5: ece98ae3dd0ab2581427a08cb92a0fd1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e73a399bc03fcc909566ff2170c3e997
    md5: b10524b8344adba8d25ab9eb696d3c3b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 98ba01e0628e9fa6b7d8e4d324ca1e3f
    md5: ee6f7c4582b534177318b5512e8e0eb8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart364/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 71a89eb1dbf6bdf617ff43db5d2b07ab
    md5: d7a07f5faefc255189c6e80770b23a82
