format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/atmosphere/restart_dump.astart
  hashes:
    binhash: 4abae7f8bb3e9934e6e65293d367cc6d
    md5: adc1027705a3206399c55b06ba98868a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/atmosphere/um.res.yaml
  hashes:
    binhash: 874670a54aedc586fd07b4160aa5f7e7
    md5: 91f15f4c154e8e1a50fcf7199e22c523
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/coupler/a2i.nc
  hashes:
    binhash: 56115c436a259bb9916bc9df630de186
    md5: 1d5bcc35da125d263a1cf1695113f862
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/coupler/i2a.nc
  hashes:
    binhash: 52007c9295710ba348b16a92f257a3d7
    md5: ff0c747f0acc3150d914f3ceda565331
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/coupler/o2i.nc
  hashes:
    binhash: 083830cfc9d1ff3231cda4d510f0832e
    md5: 854195cf95f059eb2b1dee3dd5787670
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ice/cice_in.nml
  hashes:
    binhash: 373e533d44c9266cf611d6e79cfc8ba9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ice/ice.restart_file
  hashes:
    binhash: 5f63a3def4449a9d04c14f6d2ee0c767
    md5: 6222858ffb7421a5ba860c01ddb16971
work/ice/RESTART/iced.0860-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ice/iced.0860-01-01-00000.nc
  hashes:
    binhash: fcc28d64707b42395ed7d57f7ea13d3b
    md5: f97aee770961c638f028665095bb8946
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ice/mice.nc
  hashes:
    binhash: 66752f46bda531319c13144a0d1a7975
    md5: 985c2071daada2b548c9df8e65f24254
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_age.res.nc
  hashes:
    binhash: 5e77ed2d31b33ccffdb0f62d3bebf059
    md5: f722ced3b77b65ea77a073715ea1d9f0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5e01ed03613d800b0883975de367eefb
    md5: 9033a0c20cf7f96ec3c8f7e408eca465
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b732de4c93a8d14cc8651f6f0df7bed5
    md5: 19c6bb745269641e41a0c93b3562850e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_density.res.nc
  hashes:
    binhash: e185c0f62e6d5c5d0d4ad04d75662b11
    md5: ddf1a117f0b100cc4346058b78abaf10
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ef58e035fdd408f7d698164febc3ffa8
    md5: 581a6d5aec9e3a79df411a39b50b3203
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3d74c1676165a0e3a08e88684716c7f2
    md5: d8a9ffda3fdff9e47394d834403cc862
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7c68da04b829827cb36abccbb48a993e
    md5: 94845c46238fe2e82971dbeeb0248212
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 454d9c4e8c930425e8421076db3ecc58
    md5: 3ec497fee4b94dac44a9ceadd4e63a14
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b8dc01f351e6019f3ead7d46270ad781
    md5: a7a588f21defed38585e2ad638ea91e7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a294840e4850d15850c62253b40915ab
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_solo.res
  hashes:
    binhash: 3795ac7c5ee9ed4549e77cd1ecd510a7
    md5: 6429f6c3f978757d1b3de6ac5f1bb627
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 439e178397e4e5a15ebb3333d1de8d64
    md5: 668bce7cccddee1be7d4534d83fbdbd1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fa4daf50657c8097c89e3dcec16929ad
    md5: 2aca4259e2e93c85974f26042bf28fdf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_tracer.res
  hashes:
    binhash: 0994c4ff3b65bf9ddf72ab150457d342
    md5: e2540e27901f145fdf88e7d6bf888e6a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ea0d2ad6191e94e839ad13ecdb782d4
    md5: 49c55752487bf338af86b3e8125e490c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9493ba08e0df66e80dab5deaebcd84fe
    md5: 4ae7281676f8cb1a6b6301f01888ffa6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3e26aa81d11bbaea4ce74e4c268c22c7
    md5: c5aa92f628c64b0d0fc3fcaef51e42a2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart306/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 612ed727065d316bfbe1a620c545901e
    md5: 2167e03b8c610d331908575f446c464c
