format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/atmosphere/restart_dump.astart
  hashes:
    binhash: de650d50eca7c1752ede5f1051cbf783
    md5: 8dd3cfc072bb3088107ba03b54000a26
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/atmosphere/um.res.yaml
  hashes:
    binhash: 6fb5677ef0bd164a3193af4c227aaf56
    md5: 9c19a2e5a05d570742c96d29a4f96f26
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/coupler/a2i.nc
  hashes:
    binhash: 562d80614b2616eec0915f626155851e
    md5: efcff5eab512228a81cd3af8422f835f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/coupler/i2a.nc
  hashes:
    binhash: cd25e84fd23b3862585085bceef0e2d3
    md5: 2e0847d6ebaf26a3513e76e25b1181c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/coupler/o2i.nc
  hashes:
    binhash: 78831d1362afb9170eaef440e70f0df3
    md5: 1587a21deca2cb9ad8110a27b8c89be8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ice/cice_in.nml
  hashes:
    binhash: 65fc355bc429d4fa94e8d16bcd603c15
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ice/ice.restart_file
  hashes:
    binhash: ed61a3d251b90a5047137a160dd86127
    md5: 25fc0c3e9d0da69991c97ed340877a89
work/ice/RESTART/iced.1171-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ice/iced.1171-01-01-00000.nc
  hashes:
    binhash: ff7f099dcf3b9bd641c0cafc60e61b78
    md5: 3214d2ad8b89347422bf418c20a20a91
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ice/mice.nc
  hashes:
    binhash: 29c1dac1e836531b7db91df31b46a037
    md5: 8c604fbd3ec4e8a49b51811ce99f0b89
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_age.res.nc
  hashes:
    binhash: 8feedebc8528b01b33ef70baa018b624
    md5: e720b6904a810e5b645ba96c875e1f52
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 711d16f607f4ea6b17f97ceb200dc49a
    md5: d0b09bb9c986bbe351f3b3fe24209516
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7e3abf89008c1da82d10da3db45649cf
    md5: 5b37acf972164ec0f6540031be72034e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_density.res.nc
  hashes:
    binhash: 7cef4bce181439dca8383ac834d491a6
    md5: e96ec71bbc74cc9fedecabd5ce6b8931
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 85876de167fd2965286ba545357fba5c
    md5: c1a42cb460cb0faf0d767f8a416a3a7e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 11c4dc4a8ce857ac9f134e4f3552e17c
    md5: 79bd15118c02e9fb43c80fc7ae383838
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f602c5af4244d17e27d8705f1da48440
    md5: 54e5b9bea0770a28f5b9685cd8088325
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bcd97c84fddae49e7253c818565f4551
    md5: 2fdbcfbb39bfd94025267d53d32e0627
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_sbc.res.nc
  hashes:
    binhash: abc21114ba38ebf89c56ffa9947e87be
    md5: 94ee2b237186dc8611f2d98ae389d563
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c9506afd6586198a0d64adeec6ff1061
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_solo.res
  hashes:
    binhash: eaba325df99e4874a5378e22609c9cf3
    md5: da668ac9441d545ccf6c507fd4b38337
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fedd354032a336fc3190b8da079445f8
    md5: 30b11463e7d8402faf1d961bbfd0a9ee
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e6d2628e616703fbe9f38ddf1baaf5ce
    md5: 6b384804fb25c475e10bdec7330d8b34
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_tracer.res
  hashes:
    binhash: d4e36865c3d6f7e2a78fb696c42677e3
    md5: c01f5042bbaacf0b9a1a47f2deb0230b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 993de64f76949b5e2c8d83eeddd30729
    md5: e9d3deb91367590682aedf65985dacc6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 350170e22dff02c223a2e5686cbc8b78
    md5: e2a15e21f4a7256df7b8faa02fce48f2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b4cd0c9f569f80ad14789f0dc84a0523
    md5: 7fbaa9192feface346fd77559e3d73a8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart287/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 522475b58ea5f5eae2cb2f55ab93741a
    md5: 61811bfc6c1aef0efdefef04807f0c70
