format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/atmosphere/restart_dump.astart
  hashes:
    binhash: f058ec0c70302ae0b24078498984d9d4
    md5: 2ffd55811ca709d79e77b7b2612cb557
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/atmosphere/um.res.yaml
  hashes:
    binhash: 7ee347a3fd99fcd143a1fe4f48aa6c0d
    md5: c4a72e3a1a48d7387f6d62dc8cd1fdba
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/coupler/a2i.nc
  hashes:
    binhash: b347e4d15bb94a6ac63780dc4d969afe
    md5: 72c2f3c464f2ca7c06111415d936c13b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/coupler/i2a.nc
  hashes:
    binhash: b5deeadaf3dfd6e173fec2e29a04f5fb
    md5: b6998fe505a8b6d4c4db5c03fff11b0e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/coupler/o2i.nc
  hashes:
    binhash: 956698fc32508f331019f2251a1cc3ab
    md5: b8a038be58aae1d6011497047bff0c40
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ice/cice_in.nml
  hashes:
    binhash: 83201112fa9c206120a82c5c0413b179
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ice/ice.restart_file
  hashes:
    binhash: cec43a4f0728844f89a97e09d027a7d3
    md5: ff9bcdb1e2d1fead05e27e24f7539274
work/ice/RESTART/iced.1768-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ice/iced.1768-01-01-00000.nc
  hashes:
    binhash: 4296044cc7058f8da52d354dedf34730
    md5: 51caed175a90b40bca2f1c4b8b65efc6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ice/mice.nc
  hashes:
    binhash: b679a233998e18f871013e13e6d49d9c
    md5: a7dc8c95d816f902f33df2404ca789e1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_age.res.nc
  hashes:
    binhash: c8c87b7ea0ff22a09510667b8ccf3b3f
    md5: 4d657f2af9a4cbfcbe125e6a6e3c8759
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c8a7ac918e96be84829e211d18a98459
    md5: 910d99556b0f4f8e661414007bf84aba
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 167b2216dff822ae844abe398981de82
    md5: f52f2b64ff242e7665d640ccdf339e5b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_density.res.nc
  hashes:
    binhash: 8448aeb281ee5992e1e0d9ed6f020707
    md5: 14ef718e2d5abb9c283e6e8c32458cc4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ed5c7050a57d1a5ac0173827b8c08d9c
    md5: 03774045bfec2ac2214252342c8b07a1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0682e7c8afc16881afc4393bc7259359
    md5: 0c7dd5246baa88211674f9a4f8fa2fb1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c7c031539d2f128fb7c00bb08c407a86
    md5: fbb49ef53e85f855711f630c1b7e096f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cc4ae6cd6f923dfd7bdf09e9dc297603
    md5: 5b7d8d1d7fdde6080294827396034921
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bd22ac06656af4ef423f8638c348e5e9
    md5: 9b58ebc77445b143c1374b44bd90a5f8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9b626246854974ee022e893df167de88
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_solo.res
  hashes:
    binhash: 839ec32751ba40603106f85c72583be8
    md5: 1d5085d6c3d7b9d2c18c863df1cca9d9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e61fda7aa9f8621cce91e3e649133b94
    md5: 34b754b6b0433fb83fbee099c614bd9f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f8b15e37fc8c3e4033764a8965e650d8
    md5: 664e89c161b70556bd302284bc83b9d1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_tracer.res
  hashes:
    binhash: 3873e4bd76782ce1c00a45cfca09e611
    md5: d5b9fd37d6932a1540ef13a14c8e6c9e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c98c0a881d95da77a4ad85d29737aca3
    md5: 4b22e58f69e142255b226a4744efc4c9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b4c36edec6481999858c6760d6e9f4af
    md5: a92c995249b136071a0a8447fcc440cf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1d45dc0c910b8c86c06d0e2ea0e6324d
    md5: 5b3fe9d06182d40c7ec547ecf26f939e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart323/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dcc987a7cd45b93dae2a22af82815a04
    md5: 7915168e1d87d385cb0c5d7febc16cf1
