format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/atmosphere/restart_dump.astart
  hashes:
    binhash: 8f1f96c831481991120a062ae760db06
    md5: f4dc68684da90a57bfb5b0c4b6c2ac79
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/atmosphere/um.res.yaml
  hashes:
    binhash: bef76e75b80d3d65db56604f0834ccda
    md5: e3773d5018e6e47eb48d1e3f8b228c3d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/coupler/a2i.nc
  hashes:
    binhash: 1723ac116b69db73e8451d9f7a119a95
    md5: 54bd471e4f0e7868da3db50eef67f2e0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/coupler/i2a.nc
  hashes:
    binhash: 491051f19991c1fa468f3840be2b75bf
    md5: b72cddcf560c2e395b4a4014fa81d42b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/coupler/o2i.nc
  hashes:
    binhash: 8149acc36b24133d3b4761e90f70728a
    md5: 2f6d6efb9ef4d3ba7c05b982d89c2d58
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ice/cice_in.nml
  hashes:
    binhash: 121bb70bd03c6f6a94bd6fd2464da154
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ice/ice.restart_file
  hashes:
    binhash: 92a430989d95e17e633a709f1fae9ffd
    md5: 406e9594b24c18d80196e03b89eeafe4
work/ice/RESTART/iced.1242-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ice/iced.1242-01-01-00000.nc
  hashes:
    binhash: d5e94ca56947089d85e757a597565836
    md5: de56ef929f07b9ac607d77c8c3a29978
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ice/mice.nc
  hashes:
    binhash: 29c08b8cb5541adb608c628ef03fc3cc
    md5: cfd7b13ad71ea0705e89a05a48dbff9b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_age.res.nc
  hashes:
    binhash: dc52af91dd00936d10be332ce282a6c6
    md5: 26fe7c6c1eebbf5f53354c5696e3e925
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7089b47bb34abea0b65f7d32c8d5e682
    md5: 50e68536ac16d447834a79ab1fc19273
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f046c8a3558a79507f2153cb132608c0
    md5: 0c9d2dfb27b763dc271c4a779f6d2a3d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_density.res.nc
  hashes:
    binhash: 075021f535e4c6727d8c5bb9124604d7
    md5: bdea59ec18446c9778139adf1a2132c5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6aab8982d3c1bcaa1f4b0b376e37af6f
    md5: 79b6357f061a9868011488b02b502539
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 071e33071c027cb6b5e8eedf9d817f02
    md5: af2a74719a425ab6739a0c0a63d6f277
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 58504fbc267336e5c1719a5292564c82
    md5: 9e8345024fa8c9ada2e6d33816f05d5f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ad47ff44e0029e2d2582b0d63be6a301
    md5: 6699f493ccd13aca4e598f9af3bfcd87
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ab0823000b7b1fc3cad013da0a03834d
    md5: 9dc559077b8d3fd57287ddb278ca420a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 10efdb041ed0b72e5a41494fba4c5ab9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_solo.res
  hashes:
    binhash: ba04ad2836d9599f8334339ef3422956
    md5: 3e8557c4b36261c3d20eda4e33ddac39
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c82d0066681b0ea2cfba281af099de06
    md5: e3209710ae081f19a6e3f7d7e3c173c9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_thickness.res.nc
  hashes:
    binhash: efa3b5ec440a8a408543126609312247
    md5: 4424de41d827c655ba9da58cdac4fecf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_tracer.res
  hashes:
    binhash: 3895dd2f16a70ed1738014d7af1b5931
    md5: cf780b8a099578802a396dae338db6ae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 38b02b334b695e03af70d3d343e445b6
    md5: cf17085fee35e1a77fccf49b195a15db
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 100b26548d26ff9b067c36aec9a5d47f
    md5: d368f85fc1531bfc44c72ed1850cc049
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0068010e4eb76f1884b3ff1d1bb23c6f
    md5: 4c440fea114d02213fec7e505a181747
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart358/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 07ec242bb903944384a59cc85903288f
    md5: 3661e4d95f9ccf51c17da7214d75dabd
