format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/atmosphere/restart_dump.astart
  hashes:
    binhash: 12726af304f86d7d35da0956f85b9433
    md5: 72ffdd18e9c8da2c2637eb4951299ecb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/atmosphere/um.res.yaml
  hashes:
    binhash: 473f2f174f812928fca12dfb2bd0aaae
    md5: 3615c01a4b58740173c089dfeeb69f92
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/coupler/a2i.nc
  hashes:
    binhash: a26a4255a62d4e733f77daf39ad05e71
    md5: ba7adcab5ed0d4d591d037bd31e33415
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/coupler/i2a.nc
  hashes:
    binhash: 560fd4c42e145a3b77a270b087250146
    md5: dc6942a623499ef0444c848e6fe1a93b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/coupler/o2i.nc
  hashes:
    binhash: 84b5e421d97032d3d09f1c171932a8c4
    md5: 8c613c243bda3a0d94248aceaec8f656
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ice/cice_in.nml
  hashes:
    binhash: 0eca8d05f967ea591c6058b39733e92d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ice/ice.restart_file
  hashes:
    binhash: 149e2c46821fbd59216002f8a3ebb8c1
    md5: b98cb34e80022cff8d2b6d29fe8c0145
work/ice/RESTART/iced.1811-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ice/iced.1811-01-01-00000.nc
  hashes:
    binhash: 510b4877f5994ffe29a8bbeb1879a697
    md5: 7023195088602a74c06a504873ae6c4d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ice/mice.nc
  hashes:
    binhash: 6230138947829c45053246a571cec4dc
    md5: a75c734977175c9e42d6980acdf847d6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_age.res.nc
  hashes:
    binhash: b45147429fd369d75b1638b580c5086e
    md5: ec6ac20dc7e8c9fd9d7fe9b2075fa2a4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d0086370a41e1e64602febcceb3d8a0e
    md5: ac908620b1b7225a80e682d1da7d43fa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a9b996a9fc7b106918a01df3f533d1e4
    md5: f41b26362900254a0e5d1bfc4a456b0e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_density.res.nc
  hashes:
    binhash: 721da01f6b19376eecd1faec75ec5c78
    md5: d351dd7a4552226c784c9545dae6adaf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 55e6c9ccbc0e3366863b69369850a95b
    md5: 21fa9ac73c2256de78754155b5c536ee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3f2b22ec1b6ea3af6464b3a707529ad9
    md5: c30b9b4ed763bf1892eada3cc4bbf483
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 43b98f9246541a0a3be546606462794c
    md5: 69f37bdf340be2ff078663211f7d6619
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 15bebd2eed2f1418be986409656b65b0
    md5: 968c6150139d7a66ec64d4f6950f7b98
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 847039dc8b58e7279c2cee0b80edae8b
    md5: 20615ca1ef13e3594513c0d694be338c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2c244911a062cb3a73862a18fd61930c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_solo.res
  hashes:
    binhash: dd4117590a75ba288f1ec15a649da1d5
    md5: 54774cc23acd44de3dbd5445434b7a7c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e545894d72d4e116698fd09ccd513d0a
    md5: c4ea841f5af675f981a5c8ff9b663cb7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 81046e23a0cdefec0d2cff8136e76ad7
    md5: 21a56f0bfa4467274be83072c6795573
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_tracer.res
  hashes:
    binhash: 1fff516b895f936d804533dc6767ae89
    md5: 8a0b94739e5cb01184558670d9df3cf8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a4751dd5ad10c1ffde8e530eb1fb34c4
    md5: 78082e4caac216184128dc9090bbe47f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 92f06ba3eae69c329ad24aa614cd7472
    md5: 78bed992be56624be22efd6e76b3723b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9915c18116b48bd5edd3d129f08f0197
    md5: dfba7216cceeab27553a83d44e321947
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart366/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: eba1c0f0cc0ba2120943e477d6c4e29d
    md5: 53a6908f35eea212d6c0204e7e144225
