format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/atmosphere/restart_dump.astart
  hashes:
    binhash: 9518a8b84a2d77d6149fdc2f56752eb9
    md5: fd030da7c5637137f2e78a1191122b7d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/atmosphere/um.res.yaml
  hashes:
    binhash: 56beec56d114c15fcb51def318a4cf31
    md5: 781d0abab552311691a22b7a67a51e3b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/coupler/a2i.nc
  hashes:
    binhash: 4f89af06b5784dd339ee794481ca2d08
    md5: 6b8628e0f9144743f8119b5f4eb25e18
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/coupler/i2a.nc
  hashes:
    binhash: 7e98af99f38ff5f5db89cc73e824e96f
    md5: e9d13ec1ec2046b95416c3dab46ccf22
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/coupler/o2i.nc
  hashes:
    binhash: f121c0018f1b0ab3e97e50faafada5fb
    md5: 8a2ef057f4bdb51f4339e8e2afd6f222
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ice/cice_in.nml
  hashes:
    binhash: c12d15b165b11ee635688c5bb5564144
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ice/ice.restart_file
  hashes:
    binhash: a33123c6ea43cabb06c5bf25a1ab32b5
    md5: fa651a4918c10df19466c785a8a14944
work/ice/RESTART/iced.1304-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ice/iced.1304-01-01-00000.nc
  hashes:
    binhash: b6991483d23c189afbcb16606bdf3c89
    md5: 768ffd12e7aff7712674c5f1c0bf00a2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ice/mice.nc
  hashes:
    binhash: 3f79b13dbf62c5b9034ad5bc5b967e45
    md5: bede29136ce18ceb2abfda88fbf035e3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_age.res.nc
  hashes:
    binhash: 0c9c5d02269c0d45863e8f2c415f3d73
    md5: c72a8a27b3e05b313e59dc209205e48a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ccce119a06713b56020d74972ae104d0
    md5: 77fc6b4efc918eea2ddd004b31aa4dd6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6a567b3bf23313d7d0fdafea7a192de9
    md5: 6afb788c250e9a1f39381cd92fcf0d0b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_density.res.nc
  hashes:
    binhash: fa479fd767c4dc82dac9901ca708c774
    md5: 68efbcb20cf90c6e9167f2d8c5a053d9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4c7f689931e607447744c37166bd6329
    md5: faeba56a17696aa4a24d3663e3c68c8d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1c67c6869d4a8ffc494d2e7ec44ed411
    md5: d4d3bf14b022ad630167ddac88e44139
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 623e9c78ee8b2b0d4aea71395802bc05
    md5: ad7352723eb04a808fcab2c546725d06
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a3df97e08a2fc52d1cf1845d0806db07
    md5: a93ddad925bd2963825bde3e737345d4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_sbc.res.nc
  hashes:
    binhash: eed77820499e9acaf85d83c598f63352
    md5: decac42e2ea6698eb9644767c329c43e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2511550b151bbbe39e097152040925e4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_solo.res
  hashes:
    binhash: 4ba5f452663a33a13e188875581a6969
    md5: c1896c26d32d9bb98d2fa602bac5ebc5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8a10940f955cd927f336f75819d7618b
    md5: afdcf17db262217a42ac05a693c1af4e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9d1a1c82e544756cbe675315397d7120
    md5: ae11f175abadcfe09329eb1fe4b1ff01
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_tracer.res
  hashes:
    binhash: 4f177e261c28bf2d460df6670bc09b8e
    md5: ac3745683afb0fa27cd3529882fd94b4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e057a707ed19fb7399f4997df4dc0066
    md5: bb083b199e53c35dbc0141675ca2ba3d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7530da17e86cdc61267a6b5357ae5dbd
    md5: 60910646a8436b442e0a440180f1823b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4ce3f622d92a6dbd1f34433e439158d4
    md5: 977e588c6c48ec7bb9953a418676b360
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart420/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a2e130b667b904a32c2ed948ff70d56a
    md5: a03ac6e9f028146e17efa7f525cf97b1
