format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/atmosphere/restart_dump.astart
  hashes:
    binhash: 297a1ba7218581b0183a13cc6259add0
    md5: ee212b33a657136d855129a73f9ecd1c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/atmosphere/um.res.yaml
  hashes:
    binhash: 11329b2635f9a366954a740a48ea8a7f
    md5: 01cfffdc04d8aab992ceb9a1e2ebbd7e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/coupler/a2i.nc
  hashes:
    binhash: a71f5cee282e1248298bf002087f8911
    md5: e0581213a7c836fbe72f21e422349f42
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/coupler/i2a.nc
  hashes:
    binhash: d1e1b8fe9dc616939f3b1d9310987c5d
    md5: 45f33a69dc78306b7c09587c7b74f38c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/coupler/o2i.nc
  hashes:
    binhash: 646e262b004a56b5df19eb1d3a9c7fb6
    md5: d1f918bceeb371af3f31f67095013949
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ice/cice_in.nml
  hashes:
    binhash: 957c6465bbc43d40ae520106055c0c0b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ice/ice.restart_file
  hashes:
    binhash: 88fa3e0a171ade569e6a9d25d2835047
    md5: 197e0f005ddd4c61107d458f8dcd62d5
work/ice/RESTART/iced.0903-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ice/iced.0903-01-01-00000.nc
  hashes:
    binhash: febc6e6826566763804e14e40e695e17
    md5: b81bf0e3d1282be26818aaa34e6714eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ice/mice.nc
  hashes:
    binhash: 7dd635ec963246694987ea7b4c3d77e7
    md5: 5e953a8031c3b578781f69ec87831517
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_age.res.nc
  hashes:
    binhash: 89d4abf61524e8629b87d32c2eaf025b
    md5: 09a25a7e3cbfb972e97a3bb6a767602b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 464b4efb152d0e14ec63bf295036502b
    md5: a911ce5e79d6e52f5720877e4a95347a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0103a0ac91153ec216c9aa6e1680ce47
    md5: e90eb8f25f71124c4ff8a9b25c8ab3f6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_density.res.nc
  hashes:
    binhash: eb630f9f40e732f63219d9e50bdcadbb
    md5: 1ae716b96e267dd33df5320c8161514c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c5853e697c61071bd1ee111fb35060cc
    md5: cace416a0bf61576f77a55cb04507551
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c18a82ca3bf43522bdcf495b3d9986b4
    md5: c4ff99bb429cb3e7ec4c28b66f4cd4d9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d6c02e1847a80d087c131cb967784f6e
    md5: 078c47433bfb2839d4f847709971d58d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4bcd122d484a92f4721cc811a4e76947
    md5: 8e3bdc488fd63ad73990c157e4d380a5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9340b5d970490cc1b91737e87dd6d6e9
    md5: 74860d9f135a1ba88c4668ea0050a8cb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6515b5436e0076d955cba8cfcfddbda7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_solo.res
  hashes:
    binhash: 8c488f211188f7a7f05a76ce5692aa87
    md5: c51602c7b7164e1fddb4a23c9a49b525
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bec6647850bb2674a9b68b564499942f
    md5: cca285d9cf3be846b5ffc933b68e781c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a4b22092b58ccb92254c6edf1b89e66d
    md5: 9d99e066dfc085d74112076b374ac150
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_tracer.res
  hashes:
    binhash: 6f92deb193fb23d725ae135977386721
    md5: af2a3c4cddca03dbc3c2472576960b9d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 22498826b1b4f6deee2defcfc2a74003
    md5: e350d6ae6563ea1808bf6b7344beb0d1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 85d13203c9bd602dc7367aa1da765e96
    md5: 9c29cbe513894aac9d6f3b1a9b923d2d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 99602e955c83ca7e37253763d276ccd9
    md5: 18c5700d6f72cfeeeb9e9900c1b800bf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart349/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1c08afa010d902705e396025fda9f3a7
    md5: bd5a187cc0752850402df63dee5e429e
