format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/atmosphere/restart_dump.astart
  hashes:
    binhash: 85f2aeebdeab5b6b3465df5f5aace24c
    md5: 75db6731de67065f3808c8352011e382
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/atmosphere/um.res.yaml
  hashes:
    binhash: 0c8cbdf796416d0ec515aa56efeb884e
    md5: b117442b8a25131c58f413aa8bd5131e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/coupler/a2i.nc
  hashes:
    binhash: 3de6af3bd535be53b455b9a53712f9e7
    md5: 9cc5d56dab2fe20626920091ec4e6ecd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/coupler/i2a.nc
  hashes:
    binhash: f8fa7d3b922be9bdd68c38b9169c5660
    md5: 14377a9bb86c672439d83cde6cf75f8b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/coupler/o2i.nc
  hashes:
    binhash: 42d9e2e4d41fc86fb2b2b647b4288621
    md5: 57f9a10635661a9d036f2d726396a8be
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ice/cice_in.nml
  hashes:
    binhash: 1812cd11771a3c5cb549503436ab1df6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ice/ice.restart_file
  hashes:
    binhash: f97b3a8d21847ab757fc7928138d6e3c
    md5: a4840a0630536a227031a790c1306811
work/ice/RESTART/iced.0936-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ice/iced.0936-01-01-00000.nc
  hashes:
    binhash: bb6aa4c9e3b56af90cbaeaa25805d2a0
    md5: d9bfa5d2f9cb51cc256b3a9175acd3fb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ice/mice.nc
  hashes:
    binhash: 0b9b71c1e751a9f37250159907a97e3f
    md5: 5e74c4338dceffcf1ffb85ecc1b73e23
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_age.res.nc
  hashes:
    binhash: 2c47b78437b368ba4ebcbb518e967b46
    md5: c27e4d42452a3678fca4254a3d78f174
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cc4028377cd4fe2025d83ca400c16419
    md5: 99776f8694b0a520efcc262b7fd973a4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9ad410949bc04b1b26651bd6c23df1c1
    md5: a3375e9287db4bbd9a6a823f86f1bb1c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_density.res.nc
  hashes:
    binhash: d407c249a7bd99d88a5d395ece706478
    md5: 085db555364843ab52b47744d7d86386
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3102e1aea42ce59ec279e1c792790a3d
    md5: 9e33efbc2ba4606ba654283dcf9e0bc0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3b7d045bcc66667c68611a11fc93f465
    md5: 29890f2787feccb97f8907989944e61a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 79ae0a3f4f96dc3df4921b320b883886
    md5: d787dfbf9826c4b20a62c1f0ba1dfb4b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 741fe156ba614b99ac6e07a9095ff152
    md5: ea38a0eb3281e1880ce9eafb100b4892
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cfb80f21ab541e9de54cefbf69524f90
    md5: 2436d341f7ec80fae694b30fdcbbff73
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0782c8fad11a6c75a80e1ab29c389c78
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_solo.res
  hashes:
    binhash: 2a4d9be943be2b1a537e574818f9686b
    md5: a8b8bc0573e80206f77ab895e0b86a2c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 50d8e9b63d6daeee26a7f1eaed9bce43
    md5: 666cc8a2551388a942eee1bf4d62e525
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5f5e6e4173603435257394444bf0dfeb
    md5: b2eec54a52c27d1ca367d89d02bffbe1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_tracer.res
  hashes:
    binhash: 4201d8daa2e63c0ea2ba2d978390fd56
    md5: ae8c154efdece4b75e22dfb394fc14f7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5c8341218e42e91867253e4fc8bf4660
    md5: 050840c54fba3eed9ac3f76d8b07359f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 521cecf6074cf793e9ee98a116becaec
    md5: a852f292f2f3d2064ce45eec53549525
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a75ffe022c73f5d5c11f18ee0762fd21
    md5: 607b4418c7ee56468389a5875814d4ac
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart382/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ecaf56debbf4bc8988e26dda92a095b1
    md5: a4310d406d37584759127b5266423db8
