format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/atmosphere/restart_dump.astart
  hashes:
    binhash: a2ee04e2a3c21ae3930362af9904213b
    md5: 328953e53cdb25736bc0f95e1ebb43d7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/atmosphere/um.res.yaml
  hashes:
    binhash: dc34c4c7479f2abade38687d657164dc
    md5: 99b44b045b881a91fb0d1f5bffd86571
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/coupler/a2i.nc
  hashes:
    binhash: 35f1e94fa8eb91146de8babaa2d0c961
    md5: b6137884f5efce7e9d78f82a5422f3c1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/coupler/i2a.nc
  hashes:
    binhash: e5ee588c25453df1e5d77d34e6efef7d
    md5: 1d6cdfd5f1c5aed424c3a97bdf4f63f0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/coupler/o2i.nc
  hashes:
    binhash: 4be8e467723a97f824fcd4e81977da64
    md5: daed584416f426e4bd14694befa16d4b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ice/cice_in.nml
  hashes:
    binhash: ad711c4877852cde2840dfd9a6670fe8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ice/ice.restart_file
  hashes:
    binhash: 4c3de72eb4724aaa43796ac02e295aff
    md5: 9d17fa5b80a28d792ab33287acc98cb1
work/ice/RESTART/iced.1196-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ice/iced.1196-01-01-00000.nc
  hashes:
    binhash: 5e900ad61b3cfd71c5e195ba414c7ca4
    md5: 09672463f0d2443bebc4d4285b2d92b2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ice/mice.nc
  hashes:
    binhash: 13872d821e6f1fa8979ae2d59ea9a3d0
    md5: 0c380a0c8b072e50e03b77b5e5775301
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_age.res.nc
  hashes:
    binhash: 36483ce940f069e873947d0c891739c4
    md5: 5b82ec27a655f6cae783394a0de2e4fe
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e03ccecb31577b5d4833face2a168188
    md5: f2e8839d76dd671d42950ca19e74613b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 628203f5b3f33d442a0c9ed8a7cc5bf0
    md5: 939c731e9a1a9788af61b0c83c10479e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_density.res.nc
  hashes:
    binhash: 5a6ef74692447baf2cb8b5b698012959
    md5: a69e9726ae7adfe343e3bd8f4d29430d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d8e4f6d6bda9cfb48d51baf6fdebc443
    md5: 2c37b946c90ea9a86e509e2c7cd73f9f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 387599b2cb0b3732c0858c3d43bd4a04
    md5: 5e5f59c3ab0a98203ffc3b1d472198f9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e21c9ef557695579c68d898ee1fb696
    md5: d37acda7425eb0235279a07346a9303c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 445eee9df56ae47339456900fe42b518
    md5: bb7e9dbf44ccd94e77e7c5e59fadb0d6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a911d20645e14dabeb88dea965c6592d
    md5: 8529895d00e2ee997149c2c36fa9d3d9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2e8c8cb298fe4e52805ad7140945939f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_solo.res
  hashes:
    binhash: fbd616043a197fc8d097f0339809d17e
    md5: 6150d829d6cdfb7f742a2a45123387de
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ef07bbd57bfd7a28bd03a4737193c5e9
    md5: 7a482c281cf53ce702d83480bb9ff3a6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ff7844cbbc080dd70a0811c2fe6bc2b3
    md5: 4e85a6e20ab8feb58c0f958ee7862f8e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_tracer.res
  hashes:
    binhash: 6211ed94b7ac2dcfec6ffa419c9b1417
    md5: 42e9440e4f706ecf6dfc14ac1ef4c451
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c74326535dd295c08c17c83a0b0ddcb7
    md5: 36cf886e60d5f7875e64844e070d61b7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 67af7aef056c6ab6ceaac07e10fba892
    md5: 9145335f756f09558ea7a39a9de5f349
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 288d69037826e058b5cafe6e546382e6
    md5: 401f143921f5660341478f60a0e6241d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart312/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 886009b708e54d1fabf03f072a362596
    md5: 78dd57b7f321909adc8475fe8aa2f41a
