format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/atmosphere/restart_dump.astart
  hashes:
    binhash: e08320b9caa03670a083169f0d761e2c
    md5: ac9f1414c7546fd8ccf7f6f35a3d0acb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/atmosphere/um.res.yaml
  hashes:
    binhash: ff9ee841a76ec2e75ef1e6ef06f7f004
    md5: 41d14a9c56244eb3a8151c929ef77ba6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/coupler/a2i.nc
  hashes:
    binhash: b9d20a710a5b0cf31bc8cea108de344f
    md5: 524b9b61e5b9f27438f7a53cfcaa263c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/coupler/i2a.nc
  hashes:
    binhash: c250af86031106b25fb6bade53df8aed
    md5: fe315a006c1ad110b3e054bba183a6af
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/coupler/o2i.nc
  hashes:
    binhash: ac8e4f5ee9b235c8182f4686d0d3e78a
    md5: 76f7016b28e84502e47c57fa76fd46b9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ice/cice_in.nml
  hashes:
    binhash: e3183ff7c7f4a578f7b10caf3bbcca7d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ice/ice.restart_file
  hashes:
    binhash: f1afbfde064e611aa18c6f204e1f98eb
    md5: 7641ce5de48e54dfdb38037faa2961c9
work/ice/RESTART/iced.1711-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ice/iced.1711-01-01-00000.nc
  hashes:
    binhash: 8a1d9dc15059054ac2a18b55c1da3337
    md5: b2a4f031de218a7261042d56cdfa8e2a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ice/mice.nc
  hashes:
    binhash: 43dd440941bf612722bf4f672c4f3ab2
    md5: 214862f7edf1df23351ab95bbb12eee0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_age.res.nc
  hashes:
    binhash: 7c5a95768ac3a3cc30f986e017177f93
    md5: f79133810c03e2993dda4f706ff228fa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 923e9bb6404101eae66d8a5c38c15daf
    md5: 4796bb9bc9d5b0db183195d7f08fdd84
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fde181288ea81103161918240cf8d7ed
    md5: 34e76e7dd474411789153e144e4da035
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_density.res.nc
  hashes:
    binhash: 2fe3eb19393e9d40ab2223776e95b635
    md5: 20051e4fa6b5ad8b5c3ca133c9ef2c96
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 363706ce37fb380a63ba30d09bbb4472
    md5: c1638ca981185263d43a563d202cd175
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aba5d1b47fe3b5f7e15a9f5ded7b6b4f
    md5: 2c8ef44c9932a955bb417b53ee1de2ff
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57bde05d1b2c35cd3a5568a190235c93
    md5: 67d7648a3aed24beca8f1b774004f363
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eeb7beda31be31008348a16708d0bb8f
    md5: 7c7e9ec52695854761a93b58018a74cb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 55cfc503d136d43e4db2cbbb25fb5229
    md5: d5c875aa64974d830f654b52d3c96343
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b542368e455a93e17cce732e8bb04d30
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_solo.res
  hashes:
    binhash: b08beb814248efeab46ed5dfa61cea94
    md5: ffd1c73709d98ebf0159d908d1018e1d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d0d42472b8f433cd0cbbe698595e1813
    md5: b36963689df75a99a95618f14c1df702
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7c13e805e5cd8daac74c0d43daa541d8
    md5: 631ea0a2aaf6fe5e1c1cb46aa60b01db
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_tracer.res
  hashes:
    binhash: ef3e97ebe189b00c977e58896d9b4938
    md5: 2c5b88836c3d88d1fdb1f64bd5f4dc77
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 52391bd18f35de7461ab925e4ff081d5
    md5: acfd62418c30435eb4571c7da9b25c4d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 68de9fa8e3d18c7c5edd24865c9a182b
    md5: b620fabf2ec52cd6eab606acf1ae965c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 77ae3636e63c724ac1b81521391444d0
    md5: a2de30e7645b3de1447ab43b6f383c6e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart266/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9538cfa178a4dc5b302de512e21dc941
    md5: 0ced9272c2d5f9758c9c4e0fadc9ed62
