format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/atmosphere/restart_dump.astart
  hashes:
    binhash: 8f344d846f79d8dd0705a460a3a993c2
    md5: 24918564dfb375b2432c8fa0a9bd85cb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/atmosphere/um.res.yaml
  hashes:
    binhash: 57a4e5622d71c5e2dee8010dcf8354a2
    md5: 8207bc0c7378538b3a02a0aa27eabf62
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/coupler/a2i.nc
  hashes:
    binhash: b94cd1c07ff7c6392f1eaae10ffc9643
    md5: 492c9350dcc6ce89ed2750c4b66476b4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/coupler/i2a.nc
  hashes:
    binhash: c12a05e808190bf547589124378cb7ac
    md5: 7d4fe0eb22521c52252714651f50b3ed
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/coupler/o2i.nc
  hashes:
    binhash: 99557562e2f16a00d81263911e64cef4
    md5: fad9e4ed492e80e773110fd9d1dd862a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ice/cice_in.nml
  hashes:
    binhash: 232479ba6c17a26b622285a1c178e896
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ice/ice.restart_file
  hashes:
    binhash: 331c277860c9e27183f95de0248f58b0
    md5: d8ae8f2bb6f80c1b2083b0c76e93317f
work/ice/RESTART/iced.0959-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ice/iced.0959-01-01-00000.nc
  hashes:
    binhash: d8df0061b2d4bc763823d10c1a5c0fe3
    md5: b54d779e6fe29766a85b552f293c6e29
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ice/mice.nc
  hashes:
    binhash: ec0d1ccc04748d3aeacfa2d84a939298
    md5: 306607044325b817cd250ae2bf6c5885
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_age.res.nc
  hashes:
    binhash: 77b6f6eade264ffefd97041c27e76573
    md5: f2c20205468069a043c7f6694d6b5146
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 68be20188f48dfe4a3ff0a66772f4240
    md5: 70b7531fbf4e19685e7bad5edef36710
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2a185fa7c8c3fe989396e629053a9e6b
    md5: e933b9cfd8492be9f5f279a5cd3c9347
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_density.res.nc
  hashes:
    binhash: d82716d1b85754666a0f7099b6e2367f
    md5: 00df91768241b60729733dc348b8912c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3e2a7bc2fccc1f8020f3d71714ee5263
    md5: 694e183cb262d4372936b5efc32c5346
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ac0ea62ca087125b53e2f6f6d5366223
    md5: 140f8a012d006962498b9eafd16e26f6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6815d3c6656e31550fbedc5df2ab864f
    md5: dc5c1f41fad9d9c849649a7451d5e76f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: df8eb516330cd5f65fe39d8348a6091d
    md5: 64412fed9e5bf4ab5334ffe24c552651
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9723cfa391c56670f7bdefe110f563f
    md5: 1c35ef1289c4759931edb7c87495c6e1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 86c1220e816455fa153c1bbf8e4728aa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_solo.res
  hashes:
    binhash: d9a32cee7975a72d246ffa6ba783df05
    md5: eb4a806395013dc0799236c921d59ccb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f1bc99ab83f8a919c00d46e22316537b
    md5: 83837590edd8b268e3161c2462bea960
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4d2352e78449629560eba7372ee3da54
    md5: 0d9037fed580388a66c77764481bd0df
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_tracer.res
  hashes:
    binhash: b2253cefb2ae05f91e7949c039bdcf0e
    md5: 350404d8f0870d3890b49da27ad0f777
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5f0690204028bc05ee7a7f804344e229
    md5: 65f2cd8d52e8e45a5777dab81b430a97
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fe1efcc942132b2b7dc5543e14f63062
    md5: b0ec25a24a70d5029d88ce69b8683f82
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2f041061e2f8b2062c680d9e10be1757
    md5: f800bb6a0dfe86f6b670156ed2528e3b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart405/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 976e744f27f5338193c353a88c49e5c8
    md5: 300b8ab53eba7fcd55ae657a9ac27e66
