format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/atmosphere/restart_dump.astart
  hashes:
    binhash: 35b2867cea865bf9a302fec0b5c12b29
    md5: 7a6e54c76ddbb3c4ad677b0adf8df55c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/atmosphere/um.res.yaml
  hashes:
    binhash: 3e51128bbd20a12d02642ae7b9a96bc6
    md5: 25cc7a7eb927c1f0afaf61539005b47d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/coupler/a2i.nc
  hashes:
    binhash: 3b12bd204bd3e14c8fb3f57225f502b5
    md5: 70f2be65446b8724ae1da98f4b7fe256
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/coupler/i2a.nc
  hashes:
    binhash: b971c7be36cd831a8db8b60246f4e83d
    md5: 338968e2ca2d0081a2edac406722a8fa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/coupler/o2i.nc
  hashes:
    binhash: 506dce15f514c05dcf548fef17fa30d4
    md5: 0a2b13db50cfe835d0f58e5db9021fd3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ice/cice_in.nml
  hashes:
    binhash: c7e2917518d51a52248fea34452dd69e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ice/ice.restart_file
  hashes:
    binhash: 9100b19ab64ceb5fc140842645f00fe8
    md5: 6ad79283126df19f2e8850afcfd864e8
work/ice/RESTART/iced.0889-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ice/iced.0889-01-01-00000.nc
  hashes:
    binhash: d1953366298fd6e198d657a93c629f32
    md5: 85cc9718e28d6109e5c532d9d4ec4340
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ice/mice.nc
  hashes:
    binhash: 502a0ebcfb3625988dd4988388afe232
    md5: bbd2dcae6d6565e3ddc4fda13e78a070
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_age.res.nc
  hashes:
    binhash: 833f6e69a551ea8e7bdb5464d3d418e1
    md5: 2afc22b619b2a20e76305adcb12d8614
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4c7401d8d858718964c0e1beebc4004e
    md5: 587299a8d3ae588c948c586cc336e2e3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2dff204180fe3119c3083bc6f9fd91af
    md5: ab3d85d70390d00fe44105fc559cbb7f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_density.res.nc
  hashes:
    binhash: 1ed6bd41e78af808faf023bdb8307021
    md5: c963a4cb3f3c720748f454e9ef14452a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c30ce847fe39138d338d7419d03692df
    md5: f5381cc1e5dcbe91702387561c392a2e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 92d289e845d92889c0ca5671ddab23c9
    md5: 21333ffec227ddad706e9430e06bd7ca
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f7f7ff5da1397fc4ef146ea58456b423
    md5: 3ed92db309b2db4ab0426aa326370878
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5ae39d24cb261e73139699fa9fca8da6
    md5: 14d2f0eae5769a6c7145136156157afa
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8830ef3db6642076b69db47ebb16438b
    md5: 54f575c1a6f92fd484b5d5e8de76b124
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c4039271a0a2853743c5261357ceb23b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_solo.res
  hashes:
    binhash: 533efbcba5454af28cc26de204b7fae6
    md5: 5fbcd8ac3c1acacc42e62ed7de189793
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0975d145c4c44ab23b605a76a7d7cd1b
    md5: d4cf69053c6dcb060edba77173828190
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3faa8e5597e7e77498f889ec8b199380
    md5: b122702f290891b2a8353f333fcdfb99
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_tracer.res
  hashes:
    binhash: a24a734e9ea3916de06d90c7c438ac78
    md5: 94d4d0d2c071587cc4c10acbf42a0e00
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d58fd572582ba8535d65114c7ea17494
    md5: f4be4d028640a14583fa4554969fff0f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ee074fa60237d56cd94dcccf93c6cfe4
    md5: 63986c4210a1323d83b8b5c1453efc32
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4592d3ce1087b8b0889493b337f11072
    md5: 0ccc31593035ab7a8706fa7536dff6ab
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart335/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2801e542feb460ba2d2b222a3fb2ad46
    md5: 6d319fce11b1693f59d09d268b182cd3
