format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/atmosphere/restart_dump.astart
  hashes:
    binhash: 9d3f1fb2b8be2778b76a98282a84da16
    md5: 09037a131ee28dee2176eea71041f1a8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/atmosphere/um.res.yaml
  hashes:
    binhash: 9a04dd767bd06943bbed70217f8fde36
    md5: b6131ae658e11c44b4b014748a93a919
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/coupler/a2i.nc
  hashes:
    binhash: fbc4ac993016dd1b8b631ed845d25317
    md5: 7d3fb13d319da0d6f2594c86cfb24ffc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/coupler/i2a.nc
  hashes:
    binhash: 9dda6a45243c485994260046b9641986
    md5: 42da575989b7f27af1af06537e8ee643
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/coupler/o2i.nc
  hashes:
    binhash: ef18ac63b197a48d41633087bd7603c1
    md5: b1ea75afe502c7bf9f1f191991f30b0e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ice/cice_in.nml
  hashes:
    binhash: ce444cf66a376081430814fef5077c37
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ice/ice.restart_file
  hashes:
    binhash: 2429b669f79110383668564659518aa2
    md5: 41c3f709b5c9445baea5582b39a05646
work/ice/RESTART/iced.1801-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ice/iced.1801-01-01-00000.nc
  hashes:
    binhash: c95bdacc9755e4d2467ee8e8678ba632
    md5: 791f3bb4aaf00966a1f3d61373546fc0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ice/mice.nc
  hashes:
    binhash: f4af50c86f6cf71715005fafce9b1007
    md5: ecbeb201eb06fa57b7de3d62be4f358d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_age.res.nc
  hashes:
    binhash: bf7f9dffd1527778a273fb22a1c8fdb1
    md5: 4f48fdc29bfd74003d89c6eb0974f8a7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 23f18a7c59b0a60f956bc3115f2b33ff
    md5: 6adc83189dc7183e32c97891801a1591
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7f2eef2f380d4b8beca3bdb4766d4917
    md5: 7b853da474f936bdf27359286b5e0f19
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_density.res.nc
  hashes:
    binhash: 41c06370997064b2291fe9fc518fcddb
    md5: f3e61ec5e3585eae6f07d431d5a44279
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4ffb0bb122707de9ebf13091356185f9
    md5: 29f10e34b037b7a18d13398372866fad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 335744849dc5d7f068f013a8c1ab7cac
    md5: 9e0b28c3c00d06adaae59f76f78a4974
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 55c0913b7f775343b2552d96318cc28b
    md5: 3dc3a1d3069136c10926c58d841be0c3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 965b876b255e8c7dcc9cf734a89edd05
    md5: fba9d026dc715e059aa68c9246208ba9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bc520dd15ff88edb86a198c931532690
    md5: 714f41f5e028daec4ceaabe0a8f8acb7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a5259298e71bbbad0ef9c282a30b3a2d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_solo.res
  hashes:
    binhash: 35cc36fd0d96efba6f444c9170df921c
    md5: d25cca5205be7c800e1b53dae97d130c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d0f7b2c46fa2da5ada6aaaa4da8c243b
    md5: 3b2c022933a74f8299758b459b55f546
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3af7d7eef66715a89c05c7a76000ee67
    md5: 22457e855eeffb5a3c9f5aecf9304fbe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_tracer.res
  hashes:
    binhash: bb7755de4f8243f23d0e9de5618f4cfd
    md5: 8636e51df4a85d4e3e4b7f4caed1977f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 14c85b1aaa3604603d860fddc569ec81
    md5: d1d041d359a1ed08fbd6a29e9595bb48
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f496f38d9a7a74e1da124d951bd2a8bc
    md5: 9c3e2697414d0e1675c601569cef319d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4c6860579e42612ae808a64c10a6b585
    md5: a5f13871da177bf26e964ea54a958b50
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart356/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f9c530912c47c7e06e1638192c7f196f
    md5: bc70c0925564fcc5d7b4020ef0879367
