format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/atmosphere/restart_dump.astart
  hashes:
    binhash: 560497bebe1a7c1d7c0c881127e3c10a
    md5: c943272a21e4ae3e07cbe62b40b371e5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/atmosphere/um.res.yaml
  hashes:
    binhash: 02622a87ed56bccd0c6a4a8a7f333230
    md5: d347d178ee0985b5ff531f1610a5d66d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/coupler/a2i.nc
  hashes:
    binhash: b69de53d7fc32ffd18c6e2803c896a11
    md5: b586395656d1bbe497d99623c4a1f59c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/coupler/i2a.nc
  hashes:
    binhash: 76aa6b4eeefc6992b8d9635c910d6daa
    md5: dc632c9fb728a6bb86194af670b7c781
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/coupler/o2i.nc
  hashes:
    binhash: d91613a778228a01278ff14e66400084
    md5: 0ec6c36044441fdd22bdc875edb5b3dd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ice/cice_in.nml
  hashes:
    binhash: 7bf5bb4a6bcd1e1ec85e6f42c2e3eb18
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ice/ice.restart_file
  hashes:
    binhash: 1814f33775e70d512761c12df011e6d3
    md5: e3b1d8cb6086360d103b9e8018c2bb2b
work/ice/RESTART/iced.0965-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ice/iced.0965-01-01-00000.nc
  hashes:
    binhash: e01f894b216cd0511263d2a91104baf8
    md5: 6efe942d47ee55fb05bff92d462f23cb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ice/mice.nc
  hashes:
    binhash: e78ea9ceec55c62cbd7a5c8a9cde81bd
    md5: ffc2971bc0fa23b5f7afc92043a15c71
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_age.res.nc
  hashes:
    binhash: 54e0283054c68fd2a741b63c29875000
    md5: 1e03ab800e4277e36cecdac866f8f39e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3398c4e71f1e1a5db66d8babd7a3058b
    md5: 79a4d5aea281c263baedda3b324ca280
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 63efc4a5faa50a6166c506b5daff8c06
    md5: 006bebdc83f45ae1a95f07279e285161
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_density.res.nc
  hashes:
    binhash: b26c5cd8975011516ee8898bd06bde87
    md5: 816f85f917e123225edf2614f69d718f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f466ea140940a3e01bc3a8ca799a3927
    md5: 0dde1375b0cdf0ca1b1dc814ace00f03
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0a3c2bd4ffa023f8e1c02658ec31eba8
    md5: 3c1eba30cc1f876b8ae0b0439d5c240f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 41eaa081f95f04818028e6e62398f74c
    md5: 8bd0b89fd97928918516f87d199abbba
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cb67d6258c793b8de0701d5d4635717b
    md5: d84a9b17e4fb8631523fd567e1179007
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a06c034a29510cc04d16a1bfc54d2d51
    md5: d55bd1ac47b469988fd51a881dd6a435
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3178985f0ff4ab4e823d8f927a86a593
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_solo.res
  hashes:
    binhash: 75968ebf988f8164415b476711ac91e9
    md5: 4476c508fa1de7ba8bac348fe3bc8b11
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 20b15d60a1f7ee6bd9b632876b2e5cd8
    md5: 6dd4d81a7e9b9a6667f70f43d4e7acc2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d53f5ea3d1b76fb5283c3271b3844c70
    md5: a8c330fb2f6d9c3604cf0b21ae10975f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_tracer.res
  hashes:
    binhash: 987acc5207809cb3cf2b80bdb9c0efa3
    md5: d127c24fcebea198500cb148c7de8ddb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ac55a27fbaad865d27fd9645cff29ce4
    md5: 9a474ae7293052b91e13471574ca03dd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 643a72e9be93a67e51e43312c39d47ab
    md5: 3648d8e1928d876e270903861c82687c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 14d104eb45de2c5a329a764da97cc3d2
    md5: 387c19c9ff4947e46c96fab79f3337e9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart411/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 455954bfa8cfb8b48446a240525a1818
    md5: 609e86d449cc8d00e22f79d28b8237dd
