format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/atmosphere/restart_dump.astart
  hashes:
    binhash: d46f5f4a464c2290bc7aa08ca39424a1
    md5: 7f9413e60836e56e9945ec915480311b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/atmosphere/um.res.yaml
  hashes:
    binhash: 9e3ac50e0546288b2905b04fb341c68f
    md5: d2989b12216ac4bb42df4116bd090b82
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/coupler/a2i.nc
  hashes:
    binhash: b9253d4c0a93dfa97900f73ba2ee077a
    md5: 13085f17d98109260b784d0b3ec5328d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/coupler/i2a.nc
  hashes:
    binhash: 9e30dfd2e69bc39d67eba97289647e33
    md5: 9ff9d3bd516c798b00b19ea01b9601a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/coupler/o2i.nc
  hashes:
    binhash: 5b5770332edd0fc8a3c7661c7cfec0f8
    md5: 69170278826723bff44cd8a9d1c18f95
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ice/cice_in.nml
  hashes:
    binhash: 8ebc5f9a90011f78769612c9fcc5f5f9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ice/ice.restart_file
  hashes:
    binhash: 4a125cc21f52127b8d04e5d297ab6ab7
    md5: e2361149a53ded73dcc368335cfc5462
work/ice/RESTART/iced.0848-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ice/iced.0848-01-01-00000.nc
  hashes:
    binhash: 5fb5835883071aa8e2013bfe93f76854
    md5: bc2717d61deb2cc0e69a6a2ff25d99a3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ice/mice.nc
  hashes:
    binhash: 07cdfa5e52039e358068a9bb4090d120
    md5: 80232721ef785728c71fcc4ec40591bc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_age.res.nc
  hashes:
    binhash: aa27f7c7632cef90918cf519e4bccfb2
    md5: 881fec992f99e5c4572cdf258c13a9dd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e19752ed500cf49c4ae16f9ac826c342
    md5: 4d6b0dbaf30d113225da53483e086c9d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6d550025f04e518032089a5ba430bc38
    md5: 4e777d1243a016becaa39a4cbdf399df
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_density.res.nc
  hashes:
    binhash: de3c15b36b7b2b30de5b38aae64b9cc8
    md5: 76c41b8cbd7006d432e48080af2d9b02
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ce79c316587d79ff79d5a39fb84e1325
    md5: 98ef4f68f2df801ea06177923d5aa7c2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6b350726e5e7f27c7c0e4fb434b2c473
    md5: 326d2ae0b1f01ed99aed363d37322f51
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 081f77c8ea927918489dac775a9dd315
    md5: 378eb253e28d9a8f698e15845a30b2f7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1ee533c6205e227632a9ee02c77a0d1c
    md5: 5dec04cfcb1fb7dab7a9b7d422f90006
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a45bed789d519a8ca4eb1e8751a172db
    md5: df97be0474ddd8945a7ce28907f9b73b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a16595de6bc0ce85662076dc28e03093
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_solo.res
  hashes:
    binhash: 0778f03fb88b15d2a167518d9cc42a3e
    md5: 8ce04c1621d42d2afbef1ff1e739403f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 45fc9fab79e8a4350e8cad0e3980199a
    md5: a00668cb0ab1618c48261ec3dd1dfd55
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 58db026f08ea6db22dc291902bcdace6
    md5: b1e15313d1bfdf852b5ec13dae5db28d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_tracer.res
  hashes:
    binhash: bbd4dccc6a1d3dd64974edad9c16c432
    md5: d5b5614af165edea85398d83304d6e4d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b0b781a7581c68b30b85b31d17732388
    md5: 6bf110162c3fffaa2272befabdffaa1e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9be38c0e3bdc3df10a9853badc1e819e
    md5: 788ec4ebff6fd149522e667cd12dee04
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 19d0b1e9276f2a4c431c55fc1fb0116d
    md5: 6268b5eb41931d4b54fa1554c23697d5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart294/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f22272520129500a8ff97034a6e20bc8
    md5: df798b042d41c5c3a8416f87c77e761c
