format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/atmosphere/restart_dump.astart
  hashes:
    binhash: 317ff3d3f9db7fb27cdcc80847aa9a1e
    md5: 13809b4a95d21fb32dcc9aaca2e4d128
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/atmosphere/um.res.yaml
  hashes:
    binhash: 4aaa39b6f0d9b4d6f0734b5aa34183e3
    md5: 4da68b0ee9239b82d7dca40286fda170
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/coupler/a2i.nc
  hashes:
    binhash: e6e2ac46b2ddeec87b96a9091ccfb9f1
    md5: e8d9ec7ce419924adcb0a0f719d5a2ed
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/coupler/i2a.nc
  hashes:
    binhash: 38d9cd5d9f100e67769e8c6b7a13d607
    md5: f14e706641ca624ebcf693e52db5ba7c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/coupler/o2i.nc
  hashes:
    binhash: 2c18878f48f89735e23ac5ec71dfd51a
    md5: 47dde7ad6c94b4c7b4181fd664e83795
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ice/cice_in.nml
  hashes:
    binhash: d522ee9061eb9811f4caea9d71e8d5c4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ice/ice.restart_file
  hashes:
    binhash: 5360d5cd9ea1a1b51538b87e6b806532
    md5: 6311e8d7b542eab2a030df7bff5c54a5
work/ice/RESTART/iced.0849-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ice/iced.0849-01-01-00000.nc
  hashes:
    binhash: 897c9118c0f7a18696954c059ffe6315
    md5: c93182957732ba7a9f0a6bb5dfc2f774
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ice/mice.nc
  hashes:
    binhash: 5b531236e7458585803608ec9e8380f4
    md5: d3b6733faa74f5782bc55b6346d029b4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_age.res.nc
  hashes:
    binhash: d44791c00ac90664242ebc199b91ebd9
    md5: fd0a5595afcf9552f2e676bb4da308d0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1e388e5c0b371d954533963672b7bcd5
    md5: 05b3dc3f920b147e766e0d5ad5398a51
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3d55703d4da15e494a2c12d10212812b
    md5: 82834c194c0790f22bcc06c51edf4ee8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_density.res.nc
  hashes:
    binhash: 51d7c06486be63d6acce49fb029ff1e1
    md5: 9a3365013a867d19f30ea234d83d0cfa
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ef1b86503708eff7f7cbce8575d3daa2
    md5: 3ac7cd3d906f442a2ab7fdb943e4b7fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f7da072bde4a75c25d1eacf5445b920f
    md5: 5f9ee7e633fbaa72315207a0cbf33887
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d632b2de8aa5526b6d80e8ed933c7f66
    md5: fd00291786b28c9ac55ec5a1a4593af2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f5b56646d3e1f55449ed6d56fba68312
    md5: 0c191bc694c65030025ceb0bcdfdaad5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1e4b5a21d1119959ec8163bf7179f803
    md5: 45fb21da10af53a7b31c5297fc03f375
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7cc30d0baaf240479738c5274c471a49
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_solo.res
  hashes:
    binhash: 9870e1cd3d084c5659c8d3c3a6a4ebf8
    md5: 2ef3a0f8e50e63f2d669315cbc9109fe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 205f8a678a3dd9cd1bef7a2506a7f1a8
    md5: 284924def9c3d644bf270c0e4ddad65f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 36cc6bbb80fbf505126a4cea205b2d8f
    md5: aa8c63ba3ac390f179c7359e71186864
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_tracer.res
  hashes:
    binhash: ba3673bb5de6169487addadf64479f3d
    md5: 8415e05acd5b3d7a0b1a2bd17a996e4b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 23b92a4d10ac0af5d32e67df7e1dd0c7
    md5: 6505fed87572af87a2b257aa78ec1960
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a811f7988b93b3b1cacaf40ce755b345
    md5: e6497487771276988dcba9fe05d78970
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8670683ddde9851881c7007ff61f7537
    md5: efd3a02dfd52526421565aa575bddeb2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart295/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2730ba150bdbbe677b8d424f006f3933
    md5: 3614637b832700ebf1ecacd44d1e1b0b
