format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/atmosphere/restart_dump.astart
  hashes:
    binhash: 8001544032ba4780423b81ad3fe37e7e
    md5: de0fad63e3efeb240c55fb506788981e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/atmosphere/um.res.yaml
  hashes:
    binhash: 79c80cb0d4431fbbd7f9b7d00f1f564c
    md5: a716527d18de93625e06fab4a6cb44a2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/coupler/a2i.nc
  hashes:
    binhash: 63a9c598bc269843eb77105fe05b08a1
    md5: a3cbb63ee7ec85ab46f6e838e1a93dd7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/coupler/i2a.nc
  hashes:
    binhash: ec39d2581e6cdb9ba0908aa6fbedc8b9
    md5: 1788075af5c73b78ea5ef3895e2f249a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/coupler/o2i.nc
  hashes:
    binhash: 8dff6f50152fb8b997d7ff5a634c76db
    md5: b62164e21b5ad87266157e63576c023a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ice/cice_in.nml
  hashes:
    binhash: a564c1bf8683f4dd608a32cf0af447e6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ice/ice.restart_file
  hashes:
    binhash: 39f73d71ce7d5847fca14538217974e5
    md5: 59e62ec15ce8f66d54118da4cfe46ccc
work/ice/RESTART/iced.1158-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ice/iced.1158-01-01-00000.nc
  hashes:
    binhash: 2b2e17659d3ae699a71fc2ef2f78ab57
    md5: 9af32d67797cb7edd6b76fcfc14b1356
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ice/mice.nc
  hashes:
    binhash: 0f4bbc924bc8d5038b1f66e4722229f7
    md5: 92370084f6955bfd6f0f5153bdfa7fa5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_age.res.nc
  hashes:
    binhash: a41e293326cfd408065a665df8565109
    md5: 30f32c506e40833072c298092746ca22
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3a6c2533518aac6ba0fdee3d89d24366
    md5: db965e46ccddee4f04e6f9fa5f9dd3cc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8aa044ea683f72495382e69371345063
    md5: 29ecd256543d78df3fa07c6459a5e9fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_density.res.nc
  hashes:
    binhash: 86b7c47a791079dba7b13445b4f104b5
    md5: d96998cb7b724a0c5c8b5aad957be4e7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 627bb4d451f5d4995e7f8396b84a61f9
    md5: 18d55f06245a075b880f8b924d31f996
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c318c5f31b535d0a6475c8b9e30410c
    md5: 00e95fb1e147402f51c8c01fef309c96
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2b44e094b68ddaffba6d3e72c916a149
    md5: 3ac5ea79d1b00656b5f0616b7c2a0d41
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 33bd98d3edc6f6a315762d2f654db3d3
    md5: cbc3cf4eb17eeb92f8dfddb2126b133b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c73948be30383c62506eda7cc747ec52
    md5: 4280cc76facc22d05e80c35bacc6aaaf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 79370b3a497f75f29b9b20d9e3213c60
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_solo.res
  hashes:
    binhash: 4ab4eb89049b6e6135812011ec978a31
    md5: 413ffc1bab6294a29c10506842bb2ba2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a93fa204f80b803c776d67758f462b17
    md5: 11c92a40fe1d11222b86b00de3701564
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5f28115b4334e994d83321bbd88b7104
    md5: ab87552c690e6e0b0fdb68f01665a888
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_tracer.res
  hashes:
    binhash: 7b77408eca916a95c8224cdfb5437744
    md5: 930d8c6fd0b68284a44340d53aa8fb6f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 505b77c36c24f827d6a8c9ab5d67d4eb
    md5: b602719d2e4946da812ba4f03d5a9b3f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b94d2e4746fa07e29f7b00f4067170e8
    md5: e9f4a330e345a96d1c090658a51ace30
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e9604c1b51bed8098a33296baeff770d
    md5: 2b787b3a0c70e689e6c4cece6a58759c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart274/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 748e04022b18f882e017b6ff7290062c
    md5: 7a4a68029e394ddaa68bcafe9df15d87
