format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/atmosphere/restart_dump.astart
  hashes:
    binhash: 19f48c5fc4d2a078b50cab123d27a8ca
    md5: 1b2ff39a19e39674b5fc78038449b668
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/atmosphere/um.res.yaml
  hashes:
    binhash: deeffe9d0a531a96a93e9bef228c5b15
    md5: 263cea3d8259f8827ba07bdbc75d061b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/coupler/a2i.nc
  hashes:
    binhash: 1cd990896aa76063987b43771d34bf4a
    md5: 2f911bcd5729dcd55d23842c0dd93916
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/coupler/i2a.nc
  hashes:
    binhash: 70193880c62dfe0d4e3042ad62ef04ea
    md5: 6d4b0bae888598f612d4c095ac4b1d89
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/coupler/o2i.nc
  hashes:
    binhash: eaba8c1bd60ba4940d32c4cd0662d1c0
    md5: 6b2b0d1b53a8f91b1cd3079cb9a1b9e6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ice/cice_in.nml
  hashes:
    binhash: e474c9114a50d07059464e7723ed5a51
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ice/ice.restart_file
  hashes:
    binhash: 1ad31091e72d7c118ec2bf531dacd2dc
    md5: e5065431afa1fc127c858b2cf995057a
work/ice/RESTART/iced.0952-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ice/iced.0952-01-01-00000.nc
  hashes:
    binhash: 98f9e6364c25919f02227243717e871d
    md5: b00efa5ecee0a0ab20b7b4ada762669e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ice/mice.nc
  hashes:
    binhash: f4e1d52d67bb080ad9eccef526eef868
    md5: 402411c88484a136ce3045d1dade3600
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_age.res.nc
  hashes:
    binhash: d96c6f13b7e6a28a6b545dec718e52ac
    md5: 0d2213fadfc17547c3a333dfa4c16cf8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b6d2b3b32f3199983d2f7be6802f56ef
    md5: 427bd8ffa2f7ef29b920de8010983719
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2af23f147eedea6dea1c64c7e01300bd
    md5: 99253e13c91f69b7b7f248371d943e27
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_density.res.nc
  hashes:
    binhash: f8c65bbb638b337693face0e841e0001
    md5: 54d22cbf883c904b86ea869d5097f271
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 74e2fb067460e5248196566d1b66cc84
    md5: f22c44d612b8b5dfdbf9f2b6a83bfd94
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a92963d3ac8ed32fb650368daa5c1ac9
    md5: e978cda3bd88d35382d7fb2a52edad56
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e661363fa22e23279891b8eb19add25b
    md5: 7148320d0f68a4992778f19a00488c61
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 29f04f75d06ec4415a778362979f53ed
    md5: 16be2f08843188f68c287529a88664a8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6f339ee297c5f867a11494d73295fdfb
    md5: eb5e03908d9521b51a225eb25bf3a4c6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 96033bdd9da00b14f0c2cb448ae428bd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_solo.res
  hashes:
    binhash: e53b799ddc7febe6d97ded627e3c33a1
    md5: 938409b7749dd51d5d69a5e3c210d41f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7a4a05ef051b5a2f706667af0a384e9c
    md5: ca1bac1b63ff8b22c5c2d60ff8f873c2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 279ee3e880b5cbafcc83627442eefc59
    md5: c1d143f90536e0b3dcf6ec3972ef98e5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_tracer.res
  hashes:
    binhash: 2522cf0a1e97d2ed42be4949488de4c0
    md5: 5038308c964ffc9b1050fc8aa7064b8a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 21100320ce6da6768bd5895fbe014fd5
    md5: add47baf8088c2e1eebb580590398c97
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a2145d183e8358d4446330a1ff724c9c
    md5: 78000e5ffaf0d3a60f853a88417dcb4a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cd425c2275c21f6f8d8b773890fb778f
    md5: d9fb7881d17dced2a5dc94c2fe24a977
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart398/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: be1e2789832eee98aee3e09658da7cd4
    md5: 2324bfed6d0654700531ebf424825a53
