format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/atmosphere/restart_dump.astart
  hashes:
    binhash: 7d5b95e4f948777a20e36fe1a1045abc
    md5: 50a57ebfcef93d7b2d0a9830224fd624
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/atmosphere/um.res.yaml
  hashes:
    binhash: 3e2259bec8d5c207525d7cbfe91d43b0
    md5: 362474cf684869024b8b771d88c8df29
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/coupler/a2i.nc
  hashes:
    binhash: ac7b3be275ec2bb183b1932ce42b740e
    md5: bf4f180f71c3927a6d30d0f94fbfd125
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/coupler/i2a.nc
  hashes:
    binhash: 9f40fd534dd8b563ae0fd8b1d1c0c263
    md5: ebe158ca11dbceb42fc522f7e43963d8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/coupler/o2i.nc
  hashes:
    binhash: 117bf114d107a36ea5a7fc8ff6d7f6fe
    md5: 1912bce3ab77bc1861c844b486c62e01
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ice/cice_in.nml
  hashes:
    binhash: 628a570aabbf5ff32d43833b0b49e66a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ice/ice.restart_file
  hashes:
    binhash: d5373804391d3ea0e6437de0fe8ff58b
    md5: b322ff72c43e7c5b3b62a552af24cea9
work/ice/RESTART/iced.1731-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ice/iced.1731-01-01-00000.nc
  hashes:
    binhash: a1e8d8b8773c1281af188ee55503cdf3
    md5: a0e6a6e5b6f571c854f67b4bd8385c34
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ice/mice.nc
  hashes:
    binhash: 86e67725416b920a6f040884b548dd5c
    md5: de06e2b270cf3bec8f87773669a7d08b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_age.res.nc
  hashes:
    binhash: e3d4ad73708a4b7b6a81c935189c3686
    md5: e201d5bb136294820de647a462cfa87f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 09386f5b673a7ee040554a38f0b55c3f
    md5: 831a58ca4ed0d8fc3756a3eaedef57f3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c4977d97a853cadb748a12cb0b9596b3
    md5: 34761538ba381af8ca0a4b1d73bc8040
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_density.res.nc
  hashes:
    binhash: 32e1f97e9076a67e1bf572542608fad7
    md5: c95e3d2a7b0671d60f54867810e39fa2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 606b46347fca3f24bd741d75c2af7484
    md5: 222acfd69c5c033c0d393d8407c17cdf
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b14294c594be3ceb1dcfecf1ba7c5ebf
    md5: da2afa32109390a1bf7c9a6d94b37c63
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b9bc6466c05c2f7cf7ce15da8287d2f9
    md5: 89b0ff7992f858268a2e21d9fc83268c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eef7ef17747c245311095e2b2eb5987a
    md5: d0e8266bb469c8bde7e55ea53736fcd7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 99608df5a4d4a89a7338c005a5deffde
    md5: 6331c6cc4402fc02a784fd8638c1cd1e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a8fae09c9c42dd2465f09c1a208ca5eb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_solo.res
  hashes:
    binhash: 1b5084138ce0a8ad26d99fed210df121
    md5: 60e421c1b9b4d550798f75c6dd44ac01
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2bd877adca5b12b92aa9847b1fd9dd57
    md5: 606c5fd260fdd2480772ddecb8257330
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 117b58d59861db7e9d55dde120d77613
    md5: e8a74d42f0bde722854bd41b44dbaaa9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_tracer.res
  hashes:
    binhash: 2e464020fa20b05441b57ad58524e5ff
    md5: 849e08668928d1fc538a305df72dd3e4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 09268c0358fc357ff40bbb2a9252e089
    md5: 42bcf63593493748c48452f1f35d4212
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d9f9d8c9a2b6a0341732ab4eab0891d7
    md5: fa6d6800190935967eeecf7f4a06a4c4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 384a9aab089a82c53e8d47b185771fef
    md5: abdea3a81248c213943281887758aec2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart286/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fd47f4464cf1e161adb586842f2cc9fa
    md5: 53a183c452c1878832702545ca4872cc
