format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b2b1d0785789e29299c5f19c797f3db
    md5: f2a69ca30eac1ed2a30295490d527cd0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/atmosphere/um.res.yaml
  hashes:
    binhash: 91a883c495de44391482b6e135e4ae6d
    md5: 963e6637f30794554e0c74086f8eedc7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/coupler/a2i.nc
  hashes:
    binhash: ecacec2e8ca19826b7bd694880c2446a
    md5: c8302fab455b9aadb2bedd7345b9e8ca
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/coupler/i2a.nc
  hashes:
    binhash: 082126d4cdaf20dda5facb4c93161e71
    md5: 2bd9c8bd13374466cc173a1af1889662
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/coupler/o2i.nc
  hashes:
    binhash: 8f41a8d231121126aeff8e7d7a9d2e6a
    md5: a6f04dd77ff52547077bc997eaf5e22d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ice/cice_in.nml
  hashes:
    binhash: d2a690ed37fef50759173aaa44ac1ace
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ice/ice.restart_file
  hashes:
    binhash: 87c82ea3e7cd77d7451f634c71e94d59
    md5: a34d581e6d469ac0e97bafb278bec9ad
work/ice/RESTART/iced.1179-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ice/iced.1179-01-01-00000.nc
  hashes:
    binhash: 8738c2d6ceba22eba2f350e67b1224b5
    md5: d6624c19a1d7c271836263124ec725a1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ice/mice.nc
  hashes:
    binhash: 3c301fb7b503d652ebb0da344e9a9cdb
    md5: 055b6fda90592ecc8fee55a9255007fa
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_age.res.nc
  hashes:
    binhash: 1897c242344cc7c1803275ea3eae750c
    md5: 53858c4318132ecd16b150c47cfb8ec3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 63e691e6fd65c79aaee8870b7ee6d1c3
    md5: e2110bfd2784e05c685dddc0b2425c56
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 98645d9e78284611e3faf44cc65e308b
    md5: 45ae2da70dd6ce8eea67c1cc60c7c10c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_density.res.nc
  hashes:
    binhash: a21b4f1d92f5cc2cb24e64654f8bad3d
    md5: 8c44ac932e737440d33fc9c15e67a968
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 79d851e0623892db70e1e0e39ed44081
    md5: b6b88dfd800abb214d587b2c63e459a8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5a67f7e5b7b971eded861e2bbc4379f6
    md5: e3ab7014b0ea552fc18daa19f02673ed
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e9f585c62d69a1448b1368f8d98180e0
    md5: 896ed4f2fc283479bdf79a76c90c0bfd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6ec7069f0ccecd8bab9da1ad631e6e5b
    md5: 305cadc7423ceb95470e8a6c3fb58a94
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 755a09b7657944e435ebe973f88dbf69
    md5: 82ab71d54222e3c733549d37f2e50c13
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a3b25b4a03209462c1a7a1c640700dd9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_solo.res
  hashes:
    binhash: 64161dfd0abdd0759b074df0b6253f50
    md5: cb23881f3d5b8f77a1c2f0e531553a5f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1202a2b563fdd625f36641af7028aee3
    md5: 9f7399f0802bdd76b2db817f454b9874
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_thickness.res.nc
  hashes:
    binhash: deddd9c8b7b779ddde03a172353e0bc5
    md5: 10fbb4d30204645b680bce56b653479e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_tracer.res
  hashes:
    binhash: 79fc14730c85c953566d4ebdcf96b18b
    md5: 8e2613aa360c22e8fcb8a512f8c035d6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4b126d68208bbe14780817806ef99d2c
    md5: e02b32d0af2972379b0d320ebb84d487
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a1a90c62444f50e561ab3d59ff18c5c9
    md5: fe6fc05d7c7901d27688a0c0f3ca9510
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5dd39fdc869c9ad88d65aee5559458b1
    md5: 430f64efcff0bac28a09b5e439dd3cfb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart295/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 217cd3de442e2066492a20e09cd4176d
    md5: e0e90cc42297e6c1821c4d52f2cb87c5
