format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/atmosphere/restart_dump.astart
  hashes:
    binhash: 89bb21d933730c14cdc8180800484b88
    md5: 90f084833fb8295a4c9ee939a94733fa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/atmosphere/um.res.yaml
  hashes:
    binhash: d8091e3adb68d8903e8b5c1c521258d3
    md5: 545e2e55ec92caed3a7a4fed25230653
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/coupler/a2i.nc
  hashes:
    binhash: df63f1c8edd09775a0afa694c6bd5c4d
    md5: 19d0c0c67c5dc8e330efb1b5fe49351e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/coupler/i2a.nc
  hashes:
    binhash: 52d0483e8810135b08a3c82e14541822
    md5: 9c2ea72cc78dbaf493c7aaf9922f451c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/coupler/o2i.nc
  hashes:
    binhash: 2d6096b613ff40e4b1ec64be2739c913
    md5: bcfeb721808faac9617a437021ec88db
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ice/cice_in.nml
  hashes:
    binhash: 4d0d41818050c4d4ba69c33bbd707bd3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ice/ice.restart_file
  hashes:
    binhash: 0e3f287dad7f0cfe4977d868389850b2
    md5: 95b90d150506fa28c13bdbb90c86e924
work/ice/RESTART/iced.1844-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ice/iced.1844-01-01-00000.nc
  hashes:
    binhash: 679ae4bc51aec260362e2b9903a0c75a
    md5: 6e369d2b87718da3b94710af2ff277a1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ice/mice.nc
  hashes:
    binhash: fa750e77cf9ce5e55d0523fd0b513119
    md5: 0bd79537a55e8caabdf0f5ed9cb7df08
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_age.res.nc
  hashes:
    binhash: 847aaccfde9c7ba44fcb613d73623659
    md5: f87e18b9f1bbdfb22cce083b7b1b7d49
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f3170368fa9ff65fdd12bbba1340f14
    md5: 1c5398a3445601dcebff54fa998fc963
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cc7f4d1b850605f8eb6dedda781aed04
    md5: 8199848021893c547c77e8acb182d694
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_density.res.nc
  hashes:
    binhash: b431cb5732e43a3fb3b58a6309078295
    md5: e38012e1661edfbff16bc24486755ffd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5ad45ed32f078dc40e39bd703e9059d0
    md5: bf2460495468eb1605e1590acd8c3138
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 763a3058e720a48b3776bfb3fcc69fa3
    md5: 6b86ca19f8f5777971b6214ecb1c575e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 94a7fdacba0ab2e2c8891e698c3e5f5b
    md5: f72c777be3a5e9d69256215106eaa699
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d151bb66f3f43d93ac87fcd28c7ddbca
    md5: 3fbb98389d73156f64cdad8edc460e55
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 99e900c145f402cf9fc730bac91acfa6
    md5: dae2b1dee30372cd2ff17f0326e864aa
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ac2cce9fd700829934d677a1efb63a7d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_solo.res
  hashes:
    binhash: 007a14957206e24f6c796e1bddc2cfe8
    md5: b9eb8532b33a93c1bff661a2aea4affd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ec22f32e2dd64a973bb5554fe40ad504
    md5: 72c1da22fd7dc8c67dcc72ad6a23db27
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 70c9e1857fc8699c0d056ce902c3b300
    md5: 7c2b0dca99020e84c06ff25f8fb8c5e8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_tracer.res
  hashes:
    binhash: 8f7f44a49fe39373b2c2a88e97f5d789
    md5: 71c6b299117347b2934ecc266a08bc9b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8ee861f7cdcf4e9a9ffdbce380d2c5b0
    md5: 0d280cb38004c3e408f44f81dde9627c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1afc3acc4947b9baf715b3df71729c3c
    md5: a102cd73a09bc8abf76b4d3d1bdd62bd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1cda962582fb41a30691168516f3b937
    md5: d10ef004691b642cd2d3c1eac3aedb5a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart399/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ceee79e735f0f6c486ec0a1ef77d1c61
    md5: 2499d8f232b6196bbbbba1342c944a44
