format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/atmosphere/restart_dump.astart
  hashes:
    binhash: a1f24cd2bbb819bc098a70761a94952c
    md5: f554d5573976698670bbe49f4edf3d97
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/atmosphere/um.res.yaml
  hashes:
    binhash: 108898a3468af1ba96c676877515cbb6
    md5: d1e6869e6ff7095449b3c2df4e1e9a12
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/coupler/a2i.nc
  hashes:
    binhash: f10c360d6fcf3d2357f4e65b0b9dbe5c
    md5: 1ba5a98469db1c92c0bd9c994df004d2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/coupler/i2a.nc
  hashes:
    binhash: f4c5a09f18abe2112fd1eae056a38758
    md5: b908495d7f27da6c0a53aaa5d1613f73
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/coupler/o2i.nc
  hashes:
    binhash: acbf1218408df0c9bb1b6f2f1c73bfdf
    md5: 8ead12605238a201129d17844f1a6032
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ice/cice_in.nml
  hashes:
    binhash: f01205de33b1dbfb60a903e28a597883
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ice/ice.restart_file
  hashes:
    binhash: e43b4c4ba54dcc36d3a648f15628c8f5
    md5: 20e23b224b0fd0362d50e2e0fe256984
work/ice/RESTART/iced.1749-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ice/iced.1749-01-01-00000.nc
  hashes:
    binhash: bcc140b88946f9cf8708bdfc06087be4
    md5: 7a7ee98c8e2655d474a90f03e1f297d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ice/mice.nc
  hashes:
    binhash: 2c1ccacec58772c6b32905e781892c6b
    md5: acaaf6d5ae4166781e9d5b8efdf05d0d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_age.res.nc
  hashes:
    binhash: 05026d43b1b02d963bb897ab6e881bfa
    md5: 608941a2f63addc0fa981e38fcd852d5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2a744e8a679522cc4a40fb8e8500ba90
    md5: 78fdb36097dcdac4d358e923d335883c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 55869d6ad74bdc9b3e1e39152f7fba4b
    md5: 1690ef18bf3d1dda38ab54cd7f8b5587
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_density.res.nc
  hashes:
    binhash: 1d0b47761efb0bc6db8af584c2a22cc3
    md5: 67d9b6c651dd12ca8b04ad5cf7b4ae98
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 510d01d0c6fd6f542f6c3607d89a7f00
    md5: 9362d7eca3c6fe46476d6aef13ae36a1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bdaffcad650111bdda63ea4fe3fb41cb
    md5: 0c3c8f1005ec52fd190156a78c02d891
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 033312ce7ca264c55ac94c7b483cb105
    md5: 1c1b36f9397f6661db3c3d9b371d3ed0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 84ea10a14572ccf9d600abae383bb2ea
    md5: f6d5dc9d35a1fe91fbddec639d7fcca9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 859e8361fe3d630975e6c29cb02506db
    md5: c053f5bbbe0acf5d788a6441581f6e63
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 74c33e26541b65cb3f422e0df431c1d9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_solo.res
  hashes:
    binhash: 6983f09d166c61d5f4247920af39d096
    md5: 7bca860d54355edb0cfa27f1e55bb397
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6ad8ad15974b2b57c4effeaf47e46ad7
    md5: f1a872adee5f5304f491a34d1f27cfe5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7e646093798c6b5efec15f903606081e
    md5: 8cc6072da0fa42277ea119529d829eff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_tracer.res
  hashes:
    binhash: 3c803ef21ceec44d0cb837b2ee91bc89
    md5: 51f2fe2dd72bb3483502ebb3ee6d90d9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7a9580b6681029c7b6e66a5add4e45e4
    md5: bd2e8e4cda379e71266c14338a0345f2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 13d267901627a332e2faf1b559e866f8
    md5: e18e5b84eb2ab40c2c553ee6d56a25bc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bf8a9dd6a58213bcfbbbce7815f634b9
    md5: b91c8fbd94bd6d5e23e5e49278448edc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart304/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5966bdee94c4b667bb0b85b8d90836bc
    md5: 29490c30fb3ffcaf5e2dbdad4f9f5156
