format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/atmosphere/restart_dump.astart
  hashes:
    binhash: b0569e9b4a757c001e7777757cca1616
    md5: 1ae607970cffaf027b634566acca700a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/atmosphere/um.res.yaml
  hashes:
    binhash: 45cb3e47e3ebbc45cb8f7c176b4df890
    md5: 2662fea8904b589fc184774daef49c57
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/coupler/a2i.nc
  hashes:
    binhash: 7823eeb66a3138e6635f1ae4809c8437
    md5: 26311ebba2cc47bdd1aeee250faece55
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/coupler/i2a.nc
  hashes:
    binhash: 6e3530bec3471b5c5043d701a86271c6
    md5: 849c68f75a670ac67a0c373ef2105166
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/coupler/o2i.nc
  hashes:
    binhash: 62c57ecc776d1e1fa9cb9ec957a0a321
    md5: b60b088c0f4c46b13be28c4b9753838b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ice/cice_in.nml
  hashes:
    binhash: 5be632ca998ff47e919289354c34ae40
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ice/ice.restart_file
  hashes:
    binhash: bc1dd001491705bcceb4f4da4653d02d
    md5: a0e33aeec8d545d0cfc67e7a271e3e68
work/ice/RESTART/iced.1284-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ice/iced.1284-01-01-00000.nc
  hashes:
    binhash: e1ab5565c6c28223d96367b75a5765fd
    md5: dc81e15bf03a6558c9e6489a9febfdbe
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ice/mice.nc
  hashes:
    binhash: 39cc55bde672036d91dbd1551fb5e4bd
    md5: 2cfdc55800cbfca878a9d24ca2af80e3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_age.res.nc
  hashes:
    binhash: bb908d060ab38b0590d5ecb02bf1ea0b
    md5: c57c9fcdf2945b47b467c98a90e019cd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 851a4c32743130d3582801a974209726
    md5: 34b5f2f2be0eef83ba9e04515176e367
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cd308d254a28e844c8166d556e6264ee
    md5: 8227c9b4e6d606a3fde3834f21b51711
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_density.res.nc
  hashes:
    binhash: 58ecb0ccdd29266a3ef0e2d514ada203
    md5: 503b3d4aee08d443da669a24e449369d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 010ee6980cd1831f92734559a0bb6451
    md5: ebd3c959a126f9b9190a99f5d53e17d8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 53e6b82e2730dbd26155bcddee29c5c8
    md5: ba4fec80d174988dabc99934e20462d9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e3e2fc53a14f1f2fdb1551c9373f92e3
    md5: fe1be8d78fe17e4dc9d7936b6e678daa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 107e3f1738bc0609f95b917e93c67e0b
    md5: 94a8ffa61a57a7c1c4a6322f285ce6e4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7e965f2cdceb3a98d2bb607e6d9272c8
    md5: c232ff2722194b1b4151ba6cc376cec5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 74354eb127c043270300f1d876208e87
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_solo.res
  hashes:
    binhash: fcca5c0e3857343bf784ac58afe0c315
    md5: e58214f7de54b276a0c9b1c7f991320d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d5eb78ff4564eea38e26f1e3a024f7a1
    md5: 215b12584f0099cfac15b4f5cfdcd076
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 128933abf700261b3007799514502575
    md5: 208730a342774c2552835f8343695b46
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_tracer.res
  hashes:
    binhash: ed2c26e1ffad72214a82e81859363e2f
    md5: fb687f8b84c19b6fce22eb03868bb7a1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4ec0fcaeb8a8220771ae36d606483216
    md5: ecaa6231f7462baa055c2f23dfca3d43
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a812650c261a7ea501e9636e97719988
    md5: 0e95d767c72275af6027d8f8ed4ba629
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 11688017954c53f895efcb699f33f8c7
    md5: 7377dca233daa818a02b1ee7ecabf851
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart400/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 91a4322b817691c9303c0219bbc334ab
    md5: 6e068cb1e7305d523ec30511334167ab
