format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/atmosphere/restart_dump.astart
  hashes:
    binhash: 47df1ba075b418b33dda166b05f87f6c
    md5: 0098b58ace4a3368798f08176b8acf9a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/atmosphere/um.res.yaml
  hashes:
    binhash: 959705212d1c2b916ae0242e5db8b4f2
    md5: 68317968ab789dc040033545e0f3953d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/coupler/a2i.nc
  hashes:
    binhash: fe7bca3d7081fb751397fea78dae1cbb
    md5: 003c3682f72babc10fdce9b3614ef98e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/coupler/i2a.nc
  hashes:
    binhash: 43fbd1dbda1a63ee4fd06f497c45791a
    md5: 92a1d2aead4d510ee18ad8fce75323d2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/coupler/o2i.nc
  hashes:
    binhash: af19116a5b64e20ff6544c6c6447b8c5
    md5: f491a0c9cdaad2c2bfcae9014551db25
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ice/cice_in.nml
  hashes:
    binhash: 810e10648bf1ddf9acde6dd9c01c9b92
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ice/ice.restart_file
  hashes:
    binhash: 8d8cb12a5e5be525239dff28593cd617
    md5: 9204ab9badbf3c7ae394626fe8bb3496
work/ice/RESTART/iced.1737-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ice/iced.1737-01-01-00000.nc
  hashes:
    binhash: 9a919eaff34ae36a053417871ab33e5b
    md5: 78ebbb293feea8110f483fb7d5c69f3c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ice/mice.nc
  hashes:
    binhash: 531bc7b1547e521b40ee0d1cb774ee10
    md5: ba6385ee16482cc2b648f8ad69e81666
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_age.res.nc
  hashes:
    binhash: fad799b2dba433e6dd006c9d4cbe1d48
    md5: ab65480b4cc87de007132c00b28e7090
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 175cb317f3879eae815c90f71339e8fa
    md5: 0b5d42c85216fd3c8c297f1c36240da3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 16f8b49ccdacfba0c55b16817e69ea1c
    md5: 18397bebe6ab9c2460ff9a705e1e968f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_density.res.nc
  hashes:
    binhash: 69397158e38f8990c222a37f7636479f
    md5: 44ca7a1b9d26ad510a9653702b626213
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1775e506c2bb437e43944ed16077ca30
    md5: e227156039955e3c45e515f90ea42afe
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2565ab469e383aa8ce4817f6d7fb6b04
    md5: c8fe2cfbc688371bf5bdcf61e4b270bc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9cbacb2d1df8d1a99213e89bab61e99e
    md5: ae26b9e1cb626999fe8d34fe32b2d815
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 97952482afbd14c85c4d920279df53bf
    md5: d4c7fe4308d64fe8c324d5be63924165
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f7e2d4e4cf80a6caf72510e9784d8068
    md5: 3122707655f325610a4745a2d56ba63a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fcd9c8a8b3b95b2ebaf8003da201441f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_solo.res
  hashes:
    binhash: 706bffc9b3d0086a6a3ce15508e6bd92
    md5: cebc447f9c33106685b38bc5dce9317b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 476bb1496d92adab0274c4810ec23733
    md5: 72b34a7c48873b3eb5c4b1873c5944e1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 412614160e1e06ac4a5d6414d562780a
    md5: 21dd8f1b8bfb7142d10ab21c4e02339b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_tracer.res
  hashes:
    binhash: 8e8a5c22af0d5cc272bdc210c44a3385
    md5: 46b264f256408acc009b2226b094163c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ac7b616fafaa35cc98fbdf1d1f444c2
    md5: 09547dd0ec6071d1331577ca5882de29
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d5aa4c625bb6ac39e35d487481f36392
    md5: 5a43451fcbc01da26ac1da48c64d54a5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 72c2aa650787e9ec215eb371b09e09a4
    md5: af3726a8c12fbd5644a342c20cf80595
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart292/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 58a2d693f31c242cfe6952ea4a8d19e0
    md5: 2e6f62ab8924724a81f8e52bbae8fd22
