format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/atmosphere/restart_dump.astart
  hashes:
    binhash: df75d8ef33bf86cff4deba4ce624f111
    md5: 6581efc186d75128203a9419227a5b84
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/atmosphere/um.res.yaml
  hashes:
    binhash: 8d095d4e522f2f8c8ee856ae9f9adcae
    md5: 52c95516c947d4bf2101ba524e7eafcc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/coupler/a2i.nc
  hashes:
    binhash: caefe94193f676e925742b4b7b5c5105
    md5: 336fc98338373319c271ae1f620714fd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/coupler/i2a.nc
  hashes:
    binhash: 059174d934307eeb399464c150cdcac3
    md5: 71f4b1aee0bbfa28fc868be6b94487df
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/coupler/o2i.nc
  hashes:
    binhash: 7bd1a5008c49320590d75968a6678938
    md5: dd24b48b2e19f51babc2acba04d78404
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ice/cice_in.nml
  hashes:
    binhash: 2ff0a7077e5402af355a2e42d568aa77
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ice/ice.restart_file
  hashes:
    binhash: c4268b71e9e86dd678f9b2e3502cf73e
    md5: 83807af8996e6ef9b24259a190c1cf06
work/ice/RESTART/iced.1195-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ice/iced.1195-01-01-00000.nc
  hashes:
    binhash: 4b6704e89e67f5a2a9a08f915b9d7c82
    md5: 292689af53f49bef9709e6c818c4e663
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ice/mice.nc
  hashes:
    binhash: 38360ccf247180bb0d10a11c67480076
    md5: ed6c15ad13adc2e39cd157016c6aa32b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_age.res.nc
  hashes:
    binhash: 2175beb7452e08d3bd715275202c2fa8
    md5: 5f54b0484b0795870261163cec42101e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c48bef0d6996e9af1b996ef8cde34c16
    md5: bfb5a3d8568c4b68f715a2d134a6ce8b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f6e735679cbf516ed1e3e2fefeffe8ee
    md5: cdfccfebf0c1db41ee33c2ed51b80068
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_density.res.nc
  hashes:
    binhash: 5e0ed6a1634e4cb7d6f6c019fb477a3c
    md5: e71c2a4094acfbdae02cd9a41ed95fa7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6a6d49a914fc58a69017694ba5db767d
    md5: b6e56cb57a2fd0a5c71c0b3564e47dc6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b739120054113f56752a501c98655b30
    md5: 7a23211c895b63cc4262d4e6157a5840
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f66552df5a7c24d087793ef1dd05408b
    md5: 122a7d82847595833b7492b2e8bcb00f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0510d97f7085d4880e10fb065531f021
    md5: 6213986b6e5c8ec323823dcf4ed0cb6d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4a1d1603f1516176472347390e2d5148
    md5: c73844c030dd36295df5dc616d896c76
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 793f7f3091c0c2f0cac82e32fc1e5ae3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_solo.res
  hashes:
    binhash: 6e606db7d6c819dc61675158c6a71328
    md5: b66b9f9e4e5b9b023904229842aede85
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 40103911bdfb319b9c7a25fa00f143ad
    md5: e9ef3d0a44a17bd93c08096eab303aae
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9932d1a7d9517d8b99f4c712ef9ef415
    md5: 5e2e9082466aca888fd54c96a852cd50
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_tracer.res
  hashes:
    binhash: da2bdcc7ffcfc5fb252f4694457ed38d
    md5: 7ebc61edbbe41bac171647b3d0da33bc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd0722f6c258c9d6e60544c328eaabf0
    md5: 076daea2200db568c91f110e794d58ce
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5669698fa771edabdf1ec99b061ebf8c
    md5: c24f907b8d2b2aa4da30bc1cf7fad7d2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6643a7f4e62f90058945fc3494ec40fc
    md5: ca5e944929a912329ef57335ccc4d524
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart311/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6fd5e373a06a0484ac65d035a5cb73a5
    md5: 3d74480b8ccd711fee0783a370ebf8fc
