format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/atmosphere/restart_dump.astart
  hashes:
    binhash: 07d516f0cac7a848d616359f4a3046b1
    md5: 5d4278cff0340b6974a2df42ba055a72
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/atmosphere/um.res.yaml
  hashes:
    binhash: 6864cb32906bf85ee01e1baff9e3bcd7
    md5: 94abe2b0f9fe2c259134aed70fbcb9e3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/coupler/a2i.nc
  hashes:
    binhash: 8cb19cf5069cf6bd9821bf16fa418f10
    md5: 889ccedad8191ea6ccadb72fdd590f27
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/coupler/i2a.nc
  hashes:
    binhash: f04bae3698627bdcb00336e9029021c3
    md5: b11f2b228fc6fa2c6cd810ec238756ce
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/coupler/o2i.nc
  hashes:
    binhash: cefe6aadcccca4031c9f3b4b77581d33
    md5: bdc669aa2da8ab62a2ac683fd7ca627f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ice/cice_in.nml
  hashes:
    binhash: 10291970e875ae4b78e6aeed1df950b0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ice/ice.restart_file
  hashes:
    binhash: d39536380d5a96ea210b9408aba83830
    md5: ceb7ee079c257f29b048b6078541a341
work/ice/RESTART/iced.0876-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ice/iced.0876-01-01-00000.nc
  hashes:
    binhash: a1ddbf382746d989a010967d31adb5d3
    md5: cfbe6a57f51fe47ac6d357c42f1bc187
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ice/mice.nc
  hashes:
    binhash: f7b96bd8e029a1054d9a7751bedb90e2
    md5: fb48b0d6e7bc914a8d288cbb8b2727d8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_age.res.nc
  hashes:
    binhash: f2ff8872bbdcaa28f5264b7d185c846b
    md5: 3612ffe1b2e8096f6e65da35a4b736c4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c1ff4efc33b42843407e7289c186f4f6
    md5: b6830cb4e36738158cce73fbf8b86ec7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f20888fc380332f1da0d156e6b826f9f
    md5: b6fa3ad3a6260b8c5d7a56014c0f4b35
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_density.res.nc
  hashes:
    binhash: a4eb3f5813fd80acf810c98943bd4db1
    md5: 5935aad237318f2562fe854de9da5904
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a2468359037a43377ee2b071ae60a357
    md5: 8f1587d425c6f8623b979df56d6d153b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a5dd9e6a0307f18f21bad5e2b3f2cac6
    md5: af1e6237049e10cce5fbda4a22a71b2d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 22d0c2dc3878f6fc746232434138406c
    md5: 9661ad21682779ad8cee3ba7d29361e0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 99fb0d47b80424d27d035d93a78f964d
    md5: b0815111fb85bf0df00c6aedd8df2701
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6475780916fdb7e629880e2b1ea51b68
    md5: 01f74d516d7d9f8fd8e229e2b0bfb213
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a94bf017fb9c83412a6b97d3db41bf99
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_solo.res
  hashes:
    binhash: 4273793db74f12ee6ea34004908163be
    md5: 2ba81d80204929f8980b42c728f06f67
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7abe07482fb6a7374670427336b4f875
    md5: b366d3e703179216a8cf123c7f5c2468
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 761f5fd29fedbefce97b0f60394c8526
    md5: 06ef991c88f1e736e4c733f6e4c4755c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_tracer.res
  hashes:
    binhash: bbf233f72935b41ce48a7b60de08922b
    md5: 9eab0828b75d47e1679263ec01ea0b29
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ab1386bb708499d44df606ae3abda492
    md5: d1ca766ff0206fc6b47fe0dc5da14dc1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0b31b53d11a4eeac355a28bf7125fb17
    md5: c1931a4bfda90675a285001e6a969b1f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: afbe46f0fbd816bdfbfa8a59bd3828a4
    md5: eafa0fa866cd05d6d0df03e911c10e7e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart322/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 82b15c46b287895d3db84d81512948e2
    md5: b404c40420073a353494f57f6dbfb03a
