format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/atmosphere/restart_dump.astart
  hashes:
    binhash: d672caf1c1ad70d6ed9b08946ed25077
    md5: 4ffd673f82a0e6be1a4bea5cdf69317f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/atmosphere/um.res.yaml
  hashes:
    binhash: e4ce386a54ea9595bb8451a4be4562bf
    md5: b8092c14b3ea620e7bfef423c9c91d16
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/coupler/a2i.nc
  hashes:
    binhash: ec3129ec13f250efbd1d9d9b508bd3b1
    md5: 159936e06c2839dbd1bedc6fa72de621
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/coupler/i2a.nc
  hashes:
    binhash: c0c8cd8a867c647fdfc0e86a81f3c233
    md5: d756d167dc24312478981b3c82ae6d79
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/coupler/o2i.nc
  hashes:
    binhash: d967c8894aea9c0fc951f4b25938e68e
    md5: 8d15e0645ad9f97ded34863ac9cd5829
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ice/cice_in.nml
  hashes:
    binhash: a4e1c1d3d6cd2b558f9a9f529fc10dc2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ice/ice.restart_file
  hashes:
    binhash: 81d17ab1ffc249378bd3298de8935fab
    md5: f79b7e50303dafb952e2f583b5d429f5
work/ice/RESTART/iced.1241-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ice/iced.1241-01-01-00000.nc
  hashes:
    binhash: feead1695f6f738c905d9e8e9f1ba915
    md5: 014e6cf2615ade4c1006e84e6ea26099
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ice/mice.nc
  hashes:
    binhash: f72e37cde26bc7db532ea742ce07799e
    md5: d8d5f8027ab2635fb2f243fd3fa00537
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_age.res.nc
  hashes:
    binhash: 8239d11a126e0b028ad31b58297aa1f3
    md5: 1d0af2287b805ead2fb4889dfbec8e65
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ce1dc2996dc4a92eca9ffb84ff60df31
    md5: f11aebafe0fe41b54506a93fb25aecbf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 41923e5dba94bda329911d8aea8f0511
    md5: 673453b8a894d420c31866b35d28db43
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_density.res.nc
  hashes:
    binhash: 7eb961ebedaea4a6f67ce08d0ba334c7
    md5: c2e6ca0aef4f4cad58a7bffe4fdf988a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2941ec89d98aed5d6c8b8e5cce604d44
    md5: 358b0162b05e1f4e5bc54839b0b8a0d3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f105ed3818f36500d11902cfb0e88746
    md5: 4b9524feaa56dfe25324dbfb0e554307
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ce3518965656e87094c4f3b1fb13a449
    md5: e0e4d01192c9b33166ab69b8ec95afc2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2d57ee3964d34a659b094f2742cffda7
    md5: 2f5d6c4f4c793abe985477eaf528dcc9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ae26d3e4fb731ab7dc92442a94e4547a
    md5: e59bb428ea0eeaef3b6f878da8124f21
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a90e27e647d7bed58446b97bc08be1d0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_solo.res
  hashes:
    binhash: 7adb422105a810f980fa03a560e8cff6
    md5: 959b892d6a8fa71e3163d60aaafbbfe5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 419b50476370105b56429ccbe52b8dbb
    md5: e4f68ba93c53b39c610b882841e06e49
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dfe0abca64469889f89bc0848e8c232b
    md5: 6153e934a39ff718e554ceceed46e127
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_tracer.res
  hashes:
    binhash: 26dbdc4a55d4192ef0943353fb811ca4
    md5: 0b35d7fe956ef8057461478237951dd2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 10a26292bc867f853926d2c64edc0796
    md5: 2f7b47d71af4ae898745203987cfae68
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fc69d24c6142738d67d55e1cfee8b622
    md5: ff439dbf338efff8cbcd5edb1eefde42
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d489d4e5714daf2b1e0fedc32264115a
    md5: e4d9064ed3a03f5b02d5e8146a0ac51f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart357/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0b4139c47b2e2adcc60f6ee478e9ea36
    md5: ebfc32a79ef1c6358f19308a0c4f6d26
