format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/atmosphere/restart_dump.astart
  hashes:
    binhash: a78f2c063194b0780a51fb567e5f45e4
    md5: c575786c007a79eb2e7340931e5f2c08
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/atmosphere/um.res.yaml
  hashes:
    binhash: eb7a4504df824eb0f9bfaa7b87b6e419
    md5: 8ce5ffd5573e3bae1efd0db4313e7f09
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/coupler/a2i.nc
  hashes:
    binhash: 2739a82a8f6644cac744b1b424b07175
    md5: 8aa393382e2e3fcc1043dcfc0363264b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/coupler/i2a.nc
  hashes:
    binhash: d5234ace22ff0f5bb36c3e20f6d761ff
    md5: 984e62fbf53ba26112423aedf7e6e37b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/coupler/o2i.nc
  hashes:
    binhash: 215b55f3f3a292e4ff3ee0334cb795eb
    md5: 4dc31c0fb4f19129f32ad1468f1f7bcf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ice/cice_in.nml
  hashes:
    binhash: cf7670c939d27376a6eccf7583d232b2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ice/ice.restart_file
  hashes:
    binhash: 83a083fe3425b09a3be233fe4e6649c7
    md5: 32ed7237bf3bf55d500bba7628afa51a
work/ice/RESTART/iced.1289-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ice/iced.1289-01-01-00000.nc
  hashes:
    binhash: 8af46cd4cd2b9891cd8696f63f82d1a4
    md5: 529edc139f66240d01875cc6f1a9938b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ice/mice.nc
  hashes:
    binhash: b47a938ce3b52571218e9ebfcf0a1cf0
    md5: e8512610378718556bf058b71baee6bf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_age.res.nc
  hashes:
    binhash: fd25d2d22b00bc3ea3ff7a001356831c
    md5: 9b790fac0b20637ec3ff4057e19aa41b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9292cb4e8aec78543ff400c8fdd27693
    md5: 3f7f8f59a18ca5b084d13fbb45579ee8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e8227e606d57357cff4f0212715cc944
    md5: 7b2dad00131a8cba69441b80be6eac8d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_density.res.nc
  hashes:
    binhash: e3794269d77dbfa46aeeb301275a0ac7
    md5: fb8c5157526448e9e77f4681a22710f4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e169e4b180793dced1612337550bf860
    md5: 530ba93bac0f0b3ee98d43bcbcef8be4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 50a643028274d54c89f4b6e2b0f0f987
    md5: 18cbed73741ed45e91959eda2cadccb0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1a140283f604f0c4af3516fc322a1635
    md5: 209e83874d614149323bb3fda87f3607
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a0a73c9fe58e0446bca5ba9ae3178769
    md5: d578aa46c6bea2269da824dca2a7c6af
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8c80bd1565da1479d131d0e4e7a298f0
    md5: c36dc975fbe0e6860628740d8f3ae054
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2797c9f7a88e32d7c275930477aebbcc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_solo.res
  hashes:
    binhash: 13e3a5f2d5901f20560846495ef1c2ce
    md5: e96753d478a105e77ba55c0793f2700f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: be21efcf244a127d981a3f104b0c609d
    md5: 2d463e1618a7dfa48b7617c3c20361c7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5bf16be8daf668b4652f27af312fd0fb
    md5: b10a09a9aa6ae7d263ce442f0b9d9a1a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_tracer.res
  hashes:
    binhash: 84fa9ae3d70efe9d619e4985b8f98686
    md5: c02e969d70066e9756ad41bdf76f21d4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 089da7391a954ac893992d3c45ee8267
    md5: 00130b97e72a2baa3d00e88464261d2f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9d376ae390bd0639dbcf0d111a696dd3
    md5: 0f0c64e62a3a9ca896b57bbf706b410d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 67c02bee638203268edb9882232c40d4
    md5: 9815df0d2267268003e804e658d89e6a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart405/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f96c4d83465347450fcdb1b18aea9647
    md5: 841ad5464e7545c38098393e830be1d7
