format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/atmosphere/restart_dump.astart
  hashes:
    binhash: b287028cb79b413732791977427dcbee
    md5: 38b47309784c5765c23aba2f5f2ecaff
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/atmosphere/um.res.yaml
  hashes:
    binhash: 07795013cdb8c60410882ac1a4fe87ba
    md5: 08def25eaf76d7df062164ec2af6f878
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/coupler/a2i.nc
  hashes:
    binhash: 98bcf5602c7c6dbebcfa7b666bd9f6ac
    md5: 95b645627a061e26646969486d7b5390
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/coupler/i2a.nc
  hashes:
    binhash: 27410348135a4bedbea6cbfeb7b22e9d
    md5: 7b855f8cc782e37487acc130c3041b87
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/coupler/o2i.nc
  hashes:
    binhash: 4d8eb7728ff9390cf18d76d43e56f86f
    md5: 6d2c926d6cc8fc3603e24a4e54c41d86
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ice/cice_in.nml
  hashes:
    binhash: a5ab1847ac4342f7749d525bc3f073f6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ice/ice.restart_file
  hashes:
    binhash: 9dde1e874d3b98c79f99322a7b074905
    md5: f5b88397f8252e55431bedb0d22beb44
work/ice/RESTART/iced.1274-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ice/iced.1274-01-01-00000.nc
  hashes:
    binhash: 82d1f2af396e910c817f72f14712b91f
    md5: 07c561135abc8821262c612435b70586
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ice/mice.nc
  hashes:
    binhash: ea73b1de8d5476efa9150bc1cd111d5e
    md5: 0617609d7dc825836ce6d15396d17d8d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_age.res.nc
  hashes:
    binhash: cedbc2a5ce9bffd5635499cf57eb27f4
    md5: 3525648711063b4d2451828e0b070cc4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: af4bb2e69c698d0572fa156b91c25719
    md5: ab4dc0fad8c011a6299bc81222112050
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9952e4ed5a1ff360e9c187ee14c3cf46
    md5: 4e82cdf7ad5d731f5645f410ea50099f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_density.res.nc
  hashes:
    binhash: fe4746507ac6fd40cfeb4cd8fceaf31d
    md5: 1cad66791f183fe4e3da00bfb73453f7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b29c9921ed377fbd12c9f364e0fcbe1e
    md5: d9557d5d6de46f86cd30560607d47d8f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3b94422f692622c0930d52d4c17bc28a
    md5: 51c6feab144fa53441d32385ba02f239
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 27e4576ad2cdffe8ebc8fc47992fd0aa
    md5: 38a030dcbed3537c5fec270cdb43172e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 86e176377633a73afcca2b2b9e960c83
    md5: 5c996633bf801c716d1a19790832cd9b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3d8162a511f96579adf0bc64b86e038e
    md5: 903f73775c4bad03c829860ac284d0b3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7b839385eadf492d394c45a2c3690c5c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_solo.res
  hashes:
    binhash: f9339531f6a51eaa2d2643e808227ee8
    md5: 51b777fe56d8bd2bb339603a4a694e10
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5a091057d6fbce2ae0897eb89b3979a1
    md5: 3234e05aeb495cbc71810eae804f11a8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ba4a528fd6f22de10a87fd60b0c7e09f
    md5: 4163ed773f231a5a66fd8c75f48f4446
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_tracer.res
  hashes:
    binhash: 2ddbed5226fdd211ecc764b8fe936f07
    md5: 85b86cc024b1438e7e488d48a8512b17
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0cf597f6ba64c715cd07f13e2cb6ccdd
    md5: ef83a329ce70719f6f8a55bae0b1eb9d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b0c6a767f6476d529d8dba6995755b0d
    md5: af80de75034fa44214f17e48519e7c01
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 570394a83f23c5ea3a963ccdb2ad012f
    md5: 26659ccf12f94c9ea4b845d5c77b5140
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart390/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: adaead5d53377a3c238672f0572ddb31
    md5: c28f75de2c86579418586ae22c511993
