format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/atmosphere/restart_dump.astart
  hashes:
    binhash: 6f1bc8ce65bb75786ea87d0ba26046fe
    md5: 75c4345a8e417db167dc505091d804d3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/atmosphere/um.res.yaml
  hashes:
    binhash: 752beec421adee2a490e9227b34d52ec
    md5: 53e3335673ae3830413223757758cce0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/coupler/a2i.nc
  hashes:
    binhash: f86fe552f7d840f00466e04818af5966
    md5: fe1e9838c5a80ff98b44d225d8ba87c7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/coupler/i2a.nc
  hashes:
    binhash: e60b775656350193b3f895784d41412b
    md5: 1f60945d9ed31e040a343c129a3a2ebe
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/coupler/o2i.nc
  hashes:
    binhash: 5d548318a3dbf1f3b82d40cf5d921807
    md5: dae4642de5af08c92b0b261a2fc1dd09
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ice/cice_in.nml
  hashes:
    binhash: 14140b37166b2807f3c1fa28fcd6fa69
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ice/ice.restart_file
  hashes:
    binhash: e52eef688617f74386f50bcaae8092dc
    md5: e1ec884d5a34783280104cc60651d07d
work/ice/RESTART/iced.1176-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ice/iced.1176-01-01-00000.nc
  hashes:
    binhash: 070a693bf142fb09b3672cccf9e4f1f8
    md5: eb0c89c906ca18e7278c97461e4263dc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ice/mice.nc
  hashes:
    binhash: bf7c070a3296be8e28b67f43c09c4b2f
    md5: f3e91812da799dc87594142bc37dcfd7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_age.res.nc
  hashes:
    binhash: 79f12952e7dac4321b41b7458ffb1d63
    md5: 26ba86a43bf58c8572548e383e0bcac1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 137608e3ca5d5f2cff768bd806757086
    md5: 1b440d744c176310e6fb6cb33fe60092
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2b7285c266603985a408375d3787ac5a
    md5: 8542c26cd388b6da20dd72c1c60ef57e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_density.res.nc
  hashes:
    binhash: 0990980892705edfa65c4f66410332c2
    md5: b9f32841b4e5b528b1eb26bf04b51225
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 12188915208693a45d6b9be1ecdfac55
    md5: 662db62b9d8769c578902436ca5b5374
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b75cec111ba92b99acbccc44816be8e0
    md5: 998d4f296fa3f4a2ca4da71b6ba578cb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8ed6cdb520e19307775c9763c3fadfff
    md5: 2f669a7e5e47be81c2416260dd559f9c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 41ed2355757d972584309456a3a46d0b
    md5: e4a3dcf6a921e241ba0323c677713ba7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 79566cf10427593966537b56816e7918
    md5: 67c5d7bd074a6453ed9f05c795d57bbb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d5711b69dabdc365f67ced2482b035ce
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_solo.res
  hashes:
    binhash: 9e27be7dc81650f0b66e264e5dd9f902
    md5: 66eda9f31e250fd5f2b8b99c4b50808f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f684ede18a5bc0035da456e8b0c8e430
    md5: 08a29498580526972ca31d559e77438d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0702cb7917107855c6a6fff478512ecb
    md5: 9fad6eba4504ebc961ff9e177749f001
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_tracer.res
  hashes:
    binhash: 0c3c9a84e5735e43476416d70ffe0f15
    md5: 50f5fe759b1def0bfb0151e6443c5d7a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aaee4dad66fcd09050e476beab1704e4
    md5: a9cd00575980a112fe3bbef2ec997b01
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6bea59a2e4f448172835a584116552c8
    md5: ca5f7f340ac4cf5d30a52ad49d2043e1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8fce599a6ed42035011abb3237db8a9f
    md5: 44078bcf934e465c7b9e31187df718ae
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart292/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3c9174e2174b527192f1a1e20e8436ea
    md5: 4802d241041ce817d89b81a54d5f62ab
