format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/atmosphere/restart_dump.astart
  hashes:
    binhash: 713c2ffc6d314b9f0f2777bda79b2c77
    md5: d6fa2e1b5596b48fce43fb65d679355a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/atmosphere/um.res.yaml
  hashes:
    binhash: d989d9aa6a209a5cbbebd2f22db24769
    md5: b3e515f90845bbc050ddcbd5722bac01
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/coupler/a2i.nc
  hashes:
    binhash: 2b7c519f228834ca3a2a6e6413a4ecd7
    md5: ed669fd1f585ca447a9654a60b028fb0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/coupler/i2a.nc
  hashes:
    binhash: 14d84082d1533a02d3938ecc21e2c38e
    md5: 5714e45672f9b1773777ea5e52cc8e8e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/coupler/o2i.nc
  hashes:
    binhash: 7769953e8f018559e40581efa4700830
    md5: 9dfff7a9fbd494bc11c89bdeecc3bca2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ice/cice_in.nml
  hashes:
    binhash: ba12a807646678b5c5ae06512a2e0ae8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ice/ice.restart_file
  hashes:
    binhash: 3104657d528c94004fda81f91cc8b869
    md5: 4048265a8f1caccb0a46f5cb66cf010f
work/ice/RESTART/iced.0898-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ice/iced.0898-01-01-00000.nc
  hashes:
    binhash: 0d539aad1e88af7817750387ad86d794
    md5: 92b70d8b77b827c1d2b805f0835737eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ice/mice.nc
  hashes:
    binhash: 5df7b0c91ac869b64f7cb74377e12dba
    md5: fd2375b28ccd7b7697e0576216f6504f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_age.res.nc
  hashes:
    binhash: 2419309cd0bec5459f95b0517b8a43f2
    md5: 79048986c4925f6ff2f3ca2e8c50e98b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: db68d3dce3aca99d13ab4004462dd265
    md5: d292d4694d2db880a3655b207af913a7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ab5b5906f155abfc2dfca26c52df7224
    md5: a0e81cb675d1f29054d7d0f49dcce6b8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_density.res.nc
  hashes:
    binhash: 702cad842fd0666c93701c789c048480
    md5: 6d0f7aa75b4c611231a4153a524a6ee4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 26727ee14edf8b3a45fa8a3cd1dbd77e
    md5: e628618734ef061588be0243f7dcfe74
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c29ec973468a8cd3317ec89206f7db03
    md5: 081ad0b1dfbda7588fa88ab1870b3240
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f54891fcb30f38abc050ec81b79aa0a0
    md5: b0517361852f771e2268c06c96bab883
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f7642a84a9a0b67c6741d28c5abb0a17
    md5: a8fcbbf6781214532e91ea1e4fd11c38
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7408c0633642872473fd6bde7865f87c
    md5: 8d74a67140d400aeed3a44607f02dc11
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8c13a6dd9885da64a703ea7898da2b9b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_solo.res
  hashes:
    binhash: 4bf8cfad87c34b78af88b688426a8d3e
    md5: 354fc4dc6dd1d0d71a8961336adaf689
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5c8ad5a4f52479357cd9d2fe54dff11f
    md5: d9fa403d1867f3347097a0cd632d25ff
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d1f2933f2a9362b640dc3d5407a2e8c8
    md5: 276e6f13018fe3d34b41ef486862b7b9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_tracer.res
  hashes:
    binhash: dac5246fac344dbdf93fc5d573cea6b9
    md5: d88720fa8a1ad988cd5e957faf990760
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6c0d2a6df5b8c7a5244b5874793a8490
    md5: f7afb29f171e7933dc7160a0db8b14b1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 627c401419da8be8155833f673c6c871
    md5: 530e5a8b4bdbc5a17b0ce4cd1563f526
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0074cae2f693ef4e9629660b7f3c9ea9
    md5: 3da13ad7b537562b28a4c8187a048fd7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart344/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3b8d693e0cfba1f5fbeeb32d91297a84
    md5: 2757410e0016613503c44348eb2530d0
