format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/atmosphere/restart_dump.astart
  hashes:
    binhash: 9b6fd5e5d865daeae862257aac91a095
    md5: 50494ffd196aa31bbadeb016eb85c68c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/atmosphere/um.res.yaml
  hashes:
    binhash: 9a04e010abaedfe0578362bfc4b7e52e
    md5: c6af7de82c9d025f1cc4488a20e56b43
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/coupler/a2i.nc
  hashes:
    binhash: 8dac3333e650bce6303c7b495528a168
    md5: 3b89dfb5d887c8163a761759ef4a4607
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/coupler/i2a.nc
  hashes:
    binhash: 889e621d4159360fd9663cfb335d6137
    md5: 68c4c7f05ca762e92f02f7b9bb7cf6d9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/coupler/o2i.nc
  hashes:
    binhash: e94b54c6900c9bb85f67065932ae108b
    md5: fe6bf75fa4bc5123c943ecabf52afcd4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ice/cice_in.nml
  hashes:
    binhash: 619e71db8536de5609ce5b43320430fb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ice/ice.restart_file
  hashes:
    binhash: 9f3428cec29e2ce890b85e2225d748c9
    md5: 1829269cbde05bdaad1aade792dc6cf5
work/ice/RESTART/iced.1852-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ice/iced.1852-01-01-00000.nc
  hashes:
    binhash: 7644507364df041d4bc082757ce7ce2b
    md5: 2c98c7e191e8f5f49dfa7406b168645b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ice/mice.nc
  hashes:
    binhash: 2818fca0f3e848dc9391aecbaff70e0f
    md5: 95f3373490d2d5786e78d35519d18fdb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_age.res.nc
  hashes:
    binhash: 299e48ecf32f23674c01a407be134c76
    md5: 09fac17ac48c10b85e8b60d102dd6af4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b4b239f8c68c24520f5a61a2bfa93c9b
    md5: 8d9b469cf9c49f6bb4480308613513d5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 85d758204f656d30213e5f6f379da612
    md5: f823d69cada905e3783cf39f8ad2247b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_density.res.nc
  hashes:
    binhash: bd136272c81f97b229c07449a812bb37
    md5: 85a05c0d3d5bdcdbbc311a918424af07
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 19cf4deb3abf74975632a653731b5ac2
    md5: e4faaf73a61911c1459de6cb1e9ff873
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5f995db7eea22f017cf76b42f018f82a
    md5: 2871d68942d28e94aaf56b8146924e31
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f5d7be5f2607b22536486494ef7586a7
    md5: 74f4de8a73a07e585c4319fed122af14
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9d47b5983af0e81295f2d2ecfb0fb5de
    md5: 77f492be20aff3817a322e22f875bbd4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ffd4ca5498f28d21a08c0d3c06092ec3
    md5: 6eead6ae3c2c6343ae53cb6dcd95b2a1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3981d612d0135a4ca566bf15475b4656
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_solo.res
  hashes:
    binhash: e2a5d2909a276a6d4c17e3396ecbd178
    md5: 1b076a9ed74522b7b03cc486e1292610
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1b94591b1f2b217662d1b50e2c07f92a
    md5: ed16ec27f301b3ff7ccdd913f3987fe7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d015781f14e2cef84e0cc5a71e088c3c
    md5: 8e1f15bbb6c4cf62ce0726dd6658194c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_tracer.res
  hashes:
    binhash: 338ddb375f88eea413a1fee792cc2b46
    md5: 4b395dc306ab83a6c120f637e8fcb28d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 151ac733a139300ed224551f5632e54a
    md5: 97523c84b47a07bec3f9655fc45ee475
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5b70ef89db7bbe658c3be1479159c1f4
    md5: 63ce2cc4f9504de2ce9d7b0e6a5d66d0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 87aa40760648f846ce90466b1bbaeb90
    md5: d549bded4735478f495be4d80c972e06
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart407/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e972e79557569aa16423ea1f8995b3a3
    md5: f7bb1d618efee229a1b9c70117acca3d
