format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/atmosphere/restart_dump.astart
  hashes:
    binhash: 126d6d92c326d0709d6804a4302641c2
    md5: 2c594eb397edbf2eec0d57ed62cfe712
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/atmosphere/um.res.yaml
  hashes:
    binhash: 2e338634cf582d25ba6cc27de4016fc3
    md5: 6306cd54835b2a58873b4ad32e60c837
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/coupler/a2i.nc
  hashes:
    binhash: 5ae80ba060a56f4bfd193b08a88decaa
    md5: 0a2cb927aaf8c933daae8ef6233592be
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/coupler/i2a.nc
  hashes:
    binhash: e81598db9d93e30b10eb0c9b2414ca21
    md5: b46766e0436c1e55ae25c8377b61c937
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/coupler/o2i.nc
  hashes:
    binhash: 9ad60d413aa3b729010361a58f243abd
    md5: f20382e71b4f1466e5b5ffc7dfdf110f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ice/cice_in.nml
  hashes:
    binhash: f8621cbc7ca5094ef81b4d9aaf9e6ec3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ice/ice.restart_file
  hashes:
    binhash: 65481a8c77958f1eb51ddd398045bf95
    md5: 618c40bf869e24bf5c56200ab794674f
work/ice/RESTART/iced.1846-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ice/iced.1846-01-01-00000.nc
  hashes:
    binhash: cb591bba521a406884f37e6126bf6cbe
    md5: 2cffe3ea111bed4febae0ff0dd87b24f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ice/mice.nc
  hashes:
    binhash: f50d58ffd19488d4a8e2aebff25a4891
    md5: fd5af37f7c270b1c9df9484478a6eb94
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_age.res.nc
  hashes:
    binhash: 548f308f841268a38f27bda218cfa921
    md5: 54b14a7df39e532059787325083885fc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 69839835f4ce16e0d6a0cc00f1fbe656
    md5: c57bdfd4ee5f329a8b44363444d60c2b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 114a7c864aa08b2902cd2a7d8f51764f
    md5: 0b5d8f7c4d82e38d7f76d49fdc96e989
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_density.res.nc
  hashes:
    binhash: 6762e0d9192cb3874a5be7c68b043e13
    md5: 8d8b5d28e4c1199a3d3d49eb2ae185a7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fa5fbeb86f9d5eb2524b827f972f4d46
    md5: 95c367fca3544a2bc5cdf145ec2fccda
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dd2a4a1677340c73c36938f7254c6910
    md5: 9a77ab1a9ebf1da6e4123cabe7c3ec45
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 995c7bd2c3c9b1b8a92a0a9cda29eb74
    md5: 7707f55f7883b69146aaa23879c851e9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0e30849b392f4979a8f2f2436cd655b9
    md5: a130c2b9591f9c67783150cf033e78ba
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 66be4a5e9b8d3993906587bff69fb94a
    md5: e6b9f3b7d102a6b447b1967c5bc5867b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7dfe03e3af242cd59606ef10aae2bf71
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_solo.res
  hashes:
    binhash: e9bd1f5289fb4160fc0ccd8ea374606a
    md5: 08593721d18d123dca7d254883611ced
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 347508553d294e052b3125dd4c3d72af
    md5: 7aef42e7bab5eedca58c90ead6b2fed3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7c5b880f498a9d62275947d371fc62cc
    md5: df4bb2b601ba426ac08473f9a15df864
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_tracer.res
  hashes:
    binhash: 7039a5d8f88a8c18d2e4f6c582cf804e
    md5: c418a8772b17ef804fd0342b0e333fd4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 52e09e8e4b0ed2f35d9c83aee89fa53f
    md5: dc8f551c3f38d6b43b76b66890a24c38
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c41c7201e862a5b24a8b10c47219af8f
    md5: ee9258e4a973725ed8763ab339157489
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6a9006e0cb11e1fe7e77f55e7075d0b7
    md5: 66975e3fded88eaa46ef8fec59f849ce
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart401/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6ec7b8ed3f349c2fa79a7f33c52e847a
    md5: afab428f6c0c411a740627fc006f919d
