format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/atmosphere/restart_dump.astart
  hashes:
    binhash: 18c3c05f29a4b85fa7ed4bed1a68f042
    md5: 6659a38b8dea0ca2878129ba63f2a0f7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/atmosphere/um.res.yaml
  hashes:
    binhash: 40cb389fcdf827a3ba28e50e2d2bf324
    md5: e62098987df1ff4daceac979073cb953
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/coupler/a2i.nc
  hashes:
    binhash: 4dae0a6f7170c5ed1117be26fc205407
    md5: dea5472688ecf0dda71bdb96e75cff02
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/coupler/i2a.nc
  hashes:
    binhash: d4860beea45b1cbc61420abb98717f5d
    md5: 1b504c94d2d41564b9c41ab4002f0dfa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/coupler/o2i.nc
  hashes:
    binhash: 42e9e326dd65b586c4414cc26b18bbf7
    md5: 7510a3c219647ffcecd665bee30c904e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ice/cice_in.nml
  hashes:
    binhash: 23af79f864c1b87ee1075321bdbb8cbb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ice/ice.restart_file
  hashes:
    binhash: 507e20225ce0411fd3d1e8d4c8f3f38b
    md5: b1dcd9892f81f6028abdfd59da8a6cff
work/ice/RESTART/iced.1250-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ice/iced.1250-01-01-00000.nc
  hashes:
    binhash: 86626b7f39f42972a722beb1fe2adcaf
    md5: 3440c68b57d0eff88ae5efd5f88abb24
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ice/mice.nc
  hashes:
    binhash: 251ff2687189cb6788874b52e899c371
    md5: 2f4c38792b2ca43eee93960c6616feab
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_age.res.nc
  hashes:
    binhash: 17ba7b3e42b95f3c1ce22ee4b77f3adb
    md5: 6bc1802d29bf653db7041f6d0eb96b54
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 75584b065cedc7b56f28c8e0c888c702
    md5: f16e23c0bbaffc3acf73b002081c523d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 86704dda95ce421178ce6eaad7808e33
    md5: 0417aa0cc95687b3a3a76f778696268b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_density.res.nc
  hashes:
    binhash: bc4dba4e589fd0e046f1ef95d73bbe79
    md5: e3081d5771e6a4e310209709d8a13b6b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 356ec419490706ad4e59f7a9a391884f
    md5: a663a310add4bd846141436af8a1c07a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: daa15c13f346b9f5474cee3a9eaa39e0
    md5: f629294f6025a0032da20e220278ffe3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ca6f0bdcf1110d43ae37ccd1085dc6cc
    md5: 5e90616e333bc23052239e04c146e386
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3df3e0dbfdd117254f43511cdcf948dc
    md5: ff3c2a9fc801407292279053917af938
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 12f46697c04300d457b2883be28d76f9
    md5: 11e37efdc8a3d97ab2d333e59f69a7fb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 578af842b0efb0a6f699406b57ff6605
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_solo.res
  hashes:
    binhash: cf384b6223fbfc24694889ab520ca93e
    md5: eca0c9b1be415413820605b0ff4ae976
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 52597f777b150b7dd8b47232d633a102
    md5: 6317c42fd78ce40fe3ec3ada7e91cc57
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 29236d6fd4a11b5d06bf9023e1980db5
    md5: fcde01d4112160550bda4cfd48026d6b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_tracer.res
  hashes:
    binhash: a07682ac71502531bb271e322a7e6491
    md5: 4ecc3030c33ae8226e156e42bbe13020
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9d1f11eca02a50b62be378fd5c129e19
    md5: 3ebeec545b55e862daa8110da9e97718
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 50c57bdea656f2f22e0d1da204fa226f
    md5: 5f7b190d90ac560b1b6f6ffde26d97dd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3db88615347943e7c700c8de3ef252bc
    md5: ba9754bccc82d0fcced1e10bbe5e54b2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart366/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a05716e4754fe00490df99c4de62fd37
    md5: 653a8619519b61535c91a1f1fa3752e8
