format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/atmosphere/restart_dump.astart
  hashes:
    binhash: cb2bf54e5d629b0d4791ada60bd9922b
    md5: d5f7948a28d72041abc336d2c5f44738
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/atmosphere/um.res.yaml
  hashes:
    binhash: 12a8237dfa9079b8bd86503379d93ccd
    md5: 88249ca7fac1d5eee1dc209de09841a3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/coupler/a2i.nc
  hashes:
    binhash: 0455781a61dc3a8f91ca891497236d68
    md5: b6b19a48ab106f466c515f5fb9c993e1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/coupler/i2a.nc
  hashes:
    binhash: 3b08f63f9380e41aaf856851946ae1d9
    md5: c1c542727d1336095258aa3916950d5b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/coupler/o2i.nc
  hashes:
    binhash: 2b212b8a7ff67bd501f80b904d3102a3
    md5: 2f5c943c45f825d2cfed6edad46565ed
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ice/cice_in.nml
  hashes:
    binhash: 451e31f6cf33fec10c5a2241ab3ad62d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ice/ice.restart_file
  hashes:
    binhash: 34f1fc3e0ce51a543fc106de14739675
    md5: 2af9d46505af9b4467a223b50b1dafae
work/ice/RESTART/iced.1283-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ice/iced.1283-01-01-00000.nc
  hashes:
    binhash: b5abc01700ef91ac08d4a866d6d9b5d9
    md5: e535f46890d565e018f23135e0d0396d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ice/mice.nc
  hashes:
    binhash: c1d9626c52621113d673b9b382891fb8
    md5: 53b2b9cea724f99e4a05dd7df748b799
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_age.res.nc
  hashes:
    binhash: 57d2164ab32853f40532e7db80c9f0da
    md5: 386543ffc42a528fd66aca14b5b99a13
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 067ee261802ef53814eadab715840bee
    md5: f5eb378278130e6cdf5d936b340682bf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dd4f4f4b02d6ff93c37b0175a47211ec
    md5: 12a7e5f909388b55b0cab58011de9106
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_density.res.nc
  hashes:
    binhash: 089983a6b926c991e7a5baf5abfa4d32
    md5: 8e029c9de1d5b1a625e7cb911684c5b1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 747a910603382332cf6fcd41dc98d88f
    md5: f02a703c97c27451de00d8e77130bb3f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2e220a14a6c846d233e2f5e5e7de73e3
    md5: e6bdbc0a7edcddff7e2d08ac1d245f90
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9867747dad6e20b91fa595007fe34dd9
    md5: cc8d97fb6a2fcbc3eafed855030338a6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 219c3eadff892c183c5ec0b11de7247d
    md5: 537da60221b7efa4ca904147a2015d97
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 586a5cdf15ef746e043778147c8baef7
    md5: 2780fbc5bdd357b2ba1da90e989f6de3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: df631fb93d5f1a64585104935823a18a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_solo.res
  hashes:
    binhash: 765ffd67b24597ff20a59e6c8f45b36b
    md5: 77ff329bd86613ddf09c35347bdb9671
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0042f973721213cab20cd7fbda814507
    md5: c19b5813c81cf81e19d2cd251e430042
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dd86d53652efa05a31da10516f5d1956
    md5: 1ad1819a9c168920f7600106b1a2b752
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_tracer.res
  hashes:
    binhash: 453854b6883b7769410be11ea397f33c
    md5: 6b268f7bc8d5e7f0e7bf4aa00533503d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0e3f6f8ee1ad54d12cb1804606a9ca59
    md5: 820a9800253e045e66a024932424cf9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c99d6ea43d6622316627ffe0b8e7efad
    md5: d3b5a7def7f0b1b4a14ca5a6f5315cbe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 46d7dc2c0e784f8e840458bddf766ce0
    md5: 3b6b37274ad8e232b06f520ffebed15e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart399/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7214c5013580c55fd32a00616b953b21
    md5: bb19a4a5ea151d700ef33262a0279628
