format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/atmosphere/restart_dump.astart
  hashes:
    binhash: 4b90384610d1a48acc59da235d504fb8
    md5: e6cd7406cbb510469a24eaac827b3ae8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/atmosphere/um.res.yaml
  hashes:
    binhash: 4d79ae592d24de7d6ad5bc25cf22b58c
    md5: 63eb03441aa905c4309ee9be811ac810
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/coupler/a2i.nc
  hashes:
    binhash: f2047140eff74c771f947aaebd321a93
    md5: c8d2912885e019d7d7e4767f1b0f5ae7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/coupler/i2a.nc
  hashes:
    binhash: 419ed9a2fa53858cde3845ef87acf701
    md5: a92d7d181841abdd927bd903f4ff1e6e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/coupler/o2i.nc
  hashes:
    binhash: 92e48ff7386911f8484a5eb32a7631c1
    md5: 5da6d7c71d78567bcb7eea53c8e9934e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ice/cice_in.nml
  hashes:
    binhash: 0f40cbdefad22f1295ca44faf166e50c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ice/ice.restart_file
  hashes:
    binhash: d59f17f2ee4541f7e775460086327529
    md5: 58fbfd0d58ad6a3557b0194619de12c6
work/ice/RESTART/iced.1725-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ice/iced.1725-01-01-00000.nc
  hashes:
    binhash: cd8b284426146affd09a3e6bcd9383a9
    md5: 02b5e7de8d2cc87b554864ca9e4e37c2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ice/mice.nc
  hashes:
    binhash: 86f89f9bc7baccd345acb15197018f62
    md5: b4fabcf922a804c127c6a43f1c44c828
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_age.res.nc
  hashes:
    binhash: d81176919e38b186848d93e6af8cf488
    md5: a3f7b4f10ac1a85d12d4fe8a1f1c7d6a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a3f16d48716e67cffcc0a29acb7a6517
    md5: ed3a2d03480f3d91b95f7014d6085992
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7e39c3c2f199ad638663237dd0ddbebd
    md5: bcca9dc946128d06c4a153ef16c7fae6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_density.res.nc
  hashes:
    binhash: ed609d57723f0ebc3320062065a4f647
    md5: c378208a426bb5176ae9d647c74eabf4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 80108560658adc9278f458e5900f90c3
    md5: 1605809cd19be27c66cdc8816954576a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f86cca49fdd710e74a277aa9033a5010
    md5: 869c54a4a57e5c9cd69d22fcaf8788be
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7f569d4bfd6bee6ee5df9392e963fa10
    md5: 62244c6d7e80cbe5397d947331a77b9e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4fcb2dd7e24724b17d5dafd4553fdc28
    md5: 3fbd30ae5ace6ac32bad1f887a128f8c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ba59d8df95bb3361e66f2f566990abc1
    md5: 9542676fe779f7e9d96220b478a7cb1f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cd1614230fad55d1399d6b7ef1ffb015
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_solo.res
  hashes:
    binhash: d7dea7f3a3c25bb9c07d8f57b8370172
    md5: f00c54c292f3f579b25b209fb0c0ee12
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 48b41a249b7c9acea2dae31846fdbd48
    md5: 3a57424a0c915d5d18af66c2e6fb196d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cb686bcdac5f224c239780a3aec3b320
    md5: d0a46e675d785b74e1e78d8755ff228f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_tracer.res
  hashes:
    binhash: f8f7f4b888a0792f4ecd02b5908b6b4d
    md5: f1dc6f911c0951bb9efe30a9a733d4a4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e3e72092425ca533478c1e2bd2dba778
    md5: 7452a966ad16d829b281e1a73f288048
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d6d7bac595b07b4f978762c24acea0e8
    md5: 7c53fdd99d7e03c4f4fc04b86ac4173e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 13ec001df4bc0921c527e648486115ee
    md5: 8773bfa31bdb95e78f8a8b2be4f8dfc1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart280/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8a0bfd894ddf60a2d839c384456e078c
    md5: 3f91306278597dafe8a31a48a1187954
