format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/atmosphere/restart_dump.astart
  hashes:
    binhash: b6170010f2a9bc91dae4cc9ec60f53b3
    md5: 0449b48311f53b1af6673c6f49818c20
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/atmosphere/um.res.yaml
  hashes:
    binhash: 0c179987aa591befe6303ad45b3f886b
    md5: 3755f925fce6a08703af28617ba51d83
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/coupler/a2i.nc
  hashes:
    binhash: 0dce8fc111ac5154f2c8eeaa6d2e3b11
    md5: a749f9c618e7e4f7ada2ce5775f2104e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/coupler/i2a.nc
  hashes:
    binhash: f74022cb6ae5e65b2fede78ca24d78b8
    md5: 10a6f52792e12961817984b51fc1a7cc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/coupler/o2i.nc
  hashes:
    binhash: b26e034af005a43cb6467668232a84e7
    md5: 441e5c4c464a00a5f0cc43aeec8de908
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ice/cice_in.nml
  hashes:
    binhash: 0691b4d608be5bd266baef4121e8cade
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ice/ice.restart_file
  hashes:
    binhash: aade6a24911205ccc152b40dcdd5ccb6
    md5: 9292bfdb0894ccff076b00fdc83448c5
work/ice/RESTART/iced.1244-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ice/iced.1244-01-01-00000.nc
  hashes:
    binhash: 083a968c3db10c016a8f9684aaf5dadb
    md5: c58bcf2e66169dbc1df4002d1e5bba77
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ice/mice.nc
  hashes:
    binhash: dcf62d6a33f6eca98bab018062521385
    md5: 8292f141f86be9ae5ddecb427f6b5314
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_age.res.nc
  hashes:
    binhash: f6a2b7796bb21e85ed925be9b16ebae8
    md5: f3eb6a24589197f5223c90506b2b0d64
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0ef4fde442e9a91e4b92af5c139d563f
    md5: 329f58a8e5a61649267c6de32b8f4ba9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 67f5dc1be4577307ad3f2937ee590b39
    md5: 5d6ebca63a871c29bd0c428cc9858eb3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_density.res.nc
  hashes:
    binhash: aa983bb63095a7163d11f8a4fa65f776
    md5: e3015a07c2ca3594b3863d677bfae5d2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dda1dd6d10e3d00946e3f068339fe6f3
    md5: 72853d80f141bf0ac574268f88f3c3ed
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ce1065dd1874c006560ae1ba25e342dd
    md5: 3ef7fa006c0d978882a6d13de6cb0b4a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1e22f9e4ae9c8d46896526bc8899f471
    md5: a2a753e907370d4ef205630150a269a2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da1d816cf015911e8d934102d45b43b2
    md5: 69c1360e2fb6830b84c994ded3188c9e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 165976d7854384b2e6e257ecd1d8dc8b
    md5: 61bb41bcd5f4b8a6025508de4714a7c6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7ffb1c9be619245c163941b0844f6ac6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_solo.res
  hashes:
    binhash: 83018f4e6c27233bff25853a7cf65994
    md5: 6a967b926385baba6330ba2e2fca9c88
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 72b235e9a5844f86cfa148089e1a048f
    md5: db77c33b5b4a22f4673523e6f354a163
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c7e88913a491a3b6ddd0c10e3702883b
    md5: f799ab925d3cc42da8ae227507b57bc0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_tracer.res
  hashes:
    binhash: 4690f44226bb09b1c0bcb5712a700eab
    md5: 9247662c3f802375af5adcf27a099a11
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3e00b3f31c7e9b714435658ebbcff94f
    md5: a6bd1146e5781eff8cd9c5cad82e9d60
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 403db3e8a0646c132dd1f43b399ec6e1
    md5: 0387685153944b386547fdf63478fe31
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fbe25a74c85d9f86aae5cf0683f7a8f3
    md5: 0992f7a2b7bf5e4817287cc61fe30ba9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart360/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 75844a304c5a868c8a443c43923d7a57
    md5: a047ab0be484f7d6f5f436a6732b85ef
