format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/atmosphere/restart_dump.astart
  hashes:
    binhash: ea0ae318a3e3508b2c2ec3dc2d4c0b10
    md5: a04af91b90100dbd04666ad4b706bd2a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/atmosphere/um.res.yaml
  hashes:
    binhash: 7e60a8dfd317c9438d07b60d0685600d
    md5: b9b58967acafd0ddf20131e9ac62b3cd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/coupler/a2i.nc
  hashes:
    binhash: 314f1ec081ccfb589edf34fb5312988b
    md5: ec5712a56488984f78028bd9fc1d4fe4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/coupler/i2a.nc
  hashes:
    binhash: 219f18525390e0ec72d16fb403e0bbcd
    md5: 7f8c1add02a29ec98a2abbc4de01bd82
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/coupler/o2i.nc
  hashes:
    binhash: 386cd21c7bb5eabf74a949d0cff03b86
    md5: 8734995e9b5d70e5a71a0e8e7d54686a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ice/cice_in.nml
  hashes:
    binhash: 75b76dfb0e440eabbf387b7daed32c74
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ice/ice.restart_file
  hashes:
    binhash: 91804c0ec0bbe18187cbc7a56f696107
    md5: a102666853a69aaa10f8b1c548590db4
work/ice/RESTART/iced.1720-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ice/iced.1720-01-01-00000.nc
  hashes:
    binhash: c9b6f868921d756a4cbdf1d4e5c807e6
    md5: 332f20ccea25b79231dabcf99ec4e6c5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ice/mice.nc
  hashes:
    binhash: f691aa409aa4bca5a13d73ff40927fd8
    md5: 18e94e69b16fa3ca9b59e79803f76900
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_age.res.nc
  hashes:
    binhash: c9a5bfba6192405145ad4f6a538f90a8
    md5: 0cc11b1536cc0d2dacb16911b84a6673
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6f39a4105b534b45a068578e6f86abc8
    md5: 33262f7c22b4ded6d566fd8441fb19fd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8940fc6e024a82714043b8d4a847bd2a
    md5: e96d6d9825d386b9ec3388029a2cf83f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_density.res.nc
  hashes:
    binhash: 6cb4467367ae7d629efe50dcfb4de0ef
    md5: dd25bed4d92ab46834126182df95a181
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7812fd06fad65f5c5140afbc157543ac
    md5: 71380938f1aae4039495248b7bece23a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bdf76e32c2d162966d5c8027b667180a
    md5: e571a75bab5b6e4ab2b0050116ae86aa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e0605fc723ecab6ac987295d970d4d5
    md5: c4178622101b438f61656e20c8120700
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5bb0d9d6991701e8e678ac2dbbac5213
    md5: a4a9802b8084df8205ec584a9af1b90b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_sbc.res.nc
  hashes:
    binhash: effdf0eb32b8085ab9d3ef7357d5716e
    md5: 562ad6b13a0abe84811449c94e2ef6c9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c2a9c5a9004329375a346359d9881bde
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_solo.res
  hashes:
    binhash: 38f60cd61efa41d06260fbbdd756c08e
    md5: 6c191a5231879077a774aebedf8733fc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 390139ddd15567ff1e63f6b71be74fbb
    md5: e9779dfd3c6829106534e8633617df8a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 92bad23ce74e896f4cfc29e3dbb0dd4c
    md5: 05c2d576d7540ed937377e9b2cdecb56
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_tracer.res
  hashes:
    binhash: edbde2a8a9c6c02943aee3b3d8bcf9fc
    md5: d0ae5b39713b94e618aef4fd0f06b3da
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 424420b22224c2e7c8f5ffa302e914ed
    md5: 9df3b23ad13405989448e7e47692b021
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f52ac7a4f0b860ba16f2d8c24f5dc6e1
    md5: 35fa7319729a7d7ee998e21fc05c92f6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9eeb648fc350c89a399d2203bc33679c
    md5: 66bc37c30f8a564dbb5286680287622d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart275/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ed7ca660a5d0511ef8f8ac1f8021fa10
    md5: 37ba68b813eeb04106ff62755dc5b8c6
