format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/atmosphere/restart_dump.astart
  hashes:
    binhash: 0eae3151260141af400835ae9f237b57
    md5: a0fb616641f859ee58fa0c37a0974cc1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/atmosphere/um.res.yaml
  hashes:
    binhash: c262adc43bc078bae84105a426746b88
    md5: 58dad975200a2367466c2014c98fdc24
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/coupler/a2i.nc
  hashes:
    binhash: 501d4c500081a5297a3813db6f15480b
    md5: 403850be78bffda7eeae2877090a52b6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/coupler/i2a.nc
  hashes:
    binhash: aacdfa93b9df4f74443aa70bb5016d9a
    md5: ca642b70901e81ad1800e5d54048d84f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/coupler/o2i.nc
  hashes:
    binhash: 5424b499d024677adad4317db6050c02
    md5: 2f6c20ca42b4b7e40c289f68260d3a18
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ice/cice_in.nml
  hashes:
    binhash: 8ad41ad46a993487bff2992d98ac9e40
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ice/ice.restart_file
  hashes:
    binhash: be29a0e62949f6061a0af1fe2365e165
    md5: 108665db0205cab1c1f2a57c429af23e
work/ice/RESTART/iced.1778-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ice/iced.1778-01-01-00000.nc
  hashes:
    binhash: 8b902d39b37aac9a1862935dbe609e13
    md5: 927d392bbd3fccb6195e28609ca6a18d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ice/mice.nc
  hashes:
    binhash: 794dfaa675c06d1293fcb649adc19dd6
    md5: 215a36e844cb56638c70e933b101b0c7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_age.res.nc
  hashes:
    binhash: 2cf9e6ddc5558916ea97706a2df17660
    md5: 632cbfac11ce3e4ed9cb68736508e8fc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fc9ced6602b623952cd99b4aa83149d3
    md5: 21070c651d2f37647b35595d9d4939dd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c16b6e769a2f2bcd0d1626f511efaa40
    md5: b83a1bc82ae54a9deafc81d0dfb01ace
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_density.res.nc
  hashes:
    binhash: 05332656fd07e6b7bf3650395d034416
    md5: 27cd730150fa6036dd7d522ff495047e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 73b165a506280e4ce4eb5308e987b4cb
    md5: 70a285964fce9178dfb0fc0d506e852b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 27f2a9a11d006ab0467bf47bcc1a493a
    md5: 1b7a8dedf108d4f7a401fe3308eca76c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 99cb9631b88734fed6d660ed3ea0dd05
    md5: bbe1c40f722011b9f0954d48d35661fa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8930b81be91f0efdf27755c1b16892d8
    md5: 2abd6b9034d537e1771e705057d7f252
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5eed6fca97939fdd18b5d113d938bd42
    md5: 995fb06718b1f8ab4b7e997b17af1b03
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6a51d1b0a63538ce2279e69add821711
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_solo.res
  hashes:
    binhash: 64334d7f00a829c67b5ab68903546e1b
    md5: c8d1c33fafbf2c5cb7de42f3847786d8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8639e314a06ac8311eeef6fc0c2a1ee9
    md5: 04d5c5575fecc2472e57cf5be175ffa1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2bf297b6d0acc6c103f4d63e5a948511
    md5: 6a4771ab9e0ff8885a5ca6fc361dcd7b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_tracer.res
  hashes:
    binhash: 4b0ecb07caecceeb44a6cc745665694b
    md5: 7f60267cbe1423a63f19bf9bba133053
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bd03fa7db59974db4aab4695089900f2
    md5: 33067fca41b2d67c653ecd3ae9a89378
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b730308ddf2cb9bf204b5ccdd85f7307
    md5: ac9878b7ad74136d19f2da496f74b81d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c87d6d6bb9c779f865a2aef7fc3a6652
    md5: 668aa669d0e68e086cdd511b49887fca
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart333/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5323ee8d1d9b30de121ac7f29534e6c5
    md5: a9a998880a091cac5e2b76f5c247501c
