format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/atmosphere/restart_dump.astart
  hashes:
    binhash: da392b7e9a5fe2b330d9c573159fddd2
    md5: cbdc14bd4e5848d04658da5ed46c81eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/atmosphere/um.res.yaml
  hashes:
    binhash: c43e20d2ea4b7af19225589b121b235d
    md5: d8e6fa1016b8c90389cd64449da30bf8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/coupler/a2i.nc
  hashes:
    binhash: 02ac57da5bed6d1929fd26a8a74de489
    md5: 49b545a38ddfe0e9198cb538d95e29bc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/coupler/i2a.nc
  hashes:
    binhash: 55920a67c4cfb966cb4d42ad20a43492
    md5: 66d046828e50760ed8b8c917e9561ce1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/coupler/o2i.nc
  hashes:
    binhash: 6bb93a5b41a396046cb3b8f673a838e1
    md5: 6c90cccfc907572ad345cdc1edad4d30
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ice/cice_in.nml
  hashes:
    binhash: 4fd35030fc8b35b2aef782aefd43cf9f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ice/ice.restart_file
  hashes:
    binhash: 0efe4826c2cbbffe43ad6978417d5142
    md5: 5ec6b0d0ad0a16f73fe1a12e225ffd6e
work/ice/RESTART/iced.1745-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ice/iced.1745-01-01-00000.nc
  hashes:
    binhash: 2064005b51d43fa31e89477385dbf4f3
    md5: 7515dd351c2c25f453cec8d73ef1ad79
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ice/mice.nc
  hashes:
    binhash: bce30836c5b00758c0151c2747d7d7da
    md5: 4597bcd806c359fbcfbc23703c3f41f2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_age.res.nc
  hashes:
    binhash: 5c0b92359ee67fa0873615ffd47e48bf
    md5: 3db6dba45e92938909943c5b7347788b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6977b1856af6dcb671f143277ed3afab
    md5: 6e3eeca67f728e3f260be618dbe3c695
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 58a9c4562a09355b5c52048bfd62f81e
    md5: cf47631585c4178678b829811dfc5d77
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_density.res.nc
  hashes:
    binhash: c6197e868e6b696adca0c4befa3d057a
    md5: 18e8e84e8cdd033c98f8ffaadc16f1af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c2474bbab3dd1aed4bfa6511da1eb8de
    md5: dfcd4370327f2252c6e35a156956284c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 817d838527f1546dc197493f32ef7f28
    md5: a35011d9d1a3235e5a3738059dfd3018
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6d440b301fa5b9a93cf1ff6fa13c3c0a
    md5: 4a8efa3998a1a22978870e9886eef9e7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 928f738c17760f6e439d67269d88dd1e
    md5: a0e091e6c553284654f0cc111e527d2e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 92662c1b6f4daf103f51270d24319a69
    md5: 76a6e3468f3eb2326f8cbdefadeb5d09
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5acc5b1e662390032ea589e60ce64df4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_solo.res
  hashes:
    binhash: 8b9ae5409ba51dd4ec1c00d6aee0b621
    md5: 300e00d4cf8ead06636548dac7cc3e9d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d06fdb8e2211491d47492f9139b701e4
    md5: d9599485eb2fb05d5b4262de5a7d64d1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f07ec93c4b473776b5015a4eeb671280
    md5: 2afc453611c7e8266250865360bfab0d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_tracer.res
  hashes:
    binhash: 22ab0e60f8a1e0ed35e2df97ddbc1fc5
    md5: 3e8c99ff3eba5697fc0aa9dfca8474cd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8e177dc793f36838326844dd43e48781
    md5: bbdfb020755fbd77467d44f98629833d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dc4acc8f60265fa2a20eee1ac00f68a9
    md5: b975b6d5c0944704535ec82eeae6ff8b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: be68b52a10aaa68983690de2659f1d7e
    md5: 5a50a74f07a7b264e8902bd929982a53
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart300/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9ec56ac922114379e7e16615f4b86c15
    md5: 459489d0f3da30851dd91728ca0639c0
