format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/atmosphere/restart_dump.astart
  hashes:
    binhash: 2c1aa0ef6a4c498e6a151615b078f42b
    md5: 5fa9fd3fe8c2f10ee42ba0c3e03fe02f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/atmosphere/um.res.yaml
  hashes:
    binhash: f5193a9abad651cebe8789935fbf3f1a
    md5: d14b08a2ac3397d3ee47f20bf8f9c6c6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/coupler/a2i.nc
  hashes:
    binhash: ba47ea95d582ee9fa4e045a4e6e44611
    md5: 20ccedf5b3f6cc96a836df3f85cd7b73
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/coupler/i2a.nc
  hashes:
    binhash: 14d0021f2ee3b0e12417d15726b280f3
    md5: a3cc21365573c5ef4136cc88d39619f6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/coupler/o2i.nc
  hashes:
    binhash: f9d8a1627534377ebce262856442b591
    md5: 16a9f32a76c4efb1a349521ba4952c96
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ice/cice_in.nml
  hashes:
    binhash: 1e11c6f71f10efd060c2cfa7afa99066
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ice/ice.restart_file
  hashes:
    binhash: e3709c3abf0fcd335870b56f9f8be508
    md5: eeaba978421c8b33c9bd04b3157c67ef
work/ice/RESTART/iced.1189-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ice/iced.1189-01-01-00000.nc
  hashes:
    binhash: 768829cbfacf6ae1630ef9529e214004
    md5: 37de9fecd755737c8f657abe65973e6e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ice/mice.nc
  hashes:
    binhash: 4a3fd25fc212a9f7d689505e7ebf91d4
    md5: 2bc803be3ff5760b152e2df609458db9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_age.res.nc
  hashes:
    binhash: 109655bc69dd1ea7259f2f1a17be1a92
    md5: cf17a792a27b3521e2af76611e09b293
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 93e0b65ec419991312bb69bf92a9b2d6
    md5: eddfedb93613f66931d792299d5e0dfe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e2e5514ff532e6edfa98052bce94ffaf
    md5: 644e06acff89730be9146adff30215be
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_density.res.nc
  hashes:
    binhash: 816438011e3b4acbaa14ce94ada2769e
    md5: 8c1592fdf154bf85869cf6c1458807d6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8a98092eb810db346273d00620e99ebd
    md5: b72b8c8b315161b03136427535492a5f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ceb2eee8b029cf7ed6b63aa9d94a2b8d
    md5: d56252b737973ac62737cc80e368009c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b4080ec9e302bce9fcbfede2f48ce7ff
    md5: c1c33e05689b7f0ece9e3b28b7a09f8c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d920a1b56666dbdc787add19c96db000
    md5: 4a14f24d5989e87c5627cbe923b01b5e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 870f55514e057ce9e72e126b4285765b
    md5: eff6a76ca3801d65ab00c76034da3565
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 828f5125057f98f5b76ba2d48794e5be
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_solo.res
  hashes:
    binhash: 0796415dd652d054e1aef16110fe5031
    md5: acb3faf8729da5055bbee8e3eee8e2c8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4f29dba2f822d90e9b1f1c948c6365e7
    md5: eec4d22bbc4f317f890d20633960ecc9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 64c6e77d5a43543f2daf988ab3993533
    md5: 0dc78424f56b432789917141f555b04d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_tracer.res
  hashes:
    binhash: 505b735c0254d15c05cf2403be7d3ca0
    md5: 983a01dfbf44d09e6eee523914be2ac9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4b83403290dce429bf2e5e236a781db5
    md5: 7a5932882c21ee38889ded4b24512406
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d9199faeff5c5d0d177b7e8906665144
    md5: d594d2c4e275962b9ca198cfff1939f2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1f58feb74e08fac2a3700eb8ad97e6d5
    md5: 194d1afeda45b327354044bdae95ef94
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart305/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b1f52f09a78da6f6db8487ae3e6aeae0
    md5: f3b2ea22ae7b740a123daa6a7974b48b
