format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/atmosphere/restart_dump.astart
  hashes:
    binhash: 385b6679e65b5e15f6ba54a99bd87210
    md5: e02cae0985ec6eda5d52817fb10bde44
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/atmosphere/um.res.yaml
  hashes:
    binhash: 4dc5aa49003d3369664f9f050c76058d
    md5: e600d98b98cf9a66f566afbb640dcfe7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/coupler/a2i.nc
  hashes:
    binhash: 95b65e1ed8411a6c089278c7b9e74c0c
    md5: 4d7b3190a27f95f6e465d60fadc3a9f4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/coupler/i2a.nc
  hashes:
    binhash: 2acac83d1324f205985900e2f93c2f18
    md5: 8ef611313618e35537dc362223474eb2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/coupler/o2i.nc
  hashes:
    binhash: 10e322c92a09e3fee0a6ea3895131820
    md5: 7ddbd391d475f40b685df5e5ad119ef1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ice/cice_in.nml
  hashes:
    binhash: 39f519257df1d88db2f8747fe925bab7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ice/ice.restart_file
  hashes:
    binhash: ee4903f69d565719ee27db70b4913145
    md5: e49dcd37706d43f726a04a49a3ed13b6
work/ice/RESTART/iced.1151-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ice/iced.1151-01-01-00000.nc
  hashes:
    binhash: 559389c42f832b2c367c069e437fb2cc
    md5: 58d1b84e39d8f814aaa008d816dd863e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ice/mice.nc
  hashes:
    binhash: f0fe0e1a2276d674697ff94fbb8f07c8
    md5: 9b771edbe6b1dea0aad5daf3a72b42d7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_age.res.nc
  hashes:
    binhash: efb740f3599d74013b0a119fcb630b51
    md5: 2c1ee681c7e3d896b0aa04253bceacf5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cf8ac014fab6d6e66569497a1f69cc98
    md5: 37cc6304d112f0c6393efbbc468a948e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ea4981df98e06c62ff22932c30dc053a
    md5: 55ea372530d33cf6eef2d4fc67cbbc6d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_density.res.nc
  hashes:
    binhash: 91beb654b5a4f506ee613e5fba63fa2b
    md5: 7cf7ba0540b4288984f52ae1b39ee8d4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a9d0fa53c8c87a9df92f6e8898a12e27
    md5: 7c33accaecdd34fae698aba7e673f7d7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 68436cf2382cf6e527efd9ebc17dbb71
    md5: 60fd90d1037c8edea038bfb2d2b338d8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a286fae03b6153d912d4d316644397f5
    md5: 6c471dfc1452ed3c508c96d45eb4cc2f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f7c49729bdbd8c2127e2ef09e83c54d6
    md5: 44e0bceda869423ba39b92ff490be6d1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 786457b3e5f9a8639ef9bc5da8e8e6fa
    md5: 0e9c5b93bf7cce8ebb79c301983d9a7d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: eacadaf702a3e6a9365fcd240829fd20
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_solo.res
  hashes:
    binhash: 534bc631972e32d310838ce3bb61c5df
    md5: 9e3ccde6e201d401e9555ade9499d6b3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0ba9819560c388d31576372959edd752
    md5: fc1b4961d0d267f4a547285463a1a1be
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1d7af1da3db759522573775f67ea545d
    md5: a61fcc2b3a3317bf567639ad211a0623
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_tracer.res
  hashes:
    binhash: 826da02f05444437a59675965db3f790
    md5: 28df85897aaccf172938e82a1e86ffb1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 36089f641e8c9a2f344f7965e28e4059
    md5: 080d7bdf0e617565674f184cf6fb3ca0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f2eeb798d560d99a79220a3928c93d8a
    md5: c53118434f4eea90552a8eb8af78b9fe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c50176371fc23af4975ff543328823f7
    md5: c37ef86c498e35ca96c920ff169d42e8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart267/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: defd8fd164004f7222578f4e4a2f86be
    md5: 57d9bddf06eb5f6e8ab04b9e966ff706
