format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/atmosphere/restart_dump.astart
  hashes:
    binhash: a3dc008650c71e1c91e139dd9a28171c
    md5: c905882ba185cab593ccb14bda771bcc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/atmosphere/um.res.yaml
  hashes:
    binhash: ce4214ec6a2e7e33fac36782bfcdf828
    md5: 064e7cda9b703e0e543dac8502d8d662
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/coupler/a2i.nc
  hashes:
    binhash: 7551a5b26144d88aa6d212898b00ad8f
    md5: b288de95e407c2ed72d81a6efc5921e6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/coupler/i2a.nc
  hashes:
    binhash: bddf5e01270263fc5760c1390aca2c3a
    md5: 91e2fa99ee03d9bbb30682224b94e915
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/coupler/o2i.nc
  hashes:
    binhash: c9e7a7345bbd0097d51774560d5178ef
    md5: 35b3a3073c443a061f2bf27816429cd0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ice/cice_in.nml
  hashes:
    binhash: 0e32c722dde6a789ceefc6a50bb52269
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ice/ice.restart_file
  hashes:
    binhash: 30623547818eeaa08d5451e376e4160f
    md5: a461aee54bb49ec9d990851543eb9633
work/ice/RESTART/iced.0923-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ice/iced.0923-01-01-00000.nc
  hashes:
    binhash: e181857ab5a302098f827d594b3f2e78
    md5: 1f8741a4e4f671235c1c97cdab489271
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ice/mice.nc
  hashes:
    binhash: d035b1313f0c54dad5a37d656cb12ca9
    md5: f624a118ddeb02f6d7d86b1b127b2b16
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_age.res.nc
  hashes:
    binhash: 9f97ae3f1085bf16c369dd5456f2157d
    md5: 1a82cb8120986d01311af5f265971dde
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8678457d032eafac1c2add973e1f60c9
    md5: 73a7b37a7493f9e60ef90eb284b54f31
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 673e000ded3e61244b5d6928cd56dcf9
    md5: 64fd5c9fa72eee1ad606c180bd088e35
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_density.res.nc
  hashes:
    binhash: 37949e92cafd1b98bf12c0e43dde7cf3
    md5: 514db18b11df7830443196fff3945c16
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a977b97cacb6c877ec0935f40c756594
    md5: 0a8fb690d178c0408f98d4924f63850c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 161ac6c4f09fc6e67f3ff6fb69cf01bb
    md5: 44fb31fe2ff3df266fa75666a2cfc2a1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f17c9ec434f976a709a76a3c76800ce1
    md5: a1b5bdd34d6591e3e5e758b2f7970d9a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d36216a925c99e87e90508fe965318b4
    md5: eafc19ff8b36a1add93858445da7f7ba
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 33eb6d5f63241128541d6adbd38e31b1
    md5: e482eeb00c50c9c29a7c2524c8887aac
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1e24ae284b838e4298af9b782d44b903
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_solo.res
  hashes:
    binhash: 7757d7e4ec8735d9a3b2963fe01cd30b
    md5: e1563b9303659598275c6eb1d19418f0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ea22f0059280d114f41faae705c25c40
    md5: f10e6cd6ae3059894bdd8fec0079ba17
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4da5ec7f062e3fca54ab262d2f341f48
    md5: bfd1ad4429a71ac208c72a7fd895f02b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_tracer.res
  hashes:
    binhash: 50f53256cff5d2a895d01de42239ddde
    md5: 3b195856ce2fc85e79346c43a5baefef
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1a748152ce1e5a8482dfe8194a6ba5af
    md5: 4468c4417786c83339fb2e7fda76365c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 741f73852d5475f6e88646113c9d34a3
    md5: 5c85fcd64d1ba48f3122751396efee05
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ab942bdf8140ee1e6ccef32df0f93ddb
    md5: 2eb48662774e09d62db34506c8851cee
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart369/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 53367e3b4e9551aa07212dedcb096983
    md5: 43bd43f6cd376976689c433dbc5ecdec
