format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/atmosphere/restart_dump.astart
  hashes:
    binhash: 4b54c30483fd4680017b39b56799073a
    md5: d97c9b1cfa9b0b18e083a922d8da448c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/atmosphere/um.res.yaml
  hashes:
    binhash: 49d175d67f12aaffd0fcef9708d74070
    md5: b5a7a9c3f872381f88a9c994eb0b6504
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/coupler/a2i.nc
  hashes:
    binhash: d32cf49da6ffa67f1d6b2f7eafc2796e
    md5: 6ba331bbe63580bbbfb965aee26ea840
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/coupler/i2a.nc
  hashes:
    binhash: c5ff5ee876299a0aee142219e564e08a
    md5: db6ddd2ce02764fdc4a3bb2f7bd75f23
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/coupler/o2i.nc
  hashes:
    binhash: 7b562b78d8b5f179d96962df5ee81474
    md5: def21d9b74716f5f1751b430dc772f85
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ice/cice_in.nml
  hashes:
    binhash: 0259c364c8c9c4f2308cdc821fb8d665
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ice/ice.restart_file
  hashes:
    binhash: d2b14f4d5125f81b39c2170bcb88c38b
    md5: e04c9bf3967d601e7c56b071eb40662b
work/ice/RESTART/iced.1285-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ice/iced.1285-01-01-00000.nc
  hashes:
    binhash: bb275394883e537a845cd6907b486f58
    md5: 52454d0b854eb502535d8cf6615b9f98
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ice/mice.nc
  hashes:
    binhash: 6e867f3a07d2741bc21d6d7dadedfb6c
    md5: 2050b17bbd06ed6ca9d9c4429076244e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_age.res.nc
  hashes:
    binhash: 4fcb83685fe32e52678bce2fa544c8e0
    md5: 0bf4867a66445a0fdf811aee90aa3f4c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 931f73839db91e0b6beddd3d92ff36cd
    md5: ff9b6d895fe8a88337a676bf7487c851
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: afdae7504d25e0df8c1c9d7172ea57a8
    md5: 74c1bfa7fca23713c172e942b33ccc98
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_density.res.nc
  hashes:
    binhash: 2513495129196c5798a4411c2895e2ff
    md5: 9a784c901b679f2d43c3f4270fe71043
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eb033c718c74967efbe3f4454efccb54
    md5: d0af6dc4c7799899cc7e2678e1e02100
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0dd516682cea4cff11b316edd2e7c661
    md5: 738efa975433ea6217d5d50d5b6db3ae
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6b9e2b54513a5d18ad1f195db71e6477
    md5: d4731a902176548f570e6c48e5c34ec3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2073c233408bcc471a6498b546e5bb98
    md5: bb5f235b25f040a1a66fafe0662d5060
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5e1cdb1c558741901debadd10b1c07d9
    md5: a6566cdaa9bd860a0844138879e2c6a5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f6ba76345fcce4a3c8d8059dbf66a38b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_solo.res
  hashes:
    binhash: 8c084ccf7b2ccfbaada0427e15fda398
    md5: f1bca48b1e014e367ecd5708d539dd43
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fefcdcfd10ec72c1b398fc093c4adbb8
    md5: c3b3ba6bf138e3c0e820f226d5365d56
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e5e3dfd2e90006502c59871bc8c16593
    md5: 3e88fb0a37d3a01a7f96706121411535
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_tracer.res
  hashes:
    binhash: 8ae2312bfd20b78d7a31fc927200f798
    md5: 048195d650cb1affc0d97320446b9eb8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f63058a96f813f2719bea9dc5cca083d
    md5: 749768bcbdd98960f859afbd576b8860
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b46e0227f1cab95ed4c4caae1000b862
    md5: bb4f14b524bf0b796559da9e7689d752
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c5ec2a7cd1c9b853b7695c4c58513223
    md5: 4b6dc4fc3a29baf215684d409ae89cdc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart401/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c04aeb1f9d1ccbcbfc6173a707cc475e
    md5: c0a58e490393884692b7d15cf51d7836
