format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/atmosphere/restart_dump.astart
  hashes:
    binhash: 607a150722887473b72c0596c198d5e5
    md5: 07234dfcf9147e60d28d941d710ee68b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/atmosphere/um.res.yaml
  hashes:
    binhash: afadca2b9a12e40a7e67643788f38138
    md5: 16fd0823bb3ef5df165d0cf8df1007bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/coupler/a2i.nc
  hashes:
    binhash: 012ec1a2470cc4ba2ae8032e30ae99c7
    md5: 08ad3cffe79f55f068c7c47b46d578db
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/coupler/i2a.nc
  hashes:
    binhash: 5066fea7107bf19430d25f6753b7432c
    md5: 152f67ab532363162c4c90777baf250f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/coupler/o2i.nc
  hashes:
    binhash: bddc1b869f0d6de2fbbed299e7c10b97
    md5: d6abbc215d98c5f6ae02c0e3a2164929
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ice/cice_in.nml
  hashes:
    binhash: e2db28ddc224022500a3f5e958e33273
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ice/ice.restart_file
  hashes:
    binhash: 370b005dda513b83a5de3d986804a84e
    md5: 4221c0c1ea3f4e08a0b727477e999d84
work/ice/RESTART/iced.1164-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ice/iced.1164-01-01-00000.nc
  hashes:
    binhash: 0bce66a726e8b298a9132fe0e03b2f9e
    md5: e6646a7f08fe08ce1ae2e138bbd4f570
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ice/mice.nc
  hashes:
    binhash: ba8f3c74794adacc325c67e132862545
    md5: fbfb4db7efc14d6912c89b7df6097ce5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_age.res.nc
  hashes:
    binhash: f859e2d9bf8e7d30bfe0a131f33045eb
    md5: 77e199440f89f8c7f4952db039d00744
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0b14070d13aa35d9a7270ea1b23ec09b
    md5: 6e9888c0cd114b3626ce2b59aef0419d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7bc11259adc1849bd2afa42abfe34023
    md5: 6a40f10b3cbae76d6492b5fcbf57438e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_density.res.nc
  hashes:
    binhash: c14e93c0e41b1dab627f81296910098e
    md5: 3bd485cf0c9fed73f370cd47849ea4d6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 16ae844c7c5f4261a442350775bd96b9
    md5: 4dab256ddb9d2efa1d6197a78be00c78
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 39654382e3d58a95d064ccc986ba6022
    md5: 079edc03d804371b68c60965b21683e1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2b87e496d360f37dd7117efc14a75e50
    md5: 144cd87ac1c255262521fd6b7bb59f73
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: abecf40ecd26e58f9667f8f2dabc1966
    md5: 3c7bec9a9292dca2eae215326ffc27c5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 387b980438c73e7f7c29e6d5b24f23b2
    md5: ac47c701b069eb3a2b39e0a26114ef1d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f2c75261fd70e62d466a38ebd672c022
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_solo.res
  hashes:
    binhash: 015eee9d523e78795b74362385bfb056
    md5: 950426f4821357ad2d10fdb132ea10df
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d29559d91f70a2a3d9838efcb04734e7
    md5: 8629a3bb115f4081aded889df34f0709
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 986b0e76fb6c28eca2b83a80b5328daf
    md5: f28c4c2c2716a8526485022235e67c56
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_tracer.res
  hashes:
    binhash: 3be8d6c25b8e9d012109f8d322b657b2
    md5: bebee256c2d06ef718c157d667a44caf
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 56c31b07800e5402bc3d2e5e0ec1c71b
    md5: 9649df721c3663a27674810eaef41a20
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 91bb45067a2b4569962ca7d5b95356c2
    md5: d7393643ab7c02bdaa16a32a7658d7ad
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 963c729aa4acf9dbb7a261a149d295c5
    md5: 541821ca287cc1412a6be7c18c516c97
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart280/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ca5c8841bff19a574b41d509b65fd0de
    md5: e2547e79f2fa3fddecba7fe661a72a21
