format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/atmosphere/restart_dump.astart
  hashes:
    binhash: 1edab71cd920b2ac62becca1758ba26d
    md5: 25e799f09b694e3743786c16f17b54e1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/atmosphere/um.res.yaml
  hashes:
    binhash: cc2c67f394d1c6d071d56389e9ef9a57
    md5: 4853dfa938b703e7fbfbb9f2674f3458
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/coupler/a2i.nc
  hashes:
    binhash: 1ac239c304cf8cb6b992f767f5621e85
    md5: eb27b39da59a2daa77266c546f0dd89c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/coupler/i2a.nc
  hashes:
    binhash: bdad5c0d7b0deb21489c2a29623156a2
    md5: 5c69f8740184d8dcf3ddc4033867750f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/coupler/o2i.nc
  hashes:
    binhash: 9dce331ac319376e65bbf30a6d4f9874
    md5: 0a79936d2c6c10489fac622c33b0ada8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ice/cice_in.nml
  hashes:
    binhash: 3454c3e6a44b63feab5a86c7ac15027a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ice/ice.restart_file
  hashes:
    binhash: aee6da949eb5749637474731a6c0a8de
    md5: 50efe22402f73c6742cbd0c3bdd116b1
work/ice/RESTART/iced.1806-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ice/iced.1806-01-01-00000.nc
  hashes:
    binhash: aa324276a081e0a3fad03a1718b3b753
    md5: 5fa15b23051febfe9530d93cad70a8d5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ice/mice.nc
  hashes:
    binhash: e939c08c2165319052c04c777b9f8b76
    md5: b9befe1d11d9eae658941a66112ce0db
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_age.res.nc
  hashes:
    binhash: cd24102490ebaaaf327c70cc885031d1
    md5: 93aafe8cf0360c97f1d3f825b64f5245
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: da19eb2f92e6c96f1ae76e5121fe3349
    md5: 7f449fdad886d5983ef1fb73f19c76b4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2d269eae0755213b3d24bf0edfe7b9ed
    md5: 299d757642e2e9edbd24f849fb2063df
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_density.res.nc
  hashes:
    binhash: ecca0e1f9d9c5065615ee24ba19966e5
    md5: 65ae6fe094f64def1f8795c67aae4537
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5a482803f7ac821a7e2a3c0cbb8e22bd
    md5: 512ae93721a7e2e6358c2c31c18bf443
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4df98efd522399c1d35b2384f81d566f
    md5: 308c441ed1938cfc09bea969c0456c84
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 223c611ede48238ddeb84c004da1e294
    md5: b1204268ebd5a37f687c9f151ceda246
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 81da50f606f67357275d38cf957c993d
    md5: 0c39987eab739d128895de1f8a41dfdd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 18e792e929a9972582955042ca5f78a6
    md5: a873dc5ae1b2b4ce600c9c27f319ad5c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 100eb3249ff6ce966ea3afce8797c7f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_solo.res
  hashes:
    binhash: f889c9540ec351404bc1c76a29511cf1
    md5: fff8f0522364b9f5fff0a497e1ae0f25
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a38aeb642acce6165227e7d25fac758b
    md5: f908679a5938229ba871e85663a5d3a0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 05be7d66f9e8b76f1a0ad052c6dc4d4d
    md5: d40b34e72894d22956e2233585d8897e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_tracer.res
  hashes:
    binhash: c289da82d5a528dca4d11d5567b6cfd1
    md5: 85058c7b3cd865eece5636a0672cdad9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 578d583862035d6962996800adb7f574
    md5: 8ff7e04a06d463597ab504463e5b125d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 06e1b4754c0274b492a971166d1df8b8
    md5: 4d54b65e252a65a08243c7a3675aa1b8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8bb6f87bfa847d4358538a1ba9f79761
    md5: c5616ede7db051307b0ef0160fc3bed0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart361/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f582d94f45cddbebf0b2a485bfed0209
    md5: 8dc1c49b73e3c3b6435a5b29385eca08
