format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/atmosphere/restart_dump.astart
  hashes:
    binhash: 9adae178ff87c4bb1f45e21ac0e74f67
    md5: 75e83d947c43dc1479a097e7293a869e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/atmosphere/um.res.yaml
  hashes:
    binhash: de51e31ac3b346a841c832ad2232f39e
    md5: 58fba90b2c5ed999c50a00392e8b8742
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/coupler/a2i.nc
  hashes:
    binhash: 2fe326e7b414fddee089f433d350e7f6
    md5: 0bc70e4b26c729ca67748183ce422030
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/coupler/i2a.nc
  hashes:
    binhash: 1778b358fb87038ef6b1b33e079091e4
    md5: b6881b69a4e229b447a9558100f7f118
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/coupler/o2i.nc
  hashes:
    binhash: 0dd8d7cabdc591f5253511b413f85c96
    md5: 42c7660ded517fdfdb3cab82aeddb3a0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ice/cice_in.nml
  hashes:
    binhash: 1e52e8b81f278207a7573e6f75f67a51
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ice/ice.restart_file
  hashes:
    binhash: f0c33d287fc0b52023b32e0484c8374c
    md5: 6b24b4bdc56d144557f7755aa639a70f
work/ice/RESTART/iced.1813-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ice/iced.1813-01-01-00000.nc
  hashes:
    binhash: ebdb8d16c669b49aff59b751810d258e
    md5: 9ab5f64bd9af7618bb48fceb1ad7cde1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ice/mice.nc
  hashes:
    binhash: b8a05bab2ab100771c674aa8c09e99aa
    md5: fdddc21595d9adc0c1239bb86ee2d4fd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_age.res.nc
  hashes:
    binhash: cce1c0697a19f99294f25ccc4d6b2897
    md5: 93728f3a0cec67c818170a7af73e4060
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 64f0cb8e11df7f01bdc553c2979e6600
    md5: b9d95a1b0f12f02ff988825da284dc30
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7f2867d7401dda67c920717555b8ab22
    md5: c62483de84cac467cbdca487883a5140
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_density.res.nc
  hashes:
    binhash: 8f978343f1b12631a8de3f3cafef8eb2
    md5: 326daff624c736e5643c3435962711c9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f5ad310034060da2ae7bed70634a0845
    md5: 6096bbfb00af7e6561e41e3c0e98be8d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b5e55c5d4e2bde160c1fb8dc98a4ac78
    md5: 18c54c2c21e0097a42efe2a9fca4d48b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b2327538edc6bcd18cb2853c0bfb011f
    md5: f34d31cbadc0eea812d4a8aeebe98054
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 31a151175459fdc3fd05ae151efc3bf6
    md5: a63df8bfcdd8e16eff42d59fc5e1fb68
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8d7ba8df360d9c5f76327e2f11631ba5
    md5: 99d348663d5e0f250a80dbaadeb0590d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 44ba033ee299060345c63245de83c46b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_solo.res
  hashes:
    binhash: 7c13b391fdb42756715fb283b631a96e
    md5: 0ded2ba88b7e7783a85b36cc562aa2a0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d2be334f6e013952cef6527511ae1350
    md5: 0c311bcb4c472e0b4f3ee96ba1abae8c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 92c99004927c7093b7ada53ed8d6a3df
    md5: c9e015a50b28a6b39f956de4f96a9a4f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_tracer.res
  hashes:
    binhash: 48aa251ea948aca1b46f6612603db1a8
    md5: a5700825353f4b338b8dcf59cd2692d1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f89bd996aa2e7f27b4cec2d5c0350a05
    md5: 9d3ef8497ec0e8d21092d6a385a25be1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1ff09b0fd182d7a7b981a9654433ea3c
    md5: ab6959258c3a36311e8449ab53bcc4a7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f0f51663c3b372cdb329596eec6e81db
    md5: cb85940ccd36e5452ebf3c94349381f7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart368/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7ceca350c9a2c5b5cb858be7ef28d434
    md5: 6585c8914cb49bda5347a3aabaadde53
