format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/atmosphere/restart_dump.astart
  hashes:
    binhash: 6b5eed6b04f89d484461fe7911daccbd
    md5: 23aef1e40cf0b46a7a81dd028b616ae4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/atmosphere/um.res.yaml
  hashes:
    binhash: cca1e358d2985432ea564b4560faed99
    md5: 3e7f12a253ebad5681710c2eb9fad7f7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/coupler/a2i.nc
  hashes:
    binhash: e501244987fd0d9ef5180c2fd043278f
    md5: 751d4e4a0be3f74422b613505c5194e9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/coupler/i2a.nc
  hashes:
    binhash: 0885a4d2877d7f8de19d368046a7fead
    md5: f9c1c7dd8c9e96aa599648db8101dbac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/coupler/o2i.nc
  hashes:
    binhash: b7e774545ee08d088a24187c7d6dfd51
    md5: 15824847169d765ede9e9129d4671b6a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ice/cice_in.nml
  hashes:
    binhash: 10be93356e6957ed6218bc29080c5e0e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ice/ice.restart_file
  hashes:
    binhash: 6777d3df4bbd4ae4e24f14fcdf3fcdc0
    md5: 78e2fa7e07254bfd74a93fbf0ee4eecc
work/ice/RESTART/iced.0846-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ice/iced.0846-01-01-00000.nc
  hashes:
    binhash: 67d411f8a558e81225676ec9d91d9c19
    md5: d6a85e7bd7e9c9c44158db744f499109
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ice/mice.nc
  hashes:
    binhash: cea5bcd75adbeb4e3d3790799f867c22
    md5: ac1bea2f2f3293f2b7cf8f4a09ebe3ec
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_age.res.nc
  hashes:
    binhash: 995d52628bd84f2104b0f976751b51e5
    md5: a99559de583e2354d8e86d72ab91a64c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 33f9bf7cbb1971f799b0dad5c140d7fc
    md5: 55d7505d84d06cce67052413865703a2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 84418ab84337d6b0bbb5e86de0040f32
    md5: 572712b7f7f87c2a94d377e659151fe7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_density.res.nc
  hashes:
    binhash: 5ac6f413e2f88309dcd12213786bd35d
    md5: 5db163ec7f9371cfbaea60c9c44a89a7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 290ad07ca52834a83cca51443ca058f1
    md5: b96d18f8006135abcdea7eac8c35f5f1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6e9da599b6baf26bcd8358693c45ec90
    md5: 0744c57403c192eb4b4f73f3a73c4962
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0600bd5459bcb1d384678f2f2620fd97
    md5: 4f1de969ccea4fd8b3e39554e238a5c9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: adaa62235918b3932128c45fe270ab89
    md5: e0eee31a043344a7a3c206f425819186
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c661fdff02c8d21a4f54fd92c31da7df
    md5: d7a4a75d66fd98fe40aff707c8474395
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3609c14312944839b3214c4150a6397c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_solo.res
  hashes:
    binhash: 7b9685c275a4c7bf915c011c4ccaf3be
    md5: 48040b4d3072f285751e02ff1e22baba
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: faca5210edca814e4ec0fea4adc5370c
    md5: 45a753e34dd5d1058cd22604df8e813f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bbef7988c9b79725ce961ee95beb18c2
    md5: b4a57f464299a4903561cde20a362a94
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_tracer.res
  hashes:
    binhash: 27db9eebe6b5d7102d953cb742dde7d3
    md5: e5c989899c104cec5295030c36199926
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b17c06222aca55612cc20744a255aa60
    md5: 6a1ee6d8f1d1254f0bf4c9c665838c36
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 46e2fc9391cea67527ef7a2638149257
    md5: 875e9d2c00519d00b6e226cef6b42dba
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b28e9839941b6ab278df30892276724c
    md5: ef88967d6d669b96093f549c75da96ce
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart292/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 69aa673e71820306e051dd6ff60ceb67
    md5: 8f2e563a693ccf5bde35d5f431c2edc0
