format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/atmosphere/restart_dump.astart
  hashes:
    binhash: a7c7f39e9e115eef3491949c063a3c8c
    md5: d998938e3a0e2c6d8190740945d13153
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/atmosphere/um.res.yaml
  hashes:
    binhash: 5232ce4b723a93f01291816fd02684ba
    md5: 1e35c040fc4b3557cce6857fd8ef5d54
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/coupler/a2i.nc
  hashes:
    binhash: db68ba2e85a15dd57d8844071ead18b4
    md5: a4868173cfe60b5836b4f88ee8d00e65
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/coupler/i2a.nc
  hashes:
    binhash: b90a5b96190ec4e25a462474a3978bab
    md5: 2453c913c0430dbc03c46879bca53ae9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/coupler/o2i.nc
  hashes:
    binhash: dc19b5e1d8a546d03be46d9b2ac5565b
    md5: 4286748a92399e9bc1859f3d418298ef
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ice/cice_in.nml
  hashes:
    binhash: 6a54179d7072253cde11deef303036c2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ice/ice.restart_file
  hashes:
    binhash: 7761542e287775f1fdb3fb8cc7ec19d6
    md5: 3ae76c368722ebf083ef35f58e66df5a
work/ice/RESTART/iced.1757-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ice/iced.1757-01-01-00000.nc
  hashes:
    binhash: aa87f1df760984e961566be7c9111999
    md5: a7fb53d5dd6ddf306b5ac17fbe4dca5f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ice/mice.nc
  hashes:
    binhash: 4e3b814f7acf0c485090bd808b4ae140
    md5: 2015db63040a1c9e3b35a39f1d9e5e8a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_age.res.nc
  hashes:
    binhash: 79f94152e67f7e8a522f1e9dc38266f3
    md5: ae5c1f981ee57ace22f725288a583a95
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 113339d642ba74c39714b19a7893f599
    md5: 41d2038ab21ed424c7d8d28f60ef7871
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9f8576a63602d31f1baadf5ad286e423
    md5: 2d133c5173d3c917fcc27fe87865b1eb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_density.res.nc
  hashes:
    binhash: e9c3f7c87eb3c2681b836e1cfadb02bf
    md5: bb23b3febf892a0348652804875bd9a4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a76c6430948a5db20398b6c86df9f81c
    md5: 8a7d3013751aa954dc693a0f3074c74e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2649d3f3d981c40af3ea05ff97dd2930
    md5: 80d4c78358d202d0d923546a0d9d4c3f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9d446e4e752652fb5989acdb50f0b34a
    md5: ba5208eaf333c24f1f048325d4388322
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4f7f3d5a5e5d5b8e7bc378f6f6451671
    md5: b45b0006c63ae677e8c28272b948f9d0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5594ea2b2119e86af9b6e31e47468bf9
    md5: b516ed480c704aa7f0077bbcbfcf59ae
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 78420e9c640e4e90959b3718ef32c7c0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_solo.res
  hashes:
    binhash: 632718b2a711da9d44ba99b020b0f516
    md5: 88932bb234ab5ec3518b55f7339de63c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d2cd9665b05ee9a3dcad7e106328d11
    md5: 39b233d19f3ae47ffbf72feaa5f5449b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b895b45fd424dd5d0e09e61790e2aa27
    md5: 42adc0b559bea067fcf084235cfa6f0c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_tracer.res
  hashes:
    binhash: 074efce64c7e927449b35d3fc520db49
    md5: 7c6a5f17bf42de481451171def2ca767
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 266443d124c7e816d32a048dfd89a083
    md5: 9e64e2902dd6be3ba6783c543597c559
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bec6dc1dbdfb49b40f5045b4d1982c7e
    md5: 56941508abf360ae493f207f66d9b825
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c5cd5e24cd187289f16e7124bfcc990c
    md5: 974df8b1ccf6e986cd3fc9b468ea32a0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart312/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1ee70cdebcf8c591972fe5e12d3cb7d2
    md5: 026f7ca9aad1bd4d09931996c88344c9
