format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/atmosphere/restart_dump.astart
  hashes:
    binhash: 75fe49b98f112d56f6a04964f8b1e2b5
    md5: 0516e417444f7658107db97f998bc571
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/atmosphere/um.res.yaml
  hashes:
    binhash: 687a4dee2c39c82f66b1114da5ea2c2c
    md5: 08db7bc86fc39b4a0a9f26387a350e04
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/coupler/a2i.nc
  hashes:
    binhash: be65f4b8ff3bae8132af46de0506e18e
    md5: 0d7d5640ac91eddedd1c1252c0a78af3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/coupler/i2a.nc
  hashes:
    binhash: daf1fcfc5fb9c06430fdabadfc071f94
    md5: ad952f06dc9540cce422390afa234caa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/coupler/o2i.nc
  hashes:
    binhash: c104a13a3577f258e59811e1795b6171
    md5: 66831f6fb2bc7dd30dbb2e08c1a89f85
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ice/cice_in.nml
  hashes:
    binhash: 09ae6ddd9a1fd6216f1f43e4aa3d4d70
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ice/ice.restart_file
  hashes:
    binhash: d30e880c4642e06eb6644838b66ff89e
    md5: 594553425421b94397ea9b02546a1187
work/ice/RESTART/iced.1175-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ice/iced.1175-01-01-00000.nc
  hashes:
    binhash: c8e9a2f24a73fbe9cb9980f35ec38d18
    md5: b108de931d1276df2cacdcc112c48ae0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ice/mice.nc
  hashes:
    binhash: 8fed1e5b8356eb1cb352b528c21e685d
    md5: aeef63848d344d833c81fa0766b2c823
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_age.res.nc
  hashes:
    binhash: 9c4116055afc5d52be2e5e2b9c3c9680
    md5: 438a0e198f1ffb98b97f434db1f82271
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b941f2d5894cbcfd449eeb4264472581
    md5: 2ce833b7bb32f10b12b80e0f780ccf1c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3e50089caf4c359502b0585956514c48
    md5: bb76c4cf67ea688ac21c82fbe8f813f5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_density.res.nc
  hashes:
    binhash: 3c0688b1b9308bea9895252af7518e55
    md5: 7ab12426459d7e7184c823f34320be9b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c0c44ec79811561f86bde1b260639d45
    md5: 55f3c7fb44e4fe4bc6db176822dcd6fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7e06ff3848761e361a887f64e5111586
    md5: bc1c408975d76a60c72ff6c067374768
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e154131aba00f6fd7c060ec2e2ab1b26
    md5: 073960bf7dc2eb2894fa9515d172be4a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5e02f157b47a45f0afb3ecc13a0f2a63
    md5: 141067234bbd81a2155be04550d78c86
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 68145dbd65686bf57b502d1b711f1e5b
    md5: 5aa89b8a9a4e0a1d56c1dc99208723f0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8ea37522816e59324cc910a82b1d67f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_solo.res
  hashes:
    binhash: e176cc2100d5066c59cde8ad2f917345
    md5: 124ed06775702a1c0bdc73ee7e1d6a3d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b6726ce934221a1db9522bef0284b1d0
    md5: 37abb6d6f817596e23ff2ed2dfd74826
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 64ab3cc4752ee885fb103131c7806450
    md5: b5c36369967e19774af27e6660d1d9cf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_tracer.res
  hashes:
    binhash: e7f6cd5ed9813959204b9fb0885e81a3
    md5: 52b5c17c9296b262b7a63b555f5b6eb2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5b7154766b93e759d6cb13afbf90360e
    md5: 33e3227b6ec5a7245712ba21f3d17f12
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2ad003ac524fc9f87f9fa547bc2d6d1e
    md5: 6046bbd803c4670772993a8c18ea7c8f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ac369626fd981a5d63961df7d5a462fd
    md5: 52d280ac95ea174e88542b8a46421566
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart291/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b03de7f8be3fe8d6c7b81409c90a0b42
    md5: 5a5d8a8ff91348c9c3f757082a58dae7
