format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/atmosphere/restart_dump.astart
  hashes:
    binhash: 3fa29b036f9a91499c1f5fee9c9ae8f8
    md5: c999d301784a14a5fa1644cea758747e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/atmosphere/um.res.yaml
  hashes:
    binhash: 2968beaff36f3e20b3476bb8fd613ff5
    md5: 9102fde4336d0bbde890898adbc57505
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/coupler/a2i.nc
  hashes:
    binhash: 0de641bd098fa67a78b66723c894519d
    md5: 9380abbd2001f69fda711a29ce4cd453
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/coupler/i2a.nc
  hashes:
    binhash: 605ee56bc30be9928e89cf3aaf89aac8
    md5: 8c033f36e134236b53d199c6f7bea08d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/coupler/o2i.nc
  hashes:
    binhash: 7bc667f59050e1cb8b5c0ceadd47fe52
    md5: ee2176df4a9eca7a6881cc97466c0f2d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ice/cice_in.nml
  hashes:
    binhash: 6f01186187b44fe78d5fe411fa962b4c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ice/ice.restart_file
  hashes:
    binhash: d7b6afc15d931068db613a1cb4b6ee8d
    md5: cc71790e2815755e68e13e4c846e3154
work/ice/RESTART/iced.0917-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ice/iced.0917-01-01-00000.nc
  hashes:
    binhash: eece21c2cf2de5aa5df7b58f15d3e258
    md5: e0c20040235f6e1aa197678bcb9bb9a3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ice/mice.nc
  hashes:
    binhash: 1b69be7b73cb670b3583f9ab3ad49d66
    md5: ab9e327645f51be2557e3ae7714fd0ef
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_age.res.nc
  hashes:
    binhash: 611bd8fa08215590c753dfa06d9d6c15
    md5: 04c1a35567f4790206f120b182deddac
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7ed55ce50f55b501798ca098be055522
    md5: 1fc82878024ba125d289bb66e4926732
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7889d6ee48d65732cc7e0fec12c24df6
    md5: 67f547320bd19520978f993d7e7f5d4f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_density.res.nc
  hashes:
    binhash: 231d908d2ccb73219fb8d1f8e6c2a686
    md5: e4e9ea1d0039e7d8c5bb8871598f4837
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6ec7f989c369f254c09fcc76f0f29bee
    md5: f21d716760d1ef1dea17915add1978b3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bdc0b1e5fbfe6d1a3434228f23d85ef1
    md5: d60867354193e487807cee1b4d9d8f4f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8cc460aedd6726f6ba23f482b7141cd1
    md5: be97d08fdfab50429d47cbdb13f29e93
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da6c61ba88c41eb019dc56292cac47e3
    md5: 20cceb0ddd808e61747060309f3897ac
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 65f10284ab04ffd87594170f67e0a46d
    md5: 35b127bba6e4dd0c997445c5ecf44f22
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 148f08f2e1af57733a22b80a58d53ff7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_solo.res
  hashes:
    binhash: 127d9bfe8e754dfcf4dbc7868e9a4d0d
    md5: e96248bcd04f7ee6896d2add265bbcc5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 91600a5d488e0b1dd88bb94f29f1195c
    md5: 914f74ccddb5121f18613f09bcc1f820
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 54fe9fa9678d4faf587b7b847c53f280
    md5: 6de49ce7352962013d2d569f4227361d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_tracer.res
  hashes:
    binhash: 889931fac7eaee576b5154d9ae895f71
    md5: 9ad6999865afb77120e87f516fb9fec4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b67522dd8e0365f1a5cdc04ac1d92c66
    md5: c150850791992063fa0cb9605adcc403
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f18d07939a729866936dfb8920467646
    md5: 46fe84a9c573df46fd225096bc8f1b14
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3612097a4e48f1141d73b644c4568bbc
    md5: 8070194344af5f5d05af15095dfb3065
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart363/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 77107b1db1c010a6d4039a358040c84d
    md5: 10c2da44bc79b14dbd3ed74fa0b57496
