format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/atmosphere/restart_dump.astart
  hashes:
    binhash: b68354c4628f283a9beccdd82cbfb2c9
    md5: b627fcda7df645c1b054693e8c6f7287
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/atmosphere/um.res.yaml
  hashes:
    binhash: fab5ef511e7d14c73359dc8d935822dd
    md5: 85301529d27ab43e645683a8ff7f672d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/coupler/a2i.nc
  hashes:
    binhash: 5299dce3756e4be3b494193fdee00d1b
    md5: efbab63135855f38f04f8189e2281d4f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/coupler/i2a.nc
  hashes:
    binhash: 06747beafcaaedc0793a3d03c947fd9a
    md5: 58177b64a11bdbbc1a0d8b74eac20fba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/coupler/o2i.nc
  hashes:
    binhash: fae5fa4562ae1a7238ca4e06372d2494
    md5: 64d55acfc0558e0cfbf25978656405a1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ice/cice_in.nml
  hashes:
    binhash: bda67bff47f496e9d2304c5e7f4cafb4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ice/ice.restart_file
  hashes:
    binhash: 673428f3eec8a5a0543233885a9ac969
    md5: 19a6e0811c16a33e3cf565719597198d
work/ice/RESTART/iced.1207-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ice/iced.1207-01-01-00000.nc
  hashes:
    binhash: a9e44f6181f50ded9aae6f4aaa02e9c3
    md5: 06bdb2f7370fd7848a214d2bd383b6ac
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ice/mice.nc
  hashes:
    binhash: 2febe055fb56d6598766414805bc63ec
    md5: bdd287e3afb92cccbef1c0c16a74fc2d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_age.res.nc
  hashes:
    binhash: 7f0f707977d4dc2e775a8fee7b469445
    md5: a38ea15076ddf0237ed21565598cd51e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 790eb5248b6bfddbcc38af6a68ed8420
    md5: c04b5ca48ab0ef406e801f9e6ab25c96
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b1d7bba5885b5e5662132165e41c8f54
    md5: 6fa260ba84d73000551f71fd65bdeef9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_density.res.nc
  hashes:
    binhash: b03bf3681ab42580bd7f8cfabee38dd6
    md5: f841b0fd93d918fb232537bb5d389d5e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 105d8e5140ceb474fb962e046ee0d0cf
    md5: 6ee63b7248a55155c586b3f7b528a4bf
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 128845c02c8af689dbf10cdf51d77db3
    md5: 0cb11826314f28f7583c9cc611782c5c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 29f3821515918fd5783fade3cbb39609
    md5: eb18daa12e412493c996062ff2d87e00
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0a378aaf66d3c04ed4d691f762150b84
    md5: a3723863470eb1113f29507e2ab70609
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5cee0090aa81debe30e200dc33fab647
    md5: 5a3a0157792ece49b83e21e420f77823
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ba7ca334f6fcc08a251a109dd06ec01f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_solo.res
  hashes:
    binhash: 15a0a1809b19d1920753fa9afa1b880c
    md5: d43e727bdfb71d3ab07f0cf7ccadc3c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 346b5fa9d1cf0c2ef5409bbc422edcdf
    md5: 8d91e85887419593a3aed01cd519549f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7d9335b0647828dfdee576091e1cea1a
    md5: b5b874ae93b89d4841bd05d9befa5b52
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_tracer.res
  hashes:
    binhash: bbc9aab539ca15fe78e8c04b41cb7a29
    md5: bef8ae5edd765ccfcbaa8856c26ae1a0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ce11414302f1c01d81e5c1dc98635036
    md5: 5e343928bf228b0523bbeb4e03929d2b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7a69706d3dcdd9d69db6ad815dd251d9
    md5: 5060b95606d55505beef40b2de940796
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9e022917d48dfe26095a8861286c07d5
    md5: aadd35524e6c1ea3cacb976c42ab9c26
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart323/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 714461dc5a95d1ad4f8210b92e43dc02
    md5: 02d0c219a2a677b5afdd990a6e7209e4
