format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/atmosphere/restart_dump.astart
  hashes:
    binhash: cdcc839080d2b75ee03cfe4322665ebb
    md5: 33afe202b529c17d0bfa306fa400c425
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/atmosphere/um.res.yaml
  hashes:
    binhash: eaa2c31c83dcf333f5d6a1cb030929a5
    md5: 60f7caa96a9830b26aa8127fd6609fa1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/coupler/a2i.nc
  hashes:
    binhash: 4fef612c651155bcbf604719979036cd
    md5: ee97d5f6a3a0b4557f23b8644f3d8316
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/coupler/i2a.nc
  hashes:
    binhash: bb292c473503817017349b45b339e545
    md5: 81d76d96f06886e7a017c3636a72cbb7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/coupler/o2i.nc
  hashes:
    binhash: bd5efffbbbe50a706bab592630e40eae
    md5: b25b7ad3154ed4f7a33db597b6c28732
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ice/cice_in.nml
  hashes:
    binhash: ce316f88c645901b905ea88cec346308
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ice/ice.restart_file
  hashes:
    binhash: 2a601419d6b959478eb5ac2cc0786f5e
    md5: ddae75309b101453bbaad8cb1ec13d10
work/ice/RESTART/iced.1220-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ice/iced.1220-01-01-00000.nc
  hashes:
    binhash: 84895fbaf45740573f069c11665c0488
    md5: 5b29eb8a9f6c0506c1022a676ea7a148
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ice/mice.nc
  hashes:
    binhash: 40416aab619bca63f3705d988328f886
    md5: 893ac63fde4cdff1c954dae922db52ba
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_age.res.nc
  hashes:
    binhash: 087ae53770c2cb8c31818aa55e2ee27e
    md5: c35e2ab6eb25ffb9513de00d079836a6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 72fdfeb0e338e789d86c6b52aa7c57bb
    md5: b44fb952893230143c70a202ab488117
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9adbbf7b8e427ad9565ae1db087c7a4f
    md5: 824a7dcc5ce58e2e7a6c809c0ca78942
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_density.res.nc
  hashes:
    binhash: c230e640d56d61d17163e92116ddeeb1
    md5: a6fd2f50627f4441c8225f118ffab457
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b480ef30de2461f19a3eb4bedc0ad0a9
    md5: c515113b1f2c04f651de6e35b4dafdb4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 22044f99386fe877afcf873ed824a202
    md5: fee4865511e92221a4639479faee0e98
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1f4a1487d0377fb63d37464a17caf249
    md5: 6d87350225edbc48733bf0764a4e17ec
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d643cfbe710c67fb2c5190cc469b1bec
    md5: b148d50ae7eb93983a8e6cc58e4fa944
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b47557524c5efbfb89ef62117c31cf5e
    md5: ae62c96cdff309135ca246ada58fb03a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 61d414c10a1cb1323132b940aaf8f740
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_solo.res
  hashes:
    binhash: dabd0518061067dd847e97263e8f08e6
    md5: 0b44e9c3d8ecc72fdc1ebdd87dc2549d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2037f8b672e1134d7e64b86718e988d0
    md5: 1c3ff1a7d8ffb26b60c6ad8f955b9772
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 953899e1893ec9d1638de89e0f814e59
    md5: 0b4c7812d3bab5c9baafa446f0a95a67
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_tracer.res
  hashes:
    binhash: cf425d1a7c9d69958484564cc537ab97
    md5: a9f666b61658cfee6260cafa5e3b6e7c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dda93114aab63bbd607a9e89d6f393fe
    md5: 08c59c93f163cbee7da582a0a38a9e36
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eb7f41961d85ec1c9c6bf0541b6410f2
    md5: 1af132a28dce6fa116bbeb8e4e2286e9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 889dda4f73e41bcfca4e7514004d4b6b
    md5: d3ff258fb0a9ac3e5a9e9db6f784d9cf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart336/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e2f668c749f83f88e72ba11b529062db
    md5: 1fc87afa47da0e6dd884c72ca08ea41e
