format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/atmosphere/restart_dump.astart
  hashes:
    binhash: db3c09d160d09f6918d5c0fe132fb06f
    md5: a6ecab4b52675ddbe295fdf7463f35d1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/atmosphere/um.res.yaml
  hashes:
    binhash: 9f52c5caabe45b8a867991336cb4d219
    md5: fc4f85ae932239b9752fa5a38e48b03c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/coupler/a2i.nc
  hashes:
    binhash: 3d4f0a8a2f6c428c2ebfe339d16c94b0
    md5: c5674d50dbedfdeae5fba4865b31006b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/coupler/i2a.nc
  hashes:
    binhash: 106667c1ac492bd8868c51d3266f9ea8
    md5: 200f25ebcfe033acafa79c87bb633d3b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/coupler/o2i.nc
  hashes:
    binhash: 3d1de6c5e94e38240501a9879e7da909
    md5: 10a2a224476fc026c0d79649fc36c6d9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ice/cice_in.nml
  hashes:
    binhash: ca5c205cd229d86df779e220c7df3656
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ice/ice.restart_file
  hashes:
    binhash: a7cbda8e3c0b55e27fa8befbc1c870ca
    md5: dd97ca76aa2540f5e5260170b2c02ef1
work/ice/RESTART/iced.0973-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ice/iced.0973-01-01-00000.nc
  hashes:
    binhash: 366b8bb4d180d8f2f5e7fd63111d35f4
    md5: 5cc2030aabf1f00b7e37718673015448
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ice/mice.nc
  hashes:
    binhash: 15a6ef18da20afc6e8ee5edf78dd54cf
    md5: 2b038e9d310f55ba16264625e773e927
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_age.res.nc
  hashes:
    binhash: 4f3c5bdc8b8207bcf19c0aa9893017f0
    md5: 1deaddca6e40e393bbe095693d316b10
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b7585e8b3b6e1c42bddc5e87021a15eb
    md5: 4310c2459c5b4e0da39c2a293277d81f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a5bd4e887ea2cfa6c7c0a9f253b19d08
    md5: 9b9bedb62745c03b59387a4ecb63836f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_density.res.nc
  hashes:
    binhash: b94f4732e0ef5bd86a31a5aa79207ea7
    md5: a571822fa6fc58eaad728d201e01f702
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a7333c93daccd7bd4cc9443be2ca282f
    md5: 0a916600b0aa80aa8bc139d8288683c7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e06a7563011009b06d5ee3917dcf6fce
    md5: 72b49ef2a093b092b0d269faf7692b55
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2c1a360191d09e23988e80b798c66fea
    md5: 76c8127867e6ebf94a121b56229c3f7c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 925729b60b7f5a7cb749c607ccaa409b
    md5: 4facfd66ae792c2fa8b21a0c5388c16a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0b6acc87ba6f5e582305b43fa666a58c
    md5: 3faae091738e20d5664138d5f8319a49
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 49dba4227b12265ad05412bfaab97c2c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_solo.res
  hashes:
    binhash: 64a557b42dca3f3ba9564c3f33de3c83
    md5: 29ca2f3ae33b4215202501f494ede54c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6216a8d3eef7cd2ef6225d761a48ef84
    md5: a35c0a9dc9083350bd41351dffb23f1c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_thickness.res.nc
  hashes:
    binhash: af4eabccf151bf8944c2274c02faef7d
    md5: a52aa4daf7bae066863ae4432e7cfa0c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_tracer.res
  hashes:
    binhash: a32cfef8893df46f47ca287de991baba
    md5: 48ed93a7b1bdcc366572309130d1aff9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c0fd17cda4d29cf8383e8cc3dee7c59d
    md5: 149929ccd0e55d4a4e3a6f5d36010d77
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3102d105913815083f89f75dea9bcfc8
    md5: 6b61acb3992bd6138fee40d8cdfbc269
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8bc8ba4396274c92350d288cc78e8e5b
    md5: 2e4dbf8085dcc23ba1db9638e6d5d5d7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart419/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5609d82447d85c65297a098c7af48d04
    md5: 75a66dbb9c20e2938db4ab8e59edabbd
