format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/atmosphere/restart_dump.astart
  hashes:
    binhash: 2afe17995e06e1c2ffee6e4db067b290
    md5: 6360db1b23c12ed54ff0eed30a4f197f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/atmosphere/um.res.yaml
  hashes:
    binhash: 86ead9e491b460104ac72a4ddd40456d
    md5: e07c7ec68f2ebc9c1ec195e8d0c216db
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/coupler/a2i.nc
  hashes:
    binhash: c7625232ed9ec7f9e132b3467dec89db
    md5: 8e19ccbbbc781b2ba1f4c4a7758d4ff8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/coupler/i2a.nc
  hashes:
    binhash: 5d1f600cedebf4626203fbc5f349b09e
    md5: 07b5dc7931650ff9ea5fe6a7758bb646
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/coupler/o2i.nc
  hashes:
    binhash: 0709eda52379a32038b146911a6dd1bb
    md5: 8651f8f56b9ded5b3cd2a2e8bd4f2d55
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ice/cice_in.nml
  hashes:
    binhash: 3047637647b7d6c6ddf9f7330be481a0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ice/ice.restart_file
  hashes:
    binhash: 0a4f8edf4fb34f6a8ba181a52ccc01b0
    md5: dda850108448e86ac607e32cf95cd244
work/ice/RESTART/iced.0927-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ice/iced.0927-01-01-00000.nc
  hashes:
    binhash: b4dea9cde61b02282724619daec83304
    md5: 341ebb7a4d1af85d559d755754d1291c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ice/mice.nc
  hashes:
    binhash: 6feec94a5e385a54ba438bc023b0e087
    md5: 13779f5b4a8ec3bb35d4409c6dd3e5df
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_age.res.nc
  hashes:
    binhash: c0084483606f2705826420d4222a4595
    md5: e86c2d50bbea9938de8dd75a74a8d33d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 34b7705e47bbc20b819d0893389302fa
    md5: d4b3b273d5c242d8a45869a7e448bf3c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7df19dfe6f181e1272dbf53dd0fc1ad9
    md5: 70c7cf8082298995494744c29962930d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_density.res.nc
  hashes:
    binhash: dc53fd459f705d656aa763e631a1e149
    md5: 3d8ccd5c8750f8babebed79585c7a437
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e287f1f47d9668c0677ed848a0c9fc99
    md5: 4eaa8cb7d9705363b3814edefe6c0f3b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 19572ba3155c7ebb0c941b42513acf69
    md5: 2ac7259f71b90beb1c410e3eb16dea7e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 05539ecdc5127a3518b621eae08ea05c
    md5: 7e5366234b0a8758986349a2570dd78f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 300ce384e466e89d6d0b893fd473a40c
    md5: faa54d8aaad2474d23e1752aa66fe03d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ca472f319817956914d272d72d766926
    md5: d33291effe87ee08ffd19e6fe1621ce6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c89867c5e74a7aafaf6cce180882d384
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_solo.res
  hashes:
    binhash: f0b17cb07853e1e584d6a179f5fd58af
    md5: 2617895a9fd593a37a08c9ecbcfd251e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 66255a669ce02d407c642a4ffa5e2031
    md5: 7c946df87da7b94424d47889dd59421a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6a561d173d175d1ab07a5245b7e15fcc
    md5: 7a3fb29bde1b4eea0387b58a36e99380
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_tracer.res
  hashes:
    binhash: 82c094d06cc36c35216990529ec6ddc7
    md5: a058920aac01811bf9053e652932df09
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 656f925fa9515deb068e3ca8ed4a5cc5
    md5: 8456cecd96766f338eb02994e795bb8d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b179579e68066022d3815ba1e47ed9e5
    md5: db7f4f461a300d3e79feff251a78a24d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e726befd493b6acdbc9a69d9359cf33f
    md5: 8f581ca63ff22b01d5335de7d9164bd2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart373/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 17368689d004e5a9782c545f1bf7e9a7
    md5: 2a0e264ad681a92362b10544eac6d097
