format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/atmosphere/restart_dump.astart
  hashes:
    binhash: d233b142950827db8fafc20cc05b502b
    md5: bc57dea9c78fd35090e352ee24d45656
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/atmosphere/um.res.yaml
  hashes:
    binhash: 163082b5ed25ad24c62bf16455766b4d
    md5: a08cc2a3f69933b4b3bd1d288ae60de3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/coupler/a2i.nc
  hashes:
    binhash: bfa961c9562d66818cb88c196254a3d0
    md5: e45c26124b7261adeb76f1f5c8e9b79f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/coupler/i2a.nc
  hashes:
    binhash: 53e3afb50969478b6422026a568ff1b9
    md5: 19745e4b8b3f303258ca610e4ae7c8b0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/coupler/o2i.nc
  hashes:
    binhash: 1654ae77d7eb00636ff2a29a22720c51
    md5: 8fc273d66d715ab25d9051662fde1e52
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ice/cice_in.nml
  hashes:
    binhash: 2c8e71f539a2935757ddd83cfd6fed3b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ice/ice.restart_file
  hashes:
    binhash: 4872a4bc1cc161e67f5a86245ed01671
    md5: 3b43ad312d90bc7ca057acac53ae8e8f
work/ice/RESTART/iced.0900-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ice/iced.0900-01-01-00000.nc
  hashes:
    binhash: deb02031d3563cc1c7799202bcf3145a
    md5: 29728107e1273cb2a386c36fe792ae5a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ice/mice.nc
  hashes:
    binhash: d26d7f2bd02d5ec2e993df146d4143ee
    md5: a6feefb6024d96a28095c6e0a5f0c993
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_age.res.nc
  hashes:
    binhash: 4a77e653a62aa0caff9237c64f6d87fe
    md5: e27a45d95739a25cddda25c223968820
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3a15214aad495487ddec1eed7196b1ea
    md5: 077763a93dc037c315a0a762ad1063db
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5bd36686f251aec60ae4f8213d3d9b3c
    md5: d5645bf662b250fa190a70fe253353e0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_density.res.nc
  hashes:
    binhash: f59e45aba26459645aa6edb32495f5fe
    md5: d95cbf72b9b51c34bbcbd25cb96cabf5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 60d570111567c7c6f945cbef5be4c951
    md5: 0b8c4119940770ec39d7f344d994363a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0bb95082a2e7fecd30007120b9206ca4
    md5: 8500d8e5114de3ed51d868bb12afa9fa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6c1452f2043574f564bd7869a2cfc624
    md5: 93ea27feebd87e71c5d1a9a1f0df7f34
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a43b3bc518ae8ca3c6d0ee64f305bfc1
    md5: c771c9a3e522319862c6dd149f996e96
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 86971e6430094ace8b3dabbcf42833ab
    md5: e255615fe1b50e0d0b6d5294e4da683d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 80e1cc3d37ef05ad208b813aae063897
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_solo.res
  hashes:
    binhash: a071b331a5986a3ed6e247279890f9d2
    md5: a73e88b0b757f764a9b63c4163f0f76c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c987f3a351826b8e5695d40e34ff4ed6
    md5: 9620662c4bc036e73dae2173a6b857ee
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce2bc74d81270e8bcf324000d236f2a6
    md5: 38b05fd99723718d9edd175fde5db0fb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_tracer.res
  hashes:
    binhash: 5cec7e929b59b5a4394d06a4f20f3586
    md5: b7c387d7eac63b2917f5a06e22ff0e2b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2571e8ae0da0c94ab54347c6de2067da
    md5: 7ec3b4e3e3b5746a542624f785a315ae
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 85088982917a22c40dbf9c6d7cbf693e
    md5: aa01955efa0355b9ba52cc5875db8f93
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4454bfd028b29632750c7c47585fc2d9
    md5: b8e178245f2265725049f3de48d66eea
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart346/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b28c8d4fded4f5b7e9f6f3fb5d9f38ad
    md5: 7ebb3e5f9bd1e80aef3d82b71ade404b
