format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/atmosphere/restart_dump.astart
  hashes:
    binhash: 9ef5c0922827fe452ee40b9fb762434b
    md5: 882836e8921a3c3c80ddfbf3d3db9f5f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/atmosphere/um.res.yaml
  hashes:
    binhash: e6c11d17db1f70a4e0b02032ab9e49f6
    md5: 715d361ad1ac8d1fa6d116de6bfd123f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/coupler/a2i.nc
  hashes:
    binhash: 5ef2b90ad66688935f7e3bc330bab75c
    md5: 774139133100483ed57428f6445ea8a2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/coupler/i2a.nc
  hashes:
    binhash: 809c8a7931e064e2cd676c22de10fdd9
    md5: d362592868878cb17543037c3167b7bc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/coupler/o2i.nc
  hashes:
    binhash: 32d667d3f6794c9b24c7c5c421be88e6
    md5: 9faeac3b23c4699b84896026c854566e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ice/cice_in.nml
  hashes:
    binhash: e025bd7ab3282e950e1ff861dfb5fb07
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ice/ice.restart_file
  hashes:
    binhash: 17ea560c24f33ace69943df57e4790b4
    md5: 547ab879c8dd4c22719e1e34db93146d
work/ice/RESTART/iced.1787-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ice/iced.1787-01-01-00000.nc
  hashes:
    binhash: 92fd6ef34eb1c0841541cfd385f810ef
    md5: 6ff2efce63d1cf1c32d8d80649db0669
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ice/mice.nc
  hashes:
    binhash: c63b021a936ed5bd707a06be275b01ce
    md5: 870d790f7c711968da664376a7484077
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_age.res.nc
  hashes:
    binhash: 096ee41e5fbe176b07a57dcb6dbd0fbd
    md5: 05351a7950754e9b5843354f40978313
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 296b7a66b204bc72675e9250e9cab3ed
    md5: 74f8ed63e7addd5dc805ca5530caa76a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ccccbd4beba3ba947e3c6f319d0007a2
    md5: 138362963f5699943abf9d79a3f11f1c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_density.res.nc
  hashes:
    binhash: e54ae904c5349fa55c2804b659af8144
    md5: e61fea1289b0a5b654a703da4f51abc9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f536817815be87445845de78bfbaecb4
    md5: 5b105c2a5a1c8ff5cb6e808b02ee0910
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2a414ffa0d2f0ce734e7fa59a6b4f0fc
    md5: 88c5dec74a42ede36ec1efc4c25303ad
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ec0576ae33122f107d5672b7018862c5
    md5: 4f95a9b49cfadd99e9c30971f9f7f2b1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b3629a657d8b45eff288e7d1f8c0aebb
    md5: d8eb4af4e864cc6ebea3be2b9ca81db3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7bceed68194e972c27b8390ff4c6f853
    md5: 63e6a971e2c1beb634b2413e98046f4f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 717075cc6ae8cedad2d665a660af0826
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_solo.res
  hashes:
    binhash: 6fffeb3bcfc66520e76fbdef9c3a4149
    md5: ae1d826e8cf50f3dde287ffa8d2152c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d3211e43000a75e3f3a1c8a15ca73c7c
    md5: 52fc812b662ac72242283d0796763416
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 04cf13d5d604e38a8b02cbf5a5aff8a8
    md5: 2a6f7853debcc0b983f0e9e2a4c9466c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_tracer.res
  hashes:
    binhash: 9e07b950b1c03e92b884ed4918bb684a
    md5: 582b91e81f1f8e79d7012a0a6b793c7c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 245e59355797a11ff072d4e653dcf5b5
    md5: a843f009453287a24e091719ac3f4525
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: af1797785e074a6c9a2fe4f7795ee3af
    md5: b2a44f3803935c259087d865f325eca7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ddbba3af627a6a7e47459256d36c4666
    md5: 1cbad967b54c2fe5ef2a43dd05a2a37e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart342/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f5ee42675d5b995f9edcc01a47171257
    md5: e18d32cd885e5c3dfe5953a1904892ea
