format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/atmosphere/restart_dump.astart
  hashes:
    binhash: 3288fa2cdccfcff14afc1f12453defbf
    md5: b3ec1159f51bd9042b21ad42cc97ddeb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/atmosphere/um.res.yaml
  hashes:
    binhash: 00f58ab99ea87cd232ae7aa40c154b99
    md5: 55b4f21f0fa69d474a6d3ddb50c63de1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/coupler/a2i.nc
  hashes:
    binhash: 8de8970e045be32bc015cde5fc67de7c
    md5: 13c12b7ffb2f58793d3214924498c758
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/coupler/i2a.nc
  hashes:
    binhash: 7c2be776906568ff313cbbd09aa91f9e
    md5: cc2e0ff38e06c51a7ddf8f42b947e6aa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/coupler/o2i.nc
  hashes:
    binhash: f53f67a1fcc3d7b8c04ba6c1b88a1856
    md5: ec627249de8758fefd6c56f37f8628eb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ice/cice_in.nml
  hashes:
    binhash: 8305ed7d6f073f72ee1965797f745320
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ice/ice.restart_file
  hashes:
    binhash: c2717061ecbe34ae2e99c0fad9d1500f
    md5: d0bb2a2754e2db7ca19ba59d571eb8a0
work/ice/RESTART/iced.1760-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ice/iced.1760-01-01-00000.nc
  hashes:
    binhash: 089f208010a0d7fdeee10c352d35ac19
    md5: 3c50b15c0d5990a24204f764301ccceb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ice/mice.nc
  hashes:
    binhash: 84f6568bc3045d6f52072ab87588c500
    md5: 0220aa01f6d00bdef5d5804ad114ae0e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_age.res.nc
  hashes:
    binhash: afaa6aec22f8194480232f462549bc19
    md5: cea0e2de1c3d5dc391af9452746fbf87
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 40548235b78f78232fae8f4a6c6928be
    md5: 2addefb82e7fbc1900ef5844e9de8965
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cf29009022859f373beec2bc120033bc
    md5: eeaca57d3c56101bd20341c22478643e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_density.res.nc
  hashes:
    binhash: 9c5b8f0631c0740a16ad754341557dbc
    md5: 165017234d9bf2fbd72460b35879c5c7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1d4ce0512439686ad4026c855520960e
    md5: 827b79e6c7fa78c10a52640dd0310364
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 32e55c988bce36304e09d679f7afa3d6
    md5: 088902db82d53e9f734c4bbb285903be
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0f8eb4229529a9784b6328d20d2b5eb5
    md5: 1fdce32069347a72649b6a43f590e383
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 682849c5e33989fed149dd617f791625
    md5: d33fb20545b5b0e9732550c796741c9f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 612b09734981e875f90fc2d1dec2d0c9
    md5: c9d10efda1b5b5642faa5b1e6d482994
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 713d89ad47af9619d225bbbc420cad0d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_solo.res
  hashes:
    binhash: b0ccda57012d7a627ae928e5f2dab5ca
    md5: 97282df599a0333e7408c4ca8a14509e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1027c3d8ca2f4b0b5c90d2156f6e2780
    md5: 973e6161eb9595f5622bc2a53785e12a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 200d948183c12dc30d15e60d784bf00f
    md5: ac568191f6b260c179ec56d4637c6cc6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_tracer.res
  hashes:
    binhash: dc8bf5ab453d3c77e790bcd826d09bfa
    md5: 83e55b3ad062412f36bb70c951952b8b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d01b364c1daa31af6e58339f3700fa78
    md5: 782f7f9837f6447355b5c35d6f833d21
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7b116ff320aec107fd0ced4cb2f093a8
    md5: bc9e924f3b8ad0ca44f6e8c85ff22fba
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 798882002891bbc147299fb80846e840
    md5: 7d03ee3143f990668a709884f33b74ac
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart315/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3facef968d2c4ad48d19cbaaadae9063
    md5: d75bfd61732f1e671b724106a3010bf8
