format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/atmosphere/restart_dump.astart
  hashes:
    binhash: e39a52be2d7ad164ad59f6992a190f33
    md5: 87131ce598be3bc723f7b52f868060dd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/atmosphere/um.res.yaml
  hashes:
    binhash: 309c50ae983d017c0cad6b6443e5c7c2
    md5: c9a7605953d0a33f8980f5f829f6db3e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/coupler/a2i.nc
  hashes:
    binhash: a91d22696610b7d60c18a6b82ea084d0
    md5: aa7ebba083fa673f2f0575dae3b2f2a4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/coupler/i2a.nc
  hashes:
    binhash: 31eebc898b84b808053e1cac3ca32151
    md5: beeb7b031151506a42fa91c04f76145d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/coupler/o2i.nc
  hashes:
    binhash: ae08b2308d3293ee531dc5f05102f940
    md5: 7e3d8dc66305a98d1f36a2c4676ace4e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ice/cice_in.nml
  hashes:
    binhash: d93dab452f23c36ef708ebfd1d398b0e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ice/ice.restart_file
  hashes:
    binhash: eff71d2ae78bc8bcbeb1e6e06e1ed222
    md5: 38dff7f288d81aeff7978492b04ae80d
work/ice/RESTART/iced.1829-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ice/iced.1829-01-01-00000.nc
  hashes:
    binhash: f388e890eae8afb2e8ae3e19ccb0eb6d
    md5: 0e07494bface7563d034738de42b6257
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ice/mice.nc
  hashes:
    binhash: 4cfa25221a9532fb264dd50a16213e5c
    md5: e0bb4a2bcfc01513df28313fa5c30d00
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_age.res.nc
  hashes:
    binhash: d68c3679cc56d2402a6143e82ee168f3
    md5: 10cf5a711545989dfe06f07a4bc25948
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: de31efba4088d8fe1336767fddeeaaf8
    md5: 73e361f34184eda100f695380be062f2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 883f121df7ce51062d7043dcd7091c01
    md5: 047792cb1b32617c46a8f7191f0252b2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_density.res.nc
  hashes:
    binhash: 359c39fb2667122ad54bd489d7f6bc0b
    md5: fa12ed29b253878099df9940b52e0662
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8adc656c640529fcc3e9ea5769aab3a4
    md5: 50d5d7d1619fa738c7a356c5db987bf1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a4dd6dea115b34c90550de5f4847b24e
    md5: 5137cf5b81cd4d3dae72e46ea6f0696b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 160bf926f960415486edfdbb11e33df0
    md5: e9206c043ffae17f3407d6a2ab7592bb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a405d691af242daede0bf49d0868a611
    md5: dba5e4130f32627b68c0f6415142e3b1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cc9da97af3237a735f79ceb81619af6d
    md5: c5aab1a5222c5b69999e8c83d19b986d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dc536e7863344470cec377a3e91a0613
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_solo.res
  hashes:
    binhash: 0aea54a0dcd19b5d4f7704c977c72e01
    md5: 2f5ada140716b5ad08e6643835e689e1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 74d6604362e14a4cd0078f112b6f7d11
    md5: 79ecad68a33810138fe0d184cbf207cd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2f8cbc42607f8442babea1e364192a26
    md5: 2789365157ee36275944ba49794aea1d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_tracer.res
  hashes:
    binhash: 86de3e8805718c608381e16f710126a9
    md5: 48570124add881ab91f72bfb07699944
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dc4edb1cd4f05f0cb1e78cad841e0a54
    md5: a6be9e5cfab458dd6b826a74d743e96e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9d30886784d12a0f815dfe8c815edcae
    md5: d2aa33b0c932a4243bea0b0b472ff6ff
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2358111d78ab7bf6405012c94b1a0a6c
    md5: d326d1dda8a897ed6e2b8dde732e62d8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart384/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 19defdde9c9b5fba95037914fa329131
    md5: d0b25b66e13a4c5d92ce9501176b6e32
