format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/atmosphere/restart_dump.astart
  hashes:
    binhash: 790393d8280f77496171e8b9fee6905b
    md5: e1ad181f404a8312f178968451ec64d4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/atmosphere/um.res.yaml
  hashes:
    binhash: 104585fee11569ed2d1ff3d4e21c3774
    md5: d600faeb0745b082a0476ffd490c5842
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/coupler/a2i.nc
  hashes:
    binhash: 0fab50875a2668edfdcf900ff77a5a55
    md5: 6935ddba4b56b9f81aa1d1d6f2c666db
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/coupler/i2a.nc
  hashes:
    binhash: 504b8edcfe970b9948dbc10611c36198
    md5: cc93e168eea7c764dd288ee2f6665f92
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/coupler/o2i.nc
  hashes:
    binhash: 104c23e7a60879fa1a737319d5bfadfd
    md5: c5f9b1883dbf16652e2a4b72464a3202
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ice/cice_in.nml
  hashes:
    binhash: 9877aa51c6b5af5b513f4f586acf28a5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ice/ice.restart_file
  hashes:
    binhash: b8fb319bb1075fd52ea560539d47b57c
    md5: afa1c478396c1caed705b7e6d9770347
work/ice/RESTART/iced.1252-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ice/iced.1252-01-01-00000.nc
  hashes:
    binhash: 511180e7459b0b096fec1998bea7c891
    md5: c7138dc159157789a8d81542e27a960f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ice/mice.nc
  hashes:
    binhash: 9a3d15318c880d7a2fd236d5b951614c
    md5: 9280bc790cc31c7d67702dfe4eacb405
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_age.res.nc
  hashes:
    binhash: 6699231bbff58761bbec20c1cac0c960
    md5: 73fda9a2465c8489c72c4577d64dd754
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6abfc3f8760a81252293bdf8492f51e0
    md5: 9225473244a7393bf628c64c669e9cf6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 43cf01b2be0a17c7df3fba554bf76553
    md5: 4f6ad924379f491219bb1937f9e758cc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_density.res.nc
  hashes:
    binhash: 0e930b604eef04655c2e94dc88e36bff
    md5: 86228d7f4b2cca41646db1857d8dbdcf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4287e5ca65cb1144749f4590270c2eeb
    md5: 93f71de302f5f441b420106b1b5c6e81
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e247e99d861b8d34d4274206e1055d72
    md5: 9629883b6a46be93f9e683bc25437fd7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 36ff9347ea0083db598144ed903253ed
    md5: 1ad711f592f65b58211c59dd3314fa42
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1c43f9d193f145fd5556a8a24de4d46e
    md5: 5d9e480f167066a7bdf57e6a443b8c5b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4a480305a58a02c31ab8f057e207e9ba
    md5: 800d7bc93937555caf9d9c7cbf06d047
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cf62e1043c2854477dea616e67331816
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_solo.res
  hashes:
    binhash: c055a0adf078fbf760441926c65af3b0
    md5: 1f003b1504ee95ab259e578bef38d635
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a082b0bbec91123dd645d7a8130e0634
    md5: 0f142037b47fb499276089bcd710c552
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 09f0ac1c7329c0500303d699c1fd8108
    md5: 161a7170350e706deaced07b2f9bcef0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_tracer.res
  hashes:
    binhash: 0a65986c20c040390ec7391a0f265e28
    md5: f2dea98fb76d8ea3cff113cc54b47810
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aa2457b4d879d901fb8a61b9d9f074e8
    md5: 93de68ab531b0ba4b5f2f6c03042ff39
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2dd363373380f2a8f1d56153faf02da7
    md5: c79bd8c4c281e9fbf9813eed9f6a25e5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1c1fbcaa64c7a95ade4208a92d93d5da
    md5: 6690a3ba7b11912e44431bf2708b9bc8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart368/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d9ed4a45cbc59559368ceab3320b1509
    md5: 19f3854dffaaa5e4f971a3078b7ea00a
