format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/atmosphere/restart_dump.astart
  hashes:
    binhash: da754cd0a0cdc8e620c45fd57f4aeb2b
    md5: 9e81b5a76d8b2728f91e7974b4885fe2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/atmosphere/um.res.yaml
  hashes:
    binhash: 2a428d9cd3fdb28368b82e5aed2228b1
    md5: 0cd2e627e771882d3a11ae3f76b4c875
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/coupler/a2i.nc
  hashes:
    binhash: ed26c24f633d5ad6c4198e1f1a181685
    md5: e98b402dc4c13f23e67310024c667e08
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/coupler/i2a.nc
  hashes:
    binhash: 85287b18d98099861c52379c19ea9cf5
    md5: fe4dec443125cf6d64cfb9d0992ba0bf
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/coupler/o2i.nc
  hashes:
    binhash: 0117ea85b25a98c47574be558892e6ae
    md5: bc7d2f754b7a5702651838543e11cb22
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ice/cice_in.nml
  hashes:
    binhash: 4a66e140efcdb26c0e546a867dcb7e71
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ice/ice.restart_file
  hashes:
    binhash: 16f8a6aeaf4d26cf06c1ac279ab69927
    md5: 45c9930ca2b97905f48bac03a1dd81b7
work/ice/RESTART/iced.0904-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ice/iced.0904-01-01-00000.nc
  hashes:
    binhash: 43f56dbb41915f3302ce8cc806588f3b
    md5: ecf0b3a38711bf0a5f695b9ce268fde2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ice/mice.nc
  hashes:
    binhash: 08258e1332cf40bc0f188f5a110bb7f1
    md5: aa4966f88226accd908ee96be9fecb2c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_age.res.nc
  hashes:
    binhash: 550f9ba3307526e5f8af34c248b43733
    md5: b2eac46c6f1c28fe0ce8cdc894214200
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1a30ab2f0c431d06a86a08620be22e63
    md5: 35d7fe736e7a5b6de0dcf3c081b08a9a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f491ae66957f9e8b09dd9665d59237ab
    md5: af2060e1c5a34b69a7486d8dc71ec58a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_density.res.nc
  hashes:
    binhash: 38220597e37f598b330f672b8a6a92e4
    md5: a8226c563a57c11b920012bdade8449e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c48a9fd7e4beecd8e8179205d91c70c1
    md5: 841dc33dfe34b286a5cf9f55f7880119
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 162f59246310e2421a023532346c6470
    md5: af2dbbae41f2e1b921582ac509c5adfc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 79deb346483eb5972e4228524d79c9af
    md5: 180696b049daa89adef1ea31b7533a32
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a161c5457e9a797c82255ce8ae38ef03
    md5: 4722d38da604c21891f7e6362ee4c232
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ac6eba5536e37c18ab767c649592c4d5
    md5: e4d0e3a646191a443f9b885ee9131b0f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 79488f504a870bfb7af83703b330f4bb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_solo.res
  hashes:
    binhash: 8428ca619787c67c8b45503594555e02
    md5: e760767a6e881d5667725a0356aa3e06
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb771504a5f1bbefd9613cfd801d5bbf
    md5: c119d2fca1a3ccf824b94c0bed52b5eb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cf5e89f26a9aa691bd76034e75dccd4e
    md5: e19935e1328f6967818d3fb8bb5fa201
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_tracer.res
  hashes:
    binhash: ebae89be2b85169248bde77307e0421d
    md5: 4aef7a92c1333e9697fa594ade4cd1e1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 830bc63d73fb51a46d9bc6987a550e1e
    md5: f974571ef681d8069881226eb590fa12
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 00ca5f34a3228bb3530281f0dcf804c8
    md5: 641803ac504b0a716c8b6d242e4f7a6f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f34ed4743cc3d186d349a1b041a5be0b
    md5: b2cc7d77d54dd01225a38598f43f3d52
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart350/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6a56eea62be77becfb706975ccdefccf
    md5: c38e212781380129ac70340b48381ccf
