format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/atmosphere/restart_dump.astart
  hashes:
    binhash: 90a0d1182a0ac50a6c0bfb329b3e5ec0
    md5: f2ecef41a9207ec8e079427dc9928fa1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/atmosphere/um.res.yaml
  hashes:
    binhash: aa1f8d307c053e51f94968b50775091c
    md5: 6dfa0fa60c988566dd80e93ff45a82cf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/coupler/a2i.nc
  hashes:
    binhash: d00defa25e73b5b5c1cb5ff1a6132af5
    md5: 49c6dafa89d4785fe45a01ea8a75522c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/coupler/i2a.nc
  hashes:
    binhash: 01368a829e5742f89d74ba059d4ad6d5
    md5: 3da42e12c453e8fb8478796a41298198
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/coupler/o2i.nc
  hashes:
    binhash: d05ced2ae9758480f4839c84ff4580e7
    md5: 43dc55bec352f001a1af99818ceb9e4c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ice/cice_in.nml
  hashes:
    binhash: cbbde9d082216ea9abf8f188ba2f2d0f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ice/ice.restart_file
  hashes:
    binhash: e04c3908a24dbbcac8ae1daf8072e2c9
    md5: 256059f7ff8a50ab1ec2c9ec45c46fd9
work/ice/RESTART/iced.1817-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ice/iced.1817-01-01-00000.nc
  hashes:
    binhash: 835edc20b8cf4bd0869cdb934175bf21
    md5: 1eda4d94dab396eaddb1237fdea547a7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ice/mice.nc
  hashes:
    binhash: 3db7ad444e246c233e64228baebf7841
    md5: fa03094a946c068352cddfa2d8aa3ad6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_age.res.nc
  hashes:
    binhash: 99c05b2efc884b8404d4d524ebbdc4ab
    md5: c4f5de6c582f24ddba6de0bc416602eb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 54b71692a5d2f79308f9ac97ecc74b3e
    md5: bc1236c31f807e39a608b5c5cb781870
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 879b2ffe8f3c9607178a1411208c19c6
    md5: b7fca5ffe6a27ea025f1b64bde5e64f3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_density.res.nc
  hashes:
    binhash: f025b38a5e37fbec305edd668087c685
    md5: 7a5eeea646ca618a46b98c6d419a592a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1c3e5695e27c353e6856cbbcd5d77986
    md5: 86b919648b37e59c446a959d865332dc
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b0ca1f82c27846081e3984d03290dc57
    md5: e4f1a31ab653d8253eebc5a6cd02b246
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3ea8f9e99e62cb8505bc7760c47e45a3
    md5: f27087da4081fe5a443787c1d6239dbf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b5353573b463bf95291e4eb520a942cb
    md5: 154eab0d5fff94c30846d9874799a8bf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_sbc.res.nc
  hashes:
    binhash: adb4f8804db63e758b5f0b0e705fb470
    md5: 27a273d8ef139bed09f641429682efce
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1a7501e95394bec891c162ec482eff8c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_solo.res
  hashes:
    binhash: 3d07a6de7e382393e56c8870c50a66a3
    md5: 97b11402a60db2aa514aaf0fd7fd33a2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ec4dfcfe289b4da64517e6f4e46ba8c7
    md5: 71180975705e49f6e0261424adae7526
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 234436d39337df08154e7de5aa5a92bd
    md5: 0c2a78efc6a3964a95e19e4d0ab9df6b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_tracer.res
  hashes:
    binhash: 740e3a3a66b673339a48e39334077a14
    md5: 3d335c8e3b4787034237020baf3b04fe
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8da2e557805c949915b208ff6de7af99
    md5: 0bf6f119ea006d2eaf7ddd7d8a6fb9a3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 662112fc61753c7f606f4bcc9a9f9c0c
    md5: b57d0825e6b8e6872e64f7f0a9f0d94a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ff4ec2af89908e28d47ecbb581ff55a1
    md5: 9284eb9ec9888b275b625762959e8f05
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart372/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4480d0170dbdc908bc946fd280c5277d
    md5: 330fe0e2afe04664648c23e9ea61e72a
