format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/atmosphere/restart_dump.astart
  hashes:
    binhash: 6637b6ae9220732b007c7bd1681fe295
    md5: c3663db3400c05abe54857b0284c62cb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/atmosphere/um.res.yaml
  hashes:
    binhash: cd6f4e743226345595bf15b65e84e6ea
    md5: 7fc7e0456d5e0d42f29d2cca93c5dd8f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/coupler/a2i.nc
  hashes:
    binhash: 75d5a724529425361caad731da4b7ce7
    md5: b57ca7bab86f747f0d5b1646187943f0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/coupler/i2a.nc
  hashes:
    binhash: a8a4a83777346bc62456889e1707afef
    md5: 2597f6574e8af64e1c165427053a0fc9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/coupler/o2i.nc
  hashes:
    binhash: 3121174bf4682abd6262921671d7b1ad
    md5: 4f404b94063b4cc01f89e00f331fc80d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ice/cice_in.nml
  hashes:
    binhash: e833e5437dfdd23391109e621696f138
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ice/ice.restart_file
  hashes:
    binhash: 3000a0f43c47232e8268b327cc6e7a41
    md5: 380b41613f42ac093af230958afeb815
work/ice/RESTART/iced.0946-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ice/iced.0946-01-01-00000.nc
  hashes:
    binhash: 9f029d3a523a772f211e8db367e0dcc9
    md5: 0d725c514487d5fde4e6c679e822da0b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ice/mice.nc
  hashes:
    binhash: 1443f50dbd7141197621d1711fd83d24
    md5: 2745d22e46aa2de4ea634f21a8c5e7cd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_age.res.nc
  hashes:
    binhash: 3abdf704aa0ae04cad81abad76a97531
    md5: 4a04ff8400632f9ec5ac9eb0f63b6b93
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7e0b845aad597046dde44f8a238838f0
    md5: ee6e238c3ecd72edf9bfe0a01e41f3a7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 66721d19593312567bb3f877e5ba5149
    md5: d30483aa9d13dfd049212161b92accdf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_density.res.nc
  hashes:
    binhash: 6ccae77fda7da333ad429409056d26d5
    md5: 9164f705cd7a1c6cf09f8e5436d505f3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2a67eee1d6fb5400e56a815619db05c1
    md5: abe23fdb94a6e964cb6a8bb49ea9d57b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 910e4cdebf1b2670ef6b0cdf51a7fe07
    md5: c0c65ec2909f79f1d21df9b8a00b1e89
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4edaec603f0b710a6941ce9a2fe7900b
    md5: bfce7c53e973378aedcb1f7173fb4b6d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 52f0799b73d8cadb576db799aeeefb3d
    md5: 032304a4653deb95c4c299a1e093fd17
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d90f11bf7d47b40c1f68ea359ef58c3e
    md5: f23613b3ee0ea936a6821c4234a94499
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f5ea8c99575412ba75189916683e1444
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_solo.res
  hashes:
    binhash: 2a3f3f76885dc9bb98df2db5c3e00c12
    md5: 0738cba7c685fff039883e838a65a40c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f85e60bf6835899953756891fb86d5c4
    md5: acfac07a88a4e04d236b0f540a9303da
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 99854ac43e83b928468012743997dd20
    md5: f84fb4b4e205ec6176b4f643b7b81922
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_tracer.res
  hashes:
    binhash: e84d76e644bef3809f884cce00b9603f
    md5: f692048a6e564636b5e0df54ceb58bec
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 68f541630823c1ac2a3b392f65603cbd
    md5: 6ae84ba149092f3a9c56fbdcb55fee50
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fa27bc0a838fab3c48db7187491cb79a
    md5: 5365879fd1387bd0f445919d58bfea8c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0031794ff868cc2cba373bc7829ef075
    md5: f33474f8279cb66e10ffed1c522327b7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart392/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 784a1d7f6e7c1488496dbb47dfd7fafc
    md5: f53d07b84b9835b34fb73ddd74b2f5ed
