format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/atmosphere/restart_dump.astart
  hashes:
    binhash: dd91598bfa0663871a2441fba4d90ea1
    md5: d0170591ff86df5d5998f3f456c94ae7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/atmosphere/um.res.yaml
  hashes:
    binhash: fc81d8c75af6eeec969dea45c7a5e790
    md5: fe04326479248050ca4ada09a37e59c7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/coupler/a2i.nc
  hashes:
    binhash: f1694f1cb0b437608d08e9bb4e7bb2fd
    md5: 4da4212297baffedf231745bc897d17e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/coupler/i2a.nc
  hashes:
    binhash: 4c0430fe3fe210a666ada831321fa07c
    md5: e3431c859b25d67414fc5115208fd28c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/coupler/o2i.nc
  hashes:
    binhash: 07ea1f5e47e1c514001eba9d2c244344
    md5: 9adc407f9f8b211e0f260275e83097cf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ice/cice_in.nml
  hashes:
    binhash: f0d1795a12df98db2d170b325ed626d2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ice/ice.restart_file
  hashes:
    binhash: 9ec978f6a1008771d9b8136be8d5fe99
    md5: df7b55d2ad89eca572e8d7e7c67e36d0
work/ice/RESTART/iced.0907-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ice/iced.0907-01-01-00000.nc
  hashes:
    binhash: 4a4a7399cdacb5518c3d03e557f221a2
    md5: 8ef00f508f98b013d2b44819ae2bb305
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ice/mice.nc
  hashes:
    binhash: f4a5f30403774f403a7c4a584af60041
    md5: 14d300c6daf5262a377819e57d0c2167
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_age.res.nc
  hashes:
    binhash: 4d470818c9fbea6720f185d0b3e90e4b
    md5: 1ae0142c9147adefc0755804c7a00c9d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: add6259d15c62ed0f9b8cf71f33aefa3
    md5: af2a55b14bc324d1a5fbb3c41466a596
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b7b4dc5c8c6ea8ef4eebbd08b283fa7c
    md5: 24d0789c85e29eceb031ff0918e9aec3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_density.res.nc
  hashes:
    binhash: 40cfd6e3c4878072ea15922de61e9c7d
    md5: 4a3ef2cbbeeb26b69edc89f1e92d251c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 164b904184ab7a1cd0b5c67eeaaa8296
    md5: 00b2dcb3546148595f8d4e0fa9edce3c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f96d8d7260ee1133ef9c7a4db9820cc6
    md5: 618e4797767f4051fe862d46ecc6ed5e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9ef6a794add57645581d187009f142ae
    md5: 6dde23e9531dc8deeb24b333167de227
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4917b352719165408d729a5988e61dd9
    md5: 878ee831c071a316c2437cae9ae529de
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1f6103ca915d4eef094cf34ab0003975
    md5: 3c269e2137525aa5cb643cb83ec6c674
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d49613122a74ffb8b9113cd652c0601c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_solo.res
  hashes:
    binhash: 1aafeb7e3e90f0dc65bb6cf196829c75
    md5: 69d8514d2faa2e5c8c8ed5c01e118eb5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 80ae2eeecc00e231d2a156be3611622e
    md5: 2e573666c25e98bee46db07c927f40e5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2acb2414f27821a83400afa363130eeb
    md5: c2758fb735b148a2f67d1209d0523759
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_tracer.res
  hashes:
    binhash: 51404974674266ebf01f72fa8a21ea4d
    md5: c76aac655c22cd4b2ae901549d721de5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a9eea64e06c3d1792863840e3a253ad9
    md5: babea78891acd440de42405304b208ed
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 320b518b9506057577f321513c2bd11e
    md5: 4a142590d48ab44bfcc9b471bfca81e3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5ffcdc91a1e2bcc93b2bb5dfc071467a
    md5: ccf8cd4ec6004ed9ed0e883a840c7a61
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart353/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7a535a5dc66f93a6dc1b451be11d0714
    md5: be0a5f05d25b8551c275da8067c025a2
