format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/atmosphere/restart_dump.astart
  hashes:
    binhash: 5ac90fa1ba0857b8d5ad65fd131c69d8
    md5: fd55cb2d2fb547228b5fd92ff06e9d62
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/atmosphere/um.res.yaml
  hashes:
    binhash: 1b87d74a1cb59b011ba0f01a7e90823e
    md5: c65528b9dddca9ef364f86db19e85472
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/coupler/a2i.nc
  hashes:
    binhash: 77af2f045c3c9acf7fbfc78c5d6ef8b6
    md5: 8b8d926b7f77b8d737c830204be5dea3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/coupler/i2a.nc
  hashes:
    binhash: ad4c5eb5d28bb808dab0670c2b6ef3ba
    md5: b984d16f7977db4e803502d039b87bb6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/coupler/o2i.nc
  hashes:
    binhash: 8a457737d1d7f4c8702a42dbf989440c
    md5: 8ac38d37cb37f36b4ca80448cbf35726
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ice/cice_in.nml
  hashes:
    binhash: 3a3578d2b4c50d1eaa23425e5dc19e33
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ice/ice.restart_file
  hashes:
    binhash: 880c8036b9164fa204b5c7d326edbca3
    md5: 7ede0f3f39799e11616cfbc23df6cbd6
work/ice/RESTART/iced.1805-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ice/iced.1805-01-01-00000.nc
  hashes:
    binhash: c2d5f18f99a38be1bbd34d28ad8f50f1
    md5: ce1e1b36e7c94aefab1cb3467944357d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ice/mice.nc
  hashes:
    binhash: 9e54211c749fe4a13ebb0b24e11dc1cf
    md5: d85e11e050ec2ba44818b611e4f1f55a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_age.res.nc
  hashes:
    binhash: 34b5ee8263c95c756c204a4c1cde26de
    md5: dd654ff2a3a22a47e7754cbb5fdbf5e8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9bf7b9ad9e88603f3a2da2e6e32485ea
    md5: 9d52963e4e26513cfabdf380a1148f1b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a54c29619d200c1966f77d0355b5a172
    md5: 16c279a85381a672d03ef2ab43f05f18
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_density.res.nc
  hashes:
    binhash: e4c601950b9e61dfe2930430b049d9d7
    md5: 123adaa2012f30b609e2280ee6ba6ccd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e3f38282038c0d14b80943b83575759e
    md5: b5c330f210acc8ff8397dead5c8fbcfb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d2dc4bfafc2399e7d779714fcb1bc3c9
    md5: 349aefb9efb4cbd31e68a87137879a9a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_neutral.res.nc
  hashes:
    binhash: abeeac9f3af9088b6329462d2949085c
    md5: 63fa9e5a42870b8bc5d14631a0737b3f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 555b1f3377a52b39222c975370eef445
    md5: 2ccee53bb1131d3848b025e67ea3b23c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0e1f0cc557cc08e940768faff96b2b32
    md5: 6fbaa377a7717b01ef7deff0fc20e272
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 95d7c80e074dfaf2f86368b5db9da7de
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_solo.res
  hashes:
    binhash: c5957e31ad9d857e306ec3a773d58f98
    md5: ba270b44235f4cc64572644088ae457f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1d84414f36aaeed9a452c3c469d35fd9
    md5: 5035317bc88d32dc89b046889af32b91
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dcbce070915b162859bba3ecd1c91cc3
    md5: 6cb1adb7bda07e2a2be0e48fa9fe25ef
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_tracer.res
  hashes:
    binhash: cbf0db0f7ba9458571df351487a7ddb3
    md5: 57ee56de1513c2560fe096342abf29f0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7e5c3c04d9d9ef2370a6cbe412e12a90
    md5: a0ee9f58be603c42128143a745044591
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 29f9066ab56ef1febd094fb1f40c85d0
    md5: ff3b731002dc79cd8b5b78e490f1ec97
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cea48c871c6b1d865bb92e5bc39ce1d3
    md5: 11ff50f698dc53732d961fa1f1040ee0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart360/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d4d822b12db523f09e9f217362e1321d
    md5: b621ce01882fce20924c16bdb8ff14c5
