format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/atmosphere/restart_dump.astart
  hashes:
    binhash: 8166416ca88b1626610330238f212026
    md5: ffd37c38f91c4d6ff01773fbbaa2d08b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/atmosphere/um.res.yaml
  hashes:
    binhash: 203c907d43e291004688a509954e055b
    md5: 328445e05a6c21e447c3553c28828210
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/coupler/a2i.nc
  hashes:
    binhash: ec99370aebdeff0cfd2932983766474a
    md5: 3e566147b072744aaa626de790856046
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/coupler/i2a.nc
  hashes:
    binhash: d5f2f8d8ca82bff6f185190555d51bdd
    md5: 6360b476493ca7c8697e1bf6600f9d52
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/coupler/o2i.nc
  hashes:
    binhash: 1315cbb57415fe511128bce05b0c0003
    md5: 9c51256ac28533345b7a76272e0de813
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ice/cice_in.nml
  hashes:
    binhash: 56c14bc2f0a4fb4ef3bdc92a8ef97550
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ice/ice.restart_file
  hashes:
    binhash: f3be381b4fe766f1ba52334efd4fbdf5
    md5: 62ee0af8d8c11b47c3a8037f38b15f67
work/ice/RESTART/iced.0871-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ice/iced.0871-01-01-00000.nc
  hashes:
    binhash: 9c2e977775e59d02d02b4ce2aeca9f00
    md5: b99aafcb514a38bbcd04c50069fd748d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ice/mice.nc
  hashes:
    binhash: 64075cbdd4cdbafe8c0f0b6c09c629a2
    md5: 2445c6f05bebfbdbbdea0b38a6c9158f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_age.res.nc
  hashes:
    binhash: c01b3cc123c5f1fbac4162b745b4e904
    md5: 4c9afae19af6bbaa57d5865ddc5f14da
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b481ff3cf2aa21d39e9f798ccfa70715
    md5: a42109ffecff9c71ba8bca3f4055055b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8c7c2ba65da53dfbf108494cf701ac41
    md5: 487fbd6919553d16969b1e0224efd1a2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_density.res.nc
  hashes:
    binhash: efbeeba832a2801ba1fa26fb1db7d624
    md5: b7d32ca9e0e276763a3f2ac3c70fe303
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7eae05b07eb7c3f566b2ef2b24cead22
    md5: 0a649247b9fbe5a02cf226eaf6e04430
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f94a3a55dd2bc8ccb4c05dc41e35d862
    md5: 0cfbcbf45fc76b13eb1d7adfebded4e6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 58465cb2e2756f49e8e79545d1c5b944
    md5: 5870dfd0d1cf11b084d6e2625a4aa91f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b0026c5e2abf487f3b4cc3a366b3aa4
    md5: fea804c8be189aaa4f71a8ca15be1672
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3d31ae25bf8fa47d5f3e75e6b6d63046
    md5: 8df49f92330d67b8a0b74ebb23f0a2c5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 91835f510325472c71768218b218f4c5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_solo.res
  hashes:
    binhash: e8cbadc470dd4a7f807601867aee0890
    md5: 4f6febdaa98b4353f3c7459d6cb1f293
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3cc0f196078e961cc129a58b934eea60
    md5: 7e88d63897042631be453d930f39f321
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8dbeada3469ea30defe4666e832b15e5
    md5: b3793924adcabba7ba8e2f23d3c98d21
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_tracer.res
  hashes:
    binhash: 2ac668eeb0d5d63fec1a596831f77f39
    md5: b0c4f0caadd12e00d4002abf02159646
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d9d98689c6f0b94597490f16a1fbace5
    md5: 3af7fc0ec72c57fc8a992db15094e131
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 899f2bc60668010f1101fa26fb4bdf32
    md5: c949e16749ec43457e3fbd8e0b3918e4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7ffb0ce430b4316f2b1ecca982d7dc61
    md5: d98e7aa61686a4b5aa37a7dcebacb006
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart317/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f120d43ff372177a76a1a930ac524f27
    md5: c043616f928e7908b7c81db389a3de45
