format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/atmosphere/restart_dump.astart
  hashes:
    binhash: fea34ad90e2be1a3cd8c91bd45992437
    md5: 3aff17281cbf4b71679efad07acebd05
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/atmosphere/um.res.yaml
  hashes:
    binhash: 55104159940867a6d2dc6164e60d5fb1
    md5: e400ca0db16f32b8868af337ea4c672a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/coupler/a2i.nc
  hashes:
    binhash: cf2dcd70d83cd76c2f622c633c0c8b8e
    md5: 6ba11084f1d846eaaf0547fb2dd08165
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/coupler/i2a.nc
  hashes:
    binhash: 860a9b503ef9703ba41ca3558f151fe1
    md5: 3d00d77dd94973312bd6ec2afc05f432
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/coupler/o2i.nc
  hashes:
    binhash: a853a529e5a9554a8c1191304377516b
    md5: 981d481c6789d278f72de1d9ea83b3f0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ice/cice_in.nml
  hashes:
    binhash: 2e4e77c2b3b521410f36742caa4c42b6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ice/ice.restart_file
  hashes:
    binhash: f28071a66e4585f3cc72a06ebf15e2b6
    md5: 2bf41182bff2bf2d10c33e7b8edda3c5
work/ice/RESTART/iced.1280-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ice/iced.1280-01-01-00000.nc
  hashes:
    binhash: 00204c341366f4802a710f561d45dc29
    md5: a11a12f30042c57503259f6e77c6cf92
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ice/mice.nc
  hashes:
    binhash: 96131263e83c45ab2ef4e0d082779204
    md5: d4fdb81332ea88f5cf693c198c836188
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_age.res.nc
  hashes:
    binhash: d16e8ee110ad7b89930b3b2ca7aa5bc5
    md5: d5db794396137351d3b7361b66f1baaa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9c2264c7ba58be88755ee78e01eabb50
    md5: 161a355e6424ff750e1b8eea5e75d9f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 41f653950a501f1f4741fb722abbb20e
    md5: 0801a8d6113d0b8897ccdd97c9694501
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_density.res.nc
  hashes:
    binhash: 1fb5b3650d91b604b3e1dc385a80dc5e
    md5: 17bc534c9d00e5effe4492c310451af0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3797b8b6376a2bfce06f91c2fd509b48
    md5: a69f259549425ac9ea43a96896749035
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2c8fdead6d02d6c090c9a4140ff0f720
    md5: ea7db672c8f99dcaadecb8a7041212c6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6568147355682dae438931c2f787f848
    md5: a6f56c5e9ee63f2b9ffc04cbdb66bcda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: aec1ea8be76caad9f193a165e048a230
    md5: 0f68e0c8063c0bb2746e213c45de7c69
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_sbc.res.nc
  hashes:
    binhash: de09af6ec10c48c2ad56fd935b1d5982
    md5: a4f36f38e1b80e562c5a37a7004a0e72
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 52699559d63857c1f062442c4525508d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_solo.res
  hashes:
    binhash: 9682eaaf824a057c2b2fe6b9b5dd1bc1
    md5: d864968da15f6ddd8066c02088b7f748
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5ed72711b9dba0ad947dcde6da9c3a97
    md5: 5f88be5c518c643f26c4a1adecb8ea66
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0c28653f4bff3cbebb332b6a1f2ae9b0
    md5: 7d1cf26ebdf582b5fc7f0fa92bcd53f0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_tracer.res
  hashes:
    binhash: 6973b8e743a64fd9085a468080b940c2
    md5: b8529b1c0a3bc01645e0a8bf49f130f7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 26bd1714b9c4c2892073b21eb3fcb025
    md5: 33edcb6206f2f11aca863abce1b733f4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f10d6e71e1c77a72894b1726ddeaa00e
    md5: 835dcb3d1c12ae20b122e934dc3b77e0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 711cab5fae63f6e0887ec2e21c002ca0
    md5: e5cb8111a73b4eda8b10917b1563093f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart396/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0a091db6127d26eea8cb2067d5acb65f
    md5: e01852d5499417b30b728fe9f2537b71
