format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/atmosphere/restart_dump.astart
  hashes:
    binhash: 228c8bb3452475f55a68626e7a678ab1
    md5: f9ec9fdc455246e4d15a55835a0a0bf0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/atmosphere/um.res.yaml
  hashes:
    binhash: e76f36817721d60c9bbd03a28d0e43f1
    md5: 1cc75f45cc3c80071d1d8efffce5df0b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/coupler/a2i.nc
  hashes:
    binhash: be499c82879f7c6018d07465313da50c
    md5: 5994a194856149415a6235dd68a446cd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/coupler/i2a.nc
  hashes:
    binhash: 1ed288cc9631ad115b4feb1db3faf88a
    md5: d2461b121c27a27885b31ff5e273e689
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/coupler/o2i.nc
  hashes:
    binhash: b2ca6406efacdc227357665759015ce6
    md5: 1befd9be3b4094f888a6d0a19790728d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ice/cice_in.nml
  hashes:
    binhash: e4cc9b6b1880a4008e0176c99b668fb0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ice/ice.restart_file
  hashes:
    binhash: 9a77e4b29f44ea87d21e79061e54fade
    md5: 95de02799c45aeb88abe78e6e08e3b4b
work/ice/RESTART/iced.1290-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ice/iced.1290-01-01-00000.nc
  hashes:
    binhash: 4a4f553786684dc062798872d0e1180f
    md5: fe9b2c4598a6a2d71aceac9c21398d7c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ice/mice.nc
  hashes:
    binhash: 6f43ef33dd0c2866ad2c3c2b4a2032ef
    md5: d4235c37f405b38fa82addfbf992737f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_age.res.nc
  hashes:
    binhash: ce344a727197f9c7b2db4bfe383f7692
    md5: 5613e2787f195593717a0ca20d11eb69
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: df381d1e3d6f87c0815103874e1f2f00
    md5: de3f491f212c0015629cd5795fe3e9cc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0d762b1f17b10d8cb8ac59054a8d2385
    md5: 84da7a3a1063381a8cc430e7f7fe456d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_density.res.nc
  hashes:
    binhash: 71b09759833464ad952499aaba601f32
    md5: f5fb14c10ac2d6b01d95b208fdfc1772
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f66664844be316828cfd7d01638e07fc
    md5: 62c24e28221844ebec18d6c8ea84d6f2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c7b6012e583d3f878bd0eb9d824b6db3
    md5: 2b63c7641ffeba395a54a77fa971d6c8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 93abd4dc1c5182ebaa9ad2d52268e2a2
    md5: 623a73f33439c0dd1cc2c0519511c386
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fb34aad92c37b1145722ad8b3b76e0b7
    md5: 095797ab5768aeec0e3ffeff99789c5e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 16edee6e5e9e0386cc5861ad4b144e17
    md5: 6ef8257de1d1fa731d8f01f08eafb4dd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6f35b8bef3e41aaf61b02811a08dbf8f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_solo.res
  hashes:
    binhash: f86331f4eda40835ea6a644afe412b50
    md5: 31cfd23f39584a2ee7f38aaf1eea75a3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8d2ffa0cc75ba8b1f01032f53f6a0607
    md5: ccbc03e741b5dc2321b7118afd95be56
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 889d70d784d9c3613d709ccccd5324e4
    md5: 30fbd5fe6ed080383a9531280a2c641f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_tracer.res
  hashes:
    binhash: e87c3b020e5384568ef500fb97989923
    md5: f65022f904353500696b80b2e8429673
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 786c424392a44df529dfe87a2c3c368a
    md5: 998d7da77967fb048327edca821c6279
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a83283d7fe9aeaf09fc217085a809cc8
    md5: 0231b827976c750c756ffe5c9c6b8693
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0c39806f1675a3b75ec4ebb61a961f40
    md5: 7e5adb2aac9b81a9bbff49e9d36a3f3f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart406/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7d524529f8f9bf5f4b36c60a4b64cb0c
    md5: 0894553fc9978fa8cd2591d9a09b0309
