format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/atmosphere/restart_dump.astart
  hashes:
    binhash: 270d1b1991de2d0a1e79ca2f18a3af29
    md5: 5f918242e195a77ec2d8e9873104e45e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/atmosphere/um.res.yaml
  hashes:
    binhash: e6ea478aece4cc26411d5e08ffd897bf
    md5: b4a7f1085b04567e793ed87df6ef2672
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/coupler/a2i.nc
  hashes:
    binhash: c797ff93b02328c43744c25dbbbc0133
    md5: 18d8db7a12e3c0d8d5352410e78ad3b5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/coupler/i2a.nc
  hashes:
    binhash: aa51b885a1573f6a70c5dbe96fcf8396
    md5: 511576f1433557b73bdb0337f27989ac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/coupler/o2i.nc
  hashes:
    binhash: 8031fab07ef6a978feed38d5c0b9b9d7
    md5: 0957ccc9f34aa87eeb557ff1a5491e82
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ice/cice_in.nml
  hashes:
    binhash: 2c7e1d010d96d2e7976c4b123d1bc062
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ice/ice.restart_file
  hashes:
    binhash: de99f9e07254206cad73b9a6dc1f1496
    md5: 48492dc9d011bd964f500dd6da12064a
work/ice/RESTART/iced.0833-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ice/iced.0833-01-01-00000.nc
  hashes:
    binhash: 125f2ae1af30616d97620eb3a317de31
    md5: 6550fb6b365ac98ad0151d52f4f37e12
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ice/mice.nc
  hashes:
    binhash: b8a30656f49140c914f16f19adead946
    md5: d37c6b01ef4a262a2206556e4371a4ca
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_age.res.nc
  hashes:
    binhash: 5ae63ef86ab075d429764263d72b6142
    md5: f16637c4c9c4482bcd0c8f5e9a07f4b9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e562441a60d568de77c5b21ee49bcde0
    md5: 62ef2da20b069eb4dad801ff9b4ea0b7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b05690f13f952d67d284e34afbe3f8a7
    md5: accc34a6a89ed797d1a61a32ebef1c8d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_density.res.nc
  hashes:
    binhash: e1579601562337a9113a49e4446e90f3
    md5: b38d06c8418e7d2dcb338e28fc09fed0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0a395542ee072d3eed24a996b14cd6bb
    md5: a87990acfb74bced6f0aeb74f006038a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e2bbb9ec93f3d86d877e7f1933cea15e
    md5: 084f713b7df699ac3ce59f09bf82d546
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b676a474417e77c4bd2683a9e79b6a76
    md5: afcbf776d958715070c1c005a25fc7ca
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 42c25099bedb06560c7c5e09d7b6b956
    md5: 561e54e68eb033daa6326182a429f256
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f75acbaec5d0ec790b79bc328cd71bd8
    md5: 8bd1b5f45e921b8775b3485aea358127
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4addcf26e19e2c974b32c9fb1d51110d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_solo.res
  hashes:
    binhash: 4ee7ed6f977e2b2e327164b25b4c11cf
    md5: ea01c68cbd1360c6541cb6639b1ef9c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e969948f6f2a311ffb1cb98916bfd97f
    md5: 9b6f5129cb969630fee7a26f58cdc056
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5d4f8cb0dab2d684c67f554c0590e993
    md5: b4172b27d59101d47410be47e66af087
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_tracer.res
  hashes:
    binhash: 3c29ccb9f7a422421f9ca2e107fb1e10
    md5: 572e8d72f5e4bbb9e1b09589955dc6e0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ea9413ff982cf6e6508460d28f4fadb
    md5: 434a7e3e96d860f54ffb8c648c81c220
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4e007db725c11fc0f7cb0cdddaa18f69
    md5: 8041c6333fbec06c44128b3aa458aed4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8933809679bd1085b9a797717fd4ad02
    md5: 870db49b9bbe4c31285d82596ca30143
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart279/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 05f902ed89ffb1ccccafc1a52cb9d8fc
    md5: a4e4bcf9fe11c7516927733796a66c1a
