format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/atmosphere/restart_dump.astart
  hashes:
    binhash: 3bb4e53100cc99108fe9ecc81a68d027
    md5: 7485be3ea9a4a36bcf479905b888b720
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/atmosphere/um.res.yaml
  hashes:
    binhash: 5d12d18fdc504efacff916e7da282bcb
    md5: c84c1d8ea0c881f9677893a488a1a86b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/coupler/a2i.nc
  hashes:
    binhash: f2738fcbade55b937b049e1bb4a7a303
    md5: 43010268ae5734c948c0f8bff92d7340
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/coupler/i2a.nc
  hashes:
    binhash: 6ae707aaff013267628b9b07fe51f566
    md5: b07c945655f0d2825f0d2ba5392bab3d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/coupler/o2i.nc
  hashes:
    binhash: 3cbf47b042ed807c8113531677cc2c3a
    md5: 42ea031c1d804869baba55868ea5ac17
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ice/cice_in.nml
  hashes:
    binhash: 9af50f9a8d589918bfc2557c04e99d1c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ice/ice.restart_file
  hashes:
    binhash: 6ad57ad83db1737b573e9a199c7a7ee7
    md5: 896daefeed547324a749010d24659cc2
work/ice/RESTART/iced.0950-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ice/iced.0950-01-01-00000.nc
  hashes:
    binhash: 92b62e5186846bd8ca6ba68a9f132a6c
    md5: 8ea40b0ca11cefdfce6d62b82de0e2c1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ice/mice.nc
  hashes:
    binhash: f42673b942f24bb9d7d4e10f6e07aa7a
    md5: 3eb2db703ad693fa0595cd3ebb68b9c9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_age.res.nc
  hashes:
    binhash: 49b313259b233b4d67da8560de0b3851
    md5: 346889e54f687011f279c155d4062079
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bfea6d079911569f0adc6a90f0e8400f
    md5: 56452293eafc05031c6a44691217d59f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c42f9e50ac415735cb69d97e74e875ee
    md5: 4d00c8e1e223cf900cd32b9f253c95cc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_density.res.nc
  hashes:
    binhash: 06a48fbee4a9ad688d5cd9862a4568cd
    md5: a465385c3ffffe489cbf7acf45037b7f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7905f9eba0e4468dbbe78545b39673cc
    md5: 7a365222ea7199492f36936ac0d35ca8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 26417a36245cc3ea3868a4f5dfc08872
    md5: cbe1fcfa7bcc622816afa981dda618fc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 07941c0b8dbf3350965428cc2b7fa2d4
    md5: 81b40ef355385fabce8df8947af2cd44
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cf7acd265488d4d265ae3959d7814463
    md5: 6ec7cec670af1d8bacec221cd248bd65
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4683607b7de34d54817b0c3543610ced
    md5: 482886a00046311abdb4730662b3f67b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: adff670c0b379de05416a5ba53aac20a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_solo.res
  hashes:
    binhash: 5595b57968cd133693daa58933b74ccf
    md5: 04488ce99bbcda76ee5d14c292279e82
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: df19ffa1ee5edaf8770f34ffa998e9e8
    md5: 14bc8ae1a496795f74354a30fc057038
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7075fd264eec5ef27bc551e71324e49f
    md5: 9bfdb558e64e3c3e1c8f1b7ca49eee1d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_tracer.res
  hashes:
    binhash: 87ff906b1cffaf3252e4ca63ea80222c
    md5: e18889060e997d56495a8c983d0e683f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e386c16e101249379882436636e98bc8
    md5: 8efe743f7dafc91377c097d0e7e7a3b6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9b20362eb017a6b23e0c1f4f92ce350e
    md5: d1abd758d98f10c64cf856f188081731
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2a3bfad61d97a5942d974d01443fb707
    md5: 60707d2f6e6636ba9a22c7e4e8537d05
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart396/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6dd350bb496974b7bcd549a10e164499
    md5: eb71feb59f045d1ecebe9cdd6ca199df
