format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/atmosphere/restart_dump.astart
  hashes:
    binhash: 74b9881c68c893efed80f7ee13988fb7
    md5: 9410d0f961d6e2e39366afe259153336
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/atmosphere/um.res.yaml
  hashes:
    binhash: cd1c76049d4a314b316dece1310e286d
    md5: 5f2f1e00838c4d59b446c6667c7bb38f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/coupler/a2i.nc
  hashes:
    binhash: f9cb09eeafd5231bb4f5e54cf46bff19
    md5: d823cd94aa36f20dca7eb1d2fb5995fa
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/coupler/i2a.nc
  hashes:
    binhash: 59247089af7c797683dd40d73fcf2bf3
    md5: 523936e68543c3f2d358c6d4cce0b3a0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/coupler/o2i.nc
  hashes:
    binhash: bf9f7b9fb44908175fc980f01906b5fb
    md5: fa2533d48f4e3bf53cbbe761f0775e9b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ice/cice_in.nml
  hashes:
    binhash: 9604604fa18b1e82144b9ab4a70e2730
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ice/ice.restart_file
  hashes:
    binhash: b6b4de6f7d893a9c03b9765587a0ec6e
    md5: f73902d9023a37ed4bf722cfcf3b0050
work/ice/RESTART/iced.1709-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ice/iced.1709-01-01-00000.nc
  hashes:
    binhash: 879dcb6cf21387457fe0c925d178a27e
    md5: 55b531e12d3aae1e6c837f1e7e1d591d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ice/mice.nc
  hashes:
    binhash: c3ee205e789a077b0cf3b7b6fdd42fa9
    md5: 64a04a8da973de3189bd062537ed3794
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_age.res.nc
  hashes:
    binhash: 79a4958f12ec280a2733b32c4477daee
    md5: 92a64277c754f3615798544b6f0dc7a4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1ae7e92fd87f2ab93d8a2254cd79d8ae
    md5: 0595dbfab6944139e5ac1ee4e8da56a1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0185f4bb375793f3e19dc20d35d61760
    md5: 8918764c2743c6cdd260639028ea3e74
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_density.res.nc
  hashes:
    binhash: 5eac41754737710e2f99b97c6af48373
    md5: 247c1dca791958ff796eb04e56cbe4de
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dc0321dc9f407d2051ae2589ae666da2
    md5: 237551c3a3b81ca174d0b2ed36427929
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 69577962518ba44d171d9e4c7df1b499
    md5: 0122c4ee5b6476da99ed1cddc26288e9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_neutral.res.nc
  hashes:
    binhash: de5a7cd34e2d3fd7ca8f8a253797202a
    md5: a0049c4d9f69e52c13f0522e25813d7c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 01b7bce7ea20963027dd372b09d69a50
    md5: 513fef3218d35e87dd576545df2bcd9a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 842d9873fb3391f1db34711f2168aba3
    md5: 6b58f4ddef9ea301d8d1a428354f4929
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bdbbe88023dc7385d7feccb3338a0269
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_solo.res
  hashes:
    binhash: fd6fc1f9e4171580b63fe5fe209b0dc7
    md5: f8e26726904e918b7a344ae5a1419129
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 11a7df0853c9acc2f5b652ecd69da340
    md5: 7a678e5b7ee37baecd70b8c71aab538e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6463c7152c2b7062b87cfad7fcc4e179
    md5: 180359bc9e6b650ed103423ced3ae445
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_tracer.res
  hashes:
    binhash: f17329ee3cb6597bf852771aecc24f12
    md5: 6cbfa93aab591df9373fb09b9eddecd0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3ba8b69d04156dd617e3bcff2819d0d6
    md5: e8b80c7e5c14ad4efa80f66975df8145
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5cd2e7af0a5d9be825372cb27a4ff514
    md5: 1b0ae8c5a9c95548e89d5954ecdafd8a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6d30b998c8d76babf4da361de612f95a
    md5: 99713b060486db2c059b063cb5568302
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart264/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 07728f6cbbd80945f39ad42974a725da
    md5: d5e0c22aee541d748198534ac8d7c780
