format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/atmosphere/restart_dump.astart
  hashes:
    binhash: ee568a61e52fc03d6bdc6a790c86e0b2
    md5: dadd2ad4486dd796f14deaab9de67fd8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/atmosphere/um.res.yaml
  hashes:
    binhash: 03023f83fdaba2875f3333e0b9af6b23
    md5: 8a10b227e9751b3e8316aac278ac522e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/coupler/a2i.nc
  hashes:
    binhash: 1ecba2ccf9d8da5edd435d030b2eaae4
    md5: 8a1f06ad8f1f446f04a8008f2850a585
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/coupler/i2a.nc
  hashes:
    binhash: 3cf49c05e195e6f81d87e51460d3250e
    md5: e339eb424b1d7c02b5e0bc944078e953
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/coupler/o2i.nc
  hashes:
    binhash: 659659c0df8a4e495a69d3f008485cc3
    md5: 26afc541aac21442117b5f95016c99df
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ice/cice_in.nml
  hashes:
    binhash: 669956ee95aa230e24a7eb4ed7ff1d65
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ice/ice.restart_file
  hashes:
    binhash: 5d7cbc6e45aa9964ea58051e638013b2
    md5: fcb659c49831b5e3925583b70d54285c
work/ice/RESTART/iced.1767-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ice/iced.1767-01-01-00000.nc
  hashes:
    binhash: df7b2e5be3b7182433eaf16f11f48194
    md5: a8f0d6fc108e2102e823913c1c813ed8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ice/mice.nc
  hashes:
    binhash: 3d5f24a71de6f1031fca8c9ddbd5d9c1
    md5: a9bb0472c117bb33c462ca8778e7cef5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_age.res.nc
  hashes:
    binhash: 8904649be93ccafaa04bdf66bd9a5ca9
    md5: cfc0c142e5b03ba21e112520ca1aa801
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6b1d5948b6deb39c92de124a142c713b
    md5: 09db7ec06e05d8a325a601d08c4b1737
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 29f1655d189da4edb7e8681fd3c3e882
    md5: fba10870f8da0c0cf3f350dc7bb6aa4e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_density.res.nc
  hashes:
    binhash: 487fa9270605c25e9f5f3b499c9563a3
    md5: db52fbbe32eea02b424a966cc82c9f64
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 09bf1215afe2f535b20318be21c6aaa8
    md5: 265bf7def5e93a5955306ec7df1c04a5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6061911c3ade076305543eea4eb3df89
    md5: e2a7033e4c2d619fb16a31b4dc083626
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ec97b462fda106efe0d489af6dfade9e
    md5: d68ba7593e8ea32d69ba90a7fa2021de
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 17aaae4036c668a06f1e162696d827be
    md5: 609f74bd36fc69717dc2fe245749a88f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b64a75ab6025183b526ef96b984d65b0
    md5: 85f1a5e0748d9a42464dab5284391219
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0e253f8b6a46a834d0fc14163ff3cf57
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_solo.res
  hashes:
    binhash: d11690b643ea9740150dd90252897b6c
    md5: 170375dced7503148698e8bf0fb69c1b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dea1d60ea8e54f2d0f73aa41ece4f44a
    md5: 08ef50df4277b7956162fcb5a59e88b8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b57728eb9aa3580f04a569a4e7893e1
    md5: fbc6b20bf35040bd7b718f33b5e0a3db
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_tracer.res
  hashes:
    binhash: 551c3ca45fa599899fda93fbad033844
    md5: 34e820b948c79bb1dd8968fba69bc6a0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f689aba000ce532092da2681ff4e2f6b
    md5: 46ec0aa52d47c0f09991748da36f2350
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ccbb69cec3ad50bb5650a76219672f00
    md5: 2d359cf0ac1cfebe4530d2b45fbb818e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 891c32c427567e9dc5113d915b417daa
    md5: c736012bb240f169cbdd877eea17e718
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart322/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6d071d9a6360a18fab1b6ab614c73589
    md5: f896103652260c957a8d7865298aa625
