format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/atmosphere/restart_dump.astart
  hashes:
    binhash: ddcf6116ec78ee35d0baa04422a16df4
    md5: 563a88f9ea024922e813c158d8ebf85d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/atmosphere/um.res.yaml
  hashes:
    binhash: bf96904448cb4b6b2204b1cfe0ace608
    md5: 9d3717377a72d191741e0706141296ae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/coupler/a2i.nc
  hashes:
    binhash: d641c9c39512f772fc78ab48ed3df3ef
    md5: 8ff33a7701dd6086c95d88eedbc66649
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/coupler/i2a.nc
  hashes:
    binhash: c50a41c23a04313be90686a361fed813
    md5: 594d762169813799df769452fa5b2324
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/coupler/o2i.nc
  hashes:
    binhash: 6288b243723079ff945d9c9662db36e8
    md5: 6af239a5d7780e7689e100d0e1c114af
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ice/cice_in.nml
  hashes:
    binhash: f80de3c08e4f68f5a176bfca17110eb6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ice/ice.restart_file
  hashes:
    binhash: 98dadd527038488aa0f48b6b904edf9a
    md5: a3a8d1947db95094125b282c2bfdb620
work/ice/RESTART/iced.0937-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ice/iced.0937-01-01-00000.nc
  hashes:
    binhash: f589cfcad8f75c490d87e35959ec22fd
    md5: a7e16303539832d7455e3516d3f4bb89
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ice/mice.nc
  hashes:
    binhash: 787e3921825c136fe37f7242c468f5b8
    md5: 1aa5d7bc75de64ab8c302776e6b57adf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_age.res.nc
  hashes:
    binhash: c344d94995591302b2d8287d2ddebdc9
    md5: 2eec8cbc5980a68bcf01d327a6b7f661
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bd3e43127bec3a0a36377ffd81542a77
    md5: f320c1fd5bb186e8617473742e51a426
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 709fe900b63f06a2f9ee7cea4def063e
    md5: 38db34a203627000fce35efe4d9b1190
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_density.res.nc
  hashes:
    binhash: 8f6b3176138e1e5e6b74ef70a59b1df5
    md5: b2b77961c31ee73ae18c0aa310f0bd43
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b918c9e7db9c96dc59275ee8516350e6
    md5: d4a078e63e362b2ff8daaae47feaef28
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 620d4d894603fcaa5e26fbe093fb8d09
    md5: 90af3257b7f6eae92bb273f6c7237624
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 62075c9eb677b2913d920e71d0ae3828
    md5: 7b99648d836530b684771c2729b35bc5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c883d39c341381fe07878cf1f4bec467
    md5: 0e91d3539f3b0825cf511ed00d0c566d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a9406ad371671da404414f0ae0ea4fc9
    md5: 1719b0fae29a5eddfc63c859fdf45629
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 50764dd7c39244d650a0d9ba853a4c51
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_solo.res
  hashes:
    binhash: e6855b42f74eaa7cfd06433d13ab8174
    md5: cceffc53f3f820c3e6e7136ae6c32d90
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fd9e01bba71a7ecbbc75543e104db8e0
    md5: da4abd96d6f3534b4d730f10e3e37d78
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9c60a4e7783ff88322a39289b377bfdf
    md5: 96f75ade9497b75932e553aa4a0a36c2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_tracer.res
  hashes:
    binhash: 70d84cb18529c260ffac0fd56a4c0f9d
    md5: 038b0e9d334b51ba4e6e2b719fd07236
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c863fe449e994bcc872decd5611090ec
    md5: 5cb6adbb44cf5cec09aba91d3232bd33
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b5470ebf66995ececee00b22686afeee
    md5: 4da37cee27bb58a27585183ab1a3163c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d5067fc9f90cc43e4ff9796890783e45
    md5: a593306c14f146ab6bc252659cf85151
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart383/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4f3158298f8feeba1e0dfc8fa3887fbc
    md5: eb240f0db46b2caed324b0efe77ccbf9
