format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/atmosphere/restart_dump.astart
  hashes:
    binhash: e28afffb4958c6fa2693dd20153f1f95
    md5: 335b7c4f414066b7374dd51c88363f2c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/atmosphere/um.res.yaml
  hashes:
    binhash: d8a7a461497226fae666b7c4ce8f148d
    md5: b309ee66fc1b214aae2ef4f843e992de
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/coupler/a2i.nc
  hashes:
    binhash: 75ba1dab5dd6be37bcea8af2948ef885
    md5: 8e33f658f8571fd6e2829484aa198555
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/coupler/i2a.nc
  hashes:
    binhash: 50614c51c35ea208b2a060e12cc2adb8
    md5: 923dcde035534a6c5c0f3b1697e31b7a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/coupler/o2i.nc
  hashes:
    binhash: 72c56ec63e7baff7610ac385b5555c4b
    md5: 9cffe78445d95b7502e76007ac249e83
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ice/cice_in.nml
  hashes:
    binhash: d3d1769f9c03b44faf9fc00a29a92fa9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ice/ice.restart_file
  hashes:
    binhash: 028ec25b0694e4ab4cebbbb285acea82
    md5: 321f562e8a611948595c99f47275bd98
work/ice/RESTART/iced.1209-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ice/iced.1209-01-01-00000.nc
  hashes:
    binhash: ac633366e9b0d30fc17bfc847e3b5633
    md5: c4164d6b07995e518500ab6c4d0b3490
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ice/mice.nc
  hashes:
    binhash: 15c5745af15d07d008598999f4192af9
    md5: 574977cbde6254853f326d6373b33d88
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_age.res.nc
  hashes:
    binhash: 99ac1d27646ef74a1480857e2984a0c8
    md5: b0d752cdbb9b180034251ede8ec13d15
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f5fc7ddeee9b403cf2235eda68c24e04
    md5: 12896ed70a2153a59bb03441a34005a8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cbdbbf7b92be68b06a0097d0fbc159b1
    md5: 95e7ccbe9c64515afe3e437a14ea94a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_density.res.nc
  hashes:
    binhash: e86086b461650a760fa275956c9c2fa4
    md5: 60b942b21ad2a01eb0e79066c8b655e7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b13bd4aef5740958e257dee3ec8b291c
    md5: 23a22bfde7f8ff652d6f88195dea4923
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 80165f1e053b463151b72b93ddac8e08
    md5: 51f0862116050d3e860fe82429950f8c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bad68e8155ce8572784b2b0b43ee2638
    md5: d55da401adc6ea7ac8735aa519db3727
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1bf0479b220f977a4045f51a0bb63219
    md5: 80b0eedf74c8478bfdde65526ff83055
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a22f35058989b15f823881c5d9c265ca
    md5: 64326645f6e506a7ec3e9a89b3d7556e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e983db9dcb2478760920daf19ed9bdfc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_solo.res
  hashes:
    binhash: 48ade58c8a9fea7d2e5629d03cd83938
    md5: 9e86354fdf4ce570f2b1ad430dcbf78e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7c1eb65f4b12399b6acaadb9ed738850
    md5: 1fcc6c565068e443cba20dc03bfa06e5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d7936c9400143409c69ff6755d392d3c
    md5: 0410f1613d4ac2aff00605f8c9de6caa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_tracer.res
  hashes:
    binhash: 22cf458447e3ff29d0b20a6908477973
    md5: 9cea98085a39203be5033be4c61e8597
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5c86c41e899c24da02c359ea25e6061d
    md5: 20016c0e35ed319a4e361341f345ac8e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c3538d79259785bf9784fb0dc5f6e543
    md5: 3819c57f422a85d4de0d43207ec3b9c0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 75603bfec2810f1b2fc7b8f77c5d6923
    md5: 1d40ef3eeb2f99486763b18039109020
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart325/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9bddb14bf9a1943ddc853365425ee691
    md5: 0582cc309630b3dee396cfc58c8489a7
