format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/atmosphere/restart_dump.astart
  hashes:
    binhash: eed7d05ccd329559d518cd27be0b5dc7
    md5: 996d1fb3eb122d9e801dd971c34004e8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/atmosphere/um.res.yaml
  hashes:
    binhash: 0ef4b8258097baeef03612d6ae4092a2
    md5: 23dc6e5f619d99dde5d636e7be4922aa
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/coupler/a2i.nc
  hashes:
    binhash: eb2de2c5b2b3b7de1dda1580020bf89e
    md5: d18c23146d186503b21180636f835e4d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/coupler/i2a.nc
  hashes:
    binhash: 94b8b0eb07d5687aec47a7843d23bc5a
    md5: 963af1d08ffe8dafaa3c73e3aa5f0052
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/coupler/o2i.nc
  hashes:
    binhash: 966afc26ffd7c52825941d42609e1c4e
    md5: efe060e16dba54f95684f2303f07cd3f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ice/cice_in.nml
  hashes:
    binhash: cb7593627b67ece2cd2a2e9485850191
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ice/ice.restart_file
  hashes:
    binhash: 60dc9c20ab5191903698266359068850
    md5: ebe19691d8f112943919f3f41561cba7
work/ice/RESTART/iced.0897-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ice/iced.0897-01-01-00000.nc
  hashes:
    binhash: 32102afbf96753f44e4442e0b8e58228
    md5: 83e39ae62d2c00d82e4c9ac41dc9d24a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ice/mice.nc
  hashes:
    binhash: 27a3edd142c052995ab149de72ba1ec6
    md5: 3ac265fbcc6f96fb7ed574bbf2b1db8f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_age.res.nc
  hashes:
    binhash: 4f9ecd4e3034a7ff2a2f5f6c6ae15f77
    md5: f6bb27b41a3360f00e99285d4dddbce4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a97d0db76463b01cef15e23a707bad14
    md5: 8cbc167842879245ae0c6526b29cda5c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e4f7140188f8e929ed54a574c42f48e2
    md5: 723c8da0984dec7d3e58bf81c7496962
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_density.res.nc
  hashes:
    binhash: 546e908a2c3c31d04242389f2bd66d37
    md5: 00dadc0f9536ce2a0878a20294620117
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9dfebad978812c9c619e7888fbe8c35d
    md5: 3e4fe1d9b6619e03d941c6202546fa6c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f2c9edaaff2cd6b68314bc07898d1a3c
    md5: 7b7a7b6cf0329aa2e810ba6051cc3eaa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 88897c981f6c172ea4d96121b60846e7
    md5: 169577ef94dfd327017e79398b0a4e91
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: aefac5241e4a9430775681a2239115d2
    md5: e9384e0fc6f767800697d284c81e039b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d73d82d688d23a4f740cf99e6b71bfd3
    md5: 628715a7b2c9b6d4807289c7a646fbc4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 234e2810067f6ef5f39e233a85d3bf7c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_solo.res
  hashes:
    binhash: 240a64840c02a0d7d7a504d7bc551fba
    md5: f74852340a45cda05ad9bc4413c6c9d3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8367ee17fe0b6539392f4897dfb4aa4a
    md5: acd80fa8a85b9ffd7657a4217f3e80cf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9075e6654c0dc17c50bd9be96e7d6d7a
    md5: 8f78af01eff006deb540e84e86d96cd6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_tracer.res
  hashes:
    binhash: db4f433c38c74a7a799fe40cb5e5b64c
    md5: a9afbe7051df543dd6e11f964376bb45
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b24dac94db08d5d3953ca69250c99c7b
    md5: 4ccdb13702c63aac18c971d67c0c3c2d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cd933f6f39077bade144af93c482862b
    md5: 5405dd3b564e5536cf989f3660d2fb33
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2f5f8d7b99df43140396cff7dfe1fd17
    md5: 48c0285ab39f3ecc093bb664c51453fc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart343/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2b89368ccb2136df10ef67d7c8caa46d
    md5: da93f4eccf0e3edee9a904f269ffe7d2
