format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/atmosphere/restart_dump.astart
  hashes:
    binhash: 0ea87cd56cf9e3730f622c2b194aa712
    md5: e8c6c3ffcef496577d9b5e474af804a0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/atmosphere/um.res.yaml
  hashes:
    binhash: 1a241b74e7ba7190e385d17b0d37edf3
    md5: e45552bad87a605aeeda19b936aea858
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/coupler/a2i.nc
  hashes:
    binhash: ba8dd11b7924887cec7406c84c0e8184
    md5: 1fb2e75ff60baf86ed1ed7732bf8976e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/coupler/i2a.nc
  hashes:
    binhash: 9abf19f23888662ac470889f08015dcf
    md5: 7b48ac3f677490b3cfbcd3b6dfe9211a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/coupler/o2i.nc
  hashes:
    binhash: 731964deaaf56096cdb8753e52e7e49c
    md5: e1d456da1520b3e5c79b79ec0779e471
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ice/cice_in.nml
  hashes:
    binhash: fc22622032e05cf1010eb56596c80183
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ice/ice.restart_file
  hashes:
    binhash: 8e38c5febbda3cf524d9b19097b4390d
    md5: 8b102ee151a97d31fac6127fd2d1dbc4
work/ice/RESTART/iced.1831-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ice/iced.1831-01-01-00000.nc
  hashes:
    binhash: eb2b671f7d33102aa4bc401f5e6fd3cc
    md5: 2df2c82a64df94e2852e96bf88b5141b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ice/mice.nc
  hashes:
    binhash: 0bccf88435bd91b451f5e99bfde23301
    md5: ead7d3fb5e964ee99faabffc5ee4f306
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_age.res.nc
  hashes:
    binhash: 194394952e22bf4d50772ed06a6102cf
    md5: 421e1136ef0a980748b3ed2a308a8398
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eba8d5669523ec31fc0ab0b3a00d374a
    md5: 60f908f9421e13320f31588f04c1aa91
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 28fd2ebfc72b8f530dfef87402237472
    md5: 7db681e825e60e540c77f777a45d4ea3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_density.res.nc
  hashes:
    binhash: 44ca21cda95454b42a64b0c7156c2f6e
    md5: 4784f1b9ed02003a592b3373784dd522
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d9aac18bb659d4eea3560a3da6ec763a
    md5: 08c162c1aab1fcc543a866420a0b77d8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 67a60ac71c0f248d31ee6b7a676b64ca
    md5: 26fe2d8e01c8041122e5e4fa914f5915
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e63308d02614ee00a8f122a98db6efce
    md5: e5b016c03cd61dd09482f62db8b31f82
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d5c5f60c586dbb6bccda7de336853645
    md5: e5c186ab5b39e691076a7386dab2ffad
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 573d8921cc8cbd9932d6757d09532e93
    md5: b29e2fd15c24a829d0aa123bfdba461e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 47e0f06549eb06f19b5a1c6b0be5b04e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_solo.res
  hashes:
    binhash: 18bcec15c0026f12bf968b910689f287
    md5: e821a464109560eff21ae44595bcea3a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3034fcaf867e6078f6b7370a27fc81cf
    md5: e2ab12513ee5526ec21499694f4be43f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_thickness.res.nc
  hashes:
    binhash: db99d4bf1fa1dfa3ac00d33f5ff82d06
    md5: 51506bc35de283bc772e44c2b9c92a86
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_tracer.res
  hashes:
    binhash: 253bf712fcd4a076728402e367d3d2d0
    md5: 042ab25b110a4a3b3afe9a61a7a68301
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1998163a6705685eaa1b8621dd6a6c62
    md5: b55fc66ff6c41a4b21f2199f18299367
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7333afd045dbb6f323806ba1f3f1498a
    md5: 1d06393102da2ef9bc56d187e67372ef
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 53f2ca0e832ee4d9704016a1340ee7d6
    md5: 8cb195b97a81f4ec9c60e39e704402c9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart386/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ccd715dabdb241f81d15f0deb0f8fdc5
    md5: e7cc27821ad5e238ef8c3a04f4346ebd
