format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/atmosphere/restart_dump.astart
  hashes:
    binhash: 055a1d140d85f7093eb12dad5108692a
    md5: 4769a904a25fd748fc1d9d0481f05791
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/atmosphere/um.res.yaml
  hashes:
    binhash: c2627f408b79da55dabe4eae3f5b4d97
    md5: 6675869469fa3f482da10174690875b7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/coupler/a2i.nc
  hashes:
    binhash: c314fc60f377452f77ff151bd16751ea
    md5: 5fe718724f1d37605765fff9c889a700
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/coupler/i2a.nc
  hashes:
    binhash: 8601b4d38f9c6b4fd12ab7b670917953
    md5: a10b18efc49cf8cd6766565a6520b333
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/coupler/o2i.nc
  hashes:
    binhash: e7dbcce50dca88c7d5d16482434865ea
    md5: 66be743468c7b590fb0657f03982a529
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ice/cice_in.nml
  hashes:
    binhash: 1513634363325bad0000fe604c26cf30
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ice/ice.restart_file
  hashes:
    binhash: 5cfb8d35d0e981247b15320fe117c8da
    md5: e3f7e464d96323c92f6a31c463b37c2e
work/ice/RESTART/iced.1287-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ice/iced.1287-01-01-00000.nc
  hashes:
    binhash: 8da95c72e9ac6476ca4270b6f996f241
    md5: e616fdc9afce06011813346652a84f0b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ice/mice.nc
  hashes:
    binhash: cc1d4f21f72af30ffa74c5fdc6624744
    md5: c90adb9cddac1c8cb937c0512720a7ba
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_age.res.nc
  hashes:
    binhash: 26b8a992d5527fd8929c4871ab17d2b7
    md5: 8a04013397ea0bc1fbd9134e776e80af
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f66e8e438329ed1fa9e6b55682ed0840
    md5: 0bdecc53a6ad3504f220325564456fbe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f54abc809a5d1bffba051883d92c3a0d
    md5: a8484820f92d47b6ef90150291bbbc4d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_density.res.nc
  hashes:
    binhash: 88ce9da9873c3d87e29130624183fb96
    md5: 4a3e5118758010fb1b01194a96edc9a7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 78f5fcf32a4cd57b28c1fbe898dc676f
    md5: 908be8646f8d18241299adc928b79bbd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e535be5633d2a12f4a49e01295abf5e4
    md5: e084f667a14c58e05fe0c2531684e361
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d1d82f4fb03ba865b55d74c0a30fb19a
    md5: 809592f5a7ec442496339f971f7c1fd3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1ff1599a32cd0edfa9f42f45b2678b1f
    md5: e63f912fde0c6d07819d41b3ff8c208c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_sbc.res.nc
  hashes:
    binhash: da8aa9d0ff71cbd3bf144c367ed08e3a
    md5: f34abdf272d1fbce9acee9f12173569c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b86c8410f200cabe2fe36bbb519192ac
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_solo.res
  hashes:
    binhash: 82b9b33ae2700040864efc4fbc38ac15
    md5: 31ba256db77d45520bd7b5e7502c33e2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 67110f9c0e186f162a069449bff79fd1
    md5: ebdb084e8c53dd2b411201de382815e2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 125d674d792861b47995260bb57af953
    md5: ff6e7db14d98dcff7d5bd22a8ac397ea
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_tracer.res
  hashes:
    binhash: e162aaf4fc8b7a9b060b0e342172602c
    md5: da3e65fcf468a6dd3f2fcecc52036752
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_velocity.res.nc
  hashes:
    binhash: db4cd5dbf18769d85870164418ccb928
    md5: 4bb6eb46df4cc79f35aba95f08e64c57
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 41047aeed7987d11a529f54996355e58
    md5: 0f4acb51c1f6c5cfcd1bad631b684996
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 73642e801415c4412313cd66a85c17d6
    md5: c00ca5366b4456971fe4518dde8a794a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart403/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ddcb52ca6dd0a2b11a52a0c4ce07f141
    md5: b7253e2a47d6663c7661c8e0321114d5
