format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/atmosphere/restart_dump.astart
  hashes:
    binhash: 40d2a9c26f4b1dad6a4ca43467065938
    md5: 3441cf8c3df61342617036f3c03b0e00
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/atmosphere/um.res.yaml
  hashes:
    binhash: da95f080db63c432a063c0589998c0d8
    md5: d146605233e96e339f3516330634f7eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/coupler/a2i.nc
  hashes:
    binhash: 571256575d1eef349267e15da9e5c8f9
    md5: cebf30befa447b5a3a64eefff20760ee
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/coupler/i2a.nc
  hashes:
    binhash: 40ef4e9185616d0e57f3b6540bc5cb91
    md5: 0e0c498c11bc57ff5ac8a32e0430ac57
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/coupler/o2i.nc
  hashes:
    binhash: c2193dc3fc90ef9330c01ab921942c64
    md5: 6f9e598d6a639172360e2fc89d9c7350
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ice/cice_in.nml
  hashes:
    binhash: 927371d578c994167d0f9bf968f57943
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ice/ice.restart_file
  hashes:
    binhash: de48840d3af89ca9b6b0fb71af1ea0d9
    md5: cf9288e505894d46019d99a3324ec6ad
work/ice/RESTART/iced.1780-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ice/iced.1780-01-01-00000.nc
  hashes:
    binhash: 00d8f1d052d514f27243d4756ff9e4f4
    md5: 3b75aee88151e85e9723400922c686b9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ice/mice.nc
  hashes:
    binhash: fc4c03a7f99a813a90bc3ef006bd14d4
    md5: 90a79df7a50d92db2fbd4ba7df8e6867
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_age.res.nc
  hashes:
    binhash: e8356e6f130f0834f0281a338535a661
    md5: ff680b059cc4967090ffc2d3ce1d3ebb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cdd5cf7a6a80a5555299d4af8b23607b
    md5: f374787d5283a9333924aa6e7922d937
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 70cd8fba783ce6d39448332c29e83d60
    md5: 81a01ec2e989fd5a87470fbdeaeae2e0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_density.res.nc
  hashes:
    binhash: f4d113976af1d6c0e7894a97b0a663e3
    md5: 84a370958eae8cb8494c8d5e13d9ba2e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e63efc3fdee10f08f8c2ee63c3e56d72
    md5: c2b72b3fc91318c51c8080790a23d8ad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9b5f331e00c27afbf527d3d0b166d737
    md5: 609060aa669057e596b26bc56f8d0f59
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5f5b6f6e27e5f9fe1c2edff735766f57
    md5: 2c6eca73244b825719483bf0450f97a7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 60a89eea6ab51650b54674f466747017
    md5: 04a426495f90f43620a5688ef7cc5d66
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7a25c10b71b03e1bad332c8872c3e2cf
    md5: 8cc06607b789fce539bc330154e44395
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 82d6f64beba2c8772acef8acd95edc15
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_solo.res
  hashes:
    binhash: 71c44acfcee275ee5b2fe8350a8b68ad
    md5: 4d686eade0475fd1f08dcfc8d7dc3fe8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5e73dddf40db6adc73310d497efedc20
    md5: 6d316219977a554ea38cfc2273cd60b6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ff264cd298d643bd33431d5af1cd2848
    md5: 6e1ca0065c6709badf1f8a806f742efe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_tracer.res
  hashes:
    binhash: 44b8227827b043eead6f75de3b99dab7
    md5: d1f9e9293d933ee5a8a999dcefdb3554
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2e65615c9b3dd0d2dce224aca14285e0
    md5: 5a34e7fe0a46ae7b0e9e6f168336954e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 18dd13a33c89c9af691be466f54c806c
    md5: 69b60f7c0bfa6f19c114664a221b1f0e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8a33827142efac4edb920ce0c39f7f54
    md5: 93dd0dea600afd32a8821626e80b7b51
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart335/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 33275b4a60f286691dee9507a620371a
    md5: f729d29de24a486b9fd41d06a6e82081
