format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/atmosphere/restart_dump.astart
  hashes:
    binhash: e8b0311bb885ebcde16aadc3ce04a9bf
    md5: 0655d4269a21e882252106f1c35fbe01
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/atmosphere/um.res.yaml
  hashes:
    binhash: 621b4a3783ec0a6422c65bc1fc0834d6
    md5: 257daebeec9acd32f390d1601f9b7703
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/coupler/a2i.nc
  hashes:
    binhash: 76784583b46032632a24a1e563b33e1e
    md5: 3842754fbed98d5ec90bedc4169c40ce
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/coupler/i2a.nc
  hashes:
    binhash: c4a4a34caf04fc1abaa097e87a1d4d2e
    md5: b9309bbd4d43d6f0db85a757928f24cc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/coupler/o2i.nc
  hashes:
    binhash: 49231d10f6e75b465dc81830e39ba312
    md5: b4189a6a76b612798898717bf1c3b14b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ice/cice_in.nml
  hashes:
    binhash: 1a21fccacc901434ff7ea313f220e873
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ice/ice.restart_file
  hashes:
    binhash: cf1d42aa6f41543d3e5591b0f20c1941
    md5: 94036d6d2d7999e0131dddefa47af1c7
work/ice/RESTART/iced.1715-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ice/iced.1715-01-01-00000.nc
  hashes:
    binhash: 27f3a70fa844cea7f8dd87739a02e661
    md5: 4e5586ddb06ee7df402cf4d4a2f98e8d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ice/mice.nc
  hashes:
    binhash: f12b3a3a31f447af1fe508981a5e5e09
    md5: ab42ac2f6fa83fe2bbecc2e036470783
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_age.res.nc
  hashes:
    binhash: d9bc7cf21f860c941f1b8711c74e9f1d
    md5: bb23717eb1d82e7b1ee4d97ffe7d6b23
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8cebe32cb42f524ee8e4ec92c56b24ab
    md5: b7fe00ef36837ea84077dfb886cee462
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2a6eae5b2051b53b9385fdfabc6c6532
    md5: 93bc27be506ef442243ea8158fe2b76f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_density.res.nc
  hashes:
    binhash: 0eaef272930f99aeddb4d51455bb3564
    md5: 103bf1c3fea3ee2a5de4cfaad7c7da41
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ee27a37ee4445a9d6a701d81dfb05628
    md5: 7a7eaf2c6cec7fb2701686a73b05a6ee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 92a5f83389923bf935cd0896c5bf5ea7
    md5: 3d0a71807d98d6019bae37a43979f780
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1729d21dbbc3f521986b0475aa6acf6b
    md5: 25a02fb8c5e0c9a3d264cc7e94aed1a3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0655424c2201576cbf50efc74c6cbc8d
    md5: 50547a839221cc45d126a13332bacec4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ca29950669e4966b55a93c91fcd5bda2
    md5: 25c4a2ec3848f811b213b133fe36e553
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 31b96faef9b7d29c41410b27ccd7c7ee
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_solo.res
  hashes:
    binhash: 0feaccb2b2768bd8ef2fe7a427b5444e
    md5: 585d6d569334553f7f0eb7ed5392e0de
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fda5bceb49793950e7bc6784b517c635
    md5: de7cf744704373e101843cec7c4c38d2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9a305475615ae5dde284f25350d696c7
    md5: 3671a0a473117fc657fc58967e7146b9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_tracer.res
  hashes:
    binhash: be744b686705a3b3ae680a56a4d7d69c
    md5: f8ea7f3bb96d6174284461c3a25f1fd3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fde9d4b54fe122c1c73db3ee135bd0e2
    md5: 78a79739096e97f6bcd90d86ee48e981
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 449dfb66e484028d1bf7e4a458dda203
    md5: 101f0529089709f2a6e8b633cd24529c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e7ae4da8839b2ce110e4fdaf692b926d
    md5: 002fae6e089167b46ce8197791ca07d3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart270/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5f9c820ae07b3e425242ec78a5a3b407
    md5: 5f7cd300bb4253edca8fea01af38b5a4
