format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/atmosphere/restart_dump.astart
  hashes:
    binhash: b4750a29c152ce24cfd3e320cabd0a95
    md5: 3769f5c1c85e730c6d19c7451eacaf35
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/atmosphere/um.res.yaml
  hashes:
    binhash: 9548f18664c69a114a51ee92e42894c1
    md5: 333917ec3909ce1a77973c7455ddbbfd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/coupler/a2i.nc
  hashes:
    binhash: 87dc35ebf4aebeae2d451877c6e2bb68
    md5: abcdaea3b7a6a44a145a2f90f9f07584
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/coupler/i2a.nc
  hashes:
    binhash: b9cfc3fc6e2bfeb8471815c005db8657
    md5: 4426c71ea89b93c966356598210be860
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/coupler/o2i.nc
  hashes:
    binhash: f77bf5c87d2c4d61f7d370662383bd68
    md5: 6feb5444fbbc57c3ebd6e205a2f220d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ice/cice_in.nml
  hashes:
    binhash: 74372a155ff4406c6fe46ac3ed68b085
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ice/ice.restart_file
  hashes:
    binhash: 037e907f3fe61ff696932d1e238bd960
    md5: 648333e0dcb2f3f626e2b5c76a4006fc
work/ice/RESTART/iced.1820-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ice/iced.1820-01-01-00000.nc
  hashes:
    binhash: 9d40b7f4d2547e658de2bb7edc8dd096
    md5: 9346de35aa8c4d8f9b0723b186d35ecf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ice/mice.nc
  hashes:
    binhash: d2a1c8298dac1aad3ee58f93cf67ce24
    md5: e9ec0d16f1e63ae56139bbe7efa3930a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_age.res.nc
  hashes:
    binhash: 21939c14e346639d6605561dedc9407f
    md5: 4c3a230ff8d9aeacf6d312db4beec2f3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 42e621d851ff83782d65c9d162c16f7c
    md5: 68a6f2e08b51ac3f4175363ca5b63f11
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 737d2e047953928bec24b826f2578b2a
    md5: a5d20828bfd6616c6f9c1d4e20be808e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_density.res.nc
  hashes:
    binhash: 1b32ef28ae75bf5c8dcac16620aeebd9
    md5: 3b96e74719ff4b8b968743ebfaf395ea
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e65f653312c49efc26dc394546a24860
    md5: a7636da9b2579f3ffc7232e4925f1450
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a41182fe202704ed8a2bd944c4db2dec
    md5: cfdd5b41fa69d3e587b4e45b710281f3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4bf272c500c10234f5156238d95d47c1
    md5: 67f817b05c6b528cc9bebb02f78be995
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 50fe82d482dbfa71e97dd3c010d85dae
    md5: a9028443911823bfd4b4ad29afba10b0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_sbc.res.nc
  hashes:
    binhash: afe26ed9eb540f2650adf6078d780259
    md5: 08b74a319d5d5a9ae5617d41fb2af4fd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6b9196b2b577cb95406bd15dd97b60b0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_solo.res
  hashes:
    binhash: 1413a9a3152b197bff2bea92e602f47f
    md5: 4891e1a4db0535389a81b9319f41e466
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e1da228be755055740ce9109d32c5e18
    md5: 61439f90945c017aa8c9d161d54ae8ba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 180fa2b232a6a1ee36932fa28089cdc8
    md5: bc38ba357b861620c3b573a4601b43a3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_tracer.res
  hashes:
    binhash: c9f93188244d1abd74510fbc5faeb7f3
    md5: d581478f3e68960e7df91629d95539ac
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dcf771b94795b475d9ae690e13ead0e1
    md5: a0cf360d523c183fa24cfcd3fdbb32d7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a0091f73b19b1733cf9f0018605730d1
    md5: 2cbf156a73ff51bf885863b722ab0f66
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 64330e5233696b5b9243f901f049a419
    md5: 7720ee4e441077461d503581e1be9116
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart375/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0c73379c7a6c99471b334beaddb30be5
    md5: 90bbcd75ebe2d451e8806753483dbd4d
