format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/atmosphere/restart_dump.astart
  hashes:
    binhash: 79d0942693ffab325a5e5e9a2b120ccf
    md5: ed4121771772190c37bd5f2c6f36e476
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/atmosphere/um.res.yaml
  hashes:
    binhash: 5821b47ff5624307fef0a8bf272a67d2
    md5: 93d013ef8572b69d89249aed28fd6d42
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/coupler/a2i.nc
  hashes:
    binhash: b26ded23785017acf572807d549b2c62
    md5: 01a4a6ffd805e4389bda212e94863151
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/coupler/i2a.nc
  hashes:
    binhash: 9bf4cbfcce39e5ebdb125825114aaeb1
    md5: a171d22796be5da73e52f8d07a78620f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/coupler/o2i.nc
  hashes:
    binhash: 50cd4fc61f784565e5bfec08036cfb3c
    md5: f2add845468f7972f003ab88d5657d01
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ice/cice_in.nml
  hashes:
    binhash: ce04b467707d0d0d2093790053ad760a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ice/ice.restart_file
  hashes:
    binhash: 0c296de05e43271fe194caa0532cb7a3
    md5: 0760c00690af67def5bde9882a6f2d74
work/ice/RESTART/iced.1273-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ice/iced.1273-01-01-00000.nc
  hashes:
    binhash: d3b8c3328a1547200aab4825b6fb7ce2
    md5: 65dbff84e82626c81d581a161ff26738
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ice/mice.nc
  hashes:
    binhash: ac9b580f5ab3f7a792dba76007fc8c13
    md5: c2a15d488ca40d90018cf941e5bda19a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_age.res.nc
  hashes:
    binhash: b636381f409b1351aa5beeaf20231544
    md5: 416bdd95ac57aa5c4a3ba87f5343868a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 104ff13c7dce1b98dd27f161f9ece03d
    md5: 26151912dd61064ffde950ac9da77254
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bc7185abe3f6dfca0ad549d89e06621a
    md5: f4c3cb9fb9487c8002f705e17e18d83d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_density.res.nc
  hashes:
    binhash: 82749aa8d54054858dc7037307b4c455
    md5: 1ac3067059fc098008f97f5743c98148
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7b2318ee7b4c86f83043868148f97d45
    md5: 199483d75f5b3ea6a9245af1e7df2737
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bf71403564f49e39cefde548bb0223ed
    md5: f5560984f4f35834c7ca8508f7aff854
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4e744fac2215c6cf7431ac1b25c0ce0f
    md5: af04b6b5f5f602637eaf55f646245cb4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 38c77ecc3ddbe2dfe3b2f9ffdeae1bb6
    md5: 4f6cf6f72767eced45ec18f23da4b002
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cf9c34ec8030d43b7d1cd9f0b53ad8fd
    md5: 819a1f63efc5f4780f90fe368d2a054f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 002efa1857ca46120a5b5cc79527718d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_solo.res
  hashes:
    binhash: 49844ae6161c379e6266609fc4f81417
    md5: bd916dc56cc853727242c2cbadc1b08c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c9563bb2df814b8d921c7d36ae40309a
    md5: cfc3b1d3646e6f15f3e7c6f9ba9c0f2c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6c94905bd7b521df1016942c202373be
    md5: 38f10250912244eec424d692d6c5c7bd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_tracer.res
  hashes:
    binhash: e9b2d71a8ba975e24a28ad78c1cfd2a4
    md5: 5568f03b5a91043612d80ffb5c68cf0c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1fbeaebc6fd2ec63a3837b2808faba13
    md5: 1c81b62887a2f9cf96d0b85a0eb5d833
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4e75f3d3d16ee71c5ebb0f1ed9ab688f
    md5: dfd8b960406ad38a967d7d492d081bee
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f484bc735c6e4c5e5f6480d2bec13ac8
    md5: 21a586f341b12f539074d9f5d9a46be2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart389/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b3ed99d300c67f1b7248a54580b79d14
    md5: f637cf08d59fe111481e65a3090b1397
