format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/atmosphere/restart_dump.astart
  hashes:
    binhash: 39cb20793b6c6b6801b02416fef95fb2
    md5: c00e1d7c3d4866adf4a6da0cee9b0533
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/atmosphere/um.res.yaml
  hashes:
    binhash: 94c1fbda2c265b55de870b3ab4ddeda9
    md5: e11219aa586c4bd10022b5aca53a0502
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/coupler/a2i.nc
  hashes:
    binhash: 428d4f4e260f7cbee9434a98c0c707c6
    md5: b33aa573ee82afea8cf7b58e87e4b7a7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/coupler/i2a.nc
  hashes:
    binhash: 53db3d2a9d2f40b452ead23b0954d523
    md5: 7ab4d49dc2b13c97aa1b9b0e63aee848
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/coupler/o2i.nc
  hashes:
    binhash: 809814125067f6dc9ed0443172e1d416
    md5: 2e6db5e129aadaaf216e6d2274c132a8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ice/cice_in.nml
  hashes:
    binhash: b8e12669faa54051f9aeca1f23f71150
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ice/ice.restart_file
  hashes:
    binhash: 3a1d0d265b758edcf53582ffc204538f
    md5: 6b5d194d8c68ab90d1d115f7354c409e
work/ice/RESTART/iced.1236-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ice/iced.1236-01-01-00000.nc
  hashes:
    binhash: 8006fe20a896a290189305dabb247938
    md5: 7d0409d9ba9dc54fe8acae6d276e7c2c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ice/mice.nc
  hashes:
    binhash: 5aeac8f6d0c70469ac6536a57cc1c6e9
    md5: 15dc9bf7e19f6a5a998aadd4c2a5eef1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_age.res.nc
  hashes:
    binhash: c819bb37ae3d213fb6732b3e42eff20c
    md5: ae612d40195a633f6fc483ba14644f72
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4b6f22b628ac5347f84fc5458714722c
    md5: 8dbc42c91230c033d4f34f18848bff37
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 559a34a0847eef04542ea3aeed9d71c5
    md5: 76b2f5ab368d03b57d1bb93f2d2471c7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_density.res.nc
  hashes:
    binhash: cafb8e0819a2779a3e3a749830718ee4
    md5: 84eba7c9b4bfa0315369490e95ee314e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c2c734a7859cf29896b1c26701689c81
    md5: 8b38370f4d0b612484052aa7a7d5a540
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d447079824a000b3aa5b56f7b18ba321
    md5: a631cfb6bedc99bd90861eb449ca2fcc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c3c9800711cc6ff88f2eac68b0e21b54
    md5: 3f398784576ff3d627638023f8257520
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 24ddf262d77b4a2ac7560006ad90d404
    md5: ea7ece6d56d451f111a0354b40d8454b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 881309f8114936b08a07c7221be3c41d
    md5: 0927e5a22e80e5d2e6c4c8f23dc62fbd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9fbbe9a3c3636fbc2838f3aa9d04e319
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_solo.res
  hashes:
    binhash: f71ce0acbf515d8f7d0b1b4ebad90496
    md5: 18d0f82d7c3c35dcc42718678b66ca89
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c4813c05feb2019ddab40c2ff8dea5d1
    md5: 408f313cf61f55008d518a7958d1b154
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 276bf96cf04c12e81aebdfbbbb08a58e
    md5: 6d4054fb4ed8bb49dfc4b7f7133cb8a9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_tracer.res
  hashes:
    binhash: c90f5d534cf85ed040c726989cef0276
    md5: d1bf7cecf8de10bebb59034036b9bd9c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3321983ba3c1db428b6004268972475a
    md5: 0e4506ba70ee063418f3af0a7a62cc9a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2dab2b74302a8fe0729b8253a898301f
    md5: dbd3e591e4e259cf3aa62011dcd87c58
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4a2d18d91e99361fe4eacccc179122da
    md5: a03ac843555ff17df7c6ead58f4fd0d6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart352/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4a1a91d67401f957c44579defe6d0f68
    md5: 21d6fb7135406707c28b12006a00c2f2
