format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/atmosphere/restart_dump.astart
  hashes:
    binhash: c6bb7b21119c0379ea258a637cc9e51c
    md5: e83a391df7a132f27b9d4948ebcb3b8c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/atmosphere/um.res.yaml
  hashes:
    binhash: 01ad3673eba5515cae547603218af03c
    md5: 5906e611e31b2a3be528431b2b09f54a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/coupler/a2i.nc
  hashes:
    binhash: 2011ff7c626f61d842c08b750de1e399
    md5: 98f5e75014b3dff91335b05eb60edaba
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/coupler/i2a.nc
  hashes:
    binhash: 2d431184f8b366d329f6f2d5f9a96ba7
    md5: 682bba14a0b0fef6c64b99416a63da8d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/coupler/o2i.nc
  hashes:
    binhash: a0609832f99aa5a3b2f2cbe70539ff6d
    md5: 416c7492abe9734a7d67e15447b1d2e1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ice/cice_in.nml
  hashes:
    binhash: cd53821ee0b43f626e26b5c095f21174
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ice/ice.restart_file
  hashes:
    binhash: 9176df95226c88a7ffbedf5a4a0fd34c
    md5: f1ceb1a6a43e66d69fa3d125c144a7a0
work/ice/RESTART/iced.1271-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ice/iced.1271-01-01-00000.nc
  hashes:
    binhash: 0da0d4ffd983a4646408cb49ce2ce545
    md5: 052bb509c8b3e8b95df5db4a28b3b1a4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ice/mice.nc
  hashes:
    binhash: 92fd27759160424ad36d81d46ea86a40
    md5: 44986ab0dcae0bec7af8463abbb3f760
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_age.res.nc
  hashes:
    binhash: 922ece444a59a1f37f09dbe1b420e34f
    md5: 1ffb450963cde5a69fa612343dd6aba5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6c3b4827a5b4b229f10d2543fc1694b7
    md5: 6838c1fa3b0a7596926db628d8135b3c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 24638d09f0b62492ff92f91c58fa0123
    md5: ef5eb4d4cb947910910340fd01ab75c7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_density.res.nc
  hashes:
    binhash: ce97340f5eab812f39a18b4b02a39c9d
    md5: 8aba0282d53f3a26428dac84db8306af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b2e163fcd3dfa02609b33b98fde917b3
    md5: e45a312ce07f9edbd8976d90ddac60ca
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7cd2e5eaed0ff322886f416a22030a47
    md5: 3aa60d615b3c301fda852f48378e0fd5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7730d7fccfedba5bef02aaf242de86d3
    md5: dece23e6a69fe7abcd39878e39a14dda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d231fe4bb1f5efe2f445df7ff8b05e6a
    md5: b4ced3ff28e7067129ec14d02bfb9acd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 135052715e222824c00ba4c079f870f8
    md5: 6a9489bfe73a7cf8f7576ad19106659a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 175cae1887c8f489a378c5e5ea0f5578
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_solo.res
  hashes:
    binhash: 4fa99ca20dda13f9bb874afc01368b01
    md5: dbafb25f0c313886e876eb6f33a043cc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 250a7fda11d8fc2b478785e45a60801d
    md5: 32956a5a7119c5d2f63fc58312a54246
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f1f8cae844344715b961a31dbe822e3e
    md5: 1d426f5e6b1869adbe9f7643aa0f1b7b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_tracer.res
  hashes:
    binhash: 4821668f0f1e5384b4592a84b2eb6911
    md5: 04b1136fa7f804ee5af0a2ce3410c481
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b64511ef7c24a392da987872a2a55cc2
    md5: 9bf29804e25971e417c4da94c5f99cd9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b1cc3810d6ee9cac90c8e75c10590b80
    md5: 15ff33ae7272b37c455919ed4da7deaa
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 22e70029cb0399f3514ed86ce51f11d2
    md5: d6b5d3181d415aa78cdfa2b1edaf7bd5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart387/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8f4a8a7bb48db9be25b75ff45e44e706
    md5: 6b2007e7fd737fc6a3f3a5c189ded5ed
