format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/atmosphere/restart_dump.astart
  hashes:
    binhash: 37f119a5bfbca559c0c389588f234f6c
    md5: 2a5e901fd59c869181a5112d77818439
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/atmosphere/um.res.yaml
  hashes:
    binhash: 1bfa305889b849c513619acd9f789f63
    md5: c758713281b32f6444ce7625c36cee56
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/coupler/a2i.nc
  hashes:
    binhash: 0495d92e6b6e690583be2f1fd8c9b0a0
    md5: a8c29dd2831f2ade90563d33b66bc876
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/coupler/i2a.nc
  hashes:
    binhash: 22930b557f8f71e8b77d80f072277caa
    md5: 1163f986899ef2b2ad6e581464c8d7f8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/coupler/o2i.nc
  hashes:
    binhash: ce07e1e0c26418660f6c553fdc18fe93
    md5: c08d9fdcb3dff0370af50f80251eafc5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ice/cice_in.nml
  hashes:
    binhash: 76266e0745706d63007ecb58dede8825
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ice/ice.restart_file
  hashes:
    binhash: eb0d01f8f3f05225537e7b744a447e06
    md5: 002b1a24ae553ff50fb277ef2e783870
work/ice/RESTART/iced.1860-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ice/iced.1860-01-01-00000.nc
  hashes:
    binhash: 2e55a39e4dac6df22285b6087037be6a
    md5: 03cf3e7d8e1dee790a5aab0706cd2820
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ice/mice.nc
  hashes:
    binhash: 8c5acb993aec7cc9c2723a188161c2e9
    md5: 205cc889177576461f76a6a7e7f6c38b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_age.res.nc
  hashes:
    binhash: b7f8bdc8657f7ff95a54eb0fd4acd5c7
    md5: 8a7d2d4e012c752a7765c77ca43e01f2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c48054b21ee207518c51c35b0943838
    md5: 4afdf1faa511a8c1df4b8c2ddd45becc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5affa44b92c0ed0b2a0b1b70e2de81ad
    md5: 896d362bfee73362088eff6c64bacb13
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_density.res.nc
  hashes:
    binhash: ca9ca689aab7ced5f7af53b21e13b1f1
    md5: 54778bc7e8e0d4101fcfe5da57964947
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e72471d2438b1291a35ba1fbda5bab66
    md5: 282088888b05f9a0aba7626e6a70965c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d3c6e231af7393c37745ef2513e26a1f
    md5: 01b56682fd317862145fba5daffa1770
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b5cbe016bae99a07ca4193666fb66c66
    md5: b5e73d0f4b8cd1121a13521b355291d7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7b06603ee35a772efef94a0c57c5ab3d
    md5: 383bb4dfa46bdca691991c93dcea8e1e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 576f43055ace0c783ffc469b7836bba7
    md5: dbda57ff96e28849b493f349deb69f2a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5e46ced13d3051935eb31b979e0ca813
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_solo.res
  hashes:
    binhash: 106e165b6a9502cc4337152cc059f503
    md5: 8eb98bb713b0a9cf3cfab1ec6e08ce82
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 930b7c5c27be3dda65b3688526c60c62
    md5: fde243dd39a5f60a89bb5f4af0d37543
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b734928805be9cf081852b2d8dceffe2
    md5: f745ed3f8aa4f1e17875a7bc7a2d8b33
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_tracer.res
  hashes:
    binhash: e6f4367cfa05f20179f362b2550635b0
    md5: 97275cbd8b14e26d02cc596256e62afd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a7ad93ea4d0b96eb6937f5b4098bc161
    md5: f91e2545ecf9743dac8b825761e3f35a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9be7c511f64c18f0bb78638c6e5b959b
    md5: bede89f6a0b01f8116462e9d2ce0f5fc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 81f71b19ac9f9946b1c307b7eed1aa1a
    md5: d0771cbca127b45f56842971eb7d0c1a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart415/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9207ac1f994152e3b654ff8c802fb9cc
    md5: 86acdef97d8a970d1a6b673de3fb28b5
