format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/atmosphere/restart_dump.astart
  hashes:
    binhash: d33d0269b0b159a5f027267ba37359d9
    md5: ff48c8e6c21e695e6cc3ab6e5eb19c18
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/atmosphere/um.res.yaml
  hashes:
    binhash: 623a5aa8eb0fe426a95eccc72463c165
    md5: 0ab156ff69b741fee624e2f275e1e47c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/coupler/a2i.nc
  hashes:
    binhash: f79e696b74e8e05d7ef9ac403fa4b0cb
    md5: ee7a3c5aa6b0a123068d73901fe098bd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/coupler/i2a.nc
  hashes:
    binhash: ec9c1f47ecdb7bd8006c2ffd91035b3c
    md5: c950a021b48806d9e52c0833ec2ee585
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/coupler/o2i.nc
  hashes:
    binhash: 78b94e616651dc1cfeb4222ebe63b57b
    md5: bdf47eb7c05a59e1df8e15426c1785de
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ice/cice_in.nml
  hashes:
    binhash: 0143d201e825d6f7fc395e342e475bb0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ice/ice.restart_file
  hashes:
    binhash: 3e1f665b564f3814f8b3f223b2a549fe
    md5: 7f311ff381d6ceb4efb4997831e395c7
work/ice/RESTART/iced.1306-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ice/iced.1306-01-01-00000.nc
  hashes:
    binhash: 0d2a18bba865c1b2daa4fa58e2f1b3ea
    md5: 33d8e0bed1bb823b4c4b7c883e962905
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ice/mice.nc
  hashes:
    binhash: 0cd47a90cb019c0570293b5693226f65
    md5: 0f460afaa03780d844c1c0dffeb8fc0d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_age.res.nc
  hashes:
    binhash: 955449460e2d206560ca2ee4f6981bc1
    md5: d15f047b6205fb99daeaeb72bb9bde46
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ce7797ba0f07e67c8c453afd7ff7f8ab
    md5: 7c70dca383debe457bb5bd02dbd003b2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 69f51f453fc2c92907d7a80bfcfd99da
    md5: c06a29a0b22aa5d0f9d4baf7a421cc96
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_density.res.nc
  hashes:
    binhash: 751626eb7dd5ca0e766e8df532b9c573
    md5: 2ef06841bec79d3c45b70e4000b12b66
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7f12bd8747040e38b6cd2ee069697d9f
    md5: 22a954dbe1e02bad98b7804ca2b17a45
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b28b86d48060838dde8b92c17a215b02
    md5: 7f272e7bf7045dc6fa7784b8d11e4d76
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 967d61a44a8d23760c0d055fe7748dd0
    md5: b14b6445e53c21a87f56dbb44e8751ea
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8e07cbef7bc749b7bc23728ff70e9937
    md5: 2693c64ce4c0b246b836ef62aa875a9f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ae73fe72a56a2a7c591dc36dd73e2380
    md5: 4730fa31fdd848a06023ca92dc605e6a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ac86aee01fb2a0c42a3913182bbdbab9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_solo.res
  hashes:
    binhash: e44936702514ae658ec2efd3f578fd83
    md5: 14e04d4044836cb3a2677e2fc33b6ce7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fb7b24d1529d80408ff3a3bc29a12f13
    md5: 2daf49732a875f4dbaad52a54da185d9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8f5eca6052ebcb511eb3fb2ad8eb480e
    md5: 1e0e962f29d3556ceec780e1cc75d14f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_tracer.res
  hashes:
    binhash: c4dc8aadb6414e98e554d3e44afd1e08
    md5: 6a76686e21d1b824c0bff43085c742ee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6d4ec58214ca02f25253dacff79f8b02
    md5: 03681b8bcb64f245d9361e146b2b9d80
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8b21cd62a212dacc823f3080453b05a1
    md5: 71753c8f8c409b78725e57d213789cfa
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a03d377bcfdfc6b262b8e741ff593962
    md5: 8829c0fac14523fd798f35bb8df5b65a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart422/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ae09c9d64ac6de2c101e7567f255592c
    md5: ef55f059dca2bb15d6fd12f814e2c459
