format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/atmosphere/restart_dump.astart
  hashes:
    binhash: 0abc7fcc67b11d19f6106fea35c66173
    md5: f55560dc198ab3cb6b4ed6620a879867
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/atmosphere/um.res.yaml
  hashes:
    binhash: 8954da8ecf54e040d5d6214c320f7006
    md5: 887db8d88ea8de54f13e15f480e069b9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/coupler/a2i.nc
  hashes:
    binhash: 3ceec7255d28b955df56849cc31ac7e8
    md5: c7c8f63a5fd1894eb8e366774c17e821
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/coupler/i2a.nc
  hashes:
    binhash: f7e15a0a4698f74e178e45e26565e331
    md5: bb28e7a6ab7241fb7cbaeba73936b39a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/coupler/o2i.nc
  hashes:
    binhash: f194281d0c9e4a8c9d61546f88b3efa8
    md5: af3776e25856bb6ec62cc0e20cf062dc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ice/cice_in.nml
  hashes:
    binhash: 92bbf80994bc1eb319bc319031050258
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ice/ice.restart_file
  hashes:
    binhash: 1da250b52f0fec22ff6cde4bb8270c23
    md5: 950a4e38b3b7cbae82c4e678aca603b0
work/ice/RESTART/iced.0867-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ice/iced.0867-01-01-00000.nc
  hashes:
    binhash: 065035d693c99cbff4f2f866a3ac4dd8
    md5: 648277ccc5e1d7c2b787a5b3460ebd3e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ice/mice.nc
  hashes:
    binhash: ed2eaede0e49260f08446e355f9fc46c
    md5: 4c108d239362bc41bdb91dbf06d28187
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_age.res.nc
  hashes:
    binhash: 793163947d480d503e9c7015ae2d10ce
    md5: 954b2338c160a1c9c56f83227ebfd122
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7b0302c045449a890321399923e80575
    md5: 399b2233f3fcbbd719641ee3a28cf285
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 27ea1930ceef8162d566f6eee848e854
    md5: 37e8eadda6a34541e3910b7c847235d3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_density.res.nc
  hashes:
    binhash: f823e5a441ec0f3ffa87bccdf4fa1489
    md5: 011b58de48f4c7b0c2474b25547fbbc4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 58cb8ff0cc5114b02f48f89ed5d54e99
    md5: 3da23f1e24fc74e889ec69d39518779f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5d47f80a3b69a5b12d783ff5d219ae26
    md5: 7daaf47018245d554ce3d6549964c76c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 83a20a88cf9d63bfaa7ed9cc76fabffd
    md5: 46d5a1772d12ac0be9d096ecb572583f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 78e6b02362fc4942b6baae7296858557
    md5: 02153bb5b7ae7d039e55ea74581cd9ec
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 15ded55c4668b5f853a37ad705388435
    md5: 886deb8913234379c201ad8bcb9aba25
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f2a7ced21dc2727ec3cb25d86738ec20
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_solo.res
  hashes:
    binhash: bc2b57bbf436638afdbef3ad22f816b8
    md5: 8a310ba187e0b2657df6de6a7678d5f9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a893a1221497624f8c02ef9994162340
    md5: 507ade674cef52d1a25d786c6935def5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6cf9a310b8581f0519c89c2f49e7ba47
    md5: f63be443c0ebacc4f2b5462a6ce8cdbc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_tracer.res
  hashes:
    binhash: 3003c12b4e1a1fd38f0e84b8f2bacd65
    md5: 2e45cfe9bcef17c18ff42ab179b74c8d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7e7e78b5188f1f123440120bffcb557b
    md5: 6ec4e5248ceb8e06427047881c69aa35
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55633d5daf675a66a78cf1a07efc08f8
    md5: d2d2b44f98c59df5dad415deda9c0fd2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b7fb1b3b3b8c94c170d2e82168c46ec7
    md5: a52d0414c9cc271b633897f8cc9f937a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart313/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ac2cd9ed6f9456d71d59203c70ce3fa5
    md5: 512fcb62c349ebecbe3c88288042a944
