format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/atmosphere/restart_dump.astart
  hashes:
    binhash: 54ef94a979470ab7ff0595fb60da7e96
    md5: f1de586d0abd3cc687b8325133b61b79
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/atmosphere/um.res.yaml
  hashes:
    binhash: 0479463e71c069de8cfe864877194cdc
    md5: 77d35824d7e3723ef3ef69569018694d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/coupler/a2i.nc
  hashes:
    binhash: c2d60afd9e73d25c4e1c54d47407b75e
    md5: c449dc33729ccae168e409ab6b4e841b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/coupler/i2a.nc
  hashes:
    binhash: e427c16f473b83dc464434d326836bd4
    md5: 4a692dd7e6996837ae7b51dc2d9d4093
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/coupler/o2i.nc
  hashes:
    binhash: 8cd33fe3015a9c6658d9a693d7030616
    md5: 9afae4a9d5a5cc38b06b22f977e5fdd8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ice/cice_in.nml
  hashes:
    binhash: e2a2391003526eccb73cd5530dce5624
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ice/ice.restart_file
  hashes:
    binhash: 7712a669ef9e617fc7e32e1c9bab6ef5
    md5: 8b8a55d9282cc862429b2c9fe648dec9
work/ice/RESTART/iced.1213-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ice/iced.1213-01-01-00000.nc
  hashes:
    binhash: 7b03c027445dab9f2d208ae7df437fdb
    md5: d904d63dbb8aae00215a4ac7039f401e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ice/mice.nc
  hashes:
    binhash: 761d2d2079ad02fa1d24a2d924c7b74b
    md5: 89e20567fe874856c8ebf02cb80e3798
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_age.res.nc
  hashes:
    binhash: 94b83664f1bc050b2dadb144878646d8
    md5: 7160e0408f0e8bec1ca64948c6a7e88d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0c00ecafe3625d53fd6df8a0b9f79164
    md5: 0a4c7e4cf1e1354431a1de031dfef009
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4aa380a5c70da9851fbf730ed26f5787
    md5: 469d89723c95247b87faa1d2cc60ddf7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_density.res.nc
  hashes:
    binhash: 38fab113842ec4f837bc0c7d38bf2475
    md5: 8f02ab50fb765a4088c01663241b978d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_frazil.res.nc
  hashes:
    binhash: edeb5e289a3cb29e820ff01ddaae5989
    md5: 491e2e93551d60a48593b6447a74e009
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0c82b8f555c8c4c996e5cb01fddd6dcf
    md5: 86ad45d504ab2d861a4c5c99be4d2ff3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5e91b0353632ca503ad5cbc5d4057ca4
    md5: d58ed95034923cfd6f559b56ea9f46bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1d7083facf7ae4ff15f1dc08a62b81bc
    md5: 41c19dfb739005b0211bfa1b0c2ed81b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ecd40beb5bb1336830f97dca438eee88
    md5: 87a144bdc921d764159cd6439101d2ba
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 657bab62c9f4447f9c05a1d8673ea8c1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_solo.res
  hashes:
    binhash: 54e86e629969f8cc704142117227951f
    md5: c8d86ce33b381a6e40a725112d8ea4cd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 947d5c81e0a0da6d52f643051514a230
    md5: 3d806411dab97ee23bd02bfaf20ca9c3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 144ca43445fb5501420218bd9b7253a7
    md5: 0f395a5401c11dd081527a25aeab6f14
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_tracer.res
  hashes:
    binhash: de2982f795b957003184a6dce53a069b
    md5: 098cc3e70b61327505b9128880f7baae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 85b62280652c81ec7cfe7157825c19ba
    md5: e196d3fee9e4216ed9b5e4d5d72528ee
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 50c519cc637fe81fa61d26551677b2a2
    md5: 696dc3928c14d41ac6eb5c706079bcf9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 86a7b4b769766d98345460f2e293a5a9
    md5: b9bda04800585ac5a81a91e806390516
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart329/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1515ac8c292034bdcc7600c7a30014e6
    md5: 6af00e0e680ad191c5ce323d0c99748b
