format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/atmosphere/restart_dump.astart
  hashes:
    binhash: 7151eb7622a4faf76def59f780a7362c
    md5: 9c3a9d94a4f6f54bb229e3fd725f2b0f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/atmosphere/um.res.yaml
  hashes:
    binhash: 8442be7b76652927dd8e98cbda8dd1c2
    md5: 1db820621d4cc389ba07355c263bbae5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/coupler/a2i.nc
  hashes:
    binhash: 882060809b543669a79f567aaf3ec4cf
    md5: 6db8186b3550b605c5b6ca55abba12d5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/coupler/i2a.nc
  hashes:
    binhash: 431c98140f8f7cd5314008973bdf8201
    md5: d4f0d496ca64cce659d0a9467091adca
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/coupler/o2i.nc
  hashes:
    binhash: 4efb15243f5abf4c336cbc10567dd2f8
    md5: e550438c4a3b38b1a4a69671c10b6f59
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ice/cice_in.nml
  hashes:
    binhash: ff267623cd1c96bce81535a7da1659d9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ice/ice.restart_file
  hashes:
    binhash: 6eef8b0d57317bb12837ddddf2cba041
    md5: f4c605d4aa8c655b1095a29efc3a23b3
work/ice/RESTART/iced.1751-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ice/iced.1751-01-01-00000.nc
  hashes:
    binhash: e7f67eb921adab9191ff122d535e93e7
    md5: a20ebbef0ff34ca8f6e89b5dc4d8318f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ice/mice.nc
  hashes:
    binhash: 44bf5a7627fab4dae7228601c3d7df14
    md5: 146d8f7b055dbba2d1d8cd7ecd33e056
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_age.res.nc
  hashes:
    binhash: e4428df6ad4c7e1645697cdadaed1212
    md5: a85503f4b62c431ad20fd6c784459a8a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5a8824e0511f2a8c3dbb26e7e59a3759
    md5: f19997aa0c5d6b38da127cfeabe153fd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b6277d3aecd7de472497ccb277191c2c
    md5: 346f403130fca79906ab1f56c1cf3798
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_density.res.nc
  hashes:
    binhash: b8a3c7148dd2d8c378a5afa7313faf60
    md5: 413364fd5fe3b84218481f02251e5a1c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_frazil.res.nc
  hashes:
    binhash: edf564bd05e7eaf8411695ebf00af21d
    md5: 3bc7a2f106fbadc1f9168a885acf0907
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e74ee356d8f90af370044cee4e7d9d7c
    md5: ab7d3396f65f2c40933768e1745ed9fb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f55e3ad8dff7851e962a3b2eb19eafd1
    md5: 1ba958f7452f9a35d811fcabc6ba6e5b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b949305398880dec2f52ad381387b196
    md5: bc4928dd17fad824e55192701761b0ac
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 69d2a7df85a80a3e0ee9f1c26413fbaa
    md5: d382386b2569c9f8b66eacd43de3d345
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a8eb2bcdefb2649f1ca40385374a8fb0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_solo.res
  hashes:
    binhash: d5f6e198f4f86ff201be49c096ba1214
    md5: 3f966a41dca8cc595c3d66d97dc84813
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4af4c77802c8ce6e0546235eca7fb48f
    md5: b6a0ac8008ba98200c1883a89d69a376
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 405b19a08e6703e11720a0c427b4df1b
    md5: b7137e5096673cf3d202e33e0c0c32cf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_tracer.res
  hashes:
    binhash: 117a99e0eb0e6ab1e7fecd2960cef658
    md5: 95c5018cf6f54a713e3cc300b160f2c0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4f20827b5704667f5df2810c1cc761ce
    md5: 4e0abd46592f66758e36e7f35f0abf35
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ae78c1f2cc05b367f215430c8d74d514
    md5: 1cc74863655b45650b6a711f58ee5a87
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 563675f8fb9fd933d4e28a0a6ec13e57
    md5: 24a7dc95e14748a712f5bf64f233bd5d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart306/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0ed994077f84a8ff8ec2b4f67ade5056
    md5: 1116d9f68f8e0c9d50ab0b5c8745d5e2
