format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/atmosphere/restart_dump.astart
  hashes:
    binhash: f937d111530fec48c52560b912f60161
    md5: fa73a5e4b104f8dfaf5c0009e5669687
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/atmosphere/um.res.yaml
  hashes:
    binhash: 2060d24a6d56f39f7dfd92c267028285
    md5: e4eb221343957003723176fc0a227228
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/coupler/a2i.nc
  hashes:
    binhash: cd15c066c6c3941d17e9ee82fe59cfb9
    md5: 1491bf8ee9c39894ea45d42955892c61
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/coupler/i2a.nc
  hashes:
    binhash: b27e5499d21c90432c30d4c924b70c50
    md5: 5bc49730fe11d0201b9c3e167ecc4b86
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/coupler/o2i.nc
  hashes:
    binhash: 6c1d08aeb94adbfc6e77750d2084204f
    md5: 6c897995fe3346aa166820c73588ff0e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ice/cice_in.nml
  hashes:
    binhash: 203fbd7c5a45f0a782dedadfd2c0a71a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ice/ice.restart_file
  hashes:
    binhash: d7c04e5853e43270b7a9626b910944e4
    md5: f085de0bae3773eb5fef4afcafa5f2d0
work/ice/RESTART/iced.1700-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ice/iced.1700-01-01-00000.nc
  hashes:
    binhash: 4ce1817152f9cf4a300d09313c49e4a3
    md5: 2ec84df38c0e5ac43e65fb37459a6fae
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ice/mice.nc
  hashes:
    binhash: 0c65f7a400f0948d87a4eb8dad0968b1
    md5: 95eba9fbeb2a25cbf57bea8bd279c4cd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_age.res.nc
  hashes:
    binhash: a459edfbe45d2aba8db75c0b592f7e4a
    md5: e65d9def7efb1be5d6d34154fb158fc5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 642353be2e495fb3bbf0b40d7f774fdd
    md5: 130a07fd938e02e0c9eb556eb6469562
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0ab3365cb19b75a7ae904c35f999af2f
    md5: 007fdc8d5efbb8306ca03d0166a0e91e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_density.res.nc
  hashes:
    binhash: d1620485c10dc403c8e6eb7022839233
    md5: e28e8edb545dd90dfb89139364f967e4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 762bf070d44ea50b17b98ec216a14d31
    md5: 705a51da24932b34347f008cbef02a92
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: adcd2f5014831996fff92dc916b5c8cc
    md5: 7ce6533314983c222a1a4e308f2e7820
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1480f38d5cc15bd5d2bf220a7aaef884
    md5: 0e38dc8164dbe59948fec70e4fe6c560
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 24954e73586c66a9487d5a17376a31b5
    md5: b5ca208ffd9ce9bdaec6fdaa2f1dcc3a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c896cdfd814648b0bced5d5c6c9871c6
    md5: 506722b3553a64e73678037654a91180
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d3bb9ec0b96ea094a056ee1f28dab424
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_solo.res
  hashes:
    binhash: a6d3c76128cc121387d243dd4d652f72
    md5: 9c11868d605a0b1ba05da099101d5bf4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ce0fd5b532813a035f4cb605bdaae571
    md5: 83c195f210b9dcd5adbb23661d53fe58
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9c31cc0e9359a0e0f98ad76ab3efef44
    md5: 5b6252fbbd3116fb67b526a0d4c1ca5e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_tracer.res
  hashes:
    binhash: b3001c5b2656b8d39b2b5a26f8784fd9
    md5: 34baeca8398b0e8c762297bedf289eb1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6d15e233171a5ab8ff0ce57bfea958ed
    md5: 294dab41a8a085d4dd01745708da471a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dcc300a3791f2d9aeff4647e6358f64b
    md5: 6f56b5d6aebc115b59cb2e14bb5158a1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 351393125c76457524ae9e7126db5909
    md5: 7fae209f8aaef319de417e5ba75aa597
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart255/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 07ba918d3ea8dd7c828f0f9cfb02e081
    md5: 6f31b0ae325842615fceb19f1f7eaefd
