format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/atmosphere/restart_dump.astart
  hashes:
    binhash: 7bdad706bc00d2d47c0846b5fd51e2c6
    md5: 0401d368d55bb88ea24954fce4550814
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/atmosphere/um.res.yaml
  hashes:
    binhash: 3b9e911b10e1bed07029dcf69c9d3d36
    md5: 896b8f9db0a8514b2b7212c7b1181f7d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/coupler/a2i.nc
  hashes:
    binhash: 38064343f94426f4ebb664650e802c57
    md5: b5d95f648beca6f1deab705a9ee00811
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/coupler/i2a.nc
  hashes:
    binhash: 360809c628f5386d7096b9453e3443da
    md5: 2a1bce643dc463b8c421eeeb810295ac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/coupler/o2i.nc
  hashes:
    binhash: 9f8955e354f79c8dc6f60153d9616349
    md5: dbe96b43a42aad6eba0a9802f7564c5c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ice/cice_in.nml
  hashes:
    binhash: 490bfc591c89b3ef7e1473728791d519
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ice/ice.restart_file
  hashes:
    binhash: 99e6df82433cd0069bfee16cb1bae4dd
    md5: 9a733f5efe60be1ee12ed0108fd21ae6
work/ice/RESTART/iced.1160-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ice/iced.1160-01-01-00000.nc
  hashes:
    binhash: 3d2eee58b46f19e63c643081537b3174
    md5: 6e6cceb0f91cb5256e7980275a99c02f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ice/mice.nc
  hashes:
    binhash: d3a83d90054cc2dc7bc625612d138916
    md5: 3e971f895d4624efa2ad98c3b1f32966
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_age.res.nc
  hashes:
    binhash: 877c50e7e3a3eaca4859210250caeb99
    md5: a30956b29f30c23cd4620d8049f265ee
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d66cddada9bac489e2b97d481d857e81
    md5: 787feacc1b8242b06dfdc24d0a0683d1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2079619d65da81ab235d2a0f00f279c8
    md5: 6fd359a9f2023373499537a7dbe274c2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_density.res.nc
  hashes:
    binhash: 1c7dc0e76c115b9f75f131b460ced51d
    md5: d16cb22ee5ad60cca2519af93c372cd6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a6fde69b0cac23736fbf48483c573e8b
    md5: f54c917ffe55adaa90dde7877ee3141d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f5105467b967466a987e7a83bb87eb67
    md5: af5de2bd238958f16c73ac3eb8ea97e4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7da255e8347a013f4e09b666996d7b2c
    md5: 34ca370cbea21abdf526261bcd4cddcc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 75288d883b9c2a611e13a8be631b0257
    md5: 33cd2da60b625d4a42bdb618f3d1e3c7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4b57bc37551328856ccdd807776cf2f8
    md5: 927c9ad5434e8f6654212e340385c43f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6089460dd0264f4448f0869a34b0ec71
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_solo.res
  hashes:
    binhash: 13f1786918130d420a57832958487633
    md5: cc9a14cae4d69880d0fc5d598790880f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cda024b4bcf7ade47a2f32b7459375af
    md5: f9ba70c1aa82f6d5158df0709e6c290e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ebad201513be38424fdefc08b6529f3a
    md5: 45a36cf30968c9cf682dab326d6d559a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_tracer.res
  hashes:
    binhash: 3c0b7df0be1565ed9167009501adf1ae
    md5: 8817a84063fa460c1b00aed32e141380
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 894f513466de2bcca737925725bb88eb
    md5: a4a2d39bcc074ab66f858acb79a1eb03
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ddd2b06e4ba74f0c00490b672c5d757b
    md5: 6b6876f3a040b64eae096d869b87cab7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0a3a543078b21048a35635bffb652a91
    md5: 89c63d3a61c45d055a488523aac6c539
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart276/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7b4dd98b2734bba82878e04cdc98064a
    md5: bfc206769ed6ee375cfab2f274618293
