format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/atmosphere/restart_dump.astart
  hashes:
    binhash: 80601e591e9d1892f813161bf870bbb7
    md5: eedaa00f1a3d14176a26e92486bf81ce
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/atmosphere/um.res.yaml
  hashes:
    binhash: aef2cddf6846bf6bfa099f19b57ec845
    md5: ee7a0c6b861892727b78ae69dd244ff1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/coupler/a2i.nc
  hashes:
    binhash: 2d1b3dd0ed69099b6613a7545c1cfa88
    md5: 7e1db927d9423040ebdda64b34702436
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/coupler/i2a.nc
  hashes:
    binhash: 93490691756bc971cefa56c746386fe8
    md5: bae0453cafeb9c3fdcb95e44d167c7cc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/coupler/o2i.nc
  hashes:
    binhash: afac6f17bba95ab2c9b62dcd2d9a24e9
    md5: b1203e118ce847108b062832338544cf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ice/cice_in.nml
  hashes:
    binhash: 9b0c682fb325ad8b523ef1ae421b358b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ice/ice.restart_file
  hashes:
    binhash: da478f0118b9a53f0b484c1fda1eaa53
    md5: e7cef0b300b8ee2ef9f497a1e5226c79
work/ice/RESTART/iced.1863-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ice/iced.1863-01-01-00000.nc
  hashes:
    binhash: 861e1787f284e0d08afc6eb8f7a049a9
    md5: aa7f3c0ee0702b3c47ba89f333d6f342
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ice/mice.nc
  hashes:
    binhash: 5bc5f7da430ca33c1289fe8e7f6a55d7
    md5: 2b12aecaa8aa21deb0d0563d8d61be6d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_age.res.nc
  hashes:
    binhash: 73ae93269258ddf56c897f5ca4de8abb
    md5: 3b8a27749fb49c2b0741a01449bbc04b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c3beebc898bb0a48acb81dd53e820007
    md5: 4ad7d83f0a5e1416125e82ddf0787395
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6c212df10b20748076496616e05efeb9
    md5: 5f9f7c18a60f51ecc12ba7f15501f84a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_density.res.nc
  hashes:
    binhash: 813c2686e2ca85f3bcfc98598e30e92c
    md5: 5a4ca05b40cc4afb925c4c89d5f74634
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2913f601fc58eb5db49b8f65420f753e
    md5: c1488e9ca3ade6c2d3dde716de9afd3c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 80eb4977e445230d3581b108c47475ec
    md5: 47e0b35f7c1b6edb58cd44b3123c3a09
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 753135ccb640ff555a799ef28e62018a
    md5: 73ad9bfd5358975d3a4c1d021ad9c512
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 57bd22dee7bc1a23c5d67f9131c15fa0
    md5: 732502390126bfd2e436b8768e7dff08
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1bb7d5011e379898ecd070d3680e68fc
    md5: 6c2f39d36961ddcb84002f2bd6cd6743
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d8b5e44a966f3c2a1fb56e514119ffd7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_solo.res
  hashes:
    binhash: 8f4cff911911ff4c717e64e2fdee69d2
    md5: 454ccc018c09ffa209abc6b15b2a2ac2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bf3e188319ffa4417769653bd07b2f1b
    md5: b8a7c5033441a4b8341d83c53042191c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d9bd3ddfe0bd9506e2d6be66c615a7b6
    md5: eaf2eaed13ab95f50fd7e974dff10564
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_tracer.res
  hashes:
    binhash: 0e1feeb5e5c09da94f65dbf82465385d
    md5: 0de88f6101990e8463e785c099322787
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 64225034012913ab1659f77e8f61d177
    md5: b0a5831d9d156f0e13e49469ee2eb3f0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 97ba4745885a2882d501cfc225a96fe2
    md5: 2ee28eb87c3eb3f4978f37966ff6f476
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c5f30021eb35dc87d8fab10e6098f83b
    md5: 890647b7e345a6e5de796f46c4e6d334
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart418/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9b06ee347a371e37bdcfe2f2e1a0fc10
    md5: b2e4f3d848dfeb63f402711fd5a7e3ee
