format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/atmosphere/restart_dump.astart
  hashes:
    binhash: ef988b388059f1e7ed6f01f6893170ab
    md5: c94c02f337b1af0c44b95604f66449c7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/atmosphere/um.res.yaml
  hashes:
    binhash: c2aa022a086f6e496519611d7be6cc81
    md5: 470643916577d108667f20e9939d9d06
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/coupler/a2i.nc
  hashes:
    binhash: bc467ee67052b2e70a357d92a3de4fc8
    md5: 4c82faa0b6e7f4e9afe719db01908522
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/coupler/i2a.nc
  hashes:
    binhash: 0c1d753f75191ea7b589833a8e659915
    md5: 26928164fa722a34fef2c467560f3d91
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/coupler/o2i.nc
  hashes:
    binhash: b4d7c8a8190ad6e6a9cfeb80bd559182
    md5: e1e3b168d252e89a1f8805ce630a5176
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ice/cice_in.nml
  hashes:
    binhash: 467e5ea74155c45df51889a21051856d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ice/ice.restart_file
  hashes:
    binhash: ca27338537de58e99fa1ccad019e1225
    md5: c3e27a3966989a38eb4f598d0331cc0c
work/ice/RESTART/iced.1716-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ice/iced.1716-01-01-00000.nc
  hashes:
    binhash: 1da2df9477f762f550007fb56f66bf4e
    md5: 9646f5580610160ff393e662746f2e74
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ice/mice.nc
  hashes:
    binhash: db16ef87089460e415370c2aa0216968
    md5: 52633c694ada8eafcdef5754bcb2d0fe
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_age.res.nc
  hashes:
    binhash: 7986a09afde2797c72becdb4f96f46a1
    md5: 8d7e4b4d64a52e8c6cd22d475dd4ec14
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ed0ca73228fe091a46adc33d2ac393f8
    md5: 348e2f9bd2d94f4d31fa9a34b804aa8a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2808a810c18eec2f15d28108aabf2329
    md5: 8c6655f0cc92cec3d4c9457587c42cd7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_density.res.nc
  hashes:
    binhash: 8e0e6c7c683a22b2e2f53c6a2b94542a
    md5: 52ca5b6c9d3cca9a4bc5f71a89981761
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c8058e6937339a3ac95ecc9d17d3d85b
    md5: 57e9cfe16f9d689a0f50b2b2bfb1409c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c205a2a7edc5b88261a9671397241069
    md5: 4ee2ba72d6775735fa23ba5ece59aef0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 66ab9a83400612ded5cc275c4cddb442
    md5: af501c19bcb1524e15dbffc1bac441b4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c6a140805001c96c86ec0326c89b11b0
    md5: 057cae63f5b159f2dd35313a40b0c8b4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e7544adfca531993a6a6c7ddced34d0b
    md5: 26e18c240d3458363eef6437b0dc9a63
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d61cb11121b43705fad2db33f664010b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_solo.res
  hashes:
    binhash: b6b5673e94431e368f98eec0641759ba
    md5: d06da6cbe3e247ce16fa3b33c988abfb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bb9a20348371d3e05f6a025a570f575c
    md5: a77bf437af51fa818029f04d6e8f4f9c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8723d04076c3838eae45747042cadbdc
    md5: 70e7816f46314a94e5877ddf7ad97ec4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_tracer.res
  hashes:
    binhash: 726e0a9160b544832cb588cfeb932a8d
    md5: 337049b8f9e351113914791f1cb6fbe8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4a43ddfcad15164efc379f34e58acd08
    md5: b11f511042ad41ec3e2f229a9ae929af
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8b63dc999db2b60a5c809492e4050fe9
    md5: a0887aa78016798b37f926fea4b8f6af
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fe7e6784787bdd7b59e141edf1835fb6
    md5: a6fa8cba1fff6d9dd395171415df4e56
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart271/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 65829389245a41546811452d6aa90d5a
    md5: ac68e81b541aef059aa035ba520e1d5e
