format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/atmosphere/restart_dump.astart
  hashes:
    binhash: 5e80ac1945c8bb876c57c5dd2f4d1a96
    md5: 67c0dde78863e95f5cdc818933db361f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/atmosphere/um.res.yaml
  hashes:
    binhash: 1721207d7d303cf66ce89f3408f2c045
    md5: f61163f3090419cf69a133d283f5845f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/coupler/a2i.nc
  hashes:
    binhash: 2cbb655d91cb63dbaf9a88878a24ecfc
    md5: 8f7d93915de46d4719a0ea20ed4dbc20
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/coupler/i2a.nc
  hashes:
    binhash: 79ea9a1347c83c0d9ba62dafc04f0575
    md5: ef34592486c494936190d3ede68d49f4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/coupler/o2i.nc
  hashes:
    binhash: 12ca1f85dde9c48b94865518c8e1c1a9
    md5: 15c13ccba78ce2f0490d92a3ddac349e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ice/cice_in.nml
  hashes:
    binhash: 12d85051ad60ae057c5371164c9b6859
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ice/ice.restart_file
  hashes:
    binhash: 6027a6d9c48cd7455eeea138925744c9
    md5: 34eae4a037c6b9cfbc9641d3d77f201e
work/ice/RESTART/iced.0986-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ice/iced.0986-01-01-00000.nc
  hashes:
    binhash: 304c635ee362e3cc79004fc77c948dbe
    md5: b6261f74a1ce3fcd8bb73b77be450a3d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ice/mice.nc
  hashes:
    binhash: 1ecd93d7de288f7cfd01c45897e21bde
    md5: 9c173a6608d4febf8be23a3d53a20c95
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_age.res.nc
  hashes:
    binhash: 3f0a1c423b4e29483e4ea17b370a274b
    md5: ee709b8ef71b6bd4bfcc87b8b42cf80f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0eaafb537acdaf58aaa8c1cc5a518cc8
    md5: 344ca927f2e33bd47dd91ded6361850f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9c19c8a4c2e3cf0b304e5b7e1e5ca1c3
    md5: 225548ffb3b536210e252481a881c9fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_density.res.nc
  hashes:
    binhash: 7f7e7c36c0ce82ed4351b5eae25cbe7a
    md5: 7949b699111d90124fd58e7bc54bb18d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 16c33338af6cb4f336684bd0ae711da0
    md5: 616df0206293f757028158183c8f0f02
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1c51180d8e3a63beeb88bc7e9b7fb720
    md5: 329502eec8afb973e8e86fd3e5da0d82
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d96b956a180ab9c2f964d56c98d1884c
    md5: 40adfa3da94c55e4234fd45522c36e94
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5fe16960a644eee878decbfde65976ea
    md5: 3d9cc2d55f44e78f850e24f337dd47a1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 617ce724160b36e54dbeef62a08d563d
    md5: 15558670f8e16c1203ecf63561c5d462
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: eaa979450e39e72d15f6d6e302714014
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_solo.res
  hashes:
    binhash: a3c95e0494336dd44407fc158224e125
    md5: 02a4acb22d9a5543d38d8161c156d92d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7d0bf43ccde4654eb6f588c2ea752d64
    md5: c806f1d4b67f631506a01c29401c42ef
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ed78ebc414af0184f72609bd0c3f4261
    md5: b87cbc3dc73df963049ab56c8d35e015
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_tracer.res
  hashes:
    binhash: 9155d4fc68ac2269acc2c912ce4f85d2
    md5: fbc6fc0e913df058c1ed58c5c679c618
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 58354f478e266b1f3e0dd313bf5949cd
    md5: f67f4728ebd3b087a58e23cc1e7966ad
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 46efcaf4704178923e3a7939886057d7
    md5: cf89823df253b0f1940a7342aad90fd9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 73c2321d4f8947330e7354ac85fb1924
    md5: ab5f1a5698358ba7840f29c30ad4faf4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart432/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7d15fdf0617a0e3d75eb9a061e2c3975
    md5: d03b0d3edc53f7b03efef51c203d0b9f
