format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/atmosphere/restart_dump.astart
  hashes:
    binhash: 654e76942d39297c3bd293bae59cc34a
    md5: 317abeda51a11186dd7830631ccbdb9a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/atmosphere/um.res.yaml
  hashes:
    binhash: 08509e9fab3335405fa46ee02dfa4622
    md5: dd52f227db701b07f64e11bf3a52d945
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/coupler/a2i.nc
  hashes:
    binhash: 3989688810e810bc0fcd12553f7243d7
    md5: 88de331a29c2f4cc096106a4635d4630
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/coupler/i2a.nc
  hashes:
    binhash: 5d846c0960c3fb5088f4d17fde1e1c59
    md5: ffa65e040cc823e2990cf2b54e031ef4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/coupler/o2i.nc
  hashes:
    binhash: 45933c3f7aac950839deb3c389485228
    md5: 7bfe9e1893826d51f801e634eb782b74
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ice/cice_in.nml
  hashes:
    binhash: 7b8f7f1828aa01060c498071ba1ac189
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ice/ice.restart_file
  hashes:
    binhash: ca986700996baf6b5c3895abc0d4be8b
    md5: 5fc0d311885dea14d2ff7528af14baec
work/ice/RESTART/iced.0832-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ice/iced.0832-01-01-00000.nc
  hashes:
    binhash: be96bd276fb8347f674ae6c6978f4b8e
    md5: e493ed21e2d705db201943c533386e3b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ice/mice.nc
  hashes:
    binhash: ee0136cb92c937642fa35245e36b7a07
    md5: a1311a40114463d77ef2c4aff4469db4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_age.res.nc
  hashes:
    binhash: 62c4e5946015ecf9f72041f36fc6302a
    md5: c64dddc2d727357d2e43e543a2807f59
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f7670f9043499dd7cd32b16c9d14f730
    md5: 15fc52fbb6749cf5099f42686868e8fa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: df830a68c6c9300c0b677e53c0232edc
    md5: 99cb549a5580d6c6d6c87655f2213095
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_density.res.nc
  hashes:
    binhash: 8691691d3d3826a2fbffca177e63b5e9
    md5: 7b43f865d99000755072e6e351291dbb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 394f04154d4bd1bbba29ba4e46ac9bbd
    md5: 5741ce455f5017e3f22ab294fea96799
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2ea3f0d7eeb738746f216eed3ce15d9e
    md5: 32afcd20f2e011d70bea3ae2486999e1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 43abd35a831f8ee27dd6b475cf91af4e
    md5: 01ca48bca6f5a5b93c73bfb5fe49a7a3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6948622ca5f773f8ef34f205d90ae811
    md5: 1a1e2a2edef425e9acc0930689f09564
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_sbc.res.nc
  hashes:
    binhash: adc41147908903a10c8917af1b2327e0
    md5: b7b5d734434bc4182c687cf9d54575f6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2ffe774944f3cbf582cabf7f3dd5f2cc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_solo.res
  hashes:
    binhash: 7683f8402cf467336513be4e4c7c2ad3
    md5: d7ddedb978e1112fd85762bddfc34ade
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 496471f6af5c59d968ecd086be8bfea8
    md5: 3a3464cb90ecb7400f55b5ec3ae82a0d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c742da99bab3845383d9f1ab53849267
    md5: 1efb85d896af2b9364858f45b4aa1e4e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_tracer.res
  hashes:
    binhash: 51d0aa5722c1afc45968a962a0eaf012
    md5: a932b76549cacb2d7db5627af50e1393
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6b5cdf54d3205b942ade96d8ab028ecc
    md5: 7ec9bb23a96913182d692b92c4a228f4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 28bce05059080f8250a5ce39f038f71b
    md5: a4444469263786bd2154d9cd351b4b5b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0fd513ee045709c8846677d6a50c7b83
    md5: a4dad5d7a971e44fcde27dc2238f55dd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart278/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5d7b392eb0e59ca2e28ebee494aac322
    md5: e89e48d16f36973046df7fc4eaa3ed05
