format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/atmosphere/restart_dump.astart
  hashes:
    binhash: 1a3fda6cd0842080327b2f7a2a87ad88
    md5: 1595ea4d0a7be823a4af24f5f57f6a9c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/atmosphere/um.res.yaml
  hashes:
    binhash: fc96d05381cff717a837a6678ed768d6
    md5: 9f9326daa8b9664b4eb3cffe80f0fda6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/coupler/a2i.nc
  hashes:
    binhash: 680ab17aea27f1614e3afad41cdefe92
    md5: 657f0ad9569f2d4ff18f7a612bbf141d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/coupler/i2a.nc
  hashes:
    binhash: e6724ce8521fbe47772c9368790407dd
    md5: 8c2b23c7bdc495c4388cfd0c7799ff0b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/coupler/o2i.nc
  hashes:
    binhash: ed77362250f8e1b6d4ee7db06aec4dbb
    md5: c8ee969588e5ca8c3dd753b080129b52
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ice/cice_in.nml
  hashes:
    binhash: 1fcd50357759ddacb8771ece53ba00e6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ice/ice.restart_file
  hashes:
    binhash: 560afd64eb949a62a0ab2b20594b3ad8
    md5: 5ff740239bd6be43efca941919877364
work/ice/RESTART/iced.1798-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ice/iced.1798-01-01-00000.nc
  hashes:
    binhash: 4b25e46fae7f6f87722de2ab97c87f2b
    md5: 5928805e003bf43a31ee61350e3d2c9c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ice/mice.nc
  hashes:
    binhash: 9c0ac83b93a394d4bd57b0f9302fe428
    md5: 9f1774a80da83f1263afae5695233f41
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_age.res.nc
  hashes:
    binhash: 4782f19fb59984ecd4f525efe5b6f542
    md5: f82618f3706b42b3e635c894960498c9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 72b1c8c9b06dcbb5feedca6712e65386
    md5: 5ea41d49e5fb432339b41ac43804f064
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 271dd16821b8b4cc2ef74a035382bc01
    md5: bf3a895d903f4594adf5a147dbb292ad
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_density.res.nc
  hashes:
    binhash: 0d1dd7fbc0055312ba7ca42d1de1df54
    md5: c8716f9a87ae32ba920212e3cd8bb083
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f963dd6065cc975c8df444a065ad3c84
    md5: d4321b062115f5755c5d558182ff904f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ddceb68fc4c1bc13127a2b0824e1baf4
    md5: f0af87ddd8ee1b2f214712cad37d9826
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7beef4e0f48a0c179e2bffac3d563b07
    md5: 2fdde1c378416be126a21e1e3ba78a33
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9120f1c4418b6dc8046717f07d2efbf4
    md5: cd3754c8754229c54d14f1e3349be2c7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e4c04bbf44c22f014e405afc281bae0b
    md5: 8812d6bfcda05f9e4411e11fde05b799
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 53100b770b1f4bcd5d8d17721b8a766b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_solo.res
  hashes:
    binhash: e9fa29732c2b6663d131a73dd96a5871
    md5: 482f27ddfae15769403310ad3826d813
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 88e151b91e37ca0951e90004bf244479
    md5: 9a21c5dd46d0cc15b56b46777ae5da6b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7838a2e88e093b0b268fd02d49c94c0a
    md5: de987f32655e89c5949bc11b718d28c9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_tracer.res
  hashes:
    binhash: 57f64e3bbd149ad3bd033ab89c9159d2
    md5: cc2803091430f93660e632ce8525a815
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5b8724ff3f06f679e0441ef0a3eed72f
    md5: 05a143bc8f952cb425d918c2586bc251
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9e49cdb00272d9c7739902f1e999722c
    md5: 6782f50341ec7323eb7570474a359eed
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 73e6e60a8013683fcabcf6fe0ba4b2d9
    md5: aa389e633fa7714c86d0df49ac1adeb7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart353/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dbcc186d7fbb4dc12a7396c2f0ec5c56
    md5: 35d5088d871386771d06949060f8bcbf
