format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/atmosphere/restart_dump.astart
  hashes:
    binhash: a31f8a1f93de112d4b15da7afadb6e94
    md5: 13b5df60ffcaaa6c626df81aaf2155af
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/atmosphere/um.res.yaml
  hashes:
    binhash: 245da58d58237ac68ba8adaae4e71d7d
    md5: 27c5907bd40b78044b7e72f1643f18ef
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/coupler/a2i.nc
  hashes:
    binhash: 2858db0b3603c3d1c36dfc170c4616da
    md5: 97126a9e5766ebec01b75cda7afdea94
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/coupler/i2a.nc
  hashes:
    binhash: 695064802aff414872b8d45ab76276e4
    md5: 2483ec1aecf34304785d67a3a1243cbf
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/coupler/o2i.nc
  hashes:
    binhash: 0f69b5e419ceea00a6c053db17b18cf2
    md5: 4f87078443670ca024bf31c8a289532b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ice/cice_in.nml
  hashes:
    binhash: 495310a54b2e53cfced841eaf760153f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ice/ice.restart_file
  hashes:
    binhash: d5ddd202ead20759d9f349e5d2d3d949
    md5: 1bab904989d9e412b8403f52f9181b56
work/ice/RESTART/iced.1789-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ice/iced.1789-01-01-00000.nc
  hashes:
    binhash: 422c054a46455c6cec9a15671244175d
    md5: 719187d71a308f52d5a0833f6423e5b5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ice/mice.nc
  hashes:
    binhash: 52cca525a17707260cb82e080c9ce793
    md5: 8c2ef9039f9a531e1dbd2ef338b0dade
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_age.res.nc
  hashes:
    binhash: 635af8929a6b0a21691a72744aac9ddc
    md5: 94b8b3c4cf6d8b446bad37acee13c36d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2b2cce38fbcd6c6080936d9a160752c7
    md5: 37c033f13f7ed31035a05a54705882b7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 075acb0d72633a9bfa20be66455d7a3b
    md5: 461b64d2037e47b55210b8b0f959924b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_density.res.nc
  hashes:
    binhash: ec26f667cb17fe90d20c403de59ed437
    md5: b38d684387c9e2281e317cee9fc5f90a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1e0308cadd113dd053ebe4028662b53e
    md5: 3a26fa9b89376821b1c0f89d648f0bec
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 466abc80711054128ccf3b63952a9340
    md5: b9a350d46a94f2563f1b079bf18ae566
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7cfd3a3a062b9c8c09031f6b4782ab35
    md5: 0ecbc519ca4f58aacbc232b793c62509
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ca7fce5a3acb74d42bd8859f6393fd82
    md5: 112ed8f79eb68051561a7033fccd6ae5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 17aed9cac51a5b61b72a5af17d6f3273
    md5: f7b8d32aaaec6078ac54a5effd0f9832
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 268b56d7563fe2979f1d26d0d91c8a11
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_solo.res
  hashes:
    binhash: 55c7ef32e40dc9aaa6c7812dd5f1d7ee
    md5: bc7afc69d78064c8bcfc1275f9f36dfa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2e18620fa073d2f7e591aa9829d1b8ad
    md5: b8b77efd39749505e31be0440748c768
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eed11c5f1002da6e6cab366164384c93
    md5: 94b47325e208f7e951774fea716dbcd8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_tracer.res
  hashes:
    binhash: 8d63ff5026fd2d2b13a69d886dc52139
    md5: dbf2348fbdd1f35ec0abc0550ced949d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 05804610bbce94272001236ac8eda9c9
    md5: a5cec95dce88414935c62d9e7ea25a7a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 016bd0c29d57de614eb59b9a416a9d40
    md5: 7f4ae1a53f5469cac863da22f8bb0cfa
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 941c537fd106599b7a189c164f81db6e
    md5: f6928d2adbaa8008dbc113a321a20aa8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart344/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e36790fae2115fd257ec6ec3a3a1e6cb
    md5: f2fa76238df5d08c807886f20be1931c
