format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/atmosphere/restart_dump.astart
  hashes:
    binhash: 8af73e65fda9c82ced15dbd18d27515a
    md5: 8ae28fb8be303bad6b703dfbb9455c55
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/atmosphere/um.res.yaml
  hashes:
    binhash: 9946662213087ac3a6fac2c4e9516ef4
    md5: d13b8529912734fc7c2d4b81e775abe8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/coupler/a2i.nc
  hashes:
    binhash: 6c34562fb3b40653c6a34c4cf64692d1
    md5: 1875af2653d3d339184984c67b44e8c2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/coupler/i2a.nc
  hashes:
    binhash: bcdac1178be752eb7bca85806c35daa9
    md5: 5c636a54c5fb2580e76280bbc2616a40
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/coupler/o2i.nc
  hashes:
    binhash: 1765b097a767af8879006e3f579ec615
    md5: 83fd067b1f4fd986958dff3dbccb191f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ice/cice_in.nml
  hashes:
    binhash: c02aebe7ffbe3a652847d62b85636073
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ice/ice.restart_file
  hashes:
    binhash: 4c199cd0fa634c2e59e9bd39e4d7c23d
    md5: 3d7577163de84b3792147e081d6b13b2
work/ice/RESTART/iced.1808-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ice/iced.1808-01-01-00000.nc
  hashes:
    binhash: 73af7420e30ee88225804bc0f736b5f6
    md5: b199f81d5feb954de08f7059779d80ce
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ice/mice.nc
  hashes:
    binhash: bdb5a79060c8d86b0920d18fe9c65865
    md5: 7d04fb56db972c8ac7dc1e9cd083f623
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_age.res.nc
  hashes:
    binhash: 93584c6c050f54c8e4d29b0e0c56c81e
    md5: acfbd5aab0b97dd1e9540f9d330a4392
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3d08ab8d60717b2ab39f8ec978749e65
    md5: 181adcae43c3423da85891942a15f385
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3ba06ddc5e8768cd04dd0f57378296e3
    md5: 248b13b8610a6cb0a032bd3ead3aec67
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_density.res.nc
  hashes:
    binhash: a73aecb380c08b875d9d21097a2fe84b
    md5: ed489d0ef7052f7f47cb9a0d998419eb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8e521586f5e2c75a50b4d022cd4ad290
    md5: fb2e88475aad83ff83b504d743848547
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7a88927ab386d85fa35b2eecd453469f
    md5: db8475dc0f83122dc9b092b58e8dc393
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8bfc5586588c060e9983d10dd4773d5c
    md5: 560ffd7cb76fd48e265fe191e95e68df
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6a7051dce016a9726aa968559a4ba138
    md5: d314e8bac2dbe07b32c9e62a36c80f7c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6c2eeb9f16c5cf7089e848134586e1c0
    md5: c974a87aba46965094f31e1b24906563
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 647b26eeee324b079675cec023213206
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_solo.res
  hashes:
    binhash: f9a9e3dd290d91e3eded9b183a668e28
    md5: 570bc21ebdaba014475f9cef14414566
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: baa0b34df2a04340e96ee42a931151b0
    md5: 238d74b86860add22ed5f1a3e3c33033
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e90b6f76f5ebf0d4d8250871d7eaf0e0
    md5: d6ac356f9cfcf8b025d19c663ed9a74b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_tracer.res
  hashes:
    binhash: 29b7e08756e6daf0c5bf630ee0b8ea23
    md5: 8681bc01b80646aa11b3c1693e68c6d2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 01bf2de5b1afa5addf12ac5243084e57
    md5: 95717815026486d7481b0922d3ed8db4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3ca5c543b4e43c8b17b0ceb31e10ad5c
    md5: 63d926e774cdb08e22b962e482b104d0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d98999adc022369923c47e9532225487
    md5: e8fd6ebd52db90ea204101ba01e291ab
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart363/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ea63b4830e801f6cb64ae3bbc1fedbd1
    md5: e5e524be40cc44fbe11f2b5e3c923c70
