format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/atmosphere/restart_dump.astart
  hashes:
    binhash: 275baa1c736789e28f33e3ec8ff98f2c
    md5: 673a81cb3b322f0cec440a3490951b6d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/atmosphere/um.res.yaml
  hashes:
    binhash: 5cce77ece3f5685f60129942d8ffd757
    md5: 5fc7b833a9eef19363174aa9a279bcae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/coupler/a2i.nc
  hashes:
    binhash: 3e4bebb7fd0cf387673b7fec40f363ed
    md5: 75372e37941ec5e671db8ef322ceb28c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/coupler/i2a.nc
  hashes:
    binhash: aac387d32ea43ddb84ed3a19fe72278e
    md5: 345ddc459921b546b75b89a65a30d6cc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/coupler/o2i.nc
  hashes:
    binhash: 1140f2200f9bebfca0c2eb43a1c0b736
    md5: ab0d86b7fb32f4bb06e966276c48d8e1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ice/cice_in.nml
  hashes:
    binhash: 80d11c76348ebee4826762b303c06534
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ice/ice.restart_file
  hashes:
    binhash: e351b76113384f9afdc514ecd91a4360
    md5: f746b14cf0a1c61387a5cd4c4d2539ce
work/ice/RESTART/iced.0893-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ice/iced.0893-01-01-00000.nc
  hashes:
    binhash: 31bc60f7c3f555a741959e400192fc15
    md5: d147a464c66df22db05b070f2ce4e958
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ice/mice.nc
  hashes:
    binhash: 9af6f2f9679874dd6aac673c60bf0feb
    md5: 19017f8d87e23e878cf7b1ac680b8dc5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_age.res.nc
  hashes:
    binhash: 634344b05d69823d6fa91bfb584a0e1e
    md5: 454a6df94bc8266bd508ae6c32b9a37a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b1e215091a5e805c2448f65d0260329f
    md5: 6ca4acf7ddf0a99d015ad641383ee620
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2e0d76ab1580f2946d482171a9593f70
    md5: 5412dd7ba22e1ef8ac6549e396e1d7e7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_density.res.nc
  hashes:
    binhash: d1139e2c8f452f8d9d68d5c22acd1768
    md5: 6dde545eb522f75e8387e885232eefa3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c795fae7e57136c80cca2ff7a3852684
    md5: adff00e33cf416daa8a5a6605b9d037d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8660df49f0930cf8276e387e9172952c
    md5: e77041e2fee6eb1b26ca437e898316dd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f00dfd89b4a302f53c0320425c4a37b7
    md5: d37a75966eefad72c9bf43491991ca49
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3a38cf0d956d6d42715a440581df138d
    md5: 536c318c2405220d6430b412f3a5ac1e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6a4eee5ab95399ed78d9a78e93a4229b
    md5: c85a904964f243ba8f620cc764b5044e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dc8c5d5fbcddc0d79037b92aa6fce719
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_solo.res
  hashes:
    binhash: 1c8bdf7b3e990492e8825e90eb3b67aa
    md5: 46222683a62647259dfeb3d171b98b01
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 57e16075f1d82d0ec6a5e72001c10717
    md5: 22ed6d9431a8c1b27c22b7ee748e4a5c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4e62c03d1bb78360713b8a024f8adf3d
    md5: 1b5422b05df284392ae6b87db6b42b75
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_tracer.res
  hashes:
    binhash: 91bc4c4b829789e585f5e18b4b8a8b8d
    md5: 7be57bfc150157b5d6b0e73756351793
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f4c1eb66d4ec9936f36623cdaf8fe6ab
    md5: cf3c3cede7c5c8e704924ef3b768470e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f1c232ee5595f80f59cf92a4826b5eac
    md5: d1f2d8d8b6716db4206ae0769802c3ea
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b7852fbe3cc0e1a3c4ddfbac55f8a226
    md5: bf8ee674210a7dff7b8d553924d9173e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart339/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fc1689caa8ee3912ea1124382e5b0487
    md5: acf07edb9ae649b72fa130382a297e7b
