format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/atmosphere/restart_dump.astart
  hashes:
    binhash: 294a01b35ed30849a3448318cc5dd3cb
    md5: a722434aaa86c51b17df30b4f6d16105
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/atmosphere/um.res.yaml
  hashes:
    binhash: aa46b7ccb9fea0cbd89bde04c43321f9
    md5: 76a0070c1b9e4a522d9c683a4a3d9b5e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/coupler/a2i.nc
  hashes:
    binhash: ef0c7c41b59f2fdbab7f2a06007e2079
    md5: 7caf7fe13ece72d6a552bb9e0d5f3459
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/coupler/i2a.nc
  hashes:
    binhash: afb9b33bfa8be01d27b21f141db1fbe3
    md5: 9464a91d76e1ef959f1dea991c96696d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/coupler/o2i.nc
  hashes:
    binhash: 706dd33c59cea21ddd4d791d6d401195
    md5: 509a64e1c59857aa82872f6b2fdcb98d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ice/cice_in.nml
  hashes:
    binhash: 176fc4fee5e2c2cb07777c86b7eb5093
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ice/ice.restart_file
  hashes:
    binhash: 3eda8e42ac8a83ccce35ffd0b7187427
    md5: d7de8d6dede69bf3b378135295dd587b
work/ice/RESTART/iced.1223-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ice/iced.1223-01-01-00000.nc
  hashes:
    binhash: 74e0952e937a3ee1e5fd506d12e7541c
    md5: f1a1ebf39a79db9a5e9c1578064711e6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ice/mice.nc
  hashes:
    binhash: 80924296a42f0eb88e34d159632e3b47
    md5: 50f1bf6df5e1fcda510fd96537338ef8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_age.res.nc
  hashes:
    binhash: 16a782a96cbaa612ad6ac721174b37bb
    md5: 46d2375e5ee507f4971915283f8aeed0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 36afc38e0de87e5a6602e75e07acc82c
    md5: dea7276c62a5593fc4cdb07310f3da59
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50b5f8502bc01a80472c30df6ae94064
    md5: 181623024ef02e6743eda4d929f4c48b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_density.res.nc
  hashes:
    binhash: 1e7aaac4ca6e70a9041d83307838ad6e
    md5: 891e04d8dc7d667fe06b83eb6f816773
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 53a3e1b9769acc81624a39c89bfd8f85
    md5: 088de09550cfa620bbda5bbdf02e1f2f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f055bd9d71db4f5a0bc08259ff34d26f
    md5: 525d8cbe37f4e123cabc3e4388752f0f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 86060322f6f2cca984f4326e8ee9f583
    md5: 290ea4d011142f0e0960e9c68fa7c771
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e0a3dbd4c41e678a818b89301ea177c0
    md5: 1157bab330d0e0b75359b5c866f5d1d0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c8115b263145d7ab898631b653d12452
    md5: a85c822d2ed9347ef51945216c523937
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e3a9d196007718f530a69f83f0171119
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_solo.res
  hashes:
    binhash: dda8a98753d20441a5c67d89721f0dcd
    md5: 9010d421009080db66aa8adc206fe7ee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c461945385699850a25adaf498fc83f8
    md5: bf1843e17b198d244d134ac59e973391
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_thickness.res.nc
  hashes:
    binhash: dd6fe14d89718929590337d768055efb
    md5: 16d1a0fb70d19cd98627ca35e4e9c6f9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_tracer.res
  hashes:
    binhash: e0a1ef8476b305fa3340d8bc67ab4f6c
    md5: b5354ec5dcd194efcd331d197921fb5f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_velocity.res.nc
  hashes:
    binhash: efa02c21021c121549c28474f39ed009
    md5: 55596ef36784737c57b2d11d25082d69
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1ecfb6416958d6f1f0dcc64c322f7d46
    md5: 732ae6d495370319a51410e90a5dd8e4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a5589236941734391e4dc23aa4180f4e
    md5: f12054840998f771badff05c468650e3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart339/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8284461b5f4ed97a1c05547ed5aa63d7
    md5: 879377a2a2c27521a4c6d1d4ea255e5d
