format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/atmosphere/restart_dump.astart
  hashes:
    binhash: c5109571b9fc506de49b7320fb83562d
    md5: 4afac268c93453445afbf8f078929be5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/atmosphere/um.res.yaml
  hashes:
    binhash: 6ddf91968b9f7fbca4b7487484f1f190
    md5: 9d31aebc0606e9c7a07f4ecd0f2c386e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/coupler/a2i.nc
  hashes:
    binhash: a96767ce4438c81da7129943f3743144
    md5: 8369687c7772d6d414999dd0ecd7e48d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/coupler/i2a.nc
  hashes:
    binhash: 11737e1027276b6fe9380479b041b499
    md5: 77fa99aa0772e064634de701a66c678d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/coupler/o2i.nc
  hashes:
    binhash: de3244c9c1033e8a5c204210c5983e4e
    md5: 4b65d4c2d41cd34016cdecf0481630f9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ice/cice_in.nml
  hashes:
    binhash: 32b82d52a9f8a2ea2c440178aea1fbc5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ice/ice.restart_file
  hashes:
    binhash: 85e71fc72b395794732091eae55a9465
    md5: 154da4c8f9f66156ce814d049668c374
work/ice/RESTART/iced.1735-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ice/iced.1735-01-01-00000.nc
  hashes:
    binhash: 9b3410fc0540f7f1a2054a4f40122f34
    md5: 8db3e1987d22e77d3d3c8d442f4a53e9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ice/mice.nc
  hashes:
    binhash: bf5ae5808708b34f3b80f426c1f71f39
    md5: e31b6517631f610948f625021c1d330e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_age.res.nc
  hashes:
    binhash: 536636fbe4aa70c3fe4a3009ee45c70b
    md5: d278d067b69929568e272506017dd0da
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1549c2679f83782f0feb657c208c6fa6
    md5: 8d7f8f00a99df80c5b19ec61fc1804cd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3035894d6adcefa4301eb0cf865c0bdc
    md5: 7e61a90485c382337cfffb6d00ea6fcd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_density.res.nc
  hashes:
    binhash: d4f87c1a4b4750520909d71ffe8d418e
    md5: aefed66e49e3999f860599acbf326527
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d5707796f1141e50a3643d491bf16856
    md5: b9cdd3eba3f09c5e995061336b00211d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c305c8fd48cb604ff6d53c164159db60
    md5: 456b7c33c2cc7c7e605833c842c6ccb3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_neutral.res.nc
  hashes:
    binhash: db56d5091e8dccbbb30007b7a3f09ee7
    md5: a83c73972739bc8f9b7749c34c8d48d6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dca41c0229075718382b49ad02fc2488
    md5: 53d40ef97b368ddd5721b3fbe1d63337
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 50b4ae586f2ffeabcdb4a948453ecef6
    md5: 912351bcb122dec2c9f3dc30542c3170
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 60e4f94e612738b9990d0792d1bbb81e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_solo.res
  hashes:
    binhash: 2afb1d77672f0a236263256a75ba815f
    md5: 271659cd4d141c0f8b71a0da98759ed6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b178311b1fc487efe7d44c2c549b6508
    md5: e4db9c5699de44bf25782755a656d938
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 723251fbbc7adb96cefca01dd8936a99
    md5: 6df852ee381c6c6af88772e16d5446b7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_tracer.res
  hashes:
    binhash: d3239986a29e7fdca3a423c747d77029
    md5: adf728962f799064be9c7b4fa3e19881
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f9b5261fadf1ef448cf9ff0f2fa59812
    md5: a234cb5a55abdf95a99748620a1499f2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1c0bb6656eaf106c4aca249d80a69417
    md5: d757aa24835f93c74de7fa350ebe1143
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 897b6dfcf0887597a51dcb634b783a8c
    md5: b647f716e0053b9167649751a3d2131c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart290/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2f1d1bc9333749c49072a942a7ea5ea6
    md5: fe4758bde76ca638d71f3ad3f57c4fe4
