format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/atmosphere/restart_dump.astart
  hashes:
    binhash: 1023c9697760486531395ee3fe351bc7
    md5: a2cae8b821bbaaafcf62b428a8c0bc8f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/atmosphere/um.res.yaml
  hashes:
    binhash: d693f641e556ddcd6c1d8f5210c4a8f1
    md5: 34a328aebaaa8945359c6abfc256be7a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/coupler/a2i.nc
  hashes:
    binhash: 14f81495d5e30e9b07ba4b101335317b
    md5: 59e8cacd747a69a71963a4fe09fb70ea
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/coupler/i2a.nc
  hashes:
    binhash: 1511b24545491e34e57277f7238a7859
    md5: 89a9fd89a1fa01191ad56a019ec4e66a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/coupler/o2i.nc
  hashes:
    binhash: 9db4f5cd5641d28647b949e439be0de6
    md5: 0a08bb0b7f997a2cdf471e5dd7994fe4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ice/cice_in.nml
  hashes:
    binhash: d0965343480934553adbeeb8bb819388
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ice/ice.restart_file
  hashes:
    binhash: 44c9850d47e497360b8b9547494619ca
    md5: 30bfd768506c4bb23612af310ea1837b
work/ice/RESTART/iced.1710-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ice/iced.1710-01-01-00000.nc
  hashes:
    binhash: 8a69878c4fa0a5115df84d172c040c7d
    md5: b6e4ba2eb4e5fcde240f4145d418fe75
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ice/mice.nc
  hashes:
    binhash: 8203edc8648b5379ea3b623f3be9e770
    md5: 9454796af73bb2610feabd24d1a30c37
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_age.res.nc
  hashes:
    binhash: d276613b07a6d3e654bda5624112e198
    md5: b6af1db395360e21ab9b1e0d2903ae23
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: faf5045e4d6dabe140c9084e15ede2a6
    md5: bd9bc975d45ec0301683cf5e47532d8e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3610c732fcee1ea0c34bed3717e7fba3
    md5: 332566488102818a740ac27fde72452b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_density.res.nc
  hashes:
    binhash: 0fe1dd1378121fdec76253afe0dce20a
    md5: 4bfcf6add5d9db6fa8f3f81822c160c4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 34d34762f796a6fe4bd6f97d9260f62f
    md5: 6de56545486633482a418edd62c3a221
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 809c282ae60f427230f0a654e30f7dea
    md5: f0e4545aa0c2eaee7b38110dee0e0b7b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b63ad905034c2656474f892bd6bbc818
    md5: b9481e5f056e1a26ded7bc9a523068bf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d6f3026266075ba5f149650af8c0914b
    md5: 9159754ed25b4231e0b84266c64dd3e9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_sbc.res.nc
  hashes:
    binhash: bccac3e68142d47c079b44f8e23a1309
    md5: cfe4b4e1d13abb9743830399d1b47a4f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9a8f3a7fa83cb89da04762341ff3086f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_solo.res
  hashes:
    binhash: f1e64f7d7269b57bd4cac97241c2a5e8
    md5: aeccd1dc5f041c6b5faa54db511b2e5b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dffec06bc070d4a6f2cacf8ed34bfcdd
    md5: 0750e282c11f02ebf6bac5b8a0379a69
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6d0c0e3342379847b3f546f1e6c30a26
    md5: 4092382ddb754f20e36739842cc02cf0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_tracer.res
  hashes:
    binhash: b4c7af4e042e5e426460eabed68714a0
    md5: a0d6d2788a9de9ef79d19dcc2da2f44b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 66153b23b823f64a45d5d2fcccaf933b
    md5: 3d8411b6b1d60149b16486a1aff45cd4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a500ea88762cb2aa5544323538950cb9
    md5: 765964d61552b0ccebb438b70c2fe13e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 12c67e343b5375126886ecb3787f82ec
    md5: 422c7c3df704ca1d9b4d01f956d97d49
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart265/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fe4e827a72aa1c9aa5dc4ce0a333aed8
    md5: c8c946a04a911552f92ba064e11fdcb6
