format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/atmosphere/restart_dump.astart
  hashes:
    binhash: 63d664b940ab4e954673294ae865f8fe
    md5: c8b607755ffbaa0d9fc095854c1865ee
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/atmosphere/um.res.yaml
  hashes:
    binhash: 9dee207a7c54f247baff4b1ebe3a1ba4
    md5: 60df6816b486896d38ab1eb03c948499
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/coupler/a2i.nc
  hashes:
    binhash: 77818236833e81e59cec3755a6abade1
    md5: 0e9dc64792aacc4aa3cddc92dfab3688
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/coupler/i2a.nc
  hashes:
    binhash: d8e150f54f47f91136a042bcf07971ae
    md5: 99b7afe6017e60ec8f08543b8785c2c4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/coupler/o2i.nc
  hashes:
    binhash: 7a97517950f5508c9cd6dbb867737dac
    md5: 10448620cfe82568c2d423acad05e38e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ice/cice_in.nml
  hashes:
    binhash: 5771a4538d8b629827d62fb0d7c572d4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ice/ice.restart_file
  hashes:
    binhash: 1f63e189edbf836b8027817173008b7b
    md5: 39a7ae3289223f79c790780de1fc0024
work/ice/RESTART/iced.1743-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ice/iced.1743-01-01-00000.nc
  hashes:
    binhash: f538f7dd9e35aa81c45f8b1b14cccecf
    md5: cb74deaa7d6003c579ad094e1cb7a88e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ice/mice.nc
  hashes:
    binhash: 4a334fad7bc94fc4908cad9dfcfd571d
    md5: 3f692b06255a928e1b8c8ddaba0dfc6b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_age.res.nc
  hashes:
    binhash: c7338c154e8f26a6658e4a6924a2cea4
    md5: 3443285176a82ac1428b5fba772d02b0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2d84eeb8ceada62e6ea9175555c97aab
    md5: 8a484d927575aeec9dea63caba8c4663
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2b0088522c76450129e4fdee659bd19f
    md5: d91200b2ec4207a6c58477b4f9179040
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_density.res.nc
  hashes:
    binhash: 228043f5a8248ae7f89150ed61db9973
    md5: c399c5c656e2daa7957aae624d607819
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 117ca87c073f97af616c22902029ae80
    md5: 29856ace60f0afc85644d5745626a977
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cad4624112a419970f3b3d10a0ad4748
    md5: ecbcee998ffad7731424c1cb90c5d334
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0975f8adbc66983ae2cd08bb3cd5bf4b
    md5: 98414adc65e8e1bc44c89d8640521714
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2cfb36844587ed079f021862b7e2d019
    md5: d3e3e62ef193f0fb10a765933e23c6af
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ed79840838ffa21598fb4dfa33045b53
    md5: 4957bcab5b1db2948555a53fcf45dc9b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 60ff007d9eebbf8a0c23d853caf841f0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_solo.res
  hashes:
    binhash: 852e937fbddfe0992cceaf765879a5b5
    md5: e1482056d13940a464e47c974c1b5274
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fd7d8c75cc1cef7dc5030dbf2e6aefc4
    md5: 9c1d5ebafb2d704453e3b28267c37d76
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a472e4d4a8cf60863411593efbe9df07
    md5: 40b9217f8644a0898327b3e7b7fe06d5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_tracer.res
  hashes:
    binhash: 42a29fa39307446711eff2bf0ab192f5
    md5: be04938434b92eab2ed7692c57884d52
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8ed1a716fdfd699b4a91839a5c214e0a
    md5: b0e4ffa5c3818840a5eaabd0c444684b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 542f97602101d8b8795b060779c63cdb
    md5: 55d63eb518809551c22701cb739ad9b2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dc73374562bca2c12e50303bee0fbb5a
    md5: 8afcdd59fc8047a97a572d899242ea6e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart298/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dfdc669adaa2c964c504e9cce9e85d5b
    md5: 992cb1d99e6cae6a39f3f220da6b64ce
