format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/atmosphere/restart_dump.astart
  hashes:
    binhash: de9b445aa9267a2837460f0f4e7d2ac0
    md5: e40cda0de32a5502db9cb2ac344b5ff0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/atmosphere/um.res.yaml
  hashes:
    binhash: d91e56ff4bd2f6fa4dda7430c92f02de
    md5: 6a3b1cd1f3641aa380f6fbe562aca85e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/coupler/a2i.nc
  hashes:
    binhash: 67b95032be77b30dabe012c852514f5c
    md5: 2ffe9aa8457656ddd133211e597a4f90
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/coupler/i2a.nc
  hashes:
    binhash: 21ce22c27ccc96cdaa120d997d201792
    md5: ccfc7506cc350753d931ea074f6e27b6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/coupler/o2i.nc
  hashes:
    binhash: c918bc7fc9b43820cb7f910c73613706
    md5: b89f736fe00bc57ad26a1fcb2667b71d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ice/cice_in.nml
  hashes:
    binhash: 51123a7c95832e1cc739a20dc210ce04
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ice/ice.restart_file
  hashes:
    binhash: d7a38978554685772b352ae077a46255
    md5: 24c7ee78cf1c9ea495a0b6fda8dcc213
work/ice/RESTART/iced.1198-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ice/iced.1198-01-01-00000.nc
  hashes:
    binhash: 2549d97733f2d9cee726453ef1664af7
    md5: 7499f37d5d0a35c7e257ecd5d7fdfa0b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ice/mice.nc
  hashes:
    binhash: c3069d9159126b692072ecc11467e2aa
    md5: 5ad3a0cc9da82ae3d50e6bd86f459a64
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_age.res.nc
  hashes:
    binhash: 600ca2a9bc99970dd5e11a8de2569953
    md5: 3027ff88c861f078e611a27b90db3661
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ec89c3f11fcabe7e41dd6cc75ebff6c4
    md5: 67b8a6fc62981e4b6cc36f8c4fdf2ef1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 44c2dfe138e1581a16fb2e19aa247204
    md5: 8ed434274aab7856a7ac540e5b904d57
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_density.res.nc
  hashes:
    binhash: 78f0d26015ccb6ceab5ff3bd2dee1d3f
    md5: 79fdb2d00611ae3d9c393c2291fcb769
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b6ddb52efa94a2c98b73ead50c5ad39f
    md5: ae2993bdd22579a823d5ff9c79871e63
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 16dc932c137a4436fd33d0d23eb8d611
    md5: da6b58973cce17e2150d4c890eb25a30
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d2bad6927f004fa17cbabde7ee5c3ada
    md5: c252c8ed0d5cf4693d9344e08a022e9a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fb286c8aa99fe5883eebc25c201ea566
    md5: 6609ad426beb79551aefdd1d9240259d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a14e135885c1b5cb7bec7e3040bd2b4e
    md5: 12b6d2d50ff7235164cf9bcf575d5d7c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d9ec7372451270d7d742b3e3cd79c9df
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_solo.res
  hashes:
    binhash: cb4ee3cbf9b649b171c9ccd30f616198
    md5: acf5d81035fb6944edb0da4185299767
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7b19bc5cfc7ffb9fcbd964723306a0c5
    md5: 46f3ff81c02926e1871ad0fadcc39c5d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5f3ce8d915e37f042cba1a21b964635c
    md5: 4d5592258ad93693d5629950031763b1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_tracer.res
  hashes:
    binhash: 873b0c8232af4f90d8c9b112e2347e96
    md5: 5dbc7d1ff8db4162677136931afe9c00
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 74f9e72a60c7a2f284b524ae080779bf
    md5: 1499df0a870609eb1f95b4389e37dced
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a67724ca4ab8c8c0ce5bf6dba4b59ce
    md5: f517519169bd1254afae018d9817c1f8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ae2e201ff7a062aa02c5378d0bba83d9
    md5: 15301a84a6c55f9704005be5a033074a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart314/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 78a62cd2566129ed0d7ea92e7e1d3ed1
    md5: 81cfd8df4caa7c21c539b06fde704db3
