format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/atmosphere/restart_dump.astart
  hashes:
    binhash: cea6714e8412c9c7ec8edc177a63412c
    md5: a5ae322c314368402a62df751c4f87ca
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/atmosphere/um.res.yaml
  hashes:
    binhash: e730930173d820bc8769d65c74d2faff
    md5: 31e13f9d006ce19c76c6a80378c19ea6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/coupler/a2i.nc
  hashes:
    binhash: 7af616d564bc5fea495746119161cec2
    md5: 92da68333af343c98720c2d00c6a489b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/coupler/i2a.nc
  hashes:
    binhash: c500995543399bcf53ee1fa902d0bcce
    md5: 3aa87577428211ba85af85e220a3932e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/coupler/o2i.nc
  hashes:
    binhash: b1921a1c77f8cb03d240e0ef80321e02
    md5: ae64ba751e2a2d6d710b67a198339382
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ice/cice_in.nml
  hashes:
    binhash: 9d7e3cb361861f829d5929b0b7b78201
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ice/ice.restart_file
  hashes:
    binhash: 9dce16d881daf346f8eda5e293d1bc2d
    md5: 7d6db16b80debcff20aab0e46afaa2ce
work/ice/RESTART/iced.1219-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ice/iced.1219-01-01-00000.nc
  hashes:
    binhash: 04cf0ad57a6f8786fc690635ea8398aa
    md5: 2283f716cc9828763b54f4dd1eb6c8dd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ice/mice.nc
  hashes:
    binhash: 0d5043f759cf1d1129fe53de17d0b503
    md5: 2516f327cc2e237ae6a4ff0aea7337db
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_age.res.nc
  hashes:
    binhash: 1c5ef4bd91281bca511552cdabc77d32
    md5: 164e9df5d443ef14ca6c132e016ee4a1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 215b86e460b6694bf1d84f318f08ba37
    md5: 2478c90edf6ab63b97eeea1091ba1ea7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: baf2e47d246469e869ff712f42f90b44
    md5: 7967c46bf66b51640957f011f3d12165
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_density.res.nc
  hashes:
    binhash: e6f91c9d0ef9b12a6e97691ac23034e2
    md5: 529eddd44d4e159482121858c71d4da0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c9c5d1f7d0d03e5bd5dfbc7c52c3a22f
    md5: d61a850d62fd10f9f661f5d14cbdec0f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2ae53a4dd55e616c1a959225b8cc2169
    md5: 537416f08963210774377161d6a4653c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b62c80e8df8c0ba82bb3857f325bebb0
    md5: 1832708e7a4e1d408c64d8cd108120b3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8aae2306573b9a30c6e1ede8687c40da
    md5: 0815ea6b169d81f78edadd82ce641296
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a2d5a24aa19a4569c6e9e0482116df08
    md5: 0ad1c9e1ea963b13a46e4692df0d0ae0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f0411570bb765e8c89966536c78984ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_solo.res
  hashes:
    binhash: b23bff5f6c72e33311bb00931274f22f
    md5: 5b12eb4617882e924ddc7dfbcfb4dcea
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0475887611d028e2570691d70ee4ee69
    md5: b78c3c9e6984eab19177dc7303140f4c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0531c4fccc408dabf08f8c7f807a6d6d
    md5: f4c17f6e822f773c1a10bfa2da163a8c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_tracer.res
  hashes:
    binhash: 1f82ea0a38ffbc6347bc0f25b7a2778e
    md5: f163efea7e4a6459cde3112d84ef7fe6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 291587abd0c89567320e2828e9b50de3
    md5: 061e3eba4451c42fdb0591cbeab942ea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 27097ccdc3eed02acc75bc81678bef98
    md5: 21e3da5d0e7a2764d823b04ae54ae3a7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dd4ba45687edaa3b4ceedad597951d99
    md5: 2cdc03ee27c0db039d17fe196ce7be73
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart335/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9a3cce3698ff4eecc19b0489aa5bfe60
    md5: e2950a523f62cfedec30f4e500097660
