format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/atmosphere/restart_dump.astart
  hashes:
    binhash: ad00a239608e845307fdc905958b8e94
    md5: 198facdea2adea74be02c6b2716fe7a7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/atmosphere/um.res.yaml
  hashes:
    binhash: 3e8e27758f84a04ed5d96ba8545a7485
    md5: f55308fa4572261413d3a0b114abf8e4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/coupler/a2i.nc
  hashes:
    binhash: 7b2271fd3e5d296a6ac45ab719532916
    md5: f1bc682f241296668678a8b301b81354
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/coupler/i2a.nc
  hashes:
    binhash: 35f92eb55b441f447e16765aaa6f516c
    md5: d3c8771c05cafdb0601d6b2f4cad98b2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/coupler/o2i.nc
  hashes:
    binhash: 2dea717a33ae90e0c81fb8f09e4e20ba
    md5: afd0acbcf4d4ad97b3b7d15eabf3953c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ice/cice_in.nml
  hashes:
    binhash: 0da2a62efadf1c83f26f252786944bb0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ice/ice.restart_file
  hashes:
    binhash: 1b87d409cd6a2f2aeb72b7ebe955bfe7
    md5: 09c31ba87cc09b647556e1bd138db56d
work/ice/RESTART/iced.0982-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ice/iced.0982-01-01-00000.nc
  hashes:
    binhash: eb020a5fc346e7becf4a853fa3744792
    md5: 91263e107a9fb48599429308ac60a825
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ice/mice.nc
  hashes:
    binhash: 1248c33471781d81e8ad4361e49353a2
    md5: 1da3587b8ffa503a5703634be0c78ae7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_age.res.nc
  hashes:
    binhash: 5886b448223dce15d8001901c758f127
    md5: 74232c15198bd759d1070d67ef5a249b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ba3622148b58293f364de06400fd9430
    md5: c62532b6dbf519dae71dcd7e9c66b070
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8a180a5b95ea5c7331413b0ce8c99d5c
    md5: c18bc4c9f8a33436e58d833b39d4b957
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_density.res.nc
  hashes:
    binhash: 3428851fc5422e9b269566a8cc46ec9c
    md5: ebb78aba61b6856ea98282a7260e871b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b5394a27ae921ecdb223d76fd9973a82
    md5: fe180cf94ddb0cc8791414b95221a033
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 271000e7d9996619f3655f1f06c7ff07
    md5: 3b0ea71c1bffe17204ab24b39ef0db6d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2c32ad313b8278643942784ce7cbc200
    md5: afa16105a47c290edb6ff0d2742211b6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5343fd725907951b76706a9d68afe0a7
    md5: 2757ea402d599d148e93f3f22de8c1ae
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1e92e02c19e290248c26eb9cf7d88510
    md5: 303d7978e68518a9cb0bb73afa76f25b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 63fa195911ee9de49f3bb2a58a1c4a48
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_solo.res
  hashes:
    binhash: edc99d14b23acdeaf781189f8b61ff79
    md5: b6b13a382b5ec6f623cde4d78298948f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d081f9b7f2d96394ba8e82a45570bd0f
    md5: 7eafefe33eaedbf9967868fc7b489a90
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c27c80ecd4b79985c2293bdaf311ea80
    md5: fee1d16e12f43998ae819ddc510943c4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_tracer.res
  hashes:
    binhash: b515e29ffa56675c39bb1f76eea658a4
    md5: 3036d0d08be4cf7076671cb11a4893de
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f6fd83dc42a54268fb6876030fdc8fd9
    md5: fa405d5df655d38466a03b0c8f15637c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 45cdc3a695349f98f50608a263e2bb74
    md5: dbd0d367fecf17633b3d59b147ef5c40
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3d5e6009f6ae8e11271b1177f7ea1999
    md5: 930b2ac183167fc9543ceb794b44a5dd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart428/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 89d733ee66b90c1c22dd1e923098354a
    md5: 107395b63026cfd161fa120b13b1f748
