format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/atmosphere/restart_dump.astart
  hashes:
    binhash: ea3ef08ced6c395092c1418f133a4d85
    md5: f41fa3a16f97f00b6221c2574a5e0b88
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/atmosphere/um.res.yaml
  hashes:
    binhash: 23bd68aa8ecdcd32e2d574bc23459b5e
    md5: 29f8231c32f07e7b3700fe92ade69bc6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/coupler/a2i.nc
  hashes:
    binhash: d93467fc45ad1889d04999a6421dd106
    md5: 14b983a4244fa363e100b6d739fe157f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/coupler/i2a.nc
  hashes:
    binhash: 80fa3abb95606e432b4a430e4a3c0969
    md5: 64991e99bea217faa6e0a08f2bb7ddf6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/coupler/o2i.nc
  hashes:
    binhash: e4b69d8de86dfcca57e22496d6e070e1
    md5: e9809153b5091b36b5b20d0e62758c30
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ice/cice_in.nml
  hashes:
    binhash: 20ef68e93b43dd713d7ef92bd7681d1e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ice/ice.restart_file
  hashes:
    binhash: 493039e772240a54f8518940439fa217
    md5: fa36fb0c15ef0406005aab410ea3ddd0
work/ice/RESTART/iced.1721-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ice/iced.1721-01-01-00000.nc
  hashes:
    binhash: 3704e26604625a92ed9cdb3b526d8e2f
    md5: 4931b4cd577bc4dce7ca6d26f6dda68f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ice/mice.nc
  hashes:
    binhash: 945decc82819c51c835c2162a17b59cc
    md5: 6c86f30d53380ec29f84f8beb04e5feb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_age.res.nc
  hashes:
    binhash: 530cd69e910aced219d5c6fc6e109c2c
    md5: 167d086cea2cd0423ef5c0d3172b0cca
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 218483dcae1014128c11b7a200a731b9
    md5: dc0ebdfde92fbe0e89852c18040b29ff
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5f3db1b3ac7354f2c4cb31e7c51b049d
    md5: c77842d3b330cefc7a3157cdf1cf9a22
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_density.res.nc
  hashes:
    binhash: 21d0ec11d351c2fa307f2c5aa74c5ef2
    md5: 869983e575ff7ef1c86eeae83f54c213
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0b56e5238c1f47802482bbbd60d837e9
    md5: d7918aa44c5144ac63e274c4a369a683
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cc850a73218db316b0166cfad83ae66a
    md5: c14ae5b4b789b2ccae18295d5e48641c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4c43af11e679c78ec7c0e74a5395426a
    md5: 96aec23896017e4ae183e0bcbd75d788
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 94410f87888746e04a0f91991a5a4e77
    md5: 8eda3959dfd91c4706ef2f96ac872a94
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a11b70e9e257eb8ac4f39c1c093b00c3
    md5: 3dca7dab9e3c09dd33fddde7283ef901
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2f4e23b6f50da3533f1884168a3e6620
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_solo.res
  hashes:
    binhash: 7dea12016067c82558a803b75379ebe0
    md5: 9029411b119917a4301f3520a90a2b99
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7d8b91fa97b745bcc3235c85e8896de6
    md5: 150112107721d485b82cd73f0bb6f535
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 00f8df955517eb541571d2f6364353b6
    md5: 04579017c9f31e97b804523bbf9ff682
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_tracer.res
  hashes:
    binhash: 8cede3f4852df98c1d18ea82b14d196b
    md5: ed423d2ae02907ba2bcef915560e303a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 90855286b1cc3728a8e15cb5d41cedb5
    md5: 0a47da29264ad01fa095acf11c157bda
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a1102c5190dc09fccd5b85033605effd
    md5: bdf2cb6070af800f20e9a9195bf2dfc3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 629d3c8280c54570a0bca8a5d73d29c6
    md5: 40a268f024d5c074cfdca36a577d2722
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart276/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f1aed605c720da5fb4c077fde6f0f008
    md5: f9479caaab5ee92c9bae9feea02998a8
