format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/atmosphere/restart_dump.astart
  hashes:
    binhash: 2c4288d8d3a98b0162d38d0b67c149ea
    md5: d71d9d6f0304e4139648ed995479ffc5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/atmosphere/um.res.yaml
  hashes:
    binhash: cbd14454b8042e7f7be9e3213d6ece16
    md5: f5f5b6b1fad39d4ca2fc2e85365c97c2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/coupler/a2i.nc
  hashes:
    binhash: 39cb10fbe1f3f81cff29f5033a142b9a
    md5: d2abc33dc3d184d7e76162aba5b79961
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/coupler/i2a.nc
  hashes:
    binhash: 96779029eda942ccda89192bd402c416
    md5: 92ae028917a778a16852fee25f884623
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/coupler/o2i.nc
  hashes:
    binhash: e434919776d5f0d27649e5d3deab9ad4
    md5: 9eb690e777b3995693ec4e08fa409014
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ice/cice_in.nml
  hashes:
    binhash: 033ff8edaf86b9e3696bd7e74f07c599
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ice/ice.restart_file
  hashes:
    binhash: df53770b85ef20966a11a0df02e3d2f6
    md5: 8124df9bea4a94424bccc89584c13308
work/ice/RESTART/iced.0894-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ice/iced.0894-01-01-00000.nc
  hashes:
    binhash: 17b5350a0954b084d7c21ea154c3e537
    md5: 0fd083ab57c84088d9359e9ae708c33b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ice/mice.nc
  hashes:
    binhash: 8a0fd8dd5570707dff5be07e8c68d8cd
    md5: fe5f703d18af6d15ac5a7ab6f42a6ba1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_age.res.nc
  hashes:
    binhash: 5ccc68971117110908baf1ff19c83adb
    md5: 4a235c671215494d42818bbbb1febe91
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fd71098b3dffe01e5025687b2cec68b3
    md5: 51bf63197ec052814710f3d2390d254e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1ea334226fa3ca45dbe481ff19d3e1e6
    md5: 70eeb4b3207658bad966ef781f8486ce
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_density.res.nc
  hashes:
    binhash: a7aeca764223867ba6e066cf987fc287
    md5: 71642cf81f839529dd7735bc17181804
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 719ffeedaba1127eecad995f2b3bd1c5
    md5: 7bb0d5d9e53d859228a1f6e63b6db13c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d550dbc40c9c4e369b45f4d5652489b0
    md5: 4ffd42ed246aa1bc27d302d2d541bc53
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_neutral.res.nc
  hashes:
    binhash: da760ce1e2db7c60a75479c7a108267d
    md5: 69b0654951ae9381476ef3b67190bcdb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 06fdaf02e5f65b5f59347ecb77296505
    md5: 5b5e09823f79a75d1ad8ec91d052cd42
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d9b4a259a0aac512b98d5a02d67f725b
    md5: 470aa76f049b72a677e3bae22bee0a9a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7b9c82795b52087858bf0b90755209c0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_solo.res
  hashes:
    binhash: fa77481873df8e99c2c4aadb697a6d61
    md5: 6fdc96217a893392f45447dc973bbaa4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 15989a698ff37cc687a81143a4fe394d
    md5: 99549801e7b5e665de22121c0a9c4138
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 06410c77473f1b6e99e696299dd2703c
    md5: e8cdecb4e6f1c6537f926a690e21b3bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_tracer.res
  hashes:
    binhash: 570f1691517383a75c82f5f7dca8fe1a
    md5: be4a303f13439c0525790b5b18a9a22a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f44210d1ebe2c0aeeac9d352be364292
    md5: 8688d3b19f52f66aae0432df7f403acb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 051bac5933087d9a9954c20693b033c5
    md5: 9643a6720fc60de5d956d05c01612599
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 96e867d563061120557979e9b88e57e7
    md5: bf43b638276a8c3d44f8f8ec6587a253
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart340/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a4ce94e8ef46bf1ab553bb22f048a1b9
    md5: 9bdc00741a345c20bb00812e7463418c
