format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/atmosphere/restart_dump.astart
  hashes:
    binhash: 3048aca1ac3d9382117b2dee8104857d
    md5: eadd4e56c7ef909c6f0fdea2d256bc5c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/atmosphere/um.res.yaml
  hashes:
    binhash: fac2f50197c1a1bbd16af63d34e4a8ef
    md5: dc7d8e3c4f145ecbefbba41bc0796952
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/coupler/a2i.nc
  hashes:
    binhash: e3337a9c48708ce0c967f15e081fa9e8
    md5: 81cedaf380f47080596e63eeba2cab56
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/coupler/i2a.nc
  hashes:
    binhash: c93f0eb2afeb33baa3c2fdf9fc0427bc
    md5: 1e1b42a924f7ae73a67f1422174e2866
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/coupler/o2i.nc
  hashes:
    binhash: 1b49a52a05987faa3bda36aa2d68b38c
    md5: 6b802490a9669646483e378d0b1a3201
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ice/cice_in.nml
  hashes:
    binhash: 3e65fe7dbb2ef92ef595cef0331bb53e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ice/ice.restart_file
  hashes:
    binhash: 4c7085794b79ccdc1b04051b2eda9568
    md5: 629334758b0ceaf05b13510f3d04ae15
work/ice/RESTART/iced.1266-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ice/iced.1266-01-01-00000.nc
  hashes:
    binhash: 85cd2178ea81e3ac6d994627d84789be
    md5: 85911a369243ad94d0bfcb27c16352c3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ice/mice.nc
  hashes:
    binhash: c7d2965cc92a61a0b1064255f367a41d
    md5: e06f41541d4e9d77b4f64129e0967767
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_age.res.nc
  hashes:
    binhash: 566a08fea46deee536c7773beabaa59e
    md5: 0c239082774358f8e3463e30fc14a24e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d816bfc04153271becf170c8ee814080
    md5: b1e1df307d5e2ef300d1b3dac9072b28
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8cc0a53334e04715cbcd0872e92f2b06
    md5: fd99e86bd7a5104c94a6096a8d7b337f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_density.res.nc
  hashes:
    binhash: 3b2cd38880d620a09c92b8271ef8bb70
    md5: b790f9f11c53836dc7d5df6c3d3bce79
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9b7dbc5fd98a5912916ff56fbb9684c7
    md5: 5ae19d93cfc4da45bd186b8e5da48204
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d113a8a80d85f6de911f314dd43bc40a
    md5: 512a65993f909e0fb7e2637d6e15c258
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 63b16b0fc6aaa29445b7418c33e72250
    md5: 5cd35669001483c8313f03a161c265eb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 04454f8ebcf39f65d538d68d82a91dc1
    md5: 2a4d808482ae10c99fcc2c9a656dc5db
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 14165b42f7fd94fd986f3691bc12f18a
    md5: 15ca119251fd01c28b1bc23b3b8fe2a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 997deec62f3c499a812dec479453c426
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_solo.res
  hashes:
    binhash: 4cbf369f6026c29d0099011bdace9d16
    md5: db3af150a8cd2d61818db2c9926b7af2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a4d1a17f2238f14b2b7a21b95d363ffb
    md5: 09655fc8c9775f345dfe42b0aa060f07
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ad892105268cc4acad82f963c5936c37
    md5: 008d61d9066aed37bcba9f694ea966d7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_tracer.res
  hashes:
    binhash: c7526d84bd15423ee567d84a1eebf476
    md5: fdc6b7ffee624b943a5c73b96138abfc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7bc3df70c43ff8029ef6ace946ad6e11
    md5: 3fb01e43f3db432fd4c06cc3f4bc3233
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 01807149521c4792cb23b2c825b96a8f
    md5: 56a6fcfe91d594b94f2e5a41a2989711
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8eea5ecadf90fea282d140e292eb01a0
    md5: 5b54a50a88050316b7650be788bfd9e2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart382/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: df9eed5b5debfa459cf85b76ad795fa5
    md5: de741df248ce4592c6a1fc1e5e251126
