format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/atmosphere/restart_dump.astart
  hashes:
    binhash: 46afe999b7377c73c1869e3f37258411
    md5: 82ba9f08c53bfb5b1edce42646a9e1b4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/atmosphere/um.res.yaml
  hashes:
    binhash: ef540de7d48b72181c62462452b39499
    md5: 0462ba8a4e24c124d1fe0a4f758c78f0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/coupler/a2i.nc
  hashes:
    binhash: 3e75d49f16f9374a6246f7b5fabf7bca
    md5: c0d19eabe92ad5e5dc1d17b552cb11cf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/coupler/i2a.nc
  hashes:
    binhash: 601614d3c96d5c4d42955a9ba266adaf
    md5: e0a81f315ee20848ca2c1b81ba48a382
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/coupler/o2i.nc
  hashes:
    binhash: ccde8ce5353c826d315dba279f73887a
    md5: ce5768717780dcad68972f0b28b220ef
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ice/cice_in.nml
  hashes:
    binhash: fd0cb2f3df3f6a1c324d0fbb8a433f00
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ice/ice.restart_file
  hashes:
    binhash: 83b4d21e54a4c8464aa20366f20a5dd9
    md5: 9e97d444e98134cf5bf9f46909607492
work/ice/RESTART/iced.0963-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ice/iced.0963-01-01-00000.nc
  hashes:
    binhash: 0632006cd3be6880ba2354d5645d0232
    md5: 077d35ef90050cb506c8347f6dde35db
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ice/mice.nc
  hashes:
    binhash: 1c90be7f78db98681655c8efe74fe2d3
    md5: dbf6df8f30529f9f6c4ce69aa8c36b36
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_age.res.nc
  hashes:
    binhash: 235f22d834c341cb625ccff74cd495a2
    md5: a90214c32bf92ee0f8b4b95a725a7eeb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5eb7f3d793c80b1b048b3834e09e4233
    md5: 2e4c9d0e7f1a4f07e22743633cf36a3b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4fd404b6d3fd2ea6b5b2ec9ab335e1d0
    md5: 8bdc6a35b5ceef30ad7fc3a4789e7f05
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_density.res.nc
  hashes:
    binhash: 38a584538fb8284cfb02fd0ebf196987
    md5: dfc69c9c9c36f303aa7324b6bf44b3d9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2e9c709748fcf8ac2dff3f441df908fa
    md5: b26b15534976ae8035801725f2b8c974
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 277c5e044e664c2bcb65f33bfa29cc39
    md5: fe2e55a01e290e51fd3bc3f2e26fd689
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6c66535aa11ba9f997e9f87a5acb1012
    md5: 46778f5fa844b00ced0441e24522f7e9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f469b46bba98e3e63d3917b572eab25d
    md5: 2e1664c4600d8690fd4833fa046687cd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 64ad293f25f77b7b06424d7956e55e14
    md5: 4b211e704db0a5edb21a343e227728fb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d602f77bb8566cd071b4111586a038a0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_solo.res
  hashes:
    binhash: 01677d9fad27f5183cbe785792cf65a9
    md5: 80aabacff9002f5438e8b418418be932
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9cdb0635ab731de5cacfb82146b777aa
    md5: 13d2562589245b359c4b690ec40b9d9d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 10d66efb48bbcc56ef688b348f60947e
    md5: bc50604d8d2a6379a1e5df09846d5fc6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_tracer.res
  hashes:
    binhash: ff4524b20ab08bb829c3b056f19b1473
    md5: f12640106b25f42993ef83b2e2a90322
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d22424a80e6cb51e2abad6d68630b3d1
    md5: d0ea8e0d0e4df06e028e0b6118a9776b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: da74c3aacc36b3196ed5a6fe7ad607f1
    md5: 75a5d42a3a1fe58c734019b8a39f56a6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1615440b5b113c140ca28aecd475ccf2
    md5: d60f383c6d47b816c3dce8d5606011da
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart409/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 75a5d0250c1c0a0b9ec762c754504b26
    md5: 3b75dbf895ce4dd00bcd9d0e68eaff2a
