format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/atmosphere/restart_dump.astart
  hashes:
    binhash: 77f404094a74f6ca15ceec78eb7ca99b
    md5: ca35da316e8c117e3aa0dfdf62fc22b2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/atmosphere/um.res.yaml
  hashes:
    binhash: dfdc5e01a4d8f687e0cc87e08ecc41b5
    md5: 495fc887e5d8a6cc591fcec68498fe24
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/coupler/a2i.nc
  hashes:
    binhash: 742fce938bd9376ef0aeb09ce439331c
    md5: f65ca20893403632a6c31917fd1ebdf6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/coupler/i2a.nc
  hashes:
    binhash: 1527559b12832795e9bce2404c28ef29
    md5: ee6233b8a40cbecbb1d6700d7528502e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/coupler/o2i.nc
  hashes:
    binhash: 6ba7d068fa29deeff54e64ab9e4b71fd
    md5: 917718a7d770671fdf6a7a98167b76fc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ice/cice_in.nml
  hashes:
    binhash: f77c7ce5df49a4442b01196288162aa2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ice/ice.restart_file
  hashes:
    binhash: b3b379be019c8a6454e60a2c8f544613
    md5: ffe6082c1a3401bff20ed019386634a3
work/ice/RESTART/iced.0967-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ice/iced.0967-01-01-00000.nc
  hashes:
    binhash: ef78086515d5edf70c9501b750f86f3d
    md5: 1aced3463d4468962283aa69512dfbc7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ice/mice.nc
  hashes:
    binhash: 79e36520793d3bf5b986960016d88d0a
    md5: 27daac696f0045b94ba00903296b0efa
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_age.res.nc
  hashes:
    binhash: 9aebdfc77c477ccbe8817b4fe6c1462c
    md5: 1a677bb822c976667cc98ccab31031f7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fb05f095f2744f79f3e5ca32512d5195
    md5: 621176cb3788c9db8d0a624d86d93e05
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6d94e6c52a893e633eb3ff49c5bca0f8
    md5: c800ebeae0f7d0994952a55c75b2587f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_density.res.nc
  hashes:
    binhash: 73175b87bff9761f55d242a42b5fdb19
    md5: d1cb91ed513baa96375fb3d94e143758
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8ccee6d8c6fc1f8f60822ff94d5b2963
    md5: 8f158429f4f367f4dd3a8dabe33db5be
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0ccbf7711737d09b1bcaff6a87fe9941
    md5: baf44b9b5d131f83c29d78ff12a76f48
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 15f591a40206d511734c36f7188b5a9d
    md5: 8fe4d9e066ec78808ad3c53e97e91f57
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5a7eeb2e77f595c8dd9bf7cd94779cf5
    md5: 5a78afa890e5c8d2dddaf10dd891ef29
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 110acc22fd7aa95c5a36d1e879930444
    md5: 5cffe612bc6d50304071f2aa5c288cab
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b26a8763c8415c8b2c3fa1d25a4f3a5e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_solo.res
  hashes:
    binhash: 2e9df3f49412f9b1c7829089d807914c
    md5: 7212232ca73fbe90070ace5bfaf35eaa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9ccf160865abb1b694713dfc3eddf24e
    md5: 985b868bc51841c2293f6239d5a63549
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eeb9c8b299525357d1601563b6d96872
    md5: 66dbd01bfe963724a7d3add303414bf8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_tracer.res
  hashes:
    binhash: c46735dde9de70424cfca88eac111288
    md5: 8577332d74b8a7c6a16a97332b105118
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e5857e9c71a3a9157ad0102268df1268
    md5: 37bd680f3ad550127b89c9934c796495
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4ff90e42758c46d3711c468a24c49ed9
    md5: 52e5ac0b48d0372227f9c33ed08b9d60
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 077443a5bcc9297789a077736ccbc91c
    md5: 1a095330efe0399d89ff749bc067abd9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart413/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: db19de4bae2dce9b18f8ec702381f7aa
    md5: 069f16b2a27e2b5f9282ab588dcf569b
