format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/atmosphere/restart_dump.astart
  hashes:
    binhash: a4fb0a4da188275aef6157c711e234b0
    md5: 6b688577d592f08c6f64d91837b30ca8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/atmosphere/um.res.yaml
  hashes:
    binhash: fdeb8d65fd6b72e84b6f1c38313ccda3
    md5: 7cd612f1148e69fb2ae1e737ea7ff9c1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/coupler/a2i.nc
  hashes:
    binhash: 860056383fb6b77f20262dd3159c82cd
    md5: c00e6422d76367af8ae7b3a7d733338c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/coupler/i2a.nc
  hashes:
    binhash: 2aa378176de7a5829303d1ebb845b117
    md5: feb88612d0ed67ae34a75bfeadac72a1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/coupler/o2i.nc
  hashes:
    binhash: b1eda619712385559e5044033b1e1270
    md5: 4b18696dbf945d029ab8b0e303f35e3a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ice/cice_in.nml
  hashes:
    binhash: 2c9e2372fb7c2d371871a0ac5d8119a2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ice/ice.restart_file
  hashes:
    binhash: 702da6efb00eb281a769766b9952c958
    md5: 78d6b56963093532a37177f74b19b44d
work/ice/RESTART/iced.0984-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ice/iced.0984-01-01-00000.nc
  hashes:
    binhash: f46d9c225a51800e1e25d7611b94059b
    md5: e725144cec9645bfa54de87025f0c18c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ice/mice.nc
  hashes:
    binhash: 919a52012ebc7baf297a791b3289b864
    md5: 0c1551fc4f3a32e10def60ddbd05f9f5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_age.res.nc
  hashes:
    binhash: 7739c5808a36fadbfca15ecdd0bae5c5
    md5: 9f0db2d5c2c7af560ebf66607db267dc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c3b884a1152be52c809c7a5a835c8ee
    md5: d5ed193f080a9997fa957ce30f4db294
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6b9ec8055db289d29ae5e5f460373f5d
    md5: 6f1b8ca3aa578e62fa0daaeac04e4f17
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_density.res.nc
  hashes:
    binhash: 0201e513020fab5c34380caf14f268c9
    md5: 542b286623e5245bc8d9b71c99c0be1e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5a8761fd4525662509883f139af08af8
    md5: 9710e419926870decf2f4788cdf836be
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7f61ae42936365d0e61cc13c53445a36
    md5: 2975ff5df92527cbafbc19a8e3ef8ab2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ab40f6a5460b3df99c5fff2c6e5b6748
    md5: 2e149ad604106128582bdfc0832d648d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b84aef01f72bfca2dddef0de3e022a4f
    md5: cb67d1e8fe3131cd77d5afbe70a44483
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c9aef76bd9778beda8581c26301d552e
    md5: 937a3d33a6625b964790aad5ead33c54
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 798a32f297e9f95eb9cc6b3d725766b7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_solo.res
  hashes:
    binhash: 466bf65e4a87de7c2c20c9940ebf6c00
    md5: 839321ea0b728c4e490213a18b179899
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 083b72da7d8b6885d6a5871a8d6b7850
    md5: c7efe28e6562d62d226bc7226a510c70
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0466400ec96daaf893548284d03fa23b
    md5: 16dbf3a011aef19560a89e0ec2088551
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_tracer.res
  hashes:
    binhash: b22e5248ee88f3369d8c2e27cb821d4c
    md5: 7aa46b352c66ec05ab061378d0cb3675
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 618b5a94b4587a2629bdb149c7b5a7f6
    md5: 61bb7a054ea4c4b3ca12eaf7aceaf492
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c2db436b4134e1c16f493709618e7024
    md5: 5a10a9aeff5494b567202ced29516f11
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4babd347165979395ccaa8b6d8fbbe33
    md5: 3790bd9ac3f46b77b98cd2d8ad9942f7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart430/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a94165b234a70abf2fa92d64355c6a49
    md5: 45c50976804f4b50560a911d72b8e83b
