format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/atmosphere/restart_dump.astart
  hashes:
    binhash: 9a95884bf68f949121ab96a524618112
    md5: 0b9a563e2504467d96fc732d546bd198
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/atmosphere/um.res.yaml
  hashes:
    binhash: 1fa32d89399789fe22d44249458c28ea
    md5: c4b04ff615d92dffce895177c58a1235
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/coupler/a2i.nc
  hashes:
    binhash: aabf89d4e76356952ae342924691ab0b
    md5: 3b11ac68723b2cd3a4d3f837666bf113
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/coupler/i2a.nc
  hashes:
    binhash: 6e2b4191af0ed895c2c7036197a2f6d1
    md5: 37bb1296450b7f7847708d62ef27a24d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/coupler/o2i.nc
  hashes:
    binhash: 3fc8140454faa1d9d08be2c103ea91b9
    md5: 222f98569b55372d2fb428a2c3ce66ba
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ice/cice_in.nml
  hashes:
    binhash: e2222744d60226c67016a0d7e61a6717
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ice/ice.restart_file
  hashes:
    binhash: 3c7d1c541a95c37ec003ab270d615cc2
    md5: 842e8dc964df2e96e0b07c636f652a89
work/ice/RESTART/iced.1739-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ice/iced.1739-01-01-00000.nc
  hashes:
    binhash: 032a523b8f461027fd2ba4abb8148527
    md5: 7e945ecfecb144575edc67259717e5a0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ice/mice.nc
  hashes:
    binhash: f4706bcbf6d48a21ed44a643abc7b6e3
    md5: bb78f02a14669a5c648793e31460f0d6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_age.res.nc
  hashes:
    binhash: 86a529f9ee0351b39b263cc59f0d9984
    md5: ec0a28584fce43cd142c83cfdb8c2290
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f915bc8970924f59c2afaa7cb45af787
    md5: a5e531aab5f9d44d3f94c8d7394a65b4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 837e40dc9c4b2ebf4c3bbf2900c39c27
    md5: 868741fa2bd7d5bf40520315c6647a33
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_density.res.nc
  hashes:
    binhash: bcce6c38cd0762a1e9fe70e5deacd4a4
    md5: d278768c8f949fcf64585431e51766e6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7bf2a60d521e20ad43631dec2d267396
    md5: 1127b2a515b1335f6623b0e4a31f2e6b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e41760b7a4bfbf228d8c4011bbe566d6
    md5: 1cdfa0a0653e229256e962145cb4a663
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4867dedb30ca530538d6b9142531d935
    md5: 111106a30675e605a27e0b09f2d4c46b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4dad027cdd68519d643ec2ffe170306e
    md5: 4bcefa82c37e88d65510c84fea6b8e15
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4887654ed181fb0b1c6c31e7ce0eda73
    md5: 567a4f71bdebad3e0f5a2c238c673d62
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6ea90df91cc31d6c091b5b0e0189f85f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_solo.res
  hashes:
    binhash: 597493248c9a8c9ddb510867ae0cb326
    md5: 23a5608cde0d424f858b2fe0d898d259
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e9ea66651b0bc2e0fe329bde4dc189de
    md5: e6f1f1f5f63d3260bf2237212c814f3e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2ee4754e01bd15124241f64e514fd07c
    md5: 8c6a2d9f80f1872abb01820cc956eb4f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_tracer.res
  hashes:
    binhash: abbc1f94b5cad9b4d6cd495dfb580172
    md5: 2ff94032867465639aa7ab27eea7be80
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ecc6a055b9bb1bd29918ce7178c58502
    md5: b42831177d8f616489d453e53ab2b2b9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4a09906f69c31d74d5297d65b937f88f
    md5: e217977281f31dfea89a29edb540e591
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1c47583c741592e2450fad0eccd3f894
    md5: ccdc11b0697bc4a9ec3125d23af6859c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart294/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9e534d12a1de5eb3200cdb5ebb598cf4
    md5: 64f38f2a6421b48614379d66b4443ed1
