format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/atmosphere/restart_dump.astart
  hashes:
    binhash: d504a6eb1bad0d74fcd8f5a34ae70351
    md5: ee48b5f384058dbb242b1699fdaebb94
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/atmosphere/um.res.yaml
  hashes:
    binhash: 97358de54d4b5a69a63733e494a40c9e
    md5: d6f5ff6853e1958f9860a2912b4a6864
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/coupler/a2i.nc
  hashes:
    binhash: 73e82a824ad3e7917a8d5faeb571777a
    md5: 46372d1f7888bea8366ca710f9809023
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/coupler/i2a.nc
  hashes:
    binhash: f509a51a1c451b6c390e0d3d6567888a
    md5: 07651f4c8770a131d91e157e0021855e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/coupler/o2i.nc
  hashes:
    binhash: d23f15bfba9a7106f32f9816e23fcff3
    md5: e4647ea350d2e1fa33f489231a59000c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ice/cice_in.nml
  hashes:
    binhash: 492c2a1fce6b079d94b28a00dbf75f98
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ice/ice.restart_file
  hashes:
    binhash: cf06ccd572bfdb06f0b9116dd82953c6
    md5: e208080c1daba3436417a57abc89337a
work/ice/RESTART/iced.1782-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ice/iced.1782-01-01-00000.nc
  hashes:
    binhash: dbb22425591b18019e15b4814f325cc8
    md5: ac0c09a875729433078316962c41959c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ice/mice.nc
  hashes:
    binhash: 276be8d7df1228672ea650ac5ee01f7b
    md5: 5dbf2f83cfa92c62bf1ab90787a7601f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_age.res.nc
  hashes:
    binhash: 3dfc4134761e0e00ac44f341243cc7c8
    md5: dd96e83088eecdf34c2d338b4dae79c8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f4eb535f95fd256cc1f93cc276ab0dc
    md5: 05a81e155da98e3d23b70513514c2e1d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b33688acabb88866e8f1d2bc9c1f864a
    md5: 4ffd4254355054d1d945ce15c1a3912b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_density.res.nc
  hashes:
    binhash: 840fcbce5103b9f790e2be7d9447d9fc
    md5: d8b6b35ca5755af771c0b1be5fa263a9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 403f6899a939a3ceec1b352d70498716
    md5: c41df4cfe00829068f7ff17e9c8be775
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 51b629de836ce68803bfc734d6ac9103
    md5: bbffa667ca8eede3716bb45cf0453b17
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6bcfbde79678ba07a5f7e063377b9056
    md5: 367fea87047e1f8e95f9442830e2e5bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7903e12c4a81a4b6f09d42523efad1b5
    md5: ef3c8c27a8ce28b9e4ff1dd92fd1a7a0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 629cdab311db231ad74f8dc200c6467e
    md5: 787c40552e9361ee90b3d7b0458e6bb8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7cf5eb81d97268ae4ece82a93b4121a2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_solo.res
  hashes:
    binhash: 90a18aa60207fee953b034ce6f171448
    md5: 2bca17407da18b313703d085d425cfac
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3fdfe88f35dce81784935acbc1ef64fc
    md5: b181867dd9a9e1af8c5ba2df5f526980
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5ad3ae53fabd77b493c92c7a1fc08502
    md5: 428d018b8aba8ad0a1c566ea33a7e806
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_tracer.res
  hashes:
    binhash: 3dc34d1b42b7874fff3b2f7574e7cb4b
    md5: a8dfc19e6692848a51e42b1eb83e4fa5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8d24320018cba376165323ae9772e3fb
    md5: 9cee6166927d6e1c0ca7a4bf386c5df2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6cb5e1660918cbb06cd8fddb37566447
    md5: 6cca76322a6a4a4836c66ad417ff073c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1899a93507de915aa432e2694049ee48
    md5: c61b048f5ee23c55b848959ef2844617
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart337/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 65b29edffc126c3a507dfd03c6b4a612
    md5: 5976bad9d8cb117844133eb3407760fa
