format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/atmosphere/restart_dump.astart
  hashes:
    binhash: 4e8d346542b4a64b0d17dc6140eb720f
    md5: d220fa647a3bf39f3224a10a3a594a49
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/atmosphere/um.res.yaml
  hashes:
    binhash: 6f5ed778d774aa24577d8c8d9cfd328d
    md5: bc5c1a0bc6c8faa557be04bb5112522f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/coupler/a2i.nc
  hashes:
    binhash: ac7da95c11a835bb6d83913b5f951f83
    md5: 7194a515494b1058f9e1610133d677bf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/coupler/i2a.nc
  hashes:
    binhash: 695d81291a97fe8f1a7bb7f8193400be
    md5: 4314767d983706f2f19296163949b9cd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/coupler/o2i.nc
  hashes:
    binhash: 8c80a612a127400a37ae11b2c6d4a3eb
    md5: 2e8741e3d9f8a96c2feefd0e88da3bed
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ice/cice_in.nml
  hashes:
    binhash: 23e8bacd19f2721de53bb3bcfb278a26
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ice/ice.restart_file
  hashes:
    binhash: 528450801cffef7c33753dc9ba00133f
    md5: 6a01469c30d3d3fc5155f3fdc9451fb6
work/ice/RESTART/iced.1785-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ice/iced.1785-01-01-00000.nc
  hashes:
    binhash: 73ee4ab3dba05e2a76e41475a289f76e
    md5: 979d125a54cee11b3fe6a69bc139ebf7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ice/mice.nc
  hashes:
    binhash: 8de936243315578bd72fa8dc6bb60800
    md5: 34a42b0c5f049e773942daafe752e821
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_age.res.nc
  hashes:
    binhash: 26ed48709ed421f36ea01e4610ccdee8
    md5: 28f34ea050896996a5b9a01763904bd9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e557a80f857acadc9f2d78b11c8bf122
    md5: 9f0029ac902f9aa0f1f76ddf8bdd4fbe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8a4ded20b1e37003c3905c84021853f3
    md5: 1553b973126755ef06bbdbebbc03c2fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_density.res.nc
  hashes:
    binhash: b63ea8dcc067dacaee3f813b0a0d3a77
    md5: c625b8f1123434fcc39d9f7a902f7a70
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c9f92cb9ab5a1cce522466f60645c7ca
    md5: 900ef8ce7009b2a64cf142dfac07cf5a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 190abe211e81e0fc0e47e2e7735c19e7
    md5: de829ad5f1acfa5dee48967675611c28
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4336e823a4dd47b9ded6644a2bd5cf86
    md5: c3459db80ef1c4960b430fa1f72ed808
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5db012d8d9d87e46b57695815ac2a482
    md5: e0ec6573d14cbce82b293e42421de710
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e81eed36461182ad53448fd3a465d502
    md5: 1594a50e3f158f27a9f09e12602bb382
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fb91604a54016063f3f4d11d8741ab08
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_solo.res
  hashes:
    binhash: 0d1d2d12c277cb3da9adc370a86bdf42
    md5: 1797e8a8607af6f80f46ccbfc86a4354
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 709d09ea10006251b43f2b8e5d725eb5
    md5: f21ad23892d5aaa01a5452ff55f9d419
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ca7f6b4745e0f705c5f0efa5001a6af1
    md5: f31dc0e6d9eeebe93bd6000a2e88288d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_tracer.res
  hashes:
    binhash: 43b800ba426a23435ba8d3fac949db6b
    md5: cd81f9ec8c68541049bf53c750eb1d6c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5d5b7e8116eb5a33c1073f43567c995e
    md5: 746e5bf210fa5b709c994ceb97397dc5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4c186725e8b9bc5f6f449d51f933fa78
    md5: 96ce02be5cf61052279c2e84acad257a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fb418176a22b010c8c62e750d54fdc4e
    md5: 71051a33e959830d2c58c173335b70d7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart340/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7650d639535e418d9d305f94f8952a79
    md5: 8e1ca8c24eca8a19da7712dc294fcef2
