format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/atmosphere/restart_dump.astart
  hashes:
    binhash: 45e9a8130c97efbad10adae4a2fe420a
    md5: 3c7d39248ea8c02f98c4cedd65912262
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/atmosphere/um.res.yaml
  hashes:
    binhash: c0dc493630bbcbd93852018706da1c84
    md5: 97117db2a164f99be412d5f03cb63bf1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/coupler/a2i.nc
  hashes:
    binhash: 6ec103bafcea2b899821886f1aae3cff
    md5: 3d8e5e09c4526aa78b925670cac3dde9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/coupler/i2a.nc
  hashes:
    binhash: 07062fc901a261f0d9bc1a11b2b0d9b5
    md5: e27456d8645e48f07f41234908380936
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/coupler/o2i.nc
  hashes:
    binhash: dfae9d0ebffd16774765eaa46fda516c
    md5: 6e1224d5e2ebfafb8a2556980c782956
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ice/cice_in.nml
  hashes:
    binhash: a0ecb3c1729150af7338ddbe96c58136
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ice/ice.restart_file
  hashes:
    binhash: c97acf6e83d48bc9248bfa4eb4019401
    md5: b9a2c1a74f1b948eb9c3f3cf907734cd
work/ice/RESTART/iced.0880-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ice/iced.0880-01-01-00000.nc
  hashes:
    binhash: 440aa6151d7561ae34b6836f19984ae2
    md5: 7d3202894de8e4ae19432544af327640
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ice/mice.nc
  hashes:
    binhash: 97e8f628928673de4d47fbcc407a6f0e
    md5: f5d16d0d3316f17f5a7187fe94321be6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_age.res.nc
  hashes:
    binhash: 5743c640a6fa311366dfe85ff2940f7b
    md5: 338cdd1b6e3f15423c0f8ae3e520bf9e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 89ce321b4d92a221ca5b7d54e4deb378
    md5: d4d2626d08dd2bcdd5b5a8ab7c182002
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1e8c0a6686aafa95c72ca59ad4ba2b6c
    md5: e33fa0c874dfd541b056e5d598e1bd34
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_density.res.nc
  hashes:
    binhash: 76c70270ae8860c65154a3684b8f8a06
    md5: 4eea3f33bc82e1152c9f095c2faf873d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 780b6375c2dbf8ecf219de6de5a00cc6
    md5: b70b875ba6ef84ff5cb33c87425e0583
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1104146e692b7cf1b51c17d7b379d3b
    md5: f4cfcbb24e38210ab2bfe9b02604f70a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8c6041c3b5d97912e6aab1842428c798
    md5: 8b4d546682c6ae712f166ef44eca40fe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d060107cdf3204850302f5017ae9c8f9
    md5: 6772f8922229a1216e96e439e5e29064
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 14e130c31f4432d13a04297bb5491bb2
    md5: dcd2685e48d437aa2d677b1e1cecf85d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8f186ab0b8cc53dff1c19e7a9eabc065
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_solo.res
  hashes:
    binhash: dad78b2fb7a8c3cc60d87a08be4e14f9
    md5: 8bc8500a2bec3ca46c178247040a1ef6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7e0b170648185360cf228512366dc47d
    md5: cfa1d624d9367ea301aa4525e13e9b76
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b901fcf3b7c1666692f95404214edace
    md5: e22cc8b643f953585a41df44e6250635
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_tracer.res
  hashes:
    binhash: 42b48956eadd705ecccfe304c39a804e
    md5: 94f86519c27e9da1ef238556402a992b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_velocity.res.nc
  hashes:
    binhash: de3b241a2090feb70bbafd675878d6d6
    md5: ccda98708c6ad0e7680ff2dd812b3613
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 511d38d8eff4a37b725f57bf19e0eb38
    md5: d7961c507df87fa3a5305ede7fcfd520
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 780acd83f223d942d2a271f3ed17494d
    md5: 1e41d7dbba2cb637c079181843a8acb1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart326/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 67d9c161d5a9debf7a546f67e4bc2615
    md5: 136a04271987a7d8475e9f9b2f7cee4c
