format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/atmosphere/restart_dump.astart
  hashes:
    binhash: f138abcaa8a96f9f5bd0dc7d2afd2193
    md5: acdc237301de1383f1aeb12ce961bdbe
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/atmosphere/um.res.yaml
  hashes:
    binhash: a9adeac0c752891b6060ed0770029427
    md5: 796035eeec1788c55f81b815280646d5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/coupler/a2i.nc
  hashes:
    binhash: 88d65148f01b05af6a0bf16479881bde
    md5: 28ee6d67d19fe0aa175531905411c11a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/coupler/i2a.nc
  hashes:
    binhash: 7820cd40d26ef0742836aed9bd69201d
    md5: 36f9c10ecdcdb8ea7de4f3042dd9f396
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/coupler/o2i.nc
  hashes:
    binhash: c869fb31ae626a976e6bc8bb89b73d06
    md5: 2f9ece67377b525fc944f84d5a2c5924
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ice/cice_in.nml
  hashes:
    binhash: ee75088ecc772fca3108276e9f5d3aee
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ice/ice.restart_file
  hashes:
    binhash: 8aaf87c6f71b8507053fe6d046b1d612
    md5: 753dfeb007e6fe1605007c918cd13daa
work/ice/RESTART/iced.0862-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ice/iced.0862-01-01-00000.nc
  hashes:
    binhash: 2472b6c298e86f59668dad0bfb5dc83c
    md5: f2fe95679b2410db4adafdcd84789e54
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ice/mice.nc
  hashes:
    binhash: 7c9b2c1d345170bfdc75894bf2f04f16
    md5: bac5520a38430ce3e1b02c0b9364b212
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_age.res.nc
  hashes:
    binhash: dfbf499542cfff27ff5a7de1d1911908
    md5: 013ad90af803a2564574c68afb9b687b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ef90fc12eb33ee1f9444ef594c6222b2
    md5: f0017109f8f503e29830f848819e03d9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f67180f1f5204f18b96bb1d83f46da9b
    md5: 21c577f9a9ae4c0cdf3197c19551703c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_density.res.nc
  hashes:
    binhash: 0aa878cc6f0117f3898c841158487aff
    md5: c4c57f14cd469f7f558fea9ed918bb21
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 63a3536409c24a6cb1c82baa262e85f7
    md5: c5a661f8dcd0addbb263e0110cab00e7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1ad4e484b73538c676b3d24c5047df9f
    md5: ae092c91913de4e11d223f34ef7eab67
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 839ee50782a2fdd125a8a919c8b1a9de
    md5: 29a5c269c74084dd334f0fa634bed90c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 79f9f588c71922e28c761a1fee4f6e3e
    md5: ae28e67d41dd4f7d3aa9ab03735d35a2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ba7f0c633225325245661e93257c28c6
    md5: 8fb20e2b53b5637f719f66ca8e4b55c9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 638ad1accbc7cf32db7f2eb0ec3d0f1a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_solo.res
  hashes:
    binhash: 6ed311f903de119c63c9768358b6cc61
    md5: 408f77b63474cafed43091033327c0c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 16e23f6e0916bc6b14a56ced18968385
    md5: 276f2888291c15c1bd459a7509273a8d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a73980aa4ea00c93469089c8944ee4ad
    md5: d1d806380936ba8662ca10c994c700d2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_tracer.res
  hashes:
    binhash: 5af3572a2e050b59814730782e47a275
    md5: 946872223ce971f52784d02287c1b1ae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e8576ab72762e3996c41a010c580d802
    md5: 2a371191b7aef68c1095a9db151e68fb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: de023984ec8c3305afcf8b3044f9840d
    md5: 0d106e036a83853b8c74a900b0a856eb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f7a72c57b20487b85ad58f0cee925400
    md5: 7fa2155da04709c7afd71898bc6422e1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart308/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d2c9144bd5844a5e7b5ddcdcd7df1a03
    md5: 0724fffdb9194304dba3ee8a4fdbf747
