format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/atmosphere/restart_dump.astart
  hashes:
    binhash: 8c13158143c798bfe853044e5a2d4454
    md5: 923c19c18fa32debeb964b72084c3e32
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/atmosphere/um.res.yaml
  hashes:
    binhash: 1df17a096aecc89226c634049ff014cd
    md5: 308b436d4cb23eb5cedaf8d4059e1545
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/coupler/a2i.nc
  hashes:
    binhash: 4c5bb7668bd3c94de7c88f20920a7637
    md5: 40992b26632a6b4477f80fbae722ecd4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/coupler/i2a.nc
  hashes:
    binhash: a8ffc2421ec1e29cf23de6e55971fb03
    md5: 4233006d257512d959135d5688adb035
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/coupler/o2i.nc
  hashes:
    binhash: 09a1527712031343fa22c724cc99721c
    md5: f7dced16d2d81cfc81b07c8dd62307e7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ice/cice_in.nml
  hashes:
    binhash: b03a08ef3ec0812791a001f13a2d7954
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ice/ice.restart_file
  hashes:
    binhash: fb29cf0817688c3ff78006659e31df79
    md5: c107f0b03499502546f59c1d28f6e15b
work/ice/RESTART/iced.0935-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ice/iced.0935-01-01-00000.nc
  hashes:
    binhash: 6d5daaa725db30a968198cc0d2a57ab6
    md5: 3add0e566d505d07858405a4f128448c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ice/mice.nc
  hashes:
    binhash: 5364711caebae70d13bb4ad6c2738273
    md5: 75e40291b33e4a1ab35b6eef154baee2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_age.res.nc
  hashes:
    binhash: 315c6c185e83a46557d0ca9faa710eec
    md5: 1f931320c9b97b01b5db9e50f2363c77
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f7dca50c785b38cb45cd4380e0af8ae9
    md5: c5d4ae53285fa2e4d22d019c39a4ec78
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e5b69da4bdf177707ca7d2f7f8951c84
    md5: 4d3bb16ea0aaba9817f7e2d439fe37e5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_density.res.nc
  hashes:
    binhash: ec68a365ae499007e6b0c5f9dde13b54
    md5: 495cbc96b93399e3f17c95aa14e7fd2d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c01700f909a33f4ec9a91966198dab78
    md5: 300b92afbec58dc9fb7ae8e8321290c6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ad6b7595afe3c29b928aacc2b8a1ac26
    md5: 7d975ef75938a938138a8c32dd45bd4e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b59ffba1e424bc2efcaa02c1640af954
    md5: 0834cfeb555c6ca757a7eb8c9b3f0c08
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dafab60ae022fb73a952ba8db7113aa2
    md5: 31137253e6001d7dbbb5170bf36d1acf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d8ee34af6b07c44dfa523b0b18b19ad0
    md5: 9cdac827fa800b8575b59588c9543ca9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a91bd446b61c709ccef6f744c7de0fe9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_solo.res
  hashes:
    binhash: 5a1e7ce9b8007d64e65a484587847acc
    md5: 2f391b47246ec488d46472d50dd188bb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c8ea6d20587a858837daa9d58fc6fb0a
    md5: 3a43be347da196757b2d0aad872e807a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 78afbbabec5e31afc2660da4e302df10
    md5: 3128f7bdade4453445fffefb06e31db9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_tracer.res
  hashes:
    binhash: 94fc8b6be3f22362725490c94c1c822f
    md5: f30fb17a7410b924289bc0a9db28af62
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 74428009b420c39051d829d873565df6
    md5: a82b8fba2112f812030cc6671ecc247b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cfb3b5124b907f769d89dbe65d7f552c
    md5: 674fa4c10b5e20c26f741a1c86d1758d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e7f6c11434e764d0b25f8033e8814776
    md5: 43ff075c36c5f881fda01164c684920f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart381/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2729e3ff3d70542fce836230252f7967
    md5: c7ea98608c21959d95d70fe145336e53
