format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/atmosphere/restart_dump.astart
  hashes:
    binhash: 34337699dad44b77f5b73cadde5cee27
    md5: 6aade3cddcce69822229dcb38704a100
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/atmosphere/um.res.yaml
  hashes:
    binhash: d23dad76fc0b3b7c0d5436bc4d521f9d
    md5: 03708762f7b0c28fd583fc2fa4af453d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/coupler/a2i.nc
  hashes:
    binhash: 4de9c62c722c6ae9b1c73ff9a78a2a42
    md5: 4ddf4a5ef3b2fc1f458473106e95a225
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/coupler/i2a.nc
  hashes:
    binhash: 01094a5e77bec7236151a4cb1eb7e4c6
    md5: cd3898cc9d041e6024204bb311b87d16
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/coupler/o2i.nc
  hashes:
    binhash: de0456799a0dac4ab53c3ff2e99761db
    md5: 43569d2577b4bc741a7d9f02978f4f83
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ice/cice_in.nml
  hashes:
    binhash: 87c953fe5f90f02d2f389da8f0f7abf3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ice/ice.restart_file
  hashes:
    binhash: 2a20565ab464be2fba400182975c10be
    md5: ba2b6bf3ca0efbea25b0f115a5400030
work/ice/RESTART/iced.0983-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ice/iced.0983-01-01-00000.nc
  hashes:
    binhash: 554f0d5e7a3e407cb929e844850eb21f
    md5: 0a429ec0a6ca459c5e3018e8b98cbad9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ice/mice.nc
  hashes:
    binhash: ed383565cbc9fcab17948c4dd1dffc6b
    md5: b7d6d3649e7243e73c4b771c4cc0037a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_age.res.nc
  hashes:
    binhash: b71b547c0eaa68ac4d781d268fc8462e
    md5: 48c322dc66558aee8f1e5071772e2dc1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7766b09c16b9e173b2e126805ca4fa34
    md5: e3da444099a283221207e7605da77db6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3c85e714a5e2fd56cebd7e0d682ee381
    md5: 46f5d2368532832959463a2f7ee2bd09
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_density.res.nc
  hashes:
    binhash: 2fd09907d40b9ef4d10b8d821e7b2e6b
    md5: 452b3f1d4ea6cca919ebb0283ef0358b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3db35613d7b4405f46ba8b3814a31c51
    md5: ecc65617be20ba79649947e02286db70
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b740ccca830f2db197e930ad924ae5b8
    md5: ac4edbc007bcd6814d5b080a6701d713
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 621ec41e406dcd1d9ee85b83a80db88b
    md5: 207ff08fabcbc016dc49d9d9098fc53a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2ffe9f20f9b61b0ef9e6691315b14d49
    md5: 4c7b436f6a8850bc2cba4696c6e4f788
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 651c716cfe311d4e929d506b69ffc15b
    md5: 3f299747bd5659789037bacf4f5f3a9d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2cc7c3b4b69e3bd1b9d0c3384fd993f5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_solo.res
  hashes:
    binhash: 73e85a3f0c804cf0447cd8ff868b3120
    md5: 4ba979edd12dad4e5fca777fcfbcc0d9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 43e8edc86ef2e45548dd37923dade4d7
    md5: 17e7b16c2c0364fda995e53f8095f173
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d5b0476d203b44e8c43850762ebe1ce3
    md5: f2ab97459173ecb84f3cbe6c910c862a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_tracer.res
  hashes:
    binhash: b313b07e86215b3cd6e158c07b0d6eb1
    md5: ec2892d074246db8281c126c5dce7719
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b58fdeb43aaa17ea480a5dc22badd657
    md5: b6f7d78e45aa12e596af8b69d1a04423
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 82742e7fd9173e426ed15f87f086263d
    md5: e899a5bd25a7a411efeaf24eab21cec7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8c42515fcbf166f3c060c16122b93f3e
    md5: 3ffba98d68326ca3c5e81bb5913ec5a3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart429/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 36500aafe73a0386e4f28ac9e1d7ba10
    md5: 419ab95f6aa2dbb99adc27215a0505ba
