format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/atmosphere/restart_dump.astart
  hashes:
    binhash: 742dd719eaaa6d4755374edf1356dc62
    md5: 6a23239cc787c9bd728edeb70284fb0f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/atmosphere/um.res.yaml
  hashes:
    binhash: da55430c1a44cf3679ffaee14b0040f2
    md5: eb9bd6dc530acdf9390028025958c6de
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/coupler/a2i.nc
  hashes:
    binhash: 2e74417fff8ef973375ab6bc83ab5d7f
    md5: 44a1d5ad3a3ea1b7d4c9153f074548fb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/coupler/i2a.nc
  hashes:
    binhash: 90ac0a547a7037cf2c0a256988d2aacd
    md5: 5a644b7e312fa3b12c9dae03168b9830
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/coupler/o2i.nc
  hashes:
    binhash: 3df73bc2672579a34762c60f5e701a6c
    md5: 79ac8312265ec93997a770f67dfef73b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ice/cice_in.nml
  hashes:
    binhash: 3ff72735338792d2a6767928d065febc
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ice/ice.restart_file
  hashes:
    binhash: 410b6277424242b4bbdfbd6b8b37058c
    md5: ffcbb7d54ee957e761dc8a2e63ed603f
work/ice/RESTART/iced.1797-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ice/iced.1797-01-01-00000.nc
  hashes:
    binhash: 7fd00865c8c7ec988a56cf4a7aa0ade7
    md5: cf2caf7486c287b6c0c2da5fe460c8ea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ice/mice.nc
  hashes:
    binhash: 4cd913e196db53d000ba4c7aa069b5cb
    md5: e03c5a5cda684ab14aa0c3a048b3ffde
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_age.res.nc
  hashes:
    binhash: 3c5b344338ff645146684f032641da24
    md5: decfb88084b00e12a5fca91b3cb5de0e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c8bbf1a6997b23ed94955858d08e84c8
    md5: c8d6321a88660a506771bc89add18435
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 231160613cd0c1c3b9eb0fbc37426787
    md5: 30a0a9f62a0d5b0b9a3be44452a3c569
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_density.res.nc
  hashes:
    binhash: a257d1fb698e196290ef9441d1ca4556
    md5: b403d5c420665497ee92f5e6b7a2288f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 76774bbed86c026d798d2f1220d1f546
    md5: 975320ebd9bb3033a63382a751475075
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 69954eeacc60346f182b35a9ece47029
    md5: 28049740fe589676561cb1995fd84c49
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fedae2d33788440b34166c0a5f73c6ff
    md5: 83df14708bedeb418bf18bfd9e8e200d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 34911722f4bd58d427a6a3e607938d32
    md5: 87dfc1b2073bea56d46d2a93f2a40f06
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d9f0c2fa8828f864419d9a5b3aa85513
    md5: d2fea96aa0c7d5dcd62b1158a19aa228
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 73e945646c26abed569c0ceabb3d1f94
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_solo.res
  hashes:
    binhash: 3ebf07f9726b9435b379e95360481b7a
    md5: b098e5b65258554d9eae3d2a23988ef3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e33081c9a195e86817774303552830fa
    md5: a0f83de2216aef01386d948c1fb556fd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4201e6bbb74ec9fe7026b087c4eaf06d
    md5: c7a042df5a3e36fae9ee31995bab383b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_tracer.res
  hashes:
    binhash: 5ad4cec8b99f40415c8795b396246770
    md5: 95e3df91dacf8fe119490f849fb97622
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bc5f615ab8ef7a05924abb5ad0c2bd56
    md5: 6d9e971157a98656d24b8509cbfc10aa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9bf4051d65c2aceff5b6763514ca03d6
    md5: b8a20b76272efb7b08bb540727b6f9ac
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6817e61d6cf02b3808cae9ea0f91fb8f
    md5: 138694c6576180fad949bb737a5df51f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart352/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ca3602711d2ac99d3b5d5f76a4623eed
    md5: 68c73340f4c523cc6cdf40224c4e702f
