format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/atmosphere/restart_dump.astart
  hashes:
    binhash: 8e46f22fb50d9b2b4cc15c80b8c702d8
    md5: f16624075cba90532b044dcfb0de8851
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/atmosphere/um.res.yaml
  hashes:
    binhash: b215168d2096d9adc5a5e3f273e2f66c
    md5: 2534c33bd5711553fccb3937fdc3ad7f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/coupler/a2i.nc
  hashes:
    binhash: 2bb8916ab9725591349ece7d5da5901c
    md5: 50ab44b317c8a4d4abc484bfb7afd28f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/coupler/i2a.nc
  hashes:
    binhash: 77d7849be31fb2d885437bc337f7ac41
    md5: 2a1db9e3ea26c2c8c753f3ba6c4189b5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/coupler/o2i.nc
  hashes:
    binhash: 6102fec17dd074f914a4d401b0df1ed1
    md5: 2174753044812b1a76c2e010bffb82e2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ice/cice_in.nml
  hashes:
    binhash: 3e63e90b9e4c62bf1b643f7ce8f5596d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ice/ice.restart_file
  hashes:
    binhash: f0d9fa0e205b7f7d3aa561254ca973d3
    md5: 2fa26ed6074d44e433eb34505ce56192
work/ice/RESTART/iced.1174-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ice/iced.1174-01-01-00000.nc
  hashes:
    binhash: e8443857eba73e8f65da12f51d93bd75
    md5: 2044933595372c42cf8e6f2ca6515084
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ice/mice.nc
  hashes:
    binhash: d5bfd3d9a879a3b30474bc96652137fc
    md5: 0887a32ae15d6f0cf26bddcfec3b6a98
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_age.res.nc
  hashes:
    binhash: e857ca3960cb44333ec8483cf9d42b9f
    md5: dacf11b97f7d369b86ebbba25d142304
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e4541456a300b6741357caa2273224a8
    md5: fb187ff7ed73154883528d646868b43f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0111e3614bace2b16c1f4271cc6b2a79
    md5: e7818c167973794f42e7e8abebb70da0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_density.res.nc
  hashes:
    binhash: 5bb941a71239a9762840542d5b8b42e4
    md5: bae6cd3d219806acabc857fd8725154f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bede595fff44a7006bd43dfe29741e1a
    md5: 248538cf6cc0cb7d03733162941c30c2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b7e326aaa6a865cbbb20c5ef4b5e0fbc
    md5: 596348728a95e97d13fe4fdc0b0fccaf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fc3fec2919ade6e61bd3927766595c21
    md5: 7d49c9a41e20db51f246615e3d7a0598
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7741add645861959b07327eb0fba20f5
    md5: d55f488904f1c7ae7353622dc78894ea
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3de7cb00ba99ce0ad3c4f66a55a28432
    md5: c2497eaa36f571752adb2b417b384097
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fd374b4d1cb717d2e7829fcf3ac176c7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_solo.res
  hashes:
    binhash: a588ddaa498b5da60da9250b606211a4
    md5: fcd09b2071900fb057627698152c1df5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 85039bd1287e48f35be863e0ad7d15ae
    md5: db35f87a47644c0ffcebef4077dd292c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1314833d302fa1f4c9418fb34200c413
    md5: 4a6b04b86539de75dc173ca1ebccc908
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_tracer.res
  hashes:
    binhash: b567ebfb9850816169f9fc6fb493cdca
    md5: 8ab3f4320aa09ea94e79ad44c4ae2676
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c4f51c59c4abe3bbec736287bfea26e8
    md5: 5fcb09bba39a64d82d26830d9944d639
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9858da746c39372eb364cb2185564374
    md5: cc48d53910ba2b1e6d00eeaa119063e3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 02dc59785623fc1cd48fa070baf07ee0
    md5: 7b81f13b2c1c58cbe8e07ffb145730c3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart290/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 96f9f3d4b8a19f306bee0bf3bea0043c
    md5: 823341041fe9ad9e649d4ccb413cce70
