format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/atmosphere/restart_dump.astart
  hashes:
    binhash: 40683fd2f373cd0aa519da337c2f62ff
    md5: f77539ec4d097cd6c3e15dcff845786e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/atmosphere/um.res.yaml
  hashes:
    binhash: e84df3e8b9226356eb23c6dbf205fe8c
    md5: 257d9ff1e60fc4efac3e4ab3f05a768a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/coupler/a2i.nc
  hashes:
    binhash: 545eeb99cd8d70b944c816b443f8b780
    md5: 074e22fece39e9733ef04333e4b4f1f9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/coupler/i2a.nc
  hashes:
    binhash: 5135422f6304fdd7c364ec60da22da48
    md5: 5505e5072799e25cc15454aee4c77a82
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/coupler/o2i.nc
  hashes:
    binhash: d617ea7f55868e10d5563dc8148df1c7
    md5: d8f2bfefaef82caf899ef104de3e9377
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ice/cice_in.nml
  hashes:
    binhash: d6699af1a8608c44f8fb4c4cc99dde3a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ice/ice.restart_file
  hashes:
    binhash: 2088435b89a76a5dc4afd22f9dad497d
    md5: b493e91fc33d32dcbaf5d57e12b97f93
work/ice/RESTART/iced.0883-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ice/iced.0883-01-01-00000.nc
  hashes:
    binhash: 789a7633ad3e49fe1dbf95c8f8ec96e3
    md5: 2e48915ec328a8cf0def45740d6f7d48
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ice/mice.nc
  hashes:
    binhash: d16653c2dea2d53bd3bf00e32452c396
    md5: 7382b20ef3d99991741e9d7703d11891
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_age.res.nc
  hashes:
    binhash: d003431060a80cf1a375900c0d755825
    md5: 92bdd633f20969d8f4d631d2e72d5f7d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c1741d628c5bdd7dbdf0c4251bd358a5
    md5: 9ccfea094034459f85aa7a872a3ca252
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3b506616ef631135c47e848333515442
    md5: d39544df954b2b2b74caae59587ae3a2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_density.res.nc
  hashes:
    binhash: 994fd5b4e107b72105c55d3657856890
    md5: bc780bdb77044e061720fa3b4e57f168
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 281dfbe73036e79ae8b199e1b841969f
    md5: 4037cf3fd09dbce7ac3c5692352684ec
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7dd8123e42b3b0988e8839e6cd9fd081
    md5: 995234ed1a365dbc4e586301ed844396
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b9a6d8977c62dd77aa03cc59d0cb1d90
    md5: c8d44a17681ed607837c87c1e947074e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8915c9372a21118ba5481454ae4fe4ae
    md5: b6a9bf7e1997832e5314419231f9be6f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7c8b18e015a3d86aadabf43020201990
    md5: da9ca730f518504b4d9aa1fb50fb5552
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ec90a7be4a9637718eb13ce818f7127f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_solo.res
  hashes:
    binhash: 09bff3dc14ae4ad009464660f3484d68
    md5: e92908dd86f4cbb9f69a8b89c24abcd8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8b45757d388b6713e502ed0c90b9a904
    md5: 03468e5349d678bccb1777adf7a27ddd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9be5aaa0224a0c1e5017b6608eb927cf
    md5: 34e15b7d8426a16aebc6ec991330eacf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_tracer.res
  hashes:
    binhash: 29ce27bad11e16c04e586c5dc8153aeb
    md5: 2f0752678248733ac4bb891ed1ecaeff
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1bd8d3abd782123816f1c6d111b90c70
    md5: c9133df68539b6b5fe693c2f01832baa
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d646a5564fcbbe17c9ca8cee0a3ee1ac
    md5: a7563ddc4ee436714d56eed7563208f9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: dda924f54f31c7e035d371d5a842641d
    md5: 0aa056a154b41a19c2119c28ee93f0e4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart329/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 28e6b097d396f3abd4062d0786f54577
    md5: 3a2b70db08542dbc4952afb0853c050e
