format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/atmosphere/restart_dump.astart
  hashes:
    binhash: ad1769185021d339faef9e13ae4d782f
    md5: 4d7bd056166ebd5424aa1135f382150b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/atmosphere/um.res.yaml
  hashes:
    binhash: fadb93b7065b55946a8c86eca9792c1f
    md5: 47dab76e888294a6c2a1c883ac28f1cb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/coupler/a2i.nc
  hashes:
    binhash: 42615ba96cf451d2e5705f05b52d70c6
    md5: d1283640908ab398d0c5447362e491fa
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/coupler/i2a.nc
  hashes:
    binhash: 030cd6b4ec9ef1a5dc1f49915ee5be13
    md5: b36e4b54e087ed00a544e70808ebe7af
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/coupler/o2i.nc
  hashes:
    binhash: b43d09827245815b7ec3c1f5177e070d
    md5: 5cad7fac2dc60d5d5473cb98144b35db
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ice/cice_in.nml
  hashes:
    binhash: 566c9c0fe5893b86c510baa9c71dbb2b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ice/ice.restart_file
  hashes:
    binhash: 2326b696a8afe1eb0c0de2dd0a70c053
    md5: 6f4742b7a9b75d04189d8f5c3a2e441a
work/ice/RESTART/iced.1162-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ice/iced.1162-01-01-00000.nc
  hashes:
    binhash: 12534922e644e68afdf7cf9205f9b4e2
    md5: f84c5a26d1b70f45553170b7d88baf18
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ice/mice.nc
  hashes:
    binhash: 0429f3c80e2d5b7b0b3fff918aee47cd
    md5: 82641a19c719680a988bf431184bcac2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_age.res.nc
  hashes:
    binhash: 993f11546702dca2c96ada73ac345d7f
    md5: d3fbc45fbb3eee83b1b8a93666c60ed0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 47782ce51fdc56bfbd099ecf0369c010
    md5: 83e3598f5c4e67587ae6e83bab11d139
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1329d9dcc23ce6e78653fa0dced6c8fd
    md5: 11d80a06070036b10b3f8b575928015f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_density.res.nc
  hashes:
    binhash: cfa5de87413e7c92b6a60692341acfc0
    md5: c26ca7fa2a0deea848fef21ed6934776
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9db9a566f648b016fff38d4962b7d68f
    md5: a2f3fb80015e94928599a9da972bc639
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b048b6e24d0cafb28eee3ee24e5a1a4f
    md5: cfe1e819ffaf67b409158f48171217f1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6ef9b85e7a7808878f3ef083574ff54e
    md5: 7a77f92a8651063b1b4120045499780b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b43e06e3672a08f03176366acc240b8d
    md5: d3f22185767ad701e6cc8943a2cc667b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b6400d1de1a32bd6b31854171ddc7bb4
    md5: ed12d69e745b20aa2f1463b78a4181e5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e93e0c867579ccedaef04f0518f726ed
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_solo.res
  hashes:
    binhash: fe1656e36d3c6388dab83241ef0b35e3
    md5: 183c172d8aefff6fb577d9b4891a7a08
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 04bbb866bf312a0f4883885cf0b60c67
    md5: 0624afb3de7a73832e870696176c79c4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_thickness.res.nc
  hashes:
    binhash: da38f3b500844022d6a36d69c149ceea
    md5: 9b54adfb99f692febcb9b17c250d1f8c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_tracer.res
  hashes:
    binhash: 99a1662214853c44e87b85ce7ba2f9f4
    md5: 32d8e76d6d525f52c2fa793ec1ceabbb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 89fb2707dfc09fdd5f81d2c2148dbb26
    md5: 92ac020aa3538611c84d418a806b4e99
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 21fe4669391388c8024d07534b771690
    md5: 6cb93e1490a117a41bb22a6bdbb245a2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9140f6c7ea2250e35fa4c9e10604810c
    md5: 304df9acf68d31538ca5ecb0926e9ebf
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart278/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3d47be74cf22c96a75717e5eb2f3c313
    md5: e3b9b25466c4ea6c0408d66867cbecae
