format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/atmosphere/restart_dump.astart
  hashes:
    binhash: 47d060c1b15d7d5100bfbcccdbc01f9f
    md5: 3b74ea478ab34f87f62452867352ec45
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/atmosphere/um.res.yaml
  hashes:
    binhash: 85194c9cce63115ec32e6b834112f265
    md5: 724f2fef7a6ae1a36e85a43611a166cd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/coupler/a2i.nc
  hashes:
    binhash: 3e78910a1f3e43a51c7dc120fb5b8b86
    md5: fe9e852f6d057c9c2b6701abb4aa03aa
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/coupler/i2a.nc
  hashes:
    binhash: b60cc2c9c6ec6d976f57967453f0448e
    md5: ebf9f36e495711d74017daa0ebebc2c3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/coupler/o2i.nc
  hashes:
    binhash: fd041c18a6dc632621b240b1f60cab9e
    md5: 2d6ee54866ac2941e71abb46897dc7cb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ice/cice_in.nml
  hashes:
    binhash: 5049b8db89ed839d475cc2e279140d2c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ice/ice.restart_file
  hashes:
    binhash: 6a69043c67c22ef85170292638b0bcc3
    md5: 25b7812ac6dbeb4e44934af4e596e178
work/ice/RESTART/iced.0928-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ice/iced.0928-01-01-00000.nc
  hashes:
    binhash: 4dc2631bf03ae4df1b20ba332121f21c
    md5: d7c9d61951461418b840a9a5d970b7c9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ice/mice.nc
  hashes:
    binhash: 521c9dc66c672c1a68ab44dfe3038543
    md5: da4a2eff80523ec61086edd9cdbf4d53
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_age.res.nc
  hashes:
    binhash: b75d936e426265cb0b35f9b26f30b192
    md5: 028953e24e4f128fa7a0e1fcc358d1bc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 98bb7f5b5217aa9b8c712e9faecfc780
    md5: 8e4a42d4bef25f2f179259262e599d29
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 343f56b9b1cdcbe20015462c2367b234
    md5: 860dc979fde6efbe28b994747c3ead0f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_density.res.nc
  hashes:
    binhash: 5076ddc6ea57c7ab100e7d5df5af3c17
    md5: a6bb7b4431e3b38ae9872844031e4666
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 976b7c298c5af56602dcd7a60f169ed6
    md5: 4c136797c355bd3fe7f860032ec1f5da
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0cbdd11d9afb689b2a92381dd3eac650
    md5: fddcda01086c330f190ca5ead5b7534d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c8cb782d2b67636a22bbf2a7d6ba979a
    md5: 3c392c38955d0fc6fbbb015d56a03f11
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 08beee32fb217f627c643dc6c5efc3ab
    md5: 7a6eee3aab34db29e6596f900a557122
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 37ca9b7ef5378862a3bd34e7ab4593fb
    md5: bd787b4d6f0be0074b941d87fe29f934
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8592c71c90f390ea82ff02ebedd7a810
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_solo.res
  hashes:
    binhash: 811839ad44f04305701d4b4415a0c0f8
    md5: 48ffe6f75696046b55c2738b3be3d29b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8341395cb9ee53c7ae572e39a32d62cc
    md5: 05511d2aac745ca852a34a0a9c2113e1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_thickness.res.nc
  hashes:
    binhash: de2c3a4ab882e19a7116245b4f9e556c
    md5: badaba7c47e050eead979326cb6731d3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_tracer.res
  hashes:
    binhash: 82811c083c7f28aece5c8c573c6dc8ae
    md5: 44804cbedf3f90fe4f4bf26ca0aa91a6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ae4920050260b75753ff2571d3ea5020
    md5: fb559abc61676361af63787e06fe17fc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bd45b487b92ca8928badec890ee5fb56
    md5: b7df36fc3f1ee5c6c847c63b56cfac7d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0464004b9c1f93364b0c57cdb08bd3a6
    md5: 664db0f0bf036b2459fdd1f8ee11c36a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart374/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a1def934514b4e518d68c48b44485502
    md5: 08620d1594e7ab5e30c2cf1aedc35afb
