format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/atmosphere/restart_dump.astart
  hashes:
    binhash: a3b62461b1703afefe3338b2fbd875a7
    md5: c0c22b5f9ff1bf58fa22a8ae38a481a3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/atmosphere/um.res.yaml
  hashes:
    binhash: 1a486a820223b3184387b5bebd5f181c
    md5: 17701cb9e48d3d9623f24ea11584853e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/coupler/a2i.nc
  hashes:
    binhash: dfae482ce8c17038eb061f5f02576b3c
    md5: cd06c671c5067e9919dea3b9ef437bc6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/coupler/i2a.nc
  hashes:
    binhash: 3a46d1afe95df34851ee1d60cf04cf12
    md5: f48fe6ca5140ee009aa4e383f1eaf740
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/coupler/o2i.nc
  hashes:
    binhash: 61a3165ac8b5ad61de4992afadf01644
    md5: e638e6218f4da96b71814552159d4c97
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ice/cice_in.nml
  hashes:
    binhash: dd69eea05ed50643bf723aef7f1aefe3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ice/ice.restart_file
  hashes:
    binhash: 80ee81dfb7f68e399ff6b8708fbe16d8
    md5: 721b0fa5904a6ae74027373bf07fc53a
work/ice/RESTART/iced.1765-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ice/iced.1765-01-01-00000.nc
  hashes:
    binhash: 8dd9268e5d5b1d14fa7c63517491b20e
    md5: f30947ca06c3ee460c9d8b9c23494be6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ice/mice.nc
  hashes:
    binhash: c03b71c2dd70c4a408416e7e33875e85
    md5: 1222bf8e01ca2e566eceb55607d55f77
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_age.res.nc
  hashes:
    binhash: 54427bdd78bf743b7575c4d552da0ebe
    md5: 1fcff5d5188b0051e9894984d32f7876
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3d8f6ce363708a9d80e0080135b99050
    md5: c897fb01ab2ce4da25379887ed0a17de
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ff65483caa677af102d29e171362eb80
    md5: f15908586b443efc2d0a13466c8c64ad
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_density.res.nc
  hashes:
    binhash: ad0500e004886b7dcd307e1ac169e8c6
    md5: d98f2f82011395072061979343685420
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 15d08b61c3a0b99e232663414407b7c1
    md5: 5a8a7b14612d63213a06f5bb51baf7f3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 673f54bb5946de69fbaa691c7bf142bb
    md5: 37d5fd57ef441ea9c0833e87bfcf0d46
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7bf6786de1a60fcc0e4196c9ee831c77
    md5: d537c806e894bfc3edf8bd093a0ef2b1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4454974198d7c5b1f86cbd45447a0f1a
    md5: c1d478efd86b6a3b407cb351ea8ffb43
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9527d72aa5e2b729ff2cb16aa353e60
    md5: 0c7d11af58ebb93ee3fcebde05264940
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b3401f8983da21b1f96dfba46b5624c8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_solo.res
  hashes:
    binhash: 0807989836ed330a63f0dace6d18514f
    md5: 4c98bb7bff648e2773d1f05c47407ae6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d83e0f22c4ce297ed94455e249763b2
    md5: 4e0054b061e75133cb9188d494b1dffc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d4970042675c470369e5acc201de048d
    md5: 56b87a94652910570599f83603b2b7dd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_tracer.res
  hashes:
    binhash: 8f1e749c23662fdebabea463ecf54763
    md5: 9003b41a085bbe1f0c35dcef33687885
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4ec3ef7b071e50f4541641bd7fb2f3d7
    md5: 4a4afa20ad2e8e33a02aac194d5da970
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6a9baac5d5baca001ce61f853bb1847d
    md5: 297e532bd5754b7e64ca98f51a9891ca
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 22dc300e5cf541773e812fd1427604cc
    md5: 743d8e9d29fa49dee5e5d51784cd44ae
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart320/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2abd052e9bd43b2bf55b944a4561d996
    md5: 5bfbef7fe70eef7db2edf06afd160adc
