format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/atmosphere/restart_dump.astart
  hashes:
    binhash: c0cb703f2efde1f41def2e5301c301ec
    md5: d712b913a9ca980d7bdf4cf91801110e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/atmosphere/um.res.yaml
  hashes:
    binhash: f33f4d0738dd669d666de0524da1fdd6
    md5: aa72e08416e897450b04e20adfd175fa
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/coupler/a2i.nc
  hashes:
    binhash: bd2615607daa9e16582e2b85c35cd512
    md5: 9242cec9db2632ff9e12086d8ee92e94
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/coupler/i2a.nc
  hashes:
    binhash: 1ab7c4099b7b89eaac47366f79eadc2b
    md5: d231b4256356929c44a20c4d27514cbf
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/coupler/o2i.nc
  hashes:
    binhash: 3b4b9d7f3936c751ce77b4522e67b1b1
    md5: 9e1357619f5ad80ebc2cf5b9797a2bf4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ice/cice_in.nml
  hashes:
    binhash: d25a25b95ee33ef0feefc04f1d1a7355
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ice/ice.restart_file
  hashes:
    binhash: bc93e68347407e2b3e20640e694d1e37
    md5: 99c11fedc7e76548ed99023ba766c7bf
work/ice/RESTART/iced.1708-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ice/iced.1708-01-01-00000.nc
  hashes:
    binhash: 50a68e7ce84227f146475cc7f4cd5eff
    md5: 1b6bbf82b1a7716b80b6ca2f40881cc9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ice/mice.nc
  hashes:
    binhash: e4e667a79780a08b149ea82a1dbc48cb
    md5: cc80113c1f1d43e1de5b6d68b342c244
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_age.res.nc
  hashes:
    binhash: 42f17ad6de2e9512e772b0b0f1c470da
    md5: d049c2237f009c004d680c61f4c8b7de
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b63a57386da825b3efb6e299054da382
    md5: bbc845b028e606d6aa443ea1a00e8ee7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7cd6bcc9f0facda99f1bc4388e941361
    md5: 355b6c71728e406773009ba51e199cb5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_density.res.nc
  hashes:
    binhash: fef827a760bef0b07e95acf7f2b03717
    md5: beaccfb4dc5211c5f877a4b22a9ff759
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d8506d2384b998988df89ad2888686d6
    md5: bdd0c3b1fa7df039e2fe643c91b60f99
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bf3b489138ff324c9da539ae46a3ab6a
    md5: 335f42d0c25024a2a5c35bb2c47519ea
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_neutral.res.nc
  hashes:
    binhash: da204b90235be9018839880d6125cf52
    md5: 2634bc293199af2940551fa1754f8bd9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 14fee28b5262ab2d67ed769ffafb5ca3
    md5: bb6120dfa71297858629678026dfb380
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 47f4c1b7e44cbf6607eeec7a4fded2de
    md5: 588538869af052fbb07fc52167f29d06
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6384c4385bda66fb8d8ea1dc0b571a60
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_solo.res
  hashes:
    binhash: b5517b34db44d9c130cd457b9551acd5
    md5: 6a978e178b6fb939a584f3c03e090396
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1c439b6ad18e94468bb73c72bc6789d1
    md5: 23fe2f94591edbede63d169d0d28ea44
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7cdf6e02a1c04fa28a77758088d7c37d
    md5: 6a01f4a58005a4efa331c6587fc90f0a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_tracer.res
  hashes:
    binhash: cc4889d5c0d2cfa4722ca53041d9d489
    md5: f49c4fdcdba3506d09d134cd928e1d77
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 83e1acd32041a55eefe3dbbb2fd0522a
    md5: 0543bfd60d7607438bef5002655fce65
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2f12626734ba61b83c8a48018182e92d
    md5: 71f364102444c3e31eb5150fe938100b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 733af8a98d443f20cb74d3ac40771838
    md5: bba56a811c0f62cfc8a8bb7dea67df08
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart263/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3c60c26d6d4e3e755fc6e704cc218826
    md5: 3ce106e0bfcb2f6fc9f43271b17f506e
