format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/atmosphere/restart_dump.astart
  hashes:
    binhash: f56641fde597140a95e8149bcaf8fd74
    md5: c44da849cd62a7b3557eb5159c41738b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/atmosphere/um.res.yaml
  hashes:
    binhash: f7b42c52da4c95df5fb39c12f9ca192d
    md5: 83af9dd8005082a71db6e56366092f69
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/coupler/a2i.nc
  hashes:
    binhash: deb16259d1e7f6d2f5428b6fcf149717
    md5: 7aa22de62aca0b95e291d223612ce30c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/coupler/i2a.nc
  hashes:
    binhash: 354bd0d498dd53bc66f809619d444d97
    md5: c7b7ef6bddbb55666f8323891422535f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/coupler/o2i.nc
  hashes:
    binhash: 32b72f06f73491a38792d50d29a2e028
    md5: 0ddaf3c78646aa25be22a92487c5f8ff
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ice/cice_in.nml
  hashes:
    binhash: c870feed844e04dad78e3955de984fba
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ice/ice.restart_file
  hashes:
    binhash: 4ed56ff1528f76a78a48187a9af43fdd
    md5: 8b67edd40fe7c1f390efa20910715927
work/ice/RESTART/iced.1221-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ice/iced.1221-01-01-00000.nc
  hashes:
    binhash: e80c06eb5737cb4a92bf1f187c181c53
    md5: cfe65067228f9c49c7dd3d871672c238
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ice/mice.nc
  hashes:
    binhash: f865aad206f6b28c66ee9b65408ffd8d
    md5: b02e84835a213e2f8750ef603e23f2ea
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_age.res.nc
  hashes:
    binhash: ea91e2947408eda181d313726abe64d3
    md5: 11e396d5b90fed27ebccbdfe7f2a65c9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f55bd9aa17bc0483965a41a46599cecb
    md5: 688a6f52bed79e6801d1ee8d4f10cef8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7c5af21545ad9d16b47578bbd0a88ab5
    md5: fcc2f3e24acabb20552cd248e8010803
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_density.res.nc
  hashes:
    binhash: e8a7c7ce9cf6c9d7cf33dd9afa0b5acf
    md5: 6af7bd98651faff5b302be750c385ca1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 46dc4e97b8f7f69988d659b7574b3f0a
    md5: 390e296a98672b54523bfabb27d99d79
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3801b67febb42822c675c992c32648fa
    md5: 0a3ea7fb10ff0de6ea6699c06ffcbc33
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8a261c0c1837de81070543b5042af95f
    md5: 28d35b767f32e18fccb8f80fd32931f5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9c3eb5b6d7c67197fa7ec72df6d5c663
    md5: fb25da6c8dc44a48a3890c9a76777886
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6e3f1dc632ecefdc287c9f426651569f
    md5: 8bb93c4c66378d63617a4ee87a761b16
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 370df6e33472c301f00739742c84e7a0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_solo.res
  hashes:
    binhash: e62cf448c9db4b3ea0969b4da4cbc68c
    md5: 541436740b5d1970fd35f613a099ad1d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3c79cea445fa4e76d41155556b82609d
    md5: 9492e3d1632202002eafc969991b1bd6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 78fe6eac9bcada8455a49d7d78bc7a8f
    md5: d91576f81e267994380c6a785bbcc5c3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_tracer.res
  hashes:
    binhash: 75e74689ab6ddd77be149890dd8e1aff
    md5: 9e2dc3660dd1e89b8fde362b6d5b93d1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0b50d655a68a488df329afb6706f8694
    md5: dfd4a03dea3c12d8e113e8378b181e9d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c06abb04a0c649d8833003519e280dea
    md5: 0a4b9adbdb3716c788c943c3fd30cd3a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0f56ea79fb81608c6d177ebabf2a2974
    md5: 0e38a5bd9402b2ddbf1ea5daf7a4603c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart337/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8eed6825da7869370dc61f5c2cf0c418
    md5: 03579dd353fae6269a18a0d613438f01
