format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/atmosphere/restart_dump.astart
  hashes:
    binhash: c5224aa0371a02c50e41fac915cc9b03
    md5: 59a5bbf3ae0f39236b4627d2fd24c922
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/atmosphere/um.res.yaml
  hashes:
    binhash: df4ed0803ab13bd182ef503448d215d2
    md5: 6dd6d1af07a03047ff45d79ccbc7670f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/coupler/a2i.nc
  hashes:
    binhash: d3f607a4908e0f8802e26186eb260e58
    md5: 358f6618b2452f771e591aa6f73adc33
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/coupler/i2a.nc
  hashes:
    binhash: 1adabfa66f316a2961a6cb5be71acab2
    md5: b4c36b17a4e79a29ae042a949a56949d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/coupler/o2i.nc
  hashes:
    binhash: 4cfa6e0c4594665040baa3c30a16d2f0
    md5: 8c3f99507fb5c800bb34388b04ce5faf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ice/cice_in.nml
  hashes:
    binhash: 8c404fa9ce55ac9793e5c674e2ac7478
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ice/ice.restart_file
  hashes:
    binhash: bc459cbf948a42a2c4ae0f0a8b4084ff
    md5: 0e9a7e1530c46df0f92a57678dd5a19b
work/ice/RESTART/iced.0859-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ice/iced.0859-01-01-00000.nc
  hashes:
    binhash: acf58f41cb5ca8cb689877835c641cfa
    md5: d3f0dc3786e05493e11bf0278b0b9793
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ice/mice.nc
  hashes:
    binhash: 703b39fd8965008898414b309f990ced
    md5: 2ad2d35b7ddb8e348ea0977d4b5e3e81
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_age.res.nc
  hashes:
    binhash: b926b28f2821dacf8ece371a100f9128
    md5: 99189f38818aaa74aacdaf087db65e39
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1e13986008ce4a2e321031307fd8bef6
    md5: 6dd0bda6b7d37af78592ae228165bf5a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a97791dbffbfe8517b6918d292a30b2f
    md5: 7bfdeeeff7844ef40acf9fcfd3a19e56
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_density.res.nc
  hashes:
    binhash: 8f3e41f7f5a38640cc3791ca0fdb8eda
    md5: e71899689133c1b9cb767b6c33fc81fc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 91f5922fb852ccd68c4a0f862bbbe045
    md5: 179e2cdb8bea993989baf4dbc1044b56
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a18365b809fc93d04890d3e47fca6495
    md5: 7d7444da5e10890771a16e56d935b83e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7bc930198c3715c17fbf05cf19ba4831
    md5: 721353a61c2d4f7811d6f6e7f7068c14
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f92900003eb4863e06d1dbae2e18b14
    md5: f9b383f051e380ee9bed8ba6aea0f986
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cb5f380662e1981ec7912f64ec0fb3b6
    md5: 0b7a82677dfc5eb502230360837c662b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e71ab23d115d9b843424a689cd51b1fa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_solo.res
  hashes:
    binhash: c6566320411e6cd99fe28e9096c3c0c6
    md5: accc0283b5814a1adc84b08074a5e700
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0f0535a21f51d8bbc3c8617a48780664
    md5: 92100b1b896afb0e9e5f5d6bf9941953
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a9b9f5bd33a5115a02acad9179896ef9
    md5: d84cb81774643cf5bc8fd317bf0cb350
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_tracer.res
  hashes:
    binhash: e881f22991085fdea5b3268a99ad49ba
    md5: d95a2725a9cc4f85e79e2377d1c11a39
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 84bf8a431144d062f7636b87f5305b40
    md5: 01f6f0e1bf18d3b79c2f76b6efcbb4b2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7f3ddbbbaaedd0d9137f383f778a9257
    md5: e6f6dce9039ca1005fa688e72e813fac
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fa19c8984e55529bd5823feeb6a743fa
    md5: f2825b515218829d2f97bf89579908bd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart305/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f7487c98708580fcb322df02a5b548f5
    md5: b6d429b6a7eab2776e388b6106cc3b1e
