format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/atmosphere/restart_dump.astart
  hashes:
    binhash: cadd9d6b8572e080b4f86dc405ed0b94
    md5: 41a52298072ddc405098e70de995c9d1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/atmosphere/um.res.yaml
  hashes:
    binhash: 896c96a6f728ee002fc49a048aca8595
    md5: 4a7a51f2d7b3707843e0c68e609f87e3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/coupler/a2i.nc
  hashes:
    binhash: 28aee625fc5892790377e2d2296aac7d
    md5: db56146a132811ec2ae7483818d223c8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/coupler/i2a.nc
  hashes:
    binhash: a079ccd7eab4b0066399af1402c78a66
    md5: 056c91982d393d7a2edbcba6d2b23afc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/coupler/o2i.nc
  hashes:
    binhash: e08758287e6072030244e6289186261a
    md5: 14552ad794349edad68a551b525af5ab
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ice/cice_in.nml
  hashes:
    binhash: 82ec5762603a2325a9006b60d1358719
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ice/ice.restart_file
  hashes:
    binhash: 6863b00a4c295849a9f3a07a6e8af885
    md5: e5ffd2f40d9f92d6f8a2ecbaf6f3335e
work/ice/RESTART/iced.0892-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ice/iced.0892-01-01-00000.nc
  hashes:
    binhash: 6afd2c58404546a58fbbb4aaa3324996
    md5: f2d389e03cdafd030e28aece3cb6d582
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ice/mice.nc
  hashes:
    binhash: 871f80ad9d7a32397b6289a1a4a3d246
    md5: e92af8b7dc893cf65bf446f26d4a31d1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_age.res.nc
  hashes:
    binhash: 7de1e66a575a5b28a787ef66dea0b1bd
    md5: d97f5ef553f31c378e1c0bf5eba8dc6d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 38c8f33963c9b5e4d2f0a08b7fb56850
    md5: 0419c646f12f4abeaf902d553d1b0ef9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 80afdd3d74ccde12e588e2dafaf51979
    md5: 99d6eccb29b3fde8383d6650d59541a4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_density.res.nc
  hashes:
    binhash: 27ada87152bb0604543718b195e27f3b
    md5: cdb46f1a828a60a986c1921acba738e6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b84a99365e238aef5736ecf4ecb055dc
    md5: 6c353eb62a4354c0d3844972178304bd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c36549cb37d6737079894c023873804
    md5: 8281622e1bd80aa58294c7effb8b7e9f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1a30b4426a0fe6041caeac6d037c3d8a
    md5: 3657a723f51f888ea26b2ed8bbfcf938
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b6e15a88b5e61e66f776b72b22755009
    md5: c7246cdbc7ef06a396d8b49bd375f620
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aa927ef2cc391828c35ed2d8e98debbd
    md5: 07a6a95b69f83212bc0ab945a623c40c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0ebd8c394c5f1e3a86e3e064e386342c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_solo.res
  hashes:
    binhash: 282f67fde08b95493a31a774a43d7e67
    md5: af56cba16d97f69ce5803a91b4fba2ee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1d8c4ca7a6f54be75ad693dc2df7b423
    md5: 64cd4bb4fe70fe58335e0d134728b183
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e3d000700f990f295c8de4a3ebe821a8
    md5: d40b4f02d2100f3d02c27a2ccdfbb720
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_tracer.res
  hashes:
    binhash: fd11ff6da61dc7f2f5ed3215c23915d1
    md5: 49450ee5354d5485d7c893e98e3d7b04
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5ae59ae38d3f3b2986423bc0df9c2c80
    md5: 1e0eb8967ce4799be246db2f46cb9b74
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 27086822320f8035f2a88ca5ac53f915
    md5: b15120c96a177edfa1d3d5b7e4f3e32f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ed391a19df939fe724dd52dd1a0e8947
    md5: 5702de5c1a833287c479d143afad29c0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart338/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 56a2f76903d3fabc65cf3368261fd5d8
    md5: 18a6c2661a80e91c19bd48e86e37b05f
