format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/atmosphere/restart_dump.astart
  hashes:
    binhash: 4254d803114dee38e8b26906205bc52f
    md5: 9268816ef1dce831592a28deb27a004d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/atmosphere/um.res.yaml
  hashes:
    binhash: 81a74858e6a89aee02ddb33f781e1c85
    md5: 067c8dca5755f5e3dabd01526e8539cc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/coupler/a2i.nc
  hashes:
    binhash: 3c9dd52f0895744cd29a28023e5a8f07
    md5: 79870c769b70e8707ca29b41b9e30e89
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/coupler/i2a.nc
  hashes:
    binhash: 1ec83465de9c826347a11bd660a8e09a
    md5: 06227ee6292dfa9e0300288a09832634
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/coupler/o2i.nc
  hashes:
    binhash: 06432f46e1dd37cbed1ad8b7a7c8ead7
    md5: e63edade3f9b40e500f24618af81d7c4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ice/cice_in.nml
  hashes:
    binhash: 62f944cf684b92b25394aca466bd796f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ice/ice.restart_file
  hashes:
    binhash: 4f0ffe9eb8686809b22389fc4d8acda7
    md5: 26c0d2983fad7b6a2ff0729f73b42351
work/ice/RESTART/iced.1154-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ice/iced.1154-01-01-00000.nc
  hashes:
    binhash: 089937afca94216bded087408064426d
    md5: 62ab77fbc22c74d6df6df29ec798f249
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ice/mice.nc
  hashes:
    binhash: 2f233b16fc81ea17271b65b991e10e1c
    md5: 8ccbcf5b8b883a831fe1f2ffdc0dd24f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_age.res.nc
  hashes:
    binhash: 7bd5f9185717e4c695489493373583d4
    md5: 1150cfe415efd0ac62d439e29b02baca
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 27e8315a20f850eef44655f343aa34a4
    md5: 6d3e31f3e94303951e62f7c95de07ef5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a795f2b0fa3bcf846512d237c0a5cc8c
    md5: 6f9460b54ad223124bdba661179f1516
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_density.res.nc
  hashes:
    binhash: bf03d6417288819b9a0bb8b02e887102
    md5: 83f82362529a894ff7fceade49a87bfd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3f24659dbfd95038b14bb220f9f49fbd
    md5: 4c34182d665578c3a50da11b2aec473e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 952cbf3b2f75e29d195ed51f9b9824ec
    md5: 036327fb17b85b30aff9ec8479dd9fb8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b539d44c8017de3fdb7cce103845fbe3
    md5: f1de8cafe78246065f101086d38d2430
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9667001e4b68b5145ffec1a26dcbcac8
    md5: dad9426050bbdc3b2496360490af0dfd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1943cc2e963804b26b0205e0086a980f
    md5: 6e70e45afb552690a7641f8364844060
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4f8bd7e4ce6eb103ede6127dbc74c6b7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_solo.res
  hashes:
    binhash: cab6afe18b6b517485894617a7fa790b
    md5: 1fc7f8993859e0671a05395b69989399
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: be1399f68bd39f4f6869c678b8acc1bc
    md5: 9e74a0375ca4d92ae7f19cf962147e25
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 33e7effb3527114ba721bb0a7a4de4f7
    md5: f6d78742948d68fc7d2514c8ff83e0d9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_tracer.res
  hashes:
    binhash: 69ace9a51d53cdee2b2a4540798ac968
    md5: eaab94f4421edb7cfdaa42c1ff7c44a2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 15ae5299fd9292c5262e9706c94ae716
    md5: 962c8d72594972064e059578f9d533ee
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6a5ed2b668aa47f1b88700ae25dc43ac
    md5: fcc1824302fa21f4d8dacb5a12ac87cc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a169f78afbaca3d85e7708ce42c8a454
    md5: b2902ac0b4a758cf0fb5da2934eb699d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart270/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 600ba0747f8b20056816370ebf66c07f
    md5: 8b8ed015113a867e70a8aa634384cf28
