format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/atmosphere/restart_dump.astart
  hashes:
    binhash: 5bae6226393ec88f50cd321b22004982
    md5: 475efaa7835256d5af8f3cd3bb916ac6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/atmosphere/um.res.yaml
  hashes:
    binhash: cf1ec7472f9ad110443947bf66404fc9
    md5: 37501a00d3790d6dd73f039d3f0db691
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/coupler/a2i.nc
  hashes:
    binhash: d07cb2a9a9b43e9cd7d41ba964ec3123
    md5: 351bd894b16fca304d2fc3ead4a1671a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/coupler/i2a.nc
  hashes:
    binhash: c986125290a27850ff2d33a966be6b4a
    md5: f0f8821b7d527f82d5c69e21cd354fdb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/coupler/o2i.nc
  hashes:
    binhash: 21d89874d68b63895c6068c60423443a
    md5: 27ac48510c619691d6d314f0e87124d5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ice/cice_in.nml
  hashes:
    binhash: d16d403ef28fa9f18dbb9613d9cda8f1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ice/ice.restart_file
  hashes:
    binhash: 4d681224fc0181a15cfa4c81484bb20f
    md5: 294fdbbbece3f28a229c97d5da4a3320
work/ice/RESTART/iced.1814-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ice/iced.1814-01-01-00000.nc
  hashes:
    binhash: 34038808fa42da16385dfdf5b4206b6c
    md5: eb6c349b3a906ade99d666acf9b4cdac
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ice/mice.nc
  hashes:
    binhash: cddf5f320dc7c3dad6ceb68abf98053e
    md5: 0f0dcd96461f9ad6cf187dc88ddf4efc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_age.res.nc
  hashes:
    binhash: 42c0b02a4d6db4293891a0788d3432af
    md5: 5f56e400df22105dad06d93d13ad58db
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5e5d3972422242ce61e8ea720c2b8e01
    md5: 6e4a28530b840b665e33e542d80ed9e4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 97a6271cefe54be3fdabf26634e333eb
    md5: 3ece39f526bae91e56cb15d5bc0ed6b5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_density.res.nc
  hashes:
    binhash: 379f56dbab2a3f7690c47c778b6fa160
    md5: 221a6499c63340b000b1cea09fdef38b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d5750efddb941fbd7c2ec3c8d427fa81
    md5: edf28848469b32f196339da7bd717741
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5cabf50b929c783988fe577374ddcc51
    md5: 6be3eee15bec21236ba5a70762846145
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0d2c8695344dd77137dd8ea30e37e8ff
    md5: 83b3c6a91154a24a6cc0c2797679b523
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2a4e5c2e5fdc069d9d4af867cb858f71
    md5: a28974c6e13949011c2f4f48736a3ce8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b1bb06401fa4132cb28fa25dc2b9e0b
    md5: b94a75ab05692a45047e05f420be04e1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8454ff9d9707d60ba49ff877714a4d4e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_solo.res
  hashes:
    binhash: 9076262533951f02cbb461cdba6edcd4
    md5: 0b73f7d7159cf1ca2979e915140bd1c6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: aed8c218f1c7f064691ea5080d2a1fce
    md5: f587922ceafc5a58a1e6017b665a9488
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 46f3d38f40fdd1c89eb5c3c011d62414
    md5: 487868aef838553956f2ddf57bd92960
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_tracer.res
  hashes:
    binhash: f0d2c69668290a0387dad3b6487680c9
    md5: 0614d714efece54d7261b881d612ff80
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 67dbfe585d92ae00f6b1be4c0f3521a2
    md5: f49146f010e8ba43ccd31bf2db837b9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cd56a59d66148bc66a3839d1aa6799e7
    md5: 9d5a514d67179b514cf835dac46174c9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 369d47dfde6a4a57ab67657f10ad8bf5
    md5: a118bf22c8264fc4a5d6fd1e40a739a8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart369/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9fadcbecff793f03024a5579ee800bfc
    md5: 468178b0696a1513460e09de43d0f743
