format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/atmosphere/restart_dump.astart
  hashes:
    binhash: 56b18e0c3c2bea321d0e47bd2f3bd816
    md5: 244da2d86ed993b48eef8c0333ca9990
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/atmosphere/um.res.yaml
  hashes:
    binhash: cf6c8071503b5e90dcebd789d4bc5f4b
    md5: 92561af4cf1d7113fa79ab9ce1054142
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/coupler/a2i.nc
  hashes:
    binhash: 8acb4f9524d895280617ae6fbbc3ac5e
    md5: 19e2a7d1ba66b2daa63ad1cb79eccc3b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/coupler/i2a.nc
  hashes:
    binhash: def10fecee5086c71b7280e0e39aa6e8
    md5: 6261217d83caafa6e8b1b0fe2ec714e3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/coupler/o2i.nc
  hashes:
    binhash: 9765a2d6ad4c1ec5a6f9e1bb43448728
    md5: bb675f57960ac47347f1f080e786173f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ice/cice_in.nml
  hashes:
    binhash: 416fbd5d56362e54470ae8f260740a81
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ice/ice.restart_file
  hashes:
    binhash: 3b6a3511d72d04a7b89a3a52ebbde47b
    md5: 4290e6a5074b723ce2fd83751b391348
work/ice/RESTART/iced.1243-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ice/iced.1243-01-01-00000.nc
  hashes:
    binhash: 38f01ab54c10c2ca51768ec3a5450324
    md5: 8d01afd76ab781e8f2f2d8f481b02a1a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ice/mice.nc
  hashes:
    binhash: 76a61d40a4631a8d3245703bfe14dc5b
    md5: 2921a56d51ca229dd7b40ff2a1d987f0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_age.res.nc
  hashes:
    binhash: 6840094674d991327823b1658effec6a
    md5: 084577d92d4f3b9472e18160d6231545
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0afb4b35e32a49fbbd31d429f2237eeb
    md5: 3952b5acce0f68d074f6e601ffbcc69b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d317f875f284062a77b49f3329238379
    md5: 1a4ddecb012a4cec1fadf7c9bc6ab273
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_density.res.nc
  hashes:
    binhash: 76ef472b46a7f5133fdef9b8a30e8e34
    md5: 9fe2a6238d9f1633a2ad50cd90393af3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f1e2710fc2d17db13a61d22783f4bc78
    md5: 6b276364dabd3f14037baddef5498676
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ba02814660e5bf491e7c264f037d8651
    md5: bd2982031fa330158e87bd91022214fe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2b298da7c8b49b6ac536d9823be00c5f
    md5: 5cc44c65d77198d265705d13a1e22aec
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fc9d79c03cfda4130e7e5c53e298ae39
    md5: d14955b42c1994ba7650de46c4f50938
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ee2984c81724bceca973c632de5ef221
    md5: cecd5114e2b02d7a1ed2e1a689d8d738
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9f1b815cc29fc61afc92be405310caa2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_solo.res
  hashes:
    binhash: 91a4a5c139d5e674aed9a26ec9d0f148
    md5: 33a002dff2eef46bb80e70bb663903bf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 64e876324b98aa2e8b22800ce62bf2c1
    md5: ef4505ade490f1dcbf120daf4b84ac16
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 16e8c72b75229143e1b96b341e3e117f
    md5: d87e2c30e7ff54240acaeb93f5a8a106
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_tracer.res
  hashes:
    binhash: d5472d8f66ae7d1b9d57f3bdf24d80de
    md5: 77c6d9dad63d32f07cb9ddea986e868c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4c7601b3c8c69128f7a9838489b26eaf
    md5: 147d0620bdc54ff1a3d53909698f5386
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7fe05d067901028f40c92ec9e02c6511
    md5: 0ef0103f569f9c0c903c4b57db83b326
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 375f15f92fde8e53ba7e8dd1204f1bed
    md5: 96710a4909b81f875479be8c0037610d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart359/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bec6b578aaec606c8eb37b7f84736810
    md5: 72a4bddc18a5654c1a93107909759ad2
