format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/atmosphere/restart_dump.astart
  hashes:
    binhash: 3f51c2e364d271730693a5dfef8b5ea1
    md5: 03cdf1d6b92e80f7842ab79154e562dd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/atmosphere/um.res.yaml
  hashes:
    binhash: 4ffe739b7ab4943f10a31153bbc7f674
    md5: a2477351b378f21264bc58b97c73f8ac
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/coupler/a2i.nc
  hashes:
    binhash: a5dd9e59abfb56db2e74a31fea971d7d
    md5: 081bef7cb276b461d7da6057be0cd8a1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/coupler/i2a.nc
  hashes:
    binhash: 6c268e6f041c1358bd8b19c4e5655b94
    md5: aefe6b2df2c4df442c773235da27d324
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/coupler/o2i.nc
  hashes:
    binhash: f3b45e8628590718c36282646bc32dd0
    md5: a5c03f0ab863491d9907d51f5e7599a8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ice/cice_in.nml
  hashes:
    binhash: 3d5a79421e730a3700089e7ea57ea7d3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ice/ice.restart_file
  hashes:
    binhash: 049d86cb061513ca789333e630215462
    md5: 41f96df0d4dd715c062e568effb37dd0
work/ice/RESTART/iced.1170-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ice/iced.1170-01-01-00000.nc
  hashes:
    binhash: 7497347ee90c6cad9a536a8be6e5f004
    md5: adf62c70f51d951602ff5e8af2453196
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ice/mice.nc
  hashes:
    binhash: 767d07d9e53949d72fe14c65ee0a1d04
    md5: af5b908e817e0af28013787cdf3a0d9e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_age.res.nc
  hashes:
    binhash: 2f1d17612442bfb335388d8581089483
    md5: d509d53a793199d5f0ae73b3d2e3b726
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 13b43f15b2a1b149a741045c8ba4d437
    md5: 4c1c8a56f8c875cc6274ca0ae470671a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bd7873636796358d3c84a68bb96935af
    md5: 3fa2470d6f2a0d0e8eea1e90799de1ac
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_density.res.nc
  hashes:
    binhash: 0d695dc5ae47560e27543934bca5a75d
    md5: 4e50b43f7fd3ec9d7b05e8585b6bedc1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6963ea86239618e9dbe4d03671876538
    md5: 729f459f316595c10037d6d5b6e19fd0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cfc9d543550cc6dceddf6eacfb5c5efe
    md5: 7ef189f19f4869929de6427fb6c3c15a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1ea6918ad312b439c6c5b70fdf9aa1a5
    md5: f791120e09e5f7966a132da20a930001
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 178ad56c46729f6fda9a1be997f0e611
    md5: 9de6608fe4e63bdf4407a1e8cf058cc5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8bc7cfa845cc65cdb128ce82baf5377e
    md5: 0c6d2e4f53366914524f40cd34d741d3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9fa98c7cc48ee38b91d11959774b3ecf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_solo.res
  hashes:
    binhash: 93e1643fae2b4b42216e4df44fafbb00
    md5: 12454128c14376b3abe9fd12459f699f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0666b0aa5f973763f392ca120f0ba944
    md5: 329f7f3334fcc5229f8a307daf45603b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 22d3f8fb32dd22c7f70c2db35ef190b9
    md5: 623a76b6a29e3308caed6305bc811da6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_tracer.res
  hashes:
    binhash: df4ed01845ea1d71ddc38aa93c29054e
    md5: 8a830b140d9c2e4b27daa28fab07d42e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3af1cf6b61efa0d595c494944ddba7b1
    md5: fe6c468141d0ac699d6fe5d577d3699d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 69af0cb3a61454efb94dd77191718a2a
    md5: 951ddf9dca1e31a9f85935afd84eb998
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bafb574432320a5091ec5c31d147a34b
    md5: f4895923fd36cc91dbf253e3e9eb5842
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart286/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e90a3c7650fd3bc09b1ecfecc1b8077c
    md5: b69e1b92155a965287c54a8ebd03d9bc
