format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/atmosphere/restart_dump.astart
  hashes:
    binhash: b93e84ac31a6a58e7fb20ae6ec68d67a
    md5: f6a97fd9ee9a1575a3835f42e2a0a17f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/atmosphere/um.res.yaml
  hashes:
    binhash: ad872cdfd00e1e0a7c5b59ebe0aa6969
    md5: 8ba6253992b5bb89518df0bed0721555
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/coupler/a2i.nc
  hashes:
    binhash: 9f361232ce9468105616c55539bfb0c8
    md5: 6cf1cb77c31cdeaae854ca3b3c52b73b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/coupler/i2a.nc
  hashes:
    binhash: ca947d7379ffd02a0bde748912ca36af
    md5: 11b19dade0a7fc0b0e64ea13207104a5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/coupler/o2i.nc
  hashes:
    binhash: 1786cbbf856be1b56050051a7663c773
    md5: a05ae945d239281623c43beb05becc3d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ice/cice_in.nml
  hashes:
    binhash: 08ab1d53de29acb4f0be89a9cb44e727
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ice/ice.restart_file
  hashes:
    binhash: 103780bdc3629ba89594319f2713dd7a
    md5: 6261caa7445d05f3aa933679d281b08b
work/ice/RESTART/iced.0839-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ice/iced.0839-01-01-00000.nc
  hashes:
    binhash: f00ad62950d3105e07b4a220cda6ca17
    md5: 7a8d663b1a48773e9a17076bd6e78921
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ice/mice.nc
  hashes:
    binhash: 316e786fc5f77490e21d98f649540754
    md5: d97fe95f878158f2e015bcb3857d32b7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_age.res.nc
  hashes:
    binhash: 089273cff193d78cb697c5d6f31492d4
    md5: 1667d887082036067e4f829d5be81b05
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eee8f39ccb95cb574d9a3808295a3aa6
    md5: 884e853389f5c37831ca1e5ffe7132cf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3fab4653e950721c0ece536b3f38637f
    md5: a114f97790d67bf6ca04f37d7610bec6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_density.res.nc
  hashes:
    binhash: e10e792241eba772fb30e80626cd0829
    md5: 309859fe2244c99b7dbb4f1188aea0f5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a422ac57f792cf6d508f940c8b675bae
    md5: 0f9f2b5afa3e3c9c1c8c31e641dedf85
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0413ebe166a0670dd1b77e876b782461
    md5: a071d687a4a87757f364844fcac3d726
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 13cfd90b870fd222ad45dd0bdc008e71
    md5: 74a7350bd395d4aa5215e92c30a24531
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6aebe9b6666b7b6e7eff895833c0df40
    md5: f2de697414d56a2d091a638c6746dab2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b89543bc93e9f344a0ac075113441762
    md5: 483616a85800a6f2605eadaf7ceaadec
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: be891366246986dece24266a019eb3e4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_solo.res
  hashes:
    binhash: af8fe5bbca49f2364954d65922b14429
    md5: 886c798e99c3f47ed613f310125bd255
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9c02339badd6d03108a45a4a0a0ca870
    md5: 839e8a14f498f3e0b95d339f3f331c0f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_thickness.res.nc
  hashes:
    binhash: afca1088b415ef9f7f15a09d04656902
    md5: 7c3d95b61f19185af14fd4a562d05cc7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_tracer.res
  hashes:
    binhash: 7b8e7d83e90cc99107ed190f5c424bdf
    md5: 29ba0c7d9ac15d868b0fa9609fdb4913
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dc6b9dfdebdfde86ecf4f52ce55e3e0b
    md5: 3f96ac0bef8fcb40c4c04c17eefa0b23
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3637a5ab1b52a3948df85ec5da080ffc
    md5: 6b1f9f59eaf515854a1b5b535e190bd5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b7d7f5c110bda578dec1f57c9f2c672a
    md5: eec94f3ce415275fb64c8536ee347164
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart285/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 00f1510aa51b20547f2a60ba0d8a80e2
    md5: 2c2579be0bdd3973bf0995ced2073f73
