format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/atmosphere/restart_dump.astart
  hashes:
    binhash: d6b1a10056476132a0bfb1aeeea1572a
    md5: 32bc714ba2990f0f4859e1dc318e8532
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/atmosphere/um.res.yaml
  hashes:
    binhash: ce1cd1581de254c68d96a39de8a117c1
    md5: 103356d1b71b7b80de2a75305fd95d46
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/coupler/a2i.nc
  hashes:
    binhash: 13fd9b82690543692d793fd3c497a115
    md5: 5ee4eede35c8311483a77b561f4be2e1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/coupler/i2a.nc
  hashes:
    binhash: 741e900437dc3f5e30ffe71e7e94d834
    md5: 15dea89b7473eca757287bd2c3cb573e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/coupler/o2i.nc
  hashes:
    binhash: 4bf94de3ef476f84cc899d7055c1708d
    md5: dd78c614353be70c600415d93fae524d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ice/cice_in.nml
  hashes:
    binhash: ae600e24a9102685cbc59545508ea9f5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ice/ice.restart_file
  hashes:
    binhash: 7372869fd620d4a0d6f2c18585f8a827
    md5: 40d3c6c0efd78ad4aa8f525b76058f64
work/ice/RESTART/iced.1163-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ice/iced.1163-01-01-00000.nc
  hashes:
    binhash: 6ae5c2dccc0a5ffe07a80341c5aac47c
    md5: 97674f07cd018fb9d8405ab946e1d401
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ice/mice.nc
  hashes:
    binhash: ceaede9e89d208c19c07a4e729d85242
    md5: 7d45d75dc897116f6e944a98bb5d416a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_age.res.nc
  hashes:
    binhash: 83ea8b318339df8c897fa5b5780caa0f
    md5: d971afa29726f26424f382acee081e7a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c46cb9b0414f2bbd7b0a779e727e428c
    md5: 792da2eb7e0272fcfeb0c90b306c6b45
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 56ce60e35037f2623861b5b0d6a65444
    md5: ad6a525b018acd092fb3c7e7e724c387
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_density.res.nc
  hashes:
    binhash: 8ddef648a52349228e3e800774bdd050
    md5: 2570fae96db40a26f4819626c0162fb5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 39015e4a8ad93c3479b83eba069e9a08
    md5: 482c799cec86179cf95929c58f2f96c7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9aa17765f501abbd3bb088aa07f3c3de
    md5: 46496392b2860f8281371c6354daf5a2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a3eeb89ef03ccb4a091be7e55d321396
    md5: c3de57b2e14b9441a08d21be288dd9d0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d290dfd0ca0d21fe3e394eff0a6b69f8
    md5: c6ee68a598fb825f65578fb6ecafac33
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_sbc.res.nc
  hashes:
    binhash: edb876e7822823bababfdb42e4299b14
    md5: 40b99bd3f5fe13e5eb8ea686e54afa1d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b1e76747eb6df6dab9ba61c833903c65
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_solo.res
  hashes:
    binhash: dc5177b48e99d3b0f2f30d75b87e1d32
    md5: 28daa2b8b6e13f10826e671ad01e684c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0331810cf04d769081070cd7a77c415c
    md5: 28b31a784a4166975ba407ebed86a675
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 337f3f67257c57107ff7174f3a959546
    md5: b707447c13a2bd8ec69646e37030b2b4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_tracer.res
  hashes:
    binhash: bec0dd9298d122eb95df84b5c0f4d6e4
    md5: 83a205a68cbea93a092f4a9f77b2800e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e7bb615f3a570e5b4f031aa779eb37a0
    md5: 8027aa0991397ce0b8ce4ad1f0349620
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 43f1c5bca59d29edcfbd73d841ca644f
    md5: 975aa42e3ad6a49b42118fe2ba4f08fd
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 863418aadc66114f8f342f4c3400885f
    md5: 810245065a72e3ab01ba14cc74a3d92d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart279/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e5ec3b92ea2bde4ca8b10f32d93c8aaa
    md5: d24f22103bcb8fb6e919892c8d991383
