format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/atmosphere/restart_dump.astart
  hashes:
    binhash: 936a6991aed7197d2a3fe215eb22faef
    md5: 6f22d1efbc07353b6d73d00770b74f8e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/atmosphere/um.res.yaml
  hashes:
    binhash: 6f5df0201870ab15e5019d9129c641dc
    md5: 66aa235c5d420ab747267603d063a82f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/coupler/a2i.nc
  hashes:
    binhash: 988cb0ef7d6772b8858b1841ad494e29
    md5: 611b01876f93557d163e322fa1ec7160
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/coupler/i2a.nc
  hashes:
    binhash: cd04d80690fbfc1390e6e3d6405009e1
    md5: 8347f0a659fe9767351a120944460715
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/coupler/o2i.nc
  hashes:
    binhash: b239ad15000b9feedd32d58f83998836
    md5: 6cd4fc67e0d704671addad19299e5bd6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ice/cice_in.nml
  hashes:
    binhash: cc0e2b2c0dbe6e97e149fef442bcac19
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ice/ice.restart_file
  hashes:
    binhash: 59bd4ee77f2ccdcc76186c1fe14f5437
    md5: 2315b4e2586744727360410201369150
work/ice/RESTART/iced.0922-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ice/iced.0922-01-01-00000.nc
  hashes:
    binhash: 75508384b57bf6efcd0cb4e57f315ed3
    md5: 5ad7f0883651e863035f0d81598c2fa7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ice/mice.nc
  hashes:
    binhash: dca9549fd8dbd8d9f1bb5cdeed866c79
    md5: d112664c048beaef89719e036d42fb02
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_age.res.nc
  hashes:
    binhash: 72952c002895c27ae26b7691b469b2bc
    md5: 50210b5fdadce938c381e148ea0380f3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 43afc9a532153306ff00a4fa0a5625a8
    md5: 855e1475691b462ee30e34addffc36bc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 970b9ee856eedac3790a22e08774041c
    md5: f66f94d9a6f25fed7ae44baf1b16b6e1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_density.res.nc
  hashes:
    binhash: 1cf35ed2b06e65ab282a5b3bc49cca77
    md5: 07f84ce07088fc1ccb3d4c78483d07e1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4cf08baa19dca2bb439cda5538a5867f
    md5: c9500c36d7d78bb850b95fa777d24e11
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a09a1dd9d0decbae08a5d68031c0ad57
    md5: bd6df1d1eadc17fe1792b29a582892f4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 776bd929b2a4e2ac35c1d4f60568c831
    md5: 4e7a4477e6bdb17e7092ac179c3b4894
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 665530fd2748c6c4537493aa114835a9
    md5: 5a50744cf3d2c30431139edabacd367d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ae1e617dfbfa65e784ed51cca8ab9545
    md5: bf39de2c7d706d74620608020f4e8d9e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: aef0c8b0894550cf29c7e39193a47402
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_solo.res
  hashes:
    binhash: 7dcabfe1548b67923ad8da22b75c9f2d
    md5: 66191cb870de2dbbb065b36ae1d7f8a2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fd71760868a7386c5ee0caa57a89161f
    md5: 5ef90998266894d98033bb7b3101a497
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eedf689376a4f988c242d5371acd9cd7
    md5: faf1d81bfd4e35965a9ae49331a3f943
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_tracer.res
  hashes:
    binhash: a7d119b20a2ec96add8decc4edccd28b
    md5: 94eafcc2a25ddbecb6e042583e0d7dfe
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bdc240bc0648b08e25800f5c6567c74e
    md5: 6fd022457636d7cf708f6379cd0c847c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a93b75233ff14d134adc42bd2cbe41e0
    md5: 7532bc8e56944a16927ff651df9dec48
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1fe119287d24276be2092dea502e3f8e
    md5: 2ddd800bfded2bb90cd6e90a7c724600
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart368/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e99a17280f3d8a1bebe7ff10e23cd57d
    md5: ff51f0dd7d3c096c862460e792fad189
