format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/atmosphere/restart_dump.astart
  hashes:
    binhash: a3fa35d5576d52e7388bd68062a79290
    md5: d6e61b146b169285bd12ba063d2965eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/atmosphere/um.res.yaml
  hashes:
    binhash: e994a94c15f95eb0dd54dec2d3d3e3a2
    md5: 9c02524e974abda5a22f03d8eaa78be4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/coupler/a2i.nc
  hashes:
    binhash: 14c2e1a512eebc8294bf764ba0e31471
    md5: 531093093826e42be60017c4707171cb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/coupler/i2a.nc
  hashes:
    binhash: 831425e03f6c0c4daaf8768ededf7beb
    md5: 55d185dbf6fd9f691e101bd4513133f0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/coupler/o2i.nc
  hashes:
    binhash: 455d322142abaa068a430811c04a08d0
    md5: 3f1e02a86de89b883ba0b8ceea9b4f1f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ice/cice_in.nml
  hashes:
    binhash: b1196dfdf065d04c9215a202dd46f617
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ice/ice.restart_file
  hashes:
    binhash: d08e72a20cf7793659f0ed46e83602fd
    md5: d6ef5b9b9c3837a576a1bc0465d46272
work/ice/RESTART/iced.1240-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ice/iced.1240-01-01-00000.nc
  hashes:
    binhash: 914fc7aab6f48e20a2eab7ad498aa7ac
    md5: 4d4a2946189d69d761c0e7868736a0d4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ice/mice.nc
  hashes:
    binhash: 665c6bf6bab1285080dd3c16ae4b18e8
    md5: 17cc1790285f0a3fd1178dd8cc4613e9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_age.res.nc
  hashes:
    binhash: a8bf38a8986edc4377f0ca062d4bdf38
    md5: d28623b052cb1cde052aa32872fac09e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6dd2bccfcdee7df21b336d5bf64f903c
    md5: d092da73d843a41c0e67bae73f9dfa76
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 383eca05d3a0d7e7cb4c6b717c9c62c7
    md5: 151867855fb7eaad3e575aa04d2c1af5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_density.res.nc
  hashes:
    binhash: eaa1101b71401a85f19926afb8e5be42
    md5: 4a05cdc1d7eb797f01335356c7417112
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 602d2b9b1fc73d45b9b2df447ee499d4
    md5: 9e1558f3f67fd40fa9781aee7ec17353
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 329bae2f4abe26fa160eb9c51bc24e74
    md5: 9d96984b2a237ec3721e15c147132472
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3ef8f3fe68a80c596076fb9ef46fc1f1
    md5: 73022162a76660012f62bc52256ab0f2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: da58986b657c4d792b3a440e1ddd446d
    md5: 04451759ce88d1f09c3ae45cecc19ab6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c94da9c073e41d86b6cf89586bef16e5
    md5: 352e02dbd2b1ea0d74d3a2e859915349
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cdd20ffb081fbaf7be7e4a3a448535dd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_solo.res
  hashes:
    binhash: 7bcce9ac7efd310c8625f138b1bfe50c
    md5: be3cb096b909a106715a29c57055ddbe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 31e720dd4cee630dd3cbf7e5a2b16ba2
    md5: d4aa87cb08227aa7280099cc136f2f1b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 15dcbf10d9cc3c29b159c6e697801b09
    md5: 0bfd9e24c0f97d9027d24a7583666e62
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_tracer.res
  hashes:
    binhash: 267493544a3ac09e3a6959dc8ffe061c
    md5: 3c73247036f8696edd0e453f137dbd6c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a96d615dc6a9a1f74f19a7e5574cd7d4
    md5: c1f62eb840088ea85ecfcb1cd097fa1f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7e560696ebdf71c26068c595f33a9113
    md5: 0c73bf813047cd99d126fa13de75dbd6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c23b522dbe8e6446b9a59a8e4d0a90a0
    md5: 2a8bdd9a327f602599d6bcbeb137a459
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart356/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d5cfe005a7a6f880872f67c5ceb7fab1
    md5: da99e2c9caee19f6e07657ea128834b9
