format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/atmosphere/restart_dump.astart
  hashes:
    binhash: ec8f5e36c8f6402f1099c26431828480
    md5: 9299ef813db53102f07250655c666269
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/atmosphere/um.res.yaml
  hashes:
    binhash: 9dfa3965a9e9d11f59a636a17ba7748c
    md5: d9581eb6e26209af3fd3630fbd4f9441
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/coupler/a2i.nc
  hashes:
    binhash: f57a2ea125eed44210596cc294d64815
    md5: 9672d0b55e201a170b02f8786c60eb11
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/coupler/i2a.nc
  hashes:
    binhash: 95ce7478d91ca8127c85c04b45ea9220
    md5: c2df22307bb8bde698094406292341d8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/coupler/o2i.nc
  hashes:
    binhash: 653089e70a2ff449efa95d60bb93effd
    md5: 8cbb9900632560e618dd89325d8c08fa
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ice/cice_in.nml
  hashes:
    binhash: 9efdc7859fbbb6c57097b264ca6ea19f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ice/ice.restart_file
  hashes:
    binhash: 4224a737ecc3b074cc61819692feb3cd
    md5: 09047764e6262aa21127d24436356bf6
work/ice/RESTART/iced.0885-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ice/iced.0885-01-01-00000.nc
  hashes:
    binhash: 56936ac1d5bfa19404b044433d410b5b
    md5: b70ee7e035ff28fc49ba2aa7a84826a9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ice/mice.nc
  hashes:
    binhash: cb1826baf15a4e586d0235605fd2de97
    md5: 026c8d736d32ec065dd1c62f79a7ae97
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_age.res.nc
  hashes:
    binhash: 5b43536df1206ac4bdb435e88601d830
    md5: ec6fda30e4f869d77515abb05be596e7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 740ee6704fa79b2873b800a5c80cc2b9
    md5: 7573016db57aeb3dafc71f458054a466
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 88a7455f1386fb53bf6ae1246641fbd3
    md5: 300c15cbe146cb23d419c9bfaf17f19f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_density.res.nc
  hashes:
    binhash: cc06f86492dd506975dbd91c86245880
    md5: 4ebf68abf0d613b068182ae79b1e0d7d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f1eeb98c66b3bccb1c9daffbfdd20577
    md5: d5cbdcdbaa7dd775fde07d8ddba542ee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b01b67a82a6733434ea0790fc847673c
    md5: d3c13d1b6ea93f55709b6f36e07f5ab3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b4fc5a8796100cfafb6418d1bb38ac12
    md5: d06b254535adc545f30329972dde2a22
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 267e744786be3c8b7f625dfa9a1a9b62
    md5: b018c8417fe010c7c79f30934790b1fa
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 06ac4c170c42bc9dd46697ff4812a4e0
    md5: 7084eb512d969f4a4ae728af7b6e4195
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 39a48e18a31461d92f4beeb265e1ab6a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_solo.res
  hashes:
    binhash: b0c6c3f1a3700cf0a5287382addd3d5d
    md5: a118bb6a031672dfbfd2bdead086efaa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8483b5cf94ab244459f873007e0571b5
    md5: d2e66835a15174b1c7c93fa4bfe78c8f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce1d141d981dc712d40359ac64e97fee
    md5: 6049498d1931b25499c6b5d76fdb2e33
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_tracer.res
  hashes:
    binhash: 89611226b7fca7a4b858c84586f49e0b
    md5: dae94f969cadb3a8b2b4b1de8a8f8c47
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bbe03186d5486c4b1b3a26106c5d4235
    md5: 8fafd21eb40ac2b1ee78eac3dd36f2cb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8a9d58eb5fd06c986a053ddedfd7bcff
    md5: af666f7163e58cac871225ca78faf6c3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f8947bf5353fe905f0d7034b0bdf810e
    md5: 56694bda9bb1b2ca61ad3dad4f5f75e0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart331/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b748c2b0ed55dd15e42a3f8c913d51fe
    md5: ab5889dab5b975705bc8f5b8c01c96b2
