format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/atmosphere/restart_dump.astart
  hashes:
    binhash: 4c0ee4001c2572c382636d12deabd445
    md5: 0ff7b5fb1e92baee942fd581365af121
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/atmosphere/um.res.yaml
  hashes:
    binhash: 22ff2583768acd326a7353c0da8559b0
    md5: bb5f1d5e0d05d9692f2879dc776b1ef1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/coupler/a2i.nc
  hashes:
    binhash: a66f7150ca7dc7b961f7f4c3ea08e55d
    md5: d3e5cbf909611b24aa2b26a49e5c4787
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/coupler/i2a.nc
  hashes:
    binhash: af36223432b9e692bd56e5802b876eea
    md5: fd34e32ab9a65f387a262aeeac1d0ce4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/coupler/o2i.nc
  hashes:
    binhash: 74246a533b5315aeeb598b6afb9f3fba
    md5: 848328b54d7a0b060cc9228acee41a87
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ice/cice_in.nml
  hashes:
    binhash: ee141028590de9044b12bb560fc8bbd0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ice/ice.restart_file
  hashes:
    binhash: 5264cfea13e8fd0c0cf2c79ec925aadc
    md5: f5ef20bf5812778cf436f04749601549
work/ice/RESTART/iced.0955-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ice/iced.0955-01-01-00000.nc
  hashes:
    binhash: 218b7fe772cfda845b2777a79cd8ad75
    md5: 00bdd3b4088b4970142f4f76af17aed8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ice/mice.nc
  hashes:
    binhash: 79980a1bc1b59d16a0a1e1f44e7cc534
    md5: 4e48e2f96efbfb437c4670419a9fe86e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_age.res.nc
  hashes:
    binhash: 6ee920d5535b3b5b820dfe11dc7d2ec4
    md5: 5d49848064cff2693aaa1fde69ff1cbc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 71c73d8267661ebf6bfacb6c6a748fd9
    md5: 090a719e9955268c28c8cdd4582b3cdc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 77d715e7879bace97c0165eeb2c239cd
    md5: ebbf0278a53746296d83f24c1d32d440
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_density.res.nc
  hashes:
    binhash: 8a5d6ec6b457382e4fade1e11cbc5814
    md5: c2517a4dcba241caf22ee21bfa2ab0b3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 67d9f313eeaff737d3de1cff4197a73a
    md5: f2c7f647103e0fa8b71d44ee47d7474b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ef61c0460c9975bbbef32e160d5e7112
    md5: 14be8f872dd48f569da7babab247987c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1a3857932fe36f329bba1f9019af0fd2
    md5: 0e61b2ac47991204f371a9960cf7dedf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 870b8b71c789f5d47381ce09312e6114
    md5: f295684ddce9cdfefde84bdde571db0c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d8988f4d596aadf022f7d2f3ac46439d
    md5: 5e768a91e6560a25708af27fee935c49
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ab461c7945e333217bde35abb2d000df
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_solo.res
  hashes:
    binhash: 5b2ec09b72c542f529611fb2aaa76224
    md5: 6583619068b42e69605d4ef3729f7a32
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2b7b36ad3a9a09d5a2fb7517a4162fea
    md5: c366f602d30af7ffd1509227dec53d2b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 54dac921e6a7a4e40c6998fcbd99da59
    md5: 40d1de8a96671799b5911d4f648e52eb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_tracer.res
  hashes:
    binhash: baac4de18634ce514c8273a64efe42f7
    md5: e78e3dc58ba73f04a507702b50932a84
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 66857ff28f82800b947803e670b46df4
    md5: 4765915f3f1f348f40c69ff905b94c1d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c38865767a2fcc9927f9b02167be800a
    md5: 6f5dfebcbc67259b519ec8e6de8695ef
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7a2390df4a0ea6992f1d696f2cad9192
    md5: 411f94413e668e4c143248d1295a32b2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart401/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e425c795e06a537b202fd56363c9dfd1
    md5: 8b06deaf1d26b895b60ecc6219554a6d
