format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/atmosphere/restart_dump.astart
  hashes:
    binhash: 25f9d8498704042d888a4f40bc842a32
    md5: c2bcb2d06f200e178ec26ab475e6a6d2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/atmosphere/um.res.yaml
  hashes:
    binhash: 5c234d4817e701adc2587705844748a1
    md5: f7ea5e86a0fbeabd08be4fea1514b18a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/coupler/a2i.nc
  hashes:
    binhash: 8a3fe5ae667bf95f89c1e2ed527d4ca7
    md5: 066a01231ab6df8072f92b342ff94c72
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/coupler/i2a.nc
  hashes:
    binhash: 0319cede050d1818c7dd17dcb08c45fc
    md5: f5fc6fbc6ab94016e840da0034abdb80
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/coupler/o2i.nc
  hashes:
    binhash: bd0eb293e2fd23c4f67fedf36c1b27d0
    md5: 1fc3a7ad1d951856b4466d945389cfb2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ice/cice_in.nml
  hashes:
    binhash: 2df1f0d6be8bb583e9bd276c8562acd0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ice/ice.restart_file
  hashes:
    binhash: 4a36b937064ba5afbff27c15cca19b61
    md5: 27da4d8abee78ed7ae69aee5fbc72e73
work/ice/RESTART/iced.0956-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ice/iced.0956-01-01-00000.nc
  hashes:
    binhash: 8d95f1cdbd3face7d397cfd31d9a8211
    md5: 2dd311dfd16d18bdc35b8440b7a2608c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ice/mice.nc
  hashes:
    binhash: 76b2c5fce36da4440550662244b0e290
    md5: eb74393044c98b83b6e881b317b8c46e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_age.res.nc
  hashes:
    binhash: 54d23ecede221d55f9e32084857a2993
    md5: 02e0636a7a5b5e310030ee399264bd75
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8540d6b689725df79b39fae3357df057
    md5: 2d27885213189e4ee60511b886d7b30b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6b65ab3a6b0768da7e0bf1a63363226b
    md5: c67e60fb0d9c695a2a7c2e10ce25f106
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_density.res.nc
  hashes:
    binhash: 96387950e9f160b6e30e2730f45cb057
    md5: cac7bc7456064cbe6dac6537e8042dc2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d3f0f73ae08a55de099d73382a35329
    md5: c4c930ac7bfbf1d3d410b1845c66d2af
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6d0e7fb5f1a9c5c14ca0e1286b2e126c
    md5: e6733f09a85b8b803eaeb9ab528e24b9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_neutral.res.nc
  hashes:
    binhash: eee5d6998f3fbff74732a54296bdb502
    md5: 6e0ad9080b0042292ea5c1177c07bc98
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2102a79f7f368e25900ccdab85e75102
    md5: 77987a2867316a81082b7ac08ab65abb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c501e4913644bdf13b5f20ce08ee2fec
    md5: 9b52a712029ac70ab95e0a32f6e9ed93
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: da120350b3f06ba3dc718b0ad2e493c4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_solo.res
  hashes:
    binhash: 0f7b73ea35bd8fc69df9c247c9718dae
    md5: 77e7effa89e73f2fd5e82dd9a1874d14
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e136ad5dc109f3385edc69e98f42269f
    md5: 95fee98ec65db66cf3731074d372ae2a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2710c7bcafcff411bd1682bb4c419960
    md5: bcbc97a11657ba8baadd286080305fc1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_tracer.res
  hashes:
    binhash: 37d5a1f987fca0af2762ce393d48dd7e
    md5: 9668c2700bf13fa25a9b2c900d4c2ae4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4975417df015d4bfa02d18f667800f85
    md5: 51e960d01831f0e6fbfffd14bd8fd557
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 05eefaea0711b7f71a330f3690aabd07
    md5: 58445da34ecd19ce288bedc173237eb0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ebda56b5db6da23d7076adb0f086f78d
    md5: d63f466fd7da48d85c2eab0a6e111b93
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart402/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9aee526e4a05c09687692be8e725a2c6
    md5: 74e6fc944e87ca3c28c6c441419724ab
