format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/atmosphere/restart_dump.astart
  hashes:
    binhash: bc76778ec5493c0ca2cc7f1d93766266
    md5: 7371cced1cf98f105eed5cada0880c27
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/atmosphere/um.res.yaml
  hashes:
    binhash: 9d4cae1d2e71fd91e251acee16f03f17
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/coupler/a2i.nc
  hashes:
    binhash: 853b76bb4a60de660f70bd6aeaeb8406
    md5: 453491ff53f526017456aa7d7a1925d6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/coupler/i2a.nc
  hashes:
    binhash: b982b039bd320f96ba85cb2981b9ad6e
    md5: 79daa3e61fd1b98a7ec2c6349725fcc8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/coupler/o2i.nc
  hashes:
    binhash: e462b5205c0a4cdad46c8ada7a8f356c
    md5: cf05b93ac47d9d582d9bd195e499f181
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ice/cice_in.nml
  hashes:
    binhash: 331e24a6b033ee68fa3b0a1b100dace7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ice/ice.restart_file
  hashes:
    binhash: 6745b6cd6d85d44df42db262dffbea11
    md5: 0431000b63b800dd76312d27bc966cf5
work/ice/RESTART/iced.0850-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ice/iced.0850-01-01-00000.nc
  hashes:
    binhash: ebb62b20366f9beb1ff79ab0805629f9
    md5: bf1a1980d854c902b77eb7bcf5c688bb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ice/mice.nc
  hashes:
    binhash: f5622163816cf04d0c4e876c4ad9030c
    md5: 784a7091d51c04948248589c62103a18
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_age.res.nc
  hashes:
    binhash: c37df1b1493a3cd68552e87a5ffc1264
    md5: 6836dcf3fe76f32d898adc89f356dd1d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9183c54e77d3aad715929c9021efb5df
    md5: 0071c357aed51142505144b55ab04109
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6c1809f85c9b32425808c6234283738f
    md5: eb026cd2836773443b1e0e3ba23973ef
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_density.res.nc
  hashes:
    binhash: 9e24aff3f49fc42d6dad20bc750c86b3
    md5: 45eb954053a5f318266f6ac131a357ad
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ac70a64902119827c8c6eae2ffcfe093
    md5: 6b066bfb07b8d45bc16b68beeb76e8f2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c1f039cb430f42cde954a9192dcb8037
    md5: 55d40f287cdcd72b452c9ef0cf911b74
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c571f361acc0a8b3fecc4b8608fcd54f
    md5: 99960d311ea1a1cb88800f212a2f6e94
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3529223a06eefbdde7bd7615fd86dd79
    md5: e3551a91da9bca587ef8f99f09ec6e1f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a178bde9319f3c9d067a1d3433996465
    md5: 962f0dc4ce8c0975a1ff49c897cd81d7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 35b29c13b39f4c32e1116517817b2306
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_solo.res
  hashes:
    binhash: 7953d62dac7d0e1223ca2b17f2c71892
    md5: abc71e90047a9eda84f508185628fb2a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 85e60b47e1c716f557cc4c24ae012c4e
    md5: 9ec6df5e2e9eaed645cdd6413dfe97a9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 333cdc3d5a68d228d67b35651fc286a2
    md5: 54cfc67d76d404031e4c4ef4599dca48
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_tracer.res
  hashes:
    binhash: 18cc81594d3772145c94489cd5b7051b
    md5: d4754f6849032633520debae8151d44c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b27528cb0830a45d4a8ba53559dda8f2
    md5: 4ace0c559e246908bf75ac152afe9ba9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 10830adf9b9540da407d48d01ab1fe55
    md5: 0868d26d6562161ec1c4a030811f7ad6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a73d75fcb06f06bb801aca5d9314c685
    md5: 720ca187f8b8a72d45e8bdb4d4f77619
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart296/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 48455a73b4cbc1e32bd35e7bb67ceab2
    md5: 59693388f65515a1eae3c864e3e70a09
