format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/atmosphere/restart_dump.astart
  hashes:
    binhash: 9abca194d054f5a16416044731ca5286
    md5: 030041d2e67110a8fcd64be4cda28367
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/atmosphere/um.res.yaml
  hashes:
    binhash: 4fd857d7861167ebd62ba66401515757
    md5: ee185bc1d9d202125a913881f4506dc1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/coupler/a2i.nc
  hashes:
    binhash: 156d5d5199f9f101cd8b76ab7bfa2c12
    md5: fe82dbfb3b36254cce29886c599487c9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/coupler/i2a.nc
  hashes:
    binhash: 676d1a55ba1f4b8d432db1e435548189
    md5: e53e37599e9140ce80f456572e84b465
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/coupler/o2i.nc
  hashes:
    binhash: 4a99dc33bf3899caecfaeb7d41bd573f
    md5: 7ac2edf8e3ea6d7bf9d3d6c31e153825
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ice/cice_in.nml
  hashes:
    binhash: 74105de4a7fc3eebafc5889706cf0cb1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ice/ice.restart_file
  hashes:
    binhash: 45713c3d20ec27bf742347aa6f2da231
    md5: 5af7025694839948ba88e2311ed9f8f0
work/ice/RESTART/iced.1723-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ice/iced.1723-01-01-00000.nc
  hashes:
    binhash: ccea0436ab52dd9f31b048aea120e76c
    md5: 76c54c7b84b64768efd6a34529a84050
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ice/mice.nc
  hashes:
    binhash: 8fb23ca3e6e2f4a1d25606ff3483b332
    md5: 6c3fd1f3b51f0b4768ae75ac8f2c1eb8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_age.res.nc
  hashes:
    binhash: 529e4c69b9ccdce570f74b9b207c0910
    md5: dbee9fa25ad2feac85dcf3e99955e0a4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 173d7fa8f602335a9e30f13074bf60f0
    md5: 1cebf6f97e256d9bb1c78634b9739d14
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 85b5336f48ac28595a79e31e3ad3bee4
    md5: 588ead79a974c2f14d75a83a53a4036d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_density.res.nc
  hashes:
    binhash: d74ccc3ba7393e683e5950cd78ba62ff
    md5: f3428f2f03c08f68275f7851c3d0fe6a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a1a2d59a65e11d8a54a06baa9b738d1d
    md5: 9778525062a405ea6efa389de083794b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f525da1675b0e648da21c8617342ad54
    md5: dffe352d3a038014acf37ba994258857
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f510e09b818986174508d7520d81b50
    md5: 43da5f950db89e8f62febdd3e6a539c0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e7e08e0fe7ce4282423398f81d609bfd
    md5: 0dffe9c9fa609846752ae40f9b61787b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_sbc.res.nc
  hashes:
    binhash: abb237e094ce5ef20eb4bd6e00a43160
    md5: ec58a4c80cbeddac78264b7f4d7f15b6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fc3f992a0311c41bb020a591b4a137f7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_solo.res
  hashes:
    binhash: 9c04382084f4921669b79708ef29ad35
    md5: 340d437a973e0cb318559905f16870b4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 690369742949b2cf8625306cf4fb7583
    md5: fe6ec31ff2badfc71375322db5a807fd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 715f37a27fac6285c1b14616470e4e43
    md5: 7370d0f62eeea4dee163f2b84a7f9639
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_tracer.res
  hashes:
    binhash: 5f1c2c106ead1f5033089dcac590d2e3
    md5: c1f0941d134059cbae32ae1615fdad62
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6764c46dbdacf51fd079e4a24e8e2f3b
    md5: 344143b42353be8db0ebfb8c2405c607
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: abd29a2550d5eef78c28ef58ef35aa32
    md5: 5cce861857c0f2edd64c74ce0523f0f7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3bb09d1cf942dc8de7ad62b47f25ad49
    md5: 8a69a688a2a576c38c4ef1a20d69bd0d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart278/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4e948f231a38d394c42050d8fe4b54a5
    md5: 678e13a15c1b80fce99b7bf252102915
