format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/atmosphere/restart_dump.astart
  hashes:
    binhash: e67ef922d184c53ae292f98e5b8e3a36
    md5: 03e9f154ae02fd66a0e97a3a09026406
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/atmosphere/um.res.yaml
  hashes:
    binhash: 6496113191d4ebba80a9f499eb88b22f
    md5: fe159940c1ed941c83279393ef4e028e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/coupler/a2i.nc
  hashes:
    binhash: 58276d3242696ad821f71a65dd90ebbc
    md5: 199fbbea9678e66b99b79d1b07650ec8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/coupler/i2a.nc
  hashes:
    binhash: 2e8db891b594f9c3a26f3384446eca4d
    md5: d05a6ed9bfd6cb99e1d8b6e58337ba1c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/coupler/o2i.nc
  hashes:
    binhash: c8ab58396d254385da9a0bad4f6b940a
    md5: 7b637e644c128c45ff02166faa92f1d3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ice/cice_in.nml
  hashes:
    binhash: d00ff5311a44bb0d111b364cbdb9f66a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ice/ice.restart_file
  hashes:
    binhash: 8743b4838e7a8ab25c7d163687916518
    md5: a1a5991f7379859ecce235e353d2aa72
work/ice/RESTART/iced.0940-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ice/iced.0940-01-01-00000.nc
  hashes:
    binhash: a1f0fc0f571fc37c61b8381bee7c0f43
    md5: 7f386ab603a688ee728323e6dbecb182
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ice/mice.nc
  hashes:
    binhash: 66b894252934bb32f7367b7d35432f31
    md5: 5f4552deffe5a54a1342f76aaf6a1119
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_age.res.nc
  hashes:
    binhash: cfc762012a69f063875356af95d0af90
    md5: 9a3237d6b00c9dd13a30c39422550c74
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 427205aa7edb65a186b1460d28b164fa
    md5: c30b46350e7a5fb8e20e0f8939502641
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ad6e6aeb6c75e729387e75832d66e6bf
    md5: 10174fc3859160324bb526c8ddeafaa2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_density.res.nc
  hashes:
    binhash: bbefb31b4b96a0c9295741a1a92cb9c9
    md5: e5c44ccfec9c4c9cc5d1baf15eb25ec3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cc714ec2dda90db0fdcae2aff3b0d7c5
    md5: 2573c7e64b5959675547995ae6988e45
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 786aff207a0c5dadb0ab88ef81d4db74
    md5: 8bfd20af367ecc0a50af2b2d8f7d6765
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 05c9a5ce5f553b1317682022423acb8b
    md5: 9453b13769e453366cf762e24a8b5cef
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d981c276428204bb08eec5bf81ae8b3c
    md5: 1c8bf74840f4ac782f5d713bb84229d3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 875210747f30b2c5ed86e4d76ac6a139
    md5: c6efc021ee156a31ce6b9b869c897346
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: edf16847f2ba6b750d201c1f625933fc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_solo.res
  hashes:
    binhash: f8531e395d4abebee7e2c8841e63007a
    md5: e102990098eb89be0feafc19934708da
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7df10c2d2e8793c14442a0856d193270
    md5: 58c872c4fb78b3180c947a7ef68f8bda
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c3d6db08ea14e6c5c448a5af2faed17e
    md5: b230c8fcee70ec560d9743ecbfce746f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_tracer.res
  hashes:
    binhash: 9258c6316bb08371ccde4214843fb570
    md5: cb16dd1f5323c687e5480bc823bab08b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ce0b1d0491de6fc93b8fc7385213417
    md5: 9c2e9dc08e1eff057cbc70a235a16eaf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 57815a4a3dc2cdf2848941de03abcd98
    md5: d75a826b7d31ec34311535442e02f62a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cbdc3c6b1c18bd84c53d4ea28d858dcb
    md5: 00b2733a32f7e6b74a8780eb72a1f41c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart386/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e1526b46092f0f491139047f54100720
    md5: 92f7dd0f3dc70d80bc19ea1499961667
