format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/atmosphere/restart_dump.astart
  hashes:
    binhash: e3499e9636233d2934e2035081cdb7fa
    md5: 565b7dccb5d049cf8fb36ba44450ee2a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/atmosphere/um.res.yaml
  hashes:
    binhash: 0dc41efebca54523c86192e9b641f9ce
    md5: 15893e09dcc3dcf7873d048b1a958e4a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/coupler/a2i.nc
  hashes:
    binhash: 61a721aea4ec43363cc2bd3caf4db724
    md5: 00ee59b15465b46dcf15fc113f8cd2dc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/coupler/i2a.nc
  hashes:
    binhash: c71a28997483a77e976853766c1e5d76
    md5: 8ba9081742e5993a919d28cbd8850fc7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/coupler/o2i.nc
  hashes:
    binhash: e5b58dc015dc8047812830fa46bc59e7
    md5: e5a7981299130aa9cd29994097272b5e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ice/cice_in.nml
  hashes:
    binhash: fb9c370eef105c8340e949b059ef60fc
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ice/ice.restart_file
  hashes:
    binhash: 33441828234fa9cad85e927e712eb49b
    md5: c597196a160d1fde7c5dcfbe3663efca
work/ice/RESTART/iced.1741-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ice/iced.1741-01-01-00000.nc
  hashes:
    binhash: 29dc6fbc3b9bf9b1b627cfa33210f359
    md5: 69f53204f3d59637e0f13932d4a46d65
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ice/mice.nc
  hashes:
    binhash: e40fe87ecb21099d3ad73f0aac555f8f
    md5: 08e60f3e67f73cf28bc07b2824095048
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_age.res.nc
  hashes:
    binhash: 4d5154e9c7f17b46248a7d59bd80710d
    md5: e5380098dfc4c4e0cf4f30179ef64ef0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b800f161f43fda99f6a5809a53f9ed0c
    md5: 1158b0be7d3ae93c9215674890c26cb4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f648338c6eac4897f029ef1fabcbe417
    md5: a16d7661137cedc1c3d42a5b2d6410b7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_density.res.nc
  hashes:
    binhash: ee1e308604c368be5409a1f9e960f544
    md5: 49f08961797e2eaac9613a5ac59feec7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_frazil.res.nc
  hashes:
    binhash: dfd109ca686ef5d1bd9b054701cd7bca
    md5: 010e0d2af680015fa162786dc306eab1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dfcb8b5bb9a810c7e4f10e96b7e901b1
    md5: c50d20117746e8a58a97359b87c8e4d7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5af0dae6e2ef8a08f75571c85f86d7c4
    md5: c0036cf4787e1b1c8901d5f36f57bf8c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f55feb122eb15d9a75ba469d728491a
    md5: 5054d8ef4708b1de9fdfb191cf35780a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8e9cccdb04f802098a5fad4e5a332b64
    md5: 663f70713c6325d623070b573742c613
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 89b058140fcd77fc17f627be01d48dc9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_solo.res
  hashes:
    binhash: 36bf73e0f30308ca7306a5de61160584
    md5: f0d5abbafbaec16ef8dc46eb07a9ed12
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c7ce0bbb6badbd97324eeef9d0e8eba7
    md5: 7447b0cf04840d1444feec947206db4b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2110df91935c5fffeda02d04135d62e4
    md5: 4aaa6c03b07bef3a7a84987b9cd6eaf1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_tracer.res
  hashes:
    binhash: 773f32386661ac57a1ff7fdc42c43232
    md5: 403d4fc51f0880c9509d3b973c33bfc1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e01a73396d4a29824159722769dcc8f3
    md5: 86ba9fa18f5731d71e3935368b6e8a2b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c60cd3235e0d10330d838731891aab33
    md5: 199edc2fde7f63cfb01cce72215a6b14
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eec7ca1958cc1e7b6bd7d0304ad213c7
    md5: d60fd6762dbc77308546ca905b61b232
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart296/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: baebbdc734d1585ae4a9bc26748be4db
    md5: 34142285714a687fde0b79f39176dc3c
