format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/atmosphere/restart_dump.astart
  hashes:
    binhash: 13200e3db21263281e0c56263682474b
    md5: 9c4197078ecaaa588e4c48ebb1465a40
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/atmosphere/um.res.yaml
  hashes:
    binhash: 50f5b8744419a45480ed8b70948c81a5
    md5: 97c5cb1fe09884a886524cf7ddf25cd0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/coupler/a2i.nc
  hashes:
    binhash: ee0c03ba44a239086c1d466716c081ff
    md5: 8ba98ebdc24d4a2e402bc5da308957f1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/coupler/i2a.nc
  hashes:
    binhash: d3583363b9ff7613abdeb6b416da0b69
    md5: 6ed2676721d186e6b9a2f1fd1896ab36
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/coupler/o2i.nc
  hashes:
    binhash: 254186c6b41785d024ecbefe546ff6f5
    md5: e826db348b12b8ea391ade6aa43b9e3b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ice/cice_in.nml
  hashes:
    binhash: bc0a40f9fea3960930c5b695fcfd68c7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ice/ice.restart_file
  hashes:
    binhash: 40577ba5b77b67fa54c0f9b674bdf4cc
    md5: 62426fc13c299b2d94e364a71a265b16
work/ice/RESTART/iced.0943-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ice/iced.0943-01-01-00000.nc
  hashes:
    binhash: ae20a0fb973adace4e677aa6ccfcdbbe
    md5: 476aa641e47846d9e30670cd9f3d531d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ice/mice.nc
  hashes:
    binhash: b6ce98e632d7a7a3a70ebf4038faaa8e
    md5: 51d190d90613016d7d1c52fc43a3a774
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_age.res.nc
  hashes:
    binhash: c7674a3a89f2b9bfc11ef127ae347503
    md5: b5bb9d982687e797d2a5c92c10bd23a0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5d658bc6f64fe69e93cf0c27e5093b29
    md5: eedc4388578abcd03b3ed0b4473ac70c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b7c5ce78a06f34ccc2154b3e15f783ff
    md5: 1790ed0d864c9f1833ee2d97a3e4bb03
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_density.res.nc
  hashes:
    binhash: 9009b8c05bc1d65b0652cd9e134f36f8
    md5: d129b38b287d2cd1e2806b0b30948e66
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1d93739d28550d30ea08d538f71691d1
    md5: 409dc132ce9ee7056e39d9e2abf00d16
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: af0f859d1cbc6400bd43e7dae4bc2eba
    md5: c2985b541d855cb59a9ae83a83bbe7c5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f8f4e7fc0768c27109832d3aa075de11
    md5: ac59f2dbb1510cb335eda05a92e75b79
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 320208f25f330da60e9a0fdd65f59e09
    md5: 0a5a0d79a66342632d2cc3b94bcfcfc2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 65d222ac629654abe20787326128c733
    md5: 36d44577387440747e6824ee43e90911
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 245cabacb23471581c171f5fde35f77d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_solo.res
  hashes:
    binhash: de934a2a777b3d832a2fda970ac7e061
    md5: a62a51f15ed6ea80984fd167ab7e654b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c24496dc103dfa0baa6e11572dc6eaf5
    md5: 6126ddd67b66ca9ba3e2d843493a3c6c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d8704a368b9fbf34eeb4bd57797b44c0
    md5: 720956ec6fa13f53578dff4b5c2755b0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_tracer.res
  hashes:
    binhash: 04e01f2930256ea61845bd42bf64f5ce
    md5: 85979388ed3c5c0b341a8c12a275c89f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 47ad7681f4116260e063dd4ea5c9dc3c
    md5: 73b2bfa6a1e81164a86bc98bf246f06f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 729611e7b8b4461930df7ee989f3e58b
    md5: 92d67c9052c1dc53463b63252b84a522
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bd275e27562b21262d073843ca4b8f9b
    md5: 9f9b9668f982b5f6ea6261c8c78dee9f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart389/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0518cc4e321f1b977dc4a34e54c2061f
    md5: 12ddfd7296f759a35957414223a6ea31
