format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/atmosphere/restart_dump.astart
  hashes:
    binhash: 3f72f6c1bdf271b4a26786d0b59b40e4
    md5: d64c534fc920995c7b8300430209891c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/atmosphere/um.res.yaml
  hashes:
    binhash: 5ec8272aed1c8f47a0fb7705028cb02c
    md5: 3deb6171e4b8829801ad186bacc666c0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/coupler/a2i.nc
  hashes:
    binhash: 75475700ecf71abfce7be54c8f76882a
    md5: 089e1049b4e98adb185f708a79087134
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/coupler/i2a.nc
  hashes:
    binhash: 2f73bac9004b6d71f2138c5103980399
    md5: 74f6c08eac9a95226c8318ce259f12c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/coupler/o2i.nc
  hashes:
    binhash: d4578715fcc793668ef929692ae65f58
    md5: 28fb6c74761a9dc15f3467b526278112
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ice/cice_in.nml
  hashes:
    binhash: c39d8776be1bafc8280554dd711519a3
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ice/ice.restart_file
  hashes:
    binhash: ae5b4adb10a339526587c4320b5125ed
    md5: 4ecef54f07ce6e05359a1fcac67d65c0
work/ice/RESTART/iced.0858-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ice/iced.0858-01-01-00000.nc
  hashes:
    binhash: 16767d1d7eb308062d129e0cede13499
    md5: 43ff5cd1667548539edfd42f2b592e01
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ice/mice.nc
  hashes:
    binhash: bc85d9f744d8eee88ac747e6c1cd3051
    md5: ceb3742e0c85e63de026d96fd24cc6ae
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_age.res.nc
  hashes:
    binhash: feb2fcdc29bda94fd6d6600667e8aabd
    md5: 343e5a0393904876a0d486c196047f6a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 18192d8f62f12596a7507c60a816f286
    md5: f717d6f5939389288fceff2fe84cc66f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8744ead07ad5a8f41c36c6110b785db7
    md5: 52af76572fd61d4be58d60aeef30b3d5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_density.res.nc
  hashes:
    binhash: c1dd28021ce9349924db1c9ed931e05b
    md5: 6fb8e86a8f8d9c03da27d9ed7f4134e1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f98d5517fdd935e7758ffe53fcf5a669
    md5: dfdd28b05619b4a13a6460e78ab2c15e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1e1df13f2a0d4995332aedb1b56e9df
    md5: fe97c3219287c505b18298ce65d07bee
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6ee2508956dfd43d2a70f19fa04fdf06
    md5: c1cf7b2fce287f5e8c44e032e6a13bda
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 36b160e31d0d97842a018b9ac242b3ae
    md5: 061dbddef9e27f025148bd2a76892112
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d21b242cff0159d2500d885a43088ed9
    md5: a7487caf28d29807951fdc22d93445ea
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7c7f4716d7a3a46d852057ec71c1ccd2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_solo.res
  hashes:
    binhash: 9c5e0190dcb16b1d0dddb4de72e94118
    md5: 289930a73c35fa1a5353a0ed6804566b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 801114f5d6f502d3a94738aab3e22838
    md5: e02658ec9173a8af38d16f7738e41944
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4996a86f540ec713cce216351d96ffe5
    md5: b1cef7a1dd6097c58850669e8560a049
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_tracer.res
  hashes:
    binhash: 1e75343faa0308174d7b1dcb985deab0
    md5: 29cf2b05b16675e2a039e3dc4c2be7e3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f31d801284ad17a0b403dc2a1cc621d4
    md5: 46d1011dbafbdb346c28e2c8679ea4b2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eda1f9365626f0f793108acbcb435c0b
    md5: c3d5e201bfa34f19569e6849f1d37dc6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7c45ce430c02db879b13619e0b7c1c3c
    md5: 329a76aa0e23ec2b3bcddbe0113351ed
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart304/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 47e89e62551143e86833ae70350e323d
    md5: 7c2577dc6bc16270e213af99dd5f409a
