format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/atmosphere/restart_dump.astart
  hashes:
    binhash: 7c09e8c86ff189bd3e9d0a2cab43ad82
    md5: cd4703523be3fc52d0f1ce87ee9d5675
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/atmosphere/um.res.yaml
  hashes:
    binhash: 01c73e2b809fa4e21c8cc729b9ec323f
    md5: 0cc8ec9d44d5495300e7e21e13502555
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/coupler/a2i.nc
  hashes:
    binhash: 917280012dc62b0351d7d2e8b3a2efda
    md5: 22459ba6e9fb554aff146758125f1971
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/coupler/i2a.nc
  hashes:
    binhash: 2921baf472e04a7dadddb4a67dca87cc
    md5: 34444ac6f10feadaffa8ed0d05d79577
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/coupler/o2i.nc
  hashes:
    binhash: 13187f16ad839037f5ab2776fe9ef3ee
    md5: 8002880c87231dea607aa08c66c36f1b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ice/cice_in.nml
  hashes:
    binhash: 9f7fb881d9d11d2768e937dff36e5efb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ice/ice.restart_file
  hashes:
    binhash: aeb978c6a957afc577b7bfa6fe9ae6c6
    md5: f66866f67de4d76cbcef054372f07b49
work/ice/RESTART/iced.0834-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ice/iced.0834-01-01-00000.nc
  hashes:
    binhash: 536f917224e76cd91713401a18594dd6
    md5: ec1f8f0ed75ba09cf8de2f8e8e19417f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ice/mice.nc
  hashes:
    binhash: 60d6d0deeafa49c6577843e34e585a94
    md5: d3a4978d79cc5a84c35e12af919a6c1b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_age.res.nc
  hashes:
    binhash: a11f8ab349ef028959d4c972a5660f6b
    md5: 23d4a44e1312ab9948cd3bb2a1a2d491
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a16f71a4a51813cdedb6eb327bd465e1
    md5: 75d0c94e5e4634d1555fa852cce6e053
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ba3b055944c78740bceb5837e37e6979
    md5: 61eb29e147dfc99efa48bf921d0984c0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_density.res.nc
  hashes:
    binhash: 25ee50af34ddf33df9920fe8e5cb1011
    md5: 30068532915b8c36951a2394e8e61e9a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 62b721b6994762b29e14bd7aebd2bce9
    md5: 1ba22d155a9cd14a5b7e2939b9d37c92
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 81db73d323d892b4162b61d38fac573f
    md5: efe2986be56e597004162c5b6cdbf0a8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0fe4f3d479dcf23de5f1fe782a235db8
    md5: ff81de739946d0c9b3a0a69201060adb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 69f927718d2fdd3ff4804cb6035983d4
    md5: 6f96532f697e9b9e58434d3bd8e12f51
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 20eb5c3aa4d9622e554a13c366816d76
    md5: 2cef2af84582e57e9e9d9d172f1dede6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 698a242e938f511e938a528cac8dd90e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_solo.res
  hashes:
    binhash: c4c059606e4900e36b6243eaf2fd57ca
    md5: 1b6d34ecd3d585e69c3f77327a533698
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 653ff9cfb84d202d2ad9678f3b3458bc
    md5: 9ff9ef2dda094b22d112c60b028023a6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 647f6d891e8d8c9b26a9b63005a43e49
    md5: b7082d6ae9aada31caf7cd7bc7d91b65
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_tracer.res
  hashes:
    binhash: 5aa64bce2925b685db95124e87a3a04c
    md5: bf963c1aef0143dc811db3a97110e041
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d8776320c919a148d75b1993f5354339
    md5: 9ac0f9e525cec7c9a71b6809ae9e7c2a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 463f88a23930f2cd97ed94006c10e85f
    md5: 7b77168b501a89fc3adcf399d5032452
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7acd681ea23544b3eadb2cdd0f19aa78
    md5: d82d637da9593534cdafc6c7dfbb8d38
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart280/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 64a107492ea11779587ba212faa9aa97
    md5: 7a4a0c8e9edd980234688fab22cac457
