format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/atmosphere/restart_dump.astart
  hashes:
    binhash: bb389f861b2e9fc2e7a4e76d51ab72f4
    md5: 643b43336d320ff71786f25f19ca9f13
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/atmosphere/um.res.yaml
  hashes:
    binhash: 681761d4aadc8cb52a76d5c20f91541e
    md5: 992a57a3dbdbd5f3a1e293b3c15373fe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/coupler/a2i.nc
  hashes:
    binhash: c1b48d66c558d8b1f040e22a01e5f76b
    md5: 280035b1af1ba8bb022f9e5b571610b9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/coupler/i2a.nc
  hashes:
    binhash: 59e6db4711ea1b9c6c8d6169de86b58e
    md5: ef21beb7025cc07f0c72038d53f2b803
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/coupler/o2i.nc
  hashes:
    binhash: a78e53cd1fea5cbcc387d3cce562eb11
    md5: a69f685df62af36a26d151b094e7e7d8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ice/cice_in.nml
  hashes:
    binhash: 0e140c92c7fdcef1639ab414df6f432f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ice/ice.restart_file
  hashes:
    binhash: edc299f7507ac292a4066b890dd8bf39
    md5: b2fa728ef7c2a48bad99e6ded6a72a4c
work/ice/RESTART/iced.0980-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ice/iced.0980-01-01-00000.nc
  hashes:
    binhash: 4d46a8f7e06ecd9eef1ed0d022297493
    md5: 74f8a4f05c6d8b6e3dd4fb8077ed7e56
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ice/mice.nc
  hashes:
    binhash: 567c2c65572a4ba2dce5d1cd05c0b778
    md5: b103774601b9977942c3aeabdae2d329
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_age.res.nc
  hashes:
    binhash: 217eac56160c9ed34ae8edb93aaf20db
    md5: 135f60d3053ab9a2d3f898d6dd972cfd
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bc383f9d8d52881cbe5209cf1adc265e
    md5: 041505705902bd29c6a254e3bc58847e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a34cff4e62074cb2f3e6901e1a81d325
    md5: 9bd32a6481e05eb5bc741fbb0beb0ea7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_density.res.nc
  hashes:
    binhash: 7652a9c34b57d3bfc373d90bc204ad7c
    md5: 0eae77a1cebcd87879dbb66bd7ebcf96
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e50230d939f461f3da11a015936d5036
    md5: bc9f3c936790ec25b05a2959f86902fd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8cc4af4a188e39612c4d5abaee74b0f6
    md5: a43d7e94ba67f3afba8702c508ee7114
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 850afbc33b71ea21607e33de8f3bda95
    md5: 15495b20e1235da5d9823d71b3ed0307
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 483eeb480f407f740cca95541288356c
    md5: 4bfa532904205822d36a7b2122d1da2d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1b13e9623546c89ef813304b1898dedb
    md5: 2b796f62957b81206bc6b8cc999ba98f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 08c932f194c40eb44bf449dfeda47b40
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_solo.res
  hashes:
    binhash: 65fb270cf9ead62bb79baa73b35ba7a5
    md5: 8493e345453f5d61734e17102d1d95af
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6da0d570e5f6587ca9d107916aec4c77
    md5: 40827b7d78dc3c24699520cd96afc780
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 791ec9f00cd4de8b373e00f4d29a5225
    md5: 49da0ad7bf8a4cba4f9944bbb76306c8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_tracer.res
  hashes:
    binhash: 34d7bbbb1c3c76677c65db23b62c211c
    md5: 1d1671885007be08d9380e10aed8d14c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd8a7659df7c8def453ef20d23e6b839
    md5: 17bebf360b32ae53f12818545a47e77a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7b478f9e7cd2cb1a5e03a2138745dc58
    md5: 8e11a7d955430e73e36e1a301eb8007b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 304e31e9ca07aed4aa7a44d70a552cf7
    md5: ac3a685776131665244f6e6764d11e0e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart426/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2d7dce69987e9b04076fd1ac43c875f9
    md5: b2ccbc74ff06021c3a91329b1f2d47be
