format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/atmosphere/restart_dump.astart
  hashes:
    binhash: dc18b7d73ac2981d2c99199844ef9901
    md5: 66f9c208394cc66d7375867601911680
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/atmosphere/um.res.yaml
  hashes:
    binhash: cdca9620455efe0aa60d10943a4e1ee0
    md5: 82f4e640a74fa484e36337d42aa768ff
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/coupler/a2i.nc
  hashes:
    binhash: d6ac3db1871942a5291f6418a7540bf9
    md5: adb508de1e2f278acfdd8594b68c58e6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/coupler/i2a.nc
  hashes:
    binhash: 0a6bacb26f6b6a949b9a8366f86b3b96
    md5: 7bb7eb3f7c0bb7cd92a2aeea61bc22da
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/coupler/o2i.nc
  hashes:
    binhash: 9fbb885688c1a50cdd095694604fdcdf
    md5: fd692c2926233e8b4fbf220eb1105a03
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ice/cice_in.nml
  hashes:
    binhash: 1179772ab7bedae538d994d2be70c8b9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ice/ice.restart_file
  hashes:
    binhash: 3dfc7e2c2e85c731d2eec20164ef6e3a
    md5: 17546959359c2c9a43539e610cd2c084
work/ice/RESTART/iced.0875-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ice/iced.0875-01-01-00000.nc
  hashes:
    binhash: c778f9c0beb66743b4e6536c628e6a08
    md5: b245d92f692f93eba7e34b5e9034858a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ice/mice.nc
  hashes:
    binhash: 07d6765fa600ae2e6085f4e34074e00e
    md5: 4f9a704fcf898dc77759bf388b129af3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_age.res.nc
  hashes:
    binhash: b4e1697fd45fd187cea919861564fff3
    md5: ccbf40a12e7df036245999881a3b0d38
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c661bfad06f1a19b3914106990bd53c9
    md5: 631600bd170e7497a28e1d797d5d039b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4a9722a5582c1f8714ddd76b56b291cf
    md5: 1e188f0104022ff13768d43215ee1b21
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_density.res.nc
  hashes:
    binhash: 079ada263ca0a3c07d1573097eaecae6
    md5: 437b917c48ebfbe32f27219663b46a73
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0d8cc129ec0910ca1e59a3cddd7a1e1b
    md5: e409fbe07186899cabf4f4340e8af2bd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6fb49fbe3abda99b2ef5cc303d02c72d
    md5: efc7892aaaea2729b7f24efdb7f9405a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 24ac4274d99c8b5710f8ba976802a1ff
    md5: 08c91169eead3826d434f1d9dd5a17bb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a065120a64c0cf21f7c14e052b50b1a3
    md5: 9f817af96d3d2259cd9a67db3925e2d4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5f6955238c4dec0788604319f1a2f00c
    md5: 4f639853ccf2185d2a6cdb6517d88b0e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5fd5a77880a50e734056649ebf569cdf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_solo.res
  hashes:
    binhash: 566f724ea9a435f5f1523b22c44e1895
    md5: 5e166f6a6e6d14219381be668af12710
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 981c01bc45befc9f5c1499abd987c42b
    md5: 194df73cf4ca2847a1be51c4795d7d85
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bd4653026ed79a3c26aa9ea349130c6d
    md5: dfec2d65205fa67b78690ab8d2022816
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_tracer.res
  hashes:
    binhash: 411efbee3e55b5658161b755928c72cc
    md5: e143dcef9b089e7c6d6c3f6a6775ed84
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d3509b798ee534db648865d5940d9928
    md5: e14c21b487645ee49dbaad972e73c2e8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3342c6ac91fcb4a4ae5af24c1a1d54e8
    md5: 802c7d56541e93aafb7429b8e3c0fb00
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 735c582d4a9cf2b97092c36fec11c241
    md5: 5e006e2ce30478111bcf5e0c96873219
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart321/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: debd1755f935eb97a2baaa32bad73aa9
    md5: dabd4c8c9a83655043abb75307829c9d
