format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/atmosphere/restart_dump.astart
  hashes:
    binhash: 43004a248ebcea5bfbc0310b50179828
    md5: 84dea395dd111f806519e930d5ad99c9
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/atmosphere/um.res.yaml
  hashes:
    binhash: e041a04b1fc34a35a974df736866fa3a
    md5: 547b0f5e0e57717af56e971bef9264f1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/coupler/a2i.nc
  hashes:
    binhash: e1ff6673fa2d0b855394739cca778f28
    md5: bd16dc5f1e3576474a3a1493f25e9aae
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/coupler/i2a.nc
  hashes:
    binhash: 7c78db603f1bafdbeaacde1c5d8ee995
    md5: c38d09827ed0562da362d409d29a8923
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/coupler/o2i.nc
  hashes:
    binhash: 0d2fd5da1aa728b6bf52cf130e924b07
    md5: 5bbbd8b4eff413d0943426dc8ef4caa3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ice/cice_in.nml
  hashes:
    binhash: 95933d96595ac313e903e1bdbe5e2153
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ice/ice.restart_file
  hashes:
    binhash: b2459c556e979072fc2b1799ffe770d0
    md5: 1e297ccdbdecfca4467af4084ea58e12
work/ice/RESTART/iced.1849-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ice/iced.1849-01-01-00000.nc
  hashes:
    binhash: 91a32acf41e836b3abbe4c858fe0e669
    md5: 8499e7c387e3915a1842e4d52c25e06f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ice/mice.nc
  hashes:
    binhash: 9dae7dec26f8d9ea77ddf6f1cbf0b9b0
    md5: 4b18db619e8b89aebb8e74f61a42e86d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_age.res.nc
  hashes:
    binhash: 0d7fc31d53b1972e8cea241434f8fb3f
    md5: d07dc993fa06c7f2e9cc270ca1ce398e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9d1f20c5f06a05c0754ce3758007d21a
    md5: c1a0e3b8a3657ceb7fa9fefd758b71a9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f0bb8b107fb80c7f13fdbd0218ee8a36
    md5: 8fee1b3a7d7e986c676180c0eb8b5dc1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_density.res.nc
  hashes:
    binhash: 297fd85800593064ae2847f9596ffdef
    md5: 9480ae9f721c93f34b3ac0f594302ecf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3c374adc10b247450cccd3ce34ae5787
    md5: a5518164c8af893b9309eb055afd50af
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 81cc246e9dadb619af85ed29bf540134
    md5: 1a5951eb104e66cf233d178465ce40c8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6502ae61f5c12d56785b2d81d4c7dd2f
    md5: 95bfea0fa524f4d95184935558cc9abd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8312f944e3ead14e8eb42c6f06933dc5
    md5: ae8a203e7f25c4d1159b84929dfbf993
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 63774f32710c79387d0e9c752d8ffa37
    md5: 9ae45be5bdab23ae22b72cf32446cf62
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 99ead5b0c1e506eb4e31f887400ec7d6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_solo.res
  hashes:
    binhash: c011dca44f4935a468734f4e93b8cd67
    md5: eeff1b42c71b4d35e46d56101c08a37d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1c6e45873b7513c7b81371e2d996f3f4
    md5: 472b28aa2b815471918d16659503e5d7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 831fda3b267c40e9ef8e549d3ad3010d
    md5: fe3b34019e5e6e2538bfb52f1938baa4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_tracer.res
  hashes:
    binhash: 79e6e178740f64d9a2b44158248627db
    md5: 0edfb21f3a6a41f58a22c7cb6d208e9d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 89fe28c21e48fd9537dcc589eb18022e
    md5: a6e1740bdfe5a3a4fd1b421d5b0a6d15
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c6d8627b624eea0403c9ee70a0ac2e3f
    md5: b583b895030003d42efc5f7d9fce8f70
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 594c413e607d0f28ce7c2c7c1d1724d4
    md5: 8a7373340820671c6eaf13be21850978
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart404/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b215e3d8dc91b37d2e75119a028aa269
    md5: fadab350816b7b50010233ef4cf456f9
