format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/atmosphere/restart_dump.astart
  hashes:
    binhash: b2dcf9a884f3421c54cdd568e8c29fd7
    md5: 65a65d94d449aba26013befc671e4786
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/atmosphere/um.res.yaml
  hashes:
    binhash: 9c8646c611d960ff75e6bbb6e37c8552
    md5: 593b1b4f066af978a53c36eed34d5af8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/coupler/a2i.nc
  hashes:
    binhash: bbb984a48062f980b70c951c40e00f5c
    md5: 32d3f6d9124247d3fa7c3c2073134d96
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/coupler/i2a.nc
  hashes:
    binhash: 44f5330312f03eaa7b62eab44fd3d75d
    md5: cb72181a4887fd83db1431c5822df01e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/coupler/o2i.nc
  hashes:
    binhash: b712af5bba5246f506e252736b97a40b
    md5: 47ebfbf4d604712081cf180f6605b354
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ice/cice_in.nml
  hashes:
    binhash: 21b1b9248d1719315b02e8bdef8c2be6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ice/ice.restart_file
  hashes:
    binhash: 20b4e6fbc70e7ac01d5f727e9b1b5043
    md5: 8b5ad4983231096140acb7c75ed7e096
work/ice/RESTART/iced.0870-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ice/iced.0870-01-01-00000.nc
  hashes:
    binhash: cf6318c7a51218f295f522164f791f6d
    md5: 26cacb412a43771784206028c6706b82
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ice/mice.nc
  hashes:
    binhash: 04242e569f5c0e72c85825770f61439b
    md5: 8e85eb90a224e6f6a901ce43d14faad5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_age.res.nc
  hashes:
    binhash: d43cb144469dd80db622ff94a26e9f90
    md5: fd6558ecd449fd1b38698082ffb646a5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b51f19dbc90e4d2e3ab221951601e89f
    md5: e881dead4f1dfee769a778e9368d3f99
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a2dd046d598e18e68ea248833b4979cf
    md5: 5dd0d5a8c1b3ce0c227217291e148bcc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_density.res.nc
  hashes:
    binhash: 15d0ef99c3ef3100725f7d0814c81a37
    md5: 9b7418599abe0ba604a7a173c4091c93
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6eafc452b75d88d724dc2d279bb97310
    md5: 8fcdc28e1bc767e6838492883200c234
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d24ed2abb43577aff49d09a5726660d9
    md5: 8e20eb1d535ad6c035e988e2568c7413
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4896a0988468e346e6d88cda10d1b087
    md5: 4332e3d910a3b2f3278d9bcef7b3a315
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d7da78e7b868d20fc0fc4be3a30a48da
    md5: f91297548b2332eaeab53a848e6f8fa5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 71b8ef9763b02d798dcdf81e6ac83126
    md5: 0b077c73cde44d8ef5554266eefa9a03
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bf9c9273508b6d36b9dac365c1d020d0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_solo.res
  hashes:
    binhash: bef9e2cc684564fb0078ebcb6a9164ad
    md5: 9ddc32894d3f30f9f4f4cc4db567034d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 684c6514cbecd76c827333a88f7539c6
    md5: fed154e8ee8f58130b17affe00056905
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a7584866a4b62eb0858bb841af20b46c
    md5: cc0327d619561cfa7180cdfb32d20585
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_tracer.res
  hashes:
    binhash: 3eab99c20b2a762311593d48e41dfce8
    md5: 24c6dfb6cb44ce3026fcb935feb75402
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5bf7404340cbbf4c25572672828aa611
    md5: 9279fb951be8ac7de71afe1d37a34db2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5e11bb1172a10a092b7dea96a3495525
    md5: 7f4ecfab85af48118d9fbee4ce85823d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b02c1c02136609f4b88d6f30b654dbf0
    md5: 62d034011a43b985fca6b681dc2e7558
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart316/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 938197cd7204d2f1d1b5c33205f0fe89
    md5: 8df4bc8a22a80ea94986a01fff61fc65
