format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/atmosphere/restart_dump.astart
  hashes:
    binhash: 31259986c4b53a93942982a66956c7b4
    md5: 3a7c1f4ea209e9dce91be25b3c408b14
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/atmosphere/um.res.yaml
  hashes:
    binhash: b2a967fe264101bd0c5466d9c0a9125c
    md5: ad01579a0c2aacd14d4af9484fb50adf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/coupler/a2i.nc
  hashes:
    binhash: 9658f87ae49faab745309470668828de
    md5: 82c4dae09374dd1fb90433666b698f48
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/coupler/i2a.nc
  hashes:
    binhash: 768e4125da490a0fb13505d032e8ff15
    md5: e40f757d99763a98ef1f86edb88d6182
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/coupler/o2i.nc
  hashes:
    binhash: 83e597a1cc53fef896ebd100932605b0
    md5: 383a0f162c6579d372fcefee6284fa00
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ice/cice_in.nml
  hashes:
    binhash: d788d885df0c30cd7359b301e3b865aa
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ice/ice.restart_file
  hashes:
    binhash: 961d56aa719cbd7aea627dce4f8b578a
    md5: d0cd2d52421ec0a34803bc606686b1e5
work/ice/RESTART/iced.1703-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ice/iced.1703-01-01-00000.nc
  hashes:
    binhash: 67d3a6d4a112a8d9eba084b2b5a97be4
    md5: 57b1c1f33a64ae388c12ae666c473073
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ice/mice.nc
  hashes:
    binhash: 10d135552f6ca83375bb6daa2e6a2f24
    md5: 732c58810dc904fbf1762c6bef91dc06
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_age.res.nc
  hashes:
    binhash: d84178b95dd47644786a8180d75d4cb6
    md5: a75c5116527b664908651966f895b65f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b4d6c6803c159b5e3c9e173da790c9aa
    md5: 972e42d2c2208990da3a18d4f2d0539f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bf2b66c0e20d08f1f95e27dedfb34bac
    md5: 0f9a656906fc6536579cc75969196fb9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_density.res.nc
  hashes:
    binhash: 0cc6ff2542d8e48504aea566c595d13c
    md5: 02d6d710a064b1436a25abf418de91be
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 609f43e5778c6dc814336e6a1c9f3dd3
    md5: 9d74c2d2f42f50fd3bc41df5f5fc66a8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a5e6a2316e096ff2c3ca2d44a414f77c
    md5: 361d02c8aaebd60826ae7fe8a8f05573
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cc908b6d5cf034f85c54191287219757
    md5: 37d0740051a5f000a9bc34f3d8dc3a8a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 54b8b55db32a4f9045f6a2490f2274e9
    md5: 947d34f2a942f3a52c2afe94b79b745a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9780d284345c1f2e998ff62c275fc2fd
    md5: 2f46590351288a6537af79363bb5853c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f1ab2c42eb48c432e3b9149b5166ce7b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_solo.res
  hashes:
    binhash: ce6c18f5a369738baa76f273f4c746ca
    md5: e5151ff83f15f076aa30b66158dfdf6a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6b8fb8f9056e84bcbaee2fddb931898a
    md5: eee7f182c06ab0b1748537de9d24a9b4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e398057673c04007b3359a4077836430
    md5: a29cdda28318c0d8b47bc98087c0d513
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_tracer.res
  hashes:
    binhash: 2af6ec4c76720c64aa873c9298b7d903
    md5: 2ba88a19dce34b22cf0672e1e6e7317e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c4d9f3a2e87ac4561c106226646f2fc2
    md5: 0095e676af586b89c0e0ec946af7eb0a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6d97aae30b40bcefa8062865a4651454
    md5: cc3fb19f9c7f557774c818a794f67050
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d23986a0ab7c8aa935e4a061866b9f88
    md5: fd0605fcc0bffc0daf1d757ee23658e7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart258/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d311bc9fa68bcdccde8d40145f28842e
    md5: c64770efe23a78ba0f70e5d8c64d1147
