format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/atmosphere/restart_dump.astart
  hashes:
    binhash: c7114603cc0d1a8cf9a75b9acf9b3a95
    md5: d53a9a6223744d3f385ee868e5c68fac
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/atmosphere/um.res.yaml
  hashes:
    binhash: 0de5e99163b5b739b53afe062a6e9dde
    md5: 55ae4e8d2497df5bee7f5abe08ddc210
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/coupler/a2i.nc
  hashes:
    binhash: eef99513c0bd882f4cee3327523369c2
    md5: fd4e9b2900d7177e6509144f1696fb49
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/coupler/i2a.nc
  hashes:
    binhash: 5897cb6cacfda807096377fca3d91440
    md5: cc4bd6db78c75b0169320077c707476e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/coupler/o2i.nc
  hashes:
    binhash: 6db09ee626b48e77296c10881eec2ae2
    md5: c7ab85fefc85dc7bfe69ef4c619188c6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ice/cice_in.nml
  hashes:
    binhash: 154592cb5a225da0e8dcc4a9ab85971e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ice/ice.restart_file
  hashes:
    binhash: 682ac1694423de614c11536c79acb0e4
    md5: 8308ca640a279242df0eba7ac2eeee0c
work/ice/RESTART/iced.1264-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ice/iced.1264-01-01-00000.nc
  hashes:
    binhash: 5dc0004bc82f4e958e11baa254ec88c6
    md5: d18caa7b3782fa65b871663d6b3b6437
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ice/mice.nc
  hashes:
    binhash: b6f2aeb346c67af5c2e7d9be3db5c7c1
    md5: f092baa0980443bc9e7e3a4333ed7c56
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_age.res.nc
  hashes:
    binhash: 5de9127aaa7dc89740594919afece497
    md5: 6d4e0f2934f5640dd013738c9018cb68
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 75828cb0666f6c4d644574fb011c2b7f
    md5: 98ed1ee75aa3dd56467c1f8423a51d3f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 10ece3c4e176f182a0be534c0cd9f906
    md5: de594b27ae145a3801fe23770aed0edd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_density.res.nc
  hashes:
    binhash: dfd7dc3b0d8c00601b21fa46e6a84111
    md5: 8787caa751203679beb1362a68018457
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ef1ad26c47774207820b1178889b1b87
    md5: a292500749a33e4cd9c4535a2af7eddb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d55cf8afa857de5409d80838a82ad38c
    md5: 5020ac604863a652821fd11d28a92abe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e712b5f53973457695ad7b692d915ef
    md5: 06f4b25a85c138fa918885d5bb6bc658
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8b03f4b1bffd5c2c2d06ce58bda35743
    md5: e07bc739fc847d0dfa1f3a4f5c43e351
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 21bb9ee7b2cb2d1f21219620a23663b6
    md5: b2d11acfcbaa84899d72ce35b21b533a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6c8b13765db172d40fe9ffa4ce1e3e73
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_solo.res
  hashes:
    binhash: 4a2e229b6c0e6a598b67a6bb8ee92699
    md5: b5d31fc222abe4b059cd38bacc55b5c5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d672abb1bd167a61ad0a38917c43bd2c
    md5: a0332d1fb0d0ff0c76e6b34314f587d2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 476161a026ebb5e968dbf2773603dff1
    md5: cda0e86d6b411e5e029bd84a9ae5a800
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_tracer.res
  hashes:
    binhash: 1992294583cf4ce82a43d7dd60d0e60e
    md5: 6d6b215e25ee654bb83e9591446d52c6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 513985dc45ccbdb67b4a18bed7ec3325
    md5: 0e4e7da5c2c6b777561b128ca19f6e31
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7285396268dd9430ed94fc4b05e6e3e6
    md5: 712b1e56bb246b1c3b9c7892e6b32a59
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ac94f7366f287c3688294a0619940a85
    md5: 0ed1ff671b55c07d948f8268de0476a5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart380/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7449f917e627e752fb2f360d5041df86
    md5: 29d9e038f78759edb32ae1afd6c83c46
