format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/atmosphere/restart_dump.astart
  hashes:
    binhash: 67e513debdf24bc2bede6d16f7fa07af
    md5: 88ac9b522a67a6e263652a61db5fbc77
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/atmosphere/um.res.yaml
  hashes:
    binhash: 882cee48e03f5a43a3df23273ee165d8
    md5: 2b15728b70682ccd0d7bf13623d46b43
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/coupler/a2i.nc
  hashes:
    binhash: 9c8ea96083c769b1e3678877fc50c00b
    md5: 2c6212dfde5630de341f467cef6de119
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/coupler/i2a.nc
  hashes:
    binhash: 49ae32eb4ae10977ec153e213885b26d
    md5: 549f0892cded84ecbed8918ad0a08340
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/coupler/o2i.nc
  hashes:
    binhash: b69dee7e603ead1fae91a78abb06db83
    md5: 1593713b475aabc077cf3a08732aa03e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ice/cice_in.nml
  hashes:
    binhash: 2b352ff23401a683d36218305541ba46
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ice/ice.restart_file
  hashes:
    binhash: ac6602e7aea2afde3a1474e6124dcc7b
    md5: d3353c3e6cfb4b342981df0ccdeec355
work/ice/RESTART/iced.0905-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ice/iced.0905-01-01-00000.nc
  hashes:
    binhash: 0c2cc4a13dffa5022181f7ee94439a6b
    md5: abad64a9a0fa68079fb18934a53de6fc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ice/mice.nc
  hashes:
    binhash: 95291ed198749899a7a728035ba68e4d
    md5: 44ba6dd85dc84bdd57806fb1fde8f206
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_age.res.nc
  hashes:
    binhash: a51a8708c42bb3ee9aaa2b7b696d6637
    md5: 203ba253580de056d0511797641aa48b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 52a45b050186ec79278e03c87450342d
    md5: 33f0e6f05dc7b72af2b794360648453b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fd166720c2e9affb93b1b8bf8363ab8f
    md5: 60ae9937d5075648a109238e23f38340
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_density.res.nc
  hashes:
    binhash: 1db504c4d4d91fb09f7881feaa7eca00
    md5: 20fb97fc0fe6060e0c8253b053fea159
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 41698cebcd71bcec71d7d5a2663d2936
    md5: 05334733ca9857654252a9cac5016e70
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ab9ebedb60a5cb1275f5b8fea5fbd716
    md5: 0624f4de24bb6ff603c2cfa95fe17156
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6ced53a0f09a03190ca6344dce71573c
    md5: 4f02f14fcdc8c8d8ca04af7906f313b0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 16de5d2c24f4f6ede8d58c69234a6fc9
    md5: 0c0a6c565db0a218a1b612d54c591483
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 067493ade6413af956f42f6d0e24d152
    md5: 294f067fe0a51ed108cc3407614db01c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c2be436a3edc8088e2ecdd0f78825173
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_solo.res
  hashes:
    binhash: 6a534b5cf7ab8510d05ed36d2f3ae0a6
    md5: 47f6ee064c76874de2a793fd88c57ca7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c4a0e97569849a9978306ce875804615
    md5: f41e0b6ae5f2b92f0b8cb6ac912b018c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6eb8b071f089bc81687757d8362b0cbb
    md5: bc42ae3e5b406e381a700e2faec60767
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_tracer.res
  hashes:
    binhash: 981a5a2a6a81b470acf6f9cc04cf3be6
    md5: 63b75563cede10050d1ad3b031a382fc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ddecad4c375e9733205d9c5ade7a399d
    md5: fc6a297cd6397d82157e9ff6eb2b10bf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0d6f86e52c26296a043e000d841eec3a
    md5: 5352b9233768a3224478cdefe1ce6b3f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d93b656c66704b61547950712c82cb5f
    md5: aa814c128f8bfdccae67c831a6682002
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart351/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e5a6d31c0912e630f63290b60f2bb634
    md5: 9564451f05fe5151e8d95acd3e2a6fad
