format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/atmosphere/restart_dump.astart
  hashes:
    binhash: c30a1c9b37d7c392f22fcc337e3f4d82
    md5: 9d4e0a3aa9511fccf827fa769fb5771e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/atmosphere/um.res.yaml
  hashes:
    binhash: f861960f67cee97bf0b28e9297a7d6c9
    md5: 340204a5f5aa4348ad553549d539c486
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/coupler/a2i.nc
  hashes:
    binhash: 201bee3ee9bb241986717d5cf7fa579f
    md5: 2ce051055049763bc2aa4f51a4c7232a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/coupler/i2a.nc
  hashes:
    binhash: b01310ca6b63675601549a2a2ba40a3a
    md5: 9bcb3836a0161ed41aaaf050641fd3e7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/coupler/o2i.nc
  hashes:
    binhash: ad5cc7fc6f9563e40974dc030f84ac33
    md5: 281da0b7f6d1b6892a17f37400476f4e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ice/cice_in.nml
  hashes:
    binhash: 5c5d89628ff108f7b9d95a117b3fe95f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ice/ice.restart_file
  hashes:
    binhash: 23f96c85eb0e2dc8d38abaf148153db2
    md5: 079eebc7c47c7047fcaf31d35dde3f9a
work/ice/RESTART/iced.0843-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ice/iced.0843-01-01-00000.nc
  hashes:
    binhash: d6c21352f4e3995dfb9e137fa2702332
    md5: 925157b52c7dd5b99c964a446658d0f9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ice/mice.nc
  hashes:
    binhash: ad9ba8a7b6b9a04dc8588e1be7225a16
    md5: 8937f8992de3badc18d18bc5bc44f035
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_age.res.nc
  hashes:
    binhash: 43449f070054d435d2a1b820face9995
    md5: 317ec1b9ac4e869f1ff67099b2afe738
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9c4922e6befb8737808d8849c82f6b9e
    md5: 697b98698c45a538a9952bb3a1c276ea
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 260d0836e9a5cb7c68ffbe47f73b0f28
    md5: 48b9a3d34b19873ecf812b4c40daeb12
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_density.res.nc
  hashes:
    binhash: 82a2912b538eddb468cc105895d40c22
    md5: 6f8a775a6279e9acd257010a393647ed
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d540a93118312994c7cafe867eeba12d
    md5: cc3f9e3ba3b68fb91a835e0a9596ba73
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8e1357425d966548ebf41ad4eea7b673
    md5: ae7bbfafa2feb0e95abb687f47367531
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 991b6dfb35bc14512c2f6dd2a91b260c
    md5: 243cf0b0b5c31e6d8c69818a6109a45d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ee1a25979bb922df52ecac41fb854c2e
    md5: 384718c5d5b64cc003c52a5d25ba405b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4a7863e767d304452df1429254d06087
    md5: 213d897955db7ec1e6ea298d7117ba96
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 46a9e775ef60950527a75984d78c9eaa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_solo.res
  hashes:
    binhash: fb99b608825894077d338ce4fce54a92
    md5: b16aaffd62556fe99d103fb758896f8b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3383921dba7ec210f2785c607b86b1cf
    md5: e0a52dd64be593c949949b69d0653f4b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 31f78ff66cba8e7a94d6dc722e8cfcd0
    md5: 7d2584a1899b376f191f70405170aef2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_tracer.res
  hashes:
    binhash: 5ecd6094cf543e124bcd08f62ef68509
    md5: f852eeb1c0e524221f5adde3d3b92dbc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6527da55baa7767fbc72392e0e0f1bad
    md5: 046405c7b348d5c3c097f7c698453b86
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f77a9e36aac180240589cfc65ddd013f
    md5: c58b36196347d966a6203f9f899a1349
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b99128973a2cb1f30a20d29038bb9713
    md5: 7acb480d440931ff56425a128ac26f68
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart289/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: faa7bfc93dcbf92d0ae4b11cc062ff7c
    md5: de5752470075612d0262c63182457f16
