format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/atmosphere/restart_dump.astart
  hashes:
    binhash: 8cd78f4f24d362a2bc5482b774d3a249
    md5: c21e676e82a0d04d4aa2ac9ddca7570b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/atmosphere/um.res.yaml
  hashes:
    binhash: f5f6ab7c25a233090e2d03df9de77402
    md5: 77785c2152530863bd2c2bb94a8dae12
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/coupler/a2i.nc
  hashes:
    binhash: 1045dc92c0900d94e0a623b8d948bf82
    md5: e7c7e2cf3d026db780aae8a6ea457e4b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/coupler/i2a.nc
  hashes:
    binhash: 01a8c6d9b200280f317ccb5d944bcfd1
    md5: 17d3698a256c0f0bdb9c331afb20e3bc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/coupler/o2i.nc
  hashes:
    binhash: c8a6ffcb2b15778721e858a85eb828aa
    md5: 3e1a25c64f8195480552562572ab6998
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ice/cice_in.nml
  hashes:
    binhash: b218e075c7a0fe5d35897cb8eae99328
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ice/ice.restart_file
  hashes:
    binhash: 4a343961e705fd267731cc55abe3fdbe
    md5: a51597cebb45da2b28cfee1f9c536fcf
work/ice/RESTART/iced.1734-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ice/iced.1734-01-01-00000.nc
  hashes:
    binhash: 97b2d083b581d7385e085b8d33f3cdc3
    md5: 5bad3dcee50103ea2dcf8a01244d08d0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ice/mice.nc
  hashes:
    binhash: 76e2a9066a6ada94b5a814c6ff37a540
    md5: 0f2d4af51a85756b823b005ab50ea7b1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_age.res.nc
  hashes:
    binhash: 2572f0531dfca5655d9789a7371b409b
    md5: e4c02758619d323e50d67e7097b16082
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ff477df437077df8fd6794084b28f881
    md5: 08cc775fd3ff92e93f2a7ca60d8a97d5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5bcc0445ecedea0b545901e7bb444dd6
    md5: 73c62cc55878a52dad3aca4a4f87e0c2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_density.res.nc
  hashes:
    binhash: b79008d0939166e69cfe6dbd661e2bb7
    md5: d51ece36e9c5012d904cd621765049a3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2540c9982442555a2a053b1d537ed222
    md5: 6fbccb2106028ea283fbdcc022db9e99
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 031bbeb2e38d38090b05fc472de5673f
    md5: 74cb23f8e9619d5d4b66fbe8fc1d614f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aa55598a8dc56c37d400b1cc3e2d9cc9
    md5: 0f6bb9a644472a207afd99cf61737365
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bdf21d7eea512199e0278346a5db9728
    md5: d28abdd5c21c44e5096bda343f40dd65
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4f832c6a5d706b739314287b67077cd3
    md5: ddc5fe1956e2d946fd9ac98f712af0ff
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 49e5790da1047ecdaa2e62703f98d9d3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_solo.res
  hashes:
    binhash: 49c0a162386d58d4029e3821ed123f33
    md5: edff7743c7742adf67ad25956792872a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d9843c0411a78baab58bf291378dcf7e
    md5: 19aa49d131e96fddf7678d3af9dc01db
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c0f964965387a98c77759a6b4cf6bdc7
    md5: cd4065676b5b8b0b998f134816eb68a8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_tracer.res
  hashes:
    binhash: b4b8a51004d9e4f6c028886bf30a974d
    md5: 5efef1939b979c5f68870dd66487e177
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5c309eb51668747b93c8cc1a8e0cd59c
    md5: 79cb9c9a4a588ee34ddaab5619b7063d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c296a83b2bffdb6f5594bd330c37e4b5
    md5: 407c37719e309dd63050e7c1e59ef1c8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c38fa9659656ec162c8e85b30885e4e1
    md5: fea6f01a277180b33b38d49bf977e2d3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart289/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2955913b64a2f2f60cd21ac428629f77
    md5: d4b5e514d4be3ed7fb148bc1d5468233
