format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/atmosphere/restart_dump.astart
  hashes:
    binhash: 9584c7eb2c6ce59cda31d27b6c8526f5
    md5: 8f93c116838dd2511703683d155cb730
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/atmosphere/um.res.yaml
  hashes:
    binhash: f777a0efab57a71103b35c92aa9459a1
    md5: 5b73eec013ed1ebd7b9172a7d472b7cc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/coupler/a2i.nc
  hashes:
    binhash: 8356bbd13555a77a0416ed67a9354a13
    md5: 45ff5c49c05fea52da5490ad8ece46af
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/coupler/i2a.nc
  hashes:
    binhash: fdf35eeea1f3ffb78730b9e29994d90f
    md5: 19bde532ebfb1fcd604ada4c80503888
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/coupler/o2i.nc
  hashes:
    binhash: cfc95709aaeac457c21ccdc0eaa07e31
    md5: 489c87e2d9dd00e52cf7a0db42d95dd4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ice/cice_in.nml
  hashes:
    binhash: 77686c45bf2d6d92b7afa7fd5ac6cdbe
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ice/ice.restart_file
  hashes:
    binhash: 532485b0f3fc9e407ae6d79adb214457
    md5: 11fd66170c15aedb1e7ee9be575d54f1
work/ice/RESTART/iced.0945-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ice/iced.0945-01-01-00000.nc
  hashes:
    binhash: 85661a6e9990cbbeddad6b97d61e832b
    md5: ad1d6c00c2cd93a1481958d46ffe114b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ice/mice.nc
  hashes:
    binhash: a47d3f3f24c358759b0b4dcfad803a8c
    md5: ac2d1b2ac457086d9d33cf3c0b6493b9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_age.res.nc
  hashes:
    binhash: d035484e5a8a984d0b3d45b2c08ccff9
    md5: 48d2fbbb8319f2ed7f4944acb7be0abc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d5c0c7d101d3ae6f62af54fca63fe592
    md5: 36f2be4e3e089c88c3785f51b3ab2d88
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ee206562cd1440f74b443c7ce94568c8
    md5: 6aefea2b490b388bdbe382fd66d45d33
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_density.res.nc
  hashes:
    binhash: f1cd85d1800e1db83a6506ef3aa8a07e
    md5: bfc5aa9795154e55c27b740a0dc5e30a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3c811ca9f61f307c8ed32892b00c8297
    md5: b42369327a9943db24600a4ab298bfc9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 47bb3a7e12900e2578e0b54eef54c3a3
    md5: b3f704791118a50acf3733c72b587106
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5563f9f69817aed41e21f20189bba1a2
    md5: 9a5038495d8b89b095cfc702f8852e56
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3c1fe76d22c7420b02f4c5f82853df08
    md5: 33e7ca2cd59c38eee9dd056911b5931a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 16ee7683182d08abd8177c04cec41b96
    md5: c3b6035b9f64f4cfd8aebd17a995e70c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 36c43c95f35772a6f485d11ef03a25b7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_solo.res
  hashes:
    binhash: 8205b9702320251bebc5db3b686aa91b
    md5: 4dc2653d2d9747f06a3d3c8830b3e5da
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 86f5242f664a001aeb8b0400fd9b2b33
    md5: 17f5f90fa4729b9a3203517d79db8e30
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 973bb36d11491de90b19a0e24ca5797b
    md5: a948faea0417f93432fe312e2109aad8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_tracer.res
  hashes:
    binhash: e1f12e72e2224440bb50c029687086c5
    md5: 3beb571d5cd42eca08f703d7781b5000
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4750471366c435c50c0326238f0105c0
    md5: 715321e1b91967d7cc24299c5c202320
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 58e6f1689496511443cf3c74228c28f2
    md5: ce772f22b7311ca72fe00cab46a6056b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b8a72ec732384ac4e8a601322028419a
    md5: 9d0bf00cd525bf2bb6529952f8efa252
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart391/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 690f869f43f5cccf0231a58ea7143c88
    md5: 197614001567b01691dbd90027a7522c
