format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/atmosphere/restart_dump.astart
  hashes:
    binhash: 88a6f36d2837c5afc5495afa736fc37f
    md5: 6d16a93917ba33a795d9a708978fc08a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/atmosphere/um.res.yaml
  hashes:
    binhash: 156a76dd5461e9d8400c365e2d92f47c
    md5: f1ffa9a874d5acbbcf766c71d196570d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/coupler/a2i.nc
  hashes:
    binhash: 2c8d99a4e5ccbd8147e1694c89738b68
    md5: 167b6446c9783c674c4bda66ba3adc9c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/coupler/i2a.nc
  hashes:
    binhash: 0cb93039db4ae74aa2c28662e2fcc211
    md5: 664763e8d5edd3cdcdffef05948324ba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/coupler/o2i.nc
  hashes:
    binhash: 0d8f637196fc1cdf613d21caa3ff012b
    md5: 68922a2db4cfdf8bf0719fc6624d4a90
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ice/cice_in.nml
  hashes:
    binhash: 8936482e24bbab09f159621965a2ae23
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ice/ice.restart_file
  hashes:
    binhash: 1cc762609ae7cc1ef23cbce688764701
    md5: e6f68d5f39c5a68f1f0e12cb281095c5
work/ice/RESTART/iced.1211-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ice/iced.1211-01-01-00000.nc
  hashes:
    binhash: ec76aa48b9bca5379aebf0af0842a1cc
    md5: 1c45ccdc1c523f05790efbbf53f7a894
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ice/mice.nc
  hashes:
    binhash: 0f15aed5b625b3695ca0aeaa1a0ab791
    md5: 5e498b08e11a5aa356dc6672ff1aea86
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_age.res.nc
  hashes:
    binhash: 9042b05857145dee29a418dea07c3a22
    md5: 53c1e0d5476d9b36ed3439d5ec8cf802
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e884e37201a4f7c759e6b04b1a209609
    md5: 13baf6b2f6d0638cfe1755366f6415b6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 31853c9f852ef1d68d058205e4d0f08c
    md5: 349870586ac4b9bd4908d106f8985d2d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_density.res.nc
  hashes:
    binhash: 9940445b303fb35fd4b82388d958c5b6
    md5: 3aeb39b4dd9f7203c0b2dd4ed9e27e4c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_frazil.res.nc
  hashes:
    binhash: baee1f53a530566b210666eb73e5f660
    md5: eefe1a1e6335a7d28abd15d6f3e0fd5c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 22650285b638bc02ed4003edcd9f2d44
    md5: c237afe3d6dbe6214f04c22d3a9ea2d9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 791815ce1344e237f3b94d55c25e9732
    md5: ee6ce7429ca67a59c0051951551da2d2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eba6370d1ecb174624d1b0f74bc1629a
    md5: ab025a13fe0eec3334aea3398f539e99
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dc470f1938d6b36dec52187cd6221948
    md5: 459e1b2e166b9dcfd6148c4791b7f920
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dbeeda1a6150cbf5c028cdb80cf9f26f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_solo.res
  hashes:
    binhash: b8527f6e863b2c9d31b199044736d261
    md5: b8572001ce536ecd3555d0464af6f664
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 07872e4fc002e31c17fd5eb6522687c0
    md5: 27830eceea2684d4d0c445dd3cf84a13
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7bbaf3ef22d7d96473c543a16335a1d1
    md5: 1d636a70d8440473fb8f8ea1fb8c4e7c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_tracer.res
  hashes:
    binhash: db74fe1eded242a1e0b450cc1fe51e7f
    md5: bf2d5e5022a75eb51b2ec2e4e9133d68
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 38f396fc82389a0c7eb9342c0ce8f18e
    md5: 51d8e9b8e33c1c6b71e7d35998423905
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 541cf4cb6c67a3d78af9f2da9d85f083
    md5: 212ad06e13365930885659c9f66601b2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f968de8e6454dd328050a74a0f8d1556
    md5: ffcee9db267b2dae915c4523fb090377
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart327/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e9133ea31d935e6657d42ce5ff804459
    md5: ad77640e0ea835c7fa9a1ba3a161d60f
