format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/atmosphere/restart_dump.astart
  hashes:
    binhash: d53eba1bf95a4315b157010923172fbe
    md5: 28a6d122166caba594644fb8ff60e314
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/atmosphere/um.res.yaml
  hashes:
    binhash: 79216c25a76edff4096f8a35ade1d094
    md5: e54bff03f949819557b4142ead42fe08
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/coupler/a2i.nc
  hashes:
    binhash: ce44aaca523e752e186bb38cc53322b8
    md5: df974d2d63d6ba404f9fdb97c3b71d93
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/coupler/i2a.nc
  hashes:
    binhash: ba023cabdbbcf01a6eca33d688c05440
    md5: ff6aea17eb3642324fd1017911af6ea5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/coupler/o2i.nc
  hashes:
    binhash: 807c6d83b85b02b9f1e0300498eafc19
    md5: 62d4326061f9d5bf17b647aa8b873ab2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ice/cice_in.nml
  hashes:
    binhash: cb17d18cef7f7209656cf22bd073d474
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ice/ice.restart_file
  hashes:
    binhash: 68b236025541deac9c14a2f7af06abe2
    md5: 4c379f0cd58d6af3d4abdafc5bba1728
work/ice/RESTART/iced.1854-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ice/iced.1854-01-01-00000.nc
  hashes:
    binhash: ec48a1b06d4061ae56f253d461dfd77a
    md5: 14e50178228115f110fa56ccf93e402e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ice/mice.nc
  hashes:
    binhash: 37cae3795e24a43df87737fcb72976a4
    md5: 685a5c0f9173c3e10c55b33f0b9a4234
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_age.res.nc
  hashes:
    binhash: fc3990fd0de11b512d54049d56d35ed5
    md5: 8a11f31d911197f3e9ca005dfe4a4b5a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c3b20f6b9ed5527cd9aaf215bd8d0449
    md5: 210f402d5cb58b9343825527a14cba54
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 44baaeea49833746cbfb1104297d4c4d
    md5: a398b3bc812917e6691c7f1932a0a661
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_density.res.nc
  hashes:
    binhash: 738ad23358297f49f3f8124b905d3a5d
    md5: 5c95817c23ed379618f1c76bb17db444
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b1ebe1541e915b13f293f34b3fa57aeb
    md5: 84d97dc1cca21519d186baf388f8a51d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 176ec09e72e113c3c3177ecdba9e60bb
    md5: 3c420febf56b305f6b19f2e0ac8860bc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e1b89dc8153700e29450d2a3cd515a3a
    md5: 8e2b1b85ad971a25b61588dcd1b021e0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f3f7e448b7b454fc795e585ab76f0915
    md5: a5f2cfe6ebdfb634b8b4ae3d0286a89a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7b44a1c9292e4bfb084d41f9769d5a03
    md5: 9eb3247d8de17f674f2c74e2317df79d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fe133f0eedd9bec33564dea1a9eff2e8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_solo.res
  hashes:
    binhash: 829a295395683ebd7263f9ff4d385b9d
    md5: 51441ed419849aae08043a789718f792
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 07747c5331e8fabe60b9ed65e0f976bf
    md5: 75027d58ddd1745f5d7ec0e1dd897ab3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e484248a0730dea247e5b782a394897a
    md5: 9ea0b5a1aef01ff5c46f52fdfd2655a3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_tracer.res
  hashes:
    binhash: 6695f1509f6ef82bee798a1b0428894e
    md5: 955c44fa5bcf2accdd902b4ca0ff6a43
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c2be492b7db055afe5227e20c5b5d26e
    md5: d93ac1c60bf0adff5364c95514b61b9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 03e8de2609df96f8ddf84cca1f05749c
    md5: e1a1886008481423c70d8305b008882c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cd7a68b7a1e505742027f80ff61c92b6
    md5: 079fdc991bba8b5fc31834dc0507b4b6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart409/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 99210f8df90648e9f0c0bfcd2333436c
    md5: 838181198581eb8054186abe70433769
