format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/atmosphere/restart_dump.astart
  hashes:
    binhash: 9a7c7b1bd93b5282b65d063893589d14
    md5: 3ed2bc543e2e91998950b0a81ccc4a79
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/atmosphere/um.res.yaml
  hashes:
    binhash: ab58f5c3b59c394f6c1adf0268eec875
    md5: cf03d72cc0d83edbead48e4da32594b0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/coupler/a2i.nc
  hashes:
    binhash: b7dd4399a445cbb5386d60d77af9bfa1
    md5: c60decc9b375e22660a5273c3127a5e4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/coupler/i2a.nc
  hashes:
    binhash: 26fecd76afec21cc29998d27836d5130
    md5: 86f4642e25a745f4c8dd88e77f4a557e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/coupler/o2i.nc
  hashes:
    binhash: 1f0678bcba8f7cd6a03e36ef32faf748
    md5: 2eeab8d051d7a60b0acca5ff318e5832
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ice/cice_in.nml
  hashes:
    binhash: de893f506e721e86a8c16369e5d8c341
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ice/ice.restart_file
  hashes:
    binhash: 3faec35cb45e72a60b2268c0b2019aaa
    md5: 6942f58fa699264752a8701b0cef917b
work/ice/RESTART/iced.1182-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ice/iced.1182-01-01-00000.nc
  hashes:
    binhash: 775e47f147f8c47208761203241de8cf
    md5: e3946059613930e7960139e5771ce70c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ice/mice.nc
  hashes:
    binhash: 9500b76a84326fffd8a51db097ebcd2d
    md5: 71a7fd7b1e351c537d287cfec22dc59a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_age.res.nc
  hashes:
    binhash: 0d5ae9deb367d1820604067e81ca73b9
    md5: fb64ed0eab978094c9672ec94d05ab2d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d3cd8a3f0ec949a71eb1b643a08d5dce
    md5: 3835418456b3d8eb397d7b1313ec4d0d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9bd881cbf63e7cef22bcd3b6472ea8ef
    md5: ed3db9acf6cd645f3c0cae589792870b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_density.res.nc
  hashes:
    binhash: f7b77afd5a7d581ca531070a420f0c1c
    md5: 327b64596eaca52ae0f7bd0e9ac92fd2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2a75564850b8f725a1c8cedb42c601e7
    md5: 369b363a7c1bb046b92cf8fd285ea559
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e941147056f0a7393081c96092e354b3
    md5: 74258caacabf892724ceeb862a9abe9b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ef7026665491e8af35add547263b0d3c
    md5: e48d91195fa170d9f965bedd322b2b23
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a38db4f44c7519c7394630481be50e36
    md5: 34df5776f14907bd33a2cf1fb2155885
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0b786662c626c3549a214585e9b24a90
    md5: bac3111a102acfbec83ca6bd5b4e3506
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d567d1edee21bbcf35abc517f13a67c2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_solo.res
  hashes:
    binhash: 705325bfe86d34b1c4938d3188fe94f1
    md5: 9211ab1d953eeab3561fc124d462ff32
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5b223c2a7bf7244bae1457bf333b334c
    md5: 9b5f808eff743b9801ecde25ae1d434c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9210fc2c15d97c187a2152097b0ba42a
    md5: 6ecc180c10b5df16cce00be8da8256eb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_tracer.res
  hashes:
    binhash: 85f4c0edf9f4549e4ef50d215d3c7bbf
    md5: 1f1935d19d84afbb3e50acf0057d1341
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3fc92206fdbd12566064ed6618284304
    md5: b23ad99a00ba7259e1d84d5b3661d801
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ead83ea0aaf8659e84f08f93b3911ec9
    md5: 6032037b1ddcb0bdabbc653127f879fe
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6b5334ce4f33dac712f7c7d4c96f1769
    md5: 1ca6692e5fe668f9f77dc5044569a179
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart298/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bf1be1a6cdeb02917ba089ba8c80f046
    md5: f11f7b9db37a1b8bdaebbbcd63b95b3a
