format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/atmosphere/restart_dump.astart
  hashes:
    binhash: 22ba3bfbcc1bf0105801e4aa32a2bba3
    md5: 2ee0433f124e8cdec333992df9902104
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/atmosphere/um.res.yaml
  hashes:
    binhash: e906dc3a9c74c736bd8dd67e52d4281b
    md5: 4483297220d41fd88bca547b82de390b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/coupler/a2i.nc
  hashes:
    binhash: ee48932528a912cbf52cb4a48267e4fd
    md5: ae392f93b8b58e528f2c97a00280f152
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/coupler/i2a.nc
  hashes:
    binhash: 9c5edb7e1dad4c2b8f3e6424f3d08a5a
    md5: d8d46e92b86bab088dc1b5d8e6cbed98
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/coupler/o2i.nc
  hashes:
    binhash: 6ad40e5f7bdc4cf56d7356d0d4546f0a
    md5: 43d134186e1bb9f00f1ef275e3f74990
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ice/cice_in.nml
  hashes:
    binhash: 947e51744925b19bf378afef1a973469
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ice/ice.restart_file
  hashes:
    binhash: 364b8f35ad92d42198fa0102a2b93225
    md5: 958fa044c6d324cc0ad975309470cdc0
work/ice/RESTART/iced.0976-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ice/iced.0976-01-01-00000.nc
  hashes:
    binhash: 06f676c5746250ead2b32777b1581582
    md5: 517e20297da51530f39bd9368c5ea4b4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ice/mice.nc
  hashes:
    binhash: 5fbea618212ad821aa6828939f8f278d
    md5: a1b3f967828bd0668f2361222f3c4c17
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_age.res.nc
  hashes:
    binhash: 76bfe0d0a46b74b58c3556dc888b2d00
    md5: 57025fe8a125d8cc04267d35f296f2d7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1262489771179aaa54064ed03e5654e5
    md5: 3b9bbe8c95bede4e8bea2b7b102111bc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7cb2789d33dfa8bea6b8c5f025c23888
    md5: 6e43891c7a4b593ea3d3aa620510b154
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_density.res.nc
  hashes:
    binhash: db7875e47f4bbe684a2711fa10864a7b
    md5: b5cf62cd8ede06a3b1673039e7260943
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4752745052a09f0e69c5958904824270
    md5: e193d175cc4b0fb206d25f641015ac63
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b43a881423ba614a498ddbe1f4dc8618
    md5: 920a94faeded16de1ac97e50aa2e7ee0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bd4a8b3d0e4b29c9621d143c5fd82ff6
    md5: 9920b1f8fb7c771760513abc84db8567
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 566abf2d4d50828b22d06e3e8cafc738
    md5: 5c30ac74f36679b01ab266015de07e62
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f16f882157fc5fcdaf11962dc30e1ef0
    md5: f05a3700282882019e65e0e62ce9b23b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a3fa062fd869b627c0e471e2eae2f666
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_solo.res
  hashes:
    binhash: cab97cada27da61a47dd72f27afcc252
    md5: 72fdadfd2933073972baff1e104c6cb1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8351b0c6e07ccbb304012815f8b3c2e7
    md5: 88c2f8d0f5b22d8a01e0d2c9e4735720
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b3d47b25c9e3b311dc9cfcad0b15cfea
    md5: cdba743d33bda6d272818fb7651af903
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_tracer.res
  hashes:
    binhash: ad989ca4ad7c3d77c59491c45d76915a
    md5: 6bb1a7825c91e96406790cf9cd7e4697
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6e582e10988f6f574388706964ccfa8d
    md5: 1c1f8fe8e33d578b908bbef65ea1bc77
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f1300b2e154d3cf2c9096a5abfbbf3cf
    md5: 2622518cc7b1559af38a89d2d4c6f5a9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1e3235670c724fe2f3a3369498cb5518
    md5: 19f52c25da96b72b6960b5bc11021573
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart422/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: df77b6c2efcfbe0d0a8d1863dc986096
    md5: ea742c66a918079a1462a83172290229
