format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/atmosphere/restart_dump.astart
  hashes:
    binhash: 011594a8fabdbc527f4f8f20e0f2218d
    md5: 67bc4e63630c8be10d2f2ffb6b7c669d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/atmosphere/um.res.yaml
  hashes:
    binhash: 51ceea1496d9226f7c51c48dc99d7ece
    md5: 9fc5eceec56eb82062c604d125017d57
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/coupler/a2i.nc
  hashes:
    binhash: 480b0fb93cca4ff526cce842c8906264
    md5: 5e75ef97e96d934240961ad855e1bc6c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/coupler/i2a.nc
  hashes:
    binhash: 7b64415886454ae212241ceb5b212a31
    md5: 65ce5a0ddfd907c7a74d46e0b9636b89
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/coupler/o2i.nc
  hashes:
    binhash: e377f7e950ce0a39ac1db878306724e2
    md5: a1486729532e549ef0c8645930b422bc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ice/cice_in.nml
  hashes:
    binhash: c3918630ad42a9992db7c53106612b9c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ice/ice.restart_file
  hashes:
    binhash: 3d784c38c9c17f1dee3f6b7a4c767879
    md5: 190d10d0d72a6b57f7704ec20b0b85cb
work/ice/RESTART/iced.1237-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ice/iced.1237-01-01-00000.nc
  hashes:
    binhash: dfd21d7389afa24b8f5bb9f52421c58e
    md5: fab1181b031ece23c0d0fff4d6d51cc3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ice/mice.nc
  hashes:
    binhash: 6791fff7c2cc8ef1d55dd8be73cd49d2
    md5: 4ae5a922c3aae1b2dc5b8496decc0f96
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_age.res.nc
  hashes:
    binhash: 19f63579c3e1038138c1b31dd8342cd1
    md5: 3db30fa539d4a616d313234d7b866b73
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: be851a8692914dd47152a9f029b7ab4d
    md5: 952e4e5bd347d4a91f99f9d0b0496c7f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5210a20ef09aba24fc781cfc80bbe72b
    md5: a90efdb26e8442b8997a6fe09ca17840
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_density.res.nc
  hashes:
    binhash: 9e864df801c9466a6f2e3ecdf19b3eb4
    md5: 745de25401f6f4977c9ba01dc4bde5f2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a0459b4a5b23dabfdabf655546fca358
    md5: 97f400df13d0d986b36fcb701d25f914
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e69f4cc3ccaee521f57ec80dde59304c
    md5: f60225479e55cf219b2b8f8b847f6fe1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_neutral.res.nc
  hashes:
    binhash: be2b24978578a59e6fd432c0eafa3f05
    md5: 548d56b2835205a55acec3bf89aa7b33
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 07f8ad278a0496eca7e14e8b59d74639
    md5: c9370146f30cbd08b2ef631019ab90b3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f273fd17ef882b31eecc39fe5b4cd350
    md5: 6f6917b14227325eae4220cea923536c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4c733a49c0267d1c9e4c6b5eae03b0c1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_solo.res
  hashes:
    binhash: 3e6b78e97e03414ecbeb7760f200bb5e
    md5: 9afd9b3f2988a36c14f1efd57319bcb1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 76f5db23a399c4400a2fda3c4f7e9fca
    md5: a66d1a9c1324f321e9b92a4d59cbacd9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2e15bc659ac2dfbf93a2fdd264311009
    md5: 7883a85f5c5ca5d3e073420c4335d4b0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_tracer.res
  hashes:
    binhash: 7f2f5a55f943e730f829da60f1123d6e
    md5: 1d8d8161769e74ee7fdbf3f2146e567c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 536ef3372880f1c713aa83bbd88d306c
    md5: 55a893a3c95f809132346b49514eb3bb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d583c8439bb46f8c22dad6058f8d682c
    md5: f85cb853f547c3b84706a066e744671c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 692d76c758d998286f87288d73a7f8e3
    md5: bab1625efe305a64c4e7003f9280ac6f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart353/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e6cc36c260f2d5e979455d052da06b85
    md5: 4b434326619d62c05e03323933cd2ca6
