format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/atmosphere/restart_dump.astart
  hashes:
    binhash: dc4d6be81daddcbcf81b5a77fc90b433
    md5: 7cec8b6bf6997940b2c808775e80a90f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/atmosphere/um.res.yaml
  hashes:
    binhash: 4e9bdd8fc0515e25b6371eb345743ee2
    md5: adafd9b8682ae7394e11442e424d9e16
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/coupler/a2i.nc
  hashes:
    binhash: fead0d504eb6a0ab880afc0dfca3952d
    md5: ff623d9a32b0f74e65ff01a56159aee6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/coupler/i2a.nc
  hashes:
    binhash: 7aa6694ecc9e5b88e06c0f5af9751781
    md5: 0f0983f154d0ba217b3681f5248e1f34
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/coupler/o2i.nc
  hashes:
    binhash: 12c90458395a50130092318342fbed06
    md5: 839266f05af21853bfad71604f4c53b0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ice/cice_in.nml
  hashes:
    binhash: 14e938560f79bf7b4120dc36603cd689
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ice/ice.restart_file
  hashes:
    binhash: e42ccf464ebfe27b18b16d6b7ae6fd20
    md5: aa21f9a4d94e2639d60d52d86fb6bb37
work/ice/RESTART/iced.1183-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ice/iced.1183-01-01-00000.nc
  hashes:
    binhash: 8fcc630d8b99c774e5eb7cb10858bfa2
    md5: cd77ad3c6ed136b39ce335567ff8473c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ice/mice.nc
  hashes:
    binhash: 7e57da5b2a30f0cb1f01fb304ae02a4d
    md5: 8b2f854c4e569eb91cb82508bc65d5b4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_age.res.nc
  hashes:
    binhash: fc980239bb170596e3cc47f18426d07c
    md5: 9a5587d17385b48e0040504e9d1cc82c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a04e12cf345ca64317d71b121a683a9b
    md5: ba83adabbe517ccca876d0e3b48ca8b1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 861b93e77f73dcfc2b62de5690931f1e
    md5: 7f529b89d72c828cdff74167f96b60cf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_density.res.nc
  hashes:
    binhash: fa13690e9feef74e7800daedaf27d731
    md5: 8a6354c46d65b87649132b1010be6f46
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1abc46767fb6ec1a46c8daae9f5ee149
    md5: 540b0e7cd2ee966adb0afcdb3602e274
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9ed2b7145ad2974987341dd459e3f8a8
    md5: b381f48dc7a356c0ec118fcb3d1a38a5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e8feb44104bc46e1caf3f98e524d5b21
    md5: 90fc1266d8eb2e1b4f9339bb28999bb6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: acb88b1e266aaf032ab905bd121577f4
    md5: e57c3e0445d930a3bea5f60d21bd2c26
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 05ce2b32c775613e30626782b5d43c50
    md5: c50be0b1b2d51be439b0e232bace0658
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ecb5ab6d41eae6efa87bc116517e2455
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_solo.res
  hashes:
    binhash: 63791dee3837e2a656be2dd39edd9f10
    md5: 440c6a4052800eda61673986d4012014
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 355247c144aced18733760cec56ad1e9
    md5: 249a3d30c4f3a41c91e5debf61c24ae0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 50c2e9a78f55ea67bc32aafd2d32ec95
    md5: 8af860d74a4b9cd3487becc8495ba3bd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_tracer.res
  hashes:
    binhash: c7d5592f940b23b85aec1710cc80f0f7
    md5: bf6966cef1d4bdb209a544e6c6fdf6de
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2e69ed1ac7813ffbfb8975437f90fb92
    md5: 222658b48fba7121aefae107ca450bc3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7e6751bc448336f4d5cb956c635eb2e3
    md5: 84f8157cf7bed512025aa58d332ac0ff
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1b99daffe5fee31c0ec31b280b8feda5
    md5: abd63268b86be95f914adcbfb57834ca
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart299/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 83de9a8f622a40ba42ebf8ff384a05d0
    md5: e06cab4c8c87878d03cd274f2e06d91d
