format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/atmosphere/restart_dump.astart
  hashes:
    binhash: 06d3706d7e66f11ff931beee85376281
    md5: 6e9fa0c07fc7557fa21a47a112bf1789
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/atmosphere/um.res.yaml
  hashes:
    binhash: 31bf9844ae2342006b917c9c2714ec47
    md5: 883eaf2dc969909af8807cffd7018cf0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/coupler/a2i.nc
  hashes:
    binhash: 82e04f7368e9dc0e7a2305d7343e6bc7
    md5: c5cd7bffcf537ee4a251744c7867cda5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/coupler/i2a.nc
  hashes:
    binhash: bf9e306095a20e41a2a9767a6a9a6573
    md5: f00f26ef664f3f548a0de99d207a4619
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/coupler/o2i.nc
  hashes:
    binhash: a337584873528c100418deb855da2d24
    md5: 2abf06ca5f2e639b26441cb65d748a72
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ice/cice_in.nml
  hashes:
    binhash: de41b96509028bdeea7e7d1114748e5b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ice/ice.restart_file
  hashes:
    binhash: b32d9122a87720e74286c39702f82366
    md5: 2126ecf623908a99727e260b08a1ff46
work/ice/RESTART/iced.0887-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ice/iced.0887-01-01-00000.nc
  hashes:
    binhash: dcaf36448798312512c20ddfb894b51b
    md5: 1bc8cc254953e6ea2ab468cde3e6c51c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ice/mice.nc
  hashes:
    binhash: 94e1da626db49f75c4256065ca2caca2
    md5: 892dd58900799ae2ece527d0a252a57d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_age.res.nc
  hashes:
    binhash: 4754f007e653dc87fe7f5a6116a7bb8e
    md5: 8d1698296f0ae842fd559fff5503a03b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bdfaec74511922d0dd1bfd60c5ddb6e4
    md5: 4df95e9d70674a77e696795eff86e6ee
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50987ec64c64461bcb65a578cda59fef
    md5: 84d66316ed8ad0f3d9b08669f3625c42
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_density.res.nc
  hashes:
    binhash: cac4ee31941dbf02ca26d74651778ab6
    md5: 333bab3be4bc09f2f0a6dcd36c3e49dc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9b5e338fbb0b4d58403c1d0824d0329e
    md5: 9e5568a6f330cd0a8c8fac21736da6d9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c4710531891a8a697e86fdb216543f7e
    md5: 1ec5774380a0b8b7e093032c9b97f465
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e7b58fe280b66a83c4f4d9757695bd1
    md5: 97555b528c4abe65deaac5b1aeeacc2d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2756779e3ebab07e8d1781952ded7f3b
    md5: 921f423ea6e141273481b098317707e5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6473dbe97184f2e45a6b136ef225bc10
    md5: 518697e9648a60aa68db9cd7b33293f9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: db6e10eb56013b85de3bdbfd84149073
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_solo.res
  hashes:
    binhash: 8c0009c87af82e9c8383368dddead0f9
    md5: d5142ca79e5efa467eaea4427751782a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 569cfd324e83947cfdb141c02a747b4f
    md5: b734523766fa8fb2585a3a369c9af81d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a4983359b4e577cce7dcc0bb84f32d37
    md5: c2edd9c0752c915b1dedf9d0f539f927
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_tracer.res
  hashes:
    binhash: cccaa9acc834b6f0ab4dd7c5fd59e623
    md5: 89856f510a09ea0d82d1d0ac21079169
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 28f38eaf0a3e8087f56e77d749155bce
    md5: d88ec80db853488886f30066ce31fb9f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f7a62413f3c3c32cea4c036476d2815d
    md5: dafe903994e284af6797e18349551472
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1fa6f44b2dae3e490adb33058a39ccbb
    md5: c017ba993085070cff36c2e82962dc7f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart333/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: da09217e0c2b754c96d72d72a6ca5c42
    md5: 704a96ca31112fbd1d755270558be014
