format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/atmosphere/restart_dump.astart
  hashes:
    binhash: 454356b8e08e9706b88283dd7d023ed5
    md5: 0bd167595a40753f226a84fd8be42900
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/atmosphere/um.res.yaml
  hashes:
    binhash: d9eba1e4f66e44eb02c95ddb78b15e75
    md5: e961128274bcc4b862d7d718533e34d6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/coupler/a2i.nc
  hashes:
    binhash: 7c5bf4f499ee7fcc4aaef7e6fa2e0afa
    md5: 123aa4168901057379d299ef0fce2428
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/coupler/i2a.nc
  hashes:
    binhash: a1698b32afac5a9140a5722ac8f24908
    md5: 559cfc515c76618c69d8ca38fa645b65
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/coupler/o2i.nc
  hashes:
    binhash: 119291c87e4180096ace9b0b1b86b174
    md5: e8971b8dc6f56d1e6d8110aa06f3baff
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ice/cice_in.nml
  hashes:
    binhash: 23ee514a9e59cea63d146996b83b05bb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ice/ice.restart_file
  hashes:
    binhash: 2ca83cc600f2c96542469de483a391a3
    md5: 2d0158b167d417469d80a06b2e15eb17
work/ice/RESTART/iced.1862-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ice/iced.1862-01-01-00000.nc
  hashes:
    binhash: 29ef51f50a81dccaa999d6baa6507325
    md5: 1b87a4c1a626626c284c6af798bece04
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ice/mice.nc
  hashes:
    binhash: 9ecce4a08d51c0a2405a3b97303c9ad5
    md5: 0126f46b5e1b6d02a87375b31247a7bb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_age.res.nc
  hashes:
    binhash: 4790e9154a0d0b5e305c9b16aac62e2c
    md5: eee856d050a2ffe44ce69fa77c2b118c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: df2bb00897f4c3a470d3a7cab7305e46
    md5: 5e9353a0093bf27057db2ab0cebeb37d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 81466b56b00090bad67716d2427fbdf3
    md5: ac907e2ca9de43405913e24db7f2f75a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_density.res.nc
  hashes:
    binhash: 586f3a61e0005d5083cf23293ac5cf3d
    md5: 1a9cb1597e80adfc6d4eb8ac6acc45d2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 34e7244e510a1061c4a2e170249eb80d
    md5: 864cc8b3be4db04c15e1527f7db95763
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6be3254efe159a9c96b4a88547f7e3ab
    md5: b7eed74de304359b85a1fe26a83b0264
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bd3289bcb16af5662056431b2b7bec9b
    md5: 003897c248eff9598f9729a2703cb306
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c944209b4a4f60411c3bc754d64fe73b
    md5: 04c75d075a742e8ad8ee6cc3979ab80c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6bb71ab98aa88a84f177995560c88d93
    md5: 2315dca7204c5f89921eada56d8f89b0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6f7604d5df453920f09f817c2d72c254
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_solo.res
  hashes:
    binhash: 80c3e1d1121ef2c450171678c35a555e
    md5: 1abc90c2b69a3a179d19fee617df382f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 86a66fbbdc00a232e43cf4deb68040a4
    md5: 6e1331a95192c7d89ce8e855570677a8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1d839ceb0587cb1c06b02d88c45c0e67
    md5: 8e2d2708ee5728a1b8a341a34aed3e8e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_tracer.res
  hashes:
    binhash: e5f1588569efe57ccf0257f6bcd88fd2
    md5: 339722f1c842bc8360268999b145908a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c02aa11802f7c348ae50c42df915c862
    md5: da6bf2b168428ec03630c424ee692aff
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c07e7f6a0ed84d3963ebadb60c0937ea
    md5: 5c79c0ccd89dc235af1080651d92f7c0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 06000ba16e0f054ed5c6059278debbbc
    md5: 827d9c78fd998a99d25461815842b34e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart417/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e40677b692985981aadebf8bea219a5c
    md5: 716095ba84bbf3a4ad90227d010bd1bf
