format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/atmosphere/restart_dump.astart
  hashes:
    binhash: 42ab26fce0e3e3fbb6c03889cbda55db
    md5: 80f12f04874e78ccbbdc1db939769645
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/atmosphere/um.res.yaml
  hashes:
    binhash: 45be9b1c2222239ffa7fb6da5ad1b0e9
    md5: 4345436bb2345a68bfa62bf2fb1ae6a9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/coupler/a2i.nc
  hashes:
    binhash: 7b3d8cb101cdeaa5e786346da3c469f4
    md5: 578179d120c8609b0b101de990095c01
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/coupler/i2a.nc
  hashes:
    binhash: 01eb1f12a959d1ff9dc7fa384c4fba94
    md5: ede9867e3872732c214b09f9518bb638
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/coupler/o2i.nc
  hashes:
    binhash: 5163ba8899ceb55eece26579a652afbd
    md5: ccbe28313899ab4f71cb90e3bb15be06
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ice/cice_in.nml
  hashes:
    binhash: 11660ba02c109518ed7617928fe5e267
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ice/ice.restart_file
  hashes:
    binhash: b4fb37598fb0921c1e71e41237df333c
    md5: d9a2cfc12c881b69d1bae37bdd0d3481
work/ice/RESTART/iced.0970-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ice/iced.0970-01-01-00000.nc
  hashes:
    binhash: 0d479e5f4c8c715cc0c2b10245938c46
    md5: 3d32cd4df33297d8a19f26348c087b79
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ice/mice.nc
  hashes:
    binhash: 5da1b24ab0f43fa585dd7864aa51b09d
    md5: 1ee62863d0dc2885da29da04bdeaf515
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_age.res.nc
  hashes:
    binhash: f9d2996b9cc8f4371b52bd1fc54b0c65
    md5: 47c5cef6d0d6ba605b7f00334065bd8b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: fbd4893ada68c9dc8552a357c2eb9d54
    md5: 831d5f3a2e25a28fa5353911394533e4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 166f9d2b82d92a5944bd4720f32f7555
    md5: e4b5bfefd998358b1fa8a550ec28b73e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_density.res.nc
  hashes:
    binhash: b8134792db1361390564e934ee9f27b0
    md5: 31e93aff4b61ba5b7018a21a12c2741f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3d1b78ee64a917ac7a0d5e7e85928121
    md5: 277e2e19eda4d98e71c135fb57c59647
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7262fbe7b804149d1161080d3fce7987
    md5: 4395c6cc672e6aa2e4697c50678d46c7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f11165cb0b45bdc208541f59cf7c362
    md5: e2eee0a8cda8ac380600fdd2b991b7bf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 15b3d5195c8fb277e3149c132127e6f4
    md5: 055a4111b8bdffe73d835c29675ecd5c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 03ddc3bee907a1df29b6a2e068a66807
    md5: edb744e3c6a7bbc08dc16439d4f56d7a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 978d5979a8992f7e9a7fc229a7236d27
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_solo.res
  hashes:
    binhash: 571ae3c454928921c6b75a814a904fba
    md5: a575571d0f7759f557b6758fffe3d59a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dbae3f53d7b1986e0f0af10f4a6047db
    md5: f7d07ddf4fc02eabecde40bd8aba2a4e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8dc15009447b458cd3e55513553224f2
    md5: 856add9e6da7295659879198c2bd3851
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_tracer.res
  hashes:
    binhash: 2bc1cbfdf0fdda81cd1d229d4d27304f
    md5: 6862d8b99fc0b0a6844da81ed976eaeb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_velocity.res.nc
  hashes:
    binhash: da0a915a9d942683184bd6d68452cfae
    md5: 888106c719555e651706379eba7ef54d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3e49f3ef75f468d7aa10012a5f7f6645
    md5: f1d102ea244af51b8770594b900ac5a4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3a94965c909ddf7ab2641554fcc3d05c
    md5: d293cf0d2401c49625ad9a921d8c7f0c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart416/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fb4833c69fc9884093fef7bc62720e01
    md5: 3f865277c68fd2af585142d15d7da687
