format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/atmosphere/restart_dump.astart
  hashes:
    binhash: 85271ba13059d8a4d5583386a252d864
    md5: fa4c763aa0804567b6d429289208eb75
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/atmosphere/um.res.yaml
  hashes:
    binhash: 4b182aa50d72e07713c26d1034e4155d
    md5: b0cbdf77a620e185d1e8b20d4bb6b9cb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/coupler/a2i.nc
  hashes:
    binhash: 505c4d37121465c316190ec632f6faad
    md5: 720ddf501d09c10e6974862f15500991
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/coupler/i2a.nc
  hashes:
    binhash: 6e2ee4a64b78148cb010a839dd414b22
    md5: d8b7afa681f4c2a9e9af96ec233af1ac
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/coupler/o2i.nc
  hashes:
    binhash: 3c13cc46165919f230ddc27df96d65b5
    md5: b809ac6e02dc638a2c9a1f0b02d49272
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ice/cice_in.nml
  hashes:
    binhash: 91e7eaa49b4422cd033fb3134e42fe07
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ice/ice.restart_file
  hashes:
    binhash: c8a6cb56de60fa3440c72717dbe9c792
    md5: 5beedb7dd331d82d02be4d9c91e8674d
work/ice/RESTART/iced.0913-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ice/iced.0913-01-01-00000.nc
  hashes:
    binhash: d44a49ba98d2d9e89c2e1859a17c6b42
    md5: 86f128a16eb760decf31d6645e47afc5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ice/mice.nc
  hashes:
    binhash: d4318e08c597ebedf57fb94507812d13
    md5: 0f4e2ece15a86bb0f3a892f8a80d798d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_age.res.nc
  hashes:
    binhash: 14e2082e282a0d6f3e6eea305f07fd12
    md5: 2902ea4288f41def6e81f6c94f8cdd80
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f474b4721e5da3a32627dac5355a5073
    md5: 263e8b50dd8edcceee5540c7ed9f9a65
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: df83564e4350c320494282218256883d
    md5: 40cf101e4b02d315eeef76a92ce5c1fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_density.res.nc
  hashes:
    binhash: 527ffb51c3d497e46eed7f93fc0145ce
    md5: 98b691d3fb81e906fc19b60d1050735b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a9fdebf4fcaf713a3bca4ee9d85ae90a
    md5: cc050cc3f2f4a29b8965d758b7021084
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 51f37f483a5c6d823bd0c2388d0f7e99
    md5: 9cf69d507b413ab260ae2c402f572809
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1609a3737469842dc0da8df6c78477b1
    md5: fcabf6b65044cfbdf4c6d24d9e869ab1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f3876c96cd328915e7bdcbdad4d99946
    md5: d137810af8482ef507acd33301601416
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 982de7de6b9b52b15497e6bd96639ac7
    md5: afcc6bc2284278e8ea6dc61c0f831397
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5df4084fb1e382deb23a2852393aa6db
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_solo.res
  hashes:
    binhash: 28442f4cfda0b74b29f63db458285526
    md5: 91d8537958087d1e0d9e5a6db8b7682b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 020c9a47252c7902b12c42f0ee5da7de
    md5: e404c401b9d7c4b6253fe2476b680faf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0ec29939bff973d42598dc2489b906c2
    md5: 94a4f28aa1338aea584397c6d53a6d2b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_tracer.res
  hashes:
    binhash: 1a343adb616cf343619188aeb001e2e5
    md5: 6ba265e360c4457bb33167cade364a0c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e754591bcaee59ad65c228d1d17c5aec
    md5: 8e37ac35120c26a331619648f942a607
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f2685db21a2bb8a53dfe66f4bc1961e1
    md5: 2dee2bc13b903e5ee5a623363101e351
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5d4bd57e378c6c83db62d78a2881ead6
    md5: 1a74e50d737673b0a98cd7bf4a0666cd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart359/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6bbc474d2b0c3c467c5fe19f84481bcb
    md5: 931cc2aade42e80e38e33a5a74091b21
