format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/atmosphere/restart_dump.astart
  hashes:
    binhash: 300afe56b9c90960c48caa6e773d084d
    md5: d0ec6e1c93a6aa7071a12cc6c322a632
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/atmosphere/um.res.yaml
  hashes:
    binhash: 4f879549871c14ddbbed5e5e1c8c3112
    md5: dc6cb0011264ebd21ca7cdd605b34076
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/coupler/a2i.nc
  hashes:
    binhash: 4585436d542c47b7ae5f7b16d843ad64
    md5: 8b4fb0032906cb4960f1a03ab685f817
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/coupler/i2a.nc
  hashes:
    binhash: c0010695eee7efe8965cf54ee8ea7e09
    md5: a612bad422a13bb1516db04ba41e3e26
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/coupler/o2i.nc
  hashes:
    binhash: 3954a3f818c7bb7883cd130eb19df3b1
    md5: b14555607cc9d430ac0dba0ea76c7f35
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ice/cice_in.nml
  hashes:
    binhash: 5815ef92bfc1269b721d933a032d56b5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ice/ice.restart_file
  hashes:
    binhash: 6fe680d4e59e413ac87dccdedd0f3940
    md5: b9ddead99624039a7acdedda494c08b9
work/ice/RESTART/iced.0857-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ice/iced.0857-01-01-00000.nc
  hashes:
    binhash: 00dffe8e5e498b1efeec06843b745ee4
    md5: 56ed79b3b816af244a3b6aad16b847e8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ice/mice.nc
  hashes:
    binhash: 69a977419ca3de69679c5a1d3b380b81
    md5: 0c49c8ebac2e6272f86d9cabbb3b59b8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_age.res.nc
  hashes:
    binhash: 3a017ff1cbb0e5fec6fad9514bf762a8
    md5: 18064e643693d729a601a4b524e1d1b5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1280923638fb000bceac2bfe9791a457
    md5: 34135905b9c27baea3c2848c9ce80ee1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 74c001538a07d45c73958e004b437901
    md5: 73a00e0f7215920da48167d6bf66a0a2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_density.res.nc
  hashes:
    binhash: 30587709c1a3d289a3cac3e9a53334c4
    md5: 9555340f5d34be8183f2dc304c326aaf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 099f8cdb415ec1b0c2f2b084cf6ac0af
    md5: a5bb52622eb25b31f8291e999c20ab8d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d694ff0750f391d3e780b5d1e26188cb
    md5: 24e6138ab374321aa0f2d3dfb9237354
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 17f01171f38dfcf7dc3f6502ae8d4aa7
    md5: c5f1d0118bbb4b8289b02cc9b6165889
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: eeb1398546dd4f30ef2ec26454b380d4
    md5: 8ad779277d91e92b42593e64a607b873
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0a241c7d3f40f32cbbd269e939a2247e
    md5: 5f88a5e524847cdb4845b48cb50a03bd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: da14313080c24172426adbeec833666d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_solo.res
  hashes:
    binhash: 9e2fc15b329bbaad924e0bd091d1e248
    md5: 7e4938e0bbd4a385dcaf7498def6da4b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5142ee37752ad376a23d0dda4ae9826b
    md5: a349ebb1d2004ccc7b052266f474130c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f3cce4790f137347683939b61af4f6c7
    md5: 09da0bf62dcf41d884acd39c5a01b884
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_tracer.res
  hashes:
    binhash: d4cc9090b8f69fd6fd3af7c6732a02b6
    md5: 8e1a00ed23ffe37be0172af6060f911a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c4b53c5a43c13cdf762c45b41a3ca90f
    md5: 6e7ea027a4e191cf9a9a2503df448fe1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 94241e68068350f53ac6603e99bf4b57
    md5: 50c4ed2f8387da018713a6c1b5250e7e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f9ddb64965501111d50401fc466305ce
    md5: 8d7279a49c1d0061cee4e2f1f6b49af6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart303/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0c937fff7c7462d8f047e7c1a0d9683d
    md5: 156605fb6d9f5a8d4c125167efdddcba
