format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/atmosphere/restart_dump.astart
  hashes:
    binhash: 57cebed59efd612d7130a25d2166b372
    md5: ed2270b18c4b7a65f932c12f684615d1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/atmosphere/um.res.yaml
  hashes:
    binhash: 5d17c3e7039a141f171d035bd76fb78f
    md5: 0fc1ea273335f033bf11935ffc364fe9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/coupler/a2i.nc
  hashes:
    binhash: 337858ffd8eac519d25ad3d09282b7be
    md5: 60a947cfc89b31531ba9da815d02864f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/coupler/i2a.nc
  hashes:
    binhash: 169f4e0e4f5602cf18f8f65e7a6429be
    md5: 9b462b9b84ed6e3e56e46f3b520c03ca
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/coupler/o2i.nc
  hashes:
    binhash: fd597f1b0149c37092a47c357b5eb79f
    md5: 2dab2eadd39fc52521f674c83ca0d34d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ice/cice_in.nml
  hashes:
    binhash: 150746466ccb4d5ad0f4523bf4d8c576
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ice/ice.restart_file
  hashes:
    binhash: fa25b4e914150e1ab31eacd939cf3027
    md5: f08cdea8f4ebdcc5fce66d0b29462930
work/ice/RESTART/iced.0868-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ice/iced.0868-01-01-00000.nc
  hashes:
    binhash: 6553317bedeb8fe742644deab843463f
    md5: 76d6ff6447772b8c34970fe9ad73daec
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ice/mice.nc
  hashes:
    binhash: 62beae0940508991e4589bc08081e4d5
    md5: 61ff87bdf5d3aa7437697509acf2d5f0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_age.res.nc
  hashes:
    binhash: 1502c9627790f5d84c977e1283bff315
    md5: 9fed1afdf7dca3799b954c9a15291020
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6fb393e0e12fa335f6e78e4070598e21
    md5: 56a695ebe1035fcc286279281a9e8d5e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6f00ba92c0b68cd9b671bb30eb19914d
    md5: 4199c74035bc200d02c4ce58d3b7205a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_density.res.nc
  hashes:
    binhash: 59499cdffc9803e4f583ac6f37041a20
    md5: 2f41c98f54521987db54c76e6f8eb3b8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 78481c08aa86173952d196289c39414b
    md5: f2ab3bf47be3fc358f3df4b5683394c0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f2d5b9912babe170af16f27548c8707b
    md5: 873a1b0d582c29c53c86f06fad4cb99b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 012f0255b88ef55398d0478b24776e5e
    md5: dbe30fde6a4ccca45740e6113e36625a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: adae501678f9edb79387506c9ff86331
    md5: 40392fa82f8cca9cc33fd501a74551eb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b79d42aff0fe214bb265f664e09611bf
    md5: 23b86f1fe50e15d1097ec2b41a5d6440
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 14bcc93bdc0a3c5793071b205674bda6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_solo.res
  hashes:
    binhash: a30677f228bfb2fc4b222c9c8017a55f
    md5: 34abdbc760a82e284752e068231b29a6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b5cd54bd2324824da619bbe80b844941
    md5: e9c9397c9845e77909e9feb8e8bbd4a4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bacf60a2d5d8c7ac49f1d5377cbb682e
    md5: b469c4c11c831a9d3258539a9c8713b4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_tracer.res
  hashes:
    binhash: 50331dcf468ec7c12bf6718329a12cd1
    md5: 440f95f009ea15393d72d7d68be4f049
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7ccd23ef0f92e4d000039ed07888cb42
    md5: 8255f222afca6d1d1262f22cf1ee4258
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7c012ef7ef3d4df1a7e998fd18172000
    md5: 06509f781d2f5746c18bca71722321d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8f61653b462b074ef80a2ecea41158d7
    md5: 92c85393e370c92ed552e1b29419d431
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart314/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 193f408748216c54218e722b8c30cadb
    md5: 25b1ad97864d24fb4d1133e72730b65b
