format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/atmosphere/restart_dump.astart
  hashes:
    binhash: 6dcfeeb13ed4868485c3ba6647651e34
    md5: 613f277c3ca9d6d81d5d0dbc83bedb73
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/atmosphere/um.res.yaml
  hashes:
    binhash: 1431d133958b518b763ce3628c19cd99
    md5: 8c525f353745bec7130c4dabb70850b6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/coupler/a2i.nc
  hashes:
    binhash: a4d55aaf601f4bd5e643cf6b0262379f
    md5: e426265a81459809d6f91842b5adda86
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/coupler/i2a.nc
  hashes:
    binhash: 3dad233299387ad23ea37c8ed53523c5
    md5: 5f1b89d2c53d83c4b71625430786c30c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/coupler/o2i.nc
  hashes:
    binhash: 2c25b6ed10ca254188fef4f3c251973c
    md5: b3db23616b4f0ede2559bafa303a0b1d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ice/cice_in.nml
  hashes:
    binhash: 89b39f42eb0b6db307acebf1fe261d83
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ice/ice.restart_file
  hashes:
    binhash: c757ebc3922c36bac6e4cbf83f838abf
    md5: 97b9ea0f3ac32fae76f6a202c9d74827
work/ice/RESTART/iced.1761-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ice/iced.1761-01-01-00000.nc
  hashes:
    binhash: 1364fe4c2cc4f1b5bc716ef6cdb943db
    md5: da28d05bf7dc0b242c73b72cb69873ee
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ice/mice.nc
  hashes:
    binhash: fa5cbb2c6fccd1b80a60fd8381a631ab
    md5: fa835423d96dd1c9360ac3d3f46ba0e0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_age.res.nc
  hashes:
    binhash: 614f73d5c11682e97701003afabd786c
    md5: 4904f7137524b92a26537010c8e5879f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a6f39233e2754da622014496668ff0fe
    md5: 70b728df16155a63246472f5f43d5e73
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c020e0cfa300a1f8cc17add89cc40637
    md5: 13b5515800e60ca4daf183ca5dca68e0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_density.res.nc
  hashes:
    binhash: 72d99577ad5d6974da3134d3f969c7df
    md5: 6bbfb23d7023feb48cbc4c8b217ba76e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e3e82eef32db211fedfa3bb5ee0415b6
    md5: 3effb140073ac6eb9b480cefea20fb12
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 56ecf742827735781f8a9ccae3d6ce8d
    md5: 41e4f5790c5056e6eb61cc38d842ff91
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2f40b10afbaf90bc779c657da2a2dcb5
    md5: 9a29d86839253a80769bf486d65e47f1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f4239d8fbbaa36c7acfa7247b8e7f5c3
    md5: fcc2d51cda868253b1f64084b91b5159
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 00df1f7ac21256067b1216b75a4f4e17
    md5: 47b3ac0055f039cfc005f791441adb4a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d35544d47ab11898cfdadf498eb582f3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_solo.res
  hashes:
    binhash: 90d7628a6c3c1d85c9c12cba264d2a9b
    md5: 8208538d26af8fe73db5b3e69a4e269c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7bdc630200c58ce19d7fea549184843c
    md5: e58d83d1b0a4d2e91a4b1ad657462b1f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f7e1a6ceba2d2a9f55159d34c60e8953
    md5: f7fe0df431c1daf741214ddb7cea1779
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_tracer.res
  hashes:
    binhash: 20a242e0bb73cfddb79a8dc34a253866
    md5: 3279475150eeade157304801e3ccebf2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f3450fb59d90800b51f605e197378eda
    md5: b74e64e1ce37b8bb6f144aa4e369cf4c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 885767bd24bbcca262d672506c07479f
    md5: c2923c7e770ddfcd507460c4646473b9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 646f0c972c2b2fb9c910e93c21713ae9
    md5: 394e3afd7ce8040b573e3e13d78c6199
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart316/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 91465a2b9f318df3dcda8095bdcfb463
    md5: c568e987fc043787bfd176c16b7c22fd
