format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/atmosphere/restart_dump.astart
  hashes:
    binhash: 6620596e811abaa3ea197af1354258f4
    md5: 0614a4a052d76d030f1603243c148d43
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/atmosphere/um.res.yaml
  hashes:
    binhash: 2f02386ded9fa686e72da5c8ce965815
    md5: 0b85f7be3ee173a204d0f58f722fc5e0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/coupler/a2i.nc
  hashes:
    binhash: 45b3800a5ac302c791016ab2cfacacb8
    md5: 6b12de95e877f5eb3ccf4c502231c58d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/coupler/i2a.nc
  hashes:
    binhash: f3c85fe1b325ae24a263a1c1bc7f2100
    md5: bbecec624bdae13af109b499d4a79658
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/coupler/o2i.nc
  hashes:
    binhash: 594ba15707ca735d3ad6a29fcf161d55
    md5: 3f6ccc207a61e7672af832b0ad8ac019
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ice/cice_in.nml
  hashes:
    binhash: 3beda8960c1ecb90605c291816696c96
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ice/ice.restart_file
  hashes:
    binhash: 6a4c192b19a15839b216fc297356889c
    md5: 7526c13e2b18ecf028ef99daa116da03
work/ice/RESTART/iced.1281-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ice/iced.1281-01-01-00000.nc
  hashes:
    binhash: 31d17a616a8e977c529b6b35899db5d4
    md5: 40c98a5c72b68fe17888141393240fe0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ice/mice.nc
  hashes:
    binhash: 41cbb9764b1c228a3d377d4522f23cfe
    md5: 0be86fb5e84aa8d881775782a1e9cd64
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_age.res.nc
  hashes:
    binhash: ae1febed54b736d0b667f9849567a6e0
    md5: f2d32ef3c9f2f677acc6d1290ec2a5bb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c52a394033d3efc5c39e46904062c585
    md5: cb500a51ab3947676ec748b6febe1d54
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4979a56a00c2f876c1af027f45932d29
    md5: 2c9993e7c01b2252ee566aa1593f6e9f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_density.res.nc
  hashes:
    binhash: b61f102dc37d148589ba272a87698299
    md5: 8e5a340a44960c7a772cdc19600b19ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cfb43d3da47de8d94f766b64146b8f5d
    md5: 454ce51552d91bfa5d5beddf73a51e29
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a0b6551c1f091ad23317b40a1656bbb6
    md5: 0ed97731f5518f5f8ad7c0ddb82302dc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff9a2440181bc6c59127114523829c6c
    md5: c6edcaed211a6f735ee90dd9f3f86658
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 05623e4033a00f623447982b72ce20d5
    md5: 43e39db9a080dea6e83e9c5dffe64a13
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a5349c3b3beede45ec9dd251a99941b6
    md5: 658f167b15050136b5b41f47f8aabca2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 90001a54ef031cfc512037381a3c9821
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_solo.res
  hashes:
    binhash: 0502971db76bdd2389cdad91c33d27c2
    md5: bbec9294597f3d763794f7f2b3b3760f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1fdad5cf5f20750113a122667ee63867
    md5: 9064818c080691508fa19a52d05dd826
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8022ec2a5f0ade641c37256fe90d90d3
    md5: d85ebda81d9def05ba9e8999bd7be5f9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_tracer.res
  hashes:
    binhash: e2f1da54b4127ff6002bce2879608b2d
    md5: 40c5eaeaf7d8345264c3bc99faf0d9e0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7946b5f0f4575c4c27a808016072d044
    md5: b96e48a1a1c533a821cf5cb1d92b562d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 03d22e975c70fedd0e7480916a30e787
    md5: fd2522f916669b5438b663fb11d53312
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 224efbffa074c9576a2f8b457206b9e3
    md5: fe64043091d4483abca58cc7be3c0236
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart397/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8962b86756ee89c04891efc3b280e5f1
    md5: 1a359fe540e5cfa5bfa5ff1cee8d9d24
