format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/atmosphere/restart_dump.astart
  hashes:
    binhash: c3e582d28eba970b6268d43f6d80850b
    md5: d0d7c3d77cc106e5eebfe12f5372bb9a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/atmosphere/um.res.yaml
  hashes:
    binhash: ab691cf429ad8aac03ed3b188b800171
    md5: 2d92314b7a8c441e32027d5668d98680
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/coupler/a2i.nc
  hashes:
    binhash: 6cee6e5dde59646d9af89222dfe502f8
    md5: 69770b2536e11810e6c699624d899e02
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/coupler/i2a.nc
  hashes:
    binhash: 5a0054ff8961548be6621e9df33d6d50
    md5: 144718b7bf3c06914430ae02d6985d0a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/coupler/o2i.nc
  hashes:
    binhash: ce6f83996ba24c5e4b8ecdfe9d01fe1d
    md5: 348c2130205a89fa181f859dc57ea299
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ice/cice_in.nml
  hashes:
    binhash: 16f4be0bd0472fd1a68308a715177a18
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ice/ice.restart_file
  hashes:
    binhash: 7ffba68c5cada492f2e4250c113f34bd
    md5: ddbb9cb6b4df7437c38c96f0b58caa9c
work/ice/RESTART/iced.1853-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ice/iced.1853-01-01-00000.nc
  hashes:
    binhash: 4de4c97714e358bb7e6394df3232cba2
    md5: 4f9f715945698d743bb5c91d4fd9e231
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ice/mice.nc
  hashes:
    binhash: dbe154d00221393cb9d46f693fdbdb73
    md5: dee4fbaa9c0b173c93d8ba5a22bc563f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_age.res.nc
  hashes:
    binhash: a04e85b7d134125bb887ba1d811bf3b6
    md5: f9f228a91e91cb1cad5acd4eaf02d772
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 56ca4487545b80e70c6fcacbe92d2f3d
    md5: 68db65e9d2b0ad7a28674af1a1562ec0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 20590cd1c6a223137872f332c87946db
    md5: 4440665cc78c3fe85d557d935aaa7013
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_density.res.nc
  hashes:
    binhash: 3922a45fa7b88175acc48dc9a6827128
    md5: 64d31d9acfb9003939847751ba2a2e75
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 08e55c1b20b6a747fa912ec2308e4f2e
    md5: b2b5fc695e0787163ea943b8625c577f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a31ad171228c1ec37d58f5aa17d3c91e
    md5: 1642056c4b6d7429d4081d9246407c61
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dbce66d6797c468a4720daa3d5c227a5
    md5: bdea21c6ec8a5c8010b68cfc2def29c8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 179a49a0811d22e6065dc2323f9cd9df
    md5: 221152ba3f1013bd85c6d7436917f72f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3d712a3f8241c721cc2a2a73da308d00
    md5: 1e5644191d312acbeb65250deb59ca06
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 148f4dcd684674e849bd354cc778ea85
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_solo.res
  hashes:
    binhash: 6f82000181c07d9821ba9169cd49968d
    md5: 90aca8a6ca04db01614a3d7a5aa0328f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8bef80d81326ea405901a74a77f46ced
    md5: 251e722fbc55c291e59d2b613f6d0b8a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 452ecd5aa68ff6f15c1310876de8389a
    md5: e8f582096d9052fcf41c97e078dd95ad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_tracer.res
  hashes:
    binhash: 3897eea685c9d2ebb51a8eb4734f9aad
    md5: 56c00830f28e567855daa2876998a63d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a67b0b472e0fc1fe4a4a2ee6b80105b5
    md5: 0feec7708c66544e96808a7b44d801ab
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 987b6e70905bb022ca96cdd0bfc40cc9
    md5: b1338c264cd54e94bcb8cf98eded58a6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c9a4794161a28398ad1183f3f7343ba9
    md5: c644d2e3456712ee415e5aa55e5d4e59
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart408/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fcc75e662936c707a1ce2f13e2f729c6
    md5: 5d9469af7606948aeee051826b8df5f6
