format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/atmosphere/restart_dump.astart
  hashes:
    binhash: 6b0666d266f9a17030e8cf86515906d8
    md5: fc045599d370fa30c52fb90f378312e4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/atmosphere/um.res.yaml
  hashes:
    binhash: 522d49c3aa505ec9c5a54e0734e5a1d5
    md5: 56ee8ebed0b13552693784b4b1955525
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/coupler/a2i.nc
  hashes:
    binhash: 9ef78ad9a36e49038ad3dfd6912b83ee
    md5: b7a6950e16df2c431b028d342de1651c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/coupler/i2a.nc
  hashes:
    binhash: 5406920ac4faa45c0eaddde75de341a1
    md5: 1f8f48972ac2a60ff7ea35630dd08de7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/coupler/o2i.nc
  hashes:
    binhash: d48e90cbef0a14587d111e57b308cda9
    md5: ec2a166377dadffac8a59b11b04a9281
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ice/cice_in.nml
  hashes:
    binhash: ec70d051da9b5cea4233f12efce44c4b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ice/ice.restart_file
  hashes:
    binhash: 1fcb98f138ed123d877b154dc7ec4cfb
    md5: 9d21df2a71eb4c90c6f768298ad25baa
work/ice/RESTART/iced.1262-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ice/iced.1262-01-01-00000.nc
  hashes:
    binhash: 10a64508f92ee1d9acda7cd352a12502
    md5: 8c06658d08477bcacfdf8da1d4d82aea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ice/mice.nc
  hashes:
    binhash: bb2361ccdd6b8909de565a6a89e5c9f8
    md5: 78bd022c32a24a1419736cd67d0bfce9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_age.res.nc
  hashes:
    binhash: efe38010fd01fd67a1b03bb496f2aac6
    md5: 9c4e456acd36cd1c8a0c7e071c901c1b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b7a5c91ab65d5c0ad05844af3b1a2b88
    md5: 1c6aa559122b64ead4eb4749ea38dda6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dcbcfcedb3a2d20728d4855938476a19
    md5: c4a48cbc219cc53c7307af2b82d2ce3d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_density.res.nc
  hashes:
    binhash: e10a318a20960c3a775a4d08d708ecb5
    md5: 63590ed4ecaf824e711095330c76cf4a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5f5d63aedf822034685a7944088fa6a2
    md5: 6a3da0a6285f252cdd62e867dff79563
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 66328ca26dc9764e035df23c327b836b
    md5: cde1114daf970b9555fa3b0c8de04809
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c8c7d1348675e2ae5393d67967ceb0bd
    md5: b9ea38d1e611da65f3ad97609fdb6b4e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ffabd68fe7c5ba0282f5d057a04f63bb
    md5: 95f5fb822ab8a7a4b363e929c0f74591
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cb2cc97a89f1a1a4aa5ab40e8f92b3ca
    md5: fdfdbbd9f82ab54c74e312f34cf5069c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f0d84bd3aa6fdd92b131df78a2eacef0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_solo.res
  hashes:
    binhash: 377dd52b51aefdb3533f8205c56ea541
    md5: d798db009968a5dc5372b3a148954305
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c36659968bb2ea36dc7dfe6eb84d1e7b
    md5: 6cea45702543880e8036a05e9add6cf2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eb0af4742ba369059d0f327d62a77d43
    md5: c5f171bb2a0e76e962361bdec43e7373
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_tracer.res
  hashes:
    binhash: 9913c9b14587ab3c59ca5a0125dc82ae
    md5: 3c1639afb23e3efb8a3c67ed0c143b86
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7f11fc5d4f84624fb58891c30cec61d8
    md5: 03df03923f54179c44032f2190b3ebb9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e0f6b1ae363d286e0e0b1d18008e2f3b
    md5: d1a017c389196c9f807c77154c2ce699
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6b2d3e6d5fa017e5dd95f61f84ade552
    md5: 9954c9621a3aeb36e4ed4e7c622a7002
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart378/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 618632f06157e0240a697fda146ce74c
    md5: 904b16e101b734956ee9630276c00af6
