format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/atmosphere/restart_dump.astart
  hashes:
    binhash: d22017069aa4107315f4b80a40e12bc5
    md5: d209d6378b56d058a9b648a23545bbf0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/atmosphere/um.res.yaml
  hashes:
    binhash: 72e2abd76c9a4332565228d040d28f27
    md5: 9195b45ab1e87f0f9f3b649d6a4ce27c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/coupler/a2i.nc
  hashes:
    binhash: 25983ce33135ff2430b828f62a5c8abc
    md5: 2398af4a1a9ee34f9634fd4ea03aa5d8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/coupler/i2a.nc
  hashes:
    binhash: fe0639023b349d3b79a48368658e5670
    md5: b416fd545917e276ca1df3d7e398d5cb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/coupler/o2i.nc
  hashes:
    binhash: 91d23f4707df25b41bbdf744878e9a21
    md5: 17c38e29bd6e55124e16e2c7f542ad02
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ice/cice_in.nml
  hashes:
    binhash: a65db685ea28dc813d77a3d598ac3fc0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ice/ice.restart_file
  hashes:
    binhash: ce710f866fd71d26874c3a6b7255d70c
    md5: a1c3f66632f601e3605204929e3b47ce
work/ice/RESTART/iced.0853-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ice/iced.0853-01-01-00000.nc
  hashes:
    binhash: 81adede025c82b567454cc4ea90f2466
    md5: 310f6e8a1606b9c633aa8ee2c33b9fd8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ice/mice.nc
  hashes:
    binhash: f765ac1e4583255d8aaf34fba3de65f2
    md5: 8c6bd028e1e1abfece927b5c37b0d6d0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_age.res.nc
  hashes:
    binhash: a8df6adb1689830adcd4d5f685c8bcc3
    md5: c98f6b00ee1bbc6e6cbfc8ecdd95648f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c46caff9457ac4b8705633bfa1d57c10
    md5: 20ff201891afd395b81bc0e381e58bbc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 249988dc254aa77fd90a93a53dab7026
    md5: 8900e74bc3172be41b8f1521901b6ac8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_density.res.nc
  hashes:
    binhash: da09dae0ec08b552955985304c275c51
    md5: f957ee394a4835ed8997978d800aa83b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f215c2735b5a47ee86f849932749c3b7
    md5: d1648c1e634640f85f49957f5a564af7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e293bbc7781424a906721232f5ff3d90
    md5: e96557bd1be91fa5a098062d5548e30a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f2ee2a8e0e9f363b5bf8fb586d1370c
    md5: 8735651a64c1df61a9d10c24feda43b5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e2eb2b63e89b4afdced21744faaab45e
    md5: a659d5e03a098869e5830f0b8e462a56
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9d90b16169d0ee884df914762e173b9b
    md5: 9f3101a904ee2c5e761188b9f7eff65a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 99158dbdb8d369bcf270e6ed749e5e5e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_solo.res
  hashes:
    binhash: 0b826a7b2024fe7e589e75c86cdd451a
    md5: 2fa3ea62e059fc9d2a4bfb9adb747b40
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 98112eedfbeb9f695937c3e0e5b7098d
    md5: 5e9aa30d5d6fcd8fad21fc5d58132da2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1b3117893b66f75b670907d9350b5a80
    md5: b160c5da8eb94cd56abe5e31ce5d3541
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_tracer.res
  hashes:
    binhash: d1dfde7d471b94a692cda03c40e305ae
    md5: 4a989d0ef696123973a85276e60006f1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7d5ba6a5ca9d5f23c1bb75cef5d60a27
    md5: 6d5256f58814d2706d8896572394df3b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d1b6302c4dd9577c1761001c82d44b7c
    md5: 49f0a535d37edeb9103fb1bcbe484085
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5adec037d9caa7c4bf008ee50e6bdd20
    md5: b8b533ca5bb2cdfd303d3437966b6d1c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart299/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 01247e3a9ddbdf8e9458e01b0076dd99
    md5: 7de5710b3c00b8f9878a51b5fed805f5
