format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/atmosphere/restart_dump.astart
  hashes:
    binhash: f7ddba1f06c033e0f15f2238e2d68ea0
    md5: beee987cba12a94bc076bfe2e85dccaf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/atmosphere/um.res.yaml
  hashes:
    binhash: 3c7cd712d99d88987698bef2dd49460b
    md5: 4e25f137c4fbfbace1b8cca3be935fd2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/coupler/a2i.nc
  hashes:
    binhash: f01da4aefa79b2b5a82ba1ceeba9637c
    md5: 8867ad35c37eef5b10db33a38781c6b4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/coupler/i2a.nc
  hashes:
    binhash: 944c09e4648c91b330a197d137d5bb97
    md5: e059c1023d426d758e35400250f66a15
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/coupler/o2i.nc
  hashes:
    binhash: d3d4a65301010715747f9e719b4e342d
    md5: 116bb1b6d88d694f4588d8304bbba3fa
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ice/cice_in.nml
  hashes:
    binhash: f62e914c4670cc37c165895fc01d2df9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ice/ice.restart_file
  hashes:
    binhash: 3b405ec358d5f90e937b85cdf4bbd37d
    md5: 4de34d06d493a02c81cd4829b2910bec
work/ice/RESTART/iced.1705-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ice/iced.1705-01-01-00000.nc
  hashes:
    binhash: 608a33451e1d76789283eb49b58f0188
    md5: 078562f1075cdca50b11e424aa43652d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ice/mice.nc
  hashes:
    binhash: 8f8c0b73dfc8fb3240e3509a53fd14be
    md5: 306537394bf7b795b24acc692adcea91
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_age.res.nc
  hashes:
    binhash: bc77cc707e1a288e1a48759f742bc8d9
    md5: d6429e50d40627008cbce30bd88ac7a3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bde277d3d306760d6263e6591998af18
    md5: 1b934509c4251e32e4f43e200b6f1097
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a6ba16c38856c9f7793993cc1acd31f8
    md5: c412f94b0d2335594893a5ea681f26a3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_density.res.nc
  hashes:
    binhash: cf88ddaa2dee829ea3619acfa13e52f2
    md5: 324ca65a7367abaf9dc69cb1004ffe32
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 15a55f3604e78dd099c30f01a5646c89
    md5: ecb9aad2b826e15c9ba5561e951a14db
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 56c7a918f8a2b8963c0c5c4c593b4f84
    md5: 3224fac3fccaceaf54ab94e7dc01f4f2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2dc6deec864bb95ee314da174e725b70
    md5: ecb22619b912de7aa492360ab29901b8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d0ac77583b202256293f8b9a4aada67f
    md5: a7579552ba53bb763c67079f032c962b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d447e9dedb5628f6c0e2664bd968ea70
    md5: de935b072a37d5a87aab022e7b026eaa
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 08ea5192b08df49facde561bff6f5e86
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_solo.res
  hashes:
    binhash: 10ce1dcc0df5cffa3f51db41a3015282
    md5: c2e81dabd6aa7a336ae6bc0074d58df8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: af708dd573d0028407ced8208136c015
    md5: 6780f8877048deb02376d980deedc2cd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 01046dce56ec8bc2b36b3dbeeb5c783a
    md5: f4975676260f4103559e751e51ae87bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_tracer.res
  hashes:
    binhash: 912b2920510d570b81112796f0530cd9
    md5: 3c775f38050c4baa98645f2fb1111eb4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_velocity.res.nc
  hashes:
    binhash: be3dc13caac13a6da85ed5c4d3f1299d
    md5: 1bb7b00775fd946df4a619e371d43ab9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a5aa736dce47d95b816cb44cc35a443
    md5: 31a864811162a7f5df844ad9a6495a10
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7c87c4f9338af3c7e2ecaf81c9ceaa95
    md5: 82b2737c082eeb4b11bbca862cacdf7d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart260/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1f8671bd88d91734da5ce1385b84056a
    md5: bd350deace9649c5ed464935a0f4d437
