format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/atmosphere/restart_dump.astart
  hashes:
    binhash: 33961c2b18678b202303635dac958b74
    md5: 12787226cf43a5dcea116b0fb05a5d14
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/atmosphere/um.res.yaml
  hashes:
    binhash: 67644ab032b0b023f0c56f9cd4a34f22
    md5: 9fe7225e53177efd47fd8def86aba031
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/coupler/a2i.nc
  hashes:
    binhash: 1025318e5144ff9a7406ea9d2364c9da
    md5: 6be60cd0f78e0a540a5f800fb2104b78
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/coupler/i2a.nc
  hashes:
    binhash: 0317d0ac094c0cc1c961981f1b0d16ad
    md5: 5bc4ba0dfd9b034080de76d9cf483e0c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/coupler/o2i.nc
  hashes:
    binhash: 9466e389dc78c7e7523a90272dc6dbb8
    md5: a4b9dc335eb58672246fe9835cd7d826
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ice/cice_in.nml
  hashes:
    binhash: d5da5afd7da52dc7f4b3903b744718e6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ice/ice.restart_file
  hashes:
    binhash: cbe425f31d51973357ff3f425747733d
    md5: 4937b450db5c77b7515398894a950b20
work/ice/RESTART/iced.0932-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ice/iced.0932-01-01-00000.nc
  hashes:
    binhash: 54f950397cb561062f9e021834035a05
    md5: 02752c69874b5dd7e8c05703dc636d81
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ice/mice.nc
  hashes:
    binhash: f982cb7c06345ac171e9ddc827f5c897
    md5: 85c437055ffa669b2b4f11873408fcec
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_age.res.nc
  hashes:
    binhash: a57b45f9e38f31998e9991af145222d0
    md5: af68e0fc8b68492517f9c255d1275e57
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8582486cd9f90224be547d7c94413bbc
    md5: 44a3bdf93bd572a7725d117da47c6bbc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f999ae939c0ad0a9df408f78084c655c
    md5: d93ecec5eae882e39bbd7749ca412d43
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_density.res.nc
  hashes:
    binhash: 2ec3cc557d07ba4a77b04c219bf7de25
    md5: 1542c227a69325edaa65346bb1a49851
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 55d2fa02d6fcc56919d9063a8b99c89d
    md5: a27b0e0c7736d3a451633ccf4789e404
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1016ce59f39e8b116ec525c0ef46973b
    md5: db4f53586a10976082b3afaa286f73d3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 831ce691e016f9d2efb335ccb4b03652
    md5: dcaf50b455779531a22082a99e0ed8c2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6f5e6d9444198c31c79b21f438cd921f
    md5: 171b89661400a7cee342446c4cd457e2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 685099045b8c066aea3d2d9206e35b06
    md5: 80b3fa009226aba31ff50b34fef97a87
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d6079326a3a3f4da4c753b11f0db943e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_solo.res
  hashes:
    binhash: edc940b8c3e54f5e6596494248ec7d06
    md5: 9e9b6ef23300e06c30983c2a7d2585c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cc99429c7956958e357a3c809173e818
    md5: be8e97474deef3f640086428a50b3486
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3437457afdf2bf55e00ea09c4ec1d96a
    md5: 853e17d7dc7b2f522082a45061ce2a93
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_tracer.res
  hashes:
    binhash: bf99bd2375cb7957ef161d355dc347f1
    md5: 61d5e72c9196cb3debe37718cd48464c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2c66ebeba7da769756df8d535012104d
    md5: e05b7ff1e9f54b9ad4574ce6d0bca83a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 424a3056d29225755dd98472ba6d7460
    md5: ce71681fd6f72a8b5c81aa8b5f2c1100
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c02fb6a9a785b1bb4d5aa722519309ec
    md5: a82d71d1878f8e012e4cf926cdba4c8b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart378/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ccb67ae26771e4de2d19a6c2324f300d
    md5: 344d1000b0d9ab93b51c6b0a7d386f7c
