format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/atmosphere/restart_dump.astart
  hashes:
    binhash: 44d47d5b7389ffec00950bb87d9048d0
    md5: 4b6a8e52314b8faf0df7a571d4ea40eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/atmosphere/um.res.yaml
  hashes:
    binhash: 891e8acbf132371575e6c52ea62e174d
    md5: e702545c4bc94f114640b49aa71a2d26
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/coupler/a2i.nc
  hashes:
    binhash: ad7fb8b6559de8c9063d280d7185ca82
    md5: 8fc2e7e4c058f7e1592547bae7a039ea
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/coupler/i2a.nc
  hashes:
    binhash: 4d3013a736b2c6b79c034e4b0cafd94a
    md5: 356666e8addb68e09e0a0e5118b71f44
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/coupler/o2i.nc
  hashes:
    binhash: 45e5079e01d4b1b033d50e6a13b9e3ac
    md5: 5ad2d7ecbf2050447c966674db694d3b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ice/cice_in.nml
  hashes:
    binhash: a5cc89c85b01469cf2cad33da74063e4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ice/ice.restart_file
  hashes:
    binhash: b21cf4f3ae1e0353e514e275889c43a6
    md5: d4ebf9f6989da4cba1c4579ebb2f18a9
work/ice/RESTART/iced.1161-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ice/iced.1161-01-01-00000.nc
  hashes:
    binhash: 42d1b2082f425237d1ea0eb069294682
    md5: be684085138e303c71bdd5ae74491d28
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ice/mice.nc
  hashes:
    binhash: fbc1ccbac4fbc0b77d75954b4bbea24f
    md5: 0a2350039d8ce027d2a183fda4c9efc4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_age.res.nc
  hashes:
    binhash: 3407220a3f9c5d1898d812f77669e17f
    md5: cc6e04e3a3e75009286922c7454c8dae
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cce64321ce6c91c77283dd0aa848d91e
    md5: c863c3c3cf66cf8856f7c0927b2d49c4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b14680107128f3a6bada9fd62a3c10e0
    md5: a87a34c7cf1b77d3cf630256c6118251
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_density.res.nc
  hashes:
    binhash: 2582b81fa762087769cf3218fe632da4
    md5: fc7e62cd05640c427e1fb2b4aeeb87af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_frazil.res.nc
  hashes:
    binhash: edc07ba2dc0d47b501008de05fc1e330
    md5: 540240e3ef2b371586da89681ee6c626
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 217688b8a480ad12f89824c7f92123b6
    md5: 958b6e9635c6928738668a60812c1f6e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 85e89d5e048baef9ed5758600615800d
    md5: 93791f603698d4662a65c76df74b0da1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9602ce95c285874a9c19520e0a03d1b5
    md5: c9ab34a088c50514f4ab8a402544b6fd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d608e5271c7ced17c96295cc86d19655
    md5: 39b37b794d595d32ce45be4f2a919ba6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f63ee0ea12eb82f4ff9735eea7436e60
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_solo.res
  hashes:
    binhash: 387fb5b266b5bf1adf9881d5f73119b6
    md5: 1b86fda328b257db789d911dbf053edd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 05bf03c2e19b146c547bca1826cbeef1
    md5: ce1a3c92d1dd891d18a722516f486a6e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cbfb48e1528c7a4338852f20ef960431
    md5: e95ee86892188df1d782c257b977d2c3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_tracer.res
  hashes:
    binhash: 6b63c02a7bc420d3ece5a05e942625e4
    md5: 9d8e4c4ed27a930f681908e179715557
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ccd9cdc45c21aa74534cc58c02ee3e7a
    md5: 45e93bf941414ef1604b8f1c274d0f38
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 57f84a248e18298675e26ccaa728cb25
    md5: c6b2950e1cc3c1d6a71061fda9b776cf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3779a48ff8ac266257b26d2d71e46cbd
    md5: 58ad610426e037a59bf480bcfa7ffc28
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart277/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: aeb7663fcb4279c188e47e737a94cd36
    md5: 1435d4807656a070e616c233776c3653
