format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/atmosphere/restart_dump.astart
  hashes:
    binhash: d267e13f9c4bef498385ac0788b7ff1e
    md5: d804707ca7b07fe27be656751e7b7cc2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/atmosphere/um.res.yaml
  hashes:
    binhash: 7982542edd4387a42be3773ce5b11235
    md5: e2ca468eda05d69e1857d882d8c01829
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/coupler/a2i.nc
  hashes:
    binhash: 5b0c25764b85800a5e6b7cf9041895a4
    md5: 185d635174d28a978f0844bff29b2980
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/coupler/i2a.nc
  hashes:
    binhash: 32c754c9a2a98d64c73967ceb57fddd3
    md5: f5129b003eeb08cf9be558d2a0dc17ef
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/coupler/o2i.nc
  hashes:
    binhash: c9b7573c282162075620e7533dde64a3
    md5: 724d511afcfa96599d7c8b2ca573a61d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ice/cice_in.nml
  hashes:
    binhash: 796f530008d6321fbf277f323d5bddc9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ice/ice.restart_file
  hashes:
    binhash: b70ff342ad034298d1f0cea7a16a1ecc
    md5: 4e0dcf0131ffb5c6fd880230c04099ab
work/ice/RESTART/iced.1225-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ice/iced.1225-01-01-00000.nc
  hashes:
    binhash: 5f177722cb74b37c626a9a0799d8c855
    md5: 8303d4be90dae4b6a21a3ff7bb6761d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ice/mice.nc
  hashes:
    binhash: b995921d55877b7e3bedd37ee4872e19
    md5: 6af9861830ae49b08400cdb4ae768ecd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_age.res.nc
  hashes:
    binhash: 99cf1f9627017400fa22cf799a4047e4
    md5: 00eae009c655c867a8efe1181d28dedf
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ab26fa215bd5062590a6e9d365189007
    md5: 1b8bf9f371df80317910e8d08c0f2ce8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f7bb0391ab0f66d73cb1873f70f4bc58
    md5: 77c23d488aa565d0f1dfb221d8667f54
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_density.res.nc
  hashes:
    binhash: 7edefab7026bd4dc3925523b7a2b7c94
    md5: fb08c9e0450bd62ef291fed0ec5f5b11
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d9b41f271d955196309fc9da66d39ed9
    md5: be2db67536404b31e22b750fe53e0d6d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 21132fe7cf97d3e7e9021a107a85d2ff
    md5: 34b8e5cda5839fe647438339f7813118
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 180dbf4a1def755205049391ae657752
    md5: 6b0379a32a45ec3394792cca94e99722
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d2f30b4d06a2db78b2da4dd4fdde2aea
    md5: e12462693e4aae3348a2e8fe798c9185
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0b4045cf9a213cdf2df5f6cbe68121a6
    md5: aa1aa2fe357a11c54d608b1f79b2249f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 34fb90d8feab54e00a3f738ab381dc6f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_solo.res
  hashes:
    binhash: 9f09fbef973d6bdde547f894a6f45aa3
    md5: 97af2776edc97a6070144d809b86af38
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 56e8ba2242c3f59f722e0db801f66b46
    md5: af581a5b8be7c612502f76d15b315a49
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 416d0f0f46deff829e7d350137f0a90a
    md5: 4c488e444334be02f7410d6e6b8da35a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_tracer.res
  hashes:
    binhash: 0b22ddbc3abbd05dd0f2eb5b53a04ed6
    md5: 8648eb598f864e9f1950686e6da93aa7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 87d70cc9a8dbf1910f676a354f468129
    md5: 3d80ce8e8e980cfd69df03d605b66b77
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ee19b62e87962ef30d0cdf790c40db31
    md5: c818a917ca5ecedfa5178e2968249cfa
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 353aebe1846d60ad392eabc4452f709a
    md5: 75c44b8188859b57472a61f7ef0e8ee0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart341/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a34ef3f28da309e8df60a7793dd35d48
    md5: 491af44f06f55bdc90ce59902c615c9f
