format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/atmosphere/restart_dump.astart
  hashes:
    binhash: 3fdb479c440fd91b56b9a8b5dda5ff11
    md5: 36c255a658637628de2a93174df3b23f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/atmosphere/um.res.yaml
  hashes:
    binhash: 09417cb072fd50d394b70ee3c4a2b994
    md5: 830c021558ef67212a184aa9d58f4475
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/coupler/a2i.nc
  hashes:
    binhash: cfc6d0a2b2699aaa4db2ae0af7bee3ba
    md5: 9b3d51ef55e3dd05a349d82f64ff8e6e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/coupler/i2a.nc
  hashes:
    binhash: c18dc52cebfdf3fec349230e037292e7
    md5: 35c03f2bafeb5f5d2e3431e13c4579d4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/coupler/o2i.nc
  hashes:
    binhash: 427656d742cff9ade05f0944dde03d56
    md5: 5bc66a4b7e63bb1b28105abc9d621319
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ice/cice_in.nml
  hashes:
    binhash: 1ae3f5547af9bb648d045c305a1ff2ff
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ice/ice.restart_file
  hashes:
    binhash: 66c7f6498778ea598cb817da0d0c9f4b
    md5: 949de8792546c134bc851dcd8663a958
work/ice/RESTART/iced.1308-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ice/iced.1308-01-01-00000.nc
  hashes:
    binhash: 5d85035e789639a9690fe5e6ff517e78
    md5: 4368ff7c7f79ddcde0f188de4d728f2a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ice/mice.nc
  hashes:
    binhash: a3f9c8df6936821b4e93b81b35223488
    md5: a65727390daf505b4a940413e1c78305
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_age.res.nc
  hashes:
    binhash: e675ea5b5c1e6cd788715174934c5086
    md5: 1e9a7488ff667a3ef83744f0d0a98754
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b68a1a492f3d878817922598edf31dda
    md5: cd9999a71eb5945a9d11454e6d701266
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e5b522331af2a0bd3f4682dc1032ad5a
    md5: c48405a32e75fc15f53c41d95b5d60a5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_density.res.nc
  hashes:
    binhash: d9ebd122cb7683acbcf2f5939b92af10
    md5: 25b4fef21c24ff184aba38ac3f7e46ff
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4de2b58230f94676d58d889db6b6d71b
    md5: 67cd5ca7d823e2648657770466309a7d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2d21b0ee5c78cc1e2d8e929d6df5ad31
    md5: c122b4eea49b44499f4f1b939f8a1798
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 54dd3342f0d6ad22648efcfe86b6e942
    md5: ac988004006e689f5a87e22da8fd8881
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1f2538c47acea375f85457e9331fae19
    md5: 46f5f311e5f821c8bb0ca637a1287a23
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 557f7a4b16bbd01f3461daa1578ccaaf
    md5: c074664f673a8db9b8cf709122edceb0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5c41563a00c3e111ed59c5a74fd1e24e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_solo.res
  hashes:
    binhash: 87e318867d7eaa4900cd27b56d2e8a47
    md5: 2deabd3924d054b5901f85d679a84b50
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 63294531a190e1744fe753b1948d9ad9
    md5: 014989b2632528248e714c7a5bd0de8c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 43db79ba0c91746114f42b4bc1803c14
    md5: 79ea11294b4dfd9db9a5b1722fa64e57
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_tracer.res
  hashes:
    binhash: dae1d8b462bbc3830ae5550c7b6771cc
    md5: 9a7f9194e1515c5413094bb003bd4218
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1778cddfefcfc60661f714a5fc68e4cf
    md5: 6675c102c0a431a6b2e7b430b4e3cd1f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6be42a252ffd0ee53c1651d4563cd2c8
    md5: 6f36f41d5c24ec7b5d2ae02cbf5f0d92
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6615feb4354c38d06edaecbb89a4aeff
    md5: e6772e7b5701e2bb36349d7de17bafc5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart424/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 877f37c5aa029e5d1c381dbcc4e932c5
    md5: 3178e379ac94b257fdd1f5b044fa0837
