format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/atmosphere/restart_dump.astart
  hashes:
    binhash: cbbc5fa60af0ee8cfbd3138821109174
    md5: 4fc3ea9228d138371b8132a0320f44fb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/atmosphere/um.res.yaml
  hashes:
    binhash: 25017fdf134ddef8ac64eba45a61cda9
    md5: 1718eb9119528743235aafb66572c342
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/coupler/a2i.nc
  hashes:
    binhash: 1762d18a1c87fecb08c7560150ae009e
    md5: d8887e9f047dbff32f858881434e0825
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/coupler/i2a.nc
  hashes:
    binhash: 1c9b20a90e4ce718bbcdb4e907d3831a
    md5: 5fc6c5aa110abd813512443e0c5d971f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/coupler/o2i.nc
  hashes:
    binhash: bdcfc72e6eebfe4dd423cfd4e589c375
    md5: 9272e07b251181d4b7e2e66d1b0f3936
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ice/cice_in.nml
  hashes:
    binhash: e85b30a8fa9b5274b472fc5e87172ac1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ice/ice.restart_file
  hashes:
    binhash: b5b07c54fa3af7ede24260d5bc47cb4a
    md5: 60542e910087aed18cf7fb8835d1a539
work/ice/RESTART/iced.0968-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ice/iced.0968-01-01-00000.nc
  hashes:
    binhash: 6cea2e77d3612cf053aeaae621409780
    md5: fd9f97550d9633b5172eae4cb39a9438
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ice/mice.nc
  hashes:
    binhash: efb65b2ebe366f5cb3345ba87f54f0bb
    md5: 92cfdb6638279f1d6dd7cb718e31dcc1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_age.res.nc
  hashes:
    binhash: 934368f0cb0f909e2acaa8453d4be320
    md5: 3aae8500deb58dc99b74ce0612ccb442
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b5941911e791c1415e99a7ecc7960e08
    md5: 86e78e7550701a38062da405f9c789a0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cdfd6f39eb7b8526ae801f56fcf3da86
    md5: 5d2559c4ceddc9e3c8b8e2ed8c489114
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_density.res.nc
  hashes:
    binhash: 1136ac79d2fb82839d8bb01446f45c32
    md5: 4463a430eedc3b6921ab54caa97fa989
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e09b1038dd3e7d95559e7e1812fa90d8
    md5: d79d283482041818cd315a16d8615c0f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 91859d7a6bb38d15c7d6fbddffbaba6c
    md5: 07cd48511b02044017d7a0454ea7802e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a80afcddb4ba59f875d8c198594b54e7
    md5: b15d4200deafd08039007c3b19f5bdec
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 165c1a9e5224dde5daa3d1aa1318f996
    md5: 0aacf248e9d2359348b700cbec55a2c6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 48ebae1fcc055c6eb42532815c5bb82d
    md5: 7e4acfdbde4c4999aaaa024f87ff4aa4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 02f51e054ee37aca54d4330ed7539efd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_solo.res
  hashes:
    binhash: 6a9a4d8442bd6c125e4d1192325fc79b
    md5: bc0e93591a0d682a13e5d4c50a9474e2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d4f32460fe6b86aae1afb24f5e9935c7
    md5: 7875f25ff71f98fbbfa41229832b92f6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 37ab891b079baa31b59d52feef191bea
    md5: 2fdc13fabcdd87e42fd01aca3e915468
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_tracer.res
  hashes:
    binhash: 27af78e883257451a0f7327f1fb0e9a3
    md5: 2ed2286d9ee4fa4ea4abce508aa2b41f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 01feeb4a1960ab7835d489f9582635d9
    md5: 42499d6ff1dc5fe5ae80dc176705f77f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: afdca829090c4df3d9081f3414ff611d
    md5: 82c3ae44d30697faa767a6209d9f3e6f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5be90c3acfd0f556193e38ddb6dc8cf4
    md5: 13967e9dfa77e60ccef18df4a076cee5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart414/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1fef745deb9a677a8fbc37ab56f823c1
    md5: b0c741bdb4a0ab4ad84790467085a8cd
