format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/atmosphere/restart_dump.astart
  hashes:
    binhash: 141796521ea47a874d4cd7b5dc88782f
    md5: f5ae3db340662240066f434bf4bad99f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/atmosphere/um.res.yaml
  hashes:
    binhash: 473b1d150fe0e7e2fc6630e3cb32a173
    md5: 870f23e2c430e9638e76fb8a70ffad26
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/coupler/a2i.nc
  hashes:
    binhash: fef5c63562afbe4a2ce2bc05ebf66726
    md5: 2d8e016860e33753f70ebc724ddb84bf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/coupler/i2a.nc
  hashes:
    binhash: 1781266e73cb622824b7c26969d5c8a5
    md5: 4dac0df8b12c634aaec5ee0572c4737e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/coupler/o2i.nc
  hashes:
    binhash: 12956dbdc50c15dd7c137878f9a79370
    md5: 2c5f32a4aa08227adb0454d1f6b468d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ice/cice_in.nml
  hashes:
    binhash: a8931facab4cae5e442048d873da5d31
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ice/ice.restart_file
  hashes:
    binhash: f600e55426ba471b9424a11e214083cc
    md5: aab5191de0cf3df5c7b675cfe6f47135
work/ice/RESTART/iced.1263-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ice/iced.1263-01-01-00000.nc
  hashes:
    binhash: 37101e901cb8e710b1530cf8ab53746b
    md5: 15d26e2fdbc97e88f8aca10db9ba9032
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ice/mice.nc
  hashes:
    binhash: 3d85e1e9c3a8b66ddc17bf9e87176cc1
    md5: 4942ca919d0ea5500ea29fc11adcadaf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_age.res.nc
  hashes:
    binhash: ad2a518f9cdc4e85ad893aaf743fe639
    md5: a83e7b3d8987be38518f25d423e7d81d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 12a4f967ea3f6a0a7736005924bbf08e
    md5: 862176d5141329ce7f7c3c4d9e77b5f8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: be117e8b7217288ffd554b52a92246d4
    md5: 487a8224d6cfa4bfc5ed97db910f6324
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_density.res.nc
  hashes:
    binhash: 7e6a000585f1e54ea2b50972ce8a4d8d
    md5: 2df249fa5b373959096d9c348033fd74
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 96a1b5217d41e483128349181c8a6adb
    md5: 3eed0edc4f031a0e9f64cc0457c08701
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d5f37926307b48a5800317b3a5b94a39
    md5: f59680703f9ce7a08acf0761f4596d8a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c201e5d3026aa926ac4d365d5fb6efbc
    md5: 5f61bb254e5354a58c5f7afef384addc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d9830058e5dfea8c2ac0f819e4cb0267
    md5: 2b3652f2e811909b3e15b968a3e30ae1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dc1dceb99eadfe52adbce93560e8ba90
    md5: 9559a5b976db8bcbf49fe0f34eb6fdb0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1ab643acf362ed534fdabb4cdc64e599
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_solo.res
  hashes:
    binhash: 768562770a2fe8c5d80e96aec0be76ab
    md5: 2d38f8705e1ed0a716b6880a81159791
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b1b059b7a00c4d7a80a646eb2783868a
    md5: 37f088d1e0fef71dd5a820a1d1316424
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bfa219dbfd3fa2decb609f460ce78b8d
    md5: 4ed430fcac747457f06e5d5f525984c0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_tracer.res
  hashes:
    binhash: 52ae76c90b6d7c960c18e35dba7c9cba
    md5: 285cc261e0b45f837bf689ad3a470118
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c6c3ae6021f6b5a431b9fa813083f835
    md5: baccc6e932f55b03dd78dabb9ed70328
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b58ccb8d7760e2d80a8268be47b9af57
    md5: c0f29ad409399caac0f89a18d2174c6b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ad5c76c28b3d490625ef09953d0d7154
    md5: f87ae560bef402f1c3fb8e1e9d509a96
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart379/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9ac83690ca688d2255ee88c018a66594
    md5: 47c9f3d426ad339cf89cf01c5611322a
