format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/atmosphere/restart_dump.astart
  hashes:
    binhash: 99429dbba46e933c4c7841a64e0a9b82
    md5: e098e21b33e7effc81662f65f8d9e530
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/atmosphere/um.res.yaml
  hashes:
    binhash: 0c7e9309df32f5fd1359389feea61ed0
    md5: 3c410aaf3cedf20596bd2d488799e641
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/coupler/a2i.nc
  hashes:
    binhash: 3b458638e5ca26f891f60c7482fddd4e
    md5: 18f7c3ee70ac4a6b51c0fc2625633e5a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/coupler/i2a.nc
  hashes:
    binhash: 8922576adeebfd6598b3a13f9bc6502c
    md5: 1906a77b286875a7325020f5de019900
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/coupler/o2i.nc
  hashes:
    binhash: 1d67c5cba182b758734479f0b817eb4f
    md5: e0c2b7256f786ea38caf6249fa837326
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ice/cice_in.nml
  hashes:
    binhash: 6b0f2216594ce91aa8f37aee665f39b6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ice/ice.restart_file
  hashes:
    binhash: f2cc5084641b1010599765eca816f767
    md5: 4c2013c7234c00239357a31881c347d8
work/ice/RESTART/iced.1232-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ice/iced.1232-01-01-00000.nc
  hashes:
    binhash: 50dcfa230a7a6a8b9d1c54cd2c93edc5
    md5: 4cd2aaed5197c7c8fdd55a02813a63b1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ice/mice.nc
  hashes:
    binhash: 065db5b34dc7a0ecea60bf361a067a7f
    md5: b639cff1bf7518a4f059802a3e62d757
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_age.res.nc
  hashes:
    binhash: 50e88cf152edbc8dfc73ce25f2fd00d5
    md5: 5e1e473339d7f91debc43550d1d8de6e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 95e38ee32c180bce237ea2e7b38d50c3
    md5: 69a55a41fe64f7a3f553a5aa346b1733
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ea011f8f6fa68c1c18ac6aed8ed71bc2
    md5: cece2437bcac59388c134716be8b5a19
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_density.res.nc
  hashes:
    binhash: 9d71027e546b9bdb309c99b0056dd3ec
    md5: 67d70b3ea79514bf2607a9021c249cc6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6a73035a6aa5f0f6c821ad5a1e412eb1
    md5: a688b77e74bd1aa6256e6a8bf9d37df4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 969ee4291c871263726ff73ffdf10efc
    md5: b146eba06b752b62f4c3f0c067e3292e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0e381260549dc11040f01e9bcad43219
    md5: 1bf2e522eb9d6ceee1217b0611908a09
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f827fa491ffeaa587a345468f60be0fd
    md5: b491f482349a5eb046ff65e77561ff47
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a9c462a5fd29e8874480138eaed1e945
    md5: 9934645c1cef1ffa90761c5a6a85236e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8cce9b36c10cd1c556af93f99933ab2a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_solo.res
  hashes:
    binhash: ae3b24bbd62162570dd89591ce49df4e
    md5: 2cb5e151c6c0a4b22826bb0842bb756a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c0f04d4675ae75018322278405ccf303
    md5: 894947328b18fe541b1e8f336fa4fde1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e2c3540d595af960baf04e5a72e1783
    md5: a5393bbe50139a962c68dff24c163f14
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_tracer.res
  hashes:
    binhash: eceb199d6e676b4fb999c08261d8312f
    md5: e96585215d5f084cfbc7f3fb21a3b455
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9e8c6d3a7fcf29669c99ff26a5fe9ec1
    md5: 270fc27f16dd7aa870a55c06fafd36f7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6f39c5bc2f2dcf2dcd0b350cfde5c728
    md5: 3ef0039cea589e663c2b1673936d3f5e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f4d0c612866d05cc34d4985d97328011
    md5: 338dc01b30fbdc471dfc2681a5f13580
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart348/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fd1dd928d476fa1d95926d4054ac8b08
    md5: a7c3535fd7b6301272fcb854cddfca23
