format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/atmosphere/restart_dump.astart
  hashes:
    binhash: 951304dcc62ca54084912951e78731aa
    md5: 5573faa01a7033055ea3852f7fabea37
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/atmosphere/um.res.yaml
  hashes:
    binhash: 1ec44f7d347d81de93f2cbcb390444e7
    md5: 8b807db1e7bd4989b4076879383f69dc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/coupler/a2i.nc
  hashes:
    binhash: b24bc56f2602bb6b3bff851e37e73052
    md5: 4d2f5b9deec6f3c947543c17b2a46fbc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/coupler/i2a.nc
  hashes:
    binhash: 0d7269d2d4470df622ef11e2240a01c4
    md5: c5ffd08a85d6153324163e0529fe11e2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/coupler/o2i.nc
  hashes:
    binhash: c1ee83105f439016b38795325a247e30
    md5: 0dcfe56f4ca67c9c832501ccd65faf99
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ice/cice_in.nml
  hashes:
    binhash: f1450fca31f937b7c6c2b3c2ac8f8603
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ice/ice.restart_file
  hashes:
    binhash: e5b52e04413d73185b2ddc3d2ed9cfa1
    md5: b01ba4f7a681d8fc6a9cf58dedc79dc9
work/ice/RESTART/iced.1845-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ice/iced.1845-01-01-00000.nc
  hashes:
    binhash: 42244ca1954d53e56f1c67cc8729f3fd
    md5: c315b3867f6a15e926414fa0ed6bfd50
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ice/mice.nc
  hashes:
    binhash: 6d85286c948659c992fe61eec60a3266
    md5: c8f0768a8e166593614839df6508c14e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_age.res.nc
  hashes:
    binhash: b6a5e04e0dd0b879d473136a7fab14e2
    md5: 59977fd17004e1ee4ee7d832c52a6a82
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 49a6d6e562b979730c2b9787273bb390
    md5: f21e4fe05e56681d7e35263b50c838f8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1cc1c387acc08b8241e40909ce9a8413
    md5: 8a1871e818e71da1847aa08436fa3929
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_density.res.nc
  hashes:
    binhash: f67de1b08e963bec5c4eb92b0db3c424
    md5: 37218df7df07fc71a9b5dcb8d8aede64
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2464f4a6edf851f89b997e66b7d33955
    md5: 16974b92cff3c0ed8a034d66eeb0acc7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c3ff01211ac24c9695afeb0920b715cc
    md5: 869f014a0a147cce9d2c8fc459d8464d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 93aadd4a331f31b925001c1053454641
    md5: 4236ed250fa6314617a0b6ef129a2d06
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ae99d2aade06b1f082dbd7945d70cd59
    md5: 3045157142a68968e67d9c260506c46d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5422513ae27627434a1a7b454990e542
    md5: ddaf7fc9d499bdcbbaa64099bfe2ed1f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f2897f1848c9a8f3994a176e40ee5312
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_solo.res
  hashes:
    binhash: 00d58c00837b578d24a0a290e97da904
    md5: 249648d7755c7b971369961f5629401b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 41c724a6b9f581217236ea514450846d
    md5: 5791d964bdebb040c0980e4b252658bc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 59d533ea3ffe55d56c5425b21fd1b815
    md5: 9332af7bd4f8dbd3b37fc50e92d536b3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_tracer.res
  hashes:
    binhash: 204caf506c62adb42c68697390b7a784
    md5: dc11310a3f67bf9b75987d33fa3b6107
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e2d19fab065c3781a615d30534129527
    md5: a6bc65f252716fea58f9d27d4482bace
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 849611822a9a3d17ac46436529b7a43e
    md5: 41e70b076d3ef314b3e360d71a67b355
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 827ba72bad371bd0045df595287e7b86
    md5: 8ac407e99a2f86e1076fbc956c4e2688
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart400/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b49067babffc5491d459ea53d15fd20e
    md5: 05f5a62f8ab521667b51770b653ad645
