format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/atmosphere/restart_dump.astart
  hashes:
    binhash: 1959e912052b2452bc167047e77785d5
    md5: 59a8315d7775e364bf0b8e518a597f61
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/atmosphere/um.res.yaml
  hashes:
    binhash: a921ffc7f75bf332578a4f3c6269fce7
    md5: 6c89603d20c83e1b2797bdf19c8f56a7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/coupler/a2i.nc
  hashes:
    binhash: 1524abaa4876d0413d03427987e53fc0
    md5: 4cfd5780cf046ee14f419ec0ac0889fd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/coupler/i2a.nc
  hashes:
    binhash: 1bb080ec56188bf739009f12e5dde87a
    md5: 0df1e8fbee01e37744d256782171eae5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/coupler/o2i.nc
  hashes:
    binhash: 369870d1b087ce95a45091d21b299eda
    md5: 01fece99af9ad489b9c4c282285a4bfc
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ice/cice_in.nml
  hashes:
    binhash: 0d19235ae16e884843401319bfb4a075
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ice/ice.restart_file
  hashes:
    binhash: 6bd5fb8274128d8d9a83dfd2b60d48bc
    md5: e370a22e409057891259106994f8da1c
work/ice/RESTART/iced.0840-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ice/iced.0840-01-01-00000.nc
  hashes:
    binhash: 2c54c8d84fdd89f84eae40d61326f92a
    md5: 4a6e56706329bb32a4bff4a62b4c6606
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ice/mice.nc
  hashes:
    binhash: b12d60e02fc323408b46e60b3416bb85
    md5: 4ecd9b750f89dffc129b44a8a2b20098
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_age.res.nc
  hashes:
    binhash: b5a43fd2bfede3db5e693c18b5340651
    md5: 4cbb493ba7308215711ba129d958f4f2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2e0a08642132df6e6bb5139a8067c376
    md5: e2297e6735dd231e5ba29a95f91ab362
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 618dc65d077e4923008c1c19a0669423
    md5: b4d094f9406c349f439ca9d29f963242
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_density.res.nc
  hashes:
    binhash: 4b83116cfcea42f95fd8d1fff19ff9ca
    md5: cdc724613f01bcdd770555266a9cf5a3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 715170ddd38174e5ba8f2bc4b5a2cca4
    md5: b7589b05d9527cbc6fa04f4c470a4633
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5ac76cde0ec6bcb729e5c60455bc4f6f
    md5: 5442ec38dd5818c3756f90f2fd219db3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8bb4c84e4a972fbb7e6e0b5f1a7666b5
    md5: 03698933ab01ef434ef887453f198501
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bb4cc57f6d8c97d0282552c6dd942bb1
    md5: 6aae0107f2615f2d51bcd84a617cae32
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c699f076217fbe7d10cc3cefa037d9a5
    md5: ea7656a06cf9c77fd48d9116a5ed1f60
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 26f40772bd6923e9fb18dd46a6047083
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_solo.res
  hashes:
    binhash: dbb7c1df27bacf092e7f3d2d59abfb4c
    md5: 6d2662c2c6f9360c570f053a66040aa2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dc795717cca677d5f99c26873159bcb8
    md5: 4cb6581c8db6dca7f91fa97ba56eb6e0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cd08588fb809d787539c986ce3eb7bad
    md5: cd944c5fb03828ecbee88e7190335527
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_tracer.res
  hashes:
    binhash: 85059ed77110fda700b65bdeb80bb2ce
    md5: 8b2e7930d9c637e7a87a91f678a8b111
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d83f008e47414cbb53eb4b5693795cab
    md5: 09ab4621b565b2c752375f279e341a86
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: daef5a37355c1231d52bb1c3441031f3
    md5: 9124fd20d55e8fe7b9caf251b7272451
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0127c1915ddf74b1df58d8b6cf90e4eb
    md5: f9b298c14cec4fc2f24786f4dda71ed5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart286/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bfc5e98cb3b1569a0c4853d957bc6fd0
    md5: 755c22a59d47d18487e591f321a0ea8c
