format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/atmosphere/restart_dump.astart
  hashes:
    binhash: 8f726d0487701479706ffb1d8ef64328
    md5: b53967b447b84a09d5307ecb4f91fb82
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/atmosphere/um.res.yaml
  hashes:
    binhash: ef1b473bcc573d2f8d145ba0c43351b6
    md5: 9cf96962da32350163c25ff3853407d0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/coupler/a2i.nc
  hashes:
    binhash: 28fb5db7fb77018fc0e80c45af08ef51
    md5: fe2f804d733b7ad084ab8f5c5ab42cbb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/coupler/i2a.nc
  hashes:
    binhash: 763cd98b5fc548456054e47e0e9b2121
    md5: 88f33702ee9531e35e5a45ac745f44f3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/coupler/o2i.nc
  hashes:
    binhash: bc56e1a6fd853a1a3c0c50e817aeaadf
    md5: 0a89d7d28f20f17a290ae98dd529bdf9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ice/cice_in.nml
  hashes:
    binhash: 18ec48dbcff1bfe563ea7dedb227b7e2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ice/ice.restart_file
  hashes:
    binhash: 62e310f6b10506218b7d78d2b5ee7ee5
    md5: a05e11df4a33976164e56485ac6b97de
work/ice/RESTART/iced.1245-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ice/iced.1245-01-01-00000.nc
  hashes:
    binhash: bb4adb283b16cf8f3ebd11f412d5a421
    md5: 63e487af81da973c9c3708565d3cab9e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ice/mice.nc
  hashes:
    binhash: 1ee41fd2d5fea1b57061eb81a006ee97
    md5: eb4fbe22a1869eaa70a6a33d970798e9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_age.res.nc
  hashes:
    binhash: befc25168e996baf3c5002868b37877f
    md5: 4e867ad745293163021b6d8e5cfe673e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b2672f3dc4c2d5003f13fcd9e5c738dc
    md5: 14f6433224b2e89bd10fcc51386fb478
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cac90fa517fc32e1025b9d620343051c
    md5: 52e6ef8e6e796c1934afe75b6f3bf4a7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_density.res.nc
  hashes:
    binhash: cea7f2434a948705f0aa4420214b6a03
    md5: 550166ac92d1ec682d7e7629c4742d97
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b45c18495d9f42f6fd3345b93dd0a75a
    md5: 322f455697cb27da4e62442a79cb8376
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 00d6fe0e28b8dec569820586dddcc1e0
    md5: afd29582d4cd7a798b696f7158695d8e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5b228aad7fd4cb6efdd8f28f3a8da081
    md5: 5dec9d123e2591874df8d6d899ef1bcf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 22b56e80f7b4b002711f4ae55bfd84cd
    md5: 38546c317482d9cb5da7c54b549a2fe0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 09e5d371164d2105c1820b26f5e3b047
    md5: 738f959aef3eb4f4aa5ce21cf475d88c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 42c5e92173174878a89fb3b634f0e4fe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_solo.res
  hashes:
    binhash: 60f7bb9970e389c40bab8f59ec47caa8
    md5: 90f7c5b37a5eda32e47b2a7265e5afbc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2543b44e5b22bf3d80bced23252a5391
    md5: 9bb708957620ab1b020ab75d437e630d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d12a5fb5e49c03ffa4efd84bd54eb6ed
    md5: 2927de0d3ad39bd5c0750ad199a1ab9e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_tracer.res
  hashes:
    binhash: 7f3f1d4bf91f2ace972f3eb48b9a8020
    md5: 1560cb9cb04859b1186c6e0ef6083166
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 325770452cc412063cec8c3359865978
    md5: a18171bda7a8ae94e15b5a4249ea494b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 147bcbc51b25a2756c6a8cb0f992fb98
    md5: 4bc792074425e17bb3c5f1fd4cc9c652
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2b9b2fb428f27b506a0b919aee8458ed
    md5: 4f8eaf0b8e90165ad207030a6d88ed91
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart361/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1770f743247a08982eedb0454e7920ce
    md5: bf7b8c4677576970823790d0a23caf78
