format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/atmosphere/restart_dump.astart
  hashes:
    binhash: ec5fd39ee9c3e6b47fe3dbd2fea8e657
    md5: 5430599036df277f3795a1ec6c709f3f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/atmosphere/um.res.yaml
  hashes:
    binhash: c4b207536c5cfbd0850274845ee1c61c
    md5: 534be9232433c13ee40f505d44136b07
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/coupler/a2i.nc
  hashes:
    binhash: 37e9254a9a57ef851e5d142324f57dad
    md5: 849732feabb541501aed223305b87316
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/coupler/i2a.nc
  hashes:
    binhash: 6494dcfd56a5780f9330ea9a2ae65f75
    md5: 7639d9cf51fb9269b6a1e06ba93f64a7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/coupler/o2i.nc
  hashes:
    binhash: 92309f10dbc6f9837cb85513bb3cf910
    md5: 3f36100d99f078a6eaaf6106c7e36da3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ice/cice_in.nml
  hashes:
    binhash: f9a1d25e2eee16de4feae898b37a7139
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ice/ice.restart_file
  hashes:
    binhash: 24aa4cec02840ade83c8d2e25503dbf2
    md5: 4671844dd576d66b50b9688ce75574bc
work/ice/RESTART/iced.1254-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ice/iced.1254-01-01-00000.nc
  hashes:
    binhash: c00625e32a30516e35913547f3c6cbf2
    md5: 08e5ba123c0618a230b7bcf541bb3565
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ice/mice.nc
  hashes:
    binhash: ff23d1f3896042cfa28750e2d7eddbe5
    md5: 15f3407859237e564908cc5d7326bb61
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_age.res.nc
  hashes:
    binhash: 108e0a583b9ecb19da57c05b12dd5e58
    md5: e692b5031db1bc0b5a0920c5e26e7c38
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 569a365767cbc17169cbf0d6bdb4a39a
    md5: fe14fd13600c8e6c9d1cf883b6ed706d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a392af80893e1b120975476148c72928
    md5: fd44e3e77d8fdc67e8b033d52f71891c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_density.res.nc
  hashes:
    binhash: 18d447c62f10adbe579c933343f90e29
    md5: e7780914e42c30af4c0a0859e92214cd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4a2cf1041c06fce9218ba366a34f444a
    md5: 0eeb2463ae544d6f0f810aab4adf170b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b53bff97f455bcd4c4cbea9ca191f1b8
    md5: f5e69bfd3f6547b381e2395c19fe7881
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2fb5f8e3aab78b74109ef1ab37a54083
    md5: 095e2d8faa27ad7e69bce2ed9f8dbb7d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0b606b994047f0cca69e6c511a830431
    md5: 2caa9f5a57df2ae8db18046a25cd48e0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5b6d7b51a13f0fc230b3ca0eb6441442
    md5: 18cdb45a0938cfffa4caa23a48a20b3b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 556cf00e43c238f07f8994d6ef1dade3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_solo.res
  hashes:
    binhash: 38f3373b09b8eb72d6c81fb81bf6f452
    md5: 92595ea292612b4427ca4c382c8ea85e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 85f5b091ab24de7884ab7e5060d8edcd
    md5: 1cd73230add405c01ab690be9f36485b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 97c1ac08be5819f70657387b7c979684
    md5: bd6976e8665d2b95e5baacb01bbca0f6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_tracer.res
  hashes:
    binhash: 852bf943850c0c1c13fa2f5f850ef246
    md5: 949ebc102050b76ac6c1014f6a8c6248
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cc86b6364772bf76a875ccfad6258949
    md5: 6497c5794c1a43273b443d29e1470f72
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a6845289ae9f78ece26058dee129150c
    md5: c8dd548af8e0e45619c2e5f1a693e3e2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 63a08b29474feea62e75187e29d35657
    md5: 5a877fc22da6a51ab84a3bff6db50919
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart370/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 94688bf381cfabdfbcb3c4d9e3e477bb
    md5: b5f793ce72e254154d92c006fe1b01b2
