format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/atmosphere/restart_dump.astart
  hashes:
    binhash: 5afaf09f2092c4f76d7517a4d65f2e17
    md5: 8015de642a1d491b26668bfa3ef5bce1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/atmosphere/um.res.yaml
  hashes:
    binhash: bfb79e620ef4866848cae7b167d0e921
    md5: cbfa24942779356a6a91ad5b7a7359a0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/coupler/a2i.nc
  hashes:
    binhash: 3d7845bab8258e90caee33f1207d143f
    md5: 4ed60b4c7a709f1e9a8d278cccaf7bc6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/coupler/i2a.nc
  hashes:
    binhash: d36263edbd6aa2fd99bd3954add48163
    md5: a56cff2cc2aaad52b2d6394187170cdc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/coupler/o2i.nc
  hashes:
    binhash: 3095105ce25d4970c3b10e74f3443e8f
    md5: 2eee20124b1a16f557a31d1665849ce3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ice/cice_in.nml
  hashes:
    binhash: 078c31ae8531fc85aec9ea841416b60c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ice/ice.restart_file
  hashes:
    binhash: c0f717f3bdc724992b0a762cd36405b6
    md5: 9aae1b3c526d93d39370e6fb1abb89a6
work/ice/RESTART/iced.1800-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ice/iced.1800-01-01-00000.nc
  hashes:
    binhash: 9e4b4bc8760e17b924236f992077cb4f
    md5: 0c441f72f7d4e02ffbdefc315ac3500f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ice/mice.nc
  hashes:
    binhash: 76148cae4f079c599f4e88a305537b98
    md5: 26d146064ac19e0940975ae9fa64c1dc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_age.res.nc
  hashes:
    binhash: accae6166da0fcd9adc97762aec9b857
    md5: 5e6c667da030f1db593f00fb770e1e8f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2150fb64a2c7df08db913c46711bbe5d
    md5: 56287f6be1f252ff0306759a2d95786b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c11fc0dd8801ae0f38a4dae4300aba96
    md5: 1b22ab728d89b627ebe05a25c59f4819
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_density.res.nc
  hashes:
    binhash: 01455add43ba7843276e1ec771c8d402
    md5: fb13a26fb1467ecc55434a7854fad58b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 022236023436d99553344300748ebdb7
    md5: e53a3dbe21a0b4103a1a7d3dca47857b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1b756be20576000134654af82f0eb93a
    md5: 1765ba51856e44d6fe5e432c4231addc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c8621aab6361b3d053a25833428d85af
    md5: 9ea7e831b91df6a444de1d70daaab568
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 24ab940b3af79fb7af1168f7da509dc2
    md5: 15768df017208f99e0381ebc791f4a29
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 47b237eb96ae6b2841878e4d6be9c4f9
    md5: b8a4f5c6e12dc4c275dbcd7125ca54e0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b71866982acbfa4cb1d871e089de346a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_solo.res
  hashes:
    binhash: 0052b281814d0289db11126881ae0b96
    md5: 36a93554976b1642faec48828e371b0d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 432dae4f989c761e087881515843cdd8
    md5: b0da2734e5b9a113f304ebd926eb7bb6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 48a36dbc4d329171c14ea95f9e2a71fa
    md5: 29e72d9fd70e5e46ce19b89840cf2bbd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_tracer.res
  hashes:
    binhash: 0b42e9320be50a079b559da36a6d37ea
    md5: 7e3ece1340bbc9006893f3dc5c166ae3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a3f47a22f8e098b5e6ce959a0b013fff
    md5: ab698ae9c8673b656853bfac64db713d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f1d6a86b92d031a7ceb4a034ccb266a8
    md5: a512ddbf93b0cfdfa6ec89665dbb08ce
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 19784e472f36d4bb2b80158308d02df6
    md5: 660d5fd3ff5b513d7285ca454c22b0ef
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart355/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d816956952edb127cb1d76c9167d9e77
    md5: 04622fde6d63f57161f492bb72c259ed
