format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/atmosphere/restart_dump.astart
  hashes:
    binhash: e9f4ad93e6b480e74c74f52b847b05b9
    md5: 928fd6e09202ec74a5c1deecf2e8d394
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/atmosphere/um.res.yaml
  hashes:
    binhash: 31f4c0416b3c48a03d789be3bc065765
    md5: 9e3c8a8e539070132c940d39fbf25670
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/coupler/a2i.nc
  hashes:
    binhash: 2f32f43c87b719101444caecf0453756
    md5: eaae704afd55dccc07d5342f620d9bd2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/coupler/i2a.nc
  hashes:
    binhash: 56892d5644f4b5d2d8efb9eb0f08d9de
    md5: 5ec1981b6213664d089fc6ffb0098940
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/coupler/o2i.nc
  hashes:
    binhash: 8adfa2133fbd503b8e74442d25dcf805
    md5: 4caf53f31ad1a92b405d01d55e6fd43f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ice/cice_in.nml
  hashes:
    binhash: d5bac84324fd3a8a35af945ef00cc03a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ice/ice.restart_file
  hashes:
    binhash: 1116027125289d78de5a4f0027c897ed
    md5: 46586c110436d0a0a84d5d3256966885
work/ice/RESTART/iced.0890-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ice/iced.0890-01-01-00000.nc
  hashes:
    binhash: 30c4f8d92cca829cd0f9a7d13171d035
    md5: 289840c3944d3ff1788d190adbd2f8d0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ice/mice.nc
  hashes:
    binhash: 593b3aa447817dfe6554da890049ad85
    md5: 35c1d90b53565ea12b206854139f3ebe
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_age.res.nc
  hashes:
    binhash: 1ce2b0c420ef95bbd5547c7e9af6a43b
    md5: bd78f89afb1641436b4b599d9a677b74
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3b3f43eb41a80a17e299c508a7128965
    md5: b388689c33869746169e4fc56c2cc303
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 588a1f8a9757716e1e142e6f86787d85
    md5: 8e560f1bd99bfe2439e7c35c040cd664
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_density.res.nc
  hashes:
    binhash: 185ddb1d2286dccbabcb5cc8e20c94f3
    md5: 438fc2c4d30f4c2a97ed7edc872be12b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8273bac3a1b6daf3d01b625fe9b1b1f1
    md5: bb553894c42223148d10cefe6eed2401
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 736e84e34ed8054c6abf2baa48a6fe37
    md5: 064c9da97e695af423b7f2c56508998a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 584db328db12733bd3495f4564b086fe
    md5: b000473964d976b3298d8b81e11c85c2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d7a8b00239d878fd34d98cb25315e0b0
    md5: bc12a4b7f9115e303878402da09e979d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a030ed0464225c9052277180803753cb
    md5: d1d731701362fc00166d95e03ab0ece4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d25c324245f6879ebb75938310037b99
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_solo.res
  hashes:
    binhash: ec1ad3ac6885b5019f2142a00953c57c
    md5: 4e5482d05161d4caff1e448d6b9ee309
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 06460387234fadf58e79b5571316a3c5
    md5: d6035818f9a3fc7378d875c4a9424745
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b1434e1565dc440e9bf511e68a2a464c
    md5: 4fa7802ebd570350b107576a008ff357
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_tracer.res
  hashes:
    binhash: 2efb0ff81789071f07bf37434d9772c0
    md5: 8e4e11d0fd9d6b1160a4fc623944c9ec
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2196d33c40aac8c6d9a6967acdbd6756
    md5: ad886f6c5028605e9f11027aea134ea4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dc14753a6133686c2f23bd20bfaec06b
    md5: 428e133f5393c27fb25296802d41972b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6f38b18870afef77db3764b5d6307a4f
    md5: b01b38dc4763ce265d274580ff526d96
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart336/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bd10012f02b09ea31eec504740d39332
    md5: c585f27d0ba7f2cc813fbf0201b75c80
