format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/atmosphere/restart_dump.astart
  hashes:
    binhash: d919caff49b5b6e1212ad4ff5eddf0be
    md5: e7d4afcc568765f57ff9dc4036a7d9db
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/atmosphere/um.res.yaml
  hashes:
    binhash: ee9204e3f7ac54aef0c8380d9bd4b5a1
    md5: b9f00200b0b7659ccba75412181351b5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/coupler/a2i.nc
  hashes:
    binhash: 3ad425d5d04b04bfedcf87ef40dae4c1
    md5: 90befc85d017cddfd68b21a0fe4f8aaf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/coupler/i2a.nc
  hashes:
    binhash: 4e0e349c630ea5c15cce7209524ac613
    md5: 6a9534a2b45ab6c4b8f0dc3a4b18f7e5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/coupler/o2i.nc
  hashes:
    binhash: 15cecab3f5abdc8a08f12ed7b54acdcf
    md5: 8773b857181c915c6add3cd3cbfa6c82
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ice/cice_in.nml
  hashes:
    binhash: 7cebe3ff26a319cbd1ede64d3472f807
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ice/ice.restart_file
  hashes:
    binhash: 6bdd3241e2fdb7ac36fd159fef2e0a39
    md5: 8fe3dba5548f33f9366c5987d6ab1cd3
work/ice/RESTART/iced.0854-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ice/iced.0854-01-01-00000.nc
  hashes:
    binhash: ac8d1cd46a507d2b1f7507fd09504039
    md5: 1f2c09fd6116f4a577cc9d04b3ce5576
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ice/mice.nc
  hashes:
    binhash: b8b1718da0f23dd952bae65d71a3b5fd
    md5: 8ffc75402b32209a05dfa7bd7ae51fc0
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_age.res.nc
  hashes:
    binhash: adf16c65e2386ce7b61cdc411e57f1e8
    md5: 37fa68d9f7e55b3c35cb717f82598190
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 94f47505114ec9f735e828698a39d962
    md5: 4d65de3692437a8a93c92542ebfbfd2d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 57f97c0ca3cb882715d34fbb33a066d2
    md5: a8e6828ce5937dece8d84ae4750db029
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_density.res.nc
  hashes:
    binhash: 663d42b33d3936af0ba1c7efc82954b9
    md5: 3862d7ca30c228f7eaf24d53e06d15f4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 25812f80aca067d2757e5f479cc78805
    md5: aabde0e11dcc6e9a35ea9dd6540b5682
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 514b29fbe96ed02bca4ada4594daa962
    md5: d34a88f1dbf3b1b1936fd9d1f4be22ef
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2bc46ce8911911695032ed9bc6e58ec5
    md5: c0bb0e084a3cbb53a9e42dab62a558ff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fa2db2c2a543c34a18e80d00fa948b7e
    md5: d900b3f1d7e1e295e556d19ee7453ed3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a497b7ccf3cd237bbdbdcb640b29f924
    md5: f2c715f7fde41737c83cb4c888c2668d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c670aafc43a52a6518909f95089bd918
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_solo.res
  hashes:
    binhash: eba1e39bb251697f533296b9d13e48c8
    md5: 8491c1b1fd0d88062da9bd8a66f170d1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 76a2820284ce5c5767f89e8e2807c7de
    md5: 88de67b962a5fa494f2a72f8155567fb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b10780d7cdae8e45cb5601a6774fab5d
    md5: 391459494cf74c6bc2f6a70a5eb35726
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_tracer.res
  hashes:
    binhash: 129e9415ca4f8f338f5d82600045b863
    md5: e6ee8baa31e247818d3572e4d7711fcc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d354f8e2537df92fee0ffef4c0490031
    md5: cb2693a2b339f13885776bd3d7d83573
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 186722aab0355a84f6d9e995e4bf9e2b
    md5: 2bc76bdb8b11ca7d0d1d5443cefedb92
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 31bbcae592f2cf28cbdb73b3c542f8ff
    md5: 27a5e15c31fd581ba576fb6f3f60cfde
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart300/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9d895c47079118f35d5a58675359143b
    md5: 16dcd808dbb42b1e61dbbf906a990d97
