format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/atmosphere/restart_dump.astart
  hashes:
    binhash: ed78bff7b1a6edb8afc427b1903232a2
    md5: 78d3b412d576da4e66eabb388b62f1d7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/atmosphere/um.res.yaml
  hashes:
    binhash: ed2b54caf1ee4b6a8431434547bc2811
    md5: b4a86ca01c2d160e8f3463b3247e1cbe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/coupler/a2i.nc
  hashes:
    binhash: c83f4436bfeca30a50e3c0b2c272995a
    md5: 07131b4d3203cc0735c6b572396887e3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/coupler/i2a.nc
  hashes:
    binhash: 8a3be29f580ddd67b0a55d4f52c5fe0c
    md5: 7d975968c2732feee75e88890a0f8c13
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/coupler/o2i.nc
  hashes:
    binhash: 4abcf2fc9bdd6c313e50f23f7a729b58
    md5: 6b44f109d41fa2b87b818c31f9bc4086
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ice/cice_in.nml
  hashes:
    binhash: 5a89ec35bf01bd1d47b97d80eb98de19
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ice/ice.restart_file
  hashes:
    binhash: 5bd8e6c2e7d2ea91e217d922b08751f9
    md5: 6ec4fb1d09bfac745532eb3307884cce
work/ice/RESTART/iced.1231-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ice/iced.1231-01-01-00000.nc
  hashes:
    binhash: 251ba5cdd6c5901466f0bd11de756cae
    md5: efee4a7ed52c5d6a5e92eb164323c11b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ice/mice.nc
  hashes:
    binhash: 13583c1c58d9019fdfceeba142762510
    md5: 8404384c3dcb41b3586a23ee8b69ecb8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_age.res.nc
  hashes:
    binhash: 1bfb12870fbfb5aed2aaf2280f4bc6a8
    md5: 228d8daf6c36183b06682a8edfc6869a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 318b73379dbdf2b940928692ba8ea988
    md5: d9824611d1aa1e190afd5e209af79f44
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ef2d7a46bd3d470da7e7ea105bc25e28
    md5: aa0984c571223f25d07163c748624d34
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_density.res.nc
  hashes:
    binhash: 30183251766cf87a2697bf2a49571cca
    md5: a671ae974e2106d523bf2d336c731aeb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d4028960372b58b78771a3ba3fe9f430
    md5: da7e1d2b6ec4ab9a938c39a1d92a1006
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 51fc083335dc414fdb73f7cd396e8c35
    md5: 6400ccac2e4d10d72db405acb30458db
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 15682a05ab5e1abcd5b4ebff7b9190a7
    md5: badd1596a0939c8e934f9ae26b875e35
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9f25fd7821ffdbbe4f8aa5f88ca7ef0c
    md5: 4c937ee34f446f5d91f096cbbc1c7f6c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a24d12f8aeec8cdfc07718cffd5f0dff
    md5: 98d1c1a4fc300e134d9a865d5fa17c1c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7e7e3f0ca1d174fce81c35f0a698beaf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_solo.res
  hashes:
    binhash: e35ea75d61674738c0416b26eeb2c2df
    md5: 789a5e87f83dae06ac61ea2183fadff3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5a2be530aa70a7ee6177131c89b70246
    md5: 4b03c1ae5e810d1ba012d37d3edc57ca
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 96a5b6122fdf11c9db5a8aa632032679
    md5: 4ccf4319e143f84cc23a326c9fadfaf8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_tracer.res
  hashes:
    binhash: 2c3ec7ba7843fec8aed37018504b5b2f
    md5: 217000e0a78ef62d64899c14cc053d67
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0f179993f3a876e0a8bc3bf1fbada946
    md5: d763036e40836aaa4e82b4bb19029365
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 307b8010e755c1b61bc7299889ece58e
    md5: 3508b0fdbb854e4720021449993a76d2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a2cf7981417e842bba14f059d1642d6e
    md5: 2b1e9aef5cee822c7d358c04d4faa990
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart347/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 56147eefa5a297014b96e1db93bba2f9
    md5: 761c5d7b4b84eafe8b58f5dc70aa6b8b
