format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/atmosphere/restart_dump.astart
  hashes:
    binhash: b2b4e2ff9b7fc0f1caaba5b02bc88f35
    md5: 0d6826d7e50b2f2bfc44931ac39cc409
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/atmosphere/um.res.yaml
  hashes:
    binhash: 20ee94f8858ef561607d7367a8bc13cd
    md5: aec713b0b47fc0faedd6a15dd07d48eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/coupler/a2i.nc
  hashes:
    binhash: 031ddb4db3d1074b311a2341e2a52cdc
    md5: d0892c31c1f9c13a00b22a8f667cc9d4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/coupler/i2a.nc
  hashes:
    binhash: 852428aa609009e0aa64897b54089f7e
    md5: 8a93adad2c5ae21c1e1a0095660560b5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/coupler/o2i.nc
  hashes:
    binhash: ded4a22d57d0795ca7eda1ac1f6003cd
    md5: 359d716df6d707d32238273f207af741
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ice/cice_in.nml
  hashes:
    binhash: 63f5a43d4b8b7306d4634fde227ba939
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ice/ice.restart_file
  hashes:
    binhash: 736eed380a55481fe18f6bed5828da62
    md5: 5e6134b05bf50f9b6c3f7ca874e05442
work/ice/RESTART/iced.1827-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ice/iced.1827-01-01-00000.nc
  hashes:
    binhash: 7878a270bf67c922471e52cafab822a6
    md5: 56e6d09c449d1c8fd49b19ac18381664
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ice/mice.nc
  hashes:
    binhash: e15a6bc58cec0ec45237841f3441410f
    md5: 59522d906ab5522762a0dc07de47dc6a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_age.res.nc
  hashes:
    binhash: e167339cab19cc30ad60d9579e1b5992
    md5: 30224a7cc080e075f19aab79c7d7c187
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eb2a43d32d393cea25e8db071d46788f
    md5: 4b4f2178a3cb5547d9385bae972bd31c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c0b365016cee20a9e1129d63cbf6e0ef
    md5: 72543fec8717e5a375c84e08f439ba36
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_density.res.nc
  hashes:
    binhash: 4c301e78e0f4e2dd0258fcc4e84de816
    md5: dc647179708f60a9494eb9383d8db192
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a34aa9cd41ddfdd06191061f00ff7692
    md5: 706a43039a5a7b9b8210ceadfa9196d9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6e7301a01fa70cb3d8ae8da2c68597a4
    md5: f445fca9cc01f6df755157a1597aab80
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ce414968dce62188a1eb98bdce5cb51f
    md5: 963ec1ca26f8f0fdcbeab3e354c29a3e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d0252c0078a40351102a84fc94ad7a0b
    md5: 1b2fd70a1395c4be33ac79dac7beef30
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9ba44acf17c81aaaeea38a8651dc162d
    md5: 81ff8b0003995ebb71f8b28986479546
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bf88641e51b31b5879e931d26f4056f7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_solo.res
  hashes:
    binhash: 6782f4c3c3f15122230b2606e71274fe
    md5: ba5ca9fbe61a5d6815869601f52debc0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3ab7114f343b728232f8a3a163a7d32a
    md5: f33956a3cee0dc76dcd55c10690288af
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 40a9e22a0c51a6570451c316cb88488c
    md5: 61ddd41e7c27db6e34e94353341d322b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_tracer.res
  hashes:
    binhash: 117a1c7d2a38a8bc6d4d33cd896c433c
    md5: 3c076e14708d4a39057951b5bb9fbf3e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 85ba903caed6625fe7df10920ddaf593
    md5: 1dbff8304ab22c1c36c4e3110e14d378
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 114eac704127cef343b1102d5f86191b
    md5: d0b4f96862d17dd1cd014102fb5983e0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7553a8885d660ecef86ecc25d5b6dd7e
    md5: b025d04e7f6b0098c972e8a2e3476507
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart382/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 11b7582cde2fbc3790941b067aab7d81
    md5: 44715cf30738999be03f3aecc1ec1d83
