format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/atmosphere/restart_dump.astart
  hashes:
    binhash: 90a52e72ef165cfeaa83055db670fa57
    md5: 5c03f907eb98669a49cab25e10f4ced5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/atmosphere/um.res.yaml
  hashes:
    binhash: 99dc57aaef0b929495c194c3597b2573
    md5: 0458c4bfc4c2efb2e1ae1c266c8c6912
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/coupler/a2i.nc
  hashes:
    binhash: 2a7b84ab882711bcc9827be0c363ad26
    md5: e2f6e3860dbde0685c203f0849a291fe
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/coupler/i2a.nc
  hashes:
    binhash: 4842696ba3d670bed0a895bc269384cd
    md5: ef50fafad9b3ae84ec01629464ab002e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/coupler/o2i.nc
  hashes:
    binhash: 10bb2fb44b182585e5deba3bad4b9865
    md5: 2efa5b2a86fd6740da3acc024578216e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ice/cice_in.nml
  hashes:
    binhash: 0d4aba8b8477cab03e21b52b2bc29da4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ice/ice.restart_file
  hashes:
    binhash: 0bb499d7a3972ee10678d5c273618f61
    md5: 58480fcfad0cc8ac75c14dc4f80aa47a
work/ice/RESTART/iced.0874-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ice/iced.0874-01-01-00000.nc
  hashes:
    binhash: 584ee72c5c7bc12f415488389bc2f39c
    md5: 10ee00fc2047c90b630f05258f1a2af1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ice/mice.nc
  hashes:
    binhash: 2da6c39458f2862f872242492bf529ae
    md5: db866e23590651fa17ad21b8e4114f54
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_age.res.nc
  hashes:
    binhash: 8079dfc01b5a9e978713b8bfed75008b
    md5: 47cea842f49738c19de4112f49cb3036
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 02fbf9b04a6700e42d4618b406a6788d
    md5: a163add6d4c6017191db2317822541c2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 485057b4d353a1079d39fe2f45f59458
    md5: 80e6ce82a5cfea00e72286d991245789
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_density.res.nc
  hashes:
    binhash: 506affa5837de79fd83251ee99fbf25a
    md5: 882fefb5f4ca7e300bb654e3333fb832
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0baa96a461734aa057f92b8fa937bb78
    md5: 557d451fba7d0f87c729720cb428017e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b178ae3a614869cf18667ba98a7b04d7
    md5: 3b106c83e017e5fb7e9d8fc5d35fc2a3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 665ddd397f92c11f7f49735e71dc9495
    md5: b8c2668a3b6754e0f5e20c91b18f823e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0162d4c564a2b2e656543770417c0a59
    md5: 68888ca5e4cb0d7b629f12b60979d909
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f080bc0d597954fed42fcdaaf860591e
    md5: 51fd2701f3cc4fcd8e0153db28fcaa82
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e493e0d0d1c77394326e3e90198cc8a4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_solo.res
  hashes:
    binhash: 8751eb4bf9ad8e87116f33ecfe710f2a
    md5: 6d25ac2d88866e4a8e0094c588ee687c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 439aef294877213348518e3c983700ee
    md5: 5fd2a03f8c56d2ca5c4c20c64d6aa076
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e177b6aca718a68efd30cbc993a76ad7
    md5: 3671a45f0e9ab21317224a59e3c320bb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_tracer.res
  hashes:
    binhash: 1db2a3acd8a548590b4a1b689167acf4
    md5: f110fe900e085a82ad49133efe4d5728
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 965dda0dddd62ce56f04faa17af70e1b
    md5: a31868b7037a9681544cfbaded8d2f9a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b996c4bf3e4d940b8adae985e54df4b5
    md5: 487e5a695ccad6ae2900ce523007ce75
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 68752643b0941705bf40d38e9e2af2df
    md5: 0c81c4056d7b8ce61267a2a3b49e8659
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart320/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 329adcf931c250568c9da1b454b1f414
    md5: f43ef40f9d3a707a5b682cb8d2f3c1c8
