format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/atmosphere/restart_dump.astart
  hashes:
    binhash: 0e8a216b6aff29e051e09629273ff2ff
    md5: 12616f3aca040be06d3997adbe554c2e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/atmosphere/um.res.yaml
  hashes:
    binhash: 4da3472716d2b36919feffd2e073a0ea
    md5: 69b515151164f778b0cd0dbe74637d8a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/coupler/a2i.nc
  hashes:
    binhash: 7e7a76d1b0041b356748475bf7eb88d7
    md5: de30cb4f3e03791f79d83dc64addff68
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/coupler/i2a.nc
  hashes:
    binhash: 9337fc6b93d7577b6e596abd16b26c8d
    md5: c6e703b993fffde30a055c8f33fdec8b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/coupler/o2i.nc
  hashes:
    binhash: f15b12c30263a6c4fec158ca4580e70a
    md5: d3ecd7082180f024582cf8f0e928e355
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ice/cice_in.nml
  hashes:
    binhash: 15feef9bd295edf03f7e4d0d7141817d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ice/ice.restart_file
  hashes:
    binhash: 53e619ba89a5766f09ed4fb8d6ddcb46
    md5: c90eac886f52d4f0cdb63b7feca628d9
work/ice/RESTART/iced.1837-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ice/iced.1837-01-01-00000.nc
  hashes:
    binhash: 5370f12ad32b3d9f5dc0e4bcd87d8704
    md5: c655cb62673eefabf9053d7d05db27be
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ice/mice.nc
  hashes:
    binhash: 150972c639acc9544bb6351e102a1f37
    md5: b3771da77b935e1cf0c865eb37811baf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_age.res.nc
  hashes:
    binhash: cf4e492bd5cc90f3dc5bfd36a21f2742
    md5: cd8cff108afa332906074a5bcbf704d9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1bbf2678daf33bd32fd42bfe302e5c78
    md5: e0dc809085685cb5142b706359b831de
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 372e8b7b4c74f031341b1e6114b6f332
    md5: 931179b448f11e896f093af418540b5b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_density.res.nc
  hashes:
    binhash: e449272007591b53de71cc10f6335f90
    md5: 7bd2905310deb60fdc0bcc2f767b5555
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 555bd3e57341f69b78bd44506b30f4fb
    md5: 3e95c941145a1e76b166c9af056f5e7c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1dbe92261381f6357b8751f41cc64dac
    md5: 9e8965ae0b15a7c46fcfdeab9b22dd2b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a61e0b4aec667f5bc5626af34425a50c
    md5: 35831cb432836d8581340c4e202f07d5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4071bbee3b7c4d7684a1da338629850a
    md5: 71a9ecf1b583da490080fbe7f4afbd3b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 790a77640cd647fa6e6cad10c57d8c6e
    md5: 03c7d3126925cd8beb4a18139537b0c5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8877623fea11f6097f0b8ed2d030d2c5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_solo.res
  hashes:
    binhash: a57efd95b7c9d35f72f8a954b05fa31c
    md5: 620bacfa3bab9d2e8092c3da76f14e02
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d26ae884922d1a1a12aa74ff4169cd31
    md5: 8dda1afa489f0ebc8d867438bdb0d47c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ddc1368dfcf0f8762555989db46e5c9d
    md5: d8a58091399466f2f7cf22ba5754155a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_tracer.res
  hashes:
    binhash: 7d0a3fa40fd1712076dbff573b8f8a78
    md5: 0d6aa8e6bb535bd10aa71baeeab692ec
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4d51f355bda7eba7374559acec6cfc0f
    md5: 1df1c5ab083db927330f0704ee262b73
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a94218be727e63c99ddb307431e48588
    md5: 41529a060464db3f31896da0e29fab58
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9ddde0e958b9604148c0bcf3b4d0ec3d
    md5: fcf0afbdaccdd0d262673eb129c80a55
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart392/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 750249afb4c0ab5f5afb56f11c549442
    md5: 8ca46924c12b12b1f2a18a9072f3358e
