format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/atmosphere/restart_dump.astart
  hashes:
    binhash: a58dae8ea613847016970181a21c54b3
    md5: 554fde03209874a62cffce8ae128cd66
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/atmosphere/um.res.yaml
  hashes:
    binhash: c4b510846de9692a8f11d7b11208274c
    md5: 829b7446e7862fca612a8e4a906527a5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/coupler/a2i.nc
  hashes:
    binhash: 9a231f4cf2734b9462938d36422471c3
    md5: ca6f22f2bebae4aef6d8e9675cb154c2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/coupler/i2a.nc
  hashes:
    binhash: c2eef0c15d55603e7cc79151c5119f1e
    md5: 64fa9494b16194ef4c87fee2df641107
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/coupler/o2i.nc
  hashes:
    binhash: 56717ae8bf6000d8b74836245d7188a1
    md5: ff815d76cf361f793e59e9fc99e3cebb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ice/cice_in.nml
  hashes:
    binhash: 518ba5de713a0a78e9d0584d3c2fe1c4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ice/ice.restart_file
  hashes:
    binhash: cf33793f8c87bdc9452814f5931c34f9
    md5: ddfd8359e85aab3bda3d37846e1e67f2
work/ice/RESTART/iced.0977-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ice/iced.0977-01-01-00000.nc
  hashes:
    binhash: 4753161d15f2176e4a06e4ee1ed06c8e
    md5: cc80ebdef4f8ad5ef4e839ba470826e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ice/mice.nc
  hashes:
    binhash: 5e8f331df4b0ceeb1fa99e27c45c63e2
    md5: 010f3101ff9fa007c5f051535351d09f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_age.res.nc
  hashes:
    binhash: 2aef6c603f5ab7ae67b9170d959a7dc6
    md5: 828812c88bc4e2462d3d51fd5ec26965
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e3b46e2902783183638f7ad99f6a42fd
    md5: 75504c74af0e4dd4de65bc8375809eb2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c325644af8d538d70f6deadecf372a64
    md5: cb1b28401b16b1e06a3fb30b377bdeee
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_density.res.nc
  hashes:
    binhash: 7e85b8ceb51c7b3e8e13c684a150f82d
    md5: dc3d6a0b76e2e5cab9388580409e006f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f04f9b36c203a5937c1adae11e0f421b
    md5: c069780fe1d51c1a13769c9238b73aad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9ab5d0cc9eb2856283ab501b4deac58b
    md5: 2787bb4e00407e925150c6ddb18a562d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6f678bf5c197e1684250adef51752daa
    md5: 7b5a6a5a1380d0406ede688a12118f23
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fd3629ac995da1049cb97d507362767c
    md5: 6dec5eaa0085e01457794ec1424260e2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 62a9f2cee80f827e4857d0117a61472f
    md5: f43d5b740969ee2a1a17db1e4a4e6184
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9c27eba2fedd36975e20c057552395ac
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_solo.res
  hashes:
    binhash: 686150e110346de43b6f979824e2555e
    md5: 789902f0451baeae0d8d4eee44f2f10b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 88b27bbea4472aeac09e12185884d43f
    md5: 78163a101466ae3374d910146f2d3550
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6ccd3e55a28ad9f71a8811124ce84b4b
    md5: 37f750f3ec12c4b7e1cd545ee95ee07a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_tracer.res
  hashes:
    binhash: 797114e2dbee570064abcc697e6cefaf
    md5: e7e83bc3fec0f95683e756e002b90e29
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2e580ed49c516a82820dcefbec32fc94
    md5: 29e75ec26e1fa4e9699de4f51b3f46ee
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 17952eda15380fa3a10be3870bec12e2
    md5: d875b0104d833f5f5b0e69744817d22f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6649977316c2cff7bfc63480ef00624c
    md5: be24b0540dd768aeeda62a6ebca7aade
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart423/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 346b5878b91dbc3801f6c3e99345328c
    md5: cf3c973b9b2759ec2e7e0c8e69658527
