format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/atmosphere/restart_dump.astart
  hashes:
    binhash: 40474dd3124d6d8ffb3dfd9f63039d1e
    md5: 2bf1105b610548b7aa58c4e01c692db8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/atmosphere/um.res.yaml
  hashes:
    binhash: 98b35cf070476499979f7c29716f8a3b
    md5: 7e6d1ff3490a39a48db478a5fdd83898
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/coupler/a2i.nc
  hashes:
    binhash: 36009f6a88eb7d5e7754ae3d80e30af0
    md5: d4bdca24964280e7216071e88fc785fe
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/coupler/i2a.nc
  hashes:
    binhash: 2610c300ce4b7901dba0a3e7f1eb8e4a
    md5: 6b7c1f88d1af910b3a9454ac3d86922e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/coupler/o2i.nc
  hashes:
    binhash: 7609ddf9adc1c3f4d6e8c803d9fc8086
    md5: 4c0b2e6e78d5831618d7e6f245e9e1fb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ice/cice_in.nml
  hashes:
    binhash: d2b74a3d465a3d9ce0aa48e709c188be
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ice/ice.restart_file
  hashes:
    binhash: c111ea8285aa13c5c47ed9dc8d68b005
    md5: 9db3e92ec00215f06eb9f2e980166304
work/ice/RESTART/iced.0918-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ice/iced.0918-01-01-00000.nc
  hashes:
    binhash: 7194902a435a2421b38dcdf1d7027c6a
    md5: 6fafec7a1cda2226afcb508c80fc2621
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ice/mice.nc
  hashes:
    binhash: b685f9282bfa58a054f59ee7edfa39e1
    md5: e1583607d4bddb4c02f72bc1355c531a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_age.res.nc
  hashes:
    binhash: 69687f037bbccc769afc539041b0201d
    md5: aa07ed3b116771c607794b258c2a0d01
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b5168da8db3abbeccc815dc334ab0b07
    md5: 320f80c3d7384f26c22fae73a61515c7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ffefef92614ef89df146714fde147712
    md5: ed8856e85cd29d5fdb27dee06bf9cd5a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_density.res.nc
  hashes:
    binhash: 67f68c5ccf6a8cfe35e87a463488355f
    md5: 96bdb91bdc85c642c224205b31dbd39f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2a573609fe2b6351c0590eb158f716fb
    md5: 28c7a2641ee4e7e701afcf713220a532
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4ba472c04fc8a517c328c41879852bbd
    md5: 592072b55682cd894812d88c43d915e3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0cac08cbb9ef31cd3b4d12d8417eb20c
    md5: df62926866e5a85e73d4482f4abcd819
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8e8e84067c1b489b236c854d632c8232
    md5: b30b4d32be1fbac5d42160e970e0fed3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 58d8c8d7739005f55196202c1c9fee55
    md5: 2e75b50bf75e245aff685e865ae4a65d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 05f48b206c91cc680230b96ad3ab9530
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_solo.res
  hashes:
    binhash: 3eb27bd768d0f7dd6ccd73e45cd43522
    md5: c32c3c99a38b748ed6a4c2f32f00b83e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7c2226dfce4172a1eece70927ec43b77
    md5: 0b319972a157d52872d275cc61b03d27
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 473942519a2b388994a452e3ac604d6e
    md5: a79e1a5ce2e904f6936e7ff2a9fee479
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_tracer.res
  hashes:
    binhash: 7fc15b4896314999b7cc128512210f0f
    md5: f593009976189ae10cee8de37518f6a6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 951a6d63f62d94fe6d4fb31cf9a819f0
    md5: a713a9ab9db25b691f3551cde1f5ce47
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 20b5800d6f4dae83495905f60256e9b0
    md5: 3a9cb4301601f17b597a477ef0688dc9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5d18defa311d511e1345a538a89db509
    md5: f97a17a7defc073ec67891783e175236
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart364/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c1479e37aa21e90b52d1323bb6cde3cd
    md5: 50ce799f5b7f2923fae9b60fad17d47b
