format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/atmosphere/restart_dump.astart
  hashes:
    binhash: 5405141db821ef49ff7639ba4dfefe3c
    md5: 9671d9fbf622155bf72375a6e83b9df8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/atmosphere/um.res.yaml
  hashes:
    binhash: d9890ed82b2f4471150839a48b738c26
    md5: 991d7344baa180123c1f5ee0c5301cb2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/coupler/a2i.nc
  hashes:
    binhash: f4a56eeed47ae5d566e139811a989ea1
    md5: 440386dc7f41e84c9b0fd4904c9f70fd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/coupler/i2a.nc
  hashes:
    binhash: 1380d6e3f277a424dfab3fba838fe0e6
    md5: db33539445916dbb4a8520a6baabd92c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/coupler/o2i.nc
  hashes:
    binhash: 9f89a8fb7798c81ddb4dba8c618d46d5
    md5: 20af82bb4aac4a3588eda51082022f3c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ice/cice_in.nml
  hashes:
    binhash: 96a654e69a2942bd79fcc42624ec48e5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ice/ice.restart_file
  hashes:
    binhash: 6a7dc72c7e51049fe3554dd25aa1693a
    md5: 04aeb19c2f4796f6a674cadefe6adfd0
work/ice/RESTART/iced.1833-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ice/iced.1833-01-01-00000.nc
  hashes:
    binhash: df7b74fb33e19d4a7c08cd56210d9582
    md5: 527d64f4d03b663412e1c724491db6d0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ice/mice.nc
  hashes:
    binhash: 6a7caf7daa913811f93968890e8e2c78
    md5: 293ce3bda4fc246a34792ef164007f5b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_age.res.nc
  hashes:
    binhash: ab6f2676a1ed4d6a38c2e8892a2f1c79
    md5: ac9e19a36cf635d569d34ba878f630b7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c04c56e534bb907977752f4125cb5bea
    md5: bf5b4600aaf23b2cdc40b01120543181
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 221a116ad4f8ff3c1cc26ebb4caca63a
    md5: 876b782451a4f6a8760be5b194ac9b52
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_density.res.nc
  hashes:
    binhash: 27b330e14262389f031db5f1399b14b8
    md5: bd89f5c9b84dfad8bfdc2b4ce08c791e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 963605b30b7ea5b1ee88b238b35c0366
    md5: 60d7a55c4ed3cdc83fc0a7ca5ec31155
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 478cae0e6033e2c725f046b787c73807
    md5: 508b030873057fc430cb189fac153e7d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a8e3a0ba4f1877a65067ff08792abfb6
    md5: 9010e4f756732947326574cdcbf9672c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4306857b517b636f0d9ad3c36888dc33
    md5: 3cc55273807e76c1f79e4cde7cc11a17
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4a43acbb6b46ab700e4a1d1910f94973
    md5: 0b807b20544c15dfdfe70557aefcea63
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a00b544baee9242cfc4225330a70a30a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_solo.res
  hashes:
    binhash: 7c19c664e73f61902f433974ccd16422
    md5: 87d3b33c42afec465f5a6f86bcac6b1a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: de101ca35a2ff57466785b0d7b325fbf
    md5: 9bd443502041b27e80b0efee8eafa0bb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ccbd1d8a39d57d31b315968de84fddd6
    md5: a52d1ec7b4b7ec21dadc6b326cf09294
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_tracer.res
  hashes:
    binhash: f1f874bbf5f73e94246de552ff2d336e
    md5: 91b050dfb7ef380d172234b2563b55c5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9b221f82ecc9dfe59fa6f2fd4d94864e
    md5: 7d8c9533c544346cde47a3bc8c7e57eb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1774b3659deac642b37e378eef00be70
    md5: dae0a11c5d32992189eb0f54e624c3e6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 71499efdf220de6e1d3adf51f9279f1d
    md5: 33dbcf09c22300a7965cc352f8a5af11
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart388/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2225e4a196241c57bd5afdc3b49db1c0
    md5: e7731c0a851dd2be4d399272efae428d
