format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/atmosphere/restart_dump.astart
  hashes:
    binhash: f5d4f88dccf522fc0635d4e7f8e4b1fe
    md5: 79c66f70cf534899db9dfd52c97ad206
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/atmosphere/um.res.yaml
  hashes:
    binhash: a45031a8fd6adea19e745e846718be07
    md5: f78afa07efe31d92871cc20e66d7cfaf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/coupler/a2i.nc
  hashes:
    binhash: 2bf57dd40b1e355e50b58cc41445df55
    md5: 9c29c3ec91b0182730fe942953a76238
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/coupler/i2a.nc
  hashes:
    binhash: df5f9dfd9dd11d0e65d2aaefd28eb5f6
    md5: e505c56126d4c2c023ba478155a0a117
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/coupler/o2i.nc
  hashes:
    binhash: 72c56b0b8d699c5a87543fda12c3f62b
    md5: 93e5d75f98ec6171b383b6702c977642
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ice/cice_in.nml
  hashes:
    binhash: b03f8eef8add6b52b51dbe62b50b8294
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ice/ice.restart_file
  hashes:
    binhash: 3140b0557342be06c1ecce94833398bb
    md5: b7756085bcec6ed7d2b192e627925198
work/ice/RESTART/iced.1247-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ice/iced.1247-01-01-00000.nc
  hashes:
    binhash: 0c3e11fe7d2c945a6475f7c5fa1c1bb5
    md5: 2602796ce577623ef3897c3f54c22b71
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ice/mice.nc
  hashes:
    binhash: 51675cd20b644e1d6c3148f6206dc24c
    md5: 8e36a1b6ff7138b8a1a5d2c1cab83a61
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_age.res.nc
  hashes:
    binhash: 1379213673f1cbec02475459a47d783c
    md5: 6ba5123118ae7319e646f487b0d1a1a9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ddde6a9302e2302e40974889a089edb3
    md5: 66561cdfe12acfb38d3d651411e81035
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9b9f9917a3f8fbec0bba5012ad06a1f1
    md5: 045a775a2480cf447e927752b16c441e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_density.res.nc
  hashes:
    binhash: 77f6bc0485c832e28446107f556582a9
    md5: ac7c1c8e1be0bcf46927ec4dec3a0c65
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9a9590b38e674d55a08a4dea6eb048a8
    md5: 6e0aeb1926d8b7a12783bcdc26f674b4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 81d4a9e10342e632ca47720aa3f44345
    md5: 8a74bbdca4b9a6f2b3b73111140cc5e8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4f38389897c78dfba0111d67c0d85af3
    md5: 1bbf5940dce7637fa4c81619b8b48b7d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c6e845cbb4bb148cf35aa35bd16cfa0e
    md5: 1b69c7cf9f86dc6319a69654d0b6edfb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 30fbf484f35baa1e9dde2b7c2f611c16
    md5: e50ac4a60e98f6172a34cabd2f290578
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f66f2d009f08ce4c8051667b79d3961e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_solo.res
  hashes:
    binhash: bf27edfe7daa2fa0ed3cac15069c1ada
    md5: ccfe08193d26fd9eee97af0ee29c27b6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7f61687ee6020606ba4d747f4faa6671
    md5: 3d5c0d92ee0fa1900c00bbf129553356
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e301f36d9d49cb314c702eaddc72bab
    md5: a7511732d91f358997d3f2e3b3b9bbca
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_tracer.res
  hashes:
    binhash: f5af08f0e0d596ea2141e168235ad2b4
    md5: f5010956a2b9d4972db1dedb5f55eed8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 94e3cd9dc55070f314de019a55731f3a
    md5: d3d756390f5e026d815af52cc67e7a8e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a086cd0d9ab9c5bab24a53fc871136fc
    md5: ad73883b3ee2e5ca5f9850b4f90afb8f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9db67a2f76800a44962aeaf8150d3799
    md5: 736e7d50f9f6e73d33c3b52c8e3dc26d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart363/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dfa4e9cea635eb0d784f456a62fd6452
    md5: 79ec07bf6e42b22116825ba916f8f7b7
