format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/atmosphere/restart_dump.astart
  hashes:
    binhash: 6d04cfc341949deed4e2581705b7189f
    md5: 1a28dcee541ed2a09b2ce8c405c77bfb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/atmosphere/um.res.yaml
  hashes:
    binhash: 3069de889aac6cd3304992f66adb6205
    md5: 4514cf4d84b3720ff36445d717e555ae
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/coupler/a2i.nc
  hashes:
    binhash: 1feac6491d512026efc08b6cbd1da3f6
    md5: f64c85842ad439f1fe1718a4f4798570
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/coupler/i2a.nc
  hashes:
    binhash: f55654b6bdd7f7df43e67c6e101659e8
    md5: ac4cc6cd537587d490cae5164e291121
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/coupler/o2i.nc
  hashes:
    binhash: 7997280c37917788e74b7727016534e9
    md5: beba18278d94e0476d9f215cf738e5ef
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ice/cice_in.nml
  hashes:
    binhash: 31c686a0150b66a0d2a14f12c9bbf6b1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ice/ice.restart_file
  hashes:
    binhash: 5416ea3c517ab110ddfddc40b2bf2d9b
    md5: b17c843186d473d6808cef183f6f3842
work/ice/RESTART/iced.1185-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ice/iced.1185-01-01-00000.nc
  hashes:
    binhash: 4255b98cc02ba00f024557e5201ec98a
    md5: 4b39c13e907b2c6c604211dea5f187e3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ice/mice.nc
  hashes:
    binhash: f1bd4e1702b93bfe3758541bc26a9927
    md5: 2eb837f861fca9e669dd64818d95f52c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_age.res.nc
  hashes:
    binhash: b2b7eb2b441ab3a536aa7ea04acb628b
    md5: efe6ca24bf1edfd4503b0bb94eeb07a3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 26205c8594e3e1701e26f513452032b0
    md5: 740df6c08740423a02eb40c34f297d0f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 13ee482d9bf3c862f68780f193a76bd8
    md5: 969c6920961ec3e3f3d5e76fda6a698c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_density.res.nc
  hashes:
    binhash: f97bd2642bede4e8ce06f2bcb6432260
    md5: eff6195233599db44944d9b89de7f905
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_frazil.res.nc
  hashes:
    binhash: da7fbee1f115ae1dfaf945095269d2eb
    md5: c6e93b100836873572743fe222490b11
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f6dba3e9daee69f2e3da27a1270bfa6c
    md5: edc938288d81ea010e24d0162a39013d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 51b93b3239b84c94ed6813e23ccb4cad
    md5: 7cb226b84aab20794327ce517dac06cb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a6ea7debfd6843a41af66880a82e790c
    md5: 626e7aa906b61999b3582dc5e9454bb9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7ffd7032e0dbf136f6cb66c493a2b132
    md5: d0046210caf6e4c9b27c42201cc6795e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1f9e6b0167205c1af4ad4222a56a5d22
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_solo.res
  hashes:
    binhash: c1ecadb1649f813726255b5af7de4306
    md5: 112dc4a8a3b057099e61f1cb220feefc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 108e23642d647a96ba69ade00242c8be
    md5: a2204b143bca15071d8aba055fbd0771
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5f1f794f93b3b957ad1ce9e310be2a6e
    md5: 063717ece6510c752388b0ad98da4d53
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_tracer.res
  hashes:
    binhash: 8ebee5b45eb8c56ce6cbf684eab577d4
    md5: c3bd20510c690ed014ae731256c6573a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ca411fd12e452168db94eea4edf455fa
    md5: d9097e18be38138b8189c1f0995657cd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a1d5a2c7e1f9785bd1eb37d4ae3ed46d
    md5: 6a147f115eda2dd62b8929b3e825a046
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4c1cc2c7cd6a7bba8eca941c57da754c
    md5: 31f3c3304ac75d153613b98c0ee9d271
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart301/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 468251cc13b3f2183e87bfff10f67717
    md5: 82a7d4e0c4d29ed22273b9297b363a14
