format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/atmosphere/restart_dump.astart
  hashes:
    binhash: 48e1bd1af28081a8c5fac418e5062f1e
    md5: 7e663f672ec74d47cb274b77d9671d56
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/atmosphere/um.res.yaml
  hashes:
    binhash: 2a594a3d711ce223c43a670cb05fb336
    md5: c6cfc8ec0ed4b9bbe4c86c523953a065
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/coupler/a2i.nc
  hashes:
    binhash: 7503e144df6ef781e30a75981b3f622d
    md5: b4bdfe338fa34501af5c82b833db2178
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/coupler/i2a.nc
  hashes:
    binhash: 838b503bf368780f15670875a2dc8da4
    md5: cbbd7e3bcef6e4a0bce1efb90194162d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/coupler/o2i.nc
  hashes:
    binhash: 7b3770c7577b31407f6a8845fba81406
    md5: c570d1b1450ea2c78df3e74360b349c3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ice/cice_in.nml
  hashes:
    binhash: c7288e0e5daacf0b45df110d926e2f6f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ice/ice.restart_file
  hashes:
    binhash: 20fcc4d1187f4284c8a3e2b8fad42a9c
    md5: a355ad7cf390957106f066c7d1a23289
work/ice/RESTART/iced.0869-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ice/iced.0869-01-01-00000.nc
  hashes:
    binhash: cc8fd33cb02bd29a64228bc894da58bd
    md5: a00e38437ae76cb0aedde6f9f2b7baf1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ice/mice.nc
  hashes:
    binhash: 692925307467efd3fb8235752bea75db
    md5: db9ecbcb9566aa1556dc68cf6b82d154
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_age.res.nc
  hashes:
    binhash: 3db9f0c60ae987472ee7c7495a35c0c1
    md5: 793d8d1265d96631bd535a8f7ebd81f9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cffade2ef22bf6117d61549f69c5f530
    md5: a4ffb5cb857b57e24138d373aa83b7e1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 07150e0aa36c08b9673691405b6f37d6
    md5: 33527a0e5e8e1060bca43ca96f99cd44
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_density.res.nc
  hashes:
    binhash: c84134ee7dc52becb10f14cbb4294af4
    md5: 13ab1cb8fba3f5572c3f831b70a49029
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 786589b3113a47cb1c20ac927e63f410
    md5: d67042f17df3feddfb104f42fbfe5a70
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3fda93696184d076c999acfe109f8346
    md5: 273820277406e5ac3dd6dc266e17f1b1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e036915b5f7c46cad8bca9e22927032b
    md5: 10b366b8534c21b46c601f9b52ef8fa5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4546f7bddd60fd119a3e39f6d1963278
    md5: bc38515a42239f76c5c0b002dfc456b1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 403297a978a7d1bc68fea112ae6366a1
    md5: 0697aadc2e3e2dce3981f0083e2c5736
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 644f15c769d1a4f9d3f2f1730f549862
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_solo.res
  hashes:
    binhash: 48d8f855865c726fc59f21d10c8160d2
    md5: 1b6865991dffdc2a181ec876c4ee601c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 67f4d71e69371ae8b0c91a7516cbfaf0
    md5: d9a12f77f3178bfeaadefc423b99b257
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4b428b2bf02537c4cef4884deaaa96ce
    md5: 9f4c2472402dee2aed884aea83895b0d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_tracer.res
  hashes:
    binhash: dee1ff614242baa9163d6a7129f25afe
    md5: 6509ba232998f9f0876d2d4e48bf9547
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd622852112758af4d4564a0786e10ed
    md5: 97597e9c4e5e333cd9c360ae3beca5bd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b61f634d9513aa174b278ff6e3dbba32
    md5: 17dc3b441eaac602e16eeba6e6bf1ff6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a8894d72d49c3818cd3a4fa6cc119a89
    md5: 92091be1a7bcd0d59d28e6aebfe57b81
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart315/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5e9b50103f226687f9988661e5a3f76e
    md5: d1a4168ac202a4bad7f7ad8cfa79f4ad
