format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/atmosphere/restart_dump.astart
  hashes:
    binhash: 154a982f74f9c22d8d38b4d58296f33a
    md5: b4f1c6713c5cf3ce6efb7da01d505c9d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/atmosphere/um.res.yaml
  hashes:
    binhash: 429e51be093ce1fafb06b3f5487ca209
    md5: 55f14d9e49c7692f3842e3e954ece883
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/coupler/a2i.nc
  hashes:
    binhash: 356526cac185ac0762cb69fda6a818b2
    md5: 69271d1f82abc1b9b44d78b1bb9b3b17
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/coupler/i2a.nc
  hashes:
    binhash: ab814375ff84c102b6a7486e006f7439
    md5: b6ce90735b9a5862de928e1c177f78db
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/coupler/o2i.nc
  hashes:
    binhash: 871277dab955d410d2331290cef1cc5f
    md5: 81dee6ef867725e3b8cbc624dd9bf74e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ice/cice_in.nml
  hashes:
    binhash: 9cdac5f2d7c57db43002282e82cd0588
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ice/ice.restart_file
  hashes:
    binhash: 386a5c7a1a04fc4ae71ed77db78ba4da
    md5: 53386de01bb9517c5348f15fcdd28914
work/ice/RESTART/iced.1155-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ice/iced.1155-01-01-00000.nc
  hashes:
    binhash: 4dc75ed63049a50ad96236dcb9f0a167
    md5: 18c6b0a688e71b4f3986e232c78e9838
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ice/mice.nc
  hashes:
    binhash: 336dba4ba27baef1c274659aed9a1988
    md5: b1eff7c434d01e6b0a8146d8bf6df744
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_age.res.nc
  hashes:
    binhash: 643d2e32a8895001c919d15f4d510fdd
    md5: d1e5ae97daaeacacd237100b167e4392
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ace7c6baf02e07072e20723ddf3bcb0a
    md5: 8ce4e08d5e072eaa30ab6c4ab9816701
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dbd2de74f89f8b9e8e21c7df9be9baa0
    md5: a46783f64ecbfe2cca1d512341f1402a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_density.res.nc
  hashes:
    binhash: 4a40f6045c5a244947cdc13463145248
    md5: be6489aec50aa65210dbc23c20886bcf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5e04bae0c259e787477c7cc3b13262d1
    md5: 766d9514b61238ec5a099588120e680f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 88536d2984ee2d4a58616fc36895e7b0
    md5: 74ab80dfe7d6535ac39cf68283f95245
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 56d2a08e528226f724a5b00425be2220
    md5: 454a25eaaa0324cbdac3e46b83ea4bb3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ab7b530451401f9b53daaa20465c5ada
    md5: eed8801af48067fe3c2d42cbd01eeeb9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fc9fb247325d1c1b03f9baed03b82e86
    md5: 9165fde6b1ea89c94ae07f3679ba98f8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b6150a35a2522f280240044417b4111d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_solo.res
  hashes:
    binhash: 64cced9ba1072daca7b3773032556b5e
    md5: 7e3004bcbcd47ad27399e842a96d5622
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9c1f3f342a3090fabaf52ac9488f00e8
    md5: 31453cd544a19cb372fed6e7050693c3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 15a3475f19a47778d81afe212435d01f
    md5: 0fc9d04f1c209893ef45803abf4aca7b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_tracer.res
  hashes:
    binhash: f59c132a8f7df75ab797909eea435a1d
    md5: 73d3b44d23c21c59eb1b63b0b5ea530e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b4e99e7fb18ad54e2d9dd6581aecfe3b
    md5: fbccc4e0f3e0ccaa4d98b746abb3b6df
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2633e61fc027bf37e4c6787a21cc9669
    md5: ffa0c08b9854d9390c7b8754c6e2055d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 54c3af9da03c3054290149bab8814a8c
    md5: df93759138f8fcacb66295faae6af784
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart271/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2c9126da1984fa38f9d58128c92519c0
    md5: 94bfb14ed0fb02d250a08318abd17bcf
