format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/atmosphere/restart_dump.astart
  hashes:
    binhash: d26310235931acc26f56766db28112f0
    md5: e98bd979a28638c0d14c6b441a32dbfa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/atmosphere/um.res.yaml
  hashes:
    binhash: aec56e46af64b39465cc6365bc3a1884
    md5: 685bd52eaa9081db874ffd5e3d06559d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/coupler/a2i.nc
  hashes:
    binhash: fea5180becd59ab880744e9c675e17e5
    md5: 788176a3ec3c98b1d374d34e9ade6d89
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/coupler/i2a.nc
  hashes:
    binhash: 733724ad530e4b3ce8ceccde737cc8fb
    md5: 54ecc46501eb67bfe4d895875a604550
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/coupler/o2i.nc
  hashes:
    binhash: 2dae6070182abc9731051f723f340db3
    md5: 02e6c566cb934e81d1db04dacf2f2eee
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ice/cice_in.nml
  hashes:
    binhash: a21adb6edd1eeff1b0342787f0ff6fb7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ice/ice.restart_file
  hashes:
    binhash: e7f57a671307a4b49c8d3257902dbc63
    md5: 43e308aa04216131f6f439be23c43036
work/ice/RESTART/iced.0877-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ice/iced.0877-01-01-00000.nc
  hashes:
    binhash: 11ac1e908a63c036c5cbdd726adc8e80
    md5: 855f5d0b74821ccd27f07e58b6160e58
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ice/mice.nc
  hashes:
    binhash: f325d8a9faa9e90bc8ddf65fdd80b87f
    md5: 21aac0878e08c30ef0eadaf39bf6e8ee
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_age.res.nc
  hashes:
    binhash: 079075ebae74119f2a2269f4893201aa
    md5: 3759d5eb22148c026573ae3d9b396226
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6d8c99c8fd098fab644d1bcf233ce974
    md5: a012b4fa3473465145d98b4628058e15
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 15e8451fa5bdc8732dfadacc6735fcbe
    md5: b7cb1d9aab0a564613d7928975404e8a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_density.res.nc
  hashes:
    binhash: 4b2adc650aaef8fe95882ed741fadec8
    md5: f6ede2f2dfd63f6f7241cc90da9a6e97
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ae28007c57df8eb121ecb97969be752f
    md5: dcc93ba4d30a59265aee577ca6295e01
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1cbcc57105f7033818bf79e9ed419ef
    md5: b6df427a10fbc9a11d2de5e587a11d81
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 03cef8f7fdc4b66dffad1450a1e373b7
    md5: ee0a7cea6ca28e9dca66b663002ff77d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e081f72ab3fbf0c0b783aa609f3a176f
    md5: 2fab7455c0d0f8a51c65483b84f54add
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 63709aa1d54591dc9c84ca5c9e579e17
    md5: 04c3e32f31d586461d6a18e45de01885
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d621382b4ad4bbed85ba440df9887ba9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_solo.res
  hashes:
    binhash: 1092ceabb14a617840c3a1ebf5b61892
    md5: 0178b8f6a0ed322bb2287d0209925b36
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ec81245a58e63d4c719ff899be5da4d0
    md5: bfeaffe9c3727559e23c678a11146bdb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 94d82782a8ee049e122629424ce1c5b8
    md5: 72672ad24efc16814789b6205ad0586f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_tracer.res
  hashes:
    binhash: e0bc23711d6621be76a657ceb3fa8276
    md5: 50f6d545fd6fc00f226b53d054bebb87
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7f265070c34eedf367b4e6781581d06c
    md5: e214bd77e6f2c35b4b5c872a3eed9f22
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ce5ffceec0163f0aff05252c9efeb532
    md5: f9c7d571a9df0a24da790af92286d7b1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c87d9eabc9f891eadca54f8ef07f9779
    md5: fb19083b7e04ab7b230b635d675c2174
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart323/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 91e1f66babba63eac25cd3046ccf0c3b
    md5: 52e32158289e612dc53b38f631f2b6b8
