format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/atmosphere/restart_dump.astart
  hashes:
    binhash: c85abf4eee7b41231b56ae97a66fcb03
    md5: 161bbe3a0f8be54a190711054cb18490
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/atmosphere/um.res.yaml
  hashes:
    binhash: 5a4cc87829bf4e8caa9314187223f9e5
    md5: ce91528666792458336c9b25ad41d848
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/coupler/a2i.nc
  hashes:
    binhash: 1e9f30a8185804085538af6499b043a6
    md5: 06df3311d09bf474211ca2d1bf8de494
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/coupler/i2a.nc
  hashes:
    binhash: 254e10eadfbaae416af2a67bd073fb20
    md5: 582558aa42231fa1bb0961803ad6f8fb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/coupler/o2i.nc
  hashes:
    binhash: 6e945ef56a82b03ce298fbfe6ff9724f
    md5: de6e2d6a07583deb0067bf6f52d4a600
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ice/cice_in.nml
  hashes:
    binhash: fdbf58987a85b038d7a26b54278aa073
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ice/ice.restart_file
  hashes:
    binhash: 9498f4c3a8c4b0fef691aba23307f530
    md5: dc03c5f89bb138fe2a4e68d8320d1286
work/ice/RESTART/iced.0852-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ice/iced.0852-01-01-00000.nc
  hashes:
    binhash: 33ec981197657741718656f6a8fe36c4
    md5: 5ed0ae3273d8dd10ff9395b2fb822dad
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ice/mice.nc
  hashes:
    binhash: 72ac12be6c125860e815bd09e35a538a
    md5: cec1825fd608b0a80132582c9b7e26a6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_age.res.nc
  hashes:
    binhash: 418e1cc2f5fe02ea962048f2a1a1792c
    md5: 2a9cd84598b77a12fbd55b93147da9db
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3e896f9bc5228caee8ab6c8ef7d2ef80
    md5: 3104a854126eaeb8207a1d0e05709a61
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ca8d53d4afe8ec02fd97bfee2e40892b
    md5: d356d68cf323cb36b9e546d2eebbb0db
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_density.res.nc
  hashes:
    binhash: 466629f70705d416968a0725b960a6c7
    md5: 2cdc2bf15c82972b6f2473df478cf078
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ff8de9a4358c1f15f6275556b8269390
    md5: cbd4a7513ebd28216b860ed21fb8dba2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a124ab02484c69c83e79812f44f7016e
    md5: 95d3b89099d38e82f22e6316b3129e5d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 89dfcfd601bb74d65297c6f6dfb5592a
    md5: 16af694de011a1f3218707dadab53262
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 96da5877073872e304ddb1b90bdbe576
    md5: 10cc7d14fc948cc268bed6c7f1a12941
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9d6f46d39a206c34285df743160b3ef
    md5: 3981839730fb15f66b36768315dbce26
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 30af983e12ef0960b6f5195391b68864
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_solo.res
  hashes:
    binhash: 5f3fac97a1f398184a4930d7b4b925ff
    md5: ac023091af10bad593cb72e51a07292c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f818983cc457a7bd294214b08804bfe8
    md5: 9bb16d75f7c56dffad17f38d67da7401
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 53a6758bfd4ed7dcdd1fc9c792c5c6bd
    md5: 6d2a08aeaaa9a06c5a2993ade72d679b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_tracer.res
  hashes:
    binhash: 5a3590e829e9acd6197173b6a788a688
    md5: 19dbf7e7a2481bb0abec2a7164aab070
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 73c09540cb6d0024589c151b481efb1b
    md5: 3b7eeca10dc9abe9d8ebe9ec62ead0dd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 72f60583ac8718b56a5e1558a4cbec9e
    md5: 69e1d949532001ae968b4d28f9a7c779
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b52102fd4d6c062ad875a60f7a5741c1
    md5: ff145917ff0fac09053afcd847228920
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart298/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8ce7fd142794382a5547231b6b0ae493
    md5: 746d87f35c821f89618359f4391f4310
