format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/atmosphere/restart_dump.astart
  hashes:
    binhash: 61f2174631a35ed512298a89dc7a48ab
    md5: 2dd22f941e6f425867da92898bd079c1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/atmosphere/um.res.yaml
  hashes:
    binhash: 7ae4e2f4f95cdc3898f19fada4125b27
    md5: ab908d91044c33250e562d307af78b2d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/coupler/a2i.nc
  hashes:
    binhash: a81d1ac8ee767f9eaefd1ea517032abd
    md5: 08fc37df873dd5d4dd582339e922bc51
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/coupler/i2a.nc
  hashes:
    binhash: 651b19c4874c372b45d238a39f2cb504
    md5: 638a4eacfe7618f68d12942916eca19f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/coupler/o2i.nc
  hashes:
    binhash: c9e70fe38c91621057d847e37564a9aa
    md5: 59c127354d1757983f560edb9cf31d93
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ice/cice_in.nml
  hashes:
    binhash: 881aaab6cd311a1c6b5879d2da15761e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ice/ice.restart_file
  hashes:
    binhash: c50013f573a8a8570cedc8b321bbe4ea
    md5: d7d281b0fb8593207e24160339adffd4
work/ice/RESTART/iced.1835-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ice/iced.1835-01-01-00000.nc
  hashes:
    binhash: 5cb004c25151dd13842d3b5bd1efae87
    md5: 32106f2acb5b76a2c6ad82c39abf60ca
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ice/mice.nc
  hashes:
    binhash: dc33b5af4890510c77d7543e65524096
    md5: fd12bfd323d2ed62f2b14e6e8dc32f45
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_age.res.nc
  hashes:
    binhash: a0a6bfa9a1271015544d32f678e7c8f6
    md5: eb8ac69e0e665ab12f16c21fa3e88d0b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f63e1331660d33bc9560940df398bfde
    md5: 3e9f5f441bf7334a3a1dda1505366c25
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a215d23033d2725cca43ab61d581a6f6
    md5: bf7bbc33fd7ad0644dc687b164e13611
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_density.res.nc
  hashes:
    binhash: ec3e384d7c8cb4e6be422795257c861a
    md5: 0fcada4e32a9b3e54f32b5779ab1287a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 47bc9c851dfefb171f06a216b8a6d90b
    md5: 9fed37c9f71fb35bbb81bd1e205a6dfc
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a2c33aa41b732ec2123bd993e1f5b288
    md5: 416f9ee53648919cf6dd503c0ab839dd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0cbab67310413f604adefb42acffcee3
    md5: f33197caafc36acf89152084c4b793ca
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 16be516e0c24a4f3c538fd96ec738508
    md5: dc165fa7399619e59db5f4ada33eb699
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f1e311148f64a474eaf4e9b17e0fcdca
    md5: 03e86ed2faee30d99d461d9d5fd57cf8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 399e33b1a290b4fcd756f160d8a4dae0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_solo.res
  hashes:
    binhash: 1279b24d5447dbca760ea3b2ad44d5a2
    md5: fac1ccc8c63e1ddd91f951c29a69063d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f0411f11353ea8f3683ae882b00651dd
    md5: 2bc62fe5dccdaa1adba0c4ddf61fb9a8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f8179106785d3e1d5f4178781a4b71cf
    md5: d3321bc9058405d8a2cd699bb6dc86d6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_tracer.res
  hashes:
    binhash: 3c6dfcade27ddf69df5f267ce8f832ea
    md5: 7f2014bf62e1d0e6e0472f7cd714daaa
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 59f9973df80df20d5276010dfcfc71f2
    md5: e7d60c82b4af80e0c76f22037fcc3106
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b9c03fe62feb45cbe0e7df473d40199c
    md5: bedde7ea58d80d6785b5914d8992454a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0065d2a9ca8fe36a69f030efdb3cf254
    md5: 8624e7fdddc2196533b189a50b76459e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart390/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: db9ba9dabc6a43ecaeb394f7380ba4f5
    md5: ad7e7b3e50551d455d1b1ead873ec790
