format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/atmosphere/restart_dump.astart
  hashes:
    binhash: 059da89a4574a50a426caa5dfcd1196b
    md5: 76ef34a6dce3e1f50a7d6b7f1b6ec845
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/atmosphere/um.res.yaml
  hashes:
    binhash: bc07d20816962427f606e5e96c2f8e46
    md5: d108822ec43e8b55d87fb88c2853a9b3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/coupler/a2i.nc
  hashes:
    binhash: e756bd8109af910b4d85403bf5bc79c8
    md5: f5cdb1490cb62ddc22726ab9a999a95e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/coupler/i2a.nc
  hashes:
    binhash: 436efdbed91efde165e8a209fb7ea5c8
    md5: 106f5669f0a5d9f71f0dabcef7ad2902
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/coupler/o2i.nc
  hashes:
    binhash: 39b89b48f672d0f317e2dcd7cc468b67
    md5: 2b56585ad6eebd7942068edd57be0973
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ice/cice_in.nml
  hashes:
    binhash: 7e20a2efa241fcc6bc845696ee15a880
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ice/ice.restart_file
  hashes:
    binhash: fffca0d40aaef1e4e56a251ee6d044e0
    md5: 55720a20d54c9d52a6e0a17a09ef874f
work/ice/RESTART/iced.1784-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ice/iced.1784-01-01-00000.nc
  hashes:
    binhash: ba0eab770144ef94363f92283cb07156
    md5: 039272fec525d8c8db56aceace5db6d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ice/mice.nc
  hashes:
    binhash: f2587dbd0fcad6ddd1e04d9c8c51617b
    md5: 8fd8d31d07c3967bda8eaa4cf5fcd1a5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_age.res.nc
  hashes:
    binhash: ecc1ccfcd63f29ff5dce2bcdf9b23d7b
    md5: af78904750803f332cfef4f9adbbcead
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eef62ab0255f689e6a40f71d17381c53
    md5: 4cf4f9e2b47fe68c7f23d2d4d417ff96
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8979c879432964661e550ca9eb87fe48
    md5: 71d5b2790ab8666e51f0d5cd894e1db2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_density.res.nc
  hashes:
    binhash: 9b11bbedf168f5652d4b1b9bceeabe9b
    md5: 871bfd43869cb28fb01e52c87956c481
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5c6a37c27939c10548c89007418d6061
    md5: 19dcf06edb282ed8776f449a10584f64
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e7075596151f164ae114371ac81d2489
    md5: 07450cb98634732c4835a47feb92e550
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 277fe3eddc27cc53694d2a94c9388b5b
    md5: 0196749ecf76e1a84a3181f71a1dd5b0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dae9ca321b2f00bc344b31e4f6d9ce32
    md5: d40bdcad75efe5262f1e2c6357e52d94
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 447baeffafc998e55999af82021e4c23
    md5: 375955780d1d656d652381642344f49d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7eda6b7163e3e0eb9adf288f74b992c1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_solo.res
  hashes:
    binhash: a715c22a3af83179cef146d0f8d90407
    md5: 29b2ccf111338869a49761f97e3b71cd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9453d8fc5ad1cde1ae705603626774b4
    md5: fdabcf0d8b001f43e0cb523a8c0be89b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_thickness.res.nc
  hashes:
    binhash: df2c7bed8a95313cdb823b4a89bbc73c
    md5: 385a259b60dc35f1b4c12adc5aceb851
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_tracer.res
  hashes:
    binhash: 5ddceaee473cd0a5eff9294f839b6cc4
    md5: dad08627bf1cc26105ac5965747eb200
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9e8d8d91c4b4440c3109e57306ab31ff
    md5: e20f197c907441a647043a7b50934ed9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d4f80ff4baf4173ddff43790a534e679
    md5: 05d3958fae23a6f1ece6076c37f74d51
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f2eaf892ecffcb74639e12863664eb49
    md5: be371e97867f48aebdd35ecebf9af49a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart339/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 406f4ae82dc5c56b6d8960cf07dbdd87
    md5: 6aa17697230f90527a3d6a9a109a8145
