format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/atmosphere/restart_dump.astart
  hashes:
    binhash: 81cf885c6bf3635d6c74ebfa7ace11e4
    md5: c46528409ad99d58004e2fb5d1a7c2f6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/atmosphere/um.res.yaml
  hashes:
    binhash: 5a6fc6f47bb2c4ae854cf3040f964b20
    md5: a7d045d9009ff4489ef6299f54482a57
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/coupler/a2i.nc
  hashes:
    binhash: ca7cd1f7819902a06d33071c08abcbd4
    md5: e030878a0cda5aef2d77c2e282a563a5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/coupler/i2a.nc
  hashes:
    binhash: 818e2d205530d470a824d7eb315a6a42
    md5: a96001526a8d011ed1e89495e1e2f7fd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/coupler/o2i.nc
  hashes:
    binhash: 49ac19199845da5551d0cddfd1e212fc
    md5: 2015757c38f0727cae1dc468e3067355
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ice/cice_in.nml
  hashes:
    binhash: 3d1ba2cf7d55b05b122ab6bf3e61a2b4
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ice/ice.restart_file
  hashes:
    binhash: 780ebeec1615a5b4d064bf3f35bd648c
    md5: bdc104df18c37873d323edb845f458e7
work/ice/RESTART/iced.1256-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ice/iced.1256-01-01-00000.nc
  hashes:
    binhash: f4496a9d49a72a9e1ac51a1ff6914f47
    md5: 4b230535551759cc51e6299afb02bee2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ice/mice.nc
  hashes:
    binhash: 4ebd33d4465124725dfbb8b3ef600b0e
    md5: bc27899e7527f336d5f3f2980087801f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_age.res.nc
  hashes:
    binhash: 99c7dd1902d76948102efa238d99276e
    md5: 9002b074050d829c03dc285d42f3ae0b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 58de14df7165625d5e6d94fe6c291dad
    md5: b86a1ed9d0748077cada85206814924a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2030c14f07b2835c49a171324e546e2a
    md5: ca86a61f9e0e68b08000f6b89d844541
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_density.res.nc
  hashes:
    binhash: c4decc408f5f7543b144abae31b7fc78
    md5: 28efdea90bf17a6a9012ab99d55226c9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 960d04cf41dd51384d03039fc7fa9de2
    md5: 6e6b817ae9d10050e30ab5fbee6fcef7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ff66f9d05b84153416a21dbd5ce9b959
    md5: 6811fe1eb7bae620c200fcc24f756a26
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 26f9b6bdaa82fd4d77443925817dbda7
    md5: 36f9eda836300cc1cad2149b28a1132b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e9029461b63ef19cff31c27f7a99dfb3
    md5: 2530f7f703c8f2e603df2dd2842ebbe3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b5fbe985432125a6846982583b10f2a2
    md5: bfee02d891d2c18f820bc45f1cbf77ea
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f867c9e03092025da761d34789c8f829
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_solo.res
  hashes:
    binhash: 7924fcf2013147c0df5cd4bb3026a570
    md5: 75ad86d5e8fb8052ce2593e92a619f32
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 73f100d60d22a71adbc12ee4bfbd912d
    md5: eddf52b7b1665a34f7bd062c3431f506
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4c73762fafc6ba8bd9133d484a1440cf
    md5: 4e3c0d7a29568257753849d0f61d7abc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_tracer.res
  hashes:
    binhash: 5dbe7d9df30cd69499abcb24f55fbac6
    md5: c832a7311dea996404b1ff907a38bb5e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c56d637578ad3f885df7a49fa854be40
    md5: a05784ab57b305b333418ca3df20fe37
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6c7b6ae17e2d2b1cce621a95149ad616
    md5: 50efacd6940415fdda5ae638a4adf06b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0473f6836163eb7adad0b21c60b8f921
    md5: abde3aa1c75dd03fb0bcc039fa3ab988
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart372/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 49183f6ddfe5199c257a34487efac164
    md5: 3def15d527508f74e52c83e84f8222cb
