format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/atmosphere/restart_dump.astart
  hashes:
    binhash: 8c3632750b18246f3df0faf147cb0e89
    md5: 7dd4ef24acfe0a0ad543e8814f1b7a2a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/atmosphere/um.res.yaml
  hashes:
    binhash: 61dbbbaca1d445e95ee8813a9227b1a1
    md5: 06f89e889a7f253358fb40014e9042b2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/coupler/a2i.nc
  hashes:
    binhash: 7ec37e42f9caeb70a016ed9072aeac38
    md5: b4c14417e6cc6a001f446e77adf44bfc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/coupler/i2a.nc
  hashes:
    binhash: 57bb47493601f24773c1224ed59d6194
    md5: eb708cd5065d8670edd7202cfcce0151
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/coupler/o2i.nc
  hashes:
    binhash: bb201b26c298cb085f0fac7df785e686
    md5: 4f58dd02adca4a25f8657e8015dea414
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ice/cice_in.nml
  hashes:
    binhash: da5548411fd1f31716fca1ba5c696164
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ice/ice.restart_file
  hashes:
    binhash: 8152d92b14aa7712695200b99620e99d
    md5: 1a96580b4033060805dd1e46073aa467
work/ice/RESTART/iced.1818-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ice/iced.1818-01-01-00000.nc
  hashes:
    binhash: dfe428561deb7f21a84e56d762190723
    md5: 6f9b8df23b76d4bf696441e16f625e68
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ice/mice.nc
  hashes:
    binhash: 846ca8cb805ed75ed08800782262bf8b
    md5: 14e7e32d4a5956c894236ea49ef0a058
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_age.res.nc
  hashes:
    binhash: f733d790841429babe7c33c034e49b78
    md5: aae992783551a87342f1a06257245468
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9d88d60a778748ccec88ef46575670f8
    md5: 66103f4ce1be58f7e37fe14e37ac4ef7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aee849087ebada4a694bd0d85b6c9515
    md5: 1f0b84b8e133018955c92e6eaa2500d8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_density.res.nc
  hashes:
    binhash: e32d16dc06e89451f4aedeaa74fb91c6
    md5: a1c2468c82ecd1a130794c9e05c30ef4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2d27a16022debd9eacca0b28bf8800d0
    md5: 2af39923b621d61781247a5260493b6a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6d692b8c5ba2f7722aa47b68b3a9f179
    md5: e5aa87f4f92355036771522d50c93d69
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_neutral.res.nc
  hashes:
    binhash: df59df50ff592c87736bb527b729d247
    md5: 5f138a88ea8209d401aef86153ec07bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9c1c281563c39b8668c190d4610a6685
    md5: 9946dcd4cfec2d75e609d37a06f474e1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9572fa64cd8212a6e68e0ca48e1b2159
    md5: 30f00877b3e371136530c4f0de26fa3d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 513f00c2d104dbd337b4d5884ea38cb7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_solo.res
  hashes:
    binhash: 7d6d45f0f8511bf29a0d344fcd82b649
    md5: 07b21a1b698ecbe2e8dc8ece1329dcbc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 17f2229815be3ed5d60fb80b0f7835d1
    md5: 5da9bb95253ef12d5d860a4b000a7875
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 466fbad91abc841c443fc66fcc7b6ed7
    md5: 896155a1b74017fcac9642eed9c22177
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_tracer.res
  hashes:
    binhash: f51c659ba2bd7041001df98fc961a2e0
    md5: b6e74d154f83e140e58f5515213cdd59
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 930b6ec3e7afe74db65a0d4608c9227f
    md5: 7d471a46d1953619e9acf5671fc6c36f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3f95323238120fa8a55e11276f9d1d21
    md5: 4d80fd06bb04443dfa873c0bc3cb0837
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 11d6af35342d1eb2ecaf8ead4c8f293f
    md5: 65d23a2d5b20df36437268d7d296ed01
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart373/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d580d4da81cda60be2381aada32b7b97
    md5: 20a315cac9bea7c534b7a40c61ae0810
