format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/atmosphere/restart_dump.astart
  hashes:
    binhash: 89b27518351d96438b570ab547c1ddd9
    md5: b632eea5317de2ce8586ffb162eb7aac
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/atmosphere/um.res.yaml
  hashes:
    binhash: 73074570859b4c23bf7f744bc8331e3d
    md5: bd6cbdd88f904c66a4e105e2ef0e2721
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/coupler/a2i.nc
  hashes:
    binhash: 1f805c9509a04c3a30ba3a97ba236e14
    md5: ff0f25f252fc9d67b16375a475296f25
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/coupler/i2a.nc
  hashes:
    binhash: c0a9aab9de0f948715460d3797c9647c
    md5: 0ca103c11366af8ea02a2762615282d5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/coupler/o2i.nc
  hashes:
    binhash: 91ac40b27663c68883247f20b5767215
    md5: c7e569a8514181d56bfa945edb425043
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ice/cice_in.nml
  hashes:
    binhash: cebb08fda8e07d899dbb6d4163199902
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ice/ice.restart_file
  hashes:
    binhash: 390115a543726a0f4612071b408865f1
    md5: 50e342f9d03549be942036735f1f946e
work/ice/RESTART/iced.1802-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ice/iced.1802-01-01-00000.nc
  hashes:
    binhash: 458ec9d663293198c05c42bd00637815
    md5: 9da338c40d0b16ba5b668de7c2e2f938
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ice/mice.nc
  hashes:
    binhash: abdbf202ba6677fc02f88c26db0936a0
    md5: 42ac96c44481b0f78f80f602822ee1ff
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_age.res.nc
  hashes:
    binhash: ebbdd70eb1f317ba5027e5e7feb52ad2
    md5: 10ac297f41e371d9b6226e36ff1d1b07
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1773749c94558f4d7cee0710e7754dec
    md5: d5fb4836fc172d8084ad1e280ad2b9f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 27a199c29f0cdfbe2f95d1dfd3e0c986
    md5: b6d0b86b0893111c49c8b238937ea955
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_density.res.nc
  hashes:
    binhash: 30b59a3d11e81222bea7f6dbf8b358d1
    md5: a292066b35d4005f9473921c5c813945
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c7d063b9fc5ce09e650b06fd2bd349e6
    md5: 7851a3a2149c5539560f221735e34efc
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d11b12ca4ae414f644a0be1d737587fe
    md5: 629cc40cd9b735a5c40672348fbebd4f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1eaf850243ff011eefeddec5b8d878f9
    md5: 12829fc7c290e30f9ba81ff992232195
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2a28cd80357200ec95df02f3f1cd5cef
    md5: 2ac25e17270aaf5ebf157ae4abf6aed0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f271a115f0cef7e1c19e920773f8af10
    md5: d17e3a7f7fb75168b59fc43e5bdd0e87
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 01d9e04652926d25c88dfa574e29a9e1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_solo.res
  hashes:
    binhash: 12a20c00f4017c1cb3395367eacbcd04
    md5: 722bdd9a23e91e637c96dac9f2f8465b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2de45acaddf4564d7daf49dbbf49f7c1
    md5: 7b293a4f0086f6b596751432fa851ef8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8ec5c4b12d38afefeda72b80ca81ecc3
    md5: 280b63d94c119f14516295853111c2cd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_tracer.res
  hashes:
    binhash: 4359cabdd4d01bcbdb9bb3526d324f17
    md5: c18f2ec918457b8818979cf9e839cd80
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0ec53ecbcdb5aead83054d56def0367d
    md5: 307beea96e8911db03623b457c49b346
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0774c77647ed6c7da1979945b3d29a06
    md5: da7594e35e55a3dfa0b537cf611af840
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1027534f3b712614dd708adb4886b531
    md5: d2c2235fbdaa35808ce2e002b0582259
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart357/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 369f0064e98648d0cd92fdf11fbc9669
    md5: f9dda5c581bfbeefe223dbc1acc462c1
