format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/atmosphere/restart_dump.astart
  hashes:
    binhash: f64f58e3498a6ffbd7d28a158afe9b87
    md5: 747d6961e7e2adcc2b2cf4ddf21332da
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/atmosphere/um.res.yaml
  hashes:
    binhash: a0f87db495a0cec5b0664f956221eb5b
    md5: eb94e5d4187e43df24373f2db143eb66
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/coupler/a2i.nc
  hashes:
    binhash: 8fa3ac7e49486d0d6db4056a8d968bf5
    md5: 87a60503acaefc42e6e4c1ca37f4d19b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/coupler/i2a.nc
  hashes:
    binhash: a6155dffa90c44c44bf2447a8295a627
    md5: 5e74c8b417f39dc14185719326f278b6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/coupler/o2i.nc
  hashes:
    binhash: 49ddbc060b696ad4c47f6f200fd4a66b
    md5: 83accd937365e764906f93e015e77c79
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ice/cice_in.nml
  hashes:
    binhash: f2466c46b9a235dad812d4c7e7ae0bcb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ice/ice.restart_file
  hashes:
    binhash: cb7123df120d3bd96397091acb0bbd75
    md5: de827dd5b079c866e8bebad1e35f8f1b
work/ice/RESTART/iced.1152-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ice/iced.1152-01-01-00000.nc
  hashes:
    binhash: 9b81dc7156630ffb2f17d2a0e8448dc9
    md5: a7722d7b8bc299fe5855f5357cc0cb25
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ice/mice.nc
  hashes:
    binhash: 322cdef04a0ca88e57968613d2f293ed
    md5: 24f4e53c54de3a7f617b987a3c31454d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_age.res.nc
  hashes:
    binhash: d077bc522d8b0e8fdaaf111d9951f36b
    md5: 389b3b9e0a88b26497e4b23f871eac04
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3b281ac2d485d49cea55a9c2eb3de976
    md5: 86a0293d5d15a2adacd922737d06ff4a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7f48d63c05c7351eab5c913607df9ca5
    md5: 0172c51452638448572a1b19f9e4d01c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_density.res.nc
  hashes:
    binhash: b1852ea8bfd67a081011d03f041ddfc5
    md5: a07b9637b22125a4c5c7ec7c02c8bcdd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 528db2287839a46b0cf05ab2b68d2eba
    md5: 2d0548659c4eb427c223ea2e666f1c35
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 10a86aba0f6a536f458a65f94e43ca15
    md5: ff0458225a4c5efabef725adc118e3fe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4af80f70dc2b050ac87aa4e9f8cd02dc
    md5: 47ab2859d9f7622937ef5ef3c818856a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f481fb51b31864beaae41c88288c7dc3
    md5: fb793216a1b5b15d5314c85b00d13f4c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 30c9a4d4f876f7d400c64629cf994412
    md5: 8460de42bb14a8a304f012735e4fcde5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9e4b06f790f5a438cb641e177dc61ee8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_solo.res
  hashes:
    binhash: 9ec3a6f7ab1461aa59f6d1bd8186b0aa
    md5: f7af209f7e87ac145e56d78dec28c6f3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4a9941e17f55e5bba375077602759265
    md5: fbb3fe2aecb3a14b6a176d88868db036
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ac36e6485cac2cd180b832936d557d2e
    md5: 05a90ba886995b9677b134ae4d20a628
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_tracer.res
  hashes:
    binhash: 82c663947f20ed05e2901d581bf85415
    md5: 7fd5fdeabaa8af5326cd940c6ac83fdd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 59a7b297b5d03b934a1db436d86a0846
    md5: 3a060a09a6f652b5523a47e493d599f6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7067f2f2cb43c84e6d11b37e72e3e0b9
    md5: 2cb6a070e9339c9a27fc27dab580ebbc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0aedf9129d6af3310e11f6bbdf961e8b
    md5: 8f46512c3e0a48763c55d1ae0ba90463
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart268/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a3d566f145a7c71c8a0784375b5046ab
    md5: 50b178c12ba789e7a8753b2963942ba6
