format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/atmosphere/restart_dump.astart
  hashes:
    binhash: 306b0f027a41af7fda41c6624f33824a
    md5: d7692aed301568d7389002158a24cf79
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/atmosphere/um.res.yaml
  hashes:
    binhash: 43e4ad9380d75411e81e954c5241817c
    md5: d55bdc9cea3c476c5e6d1bccdbfa7861
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/coupler/a2i.nc
  hashes:
    binhash: c83be09827b5fdee3c0e80afe5c17e2e
    md5: 39b91ae63d3ca7763652cf72e7eb093e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/coupler/i2a.nc
  hashes:
    binhash: 4f996cfc1da226c4f07f444280ef1703
    md5: bd7a07a068ad2c9049ddee62af2be46f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/coupler/o2i.nc
  hashes:
    binhash: 7487a42aec22e3a76342a5c15157a312
    md5: 312b689faa4f73e7cf7e1ab8d2514589
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ice/cice_in.nml
  hashes:
    binhash: 7a5c7aa0d9252ca53296973d2bf996e5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ice/ice.restart_file
  hashes:
    binhash: d14c3c5742a26994605aa808e2ad6b6b
    md5: f5e5998cd2def3e83efb74f1df9abf4f
work/ice/RESTART/iced.1840-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ice/iced.1840-01-01-00000.nc
  hashes:
    binhash: e8b3136462333d861e019db013e76f1e
    md5: 303e7d10e4d63850c29a6379d06cbfe9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ice/mice.nc
  hashes:
    binhash: 753fa801ebb3d528eb3d2de4e5b9efeb
    md5: 0870ce4644e3ba90dd07f02216a5a598
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_age.res.nc
  hashes:
    binhash: 57969373609ef65c7a190659a0f51ff2
    md5: 17c80f0883205db42844e9bf17393176
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 45604cf7823ba4f5e4745d29ab8a79b8
    md5: ac0162d27b2e39dc929ba303eeb01e1e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: af0b0d7cf096761d66793efcea0ed8a8
    md5: 9d7b4dffcc4a99aba8f4bf25fcf80395
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_density.res.nc
  hashes:
    binhash: 90b20caa72d398bc468c4b4bd2e1844d
    md5: a32e8dfc03d279c7d73d7798f2f28ebe
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6cc52cd785bd84096fd654f2fbf407ee
    md5: 7c4407e9722be1d8fa227f0b0128de22
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ebeedaadca0243197ae1b59de6e579c5
    md5: 592a8d058bac2508b42b568f99896509
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8bf0cb89f07729f497cd09cb63a1c321
    md5: 7ea5dd4bc1ade4ea3ab3bdc03673c9cb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 22ec8eb1ea5fea84432427bd2a5422f8
    md5: 98e170286c6a440bf30ccd170d716ed0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 36531e0a540380d252f70e32123e5197
    md5: 2e149dfc974b3e72af8d3db71854d693
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0073c678a528a21d45e2a0e90ab1f8f5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_solo.res
  hashes:
    binhash: 273b832c08ac7194fcc917985e55e95e
    md5: 47e6c3ff3ce61babcf20153ff152a3af
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e0d228dd3c81cc034a9df0e49d01d8ac
    md5: a57a4b51af4c92f121bfe669c8c29bf0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e12b600b49094a1bc6678c12277a1aa4
    md5: 7ac7bc883605ae0fc82c53335e68b32e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_tracer.res
  hashes:
    binhash: 3a45209ac4ab42aaca2bd7eb4f8366c7
    md5: cb915a6e62e606d86caa05cf23ac3fc5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f58841d697c24467452dd7856061f28a
    md5: bd9751d2d7a59a05c84cbd3fd0e7d96d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7638192bc422a852fc4681afdc780ee1
    md5: 2273d4347f26ce9d654eb95cd5234c02
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bf7137663335f27e5fb0e8b227b130de
    md5: a12180a57ccc6908fa5d7c0245e6e365
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart395/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ac0620f843500f6332f3c1bdec68e0ae
    md5: 9797cdcaedc0edc38961a68ba16753f3
