format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/atmosphere/restart_dump.astart
  hashes:
    binhash: 8878ccc9a67e486925cf2ee14e8f4ae6
    md5: c70dfb989e59e62573b82e40d47ea0dc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/atmosphere/um.res.yaml
  hashes:
    binhash: 654916c1a900655c4ff13cb9d966cef3
    md5: 51ad7fb54bd3cd2da5315a0b3e1e09a4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/coupler/a2i.nc
  hashes:
    binhash: 8d655fdcc670bf89916a470c5df4d248
    md5: ddb94b4f3d792a9145c87e40f09bd4e1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/coupler/i2a.nc
  hashes:
    binhash: 80164575cd0eeb6fe790be731bbf08df
    md5: 96e04b016e2bbd9d1e554f95d8ff64d0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/coupler/o2i.nc
  hashes:
    binhash: 3b310faab7518fdb32b6f0b9d4748490
    md5: 376c5ad74028d60fee411c5480577e1b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ice/cice_in.nml
  hashes:
    binhash: 2ce393e2c07ff29d2551e0e95061fa90
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ice/ice.restart_file
  hashes:
    binhash: db23b0ae72522b3ccbdbc180db9c1d82
    md5: fe6ef6501311959753e0f5614a7fe29d
work/ice/RESTART/iced.1294-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ice/iced.1294-01-01-00000.nc
  hashes:
    binhash: 7bfcfd613b3e2a47c136e62c93e6bf3a
    md5: e7dcdb6aef4c6a59571f87c720145e34
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ice/mice.nc
  hashes:
    binhash: c6b8fff245aec6d862fe22ad3b1196c6
    md5: 6a562e9db5237a539e5a0b176e9fef66
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_age.res.nc
  hashes:
    binhash: 7074665d8edfb0e672dc2a6cdbcdc749
    md5: f3105006ec10ff407d48f9c4698d2016
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b4fffc6492a983327a1ef497398efda9
    md5: 7fd4e03c2566c553129b9898b91c7d2e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9a871dd724d4a639aa9f1ed97023e5af
    md5: 0c041f55da6b99c4d6fc80318bdee09b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_density.res.nc
  hashes:
    binhash: c73db8ae412cffdd0ce6e2eb22fb57a9
    md5: d8d816ffecc8c146f4e63c3e5833f5f8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1febe72874867ccd8bce42fe24a6fde8
    md5: 4b1faf85b38c566e69a44af8b0562349
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f585cef3484302070fd4f7a8a9d6af9c
    md5: c91078d562229a8a4828003b8f30faaf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 93f6b7eeb3e7f7ef640d1351b5ab5818
    md5: a0ac64f37b9e5371cd2b9c1fd2ddd8ac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2a7e850c3525eba28357dd4e6320ccdd
    md5: ad17e5f7827da7837ee093dad29413e4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 04f25af0418e8074b9318191fad007d9
    md5: d3e9aad832b48c6743a1af4d28bb0414
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 071cbb1ed2ff80bec6ed573239766a89
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_solo.res
  hashes:
    binhash: f597ef94d88f6c14fdc0f975571abe32
    md5: ea2284e3fe12db45562933abc93e3b05
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9f5db037358056a20e3e1e54c4f84183
    md5: 03921875079c02a4e1da1491c7375b76
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d117b4ebe92b612d239a27b2b6059ce0
    md5: 91858031f3bf20fba8209797e4726b1d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_tracer.res
  hashes:
    binhash: 90ebf2bfcd256bd6fc5b29c12c5e80c1
    md5: 3ea0256b3211c8018959b162f9e98288
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_velocity.res.nc
  hashes:
    binhash: acb86c01bc46dee15a35a36ea4908623
    md5: a90b4e9b701dde09d57c4d2046aae439
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d55335ee0cf8edbaacca1b1205653627
    md5: 1f6fe6994aba8e7d7c2718da2d6c8d90
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b9080cd4079993cb7cd7205689d7f81a
    md5: af858d1e38d585a41271ce4fd787e28f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart410/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6cb4cdd1260d5537083f1e3522b6453e
    md5: 30ae809ea1976aef8b54f6a034a3b356
