format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/atmosphere/restart_dump.astart
  hashes:
    binhash: a64448c46051697c503c073ac321aa17
    md5: d7eeda00b3302b94a88e0e8c8eb08aa7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/atmosphere/um.res.yaml
  hashes:
    binhash: c812645b7744666f3f7fcaec25ade703
    md5: 6c8bf601b5c01b24e30937faacd4855b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/coupler/a2i.nc
  hashes:
    binhash: de5a0d3911c9c0fc6e32599492df93ee
    md5: 92766a6ccfa6da06c2a205e39eb38393
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/coupler/i2a.nc
  hashes:
    binhash: 6a02193ddccc489efb69e307e658464a
    md5: 6699b14c8475a88f3eab8899d674b008
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/coupler/o2i.nc
  hashes:
    binhash: b18e9f5a5ef6b5ed3c9170c2bd14a19b
    md5: 20ae63fb06cec339417506fd17a5f3b5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ice/cice_in.nml
  hashes:
    binhash: 4f275a14d61aa9323756780eb2e9c96f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ice/ice.restart_file
  hashes:
    binhash: 838db6d454aab97f1613856fcde1bb54
    md5: 1442f183bacdbd530389cea7961e7d86
work/ice/RESTART/iced.1771-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ice/iced.1771-01-01-00000.nc
  hashes:
    binhash: a2ac371cdb04c950b3dcf457bb1b1045
    md5: d798f1ac6af3e1b92dd1be32ee2f120e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ice/mice.nc
  hashes:
    binhash: a1240440edaa593b66050949f8d47e24
    md5: 8f639c67b0c2b66e03b8605684cb49b6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_age.res.nc
  hashes:
    binhash: 03720c61c247ec8315a484c18c6f9626
    md5: 90a2f93260e7e4301dab23ad1e672794
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: db23a2b8feb64f79ca2a5f06e22e877b
    md5: ee5cb08bdcb29250c4b99a7c687ec78a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6a8f29915cd33c56b280459295e4eb39
    md5: fe1f356e5985bf5e5621008d97053333
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_density.res.nc
  hashes:
    binhash: a42f20cfe017714c1dbba71c5e2780b6
    md5: 259632fc67cad0d343b9bc05e2435ea4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0e5db7f9d5d7e48d397231a937e3a8d7
    md5: ebdc2a1646a5ae3d491d409809bd128d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5964b1fa06f26d9c3050c2071c0d893f
    md5: ab66d4aa4072158fbe267a41f1bad53d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 91b05b8ea6e0cfb10cefa970ffd8d2d6
    md5: 34883b1c2e87a80897d892609e33bb46
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 420090b7e0287e12408846db6a8c0680
    md5: a5f9bc72590ea59d94c6b97726a8882d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d7c46779093e261bfdc609b4fe1064e8
    md5: b2c1911097f0d55fc2a09797420ca211
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 64e602f2742db0e6efe5c4dce19d0473
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_solo.res
  hashes:
    binhash: ae432b58ac884297103a2b683c0836a7
    md5: da0078e6580029c470cb97a691d13582
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e662d907270bf5f60f9fb3ba42b1eaac
    md5: cce88c2fb9072eaa3a40b95da5572414
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f5dd04fe1a6c88cc16c6a8b7cc5585c7
    md5: 709d32d03ccd04dbb70fa40592bff0e7
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_tracer.res
  hashes:
    binhash: b3925a448613059f7ff04af15b9ae442
    md5: 057fb4e957a6494af91ad342b962abd9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2c79f6a2fe5ac447ff93ff96a6f82635
    md5: 7817efbfcb21f54c3f2c59b1cb0c7e9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0b4c07133bec1e59267e5947d62c48d9
    md5: fac968ff5df85dbb57cd9222e9bf1b7c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e7ce979c9acfcb4bc87b972222121f15
    md5: b2caf4eef256717bb193cc5b39e11efb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart326/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8f8a7b8144ccc8f7b395ad2306b4c53e
    md5: e0245bb0a9d37177f72a8f13a0c455e6
