format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/atmosphere/restart_dump.astart
  hashes:
    binhash: b5773998c426569ac85684b502170206
    md5: 3dc1c0f6e160f0227034098bf1bb35a2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/atmosphere/um.res.yaml
  hashes:
    binhash: a2d80e39156f9c6aa19e20fbe4a66374
    md5: 1c4ed497cf60412a89a7b7e408b1edf3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/coupler/a2i.nc
  hashes:
    binhash: ef03c5b529f4f29257e9e8b6178ca14b
    md5: 182bf5dfde924f54ede78a57d18af753
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/coupler/i2a.nc
  hashes:
    binhash: 5ac746d0e8be64de9514649a084d5f00
    md5: 53685c3ae562665e744e9336d6c2a60e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/coupler/o2i.nc
  hashes:
    binhash: 1db6eba4da92b8ea2d51c1aacdcca4c5
    md5: ad509201a19efad71423211ffe719aa4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ice/cice_in.nml
  hashes:
    binhash: f2659824778114dff044948e19b5f10e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ice/ice.restart_file
  hashes:
    binhash: ad8c3804c32aad88875c0e103fa4b952
    md5: 00e8330d2a5af5ac5fe0448c1af4c6ee
work/ice/RESTART/iced.1309-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ice/iced.1309-01-01-00000.nc
  hashes:
    binhash: 13510aac9eed87970fc8897f2f9c6113
    md5: 3579842b51cfbc9a293f6622b766372a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ice/mice.nc
  hashes:
    binhash: 3e6ba071cc4bbb0a1dde6ce63732c6b2
    md5: ed8213fd5604e226c28abd467cd90393
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_age.res.nc
  hashes:
    binhash: a1d1bc469711d2255be1d89a2ed7e8da
    md5: 09571bca9d608dab7b79f1efbccf2029
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0c8beb417778035a62640b84d2c12a5e
    md5: 18a1ce3eaf13ef7836dd669d2fd85328
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f94aed756e0fe7a57d1ffc95d4286a67
    md5: 38101b7afe927355e976c76193349898
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_density.res.nc
  hashes:
    binhash: 5b66a574f291f4075f23765171d45a3f
    md5: d601594e73d1b940bb65c7a3268ba1d5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2e4d751b8a6fcd2b97a7958d883a414d
    md5: 9565ef8502083d5713656d72dd9e7915
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 850d8ad9f63e4e1758157c4be5c9ed27
    md5: c4b9f1a65610cc9199d47028844bd00a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57f970285d83e22d37d927b583739898
    md5: e917647ef74133d1aa614c85a47ed183
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 96df0387c0e402cc46f37993394d795d
    md5: 7ab7883a6d4e19453a6e9829daccb0e0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4e893b2da2c23b8cb8d795a72235c741
    md5: 41e02170c513ddd940c8c68159032ad6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b2b34ea74af1fbbd440d7184f514af76
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_solo.res
  hashes:
    binhash: 2b5e275c9b802cf097ffa529b8dc5a45
    md5: 73fc6444a596a37bf5543008b806383f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 42b902e8d185e920ad6db70fbf808d05
    md5: 7df4837b69f805f40d30a50ee7fc5fa1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c8d6e6f4e9b196fc0ed09497c336bed3
    md5: e7969a5229a852f49d825cf727ae6e1d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_tracer.res
  hashes:
    binhash: c9c4530e6bb09c489051ee1b3924d40c
    md5: 27e77842b79530643b5f2dd8a864c2c3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e1fa22e8b04073be52618fa89ff81546
    md5: 15ee45918449226be19ee941a41aa27d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5e3c6c6b4134599cb8a0449a06a69fdd
    md5: be36fe331023358c33633d2773884704
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 798790104a80b8d5e961705749ebc5ba
    md5: 7010716ca0e4b88e8127ec81198f946a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart425/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9743e55bf84bc03b2078750abc79b5a1
    md5: 5f34f6f8264f54fc8b9730b842de2496
