format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/atmosphere/restart_dump.astart
  hashes:
    binhash: 7e0ec105161524e561406fb64c1808ce
    md5: c2bda14bb69143551aab787ce1ad42c0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/atmosphere/um.res.yaml
  hashes:
    binhash: 2928e2b0c974b9181db2f0d7934ec258
    md5: 9520f1e60adfe4918167bef087fb6e09
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/coupler/a2i.nc
  hashes:
    binhash: 1e183ea8cbf8eff1f2aab403574b5c89
    md5: d8bc8a8c95b482172ec175d4c5ca57df
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/coupler/i2a.nc
  hashes:
    binhash: a237f83c7324d9e306105d6974725666
    md5: 68ee80e75823f8faa39f89b94c62fce9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/coupler/o2i.nc
  hashes:
    binhash: 467d5c81ad4e5f4dd3ca2fba8ff2019b
    md5: 69d17f383f369f724385145f933fc083
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ice/cice_in.nml
  hashes:
    binhash: 14a234aa19d7451ed6b834f420d5ef3c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ice/ice.restart_file
  hashes:
    binhash: 967fed6c77a3eecc71ad5b0c35472ca4
    md5: 2b38accd5f0277030251ecddbacbb758
work/ice/RESTART/iced.1799-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ice/iced.1799-01-01-00000.nc
  hashes:
    binhash: 47635d6ef2ad184fad78fb987b631840
    md5: 1c4d524a30db7f000a1ed2569fdb25e9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ice/mice.nc
  hashes:
    binhash: caca923e215281791cf88d89ca62e159
    md5: 6aca3f9a9e2988b3249b8a71549301c1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_age.res.nc
  hashes:
    binhash: a71417cac099ca751b5b9c98794e8e97
    md5: 547a480c88edd6c54c9cd3f6294b614d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b3d3ac4b7c8e22f80546dbfe213b847d
    md5: ebe441c05c901b5ae3e7c372175ad08c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f215c99a05ed26763647219955a72bcd
    md5: b66f2759e213b11cf0bcfd73cf63e18e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_density.res.nc
  hashes:
    binhash: 7eb904f14d71bab5a410db435d6cc599
    md5: 6c7a04a0ed83340d5b5e068cf7e7829d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 703dd769ecf59ae1f0a00c2b434b200f
    md5: c5d53517cf284f16cf5f4b7811e489b3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 389a3b1c2c9773119a2a61e4cf561f31
    md5: 85d6586668bfa440d958e9a5386f48e4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 867f34038701e646b35d13a24bbe6875
    md5: 75696b42c3d7ed2b10b86f4b45d71de0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d703ebf7cda623e29b39e04035942cc6
    md5: 5f0688b427cb20dee1135a6c3353de3a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d5fcc86975820acf187b1fa79047cd19
    md5: a0ddd33b955883beaf563d5e57bcf4ae
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e64a682a9e84b1707ab2c35d05ba8b17
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_solo.res
  hashes:
    binhash: d3e1985dfcc85f2890f6cb46fe577a62
    md5: ce6ae2f77b2f87b581c9337cc553069b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 61f3e32c45e82e91161e9b7cc8fa7e9a
    md5: 58c8309c7d40aa4219f104ddcb7a7194
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f467b78b54c38381287e6d21f5950931
    md5: bcabcae54226cefbafc99dd54876891d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_tracer.res
  hashes:
    binhash: 0e9e11f0306cc558d2a69ba456557811
    md5: ce56cd7bfbd7113fe88d42b6e6e9cf6b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d774925fc7985e24aff91a1f5fbed289
    md5: ce0db8a440815a477bfa7fa10163d92a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 02bd564e79df250e608561f20281a271
    md5: 89f1fd16246c2444e0118565edb6f800
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7807e985c9dbfe95819f75fe1cdd5d6b
    md5: 82f51b5462827afc779f9cbe75350f1e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart354/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e77277fae35d14ba9641ae4ca2ed714e
    md5: f7162a2db4c9eca5fc8d80ae11657397
