format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/atmosphere/restart_dump.astart
  hashes:
    binhash: f13b72a5dd5dea2d1fefa2f978cdb617
    md5: 9207623c2fa12099d251e593aa31bf0e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/atmosphere/um.res.yaml
  hashes:
    binhash: 0e6c28bf07d8dd7f5a6153e2606861ca
    md5: 5488f4804bca3f7765686f238f69f573
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/coupler/a2i.nc
  hashes:
    binhash: d2f077c906dc8265ef27820299536017
    md5: bce360c18fe1f209b9876f3cb74b8d29
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/coupler/i2a.nc
  hashes:
    binhash: ae75bbac00f61a4a9b029421866b22c0
    md5: 8b65d2f596bf9f3e0c2f3e058dfdcf18
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/coupler/o2i.nc
  hashes:
    binhash: a45d0a09768bc0669ac75967680c7782
    md5: 7c59ce31503c0e12819964c1171cc92c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ice/cice_in.nml
  hashes:
    binhash: d3fa23d6029f121da23ff1b39c535d27
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ice/ice.restart_file
  hashes:
    binhash: 09e334f7c389dd85709d4da12948b027
    md5: 243f49a6f033bf78199e59006dddf43b
work/ice/RESTART/iced.0926-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ice/iced.0926-01-01-00000.nc
  hashes:
    binhash: 2632d64cf3706eee2bf38607052d20e7
    md5: 4684d663743059ad88c37d8e445264a7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ice/mice.nc
  hashes:
    binhash: 1e546197e49a591cb2b9f35166b05f71
    md5: ea13ed8cfc070c2dcc89a3dc58fcf0f7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_age.res.nc
  hashes:
    binhash: 950b223bb36cbda8b52498f0d8966de3
    md5: 2771ab2c2736f034cd9375ae7d6f171f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ee15bc2ce82784711d159397e5ced040
    md5: 20f9f1f36a3c8366164c63cb9823c079
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 904a378fe7321d67000ef3e2c6b5ccc3
    md5: b24908573c44fc7780f43a47e386112c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_density.res.nc
  hashes:
    binhash: fb35153eaba0fd6fed74292995509e36
    md5: ec34daab88d8d0d0101510fb5021d8ba
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f89e1aca41a204e064090749e1a06135
    md5: 59b50d64ffbb0b2e52d78b25bc0cc1fa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4fffc4a99ab141cda3a8a1aa2647dd3b
    md5: 96bdf4117b89240a0cb57d277f5749ff
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 370d8cc9288c1bae4ebcf4d57144ec13
    md5: 17d1403190cf228f19c07204fcafe6f6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 46b67c9b2d852c5c703690546ad5dae5
    md5: 242b127abee481dcafb6181ac6349afb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9f46db16e493abf63880843742ee1baa
    md5: 2d8a02e19a278f695fe24881718caea1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ed1cf902d72996a12963140750956830
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_solo.res
  hashes:
    binhash: 49f0fcb78045f7c275e649992a145d6a
    md5: 1b03ddb5d05961550def03f8382c9175
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b1b930dd8e6c1b5f5516952d17d80612
    md5: 14a36ee6b9ef04f2e248c4f88bdfea11
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5971b4f42270bbd4d2ade36fb67f1909
    md5: ef9631400c96eb46c931af80f16af2cf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_tracer.res
  hashes:
    binhash: d5fcae9e5c250af34e996fc385b3b651
    md5: 714e5b5c0600b1d521b86ce4b06e3bc2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dd2b2b108946c4872510bc05e86307dc
    md5: cf1e3011ed747b1e7e325a4691900475
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e153e1df0e8fa70c7e68d27c942ad2eb
    md5: d249b6298302ac2c394412baa49e9865
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 466e2c3b84ad92b82277336c43f0f53e
    md5: 0ad17d81bcc58fd6926993925243d1f3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart372/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 403aacaef3dc5e72fc3b86eeac0f4bc8
    md5: 9b1d7c3bb74a44315f19b21f906af354
