format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/atmosphere/restart_dump.astart
  hashes:
    binhash: 6297a11131ff17e0a777e0139d87a072
    md5: 9dc44270944ed54d7311f5ac93903897
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/atmosphere/um.res.yaml
  hashes:
    binhash: 1065630cadadd10c02606299af3737c3
    md5: 41a95b7d69a943d27c62e4599b1a7911
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/coupler/a2i.nc
  hashes:
    binhash: 58a77bc7678c4efa379c61787a184f08
    md5: f131d66783f7cfe9b6cbcc622648e542
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/coupler/i2a.nc
  hashes:
    binhash: 0d876e0b6154c77f805ec028cbf3a0a1
    md5: 2bda6b96fdcd3f17aa99e2929441c69c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/coupler/o2i.nc
  hashes:
    binhash: 8c9b9bc54284272e58b5a438e59fbaa4
    md5: 828fc5880a9557c4dd64710ac7dc6f29
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ice/cice_in.nml
  hashes:
    binhash: 0867597582b88287f198d0eee538df3a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ice/ice.restart_file
  hashes:
    binhash: bc777c38b46dc63f1d933067669e96dc
    md5: 39937bfea3a17d956fab7a9241b2b87e
work/ice/RESTART/iced.0925-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ice/iced.0925-01-01-00000.nc
  hashes:
    binhash: 2b31652b76defb658f44fddf8858c1a6
    md5: ef59c2ed298ef9dc34462745349f4504
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ice/mice.nc
  hashes:
    binhash: 20b815dc6dd534e92adf116f8096a054
    md5: 6aef67ec9f1ff2208e598439390a18f1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_age.res.nc
  hashes:
    binhash: 11c822447f02decb71a6c93287aeb0da
    md5: 089f7dea98a03453d8bb4510c794befe
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5c04436f8b390202843343281b84340a
    md5: 626d7349886e0627af1f43991bb894cb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e013ee31fb9931e4071eb82008c6ef4a
    md5: 49a11b84b87ddbae16cadd4538201d6d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_density.res.nc
  hashes:
    binhash: ea9e5724990ee39b8594813c9b4d49b2
    md5: 83790b76ff38f44c21962c8fa315266c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 87a9ac118e1e6443fedbe9248c0bc01e
    md5: e7efb77f328f5a92390767dbc40cd4b6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 86253c5c7d49210ea49e9b19ed1e3083
    md5: cd5964363ead7875b39394930e0f751b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4daed2498e9c5e863df0d220f86f9161
    md5: 60573fd52637e8d9efee79c69c7afd18
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3b56f9e67e8bbe89164fee97ab560951
    md5: 0b9eb54ecdf9468094b6525923188a0e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 82730f363828e34e201f095d88ccda37
    md5: 8eea307540968544664727a1772a678d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6beaf677785922b1e65ccd401885f873
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_solo.res
  hashes:
    binhash: 197c704cb87d7e357dcfb2853bfdb636
    md5: 7c1e64aee1290cad829bf508a8f65882
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4fc0bd883aa4528f7fd276f69d557e52
    md5: 4d208aabf51f495390c573a0fdafc2b8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 34ea7978f7cc4d9e624c85293c864a26
    md5: 1329425f82342ec1223f0adb13f92816
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_tracer.res
  hashes:
    binhash: 08fe0111a191d602115ba1843fe503b5
    md5: 8885dbe0a280c0ac639b4d881fa345f5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 596f15d40ea12524d10a12e01498233a
    md5: 183d33e3ca65189a14078474bfd09443
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 13e884f1ca9fdb50f5e53cad58383485
    md5: b2d23bfbe496bc1d79a823072a4939e9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6427ce646a0b746b96754ac3bac2c8a5
    md5: 041e7afbd4445f99a3cfad37426f3339
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart371/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bac1e540e2448f1c9cab6682894acd21
    md5: 77a257d7324e0182a092a05c29d84ac8
