format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/atmosphere/restart_dump.astart
  hashes:
    binhash: 66e0a5b7a0ab39d9d1ef2bccef7ebf77
    md5: 362bf984cc1ee661aa7cbfa68c6b15aa
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/atmosphere/um.res.yaml
  hashes:
    binhash: 8018eb3d34842ba721286569c134c7da
    md5: d65ac43c24e3c8cba3650ec621f35d97
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/coupler/a2i.nc
  hashes:
    binhash: 572425f74f22dd438b66df39ecd21537
    md5: 5d02cfc9cb94d9de7726cba7be77c23c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/coupler/i2a.nc
  hashes:
    binhash: bb1829c06b836550a1afde1ce3dd74cb
    md5: a507128a430130d2df3053534b5f5c92
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/coupler/o2i.nc
  hashes:
    binhash: be8a532c6a989137897273b6506214f6
    md5: 6cb1be592bff045df8b9f26bedb0a6e4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ice/cice_in.nml
  hashes:
    binhash: e7c6d25204cf4159cb5486c236b38e55
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ice/ice.restart_file
  hashes:
    binhash: bbfadf70a663375ed304c397cbd9da62
    md5: 9b527a061528352a43afed169582ada6
work/ice/RESTART/iced.1279-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ice/iced.1279-01-01-00000.nc
  hashes:
    binhash: 1f6f6a4b59dd5a320e9cb19cf1d57095
    md5: c90572fa26a787a92ec294bf66d929f6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ice/mice.nc
  hashes:
    binhash: 5e7b5b0d527f300d90f5e175f5560673
    md5: 429812f03d5584169a0714177739152c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_age.res.nc
  hashes:
    binhash: e655e8a00126fb6c64faaee708448514
    md5: 7a68989206145b0d022577638f6a30c3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 84c099decae7db7832cc0bf29141dd2f
    md5: 8ec9b0201bcdaf3fa3f1df6a1691c635
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 09a7aed9a39e50f8b1bec7e56d67df5a
    md5: 7df230638117e063615b1cf8ffa61828
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_density.res.nc
  hashes:
    binhash: ccb94d42270e004c9f4405fa77f032ba
    md5: 91b9b017a7a9f3fe1839de2ad8373564
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cb9012afaef9c4265698989b492dfa0f
    md5: 1f3350ee0f1f7a0a33ae91b6b8dc69a5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e1b6772fd6f924b6bc6f9a884813fbef
    md5: 63daa4b3007e640920ae8834b2f41024
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1de176f83d748bc2a405a7b53841d815
    md5: 5032f338edc9dea027ccd4e420edc50d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9843ff51a261ea9d1c7c83082eca6a50
    md5: bd0e207644cf4270e88663f356ead42f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 705d464939fdfd285680e7d6d2784860
    md5: c72acb37beea218f6ac9e62bf5507f2a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: db280bb683959a51fd9d006b039629ed
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_solo.res
  hashes:
    binhash: 8dbbd3579e92da2e98a9eb74c337389f
    md5: 11ce9d6905fcfba458316b09425da22a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fd58dad58d71bb71abf4352571476b07
    md5: f2d52ed2a32c19b9738111a164ddbd08
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c0b565fccd864238fe929b464f5a86db
    md5: d750318ac05f5edb284d73d379c5a0fc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_tracer.res
  hashes:
    binhash: ec9c9846d1a5e9bf95dbdcf0f99e9cce
    md5: e35aee83a35da2a9656a0c5ebde94e63
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6e80bc44465a251e8ef1dbaa8cdc95b0
    md5: 56960f60a28878a8169d50bd271e3f84
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 94313f9af036843f5297b5ea746847d8
    md5: 687b790c986491b53aebf918941e110b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9bf790386c24ef3425e6a9e10c7bb572
    md5: 4819ee6cc265f2e9dc9a739a9e6c15ed
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart395/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 76df01da5432db6768b0a4417aeaabd8
    md5: 6297107398599cafb636530fec1f1e1c
