format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/atmosphere/restart_dump.astart
  hashes:
    binhash: f106ae5d9807de4a17ba0dd89de95234
    md5: f50b6e79d28a475f23f22ad526d336d0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/atmosphere/um.res.yaml
  hashes:
    binhash: 4ab7c47cac81e6e4828aa37d3c664592
    md5: ad686c202c61e09c66d122f9230a0088
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/coupler/a2i.nc
  hashes:
    binhash: 1fd652ad3a70d949589c2e2636954f2b
    md5: 79996d2bdcff50a8c8ed8fda69f90e71
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/coupler/i2a.nc
  hashes:
    binhash: 793a768f46d791a2447f9339dda8ae92
    md5: 60dd3429329f44f07d617e14498e13e6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/coupler/o2i.nc
  hashes:
    binhash: fbd60e7021fce241be0e15559c896260
    md5: cf3f540aa2b88265976f0bc91db99395
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ice/cice_in.nml
  hashes:
    binhash: 1796581d239a755cb9154676968990ca
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ice/ice.restart_file
  hashes:
    binhash: d15bf747156d5f5bd70772fcd81e2af7
    md5: d5de32bc627fa706c2410dfe754819f0
work/ice/RESTART/iced.1230-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ice/iced.1230-01-01-00000.nc
  hashes:
    binhash: 22a70bee56f790a5a3bb8721b7f66ffc
    md5: 654993b9e02b0b6829e5fea3fd193333
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ice/mice.nc
  hashes:
    binhash: 26e0996520c7317073de5c46404ff3c5
    md5: 80c32daa8096255e3f2acca8c219e904
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_age.res.nc
  hashes:
    binhash: 358f79a4095a58b80a46bc365c6917dd
    md5: 52b28c8eee8aefe516da7be232ce9e79
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0df5860f4680669b47ad94f69bc164da
    md5: 281c8beba37cf43cbda5b5b1f16de95b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eacf6cc4685675bfd5b9e5c9c229dd86
    md5: cd68e90842d44c230a9d993654bd6e24
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_density.res.nc
  hashes:
    binhash: 0bcc562264a679038e451db3de948eb3
    md5: 7dee875c2900bd968dd4d86ad438497a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d64dd013444a341947cfece702811b79
    md5: 7bc27be279877b0bedbf01e5a13d217b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aa57d73fbdcdf2e2cf0ef5b57cc5f7a8
    md5: 108ce70b82c05bcf8b47ee43ea0cd20b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 848474ea6ba7f2c8f953d65f0cc4253a
    md5: 766326d6c0685679a9ac6f3b38ba9555
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dd7b1e5de0249a122d86c6f7719bc7dc
    md5: 2dad77c2625c6098b1609b68b12b6715
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 90921b38b0ae7cc0a153fe271e5c68b3
    md5: d22bcb7dafda248daa03fad880704b1e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 002c965103ed657abce129149c2e5da4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_solo.res
  hashes:
    binhash: ddd50b4a9a07369149aa19edff348d8e
    md5: f9440dde84fdad90ee53a8b199c134be
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a9cbe5175586cb445c3525b02309022c
    md5: 94f6f7095adb41b04529e273685a7c9b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e954612ef2c27be2e905e642b49e438d
    md5: f01174877a8a8031c24114a8cd6feff8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_tracer.res
  hashes:
    binhash: 1d0c34f1f7947869d3035e25307c6937
    md5: ba8005ae529226193ab183d3a00456cc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6731244a896988d9ba332ab949d3deb8
    md5: 3b59a73e766b0f00492a965200fabb9d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7f5035c5502ef0636bf41211fa823f35
    md5: 2d0cc28462b8154a72427d4507934556
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 31a4582743f334a63e50b9574c669875
    md5: 29feb90247ca432108f2a48ffb424c4c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart346/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a593e4d9c71d99a7063d543f17b6c110
    md5: 68e000e79bea7ef452618e8c46f1c772
