format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/atmosphere/restart_dump.astart
  hashes:
    binhash: be4edbce195f49f2776b04ba90f715bb
    md5: fdc28e8c83eaaa0c05d952f51b4da083
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/atmosphere/um.res.yaml
  hashes:
    binhash: 1c685eee7a7cb28142f25bdcbc338fad
    md5: 9384861e62cac4c5aab8cbed625c5679
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/coupler/a2i.nc
  hashes:
    binhash: 95b442f6d33ebbdee667b744925498c9
    md5: ddbdaecc758206c85b02d19a8003682f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/coupler/i2a.nc
  hashes:
    binhash: dfeb3c22ab1d12eb25bf596e3eb116de
    md5: 1cfe096db775ef1ca676441b1cab91a3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/coupler/o2i.nc
  hashes:
    binhash: 6bb82711242989269d5fb8754d048eb4
    md5: 052d55d50f5cb4c19f9770609e740b93
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ice/cice_in.nml
  hashes:
    binhash: 60517b70bb23b3822359585c91634877
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ice/ice.restart_file
  hashes:
    binhash: fa2415cfb81b4d17c5ab4986a50e49b2
    md5: 38aacc68d0b5d2669c806c4faee1c6b9
work/ice/RESTART/iced.1744-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ice/iced.1744-01-01-00000.nc
  hashes:
    binhash: c54f262082f05d26a3fd2e99d9c9c34d
    md5: 5e2e7df504b487a20a55bf33d5b27e70
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ice/mice.nc
  hashes:
    binhash: 9b7b77a5356933a8962766ecec3e159b
    md5: 814cb9a1846508ecef54bc916dbe89cf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_age.res.nc
  hashes:
    binhash: 35bdd74aff897466f6d5ca9aacf3d2df
    md5: ebe9d98c57e1ee3139d693ee00ba4ce3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1e4b17de98323a18908aa27011346177
    md5: edfced305b0efc6383cf63d90392be54
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f54eb6d294ec05ffcf139edf2c46ce89
    md5: cd57efb999538b86fad1b655b0722013
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_density.res.nc
  hashes:
    binhash: 50e5fe3ff0776616c488b7254b95a7a9
    md5: 0a21d439b0e2f60c08f7a438153bca49
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 87ec0d2cf9742d3eb6afe947ad0a0417
    md5: fc6ea5149f917c275795a2402327a635
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d1823c9c56a77127251ce200a44f4b71
    md5: fa995a01cf8c3f0af425ee84a3ee3110
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3486842baf83c0e84642829751407b94
    md5: ba1045206e1ad3ccdf521ee03690eed9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 47e6efde3727fe7be18aa1078df9c1b5
    md5: 168915d881af982ab94ab0446e27db6a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d68d2d400d0002370e2cf7c736f1b0d8
    md5: e58fe345a22265b14292bef7ca2df0b4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cc01333101d5df602a2fa996fa2b2cba
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_solo.res
  hashes:
    binhash: 61e8369e2044c5dc1d4fe4bc0bbfecae
    md5: 2c0ace953c555db0507a094f5af898c1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9c9d22382b50daa46133d2744ff1231a
    md5: a761f67f0f361232b49f60e9256148d3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_thickness.res.nc
  hashes:
    binhash: aeeb64d5f26becde619d091c22f38954
    md5: 98b202ece6792a6ffa3450e18f5d1a19
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_tracer.res
  hashes:
    binhash: 5393642ed02f91687ef14a059675971b
    md5: fd77eaa89923d2d194cebb808d40c17e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 193f553f150051388e6a45fc2a253167
    md5: 3ef6579169569f982154b3c6e9580bf4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 05bc7dc37f8ae876a055f04b729163e1
    md5: 07ede9342b0758c03b0a3b25b89d7c87
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 46904ee393870927b2f162299ae6eaf4
    md5: 489a1234ecfcdfb47a5b097af4bbee4d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart299/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ea53983ba5e7f209e7e38d03e292bd73
    md5: b59be6a3bd0cb8210386064bfe8b7dfb
