format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/atmosphere/restart_dump.astart
  hashes:
    binhash: c89c0394714371ac87ab79f22c6b2b1c
    md5: 6447a3111382f8a1e62fce09e4e5c457
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/atmosphere/um.res.yaml
  hashes:
    binhash: dcdf79cee0396d2610e977cb9afa9203
    md5: 4d7df1c8dce722a9499c7fc88980882e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/coupler/a2i.nc
  hashes:
    binhash: 080c3baf279ca060f3993db841581c01
    md5: 2407eb7a6c66dc0cf2851fed1d8c9d73
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/coupler/i2a.nc
  hashes:
    binhash: e0e71e8eae6d715a1618a9b6dc672e73
    md5: 79d924127acff85af0b61299934266ce
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/coupler/o2i.nc
  hashes:
    binhash: 949ea46dfde803e7961fd3f8c8fdc9c8
    md5: f269af09eefbd3b797b9e58da3b673d2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ice/cice_in.nml
  hashes:
    binhash: 53c9d28ce025902f4310fc0e4a301f9f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ice/ice.restart_file
  hashes:
    binhash: 80c348d50c0ba95198c7dd81313e23e2
    md5: fc8544ebb2a02886f2f7600ea6bc31cc
work/ice/RESTART/iced.1824-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ice/iced.1824-01-01-00000.nc
  hashes:
    binhash: 175e82d00b4160401b1ff1b469faf4d4
    md5: 72aaad4fe73624fd2a102d28ffe073ca
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ice/mice.nc
  hashes:
    binhash: c1af7ba0ffb872a5f4903836e89d2bc9
    md5: ba5bc9f54257f6cc48dd42414132ddfe
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_age.res.nc
  hashes:
    binhash: 54238ff761c7ff2a7a0a91e4be130529
    md5: ecffe52c44cd7bccf267e862fe15f4bb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: db54fdd784d8bd5f78ad16f1296e8c83
    md5: c0c32e192a0ba6490898b3d402dbb511
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6908a17268622aa3c2f55b150cd64211
    md5: 3d228ed50003e08917aac39dbe9450a7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_density.res.nc
  hashes:
    binhash: c7f56433e3f9c321d1122dd19e693744
    md5: 27fb706c09f993676157b890569028f2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6dd4a7bd9ffe5683b0412951ff4490bd
    md5: a29ba6d0fd17ac6941f5bf98dce0a445
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9f569e1f946abca6f16351528ca488ac
    md5: d804d4e204be7c6324d63d9f0f3691be
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 42550edb2bdc73b402372b303dffb8d5
    md5: 2cbf6463d0da4997e276146db18030bf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 50007013b8451544ac7dad9ce38ad5f8
    md5: 34383e969104f5acc0208a50ad57e03e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ac8ef4585cdba3668ff26d4bb2f4afb0
    md5: 698c934a85f660f942f59a4b41a49ee2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 12521677d149abec423d9c0b973b774e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_solo.res
  hashes:
    binhash: fdf28d53e2ae470c2d710785b6a47ce4
    md5: 81a6d0c7e2169d5f180a153e8ab446cb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: aba887f5e51a116543facfe03a0800a9
    md5: bf1afc2b45e55a74af5c361a4015e957
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f2c07c20fe7ee22aeeba4667b36fe2fc
    md5: 593bee192dbb56b373b44acf7876963a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_tracer.res
  hashes:
    binhash: 4140f50b71fa744d2063a8d6b4ab4fc9
    md5: 59c51c75b88cc66f5a61196260feacf6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f0bf1b117cb27a6f92e351d6e071f00b
    md5: 209549d9c5cb2679e58314d117c4abbf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ae619f4385d1346b16ebcba4273443bd
    md5: fc71587033360688405d063be79790e9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f7c89e80264731c3d91dc0ec0d81cc85
    md5: c15b8a8b043fcbdc41694eac9e956433
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart379/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fc98c000cf6791295517120e97a8a065
    md5: ca4e5e7adb19a3b04ba5fcbe217cf9fd
