format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/atmosphere/restart_dump.astart
  hashes:
    binhash: a53b229004bb93bbffe2f87039d0712c
    md5: 97895dc8aad5a3b434bed8105dd5b403
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/atmosphere/um.res.yaml
  hashes:
    binhash: 21b40d71ca89b9ce6e6c5a8b51756109
    md5: be332faa37931a6e8778da883e50a145
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/coupler/a2i.nc
  hashes:
    binhash: 00bbb753c987c98ce66a7ac571ee6ca7
    md5: 137baee6138a56c86df297689945946d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/coupler/i2a.nc
  hashes:
    binhash: 307c12b17cea8eb391d6ee1cba988b91
    md5: c1d3c6b64a86aa9a43a39b83a56e8ec8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/coupler/o2i.nc
  hashes:
    binhash: b2911b5442780c634a635bee39fb7b32
    md5: 152417dfdcd6577d1c446b03d525ce62
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ice/cice_in.nml
  hashes:
    binhash: 321069761c59c3ee6734853072ffd65c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ice/ice.restart_file
  hashes:
    binhash: 0aec959e99e22cf8a65bc35fcd8fbdec
    md5: ffe021232f737780af3782e35f3fac9d
work/ice/RESTART/iced.1851-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ice/iced.1851-01-01-00000.nc
  hashes:
    binhash: 1e8446da811e03e388be76bb79fdb645
    md5: 23602e478dafaa05ae2a4cf1e23ddada
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ice/mice.nc
  hashes:
    binhash: 38963c7317ce0a7b8abd4aa80db6ddb7
    md5: 338445082254e814ae9eb5b8d7f911b7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_age.res.nc
  hashes:
    binhash: 97fcefa4fcfdcf1af8601d99a13d4229
    md5: d2808d80d8fa516c82776f1ec12cc23f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 88f0da3f0abaf5122547b15df991607a
    md5: ab9cdb13a5f211f4f2cc79af06a7ad76
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7270594bdaef9c8b3e5a3bb0766eeb4f
    md5: 052c65c05185ec9c01da77f2827082ae
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_density.res.nc
  hashes:
    binhash: adce06d590df6e304cc322e3857201a8
    md5: b9f45216a2842dae8c09c53352e177d7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fb1ec4599852dd1d095b68a903e1f85a
    md5: 6c173ad29d66c8ce4daeb1570d8611c3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2a829aa3335b0204bd3c1a78edd81f69
    md5: 959d76ab598b7e9190ce41cda03338ae
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bfd00d703a5b888ec83421916e4923d8
    md5: ab0645b49b20c0d9f7f004f61f8f543f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b002f6ce58f58094af1a1ffc6eef58db
    md5: ea8dbca9e5d840b6d1f209bbc8d2e120
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6ad3f9e3f7a683750a7e0107cd750dfa
    md5: 1b3858972d3db3c02ca91266a280608b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2d60599df227e24ddee6a2f08f5c8687
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_solo.res
  hashes:
    binhash: 040889e7ab900caff39f5e455f5b8382
    md5: 8c42895e91de726bcfe025989671c3ee
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bd4e1e7ba89033d015016741c4744eac
    md5: 3115c5f5b2d1c0ee6225c5b2f1af454f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 55232d52f1f3b2e9598d3fcdcca3b969
    md5: 7e868d78488045ab046e976a2e916bf3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_tracer.res
  hashes:
    binhash: 0a541dbaeb553c518469bb5af816a850
    md5: 0db065319a2b91204d4e05038a947793
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ec475340c7b31be846c723cc0f79fbae
    md5: 1a0d995a80a5022ecd5c0db07579b840
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 84113011a4882554980d3136b8787290
    md5: d35aa1f87a086dc833cec56b4cb55f5e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1b489b871b2662c42a39fb383f190855
    md5: 375a75f328a6e34cce636705b904f0da
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart406/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b296fbb4a8949f8f1ed8532369528d48
    md5: 68ebba6055fd4edf10cb2cbacad3505a
