format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/atmosphere/restart_dump.astart
  hashes:
    binhash: 87928782b5195283df5c205812231c11
    md5: 4ee6170b3f06a69626a303101536440b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/atmosphere/um.res.yaml
  hashes:
    binhash: fdb39328a3e3a1bdfe697b205f5746d8
    md5: e1d84888679981eddc0a14eb29b875cb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/coupler/a2i.nc
  hashes:
    binhash: daa1e8321b00c11cb864d4f69c2486a6
    md5: 00581e4acf99d4589992b05ee74d7523
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/coupler/i2a.nc
  hashes:
    binhash: 40498670fde01ef5b79d2b79bd86f808
    md5: 898b2ae281a651ab0f1ee61bdc15d852
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/coupler/o2i.nc
  hashes:
    binhash: ba36c1404e74e3b7a592eeb4cd05b9c8
    md5: 988dfcbde45972cc5a5174e904e127b8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ice/cice_in.nml
  hashes:
    binhash: 47e10a8b979168eeae2f908c4e244356
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ice/ice.restart_file
  hashes:
    binhash: 83b51736cdd74b7a462d22799d788114
    md5: 0631539ef5644d8ca9a81eb83e55d576
work/ice/RESTART/iced.1730-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ice/iced.1730-01-01-00000.nc
  hashes:
    binhash: 9dd8b05869a33a9e06d38deb6bdfd57c
    md5: e24f5684a6fa3155a84d38a3c1fb2d83
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ice/mice.nc
  hashes:
    binhash: a133ab3856fc809f0b2ec7383f1025b0
    md5: e8d48a02d25fad1047ad645cadbb19f1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_age.res.nc
  hashes:
    binhash: 4fb3276c0a6ee8906d14cc1da098ddeb
    md5: 878aa07c3a5632407e3e851ada32376a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d6e5abfa08aa06219355c4bae175e788
    md5: 5bb1c4eb9b69146f1127980b334005a0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fd194f556f75a9bd5a897cd014a07e5c
    md5: 383f3e8b83c0d1ea1a77192d4c2f7c43
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_density.res.nc
  hashes:
    binhash: 7024a268508cc90ec8023e6fa05e663b
    md5: 4f83bde3bc39607ad13a25774868052f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3ea254b53f243c73d3d82d2c19dd5852
    md5: d0c3f052137309efe0a61f8e6e09ee2f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e83761eadda968f3717adfd1733d9d03
    md5: 20b0815521525df12410d0a8f55eaa43
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9b7ce3311390afc7d7fce65ae065b3c1
    md5: 802d1168cfcf203193ff0191f1cda5ba
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4bde8c670b11e471aecde72b6e1829e5
    md5: 6cee3cb80619f7886e8e3b7d0280bbbb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_sbc.res.nc
  hashes:
    binhash: abc6c6ff7b1a13993f58315b5a7468ab
    md5: 0b476f02de325e9dc910ee4537fab0f1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 65fc01382121fcb4dbf3d1d92026230f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_solo.res
  hashes:
    binhash: 3e3dccc1c9f339e13d3776bfff182452
    md5: 415f26acc0b81d5114364f06ec275542
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 629552e23b1400bd0332ee5a8d890152
    md5: 62aaded89aca605e027c91a9b5c050d3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d8014c010c3b08e6de0b93d8c0c3bdf7
    md5: db6da256f2ad089516d4f0e2841ab172
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_tracer.res
  hashes:
    binhash: 1aae1d01febaece1c47122e2cad96df4
    md5: d3e46d2ba3986eed0aaaeb1eccd34b7d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 152ec5c161ebdbd304c8b2229c23de51
    md5: 70c4945376de469e40dad6f4e93950af
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 487b4dce1b2cdbcfe5df8dad5e2546b4
    md5: b2009cf85fa4f57cc34322986c133154
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 24a12272dbf76efb10a7eb23ec0333c9
    md5: 55225d61cbeabcb1525b3b95dc5e9c47
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart285/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 32158a5335cbdb8909cb4828169e801c
    md5: 67475c9423e1d546a6df69f39dca3271
