format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/atmosphere/restart_dump.astart
  hashes:
    binhash: d2f7467af40691c14f0e597f14875050
    md5: 81163d653e1b22257f7198d88eaf9967
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/atmosphere/um.res.yaml
  hashes:
    binhash: e0bb968e1b5b4fc8580115b5c6340e66
    md5: eb758a51b640d2b00e99ebf8129e35d1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/coupler/a2i.nc
  hashes:
    binhash: 7c6f55e012b083a7aad13a84e16d75af
    md5: 1ea454db3cfda849ce3f36a81b6d21dd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/coupler/i2a.nc
  hashes:
    binhash: 5b6e100c127be44415c3e5142c8c617b
    md5: a9088724e5a3cc6e1911f48ce17f68dd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/coupler/o2i.nc
  hashes:
    binhash: 73bba19009270755fa8548ca7293302c
    md5: 07594a9a21efb2a1af69ffa6513e8baa
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ice/cice_in.nml
  hashes:
    binhash: 83044365e1ec7ac6b1564892820e759d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ice/ice.restart_file
  hashes:
    binhash: d049801be5cc011a5bf2320ef58d2b1d
    md5: 0c401e25b9951617215562a9241aeb53
work/ice/RESTART/iced.0847-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ice/iced.0847-01-01-00000.nc
  hashes:
    binhash: 3039629a97bae81c4753d7d35447f816
    md5: 2a58f60be4bb54005e8b866eea6a9498
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ice/mice.nc
  hashes:
    binhash: 658a27c31ec93cf73977a155af61515d
    md5: 2b4f60740947bd664eef046fb598c785
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_age.res.nc
  hashes:
    binhash: 48496bdcaefc3f787ab69f967a8fdc1b
    md5: 1744090967f05ab7d255068913d0c5e7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c174ce4615c48b7ad113e8624c96f48c
    md5: ca566333815d087593bf91aaf8e65524
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f859e4536be37921977c73cf1fa15ab5
    md5: 1c6272fe0284b8a45f96281db115023d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_density.res.nc
  hashes:
    binhash: aa6d14dadc53e346f6bdc884c21e8a9b
    md5: e97476c7b82287a96915fad433a74520
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d1749a557b0726804c184f696c30e54c
    md5: 5839600732c176366fcfe4db0cfb43f5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2992738790c9fda3bc316e2862067d7c
    md5: 434e175bc6822da5e7147de7a94fa01e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b68925a0a3e9f817dfe9c2a60830eac3
    md5: 6200fdbda9cf8fc5fe1305a46e6ed9cf
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cbfd466792053cd8a5522092074839a1
    md5: 1e7d7fcb071bd3aa52e4f37908d9fbf9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4092b752c0226599b8e78fda6afba393
    md5: 1458586787452d0cceb035b4436e5c74
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5243d5ed882a2b12e98de757b3d87553
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_solo.res
  hashes:
    binhash: 31effc64c4daed57d5ac78582516d197
    md5: c05a09baff8ece6d7c5e0a2aea961c72
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d17f1ea90edf85cc62c037df1a2259bb
    md5: f441545fb33b54f7fdfec333077b0d0e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c47c990af8e21020cb40869da7a14b2b
    md5: 83608f713de021c37345c9aa192b7533
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_tracer.res
  hashes:
    binhash: 782ea5921cb0d3cfd8fcb0ce5aec81bc
    md5: 5dc5dfd6f948637bdf5778d2b09d5f52
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8aec81da2ee8e02a86dc98ef9093874a
    md5: 0ace351197e9429a49c8ea0cdb69a45b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 740535db7b3d3cbdefb34102614e9ef4
    md5: ad98da3a352f7edf7693511651826b17
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c95a7514caf7ed1dda6f334f4d6b102b
    md5: 8e51a674317637b72502361ebd4f143f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart293/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: cdf1725e5d673c3c921f2ee379c245b8
    md5: 933d39ee36b3841d16e7b1e5419c09ac
