format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/atmosphere/restart_dump.astart
  hashes:
    binhash: 351ceff0640bda8fd3ed8372e03a4764
    md5: 9ef7647a079c3d3d80bde5c36ed07628
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/atmosphere/um.res.yaml
  hashes:
    binhash: 9102078140be92f90ab6d3bb6e5afaad
    md5: 9807f33e380134363763343b190e75b1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/coupler/a2i.nc
  hashes:
    binhash: 6d2d563be9583f1c0e384636e4d1c8db
    md5: 8b920f1b0de5b23e11fd1848a4e972f4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/coupler/i2a.nc
  hashes:
    binhash: 32a81fd27768b7c2a602056c5731e70d
    md5: b67bbabe6a9ce3241744581c6c61d9c8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/coupler/o2i.nc
  hashes:
    binhash: 2008d209a8eba399f9f8d71d81b1ac92
    md5: 26adbd730d3d5f52fb1b85e51f3cd9ee
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ice/cice_in.nml
  hashes:
    binhash: 7bbc01084ee67f8ae32df426ed39ad7d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ice/ice.restart_file
  hashes:
    binhash: 3709186a7500537fcc4c6ac412625841
    md5: fca164aa043d63bf9f899c55cf02da5f
work/ice/RESTART/iced.0866-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ice/iced.0866-01-01-00000.nc
  hashes:
    binhash: b8804f7764ce2a59095daca51cbb1543
    md5: 8e102b3cd7a798dd071fe844a476defb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ice/mice.nc
  hashes:
    binhash: 568925a2af399d809d81b3f3041cb434
    md5: 348119d9caa5087200df3158880e2270
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_age.res.nc
  hashes:
    binhash: c80a1ace80520d2e59fc08972c1d1818
    md5: 9c2e5a06a8f9174670e9ad8421d0604a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 13bcdc5b2fa15dd59edf307f01b52d17
    md5: 09f1413805d41b9d94203ac609df904d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ecbd25136dd3be696d9f93995148256e
    md5: 5a60f1a1e89d211f9c30408c10c19838
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_density.res.nc
  hashes:
    binhash: 7272f11645a223c2512898d32e530b92
    md5: 645b31e79177dc1bf398db68f4305c83
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 378b7272c25ef4f11196cbafb888f0ec
    md5: 5fe195fe6716a5a6effe7cc8e0412e7b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f8abbc0dfa84268c01fa301faaa37da6
    md5: 7d47018f6d2f3be7a277a4a23b473f45
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6040f1cdf3ee3c856a7ea571e76ae5df
    md5: 101edc1a1a83b3671450b374a5fec25f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9618b735a351b8f8292508883909fdfb
    md5: 5aa9e3769ef9b7de148c2bd97557f90f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7890e58b3a9e64f344929ce81f0d465f
    md5: 80dc3f90f83a8fd9b671fae0fc5855f2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ec3edeab80ee2034cabf54230f97ab95
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_solo.res
  hashes:
    binhash: feecacab6098cc9e36700c8f9703b879
    md5: 0c85738d7ff2731401c02cf9c2cf6d30
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 322159f0d76be658e817e4fe41eed442
    md5: 1a50c552db3082a72abc1b0d1459f546
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 13075494724ae6ff57b2c21e86f9cf64
    md5: a41f0ca54d8527913e0e9a83e7a6006b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_tracer.res
  hashes:
    binhash: 5741b40cdb60df8368554389748e5b73
    md5: b07d9ec45131b95288918dccc12e1555
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c4c906e6a88d036a925cc3a01d96de7f
    md5: bfd72836cab5119d69cd43dda711ca8c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7aed50124ac360ac9831774cb47e0645
    md5: 7de6b0ad03dce6007429e4807627bc6e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 537fd297508787810b8f69fb24ed92ed
    md5: 8bde6369ec8af04a10828e0b94556b09
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart312/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b0e2bb8ec359ec6e3a3b34a295a4b28b
    md5: 21fb8918520d658f162b0534f432f4bb
