format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/atmosphere/restart_dump.astart
  hashes:
    binhash: 77944dcef80ea1cc8925b5ac6c961200
    md5: 657ac664ceb880c6d75557c9bc03c08c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/atmosphere/um.res.yaml
  hashes:
    binhash: 95f2004521dc9cc056de75f7a729fe45
    md5: c8334ae2b23ff0fec07a8795a93eb246
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/coupler/a2i.nc
  hashes:
    binhash: 519fc6b6a820053808d29b5f8fc38234
    md5: 0166ea43adc1a5a258f67a408eebf1a4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/coupler/i2a.nc
  hashes:
    binhash: 8d50662c05677a881eee9b4d9e37e125
    md5: d894047b68d0d4536548a979224179ae
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/coupler/o2i.nc
  hashes:
    binhash: 9eb70b2ef1e58acafbcf5a55bb8b0eca
    md5: b19e94f79355de6c09383fed13766e5c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ice/cice_in.nml
  hashes:
    binhash: 4f9ee7c034b55ef59fbcae2fcc70787b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ice/ice.restart_file
  hashes:
    binhash: a19c12db79ddd2d68e9678f593b7d6c1
    md5: fec56fe9dd949b3818499ebcf6195c07
work/ice/RESTART/iced.0837-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ice/iced.0837-01-01-00000.nc
  hashes:
    binhash: ba5e91cbbda8ac50be37a0e315671038
    md5: 82812ac51cdf45e8cf17af94affcad34
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ice/mice.nc
  hashes:
    binhash: f465efd23f51e8cd16d0f93ea76ca3b7
    md5: 2750f863fdc138c04fbeaa8bcce8e513
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_age.res.nc
  hashes:
    binhash: 8c4c09faaf47077a8d25f17d5f55452d
    md5: fb9826dcb63b0e0e780e029be4c34ba4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7fc3ae5d5440ae19bc98e698d6953eba
    md5: 34e758ca88cb8aaa710655cdcf2039f4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 22de84e78d466e3abb0bdfbe9ece062c
    md5: 79d8d8e60eb754394f9f58a6812bd8c4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_density.res.nc
  hashes:
    binhash: f56c89d1da378834d0ec3c2810934a2b
    md5: a69d2aa056b09c1eb60ed17c09f34239
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 121702aebcacdb8b76769cadf26a9757
    md5: 3525084e42b62fd0416e5385173d3a3e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7a7ae4044d307c7a6dcec98d4ba768c7
    md5: c3ec0dcb093a4fa894a3379ed026be96
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 97a6ee7a71910a33888aecdaa2065c44
    md5: 3dbd177f23263df2c29197e8d7399204
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0612ff7708543e5af58427cbdf8d8215
    md5: c0c5e1c4aa5faa3eb201cb370edf3c97
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 429cedd0bffd37cc4c339997b690e610
    md5: 1af6add99b2e22d7390692c574b45729
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a42ace067fa92bb31c0185b4d816fdeb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_solo.res
  hashes:
    binhash: d63b2c7ed6c2929ee9196eb7f8c4cf62
    md5: 695ebc6278eeabf86286c80e5cce61d3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2490eee6ca5618645fa5338a47fdc001
    md5: 817fc48496cd86b6247c124e7d4b8ef9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3fb5fe1ba2f688bf3d5ad747bb458917
    md5: 6f205db6a4b9780c0eade400b6b43c91
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_tracer.res
  hashes:
    binhash: a0d328793b483269f61596c2f910d7a5
    md5: 7a343c91ea5ed8a477584e0d7533645c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c0c71fda384578dbbdcd36a916e98456
    md5: 8d0614bcdac798cffa30dbd9c734d390
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 42dabdbffdb6efce95f1633845716e23
    md5: 06f78f8452cf3722d1fbad484ad349d1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 551e94c696b6d7f5534e5b554649a984
    md5: a01609fcf7adf0b8458cd1f6a738effd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart283/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 970b307252756f75dbf27f3555ad1843
    md5: e33debe57ddf2d7a3da00077d7f6c47a
