format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/atmosphere/restart_dump.astart
  hashes:
    binhash: 9760293638758ec07984bfef163ee01f
    md5: 485ebd945209c7473590ecbc32155f99
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/atmosphere/um.res.yaml
  hashes:
    binhash: 8f5981097cf716bd61689bd3892c63f0
    md5: c681d6caab57ead1ffa3f5984afda0df
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/coupler/a2i.nc
  hashes:
    binhash: da1bcbd3815fa9af495b64ba29f75b8c
    md5: a138414b67fe0e351c3fc7cac37c84a3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/coupler/i2a.nc
  hashes:
    binhash: aa3f0d479ace07a600d51e9fcb0c5d1c
    md5: a963d6f3eeba62f6ddb37b0ae6bf3c9c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/coupler/o2i.nc
  hashes:
    binhash: 0e80ba9c87e6d5264f1a38e758c37f80
    md5: 872c405154d2f9742e8f2f3ed3cf04a6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ice/cice_in.nml
  hashes:
    binhash: f0d94ead571a7e18c69545e49f3c7950
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ice/ice.restart_file
  hashes:
    binhash: 0322ed5d74d03406ba42b2811910bcdc
    md5: 3a113c15d0745389b250af1a016096de
work/ice/RESTART/iced.0960-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ice/iced.0960-01-01-00000.nc
  hashes:
    binhash: 87a262f22bb534fe37d78ae4391a4e97
    md5: 0c8650a7590afcc6311e9afa7f3a35c1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ice/mice.nc
  hashes:
    binhash: a2aacfa75696fe54d4c33c56c6ddbabe
    md5: 998a2aa180f3c40dba5da4e31b632c54
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_age.res.nc
  hashes:
    binhash: 7936fe8ebb4925306622eb7152c198d8
    md5: fc3501184c444b22eb0bb1394bbea8d6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 841480d85d8a4a2c267742c81800a394
    md5: 41a514f190cd3b1ea258e4e498e3f603
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e3b9a609f6280d921d4dcea77483ec1b
    md5: bcfb4e7bc6bb947e50b692f2f3b34ba2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_density.res.nc
  hashes:
    binhash: 6e4190b8c5d73bf50fb0781bdcaac602
    md5: 749ebbfb5b6ef36079436f705ca82c7d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fbebd04c377202073bb9bd34d02b67e0
    md5: 674e50f30b0be29b0c68b639e4bae228
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: da231f38585f5b94eeeaf0e056cc7a17
    md5: 893620ae3482cb1aaaef8c706614992d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f4a9f7688f9a6e3b0b79463bd4b34a4c
    md5: f71734288a9b541a6f7f4acdc315befe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 724e8cd60d0629bda8c803474b629815
    md5: de1f64bec4d7a277002822316fd8c6e8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b9340aba81eb1e09575b556d39a64856
    md5: ff615378060e514c8690a9a83c91f47c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b3c3a6a979d1ea15f894f08afc488235
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_solo.res
  hashes:
    binhash: e3fc9c725ffa16e8c913e9e76e743421
    md5: 6f5a797e9fd3fb0e1ee5eb63d6814000
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7d93802cc92c82a55d84e9ab6f52ea96
    md5: ac55d047aff9282f87977b738327f795
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2ccd7bde12d67d5f81b2d9726e98f4fa
    md5: ac2144a92f96a7d680b68368dd8d20bb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_tracer.res
  hashes:
    binhash: 016c93f891eb9c49cf9100fcc6758302
    md5: fc2be3c6fc3fec48f17295a17f009b8a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e6891d29b771a8a367f68d0d7fcbe149
    md5: ef60beafb9464f5f24dde3abda34a775
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 40fa95d3f69aa4087f188f9470a8795b
    md5: 5fc42879191dc5491c6dbed4c2d206b5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 15e070e8070adcf204ab495b879b6c7d
    md5: 6c00841bf54d3582c39ff363951b6b98
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart406/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2d6a0e52be1cd4b58b1a1edcbfb947f2
    md5: 08d04da91c4a5002507a39057ccaf940
