format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/atmosphere/restart_dump.astart
  hashes:
    binhash: 824c6eb509c0f608dfd5365820b51724
    md5: 538473321969180af1f9d3f23bc5c907
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/atmosphere/um.res.yaml
  hashes:
    binhash: 5df1d190b4521e7042b0ee5ba19611d9
    md5: eb75ab66f403385e2c21fc8446ea2770
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/coupler/a2i.nc
  hashes:
    binhash: ac09321e65c575f3963a777738df5d2d
    md5: b6772229033a1f4f7d93108248ec2714
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/coupler/i2a.nc
  hashes:
    binhash: fc96e4d0f41e0bf1bb03475181dcf2d3
    md5: ea6b114dceb382cbd233f8cb33a369f0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/coupler/o2i.nc
  hashes:
    binhash: efe5ffc7509240497d74bb817a05977c
    md5: 90a16fd39dbc3b86c22d160bcb77a594
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ice/cice_in.nml
  hashes:
    binhash: e3f65852ebe28b6a510a2437308e18fd
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ice/ice.restart_file
  hashes:
    binhash: 590315fa50e8951e68994bf407db76cb
    md5: 72dcdf01ea3eb4a92eceb490bc358d0b
work/ice/RESTART/iced.1226-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ice/iced.1226-01-01-00000.nc
  hashes:
    binhash: cbc5f99c00587b55bf5a4e3b137abf5c
    md5: 4f2d3c211e6b4cc8ce04b3437d26e9ea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ice/mice.nc
  hashes:
    binhash: 57fb63c8a12a812b08276102e26f8530
    md5: e4c207affbd49871414290f92b423d0c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_age.res.nc
  hashes:
    binhash: 4635bbe89ad7394fab5596531b209fbb
    md5: 5647b4a7b6c8342631212f30f5d74707
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 139ad7a70d5d34563f6ff0629d505f2a
    md5: 1da3d7ee4efe3de52383c1d1e14816f3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1030e73601a2b0b9ffc722b0b8b91d1c
    md5: 2bd0fe353e2fff063bda5e312d0b27df
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_density.res.nc
  hashes:
    binhash: 5375ca2630781ee1273792b394f24261
    md5: 280bbdaba979abbb5a713512fea3a687
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f6b2cc85ab4d84526ff77c9a186b51d0
    md5: 4ba73cd2d40a76a5d668470e9858b56f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b7285a0d0de0f50bce90304d23fd23bd
    md5: e5a74d7ead39d80bccc0a6d9d23eb89a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1e7b28d1b83509341cfa0468f5f39187
    md5: d23b5cb59b06ba7662ea3d6d6a8f9f4e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 861c2b192ad7fca1e5cc1b0046d88e8f
    md5: cc92be467926bd2176b3489a66753cdf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b2d4c7cd8aa5a7f718968349f490b603
    md5: 362e9b837ab9c393641d64c591424161
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 351b258f8dc6115f2d6ca42af42dad97
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_solo.res
  hashes:
    binhash: d03bd5f9e440bbc7fd58646c6293792b
    md5: 4e6192ffb2e7dc849e38e7c6f42b2256
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cdc69808b77d0996241fa8332ca374d2
    md5: 495ec154b0eb26ca94579728b6c6c054
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2f14de025d6ad31909ed5cd3c1503d37
    md5: 912639f5c5a7f5b9c8e642904f1dbb70
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_tracer.res
  hashes:
    binhash: 753a3b79ddc9c96935bad801171cdebe
    md5: a3e03996e1aeab23a587b4b888d538c1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d3bcdd4048586676c4d4096c86a25594
    md5: 03b516fdc953b2db79f979cd3e92ce4a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 577727e8e9703d257587731ea620d774
    md5: 0fe47c2415e366a3c37e3e15165e0759
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 13b11ea37f3a6726232b18ae15911ae0
    md5: 6d96a01b70b11f378225d3bd0b250326
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart342/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6b6ce7354700626ce07550157624b29e
    md5: ded244ef05f0c107852ba6a11082cd5e
