format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/atmosphere/restart_dump.astart
  hashes:
    binhash: 573a436a138778b3737d55f83154a97f
    md5: 467ddd1cff40bb1b250733b005faefbb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/atmosphere/um.res.yaml
  hashes:
    binhash: 573b5f02eb8e1b30c705c2632a1681fd
    md5: 4cd4119983562b58a61e7ed7e1ecf104
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/coupler/a2i.nc
  hashes:
    binhash: 99c2eebd5de84e04c8ae4d881bc1e123
    md5: 33f16ceae50068d0f5348e99433ba8ca
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/coupler/i2a.nc
  hashes:
    binhash: 4ff6c932a2664092a8efe8048b32ccb5
    md5: 9d2196bddd4b8718f19b2d494360b669
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/coupler/o2i.nc
  hashes:
    binhash: 6dfa0661e9f4b0fb21b7dfc0f3011a26
    md5: 1016d9749e360b94884d5c6ea489b415
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ice/cice_in.nml
  hashes:
    binhash: 882d0ba3965ba9996fef7e0829dfe341
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ice/ice.restart_file
  hashes:
    binhash: 3d897063a4418ff44e1aa0f39624d365
    md5: af0511c57e23518c97be293f58e348da
work/ice/RESTART/iced.0931-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ice/iced.0931-01-01-00000.nc
  hashes:
    binhash: 9a71e24f6a9e2cbe6f41c99e243a8b9e
    md5: 19ac57bd9011a29dbd770288bd3f9eb5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ice/mice.nc
  hashes:
    binhash: df2637e09a16a25edd0e5eb073c7b5ea
    md5: aebd8d97d6a78dd31c6ff3858edcb462
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_age.res.nc
  hashes:
    binhash: bb9dad2d73f63ca4c838b7128a4bfb03
    md5: 2f166f7780e7db14edfd7be52ec52674
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d7f2d36f31e36ad7f2d84bbefb24f399
    md5: 3ec19dfd6bdaf688f5541580f636289c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e3f1c09b82d77f4ef03f0b3a42acd800
    md5: 4885a54edc92606f3ef7047d138f9795
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_density.res.nc
  hashes:
    binhash: ec93755a5033fcd2f12ab5e54220be0e
    md5: 820b56c841b08e0bb9876ad1f1c1fa58
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8aa3d546b8650e8e330effd06df0e1ff
    md5: 0336ca690792316db794b53074b1d75f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f195a1abecd7e4462e326bc3873420d9
    md5: cf7ce75dc0b9ebb10715141e6d01dc3e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 573e082b748cba7d82ab1ffe0cafc798
    md5: 9f36b0aa8a93eb1af6a836f6523ed29a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8e9ed8e55474b9a0125223004d34a342
    md5: aa14f7d9de540dd148a0904c1eafeebd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6e2b59cdaefff245e855a1872ed579f0
    md5: e36b39228bbc649417be400458091d1a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: de3cbf2233f232ddf5d59f7e43a4f802
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_solo.res
  hashes:
    binhash: cb444d1ac89116972e9e88ebc148f8a8
    md5: 460c065ceff2d9a8120d926e7b7df9e5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 951e091cd4d820ced5f8cb1d308197f3
    md5: dbd3560eb8e23c5367a812c323fc3bef
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3c8a82c353776d1bf2d0c4fb297a2a9d
    md5: ab651e3465b0068c5cee5ec5d87b9c1d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_tracer.res
  hashes:
    binhash: 646847824a512f27f5e3bf10e97471bc
    md5: f8464021605cdd65713fc3a20945c3d8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e19089c6dc0ed31ac7ce205e8029e884
    md5: 6392a5ebecf020e12f0e784abfbaf09c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6e5c0e0e2cd737415c3180114d2cdb6d
    md5: 501b8c6aca11762d8aaf33012a46dc74
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f8481847aff35eb507fcfa0e39ce8ffe
    md5: e4a8ad5123606e053b54d2379c09eb29
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart377/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2b250ec61e74c7b0317e84c3cf04205b
    md5: 2786fda654b3d51963d81aac14376bb8
