format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/atmosphere/restart_dump.astart
  hashes:
    binhash: 93924782585bb1a18aaa5562aeff6846
    md5: 8a39029403e7bed9441c698d399985df
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/atmosphere/um.res.yaml
  hashes:
    binhash: 5965ac607d98f59c38f2da9da80528dd
    md5: 96c698655b025e5cc2528c5c558e035a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/coupler/a2i.nc
  hashes:
    binhash: 980ef020f2e32c26de4c060ca7cc0989
    md5: b680ae8b6b10ce0747e295fc45b1befb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/coupler/i2a.nc
  hashes:
    binhash: 0936b8f019bfc7e4aeb601610df755ad
    md5: 5e9881ceb0f3a59e45ebe50ac1b0f30e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/coupler/o2i.nc
  hashes:
    binhash: 6a4cf78087103e50fd4723975be5dad0
    md5: 344fca2308495d52a3ff15196c53dbbe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ice/cice_in.nml
  hashes:
    binhash: 3cea5b4200ef5f0f60df77f6c11d5f59
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ice/ice.restart_file
  hashes:
    binhash: 7bcca2d338978a2b1147d61c48190267
    md5: 0b507ac66a2195a2bfee2abe1bcef0a9
work/ice/RESTART/iced.1233-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ice/iced.1233-01-01-00000.nc
  hashes:
    binhash: 71f86601b76f54d26847a428b9f172ef
    md5: 6160f370998ad4b1bac9479f006953e1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ice/mice.nc
  hashes:
    binhash: bd965e3e68e0d0eb73485225011a5274
    md5: 04a5d1acc3fe0da33153d6614e372734
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_age.res.nc
  hashes:
    binhash: cb2e1a11e9a483f1e7fc28a70ea7afcd
    md5: b6cfe400de00a769244f55bee064d0cf
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5cdd94f00c0d56a919b271ea0f9a2da2
    md5: 7ff818b493ceb4c09a8c124d30d3f5be
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 421d9dd940f87169881d7b9c5f8ed864
    md5: 1d81149c4f63baf7f39fb46086747700
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_density.res.nc
  hashes:
    binhash: 285e0723c87b3f88e292ff755e53b9f7
    md5: 474349621e3bbe0780202495baf37f65
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a11576d9669044559abf51eda2c26657
    md5: c5068e78529fafe9bd612554b24fb7e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0f12f981f9827bc4f3d5a7290349e9ff
    md5: f43717ff8196b9905b7ff1e85b2f0425
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 736c5de7d0df425c040422dd20a85513
    md5: ba9776031f515a85641afeeeaaea32d4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ae6ce315e9314a463c0369803e5df77c
    md5: 1cab8a68484929d5f21e380025fbf61a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2ff25abf425f506cbedc18476d89d83a
    md5: ec71cbea47da7a27cbdcd24b5732d39a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f5c69332ad578af16df0479404fe333b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_solo.res
  hashes:
    binhash: 93f4b718bfa6bb91216cc49255f75048
    md5: 6fbcea9f62d8302e32a3845389ef91fb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3b3e10ec7af88e08c0a5e39a1d8dc8ca
    md5: 2548d0ff9cbb3df5e7162e170a0d15f2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c64e5c6cdf7bfec040cfde460758aa2b
    md5: 8c42911d5d85873db00bf37171a23dfd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_tracer.res
  hashes:
    binhash: 9d6f254bf169599f2dcf79c2e62ba67d
    md5: b825defc6ebc1bcf73bb5eb03a634d1f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8346a86b81e4eb74741277143ed3074d
    md5: 9a647bb6034a1aa99db44a81069758a8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3dd445cd55310e2c6b544a7c22c3462c
    md5: 507b0886079e96301632ac908248ee64
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fe72fa6da494a783c5d880885c71b746
    md5: b0fe39b660264411bc4016112318a629
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart349/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ed685bfab3b7ef18a086817db5592f2e
    md5: 0f7dafaf9ff2d2e2115fed0d05a8a543
