format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/atmosphere/restart_dump.astart
  hashes:
    binhash: e97ac497b048060da0e50f162817b6df
    md5: d392d76cf86ac7970e74198d34747b7f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/atmosphere/um.res.yaml
  hashes:
    binhash: 142df09224f6aed233570fc2e62c6976
    md5: fe85bb29dace625f8e7e78439876a130
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/coupler/a2i.nc
  hashes:
    binhash: 50f5df52ec4ec225514b5a6709f0060a
    md5: 4040bba9334de3be7f2ee67c5e9fda0d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/coupler/i2a.nc
  hashes:
    binhash: 9b6f63fe319744fd6a7fe2b14403c7a6
    md5: 48ece15241e56d3c9ac74e167b01f254
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/coupler/o2i.nc
  hashes:
    binhash: 0fe26ad5b4659b5fbb61d9e30f3fd895
    md5: 0f32976d2fb9db151614785dc049ae7b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ice/cice_in.nml
  hashes:
    binhash: 75e71fb8dbaeee62595ae173677b7121
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ice/ice.restart_file
  hashes:
    binhash: 69ec1d11534a701eb0e4cc5ffa60dc39
    md5: 64cb6cb6391a544e3e09a54b67b8e048
work/ice/RESTART/iced.1821-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ice/iced.1821-01-01-00000.nc
  hashes:
    binhash: 5c7e7246f3711d0fbd1788eb7ddff462
    md5: 099af602d90194e8abe626b954724841
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ice/mice.nc
  hashes:
    binhash: b9cb9665f1cf6e17607c861582c464fd
    md5: 34988130c14f8fc69e59d985eb5374b2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_age.res.nc
  hashes:
    binhash: 7abf6c2c9e6d1f09cc9d8a3067b6165f
    md5: 76e281b2d6f163a6bf2291ec44812356
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c82a994a17c74e4d7981f049dd4ce60
    md5: 1f9bf00065aee5117d8d4332d9cbd5cd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 04f28872ec9428d449f131e1d0f4b54c
    md5: 1c8f8abe7b604fb5618215b1f8e6f4be
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_density.res.nc
  hashes:
    binhash: 29325a5348a84383b89183c98d7b133f
    md5: 691f1b40770d61260c9700d36482f6de
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e845fe00d5aec66902b4ca038f747ebc
    md5: d60486c300b61563829e22091bcc0be2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 11ac4f75ac20a3d2f609c2e230ebc596
    md5: fa424e54cec80c2b36a402cc0cb72683
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 74bc687256d0700f97452da308a448e0
    md5: 2cc5065c91cd92b32327a25cf59091af
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 819b92da4f4cae12f4be6b58f0f67171
    md5: 51848000210a04174b0c20a8b7999c9f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9d2c223fe68f5a54214692dbd3ea2305
    md5: 352bed79918728ec63d715d7fa63e2a7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 39bd2e47c4338c967cde0b2f66df41fc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_solo.res
  hashes:
    binhash: eee4c721fba53729070d963ec45dc3b2
    md5: a8ff449d028b416b341d340515613168
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dfd67dbeff32b6c49c8062872437639d
    md5: a720f3247e651e50e50c286598b3e3f9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d45ec3507b9fa60e6775151394041d87
    md5: 192075ff3915bc50ac7d4082bb8b1940
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_tracer.res
  hashes:
    binhash: eb90783c6edc8697fda6931e447ea703
    md5: 8c8ed325a405c0889b3d15283e37d827
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bcc3c7868f0bcd5c2d88555c98226748
    md5: b2eb07b38cc288c2c6067d618a0e3cbb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9add5b471f7489ca56ce6b320339eff4
    md5: f157253dcd02055ab5dee44751bdc22a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d86a99f69a3734841ec02f01f715088f
    md5: 638ebc4675bad8c073b05ff2351e86d2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart376/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dd87c7b46df9478e4370ff90b1ebe378
    md5: 4f8fee507f51c747c059e08c13529d47
