format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/atmosphere/restart_dump.astart
  hashes:
    binhash: 6ea1625ad5aeaf19522e824c43c71250
    md5: 4cd717aa8f96f6a1c77901f7b62d1ada
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/atmosphere/um.res.yaml
  hashes:
    binhash: a3725003236357d831df2d7bdcff91c8
    md5: 606cee446e7b66de7b3c44e4139c334d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/coupler/a2i.nc
  hashes:
    binhash: a6af1e9a6c15fc4d16e54e03859670e9
    md5: 90255f876c9b38ed9652ba8876077f95
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/coupler/i2a.nc
  hashes:
    binhash: c5feedb901065b4e6530c98ec422ad2f
    md5: 1d4a6c9fbcab63d748a45a6a67a66539
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/coupler/o2i.nc
  hashes:
    binhash: 65c3d3fe538ed294f6479496ae280769
    md5: bc3fa0c6cf06fb1c399e26182386df6d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ice/cice_in.nml
  hashes:
    binhash: 78f69bc26d964497f01cd8b086fee5b0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ice/ice.restart_file
  hashes:
    binhash: 5e9d4d4a19db5fb0c1e1e5732c010aab
    md5: d26f7c383e62f29007a387accf06c374
work/ice/RESTART/iced.0949-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ice/iced.0949-01-01-00000.nc
  hashes:
    binhash: 765216cc26d39652174267b395c8010e
    md5: ef5a81158d91ddb7f6c8d7c941672bde
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ice/mice.nc
  hashes:
    binhash: b554010213a7ad1135004d62601a3105
    md5: 8d59c755a035cefd70288daa24f57042
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_age.res.nc
  hashes:
    binhash: d8374a4fcd39504d8831a3cd315a6bd7
    md5: 8ea6d68f4b8e6bfad43054411a7a017c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a62aa72a8f79b78d891320a62d0f4ea3
    md5: 7fb8e65a822efb3035c6c6ba7f11e933
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1d435c199350cea78c7ef9036210231c
    md5: 0185197ef7cabff996e7d24bd858f03d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_density.res.nc
  hashes:
    binhash: 359ec1d96def84ca2eb98f39d342df50
    md5: f7f403d899281f2ea1981c82f7db8d90
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ff152ffdd9e8118495a06c39dc942f04
    md5: fdbcccfd1ab99bc5eb65285dc54c2478
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fba40f3bf0885b0977121e14ab6b6669
    md5: 76c16213f7f088dcde8000baec6c9897
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cf8a84735beaef04f0b275be9d7c75d6
    md5: 5ebc9f0d555b95ba52052cd6e78b9db5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5b27499416ebb01b9066a45943abc1cb
    md5: 82f5d0e4151453c73a18cdb939825cb2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 04a4e5350d4145861cca6270fd007dc2
    md5: 0a4b246f97dd9180fca816c479138fe9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ca166604690d99c37c7ef20aa69e1360
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_solo.res
  hashes:
    binhash: 292542810abdc77f3c28b6e5e4c2738d
    md5: d4e203d56527de188defcc0c121f6673
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 383355e6db7b38911842f5a76ffbe7d0
    md5: adc88fb1afed666f20f24795e2a6c6de
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b55b008ceb25d0e474151a54aa5cc4c2
    md5: 3341b9734bdda551494451acc7e15137
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_tracer.res
  hashes:
    binhash: 49b8fa59ffb45cac10761ba1642161a1
    md5: 0ffd2d17862bbd1dffa36e75865c395a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7b8457a8f5665d8de86db2ef5a32e753
    md5: 85ffc8d65ba7779ff34f768382f1dde4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ac735b2bdbf611656621857c5a2c322b
    md5: ac9e103fcb7a42f9a637f03f06d51dc1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e70131a597142cfb3bab3dd77474122f
    md5: 6630feb2d03539630a322d7fc368a8c0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart395/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4d2bfcae3e1450656780ab7f6aadcb51
    md5: d33c7bacae91e4f636f5a972559370cb
