format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/atmosphere/restart_dump.astart
  hashes:
    binhash: a2ad6fa566d329b65ce943be7a3694a5
    md5: 2da4282b3fce036225f6c963cc5af3ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/atmosphere/um.res.yaml
  hashes:
    binhash: 40a7d9744fdd3500856ead3aee1e1278
    md5: 16c72c8fe2325188d49a6a319432568a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/coupler/a2i.nc
  hashes:
    binhash: 2459f12eae0db1165f5f598e155c7fb2
    md5: cad32bb8fafcdc9189815dc5ae1610b0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/coupler/i2a.nc
  hashes:
    binhash: 2f620033851d629b35ce46d49d1a488e
    md5: 2f7ea96a02dd438962a62a56d1f6170d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/coupler/o2i.nc
  hashes:
    binhash: 8611d5d22102fdbb23eca9427006b9e1
    md5: 2d9cc543b96044a98ccdd3c5e877c681
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ice/cice_in.nml
  hashes:
    binhash: d5ad99a2f1ba6a2770cb48bc4d4c3e9d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ice/ice.restart_file
  hashes:
    binhash: 8cfa8f45e40c8ba4def647143c5a9f91
    md5: 0c5a6af1c37ab167b84d79ff7961e8a1
work/ice/RESTART/iced.0981-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ice/iced.0981-01-01-00000.nc
  hashes:
    binhash: c3d764f950ad7c23fe50f195c507cef6
    md5: c214d41213911bf154d0021aa56ef69b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ice/mice.nc
  hashes:
    binhash: 3307e3b80d463eb1fcdcaeb2f83cfa31
    md5: af76d602f94381dc79932980bf5c3b65
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_age.res.nc
  hashes:
    binhash: bd5c8017f9b13844568db96cdfa5e29a
    md5: 3e47a1026460f5ac3e6fe6ee9ead83b5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0bdcba0172683bc25db9c4743151689b
    md5: 722f779ead1e0c512260ff897f3d0930
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 41a80d5208102c738f62669618a0c10e
    md5: a7398dbb0b712f6d480b28e6c120d94a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_density.res.nc
  hashes:
    binhash: 267d27b7b15f3eb3a7981e77b7f0259a
    md5: 8b3145fc4f74463ef0a2cabd974189ca
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 42a33fa2df82e91b13d3fe2b658d89ef
    md5: 9cf355f9c406a1666c8194edb18ea972
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6c78eae7c9e488545a65140deb960b96
    md5: 457fa13bb0dc113445f5d62bc2e2d6dd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_neutral.res.nc
  hashes:
    binhash: efe89250c8e74a47c8da0072616bfbe2
    md5: 240e3b6875c77d207a07bac9c1ccadc1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ebc18e211f5296a5bfe1c372f2154e2f
    md5: 581139e3ee1865990d8bd4db6791d76e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e04880448ce62480a75643c2317b208d
    md5: 603a556a1fb6a9f1eba911471c2e5ea2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 03a7891370bd829cc1f5069b3f393bbb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_solo.res
  hashes:
    binhash: 221235c548cec385da81d6b991cfd318
    md5: 44d5458ef60899152eb05eaf57afd68b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 54aed727b869a79fe398d289d2e4edd4
    md5: e6a45292c879dd3ad5eb1dd453d94214
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7161787aed28fd7fbfa7dea949b3fdc8
    md5: 2606acba7f7d0cc090a38e3ff860ae88
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_tracer.res
  hashes:
    binhash: e20cdc2f7fe503f275f5ebae4b715706
    md5: 414877c17fb291cd92e4871237a0a183
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cf0a8f6b732701486eded1c2f77426e1
    md5: f6fa6ef2cde272a6d27c7405542b2a4e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 37f81da57aaa7a53ea0e56a4d374fd24
    md5: 700e602e33df74805d1b7c0b1a6c54ee
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 614dc206091c0f9b2160ce387f87aea2
    md5: 6b6e52bb115d7cbab7c4858be373b752
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart427/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 47af4153a1b92a8a984a0a1d52aa5254
    md5: d6db9f83298bf103e7550ef107034885
