format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/atmosphere/restart_dump.astart
  hashes:
    binhash: 8fdadf62ff7767886654213070ce71cc
    md5: 9023f02a564bd2760e64d6f1443ac110
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/atmosphere/um.res.yaml
  hashes:
    binhash: 74cc3df5192c2b0d9cc550da07b25bb0
    md5: fe8edf842b9fea5d13cb4ec9cc9bbb17
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/coupler/a2i.nc
  hashes:
    binhash: 3c44611e843275d329066a99aea262de
    md5: d580026079c65b775e479c6ccd11bbdd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/coupler/i2a.nc
  hashes:
    binhash: 766d61de3e772a711cfe01854509a144
    md5: 7215014e3399c59b39ac0dc4e81eca0c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/coupler/o2i.nc
  hashes:
    binhash: aa1b5bf0bcc898321904046badf36202
    md5: bd4907e90960208a845ab1a9063d53d1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ice/cice_in.nml
  hashes:
    binhash: db46d5a730a4e0acdb99ca36a83fc02b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ice/ice.restart_file
  hashes:
    binhash: 4c0354329a6d5939ca8e2044d3f1277d
    md5: 1899eab11822789f287c52beab2b1001
work/ice/RESTART/iced.1816-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ice/iced.1816-01-01-00000.nc
  hashes:
    binhash: 34a7f9eb5ddcc0e77f9aa5a20107e445
    md5: c25c7fdc1a21f04c0a2a4572a32ab008
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ice/mice.nc
  hashes:
    binhash: 1260f3a6a0c1dbd8a1ed1674c2457c8f
    md5: ace601a48dd8b5d9eba2da63b100215a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_age.res.nc
  hashes:
    binhash: fc42fab60c38d5d479ae88d3bd18e1ad
    md5: 506005a77c77ce66f9356df627ca7711
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9a460ec89be8fb5f86c13e3bbb7612f4
    md5: 93bbd889673a6db1a43a88db72a4bf13
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 86afbc45a4a8a8308380bb2c119ff354
    md5: 1303c08716b4e74ceabf27f579be8145
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_density.res.nc
  hashes:
    binhash: 9a10c6ea16d3ebb206a51441c54816b5
    md5: 81bf7fae913f47b8e1353f37e1195617
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5cf30f660e3060341c0d38bcdec33dd5
    md5: fd1b0de52dfb6ef4f47e7a2616f08faa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 208ee633b0da5536e9a18f8df3390ca9
    md5: 5c20b458ea39ca6c7e54cec0992268ea
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 294f59a31ec8c47accef7a66ffb7b4b5
    md5: 5a9c221700063c613c163a814387e218
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8c42d3e224c5af550da01157f3fae5cb
    md5: 8a1b4b9e2a79a5992b0ea088e431d152
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 93bf255a5b1e64223782d4d2e25f01ce
    md5: 0850a1d729b49930f031a18e93cdd9a1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8b82de3acbc1febe25503763b914d110
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_solo.res
  hashes:
    binhash: 81457a2a61efa7a91a474d6c70c317ff
    md5: fb669e113e0d3328523de63a0a3a0fb5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 560b6cf6137d409407364537fbdeb703
    md5: 8bfc80492a2a7880bd83488bf5f80b4f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0ca155fee10d1eba57eeb1caf6bd9f89
    md5: a3dc52251eef19a7d3005e6763cd0be3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_tracer.res
  hashes:
    binhash: a3479b70e1bbd8760824dd7db135146a
    md5: dfd0de76d456eec26bd7cdd4f701beb4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b4038e8ed49492a63d6fdaf8bdbfa7a3
    md5: 1bf02fedda0f522e1bd7f7aff93dc442
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b18219c2ee132a68fd09eb301c3ad2ae
    md5: b7cccc0d022b17d4130a27338c6662b8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 186d1d08c9f275f0352f1e04b154675d
    md5: a39dd40708fe27140d84eadbf707d94c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart371/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3439e76fabce36bbbe634bf77074c9fa
    md5: 18ce7101914d0e6b945231433017dd19
