format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/atmosphere/restart_dump.astart
  hashes:
    binhash: 6d3c4f902a77d836d7c212f0b55782c5
    md5: 8fcd051c63214c202d6dd58346ea5b71
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/atmosphere/um.res.yaml
  hashes:
    binhash: b6e2f21ba68488665406203c40c758e1
    md5: d69f391ba0b651d6ae310cf3a65d5ecd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/coupler/a2i.nc
  hashes:
    binhash: 918d8b2a810c6836dfbe5a4744375b8d
    md5: 0864b9aef49162038c28493719da7802
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/coupler/i2a.nc
  hashes:
    binhash: ab419dedeec6f40a1870258962016f24
    md5: 64a5ec16d066bb0c0d2c9ea9577023bd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/coupler/o2i.nc
  hashes:
    binhash: 03062b45bd991484e6f63465fa1c9ee8
    md5: d2ce6013d1baa1a445e43d0894b1834c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ice/cice_in.nml
  hashes:
    binhash: b410a1e998609ddb570f81f33a8734ce
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ice/ice.restart_file
  hashes:
    binhash: 57247ad032ea366e50f61bc7ae3a0db4
    md5: 6e83ac6ada3719204d1ec87372b0ed1f
work/ice/RESTART/iced.1717-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ice/iced.1717-01-01-00000.nc
  hashes:
    binhash: 7e34dd23483aca999f53ce4e2624ef35
    md5: 0e7a0e282e1c91c4fb8bb7f726a071d2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ice/mice.nc
  hashes:
    binhash: b03e0698617f1f8d86c52ed1e9a467c8
    md5: 7c03d85348b9967ca2bd5b84128489f8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_age.res.nc
  hashes:
    binhash: 17cc1572bfc9fbb0bea47911229a7e6a
    md5: 8e96a77d737c79fea98cebc1488bc452
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c6afa54026b7e61d0b7e2ccec3e991ad
    md5: 3bd1a3c2e08bf631419ec96f0b979e4f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0745f586534c55e67eb2bd6ec1255bcf
    md5: 273ca6d7c4c5e55f958ac273b38225fc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_density.res.nc
  hashes:
    binhash: 6ccc2879164b11451f9598bc4f7e8029
    md5: 1a2954ce987ae22db7827f9985447c96
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 14f045f190ea334edbc758c79bef440d
    md5: 1ce86e9232597c6eefcc37db73ea247d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 32cfdbf42915b8a2e3526ecde63a0766
    md5: 911ee3adc795d3f63f601beca76b4c0d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 762d792e5007bc96301aaa115cfd7726
    md5: 52a3787fb9a07f66be0b513e57bb8da6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fc606bb025741341b961c95f026b25a5
    md5: fb65916b6818bc0a5ad9a775a0c17583
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 82f7c1f905578a863b24df72236c8260
    md5: 7e5325295b46402dc31514b4cb703e48
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: df37a49fc977d42ad34e1d7b489ca746
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_solo.res
  hashes:
    binhash: 8c8de06e0ac52622ff33f17da9dcc5b8
    md5: 0c72b60d354b2b6c7c98bf0ced918afb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d438a757a4148ed3a4f381e42a8f26c0
    md5: 6a2f4d124d64f528c827bb3270574e8d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d9208d3e9e1f4664ad98102c86b24a13
    md5: 86344bb9ae9d66b85b37e845cb564e18
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_tracer.res
  hashes:
    binhash: 8c65ea1ac02b5c3d254736e1dd242228
    md5: 49e813cbbb7cb52b14f56b1056bc85c3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4f705e1b1c4e2ba62689840aa897446d
    md5: eca0b889804a95dcfad4b0b4a74949b6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e01ede2302abd68f643c80ec38e24a8c
    md5: 23de930b7e8ec226d225bd0d8484d089
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 58e48a7568ccc98e1e1a199b9b03f54e
    md5: 2f39571e065958f358d7ce1d21c02c04
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart272/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ac0f2d2361f0c144faf128bcba307d8c
    md5: ad6a164677d005e851ed2e56fd57a179
