format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/atmosphere/restart_dump.astart
  hashes:
    binhash: 57c3a42d49c4e0c5892e7cc932f419ed
    md5: e342b674f80aeeb271d6603d5d13f619
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/atmosphere/um.res.yaml
  hashes:
    binhash: 2e3b51f554239694f6e7d9de21f35565
    md5: 02c52376e6645e651accc59030b3fec3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/coupler/a2i.nc
  hashes:
    binhash: 22fbece6863cab596cbd707835504d7f
    md5: 2134c8dcf73ea67e9970b35eb1f81251
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/coupler/i2a.nc
  hashes:
    binhash: 1b700e92d4b18ce5d10d81fe1d98585c
    md5: 03aa15ed83eb417cdaf3955edd6ee2aa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/coupler/o2i.nc
  hashes:
    binhash: 3849f1810854b7356130faa95ac5c48c
    md5: 22cdbc7597006495059c065b48ead917
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ice/cice_in.nml
  hashes:
    binhash: 2e4c34ca82f1d130099ef0887d6b0970
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ice/ice.restart_file
  hashes:
    binhash: 83b20454c7936129d923322330080192
    md5: ebde85d78ff25c0fafb4678c72102419
work/ice/RESTART/iced.1184-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ice/iced.1184-01-01-00000.nc
  hashes:
    binhash: 76d3d4cb9122a858c8c56382585ee9d1
    md5: 58dc4c17d22de7a5207fce816b7e2a1b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ice/mice.nc
  hashes:
    binhash: 2947489834ebed5a006ec3423d427012
    md5: 924087fcd61c442d6f706ee709e5885e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_age.res.nc
  hashes:
    binhash: a5a4ca10ea3e20926a80ae89932ca2d6
    md5: e5185a2fda95d1b8e525bf8714eaaf6d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 262331f46f8ea48c86c8fe1fd1139f2b
    md5: a70302e3502632e6e61bd2c6582239ce
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0660d58d4070373ad803c61c95065bab
    md5: 8bd2a0dc5371302dac7f3a07fb4f6f52
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_density.res.nc
  hashes:
    binhash: 691459ed6e6c242d1871d176e8261002
    md5: a225ddf0108f83c6c8e7039de2b6ce55
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ffa26e7ad042ac709b65e163ca455d6f
    md5: e866b3a58e266e54f50ae284d68786a3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d28e9ea1af67f582ec24b87ad18866a6
    md5: c0ed7b1dcd1ef4e0255896171b9ed5e6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9d4e2cc8b1db79676f9b9b79e5d0130e
    md5: f95921abee748c97fddd0b6bea11df8f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 87889dd61e3c3e40b3c31fe0a4111cb0
    md5: 4b0f82077c6599d25ebf14175f09733c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ed6ef7c6b1b018550805844016421294
    md5: 182de489551ecac1a0abe52fe71b8963
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f34d154c3a2408844c5ca3b998cfc175
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_solo.res
  hashes:
    binhash: fd126d8d0df3d69e9c330e9a68bf4a8f
    md5: 4cc416ebc4d57a3b73d706cc459f4e7e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 58768895466e4a789b1bb47adcb725b8
    md5: 5180e7479e0279acd2928946f8752bbe
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cc9bdbe4913208967f106c74bd6660c8
    md5: 130804c0454bcf56e155cfe9a8b802d0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_tracer.res
  hashes:
    binhash: da8485a6b92e4ed49a7982f028e284b9
    md5: 2f73d914b4c0d65bd5062039a7ba8195
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e0bc9bcc83bab24f6f717ee1295f3acf
    md5: 961fe673f416aa9aa2d13a2ac89759e6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 670189fa7105ab295b8a31d64035b570
    md5: 0d0586048197a95ad7b968b1525aa133
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 424d79214956a651d216b8e81bd05a49
    md5: 3a02e7c60605975a519009092146709d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart300/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 85ac535394ccfac64bedaf3df14193b8
    md5: 9ef7dc1587a1a90defd5a55ed1145a24
