format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/atmosphere/restart_dump.astart
  hashes:
    binhash: 3619f59f925fc8a479a692f76990e145
    md5: c5b2901826616e0ebb998c336968c524
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/atmosphere/um.res.yaml
  hashes:
    binhash: 2439cd90e4b8e2fd72480a0247993c62
    md5: c843fb9e84dea85a265a73de4d192193
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/coupler/a2i.nc
  hashes:
    binhash: 86be41465c87b4595bc27f0948bab5fc
    md5: b4e13b9535e68220730fd662f1658145
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/coupler/i2a.nc
  hashes:
    binhash: b9c922da9dcf4cc7f3b59e302007d222
    md5: 74a611683491d0cfe66320a237ccf5c5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/coupler/o2i.nc
  hashes:
    binhash: 76deb04c53825aaebe543be7571c1884
    md5: 4a3bf6ba93caa5b6e35c1c7feb180c6f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ice/cice_in.nml
  hashes:
    binhash: 7e10c1e79111eb18d0bebd656f7094af
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ice/ice.restart_file
  hashes:
    binhash: 71905d8dbee61c0be484630600320d33
    md5: 5fadd0f9cd11e76183f12c07c3fefd92
work/ice/RESTART/iced.1159-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ice/iced.1159-01-01-00000.nc
  hashes:
    binhash: ba3ad15d87cd8d5a943c4275fe7b71f5
    md5: b2788caf302dd99a9932e7cb4d8f0f54
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ice/mice.nc
  hashes:
    binhash: 008d542b0db0c7738381c58f49fe3cc0
    md5: 381f9409b310aadaf9e9a0926eb98419
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_age.res.nc
  hashes:
    binhash: 238ee3117fbe8053c024a3010b47d131
    md5: 8b94ed9bc5485f7fade309d459dab9e5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f22fd19651f6ce9f26b8dab46ce8aa88
    md5: dc5b1a77a02a8eef404363c3338a5cb4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dfd20ac3d88c5a65b8ac829fda1ddfb2
    md5: a03630d8fbb3129efb33c37719412239
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_density.res.nc
  hashes:
    binhash: 24e89394af048dd9f60374a2c49117ad
    md5: 41e48918bf498eb323726b9657f3196e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7863541426f294e1f2033b058b17b6f9
    md5: fdc8a70adf5e39ff9530352306bfd609
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 01df1207c1b72fa2ab5b332261276040
    md5: 14559170893bb68554d241c49207a6b2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b2cf7de5f131e5c213aac5dc78db0fd6
    md5: 2cbde8b532ae27643ce3e6a5345b4a13
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2c5b189100e295303fc06dd2bfffaa7d
    md5: 89df6a362acd7d32fc8d4f43cd72e3db
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 57bf9003f2ce02767b983c7771e9a00d
    md5: 21bde4669f15555bc4b5c4ea4a0e886c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1750760c5c41ade011ed31ba80774222
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_solo.res
  hashes:
    binhash: 15ef3865ae3febff331527fe1f862996
    md5: 711bbd5fea07395846ad45de0b60186d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d046174cdd5d40c8988537b42b484b1
    md5: 5425dbcfe3c1bc72f5e534eda9d57443
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 803add4242c3ba653aff3842be945e29
    md5: edeb46986f3c4d65927d3ccb52016502
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_tracer.res
  hashes:
    binhash: cbd2d5e8c2e47af3dd0e66b10d6648fd
    md5: 535a289f9f0d49c27cb12595aa75a1c1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a2245476f67fc3e6d0e763031c4341e4
    md5: 4be5186087d8d8c028cf2727c8ccb82f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7a3a3e959292c418280a339e03cd5c4e
    md5: f6e4f29c54bd047a4509aa56359f2c3b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cf16d8667ad8e755f4d812bb9b868967
    md5: 8dd4c4544f67dd305ec59b9667101aed
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart275/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 490dafbc2b20c6a9b89949c4b22770ce
    md5: eef8b9b3bd8a0dd1b022c669c54bf463
