format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/atmosphere/restart_dump.astart
  hashes:
    binhash: 369fc80ba48434cc283f49caee95563f
    md5: 805f54b5e2453ae90847a10da740f703
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/atmosphere/um.res.yaml
  hashes:
    binhash: 878d50d8c2de1bb81db0b443d553e795
    md5: 5f9d5681bd3a51af972922b8bd8ab3e0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/coupler/a2i.nc
  hashes:
    binhash: 04972d854cd7c18e6ad2245d9f99750f
    md5: 38fd434f6bef949bd2df66fac357773b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/coupler/i2a.nc
  hashes:
    binhash: 313513a8232da9f775d3d22b926525e0
    md5: 8e7a08462c8658770365d9803e898ef9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/coupler/o2i.nc
  hashes:
    binhash: 3033fc3e2c3ae9adbf64da2b1d62b04d
    md5: 4ba6107c4d77f7077cbbcb929de20749
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ice/cice_in.nml
  hashes:
    binhash: d2b66bc6bed3d9429e5f66a1fb9ecf2e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ice/ice.restart_file
  hashes:
    binhash: c5433c8596d659f43d71f3a3a0ed15f1
    md5: 2c0dad1169d94d7b6f351afe7ba82ecf
work/ice/RESTART/iced.1753-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ice/iced.1753-01-01-00000.nc
  hashes:
    binhash: 3b2d1413a133676debe75f53a2e1d500
    md5: 85998ed31210d9f991d23594d02172de
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ice/mice.nc
  hashes:
    binhash: 5bd182b0d51c56c5267491111f7d27d2
    md5: 7a9adf63fa9291127307f02ffa0e30ee
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_age.res.nc
  hashes:
    binhash: 3bc2e37fe1999cd9098b37f35befbf87
    md5: 0720b95f34ce55dcb50b0c3ea1657d69
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b7df3cc7cd68828db6cde8f9ae5d1250
    md5: 9cdbb34dc74555af85ebc8c2b0e33838
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 278c187e44d9b37843b70a34d25424d6
    md5: 6285a82b759f3024c6aae2a206d4a328
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_density.res.nc
  hashes:
    binhash: 7b39a6218c790ce3d982ed4bcd6a70e9
    md5: 0f930318ac9ee2434b5bea39fd6c9f5b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6ccfc25ce3d64ae2e4c45bf07a6624de
    md5: 6bf746f42fd7002856198c3371d5d32c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f01cdcedf80b51b83c08b13230e92dcb
    md5: 16c82fcf48f86ec1fdaaa4276beccdd0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d8a83c327f77f3f0545d96c76ce58cd1
    md5: bfcee00963985873dcc64c349ddf9683
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 95661a4fbd286e9a7d7f3fda761315ff
    md5: 4e14da90efc8c0dcc5a0392377f901e6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 90f80bb65d7c11459a8dce3d4b677f0a
    md5: f014be6a3977d381ade6228f4661afeb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4377a54efc28d8fe6c1b9d8aa90e36e6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_solo.res
  hashes:
    binhash: 15fe63bfe296df950199d699252b11cd
    md5: 9819d437d3c2a3e4eb6211137952454a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ab50d01174c5b34af71c5429d586cb4e
    md5: b5032c53884b862cfad1bbd91800e8b9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c269c1661e07dcf9c5c95feb3467e2b5
    md5: d93ef268e86626805a4ebd13f8a41d61
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_tracer.res
  hashes:
    binhash: 5f975c582fd5b4ce33ace584a55cc5c7
    md5: ee755fc35aed318289932b3b1d0cb876
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 37d52d3aa08f3e5dba698073956d6142
    md5: b1cb11b0d86749575afa85800c81ade5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9075e70f2822de82fcdaefe2b4f4b1db
    md5: e73900ee64b38b0d876a2b01985f97bc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: af5de37cd0a61a7c5a3fd2e268cfae24
    md5: ae4452c68f5006e3a6ea258f3032cbc8
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart308/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a991785bb4273c1231f359361878ad2e
    md5: 61df8d1b30563d05bc157148ed8c4b77
