format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/atmosphere/restart_dump.astart
  hashes:
    binhash: b44c1206065f84528ae6a60c8a6cf733
    md5: 7abc6d33fe8b8f4ef68caf50634d5fe3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/atmosphere/um.res.yaml
  hashes:
    binhash: 44c73907047e09e5b5a99ffcb3f9b751
    md5: c7caaf3b5b3620c4763c8f8a8b94fefc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/coupler/a2i.nc
  hashes:
    binhash: 97ce826acc81e67330487cbf5d2abb3c
    md5: 8c1890461c650bc4562543dc5aa5fc8c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/coupler/i2a.nc
  hashes:
    binhash: 8e39016347b5c35f4280b18d702e5cb1
    md5: 8c67de6de9338200788832fc045f2040
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/coupler/o2i.nc
  hashes:
    binhash: 6467cd05ee4e57c109a69ad72b8ae771
    md5: c4f8fb52bc57ed064a2676e542cec074
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ice/cice_in.nml
  hashes:
    binhash: bb2d3c0ef0e4fc6c650c9bbdb1833761
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ice/ice.restart_file
  hashes:
    binhash: 1b0224c98ec17e61fe2935b473a0835a
    md5: 19857aee119ef257c68fad5402722ab1
work/ice/RESTART/iced.1150-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ice/iced.1150-01-01-00000.nc
  hashes:
    binhash: e6d7fdfc6419335dc8384a2d4d20aa54
    md5: 672d0cd2813a0741fbec1be655d20e59
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ice/mice.nc
  hashes:
    binhash: 217587b3f0f8e50564e5dc41460bb141
    md5: 7790a8a2405cc9d2bd05450ddb72ec45
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_age.res.nc
  hashes:
    binhash: 0a8aa9695f2bf7f2d6b357c5c00a0e60
    md5: 2004c2a312896b28a29c44617f078780
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c1b32ac00fb716299a1a1350c0d9e72
    md5: 0b24312180a8a273be87e4907e61c23e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 99d06fe26eef032c0cee40f35270eed1
    md5: 1626c8de388b1e65f956e5b2423fa629
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_density.res.nc
  hashes:
    binhash: cbb1bdfc26f68e32f7b3cdd5d499fa52
    md5: 89ee552dbcc5b2985fb75f8981bcb28a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0da91a80be68374a0509d6a27dbceb70
    md5: 503e920060ef02c3a216e4d4590e6162
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a8ced56f6d8a14bd6694b436bf08a1bb
    md5: e05ef7f5352d26ee643da569ef5f3f01
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f8738f3b491973172c1e6145efc61687
    md5: 261c8864c4d276079d52144752769577
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a20b7e4c3fc4ffd73934bd1844730780
    md5: a2e67f0f5c69e6a75c494e81c9a22b1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2fce7be16de8d6c6bde06c14cbcffa01
    md5: 44d81e9ced4d0cfb44c1043de46b3ff1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c5d5b4cd142c4d23928fc49c525d4869
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_solo.res
  hashes:
    binhash: 9036f1b1a47bd6c6935928767d170097
    md5: 5c660d66f7ed447345caae5a4f29d7da
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6e0eb549f5fd0e39473f3c317594db32
    md5: d9ddd936b3b06d2994b1a06d4c813503
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a9a10e0ed436d1b70d245d271b4759a8
    md5: d873ce4acf847b1cc340bb75062f3136
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_tracer.res
  hashes:
    binhash: 49dfca66c91d71bd4b814b6594095dca
    md5: 4ca639cdd39ee6b2b73135a3049271a9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1ed582881f4bad7f1e61d5d8aeb5191c
    md5: 28bcf3fa4696ac60a74bf0bacf9d4710
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1df2e6c075275c76e940d3e82c365c6c
    md5: 1c366aa91063aae1ee924d7f5cc260cc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 059033975ec7c4529ab25baf4838f0fd
    md5: d642afd7c92854ca604fcb545acc1690
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart266/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f5ad7e13c7c6736a2978786b1296b6d8
    md5: 3001438acf921c8f667a2bae6945966a
