format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/atmosphere/restart_dump.astart
  hashes:
    binhash: db5f26740e3da25f8651c388375208c0
    md5: f81784555c84a85752a5b0f4ed27d843
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/atmosphere/um.res.yaml
  hashes:
    binhash: 98ab9d52427246dc33b77de8ff461b62
    md5: 24cd9ce647a0cb88e628036db0001454
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/coupler/a2i.nc
  hashes:
    binhash: ea93f6011316751a3bdc2f4262130399
    md5: ccfd57019e137a2cdc8e46d123974f3f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/coupler/i2a.nc
  hashes:
    binhash: 364ee94a3ca325a6af345ba43d804405
    md5: 8d745df13ce0ce299ede6176a01ee64f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/coupler/o2i.nc
  hashes:
    binhash: 8ad2850c2046957e23127f3509077cba
    md5: 7f8527099810bbab97440565a9154ca5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ice/cice_in.nml
  hashes:
    binhash: 98533d0a786d6c6c1bf90e5416ce5107
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ice/ice.restart_file
  hashes:
    binhash: 3bf8e33fcb4ffe663be63a7b070d486e
    md5: 7343e1031470de819ec3e178bab3e1ba
work/ice/RESTART/iced.1201-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ice/iced.1201-01-01-00000.nc
  hashes:
    binhash: 1dec54f33311866d4ba698ec2371180f
    md5: ac23e683cd679c20dd9e6f6773748074
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ice/mice.nc
  hashes:
    binhash: 4e719d0c4d476dba2ca86ddce154a277
    md5: a3047442ee98e8b6b815538ac18a1855
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_age.res.nc
  hashes:
    binhash: acf599c7a3f02f6e6d95b6d4dc072932
    md5: 94cdee257eb85a89d8dd2b791629f568
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 12fa31b5fdbd46c822eef8598f90b923
    md5: 4fccbdd5205d7932517ec885e4a6e26f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0a1a748327f6aa407ef07d58ff9bcb2e
    md5: 579bfebcff91cec57383292accaa4064
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_density.res.nc
  hashes:
    binhash: 4a99e090187d16ae69f0c4d0db3d4442
    md5: b558d450d2c21e7616051093699980a1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e5f1b457910950d43d6709e523362d93
    md5: 4faa1d907c3ba298933c75bf3d24a203
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ec544c11c0387dd9cb0f89d5c8544a28
    md5: 0cd43db9f7d58e0e64fd5130e570b93f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c7d3bd91eafdbb30d60f51cd61b79e64
    md5: b17feb91c89b094db44f8d05865a7a39
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4b62880a22a438f0505b686c8a74d605
    md5: 9253dbe026b6f9fc062e976d7791c8ac
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dd4cf0709ab978092e99d2edb4f4179c
    md5: fd672121f7e6accadc3f5932f2a22cbd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 12d1e386add37b31190f60d9e87854a1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_solo.res
  hashes:
    binhash: a1b3bfec884a255bb7c82984c8c42fa1
    md5: 7400c6b48ab4d8001eeb21b7259fd2a5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a4a716e45fe45f661dd238c1484dd202
    md5: ebb83ce7091f21dc3a82564c676f4b67
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f26ec74c0be5f2462a5b5291b066acab
    md5: 6eedc98c85aecb4eb7de23ac14c9ad41
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_tracer.res
  hashes:
    binhash: 7745ba378ed081c1ebdf4bd00f9ddef6
    md5: 2bf5e261da52a56df5b834fa8b02f475
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 21f386856d9dd548fd3864f74d7a70fd
    md5: 5d8ff81b451cc5a0370f76f3657de52d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2cba8d158e56de4b409daa95cafbb1ce
    md5: 019888982d786ee5db3d6c8a50f54413
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a07716298055b25a584f0e4c50a5b1cd
    md5: 90526a774ddab1a01e8c01d91431f7c7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart317/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 40a3abc673921e855ebb25189f87c579
    md5: bef35231bc8dbb4b39273facd7b91a57
