format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/atmosphere/restart_dump.astart
  hashes:
    binhash: 93b46ca89994c2818bf03578c85191c4
    md5: a094be0d2febd0819f1924cb4758427b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/atmosphere/um.res.yaml
  hashes:
    binhash: 940bd9539e6203a93138f3ab91d2c4d3
    md5: 12a84f1ca8d3bc55a16e44a602a2ee83
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/coupler/a2i.nc
  hashes:
    binhash: 6cbb0d83f459c28c52c34d72af55541d
    md5: 1be1250b0d0ebe274cf428823f1fdb84
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/coupler/i2a.nc
  hashes:
    binhash: 08550335ed288b1bd0367cca89a56605
    md5: 89946a4cf9c1afb80777d5ef7a66e963
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/coupler/o2i.nc
  hashes:
    binhash: 2a31c2e9c6cbc2b8b0e7cac0a8a143ba
    md5: ae672de627e1a7f950f4476a4e4673ac
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ice/cice_in.nml
  hashes:
    binhash: 503d0bc1966f617dcaf52e22c999e027
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ice/ice.restart_file
  hashes:
    binhash: 36d3cb7b21bc78bca77925c6e2e19ae1
    md5: a736ecc5c1ead727eb0cfd0a239d3da8
work/ice/RESTART/iced.1153-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ice/iced.1153-01-01-00000.nc
  hashes:
    binhash: 1a015b3c83522a0fa079a2b1c3f035ce
    md5: d8571debed6f5f2fe2ac7abc0d7bc6bc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ice/mice.nc
  hashes:
    binhash: 1c58186336248647d4abcdfafb9a731d
    md5: a9e89f25d4cb309a7983dd2cf41fbff6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_age.res.nc
  hashes:
    binhash: 67305b808ee3a119ff98bbe7b8495603
    md5: 812f5fea3cdd9944b8d4f86be470ca95
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6e468ce0490e85960c9cd423a4fcdbd0
    md5: c0bea53c2fd7d14451b9143619cd75bb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cd132c948ef4401208e020887b820c61
    md5: 87d7f2457ed6ba102d1d29a394e2b847
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_density.res.nc
  hashes:
    binhash: e5159290266f709db53d74182b6f2a41
    md5: 32abd93a5f1b538a9f2e2ab4f9fb8b40
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 82d99a2a08b0fef0aca81e5113aee185
    md5: 679dd082022b28b2b791dc384f946c5a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1058c1987303120ee8859ce2ba6085fa
    md5: 294307e3ccd79b911edefa1256cb71a2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 851b13674187220c3cb5d7b3df1b0eac
    md5: e413bf24918ae7649f702d6d68776ba7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 783583e688b601fba5362fac70ed3465
    md5: 0ce1e10e297517b50e85da141024739d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 92f9629b15d4f296a1f762cb55283c2a
    md5: 8e011dde1f5f0abc7996d5e6554e2197
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4ff9638a4c3277fcfaf00b8b851ec4a9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_solo.res
  hashes:
    binhash: 34b443b8257fb5e0a55b8ee3d5fcf6bd
    md5: e566155b4a537f22d7f060e2eb03c1fa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4145a01bd3c211a40fcc1867603f288f
    md5: 267e10d0d62f047ebd5c2414089f3517
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b822af926b36311fe9dd2f95fa8b808e
    md5: 5b38a22d22b0f433f18298cdbf86edfe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_tracer.res
  hashes:
    binhash: e1a2ba56fc7bff2c3c56deee5cee28f6
    md5: 4475e5b6e9a2aaff90993592b054ea37
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 71ea05a5281e0fded6f2893803a6cea4
    md5: c1d6640671ed4dc7e5717ca9b583f722
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bd2921487bc3bdb6f7a773b589c95162
    md5: 5d0a3e049b7c89afdd8f1c985399b0ef
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5b7dbc38725fac448c877afbd86215c6
    md5: 12a5dce4b1c61bb8ecfc979c4a9ba1ad
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart269/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 60d6b21bbe5b29929ad23ef10205a808
    md5: 58befe55ef4e6a02f48bfb1d0be77f62
