format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/atmosphere/restart_dump.astart
  hashes:
    binhash: 795f320cc652cfa905628228bacd460f
    md5: 5882abf7ad0b6d9ee25018c78efa9942
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/atmosphere/um.res.yaml
  hashes:
    binhash: 26b4f93b2ef366dfbb35e9a9832714e3
    md5: 23c585404d3bdc0b1d1e54ca2b6ced18
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/coupler/a2i.nc
  hashes:
    binhash: 89c758d3c32507342d1be37f691f1fa3
    md5: 3d2f79deefba2917654ce2a07caea3a3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/coupler/i2a.nc
  hashes:
    binhash: b7a65da3071935b2004f94eee821ed4b
    md5: 846fc3cd4b6140cae0e935d8160987a7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/coupler/o2i.nc
  hashes:
    binhash: 994edc1e7f7150712dd6911597908c56
    md5: ad78e2d326e0b863f8e53c83d7f5a0f1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ice/cice_in.nml
  hashes:
    binhash: 9c3735db48642bf1650905b89c680451
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ice/ice.restart_file
  hashes:
    binhash: 230dafb088797d3dece7b003134b6649
    md5: 99e8bd8b7f7ac8009a64f6c7e4ec95dd
work/ice/RESTART/iced.1804-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ice/iced.1804-01-01-00000.nc
  hashes:
    binhash: 6619bf2322183332d3449ee0119e02b4
    md5: b2c04c9129a2b84c140e0f5879286bce
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ice/mice.nc
  hashes:
    binhash: 2d8739bdc027d22cc53ca022ad6023d2
    md5: 8966ba52c4efbd6ab0e847da1592467f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_age.res.nc
  hashes:
    binhash: 3011edef72566d3f83f56f842e75742a
    md5: 62f76aa52a9a3b43aab144bc7acc0aa2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d1fcb8baeb7934f43aa720fb2439404c
    md5: adc1c2baea93a99d1524ccbb754a6b42
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e50217b2c92a75b46c069f17b8f494b9
    md5: e5b98de50aabb48c2b4194af68f70988
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_density.res.nc
  hashes:
    binhash: 1f89971cc78e0192e692153eb8876a4f
    md5: 843099f224cbacc6f3b739260c95cd32
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 47c47dd95e8546f11eb66e253083f0ad
    md5: d19ac5b28c4e19cbba620a958b4d5f68
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e18bdaeb219ae6c74faff3ef4f0423d1
    md5: 8f767268ac0066790a0b9d23c1b15920
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_neutral.res.nc
  hashes:
    binhash: abd7b2743dfaade66066f61ae1c3afdc
    md5: 7e0d54b50bd6818b0372e106a673765e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8bcdfedbaa6e961df959de59324ece29
    md5: e4f2a900411850e1a4aa2f1174d03440
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8568eb40879d73c00c16be46ff027c23
    md5: a7a4fe51c444825030c18cf03d4e15a2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9f5789f91d8c8dcd31b70f1698b3d4a0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_solo.res
  hashes:
    binhash: bb56001de783a0373d2a13e50bf32a15
    md5: c271a2cda29f0d83dfc3b895d826e6a7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 081cda67f2b06d1e813a06b35655ffef
    md5: 250d38dd6347f0c9e516f00f412efc54
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_thickness.res.nc
  hashes:
    binhash: acf0ef354164e232f8905e19f1b39c2b
    md5: e95bb75be21df65229864dd8549dd80d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_tracer.res
  hashes:
    binhash: d5d9420fc162c0575cd38d4d1f946dd9
    md5: 754064cb3f6a4cc73909ee4535f58002
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ebb2cbde506971c77839570690b377f9
    md5: 73819eb582f8bc3f1c9f7b43f66d8a14
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 260cbd3a0d3db2ed27298db1025bdb2b
    md5: bdfee6d55cb04e04bd470d56578049aa
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 799fc29887b28c6c2e2bb893e00ce910
    md5: c6c923800f2302d10a05b769fc25521a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart359/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2f4b3fb19262ee4d3c44e211dd6187cd
    md5: 2935fda4ddc57f00cc20488314ab4143
