format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/atmosphere/restart_dump.astart
  hashes:
    binhash: e18ac8fe99b2c577f121f2e3921a44ca
    md5: 0c7354e1720e7b4f0c38a0751dc69fc3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/atmosphere/um.res.yaml
  hashes:
    binhash: 7b40a853347b961ba61edb83ccbc145b
    md5: 0195ddb3b06c1116914e44dbc5ca024d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/coupler/a2i.nc
  hashes:
    binhash: de6f0461f11b14efaeabca7660eca606
    md5: 5090e802148b2a6accbf70ff1314c48d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/coupler/i2a.nc
  hashes:
    binhash: fb7c8c7c88795dfd99b45aa64f3642e9
    md5: 5467db30477fe055da3e16ba61396a3b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/coupler/o2i.nc
  hashes:
    binhash: c68ffe16fcf139c7c24cc6b152c5caba
    md5: dbd025a23b91e0516a2f24fe3e906e55
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ice/cice_in.nml
  hashes:
    binhash: 48c35c41c2b8037de0c59231ba7e3b40
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ice/ice.restart_file
  hashes:
    binhash: 6d9e7a0488181f3fe068c571d6c97857
    md5: fd3cd4e4ab71e4a3916ac5997daccadf
work/ice/RESTART/iced.1265-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ice/iced.1265-01-01-00000.nc
  hashes:
    binhash: 61c59a7493fc6a9bb0c930892094b6e1
    md5: 497ade5a046a47068428184cda044897
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ice/mice.nc
  hashes:
    binhash: ddaf9be5ba5a522aff0b161eee29220d
    md5: 483442d814316d0e529ab301b8b042f9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_age.res.nc
  hashes:
    binhash: 866aeceb69af9761747b3a77af58e087
    md5: 414fbe681363e634badeb937d4e7307a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f6aed25c2c46140a6a4a5b922bbe261
    md5: 7c0e042e68ffb70bd81df9a6bdcf56c1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0b63215ca00769f654cc1da17b8889d4
    md5: a981ec357f2de2e200ac1a66f0f871a5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_density.res.nc
  hashes:
    binhash: 87d0cb67643deb1761d99b212aadbac4
    md5: d51ae203d30b2206f1cc633801145f6c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a43ec1ca4bbafbea041dc94cc307a95f
    md5: 185e14d8c6388d52fcf7300c070bc8fe
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 28f913e18db11a013d245c47d6a47261
    md5: 5d7adf65571fe4526cf6ce1ca61707e8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 172b2d0b4a607f12f79edbad05ed3c07
    md5: 08d5f2587aa56cc996b6238812c83e85
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5fc9e9f515685ca32a8fc547c5e352fd
    md5: c2aa889142595cd2e199d970ff3f380f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f1effeec0c54d71ab6e20cdf8c5074fe
    md5: b048ceedbd0ea60bc694e5ef44fa0bde
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 85eae0573c997f4f04d00f10bfe36626
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_solo.res
  hashes:
    binhash: 339815924efa1013832fbe71c362e93c
    md5: b570861b8c8031902773b3d079e64b57
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ddb0181e5b56503871dc550e4511444c
    md5: 9990e1555e6ffd459ccbdcbdac569b68
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f644ccdce8b31dba68faf31f118b0202
    md5: c774fbdc3cf694d8d6b49a8042c37b38
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_tracer.res
  hashes:
    binhash: 9c3c7b58e22681044181a0ad955077a7
    md5: bf771989472aaceae514d08b3391e635
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4e716998a0d2938cc82dcbedfbe48534
    md5: e1f0a8512507277ffc5ee265dc72ec0e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: df9c5eea7aa29f26a9676095e447a77e
    md5: d3dbc69523e244568a57c9512d01317b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4801aa0138ed021f14b8da80baaad449
    md5: 14b0578d2ceaa3a7f45a274ae6ac002f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart381/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3b71f7ba47ae4e408aedc17f4ba9ac1b
    md5: 837d8c23cc4151fdcbabf624a86e4e95
