format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/atmosphere/restart_dump.astart
  hashes:
    binhash: 5508df9b009d8eb89c87c23b6004cc45
    md5: 2ca2f65e21afd0ad5180f38504cd027d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/atmosphere/um.res.yaml
  hashes:
    binhash: 03439de2c8eee3534a8a1461ea4caacb
    md5: a6e7d318de573ac3f959340d7f59048e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/coupler/a2i.nc
  hashes:
    binhash: f9fc075ce3d8dea5ead9b60106ef0460
    md5: fee531fb3af3906aef2ff4714af0e53e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/coupler/i2a.nc
  hashes:
    binhash: c9a8bb3f8a2af3a44dbd2ef59503545b
    md5: 4cc429c82d5e36d17f0eb218dac8bb25
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/coupler/o2i.nc
  hashes:
    binhash: 40138d760e45e436d99d523c16f7c5c8
    md5: f2a209bb1b975f88ed9fe76d0af4b993
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ice/cice_in.nml
  hashes:
    binhash: 488ea2d8e22b9738619a42b4eae0a1b1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ice/ice.restart_file
  hashes:
    binhash: 633e8c9372e3687b27941839d4d163eb
    md5: 4662fb235491d951f359cc5532e4e784
work/ice/RESTART/iced.0872-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ice/iced.0872-01-01-00000.nc
  hashes:
    binhash: 59bce87bf76365d630b1ab33286d054a
    md5: 20018d0b713b560ee554730ee9538403
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ice/mice.nc
  hashes:
    binhash: 91a28b131e1048c9799c70a48884afcb
    md5: bad4bcf0367c7b89d682a57181fa90ef
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_age.res.nc
  hashes:
    binhash: b8cd1db935184f2fb4485642e76765a6
    md5: 9be409e31c0fcd2ae0c2763b56bf199f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 65d2b4f825c3403b4a8a8ce88b01d0d8
    md5: d800cb140c7a8f10d482ffc0d156d03d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 39619b8142903bf7a0bc9630f3460459
    md5: 9d5c89691970193713b569bff70172a7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_density.res.nc
  hashes:
    binhash: 46883ddc138d5305f8a12ecd16ef0235
    md5: 739af76a29b7b1e58e3b88fe62f84f2d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 108c543d6fd842d60adef289b2d9d651
    md5: 9e40ec73b2b2f5911032f0024d29f98a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a48961ebdcde732195f3cfac950572bd
    md5: 214d56526acbd12090f17be129ce89a7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 32cb976b0fe0db0092a3fa03ff7aa984
    md5: 76f9ec64e8e843b9f048b93068eeb0d6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5bc639a02a785d5bde64e67525ddb480
    md5: 29c2f8b82007d5a8d046e6b6bf27b134
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e80b969c83b4bac5d6ca390b35379d81
    md5: 24632417ab0b94a641b8014e8d9414c9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0e4ebe82decb9ae17313f927a00f625a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_solo.res
  hashes:
    binhash: 26244e4440f0f2053c30db10380cf6b3
    md5: 52706be7f0835d6d37538ad0f536d264
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d15c38ff77eaa79e45b0387d409c13d
    md5: 7fe72ff8d0a1b87aa09aa8c534cc4233
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ede98669b972c497ad1138066a644586
    md5: 2e56feff0afbd77e87fa87c5f3d90fd3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_tracer.res
  hashes:
    binhash: 019226b0149d2acd05ce2e10e0dff0f2
    md5: 12bdbd609b4aecbb1b7a23f8c97e3a39
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 99a880b287d6923841e81c7e9ae6f46d
    md5: 223b52339d768a2588b149851e68f318
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7437d88564da8b8b2881aeea71d82d07
    md5: 6504696caa23f5da976e9047e027e139
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3ca339c2797854c9eed1fd1e6521d216
    md5: df5fbcb2f6f6698799287f89f8b93e4c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart318/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: eec1880176a2f2be0c192a4301fba1a7
    md5: 4f6bbf30973cded24eece8830a417cde
