format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/atmosphere/restart_dump.astart
  hashes:
    binhash: 97f1f4d569d8581bbd47ffda04cfd9c4
    md5: b5f7a9a519e97977331ddb269f415bab
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/atmosphere/um.res.yaml
  hashes:
    binhash: 8f0a8dba414f4c76e03e8f7136b347dc
    md5: a0c2b468a5564e68bf7715d346898cbf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/coupler/a2i.nc
  hashes:
    binhash: a8c94b20e127855fa2e0a014feb3c8da
    md5: 8dda2612ccf205325c24e131963b4ddd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/coupler/i2a.nc
  hashes:
    binhash: 3dbd75da0239739c8cbb86c6e128663b
    md5: 858a6f30504e4cb7cb24609cf3d5d392
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/coupler/o2i.nc
  hashes:
    binhash: 10aabb197622e6d0a5b9f1dddc01edc2
    md5: 5639c2cc88d44ee06a027572f06b3d4a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ice/cice_in.nml
  hashes:
    binhash: 16c33b0ac5a0307b59043cdb34ac101d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ice/ice.restart_file
  hashes:
    binhash: 516defe60215a1f8d5f10822a21cf7f0
    md5: d790441eb954b94d987aa009720a1ffb
work/ice/RESTART/iced.1834-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ice/iced.1834-01-01-00000.nc
  hashes:
    binhash: 62d3f3ed14a796803e25c89bf52a4833
    md5: 11ef19ca50b0c8547ac0320e1e306dbe
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ice/mice.nc
  hashes:
    binhash: 2166b5e5aca18eb53c12d00b4cda53f2
    md5: 76ca280588291393f3f7748cf83726b9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_age.res.nc
  hashes:
    binhash: d687308c78fba2eb6b1d6908356d288d
    md5: d44380821970ef6f985f7d14aa70eacf
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: eb459a37b79d13d6ec3933bf52ae093d
    md5: edbb0a60e5ebfba7fb2565421759ab42
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ce00962539b4f92a852318968dcb190f
    md5: 508a85bb551cd46f92e0a760f67c8c2e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_density.res.nc
  hashes:
    binhash: f99425990037a6d72465fe9b6060ddd5
    md5: 5c8f9322dd5f6e1a5bc05d19fd926592
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2c842c7856695097f08e3f9fa5f43418
    md5: f6ff07bebe7ea4cc7aab5ea33eac755d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8cc6060cea2674e646d46203c482a7e2
    md5: 5a0fca60ebc8ae57ade2b5c27cc422d3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8cc96453c8bc63c641cfe2073a9b57f8
    md5: 6e44eed2c803c55ad1ce240e21d67023
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dea774ef93e55e877c5d2709dd70da8c
    md5: c05ed86863e1b72b661e6c1540c92e67
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7a2ce9971f94076c1765cf87638226de
    md5: 06e69b7819bf1ddcae6d82ec84b4ee58
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dcedce237386928c3efa892bd48f7db5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_solo.res
  hashes:
    binhash: 27ad0340e7f09b87b44c49fc974ec4b4
    md5: 925478fed279248c830cf9bebf913d23
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8a474310f5ad23013cf8eaadf3ffc685
    md5: b1d39ebfcbf76eadb1022e4065d4c516
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 611f0e6154ebdda4985141371cb161fc
    md5: b206b5a67b5ba51695445b13e7f9e915
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_tracer.res
  hashes:
    binhash: ebdecb67715574d822961442bd5829f5
    md5: cfa06224c23763541eab26d99c715ca1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_velocity.res.nc
  hashes:
    binhash: daa73dbb1532ad9f24f2c15f2ee77802
    md5: 877b6c6376eaea3f760ce73404f999a5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 32e29fee338af1c64c9c2bb2fb6ba337
    md5: 4c0cde22e0eeaab45e135635e535d5c2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a5cd7cc25e555ac491a58c4d1aea9019
    md5: f9a425ce490cca65692a51191bb4a513
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart389/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 069002c1d68e47fc346c227e17519a7c
    md5: 56447d4894c31e345fe95bf8371b85f3
