format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/atmosphere/restart_dump.astart
  hashes:
    binhash: e29497325185ac2eadb51ac9fb9c654d
    md5: 9283df772b187a0a7d22031d0e0cde94
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/atmosphere/um.res.yaml
  hashes:
    binhash: df44c005c0cd0e5d843bbc68b1975b11
    md5: 5be97b726ed3d197d4ab080023260511
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/coupler/a2i.nc
  hashes:
    binhash: ea8d7a1f6852208e0bdfbd07947e4b24
    md5: bce5d5938a3880114ec665c1b1a517b2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/coupler/i2a.nc
  hashes:
    binhash: ddbfe160b44cbfee603a649479e7cf2f
    md5: c1ab254a31d91a714666a72911af7f19
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/coupler/o2i.nc
  hashes:
    binhash: 99c5a1afbfb1d56d5a69b94e34dc1a29
    md5: 72de444be24936e315a2beae251861fe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ice/cice_in.nml
  hashes:
    binhash: 48e7695a8d3849fa53811a0d20bc8831
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ice/ice.restart_file
  hashes:
    binhash: ebddeeae02365712376bf54bafa9f17e
    md5: 09cb2bc482339443690e9554ee60960c
work/ice/RESTART/iced.1792-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ice/iced.1792-01-01-00000.nc
  hashes:
    binhash: f147d8bd883b20dfe642e71b3cae37f9
    md5: 1a40db2591421b69f34d0f705e57a152
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ice/mice.nc
  hashes:
    binhash: 7753d53605a25edcb848dac0ec31da6d
    md5: 1a309a49b8d3293f89ff98b5d311e6fc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_age.res.nc
  hashes:
    binhash: 0c90a078a28e761fc941e5619ef04fb1
    md5: 3be8824804f71cf2c36b239b89e65081
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3cbf69441023255b47d8971d173771da
    md5: 982ef8efe9a499c1d48a5944bdcc5c63
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c0a4de70790a31335a5ce5244737b166
    md5: 02145abff7376e1a99f752c090430b89
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_density.res.nc
  hashes:
    binhash: 29a1a8aaeadce815433f8d2851f5b9e8
    md5: 01f100aea55d855708e5f749843436dc
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 638a851c8c1c697be7c1174fd2af12a4
    md5: 87ec792c1ace83c7a4aa6fa4b25c0dfe
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0d046122ec6d8ecba8d41ef880404fc8
    md5: 5e5b8bd03b98bc23c1d8d7903208886d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2452711bef9dea229d56d41e4a2af631
    md5: 9c3c4d2c858a609220e86707c2e44ee8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ede77473e5bc3db5737e9cfb837a7e9c
    md5: 5926c43ad45ffad5d5359a919570c4e8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 86988a4a5bb1a42d9f2905e6838b258c
    md5: 2745b888c26a079fd00040fe24d21fb2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b0c63b1efa3bec621192a38827109810
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_solo.res
  hashes:
    binhash: b0fd852b53a3ffb4b86c7ae57ba4e435
    md5: 83e0e8abb511a6fc66da5f256bea62f6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0c6fe0fc52ef2caad4b910bd44e5b80f
    md5: 26ef7b8c470d269048633388c5bc9693
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 886095d8b3d60dd85539f6c130ec61b5
    md5: 62b65399becc71cd4b2e30605b986206
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_tracer.res
  hashes:
    binhash: 4d21524880924429c9b2534f1e810495
    md5: a3503e52a1bf0ab94dc680ef552f8539
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 337e6c9f0c56ec1d208369196ca0df8e
    md5: 241167d7391324e776892de172392fb6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c70c2dd1de960098b4a9f5699a2f6073
    md5: 964d9485e80f6c4b1b6b2bdcf0c0c0be
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0b097df1f4a1d5bd93bddb173124ab49
    md5: b7bd87f0a0a336ef69866fe33c7d370f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart347/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 291a7f98491ed79bf48309114fe4edb6
    md5: 3aa59ef874161efc4fdf77eca7f82448
