format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/atmosphere/restart_dump.astart
  hashes:
    binhash: 39fd5a8231681cb2971a075754a86798
    md5: 97e458b7a078896cd83a8b549fcb52d4
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/atmosphere/um.res.yaml
  hashes:
    binhash: e7cdb8568322d93349daa767d2756e95
    md5: 8706e8c7a3b3e4f41469806d4161dea7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/coupler/a2i.nc
  hashes:
    binhash: bc7328f088a368ca0796f23a496d914d
    md5: 84065f29237d9f9d617a8af0f18c466e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/coupler/i2a.nc
  hashes:
    binhash: 46b2e281fe57664005fa0214adffe9c7
    md5: ea11ee526d9481cbd73e070eecf0c313
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/coupler/o2i.nc
  hashes:
    binhash: 0c286fb88ef8a68d5414d36525d500a5
    md5: f6b5b0fdb2a5b1fba3e99847680edf3f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ice/cice_in.nml
  hashes:
    binhash: a343c923b39593c3dc09169ed1474abe
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ice/ice.restart_file
  hashes:
    binhash: 3da1b282d4ffd1d2847b2b6bb8c88180
    md5: 5463488c454bfc75bbc47a1a54be2fba
work/ice/RESTART/iced.0886-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ice/iced.0886-01-01-00000.nc
  hashes:
    binhash: 4ca4da67b17531707d51f7409a50fea8
    md5: 74fe60936f14ef9f0444f89a8758dfc9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ice/mice.nc
  hashes:
    binhash: f8acac9d5edba1e8abb24c2be7e1340b
    md5: 54835dc3807e391f45ad8ffa9a480fb1
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_age.res.nc
  hashes:
    binhash: 80c74bb55285f60962d2c9bcb8830996
    md5: 5caa63afe60579573aff6a8f1c520e07
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e14356262218ddb497a4d5c2b0f803b2
    md5: e564c37b25b51c348327bcbfd1108afe
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dbd4849b2cc916e4a29a53a2fca570d1
    md5: 7e4d4a512ec93db982212657267249e3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_density.res.nc
  hashes:
    binhash: 631caab106c3a9e240918bf94907b47e
    md5: 40688c2545ed3b188684d1c2fba0fc37
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5e37654fc0b68707bcdac245d1118aa1
    md5: 087d621abeeb90571318d72048be317e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7058375133bbf4428a5f9203c4f567a8
    md5: 806e57f8aa57ff4ef4e06c6a89bbded0
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 150a16345dcbd39335de165a30d4a927
    md5: c63965cff9853ab3693e121a26700e1c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9ccb8bd611144e60c6ee898aac1ccd57
    md5: 294c19814115f4182d8529c9f29246c2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c1092847064dc639d29061fe85c48f5e
    md5: 6254b948c89d3e48776d48533df72cf5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9575666b9333e9befed2f07094011ef1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_solo.res
  hashes:
    binhash: 4520029cf6ddd6d3b7e139274ab9474c
    md5: 2152fd073d172d56cd8cecee29600a0e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b0581d9771bbd78fe8731ea38efaef1a
    md5: e6f92c967c4e9c98616b3976da8f44ff
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9286e0ed247e037cc8f7b66f921a3af9
    md5: b782dfa113f1d73c66631bf93279b64f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_tracer.res
  hashes:
    binhash: eed8dc1cf3f8ac5a145df48699e61d4f
    md5: d1a3deda189d26c02e54c413e5e8664d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ad1e544631062fc903faef18a9c24f27
    md5: 50917c519552256b537e49d13ff43482
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e1060b675a9e5dddc012507a9e2f56fc
    md5: 3f8f703bf4347e55093a0f2df5a4a95d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c55017130a396fa028ca3f410fb516e6
    md5: 4c6ce0e4cfd48fac8369e678beb1ebac
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart332/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0c55cf6892c9921983166286aa633443
    md5: 729b0dce2878103c9852f0f5d59e119a
