format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/atmosphere/restart_dump.astart
  hashes:
    binhash: c5727069ad401729c6b4cc4d7afcc1ba
    md5: 61cd965cb37b88ed9f21be79668192ce
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/atmosphere/um.res.yaml
  hashes:
    binhash: e6283d94c88fe9f55efe33b2d7079a4d
    md5: 9d86ca433d63426d8628de2e5e980008
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/coupler/a2i.nc
  hashes:
    binhash: f0865fc948256305ac3543b1c490d8ec
    md5: d7017c8b9aab9f3ee187feaa6ddf05e1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/coupler/i2a.nc
  hashes:
    binhash: 48c6bf87b8fda7e17bbef433b538a6fd
    md5: 94567cec47d557ecb8ada723ec15d58c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/coupler/o2i.nc
  hashes:
    binhash: 1c9621fb108bd44e332e18978df3f122
    md5: 96a365b67e015b8909c50a8f9dd355ac
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ice/cice_in.nml
  hashes:
    binhash: dd7e8bb1f9518b0f14ad6e96d45e57fa
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ice/ice.restart_file
  hashes:
    binhash: 92e1269ea2cab3aa45db3cb463d643a3
    md5: d210cb56d0eb8d655570e2b698ef909d
work/ice/RESTART/iced.1766-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ice/iced.1766-01-01-00000.nc
  hashes:
    binhash: b507ead2839ae0987b1eab2227de835b
    md5: a9b46a0fe4aebe8692e82f908fc0a875
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ice/mice.nc
  hashes:
    binhash: f0ced7b33939e9785d06f275e96ef504
    md5: e58281924a9e924c30b6cb3d8d4027a3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_age.res.nc
  hashes:
    binhash: 24e4c79a2295aa03640797e93f075785
    md5: 89fff25165b5043fac01a43d02fb478d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 680ffd79bf12f08e8509f087bd9b475f
    md5: a1402e750ee11790fa050bdc3e62373c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8f38b0579dc61490e67acbb5c5c74cb2
    md5: 8b935f4516a7cc8b0cef5cdd9250b28d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_density.res.nc
  hashes:
    binhash: 0bd50509099accb09008b4fa37f0a580
    md5: e3f15868419bc48afb331f02194437e2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d58c62036e878f598ace16bf71e45644
    md5: ecb6d55ea9ba603ff8dfc8f3b3b9a70f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 78822a13d2562308d8630acd9fb10c69
    md5: 145bab6a8a634dfb93e34667951517bd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3c4b8a1e6a57c89581ae224c01f8239b
    md5: ca0a6a4672bea380e7d8ae955a33e1d3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4d3d746c6dbcb1965f55f9883c2d433a
    md5: 4c3ca1423492fc46b00eb192bede82cb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_sbc.res.nc
  hashes:
    binhash: de8ff711eb04348072a78e2d9f07fe6a
    md5: 8bf17e4fd54f8cc86393d6a99c13dcdf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7d2ca42f53ec1325264657be1bc2ac33
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_solo.res
  hashes:
    binhash: 1db8d8bb7ab6e3dab453820a95226fcf
    md5: 529d84f1b604848e5aa91576744e8b8f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8c0cae69a53305930932fe0ba723daa9
    md5: e6b7a42e7e00209f2a37fdcdec64410f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a1d8b7428350709ef310f02b32fa7e13
    md5: 8007704a77e25d8d0cd234de35698daa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_tracer.res
  hashes:
    binhash: 4ff5a2136876ce296e860f593e579a16
    md5: 4156b2527044b1bf537b06b3eb3bd567
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 939ed9cb0dff7a5a2fad62fca78d35d1
    md5: 6c1771d67ff508409a64f270a75ed9e3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3e6284d3d12be299b029321cff18e098
    md5: 4f9a004ff4d21e11d6652b98f5f79068
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cc63ce4bee3f39eec1b06e9268d3086f
    md5: 5153eb58e7b15fda18e7c4d6bf434ff4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart321/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a7ac50c503606c5efc210680d4d202b8
    md5: 398ee58ca3d3fa76a498a9208e8f9543
