format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/atmosphere/restart_dump.astart
  hashes:
    binhash: 26a35d667961265c720277f6e87fdbbf
    md5: d543f74ab7dfe339bc9c9c53ab3f84ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/atmosphere/um.res.yaml
  hashes:
    binhash: e46f7ef0dedb476ba59804e0b4926760
    md5: 3d31ea3291f60698bef863578bcc2a0a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/coupler/a2i.nc
  hashes:
    binhash: f13be7b159d533d5912abeb1a5998747
    md5: f8287e1bb209c78058925fdb16e453c5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/coupler/i2a.nc
  hashes:
    binhash: be7b28799600edc127842dd0840261c4
    md5: 22bc6cf0ab6c3811fb423bb3d6df940d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/coupler/o2i.nc
  hashes:
    binhash: 28ff2180349ae1ed3e83592d8217a4be
    md5: 39ccddcaa5ee38ee5f8d2b67c1947b84
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ice/cice_in.nml
  hashes:
    binhash: 9da269a6e88ed4a1791be7f857c66ba0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ice/ice.restart_file
  hashes:
    binhash: 519ac12ae77ea14a20ebe102919288a8
    md5: a2ac81ebe121c196ab91f66c239579e7
work/ice/RESTART/iced.1187-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ice/iced.1187-01-01-00000.nc
  hashes:
    binhash: 265e877027c85f0aed4c564f6572bab3
    md5: 7236e179a8455bb08b602692ba54a2b0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ice/mice.nc
  hashes:
    binhash: 0ec97f8c37a7225ae7dc5e5d6ef45afb
    md5: 0a31ce7d09e204936c40c071b527d191
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_age.res.nc
  hashes:
    binhash: e5cc1e90bf4fa06d314c77a46ab3482e
    md5: d4a6c4abb9d3b6cbdbffcd1e4531d061
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8e3a6151f5f065bf7ec6f89538a7aa83
    md5: 5d2f2da4eb338638f5436db3823bd8e2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d5ab9d40756bda6fc669cbcff816d20d
    md5: ac406b3ddcf59bcbdf0b6049d2f254fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_density.res.nc
  hashes:
    binhash: 6e5fbbff7faca0ad4259322be4c78659
    md5: 04b10da42a443edc8ffb6ba74ce1526e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ae3bc4918e689bb0fadfb6673a4cba18
    md5: b59190bba6bbee70948e45a829c288a6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b0f72bd5f85f4565257a812e140c278e
    md5: 5a6bce64f356ebbbddae98f304a35f93
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a67518727db3e7689ec3977d8343a25e
    md5: 06fd08a27241e33c43b29eaa09a2eeb8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0156cc9d585b425f296d04fcfad92d91
    md5: a099d45a2f6a0b21746ef87f9afc42c8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2ec2e3170fea03478ed153eed36faedb
    md5: 98f35e7d7a82a0577a0127e4a12002b1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2b36ce8f1029d99e764f6c3b027b18ba
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_solo.res
  hashes:
    binhash: e4c3bd8acba5e5174732fbe1cdda918d
    md5: afbb23e71e0c1c550aba4526fed135f8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4eae7dc197b810bdb173f08c40bccf71
    md5: 968ae1e63c7d4f8a6b2f871de95540ab
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a9b39a5af81f04a9fee4d53c8584ed7b
    md5: 3a5077b06c44057fe32f913c3788be40
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_tracer.res
  hashes:
    binhash: 2cc36a9a65be2569d38ccb9ba25b5311
    md5: 01d1eab82b7258704967def0c7468bf7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 98089f4da42b276383c097c57b34c0d0
    md5: 540e1434029850a91454730f7a6f6726
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a3018876e9f0464dc8b5b96e03ec7dd1
    md5: 042dae64883e9e494e57f35bf8fe5f9a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b4d006d61f661e71c3b2b5c77f60b032
    md5: 97e08167b54f22170347be16924295e0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart303/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b3a32ea97e408374d9d80e1d5a3310e2
    md5: e335fb29e2a169814072c4985dac023a
