format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/atmosphere/restart_dump.astart
  hashes:
    binhash: b6d928678183efa75e235ca28de08862
    md5: 03a8eafffb85564582f64438c2ba4e5c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/atmosphere/um.res.yaml
  hashes:
    binhash: 2eda8c9814a577bd60d87edbfb5eb8ed
    md5: 5272c2146d89764eee73d5c1fa874ddf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/coupler/a2i.nc
  hashes:
    binhash: 825159196853d9a04381a48279c88992
    md5: 26c5faaa245c6f530417350de71a978f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/coupler/i2a.nc
  hashes:
    binhash: 93e2b4eaf73fd4fe92a04e7445bfd676
    md5: bb888fc28daf7e6ceb4f2e2e3ccbc722
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/coupler/o2i.nc
  hashes:
    binhash: 950a53c575e356d6f9f3a582aa85f576
    md5: a74df8969cdbc23ae939e93041a5b5b9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ice/cice_in.nml
  hashes:
    binhash: d2f1512dccda7588e6a11ebf55404879
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ice/ice.restart_file
  hashes:
    binhash: 47db762d47823a8ba75709c107a41418
    md5: 85e8daa3b0009696d6cacc3900ba7528
work/ice/RESTART/iced.0895-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ice/iced.0895-01-01-00000.nc
  hashes:
    binhash: de28cd66afa33727d4da7dcec87085ea
    md5: 45699696dcd4497e7007716d9d64123f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ice/mice.nc
  hashes:
    binhash: 863071c72352cb071951c39f29e65950
    md5: 4a6f02cff7208224b7583ee29bba1a12
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_age.res.nc
  hashes:
    binhash: b128ce9f9e17ae331d3bb79d3ca035c5
    md5: abef55d8902372812a044e6de459bbbe
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b2194dd3f0d2831503cce0e088686e3e
    md5: 5b167c2f49ec5b05f970f5dbaa3f7971
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e3b52d35a86c920d0dc8c93c73dae0f6
    md5: 0fb076ecc90a0a33f1f90d20760096cf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_density.res.nc
  hashes:
    binhash: 04a4ebf6577fb9cfb4b04160d01eed13
    md5: caaa274e5356867e5bf04027a48cfdf0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e0b6cf4bb826abf2cd20229f1fb4e0cf
    md5: f86e3922f0e048dc35dab7f6f4bfaeb3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b79fcbed726fa8a2e5226c49da932c9b
    md5: 64c4bb4c6c897d173b3e91c8f9bccf90
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bc70975fbe6895880c16c3ef03b61bf0
    md5: 84eb2acae0fc5594f3d81f2db86613f1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2e774a2d7d7ae4850008b0fe3f0ad0b3
    md5: 4dc8cbf3b94a29a14aebf1cef22df10e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_sbc.res.nc
  hashes:
    binhash: eece8aba216cfa8b08adf0b896f58b70
    md5: beff9e998033cd947cdc75724336fe24
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5de660ee7a882a8c57bd264d4c0631d0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_solo.res
  hashes:
    binhash: 586895b018bb6510249aaf068c58ddb8
    md5: 65249c66b43ad1eda5395a02bd54585b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: db7ba04b220508d440a2b3fa58e4c081
    md5: a74154bef0c7dca864169f293271636a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 06ecd828f953a6996f86321d4442115c
    md5: 89f6174d6a545902b78690cbe10159f6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_tracer.res
  hashes:
    binhash: 9f07ec97cb82a1591763ffac0c4dc240
    md5: 0f2dbf5699fd1a142e66e36114b600ac
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 33ff7e9688b1602f74d0348738674f8d
    md5: e5c7bbf4cd2a712b52aa8fb0838153d6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 79f2c8c788fb33247fb809e8af5a7139
    md5: 4da1e15c15603416c68254c5d8f8964b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 06ca67c60ade857cd3f816a61bae874d
    md5: ba5c3efec85b6a00960071c3bc61a419
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart341/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0ea63174889c8b83b6f2938ddfa19c63
    md5: 9e831cc625a2427386ce2fc4a57743e6
