format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/atmosphere/restart_dump.astart
  hashes:
    binhash: 3a62a4ebf0ec95bb66b93b74d2529a1f
    md5: ec22d9caaa3c9cfedc7d4e660748ee1c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/atmosphere/um.res.yaml
  hashes:
    binhash: 4ad552c3d137a5a278948cb00bca5e86
    md5: 2f1f47d50854b994c784e24c072bd89b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/coupler/a2i.nc
  hashes:
    binhash: 0bfb9a49cd6380f0546b8fb13ce8d2c9
    md5: 1b895809018d42e08f14a8e63a135cf6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/coupler/i2a.nc
  hashes:
    binhash: a969d409c869124f9917db6d8bba46f3
    md5: 2a2fc9f5d1fc15b8cf8924d2fb6e591c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/coupler/o2i.nc
  hashes:
    binhash: 183df4f2764ee0c6e779490b0b1080c3
    md5: 9e4cb26a04b8d6dc4b9a42be786702e5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ice/cice_in.nml
  hashes:
    binhash: 8f078f59ed7f8502efaf278d2c0ed762
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ice/ice.restart_file
  hashes:
    binhash: afd6ae9fbee8b9748dc967435af6b1a0
    md5: 4abb5e276c3c0a3a1d5ae416002054bb
work/ice/RESTART/iced.1769-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ice/iced.1769-01-01-00000.nc
  hashes:
    binhash: 9201f2c9dd4246440d5fe65fa1aa106d
    md5: b9314b65306a96589442c914bcd0776d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ice/mice.nc
  hashes:
    binhash: d658bdd2217bd33429621171400648a2
    md5: 407043dbfa2af1cc42e5ebb243ab2794
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_age.res.nc
  hashes:
    binhash: 8f23c7dd649496c1e4100df70e7fff02
    md5: f10d2d6d4a41383b5867a68c5b8bf9ee
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7a31ce05e7314755a245c821b7af9990
    md5: 93fcbd4edc04555e722fa2381b8c6b54
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2c54a996c674472f38dc1d9cedaa2ba7
    md5: 9a036bf0bc4ad922179f187050612a21
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_density.res.nc
  hashes:
    binhash: 3b141e820ce797b51a3245469efdae42
    md5: 10ce6c9115b64748000a50129f135bc4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d37defc34f8c4b5fa8cf40cb68e066b4
    md5: aed37271137817a984e6929fecba799d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5d2ce72c211a081caca00fd2c056dd12
    md5: 2957a1ee033fb4e70195934fac6d6e66
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ea501b7b0a2d3d988206277a6dc46f5c
    md5: 3b1c8a6271b879b47ff0de672df5dd9e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ab1b225f8b21d6ce8ec6194e117720c3
    md5: ff96143fe18b6742ba2cd30137f5fd38
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 960d1f45eddb8efed5a15cf5071cdacc
    md5: 86fa630a6bccf3a91f77e2756de603a2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a266515fc14e64918049135ba574d9a5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_solo.res
  hashes:
    binhash: 9f7e8f898938070ab1203971ef170468
    md5: aede1e0d9264fe5a4fd2b0e886af5be9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 581952673f25c5e64bcc5a3bae538f22
    md5: 785f0c649f7640a2099b4773ea92b668
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 914f661fb1daca8ce8ed17591b71fdd9
    md5: 3a94166303b8462e99f54006ab341588
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_tracer.res
  hashes:
    binhash: 0f96857105faec1092fd7a4d6b185016
    md5: 929e7bdff79c489d02b1ced2f259044c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cd1cbf13abd05a39951d6331ec9b7883
    md5: c336d59027e6bfc04fd8e47702b4a2e8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4570d75e84203103d12143423e16e2c5
    md5: 426d025d40abcd846ab3c83754f9bbc6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9b5f490b2844a3eca7e516148e71708a
    md5: 8dfb34364a21a4e9967ab84075d74dad
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart324/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 554fa53ec0e23039b577b2eaa54341af
    md5: dc96d7315ce8db8222702e1f9b595cd1
