format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/atmosphere/restart_dump.astart
  hashes:
    binhash: 1ed88f63c693bd7437ce3120bf50f755
    md5: b125736eacbc47503c713e5d577939bf
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/atmosphere/um.res.yaml
  hashes:
    binhash: 10bdfbbf63c1c7431db41d93329b76a3
    md5: 8a4b13ab5507485d5b962416f11a48e9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/coupler/a2i.nc
  hashes:
    binhash: 284fe37914933713e7f01b43c1625945
    md5: 432141dbdccb5c34bf366222fea4f8da
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/coupler/i2a.nc
  hashes:
    binhash: a8a3eb56a46c6c6f02bbfddb0a876d58
    md5: 3ce1e5fc7990e7b3dfc2d06eb7448cf7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/coupler/o2i.nc
  hashes:
    binhash: 37600910c4ad763f536e65cda5f6d1d2
    md5: f244cecd835344ef24ecd285bdac4e93
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ice/cice_in.nml
  hashes:
    binhash: 9d3e1e9d3930fc87e0059b99636d0519
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ice/ice.restart_file
  hashes:
    binhash: f0a53ce788185be1275e27e8c95d899a
    md5: 6ce5749c230c2b255c22e7b7bbb09ea3
work/ice/RESTART/iced.1149-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ice/iced.1149-01-01-00000.nc
  hashes:
    binhash: 32c19eb03d8c095559fca4936f36cc87
    md5: 2b4b0a45d8b541781da2cc2fe0a7b943
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ice/mice.nc
  hashes:
    binhash: 78f86fb739359891a21c36ebd06085f9
    md5: 77e4a19280b4d8b1f28b9b863acffcc8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_age.res.nc
  hashes:
    binhash: 4f6a9ec21167b5e369074738496c213a
    md5: faf86e7165b4c03682250bf1410ac87c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ca4b88300a5a0c2e762a880c51ca4a1f
    md5: 8f6f5cf1fc550c661ac70a291240fd87
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1891522bfd3b573632f8c2217e8dcabf
    md5: 377770308cb85729afbffbba1fe6d345
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_density.res.nc
  hashes:
    binhash: 86de1f24885e963555ae603babfef6bc
    md5: 90265a35386238639403b58bc563de65
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5efa167d422f9cb148815f12464bc065
    md5: 0b87b7ea3e9f1dbb7b43ed864a0eb8d6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 215eec394a7e8302c5d1897b6053080b
    md5: 085311869acc7c2a6ffecb5394b728c6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aebf51a8a2d48eef19cda69fecfeddf0
    md5: 86db8e82f827fe64c0b8af4e4d46e3eb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 845047d6b11c1809334fe32fb784b79d
    md5: 41c22d4cc806bb1c2c217fedb21ac9c0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 64cf6ce6c1976dfdd3b688303989bde4
    md5: dc10cc8b38d8daecf4919e460256ed7e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4873cf8e52d08c72ceb65d7bc56f6117
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_solo.res
  hashes:
    binhash: 40a8ac5db8f2da26926520bacc699583
    md5: 85ed511cceebbb87340d00335d2400b3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3127b9784876a04d72e7150d878e5e56
    md5: 69ff28a7eed314afffdb4f5aef0a8f40
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2d1b15f5899ee1675a6b7eab04c8e1ba
    md5: 765629bca535cb8a59ce31f679fb38dc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_tracer.res
  hashes:
    binhash: 1431760fd1d227008cd295a7ae3c244d
    md5: 6d943d0030be4324d4df405d92004be9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 68eaf682f26dcc31dea940ca34a29fdd
    md5: fe2f18b5c726c78cd6d33cafad00cb1d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f839b0036b71e3653409bf89df43b8a0
    md5: 548ec99045fc6bc9da1a1705dcae06bb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 51c1eb1111632ddccf8b84f4655aedfb
    md5: 501271926ee1a175f76a4ba041cef146
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart265/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e8cdb97e91036e25380afda69a8ed40f
    md5: 8161601bab880c9d89db5cdea03ab88d
