format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/atmosphere/restart_dump.astart
  hashes:
    binhash: 71f28cb77ca52495bad6447b3d999928
    md5: 0c40af64ed5f8a3d01cab0e34a504c19
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/atmosphere/um.res.yaml
  hashes:
    binhash: 2347b514adb424238b213cc43ad2a27b
    md5: 11af8383fdb19513c00f0734745766a8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/coupler/a2i.nc
  hashes:
    binhash: 4d213653e1eac346b166d768b63a5872
    md5: 0a747f128e02cb73c4a03aa27eb82ae4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/coupler/i2a.nc
  hashes:
    binhash: df1aa7e104d15943dab4fa9638b02c19
    md5: 167a8b26ea9de92d9c28db7948e6de88
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/coupler/o2i.nc
  hashes:
    binhash: abcf8440418c7f93936ef4a5034d937c
    md5: 3d191ddd7e4270b37b2163b7a7d20969
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ice/cice_in.nml
  hashes:
    binhash: 41e49c4925d29002c940486ca023d971
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ice/ice.restart_file
  hashes:
    binhash: 0978759ae4f6a5505982097a2a653a10
    md5: a38c4ebb565194c08faad70e3c6dd501
work/ice/RESTART/iced.1293-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ice/iced.1293-01-01-00000.nc
  hashes:
    binhash: 8664ef327b2b8d0efba7e331cc147cee
    md5: 3c28d52aae10663c291fc34194f9bc99
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ice/mice.nc
  hashes:
    binhash: 404ea54646421367683f4c3fc407f448
    md5: 0ce1b9afdf10d349fb5a24f34bc99429
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_age.res.nc
  hashes:
    binhash: 83ac2d3b7b8bf7d2eb86ca4c92d362ca
    md5: 1bff535030bc23de6283a46bf21f65f5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 29909e5e37ce869d50f981db1f413188
    md5: 9b6d27101ae45fa08be0f248a3c9c29d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1cc7f6fa38f6c15d772dd0f990c10da7
    md5: fa51d9cba65bc12c08231700f3ce26ed
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_density.res.nc
  hashes:
    binhash: 1585663af473205e72f62aa926dc083a
    md5: a3048609b9cdc8694dd9f26e94fff70e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c1ffac9d19a478b385b3aaa0d22cf4ae
    md5: 4fa4810c323692e044e2c5af890495ff
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 76916966be43b6ea08580e083298e30d
    md5: 43aa13c158e8e3ce9e9666100cd307d2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cb9706e99ae4ac3ef3e3a2c8d39d47e4
    md5: cd9a1b8196aea9fe5fe54d3c8483abad
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d5e5a0809b153211a76502c40442ba75
    md5: 4a8b06d36119399a01076635d8794c72
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f0baecaf81a568ea9f711448ffdee991
    md5: 15479b4c106f8d0056190bcc26e12fb9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: daa00585906ca583883de92ec8716cae
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_solo.res
  hashes:
    binhash: d6649485f9390f0fa0750449773aca06
    md5: 4cbf48af127ca49950b0f746ebddba12
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0de75e5f5cc4f0906764a7f210cd363f
    md5: 762b0b5e819df088a2115772d97929b1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bb7946caf47d4b690515afdedc641e7f
    md5: 37f0fee283841f5adeb5fff15fb5095a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_tracer.res
  hashes:
    binhash: 16d0eb9b9279d7beb34ba11550b4cc5a
    md5: 26b4bf3b63e288b0fb39634992f7bc43
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 702c51fed586593c8a85f08ccb37d220
    md5: 27356be276f3e924d38c7e296b12b665
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e7d6a67a4ea4599e4c24f95a91041703
    md5: bcc1d394bdbce422f9e0c5f0f256c9e5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5ef85a836f55d9e76ca4d500e7ca16dd
    md5: 21c0973a7b357c3d2455d6559c7e83e4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart409/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 840db4a4ac0d551e9f2acab094377b35
    md5: 42b1de5753718a7fef90e5587d6864d5
