format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/atmosphere/restart_dump.astart
  hashes:
    binhash: 8408bfc3847f613d7de39e69371fce5f
    md5: cf833510115162a11cc3ec4c09fbf391
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/atmosphere/um.res.yaml
  hashes:
    binhash: 89f7a9788079ff77be70a04f77461573
    md5: 44db1243b2ce471a7ef53d3dd93ab0a8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/coupler/a2i.nc
  hashes:
    binhash: e521bf13f05676bb96f36f22c56a56a8
    md5: b77cd6d7228eb2f3e75cc6501dde7c1b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/coupler/i2a.nc
  hashes:
    binhash: 157273a699da0cc6f48a52c58569276f
    md5: 09593d64f8d1da3dfe1ad5ed7a391e38
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/coupler/o2i.nc
  hashes:
    binhash: 7abfb8274d87a1fed73e0f5794360fef
    md5: 3ddeb43ddf1e7c85cbddbf80853639a4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ice/cice_in.nml
  hashes:
    binhash: 552019bf695366a543aa050ae62f3880
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ice/ice.restart_file
  hashes:
    binhash: 53cd48106fdb5b2fb3e9500133620f20
    md5: caa3ae260935373879c611c94136e172
work/ice/RESTART/iced.0921-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ice/iced.0921-01-01-00000.nc
  hashes:
    binhash: efe5df691fc1a952cd15b382f14e91fb
    md5: 6e962e61aaabae2fbba113d133967e00
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ice/mice.nc
  hashes:
    binhash: b824adea93b61855ff2ad3f7ebede78d
    md5: 445d502c2a54b1b8ff5f42edeff0c9ad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_age.res.nc
  hashes:
    binhash: 4017ce6b939f60bedb3e59e399ef0209
    md5: 375c80dbdc1d4fa24d009a8c5babe516
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7bd58263c986503c15283b8fa8ca256e
    md5: 0ceac099415b959d89067ff966c8efe5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bd66611b4b4ca3326d72a1473a4cb739
    md5: 24af7173ca7aa0e33b7b8a08ce57fae9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_density.res.nc
  hashes:
    binhash: ce139bfefe9af8a969f49e2f13cd24c1
    md5: e03839639cdd00c59a32b40d74c11370
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ceb949cd83069b58ff1b9afcd8d83025
    md5: 804fa3407a23d2543d105bc408b90228
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9278c5b5f4f6246e8f500bb88227d45d
    md5: b8bdf72270d309d694805cb08564413a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9f58974435dc819519a2473157117657
    md5: a0a045a32cc04c25049b5dfb2060267b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ca3499aecdf4ee3f53d9fd698fb6a69c
    md5: 77eadfdff9379d5e867ec8ffb8f9527e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 289ad07f1ec638a04cae3ed8dba29b7c
    md5: e9e35bab8749f9410a97a8005156f6a1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4aab29b8104e6c3c3f3f472d51c6dc64
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_solo.res
  hashes:
    binhash: bdd5071cfe6f51af38a33788df82d65a
    md5: 781f377a62f283a15cbf9ff1e455e8bf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 67b2523af275100a9208d843fba13370
    md5: e637ce23a5c11b2e38c326ffe5c0f761
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c0c93ddfd150075fd3a2db9810ce9776
    md5: 816a86a1f2eca027f98f6c2664059678
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_tracer.res
  hashes:
    binhash: 22a85d309dd975e0f9ddc2ac82c4bb34
    md5: fda89853112f5d66d2d1c00d7bb37a96
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4233599df84378f7d31b9a849c00cfa6
    md5: 4bc52a85d3e965d0f5d8cfcf5738a01b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fb85afb6bc60190b64be0b2f76e9598c
    md5: 01b5d4506fff336d3004d35add064120
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 36956fc55dc053e80763187cd3792fca
    md5: ffb97b8b545b4b1c1f8b59026222cc9f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart367/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 50aa61c0555a87713ed8de77af9e1bf1
    md5: 57233eec1b21a5b088a0ee84b8a4973d
