format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/atmosphere/restart_dump.astart
  hashes:
    binhash: 9cdb54ca2a0a19e3cf79b0d8c6e9f180
    md5: dfcd583f9472883991c30069c678cb75
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/atmosphere/um.res.yaml
  hashes:
    binhash: 6d61942597ffa1bbcf582a6c64cc1e7e
    md5: ccd30c64b4814f0fb9e44e4000041a26
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/coupler/a2i.nc
  hashes:
    binhash: 87d1f5903052135f844284bf0d3f1171
    md5: f99713341f89b735b74c32253e6113b3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/coupler/i2a.nc
  hashes:
    binhash: a3894a5a87b87115e2b2d341078ac119
    md5: 0a278bb663e3560f3b5d4546ea84f8d3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/coupler/o2i.nc
  hashes:
    binhash: 047b7ed1fb50cecfae67d907281d6881
    md5: 70291eaf6dd002f644f5c3000701ca44
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ice/cice_in.nml
  hashes:
    binhash: af9f5c3132baf1ca8b6d0301bb6a1f31
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ice/ice.restart_file
  hashes:
    binhash: f8eccaf17eb114d0e1601b82c772373f
    md5: 97021905cf054fc9dfe4c04ab44443a3
work/ice/RESTART/iced.1297-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ice/iced.1297-01-01-00000.nc
  hashes:
    binhash: cf942f69319a5ae9b7d87588ffd22f15
    md5: 30ddb6602518bc5ccec0fea3ac8d16eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ice/mice.nc
  hashes:
    binhash: cb39df119bc0550fa39c7946af2773ad
    md5: dc7e0400e7ec5af7ab34de4e3c5d4b04
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_age.res.nc
  hashes:
    binhash: 65b789f5f67aab7254e61cd9650c2a82
    md5: 11bd4448af3bcbe7288664df582c2505
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d92df78a2f2326c4ad2fed805f2d5165
    md5: 781ebdf6742f9ed95062f9f0bb7f8ad3
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7bf3a1de9df29b3e36d82812d7ec8f5a
    md5: e4a51314bd41a092b5e6244975d9ccf6
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_density.res.nc
  hashes:
    binhash: 2c13e5fba3177fe23aa57f37018b20a1
    md5: 39215cc583dcfc46d584f4e8a5a2d0c4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6e0b1dcf6bfed0a14af1d12fe1b6af3a
    md5: 5201eb0b127d96a844a3ee642610ae37
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 47b9c55c3066571f20988d2539c2d637
    md5: 7ae9f046d60f3d439c2006b2c0b4bd79
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 355a2a335578518bf313312a58f5de5c
    md5: 85b3ffb1b33652196fecfc28caf48a24
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cd2f68533dd0dc4df1c7c187af7d7d95
    md5: 5ac3f4ea297953c4df2293cc09969c05
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 16f3957b9dc2ebe2acc9fdd9491b880f
    md5: e96608bf4fc48794b0577d079c13a387
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 20dca6abd2507a7762be20381e00dd2a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_solo.res
  hashes:
    binhash: c1c7095b97af010e1212557b364d8ad7
    md5: 3f750232bb57c66fb534d0ea2aee26c6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 92e4cd5e14e57b03523f0aa4aea70a85
    md5: 70527a00ef40b325b1eb4158a48d22e3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 38ff0505bfab098c92bfefac1b76ecc8
    md5: 8d7130284fdb514b576042c7d6341dc9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_tracer.res
  hashes:
    binhash: d088ad14b4286604699112bbc48d4aaa
    md5: 35fb1241bc13b67830c61189c20264db
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2a7fb25434f77f3820ea52ea101e7d12
    md5: 528211b8077d317a055fa569613b95ab
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bdc23795abc6a028e299ef7141a46289
    md5: 1a56f3d6888dbe437d346f8c2414f634
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5a61ebe1d1d1f2954552554321df7069
    md5: 2c18bc7c72176b24827a122a51767ca4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart413/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 62131c1c596e56f6a06eeb4baece7cad
    md5: e557ba4a2804e28f76ed5b5f97a115fa
