format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/atmosphere/restart_dump.astart
  hashes:
    binhash: 1bdb55d695137eca5d1a47f070ad4da9
    md5: df0317237f583d0af5d80c98b8fdf103
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/atmosphere/um.res.yaml
  hashes:
    binhash: 440b2fb97d2b652743564afebaf47be7
    md5: a1e8dd91a35230c89bfda51ff25db929
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/coupler/a2i.nc
  hashes:
    binhash: 358e37ad7744288069b99b58b24a04ed
    md5: 90d9828300ca3acd5d427d515b2de2e7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/coupler/i2a.nc
  hashes:
    binhash: c95c17c43e14d8f128591a30d6124152
    md5: 465a082127e174809905df33df998985
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/coupler/o2i.nc
  hashes:
    binhash: 65d8937d770a76b1f6ead344cfc6655b
    md5: 4566d7adf7710c7d5dceacd48a5f92c8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ice/cice_in.nml
  hashes:
    binhash: edb6af1705eba8ab7646c144ab065f8b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ice/ice.restart_file
  hashes:
    binhash: 533e84227e3cacdbc877382023932f2b
    md5: db8f31408b503fe25e3fc06ae0aab72e
work/ice/RESTART/iced.1181-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ice/iced.1181-01-01-00000.nc
  hashes:
    binhash: 0dc9e263a9132799c501365906d592aa
    md5: d7c2ad2376800ec44396a3eefc6a67a2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ice/mice.nc
  hashes:
    binhash: 2b474319c9e85fbd4940dd5b5f8f0f78
    md5: 6a7027dbb2cf3e9285a7fff70e4a6d60
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_age.res.nc
  hashes:
    binhash: d0b1ab17f6795fd50c2cd9b3fe2a37d3
    md5: 8efc3230f3cc89c1e8bc0ab6a5396813
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 89234c21afb104d659a0af522ca15faa
    md5: 1dee60dfa50cea43a1f1f15d9d9b25ba
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1fbb18c16978a39045c29e37072bd4b0
    md5: 1326a8cfd89611a077057cebabca4487
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_density.res.nc
  hashes:
    binhash: c3ca039c27ec162cacf8a13982470d23
    md5: a821836a231527f1f4c4f2f66831ecf3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 691cc17ea41bfcaa5582b3f39e49d196
    md5: 973814ae8a878028686fa07db1c7c203
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9ad7df7894b79eec78d0162434e42238
    md5: 42b29b8e01f7cd60bdc22c8969d00c03
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5b31527b8c9b745e32906d9c606621e6
    md5: a08848defa081624d6cf4cdee1fccf8f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3536f28eaf89e69de9b214f9ff3a7cf3
    md5: 37eca4c119895769ecd0700fe19d8eec
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c9f3a4069ce4955b0a1744463b384e90
    md5: 6bfb89b487e31f40285149fbfebb7157
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f4219de8fab3b6339c2204e0e4e8b4d4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_solo.res
  hashes:
    binhash: 5b8ee3693605ff26afa57da88b6f1a9f
    md5: 96504201a0bd102ddc6a601c2a0f20f6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c35e3ee2d2c35e3cb2e9f37d64cf4fe6
    md5: 74a48692552b433c2fbd739a688fa988
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_thickness.res.nc
  hashes:
    binhash: be84cf6d347a69f617d9d225673cf78c
    md5: 87c673e4a2446ee11229858cdabae430
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_tracer.res
  hashes:
    binhash: 8a399c7da32aef1827f02b2d46fea47b
    md5: b8a739d7b0f407d500d46c18042b84d3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c231f148589d9d386a0dc18c9d277338
    md5: 02668a8c4d32b5b79c10c97716a57037
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fc3b5f78e37c6f499e94d3e110278803
    md5: 757709a3b5d305dc051edda9c70e5927
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 22e1b71dcc9b7cf61c83fb51a8f8ab94
    md5: defffb29853da3ccb5fd902a266d2dc4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart297/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: de6356c43059face4fa9aa06e1daf455
    md5: c4bac2c14eb059717fd398f0d5b58296
