format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/atmosphere/restart_dump.astart
  hashes:
    binhash: 50debfaa88904a3add8ab9b8f03b27de
    md5: 8a8812b008013d8794b173f09fb4e7e6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/atmosphere/um.res.yaml
  hashes:
    binhash: fe2990a3cb14412706206b009076bc8a
    md5: 91c343ea018569420a7ec56785d93436
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/coupler/a2i.nc
  hashes:
    binhash: eaf731fe0aec8fe57a7908587c7fd134
    md5: 1ef4f236676f37cd29536f629a754bbc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/coupler/i2a.nc
  hashes:
    binhash: 1eb2d29ec9ffb18eb4724b8d748fcd92
    md5: 009bcd477a31bd2d2e8b31c19b3b305d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/coupler/o2i.nc
  hashes:
    binhash: 8a0f9e998720753561cdfb1365f29e00
    md5: af3dd4387bb6f1c4928ba69616d76ef9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ice/cice_in.nml
  hashes:
    binhash: 12f57a4b44f87760fb8b156a058f1402
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ice/ice.restart_file
  hashes:
    binhash: 12d105d3b221946f2de4b8cbd48be3be
    md5: c58f750341130a0a2f49de3174ea0493
work/ice/RESTART/iced.1750-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ice/iced.1750-01-01-00000.nc
  hashes:
    binhash: 6e20da7165a80808c9d696ead7c7b79e
    md5: 33f2c71d6f4ac3c4e63c9afa83f609ea
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ice/mice.nc
  hashes:
    binhash: 9433603ba979a18583265f7214f862b2
    md5: bd27b70c6fbbd80c8a35cc73a22ca1ba
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_age.res.nc
  hashes:
    binhash: e1d3284d1cef354ba4307337a695dd81
    md5: a756d195ba84bb468078a605ace62496
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 03fe11592b81c395122c407a651f7d49
    md5: 3990bb5fe5bd759c167c3f01306a45bf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 00dce38a7e02d0cd1dc2ba7dc73133de
    md5: 9ff787094305185e4f42501dc7e35877
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_density.res.nc
  hashes:
    binhash: 45a7f1f8ab5b02bb2e90c3531cbe6748
    md5: d18f0505ed3f10d2a44ed00452052245
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b6173c878655d8184d57ecca26996bbd
    md5: 3fe4b249fafe9cf69e1b70d0a5ac703c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ffbc22fbb2ea775e1fd6ee4dd81b2b57
    md5: 2a212a187c22a27c450f5645d89cd619
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 35a2ce9e79b87d33ca8a4e44875d8888
    md5: 3aeb20b5869bad806d68d82fb8e0ec61
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fd37e55f708afeaf4bc9a1e33919ac10
    md5: 0443739bd405a98dc7cf43c2815964e7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c3c9dae6c5ed92885706e06eaa380f59
    md5: e4791d59f7fe71bdc92e5b4155d930f0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d1df6bb420991092cff74f7bd23319fb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_solo.res
  hashes:
    binhash: 80e730c3617bd01ff90dcfd65783e74a
    md5: 10afc7b92cfc906d80bd8accfd848b03
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8eab092132845c2f7051591c55615151
    md5: 4b90428c7ae9e592b53eec03ee4d2c68
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 36c60162acaa4888bb294df7ea1296af
    md5: c287786838a7a006e94c9e0b28708ab2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_tracer.res
  hashes:
    binhash: 12534d36a9cbcdcf2fc86c5377e50a1a
    md5: 68123c6c4d96726d9eb6453d167725b5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2bc1bc1d4181883e150643b4ff003cbe
    md5: e6ee1f99f97832754728755e054e8eea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d9432d3157c7af6f1887118547c30069
    md5: 5b393f0dc220a64780335d575a8630b4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1ae96c05060091cfcfa48c8534357ac4
    md5: 176643cb9b347a555efddacb685d232a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart305/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 50732ee01e66a18c7a27c7f89bd6776c
    md5: cee410a63e5e243382ae2dcd95e8dc33
