format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/atmosphere/restart_dump.astart
  hashes:
    binhash: baf22df6424f8b3a4a34171065851e5a
    md5: fc9fd57466598ef24f5b9d7f0e54f8cc
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/atmosphere/um.res.yaml
  hashes:
    binhash: 8a12b0ad0cf83a0f05618adb93af4cd9
    md5: d633739fecd0525af09d6a4e244a7962
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/coupler/a2i.nc
  hashes:
    binhash: de8a536c4eb172457c8483355508dfa5
    md5: 9741fff6354147ca5fb2b08b0c650181
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/coupler/i2a.nc
  hashes:
    binhash: cd4a74d0d86eacc95aec0302944cefef
    md5: 923a753bdae8e51a71ecf0cf0088e348
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/coupler/o2i.nc
  hashes:
    binhash: 47544d4f0217a689cf8059bba0f4eec4
    md5: ad332a161508e83fb0e68a5417bc528e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ice/cice_in.nml
  hashes:
    binhash: 7871edb8d5160e773b875988b1ead2fb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ice/ice.restart_file
  hashes:
    binhash: 46feec92363475b5cae8f4e547e9d9b6
    md5: 496f0f08aa9bde9f8c2bb7150d5d30ef
work/ice/RESTART/iced.0992-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ice/iced.0992-01-01-00000.nc
  hashes:
    binhash: fd3226df895d3eca28ffcb2e6feaec97
    md5: f76322ffaa0a20a45d2c8c134ae0af54
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ice/mice.nc
  hashes:
    binhash: 31f6e67295659f6d88387610e9528c9b
    md5: cd0f336dd1d87c7ffe12dcb6c8429cc2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_age.res.nc
  hashes:
    binhash: 940fe017497a8fa52682f441646a02d2
    md5: c10d0adde88e7fb4f1553f3eed51384e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2bb703fbceffa2f7c0c5c28a0e30d551
    md5: 6df762fdf0c4f1fd3f02efd1b32c1ad0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 525544fad88a020532fca80db98aa5bb
    md5: f49843872516fb24ee9d835681d50cf7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_density.res.nc
  hashes:
    binhash: bc3d6d99a578afd64062daa977267179
    md5: 0a4c944af14481f387980e017f983103
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cf752b20db4d1107d39d96ec5698db35
    md5: b36693e227ddaa5f5d9c09a0ecc41ad8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 947e8428c456e199af47a4867215308c
    md5: 14b1a4e064f6378ce6ad2726930e48cc
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e11b53b02c23eb8ce175d8b35c7710f
    md5: 9e9ddf328660b935366f5945db66e095
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8d376f23bc64396fb509ff7a922bcc72
    md5: c06472c4be3e23e1082b3243dd3c1463
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a03a8441acf664c89fe7830278c79020
    md5: b8dfca5c39cb3da6257f139f635c0e01
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ee14a7f638d8216a95a7e473fb0d1efe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_solo.res
  hashes:
    binhash: b2686bcc3d65765a7d80e1e0444741c2
    md5: 54b7c6b4ecd1125138778ee03b93bea2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 350408e60fd7cf7c4845ab9ec0f82b2f
    md5: f8ab684e080a474b49ce0d6fb58a63e5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f238a93b5f4bd098d7b90e0093308ff9
    md5: 3ce0d19dcded511e7ca83f4dc1e18f9e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_tracer.res
  hashes:
    binhash: da0c11a3bc4f0de0bec40afbe4a27e02
    md5: a1ce338f5ca72f818c94f87644a95028
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 57e7f1c528fd89cae0641027b153016d
    md5: 19001512bd64bcd5a7376bf0d833c111
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 381be241212f0977323fc001d8b895ef
    md5: 6fe647d92793e767a5eaf0f36da6cdf3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 63a1089c1b751e455876c032d1c07946
    md5: 23f882e77b10331eb94dcacf296ae570
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart438/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 645e8f5ea26b09810919cc8e9a65d3e6
    md5: 3304a20709ae64f762fe9183aedeb46d
