format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/atmosphere/restart_dump.astart
  hashes:
    binhash: fa88521a61d818314d643111b05fb8be
    md5: 94f7f36648f2c3b0092ad894b2de022f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/atmosphere/um.res.yaml
  hashes:
    binhash: 3c9c1bb1791ed9626b76a74d30290037
    md5: d5d4d574bf5a42fc17516bb5a0800dbc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/coupler/a2i.nc
  hashes:
    binhash: 7ffa37ddc4cec877bd525d9188a3f0fa
    md5: 86d181603e96e1836372cfb192436681
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/coupler/i2a.nc
  hashes:
    binhash: 3b63aab72a1fb34e5f5edca0c28a8790
    md5: 96179062307fa47c5a83f21732e2974d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/coupler/o2i.nc
  hashes:
    binhash: 1f3e17ba7be7f0cbee34308903668822
    md5: b29459476daf6cc6699ded755c803d64
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ice/cice_in.nml
  hashes:
    binhash: 6f32ce4bfc5392fc4fd86918472b41d5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ice/ice.restart_file
  hashes:
    binhash: fcbd9c70ff8db5d7406224500536b396
    md5: a93d8463f000dca47eef740795489fba
work/ice/RESTART/iced.1228-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ice/iced.1228-01-01-00000.nc
  hashes:
    binhash: b652327de4d587b84bb39d0aefcebc75
    md5: fb8f7a7db51079e884b16f768bc7d9c6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ice/mice.nc
  hashes:
    binhash: 499f445be2fb83baa39de0514ce14196
    md5: e3da8cb5b315e7f44272cd30e03a8f69
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_age.res.nc
  hashes:
    binhash: 9aa5d0703d916dc6e639a3bc642173bc
    md5: 6970d15a6de2b95d1853993ed0cae98a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9bc1e03cde00427d1f73b18553226117
    md5: d2e955e1466cac50de542d408b099a5c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4da22cc22fae46e903bef0268c32bb0b
    md5: 424210cab99914e85eb3d68418538088
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_density.res.nc
  hashes:
    binhash: 40f782c3bbe79d96fc2421133c2ef7c6
    md5: 7dad0b003326bd8d6590921804878ee9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 85eeda19858cf5ca9310fb60b7663c73
    md5: 108c6d16b4476d33a9f417191966ed74
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 559b029c201cbff2b636331d0d97684c
    md5: 109e9b07dc219dea0835799ef25f64bb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 608fbc2df27e2c78bda69af303a21d16
    md5: 417f9573d60c7b00e580044318797567
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ceea7c8639715821c7a62d511b13906a
    md5: 15393e760260c75159f0ae7ea61af5c3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a9dc2e49c81f3842e18e148df8db3007
    md5: 48c05b191a3c2fddbbe5b8bd5d4d26c7
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 26f5041e2c0c228ff028d8a39b65e968
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_solo.res
  hashes:
    binhash: 72e9885e4b6272850e013fbc443b80a1
    md5: 4a291b6bda240f9d307f2e496df523f8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fe2b1a527e95ec309b466f3bd7a602f2
    md5: 324905a4daaaecd272ca0cd52ec7bc6e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 016cba3154b2180d99d36ea10063a57d
    md5: c337e14b190dc50e21be7b1170bb5720
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_tracer.res
  hashes:
    binhash: 2d7f9bc86cbbb7c87fe0cb63b67b36cb
    md5: 943b359512c478e0c9857150ccf267e8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 49be7389ce1a32c8c55d0d5906f71c5d
    md5: 30091a8043fc632d80088b023b5ec78d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 421087a0fe1493b398b2317c06a9af36
    md5: bc15ce01e5640a07231c8aded8c876b5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cc9d1523ca1a7b8b3fb204239dfaa210
    md5: cef5db6180185e523e519fb2a961d891
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart344/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7b836a2ae0d2cc107e5d7c6f53d5d4d5
    md5: 6c1e77a23a5bdfd5dcf46ab2405b8d91
