format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/atmosphere/restart_dump.astart
  hashes:
    binhash: 7743083752357e510c608c7f5c7b2cf5
    md5: f4d20bc0d53a316905e4511d9ed16397
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/atmosphere/um.res.yaml
  hashes:
    binhash: 1353bb62e4fba41d921e61658cff7556
    md5: 59ce59e1b227d681cbc73392112695e9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/coupler/a2i.nc
  hashes:
    binhash: f66a1350c1a7521221311a2c1d0b85e3
    md5: fd4a1189dcfd05ced363553cb4d27636
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/coupler/i2a.nc
  hashes:
    binhash: 7df12bb40d235f5c69b85507cfb8653e
    md5: d8ca52af059ae5e3b041123f85b8e51f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/coupler/o2i.nc
  hashes:
    binhash: 5e06ac5cede42e7f0bfd7b1f175e39bb
    md5: b866f0230cff37d39d168259a4650d1b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ice/cice_in.nml
  hashes:
    binhash: bac71b0b991c7662637e87cfe0d8d016
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ice/ice.restart_file
  hashes:
    binhash: 0d1ca2e6bd75cddc8568f0c90864f513
    md5: ae2d64bd6043cc0fc91e1f1ee9cbc9ae
work/ice/RESTART/iced.0962-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ice/iced.0962-01-01-00000.nc
  hashes:
    binhash: 802b86a9928ab8e73d592ed149303c6f
    md5: 173419cad20e0d6b73c020eb0bbfda7f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ice/mice.nc
  hashes:
    binhash: b461c163c0a179e975ba1ceab6552077
    md5: 144d729cf0f15f4bf410a89209097075
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_age.res.nc
  hashes:
    binhash: 4a729e4e8ba0d3ba54e445100a690194
    md5: 9bd82e2cfc2264b50c4768afb3ca0bb0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3a3be3f5d09351d9af1bc07cb7f3676a
    md5: c00b20619e6e8cf6f799dcd772887861
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 972c68b6c69e3d786e7f5c647793bbbe
    md5: de237b1bff87df67b9ebce65d1fbfc0b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_density.res.nc
  hashes:
    binhash: 78491f0965633795cf35033e98f1ed44
    md5: 6eee3375f6e6dd514197643d3ad99a3c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 09457b90be7fcab813288823424b243e
    md5: aa6b460402d2483cda808ea1e252a0b5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f642e42e5482c64a0a5d2b293bd9694d
    md5: 49272bf5ac145f9a02c1454b1b92e46c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 82e8803270899eb0cb09897089a4012c
    md5: 638c01438156cc604824fe229be10255
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6b78a646d9ac0a31c378d421c1b55387
    md5: 4f75339d673f2f34a135d3586d0a527e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ccbfb4fa56436c1deae6ec51233df971
    md5: 5c1412e22b334dd923703ece78151f3a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3f2b5a1c21220c9eaff478a2d453e529
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_solo.res
  hashes:
    binhash: f50bbf901ca0df4c729a0d132cf8e9bd
    md5: 009f9305d49fb7f9b6136f99bb10d388
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 69d6d9cc095813e6266264501f120b6e
    md5: 0576bb911c16e3281251a2ea63fa3c67
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c9bd57ab86e29a97b29976f68f18e025
    md5: 9a539f0de7963b211443699e3749380d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_tracer.res
  hashes:
    binhash: 3cb5fad63c83e0ab3a6c9540e0a1b8fe
    md5: 69c2ddce2135a9a87a538ea3f9788a9d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 16c6169d9d9e243ce55975be1cce50d1
    md5: a0ab7868f02b5e76cc5f310384d81f8a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dded5320b47dfce32e7d350bebeb0c6a
    md5: 944969a3a7e389812d01ee90946c8a46
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cf46d265b7966e6171bcf07a3d4fd00b
    md5: bc6befcefb7e854730101fc17d6ce650
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart408/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b41fb41b570444df619482013f30f34a
    md5: 8d9df6025e34ec9d91367cb2b08fbad8
