format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/atmosphere/restart_dump.astart
  hashes:
    binhash: 71fe14d874d1842cfd5f5185b31049f8
    md5: cf795c063b131606425256a8539db987
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/atmosphere/um.res.yaml
  hashes:
    binhash: 48b2aac30895a6e836d805014394b6bc
    md5: 1b1f0ddda67b6355fdbac4c085e11f15
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/coupler/a2i.nc
  hashes:
    binhash: b61bca583cbebc0bf5832c83b0d34612
    md5: 20950e4493adbb4d421a0a36b67c3cf7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/coupler/i2a.nc
  hashes:
    binhash: c4cb847ce72024f7a30a9d2453d88cef
    md5: 9be34d0b22e6dc278da255ebda502edc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/coupler/o2i.nc
  hashes:
    binhash: 3bdf2467e255a4dc5415875d0143315d
    md5: acfdbcc7dec43c3f93c981a603001ae2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ice/cice_in.nml
  hashes:
    binhash: bdfd8f3c2dfe3221efce29feec95e4fd
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ice/ice.restart_file
  hashes:
    binhash: 180e6f0338fda9923e22fe151a0f1384
    md5: 5c96cf4215bb34fc5fa247d4d243f836
work/ice/RESTART/iced.1810-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ice/iced.1810-01-01-00000.nc
  hashes:
    binhash: 2e56bcef28df7770e3477ac6bdf4ed7c
    md5: 7a12f92fff855252069e2f7d434ec84b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ice/mice.nc
  hashes:
    binhash: c19ba8dac4942f842a2bfea78bd0ccd4
    md5: 4fe239d736c7c8adaa224ba770c925dc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_age.res.nc
  hashes:
    binhash: b276f67e5ea942ea93391532187f6340
    md5: 19eaeb9b8d8a635cfe0298ce5760a58c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 195b00285fc7a4e01980ea5faef0240b
    md5: 8e38a85a880acdd489b06663eef4cb7c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cfb67fa9e76d9ee7ff4e83d797614c3a
    md5: a6f72235a45bc2cb16d918ffaf48d5d4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_density.res.nc
  hashes:
    binhash: aa0c15d1a580f2c71a6ce45f32b563d6
    md5: 5d68cc0c3421288fd8677afa9bd10821
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 11fa965da572ac50f1fcc276e58c067d
    md5: 992f031ce8e78faeaca05529db94c17e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f2b524c97a1d513a4aefed5ee5dc0c96
    md5: f537ad4ced568621128883bf5b68c26d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 11a4b6b99d68241a7154b471207e5351
    md5: 445aef994b68a0bc8038fa56ec4e293b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8db1a0ee5f77107caa48e287c772e1bd
    md5: 11dc5c12b9ed630e7874ad069d8de516
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f30f5e46ed364d3edfa885eb5d54c324
    md5: 3fd30324f7fd861facaea9e0d1cc91b5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 55ed144c61d435f1d7ed6f9d8fe4da8d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_solo.res
  hashes:
    binhash: 485e946d33989957fb44bc12ae17b7c5
    md5: e8ac4ebb6389afec4ccdea823453158a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a2cb0ff278e7d360cf95073bcea6818a
    md5: 5ecbca0fbb11dc6b691e3f0e00912806
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b210529bea515fe595d7678d04ce907
    md5: 46b9315c3c9c6e46514984315de17a5d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_tracer.res
  hashes:
    binhash: 91df36a6b0a77425396021d895ffb262
    md5: 7748df6bd608aaa7921b102adff77c01
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e3ba1540f65e4f7d1d7698021076ab1a
    md5: 252b90b5c3d28edb55dae4ffce170d90
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b9c556c1424304f4c6b230a93a7f66fb
    md5: 359b593637958001427c386b538b6db3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1d62a47077b0938fd8484c733df63aa4
    md5: 401101075a3df6347a282c4af9389b1f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart365/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f1238a07484ce7d34b552f1b5609738f
    md5: f292299e2689b7c35d1f7356cbd2a68c
