format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/atmosphere/restart_dump.astart
  hashes:
    binhash: b622c37640b43aa85cf6e59983d4048f
    md5: a13ba6769802b0ba1d738da277b96d07
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/atmosphere/um.res.yaml
  hashes:
    binhash: ece6a435c90e8a6931cafb7c0de48dd1
    md5: e63b32ead193a4dc087ca6f6d1bb57da
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/coupler/a2i.nc
  hashes:
    binhash: 5b031b0ae90a4c83ee64a423c8bbc4db
    md5: e59ff88cb1883dfe9c0a7e6268af340b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/coupler/i2a.nc
  hashes:
    binhash: 5807118bb14d722df555a372ef17fe69
    md5: df1c531e1b145c1533bae98dce6bcda3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/coupler/o2i.nc
  hashes:
    binhash: 682ed36c0354bdf77b96e1419934ae00
    md5: 408c97f6d7a67bb2ce9975e0e90ee76d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ice/cice_in.nml
  hashes:
    binhash: 4a8ff1147f6a0f969917b7b2ec0d7779
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ice/ice.restart_file
  hashes:
    binhash: 384b8735024975ed9fa9a00127718eb6
    md5: 626ac89dbfa83969968147154da4de9f
work/ice/RESTART/iced.1803-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ice/iced.1803-01-01-00000.nc
  hashes:
    binhash: 2719131ddbc4b130310326b40cee6f46
    md5: 90fbdd1bd55dc4133041aa4f2e31bfc3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ice/mice.nc
  hashes:
    binhash: 181e2088da3e96eeef716cb8a210a94a
    md5: 631f48df8fcdf8ba2e394f519a94285d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_age.res.nc
  hashes:
    binhash: 440ad1c07cfc9f53602087b64a5e17f8
    md5: 58766e5b37b4ee0cccf28c770f4b2678
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3c6e6c55919c8883ae76dabfd7651a15
    md5: 24f533a6aba735151f8da0bd2e758a31
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2da4d5faa120a668f4cdf8931e890601
    md5: 550c37d35d9244ba774a09edd63551fe
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_density.res.nc
  hashes:
    binhash: f601e4f161827e09feac73777d88a894
    md5: 27d6f994f6c237b04b17b49c017e46d7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1b80abdb41814bf7c82f50493241ce11
    md5: cbc86403a23acddfb78691150a269630
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ff1394277ad2031c0209c8299b7fcce1
    md5: ea8ae4bb9a157e941a09ef48a8363cf3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2bd92a8efa21118280e4798c904150f6
    md5: b0bd46c9aa3d3c78bb861ae6d653bc5d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f6fc0ba0fc771310fcd72beb06793d80
    md5: c0bc0250608186cb45b0cedd372ac92b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c0d41ce668668ea093fe434fe0a25278
    md5: 7cf4d1a255e017c4d63c70d80f5f5669
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: dcebfb2b171817157f6aa2374a7510e1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_solo.res
  hashes:
    binhash: bc2e440bbae32d48e086454d16eec97f
    md5: 9a2b001edaaa45e75c320feb254d0b4d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 94e76ff91ea82b885397233cb261948e
    md5: 5171ef45f991a37313f1890666ea9957
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 68f70eafb991e0a4d000b211f89e35ee
    md5: 264268c37079415bf1d3ed2ab354edbd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_tracer.res
  hashes:
    binhash: 136554d186096615adecaa8cd73864f1
    md5: 7e4cafd0c5eb46e7d55c3789c4e8a789
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4ac9fcfec6188ed783adad7648c0afd9
    md5: 49f73b8b89bb7ac9eb12bcf972723594
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0fa6dd95d91fa18d66fcf7deb87b13a4
    md5: b832d9f24540fee04c5be94846f5e82e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7b32d6a2a1c4aa1b37cf5100c2ecb684
    md5: c5c797b3c04f97f0d299d734618fd07d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart358/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8bfb111d4941f9172be1fc54465c1477
    md5: a0f03122e16e8888b4a2eb1891d579c8
