format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/atmosphere/restart_dump.astart
  hashes:
    binhash: 006b0d9088fe315527be4f72db100313
    md5: 70620215ef6acb69b57c6c7c5d46b522
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/atmosphere/um.res.yaml
  hashes:
    binhash: d0b849636d724c594f2cb40c009d9828
    md5: 6052b78673c3d0f26751fe846974ac23
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/coupler/a2i.nc
  hashes:
    binhash: 5c3a2c535fd816ed28d90f148bfa2310
    md5: 23791c7904edccc4a497ca60969b0252
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/coupler/i2a.nc
  hashes:
    binhash: efd0e80d290491cc0bac356af64c6aa9
    md5: 06266fdf16607ecdf2cd6cb6d81a1475
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/coupler/o2i.nc
  hashes:
    binhash: 8f9202828fac67664ab35eb75739dc72
    md5: cb48174fda2008f033b1c09590498c04
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ice/cice_in.nml
  hashes:
    binhash: f92681bc4b8885eccd446cec75dc7f21
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ice/ice.restart_file
  hashes:
    binhash: 0e9e38c91e63a5347df1f3deb129834a
    md5: 04334fd0025b065cec2a4b486a4b89db
work/ice/RESTART/iced.1772-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ice/iced.1772-01-01-00000.nc
  hashes:
    binhash: 4531a927bc62c9e438b270f809ea3b71
    md5: 3355385a86f38f27b2d050968708028a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ice/mice.nc
  hashes:
    binhash: 837e6f57f60405c19267f74ed8582d7e
    md5: f045705bfda4c67f28bc3ef7b025c1f7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_age.res.nc
  hashes:
    binhash: 96f839ae3528974f718bdc453bb7a100
    md5: 50029b4dba424662381f7567b592d4aa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5c53b722b8d06edb8bc6495f6edfd702
    md5: c903aaaae06a97f4ab8fccb84121211b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7a7e27cfc2c151463b9002371407f743
    md5: a0f8f955e83e50e0a8b17f0b0ada1fd5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_density.res.nc
  hashes:
    binhash: 2291ff6c393909e93dc1c522ca5c5d2b
    md5: 601811700740f89ed098198c98887f61
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5da60d2b60a54446db471ffd6fb1ee9e
    md5: 7529080dbcd3df3ded750adb1adfcec2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6acb1510badaa81655d0e349c46def65
    md5: ada2fd60b50095155996ac93be1255df
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d5cb5e64596f458582885f17deb10733
    md5: 4deb01d57443eecbf78034ca0d838b9d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 40d96a5af93bb4436536666fa2954308
    md5: 22311366c2300c3ec6614e1b35e6d5b7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_sbc.res.nc
  hashes:
    binhash: efcb7788c4603278f3e32c70f38fd414
    md5: eeefb9d86b75cc5d47a8d60d6444c5e5
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: aa9b0b2aa6fa66bee3b177822d97f34c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_solo.res
  hashes:
    binhash: 2f03b768edf994f587b9f51532ab0e8e
    md5: 034cff3c1ca3f45ddc6e65893b31c1bd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ca9e80c47904c2c1766e12a09b68c1a8
    md5: b074eb3f611546719a99281ed2113035
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5f9821310b210b161f51ec61ad132f19
    md5: b72910dc6e3c3354a2bdeed56c331219
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_tracer.res
  hashes:
    binhash: 1933860665b351b97d6de16ba5a82fb7
    md5: d0b5dbe55a4b04e9e437a07a6010c385
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 597e6afa43bdc38f7e0e40fb757c3492
    md5: 8cfa46e53d9783ab2e3696ea39a2abbd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 597e9e7ee913489ea514a7ffedcc8818
    md5: 4ab0ec48eb8ad7aee58184799e76415e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b6c76c0513a32cffbdd000b60cba9363
    md5: 5f134983f3561302a7a48f958fa98d0a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart327/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b8c7b4591e62990f338a850a5a3fd385
    md5: 53e5c4f287f2aa32ea88a9f636bc81b9
