format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/atmosphere/restart_dump.astart
  hashes:
    binhash: b0a661c97d68c389e0c69af67d7c30f9
    md5: dcb990554e3e4bbe0694adf92b4e731f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/atmosphere/um.res.yaml
  hashes:
    binhash: 0968430fb11c0cdc2a3374039132c1bc
    md5: f6630cac5cab394311587df81403beac
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/coupler/a2i.nc
  hashes:
    binhash: d5765962ab297bdc5d44afe6c3249f4d
    md5: d7547d95ec20ef145644d9af56c88c1d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/coupler/i2a.nc
  hashes:
    binhash: b091832eb543b5da46ff54cf9a41eb47
    md5: d7f13b42cd92e48e7b9edad82b1fd0d7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/coupler/o2i.nc
  hashes:
    binhash: 66db969b2a11e8b1e17f353408c8cebb
    md5: 132da404fc28a7a04a11bfda91e82c7f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ice/cice_in.nml
  hashes:
    binhash: 3b76f783420883c7a38c973a33c70aa1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ice/ice.restart_file
  hashes:
    binhash: 002ed4f80a85d1c5e4ef54b4e9105897
    md5: c334add9a35d3f83a977cc6fd2616d5b
work/ice/RESTART/iced.0863-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ice/iced.0863-01-01-00000.nc
  hashes:
    binhash: 7e09cb2eeff0ddd037e17fc493f40086
    md5: 6531495bf0ae8b36561a5d48c1733bcc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ice/mice.nc
  hashes:
    binhash: 283bf375b6cbad2198bd625f1380bb27
    md5: 1bccacdbcaed86f4b244abf5f6d13b39
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_age.res.nc
  hashes:
    binhash: f221e777b17d5c973d68dadfed6cef86
    md5: 33a7a73b6f9f5a1b303341b4ad0aea21
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8634ad1dd7ad68a285ce8b5a1ba0df24
    md5: 4b2e588a7190e7ad7550b3417b7076c4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1408ac4d4345c044a8e7a7cd678f9f4f
    md5: 36cd482d8ed44005945483c3e59cefdd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_density.res.nc
  hashes:
    binhash: cdda657a49ca04f0f305d659a42db5e0
    md5: cc3925430cd5fa6ee994e705f32960c7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 087e68f1770960f74ad12ad9448dc12e
    md5: bc823e89cc4e23f6835133823630539a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b9f1983e994d909afcc3486400d349c4
    md5: cc93a854d8dd44ea8491e6eb73962331
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 65011088b52c508f37729b63e54b74b8
    md5: 4d16bfd7599dfffb93b5448466049042
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 40c0fb39cb8e53fe825141d81787d583
    md5: f7459c9d6311bf6e62b120b86dcccca2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aee2174e9ac46e3df9a64c0cc72334ff
    md5: 9c0a9679e2531714114f6a26bb007a0e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4501fb4d8e08a18036c8c80de14f718b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_solo.res
  hashes:
    binhash: c4a44f00419a04cc0f9131c272f43eaf
    md5: 7f5d0f5e22ecb882066621e8c4e4ac31
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0ffccf9973ffebad4c7c378290e61f68
    md5: 09bc7f7d668d034dfc02c06801dec529
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8fb6e3ed1547703628ab86e7296b4aa7
    md5: 182c8c9a385f4b903e95e13d32097fd4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_tracer.res
  hashes:
    binhash: ce63f0c863690f4ab9d41215594c8144
    md5: a78291060634a2bc570f429189820034
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 59cb3642f4e7b2fc465ff93ae8339118
    md5: 0bff4e7b1aef09b20d456c743accfd20
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ac60bcd8b300e43ba02c3c8c631ea208
    md5: bffb3fe3fa25225a133067b081251d49
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5ef245d1244cd64e437f0add3fb5e2c4
    md5: db6f4cf5db95a05e4e26b0c4820ea053
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart309/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3c34ba94e4a01ed4f3cc2b5ebbf8c98e
    md5: f41294a00e03f9166488374cecb38345
