format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/atmosphere/restart_dump.astart
  hashes:
    binhash: 269d3ce46a9a600ee7776ac0cb9b8fdc
    md5: 42857c4731ef36fe04880a50fd9787d7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/atmosphere/um.res.yaml
  hashes:
    binhash: 7f5141cfedc261c70b3e23b0537a4865
    md5: 5cb6579b796454f33f1c59959fdba31d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/coupler/a2i.nc
  hashes:
    binhash: 628b99de5169f5d6da154d8d7ec949dd
    md5: 2ab8159705d75fe5b7c59eaf3f96203c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/coupler/i2a.nc
  hashes:
    binhash: e1bb20ff24eb770ea86b6959aa544551
    md5: 6263b3cc668dae81ec33e7d7317a613a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/coupler/o2i.nc
  hashes:
    binhash: 812fab78b1dc2665f9717afd51cec8d3
    md5: eb46a0ca73943f5703c00368459672cd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ice/cice_in.nml
  hashes:
    binhash: f73619fe0997ce8161bc5f5b7a3025c0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ice/ice.restart_file
  hashes:
    binhash: 81245aa33329c53b321608f8289a94cc
    md5: 06be2354a28780c79dbc4c313ce509e9
work/ice/RESTART/iced.1229-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ice/iced.1229-01-01-00000.nc
  hashes:
    binhash: 03732777fd3dd975f0861093491138c5
    md5: cdbe1e1829e6009f2aa11a8a94578e42
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ice/mice.nc
  hashes:
    binhash: 44169ea8cbc6c458ad49fa67f6508996
    md5: a6931cd75f51ecc467145d901c29ff0d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_age.res.nc
  hashes:
    binhash: 0f54cd18ab3effb0918994154fe35bc7
    md5: c44564779c228b54cb33c387646973cc
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 81b7614ec62254f1de9635f02658e3a2
    md5: 77e215757e019493bcc45c44d2fadea1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2d0f7f50bb349f36a3daa9bd62c2627d
    md5: e32634660c6eddf0b41e242747e57b3a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_density.res.nc
  hashes:
    binhash: d85653ccb1c620481c2960238e5b4551
    md5: 8dc9b120c9094ad8b416fe7d76244a82
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 85f4b0c31375cc648737fd5565df57ee
    md5: 086f1ff98c80d66cb9372fe726147740
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0f8da3ea24b7f96ccef5380526d86fd6
    md5: 82281bfe9cd34c524edd33a5fb082b00
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3af1c478434b155789c6caa95fb02e93
    md5: 6108dd4c882d138538f43558e0fe5aee
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0b1da1facffbb9b21f850b83e71c7a1a
    md5: ee5192292d9bcb5bdfb7740b7510be21
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2db69586ad3ef5f8c864ca519ee634a0
    md5: e7d14e62347f24ab940eecddb711f4ef
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e474880a76aa4bec594ba3389ad6a2ca
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_solo.res
  hashes:
    binhash: 9cc6cd2bb4d8640d6a4697d1c63a1845
    md5: ef82c714a0fa0e27d20cb293aab4744d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 514715457eae88c2562162564f8ded04
    md5: 62af7d6f110a56c7a55c1c0fdc790540
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ab37a4bd52c2f8df2c2b294686fe3c62
    md5: 17bfb4522e7421b11d3829612a5ae798
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_tracer.res
  hashes:
    binhash: 62ed2ac1a3d1dba25fbf9ca189e9b5e7
    md5: 3c3af32de3f5b5e6e64fbe34327d8194
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2015d038f3e5cb855cecd56427c48a76
    md5: 68b67700466cffce05cbc58de2101e0c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 668dfbfdb95ccbcea320060631b2be79
    md5: 348c54db0cb53892d708c9b160cafae8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f9b9d04c05bcff1d4ef7024f2bc60596
    md5: 0f82918dbc108c1d7765e05d737ec106
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart345/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 54c705c5d3b3714ea4acb9f949707118
    md5: 845ef8db5d5da7d14d61e2e7b7468acc
