format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/atmosphere/restart_dump.astart
  hashes:
    binhash: c568f77ec32b1c55b6ca3ef6b2563f13
    md5: 93817fe7093635a277a62b6daf9d0ba0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/atmosphere/um.res.yaml
  hashes:
    binhash: 68cd2b271ec46aa7fbc9a819c7c11e1f
    md5: f3982b559cea45d6c1d7eb4e5c8d79f2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/coupler/a2i.nc
  hashes:
    binhash: 04f7966dee6e6f73d6b442f992712f1b
    md5: a4e6ee007ff110a091087041d739b34e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/coupler/i2a.nc
  hashes:
    binhash: 20681333fa18d1707a061a40f808f410
    md5: d3bb660f4a90318f26939e787d0f024e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/coupler/o2i.nc
  hashes:
    binhash: 8e4ded3f9c4c09c085a1e3ac063a8f58
    md5: 8a698fed798d4337728ae78d27665178
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ice/cice_in.nml
  hashes:
    binhash: 211769c623f66cfc32027f9ff3a6cc60
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ice/ice.restart_file
  hashes:
    binhash: 314d60b6b7d991303b6e1b1c846333f3
    md5: 7244e06ea75937dce8b5f94cc676db59
work/ice/RESTART/iced.1180-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ice/iced.1180-01-01-00000.nc
  hashes:
    binhash: 8b15b33d22de4a105b5816d326c3bf65
    md5: c151a07584ed1f6d24538acfa83e9714
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ice/mice.nc
  hashes:
    binhash: 436e1290c95f6b9776a3f80e27f92e3f
    md5: cf6ab448a50804aa6437b1f70bdc7483
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_age.res.nc
  hashes:
    binhash: 43f0fd0c86e5ec6b880f6a28b4ceba03
    md5: 6618ae002071485812ab1885c0253738
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 53fe823d5028c578c91e6117f2aeafa5
    md5: 71ac7a3a5a905722c298d5eba125aec4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aab2d9094f4b914cc56c8c22557d900a
    md5: f684054ca6c8140652cbe8ed7b6be1d0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_density.res.nc
  hashes:
    binhash: a343344857f8fea7f07783f716f31d5a
    md5: 9ed7950d85d50bdccb5e667c6ce09f31
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a7761504f4d503725e44c96e16ea366d
    md5: fb08353c302a5a4e4cd87f012de8e4b5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d32b73277d173c28794c03dd364b746a
    md5: 1ab76c79554d390ff1efc5846c5dbd62
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 564b2f8c53e33e94af402cb708df5dc2
    md5: d738524b9d95d25537ad24d4101e9149
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6f692ec8896a7a474f9792c822000c8f
    md5: a0b6c2032d7f80e653e172e6d90873a8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 65f9a1004fdb1d31149cb04ad966d154
    md5: 4dd54dedd77241c231cb81c178d2304d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cc8842d40e4afa1986d37b6a24d289b8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_solo.res
  hashes:
    binhash: 96be7eccee63e6addb5e63bed487e1a5
    md5: 8b7cf77f53f0d2bb9d529fec2df0a608
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4dea66ebb36e451d99ee4f40b72318b3
    md5: a872da3af05f91c5548797f06b9346bc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 697767615b3bb364901227727d3bdcc6
    md5: 51354326329fb10ec6bf0ceec539fc55
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_tracer.res
  hashes:
    binhash: 9317d50371231c73cb5660382de49091
    md5: 0ca8f6ce89bce4f2b9a7d068ef8bca03
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 566ae3a3a9d6b790794d7b06349dbf5d
    md5: 2e7ed77fb62b2698b21b9ce971e46cfb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a2c19d4da11e79a9f100bfe4bbc87f64
    md5: a2d91af8423688219810190dccc83fc1
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 872e0343e53b91f849ce4def4205be98
    md5: 4fda3eed92e670bf0d1091721ba8b8ef
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart296/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fdc3e0fe19d16aea7627f0df86ccad22
    md5: c33c39176fe872c60cd646eb5e59e94f
