format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/atmosphere/restart_dump.astart
  hashes:
    binhash: b9f0c1275330dcc2002a0b4c4b06f71c
    md5: 084cb7c3a3cf924490f65a5fda8abdd3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/atmosphere/um.res.yaml
  hashes:
    binhash: 2bf0e3c0452dad3f918b5006a2dada52
    md5: 77362df54caafbcc90181fcf966b1f6d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/coupler/a2i.nc
  hashes:
    binhash: 2bc0864d76921b8f85588f47e653afb1
    md5: dda1dba8ed903b8b850a006d8c6840c5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/coupler/i2a.nc
  hashes:
    binhash: e33ea5bce63432a0fda7349b33f8ad64
    md5: 5c1224ad60cccb7a88ace09f64e0d0f0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/coupler/o2i.nc
  hashes:
    binhash: c9f800661f775a52acc1d858095178a6
    md5: 20ceed96e9edcf83a295cee0518ace19
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ice/cice_in.nml
  hashes:
    binhash: 4f11d6db2c3d377279b5c4010275c8a5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ice/ice.restart_file
  hashes:
    binhash: aff0feceb2e8a15abb6ef4e27e20530b
    md5: 39f203ae9d39205d1400a18895141aec
work/ice/RESTART/iced.0938-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ice/iced.0938-01-01-00000.nc
  hashes:
    binhash: ee661a11544c9a9f38c9a165911741b9
    md5: c9c70504a2d3ea4a0fec2ee92b7e5ace
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ice/mice.nc
  hashes:
    binhash: 4392d127e86df8600250285114320ac5
    md5: 4004e094eb75c5f81d29be6bf0742166
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_age.res.nc
  hashes:
    binhash: 4c03c7d33f71566c68833d36f56b5c3e
    md5: 25e0ce8613d39569f867070191b5ddde
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bee3336622cdc67513d8552bfcd57ea7
    md5: 731794539092582024b3de5865da5fbc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 661da456c8c635979182c1e47369f9ee
    md5: 6716a8f1fbbae6ecbe04dbcaeb7d4f4a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_density.res.nc
  hashes:
    binhash: ab0c8054b9a41e3eca16c89630e21910
    md5: 45556f24b29dfc991e824a32bccc3b42
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_frazil.res.nc
  hashes:
    binhash: baf790cb070c90741fbb25baab742e6e
    md5: 1e9b9c590305faef8248e84f19c18b91
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 959123342cdff73f37d73532d6da8408
    md5: 5a388aec5d67f9794f1e14792cd049b5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 998ba4c2c72884978c70483e6a557215
    md5: 6196bfba26f804f3077f4ef4ba59930c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ff6f5a8add6ad080bf73353a0f3771ba
    md5: 05bf5cdd8bcfd380308595667b18d20e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a3828aa4b8b68f54d47669afb92ff5e5
    md5: 0e85226d5112d88f746ec5468007bb67
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: def57131b98332a257fabb0444e0e4ad
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_solo.res
  hashes:
    binhash: 011de6a7c0b97c8d02e99df50191c0eb
    md5: 4841505fbfc990f8825fee26f68e61d1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 21e9a5d882bd8537c9902a91dc15ad86
    md5: 5cbab923fc338c2f81a66bcc88c6ac3a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 070272d177ceee452113d089ffcae0c1
    md5: 105bcd5dc21ff7482a4b110f44fdd6f2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_tracer.res
  hashes:
    binhash: e9462a2c2f80f9d115e197da6391c7d1
    md5: cb3161b317f2f9339f06a5fa0bd3abd9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2782c7026d88c1ba1bf46bc0de059961
    md5: c8be9424e5f072b7a83a58ded451433a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: af63dcbdac3150568c5521c39256be1f
    md5: a54d099477617e72eedae13d21d7f624
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 604b6ce6e301de5c384492b1fb5b78e8
    md5: cdf6444ddde7037acde9f346744bfe78
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart384/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e7a1d3415154a53384e6770ee8a25b1d
    md5: 023ab4a1eb08dcac82970d2ea47f4d0a
