format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/atmosphere/restart_dump.astart
  hashes:
    binhash: 1c312f9b46cdf0586b46845560e599ac
    md5: c4d0e2c238dcbb6ada32408b58747dc0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/atmosphere/um.res.yaml
  hashes:
    binhash: 5833e79b70b81fdfa86b624e1a02da92
    md5: 39a5748a85df6aacfd79cba5968b02b7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/coupler/a2i.nc
  hashes:
    binhash: 2c9490bdf51b20e02c639481932e9c2e
    md5: b54f5eced63a76ca4efc2b70cf0eec55
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/coupler/i2a.nc
  hashes:
    binhash: d150dfff88f14758574ffe48eb00036b
    md5: 9fca947885008dba1333e010ef03cfc8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/coupler/o2i.nc
  hashes:
    binhash: 2a63646722bced79ac21a7e9670bb7bc
    md5: 756b928d02e154c3375ff32e427c2366
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ice/cice_in.nml
  hashes:
    binhash: 49c9c8ef4d3ddef17b49a5400441a7a7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ice/ice.restart_file
  hashes:
    binhash: f15e5bad9294e3351ebfbaec234be055
    md5: 0a9b1df7b33e88d5e75f19c5be0a0aa7
work/ice/RESTART/iced.1169-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ice/iced.1169-01-01-00000.nc
  hashes:
    binhash: b6d99b8aa635525f5886eabd52ccf5e9
    md5: 27394daf5730b5418b91a39a0111f4a2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ice/mice.nc
  hashes:
    binhash: f508bbb11da768859df4056448d1a0e2
    md5: dc394e7caf50b5dc83b969df7cf63920
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_age.res.nc
  hashes:
    binhash: 6c8e0c7cfcf0758d99e446f381581db2
    md5: 61569179970c8b626ad5a866f97746f6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 74b656b67782ae7ef0b159b9d82ceb10
    md5: 6353216b56c6f5e6d492363b3e80f509
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 13def9b81d7b67adf853344d6a3fa9ea
    md5: a9afbfcd3c022a365fe6c3f28e551c9b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_density.res.nc
  hashes:
    binhash: 3afff555d9c71091cacb9e58729383d8
    md5: c2ba8b65518b655f633cc4b32f8195d1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1dd0d380723ea46f05d439f97e79a2de
    md5: 84ab186637e9be941843ca3c6b99cdc2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: da7477540cfe96cd7c34b0229cb7482a
    md5: 8b9a0c518c0ede333b0bcd9977ef834f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b76da77ef09238aa4be6ac2b215061cf
    md5: 28b379296b3a7a49402f461f539af4f5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 896434702df21f6b8cab80958e55e0cd
    md5: a3250c4cba38fd32d14fc085a7e44284
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_sbc.res.nc
  hashes:
    binhash: eae4c68779b2c963140d03aa6a429a33
    md5: 2a3621e25733ea68d268d5955650ae19
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 41a258bb3b3a27f0b3fd4e551994a546
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_solo.res
  hashes:
    binhash: 49a3cc23e89b672e2398fa8818731e28
    md5: 2a6df4f5016729dd7d8b72c6b92027a7
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cc82d472f550951e5f0ad9bff5f24d86
    md5: 67b2339a17c3f2884c76a2cc53cc1c85
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c6b39637b23aa217bd82eccb13ca27e1
    md5: dbacdc700ceec7e00bd03125443df5b8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_tracer.res
  hashes:
    binhash: 2843c93a42b6ddc48c155109c0f78099
    md5: 7d7afa08822c83009bf4ea67ec02e3ee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 43a69ba453207268db5c43107896aa3c
    md5: 0413d45beea43c706e2a9df817b6559f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eba63a5a362fbd5f4b88e7bf0364abb2
    md5: 108fa4068ed769558938ad1611a9ea01
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5dd8ccb98152afa4b1fd763ed6bed119
    md5: a7b144fc15b5e835cba624b856e7899d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart285/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 21e34a8fd122c791a1c47235746cae25
    md5: 1182409758a1587882097b2f861c9cad
