format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/atmosphere/restart_dump.astart
  hashes:
    binhash: 30d929fb2c51ff7017192c50e9c6f61a
    md5: 1dbc3caaea74a33da0d3f61869e43253
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/atmosphere/um.res.yaml
  hashes:
    binhash: 27cac6855d2eb7c9629644518a0ff7a2
    md5: 4f728df555255a2b36e7a3bec5364afb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/coupler/a2i.nc
  hashes:
    binhash: e9dd3ad2cabcee32c6da3390b873b9f9
    md5: 3c29386c27749b0540289e7f7bf49118
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/coupler/i2a.nc
  hashes:
    binhash: 3dcc8052322a868c65b3b6d0dc12d39e
    md5: aa40dbd3bf2b2906fee5dedfdb2515b0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/coupler/o2i.nc
  hashes:
    binhash: 254bcd2785ea155adaa2f0411dca0114
    md5: f3c9677edb2ffa11231683d454196a1a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ice/cice_in.nml
  hashes:
    binhash: d85ecc348489caec802b629cc9506527
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ice/ice.restart_file
  hashes:
    binhash: 039735b18919f1e2dba08dd950cf7ab0
    md5: 8b8751481d5b4f792b4fba18433023d9
work/ice/RESTART/iced.1234-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ice/iced.1234-01-01-00000.nc
  hashes:
    binhash: 5683ee65f126e6c8057489eea6a104b5
    md5: 80521ea16924c9d822af606ec3ee3ff3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ice/mice.nc
  hashes:
    binhash: f15310eeedd8bdfdb5d36f333d6841e2
    md5: aa7e9dffbd8debd3fae9ce9bb3792a06
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_age.res.nc
  hashes:
    binhash: 6d57e59821d03eedcae4951856919208
    md5: ae540b56d655fa8d1ed22ee581829ab4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b270514e5779214190cfbd5b04242303
    md5: fccc9c3ded6967c8f678be2b29561c5f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1c0c1936a6c86b789736fa3aaeee773e
    md5: be667d46d0709c3062610a3f682a3eac
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_density.res.nc
  hashes:
    binhash: b4cb03c5a9f2dcee18620f6667d952cd
    md5: 8eb5de8887ad46bb80da1af3980fac3a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 499a00a1eb5dc6d799c31fb76ed64abf
    md5: 37f92f2ad1a180f98fe868b1c8530cd2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6bce6260458e4bab986a4a2c29585704
    md5: 9e165341c10210bdb2a32019e9d3d5f5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 70c3136d05bf1e03ee6378befc7cf791
    md5: 150127f4ba84d335b2994b208ac5b9b8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c74f0b49cc6182a9cda01811de1335ae
    md5: 65daae5daf2ae18e86e13771fbeec4bf
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 637f9f7a7c8370d897d455ad558c06d4
    md5: 8f18aa675f610578ee106ffe96c99e43
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5925eb2abb0aeb4e7a03468193be7164
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_solo.res
  hashes:
    binhash: 5c5389e389dc78aaf35e6099f0de99b8
    md5: 55b550519056b150f217d06ccc5269ac
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d5399f46c35f929ca817a7fa96d6858
    md5: 8576bd9afd80ca17dc1a0da30bcf9c01
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e91dfef105d8e9855e7a1977a96b458c
    md5: bff328ca23000a18898a828982197ef9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_tracer.res
  hashes:
    binhash: d867f42b1576140ba375f00f65035402
    md5: 6d1856499c9f5d80a0058452118115d6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6d2cae3a4c84f0053069e3298747d336
    md5: 9935e1a765549c29b358959395108c03
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6135a678a68ab3d811207c3db56b27d3
    md5: 0630bdf196880f259df24ecb81d681cb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2852ed37caa27aa626b2ffad94051aac
    md5: 095b97a4bc1008fb668ea36ca25d2405
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart350/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ff1d712a79e4ea55c588fdffc35497e8
    md5: 6606acabc7a00c842bc035bcddab3097
