format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/atmosphere/restart_dump.astart
  hashes:
    binhash: a1dab240a3dd7a72e326908a2de8651b
    md5: 8efbd317e77a2912a417990f607f9950
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/atmosphere/um.res.yaml
  hashes:
    binhash: 8cacbbf1938ff798bed3a9cabe9b822b
    md5: 0c0258a46d256741dbfac811c6964ce8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/coupler/a2i.nc
  hashes:
    binhash: f6c9e91469fd6bcb9d6843ae97db19bc
    md5: d630d6a45d4fc85f42e7cce1e1521ab7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/coupler/i2a.nc
  hashes:
    binhash: c3b0011459f9534d6e02dbde8367f6af
    md5: 2d1ce2ae9cbf7a39e41613adef922014
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/coupler/o2i.nc
  hashes:
    binhash: c5f6801d010391878a46cc8f02af0998
    md5: de4ba3d5bc36e06b62c256bec17c1034
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ice/cice_in.nml
  hashes:
    binhash: 24ec72ddfc3c4bf78d45a34ce27bd1e6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ice/ice.restart_file
  hashes:
    binhash: b8f34a554d2a5a7c31444a198ba5a7c4
    md5: 1320158c163c05eeb43218394651eab3
work/ice/RESTART/iced.0915-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ice/iced.0915-01-01-00000.nc
  hashes:
    binhash: f3145a6fd29180f3e697f81656ff2d63
    md5: 454be3304da144e9aea14f9d1a175ec5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ice/mice.nc
  hashes:
    binhash: 56c8d66b903515a1749efabd196c43e7
    md5: d391fa3c52cbe1f02cb32237a470f0b6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_age.res.nc
  hashes:
    binhash: 33c2dce817ce4c307496b7e816b43571
    md5: 07fc7da746e77b4923956a1745f5dc53
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5b46c8ae6697292eb0752f4b751ba337
    md5: 3001abd95144fdf7bd1ef9540f31559a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9300032241e35c2ba888e164ee6e4650
    md5: 148b4d17576e6b40a9655a8b173a4dd1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_density.res.nc
  hashes:
    binhash: 576eb5806e28b06edbb982424d5578a8
    md5: a4e1dca790e642b42c57762574ab9f56
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b2c7e66864aed62f5e3c99ee7b518ace
    md5: 04dd5d170fe5d852cd4b6c3f66e2e6f1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3847974da15229960574c9950234647c
    md5: 7f820241d52c5ee62b52c29852ff6c61
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f5e6f07b725d21e980fce217c461d4ff
    md5: 9d4d4b48455af7976130a0da2948d393
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8c0b89990b28c31df5ccca2c7b822722
    md5: 8e8c48b0757fa099780eda1992ed49da
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_sbc.res.nc
  hashes:
    binhash: fd7b9082743a98f2aec5493513da1c03
    md5: 20805a26eb0d5c38b2c72bf16db9b598
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6c8203595f0419b66618396213617f06
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_solo.res
  hashes:
    binhash: 7585b029d1a882668a359765198d2981
    md5: 0a00123934ac20b91261fbc8817ecc42
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a50bda3b4f0e9ec15ebf6ecdbc145e46
    md5: 668fcce38623517e6ac0f3025893f6fd
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b0a6f772ac08deed7a60a37feeef3945
    md5: 9335342f2c79abbe2df031cf3efe9b22
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_tracer.res
  hashes:
    binhash: 9b33d0a5952bde1b69d916249a14bf0f
    md5: 3e56b84352bb00b4053ca5ea9f745e05
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 338a62fb788890cda504b663f4dbabea
    md5: 0ab628b616aad61c2c8afd964ed2dc0d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 58612c3d70a62e52262a6871f3701d2f
    md5: fab5fd2714d4e63ccb34c07dba679d61
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c98eea1b38d71a709f9e44338c23f6cc
    md5: a6aee498dccb3711bd057d7afbc5eb83
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart361/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 86b2ff9f8c7174c0a33be6a6b93e5b4d
    md5: fbb8beeb6adfc4db4eda275e29429c99
