format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/atmosphere/restart_dump.astart
  hashes:
    binhash: d463476a528be0b375e24db48a3d8279
    md5: 8bf212a7d643cf2206d69316edfb489b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/atmosphere/um.res.yaml
  hashes:
    binhash: 12383bbafdaa82616452f732ebaad633
    md5: 7955cbdcdd96dc626bd1f7258c38edd9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/coupler/a2i.nc
  hashes:
    binhash: c814f63e643189ce7fbc46e057b556c2
    md5: 62c06b27e3578220cf3ba50d6f428438
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/coupler/i2a.nc
  hashes:
    binhash: ad972981a0c99b366aa15a989b30c475
    md5: 54b8b873f7374994ed780a565b7de26c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/coupler/o2i.nc
  hashes:
    binhash: bb063a92eb062b9f7d4ba9f645b1e217
    md5: 9e85b1ed5a0af6b931301e95f6a05b5b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ice/cice_in.nml
  hashes:
    binhash: 8161fd4f5eb9a690e0914cfec2262752
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ice/ice.restart_file
  hashes:
    binhash: fab26043b0748df2082eefa0702e3ffb
    md5: 3990c90d0a856bff5f6096d319e6b65d
work/ice/RESTART/iced.1291-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ice/iced.1291-01-01-00000.nc
  hashes:
    binhash: 4ed348ec0d4b249db2d0f2a66eb55863
    md5: a32edecf14185f62f4324c818f06782d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ice/mice.nc
  hashes:
    binhash: 7352e8842944ead4fc97c764278a442c
    md5: 096a227c158df96579bc011be54b9381
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_age.res.nc
  hashes:
    binhash: ca63ea65488c9f793daab4c0f87b94ff
    md5: 79b47cede9d41e93669be45261ef0432
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4088d54c7274209dda2c2c8d8c03e74a
    md5: 344c7a553e9dac90491584e6ec5e9c7e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 67f1d4b07d45eaee29c8a3c3871a0373
    md5: 7f9ab44c9f86e0890ddec60e798dd5a5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_density.res.nc
  hashes:
    binhash: afcc153ec2abdfd5a15b13a3e8acfaa4
    md5: b3f37511cad723d2ec44510b26221eaf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_frazil.res.nc
  hashes:
    binhash: af4c7832ac776dbc1e04625f8fc12940
    md5: c9f16573ae3a8ed329011c3b62db77c7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ac6cba680d9235b547b1a5833122c9a2
    md5: 9c44a2d93128575c23b6bf4057ec8bb4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d80aa06266c524fb059400d9e3f51ad3
    md5: c5180c036322c1db17706469b35edcb1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f7102897eeeb8080d9a8c4705f8f5f72
    md5: 989f915c9aaed6125aeeb152b634a9d2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4781b4be6bcdbd8f5dc369aeb0b4463f
    md5: a4d9f7c36f64cd6cbb52493df3187951
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5e416f8b850f63879478ccbc5032bd7b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_solo.res
  hashes:
    binhash: f01b8fc1aade8286bd27a6e089c53685
    md5: 86c61ca6a0c6843abf667f9a25ab1892
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d1d9b3b63b35c48bcb4ce6761ec85229
    md5: 76db753a9478a2caa521dceb058a161f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ea392b5250b053cbe9d718e9afb27c96
    md5: 51aa2058ae9568c9e01c83e102a426f8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_tracer.res
  hashes:
    binhash: edc457ccec04ee450cef90d68d24b3a2
    md5: fb21ecb6fd3044a8d31cec7adcd2de42
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b713d25249498f697543f417142a596d
    md5: 4cca0f8e3f1702e6cd1f443539afb361
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 71f557ca710e11a05166b8dc73b9ff43
    md5: 4c7e2d1b41cabaed211e853c73bda492
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 74a0913d8d5772d266115a76425de246
    md5: 1f4a92b79cba44506764dedc700bf21a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart407/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 09c624f7f5d6aa168f0fa316f24d7804
    md5: bdba3d14ceeb484ed2c162a294913793
