format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/atmosphere/restart_dump.astart
  hashes:
    binhash: da9b7fe72626b5e5fcc31a5999e0a3fe
    md5: b9433f64d13afa248619b4781d99a4ad
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/atmosphere/um.res.yaml
  hashes:
    binhash: 315360cae48668aa3e04bb6614d075d8
    md5: 410048e7cb3a7483004c51a15a73a8bc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/coupler/a2i.nc
  hashes:
    binhash: 563a0561e0c1b0ba06fd77a0858e482d
    md5: 961b4c667d6220e085a6f982e2edc4e5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/coupler/i2a.nc
  hashes:
    binhash: c281a78217ee92edcfeb77a765dcbcf2
    md5: 7ad1fb7a6e805a14a8fdea172c8d7d0f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/coupler/o2i.nc
  hashes:
    binhash: 1ad30f908cad938a615f447821f691bd
    md5: b223ff602051b6fc4872d6517375b68a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ice/cice_in.nml
  hashes:
    binhash: 15eb1b6a3050935e5b6099345fe924fa
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ice/ice.restart_file
  hashes:
    binhash: a1b01f4a681a01504b0c805535b3ff7a
    md5: 7d258492a8877368b1f121bbe33b3351
work/ice/RESTART/iced.1788-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ice/iced.1788-01-01-00000.nc
  hashes:
    binhash: 8a6072164f6e9d7cdb2550413188baeb
    md5: 20caa51997f446872b03d70eecd242ae
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ice/mice.nc
  hashes:
    binhash: 9534941eeddf051c355a25aee3d31395
    md5: cb95926283847b9056563b813fa12340
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_age.res.nc
  hashes:
    binhash: 0ad2f2040313c58bc8560cb86e30d862
    md5: 29e24d42a2b578dfe1a42f21522216b4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1b49e42fe55af168821e8c36958bb0b9
    md5: b23adade886e4a0a047b8694478c88c8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9a74d4675ff5414aecc640e97dfd012a
    md5: 2afa731eee71241b21b21b96e9547be4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_density.res.nc
  hashes:
    binhash: 816c24e379f1cbbb807e7c0d5dc0a7fb
    md5: 0992ef90ab5448008fa53752ab36f51e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cf561efc6055c2376e0b1eb652b99433
    md5: ef9345d6b844a272fc1fda1e9931c00c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bd57a1e44d0a671ff52d532b451c9a63
    md5: 8cd19a0a81559541cbdc5927aff134fb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4736391a08500a9add2fa1a0f8844d41
    md5: eba3e4f9b2f8fa616cfb6d943faece2a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6ec85eaaea8da322f5e82358550c2b5c
    md5: 20c8964051add6b19b81c6c324da550a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7bace4a97b3d84f12cd9f17b4785e503
    md5: 51cf42f69237efead6ab36168cdba80e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 503eb0ad69977534fb1f22c3796e4c00
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_solo.res
  hashes:
    binhash: a477850689985c09a758c66f233607da
    md5: 030917f01a1753cd176b9aa67355d11e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e5fa9c6186b4b72531a12fe3630b94f2
    md5: e528e596f33154b07228ab914fee1dff
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9c7a216e67b898b2d0b320c851693f2a
    md5: 954a5ee0ffe9928499bebdb6c1f13507
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_tracer.res
  hashes:
    binhash: 454d5427dae6de84169402ed93ffddcc
    md5: 13d66512dec918ef0f0792752c9d4e77
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f21aca9410322cfa1ec8ad4712e760f5
    md5: b9cbefe6099293fdf3ee2736e4ab2605
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 58a3b6215080115ab48660a97809a683
    md5: b3b3ce743b3a088cb6e37d8f2f94ea84
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c6d9530330c6d5efdf877fb61b9b3fbf
    md5: 153b3d0e74e56c7a1616efa70a314a42
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart343/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2b0b17a990dedabefbb44276ea8f44dd
    md5: 512d46b9961ae639ab3fc348f7667e60
