format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/atmosphere/restart_dump.astart
  hashes:
    binhash: 6993f450ac052b44c8f35c2c2fa3af1a
    md5: 1ae24b76ce7edeb7589c5e47a5e86af6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/atmosphere/um.res.yaml
  hashes:
    binhash: 2ffd03ba247b4465c9643f820d2f066d
    md5: 4abf3567d0ec78cc18aa798cf5130688
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/coupler/a2i.nc
  hashes:
    binhash: 67110c93bcc49fc4d409b3d8b37c08ac
    md5: b33d661291855dfea3738f63d9a8e593
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/coupler/i2a.nc
  hashes:
    binhash: d3153e453f5975638b6039b8cdc41295
    md5: 2ed7e15d294964eff2ecca3193b865d8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/coupler/o2i.nc
  hashes:
    binhash: 013e1f18b50d6d41f1d11117a17f6e27
    md5: e352a36ceee8c8d17e50ea521edb9a95
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ice/cice_in.nml
  hashes:
    binhash: af398157736e81a64b154aa82e1223a9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ice/ice.restart_file
  hashes:
    binhash: 2324a1937a26f9d94792a14c44b3eeb8
    md5: 9f1c1d7ee1949889382c17872c8516ba
work/ice/RESTART/iced.1838-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ice/iced.1838-01-01-00000.nc
  hashes:
    binhash: e6d0fdb8f257f9f0b98c0ccc49d25535
    md5: 71508ca9ea2531ddc21b30d3a0be9044
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ice/mice.nc
  hashes:
    binhash: 4a77ef27b615d62b6dda2264ac4475b7
    md5: 4af47a9d8c5b3e908b6362d75cea1cdf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_age.res.nc
  hashes:
    binhash: e00a57e2791cc66a607488ea1926c0d9
    md5: 385f2ffd10939597ef845be6fd7b9005
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d9bcbc8abb0cd5c88604855e10d7c7df
    md5: 7e1c0ec3f33b6de7be69cd91065c3910
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7c5cab6619890ab22ca8596deb3b9aec
    md5: 37ff81cabf1d59e4406a3a2dc39ca43e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_density.res.nc
  hashes:
    binhash: ea3bceb1d83c8a88f3210cd663835c5a
    md5: 918d51d9b2caf54feb37c7473495f9c9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9211a4fdceca919ba0fdaeedcc8512aa
    md5: dab39ff4b75c221aa40645c71c135da4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8e5a4cc73108c589215c562607067b81
    md5: bd25c99c47b13e27d75a386adf557442
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fc127933d4d0e669b23250740e9a5a18
    md5: b6c535cf0e98272b73fc56198ea9450a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1efc31aae4545b4ef8fbdd2015c98040
    md5: 77a354adb3024beb359ece31543bd082
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 710852727175418060e300ce50fa94fe
    md5: e5c412e8594af65288ce6b22a18e4dae
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 92b6845e69b17015c577bad8e0d22f3f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_solo.res
  hashes:
    binhash: ffc1929e957659a3f49f66a6fdbcaad9
    md5: 26ede060286942670205d435074b67e9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3cefdeec5c9ec85dfc7c7397659bd9c3
    md5: 4634d0c6ae22dfbbd21c8e0729e1e16a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3391a8b18f715d3dd421f5dee2b79cbc
    md5: 3c0338fe3a40c95b2dc67e4ceeeba3ff
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_tracer.res
  hashes:
    binhash: 77ef74f36d5f6a2344bb3a7b1162d434
    md5: 044fc362630146c9ab3873b595254d6f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 82d4540a721d23eb337fc2b4c44275a6
    md5: 1ea6b8d296b8b1712fe1d8b07cf21494
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f44ecf422825b4280d0d675969b4c47c
    md5: 03ca1194a2aec432e35a76da3ecb46f5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: de519167c1156817016f3ee40e62d2dd
    md5: 519286fba2d1df0edc8f84721109e219
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart393/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9fa76e071f434879c930ece696e6f440
    md5: b0f0bbca18ebf003edc6946e9df56304
