format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/atmosphere/restart_dump.astart
  hashes:
    binhash: f4da4b16c6962880978e27a75ea51409
    md5: 02b03abe0e8c11acdff321f233531a1c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/atmosphere/um.res.yaml
  hashes:
    binhash: ee7c40a4044dd047e1b3dde15e130d11
    md5: 064ff6eb817a2fb0b5b55eaaa48666bb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/coupler/a2i.nc
  hashes:
    binhash: af075b3b818548f98dfac7c84eb64558
    md5: b231638f5aff6cea2234070340894c0f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/coupler/i2a.nc
  hashes:
    binhash: 31d47cb5c45e52e757a54a2a8f902988
    md5: df5f99b9237d1535a6affb69313248a4
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/coupler/o2i.nc
  hashes:
    binhash: bd5a2c88d17e1c9be1de855367250d5b
    md5: 53e23fdf8062db8dc7b04d3bc53c133f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ice/cice_in.nml
  hashes:
    binhash: 4c69512221426df5c3d80655e2544cf1
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ice/ice.restart_file
  hashes:
    binhash: 289e793710bd71d01ad54e98bd4ae112
    md5: 2ebf433f70e62c90393436faa0b921d8
work/ice/RESTART/iced.1296-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ice/iced.1296-01-01-00000.nc
  hashes:
    binhash: cd7b19f9cc111c06c0bef8c64b9a190b
    md5: 64f315b5a4292ed02197505364f3bdbf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ice/mice.nc
  hashes:
    binhash: 87de59279d1bfb2d510be32a4f9d1f48
    md5: f6f878d66ad2cac983864908dfa71cf7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_age.res.nc
  hashes:
    binhash: 8410cfd56ed298a40146505665385ea9
    md5: 9026894be881ad4a4e99f9308141070a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c90e309a02d2c2a62e90f206db64f75a
    md5: a56866ef40628f3734bb96913c935852
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b0a655ffdd64c936a926b9c87143fbd6
    md5: 8e6ba45f97ae1bb18c8b29396270e14e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_density.res.nc
  hashes:
    binhash: 139f32737953f49304eaade4c677d4b2
    md5: ead95fc7cd36644a7841f3ca76470da4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 16f4d7dbdd2b5e12de89f62cabb1078d
    md5: d92b0d1100d795bd46aae2162c9035b8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d3f1fdd721c1b7cf88623e418711129a
    md5: c17d8b1cfe817704470a2d734b777d54
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0e449590cc0c0c5c7960651b6302f192
    md5: fffa8349484ef32c12fe2e0c536c8856
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 502796f656a409c7c7c7c332175f043b
    md5: a6b1184debeb6a6720429c665fcf8181
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 18a23caf77662ce72428f982156974d3
    md5: 0fd494ac9268ff53ef6ceb091a3ba579
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ba4623d20b472e1a3210c8cdc6477458
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_solo.res
  hashes:
    binhash: dd981a707658c64ca6a6f6eb08a0093a
    md5: 900227fd02100f5c94c8ed451f987e0f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8d98034879defc2623619cbef61f3747
    md5: 1d8028c71cd184a48151cfc764722b5f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9d492b1a5b1e58485493bd14ac815054
    md5: 7fff24c842556a808f324316e5aff1bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_tracer.res
  hashes:
    binhash: 7d3d3012122f0e10327208b3ca91c89e
    md5: 896b448de6cd92559b0e720659c8e475
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5b5559842d04db6468e828f862cfacce
    md5: 28e4f4f18bc222e722370c3a8a4f974b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2af1007a64f466ffe7cc269c437e0c3f
    md5: b092561d79debfc3310678ba45ad3925
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 714a1939359e7dfa96072b6e55a2d71c
    md5: 7dbcf58d470391dca8b1c6416fa19762
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart412/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8e32bdace428c1528f65b6859ae4ff36
    md5: 68df9c0776329b6b3bae8d569965c6a0
