format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/atmosphere/restart_dump.astart
  hashes:
    binhash: bce2e7813a4633f22b4d2044a7230dd9
    md5: 3751418b35d45bb9d3143d516cc51132
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/atmosphere/um.res.yaml
  hashes:
    binhash: 1bc7904cedd8bd3b9f3d4e7c94f75562
    md5: 1c5d7c8741719662a50d2867ce3c750d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/coupler/a2i.nc
  hashes:
    binhash: 17c72575a4d3d7e4b8d9c360d0d601cf
    md5: 29eedfffcc5c5318ba136b4ce0ca43c2
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/coupler/i2a.nc
  hashes:
    binhash: f86f676dea551d2d9692e4d1b52077fa
    md5: 0d5c98af679f59ed69333ca0be357153
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/coupler/o2i.nc
  hashes:
    binhash: e9bda2ac8d4ac8ed39a0b48b935ffefc
    md5: fe1fef9db1073801344b40c916fde472
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ice/cice_in.nml
  hashes:
    binhash: 19d1551a4fe8bab6d0f29051d3ec1aef
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ice/ice.restart_file
  hashes:
    binhash: 19607f3ac4a7dbd2618438da8b393844
    md5: c565bd5ae25e3512c89d233d6037a2ef
work/ice/RESTART/iced.1205-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ice/iced.1205-01-01-00000.nc
  hashes:
    binhash: dc5e7dacbb27e8d9732d72b6382ab130
    md5: 000f3a1f2aa6835657966152f6f51dee
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ice/mice.nc
  hashes:
    binhash: 8f6ad7c42dab0f1fb3d5dd9619ed8cc2
    md5: 6874319d9907a62d35284eb176e96438
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_age.res.nc
  hashes:
    binhash: e38c9236f5d4085faa6b41a6122ccde4
    md5: ec21c97747d3ac77bd82214ee87dafc5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 320bc6695a50e79f5ef632f4d75d4fd8
    md5: 46b28db5596f677ccf4a5f5ba54de9f7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f19b3af3516f8af18789e0196019ccbf
    md5: 9adade5915ab337b76c2b668c42373db
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_density.res.nc
  hashes:
    binhash: de4e04148e28e48bd5f7704d561bdf7a
    md5: 09da3b764e9e57ca406fe136288361f6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 50dd54774c578a3373c4fac1773eb0e4
    md5: cedaea10ff8606bed01f6d90ee70b3fd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 10d62542cac867f2c23534bafe6b4f76
    md5: 6e90a19c6b146991706fb5128b1fc1a8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8718f145ac9b9a4a9f27350c905e7918
    md5: 9de2e4db1de42023d8bbac381a11a362
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0ddbb774b96f93918cc686fc78d751c9
    md5: 683ad4f097d7de2c8b054d1b48f475b7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9c3514f2e15fdd8dd1ba6d94f817b3a9
    md5: b31b0f040561f72181689775148f16d3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0abf63cbf4b7a336dac99acd8ca1819a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_solo.res
  hashes:
    binhash: cd8dc49d152db7de278218b9f6575c95
    md5: 71c0199a7c59d789d599435fdb61df26
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8fd690fd5e7669d238c7da5f9a28f060
    md5: 8a32ad977498163a36a0664c970f0b17
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ba3577fed4a379aba77a701aeba1d820
    md5: e17141da691724e1152589c05d795ca9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_tracer.res
  hashes:
    binhash: 747e96b8bc51638a8bf9dfcfd1c0943d
    md5: 7226c4519058813c326a4130f5e5c2a9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3c40c01a67aa126ab49e1fdd154157ff
    md5: 4f2c1364c7046e330564569dbbe217e3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f815951ae03673b1f3ab269e97161b94
    md5: fc3efd5ba178fc674f872dd9ef6322ae
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 465608f9fd810415dcf58b8e9018be02
    md5: a0bb820e8b17935326ece3e6e50d38dd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart321/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7bf3300da5fa1c01397acdbbceec5462
    md5: f014425dc36dfd02e56c66b420cb188a
