format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/atmosphere/restart_dump.astart
  hashes:
    binhash: 3ee34cee8acdad3b8dddb9748b4c5901
    md5: c77e3e81304c2212a9cc11d8c308a8df
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/atmosphere/um.res.yaml
  hashes:
    binhash: 9d407348826ce03810cdbef5c187241f
    md5: 9da9f361f9d9097f9ea99090140158b8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/coupler/a2i.nc
  hashes:
    binhash: 102c0d2cfaef0f488a28fffaa81ef778
    md5: 789badcdf57f5446e6182794f3980260
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/coupler/i2a.nc
  hashes:
    binhash: 6f68802188e11ce6e8d6b63a07af1d1b
    md5: 04df97278bedd5ad8311605ef8a3c25a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/coupler/o2i.nc
  hashes:
    binhash: 8e262b94799a19e925b2c6aab1e25043
    md5: 45524462a383256d8acbcb5c7bd7112f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ice/cice_in.nml
  hashes:
    binhash: 5948c0d496820326a7ed3a237416f052
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ice/ice.restart_file
  hashes:
    binhash: 0a500f2b1d5db4dad2a4d3ea4ca6c90f
    md5: 8709d4e180830c13985c694a78cca3c9
work/ice/RESTART/iced.1775-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ice/iced.1775-01-01-00000.nc
  hashes:
    binhash: 35bcbc34295249a654e421f5f622315f
    md5: 60c7d4ed75e43516ce5c6dc4ecfdd142
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ice/mice.nc
  hashes:
    binhash: ff2d2ad2cc572ea65dc7534bf49b096f
    md5: 05cefe727cbbe6ee0dcdbf33d7895c24
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_age.res.nc
  hashes:
    binhash: a6514427433c76aee328260e00d27076
    md5: ab40f9af89cd4c274ce7c87ce8eaedf4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bf25e54891625de947ccdfa1ded21528
    md5: 219a438b55522a0c411bed773e70e6aa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 89b5577fc9d0de6e4a32bc384c4ac514
    md5: 30ac0a3574277969a7d56b305ea5b6f4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_density.res.nc
  hashes:
    binhash: 975a0d5936bb6127f4fd68a7c598c0c3
    md5: ead236b63366de5fe1c0b6d7da9787f1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b4a1b75eddb2d5d344d0bd7751edf4db
    md5: b4e8ad0a8a54cf96d0955e189607ba5c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d2dcaeed4e12347c0cebea40acf45bb4
    md5: c064a1e5993be176debe75f514b7227d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 35522fb406773b424c968fde9657fdb6
    md5: 9cd89af422cb13fb65f6a521d7f739ca
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c882d31290a361d8ab848d8c06711113
    md5: 191fb1969452ecb2a5423387b9615e37
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1d8bd02252435117ddd73c1e00d4cd28
    md5: 7f233a59752a6c8f47bc6006d5f1b9ca
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 580cc9fd542d0a73013678c44adaf543
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_solo.res
  hashes:
    binhash: 927ca5c366b24ef988065c47d6ae1bac
    md5: bc1134ae7543e316515788cf18ba0967
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2ec1a4a31bcf29133de881c9cba28e8f
    md5: 55122d73248a104f09df4bf9c75ef085
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cdde2710263b0cec65e966a4e0530fbe
    md5: 3ee34e7b844f1a888be2fbd24b27e71e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_tracer.res
  hashes:
    binhash: b6d456b0cbc0d1ec090b110763ef0cf3
    md5: e0637b21ebb01f68eb4bf5e2d67b124d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0a86814aa8e4878ce761bf0b8625e661
    md5: e5f73944a2e342d631a1cb5b1acb2e5b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cfb989d1855d9c13a5385335df59b8ee
    md5: 1c2779ef7ce479e878bedcc41e74c170
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b4600f0f4903ac85eb11e6ab7798690e
    md5: c904d7b0a868b59f3d77227091446712
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart330/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: de4efbd22eb095f4904324ffdc40a967
    md5: cc4b838565a6bab753a83540b9f594fe
