format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/atmosphere/restart_dump.astart
  hashes:
    binhash: 4cefb8e7815aa7cb858f9d36b507057d
    md5: a9702b4fcd32e22798bf3d3512d444c8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/atmosphere/um.res.yaml
  hashes:
    binhash: f9ac8d196ac4f6bb1e49566c79084c86
    md5: 55e5e8298627b4dadac74e830a3a65bf
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/coupler/a2i.nc
  hashes:
    binhash: 146bbb30e55ba2b876bc07c4bc994cc9
    md5: df298b0338fce709f4eaf192bcaa1fe9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/coupler/i2a.nc
  hashes:
    binhash: b59c9cef6afbab18259868d6420a4cda
    md5: b52565604d6beeaf0cc022df943b14c5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/coupler/o2i.nc
  hashes:
    binhash: 38360913b791069aa7b2173a74874d00
    md5: 8ab461e6c85a0dd963e0f48796644bff
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ice/cice_in.nml
  hashes:
    binhash: 0f247dae0106ada27454bb1e02c51f39
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ice/ice.restart_file
  hashes:
    binhash: 9b997ac02602b3056b58aa2f01956534
    md5: 4decdc0a466334ec0eca689fd638a3bd
work/ice/RESTART/iced.0835-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ice/iced.0835-01-01-00000.nc
  hashes:
    binhash: 1e1088ecdcb576a4ff1b0f21a0170982
    md5: 552fc0bec071583973fd44f469d78e77
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ice/mice.nc
  hashes:
    binhash: 61030c7ba70545214a3a321c642aee6d
    md5: e7be20d2c2d08d6237002e8801bab240
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_age.res.nc
  hashes:
    binhash: 520f5d4b20977f5dc722b770196ed053
    md5: a61d5033badc9c75aaf5580c7c39b3ba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1d5a71df99e00126b48f14f89cd5db54
    md5: 4abcf027f83c410c5060b282a4c6e949
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7843e2c10b0f18e5b454629978adca26
    md5: 44b73e4b26d5271f1797dc2b28a9b611
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_density.res.nc
  hashes:
    binhash: 6c41c2780bed7f0538e6fd5b8f4d0ddb
    md5: d6fbac6ffe4590034efe327aab873219
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8d16bc046b72cbc0fea48f7ac579495d
    md5: 7d0dc8b8bd96b5d4a450934e56fd2fff
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9eef8052c6f5fd39bdb092884bae7237
    md5: 49dcf4568667c035ca2b41d134c16d70
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2033d99925167d2964be438b25e2c3bb
    md5: 353413245caa4b6cdac27707e0566f32
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ffa3db984442cc99b8c3f3f3044db92d
    md5: 256356a88289f93e4f561a139baeaa62
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3f44c6992072c3b3b2ff4a2c363f8e0f
    md5: c4b52eafa6789ba402726d2fa58c5470
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7ab3f29ddd7d7404ea16c1cca82fbeff
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_solo.res
  hashes:
    binhash: 049fe7e2de8865530c2b47b6d1b518d4
    md5: 17daee48659a6cb8165518668cd68004
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 17f2f8d32cf5069aeca4cda816ac1d50
    md5: a76f785b3e8d405ab7c33fbd79923125
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 70f3c0f06c149f528e8b8f84c58fdec7
    md5: 0c6c843d004514d0613b923041217ec6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_tracer.res
  hashes:
    binhash: 4c59325319291229a12005c1e87f3680
    md5: 6cbfd09b73720d11651a24573609df73
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c10d2d52f2232e539783ecc5e7c08539
    md5: 93fae4952ffdc56a8c106cf3535305fb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 9d698d3c29c6040a3f4d99fcbe9c5c46
    md5: f7293e6cf2f2bf10793cc975ccfa643e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0deec21dde16a35b26cfbd9cf8bb75b7
    md5: 93181ca52b2d7466b2841ac31365c996
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart281/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3a9eaedd1926ba97d95797c3a00615d7
    md5: 5dfd5b6b713187565e48828ceb68d2d5
