format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/atmosphere/restart_dump.astart
  hashes:
    binhash: 6189bbc95f0825844f117e9dbd73cdb6
    md5: deab4290d397a217b0af63806298cf19
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/atmosphere/um.res.yaml
  hashes:
    binhash: 826fceb539de9770b78a6828e35edfd4
    md5: ed9eccda5e1fa41f86b52726896ce9bd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/coupler/a2i.nc
  hashes:
    binhash: 8460296279c1fa5f16597de347ffbcb5
    md5: c77768d9c96a3441a052ad0e14bdc798
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/coupler/i2a.nc
  hashes:
    binhash: 52ce86f6a2c5bd0394b749a1b4b4e7b3
    md5: 5ce8f975b2775ae2800de340b1f19d96
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/coupler/o2i.nc
  hashes:
    binhash: 37b630b05ad9153ed23e4a666f3d2368
    md5: 2ba7eeea974531bb1bee061a280a3536
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ice/cice_in.nml
  hashes:
    binhash: 8c23441a6682ea1e86bfa8b79cac4f34
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ice/ice.restart_file
  hashes:
    binhash: 4ea128fb5d1171aace3c61b6db3e8779
    md5: e4b2ea447ec75a6848f4ef4369a7ee0a
work/ice/RESTART/iced.0985-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ice/iced.0985-01-01-00000.nc
  hashes:
    binhash: ded7f6c235a52aedc71b06a830cc2249
    md5: fdd137d396a25bb2fca4d9a1bcd4b72b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ice/mice.nc
  hashes:
    binhash: 10fe930e59763b20752c0ee418279726
    md5: 27e8b5b5b1fab52dec2bdc0f6dca4d1f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_age.res.nc
  hashes:
    binhash: dd0a3fb7ac8b258961de9fb105d41ccb
    md5: f02446e023974578ba68921ec4d4a47a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 00e34d50f23d76b1f76952e4bfe4beff
    md5: a2a027573121c4c224a5b5014e1dde48
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 695440ac2393148c0b1bfc4889d61a2a
    md5: e4a2a45826c29176a057508586b1120b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_density.res.nc
  hashes:
    binhash: 123f24a448ebff011caa91e90bdf5b63
    md5: 571d9d2f95dd3efbe388003a80389ff1
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 223f7e939ecfc23b58a69a8cfe34cc76
    md5: f11c6bc5af8f1763859de8f44a2f1aee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1d716c5e43bbb22836fe7b608d39b67a
    md5: 75cff4b08d21d7128c02c4c2478752aa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8a8c157ae046c5a5219f6be3f4d0c5cb
    md5: 467d2ee0b7532893711b14d8f19bfe24
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9aaeec2eb86c2a70ec6b98c2b0f2d2b8
    md5: 5230fe9a476a13177466da17789c2b1c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1497fddafbac8e96ba82296501c09296
    md5: 31dedb3472cbd20fceeee8feed598e94
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: baa1e47fab447b063628583d0088da6d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_solo.res
  hashes:
    binhash: f1280b93e2a1316dcc47578e0208eec7
    md5: 8144d84a367564fb99e00ec189f121df
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b63930d1a644ad394d3f3ec258515fba
    md5: 503e54b785a337b6d3eb16f6a83d111c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a4e26d7b5b502c54e99135604a9f89be
    md5: 704867d3c7e8b5580d2a2902c5cd0a7d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_tracer.res
  hashes:
    binhash: bc2eabf72b2601cc0a03c93ab410cd8a
    md5: e6af972ff52b7f7a8719863e459e1e17
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2626b61fcbea31c726a67e551edccbea
    md5: 0d5c5a37e16e6302fb1fb575575e5440
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d7ef815d2ccf4f32a86e640e44fa90a2
    md5: eb44ccb883dfe41e20735c79c6270f0a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b178297861f8790d1fa271c333826b7c
    md5: d6af5dc2b52837de22506bd448b09313
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart431/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 60406f5f4051dc5b0247a1f0047cce74
    md5: cd12009edf60652fb6a926dc144e1b47
