format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/atmosphere/restart_dump.astart
  hashes:
    binhash: f3e602af0fa27c3c8177ced66c0dc0d3
    md5: 6ad0b2700b8c6cd683b20a9c7287ffdd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/atmosphere/um.res.yaml
  hashes:
    binhash: 14aca7c0e3ac553902061e6dd6c4451e
    md5: f94d99626ad478b5aa53f977ec52823c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/coupler/a2i.nc
  hashes:
    binhash: 73a2c864823c2a3bb4497661f1594809
    md5: 078a5b47423371ed7a3ea4af21295ead
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/coupler/i2a.nc
  hashes:
    binhash: 165b96d469b2f3ee4c4a2d5f7564fb55
    md5: 824f6fc646dfd911c02d080b367412a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/coupler/o2i.nc
  hashes:
    binhash: d44328ac12e2eee9077389f6cfff8ca5
    md5: 75b65d35731dce987a37df8fc72d6a4f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ice/cice_in.nml
  hashes:
    binhash: 7356e122aa7d290f38fd6df12b188147
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ice/ice.restart_file
  hashes:
    binhash: 3bd9cc3f444cd639548a7b150d472545
    md5: a9c6b5a4fb4caa03ca76fbc7a1707bc1
work/ice/RESTART/iced.1197-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ice/iced.1197-01-01-00000.nc
  hashes:
    binhash: b193fe0d9a7273bee024e89b729efa11
    md5: 739c928567ad5aa9a9beec98680f2cd3
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ice/mice.nc
  hashes:
    binhash: 54728569d44e12a0baf4a17b71db3d0c
    md5: 01bc332b8315255f22efe897c08528f2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_age.res.nc
  hashes:
    binhash: 7550a2acb029a25768d439900d85f46d
    md5: 8a288e2335ffb4f47d39986a0a06966f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cbda35cb97b14cdeeb6d44b8a13787d7
    md5: 57c5c2f2b399147267a294d8b802330a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 15f765dd91545b5942293a295f7c4c18
    md5: b8e44b46aa7a226592223adc2b325adf
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_density.res.nc
  hashes:
    binhash: 60cace4379b1059e53d64591f408ffc8
    md5: 72450802df4e572d5e10b1375ef7ef8a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8cdae0aeced020f1e4a6ccc38f45ddf1
    md5: 314c00a133fd7855b985a274309d95ee
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 90a06e74d0798d3cd27f6d01901ffc40
    md5: 527f4130be5a0fc5fd0a32dd17dc9f31
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5f23c5f5ab5eac3f25e1eadf93fbcb3e
    md5: 1c8f7f34e1e372fa62f10f153ee3ae24
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fbdcaab4fea22051bf0d612bdf4549d3
    md5: dd47f485353b03151e811c68885db08e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aab0522165fe5c9cd27078cd506853de
    md5: 21476a9bbe1f6ee40be1574d2153644a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6163b8d9c524c0c7ea1419d77e24877d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_solo.res
  hashes:
    binhash: c8d3897ee60e10a9c706ea2f81d21bfa
    md5: 4ca135c91d7a28235bc6ce80f2e98e0f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 742c0d9885f216f39772020e8be5985e
    md5: f3d248508bae70579ca731b79a909ba5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5bef9447f7e5529c1b70f031a66ee8b3
    md5: 91ae03b786e2ac12414687b157dd3bce
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_tracer.res
  hashes:
    binhash: 1caef52af21ef0d5f73e2bcfa2c5a575
    md5: 1610b356d42716c15aca4349feb7f0c2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 66a91c72b474e0ac9eeb11591f86a421
    md5: 7f51d3150915a94bc2dd9bc662fb94c2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5a54209257060fedcbde9f9f0d3672d2
    md5: f6736510f50d17f0d1d5be32888e530b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0de9fb22f7728f3acf520bac44649b62
    md5: 4e53834a2e085bbe6527f2d2a7d9dd70
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart313/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4c54ff0e2958534081389b392a693dbf
    md5: d00ebac5610c1c8d21aec6f975dc9f86
