format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/atmosphere/restart_dump.astart
  hashes:
    binhash: d089c151b3dfc67e88b1702c53a5db04
    md5: 0df9324388cfa43ac4a6780b7203feb0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/atmosphere/um.res.yaml
  hashes:
    binhash: 7ff65d2fc9be69591025767cb39338a9
    md5: 575443d8f1bd7b08ff997e651eceff37
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/coupler/a2i.nc
  hashes:
    binhash: 6eac8a5332fe76f37df461a77b398142
    md5: 3a5426b9ac4f9cb52fe64570170d2cec
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/coupler/i2a.nc
  hashes:
    binhash: ef1f1198809642164efb8094ba5d98aa
    md5: 625ab5938721aa7ae1a9d9556951afcd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/coupler/o2i.nc
  hashes:
    binhash: b6b42e78195a8580c8226006a6da29cb
    md5: 149fbbade9ab516ebd369119c07a6947
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ice/cice_in.nml
  hashes:
    binhash: bf99bffd3763c333bb3f389140672be5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ice/ice.restart_file
  hashes:
    binhash: e11199059a4527c1b400436a5d8d1aa9
    md5: 6c72146125567520527e8695d6d33379
work/ice/RESTART/iced.1856-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ice/iced.1856-01-01-00000.nc
  hashes:
    binhash: 0b6e5c7f73ec914239553a97af82eb10
    md5: 5315e5d72d4127c7c4bc30a9b31650b5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ice/mice.nc
  hashes:
    binhash: 455298b6fce662291cdaf6406af1c322
    md5: a399131d3e0e0c0782cf6624b7efffbe
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_age.res.nc
  hashes:
    binhash: 51cea62137fa94427736746454951a85
    md5: b93c4e9214bd6090cd7d17ffa252d582
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 36e87fd4c84fd0b3239eba5c708c08e1
    md5: 654aad9b66aaea2b188b9fae766e62cd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f3129be7b14d21198db1149b68744d92
    md5: b95eec5f89826ff2d42591f956089ff8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_density.res.nc
  hashes:
    binhash: a939c454ea984fd257db965a33bb732d
    md5: 14607cbf755bee475971a742e275ddae
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a073a50a66efe78aa27fbb918ff1cacb
    md5: b5e4c9ca7679004feb6bc5022ccd57c1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7c216f20cc9319dc1d0997940a152d87
    md5: b0a49865e6d3cc9f2474c910d2a64b80
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff9e7bd917388029592296fd8e290fcb
    md5: 75637ea4872b95c68f507b6f40533ac9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8beca2b963473b5ae91daedaa6f7991e
    md5: a7cbe2d57a2350e5e994eee7cfc8595f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7177bcf6e2c987c7551fc07fee0ae89c
    md5: f4487001ed37108faf2793f3b098b691
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 20d2cf9102cbdbd2820edd0c026135e2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_solo.res
  hashes:
    binhash: de5593a8f520c2d08a63f8fdc4480bb6
    md5: 7deae339a2a9a621824835eb35eb83ea
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 223bc5c5d5352fa740c65a61f3f949e1
    md5: 4f9281876b91245feff5bfc215fc4fd7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6b821bf2dd22092730324d0078b319dc
    md5: 73a9ed487342b4768d10ccaf5d1c340b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_tracer.res
  hashes:
    binhash: 8ae3ec9aac684f8b3e47235edb5ddd74
    md5: 3333b2c0f0bc4c22cd2f961246d9ffbc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 43beb73ed8ccf67ec0cd45bebff0b636
    md5: eecb02eba9e10a92370e19c424f74535
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c75a408b58cd0d572ca5379c573ecd82
    md5: ee11acb4dab9d5661d4df054347d4d19
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eb0cb9b7d20a9546811d6474c2b5d5fb
    md5: f0719694c9beb201dc2b9b4504b00b21
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart411/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5afd4e213d24b7c6c8be72730f2a3e60
    md5: 0ea6ecd7f210b0cb6a1cc727566c3729
