format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/atmosphere/restart_dump.astart
  hashes:
    binhash: 20f96eab3885b9cc074788d8d896a3f9
    md5: 04a0ea4b84cfe2e87a875a0db7f1cd1a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/atmosphere/um.res.yaml
  hashes:
    binhash: 0707d42922c287bf91832b2f0229530f
    md5: 30462e2166e755e21ee4938571a530da
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/coupler/a2i.nc
  hashes:
    binhash: 93c06aaea0b7e9ed711f4197599cfb13
    md5: 310e49c7bcccac25b08748d7f28b8d89
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/coupler/i2a.nc
  hashes:
    binhash: 6ffbf00adbd97bf1e82bfce5a1783bbb
    md5: 9a015cc58adff60dfba8798cf9f4ff2b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/coupler/o2i.nc
  hashes:
    binhash: 242634f976f4e970532e8545a61471a0
    md5: d0aaa01d80294c810ec67f4b4d73f31c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ice/cice_in.nml
  hashes:
    binhash: ffe83ba22612df1b9468437b19db1292
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ice/ice.restart_file
  hashes:
    binhash: cebe8225cff99e2a855ea7bc803d7835
    md5: 9c07f2d6f67c14a39a38439ef22e1357
work/ice/RESTART/iced.1307-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ice/iced.1307-01-01-00000.nc
  hashes:
    binhash: 2044160c6930f136d3bd1b839cde720b
    md5: a41d1633ee81a278de0d83091a63f8ad
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ice/mice.nc
  hashes:
    binhash: a6f9321dbd895b0bb194b0c7cc853441
    md5: 5f1c0895aee4db642030bb0e6491c70d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_age.res.nc
  hashes:
    binhash: 22309fbc01ca861e0c74c8d399b34fce
    md5: 66b81daf633a22459bbd027ec2b4fb11
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5f91d09388a7fe9102b322bab652e5db
    md5: f4c20463eb945b7d5a907249134a0c3b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 84acbe6767c2899f87fa5ca9074a1c21
    md5: 49ddf4523d880f4440ddee02bdd23242
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_density.res.nc
  hashes:
    binhash: 1bb39e9eff3613fee83fc4b403b3c16d
    md5: a14390267f86fdb9b2128d420a9d64cb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6ac4b98d3c24cc300dd05095ea87ae7e
    md5: 005f78f7e7fa67c3c1cf3b5fc5055a35
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d14baa1816be49576c81d948eb54c969
    md5: 31cc8605a6f09826e56415943c9d9438
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 742d00b103f9911aa7002ffe8b0a84be
    md5: 4e231eb286e3a6ca27c77e441e210aab
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ea658f907fdf343e61faf2014e6315cc
    md5: fbf7857c11e86404a392daabaf46700c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f7ef76d3fb495a43847374c49f811c2c
    md5: d54a83bf0e40424f50e52698319e1b79
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bc6bd701b53be79139f32ed79492f4c6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_solo.res
  hashes:
    binhash: 0f0c6d8426b71eb2959d80683bb54530
    md5: 7ce52ce8c1c7ec1c1f19c801dc380e8a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d4a2c82e0f05993f96f305f395c36cd1
    md5: e72d420b9cbe6ab68e147abd89faf19b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2e4ce6ceac1561c8c58da524dd79e84a
    md5: 4d5cf7f550dc2ce9eb34820530528a9f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_tracer.res
  hashes:
    binhash: cf3857875ae85b368a32793b48cb773a
    md5: 0acb5d2338a5cad77a6a63b03a3b6f81
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 65734f1a019b090a4b8a53a88ae5379a
    md5: d9d19a09a259b6f3002f6e7eace145ba
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 11d5414dc0f39895e11a707431298369
    md5: 400cfaffda773caa41a2ac2207b7fee2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 50b3fb416d055eb287d3238d904f4a30
    md5: ad2ce2c89cd225e4f077bd6affe58794
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart423/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c176e59fe7814311e8cf08c1625663d7
    md5: bfa3166d4f44581f4b89b25feb7f9fbb
