format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/atmosphere/restart_dump.astart
  hashes:
    binhash: 9df8888560bb7efa93e39f79dabaee23
    md5: f6cf1edfb454fe8de3d52be21f26549b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/atmosphere/um.res.yaml
  hashes:
    binhash: 325cf4b36b5f2b2d7c265fc06d311283
    md5: 8edc718db173c1c975cfee2c3c41944b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/coupler/a2i.nc
  hashes:
    binhash: 0720319cd039699b8b8cb00b233f8151
    md5: 15a98b01afaf19317c517f76d73ab860
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/coupler/i2a.nc
  hashes:
    binhash: ca335a0fc0b9257ca68d8c5cca0e1e72
    md5: fe8504e59f2c174dc8ffa2ec2d0174a3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/coupler/o2i.nc
  hashes:
    binhash: 7dcae73e5669da1c54dc1a7bb376bd0d
    md5: 797cb856e4d04d6b9825582dbabb0883
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ice/cice_in.nml
  hashes:
    binhash: a053feaa5930f55bfc5861827c327647
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ice/ice.restart_file
  hashes:
    binhash: 6c954fb868f3cb390347f6f536b0e949
    md5: 39af23cbc0fcff9ddbce24efbfa90027
work/ice/RESTART/iced.1156-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ice/iced.1156-01-01-00000.nc
  hashes:
    binhash: d47797b12dd3a6677b14affbfeed37de
    md5: 41eae4339459b4f1d488f8129f97f780
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ice/mice.nc
  hashes:
    binhash: 32e88df0c3bb9b29ab9c6dbc1b3f32ce
    md5: a76822b8bd57df8f9eb616ce88cdc864
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_age.res.nc
  hashes:
    binhash: fb99397928c04144ad4c6bb50df045cc
    md5: f321b0f38afc51027d0c3756bd82e9c3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 296360bfc6bdc7a5ddf1ed643bf2aef8
    md5: 286041e0c4ddea2b2d502e34c27c2438
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 07555d5c1cff9965eef3c3219733c636
    md5: b6f365a1e1bba132c232bb5799b6a0be
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_density.res.nc
  hashes:
    binhash: 0643c2933c3bb49e0d2a727113570d67
    md5: 549558540538418e270b9d2638d3a102
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 57c0ca2e417d43d92b21e389a76bb881
    md5: 282f96d020fbb3a1778d4fe6326f0d45
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f8ca3a134153b1e00d838e9987a79062
    md5: b423051bb3e7c9762d3dd7bacc22719b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1b1387868b6ae78bb08b63ef274b1f03
    md5: fab8f344b3122faf6faf4b7052972425
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4a59840b78692d61ee667e3036d77df9
    md5: 2f1f18ae244184f640387b2df370b452
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a626497f39dfb1c5546f8ae72572b0c3
    md5: dd83ec066d00fabbf6b5e95c573a729a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3d69baab5444b6d44d6793434995d04a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_solo.res
  hashes:
    binhash: d5de6fef3609e948c797e742d840aa93
    md5: 1d2c0ae2c726c3e9c570c31d4e0f79e4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bc2788760a2460e8719d7738941c7cc0
    md5: 908a1e18b53f4122881bf54271a09e35
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fa66650bc87e519190b64231404b7a7b
    md5: dc0e409e100be1cb56d0a18729299627
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_tracer.res
  hashes:
    binhash: 1a33810f533c4c1900bb27e20f82c2d9
    md5: 2a54c910f27ce39689199ec4a3376010
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 122378e19358199e9cc0a8c22085d929
    md5: 4aa926485422b859d4189ead4999ac66
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 779956ed79214b6ea65bee4bfcb1a460
    md5: dca68ba8acfb1b5cba4d4f03b116b84f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b8b4ce80008acf2a0917b103108e46e2
    md5: c6b7699a4cc8bec797e78e5ccc477ef4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart272/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8d54654be8f0b6f829d3540ac946048b
    md5: 18dc9573944553bd9e7d8e3520df3848
