format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/atmosphere/restart_dump.astart
  hashes:
    binhash: 1ce4416279553e901d06b2f82711631c
    md5: 824be8426eae7b6af57ed50fe315ba9e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/atmosphere/um.res.yaml
  hashes:
    binhash: 96c19858b9b9f78e079d6fde960f85e9
    md5: beae267f272c17f418353c9733f0645b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/coupler/a2i.nc
  hashes:
    binhash: 72b00876c157b79d0f8f64b46d80e64f
    md5: 509955777d0bbb8c51c279b1392b5fa6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/coupler/i2a.nc
  hashes:
    binhash: df0e0be0c648f8018e3e212d894bfe3e
    md5: d9f9c585c1f12a6468a5a774f423ca4f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/coupler/o2i.nc
  hashes:
    binhash: 5087847deeb05f20966e3cb96dba87ae
    md5: 87d693a27ad2420f3677c3e12b27d0cd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ice/cice_in.nml
  hashes:
    binhash: 43b5eb4705575c92a3cf90673efd426e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ice/ice.restart_file
  hashes:
    binhash: 03a490170525236f30fd790bcb859cfb
    md5: 454fcec3b778f58e5698283f372b5bbc
work/ice/RESTART/iced.1214-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ice/iced.1214-01-01-00000.nc
  hashes:
    binhash: 072d280c630962bac4499ff15a580a3b
    md5: 1515604948408c170d57bc7bf612ab3c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ice/mice.nc
  hashes:
    binhash: 4182af8eb74cd54bd02f06456f7f3a78
    md5: 6ccf44b39c8f361617608c651c75571d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_age.res.nc
  hashes:
    binhash: 4b2c3f2aa56aa62513981eacadd290f8
    md5: 12b0d8f1d2b91cf8bdcf98bcd793ac23
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4824e7c716322ffae5cc90fd58f9fd69
    md5: d238fd634bb00fba845ce3068c50ca24
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f3713fa99b5bf2cf9cea88a95d5d841f
    md5: daf6bda330a67eec0def12f33d929a4b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_density.res.nc
  hashes:
    binhash: a192da200d632515fa7697085d198e87
    md5: 34cba3d8bac312c6884c526a3b7088dd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f083f0b1638204efcd0527dd3702f911
    md5: df2fb2e168db9dc6642357bc8247a188
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4c814314de9ae0cf1b3fb5f807658b9a
    md5: 0f90767fd1fa0ca9c8152e0d4840a9b3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ca9353f41908987cd68687b8dbed5394
    md5: afee853519c58374aed585b7a1b98167
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 939c701f075343f8b4e570194b405a9a
    md5: 2b851d6329786e172f2d72226b28fb64
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 31b23d9178ed429946d292f6f397c2fd
    md5: 5b5461252a653f5d276fa210949148d1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8b9c671ba16c7f7f0a9e09d931b5b7f7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_solo.res
  hashes:
    binhash: 581f3afbd67dece6ef8d46abcf3f59c8
    md5: 3de535e61c1e0e38f801ad7669c33b5a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e70b298f7088d7224132a390c2fd0918
    md5: 9d25ab3a2c47c473fa2f420625119a6c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ac7c3971c5dbe24235d41b6b2536ca91
    md5: 249aa4e8849811137b42fc132b2e5c40
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_tracer.res
  hashes:
    binhash: c9e34301cfc951a15aca5158410a1fa7
    md5: f542320f1cc975b259f1bf7c580b44f0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d5439a921a93ff8fa9aa84424c9e360c
    md5: 2bc02a17b8b5671edab850cde3c9eff1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5e817f430ebdad4b6ed76a65ebf73bec
    md5: 18c559c0d072f6e34ecc54df52911bf8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6b20a0600146886a0ec239dd7b482259
    md5: 7a2db7cbecdd384175f884ed85a6a04b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart330/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6a3c70ec5389cff16b107025780ebcb8
    md5: faaff44ad2336363fbf52d920aef813d
