format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/atmosphere/restart_dump.astart
  hashes:
    binhash: efdd37e5d226a4bd15a5d1aaf120331c
    md5: 21cede8b6ef25a8a66610a169380886f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/atmosphere/um.res.yaml
  hashes:
    binhash: 84188f178dc90b412095294a4b1b026e
    md5: 3b5a387b5aa7a0ae675bdbb235f5dc7e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/coupler/a2i.nc
  hashes:
    binhash: e4889b5aaded010fbd6bef1c649966fb
    md5: f62a6df4037f91e6bc984b2e6339e19a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/coupler/i2a.nc
  hashes:
    binhash: ebdfcdcc4708fd272ea4e061f04f9e28
    md5: 29eb4a0507fc7d9b8b76d999a79e635c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/coupler/o2i.nc
  hashes:
    binhash: 2afed48fe9dbd73cbf33eadb718e0c81
    md5: 8928573b073675d0f838a00e06412e20
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ice/cice_in.nml
  hashes:
    binhash: 1d6a3ddee6057c23d42e98f8eae4b94b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ice/ice.restart_file
  hashes:
    binhash: 9cf53c1fee115df4586e7f0524a692e6
    md5: 7a0a0dc1704b420a00387f7efd773241
work/ice/RESTART/iced.1300-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ice/iced.1300-01-01-00000.nc
  hashes:
    binhash: f99a2c974f0e60f06565cad4bab070ea
    md5: f7ab71efd9f17470c93553b2bb61657f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ice/mice.nc
  hashes:
    binhash: 48b5ca274a194c766a63b8cfdaccf6a3
    md5: 7c3bd9627a93bafb55b1634149b4c029
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_age.res.nc
  hashes:
    binhash: 7d9f2e687aee906ea65e494482fefd61
    md5: 916b89e39dfbd8744d6008377e3580c7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f2fa6168d45c6398e5a7d9ae2da68830
    md5: 159f6d9b0ea3780582cbefc91829260a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0bcb2cf3f0b28d5a0ae462c7326fd450
    md5: ced0df16189021e5b06316b04043dbf4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_density.res.nc
  hashes:
    binhash: d55b2e99f3801f7d71f2ebedbfe9f490
    md5: 65c33571f04e5a560311c41c496c481d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f3c654ecf9c26ca93f54a17bfdc97429
    md5: 5547f720745dde0b399a1cef0d61fd90
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 48561cb2992e73a406b2da08a3787f98
    md5: 2528a4d70165a163aaa23c6dd105bffe
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bb2e60d297fa42ea50cb5f0b436d4a84
    md5: 83ae66c06a49f356b2fb986191e4370b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dbb3e1bb994ae07675b979542a855fa5
    md5: 7960666802a5c10551d2624d617c7119
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 116f97558f7870ae4f06ba0faedefa5a
    md5: cfac447fe90ca4945d6b438e5d22af7b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 58908880494f2204dd4266e1f6a03d74
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_solo.res
  hashes:
    binhash: f343654ea7977b5293a06e05e3a75f3b
    md5: 43e89e2d3bcd55256a2c7dfe94ee03d5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1ea3805c6cfd260ab422b5e41647e541
    md5: b3cf9d287cf901b7d7e7f547075a22f4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c39d0897f553a09259a381fa35316004
    md5: 76d6a35c78508e3a66663d6e95ac2aa4
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_tracer.res
  hashes:
    binhash: 6ef63debb7db92b88e7556ce159a5356
    md5: c4b3d0084ec46d6e4419e0c1207a272c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a90c2a156547eedb57b7188c1fd6438b
    md5: 08d6fd1d9379d9df01d76db966d3ba51
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0c6af362a94551d8e1cdc7a98fb6b19d
    md5: 15f958dfee33aacc5c72aaa658d19d63
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bb86cf6f5497adfac413b34c485ab573
    md5: 83a60389b8ac77df53807fbc28a94742
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart416/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 57e861c2ebae8c1a5bd0c819dfb6db00
    md5: 1c584fdc7e1792f72cf64011d8727e3c
