format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/atmosphere/restart_dump.astart
  hashes:
    binhash: 0106f3240d97f5dcfba0d5070483dc48
    md5: 8e26f5e411142d9a159600a93eba9cfb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/atmosphere/um.res.yaml
  hashes:
    binhash: e289a6d59120e3cb74b1e28588b4f05c
    md5: b01e1920e68ae1e9e6724b2d60eadd7b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/coupler/a2i.nc
  hashes:
    binhash: 6e64c7759591fc4498c87ad482908028
    md5: 3901574c0f470ebaa7348cf1b6d0848f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/coupler/i2a.nc
  hashes:
    binhash: c3ed59b7ceb6a79eb945cfdf9919bf3c
    md5: 5d794869309536eec881a18010ab4855
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/coupler/o2i.nc
  hashes:
    binhash: 564b3d83db0a7a711fd43a3ceafdf381
    md5: fe409ddc4fd12c7bef6ac4b139f1daba
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ice/cice_in.nml
  hashes:
    binhash: 79a0213e72e109d3a315478d8791f463
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ice/ice.restart_file
  hashes:
    binhash: cc02a538a0aabfa5e36feabfe0cded44
    md5: bc14d7222c1eca815df86c582ab1b9e9
work/ice/RESTART/iced.1790-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ice/iced.1790-01-01-00000.nc
  hashes:
    binhash: 270dc6cb108359770776644a15c43fcf
    md5: 172ebc24cd029116aae57368a7169521
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ice/mice.nc
  hashes:
    binhash: bc568b4d1ad573c0fa3b817a0d58f8f5
    md5: 14b267fecdb99335f110f00a7e30e8d5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_age.res.nc
  hashes:
    binhash: de7861718b4e39e41d682e006b9ad01a
    md5: fcdc32d5d9ad5c727216c7645a947928
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ab1ee343221055cbd26adad6202faac5
    md5: 2674cc127487df5afefb75fee6c18c4f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a9e57916a2894e1b7dfe117e7f796ba0
    md5: a29161a3623e49e1a63b481924aa38b5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_density.res.nc
  hashes:
    binhash: d8d8c160c7a0077eb0795b86205f67d1
    md5: 617c44ac7df5913a617ed71eb4dcec6f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a5e99e86df6a2a9a85f001003676b24a
    md5: 7eae0467e68797deb4bfc8e6dec40488
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7b1285de39fb981ad4d5617d774f21f1
    md5: e7f068f3a4a3795d9998e5538be64e54
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1df12faf517ea9cba18a131c7906ff43
    md5: 39e1d240d87725c68123c13ac1d337ac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5693f59c6001ad7b82ea7b892c11072d
    md5: daa05b78372b45c2d834573e8ab5ba5e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a43bc94f4da0c35a7e954b433a086ac9
    md5: 8a8b18efa15cc9e4760813d076d36ed6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 272d0728d3b58bb92c1bde7d04802d60
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_solo.res
  hashes:
    binhash: d4a75896301a6384aa0a63b6fbcc3385
    md5: 084b8c6c378cfbd9ae0bde73e5c02f06
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bfdcac0f225a7f91502cdfc82214b15e
    md5: 9ad04837aebff751a1a15c925cfae4ed
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7d14f15c6e01269a68f9f33f5e4d2866
    md5: 750c4ea2b384266b00f7346671687270
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_tracer.res
  hashes:
    binhash: e183b077ae79915be272a059038f82ae
    md5: 269a42e10fdc8007737c6c4ae1d3735f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 72cb82596f04b642e20b1fe0cb5427ba
    md5: 2fa275db0c59a1abf563e654732d4587
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a03d56b9c67759f97cff0a94879e7f66
    md5: a2c5f4ef2be555895f712548c65bc7c9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 761e0eff3ae457bd964b961d9960d321
    md5: 6358a3aa2e68f4176aa313cfb3d51288
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart345/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b64a0bb4b3b4fa1db8558f461736d4c4
    md5: d6f64c0e329c6fbce9d04e771aed472e
