format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/atmosphere/restart_dump.astart
  hashes:
    binhash: 7b96280da49e3ceb27807f4ca15b6f92
    md5: d634475b65d1435e5fcee917035fefc1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/atmosphere/um.res.yaml
  hashes:
    binhash: e17a2fc67db029a0bf4791f5bf31b2fd
    md5: 26f83e069d13585fd67b0aaae556a02b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/coupler/a2i.nc
  hashes:
    binhash: 83542babb9069859ccc821d0edcfde2c
    md5: 668ed693ab3f7e84d8815cc852699495
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/coupler/i2a.nc
  hashes:
    binhash: 9bda0edaf36cf0c90e4fab091686a490
    md5: 9a41902dc651c2f0de1fac4bdfc4072d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/coupler/o2i.nc
  hashes:
    binhash: 6ecd43d928ab5d1cb46d2b63ae089bc8
    md5: d3fe687a671954df43923e884ea79b6a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ice/cice_in.nml
  hashes:
    binhash: 29bde9688e9cb6ed80b167aac69f8b0a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ice/ice.restart_file
  hashes:
    binhash: 92087db5c16e5558b978543d99769d85
    md5: 24ccb399db21f7e7f3140a5943a7b1c0
work/ice/RESTART/iced.1269-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ice/iced.1269-01-01-00000.nc
  hashes:
    binhash: ab1dd85ad4ea42f810f34a9670c52cad
    md5: 4f5a34c6c391ce2e7fbffadadef7fabd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ice/mice.nc
  hashes:
    binhash: 70a1afb9b678815908638c47b187c95a
    md5: 75a0cdc16a6d09589f727e87a3fe8ebd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_age.res.nc
  hashes:
    binhash: 89b7f13ee1e8954535ff9137a88c9fae
    md5: 9ef8fab81e800b8540c3939c9039ee63
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b5d94a8ea437c7b4c4a795d0b3c5772e
    md5: 0cbfeac8f84ebc0579b0cfa09d387328
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 73e457cb6e4bcadec8c37653d9eb94c4
    md5: 8facdc0c6b23872c352958b130b41e28
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_density.res.nc
  hashes:
    binhash: 0c4d71332254ecca921ea17808eb7e42
    md5: 8ba92e25de030f3aa5abc44e387247c8
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b00f1d4e6d4bc4f3fc509d835f93d920
    md5: 7a7113560e0ba4b5d536c92dbfa5b584
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f900b30a7caeaed9cac6c47aeebda8b7
    md5: 6259abe9402d6efcc4612e62cfac5dd2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 63b7e5e045c861052a0a1ba2490ddd56
    md5: 7991564469d25298b8f5561cbaca8bf8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: aac24a13f64603e4a31dccdef71380a8
    md5: 0fe09985142fde6655ff4b6f215cb962
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 585eac407d8dbe4e49ee2993d315dac9
    md5: 5c767c277a33a2ad99f1342f66571744
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 25a08ec97754bdc6504f0b13c6b4ccc1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_solo.res
  hashes:
    binhash: 111404fdde0e2628c9267dda929dbed5
    md5: c8ccae7d117300394559346cbda7e7ad
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ab7ef23a2c8b12157dc6e57397b480c5
    md5: c3208a1b07c352564ad1e87632a2c802
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 47feab8a82e06684d86f80de952f7056
    md5: 8218675c16943c964c0983645ded8ef3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_tracer.res
  hashes:
    binhash: a1e1f4882d8043861072215eaa9df13d
    md5: 45b5e18b3c1a9ccb0c08df80b1246d4a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6f379166b48a1dfd2434abff94903620
    md5: 9405791411afafbd53f786bf96886524
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 14bbb4f66a87bf1d977db557591ef700
    md5: fb09742665f313b6641f4a82bb270e44
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e6599398e9ab1f557584e9ed3a97fc95
    md5: fe399414c4df91e78e6bb3db87e6a2ce
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart385/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 08b8b11892cce142d9544022b56cf0c3
    md5: d8d6e8e7b69c259f4a6e706cf19ec9dd
