format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/atmosphere/restart_dump.astart
  hashes:
    binhash: 4d31fce2bde2e339bd65684e51db562d
    md5: 0cf7a4c073fbffddbe673833a8ed699f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/atmosphere/um.res.yaml
  hashes:
    binhash: aea3d23dbe75ed6c07aeb35ceea3bb89
    md5: 022f12c0deb7b9d0bdae816e782c326e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/coupler/a2i.nc
  hashes:
    binhash: 7a5bb1321dd3772fb847eb1ccdab8d65
    md5: 1b0ccbd0987967230c57fc0754bc29b9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/coupler/i2a.nc
  hashes:
    binhash: 886941b7ba894c1f9a63e8d1dc06de6a
    md5: 5709adfdfd788bb5ee309bea7582ba2b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/coupler/o2i.nc
  hashes:
    binhash: f8b5196db6d6c3ba4090542ba099d6b5
    md5: 9979869f966a4d90901991c4aa0495d0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ice/cice_in.nml
  hashes:
    binhash: 453002ea79532893991d289c1e68f803
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ice/ice.restart_file
  hashes:
    binhash: fcfb027467e59bfcf7ba7ac0b27106f4
    md5: e5deae11c882e01b532280488a5323e2
work/ice/RESTART/iced.0855-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ice/iced.0855-01-01-00000.nc
  hashes:
    binhash: d9300b306738395b3bf466432a135905
    md5: 112291069187a82d8dabedb542ce413d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ice/mice.nc
  hashes:
    binhash: b864ea647376deaecb68a118da172937
    md5: 00305af73d7395e613f7583e87e18541
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_age.res.nc
  hashes:
    binhash: cbbb87f2e38b2e857ee65f749ded8521
    md5: 07ff40e1df5ec31ba1560898706641fe
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b54892c1d2eea79a0dd32f78907f3272
    md5: df7982aef2c548c30021bb26c579b3a9
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2859f7383924c9d19e49f93a0af02278
    md5: babe52462ebf2c9c7458686ff4d71415
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_density.res.nc
  hashes:
    binhash: 77b98372edb52ce44ddcd9019da06ad7
    md5: 250479ab19e72e8fd3ed14145717e4f0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 22f0f02d0b071cabd6e747cffcba16e5
    md5: b0ae2ecb111ed9a7d9db41110b104281
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 96c9e67a5457504ca09dff5dbbacd848
    md5: f59cf57a5e84a7ad0e85b787f661fa0d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d789ea66a7becac1b9d8a7787fd89773
    md5: 14abd03df19f009d40bf3fdc8eea17c6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b6b8f077b53154060064e39b891905cc
    md5: 2d62f378a79cc4db75498ae996f059b6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1d022e2c769bc1bbad9d31a2be54fc11
    md5: f7b8212c5a7a4f7a33029debde2c029c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 73244fab304946811ff362e61b3a69c6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_solo.res
  hashes:
    binhash: f2a6c070cd6128058856bbf35fd2e4ce
    md5: 92b6593c1d5e04d475057be4c25e827d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 33a13bbceab67c439f5e16e9182a404a
    md5: 02ecd9f9ddeeef3312bee78ee6a1cc7e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e7b1a51c59c6c57c0363107be1715642
    md5: ba992e69a195ea5aeabb45ce3f5e4e1b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_tracer.res
  hashes:
    binhash: e9bea91f944ccd00c4dd9e867c5df169
    md5: a8acc30ea24e079d44c27eb9585a1686
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bdb5be75bb0a894d70484eff607b14a1
    md5: 5c9e44571e6d5fff7a50c4a2e7d35b0f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5986172f2c4a4bb616a898fa1b95c2d4
    md5: 7ae937349bd00d5f69748e9c175188ae
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e6c7702b757ebe77cd60af8d22c2340e
    md5: 613e0a791f0f5ce43a0fa1113aef9575
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart301/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ebbdc873156151adecf85cb17baf426b
    md5: 79e0e44799226d50797b2eb07ca2bf0f
