format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/atmosphere/restart_dump.astart
  hashes:
    binhash: 6bbce925a3408e9f1814e7ebaecf8276
    md5: d23fa77483539dd742ee63360bbcd3d5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/atmosphere/um.res.yaml
  hashes:
    binhash: 99cd8d03e3f73793d2587ca3a4f3ce6b
    md5: 185d1972eb1321099cdb409ce5b61949
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/coupler/a2i.nc
  hashes:
    binhash: dd65471471b659771ac4b9c7f1aaca3a
    md5: ba6925886dc88ab7a07547a3f7780560
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/coupler/i2a.nc
  hashes:
    binhash: 691018d85d83138edb01423d1b40bf05
    md5: 3848563abe77ddd7a4e15f26e371a0c9
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/coupler/o2i.nc
  hashes:
    binhash: 7350677b50e61dcb2c29668bbf94c19b
    md5: 43dfdd9f644ac13e5f4b6f82e842d390
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ice/cice_in.nml
  hashes:
    binhash: b1073a28498dd43d131c28008079f044
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ice/ice.restart_file
  hashes:
    binhash: 7ddabd1661b90f50196cfbcb2b07917d
    md5: 4c9e51443a1af754a2d4afbfc0e46901
work/ice/RESTART/iced.1246-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ice/iced.1246-01-01-00000.nc
  hashes:
    binhash: 8ee2e1f3adf354be48791cedd07700cf
    md5: 92775d722abf46c644e4d8ef98839897
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ice/mice.nc
  hashes:
    binhash: 3147ea7823d3f17df7b338de60b70d37
    md5: 1e5911ed82fe529e3c3a88db9e4b31bf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_age.res.nc
  hashes:
    binhash: 58237fdc674bc9ac98bb6700bcb60b0b
    md5: 8df05c4c8f81024300819e32b7e757a8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f908dabd01145074df64d8c1f96b5425
    md5: ea6a8bd599491f4cf16caa947b2e664a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: dae170d72b45b96510e8c4d65978774b
    md5: 029d4694a462b21cdc0b79121c9caf86
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_density.res.nc
  hashes:
    binhash: 94eb1f008b14268b7fce9daa033fcc58
    md5: 3e3f18e1847ba3f7c1b6329e4c497e3d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 41a2054af702a8fe339736617b87a2bb
    md5: 9fdc12e8c919b0e35223547b48b0ddb2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2247d83787534663d3e33f22c048f211
    md5: f5a441ab64ad2e88659ad2913300cb04
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7a51e97355c904a77f356b809b9e5422
    md5: b3c96bf7f2fff451e7e98d5b4627bcd3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5e2064b53e68d52aeb4281c53305467e
    md5: ea84ace557ee882419658e8e551e6d33
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 99414e84edb6f4c5495bc563c4e15154
    md5: 2b6501e9f117034747688816a1ed7ae1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fc305e5bf6484a08d78508958a6efa55
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_solo.res
  hashes:
    binhash: 43a6d6d35920ce3abb69e45a1412d5bf
    md5: 6588bc3fa75ebf29ff609b983ce2fa4a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e67f50fec9e4b53a5df2a1dd221eb853
    md5: ce59478a810cc082f20df5d8ac5ed3fc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 85214b5367eb48a3b2c775d281ecaae8
    md5: d85052c1b5160b6b42d7a0054b0b353c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_tracer.res
  hashes:
    binhash: d36379386f91399860e8290cb6087108
    md5: dd04a90a95c7cdd68a7fc62e877fc7f4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 15b00000f4be89cd81e22329b98359ff
    md5: 56fed99853988673531adc0bfb8770a2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 59738878c5061a2badbb7c4fb571b515
    md5: 04c0017fd36771f45b8246b60213e626
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8f36c87e56a0367fa7d2315b4d234e77
    md5: 308ca4a9e193a8699622c97ad977c861
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart362/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c72823e9a22597b20e14f289fa0c5393
    md5: db295542f1e596fc255078d21f4c19c5
