format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/atmosphere/restart_dump.astart
  hashes:
    binhash: 8e4f5d39956a8577af47dc8bdd24dc6b
    md5: 9b41b302c6b606d5fbec0fe6314d075a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/atmosphere/um.res.yaml
  hashes:
    binhash: 4cd040518338c6da284aa6f1953067dd
    md5: 033aec13267b57b8d79eba8dfa19f0df
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/coupler/a2i.nc
  hashes:
    binhash: becb2f49a75d36ae871c6594b08d2c1a
    md5: 8ff1e2c9d76ef9bcca8204a1ee2be984
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/coupler/i2a.nc
  hashes:
    binhash: 0b19b5a26e2a5e225ce539ec75b329ba
    md5: 49725714fad48327227ff2c1c25aa3ca
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/coupler/o2i.nc
  hashes:
    binhash: a012634606af5e16c237b06cb32f2446
    md5: e959fab1b7b0486a7f673ed218b027bb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ice/cice_in.nml
  hashes:
    binhash: 36dd7dbc974ba0f29dfd547e23642032
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ice/ice.restart_file
  hashes:
    binhash: f5a75c68f3a0dfefc9d9a2a15d4ce35b
    md5: 70da480bbb2077ff2405bbdec2738907
work/ice/RESTART/iced.1819-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ice/iced.1819-01-01-00000.nc
  hashes:
    binhash: 572bdc7fac02abedb1941df185fec988
    md5: 1416f935921d3757f412074b6f21792b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ice/mice.nc
  hashes:
    binhash: 2c60de0983ffd0aafebd610aef114d38
    md5: ad4973e1a5b795286fc2464621e81fdd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_age.res.nc
  hashes:
    binhash: 7793fa0250f35010d79effb4a28b7a1d
    md5: db91a5036dc2c5deb64b7efcf83a4364
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 005c911c7670258be5ab62c8eb9ca1ce
    md5: 41346afe9e08dc48248c9e4583fcdacd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 595dee4e3b75965b621c9949602a74f7
    md5: 76bc464dbf610150598165293da76a36
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_density.res.nc
  hashes:
    binhash: e82da4c11ba384b6a9eccbcba2cb0f42
    md5: 0e79628ba25a106b33f5df33844cef0e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 51d7aaae84b932465da847683c610c73
    md5: 67c03976f1078d1ade28c79f9cc21453
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 094970faf2b335e86437e0a692a46038
    md5: ea1de0a8bc31b50c281c4f850bf45809
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d4b4ba8fe39de778f26771a9a267cb6f
    md5: fe8c6cd9bbb945f753d574c6a1922999
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ef5e3ae2bb1cc583e2b50222490a9528
    md5: 100adb1e035335d7790f5700bbf3fdca
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9e8e47a1c1ab0ed29410260a8c4c8b74
    md5: d5aaac8738bfcd527c2cc979466bc161
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4e5a6e4c10efba062a8f92656c180bde
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_solo.res
  hashes:
    binhash: dd263d769287930d3a72025b62e32f62
    md5: 7f064f92c36b378c691616f9a1b7c59e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7291888275ad900f4aa8103e4039e7a9
    md5: 1290047333cd8cc306c4046abb17625b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e32d5798ba4eb47a72bd390f8fb7bd0d
    md5: bf5a9c9595205a5a98a9db9152947ea8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_tracer.res
  hashes:
    binhash: c89dd507781a2ece8e6192543e69bbcc
    md5: 1030e1ce0de993a98958c71488561145
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_velocity.res.nc
  hashes:
    binhash: aaa2f3f2aea44e2076b22bbb11caed65
    md5: 0318604cb07d8eb06b6c16ef48ebced2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e38ccbd46314eccc3472834aaa3496bf
    md5: 8d473acb74ae379162b00ba6c9c9f255
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3d5c2ee35bb97003d797e9a069b775c3
    md5: 98c86f2bc7c8dfedfeadbb459d59e648
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart374/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1fb0178c629eb3a39511cdeebf8b62c4
    md5: a652cdaacd18fec0e388ea683da0e9f9
