format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/atmosphere/restart_dump.astart
  hashes:
    binhash: 87283029ac24752c67f76ab84775e23d
    md5: 0984af6aed84295210bd77b0bc518d9d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/atmosphere/um.res.yaml
  hashes:
    binhash: 7fa82b26c3371dff94a252caa7abbd2f
    md5: 79e2459a7f905e37a0652b6685ee2ec9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/coupler/a2i.nc
  hashes:
    binhash: 29cf2a0c81bf9eb28314938362ffbfe1
    md5: 7859fb22b099cf3e420eed86ad8180ae
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/coupler/i2a.nc
  hashes:
    binhash: 4e0ffe20863cb5f8e38235621df7f50f
    md5: cdc6e082aa8eace9a1ea98a5396d19b6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/coupler/o2i.nc
  hashes:
    binhash: 23ea4e459dc54d6b2929c1701673b8ac
    md5: fdfb40c3ec7a6513551528897a712838
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ice/cice_in.nml
  hashes:
    binhash: bb5cc4b0338d77728863042c7e393d2d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ice/ice.restart_file
  hashes:
    binhash: 51f99ba6534c7c14ec3c245d65466b59
    md5: 7744263207a8e014344f9e3ec1cf3bd2
work/ice/RESTART/iced.1278-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ice/iced.1278-01-01-00000.nc
  hashes:
    binhash: d699890c3623c042c2573ae7003bffaf
    md5: 540db53731a4ed439dda3840b5ba6b0c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ice/mice.nc
  hashes:
    binhash: 504a1d48042df4364d405ba3c41e8c0b
    md5: d5dfa409c0625f9ce81faad9f3ef0d75
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_age.res.nc
  hashes:
    binhash: b1ecbe849f5023bea1c473393293ef6c
    md5: 6f6f9dcab82cd7ea4a20dd627cdf6d0b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 78640fd3a6c0c8ca3896d938a1b72c2f
    md5: 21280e49417dc9da85e264b113426485
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8c291552bfc1be48ef03ea37cb3e6cf3
    md5: a0ed6caeb25141891c28a105ac66df21
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_density.res.nc
  hashes:
    binhash: ca2b17cabb98826f208731c0291e2e3f
    md5: db91357b7b0ad966408e2bedc63d02cb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a1af2b71d3248ac5a759c97aee88800a
    md5: 0bdb5b842d64709a06b1cd673f63a0e7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6a06eb87e72a1e821b0411071d619ff0
    md5: 485ca36d33d19c29e2cf54b5d801af16
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fd8a870d8ee5a2c7557c9b053a0179bc
    md5: d591f8ab45f70a0443e9ba85c774b538
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 89f0e9bfc60b2dab7802e3048ee554a4
    md5: 411ebd3151254217190fce395d34d81e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a4ade8aecba5fde4eda9c07d1ab00712
    md5: bebdc8da9f7daa963a29b168b5163470
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5b829013c09544669c6e51183e71b343
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_solo.res
  hashes:
    binhash: cb24eeea04f289ddc9ed5b9b248c5da9
    md5: dab06e95f05617a736c395544ad6b221
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 45649052ceb799bd6967ce364d0c449c
    md5: 140bb69da7e9772539e73443a027e6a1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 24e084326f54d7b7ac0e571d169e2a0f
    md5: 8bf00663a31912b0903144f5406d548b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_tracer.res
  hashes:
    binhash: 93c6be3ec933fdfdcfb006108a2a1162
    md5: 4deaf55bcd5c226a05a16211de45b499
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3ad51c690e861987b2e652be613cca06
    md5: 0fe5d220a0df46198e6bc984daef8a85
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d535fdab7093ef2c65a0cfcad25130f0
    md5: 44dc11cea05dc1fe874c3d51311e0305
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3b0f331e3dfac3d93c3e541dfcab96be
    md5: 705c4eccfe9b6b4c62d3ff5fe79ce43b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart394/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: cb506263f799dd54a4c9cd84f2daa49f
    md5: bc524356d0f62603312e45ed029b9e62
