format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/atmosphere/restart_dump.astart
  hashes:
    binhash: 32f348f625d7a0f8e634ee2b5749b78d
    md5: 9f551d5c5d875c4ba7d3ea853f270b8c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/atmosphere/um.res.yaml
  hashes:
    binhash: c6e59be46c850402d2ea3abb4299ed37
    md5: 312ca73294baef8cba69f1ca9932cf93
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/coupler/a2i.nc
  hashes:
    binhash: 7c7e7eaf02345def1c1c691f7ee7f46a
    md5: 288349e4c10778bc3bc2c1d73d4be044
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/coupler/i2a.nc
  hashes:
    binhash: be51fc8e18c6b9d079a934c2eca1e9de
    md5: 710e7ba689d3ad588512351f54f1ee4d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/coupler/o2i.nc
  hashes:
    binhash: da36cf3e4c3b63d8eb1cfd82e245477e
    md5: 770096db536a02ec85f8d042137fe09e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ice/cice_in.nml
  hashes:
    binhash: 41a556eee7fe236bd2f044750fbe8012
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ice/ice.restart_file
  hashes:
    binhash: a574ceee7e34a0ce04ab588a6282e4ee
    md5: f4764791065499202418b34cfdd232ba
work/ice/RESTART/iced.1303-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ice/iced.1303-01-01-00000.nc
  hashes:
    binhash: f96912edd7d32992597945f58f69b07b
    md5: d1fa1441c904c852eb6402cef5a8a3ae
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ice/mice.nc
  hashes:
    binhash: f4ab8a5b1f4064a3c78b92487f0d9471
    md5: 2714568d980574712962ddaff6f835ef
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_age.res.nc
  hashes:
    binhash: ce4a52ecad6d5a8d350ccac4791e0b7e
    md5: dfe1e0b7af94758d1efb5ad59898e7d7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ba39e5369da67d60dccae544ad946018
    md5: d37a0467a3efbea7937c8fdedb234205
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7d32f4709502f7aade1a562814f9f519
    md5: f9e3727592e08bb45d7d22370e444360
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_density.res.nc
  hashes:
    binhash: 7f78d9d8209dae0f44dd29689089b494
    md5: 71ff2595d17d8881f2fb912e44309d66
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 67448b198a0c3f7c9982a119ce68e668
    md5: 598f3facb1ec5915262a03b69ef36615
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b9b70498a4c24f7a9f91662b33351eef
    md5: fc7bab690f0fa5595942d4da20cea4ba
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 844a7f3f20276f9b63bb3498082dc1a7
    md5: e32cd1d6b7b34584db625922612a6192
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a172ce2547ac256492d79c4ba4193bde
    md5: 729f69630472d53e316fa70577376c15
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 49bdcc6dea8355280b1df500e6e99c5c
    md5: ec6f6564823e255482916309abf5eca1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f487987dab0037c3fe01120e6c13656a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_solo.res
  hashes:
    binhash: cbcf15b89246297e2157d92fd6226c7b
    md5: 9c359649185f5443b1117ff5071042f3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8662809fc8a6a401eecddc8e024b4f32
    md5: 812ef9354c7d44117750b96239500539
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2dcabf21ed7b0e585319e1586579f2f2
    md5: f5419a0b7ace0a0c6ceff1393d6c4548
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_tracer.res
  hashes:
    binhash: 8c13d9e69c8023f9c74f5a1b4cc4bf38
    md5: 6480f5a2dfd48a3864110fee1942bd00
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4ba52b88c1443760bb3118c92857e5cc
    md5: 1997b77697a7227967d5e41c4bf89f97
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55bd405551a242e97823b9243208118a
    md5: 2117c96a46ad31554587b27d5d697682
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a8111bec1ee35277f6175e14b2f3a799
    md5: 6d7954bf7b93d6ab76d4878d7e2e9444
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart419/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 195dc40c08c33f6d6f51df449525728b
    md5: 0c92976ccd969ec2b9bf74d11a8e131f
