format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/atmosphere/restart_dump.astart
  hashes:
    binhash: 62734e7695f183db131b0519d645f1fe
    md5: 5963b91a43b05e5c26a7a5557f9878df
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/atmosphere/um.res.yaml
  hashes:
    binhash: 02762e8d516e3bd48c4a60f5c60112fa
    md5: 3ed29ddcfac2b71e6616f985c1a7e006
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/coupler/a2i.nc
  hashes:
    binhash: 355e8dffb20617f6397e303854c94e49
    md5: 9e21e0e3bf6abe8a01016209506b82b4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/coupler/i2a.nc
  hashes:
    binhash: de3baab351e8b332b15c2522bb04749d
    md5: ae61300e25709007886ba6d910849886
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/coupler/o2i.nc
  hashes:
    binhash: d3c3086cb5f71840c973a295825b65c3
    md5: aa094f6518957fc03608613288bc4335
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ice/cice_in.nml
  hashes:
    binhash: 18078610adc9a327c222428696342e7a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ice/ice.restart_file
  hashes:
    binhash: 9e786cfd45a3d5182ab507e4ddb25ea7
    md5: 8c4d42a54ed386f9622e16bed22eabe7
work/ice/RESTART/iced.0988-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ice/iced.0988-01-01-00000.nc
  hashes:
    binhash: f43ff6fcbed9f341d37c25f19d4af902
    md5: f28d75d2a41658c687f774fb2fdab5bc
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ice/mice.nc
  hashes:
    binhash: e24b925e7ef9c5b463ae34be50a9db11
    md5: da6f355ef1c6c437747d665abca70308
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_age.res.nc
  hashes:
    binhash: 5c659ffa6afd6e5fff92a4c18ea5d43d
    md5: 2ee0c55a94dbc983a948d8e7149763a8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9ad8f16942cc072ddbd7a504714adb19
    md5: ab688c24d5b88846ecebc83c0a1181ab
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a06a05a76edf44370b58f13b38a73843
    md5: 22b8ab269550ef52454cd5b7af6350f8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_density.res.nc
  hashes:
    binhash: 68773ceca7d51f6d49504749d5753f8f
    md5: 2510fa9cdf20f411f9fa9cfae1153fdf
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 40151491e4c555ee1d5dcd90669e2692
    md5: d773d362f2cc94a09463950d7f11aad7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4fb95340b3b6ccc0f99841681f69db44
    md5: d8a5630f2beb17656cb82055c47d9f33
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 428c0ce0dbb0cd410ae0002a9dde6379
    md5: 11baf4e6287e91fb525e35fdffbe38c6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c955219e84c6e59066882769b01fa6db
    md5: a25b223a4655ca596928bbd6dc5c2abe
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a3c605f33b9a6735e2dbec4ab065654c
    md5: b659d940c3e2848271902899791cb16a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 191e633f20de1c64e727b8fab3f4352c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_solo.res
  hashes:
    binhash: 935651e59dabd0c21216193daa21acd3
    md5: 0e1d5b65f19de2f70d11d3ac72224f9d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e363cca2002614a406290955ef130628
    md5: 2efe036808b819dbce97fd0584bd89ed
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cb7dbbcf7a531a2254093c833cd9176b
    md5: 247b842920c24868841c5e4a4e91b2c1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_tracer.res
  hashes:
    binhash: e98279b0c1e8d4f8e0236fc3a7f8d717
    md5: 664f195ef041d95f38289e2dc6da9789
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b153182828d81ee0823bd5fead85d414
    md5: b6f46c1ec0e30110c42266da37a89bd0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 95545b3caa1fd1068352e31e7b9e263a
    md5: 9da34a6d6c05789c5f2d42004b9c85f4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 83cec6d8b660a34288441c18decbaa3b
    md5: f72bba6689efa32e0c25817e17d666c0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart434/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e64209a45c11299f81c3b59c900a8bd6
    md5: 5a7fdd981fd21ee2f4222d320b7b976e
