format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/atmosphere/restart_dump.astart
  hashes:
    binhash: 5fbedab993c1e3ad392aff00ec665f10
    md5: a1f459ab2eed31f7d6296b486e44511a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/atmosphere/um.res.yaml
  hashes:
    binhash: 4fc5758e47ee18b881abd759080c92e4
    md5: e6eb8e5a0f5bade192f9909b6cfd1d38
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/coupler/a2i.nc
  hashes:
    binhash: 855889ed194fa7cdf9dcbca822891549
    md5: b18d65442c4603b14ea7d497c94baffc
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/coupler/i2a.nc
  hashes:
    binhash: 782580311b0ae833ad8882e82307bb16
    md5: 7fa13de7d127ad18d7d23ea8a4450450
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/coupler/o2i.nc
  hashes:
    binhash: 6ba8f0384dd440650b7b29d746a10119
    md5: d00eff33d8ae3682d213312f925cd415
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ice/cice_in.nml
  hashes:
    binhash: 36ab212342e1e0412d49d77519582a90
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ice/ice.restart_file
  hashes:
    binhash: b724f9e0b674171c4e3d947cca8ac056
    md5: 5349906e2b69df253c3435ab3f344668
work/ice/RESTART/iced.1815-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ice/iced.1815-01-01-00000.nc
  hashes:
    binhash: f999c6ea35697bae07a9c1a7b62220ca
    md5: 8b477c653917028af10ca56b99b23917
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ice/mice.nc
  hashes:
    binhash: e3aa71dfc0d2f24294970e7bd7546bde
    md5: 8b453ba5c6eb9bfe2266b74b63603b47
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_age.res.nc
  hashes:
    binhash: de1dd3e9a9931e4ceef9875f0a452e1d
    md5: 9a30f6eb11bf6a08128c34f486211f7a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d75236a7157d17cc0667b302127cf1fd
    md5: 38011251e16d69619cec317ed775e85d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d4d60181973e7b7a2653b9fd7c608666
    md5: 1bb82ee4ad027c09eba992ced6127b44
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_density.res.nc
  hashes:
    binhash: f35da297c385dc54f97e5e6b89bce512
    md5: 9b7eebcaae632b09d3c4c0512ff6bd68
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 740c9167b96db24ec3bf1bca46219f0c
    md5: f6bbf3284769e0a5633fb92ec0efc40f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ad2b02a479558e22b7f2bab7bc78fa01
    md5: 61efe27175503fd3ec75f4f9b5787225
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 8c13885e64e583f98b0f590356a0e0b1
    md5: 5482bd06e0586222580ef88642ec60f8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e5f8e1facb0cbdea358609c65068c49d
    md5: 2fbcdafcbad5b691ddcdaac2c1ccb779
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9b410701db4eb3e558145bf738eadf09
    md5: 7ec3c2e7b924104b14e7d7a2cd2f255d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a065091f77b527148879eb6f25f0cafe
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_solo.res
  hashes:
    binhash: 07e7d8496b5508a3e59e0c7f86efff51
    md5: a96941a0acf03ddaa70f99dd1fd47c9a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1a959e884ae7c9bbc81ff699b48e9f36
    md5: 2164df19b9d24001a7bbc71a80c5b257
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 58b05618b7bc88579c927ef952941b50
    md5: c313de5fe84517af0a4fa68bca6b12bd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_tracer.res
  hashes:
    binhash: 1920e0d52081ef9f80095bafebf85f20
    md5: cdd48be503e92cf85c4bdbe4aaf8ea7b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 85852478770ed1c75375c2b81b820f97
    md5: 2691627e0643cc2167dfe494daae2688
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 34fa7a75b2d7dfc4b3af337c6d41e14e
    md5: ace6752a8f9649762fc9a1c96d8fd87b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bf853e5e913365abd055d3474dc42681
    md5: 73ffa4959aecbd4ef7e8d30ed6dcdbcc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart370/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ccf205ddeccd54c12e6ed2a5d4541ad8
    md5: fa903ca099d4cf2c7c34bb6fb2db9c76
