format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/atmosphere/restart_dump.astart
  hashes:
    binhash: 3d5ef8218a6fa4acb38346c82536ff2b
    md5: 430888328dd0fac28bb146f4652867b6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/atmosphere/um.res.yaml
  hashes:
    binhash: 9bdcc0e205dba18c1affe25696ab067c
    md5: 352e51f21d03c9c905ae25235529ae0b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/coupler/a2i.nc
  hashes:
    binhash: 1ddc3bdf1421701bc9c27c3bee8c916e
    md5: cfe3ac88862e79ba111afa1612be79cf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/coupler/i2a.nc
  hashes:
    binhash: bc5c39c38d7f963b28601ef6ea6ccc63
    md5: a85285f74d2d3eadd79a693978884703
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/coupler/o2i.nc
  hashes:
    binhash: f221086126a3c92d9faa186d53cc863e
    md5: fc82d47bae190dd2825aca4799e41f82
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ice/cice_in.nml
  hashes:
    binhash: be61f34ff7d1069693f5f5b460b10944
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ice/ice.restart_file
  hashes:
    binhash: 4910bdd203945203e4dfcd2997a14feb
    md5: 38dd070dfb25fcacf4f7ed8b6f0edb59
work/ice/RESTART/iced.1239-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ice/iced.1239-01-01-00000.nc
  hashes:
    binhash: ceff5c04deae15308e3e5e722296e517
    md5: c604c9a1d4846e1b8d1a22ae6b2ad6e5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ice/mice.nc
  hashes:
    binhash: 43bc14c05a64298d163c3abd0c64c7a4
    md5: 47a8837c605dbaa9ee39647284357603
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_age.res.nc
  hashes:
    binhash: 8dc69288639ad4f7da267a5615cbcd19
    md5: 6de19f3f3d3a2de13ee33d5d3d182791
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 06eb5760d656a03e24460f726cb58d70
    md5: 8cfcce88b1486bccae2bcb130ca51fbd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 605960b8deb638b972853a320a07aee5
    md5: 93055de02db9030f3e5a55b43e1210cb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_density.res.nc
  hashes:
    binhash: ce553988f7b47d181b923777283e6671
    md5: 9551349565f270159f797c093653ee90
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 48e2c9d489bc3243062dab2315d7eef0
    md5: 8653de51d8ffcb5ad450bd8a034b4a41
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0c7522394cae908d73d1f82477198037
    md5: b12a51119bf33734dc06e4cd0e95f217
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1e705411356f58546b0b315418e4f2bb
    md5: 96c9b95987b1d1d366f10242f6807c38
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 282fcb68e95425e7026b9e66edc90a87
    md5: 57215c2b48065dc6fe6a9f41018200da
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 289c905401c244b1ab334dd00ea26ac7
    md5: 0b75cef8951fd1f440aac66342619a45
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 89a24195b8610b8727ac48a8a64727f4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_solo.res
  hashes:
    binhash: 595facee32a87a9e20cb911ae4e69a77
    md5: 323a504f1c92c2cd7b9c9c59c0a24cd5
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 41b8221161ec1b07d12e8badd855a19d
    md5: 28349765eba2d6efae714e7e1c83278d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 228a06e51d832c88831f41f7c1e0c566
    md5: b091c66123108e2185f32e09452c0816
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_tracer.res
  hashes:
    binhash: 5c944e84248f29ffc9add0e464ff2ff5
    md5: f5386d5f31515cd2c19e61dcd7f239b6
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5fd47d7bea276643bef88f21aa5d6265
    md5: 7f43f07adae867e426f950dc539966a0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a6460a13bb194d1ae76332fed345b9c7
    md5: 14159165a14d9ee3f5970a8d091d76a8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0611425b37e623b8aece50ba0baaf474
    md5: 59f38c6bfcf4eb7b64cb41cbcfbb0ab2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart355/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ff8efa25162f8852f3c0000c92a9ec74
    md5: 5f3756a6670518c5403d98b5575f2246
