format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/atmosphere/restart_dump.astart
  hashes:
    binhash: 13cf68f1caceab160f2a1fe87d6f0f6f
    md5: 8f86e287048bd5474304c6b54cb4b506
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/atmosphere/um.res.yaml
  hashes:
    binhash: 8a32733e97fdd06205d6093bcf843c9f
    md5: 9e260c9d166a9278d25605bc9b021df6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/coupler/a2i.nc
  hashes:
    binhash: cc9c922fe0e0b186f7d25387f61a1514
    md5: ee15c9ac0aab1be024c550376d58b2b8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/coupler/i2a.nc
  hashes:
    binhash: c69b7cdbfc99aed12e88c92d21881f65
    md5: 4e08715894adadb2f5da53f1bc85552c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/coupler/o2i.nc
  hashes:
    binhash: bbb8bb761dac99ce2660196588f67b24
    md5: e3362805dae11ef5ae792b179a422657
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ice/cice_in.nml
  hashes:
    binhash: 28c493b68c53fa76654ffb345d7b2e0c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ice/ice.restart_file
  hashes:
    binhash: 709985b566d3f0dcb3f477ee8b1a1363
    md5: 6abb296dc6a1d314ba50e411dde9b09a
work/ice/RESTART/iced.1235-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ice/iced.1235-01-01-00000.nc
  hashes:
    binhash: 5d9cc1cd09bae01eb58b2f986bdf696f
    md5: f7d304ae9a5a61e1d36dbd182285d2ad
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ice/mice.nc
  hashes:
    binhash: 211776852ea267c10d1e84d5b9f3832b
    md5: 287e41c79eacf12d9f20a972dc90096f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_age.res.nc
  hashes:
    binhash: d4e1be5e9962a513487a3c9f206911bd
    md5: 260660b87e19ef91b2827bb8dee49941
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7a61265b62d70012eb3daf63e46546e8
    md5: 94efa6f10bacb8b30782e07316692103
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b98fa45d201972b16089ead7caa1e525
    md5: 6de0fe2885e93b4ee288537f5c401e6c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_density.res.nc
  hashes:
    binhash: 60d5ed00a897616a5fcff9da1bf16b58
    md5: b7832e6f6e9573f9701f64f6b97e1ed0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 56b6ec382de8a792cd509a31cf08664b
    md5: fdd71f258c8ab33df46e2fe3e5385792
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: de377d271b868ec944847cebb304c653
    md5: b4657ac4236e86b9b1b767df5bb3d24e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0e5d3c80d7f7fd2031e7bc587e90c07b
    md5: cd7b16ff2b947082477c4cba3f3514c5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cf69cc755b4202e9556d753ead48df4a
    md5: 480610a269a690961bab8734bf67f03b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cf08e454159d33492503a03ea7e4ca93
    md5: 756402de56956897d77b62c9bb75689e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2cb0a5b2bcc8f1413e9dc82447295c20
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_solo.res
  hashes:
    binhash: 4b5720f80b8ca4eac735335c7cd285e5
    md5: 59a159792a738dd723fc69d09b509cdd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 90c53d7c69c2d33b528c291daf784e6d
    md5: 34c908c8eb6392b0ea0d1263cdde0327
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b1765d5a49eaf82a920b95df5e7123dc
    md5: 77cc9d7eb4a18da29200791cb0cc00e8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_tracer.res
  hashes:
    binhash: 04b0004e59972408104a79ecdad9a797
    md5: 6d1596558116aec04db762cf01bc85b7
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e8ee210b1ff501159dd2db6946ef1e9e
    md5: 03574dd69d0d014c864e20e1d06f60e5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ebfb157b30556d5858554462defe6720
    md5: 185d38e03e4f293bec2f36e28f401c75
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3838b8e1d13177e567075c4088f743b0
    md5: 5fe5bba7861d0f25208370888ce2e690
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart351/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 593d7f00e3c09f6546cbc1be2e217fdc
    md5: 47cfe492be419e57d46df98c60d2c601
