format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/atmosphere/restart_dump.astart
  hashes:
    binhash: a3634e8959a7544479498998ff7692cb
    md5: 2b8eb07a7b19c4fe99338cd892574265
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/atmosphere/um.res.yaml
  hashes:
    binhash: 9234a09ef2b6d3a000ec6cb53fff0c75
    md5: 8d2e65e48b8918fa69036810b660ec9a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/coupler/a2i.nc
  hashes:
    binhash: a9aa2772470fd95d02e34ecd7d718b24
    md5: 1eca10cf8d9e2e049222d9a1fe78fff9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/coupler/i2a.nc
  hashes:
    binhash: d209dcaedbbf788826c33b71cd976939
    md5: c04e8edf3b3d33f87917396025d49b2f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/coupler/o2i.nc
  hashes:
    binhash: bc85aec5322312785c30ecf9dcd3eb05
    md5: 9732ccfd901baef41eb528f628c72ddf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ice/cice_in.nml
  hashes:
    binhash: bfe7411759dfdf07cb8491c6d6ae2457
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ice/ice.restart_file
  hashes:
    binhash: f437c5cee3a4bf9374e2c0cdab1d4ded
    md5: 6665fbafb4b6faab38bb0a56258b671d
work/ice/RESTART/iced.1251-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ice/iced.1251-01-01-00000.nc
  hashes:
    binhash: 5bdf8b39d282a96435a5bc6056c86228
    md5: 5e8d25872991c6cb2f36b43e4ed085d1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ice/mice.nc
  hashes:
    binhash: f037e0596b45d390266ff43017f0bbec
    md5: a31878ad1c8baa367d46b8183f337675
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_age.res.nc
  hashes:
    binhash: eea06e541d95111d30c3c7a2e8dac374
    md5: 94acb211648bb2348e9501c9b88204f4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bee0a09a6b58002313cf4bc4e0174d82
    md5: 7a4f42d44ee9f024e3aa8143e6da749f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7648d0d8ca889e609d7009ea2f603353
    md5: 980fbe002bb2a1f3061a0aa0016adc3a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_density.res.nc
  hashes:
    binhash: 8d17d04808a069a0f8cd368c5c7bf7cf
    md5: 8ae7f22284cdd74c22fc2d37a420cded
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f47a952b658050d73a2bc698e6b69559
    md5: c204167f508b2d566a12347d6f797aa9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c9495f99588beda949dc5e3de703ee55
    md5: 1f680643886ca0bf9bd28e86971ae54f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_neutral.res.nc
  hashes:
    binhash: af7638f0d38eeff2f73541824d3aa756
    md5: 77398ac90c9febb1f607ba36b4710a75
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 73df48dd247ae125dfbf6d8a386616c2
    md5: ba7427e9437cedc009d0825e84cea194
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 794676c7c7741b66c4476953d2b789f1
    md5: 16f03ed64afc82f1b3bd6514df821f2d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8557edf02e430cf271cb2bb7e4042035
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_solo.res
  hashes:
    binhash: 10ec516b126de994347a30bd5136bf5e
    md5: 875ac1901efeacb306c45e079c00505b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 86e5c7918cdc94fa9b7f40e75162db1e
    md5: facaef6d0911990f3e2666b1b25eedcb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 819c1feeba2bdc9206ba3a3571d2b63a
    md5: 652985d410aa84098a46c43fcd0f95bf
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_tracer.res
  hashes:
    binhash: e11b426a830e8321502bacf2580282b1
    md5: 8eb08b1d4941d996a21a219c364b6a32
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2a521808e7fcee5c2496733f56ea746c
    md5: 032125330d8b7b2984bc3fac531fda73
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f1afeb0c6168ce608582348d55096b07
    md5: 0cba68d6375bfe3a22c69f9329889985
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d731160ab6e07cb67f7d8d282eee5a45
    md5: 575f5054ab3b9184ec71f3380c8b016b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart367/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a2ae80123b3709e055f1d486190b11dd
    md5: ef6a704e0294209388c6728417e9bcc0
