format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/atmosphere/restart_dump.astart
  hashes:
    binhash: 4c0c26acff6ade1d075660c29bc68b3e
    md5: 37a3fc4f38ed19ef8c12f047779d584e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/atmosphere/um.res.yaml
  hashes:
    binhash: 449767e7894559979a9ae7e2b75073c7
    md5: ca37e2fdc980ce811cdd9ed4c5c18ad1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/coupler/a2i.nc
  hashes:
    binhash: 793cc253ebf4f9eb2d6122c370b6eab2
    md5: 9449e63e20ad19f60e0126062ee62d59
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/coupler/i2a.nc
  hashes:
    binhash: f4cbe1e27949150619199741aebe10fc
    md5: c9e4ed828ccb9addbbe7fbfb1b68998a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/coupler/o2i.nc
  hashes:
    binhash: 4f1cdd5bfca999bee236d85f902b5567
    md5: 3363c9793427c7e452aea68892382ceb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ice/cice_in.nml
  hashes:
    binhash: 105da8d9ec1793f345d6b4ef19c0aae7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ice/ice.restart_file
  hashes:
    binhash: 46a338304c266043acce2ecf4f082445
    md5: 23a71e1b13a891a40b9a41b75ee965b0
work/ice/RESTART/iced.0972-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ice/iced.0972-01-01-00000.nc
  hashes:
    binhash: a43da4afee15581d971c85d69043eb01
    md5: 284a4190454d4d83236179630f59427b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ice/mice.nc
  hashes:
    binhash: 9a6e8de5094c3b8172df017729080152
    md5: 24567f2e15ff4f0816b1e855228753c9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_age.res.nc
  hashes:
    binhash: 4e73725015c87fc4a5bc34678c6f0dd8
    md5: f651aca5c47e477072d4372402020f04
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a862533ac0d856514203c455227bcce5
    md5: 58973e3d81a156e960e06f6425a810a7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: d69c993f9227fa9d27217b22d0f0a8c7
    md5: 56362ac7f3b911f50a3b9df1eed3b099
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_density.res.nc
  hashes:
    binhash: 91c44942043d06d3693ab77e8d3ca947
    md5: 9fbdf15d935073cea841d168d24ffb93
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9ad914ed39219b728be056450638b6d3
    md5: 4c46a05cc70afdbe303bad98afe78f93
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cd521e8cb7a71c0cfd3409dc594bacec
    md5: d1a30bb01077f66337453c3848455310
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6549516b6c90cef43a2ed40bcc60df84
    md5: b5ff3087a268752a5eb8033cf4390064
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: de4756addeb75fa1f990d244bd752e21
    md5: 503bb68c89c9869ac0f31a863d19c633
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 307077bf6d38e6be378a05addac87509
    md5: cb0b927b4011f66d1eb34043ee60501e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f3581c4c84abf6184f8e32e8ca05928b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_solo.res
  hashes:
    binhash: b130cca2a1f3ef316433d064ecf39781
    md5: 20ebe878f60b99de6d96c311197e66cb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 640ffb2b6ee07ee7abc33262fa0d8780
    md5: 0fd71bc580367bf7b795047f8a714a03
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4f5f87d5d6b99d9a244f7c67c710825d
    md5: 21e0c420f1df5a3a629cb5cb97956920
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_tracer.res
  hashes:
    binhash: 2b33ab0e78b6877bd1eba83490cd0dbf
    md5: f09be019d72d95917dc5ddb6ee8a7841
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d242394a37252a181b0c68146d54cc5c
    md5: 8d1c7a2be8a9ac15d94fb9e2358639b4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 326c0a9d1801ddfa1b50ae707126d42f
    md5: 91bfbe8e0fdfaf2f4818aac961890182
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0bba220225c5d88256a54f96ae3eeee1
    md5: d87e6765368c91d7d6fa8e977665a0b7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart418/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b811712f2afd9919cd30cd492adaa927
    md5: d0f8fa6650ebfb02279c1afeb624ca9a
