format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/atmosphere/restart_dump.astart
  hashes:
    binhash: b239c2b4aa457b68ab55054beb83413c
    md5: 5b2acfcc85add31801d61b541f5c6eab
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/atmosphere/um.res.yaml
  hashes:
    binhash: 5c0525c4186bdc8932c477e772b7e8bb
    md5: 206fec787ff7c68914efdeb83eb7d28e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/coupler/a2i.nc
  hashes:
    binhash: ddf7255af880fdff31d5b9aa9cd3aa43
    md5: 4a46c7d2a9f99ce8217ddb32389354ba
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/coupler/i2a.nc
  hashes:
    binhash: 37778f06835f5741ee29ed73f3043b69
    md5: 87ff955917e9c5dc27d84cfeea03275d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/coupler/o2i.nc
  hashes:
    binhash: f29d823ea5c7adbc62a0a1f97fbb44f5
    md5: 9ae7ba5d352f4f6a45946a80c07dae8e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ice/cice_in.nml
  hashes:
    binhash: 96bace83188fb44bc7bb9a9a3ddcc56c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ice/ice.restart_file
  hashes:
    binhash: d2b83418bd959cdd79fa41adc7d4a920
    md5: 05d4acbdd59d7d0fd5c52e4a8ea1b67d
work/ice/RESTART/iced.1248-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ice/iced.1248-01-01-00000.nc
  hashes:
    binhash: 1678e5a3c8a89c7fd82e20078fd6cf9e
    md5: 83a297f3ea44e1d3e9ce31420ad9f3b2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ice/mice.nc
  hashes:
    binhash: f996bf278678e9ec570185cd0d7f7158
    md5: f7044ff2aee66aa33b6e2b5d7b4fcc49
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_age.res.nc
  hashes:
    binhash: 2e8fba052539d5f3eb6afd2405d13a4d
    md5: d3b37c1d6d2b93c80a73e777580116de
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 556a37980f8c8da6ef8baf8be67e8a99
    md5: 0788b0664b2982b867a0ac924ac521a5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 202e343602b742e046a27722da930b9c
    md5: fe34e03c4f9e39fea4f481fb2a6b9ffd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_density.res.nc
  hashes:
    binhash: 9536f52b5063f9b4afdf76e8b9563dde
    md5: 2e5e752570d7aa4f245f1d2a89530d32
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b87b87750e783e256c591e04d792a034
    md5: c274c72a011a51bd18459c8068ba5927
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9b4a51fed6f658a896eee838ea4ce7eb
    md5: 40e9c228c2cb2ea63129d318111da705
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5cbcb600b2894caedb5c163935f1bb51
    md5: e55cd7ad111ad8de076835c84f9a293c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1b8b9aed9689bc36e88b5fb53d0118b6
    md5: 639273927f643f32de8c01aa388921ab
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 88408ff11b8a6954e797d9666c6b2973
    md5: 015bd926f566f2fcc562d5512bc7bbb1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6545a20e9440673475251b5d710f6a1c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_solo.res
  hashes:
    binhash: 56ca5a217f558613482ea358192879e1
    md5: 183fbc579e7c7acff469f448924dbf23
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e454c264ef709c439038e568c4a6deb6
    md5: 18b2dffe3b00f44e3537954be2e79ec8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cc2b9c8956bc5846870c22b1f091b348
    md5: 864334bf172891994aa88e2e0ea8e4f0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_tracer.res
  hashes:
    binhash: c586b0e39ed40e511459fbdd93b8f879
    md5: 6e72f987d28d6e0d5f698c4bb96aa883
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0364aafe6a5d39178942ea151ddf866a
    md5: f1e4e5138a9e2cce95b618634f60f685
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a96d67280414934bf293a214fade83d2
    md5: cd72a47402f18e0fbb1df73afb301e3f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e3b76b5f63c70b5204fe91ea4f5acc25
    md5: 9b1bfd23e18b6b035b854081c8382d37
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart364/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7f89c5fccb4e524e0b14d5397884e2fc
    md5: 756840c2f868122b8aa3b3fd38e0ec74
