format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/atmosphere/restart_dump.astart
  hashes:
    binhash: e3c5b20afc9a746c2b5449bbb06b7923
    md5: b7423ddbec442371672ebd8fc1610a55
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/atmosphere/um.res.yaml
  hashes:
    binhash: c079d7802025a719be485754054a8201
    md5: 3295743f0cca5c3da3e9068ac3105fb9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/coupler/a2i.nc
  hashes:
    binhash: 9e3167fc6a189a46bf10cbec3f44a52c
    md5: fc73d2e5400057695a7e65e91e37f066
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/coupler/i2a.nc
  hashes:
    binhash: 851af883e5f20228d4e7cf615be43e12
    md5: 6bc8d339da6d714a321dc0bb5aeb6b23
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/coupler/o2i.nc
  hashes:
    binhash: 276e8dcaabeaa59cd125276e555e7c6f
    md5: 98f309ec81360e83937c70dbb18a2eaf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ice/cice_in.nml
  hashes:
    binhash: 0047a496d607eaccf4ad4bafc8f979c0
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ice/ice.restart_file
  hashes:
    binhash: 846a283d2bcdbb72f778c5b0cc5f76eb
    md5: 942841ab8ae187ba4a31d82533cdf19f
work/ice/RESTART/iced.1836-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ice/iced.1836-01-01-00000.nc
  hashes:
    binhash: 60c1adcfdb5fef522141c4f647410a78
    md5: 743cf418bb58d6e74d616039114501e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ice/mice.nc
  hashes:
    binhash: 0fd73fd515ef2a8a1bd174fe9f25572f
    md5: 8e30f7c4a2ced7ce54d5aa7627f295ad
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_age.res.nc
  hashes:
    binhash: e09c3cf07765adb16ff8d8dad67cba3a
    md5: a6a5d755aa0088945b10771d1ab05615
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3b4a9ab05eb97f1d4837df9359ec783b
    md5: d958679dce165ab707adfc97a5bb3c29
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e950c1f68ace2ae310f2507f2785908b
    md5: 093d04904b48496f44f00035766f522d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_density.res.nc
  hashes:
    binhash: 48c3fe8ca1c9d53161dbcb4b24d2d2f2
    md5: 080bd820d1ef902fb5aa8e9c9613e063
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9b4fe5466441c596e34d1820cef3928c
    md5: b012ad103ff78222d5ff6e32e13dfd97
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 35371932b43ef8c8a3af0d25ac19e874
    md5: 2c79ff1fc30aa3d08f01ff3c79432340
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ac1cd64224df666dc54c4dce756637b2
    md5: 19d98b80b8b917983f1c326aa90fd203
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2214ee94c88347531cc528dc7d5c694f
    md5: 09e318f46dd06b924f0e907ef55b2ef5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f5a78450ea912dda40c488eb3e99e4bc
    md5: a35f01c1e469969d5bf33b54505a5609
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6a34cccc25b68e3a43952019fc79aee3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_solo.res
  hashes:
    binhash: 595748c6cad861a23878aaafbfcfb7ca
    md5: 6332fd2c814964871363bbbcc548bc80
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6c8d0da545753149d794cf6cdeb5562c
    md5: 66d68461da5ae7db4fdd8f0881cb40f7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 07fb6d8ea030cf88b2d0ed526c21d543
    md5: 27adfbcccdb167ddc940b8e33061c95f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_tracer.res
  hashes:
    binhash: 224fbd21593b62907501f952c46384f9
    md5: d5d7574359442c138993d68a70d53e98
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fb8ee909abff1268b762c7f7e6123831
    md5: 8d0153c7c8ff50781233acbe79fbddc6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ceb70f98d6f4a72dfab7d3d5f57b2244
    md5: 27ee6427c0dd0c6bd4e98c6ec4090861
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9008098e7e951d42457f40915b88c76d
    md5: c0225334c7979b2ab4560e0262e55ca2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart391/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 692c43195e6de75341df476577a292a4
    md5: b374262f8a4972043d1e5817e4204e76
