format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/atmosphere/restart_dump.astart
  hashes:
    binhash: 0220fb3db5a6bae42ee138adbc562739
    md5: 865f5caf8fdf9595035f00ff77b7793c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/atmosphere/um.res.yaml
  hashes:
    binhash: 8f6a51712e42c97668de0475570e2328
    md5: 077beb599f1ab8c2965a7291cb610b7b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/coupler/a2i.nc
  hashes:
    binhash: aeffee1c4b928c8a2a8771adcb03c0a5
    md5: 0189f31a31dad9e45d3dd1979e2c27b8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/coupler/i2a.nc
  hashes:
    binhash: 35a3f4827ee22d1a51a8c5fc30b55dcf
    md5: 88b765ed6e8b64a5e643f5bb1019670e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/coupler/o2i.nc
  hashes:
    binhash: b5b4d7ac2da09cd842559fb82bdc56f1
    md5: 60e57b44068d18df534e328952674efe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ice/cice_in.nml
  hashes:
    binhash: cf107dd4b866329ad81eb5af509eb8ce
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ice/ice.restart_file
  hashes:
    binhash: 2123304b8654d14d07236f3126026eab
    md5: 7dfbd3ce425a2bd930172780108e2626
work/ice/RESTART/iced.0941-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ice/iced.0941-01-01-00000.nc
  hashes:
    binhash: 0d22e9486483dfb626d5e479b90917e0
    md5: 4d9c34d9a9dc414cb662a4888984d9e2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ice/mice.nc
  hashes:
    binhash: 632404554c4619b696af8ac8f387d999
    md5: 7a488c9d847cef46877e3fc2845a5f8f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_age.res.nc
  hashes:
    binhash: b82f40975c557d1df567bca6532b0748
    md5: 4fb0b9d80056ce9fcc9b669c865014cf
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3337b6205e679b9a9772264db39c79da
    md5: 8d01f4bb3ef6fc3317813ccf1695f05b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8780ffc6fd826d943019a7bbef9fbd28
    md5: 0c3d63e4e0a3fab514e014dcee9b1d3e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_density.res.nc
  hashes:
    binhash: 3459333f9ac6ed3d64f14c46097785cf
    md5: 6f28757bfb1973734be057b700cb25ec
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e4c7597f30e80fba845ff241be7e707d
    md5: eac83e650a7b299358ae04ec26c8970f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8386f9f35516a72b1dbcd7040e3c3768
    md5: 63dbd339b29d0b171aa3eb9099fa3d12
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5ac0b581513c92a0c99e133e0dc0e839
    md5: 4b0593defedf45fd3bd039d3ab09fdca
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1b997e8790fe11992b11229ddc08a2f3
    md5: 224c95b58248b311bc2856f8637c64f6
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3052bd847e05891441c095756b36a4c9
    md5: 36cc3f66374f8cb9bc7cbf87920ea28c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 35d0f57985a23a99c00338b7fb82b637
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_solo.res
  hashes:
    binhash: 400630ad07aee0340c55782939ee50ec
    md5: fe00d7270d20f9b6dd04c0d101364fea
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ed39972d9639cc0f145e29645689e85f
    md5: f72225bc3d1bf1014f8a771c2ffddad6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5946fbc19954cadcdc5e97ba0a307a2f
    md5: 2a3e1c0d1ee7849a3d0722c251cce90d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_tracer.res
  hashes:
    binhash: b8cd3536248c16cbf0c5340f09f82ec2
    md5: 7faec09cff91ba33e0fab81e4571f336
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dc8b404566e59fa59bd99c527c12b244
    md5: f19f851f2f1c167ae2e4b2d8bc9e39d6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 011d77a3672532812988e69f982c52d2
    md5: 988f9ebf0b0efe305280fdccca1974d3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 847a0fe49dc1d31acf4ab897117e9fde
    md5: 0b9e48b95bcf8bd1abdd224ece7e2ec2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart387/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 94adba10822adc5aa918ed66638b6694
    md5: 063da726f2c1ef9e2a30f4718d54700f
