format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/atmosphere/restart_dump.astart
  hashes:
    binhash: 8a23e0512ea802ed9dfecad8a59d0be3
    md5: 1d4315c2303fbbd4122b7dc8bde3d98e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/atmosphere/um.res.yaml
  hashes:
    binhash: e95a6c48c903fc3f228cbc7193111fba
    md5: 4b0cb6f4a36447a94c2ca0f91a51a22f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/coupler/a2i.nc
  hashes:
    binhash: 74b4805daad3743f277288509405f3ad
    md5: a0560e34609a710f7a83c30e10d55f20
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/coupler/i2a.nc
  hashes:
    binhash: 48196b5dc214f63b9cb9b99a5072baa8
    md5: 0eba8e46691b4238dc27cf4abf9caef2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/coupler/o2i.nc
  hashes:
    binhash: ea414a6319eca6a632752224409bafc4
    md5: 80df97e016fc704eb40b90db1d8af3d7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ice/cice_in.nml
  hashes:
    binhash: fc15f36e9d3f90a601c38c7d2a48e1c2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ice/ice.restart_file
  hashes:
    binhash: 346f3221bce5a41afc7083923023a6de
    md5: df6a5cd892fc076d4589956e51b33bab
work/ice/RESTART/iced.1779-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ice/iced.1779-01-01-00000.nc
  hashes:
    binhash: db9e26e63a46361e951e0291c7e4064a
    md5: b3282c42160088d2e69a96eb86407ef7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ice/mice.nc
  hashes:
    binhash: 92af82bbb50b73bb8a93cab9287c2b1e
    md5: 04e8e0bb113acaf4b8f0e715fcd8159b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_age.res.nc
  hashes:
    binhash: 62689b664602c042e252e525f56b643e
    md5: bb91550f4065cfc09e97ba135b1c7606
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 785b22fcef68225af2f6e074af51aa8e
    md5: db05e9b6f4f52da063d27e547afec42b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bb453e4e3cb4e6419d068f379aed112d
    md5: 83882e37be2e35a6dd56028e179ce968
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_density.res.nc
  hashes:
    binhash: b0d646b05e0af59bb70dee55293393a2
    md5: dc0722df494bf2e1fee9da333280524a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b081a31740dea8ac4e8a09b38d332bc3
    md5: d56380e5ed773b29ffb8fb4b1ab5a094
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 535f9cb80bf1f81ef3584467b64fc0b7
    md5: 01b4597311b224a8cbb39740d853a514
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 420800f287e4c8457e496b179e1693f9
    md5: e802100e9783830ddd5643ea8059a96c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3410cbe722d4d720ff748f12e85d4a8a
    md5: 4aa271c0df8338364fcef7c838b0f02e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8c30f663ce869aadefb387b8a24c373e
    md5: 22928382b3a14fa680f0f436b316a4b6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: aacf84fdac8a0f88b33ca0b208eafa7e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_solo.res
  hashes:
    binhash: 97a00c85a20369ac52bdd7c46ffd329a
    md5: 31bede5f91a4f3b7f94b0c69b82d55b1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 84b551aed09fdce0b7fa499769e0a9b2
    md5: b3d909f1b7b6e5f3bd0c31f68fa402e8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 64b9bb0c756597cd4b4236d8a4cfc98c
    md5: bef98444d2ebed7904a1ccf383002703
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_tracer.res
  hashes:
    binhash: 96f72ebc7f9ecf95c24f4939777769af
    md5: 3efb06439f2edec009d54874822302a3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e16d3a8dd517db3d498069b145b78976
    md5: 7765b32a09ee340b2b476551eac3f993
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 66b88efa6ecc922473d2c27d563c2b27
    md5: 9fdfe06fb4d07f7d98d9904c33024a57
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 48cce3ced7e9d5f7306d7d5c7117017f
    md5: 9b7bad7f1f11adef8d41e63e30a4af5e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart334/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b762b3d868c9adc3545e36c63983ee55
    md5: 5900f66faf03e685e60cb5982e0cc90c
