format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/atmosphere/restart_dump.astart
  hashes:
    binhash: 98ae7c1bf132498fdbb973ad0173fb1a
    md5: 8bcff4bf921152b9259923976368cc8e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/atmosphere/um.res.yaml
  hashes:
    binhash: d83de72458388b1f1a2074354e4159d7
    md5: 88961a18ab86dbb076292712b65735cc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/coupler/a2i.nc
  hashes:
    binhash: 445685dbc1d6c9920bd1b688b7a5e3dc
    md5: 37374641f754f38840a3c8382a80a8c1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/coupler/i2a.nc
  hashes:
    binhash: eed68a7d9b30075b29228752d462781d
    md5: d71460c7ba4302a56842696a351052e5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/coupler/o2i.nc
  hashes:
    binhash: 796be3ebd019e517f45e6c130a54603f
    md5: b6d81947674351308c130fc284beb2d3
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ice/cice_in.nml
  hashes:
    binhash: 4c01cdd25536ab83584808f8bd03689b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ice/ice.restart_file
  hashes:
    binhash: 37237caca1b267598cca7879df43ac03
    md5: f23db0ffe09241581691fbfeb0d57b98
work/ice/RESTART/iced.1204-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ice/iced.1204-01-01-00000.nc
  hashes:
    binhash: 80c56592a8cd7549e0c23ae453f9b0fa
    md5: ca1218cdb684522b2cdc0696286901e1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ice/mice.nc
  hashes:
    binhash: 9f33a930db8239298de4b11110b31dbb
    md5: 236ce20cf8fa7f17bde495fd8f651259
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_age.res.nc
  hashes:
    binhash: ab47056f02e27a041936d26e9cfc39d4
    md5: 082c27f8adbc8cc70ee06be5d433c614
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3f158a201190f37e571f75ff6414bad0
    md5: d032024b0319b11f3b91eded9a52870a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1141a4261df713f4183b84ddbcb5b69b
    md5: 00786db7f449f4e85038ff6542dfca92
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_density.res.nc
  hashes:
    binhash: f4a4633082eb5c17ded1083cbfeb5a4f
    md5: 6684f979889bdaf09af77edee9883979
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f9a3c8fcd5457220ad0b0c69581d0636
    md5: bc7a60f5987545ac60bb390eb89e5bc7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7eca17eae8e7c179752c1d4dc5d6e750
    md5: 7bb99e20786e9b380d1fd851e891aa01
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f1ba04289e70ccbf7f3ac94bc577d90e
    md5: 50493953a50136249cf5635810527b4b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bba29b3a2bb699be25df3484109a99a0
    md5: 5e095fdce346aebef9fb4be5250c5d65
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6b6375ea44bb8aee202530e928ffe9fe
    md5: 68c428309aa8be5564b49a22e87328dd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4f899ddb0268e9ebe8c14a4fdf7afe25
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_solo.res
  hashes:
    binhash: bf6bdfa94e60438ccb0dde61ff111b7e
    md5: 2ce261a698925ac93f4561fd7b9d2f84
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8305e16736dc2aa5f53feaea008425bd
    md5: 7d0b6760eac8f066628ef84d60abc133
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f5f1bc7669af2fe013ce51c8943106ac
    md5: f7e24675fcfa492e5cf4d796d5460340
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_tracer.res
  hashes:
    binhash: 723af92a7ee5ccb12518b9105a9db0ce
    md5: aab96358121e1e179070e72649d51d8c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 163f5fd3d0a0e22c5c9dd2971f8da2f3
    md5: e06733d0dbfbfa0e150745e4265e959c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a414dcf89f81cd97d951ea472b3a6413
    md5: 5f320b3a146640f63d889b75f3d86db4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d40068954d3bd7d3624379e64c8de83f
    md5: 7cfd67d894205ebb659cd055341ea558
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart320/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8277c6885c7a3c76e1a22d032b1bd861
    md5: 4b521ec7a47f3c73973a473fcf097ad9
