format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/atmosphere/restart_dump.astart
  hashes:
    binhash: d31d40d4f27e8aabe9534947ec203ad6
    md5: 5b3860abd1d3b4a13bec85ccd0d0d6e8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/atmosphere/um.res.yaml
  hashes:
    binhash: ad2db4d242b38d9f31238b1bf02973a5
    md5: 60f2011cd11ef5ca1a31f993014ceca9
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/coupler/a2i.nc
  hashes:
    binhash: 24224dc35253d65952d18593ee20bcf4
    md5: 85de7a2ecdcdf42c5adbe39c804deee9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/coupler/i2a.nc
  hashes:
    binhash: b860c72e0860b924c1730c2c82125798
    md5: e1e8f91a821b42ac4f167613d7cb8359
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/coupler/o2i.nc
  hashes:
    binhash: daae59a18141e88dbfac3f174a558ba6
    md5: 93eb7adff760c5df0dd2f7f6dfa34227
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ice/cice_in.nml
  hashes:
    binhash: 41febcf4fa8e07a8d6be73dc482e5318
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ice/ice.restart_file
  hashes:
    binhash: bd8cb4157cf78f208f4eb9f37eab7a25
    md5: 7b2567a4ce5cdab1bfe0da0ac963b3c1
work/ice/RESTART/iced.1774-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ice/iced.1774-01-01-00000.nc
  hashes:
    binhash: e938128df19e92be2aa2932d64cc83f6
    md5: 94307fa5932286619f47a84cf23af237
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ice/mice.nc
  hashes:
    binhash: 60bb02566e69bb68bb991ceb0b7a765e
    md5: dbe1d9f8b041ad4f6227659353c4b1ba
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_age.res.nc
  hashes:
    binhash: 80bafb971999b95df8eeefb2d0c20f12
    md5: 00d467c2e406a638fbec5f55c6a64de2
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2cf5150c947f0d0e537ab95854dad69b
    md5: ac244bbb406f00048b0b8065f300473c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6f09ee59065c3f09364354007483b78d
    md5: 27adfd1b13100d731a9611269f879278
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_density.res.nc
  hashes:
    binhash: 83f4299fa86965e3da6eed8ec954ee04
    md5: fe9541ad767f66cb259e7af3a264d3df
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c3594ff74bcd2cbf59c001be9f589be8
    md5: 908d292095023a1a16e83f0fe0388d7d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: aee6c56cb72b0989dbbf71e8bf0239df
    md5: 443a6f69b178cc1c3c3ff613c0bbb965
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c407fc65e2c3baf6b16837c187a084cc
    md5: 0db62e001f9ed59836b1e753925c7915
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f001fa17b67b939ad374fbe85f1c00f1
    md5: 78f3ca1d32c689e865a314fd3df3cd67
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cbd4946654950b72d612caa84214b201
    md5: 06c590049075b0ae1b3e533a232c4164
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2eceb241c177f740febb9b9e91482755
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_solo.res
  hashes:
    binhash: 6c8edddd37e6a0715b53e7a85ac3ffe2
    md5: 5b4ea00601e139f0b9517b01bf999409
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4d950df32c1a784f7f1436e72d4cc297
    md5: bff5ab85c02f273a9337462e08cc9103
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 62f79ee29b0f28c49cd8ccae070f9566
    md5: abe8d29ff6f084450ea6acc3f1c2b7bd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_tracer.res
  hashes:
    binhash: 79799cf4d553c3bd976ca1893609b1c0
    md5: 7b8fbc8c21450ac57b91b6d974f06f8b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 64c49cdb989d336de42aaa5316b921fa
    md5: 966b058dd8fba382ff871334e8bae71b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6f9a0a4d98e5acdfe4f5d90614024695
    md5: 798c460477fce25e10cb68e9819e996d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c55f4fda7feedaa6cbfdc7b0e4118ca5
    md5: 4a8f249126868159e98844bdbcb9de53
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart329/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: de2634edda269c8142d28d7e2db04edb
    md5: 91df82634e2a80dfecf082bf4748097b
