format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/atmosphere/restart_dump.astart
  hashes:
    binhash: ccd8e2aa21401651fb16a2ebeda47092
    md5: c402ceb663afdd9c9a63c543df658219
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/atmosphere/um.res.yaml
  hashes:
    binhash: 5498b272ecb20131da2724998f9fed67
    md5: d37628c5a563c3a0dedf8b5e429e2e7c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/coupler/a2i.nc
  hashes:
    binhash: 67407b31d396faddfd3507898e0b0132
    md5: ce0fb9ffde1ba7432fa51f20416e767b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/coupler/i2a.nc
  hashes:
    binhash: b271b368077197ccda6c5d9f99972032
    md5: ca817df99d327d5e1eb82e35a509a8c0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/coupler/o2i.nc
  hashes:
    binhash: f0aa67fe97958b2f5107cb5f1f557d28
    md5: 523c4e1cc7e6e3a6d526992effd86882
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ice/cice_in.nml
  hashes:
    binhash: 93a0c3377a7061404485b4a8e74ecc70
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ice/ice.restart_file
  hashes:
    binhash: 26db57cdcf8a555eb48c46e194eb4d14
    md5: 1ddab4de583da7dbd625ae6b992066f6
work/ice/RESTART/iced.1823-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ice/iced.1823-01-01-00000.nc
  hashes:
    binhash: 181366a99882bca6b928aad85cecbf43
    md5: ef44543f13fa8049f75620432a3e347f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ice/mice.nc
  hashes:
    binhash: 320fdc44858c36e9144acdc08a9ce7cc
    md5: a0beffdb2ae1e200cfb34880e0d155ae
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_age.res.nc
  hashes:
    binhash: 120f463dbcc1aaf48de37fb6fedc6b11
    md5: 98824797120adca4f2434646fbcb1fc1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6239981fdaa4c9028318cd5ef4eeb50f
    md5: 2d0b391b9bf814c8222a96e33a8e4cb5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9ba73306ba9799c9f74b6b43920bd6cb
    md5: 96c20ec2aed691f7b899ab548422fbf8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_density.res.nc
  hashes:
    binhash: c6a32b1e7e9c3c3787a90dc95bf1a621
    md5: b970d101134249a5c628e6328725a282
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8b48f574cd829070d01b5f557a785013
    md5: d9645589de06648140f8c8c23e212af4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b583151d1e132a15dec42f9e196244ff
    md5: c3a203b605f31bb72f235b5f8aa44fcb
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_neutral.res.nc
  hashes:
    binhash: de24c88d24aa429005cb1c8594f577c5
    md5: df7121b2b61b4793f847347eed4847d6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2d4bbfa4c49591590e35a8558cc52230
    md5: 07985996c8e6184e36bcfb437e5bc160
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f711db3ae36e5c31ba157c0775dba49f
    md5: c749e2f2d67e660bbbbfad0fe70b9a3d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4e260e8b64dcd6b7508c51d5adb9d097
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_solo.res
  hashes:
    binhash: e4e8d988634d8a7053556b7b8aa7f9dc
    md5: bfb61d82378c3794e6c17960e7513610
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 943e5ad6771476fa0542ded41b7d67ba
    md5: a6f72250e322c7bf8f85b6ad883f7dd8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1e49d4850a3f9aa391cf667e5b4e9060
    md5: 0babc0807b9ca10ad79b61a8bc93886d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_tracer.res
  hashes:
    binhash: 311a8043092293f8210c0e5c20cff961
    md5: d379f8843e9b9c64afa7134d1a548170
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_velocity.res.nc
  hashes:
    binhash: de03602d5ad530ac008a56750ce4a3e6
    md5: d9e16e2b3cadcb286f657737ec547689
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bf1c0cbf99d335bd4d76d9d15a332f62
    md5: e2f567538f25abd23accd2c2e714b36c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f79ffa886778a6dc2c13075b9d11da88
    md5: 6fad3d4002ba380925d7290cf1bb27ee
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart378/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 639f9c9ba1ba0c8b64c5f7cb9dc29bba
    md5: ec69b8f5d0f96f58f194769eead180dd
