format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/atmosphere/restart_dump.astart
  hashes:
    binhash: be4f5abd0b187c92d988eb16d7168c7b
    md5: 0d82a4e2c5259ebe62e5ed15366499e8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/atmosphere/um.res.yaml
  hashes:
    binhash: 1145a9ef726c101f6130adce22b5260f
    md5: 50339661534c65aab0c3ff46a4665457
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/coupler/a2i.nc
  hashes:
    binhash: 72d1c300077c3dadfa3b742257e1064e
    md5: 1822d8ab41fe5881b67a0ef2bc01454d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/coupler/i2a.nc
  hashes:
    binhash: 46650f75c2bc1347d0ecfcb944469f96
    md5: 2b30b277cd351d1fc6f82032c306475a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/coupler/o2i.nc
  hashes:
    binhash: e1e9fe0812a1c9782e22337738e46d56
    md5: ac68f7b5f02d571cb21d652b02136330
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ice/cice_in.nml
  hashes:
    binhash: ef3bda951c7d8255ee52d7159fbae079
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ice/ice.restart_file
  hashes:
    binhash: aa2434c04eb293b4e9f2cc998465baf9
    md5: 1779e6f3930a7f4c8ccc632ae93bbb87
work/ice/RESTART/iced.1212-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ice/iced.1212-01-01-00000.nc
  hashes:
    binhash: 86d72d909052e6f6ef6c4a7659368e4c
    md5: 1b692244f5be815ae2967ad27a5835c5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ice/mice.nc
  hashes:
    binhash: be3067dd3171d0d5bd162488fb515738
    md5: 5e64cfd21f9ad598e989a8632fd6d93d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_age.res.nc
  hashes:
    binhash: 0850f5c23164521c4ea2b97f749e5517
    md5: 4b709b44ed134bed152074b668f1d884
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 25a79ee7016c05f1f6a9c8a87cf124d2
    md5: bd6c08d0204f53fc69ddc629bce8b9aa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f65b2a53404e87996bd7d0c431411af7
    md5: db441aa4a703aa5278cb62136098c075
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_density.res.nc
  hashes:
    binhash: d1c4bd6a42bd19ffe3f74cd18aff48a4
    md5: 74b0c889baf0be8523c86aebdd7f68b2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 371fe6e47c858f660147337a2923e0f4
    md5: 043cb5fd2f02763963287f09fa0720c4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fc82a68d7736378eef4b9d49fe3581c1
    md5: 2a333c681b66444b0e44ed26cde42c0e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c3de354170ac9257bcb8b9268644763a
    md5: 07b27a4cb67d9dcdcd781eb0fcfadb57
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bf02cb7a7ff1cace21ab41e718cfb608
    md5: 50fd0bb8298b22cfb4b788478a912440
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d13291fccf32c4c5466978502a460ae4
    md5: 476b491cbd2192ce8f5d1b8931531de3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c86c0d36603200f77befca00c63cd5f8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_solo.res
  hashes:
    binhash: 279ae16121b9ce829868677007a759c5
    md5: 1a1fc38468854499fbe470b83f3f2dab
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5a0035cf7e5a80d9705da06afce94bb3
    md5: a4da74bd86a4e430afa7bc4fe0ae6a19
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f4ef923d4a8ad5edd577abb7afd1356d
    md5: ffe7fe12f70df8b6c8c8a9bb686dc982
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_tracer.res
  hashes:
    binhash: 9ef177918e62c6e0075ed121dc80382d
    md5: 8166d5f55f11264b202955ed032f206b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 09698d926e5f9b02f2cbe50aeb3423f4
    md5: fcb123c5f16913ef7036a7e8f7ed9023
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 302480a06cefea88097d625680108111
    md5: ab4b988176f3cf5a9f42232a305b2c11
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 54b4c190d4f1ae5e306e7e632a8e3df0
    md5: dd6ff549315c9a3a536289adaca94848
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart328/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ba24d7a116d6cfd8a7ad717eb1ea93b0
    md5: 3da791e1b9240723a2474f9aa2d856a0
