format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/atmosphere/restart_dump.astart
  hashes:
    binhash: 63f2319d9e9f3b626dd63a7c90ba3e8b
    md5: 00563bc1a4ffc77e2685e910c98bdcb2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/atmosphere/um.res.yaml
  hashes:
    binhash: fb9bf58fcedac0572b97563edd102ae0
    md5: 109ca44bae9cbe123939c8c994e739ee
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/coupler/a2i.nc
  hashes:
    binhash: 91afdad1a5903ce55f92fa205205adf1
    md5: b6ae24347f94a946a795c4369d74e79a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/coupler/i2a.nc
  hashes:
    binhash: 205706942124aa376430344acab2e863
    md5: 579ff66c10ff1d35dfb7a5f832ef34cd
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/coupler/o2i.nc
  hashes:
    binhash: c859a4c813a32805090e9bf3ec34c9dd
    md5: e37de61fb8e3c5bce7783ccb7ca38670
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ice/cice_in.nml
  hashes:
    binhash: 304b7e18176a421d3cbfb20ad8e48352
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ice/ice.restart_file
  hashes:
    binhash: 77d81a3654ee12b25b90a882fa472027
    md5: e87b41864fe68af05ac4a893b7a9dd0b
work/ice/RESTART/iced.1859-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ice/iced.1859-01-01-00000.nc
  hashes:
    binhash: dce222e07cb86883792b813d0efdc494
    md5: 9dcc171878c1ff1cd2e2375c8b41c786
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ice/mice.nc
  hashes:
    binhash: 0f9ff1aef2910d9f0b022e8fd58799f6
    md5: 3503c4aca7e3ac8f77cf8057f4e2ebcf
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_age.res.nc
  hashes:
    binhash: 55f790a41d0446d055a027b82150bfac
    md5: 653be679d458dd25ad9e684f253f68b3
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 85053e86b09468724cdf4353aa424114
    md5: 0994aeb282854d879f5c16b015105242
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: af5698e1fbb8df82d77e6d105c58a94c
    md5: fedb983583b8bc10e70ca81982610d70
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_density.res.nc
  hashes:
    binhash: cd6a5dfe3576435b493a2d117d766bd2
    md5: d44cb54205567aabe6a28f25a342924c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d1e679daf25f4f37ec527fe92233e085
    md5: 79126fc757a9d53153d63ba6c64ab6e1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a5d176061124aa241bf6346d520ddc71
    md5: 1449abd077baf9badf43fa6735b147c9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 459aff36e10ca9309af12e2173dbde61
    md5: 1da7e601c48b63fe83f029a8c02cc752
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ec6ab64e574bfa7c8256d508d09d4044
    md5: 5ef314cac8ad82bfcbb9a2cb44a4e318
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dbdd5079d1039f6912f1efe91d297f4b
    md5: 9a5ed2543f9bdf396b0e315e93618ca6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 70bff2eed061648fc199457784708728
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_solo.res
  hashes:
    binhash: b2661cba5d987f81d4c1dccd60018928
    md5: db7a839aadb244c6fcc9e675ed69c855
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 31e341aa7afc1edfdeea1edb54dc82c6
    md5: 64852392a2333781203f81b5d96f9cc8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a486dd356924e3bca14a7cbdfe261693
    md5: 8026adec479034b81a9661e4103f33ae
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_tracer.res
  hashes:
    binhash: b2bcca18d952f63803505e7a7e6fe4e8
    md5: 5098219c7124e551706f9281ae408171
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5c4db32b5523b95b8041886331674d7c
    md5: 8f21bb171539d2608e686bc9faa4de0c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 261695d9eaeffa06ad8c8740710f21e9
    md5: a99be0372cc736e52746506eba5bf817
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2fe64cd624aff0ae95701bdfec666a4b
    md5: 24a86c63544d67b71299815b64744bb3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart414/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 89e48ee22dfa1d8c6969832db56bc75a
    md5: d42f39a4f2dc1f1c1578c94c7302d03e
