format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/atmosphere/restart_dump.astart
  hashes:
    binhash: ba19767a1625a09c7419ad0ce599c980
    md5: 25d9972fd938bcbca9186a4216a80873
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/atmosphere/um.res.yaml
  hashes:
    binhash: ad1b603590a2db6e6a97b425acfe8d49
    md5: 028c9b26a7a46e04735fd962819af4ed
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/coupler/a2i.nc
  hashes:
    binhash: 369edd7be3b096c3f1da96d0411ed947
    md5: 5c0e545cf98d6adc7bee993a41841ead
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/coupler/i2a.nc
  hashes:
    binhash: ed3f418f02da6adce0229efb3723f22c
    md5: 6ba3db9e0daf5a12b2ad0e00bb382f22
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/coupler/o2i.nc
  hashes:
    binhash: 2c32ad2c3f07ad70d3cc471bee6c1c24
    md5: a0b4c38dae37aa61cee4904111a9f9c2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ice/cice_in.nml
  hashes:
    binhash: 684c024eaecbbf173d23774bb3d8f445
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ice/ice.restart_file
  hashes:
    binhash: fef4fac049bc4f64b518027d92d0f752
    md5: 6988c1f6a9e94ac837802950c0b4fcaa
work/ice/RESTART/iced.1257-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ice/iced.1257-01-01-00000.nc
  hashes:
    binhash: b17d33de1a58c80fc4691cc52692c13e
    md5: 8d851e092b89708ec684ede0d2fecb2c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ice/mice.nc
  hashes:
    binhash: 5947762b94ddfc9aa75764fdac0b3377
    md5: 9560525ad40be2169062db1a337569d8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_age.res.nc
  hashes:
    binhash: 175e7e994fbe8b4a01104512f29da0f7
    md5: 916603f717d755dc034eb94050d3d28b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d04f50eeb714455bc35268c8dd449b22
    md5: 7b457316c600d86008960c18fc1ad7bb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 43b809f73f3159faa08f1d4571b8f10f
    md5: b84c6be844ce3a62d2ad58112d8da2b0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_density.res.nc
  hashes:
    binhash: f2dd0a2169fddcc99fb90452b3a4ff2c
    md5: 45c77c4cb143077ff97d95da716c9fcb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fd1c9500197197a7dd9d4abeaf8dc81c
    md5: 24ce167762b6efc010ea8745959ffa57
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8894aa065ab8cbc62dadc95aa1448e28
    md5: 8e0ccf6096d25ad51233dcd8e53c4fb5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e5c43ffca778e5661695b5705dfd1a67
    md5: 4b6eb5013a6d52c1d2ae58c3134d63e5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b6c77857c790e0dec86ba8820b37e792
    md5: 8cc3c6f5c75d51f680ac701339f82a73
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b79df030e37e52db0b934d2b18cfa4c2
    md5: a618a4889d2c63af85911ca5b51c466e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 073c2133c83aa8c25d52486c28ef08f2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_solo.res
  hashes:
    binhash: 416138d0e9025558afee8d31424407a7
    md5: 23b996a5c4e6f78b6e96a692b3e108fe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 95637bf90feddc1c1dc483d2d73a7b30
    md5: 84aeaf6b1a1b62fc67caffd2fcda004a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 70b25659b2f7f38df10f823b6054354e
    md5: 9aa7d232ce2cf158bc756c769f91916f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_tracer.res
  hashes:
    binhash: eb58320dd0209fc16fbf820d5e16bc1a
    md5: 06b828c254028a15fcff7d6bef5349b0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3db8b3f197482a0202a323ca5e35cf75
    md5: 771e4476c2f8ef7a2a690427911db0e5
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8aa44a39d35ab69730bf88f43ade9189
    md5: ccb2552cd355d5dea848e819df4f1a06
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 984e471807a3bcc802dd14219c009874
    md5: 01052de52d12636e3aca35df9d5226a5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart373/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3379951ad1857f9723683e4db1a1dfe2
    md5: 8315675621ef88247ac9f497062ec571
