format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/atmosphere/restart_dump.astart
  hashes:
    binhash: 721b4924a41280195dae26ef5cde79ef
    md5: 7149ad8f51f684a3dba362ece807364c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/atmosphere/um.res.yaml
  hashes:
    binhash: 386f6494a8d19c52ef5ccfb3a7c0343a
    md5: ea8bc0ca8005ea7d10b67a8ca9c1536c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/coupler/a2i.nc
  hashes:
    binhash: 083a52094ce8b624f68f9a36a1fea4d0
    md5: 5017529537545d959dab0c67545bb834
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/coupler/i2a.nc
  hashes:
    binhash: e99dfd55987be597a437dee7a811ddb2
    md5: 6bacb69faed4fd23c48d27eeb15adfc3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/coupler/o2i.nc
  hashes:
    binhash: 19ac5a6a78df011ed8434ac83484487f
    md5: cd6893da48298d571bf8f805578f9f3b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ice/cice_in.nml
  hashes:
    binhash: 85fc0cf1865e61bac840994be81a0ce2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ice/ice.restart_file
  hashes:
    binhash: 75e1cda94988939971ac2861abaa9d72
    md5: 0aa62d5424bca6b71c288b6a8cacac0c
work/ice/RESTART/iced.1188-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ice/iced.1188-01-01-00000.nc
  hashes:
    binhash: 246d4eecf298d4f4b31fd9018b72feb3
    md5: 7d1c30dad34064c46c70553575ccc938
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ice/mice.nc
  hashes:
    binhash: 083ef29b86b2f74924a0969a88a2d5f3
    md5: d5e084f6c256b2f224f74bb5d157b5a8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_age.res.nc
  hashes:
    binhash: fee99dcd7ec393528c21714068f9e83a
    md5: f48fc85f47f3b360ae82f73cdf187453
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1a619ef1980da972c34a58cf56299931
    md5: 569b7565acb607e48f3a7316dde48b20
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4855f3717fbfecf42a6318e6c90bd107
    md5: c3b1aa26d0a28cad214037df5e43fa33
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_density.res.nc
  hashes:
    binhash: ae55c7a506160dbdcac51e26b2213164
    md5: 150c308b56f0bea0bf7a006d1acdaf8b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e9673083c655acad96e6f93d1d19260b
    md5: 65cc4b85cb5cdc11a7b259b30caaba43
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f86328deaf5363f021c0a60596d03deb
    md5: 6da6f82a08e185a6e7dde76df50c051a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 973b996d56f593733bcda1d395ec4321
    md5: 1007ca6248593253da6c0c4356f38efc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 509a5200414231ad89b04798d13b8ede
    md5: 4383065bd7746c564e41dd0170d1ada7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e1d3b74587894ee91ce421534d9ba4b6
    md5: 9902da3fe4c0e1ba926b5ac479b12de3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 66b57add568c972390811e1a86f71fb6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_solo.res
  hashes:
    binhash: 52006391cd0e642ed9b6458b54a01c70
    md5: 087f1352a692722e0fb4fb375081411d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4b197feb0effb036207d3c526be3ea3a
    md5: 604ba1dfc7a39675f6464095a1e73f0a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ee78aa13c9e4ee5d6c439dc260dd8e20
    md5: fc23bec1bde8ed96cf80a69bb0e26552
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_tracer.res
  hashes:
    binhash: 3f4f50249d4ca5f9492caf140e07f18e
    md5: ce9d81404ae4b168bf6aaaf5c2789719
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fa9b6dca22aa8413f910e2a1131f8b0a
    md5: dbb9fc1341e95d225e42bd1ea9d44052
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 54992ff82945e688901d436f05e2e399
    md5: c5bce4f7eb8afa51e503b00e4d09e802
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3863108942c268567b4368796d3a6536
    md5: 1a05acb43d91fde1fdbde0fa113eefd3
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart304/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 74380486d1ea65ece5384cd401c87e1b
    md5: 4146f73b03e8092a24c232d35e5c8d13
