format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/atmosphere/restart_dump.astart
  hashes:
    binhash: 11a60d7aa533a054118bad36ae627a5e
    md5: 6bc8796c761ae4572495dcf479acff73
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/atmosphere/um.res.yaml
  hashes:
    binhash: 345c4dcd2b0b15e0d6954a710d950274
    md5: 45245d996605effb5695f494d0be59ec
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/coupler/a2i.nc
  hashes:
    binhash: 7037add5a13b9a60e234910df5ee2f4b
    md5: 4a47589da51ae023df9dd2387abbcb16
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/coupler/i2a.nc
  hashes:
    binhash: 077e27fd8d546968f2ecdfd69bbab19b
    md5: 97f2d09f5daf1ad0e26de583605e3b42
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/coupler/o2i.nc
  hashes:
    binhash: 02b4b2cc2d02cb11cfe256b4d6ef440b
    md5: a96074e57529445a4966f9bacd941ef1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ice/cice_in.nml
  hashes:
    binhash: 25b6a633aa023c6d94b8722c8b6cdb8c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ice/ice.restart_file
  hashes:
    binhash: 8afecd829e3c68d9dd563069ca6f3f96
    md5: 8e311e81943683a7f1cce3b338373cc7
work/ice/RESTART/iced.1729-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ice/iced.1729-01-01-00000.nc
  hashes:
    binhash: 40e52805266272d2e00db9763ead8858
    md5: 533ba6500f9f2dbb15a0b56c3a3c4c73
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ice/mice.nc
  hashes:
    binhash: 44bd51da45e24803ff85c2554de6198e
    md5: 313be44e5962915bae99fe539fc64909
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_age.res.nc
  hashes:
    binhash: 473c8db8af3be6e46419af60d421c6c2
    md5: f9fe9b700ea72e36da87e7e5344b394a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 996953b91c274157de8b4edb7a00b1fa
    md5: 79024cf6e999ec95712c4101fca84920
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1f3665801b7efb72dc863af00866d8ed
    md5: a42c68eccce2784dc6c51afe79bbfcf5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_density.res.nc
  hashes:
    binhash: a4e318255090db580e62fd72bb34b077
    md5: e81c754c7a3986c2c993fc94351aa206
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3b1f9eca210127211f6d6e661d2706cf
    md5: 46e1f8b517f286117d72967e8ec0b382
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 4a68e070c5bc251d951c4b6583edc431
    md5: fcc4a27e08dd0f967f78326e62e86bde
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ad9cdc3a33db6b5470880f255911d42c
    md5: ee22743041342662acf6e34e7fab2664
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bcfea1feaa5e85d08c47fffc2625729c
    md5: b838542fb39f1e501c697118ed5c67d8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0a21493f633bb76107ab500026b9d38e
    md5: 0b8064eb455b917c43e8d4a69684d54e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 265a53a1487de34585635939cafe335b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_solo.res
  hashes:
    binhash: e722c77f3ed8ffed8beffc2f946bd390
    md5: c8a228685fe079924a4fdba1a9022867
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 13e66fc3cf9ed1b310cb8d4001a7af3b
    md5: 4fab788c75b96d07eafd53ba1f8792c2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 05246ad2b3e42180f1f928c3a0111c7e
    md5: e5cdda7dba5a9081223f27198711c410
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_tracer.res
  hashes:
    binhash: fa5c769d3d959cfdfa5ee46c5271b681
    md5: 3e4459d5244a83cb6bdbc99055273e17
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b2dd2082c48f1559262c804d3a60016d
    md5: fa631c2b735224ba3613c99d732bef42
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8bdaa29ba3f2eb063471d58c885317a3
    md5: 6e56bf1a3deaf4ee5eea78bc30dd8c1d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: da4c72c6c8e2eae1d53fea45614c1064
    md5: 4fb4c6517208c42c2a642a8ef93c0f1e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart284/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 73661be36f969c50b0fd520a36d6aa36
    md5: 6737f37d2b3c0adfddc7791931ce10a2
