format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/atmosphere/restart_dump.astart
  hashes:
    binhash: 6b5de2c9c052af9e2a2d4a01f1a5c2fc
    md5: 9bda651e0a51c4872299de476ee0e2c6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/atmosphere/um.res.yaml
  hashes:
    binhash: 672e81be19f0042f0394f1b95346ceeb
    md5: 264b8640f357b0eb3643225130bc75f5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/coupler/a2i.nc
  hashes:
    binhash: 4e353212407ef58dbab2e120719bfc53
    md5: b9bb38034f7fd465510f7ec7c0058447
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/coupler/i2a.nc
  hashes:
    binhash: 0a86f4782ba0f9ad4dc0a58ead1929e2
    md5: 95de361f3fed9e37fdb8fcc2512aea1f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/coupler/o2i.nc
  hashes:
    binhash: bb4cbd796592186f50ee163297361e36
    md5: 442d4aff6aa3939a6b1b621956fa12b6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ice/cice_in.nml
  hashes:
    binhash: d0c27c76968cd97fc64f8c81297ffa61
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ice/ice.restart_file
  hashes:
    binhash: 8a55077be1664b2f69fd994c24704f6d
    md5: bebe9a2d97922f12ceb66168547e59fb
work/ice/RESTART/iced.1167-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ice/iced.1167-01-01-00000.nc
  hashes:
    binhash: 1b44fea84edc85f76d44d9d5e37bbd5a
    md5: ca429a4d18dc97f42ad35c4e82067ada
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ice/mice.nc
  hashes:
    binhash: c82dbd651f036b0ddfc4565cc9fd27e5
    md5: 36d596caa93490a10cd5c6497ef1f300
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_age.res.nc
  hashes:
    binhash: 853872fc3219883dd5d6e41519e0804a
    md5: 752479d0008c92a473ac18b08bda6cc5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2ccb3f654283a008fb0d1372e6a2cfee
    md5: d9a4f37980c76d9714b3e74f5b565540
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c676b9c7f554e838654930b082e5b162
    md5: b101da7eaad91f9f656cd6b355301459
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_density.res.nc
  hashes:
    binhash: 84a69b19a09e3b4b1c6d5e33e816d9f9
    md5: 9ea06074c65880f2545bc6514971772f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d6703baa4ef476f89011a0441b5e24ca
    md5: 6b967839adaca140d78fb385f1ab4ed3
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 14155235675a97d7a63cc436c468beec
    md5: 3ee6ccce7ded0244e2c617cdc1fd2189
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 65c44df9790d49c9763e15a7fded6c1a
    md5: 5f19ca5f0af6587d6fdc85f967ae44e9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2572192fa4f0b721926ea3e9b3b0c4ed
    md5: df1835340780254945fe00c0bd8d55f4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 47d3322f28e85ed9c4b72bbd20d42364
    md5: 2ae17dfd31dd7a446ec6e995f06a3587
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2f1f2ad93b8387e189daab539fbd74c7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_solo.res
  hashes:
    binhash: df54e881741d2356a504b7502a9721f4
    md5: 2fe2343e9c7d82d99fdef7b6ac826a2e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f1d69989821f3fc9371e9a6c51158616
    md5: 9e9f21158017eb6ae14106ae518dc701
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b082930e466bf43be048d412775e953f
    md5: b195eb76687804a78cd0df881341ac50
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_tracer.res
  hashes:
    binhash: cadc2c88a0905e19fd0e2b9fc91f08b9
    md5: e4cb5570159d95c33b8a8ea564a00178
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 863a9d5baadcecee31d8fce69faae331
    md5: 09810f408214d8f693dc4f8c118cfaaf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 00baa5b50917156dc9116f61563afa8a
    md5: 94b1878d07b411fa082713773d4e84e6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e9b38f72808e120ef1d4e2c0dcdb203d
    md5: a932227463e02cc102448b8d026b6a77
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart283/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e751a39c01039bbb0baee2d0423d107c
    md5: 7f737648acb5d58a527b3b23dcc38caf
