format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/atmosphere/restart_dump.astart
  hashes:
    binhash: 9ea37e673259dabfb8459797b9a32380
    md5: 062b118325774adcbb95e8449e224a2a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/atmosphere/um.res.yaml
  hashes:
    binhash: db7e429d3469f378fb27847de03b0927
    md5: 1c178046c0f09aaaa45f59a6831da0d4
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/coupler/a2i.nc
  hashes:
    binhash: 357c73819c616be95f4dec59973fb722
    md5: 9a799ca1433619ec7634f15271ddbf5b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/coupler/i2a.nc
  hashes:
    binhash: 63ae9435898ac7fc327ac07c9c819cde
    md5: d7e5d8bdc6c73a0e588f91a10a991d06
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/coupler/o2i.nc
  hashes:
    binhash: 5b650204c3df615e8cf3b4d586237eea
    md5: 4e6082569a99a00a65f85816a3be7a4b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ice/cice_in.nml
  hashes:
    binhash: b2cd81d9f119a2eb29e3d7634429d3dc
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ice/ice.restart_file
  hashes:
    binhash: ae29df5efb5a16529226e3969b9d79b0
    md5: de9796baeb99f47527a408a0e2e11cdf
work/ice/RESTART/iced.1758-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ice/iced.1758-01-01-00000.nc
  hashes:
    binhash: 1e44aad640281ab9a8551c8e5395fa74
    md5: a6bb7da89496668a4c852bd6145b6165
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ice/mice.nc
  hashes:
    binhash: cb3ffb09499707bfca771863f2c4477b
    md5: bdda41eb848986d9d58c3217d2f18395
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_age.res.nc
  hashes:
    binhash: c1ef2eac234ec9bac7be9d2ac000508b
    md5: 9f421c9f007e866ffb586ce75028cfae
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: a596091051336ede58fdf65b18df106b
    md5: 9a046758eb75b481a222c7420a0f413e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: bd7ca0ff2bff79b330746f4eda07d745
    md5: 9b16cb548c2b7f158069c89de8f9ec57
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_density.res.nc
  hashes:
    binhash: 3ec6d1b3efa1ba32628531ed432bfee0
    md5: 44b4cf00ae3873629683cf5a7fa1a806
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 21f06a3f4f6318ddcf20a121027068d5
    md5: e89480211621e0d899ea8d283b01854c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: beefa64373f188730475dd96bcd8e85a
    md5: c8f13ef0bebd54a79fa6352972d1fb30
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4c2ae7d74ab4c9f1d340a3c8253d5f8a
    md5: 23e7c996ae3b5a8e264a2be0dc132d07
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f00e563388e702a241957c465cfb6c02
    md5: 5dbfb3088571b9218ca89b2341c6f996
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 402f77e918cbdad8dffbb058d58a2326
    md5: cc09610645e8d8952c1ef3787aa86cd8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 02449f9536a0672c10612a799976d1dd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_solo.res
  hashes:
    binhash: 77e28725158b048439487086416924a2
    md5: 647a9d0968dc8b1823d1a78629e781e1
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 52dc3134e80e963b9b1c4e8ffbe2b63b
    md5: 3ce75a2faf7b29557ef85f5fe8ea435a
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8b2e06ac8dfc777e8b3238efb1fb7579
    md5: 3f76630970382ec7a8df2b9d01ac5553
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_tracer.res
  hashes:
    binhash: 33c8cf7020eda012773feb32353762e0
    md5: 7802c99774c0264a26a6e135cde876f0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ae67d3a4087e765e2449fe3f52b81ec9
    md5: a5bfeb7807ef89e6dd4726f1f11afed4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c982d5a46e0ad6b28f7773664c45bd9d
    md5: abbf11c81c696f088d4baf8e148becd8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9ab66f18e428b7cd58bd008d0e1be62b
    md5: e35331186458c9d63252fc49898dd3ee
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart313/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e650b77b0489e5621c7b22f8c682ceb4
    md5: 2c2db874c06c2984e826857e29265381
