format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/atmosphere/restart_dump.astart
  hashes:
    binhash: af9b4d8758b2470fcb22700a54700d78
    md5: cf84936cd50eea8f888caa0b7897e618
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/atmosphere/um.res.yaml
  hashes:
    binhash: 88e80fad58667aa4f73f23614345ebd1
    md5: a2bd27827e9e86ee72411232df424ec2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/coupler/a2i.nc
  hashes:
    binhash: 0af283aa0455838a25fac2b978896465
    md5: f3581c329ba039895ef190f3dce11f34
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/coupler/i2a.nc
  hashes:
    binhash: bc59c2cbe881d2eb32c244bd44efa8a0
    md5: 6c876d3afc82af7123fa3be9d4bf0865
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/coupler/o2i.nc
  hashes:
    binhash: e5845b26883c41c831b2b7224738a719
    md5: 330f2900d411b0b347a69bfe86fd71e8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ice/cice_in.nml
  hashes:
    binhash: 316e463b22e0a5830c9013f846226b21
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ice/ice.restart_file
  hashes:
    binhash: 09bd96188fc8c054c8f8c5b2aa970aed
    md5: 1cf1a621cf79abc10eff589af60a3455
work/ice/RESTART/iced.1848-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ice/iced.1848-01-01-00000.nc
  hashes:
    binhash: ecab4b1d15eff9cde25a2f400e21a5d8
    md5: a627877dbfe5773aa2b64a55aba9b257
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ice/mice.nc
  hashes:
    binhash: e6e95dd7229e27ebfdc7a859e45bf487
    md5: f25734542a0140d980e2cf33fc18fa79
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_age.res.nc
  hashes:
    binhash: c6b7765a0966cc8dbedb521b4ff514aa
    md5: aae938526759d22099c491d38c995409
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7cea3eb3ba57ab37a72470f35c2ae2a0
    md5: 74c10110e6043a5eebc0eae89f3c4cf0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b88951e5516409ecb6ddf2d5ec0f0612
    md5: c3c26d13684433d078a606b79a7f9272
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_density.res.nc
  hashes:
    binhash: a44ecdc9317a3a3dda247d33a9fcc013
    md5: 93f15deb88503eb2ee66b5e7889a29a0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8923ca48f63710311ce7be0c829d7991
    md5: ecc9180e47c8c0a9d2a19761a0aa7562
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 63c4105c67f54bd20715c958b98b271f
    md5: af6b06ea741445579f778e09aec32844
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a168dee4abe20b49ec353668db38acc9
    md5: 7fabdebfbc7054f17ce8b37ffb776060
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f35c8d73d10d68a51cec0d63449a798a
    md5: 08a78244b2b5f2db3cce68f20b16f910
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ed9c334731b13d198e84d91a26ca41b0
    md5: 2d5ad865672afbe98eba83bb3ba9ffdf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b6488898891baf845ed1fe9736305757
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_solo.res
  hashes:
    binhash: a1f4e01a9344779e73f8748bc9d2628b
    md5: 8a049249af9849aa80b3d69a8b115f57
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a68732139895f625d15e0b36120b6f7f
    md5: 2abbd637899d9ecddaa4956398795cd6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4d03dd6ffc1dc138ef346fb82cdcc0e7
    md5: 2857328385aed93e81c0cf12a17895fe
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_tracer.res
  hashes:
    binhash: 6c2929ca1414c47e5ef9efa140f0d209
    md5: a37e9b6d838828bdec9f0ee3096a8795
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 301f14b162979c193f7e9b22f04c666d
    md5: 7ac69542fd4ef913f74bffc166833ef0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 651a67d8a64564b67d8a79de6f1782de
    md5: 53e1758f7948dcf508809c1aeb9db74b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fccbd90a92e5b9d8ad4548283086566c
    md5: ea6a85dd15e9a6ef203629e0901b0615
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart403/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dddc22e30169c7783459a307e03c8cef
    md5: bacf0da9d80883ff359d1698b4bca795
