format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/atmosphere/restart_dump.astart
  hashes:
    binhash: dd773692ba7e46e4fa3e6051dc125b78
    md5: 66a2e94d14c9627da153f46e8cf0cec8
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/atmosphere/um.res.yaml
  hashes:
    binhash: 4212d3b03bfec4187c97543863e264fe
    md5: 0790a3d8a94ebca9b7699d0e23d7a469
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/coupler/a2i.nc
  hashes:
    binhash: 4331e40278ab2f15c1c337ea6caeac32
    md5: 1c749040add406da53b3ff0ad2778c8a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/coupler/i2a.nc
  hashes:
    binhash: 4bef82fc4a120fde0abef5fb3630cf2c
    md5: 0c33f880a2719d6cc20f5498aa158885
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/coupler/o2i.nc
  hashes:
    binhash: f09cd0d640a487c10809c43a3b4c815f
    md5: b978d91cc6499c449bc4e0cf70f4701b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ice/cice_in.nml
  hashes:
    binhash: 6835a21448aa4f3ecdeae0863a503487
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ice/ice.restart_file
  hashes:
    binhash: 90495df9e9d086c9f85c4f35651589a4
    md5: 739b7b8f4cf54d589b6219d1d218509d
work/ice/RESTART/iced.1270-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ice/iced.1270-01-01-00000.nc
  hashes:
    binhash: b2bb729a5c2d4f203209996b0dff9d55
    md5: 994b49a8718d0ed49ee98598e26e5e55
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ice/mice.nc
  hashes:
    binhash: 6d77cb5e4e28ed49a222c871139c1574
    md5: 94b3b23ba74e19387c25c572d47fe732
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_age.res.nc
  hashes:
    binhash: 9bf7161a2b2a44b6456087ec5684df3c
    md5: 431d3c52e521be904567bf9fc52f912e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3381669f5083dc0e2b7a9d0ac95f0ca5
    md5: 8d860752b3f8f23ebd2a6a7692c212af
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6d3d7e6eb096916f315b3bda1adc76cd
    md5: 3bc5ce6f73ba898ee3dfd75eb47fd44a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_density.res.nc
  hashes:
    binhash: 24a1c525eaebf47ca95c8eb5733f2e4d
    md5: 684dc415acb621a68d57b2b5dc00484e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_frazil.res.nc
  hashes:
    binhash: cb882a20efd0f79fc9560c2c960fe5ba
    md5: 46d7d3e0d13ad46e1f44e21f3a4edf41
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f99d86df978222434e72498e74765565
    md5: c9824a9abd39383f6b5a6e909deee45d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fc606c0ef2f840d638860fb9d1fc0c13
    md5: f224a36778a171210a77195665849e01
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9a6207f13016e16439416d56fe611b27
    md5: 72700cd87c98cc26dc909fd2f01df55f
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9bd7d7a1d49d03ffd5f07eb19e4d104a
    md5: 4f3e90f7998e2bca51b0e0f8766073c9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 094eeeaddfa96abcd0c5bf4e060c4c16
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_solo.res
  hashes:
    binhash: 98a3c4fbf38eb1d749cf919a9fb9ea11
    md5: d4358d3dd780dcb44a752f6a2fe9ba0d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1cb87060c215e7df3d50a0c9ccc07ecf
    md5: 2421ff68b23c69a2450e3a429ad1ede4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cd85196811f39eae8df4f3ba687dea9f
    md5: 3e4a5570b1e3453b65deb5643589eb65
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_tracer.res
  hashes:
    binhash: db15175c621b593e1193a79f12f2e9f3
    md5: 03ead119cec959ff663a3aec4c527dcd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c206d00afd42fa29522470472ae1c4ff
    md5: 7e1092a518356567ea1a87c771501e93
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8f0b4467752868d4b21547b09e79a42e
    md5: 63836d62fda65ca5314f81148b079e36
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 23cd260d81290125ee760698d2bbb8a1
    md5: bd40a4add6a11217d999ce20a956a92f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart386/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d1c36e4b3477723e2f7329cf30044188
    md5: be3bfc4455ccca2386e2438f9c20169d
