format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/atmosphere/restart_dump.astart
  hashes:
    binhash: 6288f8a4094a2e2f42ab25fe91a87dad
    md5: 3e060cfc5ad3156f03daf0887b7c8fb7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/atmosphere/um.res.yaml
  hashes:
    binhash: 6d878b39e6afa0ed649556e90a5cf2bc
    md5: 4624379d388b77012cb645f58f1e0a40
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/coupler/a2i.nc
  hashes:
    binhash: 784f639d30635c43d5f326b38a5f961f
    md5: 07a6325402ed2d50509e0a533a15e649
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/coupler/i2a.nc
  hashes:
    binhash: 830934c9f60fd72a87ed7c409eea7cd5
    md5: ecff5a9877c11ae6b119e8442bfa7fe0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/coupler/o2i.nc
  hashes:
    binhash: 752e43a3a76b2f4a62e3b6c1a3e3ff61
    md5: f0842e5bcb0342f77652c00074bea6e1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ice/cice_in.nml
  hashes:
    binhash: ebd57ff2b63f719df2aaeaa579fe0f2d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ice/ice.restart_file
  hashes:
    binhash: 0bfc0c1e6fbec9d2d7f7952f8d05f39e
    md5: cdc4917ead853fbba2138b1079bd89ef
work/ice/RESTART/iced.0916-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ice/iced.0916-01-01-00000.nc
  hashes:
    binhash: 506be4404016bce447c39f3e7f518494
    md5: d046feb1985fe83b9d3c2da1c6697eef
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ice/mice.nc
  hashes:
    binhash: e74533e5261149778ac72530136e74c7
    md5: 5e0b0342e42b87b5d62f595a0770c376
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_age.res.nc
  hashes:
    binhash: 3ea31c8af619dd112e36cec82e5dd05e
    md5: 210086152fd8b7867308e24688048e79
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 331fca07bef95befd734c2c77b29f94d
    md5: 0ee464d9e0bb8b1fbfc21524eb0664ca
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4cb8231c622c61485e7073d97d939854
    md5: 083078e152ce27f87e90eb2b67172927
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_density.res.nc
  hashes:
    binhash: d6759b8987d9b7b1e256407d69b3c50b
    md5: 9bc56a7c3cc3241ff39b044f7b05b079
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7c1be369ecd573ff1faabe9019b22669
    md5: 64842e1e8bde0b9fbe8deff568f6ada1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 31dfa42027be35deebe87eb23a4c59e0
    md5: 7c09a25b1733e8d81080f93778b95baa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6056aada4614f24994eed4336c5408c0
    md5: fb109167594c252510773280835b572e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 79c1dc2fef54e4f22cdd91307c2d383b
    md5: cf271301acb1a9648d38a5b636e118d9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 950c90bb73e771a4830f4d01c065b217
    md5: 0ff7fa0f862a5ff7595248dcd4386743
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cf5e8ffe23006d4c9fd2f3ee876faed0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_solo.res
  hashes:
    binhash: 92266effb665c19623fb5306cc722527
    md5: 9cfd901bb576532bd720c73cf9d20584
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1ab4b109a793cbc4e2c477b535af880f
    md5: 5e79daa8d271fbea2409e9bde2bb0b3f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d2f6479fafc9d5aca027cf5c5852a337
    md5: a507e4f3cde9b7a86ff0a234471835e1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_tracer.res
  hashes:
    binhash: 830478d83fdd1659295f05b47c601c7a
    md5: 638029238046db6ca2c5feb75e88b680
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9c35796dc87a74b0ea1a36235dfc9c24
    md5: afd50717ab54ee7690f7462f3289f01c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2a16935bc6bf2a23cb160f12ffe72c06
    md5: 15b69973e01938f146213a28672086c9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 30aa2646c08cf24f4f585b689fd76bc2
    md5: f84a230269957da2cfe524fba94e0630
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart362/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e4960ca8099fafabe477cdbde84c9351
    md5: e1fe150de7212b445810c9b02ca3e3d5
