format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/atmosphere/restart_dump.astart
  hashes:
    binhash: a84db761f1f2d8726a1db23f7a5f5963
    md5: 353284ae72757a7c670541c74696d598
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/atmosphere/um.res.yaml
  hashes:
    binhash: b73962d01756490aeda55db2da0580fd
    md5: 6e866c1ad6ec56b5cc7d2b4cce0cd609
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/coupler/a2i.nc
  hashes:
    binhash: 84d9e9aa0de1b4053449367f57fecc14
    md5: 80246995b190e0ea0c5c54af40c8405e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/coupler/i2a.nc
  hashes:
    binhash: 6a3d7bc39b43e391ab5054faded01679
    md5: fbb4f192ebfc423f16bc5d0753903238
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/coupler/o2i.nc
  hashes:
    binhash: 847da9db4f9b4fcc4ee758cce5916737
    md5: 06a238c1aa94be2200c1f0877f047979
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ice/cice_in.nml
  hashes:
    binhash: 8a52baaef852ca0b8fd399c41c0014a2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ice/ice.restart_file
  hashes:
    binhash: f4a743d19152a0706cb36ea1b817a161
    md5: 8c00a030549b056a502b723df0542bda
work/ice/RESTART/iced.0991-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ice/iced.0991-01-01-00000.nc
  hashes:
    binhash: b3a090502b73c4fe8c0cba2b5ba74555
    md5: af7939479b7ea61f709814cf0819b28a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ice/mice.nc
  hashes:
    binhash: d37d783fbd7853c2213658bb4a8ffed6
    md5: be32f60772e7625f86a71e2c8570d4f5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_age.res.nc
  hashes:
    binhash: f8f37010b1a986bcfdf8cabf87ff2ab6
    md5: c5057dbc455a0cdab4994df216e0b569
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f95ba7e98d7b0f9ea4292f54ab52a593
    md5: 38a25581db0a690a76551eeaff2c91b4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: aac03e7f9fdd53a7bb783be03eea340a
    md5: 6530f100695caa7300f65868545f6665
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_density.res.nc
  hashes:
    binhash: 10b8feec159728cc57bf3fda311676af
    md5: 53d0c5ec8df50beeb36f873411a884fd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 468ca39ae8a029b4ae72d2f513e5fcd1
    md5: 387a712a1dbe292516dbf7acdccd8a8b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f7d09a3b0daefbbe7217abe86ee0bd90
    md5: b09c47ed773edebc4de87a24a12a3605
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d87ed5043578e1936c87bf790cd9f3c5
    md5: 25ddf9dc694af6cb9ffd5aecf722f7db
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 01152c90f1c80ad7167131b33e7a9570
    md5: fb3359bb5f0810b09f1aa5194c7cec58
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2836fee75f654aa3cf174bfb804cea34
    md5: b20455042302e9bdb016ff985296664e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 57390c8d00cd0d88438ae7b56b164314
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_solo.res
  hashes:
    binhash: 9f61caa36aee9a9a946ed3265c61e6de
    md5: 5ad3a1fa152012534a9760f9a62eb5b3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c310424e901540c10c914d50095e5f15
    md5: 8a765f90acacb05e565293d5f4384fe2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e8dec6fe398f3892ee703fe4f555d93f
    md5: 231fab11f5cf494ca86a39ea96928df9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_tracer.res
  hashes:
    binhash: e311642f6b3d167abd40b337472dffa5
    md5: f99541cbed74b7ad1148ac8c49e2ecdd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 859cb9bb74957b3587bc058f04bc6293
    md5: 640f4cd3111f33ade908c0b0c086f553
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ba03e22a6172b65337a1b82bb266449d
    md5: f1bf00869b55af46768810dfc743cb9a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: beb6ec3d16a2e1365aa0e781c5058c6b
    md5: 30acb7fc79a390b24a5ce56713244248
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart437/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1865e42f62b7c86c213fa2033b555758
    md5: 91fe1bb76ee72f92d21d579afb2845a2
