format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/atmosphere/restart_dump.astart
  hashes:
    binhash: 8ac66cba52bbede1b7cd9aa8968073bf
    md5: 6e9e8dbc86116accf635d5f07a770879
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/atmosphere/um.res.yaml
  hashes:
    binhash: 752a4fef9acc5be67da9eedbf86f9657
    md5: 7aadcc16ddbb5b407cccf28452fd875a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/coupler/a2i.nc
  hashes:
    binhash: dc46bce3fc0e820839b772b8ba433d7b
    md5: b8b2c1a30f9579d17fd0152c09098ab8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/coupler/i2a.nc
  hashes:
    binhash: 1e2344febffcd19b229a954f3c94f5c8
    md5: 00904c3992f5761c5647177980007f66
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/coupler/o2i.nc
  hashes:
    binhash: d962c97f6d45cbffc309ecce68899e22
    md5: 353e98157b5f5b9c5a9837434a62c8e8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ice/cice_in.nml
  hashes:
    binhash: 21c7768856000350731972ccd700841e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ice/ice.restart_file
  hashes:
    binhash: da0d86a047edbd428635d50f594ba145
    md5: 055d2e72059803ac0b24a3e67a5a4a91
work/ice/RESTART/iced.1825-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ice/iced.1825-01-01-00000.nc
  hashes:
    binhash: 12f4cc4ad9e88eb62c36d3385ef3f468
    md5: 8d46c711e86f9447e2f9c8ad0481ab85
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ice/mice.nc
  hashes:
    binhash: 875da698591c26b4faea21650aaae35e
    md5: a10c6cc46be4b063d2bf26b9c7dc9853
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_age.res.nc
  hashes:
    binhash: 88c650eaf4607d2666b7b43391f1eeb2
    md5: fca36177ebf3bfe59661269e49a9dc55
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b655ca1237f7404bf1933e5962ded7a9
    md5: fc7e77a8aef84d4e353a7ca5af2ac29e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 439a56e2abaf69b137cfe3f3530d89f9
    md5: 5199c29f5e6d16b883f3131bd09acf52
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_density.res.nc
  hashes:
    binhash: f4fc70d83d8d58f67966cc94d675f02e
    md5: 19744701253ffe299cd139ccdb843f62
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 722f393f847249b10694d7f41002058c
    md5: 5605ea7d02d9c1f5670aaf76e6908e21
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a5f16d0c09cd2ae81dc3deeea7bffad7
    md5: d855dae5c140064834bc95f58b91328f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c7652f417308af0fbf18b6c5c36c107f
    md5: 04edfa27180e3e3f5f03e5d1dcc5e7fc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1ef28845b283780179922c037343d79d
    md5: 24917f19219e3c314b26a7b15a30faa0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_sbc.res.nc
  hashes:
    binhash: eb67e84cf1e17ee81c8713203151fa3f
    md5: ee7759b9ceee544474fb0b5510a4f4f8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1f0da07312d555dd38c75a6299e7b2ff
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_solo.res
  hashes:
    binhash: e6a7f0a520e65fda80070904bb12c4a6
    md5: 3b9f7fe526a57729dca8db0e5cb968fe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6d9af3ad67b4f382ada0c52974ad1e1e
    md5: 395687023cc02cf1585a3ac19a1dfa58
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cc3b9cd19e47b170121da57856629ae3
    md5: 4880fb1aab3ff9023269b36265bf16e2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_tracer.res
  hashes:
    binhash: 2971d11a633a96f277271576fe4709e5
    md5: 1009f3b2590c86a424c6671d1291fc05
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 25e6772af383f65283ff96e7612d4869
    md5: a071d5ce05fa23e8c1aca4f79c0f61f6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f98358b05c3d302cadc8be6a6a0c6e8f
    md5: 9230dbc68de3a873b3c1ea238fe9769a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: aa424da88820b6a93cd7e509e8fe2bb7
    md5: 7aab2ff5bed8a9bc3c27efb26a04b454
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart380/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 93a2d71ed19b18537fe3ea911f24c907
    md5: 9893781e40d404924f081d484b44f97e
