format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/atmosphere/restart_dump.astart
  hashes:
    binhash: 95dd9e07908350970bd95d7c2d50e6ed
    md5: 6a5aa104ec9134d6e349dc4d21555422
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/atmosphere/um.res.yaml
  hashes:
    binhash: 7f809858cc15e2f3b8444c8a7feaa3fe
    md5: 92e0dc6f0c4814fbb058c4436f93077c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/coupler/a2i.nc
  hashes:
    binhash: 0fa8ee5e91ff0ad772b126f027bb6c88
    md5: 1572b230b76697d1fe34c891ad0c5c7b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/coupler/i2a.nc
  hashes:
    binhash: 0aac5f07f8b16bace4eeeddf16ff43ed
    md5: af260fb68d1aa9114f493e4fe7d3cfba
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/coupler/o2i.nc
  hashes:
    binhash: c8c228c0166b4005ed1a5d457e8a1b84
    md5: 9d6f4cda243bd05ca7cf6f946c7eb3e1
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ice/cice_in.nml
  hashes:
    binhash: 58a0261db4203336896173c64133a95e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ice/ice.restart_file
  hashes:
    binhash: f424e33b0e7f31feca29c6d2c7e8ff18
    md5: c6cc0ae2446c1aee35b2400c572bd04e
work/ice/RESTART/iced.1302-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ice/iced.1302-01-01-00000.nc
  hashes:
    binhash: a2e8a3195e87662220c23b0e4feeffc3
    md5: 79fdd5237af46d8f146f0f75632ebab8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ice/mice.nc
  hashes:
    binhash: 2862c3c3592b64e13b1f34c7e332b161
    md5: ba5ac0c9140d0010db49d7e247a87cbb
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_age.res.nc
  hashes:
    binhash: ab06e116f0616d149da43331735f839d
    md5: 463337d19b6dc9beb6bea3ce8f2eee46
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d1aa2f8ea0593f8f9616b09afcc12f52
    md5: 67466efdf905c6b048c3afe0b518f8f0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 24d5a216411d99bfc51e222719821578
    md5: 69336410d2b54dcebb58c011a08260f0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_density.res.nc
  hashes:
    binhash: 9537aed02d1f11a04730654fed1fe275
    md5: 3e0691fa987c1229a6285214083ce7c2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bb8e1e2f382e1877eac4179d2025c684
    md5: f2aac9c591439258970978a794da7cc2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 37641f0a5a357f5378e240656384fc41
    md5: d5d41148ce82e3f9d1a2f575eee9a06c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 22f24cbac8ca91e08e79f3346e85fa65
    md5: 29bd0f31df8f0be45b7fa4e033243a9a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1b4fb484f2f824fd4b84b02d5024a4f6
    md5: bdca219717fa5fd01e1f779bee34bcfd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 46c06c4fb3509cbbacf84d5b3def2652
    md5: 23237c0b949cdaf93bbcf23c4b17774f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e3738dca2a7cf3190f0e9c1ffe15c132
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_solo.res
  hashes:
    binhash: 168a050273170a73e8f103d08ad5b3db
    md5: 06038a792e9742ed3d337408b4b51d10
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 237b5910f38fac2ab6ccd50ba2d8190e
    md5: b608206f258ea92b9e44696c3529d28e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4957b82b71cf65acfeab785fea049730
    md5: 13a93489df192ea0bb43f29793f6c562
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_tracer.res
  hashes:
    binhash: 1022faccf06f42004390ab780e005900
    md5: 33535cfab54ac4fe64a558a2f3d76549
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8b4970e253d8d1fba139e5cb73c61055
    md5: 314afb48422d382153e67b481b8ddfeb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8f0081fdd5d56f57c3d92a48d1ee6edd
    md5: 927656b0b4c23dfe36c3e5170268757c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f59520f0d967ac02c7cdb00dcfba35bb
    md5: c003787c95340dcb762eaab900e570f2
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart418/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d85771d8a75e16c54160777190730c8e
    md5: f2015f80d79017f700ccb66fc9fb0ac8
