format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/atmosphere/restart_dump.astart
  hashes:
    binhash: 54280d3f71cadb30164ab18526b4e339
    md5: 728e54992a6be4893679bdecfa2b5dbe
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/atmosphere/um.res.yaml
  hashes:
    binhash: 80d4c4ce8399c46c9cc4187bd098db1e
    md5: 4f6b610a67abc755f9e35b0162cc2c49
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/coupler/a2i.nc
  hashes:
    binhash: c13e40ba367bdbeb67685dc7f1d3ac05
    md5: 883e74bb5334b0842ce6eb855a053da4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/coupler/i2a.nc
  hashes:
    binhash: 6621527227364c43eeb74297e2810e02
    md5: d5a43432338f0797cc9b9ccdd5a8fa1c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/coupler/o2i.nc
  hashes:
    binhash: baf184deaf2827dba4103533a9158e69
    md5: a0cba201e87c29c0db00f19e10804710
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ice/cice_in.nml
  hashes:
    binhash: d6cfc5e49ecf948d5e672f970ba6de9f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ice/ice.restart_file
  hashes:
    binhash: 2e53f8b121804b19bdb76a1246f74f46
    md5: 358c875e2ad94a3cbf045855794a4d40
work/ice/RESTART/iced.0888-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ice/iced.0888-01-01-00000.nc
  hashes:
    binhash: 0e91fcb6e191072508c561c07798f253
    md5: d18cca27e4bee2e385fe8110b5ae9a9a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ice/mice.nc
  hashes:
    binhash: 2b7b12c998639bb2b71c1cd45e5d4b61
    md5: a8007fc062c1c8455e5a8a8290133157
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_age.res.nc
  hashes:
    binhash: 93d92a41300b9e329a760b61b78a0f40
    md5: 0cdf6c4eb392addf539081039f1e2190
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3f62438ed393aa082a41ccdb47a6d1cb
    md5: 9a4f1038341372fc397be4740b111c8a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 811d8d067d3bf6a015cd85c34f2bc463
    md5: 0dae53320bae7a6e3a40ea79999d1bb7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_density.res.nc
  hashes:
    binhash: 09dab51f92e20241590105ab66a0c183
    md5: 16f5901e3d60be9caa56b68e6646e9a2
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 35c20a18a1e9c7963bdbf0f086e9d960
    md5: b97052c3429f18df35f749a93045bd54
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d43019d181311b5a7d0c77cb1367e076
    md5: 471c56ad0033c8f9febe004bc6d02b10
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 380386b6ecc929caea5a739e31e0420f
    md5: e78e3b00c01a2b1803c100a99ac44ece
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: efab46c8968584c5dd1cff74fa3cf69c
    md5: f0675859a0a0b6e6ac2601ad9759a17a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8b09a06c3a6f7e808810a823441d917c
    md5: ecb103ad4ffbb70050da6bf2c1b12b9f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ba0126b1ab50e0318926ea00adb49381
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_solo.res
  hashes:
    binhash: d4b380d17261db77891ea83a87a7b847
    md5: 9072b1b967b701f4c598a4e4ae9d302a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f537ab28bde20b10c9971ff63ac43105
    md5: f1e2eae469e3b397893e885adf627610
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b6fde3148b317efec36fb0913355a5bd
    md5: 1b3c401afe8ec0602a7109276b1ec98e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_tracer.res
  hashes:
    binhash: 791ac0871bdeb16070e97ea61287a13c
    md5: 9415ed3028ad89c241aab40986c8ef59
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9197d85dcd354f55409a263f36a1d9f9
    md5: e52c98ecfb4c69d21cea848d2f9c5f4f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 988d4b7ad0641d9a5566c0ac04b0c6e8
    md5: cc3f12291d6752a57d6de78aa941bae9
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 477a8a71df859ae357bcd1dbce11a103
    md5: b8ca6423bfd92d233e4e541a7954d836
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart334/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4bdb81bdc451f430bb745507d8cab21a
    md5: 3d52940d18dee4626f8efa49fcc582b4
