format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/atmosphere/restart_dump.astart
  hashes:
    binhash: 8a8a92d034b7113a760fffe07044b8de
    md5: b8897825c067db4999d7f45a124434d3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/atmosphere/um.res.yaml
  hashes:
    binhash: 5b7dc6805fbd8b76ef1952b497ffe077
    md5: 36dffa5e394f3d947032f55efe2eeefe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/coupler/a2i.nc
  hashes:
    binhash: 322f1f10f210e0a198bd8bbce5caf38e
    md5: 90934e002de1c37f1287ab9b959fa1f0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/coupler/i2a.nc
  hashes:
    binhash: 7619d252c70fdde37707abfabbb15524
    md5: 1fd3cfea26eedd5ed8b933c20cf8a42a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/coupler/o2i.nc
  hashes:
    binhash: 4e01278cc59dfa46281f0a402c498bac
    md5: e2ceea965448bf67751475e11c3ab215
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ice/cice_in.nml
  hashes:
    binhash: 53488e882bd30835a348d3367f1b97c8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ice/ice.restart_file
  hashes:
    binhash: c197933e4242ec659a2181faea9500a0
    md5: 27b15cb4e61c6a7e1f3e92581af6870b
work/ice/RESTART/iced.0884-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ice/iced.0884-01-01-00000.nc
  hashes:
    binhash: 51cc1802deeca0c74038a169c5f3ded5
    md5: 01dab591216a6019d1c3dd2665ccdc69
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ice/mice.nc
  hashes:
    binhash: 52b18760fbb148f00aa4766f430c5288
    md5: 07ca6ccd97bef1415afd74319291c54d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_age.res.nc
  hashes:
    binhash: c0134f282d71296e932c2a6be800b397
    md5: e942f3bb3030d48ba552533179287f3a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 20a8b52c30ac269b7ed90735835da972
    md5: 86748f49c8e97a60b25df320f6dae74d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9dccb8f2ac8ad21af8ac7475ab4666be
    md5: 2553726c855bed7e832094387f735cb0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_density.res.nc
  hashes:
    binhash: d5da2887e1be935900c03b0cc6eb73c5
    md5: 7d1a97ca1d968ef5174037e289da9a51
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 52855bf01b349da816bdfd2060aa1a73
    md5: 105af2a646f1b80ddfd06afff018f226
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6ca823a402f0b876c59bb9417c5b73b0
    md5: edb114716210090da17a89429ccf5153
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 54c02639996904c212894274811cdc1e
    md5: 2017505cb4dc2dee122667df4f81f4f9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: baca31a010bdce7879e7f3f3ae9b6cb2
    md5: 8f3cc052abafafc6f8b5c73dbf9dafa1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 63b8d15eb1d1dafb1b527ae04fde9921
    md5: 697a4d6d02ce82ea818e82a6bb7a5336
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c17737657ec07e8f361a57abc0902c4f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_solo.res
  hashes:
    binhash: 775babc1d0c29087a7ccc4c0ad1ec25e
    md5: cdb88580e0fbe9c1192a662ae08005cb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 32477c317c22d592a44f69aba939797c
    md5: 31052e390438afb29fdecf73fd30b006
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 047ad9b72a8e607faf9f098b356fec64
    md5: 4f754f3317409aa47380ec1adcdcb56b
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_tracer.res
  hashes:
    binhash: 2435c51dd081a22f3ad1d9cb6d1e2b6e
    md5: 1a24a90bdbbee6936e56dbe754cfb567
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b81112fea3cb280d4cc23059c7244cb2
    md5: ca651dd83af0a1b09e0c73cfb0df2510
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 17d36a14d512607a439a79e7963eb95b
    md5: 45e476ece260dea8d92447615d5f15dc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: bfb14c38f095cff9745e7aa37260bf03
    md5: a6c01530ccb0785f7335bfc6683ec665
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart330/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 984b5311156915afbcebfeee6f185833
    md5: 6f49054e3f2493ffbcb28ae3e1ff0b00
