format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/atmosphere/restart_dump.astart
  hashes:
    binhash: db1bd43b6a64ac2c3ad51a6548f064f9
    md5: 15d3eeb2de5780f33b6681159ceee8a2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/atmosphere/um.res.yaml
  hashes:
    binhash: 7d76c2b0e69d9067578ffab9c4a7d71f
    md5: e071e6dc3f84dd5b9a19ef6a928eb298
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/coupler/a2i.nc
  hashes:
    binhash: 31b06af1f64e4c8b85e43101533fbd7b
    md5: a26c02767ccb60cb2a19aede4659df81
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/coupler/i2a.nc
  hashes:
    binhash: 87ac2f2f9ed021278b6d3324240050bf
    md5: 1db8fbc04f9777a87440e3ae22424d62
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/coupler/o2i.nc
  hashes:
    binhash: 1b44d0ca5d7e9043905013efd11ddd18
    md5: 9d507f6f94e15528c9578416006c06f4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ice/cice_in.nml
  hashes:
    binhash: 0ccb4637ab8109b72916419485962624
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ice/ice.restart_file
  hashes:
    binhash: 1de6fa0acb1f6575c62f3575d0452e95
    md5: 9145355a2bc4e3e66ebd77e67585636e
work/ice/RESTART/iced.1752-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ice/iced.1752-01-01-00000.nc
  hashes:
    binhash: 10aab528b26343180400bbbb4c4977e3
    md5: ba0130baaac38032e8b2e9c1c72449f8
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ice/mice.nc
  hashes:
    binhash: 85a63b1ccc6bd609f99fb36d40c12699
    md5: a85ed1fe6ca841a5e25fc806ade5883a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_age.res.nc
  hashes:
    binhash: b43e80157bc0487cd665176b0a29a32e
    md5: 34897ceae2b949d04800b91d8e7b98fb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9298b9a77edd12187c39c7ff5088f6d5
    md5: dfbcf91a2c420c24068e6a05d7ea9f90
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0914f2608f7806a9b4b8b6d96548b20d
    md5: 832770a10b9a25652a70ee10691de55e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_density.res.nc
  hashes:
    binhash: e6dd06c1440fb7e9b932d762607762ee
    md5: 82c29286c6351204f83cbad5ee473212
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 62de761a601a2630be121d7caebf8035
    md5: bc9356cad6a118c4d5b6eed1cde99c14
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a1ae26847938fc5a46d85a57cacbaf11
    md5: bf339baf75457dce6a8adb374bd390f2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff956ecd938e65fe863dde995e722e26
    md5: 1c712ab63cb5e74b780945e0866795ff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6d779d399da0a8bec36bdc9759044a4d
    md5: 078187e061e7debe02fa0d45f65f85c2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0d500f1115378c4ddc16a126bed11cc8
    md5: a5f2772cfa9da62834a15f3722a75d25
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ac33a6ec828f0ace34fd031d31d01105
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_solo.res
  hashes:
    binhash: f0e188be01e4311b9c192c8e4476b60b
    md5: 5e8d3754fd07b59bbdac1c59b4b180a8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d3818b408ef367c36301fe774a88f75b
    md5: 4b01dceafc9885c3ea7aa3e632c476ba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ccd7f74dda0212e3a944cc521d267ba4
    md5: 16f8123221da383e2a51966acf9381d2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_tracer.res
  hashes:
    binhash: 0ec30749500c837cff9f3c009bea681f
    md5: 854fb78d607eead049f45742d35b4e64
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4474fae18838ed573f2f3f13ba067997
    md5: 519f029cbfa28dc75301e35a31345bb4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a082977e11737c00b4c751cb7f51ab8e
    md5: 86908e2ae0140a05964cf9c757a354ed
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2e000183bd6f35b39c9d23c809a90966
    md5: 42828b78c56654de24711b89503f7df6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart307/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 457b6f4b1737ff11d0bb895b951a65ac
    md5: f92e82beb9b8dc3db075e27b4cf5cacd
