format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/atmosphere/restart_dump.astart
  hashes:
    binhash: b4ecbf74550570618c07dac04c6d09f3
    md5: 8dbbe657b790aae92711573761f655a7
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/atmosphere/um.res.yaml
  hashes:
    binhash: 226b77892100db9178504b09b2be1da1
    md5: a15c7d9533577cfce20c1fa6d72c939a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/coupler/a2i.nc
  hashes:
    binhash: 4ec566161c2bf0d2728374c4b627fb94
    md5: d8f7c23deecb161fa31cbc88089b4beb
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/coupler/i2a.nc
  hashes:
    binhash: f1d3c615bf04a3353db5b554c833dd30
    md5: b5b2cf183f1db5e7c7965151d9d367e3
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/coupler/o2i.nc
  hashes:
    binhash: 08fd746a546b561ae8cdbebb951b2ef4
    md5: 6e6047ff32d8cde203e398cb717e8c70
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ice/cice_in.nml
  hashes:
    binhash: 33af05c2a46147147e6a4cb554e267e8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ice/ice.restart_file
  hashes:
    binhash: 4bb2fbd8e9d9e8aad2da2bd727ec832a
    md5: 17d57599dfcd410ba56a8c20e91b1329
work/ice/RESTART/iced.0838-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ice/iced.0838-01-01-00000.nc
  hashes:
    binhash: 6059e2c21f2b1a1713501c5cce800ce7
    md5: e6daadb647fde344f463bb587406b0e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ice/mice.nc
  hashes:
    binhash: 3b5ec0607c1bccd353ffa30a41e73fdd
    md5: 4ac57b6e707992aa3e29cb359718d14a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_age.res.nc
  hashes:
    binhash: 34d6ac4859b6e64b9b22c88c480e3d58
    md5: 25e56d90d71a211d9409c5ef2d1dfa52
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0a6a6f73a22a54a68fc5071a0b815e61
    md5: 5bc32838cf44856ac309e74f5763e7eb
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 7b0a3ad896eaff4b8cc1c062d65134fb
    md5: 9e6cca4de9f7ce92f1ed13301a4399f0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_density.res.nc
  hashes:
    binhash: 49a527f55109f12caf2863855521bf4d
    md5: 2a74e88f613b066b533a8a691661616c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e36a744f3d5895464c4d8f1713d42d9a
    md5: f4c526fe6684aa91c9f2fb7f1ff65aa1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ac507707555b03c271e241ba8559d61c
    md5: 6f954039a226148c1e6d771eb53457f8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 3230ed9673e11f2ac3e3f1a1800e1111
    md5: b6c2b7e28c41903614492d86d6f1d436
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c3c439dfd5be1b7b85bda89f440b3bf0
    md5: f2d581350d59591d1b9ae3734a253ee9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 187b2474e99b93c9ce30b50ba12d9886
    md5: 98b68a0eb3c5baaeb479a5b6ff71d00e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ef6125fc65cc4b3cbf153fe4f44dc5e0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_solo.res
  hashes:
    binhash: c2418d9e4832967133c8b3d4317e39fb
    md5: 798c937092739f4bfee35bd28ddb3d6b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 3fea53e3bcc20356b949c502598e1e97
    md5: 9d9a32dbec50d03d1ad5f576d53d2c12
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6c54d52008fb518a9d1e64befb13198a
    md5: a656518aaf95ff91ee3333002c89b891
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_tracer.res
  hashes:
    binhash: 0028cab027525a5584997c0d26ab164d
    md5: 12e1239b91a96d04802ba7677de86007
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0606720ce39077b942de3c8733f6c37d
    md5: cdcd3ffcf807e8c9c4032849bb36db33
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f1ec40c684a7ea935b1a08634a7e9270
    md5: 55dea1974a369ced959ffb263b805d39
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 60f78c5fbc4a757390657e6415f0f9c2
    md5: 65330b10616d7d00c3bbf6b76629e603
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart284/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 729cacd71eec0fb55e845364c3ec635a
    md5: fb4eb3eec76db1f7f3e0f312083c655f
