format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/atmosphere/restart_dump.astart
  hashes:
    binhash: 6064d3bd2dd62b4c3da41df7c84b163d
    md5: 29b0bdc1560742644a850082a99fe455
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/atmosphere/um.res.yaml
  hashes:
    binhash: 92d9706d01c9c2d9936980dea8642d0f
    md5: e0baa1fb81633ca692395c0134325afc
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/coupler/a2i.nc
  hashes:
    binhash: 4f3607743cb8fe16018256773e6c014f
    md5: 945167e93c30e28635eb9bf95ef5560d
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/coupler/i2a.nc
  hashes:
    binhash: a1a01dc41da901f6ca3223c2d9d7b756
    md5: 3be8b52eec2124fa94723c4e23779fd8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/coupler/o2i.nc
  hashes:
    binhash: e5ae858a6a524c457028a00d4ecd5f78
    md5: 392e9b2fe75abf08d909e8a4e38523ed
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ice/cice_in.nml
  hashes:
    binhash: ac14d320d15692da2bea3e2c52901d65
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ice/ice.restart_file
  hashes:
    binhash: e8c68b8d19b98dbd4cc4d0d64c7ee7f6
    md5: 214cfe5b2bf3fca0e9d78b0023fec000
work/ice/RESTART/iced.1807-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ice/iced.1807-01-01-00000.nc
  hashes:
    binhash: 5067b2578f20f982c9735377c78dc8c0
    md5: 16a2c229f59da339ae63480253d95f71
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ice/mice.nc
  hashes:
    binhash: 8079be80e8def506587ba50612e9b9b5
    md5: 021bc29c3481562edf87a1b82bdf4338
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_age.res.nc
  hashes:
    binhash: 935250a83a2074c58514bbcf880f9c71
    md5: ceb0da0e962d229a1593ffe839b450fa
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6b6326a675d20f2fe1a9fe9be6029d15
    md5: 68af2b82d6f35374e346e63de8ce4f02
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3b55f24543da8ec9df6066c750b23df2
    md5: fe95b793f026dc2585b9acb82b753245
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_density.res.nc
  hashes:
    binhash: 6045ef27c9773358b1acd3e79651cd3a
    md5: ca28b373e1c73ce6c869a57b566ab4ba
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 804fa3dd95421016eef9caaccc74994d
    md5: 8a21ddf1602acf6245c94aba8cc64fd0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a863db067f648df217a7ff4656677886
    md5: 474dc9d13bebaded3214f8808da77485
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 59d58448e2d6965e8e36fcf76819c1dd
    md5: 060d6583a4eb2aa15a5b1053b860ce78
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 639cdeedd3d35ec77ec3973ebba5d213
    md5: fe8b774d1de8b5b5e3753c8109a0dca0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8e43597e8fc6e621d6d7373f25ca1ac5
    md5: c358e4bbd7f8f56c3de7547e18de4394
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5986709e6c26f134190e17e01f093062
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_solo.res
  hashes:
    binhash: a79c70d397a575784246c7f21caa79c5
    md5: a238644cb36a039f37788c27e64a7354
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f9bfe89f4f89101b2115c0d27f14fe57
    md5: 3ab9ef6cbf1412e1dfd88b52ae207595
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 328ab386ee41f02f193de6506954dcd8
    md5: a718285c411c296352e80b97409b4fa9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_tracer.res
  hashes:
    binhash: 7064beddfba88226bb311559223640ec
    md5: 9f1bfedcfb96c8091eff085f9ed7d08c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6d182cdb751dca27dc630b56e34ae747
    md5: 2c55c2931d4dc450b698e3b9d10bb833
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f08ebfe3680b0108ba12540123109b80
    md5: e08ecd751d322a443a4021575fee87cc
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 79ab457a8b43fe7af42790548f2b1917
    md5: d98c8fdaeb5a4dfc58e7f31cf9b91c30
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart362/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4f919223ebac92d92a57b8c4861d04ce
    md5: fe64007f5a2b7e5fa44a91c1aa3abc26
