format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/atmosphere/restart_dump.astart
  hashes:
    binhash: 6589d769e8fb04fd3f12be9728faa540
    md5: 55fa1fce8055553d21b2df965912bd67
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/atmosphere/um.res.yaml
  hashes:
    binhash: 6e41a29a0e93c869002d98b02b92bda5
    md5: 8b2fcbef365db62ce4e76e56ec5d7b1b
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/coupler/a2i.nc
  hashes:
    binhash: 199738a09cc4447ff6399f23c9ac7761
    md5: e8d36f3cb2bba3585e83d136be18d078
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/coupler/i2a.nc
  hashes:
    binhash: 0e595af8d56ff0bfb4d28e77adea948d
    md5: 304f887d5e3471fdabc0a54f73e983a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/coupler/o2i.nc
  hashes:
    binhash: 405e8c673674313df65ccf40bf6f6d5e
    md5: 51dc6f2d6aa07b5ce698f113aee90abe
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ice/cice_in.nml
  hashes:
    binhash: 7190071a66e9b3e1c74e22fa1236dda5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ice/ice.restart_file
  hashes:
    binhash: 13c1d7f30eea2ff6ff8c65423ee2607a
    md5: 0eac3c2bdd5d64441e02711bcf46b448
work/ice/RESTART/iced.0954-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ice/iced.0954-01-01-00000.nc
  hashes:
    binhash: ecd83e21f7998556846dee54aa295c75
    md5: 76e1efa1aabb83c40bd68bafea2a13d0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ice/mice.nc
  hashes:
    binhash: ce3757f95ba7d0159ac53ce97838e27d
    md5: 72c08e2ca70c6ea8482af00aa4e84e0c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_age.res.nc
  hashes:
    binhash: 1f1ae1830345d64d26fd3f15532b8902
    md5: 5a3af92ff17a2c3be16af6de88a1c3af
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f7c6a029db7dd1bf90920ada0e847981
    md5: 71924ca870e9eec90e6a7ab43572e79b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: df00346ea6750fe8e829381aea616cc0
    md5: 6ab2067ae8f081d15622f43313cc1d66
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_density.res.nc
  hashes:
    binhash: f0c86f6502c4c6f0b026004f9733f0ad
    md5: 7cfe6e7750fe9c49d2b674c318f4793f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4f403da0bd36e599d19e832b3cc871f9
    md5: 1850b440999be05a70a7047432705a5a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 65b6cac448803e15d7b4f838ac1dddb0
    md5: 3f58a52d9aa59909c492b14084687b96
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 77ce7720cf3b03f4589cec826a544363
    md5: 2c08b6dd3965f4b3bd40273466b261c8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 72de1a35665475332d652d0ea5a16a27
    md5: c11684ceef10ed038c5932a9c35cfaad
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 79c683a34d7a9417cfaf858c1ae70e88
    md5: c15fa664c3a22dc80cf951b04a48add8
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d9775fe9e2a6c9967051026732338051
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_solo.res
  hashes:
    binhash: b9a27a38911cafc5174b0dac8f8e7b29
    md5: 05a343e357f489892271adc58567b766
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 425500c34504504c7efadf1888d875ff
    md5: d7f12002ec68cbafee97caa2d794aeaa
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ddf46604ffeccd70a83310283e3c7c73
    md5: 8eb2c442a0844d9e9a535a832bc03f92
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_tracer.res
  hashes:
    binhash: f11606637e4f5fa43a1f6a1bbf911f67
    md5: dc64985a047efa98f6d7569057b09235
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4afcbb6e31588eeeb8874f53f5abc573
    md5: 858a39444e4b0b524cae5b3e1d784828
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 14457caa96d04eea775ba608cf544074
    md5: 26390388e77abbb7a3ead863020601a7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c0437e2952591e9a669326bdd0dfdda4
    md5: 1f83f11722ede6e3735f1602920ae47b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart400/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f0a846d201dffeada569d47228749992
    md5: e991c09f48037331a9a6ced0867ebeb3
