format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/atmosphere/restart_dump.astart
  hashes:
    binhash: 35b0a68415a6ec03737c8d91b59bf26a
    md5: 19e1d4343a9c102f185555ded003493d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/atmosphere/um.res.yaml
  hashes:
    binhash: 849b87647e8c04f97f438134886f00c1
    md5: b3bcbc4d486a313119c7183c9df740fe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/coupler/a2i.nc
  hashes:
    binhash: b383e09e3ec2f31d382187ee6dcb33c4
    md5: d223c0a83a10bc1c9e4c6964dd2fc3f5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/coupler/i2a.nc
  hashes:
    binhash: 2bc46ea6ec48890cdee09e1bc521c5e5
    md5: c4507a0893688abe2d5d055370e12363
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/coupler/o2i.nc
  hashes:
    binhash: 136facf70ebcdbe96775c3b00e063ac5
    md5: 608fb32b9ba81cfe1651147814559e94
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ice/cice_in.nml
  hashes:
    binhash: be248b6564671a958775603c3ca1053f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ice/ice.restart_file
  hashes:
    binhash: 8c90dbcd47f240956e76c320cb967aaf
    md5: bc425046a8b1fad4a2de64f57878fff5
work/ice/RESTART/iced.0856-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ice/iced.0856-01-01-00000.nc
  hashes:
    binhash: 8b354a978832b455699b87f39198953c
    md5: abd9cf69a7fb29833d2e2081f9c6988f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ice/mice.nc
  hashes:
    binhash: 0812a18f56c97ae6ca48e62d93c76ad8
    md5: eb2b6c77e681fe6838927e9da437341f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_age.res.nc
  hashes:
    binhash: 1c09beddbe62f2f96b4a2d03d3125189
    md5: 4d11b0a75649ff352cb5d6b1e9a2ba61
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e29a288f142599c84061fdc49d6cfa58
    md5: 1cfdd85db9629f5c9aeb84700bf68e10
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8048b8b2ad0bc2559826095e194d214f
    md5: ea8841b43bfeabdcf8da63cc5bdc4eee
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_density.res.nc
  hashes:
    binhash: e7900fb73873993f7dd79026c8b39176
    md5: 872c64029a7ab4c08a73ba7520d5485b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_frazil.res.nc
  hashes:
    binhash: af5b2dcd62d654714f5cd637a83fe610
    md5: ac1dd13ed810ab5d986b3fcd6217b248
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a73986ed1e9c39a08257e43259a88633
    md5: bb7162097b45b88cb35e9e55a39dc3cf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ef222dbe44b8f6c2b425cc09cb298804
    md5: 04b4be4a5ae66b3c42b29b2b96191046
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 3d8b8fbd5fd53d9c6b3d7518b49e9bf2
    md5: cf5d839e10f2ca03b4f21614115f5bd3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d8424386b6c1494174e47e8b792eb806
    md5: d2b742837df1239c2982ec24d2cde994
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6f16a7820789778d0b0bc2c0d2577bc0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_solo.res
  hashes:
    binhash: 2407cc0f2754be305b87217e749f1c3c
    md5: 0d86d7ccbf781e795a9e581e1719d50f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 389bdce42d9d3b2e8e6932af68d9cb51
    md5: 46f38b4426f379f22c49526f81217567
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_thickness.res.nc
  hashes:
    binhash: acc3ae3fbf90f1885831f63d6d00eb8d
    md5: 6bc53c893afc20246f91c116c34b3de3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_tracer.res
  hashes:
    binhash: 8dbea98e2bc666df7f11da9a58c917cd
    md5: 5c03508804a20b25ba69fa1b46b8e3ec
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9891ed622822231a636c69e16780c709
    md5: 93b425bd6a56ec3308d068520c78f1af
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c7492e27bca7a5bb395f889a33e2f08a
    md5: 041a750aa69692318b6f9132589fd757
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9aa93423d4584ea08e291b0182494cc2
    md5: 0ee524e7b89a574a1b34a95c5c9930ff
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart302/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: ed18dff26ce745607681702b8ea41476
    md5: b22dc0eb1bd1821dcce1f3ae895c9abb
