format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/atmosphere/restart_dump.astart
  hashes:
    binhash: f74629f1ad4942943d3824ad5b7a99a7
    md5: 2e8a11f73d2b9504d4c47f0e2403cf30
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/atmosphere/um.res.yaml
  hashes:
    binhash: 44a699b8d1c99660e084f7671eaef6ab
    md5: a10464511858c1c32f16d4c3e0f68d14
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/coupler/a2i.nc
  hashes:
    binhash: 02e391c338efe72ac4a472d6cdd4dc50
    md5: 677d20035f9179d6fb1e621f5ee5b8b5
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/coupler/i2a.nc
  hashes:
    binhash: 1d0789be71b3a226e8efe54e850de558
    md5: d9b3398ac88b8a30f59f052f5b817c4d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/coupler/o2i.nc
  hashes:
    binhash: d73cdb6526c76cc0cff58c9b5c5f2f84
    md5: 29a0592ce59636192b829445d1684edd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ice/cice_in.nml
  hashes:
    binhash: b2b0f398c83394a33edec2f598f808a8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ice/ice.restart_file
  hashes:
    binhash: f483b144d25b6aed30be129836afcc18
    md5: dc5e8058191f73dfe72c9daa2b6057a5
work/ice/RESTART/iced.0878-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ice/iced.0878-01-01-00000.nc
  hashes:
    binhash: 02d459751b74b7364d3c49c7c461bdb9
    md5: 617b9c3c61cdf8c3ee7a24f4a2821b2e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ice/mice.nc
  hashes:
    binhash: a8f262d64469b89830c1f2b735bd417d
    md5: f73ce7cb4abd7bfb5b528c38b4ccc329
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_age.res.nc
  hashes:
    binhash: 74a3aa41c4d565e4d853c9ab517fecb4
    md5: 7bb9747afc8971b8a2cf3ba02a6d3754
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 652d7c06d8ed07433c3e28c9af0fc787
    md5: ffc0436da3aa2a8a8913baa15a4c5464
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 50dbcd97534d8b7b2f57688907110f28
    md5: 26865b69ac88589d0ebe918f6ef55502
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_density.res.nc
  hashes:
    binhash: ab28872917287c512fa1db08c34a4aae
    md5: 0bc1b765be3dab603de87604a0470e20
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0f4ecc1a6c57abe714dbf117f82a61ce
    md5: badeb46582d43e4ca7c9c6a547efa7ea
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d9825b0eece750bb37a6e96fd68ca562
    md5: fb54e4097abc6f336d374fb75104e317
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_neutral.res.nc
  hashes:
    binhash: cdbb3d4d712d119dbb2f16fe9d9ba75a
    md5: 506649dba1415ff09b4b7c3a0e00b5e4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 98549f00bbee16889e77138b13d3231b
    md5: 6a73528762740423eb420f0c77941ead
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ba1454a1a09b5bb652c748b3af0beffd
    md5: 913d546a552e75d44eec8204085a31fd
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4ae23f415408f9f8edefc0b731f59575
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_solo.res
  hashes:
    binhash: 4ed3b2df23389c27f795e76592d87912
    md5: 758532a76b7454717ddde402f99bc243
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 5fbe39bdc4d497250af7f6069695837e
    md5: 26e731ec58489a4aa4b80e5d63851831
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_thickness.res.nc
  hashes:
    binhash: de062b646375fb885706bdecf51a830a
    md5: 9f488b71941d63db6a5de1453291682a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_tracer.res
  hashes:
    binhash: 7260fdb9e327dcb4e0128159072ba26b
    md5: 5acc8e74874b5efa5f85ebdfc50280e9
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 92817aaac79720ffc3eb4f5af45816b7
    md5: 3848bcf8fb2374970bc1bbd0114df040
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b6587e84d582826076ec63cbfa0cda2f
    md5: 622b20e5d8fd137b943b07f3b0bdaaa0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e5c548f72fb15d85aad2e67fa9b02550
    md5: 5621fc608599e06dffbcf3cf8d07673f
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart324/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d4da4af9ed5b7eae74f8a7871d50b008
    md5: 156c70c84f451d6e2960b7e47bf28c13
