format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/atmosphere/restart_dump.astart
  hashes:
    binhash: a2d3be874d1c8ce5c970841bd9299e9d
    md5: 68f8658bffef9a0e9a1bee07946e46c0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/atmosphere/um.res.yaml
  hashes:
    binhash: 7cd2a4d1f2903895cc765fe595eaf660
    md5: 9220c798a6cd9a08a4fa760b7ab6faad
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/coupler/a2i.nc
  hashes:
    binhash: d4325d84acfc2647f6aea17324dec32e
    md5: 88e842ad4ae4891c67278e78f82ff51b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/coupler/i2a.nc
  hashes:
    binhash: 8a9cdb94ac5ee0a0338028b616b2a885
    md5: d31300f03c79d89431de04a08c7e1b7f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/coupler/o2i.nc
  hashes:
    binhash: 093da80304c2b23c8beae4e3840da2ac
    md5: d7609b425e44de51109deb6d3717f1d9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ice/cice_in.nml
  hashes:
    binhash: f01c93745ff093b1a455eacc6799675a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ice/ice.restart_file
  hashes:
    binhash: 3314d61574a026e03ea9b53017c9824c
    md5: 435b530a354e77ec49d38ca56e81af6b
work/ice/RESTART/iced.0964-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ice/iced.0964-01-01-00000.nc
  hashes:
    binhash: e35dca06b36542ef1c64ae01a80f2796
    md5: dffb1ab439d66e4648bfa4cc952b8022
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ice/mice.nc
  hashes:
    binhash: 6ee12a96ebcb265f46fd465b38648bbc
    md5: b97ff35d363c2ff6a9fb34fce4facd0c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_age.res.nc
  hashes:
    binhash: 3228d2820ae3f518dcac103069c177d8
    md5: 5a50e2c716817d6d6b287d5fe865f3fb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d218ff823d28704ae503d2f8f8fffa2d
    md5: be460e15ee5ddca6cbf3aa61f0d52ca4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a7402577abe92723fa8e704a4a201e6b
    md5: 410f7d0cd582b781ab3898a83ad76f6b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_density.res.nc
  hashes:
    binhash: ce2a49f9990b41902839decc88448fd4
    md5: bbf429a6b5c2f9a493a0fa65c494ea99
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 736ff73de2374263e2d76e49848bfaa4
    md5: e2a433bc3a4c05c744c7daa8dc984141
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: cd33ca16fabb8a35352aab6e21c99182
    md5: ec8a4549a29daba9fcd8460db79b995c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ead60e2dc9284b6abb1be1c532249b18
    md5: e22e3a576b3c25f9ed3b27456ba707b8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 19c6dcea9f420dd084e01925c6fe413c
    md5: 06d53889c3a5dad175930b15fee36a9c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 83a37c016b4ebed969dbe123f5873644
    md5: 0504de5a7be3ee1bb8506d07e975a18b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1a51849cbd07b8dd8ac8f0a893f66f79
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_solo.res
  hashes:
    binhash: 94890c0659ea1c1d51027cffa1affc7f
    md5: 44d0d1a84e2e672103bc78ecfd4bcc3e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: aadaf390b39d2298d5d4153846d6e00d
    md5: cb22c42ba0eb933efed83226dcbb2a6e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 181811fcd265d3a0e58adfc662006674
    md5: f4844c413e1ffa69158f14378b98e5f5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_tracer.res
  hashes:
    binhash: 595bcfeb5a8bf84f8d83c53b326d6deb
    md5: eaefe8c87dbbcdbfe1893d4a7e6c62e2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_velocity.res.nc
  hashes:
    binhash: cb82e656eb1bca36119a7ae95540d41b
    md5: 393facee7bc4940379bf1eee2d75872a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 28c9d34ad067275d13d93b85f5941e91
    md5: f394ae48d686a5f27e1b226d0e3880df
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4a47ae95d6b72e82ecd49ea7c44d11b1
    md5: 1e2db3daaebbef636d5ff1e3a9e63316
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart410/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2a6080705fc6779ea9407d7843e09968
    md5: 27ea5547dd4e02aa74a2bf1149b6309a
