format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/atmosphere/restart_dump.astart
  hashes:
    binhash: 95d6069e6eae2279a91550fe2c2150bd
    md5: 8f93b1664977b6788c54f7e05b847ab3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/atmosphere/um.res.yaml
  hashes:
    binhash: cbd66a7de8e5d6c8d5aa81ce5420c2bc
    md5: f808ec6ccf404ddbc51c5859387ef40c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/coupler/a2i.nc
  hashes:
    binhash: 9609f4a20edb760dbb6ed3d1e34019e4
    md5: 2e8743d7df6ae6c27d7b16e6946b0cdd
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/coupler/i2a.nc
  hashes:
    binhash: 0a3a1787e2223e7924e301793f3a0d5c
    md5: 7e93d03832aa72d9c604c0d2a1ef7f67
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/coupler/o2i.nc
  hashes:
    binhash: 6460e969556396bbe4e21c08c6d77696
    md5: ee6aad94422f4fc1d7570531a511dde6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ice/cice_in.nml
  hashes:
    binhash: 0ef33615a94f88fca897b751015177b9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ice/ice.restart_file
  hashes:
    binhash: 824f1466b2201fcad8b7bd8978f8170c
    md5: 2a9d9876f858ea17725a827912ed0a9d
work/ice/RESTART/iced.1704-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ice/iced.1704-01-01-00000.nc
  hashes:
    binhash: 22b5e25b4c7e36ea54c814f200614363
    md5: eb598347af2102f91a78e028f521c6e0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ice/mice.nc
  hashes:
    binhash: 898d7ce61d2dce4f66cc0bb0205edf2e
    md5: 8c2ee2f55ebfda183483cb0879ecbf95
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_age.res.nc
  hashes:
    binhash: 13da5cfd79a6977ecc072bde7f92a7dc
    md5: d7c2f20bc1f09b26b20074a152f08973
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 001e943f63c02fa7a3e853e73972fb09
    md5: 903dcb3941053bbdf0f71b9f4c278e16
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b40cbe9d9e26b4c247378a3879042a97
    md5: c67ac171fd43c2c1189e460ccded5c82
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_density.res.nc
  hashes:
    binhash: 6854dd2381b38c6c3fa79b32561eb1e3
    md5: f95e1f33707e8db881f0118647f6f30a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b2455d2e138b1da7425c77ab57e8846b
    md5: c49002febecfd5ddd4b73bd0bbf80ac0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ba93ed6c0687b4fb396e9562c3f58c02
    md5: d460ffabc90f57d1210691a3a705b16c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57b684d47c588e56f3b5207eeac98555
    md5: a28630e25f1e9383d28733ced290053a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d7c4959dd8e068cd33d7df47e07cd179
    md5: 6de38e9cac84483bb19cad4773ab8ad5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_sbc.res.nc
  hashes:
    binhash: f4533f3eb600e3db2c315472d051f29a
    md5: ab1e68ca8eb0f019479204ad3f5716bc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b5252b6a6c78dcc6142c3b395ef1e6f3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_solo.res
  hashes:
    binhash: dee663e153e67d1e673631f1dd86bd1a
    md5: 1c636cf31b44563e4b10ab69cdff1215
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a61bb6c6c5bfb8bc88ef2ef94966fb4d
    md5: 57a112653bdb06d84813764a5f297f51
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d88d269b6ad1ec7057205573e535db27
    md5: e0a1ee1ce86462eb1a11ad94677e0898
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_tracer.res
  hashes:
    binhash: 06d4a28571a5cafe9570393cb9e5e0b5
    md5: bf99ff291c28707a07f358b64b596dff
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 29db41f01ac2e302f5f6f536baed311b
    md5: 6b7db8b5c0cbcc3b5fecab7301375abe
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 6e80d674795ccc7027bd6b9313287316
    md5: 7e45a1b33920de4817dce9d2357541c6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2999650d12696ace59dab6c3c76d5bb8
    md5: 33729f3eac063358e6a924dbaeaee89a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart259/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a4af596d98c8ce09976a1d7440f4df06
    md5: cd7caff843b5acedc5715c0e7fc6c68a
