format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/atmosphere/restart_dump.astart
  hashes:
    binhash: bbf0c570478543f6ed3f764a81f36323
    md5: 05e100266a6fcd5837672adab787faca
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/atmosphere/um.res.yaml
  hashes:
    binhash: ebf38ae3cee3dbdc8ee40150a14a309c
    md5: b45c828cb2add9c1066c4531e8ae7c8a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/coupler/a2i.nc
  hashes:
    binhash: 746f121b94169692b75cc28b8bcc9ae3
    md5: 85887c9057d29d9211b1afcc231100f0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/coupler/i2a.nc
  hashes:
    binhash: d934d0fa991f939d225109fb7af2ba43
    md5: 698d3d29b8e75a28726dcd5f68db43a8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/coupler/o2i.nc
  hashes:
    binhash: e75056c51b39bd724311cf365e04fb2f
    md5: e522bfb5a8fd7392c0ada3183f09cde9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ice/cice_in.nml
  hashes:
    binhash: d2c6bb70c6c9b47e805ed5bf4c55b252
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ice/ice.restart_file
  hashes:
    binhash: 6e4311c8a879ac247b577eb508c7c90b
    md5: 53441d3414d3d708341e62a83304de5f
work/ice/RESTART/iced.1227-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ice/iced.1227-01-01-00000.nc
  hashes:
    binhash: 5ee2cbf083bd364f4440308b3aba78cd
    md5: 3beceb8d21a91cf3fccb4796f89141d5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ice/mice.nc
  hashes:
    binhash: ac875649beae854a6b782d0d7c4a5ce6
    md5: 69e85c4ae304776aaf8897387034b0fd
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_age.res.nc
  hashes:
    binhash: cbc4e7739b5ca4d7da804a420fe2b482
    md5: 5431059e50f11c783caf153907a31fae
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4e4c466fc69563387d8bde7c18aa482b
    md5: 433bfc5b0290042a53886038d6c81b9f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b590dd6a91c158ef00a2f93d190d9a4c
    md5: df31b1ac24954c2091752ae0a7af3d72
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_density.res.nc
  hashes:
    binhash: e76bf74fc3d51efb59b9b7de2cdff4ad
    md5: 3db35243e7a91be380af88879532329c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_frazil.res.nc
  hashes:
    binhash: caddc60306b0da4b8af9fe1ac11ce84f
    md5: f6d4f266e7b906ab732d9e97c862fb3d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f1cc341cf791d4417341dbeee1f13441
    md5: 4de7240e4e25110de3d8d6912231032b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a29cb2a15c6e35f5689b1a971619df17
    md5: 0748967782caa14a8826c85892b93d7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 793f22abd4681a9b675ce840bbedec55
    md5: 5f38ee9498faaf433bd3ee34168e8587
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b09dcaf4d11f9f26010cc1124aca014d
    md5: 3b4ca98bb273065b0bd3bb394442926c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2c688599105edbb1486d9397eb4757ab
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_solo.res
  hashes:
    binhash: 227350bfee836a4ec52d579b641bd522
    md5: c442281de53cfe13d0cacd40813da987
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bc9b368c43c3ed09baeec848fad1bfea
    md5: ff12c69dc88529429540c71c20858215
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 39035c43d45b5ab7205835abaf42ff06
    md5: 46b5b90e4acd3b705c66346b954271a9
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_tracer.res
  hashes:
    binhash: 6df98ed6774029350f6f1a57984e46fe
    md5: 0bc92bf813a8e27d9579a8ed6a341512
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_velocity.res.nc
  hashes:
    binhash: de5beba32cb5380feee841f677d8dd77
    md5: 9c2e044ddb75bcac0b9348b6f47394d6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 3b31b33fd40dbd182b1af5c24acb811b
    md5: 2970dd24413862417c564d8bbb7ea0d8
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 02671a6ddaa0c9029698dfe0961e7680
    md5: b637ecc092cbe2ac1f499bbc0578eef4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart343/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4dd6e6a6ac72ee64c3eabab8733cc486
    md5: c93176241549ad0f9b92f7720b729a77
