format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/atmosphere/restart_dump.astart
  hashes:
    binhash: 723c252047c53896935c6d008e1fce89
    md5: 3ebf00096e3f40b416c74f3380ce5f6c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/atmosphere/um.res.yaml
  hashes:
    binhash: 6aa7d9d69c839c95b3ffa66722b860d3
    md5: e78f5c13c88fc650093f518beed04e39
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/coupler/a2i.nc
  hashes:
    binhash: c27fbadcd892f2c688e4678d35b99aae
    md5: 24c1442e2a4614c0a5355e6c11d3d262
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/coupler/i2a.nc
  hashes:
    binhash: fb3cf9d46b93584a3deb3c6ca5d0fe33
    md5: 4d44f0f726dff1ce15c300fb51dfeb09
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/coupler/o2i.nc
  hashes:
    binhash: 24d5813bb4ba5bd0b7e9e108aba89c2a
    md5: 2815463620b3a3a050f9e1fea065aae0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ice/cice_in.nml
  hashes:
    binhash: 66454a5f3f980a456fc19c81cf5b87ce
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ice/ice.restart_file
  hashes:
    binhash: 1d56812248c4e5f0ca6c0b60139290f8
    md5: 46bca32f6f278f3b35b8749f7eb15111
work/ice/RESTART/iced.1832-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ice/iced.1832-01-01-00000.nc
  hashes:
    binhash: cf57324dba88305e2c8f4025e181c7cd
    md5: 1cff8cd78a99270255f9ad46ee50cf7b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ice/mice.nc
  hashes:
    binhash: afe77f21a28efab4daa3960646415af1
    md5: 28eba986f19904665277d27756bd2a4d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_age.res.nc
  hashes:
    binhash: f7848c94daf84bb4e07214e6b543ce9a
    md5: 899eead8c6787b7931bdc3c23609cd98
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 66660ca6fc2e6972d670be8a8f02ea27
    md5: 110b235bf6259af5f44a095b385fdc35
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fe54c16b9484646e2b516902f8432d56
    md5: 0b18a364780e3c5db235af2469d7e897
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_density.res.nc
  hashes:
    binhash: 36f521c0f4e54204587aed79c3176cee
    md5: 1f5cfa6908c40187c4fb653e881a5b69
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 00ad59c9403a134c6ddf7f97764fc9b0
    md5: 0881fe96d5ee6e7b508fb739dded85e7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 18ac8abb964d2b7794fa2bd1c0513228
    md5: 1ad94e7430a18f07a1c9e5252392ccd6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 80f2d54da14e5fcb070a020298a0acb4
    md5: eb3f81445c77ee8276eb40fc199cd44b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a9116e04a7d9bb47ff6392266afd8f25
    md5: f05933bebacd42967224523e0ad72d21
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 043905f69087f53166d36c4e18e1cc7e
    md5: 37de323bebfb245b5e9b83a70ac69cc1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 994c86ed7b890fe8d3393e150f911123
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_solo.res
  hashes:
    binhash: 241e6288b364292496ba90b86531b509
    md5: 56d6108cd4e28d4f443593687277b34e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6ccbbe4e5943809000e808e02992e4c0
    md5: 2d1972c0f2576af3b37902fafa930c41
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2da82bdcf1b5c2e8c083fc04966e72d9
    md5: 4289a4481205fa279f0a634c0583d4e1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_tracer.res
  hashes:
    binhash: 4b7c7c7536a2b9cc5a8115eeccf46459
    md5: 5fe9dee1699364b3233edeaa36a4144f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8f0960e2de5cc53676124ea0ebdef24d
    md5: 2c0067f4b14a19ed0f2c5a2b8777ff1d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f88c16aa6606362e7ae14e1a418ef0dd
    md5: 5dbcc7b73df13df426b13e8fbe676799
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 64e59b576092a056e718f44937c6eed2
    md5: 09f5eae81b48f755912a762776ae30ef
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart387/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b9b96442e745660a95b60f14c2b65429
    md5: 5262837d96d83e5ea7f62529bc5bc5a8
