format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/atmosphere/restart_dump.astart
  hashes:
    binhash: aabfbad7b74c5d96ea23748bed51c792
    md5: 50a321c017426ff97a7b99859da5169d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/atmosphere/um.res.yaml
  hashes:
    binhash: 4a5f28fc718984659b0eefaecdd440ac
    md5: 4d8c56dca6b8ce48c4208a4a22ef43bb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/coupler/a2i.nc
  hashes:
    binhash: caf2eaac843206fc00f564a8b11a1101
    md5: 26981f3142a75e4c1c01332ed966d294
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/coupler/i2a.nc
  hashes:
    binhash: d36b4515fd7402dfaa022473d05c97b7
    md5: 0cfd8c24c3ef45601a16acc6580b3622
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/coupler/o2i.nc
  hashes:
    binhash: 620ebfbf4c011cb78dba3e6d94cde46e
    md5: 14e26b8c2f0d58bd7efb7d9a4deceb12
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ice/cice_in.nml
  hashes:
    binhash: 2929f4e4713be219d427c539de3411d2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ice/ice.restart_file
  hashes:
    binhash: 93be5561d495a09904459aadd6863d33
    md5: 36faa8a47006c42a19ee31423ab49ce2
work/ice/RESTART/iced.1728-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ice/iced.1728-01-01-00000.nc
  hashes:
    binhash: 6262f3d602c412d779b1a34e4f9da0b1
    md5: 1b9381aaeedf7a2e99c81cbf7513ceeb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ice/mice.nc
  hashes:
    binhash: 060ef677720be417576da5b44381fe48
    md5: e80a7655e4ffe33150bb790885dba6f7
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_age.res.nc
  hashes:
    binhash: 3a369cbf0188cae144c8841bef2b92c4
    md5: b8b6a7ec59942879680ace09960e5fa7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e3a1bd9016a0da97bad4c12f8c57845f
    md5: b51ef58f8a9675880031145f843c62ea
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5573282ee5b252ed81f4db5f9a83e156
    md5: 92d82f9a11acafd781096f57a040757c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_density.res.nc
  hashes:
    binhash: 0fc87c78b9acf09dac698ee19ef2f054
    md5: acc279a9dabb8c66a535c66c98034f62
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1f6a63313809eefe86dbff856996ad11
    md5: 2d50ea39f2f926bec981cea33c6b8807
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d9cb55cae9482424e0cedc375f200eec
    md5: 2c1b76a0f9aab26ce3ba8c56eccd4140
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 527b9cdf2f8763af12365215f69f406f
    md5: d8188aff9b813bbfd4af109aaf83789d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 833d8f7a88d531e78dd9c1cfa8508a04
    md5: a5ee262031b396043c01afcb5035bafa
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b17f1f26e7457682534dd01e3de049f2
    md5: b6b82cb86974ca58667fad811eee224f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4eab0619b0cdf6a2281c6beebdbc1e84
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_solo.res
  hashes:
    binhash: 0c141eef7b6371b85d0924eabe114079
    md5: d2e154c1a32e94a3a235ed3c4015e8e4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2e8216726b89ddcbb34462a6350ef467
    md5: e337d3d3e2f3aeecb51254436b9c71d4
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1c6bba2a72a4cbe29cd0db0ee9956894
    md5: 8d38d0b06180fe253df35190a1936084
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_tracer.res
  hashes:
    binhash: 2a5103c2d3ccee311d875f84a80223fa
    md5: 45240ba613fe6c5bb3dd3263e831885a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fd03fce564e68f31aa090ad85daf0998
    md5: 2337398d7e4c1eb779b192811315cacd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 90fad02e853986f30ecd73a1c1f204f4
    md5: c6cec6315ba7407afad085f1c984c8ee
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 507da39950da606b15bf05d5c973e7fb
    md5: 02751b028ad594a92154f8d9fe07ab80
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart283/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3da63a1b32620d907137b4aada45d311
    md5: 2a768c87363eaba2b9c5a28afb02d34d
