format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/atmosphere/restart_dump.astart
  hashes:
    binhash: 959c26b3056d0500e3edb92656059921
    md5: de5aa0f754e8dff82ccd2c5b88cd226b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/atmosphere/um.res.yaml
  hashes:
    binhash: ebc479c92fab7b0bfe5fb6c79ab2323a
    md5: c44478569247bb26fc309dafbca6e474
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/coupler/a2i.nc
  hashes:
    binhash: b327953c3752153df5786c913b16f97c
    md5: 9cf61800fa4164c56e9e324a9c562dc0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/coupler/i2a.nc
  hashes:
    binhash: 75ab1c703656049482eb7940a3a4e5cc
    md5: 89c365dffe30f3fffe04c4deb2bb78f8
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/coupler/o2i.nc
  hashes:
    binhash: d2a64a9ac69b0f659493b603138bd8c8
    md5: ea2c63d2e9d0cffa9f9256bbfd1b0f0d
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ice/cice_in.nml
  hashes:
    binhash: a4ea6cda39f56dd264496936467820e8
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ice/ice.restart_file
  hashes:
    binhash: 946d1ff757fa15df936aebcc37e40eef
    md5: 442d24d2557734883e156f69ace30e1b
work/ice/RESTART/iced.0961-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ice/iced.0961-01-01-00000.nc
  hashes:
    binhash: 023d59731da744ab627329633d8e7868
    md5: abc5472208f810d4841b8babccd294e4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ice/mice.nc
  hashes:
    binhash: 2af3a4655b59fbe32eb72895c87839a3
    md5: 7a8e655ec6c0974cc0947676754116dc
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_age.res.nc
  hashes:
    binhash: 642fcc480890be3e0390201b238eef0c
    md5: 4daeefa432dbafae63e6fe2968d97b4b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 11eed0e1f47e62003f1bfce4a5aa99f5
    md5: a02401e075d9ac1b9c191b75e7783f57
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 36b249310c1d25acfaf2fc3d3cb252d1
    md5: 922d61c80574d71ba41ddca7cf004407
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_density.res.nc
  hashes:
    binhash: 03a69f9bad4e60831a5b87c2ab79460e
    md5: 9c618bc015befcfbf1a2f30bdc648994
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6b104cd3b01eb5631df0bb38e23ac441
    md5: 02ca73a0a56b5883ced2ad9c8f03320f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3bb8d192f38e5b8f36b97e801ce3617a
    md5: aec987e50d41c797072bce517baaaa53
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 0f55be7af7ee9d2715979a4f54a0df6c
    md5: b442474269703cf14138d4a64aa7606f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6a2f1df4a503cc7235f7cb349695fd5b
    md5: e1ea74c3a9e0acbc1fd7d25d6ded57f0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 27e10a8d4ef26efa6684d0bd3c57c697
    md5: 539f45d6b7828453ebeefde9cd7dae7b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 47d0e7f9cdc79faa15867cb48c05664f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_solo.res
  hashes:
    binhash: 30a2ec89c56fa8eb14cf5077a048e81f
    md5: 766d8f05b125747612b946a6210b68f4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c0994607b48bb3068c86d6f00d606a1b
    md5: e090d756ab59df8d8e9b4052b57bc6f1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_thickness.res.nc
  hashes:
    binhash: feb71ff2dcbca49b9016c8333dc1267a
    md5: e32ca0f300cbd0c10af0ddde603375e8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_tracer.res
  hashes:
    binhash: 064e1e935627fcaf28a54857bcec966a
    md5: 5d9fe983a7d9d5f3ddb5c4ddf0abbe70
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b56ba5e499c1be0652989ac74e522c97
    md5: f2b5520a774fe3f74d24681685c35110
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0122b46f4c37084dc57b42705fa98676
    md5: 542cc32855845f653c35d4d2141a6980
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ad245e8bde7d7b9d27bd65f8e2bdb512
    md5: 1d4568988274910407fcc4719d5ed282
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart407/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4ae2fc7d0b9a5e498e34cded61e0e0a6
    md5: ec71aeb1e8f3131f7c38b0d3892cd6b9
