format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/atmosphere/restart_dump.astart
  hashes:
    binhash: 4b63bb7dae9e531a4bc9953e2ce0b3f5
    md5: 1577d25f9064a46f8583192b7b965f2b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/atmosphere/um.res.yaml
  hashes:
    binhash: 71bc90161eb860ae457b5e1c949bac67
    md5: 34bf67fd31fee8693720d67dbeb513b8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/coupler/a2i.nc
  hashes:
    binhash: a7120621736e9640a41cba806921a467
    md5: 07a3ee8057611bf65987c656fa52aeed
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/coupler/i2a.nc
  hashes:
    binhash: e0de3fce6d9610bb3e52a07698feb89d
    md5: 4fae2bad5465a3c18e830296c762ea74
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/coupler/o2i.nc
  hashes:
    binhash: 97adc125802740635035d162d0913da7
    md5: 9fe79a13c49cd4f7004e0c7b5ef0ebdd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ice/cice_in.nml
  hashes:
    binhash: fdd210cf6d2509af8358cba572e39965
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ice/ice.restart_file
  hashes:
    binhash: 591bf98051a86395cf9102b466642fb8
    md5: 16ab12ea583dc64cd05e4cfb171322a0
work/ice/RESTART/iced.1748-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ice/iced.1748-01-01-00000.nc
  hashes:
    binhash: 8d49cbceff7a78b0cafd3b9924e00f63
    md5: adcdcc8b4d60758cf59dfc264b30cb2b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ice/mice.nc
  hashes:
    binhash: edf4b06ef3f746905a3d496e6214bc8a
    md5: 55ddaf8d9ccf24002767a8dd779cc57a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_age.res.nc
  hashes:
    binhash: 2d3fb36164a5013a1f28cef733712f81
    md5: 6685419864127fb9c47ef0aabc687779
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2169134776826d5f2c554099d637ce2b
    md5: eaed05d6b80fd2d751bb7c92ea406210
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 314a74a83d1b3129fcbe7201491b5873
    md5: 07c9f18aa1d16368e43ea8ff5dcade04
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_density.res.nc
  hashes:
    binhash: 216956b6dc55dae7b5c1d0949a84b337
    md5: e621f82c93ebdd3ca84df331b8e81b60
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_frazil.res.nc
  hashes:
    binhash: aa9516bb0a5fcbee28e4f4dcaa544620
    md5: aa5bbb8d1bf437b44cd7400771f7e792
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6101dd9d17650fbcc163bf0f51f930ec
    md5: 29212ee5155d19e39746ea9b3d3b38a3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4b66fbbe201bbd2f68fd2321865d7f1a
    md5: c4e3b8ff9a5c14550933d8013f82692c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1d187fcfd13fb97d92bf7e3a391c6e05
    md5: 5468581fa42c8f596df9439e611b2c82
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d107d9f4e1a1811d172b54b1c81e5885
    md5: c0ba9ae97bbfe88e1da667687919e77a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a32978b9f2bdac2ed95db45ea629a9b7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_solo.res
  hashes:
    binhash: 523ddbfcf45d1f0bda8f949c815c4441
    md5: d555cb1afb339ad3f9f6b67948b68e9d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 538097383ab79b21b9e65baffdab5c7d
    md5: 47c3dce96ed3a51956311b94648663b2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6bcd7190e0766a5b2010ccd18ab169c7
    md5: 1be01267829022da4c323f2b61a86c06
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_tracer.res
  hashes:
    binhash: 12c3da7ac2b9b36676861ac2018737c1
    md5: c8b7613bdec6d1f4fc2028e5a40e703a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c2a577625efe3d8d2654b2873c7c544c
    md5: 94d3a0a1cd8a9e6de08ed1e765de0f99
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: eeda28b7eed9ec67f2a49dacd906de00
    md5: dd003199fb87e4fb5bf9ba64dbe5e5eb
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 60f8151532b71893190d2d21a420d9cf
    md5: 694389c043fb251a45c822a7c23ea5b4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart303/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4c0b2d4bd1f71c4dcd927a67317536b2
    md5: 2a66e37fd9db0f17f4b2b3e4d659124d
