format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/atmosphere/restart_dump.astart
  hashes:
    binhash: 2687df91bef18ddced685416c8fc37fc
    md5: e2d31ba473c6e657489344a6fd3b5b1b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/atmosphere/um.res.yaml
  hashes:
    binhash: 5762b3a7361818c4ff7f581f9183a0f5
    md5: 01d7e2394142f830ae53363dbb61dee6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/coupler/a2i.nc
  hashes:
    binhash: 8ca16df6457107caa5c3096c9124e67c
    md5: 198267887a35d1adb2bdf1d81f1b00df
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/coupler/i2a.nc
  hashes:
    binhash: dda5be0d89420f6c8327974801eacda8
    md5: 61e0eb0dc39e062444f738166f5ab355
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/coupler/o2i.nc
  hashes:
    binhash: 8820b975702d4fef5695ecb30be5b9e9
    md5: a8b4c7d8c48dec12926af783126795f2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ice/cice_in.nml
  hashes:
    binhash: 57533bac1fbfa35622c1d9d0236e8ee2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ice/ice.restart_file
  hashes:
    binhash: e13377eec1f7807703de71ef696ff7bd
    md5: 81df48aba4c68cbe966c0e4583185a3c
work/ice/RESTART/iced.1288-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ice/iced.1288-01-01-00000.nc
  hashes:
    binhash: d7b3ace3938638b832a23f1833a01475
    md5: 8f5b5c05dc53b986c2853793e29654e4
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ice/mice.nc
  hashes:
    binhash: 85fe257986aca5159cc847fa8efd27ed
    md5: 3b4c846578940cc53f29a818d7f9d243
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_age.res.nc
  hashes:
    binhash: 15b3ceea13572d7c419987f9091dad6a
    md5: 92d7e0ad29474bf1f521376ad66ef776
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9629ca13b8a20f908749177a4a54a0cd
    md5: b9c740a091f48f6662109f989a7a483b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: da362e696e082a549294747dcda1e5c7
    md5: a12174b2d6b06b856969ea01cab57f81
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_density.res.nc
  hashes:
    binhash: 126c00bfc3b1cfa2c1da16525c5e221a
    md5: f720a1ed74baea62ab09c6d14a691de5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 51c3ee7806b8f6537b10eb8a0d3d993b
    md5: 015bb82c7cb852078ab11a68b5791030
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 66c9e3c3816057f3029ca52d74a26042
    md5: 78157fbc959a4791aeacd108538eb4ac
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5f5849e7cd88a968e9299251abb9bb46
    md5: c74ef52830947ff09d38536b9b1ea9bd
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ffb176a44007395ef4e3156f3c3eb231
    md5: ea73932c58c0915bc6e8ac7cb7c4a0b8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0011ab936597614f29ef0f7466be607d
    md5: 3e47af1f8f62f27e7df31482e4eb5493
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 725c2cba4294b35ba9b8486d7477f0c7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_solo.res
  hashes:
    binhash: af17490b9afc25b07bc00e781fffda2e
    md5: 0003b6487bb0e0aebc2b1c7aa7c2d162
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c3279456ea11bbef493e158baa69179b
    md5: f9758fe3330bbbf4b19b60bc28751f80
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9d822dfc6280b0868a6fc0538245c63a
    md5: b4cf3dc42c3cef8781f8846800484e99
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_tracer.res
  hashes:
    binhash: bf02f1226f07182a0d8bf3df78b23e0a
    md5: 11cc40e018557ba46b98ca41def526b5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b047e3432b1207eb42fd9785aba3ea08
    md5: aa735811eb8219a611709d43341e052a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cadf28bf14b13dc0a92956a8b9b7824f
    md5: e39b591f87c27229b6f282dc00c71d31
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: ff712db9d9772fa460e874502c140085
    md5: 4c4b987befd764ce1162b6246a827f3b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart404/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 86be02435eb08d3be3566e3667a299d9
    md5: fe533ac8ea95377cfc8acd4a8bb3bd8f
