format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/atmosphere/restart_dump.astart
  hashes:
    binhash: 75d2dc96d78ef682b5dc4446e6da2d09
    md5: 27e3179c1ffc0e9d670bfd5b57e9ab0b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/atmosphere/um.res.yaml
  hashes:
    binhash: a11935ff142c6c67689e45195f535c3a
    md5: bbcf411b63cbcd386a6e9b6a55c19cbe
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/coupler/a2i.nc
  hashes:
    binhash: 3b17d39abc73c353aefbc37d344b1335
    md5: fd9d17878e3952400cbf6036b267faa6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/coupler/i2a.nc
  hashes:
    binhash: 1313396f0176da9aec939ce6ab01ee90
    md5: 87c56844558ef90762da593116cc9e51
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/coupler/o2i.nc
  hashes:
    binhash: e58f73dfeb839a0c6e687b5dc94e250e
    md5: 543f7f4e61633a852089df862cb96ced
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ice/cice_in.nml
  hashes:
    binhash: 53463a961763aa6d4c60db6706b7d5d9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ice/ice.restart_file
  hashes:
    binhash: 8811f6d7a1d98f8b3a4ed45bed9c6dab
    md5: 6564d45bb8b6a9cdfb356f48d4960abe
work/ice/RESTART/iced.1282-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ice/iced.1282-01-01-00000.nc
  hashes:
    binhash: b9c18cedd36db4319ffaf1986889c249
    md5: 643baacd9453dd259bd8ebf6fc5ef44d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ice/mice.nc
  hashes:
    binhash: 965e8b89a00ba1cb1062649022d56967
    md5: ce29813b69b100b8c31087bb5c38071e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_age.res.nc
  hashes:
    binhash: 48faf2e35ebb54352c3c37181a203cc8
    md5: 1de81f5be27537e581640129f0a3edfb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1b2e9f452d35cd8be438512990348c9d
    md5: ea27f2035e00ca078159283ec974ffb0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 457ffb1f7f9c948c5b0d973fe4649360
    md5: 3aec7c93f66d118bf8430ba7ba98daf0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_density.res.nc
  hashes:
    binhash: 3401d7e07be1cc51a562db0c55fe1640
    md5: b48f9d3aa2e7f6d31b5f0f037491d895
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8eb5f1ee3f5e1df3cab42fa97f58ec7b
    md5: fa03d701e6c160836de7ea5a64e68e13
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 24d1958d318ffb4d3623073ec1837ae3
    md5: 7feefae5348d5790bf896a9e61dbfaf2
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 20c5a2c839f6dfd6dd95108726c686de
    md5: d8de574577661a504a8f1d211df866d2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f0f33bbe45cb89c7424f88a9e2c584aa
    md5: 2161b0e55d7dc73ba059678762c3d9c1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b1c9da078032d32370bc7960fdca07c5
    md5: 33a59f08b7230b1d9307c93fdcadfaf1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c0b4317d27477a6d4ff24000693de0c6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_solo.res
  hashes:
    binhash: 51ad37cd10a9c28773c3006b9742d72a
    md5: 0314f07036c9309b27029725b8672dd6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 51f042e7a416dd1d18a484f35fe27ddc
    md5: 979d40a6c09e3c37fcdc38b95a084313
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d272a4ad5fa8b9f187f9dd7f5bcc9724
    md5: 66d77d55f6c6dbe677e4c9a65078eaad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_tracer.res
  hashes:
    binhash: a6f8acf7b29681e5ec1ac86dda27c203
    md5: 09010ad429dd6985440ec19a49499454
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 52ca41a0b7b00d2c84b53b00c6126244
    md5: 995fc03fff2ea0198c5a6b6d5a122190
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c79fc44df755d06fd7d62be0a0c60592
    md5: f9e320da1e26a2c9b9082bd362209f0d
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2b597bd1af4b6b7161c22fe215ef191f
    md5: 22dab65e7866f0a9f1965c045d6d591e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart398/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0e58a70e77d42087cf3a1f0b5d5cc48e
    md5: b6b251b8802075128b324952eb8aa6bc
