format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/atmosphere/restart_dump.astart
  hashes:
    binhash: d63eaf2329f847d3f08d50531600fff1
    md5: 10fad92066763a20a2646f76cdf01027
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/atmosphere/um.res.yaml
  hashes:
    binhash: c54d3ac2b8fff1de59a710534f369da7
    md5: 6d878a853a162a7421fc55abd593b8cd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/coupler/a2i.nc
  hashes:
    binhash: 029e363f7388ca9ddb8269b3d9a70e94
    md5: 436f1899a4433ccdafff3d83b3de784e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/coupler/i2a.nc
  hashes:
    binhash: 9733a59f3a2df1f855db81f9eb8772e4
    md5: 9d66a32996bea036de7483c40f30c930
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/coupler/o2i.nc
  hashes:
    binhash: fdfdc42a443078f0e3fc4b660f34404d
    md5: 9b080326012f4968a70c91d488f88347
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ice/cice_in.nml
  hashes:
    binhash: e2e6394bed4758517beb86db4c72113b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ice/ice.restart_file
  hashes:
    binhash: aca00be6fb6d174a2b12e8a7d46423d8
    md5: 9a96bd0052077d1567d1aeb8cb393748
work/ice/RESTART/iced.1206-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ice/iced.1206-01-01-00000.nc
  hashes:
    binhash: 3a180dc09d350e75f57e303bce68f818
    md5: ee1b7748198bfcbd66ea23f02c772f37
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ice/mice.nc
  hashes:
    binhash: 1138207da0937d9da8ce8b9840aee6ee
    md5: df0ea3d91c0348732f6dcfc03ad940b5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_age.res.nc
  hashes:
    binhash: e93bf77f987b09bc466f3691ddff25c0
    md5: f8991fc5675eb2be0ef378f5286c24ad
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 48001ee6544fd838ed60c0d7c2401814
    md5: 246021d8d7217a918e668deafc7bcf53
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 35e82c7679c21051e02820f186a0c604
    md5: 12bacac13357ae15ae33d1db6af20465
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_density.res.nc
  hashes:
    binhash: 81f9ca4e24d953a7a14a739585a64b33
    md5: 61703cbcc7507e8e811d67b08f71718c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 8739b79a81586b1d09a0c2d496a0fd5d
    md5: f09fb30d8db1af2c4fa99955a7bf4874
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 80a6463112f98f3c0f69d54484d379ed
    md5: 6f4aeb766121c14fb3ef4ba87d0a9312
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 13c4e95c7f7abd5405bb96f4e3a01624
    md5: 0f689544722704a26c4cd5ca2e44fbce
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a1430fafda41662b26237790f6513209
    md5: 60610485dfa2988f3ca6fffe38c75de3
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4d2ca4d92f74b00cce180349ba1e5561
    md5: d91212795a9e79e9c153211b2b039949
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2c4e41b212883aaae9c886d2d5613f39
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_solo.res
  hashes:
    binhash: c5b55634ee555d5c929f47ac99603756
    md5: 7d04e99756bb8aa44e4b28e374e573b8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 1d2bfc114c59761c61ed3d022fa20331
    md5: e9962e3014d53abe3d626ff6a2844baf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7601999de10a62a28614603bd3f14178
    md5: 9e0e168882ceb0b73e04e6374bd66894
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_tracer.res
  hashes:
    binhash: c3ca05b37b80d82720a509cdccce3c90
    md5: 79d52636335e92f3d7c9c26ba65dd95e
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5c7e484fdf9112e7ca26eaea0ec1c058
    md5: f3aa1381b6d93f02f828e533f35a8004
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 936ab4a93a5b9f0520128cabd8eaef8b
    md5: f5adc4582e2b85946471e9b1f9ffbce6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4635b98ba895d65c13c7dd8da4a1affe
    md5: 1e7eaa1a9f22dd39d58fc2bb23172b98
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart322/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: eda1c44a0c670a3729d263eeb40b7f19
    md5: e55c30cdba91e9e08ce2c7835d7951e8
