format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/atmosphere/restart_dump.astart
  hashes:
    binhash: c379919942d53a5e03ccc424d07af8f3
    md5: ba3b2a1a8f80e03deff4225d916e8f6e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/atmosphere/um.res.yaml
  hashes:
    binhash: bb54d273a177ec4b6d0fc353f4868726
    md5: c76767b2b2d45a947cfb8c7954e63989
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/coupler/a2i.nc
  hashes:
    binhash: 8234347479b6f125ca5dda9dfbf79dac
    md5: 7bcf773e569c4c75d15bd67e62b90e48
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/coupler/i2a.nc
  hashes:
    binhash: d6332864cf92346caa2107a625f51b45
    md5: 8afad5d04fba14875e985bc39af19a20
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/coupler/o2i.nc
  hashes:
    binhash: e345ca5aad9bc9c47a71bd41e4061916
    md5: 4379652f136cad5b9b4928cb4e77a1bf
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ice/cice_in.nml
  hashes:
    binhash: 0af1c8a8f7e55b7d2846ca8838950f5b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ice/ice.restart_file
  hashes:
    binhash: b24625bbf8e1e1748eff9fa52f4a0471
    md5: 5052de3c7868cfb8939eea6e819e78ed
work/ice/RESTART/iced.0987-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ice/iced.0987-01-01-00000.nc
  hashes:
    binhash: b9413740c7bb019fd47e2fe76d80ab1b
    md5: f72f9bb2e2f311820fa7f41ae2715b9e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ice/mice.nc
  hashes:
    binhash: 83d3ecf656b5e750f388c149cf8f44b2
    md5: 00ff01607e4a55d8d261c5c0788dca9a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_age.res.nc
  hashes:
    binhash: f47a99f4d82abe4204982253ee74e5ef
    md5: 9c5959a4f8bb728a9a591bc32c13850c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 68f3de8a01610adcd2bd076aa3898ba0
    md5: d14523d44dca95052401c068b6f6e398
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6840b936da2c855be118ada4dc8c095f
    md5: efa941e649b7f5021e3eb03ee8f23705
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_density.res.nc
  hashes:
    binhash: d6d1ef237c871d22319c3b78f4154e41
    md5: cc10604c65ec83d77b5fa6512d9eaf58
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5e4dfbc34943c50f42fab8c63c064a05
    md5: 689b9d9ede486afd9c1563f49c179b81
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ebce8929b6f7670a541773f1dfe510ac
    md5: 0153ccb96bf20c6a44d5df4074441c5b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 51e38d26d78a1095d6c584eed8c40da1
    md5: 3b655acc481b7726fb8787e863488a75
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5f0fc4ea6e2dbad04810fecebe1ead5c
    md5: 251046b31a1e6abf922de86dab33cf50
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6e731c20e62199583afd0ab0b2b5f113
    md5: 68f458f38409666240d03857023777c6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ddee50ba85728c4f46ea789b5944e838
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_solo.res
  hashes:
    binhash: 8045bd46cd56d5c6496f141caf2b12f2
    md5: 66e2c35f74635842232880d784f1f6bb
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 87f05af3fcd3c293d20d0737d8fbaee0
    md5: fa1a5234fdd240d75b0a4ec128b752bf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3aad616559376989ba03027c9e64245f
    md5: c57497af3c9323495b8cffa52f1df018
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_tracer.res
  hashes:
    binhash: fb74680002a9b90643f493ec2192f30e
    md5: 4d0f783d3c83bd2bc2a93cb976d9f946
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 456a872cae21a4abd5251e566a17f9df
    md5: 9db43fb98620f484a1143c25a3392a1a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 23bcede1c4de14ae8f1dd3e26b6f3b53
    md5: 55e0fe89aa61517d023d2e34455776f5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: de88feec8a2c4c08c628175dbafab459
    md5: 0d2af0ef9ecb265a2d61043453f07e52
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart433/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 03f3af47b813ccef6abf6e2f5ba6a5f5
    md5: b6eb1b9f6038b020bd483ce60aab071f
