format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/atmosphere/restart_dump.astart
  hashes:
    binhash: ab39dadb65fa0d4a357dfaac98e16f67
    md5: 963e724be8c4a109668577c131928ad0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/atmosphere/um.res.yaml
  hashes:
    binhash: f06351e85779a598e544a4323accff10
    md5: f52c4ae9b243d1a711e2dc949f078115
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/coupler/a2i.nc
  hashes:
    binhash: 8a135dc903d19f0510cf5f86b06eb821
    md5: 6d20862b672b2067c7cec5e9a4890198
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/coupler/i2a.nc
  hashes:
    binhash: 3aa5c93e93c10d24f66e48c3f7a79c66
    md5: df4854bf691e498f30f4e8872b59443d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/coupler/o2i.nc
  hashes:
    binhash: 2a2f45c16feb254357d2962d58438d54
    md5: 0a614c21e6e93266c46133b5164d88cb
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ice/cice_in.nml
  hashes:
    binhash: 711005e056c3e64e453dc50778da649b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ice/ice.restart_file
  hashes:
    binhash: f43b5bef3c9000e642ba2314b050a50f
    md5: b0f08ee8cfdb466874982bff45e68d63
work/ice/RESTART/iced.0920-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ice/iced.0920-01-01-00000.nc
  hashes:
    binhash: ed135273ba165ed2b30b44a26cebd41b
    md5: 4b08772c2b92545fd3eff13ddf3f4022
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ice/mice.nc
  hashes:
    binhash: 24555a9cb07b499164a802bca99a8454
    md5: 196efe217a6d8973b149e388219188e8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_age.res.nc
  hashes:
    binhash: 16ccb2e6c931b627f39ac1481e3a370e
    md5: cfada7a48a7abf923f5af3cdc1199607
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2bd99ffee90c8f6b63d0f0c17d28a24a
    md5: e5355f6e43deddb22149b6b70d8cd0de
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 049d37dff3389a4d69517382b2f265ee
    md5: 03696206d6214d96be8bc0a9c3e362dd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_density.res.nc
  hashes:
    binhash: e6c0ddb2bac22395b5ca493bf7e62e62
    md5: 8b68ad7a862f79271b6b3d60fb51ab49
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 6da04e5aadfb5ba4d43bc4881cd49204
    md5: c2d2b976446d108f5c847d212c7489ef
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9f72024ed7e45245b176af11173a5e50
    md5: 9a785ecf655a1b255c10e756771d3f43
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 22439b07b981dea0e7964669acaad60b
    md5: 1edb37184f309ed20aeaa02287f248c9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 022e61711d52990521448b6473b406e4
    md5: 28faabfbe8e9254b0406fc6e7670fdd9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_sbc.res.nc
  hashes:
    binhash: db41e8b007f7eb03cc1ce90317eccb17
    md5: 868b35ba3df866b50b293c4127c3d137
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0c7934001487377539fb38184f46e909
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_solo.res
  hashes:
    binhash: f2ec6b455d9791b68cf5510d591e6256
    md5: 16e61936f4766206c5db85fa1ea84257
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2afb84c35c355a58067ed3a0e994ed5a
    md5: 62109d039050012de586fb17ae55139e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2c28a018813bd309b0ccd5536098de08
    md5: 860ec68b52992dfc90c5418fb6836f73
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_tracer.res
  hashes:
    binhash: 724ad48dce0c26be3ad7cc43c3e0c123
    md5: f3c375ed82045c7ee6c04fc4f95024f3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 45ee3bbcbd1ee0b6673b257376ad8699
    md5: 9fe2f89b0c5fad5387b8a13f47e425ea
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e145bcd776d610c6c9cfd6764e4735c3
    md5: 1e67089ea56c309d86c8dff9e2b53cbf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 76930ff41ea14e8ee4766426557aff82
    md5: 2d43ef22800f1f4636b3614835d79807
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart366/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4d180eb47c8e7e2d5f73b5c85e758726
    md5: 671e0340e32a45d24f518f08f8af771a
