format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/atmosphere/restart_dump.astart
  hashes:
    binhash: 60d9947fbb7a681ae894826a60aa74dc
    md5: 1abfb1884a9fd7a198e9dc3d307c3ddd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/atmosphere/um.res.yaml
  hashes:
    binhash: ae5309bf94a9f04d763e72f0b17250ad
    md5: 82d5bffcb6fdf5dec5329116b93c9db8
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/coupler/a2i.nc
  hashes:
    binhash: 38e0c6241793f32fdd59bd83250859e0
    md5: 4dfdc4aea647bc46e73ead8917b95d1e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/coupler/i2a.nc
  hashes:
    binhash: bafaa431b0577050772319010c57cb53
    md5: dbec22158e4123dbe0044a456cae3363
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/coupler/o2i.nc
  hashes:
    binhash: 10121fd5c42e6d7e5d8c92ef5592a659
    md5: 356e49b05579ff04a9828251542542a8
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ice/cice_in.nml
  hashes:
    binhash: a1bc7688738bd03bb547633785e69d88
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ice/ice.restart_file
  hashes:
    binhash: 7ff3fa91817248655c521f0128dac5ac
    md5: 95a72a14ff8140cce5e47403242b998b
work/ice/RESTART/iced.1777-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ice/iced.1777-01-01-00000.nc
  hashes:
    binhash: f8f3bd3195acd953c6b9fccc1e162192
    md5: be75eac440ee4751e20683dfbc21aef6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ice/mice.nc
  hashes:
    binhash: 34e61b413582fc6442bb73eef97c6d1c
    md5: 2294cc4a2bbfef78441f6027f0f4af43
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_age.res.nc
  hashes:
    binhash: a9fb4126d1b11077a6d0290c0335a27c
    md5: 2ff53c3e0a9e60f102eb87617202e38a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 64f98881a53e2bc40f06914173ac6982
    md5: 5cd81c6d6f5d5267d18313739e1fea86
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 55f374c12b782877e370655841bc0865
    md5: 7f9ac9afb202bfba2301b7df3ea8495e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_density.res.nc
  hashes:
    binhash: 89a6800cc3984d139e1abda456a5fd1c
    md5: 681a3728f0580ccc5b52e0c503b873d5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bdc57d08222e57cc9e840472e4dce378
    md5: 5eed4d8d68cce7070e2db1144fdddfdc
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 48bd0330cc9d2058faf04f030cc3fafc
    md5: dde5336073e2cd6e0807bcc53c28be4c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 09036a8ea002eeae48e00e85582652a2
    md5: ba39978ad5ecbd567b89aeadaedc150e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 34feb05832d97cce227a1df6044531fb
    md5: e1a7113c3b94e5f3c99b15c2a6ef71ad
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 200a1588c682bf96d234d7be09354415
    md5: 4873e50d2f38ccfd677155eacd7acee4
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 84ec6a795420a0c436ee78ad072b35c7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_solo.res
  hashes:
    binhash: 27bc80327a739dd769435bf4274ac410
    md5: dbbe905841a82c864ca5ba9107b06049
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: abbe3b21e23975854c3ac2018185e912
    md5: 9a70dc300bb360dc9b372103bd1ee09b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a273fc6af3b87027529158bdb8895ede
    md5: 2134bd26ce83dc0d37f8fae513111f46
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_tracer.res
  hashes:
    binhash: c1b5f002100f4da734544eea98259e6f
    md5: 1220d0cd269e466a8c76991a17d38ba1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 120106846ca26de7d84e6b25dc08dd9d
    md5: 2bda31f5131cb8a611df7de19b50b404
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ef90bedebe1adeca368c7437309939a0
    md5: a2b17273a2867de623fc94f646443921
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b83474eaa793a04e481125440da0a85b
    md5: a2d60db9d553a2b02c0a5b3855011c9e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart332/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e4c1fca0ea2cb659bd59eea7b56d37a7
    md5: 383f1f3f97d3fb8be21b8b94885a2bb0
