format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/atmosphere/restart_dump.astart
  hashes:
    binhash: 727a4ce529123cf4d171faa525edffef
    md5: 552b68bd2869efa06f3ff42f1cfeed52
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/atmosphere/um.res.yaml
  hashes:
    binhash: 2acde97b760d9511e6ee7b0b10ab4e29
    md5: b15838fdc168782c2d74a138100a9b21
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/coupler/a2i.nc
  hashes:
    binhash: 2acd2f3fbf9f4f73875c60e45a605308
    md5: 1b1736ff31e1df63f7f3c0bbb43567e1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/coupler/i2a.nc
  hashes:
    binhash: 5be7bd9bb3d960f0aa994f7ad8cd3af3
    md5: 51a866d6d4437449ae20bbfde2d3ec0f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/coupler/o2i.nc
  hashes:
    binhash: ce5d4377226faf82e4a919976e0f1075
    md5: b5a2841aeaf50e59a5b80c00a63b7317
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ice/cice_in.nml
  hashes:
    binhash: 95588939cffa0fc603023794aa7fbcad
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ice/ice.restart_file
  hashes:
    binhash: f1bb3b3935be54fae66e9d645d5ef0f7
    md5: e96fe99ecf75cc4d5a816b71033321e8
work/ice/RESTART/iced.1842-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ice/iced.1842-01-01-00000.nc
  hashes:
    binhash: d75f9cdc73d66de2caeebd6424f323d6
    md5: d4923df9de88b9627edf52bfac52a699
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ice/mice.nc
  hashes:
    binhash: 1247d08b772976dfef8396dc1431e150
    md5: 880c1aed0171db4a71bba8a8f2bd651d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_age.res.nc
  hashes:
    binhash: 5addfe5e8b167c18fd8c3bb58f602427
    md5: 1b0b66253c9e78574d059816dbe706a5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: dcfa38dd5df611330d12cd48f6e89a33
    md5: 42bbb2b0cf24a86b309db31735b82be1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 20e597f0801f2af02f51c115a6f01ee2
    md5: a563ec12616e28f5040dc5f67d12eb9f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_density.res.nc
  hashes:
    binhash: d5d4f4b959e1aeb1220cdc42c53f40c0
    md5: 8b25c81b6714327219676ccc8ef387da
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4d78c43ee178c0b39c7ec21bc251eb39
    md5: 76a7ad7169ba2a2a457c7b0fe7c3d40e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b0a8214b8fced440639c1b331fc92433
    md5: 70e9ba6d0126ad8a09bb53a9b56ebf43
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 943c67ce595ffcc221d298bfed7c68c6
    md5: 3bad2cb5075dd3ade4ff3afadd6135aa
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4d4e977d8ecad463c01bd5a8836f1c84
    md5: 87f7dc43c9a9555ccc9466baeacee351
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_sbc.res.nc
  hashes:
    binhash: cf55444033e3c8fc035f6adb168c634c
    md5: e39d5fb8d821b2ec50064d99fc7f2766
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 09940245d832fe18d6b0a7e7510d3b04
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_solo.res
  hashes:
    binhash: 1ed28d57733d93af63146df84cb30658
    md5: df33b3e94b6521d7da9798b6c372d6ca
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 2e3eb2afec11c94436ac38ec40892f0b
    md5: 4953a93ed66ee8c48515b5c0573b0110
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3117a7c757ca22f0ab66a31f4cd938e8
    md5: c3b9861ae50d128bf14774f380e1f88c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_tracer.res
  hashes:
    binhash: b48685643199bbbe0ac65ea7d74c4598
    md5: 068980a8ba9faae9a89989fb5377e8b1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b565fcb51c14867d1ce11e142f4fbc89
    md5: 2e45d43ccc5d36dee7c4b888e5ac6d5c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d76a9d3c50a9915b6db6d74f73bd1fc5
    md5: 82791a178036e36c98143805049c69bf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fa85d6caa760289f15ae1d61b2eee8a0
    md5: ff834d5f3df9c6c3b41e704c15780652
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart397/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7dcfc909b095a6672305c8d3eba2338e
    md5: dbf279cfba07d9ea1cb51e377d544c86
