format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/atmosphere/restart_dump.astart
  hashes:
    binhash: 401c50b1eedb1cdb77ef4ac26f65725a
    md5: d12195d0b821321b05a0ee22289f5e65
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/atmosphere/um.res.yaml
  hashes:
    binhash: 0b85bd9eed6796c595ef5d56cd59d0a7
    md5: 7b2e64b5c19ad865a06226548891bb8a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/coupler/a2i.nc
  hashes:
    binhash: 6066321d1ceb713a0f0299d7129a1e46
    md5: b36c732a75d75fc6aca90a06732b92f6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/coupler/i2a.nc
  hashes:
    binhash: cae1191d8fc2582e664b806b05e2ab33
    md5: 3d0b622bf5e5bb5040acbc09041ef548
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/coupler/o2i.nc
  hashes:
    binhash: c45cadc8d18f23013b2b6e40fe6aa667
    md5: 9f8b7bd9fcc034d7dd8b8288df9bef0b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ice/cice_in.nml
  hashes:
    binhash: 7bfc4bca4e708406280b2176c4469eee
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ice/ice.restart_file
  hashes:
    binhash: e1c35a3106b10a567840d627ba8cb8fb
    md5: 1b0e0eda380249c6dad3c41c5aa7feab
work/ice/RESTART/iced.1702-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ice/iced.1702-01-01-00000.nc
  hashes:
    binhash: e977f68c4873bc7e86fa290db60f822e
    md5: ac5a5ea1ae8cc39fe23276297de47f37
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ice/mice.nc
  hashes:
    binhash: 1c699c7b1a25e7c6fae570ed6628db97
    md5: 15ecf265aa0abaec71b528b104697b30
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_age.res.nc
  hashes:
    binhash: cb74bc2ce2e751afd8b7526abc318604
    md5: 76fd8ecd14a92c5859c207d2074b2b48
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e46dbf745c7811e0467915fc01c64a2e
    md5: 920bb86513731c624b23466a9aa07e81
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1687960e1992e7575f1d4fb22cf114e3
    md5: 4da32c55ad5e1c803751823b02ea58b2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_density.res.nc
  hashes:
    binhash: 442d47a506d9419873aa55a7f2af818b
    md5: 7e0e52fa171ef2fc15ff1eb2bc510d9a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b4260745fd8ea4768080aa895c72820c
    md5: 2c8d2834b89966eebb2350894d0dfd30
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e03ad99c94c38bdb3ef2269be6c82f3e
    md5: 900e4a4ad0692fd8ef27b2705b712fa7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a24bd7ca5e12ec51b251c24564861c12
    md5: 21e058bbb5d7fe83859073d2fe30aa1a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e6c281d6810dde91ba50e3bfd12a45a
    md5: 54d1a73f26c2d61fe20d1a12515b00dd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d74a694bbe5d6228cd7a6ca2859fa74b
    md5: 147b8b5542f69d4563fb1c2191ab388d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cb8c085d77f2bb789dba38f4ce181221
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_solo.res
  hashes:
    binhash: 1127eaae46da203423ddfc682d2d5652
    md5: f235b8be9db89b14d729814ac29e1ad6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 489d00a83c13020ee24fd0423dc71641
    md5: b9e60520cf8aba88586cd10b8e3a64f8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9ae1e8e19b56f9554d6d605b2ff98f5a
    md5: 6e6e847a1df5a63b38b6b9f11e153f31
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_tracer.res
  hashes:
    binhash: 949e9348960245f5637576b21c14665c
    md5: 891b6625eda44e9df70adc7acd858c9b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 42fc453f32d69d141554c5a4512588d5
    md5: 49d35486545c29238cc2a97bf10651c2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 02b3705656f6ffd6bd8fb790d4c3e4c4
    md5: 85d61a33fd35a190ecd26dd5a17d5f03
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 53201e360a2651fa3bafed2abd810dc2
    md5: 8b0e8492e0a2c7e18ca7e1052b976074
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart257/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dc1a8ec35ba70fac5c1a1f99425b8c0f
    md5: 81e5d2ae48a3bf7f7d2ce878220a87f4
