format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/atmosphere/restart_dump.astart
  hashes:
    binhash: 2f855e3401169cf76b9ea94be7c2aa7e
    md5: daf681b2ce178e7a7a8ca7689e69cbe3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/atmosphere/um.res.yaml
  hashes:
    binhash: 56f6f58852d6b4f07e8b5cab350ace0e
    md5: 9557226529a57c6006146e891c4213ba
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/coupler/a2i.nc
  hashes:
    binhash: 94c1db009d1a0eacdae92f8395639b1e
    md5: 92493c72a86bb621bea4111719bd7096
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/coupler/i2a.nc
  hashes:
    binhash: 5173bcec45226ad7fbadf4a0a9b7be28
    md5: 169cf3b8dbab9e5ecfae8d592d817ec7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/coupler/o2i.nc
  hashes:
    binhash: b20626b492c3dbb5ae4d82387a53d887
    md5: 1f2372739336224b7fe4ac9da59da8ca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ice/cice_in.nml
  hashes:
    binhash: 8e67018a2945b09355ce46c4604d3273
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ice/ice.restart_file
  hashes:
    binhash: a6b938d280479ca0f67e9e4eed2d5d26
    md5: 72b58317499dd3578fef185dd03ff5fb
work/ice/RESTART/iced.1177-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ice/iced.1177-01-01-00000.nc
  hashes:
    binhash: ce39bff4c5bd56ac22278d498a9b0fcb
    md5: 6a32f6ba8237cd15dd11f7f727426e43
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ice/mice.nc
  hashes:
    binhash: c2f59223dfcda5296ea6bc01b1f018cc
    md5: e7b50cec4871d4a03608b455dd9f256b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_age.res.nc
  hashes:
    binhash: 43f6794337fe8dcae44855acf8cbd296
    md5: 694ee4e91c8beb2e0cbf3118c99f1af6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 127bcf65048fd8012d3f2a3119ba6bb2
    md5: c37dabfe93e20c59a656343e4e2957d2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2dbfef528273640e4c94c065ffb4f3e6
    md5: c8d0fdf051e59b35c3c35061b960f9f2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_density.res.nc
  hashes:
    binhash: 480dcb995e8b63795c8cb71e09e0211b
    md5: 686ea3bac71c5d7eafc831d246d0cc29
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3ecaecc04d1451ba2ab87cb18f5c6c07
    md5: 5e63c96f5daf65bdd9e5949e12c06f55
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f4cad42c5cacaa5861baef3bea3ddeaf
    md5: e02e49f1639683a7ae8ae16b249eaeac
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7601e7b039b63409d571ec170ed79962
    md5: 28a4c70d5af28a92db2243b44f93be16
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: dda04e4c6a9166d17ffa39b9cac9997c
    md5: 7200bf4447e26e3818da03b8721d5488
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aa782651044951f76d75a941a8b4afe6
    md5: 75e712363f20437c110e4b61daf117a0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0b7ca8b1dce2e0c34fb9310865eccb04
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_solo.res
  hashes:
    binhash: f6770da6e02344b2b3acf7c8a497417d
    md5: 3fc18a8d63d02539b36cc9c1e7f62674
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 9b24a646ffcf47524c26309be1984456
    md5: a9b3f04695a6f3320e916e965c3ef401
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 58eab27423684e33629a6c02a79b1911
    md5: 1d9195b732b03659a313dd2c3936a4e8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_tracer.res
  hashes:
    binhash: 844e9e307ce0876ff245eb835f4c2476
    md5: cfa9e67a514d7dbb5195f6806f079783
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7a74e88563b6a50316167ac0a4367032
    md5: 9515a73bf76b5f512e974c454f831060
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a22c2a7b7ce9d252f67b0edeabd6823c
    md5: db5d84c0024883b618063c4c09bcb605
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d6823d8dd14a51158e75397695af6821
    md5: 5d285da948b12f1300b11e8434a7cf44
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart293/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5decb722cbf930f5a63fc448c4d23544
    md5: 0b0726b95fa7e7427eaa9d49e992ab15
