format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/atmosphere/restart_dump.astart
  hashes:
    binhash: 918d8986fa81ab45c1b43c7990585b5e
    md5: 07f522695df9275c87fe68e5ad118ac1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/atmosphere/um.res.yaml
  hashes:
    binhash: b1b31a05b82d505db1365c86ace9b640
    md5: c1f4d698cba0696f71a8c8c1181b9f75
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/coupler/a2i.nc
  hashes:
    binhash: 51e05556d3a5091fa9300a614e8469c1
    md5: b886387c71f3763d3eedab294e0be7e7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/coupler/i2a.nc
  hashes:
    binhash: 76fc98d7825390ea8a6b0fddf66b909d
    md5: e46959b637c9e3396eef602819039e14
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/coupler/o2i.nc
  hashes:
    binhash: 89b3c3cc220dd6a51a1ddaae57c013db
    md5: 19ff119a520c750b476551acea84d41b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ice/cice_in.nml
  hashes:
    binhash: 499d0cfd3f1adf1cedb72160b45502eb
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ice/ice.restart_file
  hashes:
    binhash: acad13702e8c7fc70100cb74cc4b265c
    md5: 830cbceee69e8531319eb798cd84a828
work/ice/RESTART/iced.1272-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ice/iced.1272-01-01-00000.nc
  hashes:
    binhash: 35100085a39425ffc4be03a9e7ab4712
    md5: 971d3c215319c72b77d068fba7b592c2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ice/mice.nc
  hashes:
    binhash: 6e311696d4c0c06f2cb13dbd9ac39fbf
    md5: 1ef995ca9ab920ce8d3edf7a9cb369d9
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_age.res.nc
  hashes:
    binhash: 91350911aa2337569de6699eb9423d80
    md5: ce914e2360d60f26872c24ab9bbb3ce1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bb37da24e8b70f27c50ccd44911edc18
    md5: 64f800cb05923cf444e6908a6a8edd30
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c581f7b742f1516fb92f59113b6f78d9
    md5: 1f40afeff5725d7cd5178d2e42ef61d0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_density.res.nc
  hashes:
    binhash: 39957b23ce0d247b88d5c5adbd8c01a2
    md5: 943f60ffe5177663aa8099becb1307f3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f401b05c6e293de0505aa752bc066538
    md5: e42f64a9f537f21200499d2f60ee1c82
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f02adf55729022dad3fb438e7c8e77bd
    md5: 4e506c73a0165e55891acf16139cfc9e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 86d32f7c75fa765abb9afa94561c753f
    md5: 46ce6bb1fb3e466563245e37238c8f48
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e6f9aba069ca2536c655baeedc85b7d
    md5: e1690a5a4d7c9ed4ef42dd0e12f536cc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ebd0e48410d51443ea364bd80c9f4cec
    md5: ccdbfb92d50b037b3ec85b17a1a83acb
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cc44d1d70dd6fc5a4d0d5a578b416ea9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_solo.res
  hashes:
    binhash: d4c6445421e047165d99f1b2a59eb088
    md5: 8144a8d9bcb7890697feee736d923b49
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f9478a795facc333082fc61f8e0fec27
    md5: eb9df690d6ca6cbb9a8b84dc3cf1b5a2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8063c3a5e253f885e6305ce8f75ba65b
    md5: 9f0e4bcf4ae18f5e05214d1aefd9bdb0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_tracer.res
  hashes:
    binhash: 4fb9e0a049c5cd4cfd03680b0874b0e9
    md5: 46c26a52b6daf5829e8740caf90ab175
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d4044dcead98a2a8b221d800217a6c84
    md5: aa1ac6dcaeb2bc6dacd395db3fb8fdb6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 146d8336b49d55b74a7b8f84fc18eeb2
    md5: f65928eb4fce6f4ab37e344e65e73b09
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0468b1fe13f3221c1b2f4eac8d4dc872
    md5: 93c5cbce7506af2f9f49264b2cbcb7ed
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart388/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5e54f4d857006ea3579364039bca2507
    md5: ecb5510006977667ee4fb62e6a9514bf
