format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/atmosphere/restart_dump.astart
  hashes:
    binhash: 4324eb0db1cfe7ebc03caa15939ff1c2
    md5: f6a6ed7b8c2b5af2b0080aa79f846da6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/atmosphere/um.res.yaml
  hashes:
    binhash: 3c4caca7b0b0450b19f5c1b937d8e1bc
    md5: 5666fdc22b5fc984fc8ff8cc538d9958
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/coupler/a2i.nc
  hashes:
    binhash: 1cf26fc65fab76ccb38284f9227575d4
    md5: a7f983a3884da03a12c9b2d0f5fbae34
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/coupler/i2a.nc
  hashes:
    binhash: db4ddd8c6f963137fcc9eb6f23666db0
    md5: 1e8afda750d92373f48f2e62d6903205
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/coupler/o2i.nc
  hashes:
    binhash: 943a38faf61448798de771e7cac24902
    md5: 0f65713fa4d5b96a543f9f1f65093b82
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ice/cice_in.nml
  hashes:
    binhash: 2ef385eb8a9253edbd221d4fedc8ade2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ice/ice.restart_file
  hashes:
    binhash: 8715c1dd3e2d250f03eac982d421562e
    md5: 6dee4cc66b4b40376f4dfdca0877bc0c
work/ice/RESTART/iced.1706-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ice/iced.1706-01-01-00000.nc
  hashes:
    binhash: 4eea449d88035f390d4b1b1b172c330e
    md5: a8d0cd6f64110cf390a6bff26ffb4ff5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ice/mice.nc
  hashes:
    binhash: 15b7d992e86e85e6475902e4b6f9df96
    md5: 9005501aeba3d2537d1be8bb130eec54
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_age.res.nc
  hashes:
    binhash: 2d935d18a06ba27cf5b2d20acdd0b9db
    md5: 7bf6133d765f15e6615827878c136074
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6a179e4ad113d3b070369884e27b1d16
    md5: fbddb92dc8747a4f18b3034f4683a45a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 64d58bb36896fde329945e2ba189621e
    md5: 93308edb92712892360327878a5cb0d4
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_density.res.nc
  hashes:
    binhash: 46afbf25965df04485565d89a1a7a2b7
    md5: 24dee00534f2f0342c302d1679f8d6c6
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ec30466fa794b7b95669ab2b9fe58dee
    md5: 2a945fb344f8c2d122007e4b00474dd0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: ceaca9187ac982a7fe668a21b6dc88cd
    md5: 5d650184851887eab6e0f882ab072dd4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dad72b2bfe6830fc87329fcf85f00283
    md5: 208b2f84f39d60a486f4b0b554b1e118
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c0fa6e4d85211ef2ca895036fc143172
    md5: 69c88bf39ea541f1ddee211c29500fdd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 406816cf786b02eed3a4f59036bfb84e
    md5: 5a5a1cd460b4961ccd4c768a20762bbf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a48ab11791e7b8974ee5502a30d52e5d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_solo.res
  hashes:
    binhash: 2c1bdad3086434809340b31f845575dc
    md5: 6d9e2f80ad709520c430657c495f506f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c46c8e3ab487e5f3a44ba5ec7b154812
    md5: 940dde51e922baca3d28812196599b81
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 011e419d342bea85408bf5b9acd46421
    md5: c879017a5ea32081e54cc9b1f77318b3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_tracer.res
  hashes:
    binhash: bb99209447b97487447670e82a934bde
    md5: 2a9a5ba3c990339b8c9ce8697f1e5453
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 383e475ad3bc8137eecd1e807913cd4b
    md5: 368ea41edc522acf988d023906b01bab
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5520594a16e525b086fc8432b5404576
    md5: 4271fcfd4f5426abbdfb5be2df932a76
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6e29607f9edfa17833acb7a878f69fe2
    md5: 24883770208fb23ee10ec2c81648b16b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart261/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 355b9986314ff847c904382203417e4d
    md5: a34a6937e9f8b0db5e5fe0ee0ede9705
