format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/atmosphere/restart_dump.astart
  hashes:
    binhash: cb67850878b4214a24d68782d7691ca7
    md5: ec14e9fcff1a31f457e7e2b6bced5733
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/atmosphere/um.res.yaml
  hashes:
    binhash: f89783b8732119ac2a11e9a445279afc
    md5: 5c6a21e2791c6408566359f251b73081
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/coupler/a2i.nc
  hashes:
    binhash: d4c94e669d41bfc7e44d2c54453bfcb9
    md5: 8bc87a38092becf2a2160c18942c56f4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/coupler/i2a.nc
  hashes:
    binhash: 2d5804601ea6df6326e11991e4c79e2b
    md5: 0c7c317ee04bb2706b3d4910491ba342
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/coupler/o2i.nc
  hashes:
    binhash: e98917b004a021973697ba622c2f3b2e
    md5: 6df08465bc6adb7def07b852e4f5f17f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ice/cice_in.nml
  hashes:
    binhash: a7745cca52b27fb30a7c5ac75104a019
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ice/ice.restart_file
  hashes:
    binhash: 6efb2dffb816b52b99c4e15ace9bc265
    md5: 185955aa3340bed82a6e1ff92581e270
work/ice/RESTART/iced.0933-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ice/iced.0933-01-01-00000.nc
  hashes:
    binhash: e27e55776172d0864e77e0ac23e6f69a
    md5: 461933b5d38c07cc10ec44fcf2bdcb0c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ice/mice.nc
  hashes:
    binhash: 813eb288cf7e0be55a3a8d3a4610ac78
    md5: 9637b46ae114579255ff2bd9ddc894f4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_age.res.nc
  hashes:
    binhash: 5afe6ed7b862e0dd9583833a71521428
    md5: db6d7aa44bdfd7bcee6ce2ee318d33d7
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 37ed411881447f0e4b3b2c65537cb79d
    md5: 91fc9d5d2788dd20296a60ba3ed0d76f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4b6de5ba3337e3a82d96c889a93f86a6
    md5: 50abec9b15b9d364c1c39cd28a42dfd3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_density.res.nc
  hashes:
    binhash: be65d88360e7e4d1ace05ffa7523a004
    md5: 312e57f2259cd58c2543759c8e43f09d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 80a715f833d73352d629abb2cd0f0153
    md5: 152eb13b46c56278e97e40cc126600fe
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fdacd63b5294d1de5b4ae89618dbbd0e
    md5: dbb97cff49140b680d1f4929a4ebea7e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 27d9acb9b6ddc86e4f79af73a3503d43
    md5: b21bb83dc92d47993b03aeb0dba853f9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 40345aafb159d5cabe6fa0bbba1b9571
    md5: a6067915640571d0bf0ca3750315ad6e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3a8d726bee6f40c07a8afd567953337d
    md5: a7362e9df8f2f3e55fc724324c6690d6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5ceb546334a10667398cc419b576d1db
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_solo.res
  hashes:
    binhash: fe3da23f6f6ff2a9872a0beccbad6c8e
    md5: c9a5c2f611cbe67261809e11b70cd278
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a7da78f2b920724d1f82194b6d00919c
    md5: 6758227a3f2eb5ac0a7d726f950c7d2c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0a0f4c46c4076969699c4a8bd1262f61
    md5: bfe7b47f6db34620d8fad8e2c8164e82
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_tracer.res
  hashes:
    binhash: c2b92a6e443d69d89539489229f81c6d
    md5: 778f4eb9b6f7a487e8cc27c6e740c318
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a0387df79173e5f92ad0d169b92f539f
    md5: 16c40109f6dd24de24400785e9c092a0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 091591f9ee27a649135ca32e7b17631f
    md5: 8ae6db6e2b788e99eed8dcc22a0c0b64
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9b46ddfdf9732a4ba32261ce7d5ce4e5
    md5: be3e200069098f0255e8ea9e12bd3836
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart379/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: cf31344233506ea11535c54d8c63e10a
    md5: 97abb6201b5707eaf4edcb4f124da2e3
