format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/atmosphere/restart_dump.astart
  hashes:
    binhash: cc144d49aa2e9ee26e86b2972e562176
    md5: 7995f4a27b11a7c90c811f9454006543
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/atmosphere/um.res.yaml
  hashes:
    binhash: b708da6daaa8cb4abc7dddad54be98aa
    md5: a887100b0cea4e6f1fb9393e1d2e301a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/coupler/a2i.nc
  hashes:
    binhash: 191309bb2f415e6b286fc46c316d7ed6
    md5: 35fd54262bc8f7466c59fb8c528a2ce1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/coupler/i2a.nc
  hashes:
    binhash: d4ae9115543a0ba30ed10840281e46a6
    md5: 2a5c2e0891a491ecdc4dbc4e222ccad6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/coupler/o2i.nc
  hashes:
    binhash: effe7b6ba6ce5223a345541dba59494a
    md5: 6d75a86c6656b8a9bb338537b85aca84
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ice/cice_in.nml
  hashes:
    binhash: 2d94c96dd04f0b9974b4e34d0473b23a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ice/ice.restart_file
  hashes:
    binhash: 430807950b2885e61e24fda3eb7fc569
    md5: f2f618c00b0f715f604256dd42e4967a
work/ice/RESTART/iced.1756-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ice/iced.1756-01-01-00000.nc
  hashes:
    binhash: 57bba5d14b839979bf406f0227fd1a42
    md5: 49ebf6b5fe6dad6ac6cfd3aeb240d4a9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ice/mice.nc
  hashes:
    binhash: 4f9cba8f039f8a20f8a18a60205b423d
    md5: 1f1941ac3eb47aaa8d57ce7adfd5c295
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_age.res.nc
  hashes:
    binhash: a2ed7beb4ab79e857004f7f0490050b0
    md5: 8b11b2e147eed076bf051dcbf4c5be37
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ef0de2253e76a666c100e736e02df1bf
    md5: b8ccc4835cd8f7fdaee5273b227de10b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0a17034a3c201cb2491f848ee1a5c7f8
    md5: 7c377852053f8505054f770e85326439
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_density.res.nc
  hashes:
    binhash: 5c84b8e2f02c31b85cc47b56cd26f571
    md5: e81829b089323903a1b589d0e7fb39e0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 205bb47416f3260da167082409cc0d33
    md5: c3fc9af86b3696afb363087ccd1e8e45
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 03ba6d063d505c73e0bea3074d4387e4
    md5: 110f92fc41ba935881b543715451febf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 757e12cfd5ca6e43827286df14392491
    md5: 18baa9ea316a400a2c3db8e10794050c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fe5e420a78fbe1f08ece5017a60ab594
    md5: c623df3d9bc5567e997cc0995d3c9f8b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 0a3a8a1a90562cd8ac7a67874ebd179f
    md5: 814737bc5a52dd564fbb6aa961f66907
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 09c2240892e15745945c49ec41f84c2b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_solo.res
  hashes:
    binhash: 44fd9f87f2acde7af0565ca394904c8d
    md5: 7ef1c66dccbdd1492025f74cb621f57a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 35750ceb48e2e62ddc61396e05d1ec7e
    md5: 92fbb51c9c7255e2aa63bf692219302e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 2fce4abbac588e722f7a4adbcabaa4a0
    md5: f9c7d9afa3114c925b51827199c24b28
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_tracer.res
  hashes:
    binhash: f7ce9950962358c8992ad254d2ede7a0
    md5: eaabdf9c8f1a90cbe4d52bdc29af1569
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1cacdd9e563f1dca76b3ec9b9ab8714d
    md5: 1ada0f2051f9903ae684bf39c4075470
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5bde6b9b717698a7d7ee72e9411c5e0c
    md5: 1a590bdde6ca7f04029ad065392910a7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 96816e760f32d58a5db21e1bec91c2bf
    md5: 3f53fc4f98c70260b9a2297cbcacd3b0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart311/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3582091c5d636fa0392f6782aeca0efa
    md5: 808519e6d885ed898ce958c7b2e0b41b
