format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/atmosphere/restart_dump.astart
  hashes:
    binhash: ce95cdfc9bfd0678f3fae0476a407e4e
    md5: 4ac98a72c3263a78b02bc89d1ea21981
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/atmosphere/um.res.yaml
  hashes:
    binhash: a7e190a31ed495687d31535c47ff9f1f
    md5: 96a75af22a2c3dcce69a6cdbbfc120c6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/coupler/a2i.nc
  hashes:
    binhash: ce63793cc5fde5bca7b2f6a65f0fa57b
    md5: f396ce4e1652a69377e8d873c0648123
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/coupler/i2a.nc
  hashes:
    binhash: c275d0fd2d45c5f6c72b82f18b009676
    md5: 71bd7d0cd9559a72a856fcd5be009123
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/coupler/o2i.nc
  hashes:
    binhash: 7550f5925e70c971daed29129408746d
    md5: 4191db38dc559aedd64bf939648ff821
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ice/cice_in.nml
  hashes:
    binhash: 0e724cf1250161ce0050540da7911918
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ice/ice.restart_file
  hashes:
    binhash: e4e681cdd5a91282e6f01c2b07831573
    md5: 2ce3763bc50316de352a2b7627274c81
work/ice/RESTART/iced.1732-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ice/iced.1732-01-01-00000.nc
  hashes:
    binhash: 2c45093a619b2d97a0601d269c346190
    md5: f8a6561ad04a8c75501f071ca7f056b1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ice/mice.nc
  hashes:
    binhash: aee40ca7175e2111fd792a0c4487cb1e
    md5: 58157e839a08485df1f6640b709bf940
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_age.res.nc
  hashes:
    binhash: d708a18ee71a3970ab367cd1f6b5eb5d
    md5: 99ad4297d0ae161c0a51c61255cc1515
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f232e0b8b7de77a5e8bb062bd0a276ea
    md5: 9ea30f8d51a82048d6cec57249325cb4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2ea891335ae7ecbebd6c59e6de79968f
    md5: 3f52457448ea119769dd4492d15d74ba
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_density.res.nc
  hashes:
    binhash: 91c167388838b1b4b8cc655b017a49d7
    md5: 89aa5bae0509d766f5f97999d32db369
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eff6a6f4991cdc3fa6adad726a2db1b6
    md5: a3f327d2d80d533fbc66a4c4c1366cc6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 54c7969a6b15cc45f8a2c6753a595435
    md5: 308d07d38af4e8e2e86705749c9df02f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bdf1b9f031826f0d9d871ea732e3e378
    md5: fbc4171a4b0eb01c5ecf571ebb341c01
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a30d5342e9e26560390f5b6b51c472ac
    md5: b932015a46915a419d782278a467b331
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4abaeb93c062abbb423b1daf1d9a7b86
    md5: 5d666123b29e845ce60c2303d9bdebc9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e4e26ea1808ea2a054a249f40a055397
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_solo.res
  hashes:
    binhash: 8abc3c0a67df30c572d964dd48ee817b
    md5: 5bd2a723d5186298ae888a43b741aa13
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 77738547f66778f366604516978a8307
    md5: da5d1709899a5ac744267f24fe6f99f2
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 350a7e0afe73eec645eb3b3ce59ecff9
    md5: 992a0f8a3c9d85e2b032b25d3f3cc211
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_tracer.res
  hashes:
    binhash: 6d8e029491eea5d41e4b66f3aa5141ef
    md5: 24e9953e8613f1ccd8b4eaed4b16bd93
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 05fda91a3b65d898445471df68a9bd9d
    md5: c0425a80c43d2a43b3c4c6dd20e42e86
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8fbf37ac30cec88449373b77365261bc
    md5: 19717a6e2095eb801562d624e672267f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9ada40d6bf313f0ee9d92267c3e2bf58
    md5: 04e44d46dfcc2f10f66a2f31faf6994c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart287/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 02a1481c09b6ff8daa7676799152b400
    md5: 45c2f41975a4bd7855f53d3a94d6b4af
