format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/atmosphere/restart_dump.astart
  hashes:
    binhash: 9031d04038edf44f842238fc6d8179cc
    md5: 1eb24df829b74b952144dadafabc1f80
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/atmosphere/um.res.yaml
  hashes:
    binhash: 780348d9c3ff8a8ed56140b5233eb70f
    md5: bb9585f8ccba7e3040bae55781b397a6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/coupler/a2i.nc
  hashes:
    binhash: 268013b43a4ed143defd8040dd056161
    md5: 4db4f6d53201421c8f4aed1edb20b887
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/coupler/i2a.nc
  hashes:
    binhash: c71744b26d976b39b8caca566ab28a2e
    md5: 931e88392607b7eeb9d09b6477dfb39c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/coupler/o2i.nc
  hashes:
    binhash: 801d70587dedac1ba03ba022fe423fad
    md5: c6493358178e06875b503defa962719f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ice/cice_in.nml
  hashes:
    binhash: 308d7fe2aeb9790f3271501bd82e06a2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ice/ice.restart_file
  hashes:
    binhash: fe7b85836efe432a050795ba0204c270
    md5: 2d5bcef71fbf8cd9c503ac3f27d8b39b
work/ice/RESTART/iced.1166-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ice/iced.1166-01-01-00000.nc
  hashes:
    binhash: dab4355faf0b3803b5a9c24543fc9abc
    md5: 6e5caa1b366158d6381a7eefef929b4f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ice/mice.nc
  hashes:
    binhash: 62945521edf33a39b4567753b51139a7
    md5: 73f5423ae4da1ec8d756091e4fa7600a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_age.res.nc
  hashes:
    binhash: fcdf1d1081f48d2fe346a807400a107b
    md5: 6d3df9800be0309adc7c991c3950f76f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 67c8ad90706ca964495e00c3b4cbc544
    md5: 54e5fbf06890010c5ec9aaaf921ee6ac
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fd8df85753156e190eda8e0263abe032
    md5: 5d58487bff2381cf21b77c0fc0b2ffd1
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_density.res.nc
  hashes:
    binhash: 152dbc31aca1592b8d42804a51c2fa9a
    md5: 22d973809aa9ddc53a141907dd113225
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 84c39cceac308bb6a5dce2fb6b149bc5
    md5: 6ae2d2ba5ed3ec590fc3376cf9d0d4d2
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 97efdbc82a33a7780567b4d10133435f
    md5: e8afe0a627b9b76d6eb39513f8c2b9aa
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d4302d3d1baba17e810aaae9cf4b8da3
    md5: 67b8226ab269c753c8bab03592e4639b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 786a026e777a1fb36eb1d9c24de67b40
    md5: 296c1d46874d15a735530cc288537136
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d3b3ceaeed35461410689427bfb2b9da
    md5: 6115a7005a1fe0c2d4051f3804830693
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f2643a4f2b23edeed9cd78514d99c1e2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_solo.res
  hashes:
    binhash: 9f58a0b3410ea246d9bf1c026502486e
    md5: de6006354d7bdd1ce63306949bad0393
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: aa0afa52210dffee51de0b7a00ffcb73
    md5: e6895d7e8a5a87610e10949a0ee82791
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 22c6ccb4e2cdb24b30619bf0fe918ba3
    md5: f54b99d6d02525cbd638b643231c9d93
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_tracer.res
  hashes:
    binhash: e3a64ed414ffdc5a943d873d725e1485
    md5: bd0dbd10f1932b0d67141e1e51b9ab0a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 31c98becb2991906ba53f5c465950e0f
    md5: c718359bec8fe0d9cfdc0e1fee708d26
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: c044a6382b0c58f9af0611afdc13612d
    md5: e5c62ae35f4dc0b4c0ff4f0277cbe547
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0a02501ee8ae1b7a7dccdb18bae2c309
    md5: 3bc1ed34d4c658fd736b404689fbd8eb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart282/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1a9e70d2ca4692e6a546074b71b050b0
    md5: 968d5003b37cabd209c3573f0072fb39
