format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/atmosphere/restart_dump.astart
  hashes:
    binhash: 9486ec5b5f9b1e39e5fa01360285ba93
    md5: 01f0afd20c17e022793de28b26891031
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/atmosphere/um.res.yaml
  hashes:
    binhash: d934c5ff04896931cd0bce5863b6d3dd
    md5: e60f69c75568045429e1d0c86b2d8031
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/coupler/a2i.nc
  hashes:
    binhash: cda80ee1c919d694c89891a43275c13c
    md5: 97189ce4243a6961d212910ab1b51420
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/coupler/i2a.nc
  hashes:
    binhash: ebf881293b225a4e5d7e407306f5c243
    md5: 354290edbe973447b8bd2e0eb070828f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/coupler/o2i.nc
  hashes:
    binhash: 0fec8ba2bfc5625e896291ee62090e61
    md5: 71de92b4cef261f7339a895cfd7b4ad5
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ice/cice_in.nml
  hashes:
    binhash: 19762c647e892ba73d3adaa750cb426f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ice/ice.restart_file
  hashes:
    binhash: f3184e374000228b711a8f1cdd4114ed
    md5: d1f79344b61a2a9331ed559326259cb4
work/ice/RESTART/iced.1157-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ice/iced.1157-01-01-00000.nc
  hashes:
    binhash: bacc010d1ce6b1c110794dc4e1e06cb3
    md5: 0678b917f3b39e53e445f0f03dfdbec6
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ice/mice.nc
  hashes:
    binhash: 198e55ce4d8433e4f5df505056e1b2d7
    md5: 7a1f96c5fcf036388ced876e63c1b85f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_age.res.nc
  hashes:
    binhash: 468cad24a4bc583da0f0f8778c429aeb
    md5: c85480a50f0aff2256da26915b85730e
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f90599c653dee841fcc29fa4aa7f22e7
    md5: f7174f8840d34b23632d62ff981f3511
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1cdae984823cccbade28b30785af0950
    md5: d534a7d308cabe9a26781efdae18df96
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_density.res.nc
  hashes:
    binhash: 051e052c39aa017361c3c51666f6eb07
    md5: 3c3514e0c65a516dfdcab96236896c2f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9f90e24262a1b941da5e51448afb09be
    md5: 619a1dc8865470a977c46c048205a43f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d9441f66123da5c8ad93280f9f5d7cdf
    md5: 70f7ac03ea59bd9116fe8026dfdcc58f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1314b904d34806c4045684cb12bcb157
    md5: 8d92a4de8eb6e1c993f315508c7edc4d
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 323d26b8c2f587fbe3ab72a246b05dc8
    md5: af3ec7eec26eb3a98b1b1759abe4a4b7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_sbc.res.nc
  hashes:
    binhash: d3bb1a124e9069a855a5f6081240b410
    md5: 8236bfec5ae1def2fa5b61cbcf4bc06b
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 32ce73a8f18576979086f6094f1a552a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_solo.res
  hashes:
    binhash: 4488793ba3c5aafdc0b0cb4cd8e68ae9
    md5: 7faa1a7a88580643dea4a2129fff93f3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a402cf6aa1104025616819c00c37e625
    md5: 9945ddec04744e4e0bf79f9df9081ee6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bb763957eac16bf0f600c593d6c599c1
    md5: 4f73312fc366ae9093bd10a598a8bc77
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_tracer.res
  hashes:
    binhash: 829ecefed204453fa3b863b9e4fe1756
    md5: ede92e063cb273ddb427d19d8cdd0db8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5b812501deacbb3060793569ccf661a8
    md5: fd9c25d4252e45768c9837f596b4ccc7
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 88b2a70c3683fe59fcd1e8fcfda9bc3f
    md5: 6a3e5bb71eaddc8f3473abaefdc91026
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 25912f9492402c2daf04523cb1cc4a91
    md5: 8007e3463f5b37c634fb2f172e67bcc7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart273/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8e7e33b67e0232522d9aced1b4383bd2
    md5: 234268f2a97b5f2bd5d230a4f69cc638
