format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/atmosphere/restart_dump.astart
  hashes:
    binhash: f8fab06cd34dc010d8cba066f4d465f4
    md5: 4ee6327c85fe73441ad1aa7ae3befc0e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/atmosphere/um.res.yaml
  hashes:
    binhash: 541eb79256765219692bcaf4d539bd17
    md5: cc90b90c65c3e2196cde5befbe618e23
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/coupler/a2i.nc
  hashes:
    binhash: 198789c5af18deb56fa23f7ae644fbbf
    md5: 8d6f4d5aac8d18d1e69afaabf3a0659f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/coupler/i2a.nc
  hashes:
    binhash: 66ae0a3b10520e50239a927cc507818f
    md5: bcff4bfe4b115d21423923c06271e315
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/coupler/o2i.nc
  hashes:
    binhash: 4ff101b11741b44dc06763f074193246
    md5: 11f237081989900f5f6e2c2d0b2949ca
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ice/cice_in.nml
  hashes:
    binhash: 34f8f63e7677ee240ce5be3a81156368
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ice/ice.restart_file
  hashes:
    binhash: 8cc15529a2a1ae1c6da724d3f6824869
    md5: ec9600747948846d2cacd9461fe5e520
work/ice/RESTART/iced.1267-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ice/iced.1267-01-01-00000.nc
  hashes:
    binhash: 20dc63c9cea0e71cd0d347612abc2a36
    md5: 977c037e451e9a5fb5d7ad989107ec83
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ice/mice.nc
  hashes:
    binhash: 1b4c40813b86054ebfe2a11cae2d79ec
    md5: 794a43d0c34fd5d51218ab188a39cb28
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_age.res.nc
  hashes:
    binhash: a5f079a39f6abfb1ece5f7fecbd4167f
    md5: df18a99cebf03847877031c861c731b5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 074504c44f43434cc2691ff34288ad23
    md5: c99fd8167957828581250f68eeb744b8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0c5ff58ddfaa3ae595e219c9c0ea567e
    md5: 6eb800b396ee54d08d64a0135a89ce75
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_density.res.nc
  hashes:
    binhash: 1e3231716bd9b0fa12175a47ddc2a80d
    md5: b9be69a5ccea09528e39b9b369907795
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 95b2edf56a9ccdf69cd90ce35598a6d6
    md5: 8a707404edf7388ae77fe744aad9bdb8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 62bf8a942b18c6fbae5a41e058095bd0
    md5: 7f87191c268be05086110876a924223d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a7c9db7aa9465a3f9a4f5ac45c75e595
    md5: 7acd08228beab7f4246a33d1c2bab1e6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 55a0a19da922022c7d1f3612aeb67403
    md5: cd69117a696f679b98a40a0372c12edc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 34b9150215baf9083ed7258d3895804a
    md5: d059bb0b60b5e96fce4f5f7f390fd502
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 73075b495c6405d0ac9994fca5889b4d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_solo.res
  hashes:
    binhash: eba01acd8644d47ba33c395e24c18844
    md5: 94d3ee44be6757551fbb37b925710d85
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: bfd1e6b222cd33eae1e8901eb1944c16
    md5: 62a2d1f9f424d9887502625a3006c722
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5dff9a02cdf9de8187286f7fced3d606
    md5: 457e9aa0ca1f420c1eed415b8b747cf8
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_tracer.res
  hashes:
    binhash: eb9d3f2aa4f0dd2fac031521dc586751
    md5: 8d4ad4952c6ebeb598af7c3dd896f263
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 80984d1157dc327f481de5f24f55b62e
    md5: ae2b2319efd15eb3f7acaccfc3d534b4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 52101da39d305675c8cd3dd605d59a8a
    md5: e3ff2bc2667a8c8160ef83a691b505f2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4fbaf0ab239ff575f5edef2527ddfe3f
    md5: ccae40cc41f2bab9c3f663aad8b1676d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart383/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 0524c888ac7dbdb222c87156d1049be6
    md5: dd49820e2d4bff8f59ec9f27d87a34b6
