format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/atmosphere/restart_dump.astart
  hashes:
    binhash: 0196ecdfb975ecce34f76d4953c922f2
    md5: 9848fce322e1a8d5f76bd1d4f42a3159
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/atmosphere/um.res.yaml
  hashes:
    binhash: 8c23a58481928d0b9eaa9ba037dbb9ba
    md5: 8b571145b1887fdc7741e0bc0edaeb63
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/coupler/a2i.nc
  hashes:
    binhash: 1b8243b254117362dc61d43ff59f115f
    md5: 5d3beffa0a0cc4ec529a1c760b5245a3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/coupler/i2a.nc
  hashes:
    binhash: 20e62c0919638aae7b56aaac4c45cd02
    md5: 93603f4d3752eb43a6a3821758d10b90
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/coupler/o2i.nc
  hashes:
    binhash: 8c8c3433fe11beec4084a9505ef05fec
    md5: 5568de9a3fb41c8805d150f550bf824e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ice/cice_in.nml
  hashes:
    binhash: 80fe28bcdf772be5fc0ccd7cedb2559d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ice/ice.restart_file
  hashes:
    binhash: 46d4509f8553315740721d0f525e3874
    md5: 0740d26ac6e126ed0521ec541ef7a4c3
work/ice/RESTART/iced.1719-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ice/iced.1719-01-01-00000.nc
  hashes:
    binhash: 7c882926e979d4cc0c55b1b014b0c2ef
    md5: 7d9f7c0039c5de9efc8c71183ab33a49
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ice/mice.nc
  hashes:
    binhash: f853f2a06e5115126aa6591954191242
    md5: 77713e4907297481c7381f2228ce27ca
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_age.res.nc
  hashes:
    binhash: b00f25265cab94c3e566ffbabed301be
    md5: 1cd8291ea582d9cb3cfffebc791d3bc5
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7f34a3dd6a775cfeb1d595cb69a1c97e
    md5: ffc6fa4fdafa1ad80d13d538cab1dcf5
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 00fbdca33b1ee48f0af2fe96d90c2775
    md5: b21c1fef11e0d8efea7cc4e24b515ed8
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_density.res.nc
  hashes:
    binhash: 6dfb11c0d59b46de239420c02924187e
    md5: 5b344155c0ea301f0a99e1da91b90830
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 519eaebe6f8a22b3e006bca2968d2ff8
    md5: 1716ff30bec3912cf2ad9a45f614e6a1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: d3d97cfc8bf3ada72eb6ad51d0bd4efd
    md5: a485101bf22ca4b034a3fa702a7a0a28
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 597e521b1b9fb8b9359e6d9daad2200f
    md5: 405f0ded7ec7f70ed167091197fe7a82
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ce0187f85119f819c410a9a63b411ea1
    md5: 30c0f9bb3246b68b713e7cbac315e64b
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7a9bc198461a43b70dd04bcf3b10e4a3
    md5: 182f493275d150232f677598fc58f5ee
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 432c3a061672b759ad65501f6874c4fc
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_solo.res
  hashes:
    binhash: 9674258b09cc64bca8c6c1a29ff86f94
    md5: 819b4b57b97cdf03d10bcfc97c374cc9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 151e783022f970b101607d5594cd4b91
    md5: 778af47fd221ffab73d69b1b44e9a756
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b59a262cdbee49efb9cd8d2e26aa581e
    md5: d9f2daeafee0c8469e1d02353c0e9a6f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_tracer.res
  hashes:
    binhash: 0a25559689749bf0f8ccac998d262055
    md5: 8b7fa1d7922a3e49e991e603961d1739
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 127823fd09f0c964ce0d0f1d7e392795
    md5: f6e9b8b49e335382b954b16cab8757c3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e14194b33aa21789f7134bcd25c05276
    md5: 03167b44a21afaf1e1b397c8df54bd67
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6d632f83013be0295bb11bca362c50cb
    md5: 9809f9ca2bace35b46ffd4d9f5ce32e0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart274/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d299ccc12e0361b9263f573294e6a0c2
    md5: 3e7e76eb0e77b9629d839d5d10a08372
