format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/atmosphere/restart_dump.astart
  hashes:
    binhash: 67d3ac7155ad1f4ef70c063f1c9ebabe
    md5: 35597f09d370555d553f1b4c6ea545de
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/atmosphere/um.res.yaml
  hashes:
    binhash: 22771cfdfaef9f5e3711d533601efd84
    md5: 98bcdee3f93ced80e054776c8034c0a5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/coupler/a2i.nc
  hashes:
    binhash: 88dc031f252972db5e63917b89a19442
    md5: 292536a29153665f53bfa10205c092d8
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/coupler/i2a.nc
  hashes:
    binhash: 76779e22dc3112676ea671ce0223631c
    md5: 67f7949160a0725ac342acb47d18fa2b
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/coupler/o2i.nc
  hashes:
    binhash: 8e7f60d0dd74771688bf3c6ac8b1c10c
    md5: 1a6b1cf97b9832b621262bea4a35fcae
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ice/cice_in.nml
  hashes:
    binhash: 505921cc37291f5efed31e77f371d83b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ice/ice.restart_file
  hashes:
    binhash: a8700f9c3f0c8f80caa8ec7abb6699e9
    md5: e3b50dc71263ee806017a541c4a83e42
work/ice/RESTART/iced.1259-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ice/iced.1259-01-01-00000.nc
  hashes:
    binhash: a2569caaf3f6fcaa49a44e29ea6d2426
    md5: 40c084e216c5b74394fe4ab1fc452767
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ice/mice.nc
  hashes:
    binhash: 5cc1b5d02ef74f3f57a4b5f7966e073b
    md5: 8035ea7e6bbf08db7de45f7e1e4be7f3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_age.res.nc
  hashes:
    binhash: 4f2ada10762d88a5e798c2ef0fa10c1a
    md5: ed2156f2dc71a7b4248d69255fe96f7f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3822fbacab53d0899ffc8ba602d47145
    md5: c2fc249f350ba45e10dddbeff7df39d0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8f2ab23e10ac521a6db3f691745f7081
    md5: 3d63c5225b10eb728ed81401dfec37fa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_density.res.nc
  hashes:
    binhash: 2014d0819e9b267e9cf5dd5f90a566c5
    md5: f5042dcf7bba92e7e7ecae88e55a2b8e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0aadc1e35fd2b589b79e5b64fa39338f
    md5: 35b1124a435b940361680f0ffa144a94
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e0b3e3e785b25277e51768c16fcbf228
    md5: 7ef2787795527ce3fe775a525b3e8d59
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 88d23c49aba02be925b7ea44bfa33050
    md5: 0504a8eac65ca87782db5e1c259dd26f
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 036bed46ff4c151f4857b3e9a2dbe749
    md5: b95707cb15eb07026abb1d1e7e4cdbab
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 501c48f03d0b4233e8f2c13b1dd63021
    md5: 65a5aa7500965fc3fee52f531cc433a6
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 39a472a955f4620d8ba01709ecd1f508
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_solo.res
  hashes:
    binhash: 50d9dfb7a2214886f3daaa367b23de8a
    md5: a39a0926dd9fbbc66297ef91f99a856a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e36af53ad2e56ef389389f24c83d463b
    md5: f89f0706d4ac7a57e29cb08b57e2c5e9
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 55993d6d57e7146c48024c5e82258af9
    md5: 5a647c97f6f132f6b4572e76ac40b50e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_tracer.res
  hashes:
    binhash: d9d31a48a6916f463dc9366a1c1bd983
    md5: a4053d20cc512c4da3da6ea890e522e2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 29a1533bb8e63ab68e1f136979c73a1c
    md5: c14a89c4ccf8f39cd008d6a442699800
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f2c1e5e44f5c2149f4506ed47908a577
    md5: 975bc94e9731f1de331793ab790a6827
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eb7271e6c1c11304287c46abb49a9ff2
    md5: 4ba53bce9eba87b5a61ba42d7904a3bb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart375/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: fa31ca8b44badff41f6f623746513745
    md5: 62e41d9502cf8d1e60def86674f025d4
