format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/atmosphere/restart_dump.astart
  hashes:
    binhash: aedfc53e3086de59740ddd75b18d5acd
    md5: 2aaa846d68a65ba9a08db4900a75822a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/atmosphere/um.res.yaml
  hashes:
    binhash: dab65bb0c770a6d9da544315d1d2bbe4
    md5: a251c25d14fdce8b2012f5c77c2be54d
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/coupler/a2i.nc
  hashes:
    binhash: 0455cfe321e32ae9902097020ae01d2a
    md5: f16b94884d80db3146c547ae7aa378a7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/coupler/i2a.nc
  hashes:
    binhash: 1871716559b65900754cf90f9e027342
    md5: 1eee1ead5d5ef24eeaf583f069b9ecce
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/coupler/o2i.nc
  hashes:
    binhash: 7da3f1e8c9e67225653670807dd7b81e
    md5: a962455e62163c7bba04fc19eb7d6432
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ice/cice_in.nml
  hashes:
    binhash: 27884f04863c6d1dd0e2cd84de415eb9
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ice/ice.restart_file
  hashes:
    binhash: efbd5c0ab048cf0c7d1e93dd185fb801
    md5: 42ebd178de13d3285b14393c48b668ca
work/ice/RESTART/iced.0836-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ice/iced.0836-01-01-00000.nc
  hashes:
    binhash: 44d2ca58f794b5af724079f65ae302a9
    md5: 40fd49e7194ff38c7c16aad645e2a3e1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ice/mice.nc
  hashes:
    binhash: bd5c4f05336603faae708eaa59143b6a
    md5: 3858f2d399019476b30e69f5fd3f69ea
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_age.res.nc
  hashes:
    binhash: aeb3dab686e2f688ad96d781e632ecda
    md5: e66659f117b378853474249b0fa22349
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: f381e8a32430c04d35d59724f40d2d63
    md5: 7c01d7a76b46dcc802d593988ce7c064
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e59d68a27f7bbaeb49f779264e116a93
    md5: 90e5b497ee0804a65d0db50830ccac01
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_density.res.nc
  hashes:
    binhash: 648e50debc129a324c576dfee2547c9a
    md5: ddfccfd6997957a727043b4d1ff90559
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2cbe92614e25ff9ef0a7b8eee7a58d69
    md5: 6ba8d144ab83223ecaf6f608c1c78d94
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 8a4996b458857de68db0330888599ad7
    md5: 839eab94603dd241eea74014e962c335
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_neutral.res.nc
  hashes:
    binhash: aa85d447a23596ed0a4d7a2d9b74d0f2
    md5: 871c038595729d2d4aba2fe8fcc43803
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bf05f454b5c512eaa0d0915a56b789eb
    md5: a8391170f52eb9ef234e658cf9caf3e5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a33eead886cd247dac787fbd8b342379
    md5: 6fb9eb0e324aa830c8436edc0b59b74e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 17dad8e25a076dc57ee5f219d823ebdb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_solo.res
  hashes:
    binhash: 1c96a5d44d9c46a9a54cdccb169de902
    md5: aa41ff8d2c9fc9944ead3ca0d1dd06aa
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8c56ec250484913379cb40aa60b3f8c6
    md5: aa88128be412b17ffd156c66bec372e5
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 035eb6fe4fa915b035d5bf31f691a470
    md5: 6276107dae386ed9ecceb551190c4c00
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_tracer.res
  hashes:
    binhash: f5556c010524fc6761a12d0f494a195e
    md5: 3851f36971c88aa41ddb64ea0743f288
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 894b45469baa3f5b4a6ab42105715d90
    md5: f05743271c868ed44f24fd5957586b59
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a3ce28c4f3377a103ccc2588620c9a7d
    md5: a04fd2b609680fdbbd36a8ebfd6d134a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: eea79534975fecc6df043dbda6bc3443
    md5: a104e8f065a41e8998553419b123f542
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart282/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: bb1b88202dfbac4b879ca07e2858420e
    md5: cbedacfdaf335aa520fba9ce07b1e735
