format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/atmosphere/restart_dump.astart
  hashes:
    binhash: d970f8ef8f7fa3a266eed77384951061
    md5: a514e036326ca9860c6ae371d2d71e04
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/atmosphere/um.res.yaml
  hashes:
    binhash: 187e02947ba3448db7d9404f7d695047
    md5: fda2f07e8c936940902473fdc84808d3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/coupler/a2i.nc
  hashes:
    binhash: 16d5047824f4a3ef9c98593c71b36e0c
    md5: a100e1f3f27067124ddd327e01574edf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/coupler/i2a.nc
  hashes:
    binhash: 7de53245bd19903b59c87ae283a848c3
    md5: 90bc10f4b7eb67640fa1d6f3c2207452
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/coupler/o2i.nc
  hashes:
    binhash: e8cd2a6cdbeb2d2cc01263382412183c
    md5: 5e1f24c5832be881f8a483271e287e7f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ice/cice_in.nml
  hashes:
    binhash: f6019463dbdf2ca741806b67cd249931
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ice/ice.restart_file
  hashes:
    binhash: aa0e6c7c478e7da18f5da1e3e2835df3
    md5: fa6d4ba6d807f7396e14b23653759430
work/ice/RESTART/iced.1253-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ice/iced.1253-01-01-00000.nc
  hashes:
    binhash: 92f67aeaa01ec7f11b1253e90e0446d7
    md5: a56d16127dc9d0103ece269cfeab7b00
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ice/mice.nc
  hashes:
    binhash: 2ec8bebb1180e2e7f95b5863bf905b4f
    md5: 774c0be839526ab25509a9d6ec1a392f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_age.res.nc
  hashes:
    binhash: e1b71e714a4cc7c41b957906052fa656
    md5: 4fb6b80f2fcba8f048bfc3b6be84476a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c725fd9b5792a531cf8cdb16256faafc
    md5: b4f2511ce2fe7b646d22188af1cab8df
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f37e17e080ce6804834bb4380a69575f
    md5: e39c5ec9d4cb5438629372ccbb700a75
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_density.res.nc
  hashes:
    binhash: 8168351dd35f5936ab5a73397f082910
    md5: d090e2c664940458c7b14829012c1ca5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fd62e117bd1a4b0c029e3e74983ec9ba
    md5: 196698c5cec7adc4ddea2de297362db4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3702c4a145b3abfeffc0cb5a22bdb028
    md5: c9b36cf50c01a6ba6457b74bd63624f8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_neutral.res.nc
  hashes:
    binhash: db8048d7abac8a143f72e1856cf42ecd
    md5: d1d3b2e1855c4ee217edbb22040eb785
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7e521adb7e0cc16c73260f61843d3e9d
    md5: 113d451337973b08731e4eb88a7bc9a2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5f6f6c1d65a1c64b9aafe2c5826d04c7
    md5: 4c66b6cf43357b1b2af3338d8006b99e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a93cd5dae3217b2c65b4bdac262a7477
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_solo.res
  hashes:
    binhash: 99400dd91a0a9bb430da8d517c26a7ee
    md5: c548dda4fa72df42245e56cbcf64a275
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 372935d5cc79d9f5e3f6ceb6e8183a6d
    md5: 889897a803b32302a86532c4ef233c1d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4fcc7d5f517b8a2ee0fbcf6dc1bbc6e0
    md5: 0e806246a592e5fc7b4ba40084ba4c0f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_tracer.res
  hashes:
    binhash: 633f6bad4bc20cb98f671c3b87437f39
    md5: f6af9e217199e4db72209a16e81fb582
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_velocity.res.nc
  hashes:
    binhash: eec571d053213b50274cc9e7322c3d6e
    md5: 036c63960d76bdeb99bb4b7c17e8c234
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b0af36798df857f40216b47d275ed9df
    md5: 5d189bc0eb1e6ae6d9157091986aab30
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e4f0ad21440fc54d20f0c52109a0f775
    md5: 2d6872e0a8398640f9704f11e9568bd0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart369/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c0a109cae020200b30b0ea63b51f08c3
    md5: 7f3e79262ae6b6c60f2b129c9230f25a
