format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/atmosphere/restart_dump.astart
  hashes:
    binhash: 5db022107fbc7ef0c3b15a75dd7497f7
    md5: a038b719c3ffe37b49137c0299850bf6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/atmosphere/um.res.yaml
  hashes:
    binhash: ca552821785156e5668e0fadf290b838
    md5: 8bcf9bc2f1b0e3b92beab0dbf5446a63
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/coupler/a2i.nc
  hashes:
    binhash: 24ae902e2c62c8ed75847c12551e1bae
    md5: 3fc38fd0548a43950c9f35d7e4754d04
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/coupler/i2a.nc
  hashes:
    binhash: 116a982a1e045178cd35f07ef6dec499
    md5: 79335ce840e7bb458dcf6f9b3cbbf92c
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/coupler/o2i.nc
  hashes:
    binhash: b14c1f0e870c597ae59bc35d8da9b1a1
    md5: 2171ddb6b93f8d347ea7cbb5fff5ad95
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ice/cice_in.nml
  hashes:
    binhash: 42e73d18f7b23ce2cbb3f8b287908bf5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ice/ice.restart_file
  hashes:
    binhash: 0a687c1d75118fc31fe806d57ae9ca53
    md5: 8ce11065dcd1cb912315dade6912caf1
work/ice/RESTART/iced.0901-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ice/iced.0901-01-01-00000.nc
  hashes:
    binhash: 0487152e80bf5d07c6e9268f4cd40f0e
    md5: 719d9cd6b28a5c99c5a67cd3bacfd1cf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ice/mice.nc
  hashes:
    binhash: 09ead2d49dffddb443bcd77301eab977
    md5: 96995b01127a21eb4c7f9ceb14bd6d07
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_age.res.nc
  hashes:
    binhash: 866a9121ca40ad4893adb11968a0629c
    md5: 489b139c3dce84d768218fab80e1fb77
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 36ff7b2ab73ad3e822e1e18a102794b6
    md5: d9d9dc88dddfbe0229bcc0fdfb71eea4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b6990d2d82a4047f09fbe9251d959f25
    md5: 38e8eefba18b3b0cda6216dc77407130
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_density.res.nc
  hashes:
    binhash: af87096db7de042ec254f7ce3fbf422a
    md5: 75c281e2f2e7beeaebf42b255df1a746
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_frazil.res.nc
  hashes:
    binhash: efd1dea43d126752038b152715df4119
    md5: 4340fba58747d30ef2319735e42d0faf
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5ce3655f6356ef832c33cbdae66819e8
    md5: 7fc2caef5e5e9380b9ffb65189a6c359
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9ce582dd840e666ad288f8139508e0d8
    md5: 32ce55c8a0bd9223cc4c32d03b933419
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 856db74402108d479977ccb0f97373ae
    md5: 95559811deb9e9970eed4976dbd86787
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 3270349247ccb56a9abb17b2256891a8
    md5: 33dab7b2425d738c92de4aebd38684ab
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: db9c780fbe59eaaaa578a4be1c3daa07
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_solo.res
  hashes:
    binhash: e78073ae6a08535521a665cbf61b7196
    md5: 39d20fcb264c059ff11ad183c8d19639
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cf941af9ea1f54af26e615ec6c66f1d2
    md5: fb399d83cf3c484d3916c459a2327d21
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0b20074afed2de8a46969aa874ebf5d4
    md5: 3950dd7fb14e14704d4cfcfc21462134
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_tracer.res
  hashes:
    binhash: 0cafb3b69fdbbafe88ac413446806239
    md5: 98c63fed10a3021c85dd3a37dacdffbc
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2c2665a524ee7a90b599c1d9fec78de4
    md5: f2e2b3edb2a0c62fe082a1b6486e5de2
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a30744b2d6092862befc1f0f3bbcd219
    md5: aa9cf489edd23e0c04397857a92ba985
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: be98626a14fb29ab3fd21c20988415fa
    md5: aedeed23abc63c85cd3df66d4a774081
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart347/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 826049767f02b9ff301eb38b5d4dcfd9
    md5: d6f5b429fa561ed1ef6331e274d6eb51
