format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/atmosphere/restart_dump.astart
  hashes:
    binhash: f727412af331ae3672c7dc731bd353ee
    md5: 9af281343b76f237b50ba1e80fa3b380
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/atmosphere/um.res.yaml
  hashes:
    binhash: 3542769e1b310d0002fb36a87a2a1928
    md5: 180838520b82e00a33def7f055f14c73
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/coupler/a2i.nc
  hashes:
    binhash: a83e0d23c1226bae6e4ddad973e8f77f
    md5: 1c112ec258f953ceecc4c78fb260ff05
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/coupler/i2a.nc
  hashes:
    binhash: b8030ef2ebc7ac27be5506adb36f3cbf
    md5: db0484b042616aaafdea9dbd37137ea0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/coupler/o2i.nc
  hashes:
    binhash: 0d82bdce2d9f8a99b3395f007cd2ba78
    md5: 7e9cf8431e80fe92b75184e12829c0a0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ice/cice_in.nml
  hashes:
    binhash: a600550d0c212a29eca3358ae3b942b6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ice/ice.restart_file
  hashes:
    binhash: 53e7ce3723c8b8f0ad56ec8cc251e51b
    md5: 8a04d16b406dd2bd531ee9e934a13488
work/ice/RESTART/iced.1165-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ice/iced.1165-01-01-00000.nc
  hashes:
    binhash: 5570bda3eee69fc1031a911563d1daa4
    md5: 3a4df5f0c0e52ce6de26688333dd6b0e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ice/mice.nc
  hashes:
    binhash: 54d08bda1fc7b7d9bf21da4acc7830f6
    md5: d0726146f530894adbbd75e9f8488ed5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_age.res.nc
  hashes:
    binhash: 412531aef4f891b87d1866a604cb1719
    md5: 01527bd2b28c653215fb2fe27d64e427
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5ba8894885e7dc4af4931ead607931ae
    md5: b09d1de7f1ca8e6d0ace82bdc8044be0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6b442ce6091057fae06bcc8cf00758e9
    md5: 66f05793f66cc23a3f4ce3add74b38aa
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_density.res.nc
  hashes:
    binhash: 76ba4e292e2a36c7564587148085e74d
    md5: 55fbf0b6ad312245447a8c900cfff1f5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 100a8d382c2e0248bb66936adb450f4b
    md5: f83237af86693fee21818fa5376ed1fb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c761051875b02e58d7e7143dd9f3b0ab
    md5: d6adde91bcc49f77e4d6dc38dc0c1b6c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7368491eda4b4d945b6a3c08a48ce6e0
    md5: 3ef0f4373858ca8627e9d869f6c465b6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b1ce56d2080cec04d58b78ca4421cd57
    md5: 7416804dcf9b8de27dd354e7240408a2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 41d30c810d9994aae3fa4fcbe9816be3
    md5: 07e8315a285164f5df506d12f806b5a0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6cf34fc8a99d6b70d695e352a847cf5f
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_solo.res
  hashes:
    binhash: af0fb1adc3f88a413d2d8d9da345554a
    md5: 238fed9e32b89e6484fe3d86c3d2dac2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 21935c47b04adddd299a76355a033f8c
    md5: 20db65751ed928ca77ab1b8ee4889dcc
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 3a954d567249f4ccc41f4b5e3b003ac4
    md5: 00d5bb29c1c23f8181d304ffb28b9734
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_tracer.res
  hashes:
    binhash: a0295e221fa4e3d65505dbf37b2ce36c
    md5: ad676dd8baac2e08918c7e5e366647cd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 5708ef8c8f78c0d126652d5845b4e1ce
    md5: 486fd251251eb140fe8b9e480e1d69d1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7b9910793b7692cb0f4ecbb88c275992
    md5: e95a7707a6a3ffb73716b1f87f4134d0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 79ccaca7c263ac10752b576819f001a1
    md5: fe4608decda9829e8c11cf9c2c39ee63
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart281/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e9749b1dd969341230dbfb7b350f8481
    md5: d493fdfd4c05ebcc3fb64db62b4ac917
