format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/atmosphere/restart_dump.astart
  hashes:
    binhash: 67cc70e789029ac2a3a378ad7bcf129d
    md5: 61a76ca17e57fbb5b0e00766203a45f6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/atmosphere/um.res.yaml
  hashes:
    binhash: 34ed5500d3873b3bc3586abf49586085
    md5: b02fa2b4c956753d0060c26ea3d8b48c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/coupler/a2i.nc
  hashes:
    binhash: 24dddfa8362be097542e28258c51f3f7
    md5: 90c70dab938ce66df3660d34565bd6a4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/coupler/i2a.nc
  hashes:
    binhash: a1825a9df87e0f207c1178fcaf92574e
    md5: c74124c661b6cba34e0775b07f21c4ee
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/coupler/o2i.nc
  hashes:
    binhash: 4bb999fa213c5a5f4864a01c53cb8a2a
    md5: 443cd40994744a281ad38e56d920fed6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ice/cice_in.nml
  hashes:
    binhash: adf876aac27f4c73922be331cad0764c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ice/ice.restart_file
  hashes:
    binhash: d5ec2e83854b9ea93c11755ba4a590be
    md5: 5d8b10f4d47eef24525aa2f04c6cc60c
work/ice/RESTART/iced.1178-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ice/iced.1178-01-01-00000.nc
  hashes:
    binhash: fb7a0b18de040ad0a7bfa4eacdaabedd
    md5: 54779e663cdbdb5887bbc7b12cb2a281
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ice/mice.nc
  hashes:
    binhash: e0f4c17136382e51f37752e513df2e65
    md5: f053cf33c37172333ec847cd43915150
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_age.res.nc
  hashes:
    binhash: 92658517bb18ac94397a6dfd76403bb2
    md5: 873e6e0c7613209f6c413611a3b5f93b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 03887bfc81db4fafecaac01c265dede5
    md5: c239ab57fba826b181daa3cd4a1a6325
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 6eea0236db604e88cc3810391af26d3e
    md5: 0dad98f54324a7e22a30183daea10801
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_density.res.nc
  hashes:
    binhash: 8eaefbdb551b3551f19ed58bc9343dab
    md5: 5e2b3384fd8061ba6a0501636d87fb49
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f8d52f98ae41ac5ef754d3d86b566391
    md5: b50802dedb5846613b09013f584b09f9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2982965397ef78f466b819f1b154fca3
    md5: 992fab0ac1d7638585b2fafdb26ab44f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e5a60fc321ec071eadf2ee8ffbc80ca7
    md5: bf66dc82a92811f6230ef269d3375fb8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8b5548177dc63bec71e2698e252a18bb
    md5: af2dbfdb070d588f80c99fe5bddb2aa1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ab6e47d13134c7914d62a0d72d27c547
    md5: dc36f66de325229a2c52cf38be92d3b1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a202871d3e6c4ae0243a001b5ea67573
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_solo.res
  hashes:
    binhash: 0b84f5f8f6d310a103855e3f8a1180f9
    md5: 3d428b944a67fa307595cabb8b107185
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cc1f3b216d1ab98e5d13bb757b62b39e
    md5: f2974cfcc2c89423db856dc390951738
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_thickness.res.nc
  hashes:
    binhash: fa23dd87426aea68628a38a79ed4d9f3
    md5: 27034815c3f34d7901526f043d54de5a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_tracer.res
  hashes:
    binhash: a4b3c7e5e1bca84f87ad9c281e35cf1a
    md5: 2ace93cf46478ac7a2aa2d42eca34f29
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 16190604de003f013138b9a8c0f68926
    md5: 0b499b7fd9473e1cdc242d5eb9542321
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2b200faf40fde6bf10cc6941da707768
    md5: b9f5bed1e6952b631740c14aa5ad118a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 9dabd08cdf9f85a387fe1d172e046bd5
    md5: 312cc8815f69df275ad0cbe2ac0145a9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart294/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 24238237acbcc3ec42f3e1cb66b0932b
    md5: f157f273f5feae47bf4686de2a9db2df
