format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/atmosphere/restart_dump.astart
  hashes:
    binhash: 6ef8506fd1f889780679d251ce3dc169
    md5: f25afc701fc9ff0f7c192643d56319bd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/atmosphere/um.res.yaml
  hashes:
    binhash: 54831fec99dd387fb71b55f33278eafc
    md5: 4b3ad62780af617d98b5091055db250e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/coupler/a2i.nc
  hashes:
    binhash: 7c82419f65729fd51dda911fe978a64d
    md5: 324e1df0e5660e4f94858a9eb5793e24
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/coupler/i2a.nc
  hashes:
    binhash: 613c2adb8276a660f836249b43655169
    md5: 5b14df1543dd2dc2ebf9055a34fc4e6d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/coupler/o2i.nc
  hashes:
    binhash: c6d9b8d7dd5bd28730696058585ab5d1
    md5: 1dde1d6e1e520e8ca4bd0de61dcd736a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ice/cice_in.nml
  hashes:
    binhash: c5edbbfbc90426620bf1f6df57b29480
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ice/ice.restart_file
  hashes:
    binhash: 8a85bf7d5d2186de86e8004f1554261c
    md5: d5d16f19bdc8c3e41499a08a8d7bba95
work/ice/RESTART/iced.1191-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ice/iced.1191-01-01-00000.nc
  hashes:
    binhash: 5ac1a4da150e2dd0487d1ff80e0c3500
    md5: 0e4f651bc014f73e06829c01df0cf4d7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ice/mice.nc
  hashes:
    binhash: 4cfc383772948c083df8fd3c9d2fc466
    md5: aaef66ba39b6e0ac3ebec4c4b4bcf00c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_age.res.nc
  hashes:
    binhash: 50a98b98bfa2dfb488f7fee2e956cf98
    md5: ba84b1a105e4ae6e2c7ad5230aeecfe8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6aa4363600619011e5aca1ec6b8b7fd3
    md5: 6f807515c2a825feeed14bd88d74040d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ff54b0879d960e49f184ecdadaf344a9
    md5: 150b59186f3a5220142e45ffca5e1e3f
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_density.res.nc
  hashes:
    binhash: c9d4aa33fba147daf55be33b7d7c3f58
    md5: 1dc35a69fe29e989b807387cd2351f69
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 28ef9356bf2a0089197b7a87eeeda3b2
    md5: 518f19ec255577abe4bf53cf74b0a0e9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 23f39d0c8ddd3dcf07b7979c1e50104e
    md5: 8b11adf6c1560e0c84cb2c65a502f1f4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1d6794d50d69b68c61d04ca14b993bb0
    md5: f35683c38b77093978167b624ac44cb0
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cb9c48dba6d23e67f01ed36cd8012037
    md5: d87c982f24581a69ad0d24388c151a53
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2a547799023981ebef3119bef63bba89
    md5: 916d58435a9d7dd83f16c06d13ea9af9
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b41417aa4a68ad5679da9688c0343daf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_solo.res
  hashes:
    binhash: 9dc4f90a2e963fcdbfe6620b74102767
    md5: 525e1f2ab0c9bab422932da4e611be7d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a581ed4552d338786087279efffbe2ef
    md5: 2225d98e7d0482504076f6e73069f9ac
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 754b6f8bb77af906a7acd9003275c5b0
    md5: 8ea80cca9112d45658cd4dd9c7db3fbc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_tracer.res
  hashes:
    binhash: aef1601953650c71d5bcbd3ce9799fe9
    md5: f1fae6ff53395ee00220752522437d80
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 4861de592e2889a83950e4baf534177a
    md5: 7a34f1d1a6337d98d663b6f50694bbd6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: aeb37f44adf16f5a087ba3749ab6d596
    md5: 00aeaf078085463dbdd9c0953662ea42
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a2b4e012d864c222addf27bd74a9ba68
    md5: cf9a2dd95d8f9ee9b5b4b937cae83c36
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart307/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7877e273e078b29549facfe27cbce2a5
    md5: d4e561f880b73e0fb7c55c8b28132733
