format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/atmosphere/restart_dump.astart
  hashes:
    binhash: e8116c796b689ffaa5309546209a6c5d
    md5: 862d20bae83d9c24cc4cc9f2499e59a1
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/atmosphere/um.res.yaml
  hashes:
    binhash: 1ca3fd22ecc285661544f18c6ae7ffa6
    md5: de860063ca9d5c4aa7fec9ee264d4e37
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/coupler/a2i.nc
  hashes:
    binhash: 745683342515c7c7d5a9dbb0551b7ea9
    md5: 9c29819be87a7771afcb123cade41ab7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/coupler/i2a.nc
  hashes:
    binhash: 6a9bb375374078232abcdee19e7de77d
    md5: 5ee5f479b43d4f88d6ad312cd9aee112
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/coupler/o2i.nc
  hashes:
    binhash: 742b8aa86b67acf4caaa0a09ac1d7e61
    md5: e00be4a2bcac329e85acffd450231f8e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ice/cice_in.nml
  hashes:
    binhash: fce072c92fd25d8ec766aae76ec4638e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ice/ice.restart_file
  hashes:
    binhash: 43f9cf4bc0699ad33255f8eaeb2d1c45
    md5: 62920d9b7469f6323c88fedd7794b5af
work/ice/RESTART/iced.1795-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ice/iced.1795-01-01-00000.nc
  hashes:
    binhash: 7e7ec6cdb64401d4f898b7de541cb24e
    md5: c09e4555d90662e714230bb38f126b88
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ice/mice.nc
  hashes:
    binhash: 261ae782c4111e721cc86685bad9a63b
    md5: 9b235ee596415148687ee501caf0a6c3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_age.res.nc
  hashes:
    binhash: 7c33a0c5602b8d4c1c773c3f51ca6897
    md5: 22479526f023cf157c5ce230cafcc129
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7e4d7d26139e2e29f23e7a23962d92e5
    md5: 7aee2f00690da74269d26b5748c6b7b6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 0187b6e714bb20e85cf8c09a29e77655
    md5: e3650e0fbfc87eb724c03883629ae694
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_density.res.nc
  hashes:
    binhash: 177d98af71c4ff968abad15de9b11869
    md5: 45f1ac2d4886b5d88d3a4e31e182fe78
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 64173741de9fb49ce818eaaed750f47b
    md5: 0c9a029c89e7552bf924bbbe2cf8f196
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 037ccdc6159fc986739753f0f2d426c7
    md5: 66ea6293222d407ca2ac4d7cb4d65307
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 991b4cb61246e458ade3d95ef8bdbc14
    md5: 49b94d43b54a53c2225685afe7e487e7
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fc1e39ed0e923c5e175a71fa662fa68d
    md5: b0fcbd24bf97cc1fd49233e2e75cbd31
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 371b57adcd96a0d11709857651d5ca0d
    md5: c122075b134d998c6e60d198b21081a0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 60861c97dd5bebc9e1730ff7e8a53b52
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_solo.res
  hashes:
    binhash: 25682fa36ef89793fe485af6c826e174
    md5: ed139aaccf65cc1be8e6a9a7c6662d3e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7968f31985636e0317a6c41ce3d215fd
    md5: 04bb33f0a6607fd4aef212a286879818
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7e0c78488789781a04dd8e9d97b6041c
    md5: 1785ddc5c59245509c43c3df5e08c244
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_tracer.res
  hashes:
    binhash: 854be436006cd40a9bdcf122daa0de81
    md5: 3bc38f9f5beadb41fb7e33d6a46901e2
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6b2a277c4b7636c12aa65aa30f3bcd2a
    md5: b2bf7033fbb12270a2c3a60725e6c482
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: d4fc893a235242e875813924886af265
    md5: f05a18a410535ca29429768d7cad56a0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1f82b93366d69e5e22a8cc12db512dba
    md5: 69f8c01d380d07242c0fe00cfe4ac553
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart350/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8bd31a5abafca16860e06cea59e02c90
    md5: f3215bd553b5bb382b97c33b218cb1ee
