format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/atmosphere/restart_dump.astart
  hashes:
    binhash: f413023f48102e1ca1e6cbb07c043807
    md5: 179a95007409f94c34643ccc600db828
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/atmosphere/um.res.yaml
  hashes:
    binhash: fee1739dee466cfd5a96cee38c78d938
    md5: 16c55707a03af5ac9c6799a167161ca3
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/coupler/a2i.nc
  hashes:
    binhash: 6c14563b61639561357de964d12c9f03
    md5: a3f8bdd96c04c4c7dda74c1524fd92e3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/coupler/i2a.nc
  hashes:
    binhash: 9d087f6166a6a0b45455ac58fa0a9ebc
    md5: 8d236d3764d4c876b75f08ee1fb2b125
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/coupler/o2i.nc
  hashes:
    binhash: f66c8612a469f3d44dce413488ca054a
    md5: f6c52a37798c1c37f19c51f11694e4c0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ice/cice_in.nml
  hashes:
    binhash: d1be2853352183fe3ee2f22a2c76a296
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ice/ice.restart_file
  hashes:
    binhash: 6247ab16a4079117067428a44b93dadc
    md5: 14dde4d5af3d63104e430a084c9fdb42
work/ice/RESTART/iced.1277-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ice/iced.1277-01-01-00000.nc
  hashes:
    binhash: f8b16dade86b2285590f4d95ebd81bbc
    md5: 2573b395fd60fef778b2e4be77acef31
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ice/mice.nc
  hashes:
    binhash: 1b9ed9dc9d3e31885dcf495a99c3c949
    md5: bdbdde903a663967b177d1c90d7c29a8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_age.res.nc
  hashes:
    binhash: 7af31cd7a320daa727e60e298941d768
    md5: 60c11a76968be43dcd481f9cc49f0549
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c9117513297a04da188e324812326d8
    md5: 6829879b2a6ba6c168f91dee82d3c503
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: fc8cf4a35b92baae686687a11e6d82af
    md5: 0177aa83e926e846785174701d84d53b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_density.res.nc
  hashes:
    binhash: f900926e66f62d62f50a7650fbd859b1
    md5: 9db600ba4668d7311fbda8ad13f56d84
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d0ec41f61d454914cfe4eb638cee54db
    md5: ce3e679a7cac327e9f345f52a7a1bbb5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3aa8298c3d28e95941e957a1883a4ffc
    md5: c7ebabef23132ded91d2376f71cfce2f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 72dfa26b1f8cad129c9d2985ccb7da90
    md5: f7fa01118c07d920733ea9b235676cac
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 516196a711262907dd2ad8654dff3138
    md5: 4b43bf62f468905c0e8efb85c45b35c9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ce038a3848a875fda428d593f3d69d65
    md5: a0b8bec38964bddee111b6626b564f70
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 9b0751a698868bdae2741ebd7702b94e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_solo.res
  hashes:
    binhash: c8d3b10b9a769be24523cd360ef409f4
    md5: 06e3dbe301be34ad3a73a8c6dbc8f607
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 363faa11bd8c558f5e8f96d5a201aa9a
    md5: 6f6d23684cced2eb7ec01ac51a7f7806
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9ff690fb2ee0398a601f5f0678fcae95
    md5: a491dfa68f7e148c219ca6168506a78d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_tracer.res
  hashes:
    binhash: 4e2dd2e3b09887304aaf7b5daded4e2a
    md5: 1fe2bd4287a909932b811f841b32f85f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1abda0dbfa85607c457ac100828a6c4a
    md5: 0d363cf35a83ceba989232573b74872c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 694f5967fd3f0e93f7ddae583caab7e0
    md5: 1aecb339dd2e9e5c559321a34c99058b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 38373050fc05f13f214e31ecc226d081
    md5: 012d56404e1f354f4b5d97dd6880a42b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart393/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6800159e7f3dc38ba80287a2919be9a7
    md5: 6704243722b5db41c5c28033e6f59a39
