format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/atmosphere/restart_dump.astart
  hashes:
    binhash: e41ac141826f29094be06f0377006b7f
    md5: 277efbcdbbf96dcb60af8ae78e3173fe
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/atmosphere/um.res.yaml
  hashes:
    binhash: 56bfbd1779813febdcabf83ddd240942
    md5: 76d9d0c0d2f936c4ff7791397ed5b651
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/coupler/a2i.nc
  hashes:
    binhash: 555680db52dd41a0d3e00b04330b40da
    md5: d6207bae9267d78a1faeb68911f323ce
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/coupler/i2a.nc
  hashes:
    binhash: b33c1a3a6650cb05317df4ff5bcf3524
    md5: 7a6ed6c2162672490ddf3ea4df10e66a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/coupler/o2i.nc
  hashes:
    binhash: 0e58a475b169b5324f5061c6a8a74840
    md5: b7cdf641cccbe154b7353c3305cff1f0
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ice/cice_in.nml
  hashes:
    binhash: bdc97a85bbe84166af34fabd308d370b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ice/ice.restart_file
  hashes:
    binhash: 131b38da1c0d2fedab6685654adedaa4
    md5: 75f6110b6ea06e89a1d8c1eef311fb34
work/ice/RESTART/iced.0865-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ice/iced.0865-01-01-00000.nc
  hashes:
    binhash: 5697f5b5d2113bedb1de152b0e73dd3a
    md5: f35d9501c2836b4fa00ef8c885e57e99
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ice/mice.nc
  hashes:
    binhash: ee4783eefddc33c72ec3395a34f79056
    md5: 3cc532be157b81f3eae87d971c6b4b88
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_age.res.nc
  hashes:
    binhash: 1f91981fce9dac6148de072124eca566
    md5: 2415ff450680fbdc88f4916d88b8d10c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bb3c2886ed1cea625e3a934abafb95fe
    md5: 47d807d110cb9ea627d4603cadbde54f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c371dea18862486f4cb0f215879e4918
    md5: 3aeec68f97abf5f0670a07bf1cc6cf79
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_density.res.nc
  hashes:
    binhash: cc961a1334cbc2b7797fc8799e6b1362
    md5: 988ca92f6657bf5dff37b0223c80facb
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a0c5f85ba34dc402e572e862ea215cc0
    md5: 1981ea3d0b771f37eb17c68811ed6d22
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0713e49a953db60a96f42d8b85fb5932
    md5: 4f3ce424512006beea6f91fc6b9ade07
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 33317444977e6d2dd5dd4c7b58128d35
    md5: 1aa7ecd29c0aff7cb8634ae51147337e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a94bb53ec05c2187693a685405dae049
    md5: 9e20b92c07e2ffbac33c725a0615d061
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 66b7e28b717d2994ed39e8ad6ce30311
    md5: 34461f4dd163193443bc2e557e3f2206
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3d3c7625501c21620d85ecaa3812f712
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_solo.res
  hashes:
    binhash: da8d8af39d805a79d6fb6ed7a70b388f
    md5: 6b1a2f42c48789c458d6add86ba78abf
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 467fa2b2a498d1426ad5695f5b9d3c2d
    md5: a84661401747c4e47b15cfb7f56381a3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 8e3d14d946e836e462001492fb0f085c
    md5: 1e018dfd8c91fcdf3d1a93b70efa74ab
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_tracer.res
  hashes:
    binhash: aec7203a8f70959fbdef1bed1e507d14
    md5: fcc89b9b38ce71de41f4b08833ee2965
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_velocity.res.nc
  hashes:
    binhash: caf40c0bce65ddefd97395d3599e06ff
    md5: 04d5595354a6752a79bff9fa707e827d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 965c6de3682e49c5e28f758cc8971d84
    md5: 0d332394ecc52f412e22bfd7d45b0c56
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fda8c8d8457a671d837fe673d05606e5
    md5: 363e2e804d0b7f7da8110b4e1bb4540a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart311/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: b0da543665b443a2a41785064705853a
    md5: 00724b7f4d6ce68080214ea730289415
