format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/atmosphere/restart_dump.astart
  hashes:
    binhash: f945655dd48aed0856077a2539d3687a
    md5: dd88fdd070e5cf39f2c368825711e83e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/atmosphere/um.res.yaml
  hashes:
    binhash: b437d60978022dd696d18d0cf85ee6ed
    md5: 3817071c235ba60c0359a670e41255c5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/coupler/a2i.nc
  hashes:
    binhash: 5cd8551d933d1156c4b9e7c973c1e905
    md5: 99bf9579d9325593efe3bb61ab50659e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/coupler/i2a.nc
  hashes:
    binhash: 7ef39ced7d8f45f1edfaa563471b761c
    md5: d9ba290fe0ea8ff4556b6897da7642ad
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/coupler/o2i.nc
  hashes:
    binhash: 422fc7359eaaf5ce53dc66f407c3a19f
    md5: 236eb8d790f87e1e108e001a6b4855a6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ice/cice_in.nml
  hashes:
    binhash: 7ac14e40d6c1075bee477907462b289e
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ice/ice.restart_file
  hashes:
    binhash: c693458f4b3c3ea94c46c8f92dfc8a35
    md5: 5ccd983c5488bacdf74656473a60b49f
work/ice/RESTART/iced.1186-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ice/iced.1186-01-01-00000.nc
  hashes:
    binhash: d8f24cc63d4f53c2bda994983d411277
    md5: f3c23223a782683310dcfd031cfb6d26
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ice/mice.nc
  hashes:
    binhash: 00711e9d5ed88fcc09705883b1a2559d
    md5: 12bc858cebf1d14319cbb693cb1d96ff
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_age.res.nc
  hashes:
    binhash: d80fb34c91c06102bd3a16a3003a6959
    md5: 9ec6cc6dd9c700f1b73d7c9b394dde87
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1a6cc67f620a4be98a0089ab4f4231e5
    md5: d8194368373804724807e706d4d7b2dd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2fdde6ca6213d3657d476279f1fe4e72
    md5: 9727302c79912dec32589a8f6df4fda5
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_density.res.nc
  hashes:
    binhash: a9a8e499726928a80daebdbad1c138ef
    md5: 6d742982e12e64ccf3cded9022cdb737
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f1e65f235113c1ff5031738fb17434df
    md5: 88418647b45e759c240b6ed3c1f60da5
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 21dd4aa01b8c55916dbf96b111769697
    md5: 5356609d88c7a9620db3e03cb5c625cf
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_neutral.res.nc
  hashes:
    binhash: faab437c0c943603edf985a6d3943316
    md5: 4d5e96507926448662ca91bd766deec5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 17c89244d05546ecc24565c49f521806
    md5: 339bbc61a48d0a242cb9aadb7fcf13af
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 265b73d1763b1c9e56a16e6a1429b486
    md5: 88ce3403e8fe00397191a65663d7e29e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 522e3acabaad315f5e93dd83f387c018
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_solo.res
  hashes:
    binhash: b8bdf62846845759afc35bf65193210a
    md5: 5e62b0ae9e905dd96d9dd097d49f51cd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6a2a2c8edfb2367d05e057ecbf39398f
    md5: 3f4199013b7f26c30dc43af3d79fd16e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5cda1a71bed413adb84472540a355243
    md5: 815612dc3820df6d3d202e85c6733df0
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_tracer.res
  hashes:
    binhash: 390e8c9b670342faff274a973e8dbedb
    md5: 510f7cf8dd97e4a35ae8f3679b54bdd8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_velocity.res.nc
  hashes:
    binhash: af8f8cd885d0999c8e9d0c20abd0336f
    md5: 90d6789a0abe242567680eb3d7bfa00a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bac09b873a3fbdb9357ccdea994f0c02
    md5: eda7420fe01bb3dc6c0a2796db7ddd52
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7b0f176d24a81273e37a10cb7300fdfb
    md5: bcf7765509b8f764f69b79a2d66d107b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart302/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9ca9b50f12b7d00e51de0f3c4c55c095
    md5: 4c8516b2019aa0959a4209683a4054b6
