format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/atmosphere/restart_dump.astart
  hashes:
    binhash: 83dfad740444d7b91d086688dcd1829d
    md5: d47b818c97227e06242b768db084378f
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/atmosphere/um.res.yaml
  hashes:
    binhash: 34029167a57d0d8faa3ea0af4ba3850b
    md5: 6d7ca491c2c8b91ede6b3402e4160ce7
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/coupler/a2i.nc
  hashes:
    binhash: eae75423112432b02bd8a429ea19eefc
    md5: 4f39ee77db42323c22ab16d6b6b8f5f9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/coupler/i2a.nc
  hashes:
    binhash: afa3390b46accd12544ff9f9ef29d883
    md5: f3d94b837831b92d0a804fd23d0ce4be
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/coupler/o2i.nc
  hashes:
    binhash: 4adacb1684ef2911c0f7144c33022298
    md5: 4c88b2048f7209754a0baf779d21d6ae
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ice/cice_in.nml
  hashes:
    binhash: ce9e19dfd26f0a5643d31c0f97cb7f53
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ice/ice.restart_file
  hashes:
    binhash: ba673558a746da4fba469817659b32ce
    md5: 6601df4c58d16d46dda3a462c993d881
work/ice/RESTART/iced.1202-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ice/iced.1202-01-01-00000.nc
  hashes:
    binhash: 99ad215c4a8697aa280f3409ef468398
    md5: ab442303d6185b3658e9861e2fd60a71
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ice/mice.nc
  hashes:
    binhash: 55da742b597b46e6128d61775db432d4
    md5: 825a97730b7b4f17e0437e5e1e87db51
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_age.res.nc
  hashes:
    binhash: d383b40abe20d0ab2380eca720714291
    md5: c2abcb7b63d4501f5a7278e4934cb12c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 22c4c92914eccd004702c34d35d5b3d8
    md5: 488aac1682be637da981a54602259a03
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8696ec59b398057708b61a5e8fa01026
    md5: bf3661fb34152c592ed96a5627a953db
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_density.res.nc
  hashes:
    binhash: a55246850756d96e751ca4699c34bbad
    md5: 0a8d427c54caa27f014791d9eef48d8b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b0edf32a17010d683a1259c0cf8afbac
    md5: 7822eb2527a8e8d993617b8a5ba475ca
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0dd6e2a147125db92727f5159a493044
    md5: 51278a977f1b68bb1c4684e7e1fec811
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a3fd5462140a0edfbd8aabde35aa92d1
    md5: 78697d02c5affbc99c4f6b54a83ec83e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 88027dc64cb7d108dbfa680d61613180
    md5: ca29d207cc01e786360166a9100b10fe
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 87798f27d42ba48ac31c743f6fb9af9b
    md5: d7f31ce6522593a2b9aa11d48c4d1046
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 92349792ee0cbdbce0160a640caa8ab0
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_solo.res
  hashes:
    binhash: f220fd7e6c9ed56da4038fd91501cbfc
    md5: bc382fab93caaa1d90bb9a4f0aa01c1d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f7250ace5d21ed6f67c582868fb280a8
    md5: 39a5ab662b5cc1143f07da865d9655cb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 399953acd7d8eba6a68b220fe649fc42
    md5: cdd98fe7d77ce2e245d17f4febef4100
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_tracer.res
  hashes:
    binhash: db9c141c6cda8f9026223c0aa7cd82a7
    md5: 939e398cfce1bfd40b1973239e3f31e8
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dedbc7c5ecf8dff6a1a235317cec20c8
    md5: 4b683779599d4da0450e19332d680ac1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 846a07c442be9721d80815c9ac8bd200
    md5: 9b549493589924458d7260bb5b79df8a
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 08c41e5090ce2d97ee9e90f8f756fddf
    md5: d22eb5792ed0a02f53ac763d7f68c706
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart318/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4fbbd14733c19978ab37c22aebfe2744
    md5: f903172ce34f202fa25ee6f416d51ac3
