format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/atmosphere/restart_dump.astart
  hashes:
    binhash: 64aaff349c525c2152540475cbc2b57c
    md5: 55ef5c884018bd406cf7abe5112f7937
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/atmosphere/um.res.yaml
  hashes:
    binhash: 56005e4420edfd42ff0864507a54fdef
    md5: 2dccc5f34b47624b81951f85b962c9e2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/coupler/a2i.nc
  hashes:
    binhash: 671c822b7dbcab059d92e512b8314e40
    md5: 5abe77929e2b82f7b0b9188ea152bc55
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/coupler/i2a.nc
  hashes:
    binhash: d6330f365c3a49778f8b1df689b73a0a
    md5: 4a424018d929e979334cddfa2a022063
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/coupler/o2i.nc
  hashes:
    binhash: b1bfe246f865a98e36de7bc1add673e2
    md5: ca6090d2d63f75c0b61dd5c6e3727017
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ice/cice_in.nml
  hashes:
    binhash: 49e1f02be0d1851aef0b3c1836aab317
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ice/ice.restart_file
  hashes:
    binhash: ec95bffee372f5d4824cf2d6d51abb1d
    md5: cd140c89d98f8303196634ded001827e
work/ice/RESTART/iced.1754-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ice/iced.1754-01-01-00000.nc
  hashes:
    binhash: a94de1c4f557016bec81241ff11b3369
    md5: 0e847a1a4f7ac3c6cdc593bdc8c42972
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ice/mice.nc
  hashes:
    binhash: 0efcb4ac27f397e0fb193694a94e01a5
    md5: 30e1e03a71e7b2994bd0fded3170e28e
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_age.res.nc
  hashes:
    binhash: 86d90af85236b486d68dd2a58d1623f0
    md5: 3826c588dbeaa0be67d3a7464cae00be
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4684c88dfdb7c79916f9ebe99af64199
    md5: 0f8530a07ef62c28bb25da3f0d4d9387
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8bf3ce9806ade835eb4b55230c25f789
    md5: 22497ed5cba2e9b0d5651bb580ff40a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_density.res.nc
  hashes:
    binhash: ef10b93214d6bf785421f666576958e7
    md5: 64b109f384aef1ef7ddcedb31a063ee3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 653fada560bbb846b72c1df2d1bb9605
    md5: 6ba1557104ff19468ffbe0e8706dd97d
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2012de60a102ecd2f4e21945b24d33d9
    md5: 4fe71c8692ce4085421b24796ef3f855
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 894403f163d112ddb001423783365880
    md5: dde768a630c11ca1c5312c791f859d30
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 15b04cee5fa3fb35d310b3d8e2fa5b2e
    md5: eecf9a9f7def68ce7eca84dd88f100a2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e87eb3d79ef9aadfba8f3acf1bfbc387
    md5: a8b17aa4dc7ebdc2431b0f63f81a52f1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 439b3ea857ab73e698d9540a2972fcfd
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_solo.res
  hashes:
    binhash: 337ad6cc96bf7dd7799e5ec871335b56
    md5: 6ccf50d0e572189e2034def351d8c381
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 00824967b24bae25e457f2a68417d092
    md5: 0128aa9830c4be9378e69d90cfbb6438
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce4d27c70080c66dc3cd405736c13822
    md5: 595e9508b054be1799c18efdef4f5678
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_tracer.res
  hashes:
    binhash: 00819f65bf9097f9efeb1ea0d5dc725e
    md5: 40f4b32ab3dbb2d78d96329335feb199
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2232c5354f75cffa3883f345474ba043
    md5: 145a5e2c00664422d27c7fd3bf87b7cd
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 23412d1f6eda7cc3c1a1bd23cc33147a
    md5: 316890faf3221e8af135728b57b5d383
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2eb607b6817b1a06b35464b45feb17ae
    md5: c3c4f7498d9667b13a0b6b8f2aac3f51
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart309/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 05ed7ae04d655302c4311cb7cb33c3b7
    md5: 617898f3ea81b2e56df2483c96fe57f9
