format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/atmosphere/restart_dump.astart
  hashes:
    binhash: c8152ddec4e75cbd8265784a1ec5b80a
    md5: 632aa53d16d19282c5196a2a2761bc85
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/atmosphere/um.res.yaml
  hashes:
    binhash: 2e8e9385ae6f00cb0e774cdf5503ea84
    md5: e55a3a773458fd6b20777bb66a0e53b6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/coupler/a2i.nc
  hashes:
    binhash: 8c20d15e4c2ffa3dbd097c34fcbcf7cb
    md5: 116b09d8a3b3c47b9a0267dbe21b2e29
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/coupler/i2a.nc
  hashes:
    binhash: 8661c891d5f97a656dbb85dcb9efa06b
    md5: 4be63557deff539eb55534b7962d6005
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/coupler/o2i.nc
  hashes:
    binhash: f5db2749fbee38f8ba132ca75c7225c2
    md5: 1c5460aac6bf3363df3a1377d27bf890
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ice/cice_in.nml
  hashes:
    binhash: e2d80fb07194e37b723a843ebfa020c6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ice/ice.restart_file
  hashes:
    binhash: 44c1577a2c26d1525111a0b4c372ba45
    md5: 5e213d308b41dc331a576b9352836c1e
work/ice/RESTART/iced.0861-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ice/iced.0861-01-01-00000.nc
  hashes:
    binhash: c6565ada93003822e24703189836314a
    md5: 716a1e8df7c380c607961c8e0be992d7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ice/mice.nc
  hashes:
    binhash: aad8e9f11225204ac3a3f17db6f2c5c6
    md5: d611342c12737375df091fc7a17425b2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_age.res.nc
  hashes:
    binhash: 3566be09ce4c55fd11fefabdf0bb7e3e
    md5: 70309c23193ec4db38dad9a257527438
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8f404f46cce417f43aa03c303fe2ad4b
    md5: 2bfd4a1011d172cb31581640d39242ec
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cc776c38b5f7a7d7044fcabbe9ef0f0e
    md5: 26bbd6cf369397771b33a23a97e71c52
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_density.res.nc
  hashes:
    binhash: b18b05b77fdfe02b778cb871481271f4
    md5: 12d373d540674c058e14dd0b7aaa3600
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ce1b16da40a7f1f1cb048eeb3b271e65
    md5: 8d43cfad47162670be97f4c8befb831f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3506f2791fa9dcc09e65715058a9c480
    md5: 26b4a743f004c6bab374f1728628f050
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ba5d5b784046272ca1406b1203fa618e
    md5: ee1ede542cb2c092dfbf68dba23f22c5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 5e5d9a5db4b674739aaad2d2dd888b6d
    md5: 69acb32e1f6104ec8af7bdb0950317e4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 230384967847ab5a41c0b3a36e867e17
    md5: 4709ddf48cc1c23dc2eba0ad8451f542
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: e03a26716277a4ed2be1bcb61af482e9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_solo.res
  hashes:
    binhash: 63bf39886aa0e76de847155ce6d01ce0
    md5: 3fc523f90b3bad17f5eded799fe8d9bc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 20d05f44811bbe64c5a61d0f73fba05a
    md5: 35fcbe1cb4fd435ce98aed6cef577d70
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a7eb9bbd3848f833fb5e4fb6123485b9
    md5: 8a18f8b2df7cb1c8002bd5a65c161022
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_tracer.res
  hashes:
    binhash: 699ec92ff470b3668159c75e800a373a
    md5: dc144b16fd59ad15572d1eb6a94fc535
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1f5f224a4ce25d07ed9eeacd91bbd42b
    md5: 4a0ce84258bc00b6906292b2a8ea3cab
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 489b550ce3137fc97f717b7fc44d82fa
    md5: 44764a7cce0ff7b0571a7757ad77b291
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 6f1efa2db33022105ca92ce1b0140d5b
    md5: b0bc73dc6a11134a57d9bcbee30744eb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart307/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 674c2384d247becbe932007fb67e6a94
    md5: 06f5d8541ffc1d99e3b7a615132f2d99
