format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/atmosphere/restart_dump.astart
  hashes:
    binhash: 06a8486bf8b090f9ed8324fd4d8f79b1
    md5: 09e1c2e0260f48e7046707360da1554b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/atmosphere/um.res.yaml
  hashes:
    binhash: f13cd6fa121ff086d62569d9d0ba70fe
    md5: 026eaf2a8bc18c86d58ee4d27d536a25
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/coupler/a2i.nc
  hashes:
    binhash: 59453cbd0e76aa9443122f0959cfddf9
    md5: bd091b8708f368450645130d0b1a7989
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/coupler/i2a.nc
  hashes:
    binhash: 7af30594d23dba458cdbfe809c605e1b
    md5: 80e439bb2bc98ab780fefafcec7b1b85
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/coupler/o2i.nc
  hashes:
    binhash: 4c8c44a6d01edba2ed85774adf758fc7
    md5: 33a9c49450ce0d8aac66a6edd100a2ed
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ice/cice_in.nml
  hashes:
    binhash: e7a59f71a0f379ae9954cc3df7217e44
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ice/ice.restart_file
  hashes:
    binhash: 7e930b9a9636ca7631992fcc3af4c387
    md5: 4bcd2b33cc017c5d1e6561cb46faaa25
work/ice/RESTART/iced.0953-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ice/iced.0953-01-01-00000.nc
  hashes:
    binhash: da85ac6324b1c111e5ba905faf858a39
    md5: e6e01168aaa86505fa924b8c0a5422cb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ice/mice.nc
  hashes:
    binhash: 0e9ce36b3afe642155fa2f6517c047cb
    md5: adc4a74982e9d3581397a42c113901b5
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_age.res.nc
  hashes:
    binhash: db4eeae5990e84da4e54347b199441ca
    md5: b45e364a1c9f5f1c0b15b7f2b883f578
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2a9491a2f0b1b38ec72fafdade2bdf85
    md5: 58ffe87a49e96b4301d5c94c872e799c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 74dcdd408ab405cd38c4289ec7af5030
    md5: 64f6d8416970e9982c9037fe6e7492b3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_density.res.nc
  hashes:
    binhash: 23a8f191b6e8200c6459bca686b523d7
    md5: df36f636dc921e817e3f3a30e7f42cea
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e8936a3abcd973c060230e400660ad7c
    md5: 637a71b8582a17ac05bbee3c853306c8
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dc8c8ba8f71dfdce88d3bdd9c2635406
    md5: f00563dbdb2ac2ba7502c088e8611a26
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f24ba5a9b876d048fc35667ef69666df
    md5: 9d4366dd1a85d813f5d3f8a13bdaf3f1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7c5a71f39d7b4cd9b28ff092a964a53d
    md5: 855f1488d466d0ce76cd01f7bd2f89fe
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6c2b7a365ea89b5535315cf923278b29
    md5: 5c75e08fd2807ec1593960bc6a90abf2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 119bf94ff43b79db17282815fa4909b6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_solo.res
  hashes:
    binhash: 3c10e7d2dae59abb3f31053736bdbec1
    md5: 2bed8c7fb4c26a670840fdf0f9e883ec
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 369ca97dbaa82bd74e596527ece73da3
    md5: 50936c1ed1ca831aec80b5feef2ba7a7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cc67a14364a0fee5626ff45d5a919feb
    md5: 47dbf70e178136fc9aa5a14cd96d8490
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_tracer.res
  hashes:
    binhash: 2c042373662bb4e1dda1282a8f30ac92
    md5: 4499b8b34906ea43e862660e4795892a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6c69738f750b60d2f8ab5c449ab701ee
    md5: a79b1798aa1475ac5eee020b04f6d88b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7d491f5b0f7219478a041f3b7b6b3beb
    md5: e2cfe5c0f52244f60927fd3ae9f11c3b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: a7d9bda60f7d2b3cbf618d9d02982094
    md5: b3ab95572b4f54b2d6d6b2540a74764a
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart399/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e3043ea7f4c377288d5ef8c7703e17da
    md5: f44638c6b4d37f9bbc2d947dfe155beb
