format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/atmosphere/restart_dump.astart
  hashes:
    binhash: 5fbf1bf78fc23d203f284f099be48af6
    md5: 0c7c1ec3eb9c2d0e2b9d8dcc46670624
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/atmosphere/um.res.yaml
  hashes:
    binhash: 9f2e139600fb062d09232cebc388925d
    md5: ba7e92da24f70289ae38961590575526
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/coupler/a2i.nc
  hashes:
    binhash: d64b4b63ae7b78ff90f2da7794241883
    md5: f152c4f4a7c154c090a38029f8617c88
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/coupler/i2a.nc
  hashes:
    binhash: f2eed5ed8ad6a584a44c01a0cf24e879
    md5: acb63b9b537420d4b1d58e8df316cd76
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/coupler/o2i.nc
  hashes:
    binhash: b59c0190d36806519ac31bf5b2bd1475
    md5: d2a8a701087af68c2d82e965e1bc603a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ice/cice_in.nml
  hashes:
    binhash: d2501a8765301f6c90ced85cdc35fe90
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ice/ice.restart_file
  hashes:
    binhash: 19a1860f33c0fa9188416ae02905841b
    md5: f81ab888a69b3da2d919d4e1ccc0c26b
work/ice/RESTART/iced.1843-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ice/iced.1843-01-01-00000.nc
  hashes:
    binhash: 4e468b6c49be80bbbbaf109558b412f8
    md5: ddbd42b85099edf98c5ddcc796922e73
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ice/mice.nc
  hashes:
    binhash: f571124ca804bfeb3de00bd48ac376b6
    md5: 71f57dfc9f8d666c937e8837adc8f8f4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_age.res.nc
  hashes:
    binhash: 64fe1e694e8b28eff63583cd5f21ba88
    md5: ad3cdf328e32cc5c81908f8dbeb2c4e9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7eef1b79f98775554814b97db0998e6d
    md5: 7f18f48699b2e380cc99174a677b869b
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cb8bae5cdf904a19a15e237e062610b2
    md5: 2a06e50fecece89996e231199efc7992
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_density.res.nc
  hashes:
    binhash: 3b8a62d6e4bfe6da37a57a57bfb9da9e
    md5: 9bcd4a0aa6c0ff9b7c93dd0a75442c9f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d5caa56f286cd9746773876ff447aea3
    md5: 1f09be96e7f5f3d811e7899dab014615
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 97c3ac2a1e8f5fd8ccb112a63db27de9
    md5: d532abbd4b193c97ac5a3156232e6271
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 31c6bfff1ad8970417675edccd569653
    md5: 57bad66048dfa4be21abde26545f720b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4ed86b500986a88eddbb99d0a906e9ba
    md5: edbafbe32a3f18d6f10bce63fab87427
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 16992a2c80a8c6a3c49015e612331548
    md5: d165e796fadd3ecf5a2071b5676763db
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5078c1fa507fdd978e0b24848b967de4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_solo.res
  hashes:
    binhash: 8d8e9e8c1bac35540205b481b2b85843
    md5: 710d8ee95f3aa1f03768ab02a8412b00
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d355f60949cb93512eb168fde4057efe
    md5: 1b64bf098d051a36c8dafe3276659b15
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 93c9aa8c5dd4acb973cb7e6f2ba6b289
    md5: daf77e1072d0212eaf84dd78e8f91cd2
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_tracer.res
  hashes:
    binhash: c97e00004bf3d3e15192c0513fe58494
    md5: d908677a6ef7c8704fb50effe28578aa
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2ab12b125e96fc87dc283faeab3b57c5
    md5: f3e4d19da124cf8f38c185fb3273282a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 37114f993822a5c898e297d8913bcc38
    md5: 7eb2fe0820d5ca11df9fe160bc679096
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: edbe353aec30f0262e90feb0031baf4d
    md5: 79bdcc8cda1917f1aafb9e2ec292ded9
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart398/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: f8661f945bc17535ebdf52b8f8376b4a
    md5: 11c0d82fdd64420685d86c8d583bb50b
