format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/atmosphere/restart_dump.astart
  hashes:
    binhash: 37f0d0b4acc0d3bd6185cefae9090272
    md5: d27b1dec32707c4a359fb7810e0ab02d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/atmosphere/um.res.yaml
  hashes:
    binhash: d4266891054661c253bc2d13b652f776
    md5: f3d8fa9d39e0de514e50fbc63fa73bb2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/coupler/a2i.nc
  hashes:
    binhash: d916d9c9c1acef669b2c3cf8a39b7384
    md5: f872fbb7081ed99ebe09dbdda2c9d308
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/coupler/i2a.nc
  hashes:
    binhash: 83cad7d7f5467159da28297936c874d6
    md5: 40f17858b5e36fdbaf48fc592bafb3b6
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/coupler/o2i.nc
  hashes:
    binhash: 8d60a6eb96a298f60a481a1f6b4b6bd0
    md5: 9867e261713bc0f918822e41705ec4f6
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ice/cice_in.nml
  hashes:
    binhash: 0d2f9f74f54e18c755088a22bcdcc2ff
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ice/ice.restart_file
  hashes:
    binhash: 932124c3753bb040059a877c581ba447
    md5: 0ab8aa9b9622de931cef4c06cf858d5b
work/ice/RESTART/iced.1812-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ice/iced.1812-01-01-00000.nc
  hashes:
    binhash: 20e9a6f285d65bb51e397112d0c9f829
    md5: 21c62b0637903aebeea3185f21b167fd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ice/mice.nc
  hashes:
    binhash: 4ee3f6d9bc757f30696b63e87d2a77b4
    md5: ae243145c8e7cfc301c83d5165e2e7e6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_age.res.nc
  hashes:
    binhash: 4ba0e818b9611dbde642b98eadf7063f
    md5: ec7c2bab617fc063f37a6b8b920c2539
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c02f80a12710ad53bf309c513a7fe128
    md5: c7a6d36f000839f75515a4e290ef7ee6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 8c19f22ebd9f2da5e34e2c2d0485e211
    md5: fa27caaa1dea83b768852e438cf134b2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_density.res.nc
  hashes:
    binhash: 2ebe03ecec3fd990e335a4e885aca258
    md5: 1d1311328a66c0fb51bb3b8028b452f7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 1f87285be9a46779e6d325b643600f7c
    md5: 7a3bfd6ae315a8b7395650275754bde7
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 58c24c44898976954a6e7e99c7452bdf
    md5: 60f5ae47d3f87693c31eae21726af49b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1356d5a792a3576a13daf2007c302da6
    md5: b65cb0bef12d9d7d7246215c3a992cb5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a7599b83b0aa2cc74b13d23d0b73f54c
    md5: 8f4441f2c654c44d7b20633cef6035b8
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c3235e9696f61993b87b1b853f05858f
    md5: 71120cec0056db8c5132e85b222cedfa
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c0fa89df18bb7dabace3c30ea0e74531
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_solo.res
  hashes:
    binhash: de173a3c4d081db8420e73b6b0310d15
    md5: 4616d9da01574f4953550afca87fedc0
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: db7fe0b17a71a972c6257bfacd44c899
    md5: f8a9562a446f0646721d2d967ed3ee26
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7ec5f7d57f0e550c758fc246d680139a
    md5: 270d6dbcaf580c275f7c7edcbaac1990
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_tracer.res
  hashes:
    binhash: 383c3c8344a927faeb59d241b1db4199
    md5: eb20ca9d05c0e04b10e9e1fb1d851539
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 375787f59ae78c83894f1fe1bbc3e77b
    md5: 312182e356f1147fd1453d10060ab064
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 70b1c5a765f3b5fd1663154c0967fe03
    md5: 3abe8af27e9fdf7226e235571f2b9e2e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7629fcf5c3e1b4a82417dfb42c7eabbd
    md5: 99e19ac73fa2ff521566e16d13910960
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart367/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e278b6357f78efe1283c0deddfb0f93e
    md5: ea719ebe47b26531154050fa2f86bdff
