format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/atmosphere/restart_dump.astart
  hashes:
    binhash: 3b8c48be5bbff9b8f73fb427743f2b09
    md5: 50692c3a4ac337724e0afb755e11850b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/atmosphere/um.res.yaml
  hashes:
    binhash: ceddaa0eac5cb6901a558349cfaa8abb
    md5: 47035b8635d58aa0cedaa1dca2c3b1e1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/coupler/a2i.nc
  hashes:
    binhash: 6e2ab361153219d0f408be10c6828b28
    md5: c288b8a2357765a2699a19a5d2366bed
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/coupler/i2a.nc
  hashes:
    binhash: b00d728158cf74b97b9b052a43f7ebc0
    md5: 8db027958719583031f475178fa24593
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/coupler/o2i.nc
  hashes:
    binhash: c37d826386a6a4c05bbc220b01a7c0e7
    md5: 194a261ca57ae9ffb2dfdf02d1f77604
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ice/cice_in.nml
  hashes:
    binhash: e3e2d65026dc6e5172d34ef90ea441b7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ice/ice.restart_file
  hashes:
    binhash: 07f43521f84f0dd72a3442c54a165838
    md5: 583a1ecd0d28d39d09e3d3a049e0b24e
work/ice/RESTART/iced.0910-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ice/iced.0910-01-01-00000.nc
  hashes:
    binhash: 7171363b43e1e3761d38b6f44d56c1cf
    md5: d06bfc3c336b3377d903dc4cb6c80eab
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ice/mice.nc
  hashes:
    binhash: 94d82b89d8fb74abcf4c3b17c9305b04
    md5: 7b9eba26ee4af143c796c745991ac07f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_age.res.nc
  hashes:
    binhash: c398eded1bc1bcb106c19ab6fe86bdfe
    md5: f888a5ec6cecc176bdb7e78e7765188d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9e7515f4edb70f642ed3163b81ad8860
    md5: b4472fbd27871cd9b141a2bf9c652922
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ad0dbbcf72a437ee925a66598a7c6222
    md5: 424f5297d18f6ef942fe50e788d81f9a
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_density.res.nc
  hashes:
    binhash: baf8359baec0ef1b928bac7f259b4eae
    md5: 6df261ee2100b8e743fff333830afaf3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4935c8480539bef66afbd76bcca2346c
    md5: 32ea85ffe4407c57c74dabdaa069ae4c
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 190636e37f58db2eab3490fe1cfa630c
    md5: aa1fa7d09468f1b822018207111c6f8f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ff81bb69590612949d83c05937176461
    md5: 7b19355e8f8698393a6bb918540d2c8e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: daf342751a59d445106cd48b42295008
    md5: 7150f1c0f39fc9ad65a39a72b34788c0
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 586f1903e939d48b97ab53c3fa4f9195
    md5: 02ed86f98d12b0dd0901e961fe92bb39
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6f551aae98549dd6d17adc4c1036beb2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_solo.res
  hashes:
    binhash: 27439944c883d4acf3206a4aa437cfd0
    md5: 2e74421fb7a19376a954bbb04c767afe
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 141dc15f2c6d37f0ab935dd9365ff195
    md5: 38e1ea46e2044debc2a53f86aac0a3e3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 682efb7c5ddfa6aa0fb8ab73bd1f1944
    md5: 729565e5ce9fb3c4b340ddfd7caa90bb
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_tracer.res
  hashes:
    binhash: ba441a44f0294e0de88d9312c7c39e4c
    md5: c3f78645e1926b58e02e1a8cb61e885a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0286f0a2229ae0adb5d63fb128a44b96
    md5: a790e6d66edeac2794f1a5d5f337d409
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 8b74aadb917965d7da6de8a2bc04ecfc
    md5: 10662ac9392ac0b09f58eb569f44cf8c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 176334faaac487ee40144be8a2ace324
    md5: 932feab56767cd15b1d3c0fd936ffdcc
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart356/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6791e78a82a81cf02710ba7ebac3f92a
    md5: a526a2788cd8b0298c06ab4a23bf6b05
