format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/atmosphere/restart_dump.astart
  hashes:
    binhash: aadb32bc95e1c53362f85fbbf919cacc
    md5: c3869d2a5f25335cba11e99eb2db4bc3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/atmosphere/um.res.yaml
  hashes:
    binhash: a1522cdd44701f59b0308f4fc7697137
    md5: 28934112dadf98ee7b6a43da95de6eac
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/coupler/a2i.nc
  hashes:
    binhash: 23b3c8f70224579bbeb3fc395b5fb7dd
    md5: 6e1599ff5ad570669f0b62dace229403
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/coupler/i2a.nc
  hashes:
    binhash: f0fab4f3f5c56e9483ae26847b7df94c
    md5: 32169656fc896d368e8834d81a82b5aa
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/coupler/o2i.nc
  hashes:
    binhash: 208905797970b53ef31dbee820ddcbf5
    md5: a8b1a9be29935f47429c068c5a05fadd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ice/cice_in.nml
  hashes:
    binhash: 21fd6bbd0f9d67da5cb136b9fe8be045
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ice/ice.restart_file
  hashes:
    binhash: 02771544055457b9fe734ecb89a41a54
    md5: 12cc0249d54c2be820bc176c2ca38233
work/ice/RESTART/iced.1249-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ice/iced.1249-01-01-00000.nc
  hashes:
    binhash: 1fcaca91a49e3c18526ae554677fc207
    md5: 78163740206c62db13024ad7cca0641a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ice/mice.nc
  hashes:
    binhash: b55abaf5c5c927af73facbabff74b4f0
    md5: c9feaa6894759a024ae047c958c5e871
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_age.res.nc
  hashes:
    binhash: 36480388dfea039683510b83f1a69087
    md5: a9012b285fdf2f5e2ef34bce0fae269d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 8451dd1deaae368369009bd64410f34c
    md5: 3d48c4d60596e8f57a3878b7649113a2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e3a95973c345549e57a82ccd22ff9be9
    md5: b4543eccf3b3594600c969d0623df57c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_density.res.nc
  hashes:
    binhash: 89d3ef84f7f2eb2b55c552690c3d9257
    md5: f16cb02c12f039662eae566c3d69bc29
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b1e530e6e44fa2024b6a766efcc941ec
    md5: 79677859d38b37081ec47bc55dd6d060
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 11bc0e69cf67a29a5cf46c41b68d14fb
    md5: 774036ae7f479157c1c5ec503d1ee43f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_neutral.res.nc
  hashes:
    binhash: dbbbc18f75f8532b37d671a6fc1f5c5a
    md5: a8bbb450541cdea3f25cfa2c7c37cc68
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6c5563b3f31fca5819b582fe140dd559
    md5: 1a7fac87e96a902f1a7e44ebb49ea5a9
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5037b84b78b1bc51b1dee662d953cc58
    md5: 56846357271c68d2aaa664beea13b0d1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: fe9a6988ba326b3745a2729f114b90ba
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_solo.res
  hashes:
    binhash: 2ec8fc55f1aeea9feed28188b4d23388
    md5: a4c2f3bc310bc4b5e9f91900f7725cc9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a56ce0455a8306c176cb1a630b794544
    md5: ffd0ccd45a67fc3dbb7e0e3c071fa060
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e986894bd69ce23c2e555f585a32b384
    md5: 4c4a0e5c9ee9d712ebadb20d5455d669
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_tracer.res
  hashes:
    binhash: f466dc56c82b40a6b46f32dc16871938
    md5: 6ecdb64d3f56d9d5c890004977488926
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_velocity.res.nc
  hashes:
    binhash: d5cfeb94f76f4402ac1b071b5dc43249
    md5: e08efa1442832015c831521c9a406082
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 51a27e723457b7582dff81007fff6541
    md5: d918f9e7531ca64bafd0a9c910565b7c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f5e08ca1ecdd8b2cbfd10dc78fcc4fbd
    md5: b71450f4342ff0dff2b288af4df26677
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart365/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9d999583f53661b55c1307f71cca4a91
    md5: 2e5517ac0feec6123826d4f9ea94b721
