format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/atmosphere/restart_dump.astart
  hashes:
    binhash: c927dd6104279f2772035d7f26a0978b
    md5: da6e2a6db566b91cc776828b8977d209
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/atmosphere/um.res.yaml
  hashes:
    binhash: 876960b9f23768ea88c29df5fc383daf
    md5: cb16e11222c865b7e0e24db1e186a339
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/coupler/a2i.nc
  hashes:
    binhash: 85e5525adb81a942105ff088693248f5
    md5: 096c0eb047122e67d19e284f33fec18e
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/coupler/i2a.nc
  hashes:
    binhash: 58662b7bf423b189380d6f0adad59bd4
    md5: f4abb096bfe1e3046056b87da32ed29a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/coupler/o2i.nc
  hashes:
    binhash: bd67b5188e524c95f8cdf19d54d3ded9
    md5: 4fd4559ee3b00d98a637f648ebc90fb4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ice/cice_in.nml
  hashes:
    binhash: 3f50775e035ffc47af9403797f3418b2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ice/ice.restart_file
  hashes:
    binhash: e5b9f840b938ae7e8a5115d55f2758e4
    md5: deef6885be158850882172fab2ea49d9
work/ice/RESTART/iced.1722-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ice/iced.1722-01-01-00000.nc
  hashes:
    binhash: f9bde6d4361d28e5a8e9e1932453f3e0
    md5: 8bef1ca57094b4de6c665b826381849e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ice/mice.nc
  hashes:
    binhash: a383639f8f54bbe9c8ba0c056e94edb8
    md5: f0be8f36d8b96c1031a0aa8b34362289
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_age.res.nc
  hashes:
    binhash: c22c51d0fe8842f4becc4dd3b2de5fc6
    md5: c204a898b09311613b5d2b3d6f2b5c19
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: be94c2f8cddb3b53206badee5f165432
    md5: 0319dac0c1e91c4670e5c882f349faf7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cf25e38056a5b06468238ca23fc8fea6
    md5: a24d6e30bba157b76e6ed0a6efc005a7
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_density.res.nc
  hashes:
    binhash: 831c940f2cfa8703ac8c6d78d0f8079b
    md5: bae06eca53d0700637688ce6ebe21fbd
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3341afb4a64a3eb3b10ef1e8ff6e8661
    md5: 4d88e75562cae529d2d890c9354e778f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 38aa432d9640b8e7b07ccdb9e7d0be32
    md5: 88203c44fd56fbb5e804a669f20381d4
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_neutral.res.nc
  hashes:
    binhash: fb9178088ffbe33313d54b64ac74e69d
    md5: 7a249337d2480f26bdef00c5833a3cf1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: df8287bdc01467d7d00af0ac050893bd
    md5: 3e9d031e0f3b4806bd3dfadd9ff81152
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 9c7b7785055a6ce15de320581b9e23ec
    md5: 3a99cf1fdf335857fbc202b622350656
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b5fea9b21b115343aff546aa9c4121af
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_solo.res
  hashes:
    binhash: f21bf55456ba9e6de4b77c821dfde2f0
    md5: 9cfb622c5e0113ae924cc95977d1c53b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ccd2016c7c30437bc89c3cfaf0142de7
    md5: 8f24497f133f8896065d086a926113c0
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 095d5e674671260df45fa1070f8817e8
    md5: 926ce9adfba65e6c4f80595788ccbd1f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_tracer.res
  hashes:
    binhash: ed3a3a7c37dc5251e10ab5c2e617c905
    md5: bd54c63f69c715396768a37276d668b1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 1e40dd436faa3fe524f6c347a03693ef
    md5: 20ff5ff2cc8e29b37c4259d04efc1184
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2c668a45b8ca04f081d44a9c8964b461
    md5: 1c49d4caa1b6d25e631d9b583a933a76
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8777345b9acf091816edf988b370e861
    md5: 50edddb5082e7fe001fca6e7d240972d
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart277/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: baf58ca4ea06880b0c47815937a323a6
    md5: 1d052ed2bd74ccdf9fcdb8a2caef5873
