format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/atmosphere/restart_dump.astart
  hashes:
    binhash: 477735e0b0481a71abe204167b0b024c
    md5: e2362999a83afa655c6ebc83baccc2e2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/atmosphere/um.res.yaml
  hashes:
    binhash: 521cfa86c3904e4070647ce25a7ea896
    md5: b4c294c8c4d18cb9e480e0620d231c71
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/coupler/a2i.nc
  hashes:
    binhash: 680a3980efd678863f0bb885ac9cce29
    md5: ebe6d07d17895edde2d1897df6f8deb1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/coupler/i2a.nc
  hashes:
    binhash: 8642c8deb029194e6adf72d4f3aaba0c
    md5: b447b579ade5058232d01a8c3624b7eb
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/coupler/o2i.nc
  hashes:
    binhash: dce8ce937c88459d0dfccd912a855952
    md5: bf2b69791fa4600511b2aac528c9f7ba
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ice/cice_in.nml
  hashes:
    binhash: a74fd8354d1a5d5004996b35c6f56be5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ice/ice.restart_file
  hashes:
    binhash: b1b9958f3b1f2c6eca4237896a5ee7ce
    md5: 836764fccaac472b01d84d9574947c35
work/ice/RESTART/iced.1755-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ice/iced.1755-01-01-00000.nc
  hashes:
    binhash: 3ba3bf7e6a6730af4864ef3c75fda432
    md5: e45d63108d06d604a428e6e79bdec67e
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ice/mice.nc
  hashes:
    binhash: bb610936b95bbcd64d2d0b885ddfe5a4
    md5: 034b07a947cd25833122a565314a0e09
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_age.res.nc
  hashes:
    binhash: 0450e5341caf5f3cbe0719b72fd5eaf2
    md5: 35f156ed2639c69058d1e8632463b8e8
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 66bc352f885628bce560611aac8cfeee
    md5: 10bd46511d8764f90d1ec95ccc7e2f49
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a87471f4c27b88db20b5833ea0bd61e2
    md5: 704012b82036ce10bbf8ee3b757fd5f0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_density.res.nc
  hashes:
    binhash: 506d5749b89a35e6bc87399c1a4c5378
    md5: 8daa68d2f805e4cc45e3be4fc5d5560a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7b6c38db76c7d0d91d54571f7b1c9b80
    md5: 9ed63f7963c866a286f3572fd0c671e6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 628c2d86ea439cb8a87bcd0a75d57bef
    md5: 269668a014a5aa082aa124c1c593c14c
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2b184d3fd1dcbd32de4d9713fe005d90
    md5: f6b41fdd023ac40cdbdb88f77b53adf2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 6824c1b5d086caf404154cd0df305557
    md5: 060fae7677f99274b9f658931b7373ed
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2cb2e4065d3dd3e5bf201926f2ca87fa
    md5: d2a9e4345b76978aa1f8e6385ee72ebe
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c4226582b56d56262376caeb0eb03fc6
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_solo.res
  hashes:
    binhash: db3bc58093f3840694ab18081179472e
    md5: 695e59336d3b064b4948668debed087a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 83663e61f7711ce1d25bc06ae8d672c8
    md5: 888965f53cd7ac5270c78830cdf0fee7
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 25389d62a96fecb07bb70955c94e7fa5
    md5: 6a24669075a2f2dda3d3904deed15e18
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_tracer.res
  hashes:
    binhash: 91aff18c99673302ef27a507db680d50
    md5: 6eb87dc7d7a913edda1b34649c7ebe50
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8fb9752554fe62282eb4b79538f9acc2
    md5: edddba060b63fed7d79ed678367c8964
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55e8b4552e3d7672c5124031142baf1b
    md5: 41638a8121eb78f2a260caddf57e6cb2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 7d88edb5a2cfeb082e4b8f41115f140a
    md5: 3de52dfe2331495c6ed308948b208fe7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart310/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2342db294de22906049753d1a8aa47ea
    md5: b7f80e55b5b32bf0c7b339d01b8c46f1
