format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/atmosphere/restart_dump.astart
  hashes:
    binhash: 28fdf3fb49af52bf7ed97f3db5ed9864
    md5: 8f285bc2a172141fb64095e6eb292160
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/atmosphere/um.res.yaml
  hashes:
    binhash: 7d9ef2a5b921d4e6094b88418448ac2b
    md5: 82a63035c2472a812f6b6ce49ca3ebce
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/coupler/a2i.nc
  hashes:
    binhash: f56077d24ab750eedc9a8f03d746387c
    md5: 727a2241ac3015a91cb76b312cfc43e6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/coupler/i2a.nc
  hashes:
    binhash: 87ad056e578ff18091dec1d5ae154856
    md5: 4fe1204a7f6ed22e3ae956c2c2874fc7
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/coupler/o2i.nc
  hashes:
    binhash: bfef7fe74b9552708c5e8e6db8798ccd
    md5: 4836f3f9e201152a458ba9f46d9d879b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ice/cice_in.nml
  hashes:
    binhash: b9535894220d16fc2171ace08a8e7f18
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ice/ice.restart_file
  hashes:
    binhash: 56016b56cc9603ceb7a7aa9dbc111706
    md5: f1ad2118ce43231d811af8a06f020a85
work/ice/RESTART/iced.1839-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ice/iced.1839-01-01-00000.nc
  hashes:
    binhash: 0d285ee47cc369d9ebd5d95acf6724ef
    md5: 332733880af9908dcc53d0d61cd44d32
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ice/mice.nc
  hashes:
    binhash: 03063ee746164ee6aa52300219547f28
    md5: 5d8e8be386ce7cf409fd8a8f287cf908
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_age.res.nc
  hashes:
    binhash: 83e46157b5a1d10960375d99e28eb226
    md5: ac79abae87b897282952668d1f91f866
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: dd50e5a796836c236e82367976c0260b
    md5: d24f5f8ae5eb7b8c3fbb3b3cc99441a7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: a0c83b47d87d0ad28eeea3dc33217718
    md5: 0b8e0c533a8d4001bebb9210355479eb
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_density.res.nc
  hashes:
    binhash: 26163287796f0923925e505674c0519b
    md5: 37d9b146fc97399cf39365ae09f97a06
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 47f6050f9117479898d7fef9e8e33283
    md5: 04618b33c60385ae3acef761d5e6d717
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9c06157572a2eca9b7a8ae25eb2f3274
    md5: e8488904c33a6af6a59be8058a5bfce6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_neutral.res.nc
  hashes:
    binhash: de5597aad1463451e8e2c90c0eae5b9f
    md5: 12fd355bd65d3332154935f8ed62bb54
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f91e659dc4680877836cb0d5553b52e0
    md5: 12574fbe705e40daf5e8864c2d8eb65d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 37b8e8e44e22278e1e1ccbf74b5d8279
    md5: 6d537007f25ecc02a7a8c9ba2249ede2
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ea9323eb14f38daa287ab584802b9a7c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_solo.res
  hashes:
    binhash: aed024ebe4e0de474bcf1f675dc1cef6
    md5: f694f73933206243ff4de194943246cd
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f947181d22eb32005d8191a4fa8f725b
    md5: 6086aa98784b20f72a731753a1401861
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 740f65aaf80774870f206ca4e4cde108
    md5: ffbf812e1d886dc4c4875a30feaf4880
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_tracer.res
  hashes:
    binhash: 99527d82c8b0623b97078bf329b985aa
    md5: b68a36436153c7dc498a5bb3e4e3d3c4
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 79a52fc44de52e03e6756bb171341230
    md5: 87c9368630114ef0857f539fcf946b12
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 5372951926a48d889239333efeee1478
    md5: 8387baf1d965e72f5048c116cc9a7601
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e61d5229feb54955e180fcd04d115d58
    md5: 911096f56ea507d1393ddbb51cde5d40
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart394/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9f5dc2327c6579139a56d1e7de7e9116
    md5: bab3f2e34f7418cad3b6fa04a41bade7
