format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/atmosphere/restart_dump.astart
  hashes:
    binhash: fade54c4d917070be82e4f002c74ff70
    md5: c8138b77fc60fc6f25b14d922b603880
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/atmosphere/um.res.yaml
  hashes:
    binhash: 9f84e715a6fddbea48594ec326a28ec6
    md5: 4e7656668a37edd26cb4e939a3947789
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/coupler/a2i.nc
  hashes:
    binhash: 705a2706a8efeeda0b62f1fda2f3a150
    md5: 5afb333a274969d498594b46251a1372
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/coupler/i2a.nc
  hashes:
    binhash: da51ac7a9c0b42b4c04c61abad8e7f9b
    md5: 4f521c9561d7aebbeffbf6ceb61891b0
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/coupler/o2i.nc
  hashes:
    binhash: 1167e1933cce93253b41e450020eaa9a
    md5: 41b172e2e484bb6b48eb3dc4919f5c7f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ice/cice_in.nml
  hashes:
    binhash: bb66d97df48bfb41d2fd988fa034a60c
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ice/ice.restart_file
  hashes:
    binhash: b1e069819b8b78f57f491a829f9cb51e
    md5: 155f2ebe791c54354200443dfec14594
work/ice/RESTART/iced.1712-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ice/iced.1712-01-01-00000.nc
  hashes:
    binhash: 7cacc71f2c7cb498ffac6905331a4e2e
    md5: f088cd45903a2835d37e9ba729812f9a
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ice/mice.nc
  hashes:
    binhash: 27b4b7f78105a4cbf0f702eff9257fdb
    md5: 760120ff73c7019b02e1a852b9ce5451
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_age.res.nc
  hashes:
    binhash: f8fcc6fe0ab6e851cc9c6fcbaababef1
    md5: 0baec43b9a026506d01cbaceb03f90c6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3572227707a11a8acaf93d578619f165
    md5: d35e3fe9d1f1430d2eb28a8b2dcfb14a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 429acac2bbde4f3084b042843428d280
    md5: e56e5f55aa368c692f0723bb6f3ac9a9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_density.res.nc
  hashes:
    binhash: 5135617d86d7bb25daa919edf3f362c8
    md5: 837ee0c11c50f93a79520c5df759a319
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4ba39d1ddcbb86ed7c1f76bc3d0d6f88
    md5: 3b6a8a1ad5ac622083d1adab5eaedd5b
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: dd6c97e8cef35ad1d6afa414484523b4
    md5: 05f8f3bb730606a67887d47fafca1629
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a25bc072f5f7c6b5117b9aceeb4fc51a
    md5: 6fd4873736be912d0f6f58102ebedf38
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fd316e77e6cc4fa5e1ac9753a67b3ec0
    md5: bd6ca1422f3677970e1044df80eee917
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c38f0ac4e332ac69b733c46c7cd3d321
    md5: 6bdd46bdfd8f95bd79d32a79bf52bc61
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 6a5ebbab1e7de12e2c56bd1aa8aca6ab
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_solo.res
  hashes:
    binhash: 4c86f5701df0052c33a460c2c24c075c
    md5: b973f74dac08db570cc4a4c1010340dc
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 92182c75ade4633fb018aedfe054cd73
    md5: 48b620a13ae5ceaaf657836d5d775d81
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9567cfef568ed9fde328086a9356d57b
    md5: 3c6b987445113452a073e0cd1f1a4173
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_tracer.res
  hashes:
    binhash: 9d2ad75e918ec0f66276ec1b8a6f7783
    md5: 4728cb780f527c03da310ef474ccd319
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 127e4d16e61271a6d51ffcaab856a9c7
    md5: 883aac4e6e39d44ace5d85b1ea35d4eb
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a4e08de55ea1a18f1e5d43d61c92f727
    md5: 613e5b7b6518c965ad18d1b2c9134221
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4bad2b4d7a726fef699d4d4826dc7029
    md5: 191f588a1cbdaea3d5151dd99bc4a56b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart267/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d78e30542cd157eebbe73a50a839bdb6
    md5: d99b660fcf39b742a170788c1c4ffb18
