format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/atmosphere/restart_dump.astart
  hashes:
    binhash: 2cbcf228caae29899fadd08f3bc61d4a
    md5: 5182e44eeb99d92ec76e8949e0b640d6
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/atmosphere/um.res.yaml
  hashes:
    binhash: a3f591c9c10910bfbe1857aac213f64c
    md5: 8c135496564d12d73833793eef02f5fa
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/coupler/a2i.nc
  hashes:
    binhash: 557a2a80a79417ca7a6a49c6374a1e4b
    md5: 4aa36ec2eedac2ea9773b0e4eb825d71
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/coupler/i2a.nc
  hashes:
    binhash: 8ad180ee1b174edff7807c2aaf9ca0bb
    md5: da3283662dd8a31442bf981a98851942
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/coupler/o2i.nc
  hashes:
    binhash: 01a89807037cb56789efb27b4fb14127
    md5: f859c5ab08b13ea9c4027922bff7349b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ice/cice_in.nml
  hashes:
    binhash: 76e509a17d366f9a2426318e43319fda
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ice/ice.restart_file
  hashes:
    binhash: 6730c7a269bea4dfe7909d6c8d1da396
    md5: be9ed1e457cc2805ef51acd487d593d8
work/ice/RESTART/iced.0947-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ice/iced.0947-01-01-00000.nc
  hashes:
    binhash: 1e07de1bb38b49a628e98acf0ba9f751
    md5: 0a1e64bca62d09ddd2a630a212bd8b1d
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ice/mice.nc
  hashes:
    binhash: 29e8525e73bd37d9b5ec372a0a9bf945
    md5: 69d36af29df192be4f3d35df82bb0300
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_age.res.nc
  hashes:
    binhash: c78cc5eae64364955e54fb8bc8ed81ea
    md5: ae4abe9b173a1b8510b22b55692cea9d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 22dd5e96bd2f022d2ec8cd21b00c63e4
    md5: a91c8da67f58b85341d280f4d8a78baa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 905fad48a47237bb1e40677185e20bd1
    md5: 1c5b5dd03d7e2b90cdcf172dd3852504
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_density.res.nc
  hashes:
    binhash: ffab3a040e19edf42605efdcd47bae3e
    md5: 0df42483b74ff66275ee3d8e1c2487ac
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 484929edb5d343453597cf8f413e93be
    md5: 4f573f89e116c1e6736a0e484981918f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fd679928d9f4410bef3a64cf42a28963
    md5: 4b452878d64985319435e524b519baff
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 808f156e3206f39493f7914306024d1d
    md5: e69808f484ebe21516d07b71468139a9
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c30fa840a54395e82f15a5a4e6fea3ad
    md5: 04b527c0c04861d2eccae205f60ac904
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8b4384c77cc5cf24b02bd5f4e589cd79
    md5: dbe62aa696ae1c39e18e50508bb08d10
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3ea1a9bd6d7612f4f89adf4f48929daa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_solo.res
  hashes:
    binhash: 55b8622fad0e3ff77595b3fc53d317b9
    md5: aa58f4367813c257e2014fb7846fe411
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 81a24487f0d76e37f261fee2aac1927a
    md5: 0c6e25c997d830a73ccb7ac5542f1400
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0341e204084fdc22602661e9aa557eb2
    md5: de322f2fa239fe39e4d918402e37a2ea
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_tracer.res
  hashes:
    binhash: 63c281e5e32f51c585dd89036f844cb5
    md5: 5e359b85cf04f480d4891610f0968d86
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7469076c83ddc9b8b2acb1e485b2b1a2
    md5: 834ef93d46f39df36ff4aff1886b51ec
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 688734df5fbc2f92bd86d247bb404600
    md5: 8f858af02d17bd21c50061de5e3c146f
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 2ce45dfe6cb83d5545bac68f4eef4796
    md5: 7cf792513edcfae5c68252b970af51eb
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart393/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 154ab3cccecbaec46613d8f12840efda
    md5: 1b1038b8c36ab626c68271ca01800815
