format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/atmosphere/restart_dump.astart
  hashes:
    binhash: 69eb212ac0b57e5a22703961ed30dde4
    md5: abd10c0c83ae33a5bb1792781cecafef
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/atmosphere/um.res.yaml
  hashes:
    binhash: be8105184b4a1e8893fafdf0b5710f4a
    md5: 20352dae133865b41eccb61d91ae77bb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/coupler/a2i.nc
  hashes:
    binhash: 4111d7a666c334922b6e50919752ba20
    md5: 1d94cd522e29b67d60f6158f4ad7d73a
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/coupler/i2a.nc
  hashes:
    binhash: 28d71c2462414b485124c47b2881f7f9
    md5: fbeb31fe9e7d689ccee6d3c3ffbe5723
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/coupler/o2i.nc
  hashes:
    binhash: c849c28b15c49395e4a80dab07d2caa3
    md5: 1b49423de7286435b2d99179474f9a9a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ice/cice_in.nml
  hashes:
    binhash: 0c7285792982dbca4845e4c56c5268a7
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ice/ice.restart_file
  hashes:
    binhash: 572c84a551b4e7a6e3664d0b04394146
    md5: f681b7f47d8f8b3269fee04b8f8fe34f
work/ice/RESTART/iced.1742-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ice/iced.1742-01-01-00000.nc
  hashes:
    binhash: 1d07794c7175cf728ee58ccda5c52ef3
    md5: 225d6034edbd3ea9453fcd7ab982872c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ice/mice.nc
  hashes:
    binhash: 55ffc221e6cc67bdff8e711add5e029b
    md5: 74b7715a58d80f5de9d32df5942f8756
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_age.res.nc
  hashes:
    binhash: 65f2890ac07524d7bb4bf54ef9160d5f
    md5: 7cc0b337bfcf5f0337bd357e8af72f91
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d61892d45c8b790abd826815b17ccfc5
    md5: a5d9c65b4f044ee06a02a5c3ad93856c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 4f4281d4abf36f3c9a68496d65d4a256
    md5: a908e0fbce83d993d68e12c405ef4a8d
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_density.res.nc
  hashes:
    binhash: 867ba7db670c138385354d3bb9b15e81
    md5: b11c485ec1685ae5623777bc22787681
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 698f9ada105dd3d8bd0ac71fdb888d34
    md5: 7570543512002359cf02f80b4baf00f1
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 427c6b29fe7518454dfe529bf31ae350
    md5: f9aec234a906ddc12736bc12c42b8c6d
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 718d921cefa49541ec5f7c3647c2a5c0
    md5: e74a6b799aa324e44c02941150939c60
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2caa5358e5c0ec152f4f3d43d02815b8
    md5: f2f3a007376eb2bd31e44764f8741cc2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b73d01d58f6c1454ad32e952d1f3e7e6
    md5: fb18e48b3b539c353e62203d5e645e74
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c0c3cdd6d2b7fa06dfd89468d4a4b0cb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_solo.res
  hashes:
    binhash: 74c55657925ff1ccb593fc6f608eb2f6
    md5: 27b4c3c331b775ead47424ad7800cd2e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 517a35d9b5d79c892fcb0a72d751ada7
    md5: 28c57d777fdf8239b7a257fe7de54fbf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 56c0e6207ab3df8f90b69a4f5bc4a767
    md5: a0a5b15b4246506c7540224846351b71
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_tracer.res
  hashes:
    binhash: e67166a4959e96f273d6b19459d37e42
    md5: 8c305f0b64db423fefc08a9bd61ce905
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2135c0f1c012f5c39f27c960958dd337
    md5: 5200e910ed97beeedc084a1752dd8910
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1c3ee78319ee490942860fe7849c6aca
    md5: b6f786d394ada798aa7dfa89ad6b28bf
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 36d2424a7d4584d65c0a83d3856063cf
    md5: 10f6d9bd49f4b7d323e47b0e879692c7
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart297/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: dd4dd7d58555562bc7c7d57508b20721
    md5: f832c313f6d1aa308bdfd3cd9cba67f4
