format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/atmosphere/restart_dump.astart
  hashes:
    binhash: 4c36bc811d28d92b19943b993c53d18e
    md5: 42476f58066ebbf3c793c95f912e568e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/atmosphere/um.res.yaml
  hashes:
    binhash: 3400abfc783679a59374c4d76d26c226
    md5: 717a26ed8b26efb4c534c9e5e8bd2856
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/coupler/a2i.nc
  hashes:
    binhash: 5db192fda2c2e545e127dd32d1c1cfc7
    md5: 03179badc697b87f340f0e370eeb604f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/coupler/i2a.nc
  hashes:
    binhash: 66d63fca240b8e7317ba7abb432803af
    md5: 6540f9de432229f3abdeee8048838432
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/coupler/o2i.nc
  hashes:
    binhash: ac28fd3e4833724c4b6515159702026a
    md5: 70f5f12d1c9e96ab29a74f6a1686c8c4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ice/cice_in.nml
  hashes:
    binhash: 9a464aa5a251fbd598dbdd3effc8f52d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ice/ice.restart_file
  hashes:
    binhash: 6d5e1a3af6ac5429944baa01313c6d15
    md5: f549f18b9eba2b634ec59253adfa5d1c
work/ice/RESTART/iced.1258-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ice/iced.1258-01-01-00000.nc
  hashes:
    binhash: f6176de91749dcb8a9696c339a88155a
    md5: 2593fe3da32c1a1bafad3c5b8e1a93f2
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ice/mice.nc
  hashes:
    binhash: 19a2f0f347906f0f2b133af7b2efa6dc
    md5: 9dff5e69674b97f4198e7e3b0c28bd3a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_age.res.nc
  hashes:
    binhash: 63e2dfbe4e05bdb18e149fa2a9f835e3
    md5: d29a8828ab8c5d1437c40befc2c5e4e4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 249a759d9f6b0b6c1e8d81334a0e4d62
    md5: d78cbcc7412b119bb68fe088c169b3ea
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb40a8faaf9f9b2ba3b20e75a58240f3
    md5: f54471c06a12e68eae83f67a5ff365be
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_density.res.nc
  hashes:
    binhash: b14848eb381227b3aee274762a0ce706
    md5: b1130d4e3eee5b62b51cc3ee9d1a44ce
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 715fb7b2ad9305cc6b3e15c5facedadb
    md5: a0e888006c485ebbd44f79a274c29c85
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 22cfb8368f0b29044cb07d4c0567a066
    md5: 48a7b569406deadf70751efd1e33a515
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 50bc35201b0e693c4c62fddb5c7685c7
    md5: f4296fd25ca3bbf6dbe4f75ba6cfc705
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ec2056f1fa360a518cfb406a20fbdea0
    md5: 650a5ced65c8e02bc9f777ff0e9e9d7e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1bdc3d5bb56c9601f6cbe1fbbd754ef2
    md5: 7e2509f69f90f10a1ec256d053ef1c7c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 0a52534d996ccdf733d906ea84eddb05
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_solo.res
  hashes:
    binhash: c803b1bcc3a3124562756717fd71d321
    md5: ff6070b5fd886b3ed61a592172bbc7c8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b4b40b809ba5299b67825b4b60bcd0cb
    md5: c06d9ed034b9a08597ad8df4a4306667
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_thickness.res.nc
  hashes:
    binhash: a7d511bfad024de7a0728415296afcbc
    md5: e5d612a6623b61955b23b162166b76aa
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_tracer.res
  hashes:
    binhash: 8a464c373946cd4fea65e9d06c91f540
    md5: 8fe5d36c9c157991bf4f66822d2acf43
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7cbf5e72c039e3805521260ef7ce5fd5
    md5: 09fd95983d727e7c16be626d5e47ce76
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bc03a0e5749f814b118ca758daec4881
    md5: 4e7d0ceae9268520c986930ddde62529
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: de091d92e17627a53e170c4cc48d484a
    md5: efc4c296db2aea150777dbd4d3ce9149
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart374/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 16ab9a33c987ab43db74f4457fcd8dfb
    md5: 0b5332a0ff6cc6848805f59273e904c2
