format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/atmosphere/restart_dump.astart
  hashes:
    binhash: c4ed46c5e768fde2c2f9e3b2076d22fd
    md5: 6f20ce1f02f6fcb4cd3b785476fbec49
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/atmosphere/um.res.yaml
  hashes:
    binhash: cadb3ecdb4509cee4a0a8d4f273f0f9d
    md5: b59ec40105cfab96a1d817e67650d061
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/coupler/a2i.nc
  hashes:
    binhash: 70575b567f39f78a1bb3ccfbb6c75a37
    md5: b44b7c43cbf383312b60502efab984d1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/coupler/i2a.nc
  hashes:
    binhash: c1c70b89d0266081a90d3c1121cc33c9
    md5: ff7198f8a647ec4ee3959688c6e880f2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/coupler/o2i.nc
  hashes:
    binhash: f593f6edda83d194f03819a5734b5802
    md5: f573646d1cf8ccdb5f1cc906f9a6429f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ice/cice_in.nml
  hashes:
    binhash: 4122c2838217f799e1d6477050c5f4df
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ice/ice.restart_file
  hashes:
    binhash: 6248f989e8e550688453eda42f41d770
    md5: 820ab0f22528ff311e6ce639e2a3d406
work/ice/RESTART/iced.1172-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ice/iced.1172-01-01-00000.nc
  hashes:
    binhash: 4fc21b7f3d8f30291e417a019dc229c4
    md5: 67f0df71471a42469449197bd95880a1
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ice/mice.nc
  hashes:
    binhash: 40958c4cad30382285f3aba209811523
    md5: f94893bdff549a7992c7d29ea1e0389b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_age.res.nc
  hashes:
    binhash: 151344625457d42f84d3f7ab440591ac
    md5: fe6beb6d2028205415faf35492120f8f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1eadaa1728d1cab21f21f48b36cbaf98
    md5: cc43f44fe77226625be509acdbc2e2f1
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 92efa289bfc79a61e854e46ea4e9fa00
    md5: 04a9e84ecbf9f212ee89ab4038f870ce
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_density.res.nc
  hashes:
    binhash: 386619fc6a244a54f472d0ff40ca1d91
    md5: 91765a7787629bda2e3f6a26efbaf3c3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 0983f3cc6c14ace39e9cc880c9fcb708
    md5: 029261ea4a41d4084a1f6b0303e659fd
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 869ba81d1906a78761ad94e1457571fe
    md5: 57aa61f0a581012a0eeb2f4ff452bf27
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 19003846833e3109728870a3d68b80f7
    md5: 3fcf357c4a9bcf64d5bd8a7cde0162ab
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: abf62bf5be309bc6e1c56384a8ae8fb2
    md5: 25735828f377c52efbe20225d7e5449d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 47a82203bc313da642f3bea4e7acb3fb
    md5: 3e136d6a2e5a1e0756422416374c6830
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 16a7f86774e8307fcbc6ff9bef41fef2
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_solo.res
  hashes:
    binhash: 94c23290236d8819fcec11a3c49e4578
    md5: b49402d29334ce772916b7f0aa90e3f2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 44927126c4bab5476518aa54b8c2748b
    md5: e74ab975822335871ba4d5623a00b087
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 26cc95e3cfbe1f6fbfc33a89bb778e00
    md5: 486591ab49232346c0a5e93ab26b71fd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_tracer.res
  hashes:
    binhash: 5b8cde88b586f4490e7eb8b667edf1cc
    md5: 993e74980f3a1bdac000f0d4b24b34a0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f418dbbe804f6f56a55e0be93479135e
    md5: 157c9de36fa5eb4ea71374e11aa27119
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 0ce4a87d22ba3028217009bd4cf4cb36
    md5: 99e3133a178bcae6bfada62ae5305af0
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: c110830568e6cef8988ddf667b2f7e02
    md5: 7e0e1b1c72ae08fb23ceaf31b65c89f5
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart288/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 8a1f5d6f4a8a60110f8fd28c289f777a
    md5: 8a204bf2f3e48d7679d38438f16e9850
