format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/atmosphere/restart_dump.astart
  hashes:
    binhash: bebf74f1f477e03486245845e9445a23
    md5: 536a58067d7d5e234a1711305551dd1c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/atmosphere/um.res.yaml
  hashes:
    binhash: dcd9a01499a1f84f2f21df24822ae5ff
    md5: ffc2e83cfe2f9c9ac24bf6497f2ddf5a
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/coupler/a2i.nc
  hashes:
    binhash: edc3112bd6abbe7f3c4c00043429cecd
    md5: c9b2e668fb0e9715549aef87b086cfe0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/coupler/i2a.nc
  hashes:
    binhash: fd7c6179d43fcbef7cd264924b1e3576
    md5: c4ae5b712ac6dde5efc51c895cdc00da
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/coupler/o2i.nc
  hashes:
    binhash: c3de21ae40422adf6dfb4f53a183a26b
    md5: 41ed52971ac8fa51a5b2f617a667c9a4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ice/cice_in.nml
  hashes:
    binhash: 186b4c7b7b803aadd699bece3d2ab34b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ice/ice.restart_file
  hashes:
    binhash: 6af93d74b6973de2cb2c0b6e0747be72
    md5: e72e936ef618414aab6f28057ee61ec5
work/ice/RESTART/iced.0966-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ice/iced.0966-01-01-00000.nc
  hashes:
    binhash: 3b2539e9495938667a0e1a3bd5c209b7
    md5: 39436ecb4279e5a2d7cd2ac569c09ced
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ice/mice.nc
  hashes:
    binhash: 455777d47e9cdab5f59e7e1e7196ce79
    md5: e530f9f1c73c89461c19cdc5cf26d10f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_age.res.nc
  hashes:
    binhash: 2617198952e9f28027c9d1532f564a31
    md5: f7913c312d114e08e1f2e0df8f97a8af
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5ceb3365ff88f7eef111c738c7dcff54
    md5: 79e9ae2fe9b3fb89a42e3df53d3b3d75
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 9522820721791dc3bcb516a9abf5a228
    md5: d7580d96b030ef0d54261069b1cd4cad
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_density.res.nc
  hashes:
    binhash: 5acafa13a56fef8eeb6825d052991c36
    md5: 72bd567b0c68029ba795ecb659de86b5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 51e1d81b3f5481e9c756ab2ad3d4532b
    md5: 6b14a2533eb2095df794ed2b2d1a8e9a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f29e73a03700b7c6231f04f35630798c
    md5: 56509dac997194210fc5892a371ecac8
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bee486b46a0e90ddd4046019f3e9881a
    md5: 614c5edcb62549be632bab8aba6513b8
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: bde8cb72557a2b0a51d16a79e25d5087
    md5: 70e919da27e435e82617541811c1c9b7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e9ccf5728dce105519ff2cc13e34da7b
    md5: d9b479a9e7d71b47ed6a8dee78c2d097
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 74940c4daefd9bcd2ae28373197af471
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_solo.res
  hashes:
    binhash: bcb8f3e20134709119a8ce46eee6b002
    md5: dacca9222fc002fdd5c5496d0df1329d
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f0f241fc492d45b6fbcef459f20ca0a4
    md5: ce3638834fec0a806bd44f0a76e20814
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_thickness.res.nc
  hashes:
    binhash: d1cebc2e1024707370c366b7f9ceba70
    md5: 7132187bd066a6bf24af61228bf1fd96
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_tracer.res
  hashes:
    binhash: 775ba418c968e0548d67dc49fa555380
    md5: 155b3525a7593bfc620572ca8f7964b5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_velocity.res.nc
  hashes:
    binhash: dfd547c767f1f77676f7d7233958fa18
    md5: f442a14fda2be5a14b8fdb9e55232769
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a495528394c008a6169a1e5fe2ffed99
    md5: 114a08ceafc5c6257620d40db689dc00
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e872a398b6c575803fe9ff82bd0dbe99
    md5: 16c1d29e9e2e410f736047c5a8681913
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart412/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c1095a5d449f3593dcb628d29063b178
    md5: 4cab86f91adf75443d4ab9c5641ec104
