format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/atmosphere/restart_dump.astart
  hashes:
    binhash: c32f099945c2b2e54f345b1cc3da186b
    md5: f6a160f6c7ae76d664dd0e65b9237f6e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/atmosphere/um.res.yaml
  hashes:
    binhash: 2e10bd772122d28b1df80319693a29e1
    md5: a2d2463ba8e7ff90ec7782d4a0baedef
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/coupler/a2i.nc
  hashes:
    binhash: 58ffc160fd1f12075836feeac889266f
    md5: acc9f69cb3a966df67aaa1d97fc5c978
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/coupler/i2a.nc
  hashes:
    binhash: c5c00f28a7ea65ed8d65c30f3859ce60
    md5: 32f06a69f1eb887dd37e36337aa11c8e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/coupler/o2i.nc
  hashes:
    binhash: cafd634a88197a3f28f5e73f3a066f9d
    md5: 0657c0ab810e76c13d62ad53df839cf7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ice/cice_in.nml
  hashes:
    binhash: 7d987cca9e916ed1e3980619c27fba57
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ice/ice.restart_file
  hashes:
    binhash: 2461858bc0bfdcc38afc5c1da9634012
    md5: 377e8f2b725973471a951a1810b060d5
work/ice/RESTART/iced.0864-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ice/iced.0864-01-01-00000.nc
  hashes:
    binhash: 848b4d6377f29bf556ac15d1d605699f
    md5: 59ba9ea1d61621cffe42fb7f2df8fa72
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ice/mice.nc
  hashes:
    binhash: bb08a214953232e53eb0c0a2bcbcf1ac
    md5: 1665e1fcc65c9921c706192721a50cba
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_age.res.nc
  hashes:
    binhash: aa9287f28650b4277a2a38e33744ae88
    md5: fa495d2cb891955f28d17c5b3c00e01a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e7f0583aa83628aa200abf267a5e2a0f
    md5: df6ec7b5b7e54abe15f5a3c8a0c38d0d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2a4c96393b8d23151bd028200596bcff
    md5: 3cf02dd3137d4978164811dbedc361c9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_density.res.nc
  hashes:
    binhash: 000bf17dc3ebc7202570c569f34c49ce
    md5: afc2fb2c45688f4ae5f867c6fb3d331e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 67edf4c09dfd04f4f9d1781ba91fce4e
    md5: 7e5baca46ecc098fff8305bf1bf60917
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2e736790c7e7e37c22712839c5d634f5
    md5: d2b12928502999b9701d6f695ab944c7
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b1f5d2dca19085880932b1d6c3802df2
    md5: 2faa902f10b911ed03a093f02bd81c11
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 043658cc025148e761fec03b7312440c
    md5: 10c2bb2b43b71f9e868d632ec3e58567
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 50d8cef8605fda7e8dddbe19415f092a
    md5: 8003519311f8c409738d05f3b9931a31
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 8721b5d53866160046852cfa9c950951
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_solo.res
  hashes:
    binhash: 4e85d4a4f808a487df4edb9ccdf15ec8
    md5: 3b07bcb9d4f5b0e2e8860e4a63f38749
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ae6734832fe42e6d1cbab2592c65fdd6
    md5: 8c6c11852fc1175aa6870f5ddd785dfb
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_thickness.res.nc
  hashes:
    binhash: eb84bd84069ca0ec13acd1e47dd0591a
    md5: 0d3826d31fbac5d5b113433fa69e432d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_tracer.res
  hashes:
    binhash: 1edaa7a755e13a895bba187622b857e0
    md5: 0dabb9b774e5fb319b2f856ee1ff2b11
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a9a88e28e6eb8d75d0a6b9e6e4e3fb56
    md5: 03d94a8a90f058fc7041820b3e9b2f5b
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 41f95ba3d3859c60eecc9291883aa6ff
    md5: 4ac9cfb1ec21f33139226bbb07c4d9d4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4651013ef59bde9fd69b6106be8b3243
    md5: 70450df6f9f2e505620b3555ea2ad394
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart310/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 3fed776933950727044f66e383c7e12e
    md5: cfd05d7b63ede6e3fa1fee61aba4e249
