format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/atmosphere/restart_dump.astart
  hashes:
    binhash: e3f3cb8671a000f81ef026bc0f1058cb
    md5: 00e4a5ee41cf60e9396ef3b49184f94c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/atmosphere/um.res.yaml
  hashes:
    binhash: 547053e79d342039c4595b02b0c91aed
    md5: 613f737f54d828126ff541994c94efb1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/coupler/a2i.nc
  hashes:
    binhash: 277d09a6704a35a8ce47ed47640efd05
    md5: 6dc7fd4ad418e419b18a308711099af4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/coupler/i2a.nc
  hashes:
    binhash: e528c3cc5c6f7dae597c3033b1752cb8
    md5: b6a75b3eb5ba937dd0daa7141f25f154
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/coupler/o2i.nc
  hashes:
    binhash: 01b8aaebd475b23c4268832370ecdeed
    md5: 1869b37802217d34255f2f88684c2a3a
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ice/cice_in.nml
  hashes:
    binhash: 26385b9fcbfc665227f48826fd11061d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ice/ice.restart_file
  hashes:
    binhash: dbbc847a48c0a8ece091c461599663fa
    md5: 596bd143c48d035eeaf67144358edba0
work/ice/RESTART/iced.0930-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ice/iced.0930-01-01-00000.nc
  hashes:
    binhash: 73a3efd9477759590a9a87339ffd0d2c
    md5: 965b9adb576b615294b64e96a91954bf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ice/mice.nc
  hashes:
    binhash: aa1b1489cfabd10abcd0031e43a3e492
    md5: e58c3b53cf3b4acfe21ec0c81e53da5d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_age.res.nc
  hashes:
    binhash: 7a855465837803fdf996d90400215f76
    md5: 0bba55219908c047a54fe5fed59e6730
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 42cde72d8e8b2a54dfd4633d523cc108
    md5: 4cde06abf1fd1c783b33ebf12885ea5f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 744b6ee81f2390a334d84e7da3727f63
    md5: 5afa0a4a42ccaed1e43d4fe108400997
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_density.res.nc
  hashes:
    binhash: 56f5026234f76eab5be3d68656efcc53
    md5: 4925037814b16b36f99c383e31d2b0b4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_frazil.res.nc
  hashes:
    binhash: fe797b8d8b0a5b042f12995caf989781
    md5: 82dce31556862d3bacac523be65cdaa0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9f2ac94e2e5e712a2c994e4425d328f0
    md5: 7819744c7b51d931f8029064a7dd398e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_neutral.res.nc
  hashes:
    binhash: d6dedf9bb8e5f119e17296f9b6f9a1a9
    md5: df487c8e88e3c7974dbde99f40bc1510
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 0c921e5c3cbf50e6b30e9ff86c9ba517
    md5: 1f277b2bea2df5bcb08ea518e3ed9e3d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_sbc.res.nc
  hashes:
    binhash: aa7b1b8a48997b2d27f279dab402b432
    md5: 5dd3806deae2803357e23c446c1d8f4c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d70dd11ddceda47f115da061b02c6ad7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_solo.res
  hashes:
    binhash: fa4d7b43fdec751cfc61b1afda3ac2cd
    md5: a04a1cea25ee11c152186f01059fb944
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f9e636de1d0a20a5a25ba29aa9d1239c
    md5: 1948254c4af6f8c0f69a78bee974425f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 161c7234cbb540d770556d4fd885a239
    md5: 1ba0aeac49ae2fcafdd93bf7c9fafcad
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_tracer.res
  hashes:
    binhash: 187d53576146c510a2bda734c43db5dd
    md5: b2fc3d7a9b1de58c80977caffd71d99b
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 148ee0bd942ad38d1534a49740a07444
    md5: e04b360f1a7f42a0ddf1771f3340cfc1
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fe8adc77fb62e8d4322084ca529875ac
    md5: 86a9a3585d85a1b190c3ff82ff41e6a4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4e4ac65e3c0058f28a1cf95597886543
    md5: b6035254493c54655c63fc141bdfd03c
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart376/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7c4420b130799f24ffe1162fb24fb3e2
    md5: db7c84b71040b0b5e3f43164e12f6cca
