format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/atmosphere/restart_dump.astart
  hashes:
    binhash: 458c898706c538480a8b33dcc1c31d30
    md5: b519e036a883442e3c0905bb636a860e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/atmosphere/um.res.yaml
  hashes:
    binhash: 328d622c65a6375343e67abcafbd8402
    md5: cf2c88361b5b0d1f3ff2bd95f8a9d4f5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/coupler/a2i.nc
  hashes:
    binhash: ff7132e7d72aea7da87ad5872d89ecba
    md5: aefef60cbca426b9171854d381b44dd0
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/coupler/i2a.nc
  hashes:
    binhash: d40ef0b128497589790f23da3efdb2e6
    md5: 9232f2e36ee7e1d81c73faa4737ce13f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/coupler/o2i.nc
  hashes:
    binhash: 34cee4bae6378023615d15a61970d367
    md5: e58c0059d6ee1426a979bb777314511c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ice/cice_in.nml
  hashes:
    binhash: 6d36f103e4c3edc1afeb8e5c74bfb08f
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ice/ice.restart_file
  hashes:
    binhash: 43eb73817d8ab0d735bf9d459f5df004
    md5: 40665a9b6b2e452d77ba500ea96d3092
work/ice/RESTART/iced.1858-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ice/iced.1858-01-01-00000.nc
  hashes:
    binhash: 9cb953f90f9825fb5624ea818729e25b
    md5: fab0b49eff0e1ed297954840d2f06099
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ice/mice.nc
  hashes:
    binhash: d6401814460f2cd2478970230240e0db
    md5: 909185d058070b03adfa2aa97b5fded2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_age.res.nc
  hashes:
    binhash: 62d30a4b6a1615442855c4c319d9822b
    md5: 9aed5d953ca8c6a9cc6b4f2fd9130fa1
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 60b7df3f9896916c136a02ae8180bdee
    md5: 35f88e16446394f6c1c2472836dd3af4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f6b8ae79c0d43581f7811dcaf31fcca3
    md5: 22d1236e203104bc3549d359176e2a42
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_density.res.nc
  hashes:
    binhash: f9445bd53331e72b9054a3047f99cb14
    md5: a53ee66fe29ec15fb98d39fda7a1284c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 36d6e6b4150e6f7d9bcf707834169d1b
    md5: 6408ac45e9de038ace27d62bc840b6ad
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0f846c53e71e32a043c35b582b6e9f81
    md5: 8919f0d96f55897f8e73c464607a3f6a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9b93018ff04b0a8508de938c0ae0c293
    md5: c30ae5852743cacd84990ae723a91e7a
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e07d9f8b093cbb06940a6dce7bbdc6ac
    md5: 36285397ab91f0e83d65610ce93451ce
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2edf6ad331bb20e72391c20706fd609a
    md5: 55e9df85266517ac1d4af8f0cf563ca0
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3d4f3a2d4dae4f8fbf99d7c1ac8a01c8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_solo.res
  hashes:
    binhash: 7abcbe6065d5c853fdcf54cf73c60178
    md5: 12afd34b7ba983df3e909c9ed242a5c3
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8e7fdf7c12ba797b563f234ad6e133dd
    md5: 0339d319fd09e3b0f4418d57665967ba
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 864c55c9324a2456851dcd0c975c2cfc
    md5: c85f41c748458cba53cb0e0ef8250b87
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_tracer.res
  hashes:
    binhash: 4199a84206fdea4e38b229409b86239f
    md5: 6c218dfadc16224b9c99931a98cc8d7d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6e9e809b1aa7fe6a61ea0d4087e11150
    md5: ea475eedb622bbe75007a7671bc99730
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bb463f8998fbcc28283129deefe00ddb
    md5: f0ace552bbfbce82bf61c77cbd775891
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d76720846825c76bdf31ec23cd7a0fbc
    md5: 36ac1c212ebc97ff503c111853b1ac8e
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart413/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 79457cd1c6a962501061b92cdb55be85
    md5: 179f205af9da49279cf5b6e2d6507e3c
