format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/atmosphere/restart_dump.astart
  hashes:
    binhash: a9cc5f3abfafd1ccba4437c48b36bea5
    md5: dc6ac3039b5e06321271463f4b8b30af
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/atmosphere/um.res.yaml
  hashes:
    binhash: 1e4e3008fff04552dc7b6f421a03b0af
    md5: 25f9e4fe1ddd3e8955a2c02655d0eeb2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/coupler/a2i.nc
  hashes:
    binhash: 233944e13e4d77c2be46c44ba3993c9e
    md5: fcb46afa62e619efd54bdff7c1154ed3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/coupler/i2a.nc
  hashes:
    binhash: 392cb2de8ff9c457d60cee1f11fbbeba
    md5: 7c8d240ecf22a4a6b117aedaa5acd25a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/coupler/o2i.nc
  hashes:
    binhash: 70a1b7683e73f2b38453b7356e66a879
    md5: e4b980a161a05d89045bf6c56fde06a7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ice/cice_in.nml
  hashes:
    binhash: 0b1e8d83645d5fc0a35c9eecce10bd70
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ice/ice.restart_file
  hashes:
    binhash: 81df0784724ee3a8ee9433dd781c61dd
    md5: 9d4433fd06901a3871d021c2b48712c2
work/ice/RESTART/iced.1193-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ice/iced.1193-01-01-00000.nc
  hashes:
    binhash: c8f31e2b58234df7177cba5e8ed453e7
    md5: 3eeee885c7bd09ad9bff4b1172190267
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ice/mice.nc
  hashes:
    binhash: 74d8c5fdd9d1ccd04291976796db6d57
    md5: 46108b7b764d56d78ac19e13c7742295
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_age.res.nc
  hashes:
    binhash: 316818bf30a84ca7e1678c3db7a1ba4a
    md5: d528fcee0caeb847acd1646affcfee07
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6b4b721f05f1066ad41ae70a1cdbf9c4
    md5: 531ad533fb2322bcd4c298698e908ec4
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 05e16c6003b1e31cc11c5f0469033091
    md5: c0f4de54b36596422c0a790fcc0dc88e
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_density.res.nc
  hashes:
    binhash: dba36f6897f1f64f5a97940e37465e80
    md5: 4bbd9b088de893e07085406790f35e7d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 29376c15dc5a2d5e50b46d879982b669
    md5: 7704607b1e0c9c3a13c4646b7f383699
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 0c27562719457419e7afd0eb217007e8
    md5: 93fab0416775c57f1f9f82d5f9a2f574
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4048c1d8d2ca5f7ced6db5543775879c
    md5: 276c4b44a2a3e4ba0aeb43b8cfc71507
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4db6c0738bf97001e5c32a050d493ee3
    md5: a8e9ecbb23666a66b7d29a1cd7e4c74d
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_sbc.res.nc
  hashes:
    binhash: a0350787c808c6041341db08607f44c7
    md5: 6fe980e038e79a9768432b7bb1156d08
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5c25dea89c3ccd580a65106c9075716a
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_solo.res
  hashes:
    binhash: 678aba529fb375a6ad6612358707c143
    md5: 74fbe81e66f614aee0f6cc3a56e86c4a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 41d5c7a3339d1ac77785b59ef21cfce9
    md5: 95f1b615d8ea9af90bc471fd6e31c0f3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 330aa7bcccce86c6c5caa26ce5327bbf
    md5: 65db1ba1871a2651b02022b29c8d6afc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_tracer.res
  hashes:
    binhash: b798771d7ef17d882c786c018588501b
    md5: e5ea817bcd7f2d70de8610fee0611b36
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_velocity.res.nc
  hashes:
    binhash: e34349611c1eaee0b49e59ace3d45810
    md5: 630159cb2fb4ed003a5b5af2ac191f9e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2601526fdeb503db5f696249f381a0e1
    md5: 94e9fc19fd6bad479cd388339047c070
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 17c4cc24d3afe3b766506bac7704f852
    md5: b6fd39709a3bae6e98840ae1418a5988
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart309/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7534fbbc8532f997ed4d82ee2d348956
    md5: e7e28b852a6927420740bcccd3c631e8
