format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/atmosphere/restart_dump.astart
  hashes:
    binhash: 1e6ff18e4887a9a54f42e382b1d80c59
    md5: 2a2f6e6e1f827d94cf0f263c3af6babd
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/atmosphere/um.res.yaml
  hashes:
    binhash: 2cb756999de8e23994ff53368c21adb9
    md5: b7e61aa16480331d15a8b56b0d76071f
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/coupler/a2i.nc
  hashes:
    binhash: 5c43d7353f8397be15d15d71283ad342
    md5: 56141c7be0b95c21e0000ac96347e793
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/coupler/i2a.nc
  hashes:
    binhash: f579ee04045ae414610b2532877c862b
    md5: 07e67486d5d5f82356a7a7d46fc25c6d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/coupler/o2i.nc
  hashes:
    binhash: a2b57b089fe8ca6fa89bee52cf09c795
    md5: 06b26f4ae96465ff0173c7f002bd0c1c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ice/cice_in.nml
  hashes:
    binhash: 826d5e4e559257d79919630a6fa737de
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ice/ice.restart_file
  hashes:
    binhash: b8a42ca4098805d1ba24d4f293d8c12e
    md5: 8557899d1e62a7020ce238b591e92691
work/ice/RESTART/iced.1773-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ice/iced.1773-01-01-00000.nc
  hashes:
    binhash: 04e1a7c8444774bf6f31f8646006a1ff
    md5: e46e11342a8a39cd5e0b5c5a5053d1cd
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ice/mice.nc
  hashes:
    binhash: d4c307e26cc1c33dfa44a72ad31a24b8
    md5: fcc4ee480725948018fe63ab408ef670
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_age.res.nc
  hashes:
    binhash: 374bff8639f505954d7d7fe0d02c2c95
    md5: ee7d5ae79e6b25f77e8d50ff03865573
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c262ce53b208aa62aa1b749bcb0dac1e
    md5: 4b12e46526e697fc79e2df7cac4b0adf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 1b5ce42780cb7a90fc4b70994a99ec50
    md5: 02358b5216dbc448c77c6088addcb66b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_density.res.nc
  hashes:
    binhash: 63b06c64fc9ecc953baae1e1c23d189e
    md5: 49a84e447384140e6df99e31556c01b3
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 40234ad7659e28515742acc3a096d6f1
    md5: 2ee1315496110ba74af1b662735ba8bb
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 804916b87406171944ce3cc238e5b747
    md5: 96ae6ba38d21e2dcd983aab14bd53f9a
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c26809a7f303f1c708cbd8ec91d0c6f7
    md5: 64e28bcd5a2d59b52cac9980468906f2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8dc46b9c105058a38027a7245434516a
    md5: 6809a8188f7d8494ab3ce0d308444d22
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2b334d0173df3f27fa19673e9366dfc9
    md5: 85bdb9e1aea4a9981c48e0563a9de1df
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4e302475c50ffd6a7cf178e3dabc3a25
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_solo.res
  hashes:
    binhash: aff5359881df862b2603ffd580799d19
    md5: 874135a699e5019f8f93db44995e2af9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 39d35066c33e73f7f1b0b76d434f6b4c
    md5: d32f879b891e850b4aab5a5ccf3134b6
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e4bf62ef19291e649afca2ede2588aaf
    md5: 7fa92889e2c29abe45084be5ac2bcac6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_tracer.res
  hashes:
    binhash: 8e7d4b3ad6f96363534cca0f77c586e1
    md5: 38a591b8545b175f128ee0225e80182c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 69106885327559b331ec1d42e46d5d81
    md5: a0bfa506a14054d64b2fa2c1dab67d32
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2d979605e47e215caea46571737cc028
    md5: 43756c6a8f9c654196d44b95e35f23b3
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 8f53d405b07d763eedf6b51ec4003149
    md5: 39c82c8d7dd3a3c7099c0788d22e59d0
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart328/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 25acc0f4371aa9b9f4a7865a57d6a2ab
    md5: 0ec699dea0c038a00a9ae91c71f10092
