format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/atmosphere/restart_dump.astart
  hashes:
    binhash: 63789176d5efdb6b64cd1f598206d967
    md5: 6fb7ae2b993c35c06fccdb52c267d6c2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/atmosphere/um.res.yaml
  hashes:
    binhash: 2b9971cb83c17f151bdb4bf0f13c51f9
    md5: 752accd051a1b6a7a31d5eaa4a16c3e6
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/coupler/a2i.nc
  hashes:
    binhash: 80f99889943b22c4294456ffd76086e6
    md5: 70383d1ffe1dcdf791cec56ae9071f34
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/coupler/i2a.nc
  hashes:
    binhash: 1f3193fd1b7243e242ab1b963ea6110b
    md5: e88cf5da5ab78270f2198f73d5e9ef5d
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/coupler/o2i.nc
  hashes:
    binhash: cc2dbafbb8d08c6c0c63fd4c9ab076a2
    md5: 36de7612e8410e7293e94b75bbec56a9
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ice/cice_in.nml
  hashes:
    binhash: c380d67de6f285da0d1230a7fe584d72
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ice/ice.restart_file
  hashes:
    binhash: efb2883efe5e5de26c62d4cc38149d60
    md5: 5522f91cbf8a6c87dfb01fb98ac4f9b3
work/ice/RESTART/iced.1727-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ice/iced.1727-01-01-00000.nc
  hashes:
    binhash: 095fe5f5903b555b512e275667fe1ce1
    md5: 020d41df378fb21c30c00e2acde5ccd5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ice/mice.nc
  hashes:
    binhash: 7867d23ada5a87816649f8dc444a777f
    md5: 0a5aa1bb7d07d9539f667d2640e03aac
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_age.res.nc
  hashes:
    binhash: 8996848fc3ed06c4879a4d8fa1ff5be7
    md5: 47a2c6c8575e2f99c041ce3b10e7b634
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 594e518165c64e92d9c2caa653cb7793
    md5: 9a1d3d4a961238db4a6dc45ffbd5bed0
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 5da5616c1b7ba6270ac4b887c0eff2e9
    md5: a8e362389cca1e3cae5a2b7115d9c425
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_density.res.nc
  hashes:
    binhash: 8d99e8f5662103625becfc30aed5a8ef
    md5: 2ec380f7fa6f9a66f4908aab58c6e298
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a84151ed8ea595e58417f545f0f4d5b6
    md5: 8a415bfa39c8a365cf50352e1085ca4a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f8e5aaeac806ded2cece32e31341908d
    md5: 4563d9482b41835809496efd7d8933dd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4bd20102fd9d48498af7d9b826e57de5
    md5: bb591310a73c53055e3c6574b186be79
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8b2556f20114104d19db34cefc70d1ed
    md5: f6a02ff8f16e2fd560b3f6d94a02ba47
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_sbc.res.nc
  hashes:
    binhash: efa21aef43ad8665fa10b081aad90fc9
    md5: 0a2fe7e829d7dd8ba666dfcbfc57b351
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5cc6a115235cf19f1f4327acb939eb5e
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_solo.res
  hashes:
    binhash: ceef22e2e30ec6a8b36e45d527984591
    md5: 3515940d8c109427f9612b2e77e4b94e
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 576d8b35fdb1336b3b48f67f7f594157
    md5: 135f5e9192651aa0fd02d9c31119356d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1b01826f5cf40cac0ece4c3ce6ee6fda
    md5: e3ebe5457b6846e01e37eb27863ce89a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_tracer.res
  hashes:
    binhash: d1389df2ba7aa17107ba30dc0d67c0e0
    md5: 61e2283e047ef9c3d4a0fab40e8f5094
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 05d9064c1f4790f81cd91b98e4178a0d
    md5: 52ea82b058373fea5618e154dffe7ce3
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bdb630b8a87fe0982ed0a950cbe5ca00
    md5: b760cfbf32732827f0c162d63cd6a138
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d851f0e7cb6137d18fa185e3fc7ace7f
    md5: f4311a90ebe7412053e81bb2b417f476
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart282/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2eb8d35df54e889016355851e6d6cf64
    md5: 9a145faa20ebfdc264c0b8946646a0e7
