format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/atmosphere/restart_dump.astart
  hashes:
    binhash: da75300d2ba351edd2067ac26b7ea8ee
    md5: 14f7ec13a34b3ef18f5255cd56e812c3
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/atmosphere/um.res.yaml
  hashes:
    binhash: f5407526356638b511528d22cb86f47b
    md5: 6d43fe6cbbe2395f302ca496fe7aa5eb
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/coupler/a2i.nc
  hashes:
    binhash: b766f57b3d1a84571dc5e7c50157a7a9
    md5: e38efaf54c172402fb6721637902478f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/coupler/i2a.nc
  hashes:
    binhash: 125a96b91a930c1ef230c79151d2aea4
    md5: 525fca00ef417ab6cd81602da057b7b2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/coupler/o2i.nc
  hashes:
    binhash: c7c47c76d47d4c3f1480097a7d638422
    md5: d01faf54afe12d7fe74252ce0d912c8e
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ice/cice_in.nml
  hashes:
    binhash: 593361f580d5483e4a682a0394d4aef6
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ice/ice.restart_file
  hashes:
    binhash: 23a890255dab0cfb2f5a56dce872686f
    md5: c8f15dd89e97c55251585960100cdd35
work/ice/RESTART/iced.0842-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ice/iced.0842-01-01-00000.nc
  hashes:
    binhash: a2de1df518118cb237945c09003b628f
    md5: bb386c61d136418b424feca7e3b865a9
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ice/mice.nc
  hashes:
    binhash: 6a5a60eecad2fd2adc47463247c0c40b
    md5: dd0c1cd564030c5512c153d03fb3125a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_age.res.nc
  hashes:
    binhash: 5246ab79d5272aa1fbff1a5e65a466cf
    md5: 0e2684833634c3a71af652ff240672a0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 40cea3bf970067e5a11e76c4a5b42f35
    md5: 1ecaed3a8e7f49ac6524b7db3d035ac6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f74ea63892d6ee9563cc272296bd3ed4
    md5: 07c951be3c7adb3e73927e28b1c7a59b
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_density.res.nc
  hashes:
    binhash: d244cc697e5c42ebecd5021770a5810b
    md5: 4e6ba48698a6e59be54356ed884418e0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d394718da25566f25967dae6897f306a
    md5: 3ced38026b4f2a7501a84d8e2af38aba
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 09b499d887583f0fa47431b553344d87
    md5: e1a40b7475aa003aa93327a2f95eab13
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 438fc2aadc6ee6c6ecdd9267a3c26b6f
    md5: 63d477e02f77a95470406c7aa8b838d2
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4d862fdc2a8f169568f9867a8c76bc3d
    md5: d212282000f022013ad3f516654b7b19
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 68b0af27381601a31c2f0b183a2ef3ee
    md5: 2f8af24a6818e659d7979fad8f3542b1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ee63991d27bb5d4eeb40f70a7e09c94d
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_solo.res
  hashes:
    binhash: 939aeb1009fdecbee8f6a7fde0a6bf19
    md5: 8c922b6412a25eaaf6d7f1ad1912b5f2
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7808c9be44f0c288bfd375896417377d
    md5: d473baa9f381eb1178f10005f0cf93b1
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b99c955106f6f4da4288835b86bc9e84
    md5: 7d59ec8df01fa55a6de42e9442f3a928
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_tracer.res
  hashes:
    binhash: fd2153f7c4a2f9b299d938992c0e87cd
    md5: f30ff5ed35a653a00661ae45c30a98cf
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 14ea670ca84507e2b595ba2725e7b34e
    md5: fa1076c04a5c31b57db38799647fbfc4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: df7009288e64e1c50cf7eed2cb0399b3
    md5: e4150bc69c3da4f4145eb62c7f355a3e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: e6301816cc54209a0c5fe3090915af18
    md5: 6c9941153d510bd777d63b51a066cc4b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart288/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: c70a323284df641f03f81abdc3297e32
    md5: 94372b98f236e681a81d8c7eecc7d8c8
