format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/atmosphere/restart_dump.astart
  hashes:
    binhash: 3202b06a3ca9094c55a6b434316735e7
    md5: 0185cf63e0746328f16505bdd3776e17
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/atmosphere/um.res.yaml
  hashes:
    binhash: f17782dfcbeb30afff31f4ebd14fcd91
    md5: 5452b40c480cc24d1f8e371a7f289879
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/coupler/a2i.nc
  hashes:
    binhash: 9bcebe2a5cf7633d3c29041a0a68bdf6
    md5: 56c5f057a16aee1afb7f287d0d9162de
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/coupler/i2a.nc
  hashes:
    binhash: 869776efc754b4103d6fed693e84d2e5
    md5: a38ff9e654a95d7c184b3f4ce6870081
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/coupler/o2i.nc
  hashes:
    binhash: ca58e934fe26c039155bd5605bdb6560
    md5: 1bf447a083592558ab1679a9ce0b788c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ice/cice_in.nml
  hashes:
    binhash: a879c527e776265297298c084a098c2d
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ice/ice.restart_file
  hashes:
    binhash: 2d6623086f2d7330aa67f35b0db91ded
    md5: 077643f1b9bb43d91bf1f4493f1aa3fe
work/ice/RESTART/iced.1276-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ice/iced.1276-01-01-00000.nc
  hashes:
    binhash: 834cf64cc45e15056419664390f82e38
    md5: 415f7761eee13355f37363ce583725ab
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ice/mice.nc
  hashes:
    binhash: ff4936eb2681c853fcb0ede7c9e43d80
    md5: a91dfbb72e70396571e848f5efab837b
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_age.res.nc
  hashes:
    binhash: a238b26c1f4251fd77ac6c589393b4a6
    md5: 580df3eecef658972ea4228d4146f865
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1c20502183533191e8b2217b9085f9b8
    md5: 151598d6a54b252c5fab3320edd54abf
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f85093b799006c495f362d0acf5563e9
    md5: 8928b3328c3fd47fe6eef6fd22b13520
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_density.res.nc
  hashes:
    binhash: ae9b43eac67aae49ee4301390eb6d510
    md5: ee12c4652f8065b0da1c2dc86cd247ce
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_frazil.res.nc
  hashes:
    binhash: bce1fe73e35d92da131a667a2d58870b
    md5: 7e5a043cfd9aee74d15b11032ac41867
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2dd34196d135d3da7bafc774b3363a4d
    md5: 555c009a7d8325031c19d32d36914a68
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e973195ca0325b6037d6668daee8c1c1
    md5: f838f47ecc43b45b07d6698fc1ce8f65
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: fc66ad2dadc243d97da3e338884a4e04
    md5: cdf5d5a47b746763c4fb1c8cb20664f2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 28365d707a96d677a37ebdc22b73b35c
    md5: ba7083cd0f96f7c55e541e35da68ca46
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a0ad8eccd5af5b9b53f60a136343d961
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_solo.res
  hashes:
    binhash: fe9515d0dd4a74df021b16a18c316915
    md5: e57f0f16bc6fa995f93fe80d9469fded
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fde61d84aaa852afa2e0116d831e6e28
    md5: 86611f711ab579c9fd36e968cbd94e95
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 02ee9d7cb3189ee53ae725192074518f
    md5: 25601f6939340e4b6612c8b43255ebfc
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_tracer.res
  hashes:
    binhash: cdcc8f4adc3dc61da97a7f1be134f3a3
    md5: aac6f7b7a31070b0bd70d13855eefae5
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bf8e6a12eec0fbb05f8abd225f47b9a8
    md5: d767a09847a8301c74e11b0f8540645d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 682d05c63799ee3eac09e377b6a3f36a
    md5: 468faebea670e1dfb86b57bef7d63a2c
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 36b2c28d8ec7946e18f6e6b0fc4b86c6
    md5: 949786073fa0ff809dc8dcf1d068f100
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart392/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 2eaf0f32fee4ec4361ec33556f6cd0f0
    md5: 69501da8915bfb094314289e87185fd3
