format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b821f5ec309be21a629f3ec39a8be7f
    md5: 871e56bd890c3418d9b8567698e83c93
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/atmosphere/um.res.yaml
  hashes:
    binhash: 62fbe98e97a665961f6c9df1b541e474
    md5: 131a169b5be8c8485e1df0baf93cdbf0
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/coupler/a2i.nc
  hashes:
    binhash: 5f7378c144d2b2ceb53692e02cf54842
    md5: aa48f24b1a0df20a7098080394155411
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/coupler/i2a.nc
  hashes:
    binhash: 28314502b2d8c263f14bb0707dee1f76
    md5: 73782983f616b3c240d3daf51d885a88
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/coupler/o2i.nc
  hashes:
    binhash: 41ef787b2a8389431c78a1eccc7e1e71
    md5: 3938ea9994ee57cad8862747ce0f7c91
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ice/cice_in.nml
  hashes:
    binhash: 9efbaa5b3ace244b247238ed959b102a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ice/ice.restart_file
  hashes:
    binhash: cee5edd6ff78fdf15c3f89f5d4a1ac76
    md5: 95a4a84e08b4034b64810dc962634184
work/ice/RESTART/iced.0924-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ice/iced.0924-01-01-00000.nc
  hashes:
    binhash: 3a5006042e70568dbccb4b718eb770c3
    md5: 317663973afe0c1db0b2c9e6fbcc742c
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ice/mice.nc
  hashes:
    binhash: 097e6b76731612980adfa96acd9a027b
    md5: 50ed413a2664b511321787d6200bc3af
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_age.res.nc
  hashes:
    binhash: b7e54937ea858ce734c8f27076d951fb
    md5: 029c7267d5bc272a32662c596cb70737
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: bd4060e65a52809777b98e64b07ef350
    md5: afa4312bfa25b75888b9242749c7164f
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: cfd9ac083b07e1ec37b2c4c5ffcc8b67
    md5: ed46d1e7b81003356de5ef5d9bbc8b43
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_density.res.nc
  hashes:
    binhash: 0983b45bf74921a127128a87fdfdc52a
    md5: 87b7be07adb33177eb4e14663d687fd5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c1468a2f622541c4c6765ccf9338120e
    md5: e24516b5ce6620dfb1bfb2fabeace7d9
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1176e64e342636c42af7cb427ad7ede1
    md5: 8b28ed10af6206985bc2d018d769dd5f
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 764fd33d20191b6d4fe7c2b9bcc0c3ee
    md5: ae23acd871837f89fd45ab07fc55fe0e
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8b882299e44b14d853069f0b395687d7
    md5: f72309dae125967158abdcfda7869c92
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4aaf9a0514285efa60bd57c95c86745e
    md5: f365d611bcf94a62f6b83cad9d5b5103
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 5ee5ce3a09be73c519f84d9c5ea81aa4
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_solo.res
  hashes:
    binhash: cb770c66153490da56f5916e600268fd
    md5: c907dec253e2ce675945d0d79fd3c0e9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8441d40f88131e7a1512afbcf9260d6e
    md5: 0906fe033316a149daf8e21d95d19c8b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e8605ea17504937ab4d0fea9d00f2ea1
    md5: 0020896077297149f3a4f9cad4cd99f1
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_tracer.res
  hashes:
    binhash: 8300c9c362eeddac2f9b93e7a9a768c0
    md5: 01b7ab5658c772ad13373c10d3f10b95
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_velocity.res.nc
  hashes:
    binhash: baa8693b2c5ebbd75ba02ff29f6c46fc
    md5: 4fffd1bd2ee38dfc08e43eca4c6f7408
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fb9066445031f06769dbf991de7509ac
    md5: c3a75e1cb0226b8511f968bce4236538
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 14a604573c7b2094e4a72ad9385178cf
    md5: 8d5c1a19f16bb28b6f3d7482a48cedd6
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart370/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 1ce31077f99872de4b2d5231acc211b4
    md5: 809602b7d5c77bbbfeb03ebebe81079a
