format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/atmosphere/restart_dump.astart
  hashes:
    binhash: 94b530520734539d572771cfb6da0a32
    md5: c19d4b701fff5e1cf667a151609c11da
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/atmosphere/um.res.yaml
  hashes:
    binhash: 2b5a0fa86ad03ca166aafbba58ce16a1
    md5: 420d7fa2fe2dee81da3aa2e6112c1c65
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/coupler/a2i.nc
  hashes:
    binhash: 20492199c3729c10b042f20a71f6cc03
    md5: c8351180668fea7be062d57f80ff67d9
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/coupler/i2a.nc
  hashes:
    binhash: 6da5bdd8dd5eec999cc07942912f3aff
    md5: 607d10e2f5598a26eac1e75b7f0213f5
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/coupler/o2i.nc
  hashes:
    binhash: 32c20ba1b0781cd3f67fbad879e73919
    md5: 1494d6f2f7d94184c08e6b728238ff97
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ice/cice_in.nml
  hashes:
    binhash: a3dc4cbd50d4bee4c1640a112d0714b2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ice/ice.restart_file
  hashes:
    binhash: 3064f321541f7a1514ba5f408c3ad184
    md5: f38ff4b550986bb4a7692770ad0b2de9
work/ice/RESTART/iced.0958-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ice/iced.0958-01-01-00000.nc
  hashes:
    binhash: e4aacb158c4a3d3220d29d76499179df
    md5: 6ffd84a419ff60d60a793ef81d61a589
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ice/mice.nc
  hashes:
    binhash: 55036b44996cd0e51e47ba9ad9b93d46
    md5: 7b26cbae4b1357b92e3c19fad2f407e4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_age.res.nc
  hashes:
    binhash: ac0bc6b296a2e065e022760606fe11d2
    md5: 5effdcfae912675394d69885d806b8e0
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: b05e7fb0554ba539893c3c1b36f2aadf
    md5: fcd92e35bd57d0fb30f93bf532a56bc2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 76f1527f2b38471ba118da47d6e4822a
    md5: f79d79d7bccdfc361de186276bfec926
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_density.res.nc
  hashes:
    binhash: f2eb3262a5328bba59fd97ea9dd8512c
    md5: 4428713142afc3782f78c17276945486
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2c1aeaf3753267dc8d945691a1775334
    md5: 49cdf2422f62f6c4a89366c5f638dc7f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 43350d323883a1ffd74056d77ab09077
    md5: c67433bdb130717ee7f00fa90d69d8dd
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 6ba0763b3f8ea203ca2f276cc52416b1
    md5: 430fdca0ad116aa1ae3fc8df60904eff
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: b247285c27a081c50a8f9174bcf8bada
    md5: d833d9bf445538a91f11edf817d8c24a
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_sbc.res.nc
  hashes:
    binhash: b250fc2eab194c215579f8f4fcb9da72
    md5: 3229dcb772c6758e825293383f07f5be
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3dd97b77b0006028402bd035bbd3330c
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_solo.res
  hashes:
    binhash: 8d68984cd95f26a5de707b0d5f9f8166
    md5: 2c2284e6b50777d22b84ce750b7d5219
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c214bb0f4d01a8c03d8ea147b22e9c2b
    md5: ff7e1c43f7526f096a11c382c1d0ce76
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 99d376177b3e2c282f8f18e041657a06
    md5: ff0ff9c62186d93630e46124e02f4072
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_tracer.res
  hashes:
    binhash: 2de99f163f6c853f5d40952022b7390e
    md5: bd35411fbd59148ef1a3e55fddcb3bda
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 822aa7fdc6ab92a9e4a4584cdafd85ef
    md5: 4f2f19c11031ba5e7333d120c4891d8a
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: e34588c8f8dcc0b8407c6ebf5be8d3ea
    md5: f1ce05acaaf9b578d82927c51ace2e0e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: cb5011b4323910d2b6504563b51223c2
    md5: 06cffc62b9c16aaceb7fa78f4a064645
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart404/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: d832745fcae7f999cc45f80b681bf782
    md5: 0bc1c0b35c2bda36b2ef1917fe1bb2f6
