format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/atmosphere/restart_dump.astart
  hashes:
    binhash: a2417d85e20097091b0e05efa512b510
    md5: d0e4ea0711b6e01ebc955d2f0e235608
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/atmosphere/um.res.yaml
  hashes:
    binhash: 557d72688fea248b805f236c9c3c7e54
    md5: 57364e68726fd850cc75d6fde07ad4e5
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/coupler/a2i.nc
  hashes:
    binhash: 3b0517e8da8b3d6396dca64e58c977d3
    md5: 75aad1d42a0a1d05db1c82100d8c18a7
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/coupler/i2a.nc
  hashes:
    binhash: 774bee7e57116d09789f6db5d7314568
    md5: fb5e933848fccba8448e854d4d3ac0ae
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/coupler/o2i.nc
  hashes:
    binhash: 7bd11e97ac6fe65cbf88a4ae740f1814
    md5: f3447d0657e5d6c13bf8dcda9233b488
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ice/cice_in.nml
  hashes:
    binhash: bc6382aceeadf6f9b97f9f7b75d7d88b
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ice/ice.restart_file
  hashes:
    binhash: 9bf169c87b8e34caf23d217f22368e26
    md5: 53b8ee525a486760e92be18e96641fd1
work/ice/RESTART/iced.0906-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ice/iced.0906-01-01-00000.nc
  hashes:
    binhash: 0bc087c323693d65f397ddc2924819f3
    md5: 1815c30888305930def7c9dfc551c231
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ice/mice.nc
  hashes:
    binhash: efe3a9119de0567bc6125511b5a7d817
    md5: 7e89f08b69d07fd34e0bab232d9217f6
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_age.res.nc
  hashes:
    binhash: 61462151c9b609dba0d6074fbac381e2
    md5: 2b1f3f0f122e17dee46ef3863b061512
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0591f429ed5198688418776e0396b63e
    md5: 27a62027e1bb9d5b277beeffa1540ec7
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 2ca3e4c4978b226ce66f8a83f82bb1a0
    md5: ca07b7570b7eaf7ca0363314bf4da613
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_density.res.nc
  hashes:
    binhash: 7a41e949a2732cecda448c89ad9d9e01
    md5: b58277e71b9420a613d67ad71eb9ab0f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 27f4629171b8a8634bf8eddbb88cfbe0
    md5: 1851b6aa30675831ef46fd0deccaef68
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6ff2e0b0359fcb04c82ed21b316a396e
    md5: fca226ede80c136825db5ac486eb17d5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 565a0d7b61422c3c43a25b44a66f332f
    md5: ddcde729dc80f7f7be09e8ccc482b713
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1e727c38c02fddd1b5d200129248b457
    md5: 734b65d4a5828b3779449f84820c06bc
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 467567465514805f148b21b3d311f959
    md5: 4048dfedb0e8502b2932f36aa8a8f8b1
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1b3b6fee98904c435a5c6508f42cbdf8
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_solo.res
  hashes:
    binhash: 503a7567727fb29affa8baa805e50779
    md5: b3e08689d29a82802b8de14fdc47a891
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 4db8c5ab17ea843c5545637ffb3b73f5
    md5: f4fc508a45b031d05d8ce444b316c482
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 4b0a1c62c9984195bc1afd28aac96f27
    md5: f7f8e02d5ca38fa3e56d2900f9bd5626
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_tracer.res
  hashes:
    binhash: 191b216480d797c54b46b742f90d5669
    md5: 86962f226b5787a9f8d6701889be0a3c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bd8284620813e5d14ac6ae8b6e3c87c8
    md5: dbe09a8e4ae1f5e230d1d8262ebf10bc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: b93febb782f19a8876c9f7e774a9f4c5
    md5: 518794405561322a7af2c09a4d413873
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: fecf1cd8e600a699d94cdf35ec410910
    md5: 715fd3c98925d46d55a5c0c04133a575
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart352/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 4783fdcf407cd978316a559ce5080cd7
    md5: a782e4f3a3a508517fc792a83ff7094c
