format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/atmosphere/restart_dump.astart
  hashes:
    binhash: f5e18d01e60e16d40cbd19c90338aa01
    md5: 8749a3630f144c84ac77de1a0c2f794b
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/atmosphere/um.res.yaml
  hashes:
    binhash: 4ef7c1c7fe65a8c92eb57c965fb1f6dc
    md5: f9a6228f97fe16d719f6fadc02ce6776
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/coupler/a2i.nc
  hashes:
    binhash: 95984e580057e8315b14aec3e219d25c
    md5: abb5147574aec6976e68456b9b8b7d10
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/coupler/i2a.nc
  hashes:
    binhash: 433520997aa8bee532e7740d4d9457e2
    md5: 8295647ba6b9c3c310c129dc5a453672
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/coupler/o2i.nc
  hashes:
    binhash: f4d2410af46da487df9362281e8fec8c
    md5: 5135b769db8faaba6371cdbdfad52f0f
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ice/cice_in.nml
  hashes:
    binhash: 269630ae432e031d031549dbdfd8562a
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ice/ice.restart_file
  hashes:
    binhash: 4a4f51baf0e41c5d906a52f0358ab27f
    md5: 53a608cd6c0c85f0df3ce5258824a84f
work/ice/RESTART/iced.1747-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ice/iced.1747-01-01-00000.nc
  hashes:
    binhash: 28579784447e3c8196e1a490af797d34
    md5: 7aa79cd10f7985dc6f4df04aee361cf7
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ice/mice.nc
  hashes:
    binhash: 626859f343d9494e108e0c6e1406e5b2
    md5: 52c4005e8259aa211ded627282e9ff12
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_age.res.nc
  hashes:
    binhash: 00f7552a23dd4f30a028fb3f43710773
    md5: ff9bcc8ca9978149c6821103e800ddba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cb2e7859b79a7545958d8a10734c3ac9
    md5: 500bf7ccf626c824d09ed24416f06fcd
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ee1632d5802691742e877ebff6f20ae3
    md5: e5ee5f9d11a09e5f1946458532f7baf0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_density.res.nc
  hashes:
    binhash: 683f3fef03a1358cbf336c184c9a9854
    md5: 95431b630d0b60936109ca2396a3f7a9
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_frazil.res.nc
  hashes:
    binhash: ebe778419d2ea6936c2a4d5ac11b164a
    md5: 609b1cf88578f58b617c4a739fe3084e
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 9f22e5b9fece1b97cba6b957021b7a51
    md5: 57350ed09c1fcbaf5a34b4fdbc66da75
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_neutral.res.nc
  hashes:
    binhash: c2c2e5b8b2c66c88411d8c75206c550b
    md5: 62f5ecf2dc1797f4d612bedfe0b69de4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: d1e8bf563687586e296a21eb3ee5cf78
    md5: 6519f4068ca61e9e63da1879e55b6e76
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 5b590526954e15b5cdc014ed59b26c99
    md5: 3cbd12d4bf3cd37922f62cad97356d7e
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4c73ebadaab403a86ca8fba9a33db7f5
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_solo.res
  hashes:
    binhash: a898822025076cf18bfebe942b1179f7
    md5: 7b0e4e2fa6d0157646dba270aca5cdf8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: dbc001cdd82f9132adad210b76468174
    md5: 7557fe81600a95466c5904c8033a727d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 73144d891a5244ba3f913755863d6367
    md5: 8bab617f917b2b3135b591bf2e7d8d4d
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_tracer.res
  hashes:
    binhash: 4d2df4661d89f7de277afbc1e97cd98e
    md5: af842c9b848208c66ac64e5e25e94883
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c1181d68911f900a11e693b54fe9271b
    md5: 0c53977ace3b5aa5dc0c5f329428dc27
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f154da23cac1845cf7ecb31a06429c09
    md5: 88665efbed2a5dfaaead022e701c42f2
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: d5f2231fff176ac73d20a8063bcd054f
    md5: f135a50f9c58b87f8f1ce3e35460fe48
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart302/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 492d1ab06b52cec1ac2440f1fd40d3e9
    md5: 629bd0b4ad279d41ea5f947f7d7171e7
