format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/atmosphere/restart_dump.astart
  hashes:
    binhash: abe4708a03f8af57468b98c27c698274
    md5: 662b534c70ecaa65a0df9060a3bcf0ad
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/atmosphere/um.res.yaml
  hashes:
    binhash: 9a079f46a8810f361f1e30408b48c99e
    md5: d8bcbe52212b6b76a1216cb3042c8fcd
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/coupler/a2i.nc
  hashes:
    binhash: 46a8a730ab71c88c37fc295fe4269a6e
    md5: feae1a7ef03c0c295931563ef81d93c3
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/coupler/i2a.nc
  hashes:
    binhash: 0a5a284f1b2c6f45f7da78cd17a1b4d4
    md5: 2f7dcb655d52b9782be22b5f4c5da260
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/coupler/o2i.nc
  hashes:
    binhash: 3efa9e60af9e24d238daa89a9608cf9d
    md5: fc30b849fc56443cd50a736d4e188145
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ice/cice_in.nml
  hashes:
    binhash: d2c9c58ee0651775760e03da198e66fd
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ice/ice.restart_file
  hashes:
    binhash: 27185a43cc2973dd2b87cc47753af56e
    md5: 4572473212bef8377b6433a5cce65587
work/ice/RESTART/iced.0908-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ice/iced.0908-01-01-00000.nc
  hashes:
    binhash: 40862715779851102ad6a0af2eb4340c
    md5: 12a0cbaae992d97ea108b81676763711
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ice/mice.nc
  hashes:
    binhash: 17da971feab0bb04f9912d727899c1a0
    md5: de7bc10be1c384cae72dd655507c0f9f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_age.res.nc
  hashes:
    binhash: cfd2492991a23c1827840c9d51209932
    md5: fcf0df841e5ec292f535e3101b01d2a4
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 700e5e56517a1bbbd4948960ace0b575
    md5: 059ac922c9faa3a0c57f1d1487fcdf51
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 380a6939899941dbeb3e2deacc0e3a04
    md5: becd8a49f97187970f4ce81f12f9fd88
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_density.res.nc
  hashes:
    binhash: 1440bd2d050c8d7f7536d14fd05f6b6d
    md5: e0dca174351b2f86a84624c0c98876a5
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 554558d438a669e48b9b84ac73e50d51
    md5: 85ce8af0e5b81cf28126144f14dad31f
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5410591968a3447f8fbb29e090682042
    md5: 76f447a2e1230a5a2e5daccccb4d7074
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_neutral.res.nc
  hashes:
    binhash: b8a01bc4fdeccf4748a90ad6a02b1256
    md5: 0b267f2845290d859e810bc7b2038d51
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2f9a8866df76f1d6e086ac59f71e8073
    md5: 951dfb4979931f14a28970f5305992f5
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 4bf93f635d8ab72ca0f8a7e6e8235f5c
    md5: e78efcc421fb904e4875560b3a60479f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 72c4d45463f33d71079a5da42172609b
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_solo.res
  hashes:
    binhash: bb504ac2d07156bda4cd5b844c981564
    md5: 0c7e2df350b423e84253874d7bf2e03b
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 6aeeab624b903314cd295e489c655a28
    md5: a0c900fbf923cbbb61a0331039f4bd4b
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ce28bd4e927390573a33c097c5c9930b
    md5: 2f4cfa39156d70fcdcd961c252e76846
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_tracer.res
  hashes:
    binhash: 8f0fa40bcd521d39610857ff97a3c2fc
    md5: 4cfc9b2160c56b47052b47b0847bc1eb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_velocity.res.nc
  hashes:
    binhash: f5057b044831adcdd4eb692b03b4b604
    md5: 6ad9f5a875b912945cb0b1542f380155
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 565bddaf681821e0c524b4c86a3506d2
    md5: 1f1cc1c9dee2742e2ebda5bbc12593f7
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 881a1f42830fc0c24d7b00f4748acffc
    md5: 0d01c0d4e0dcf05936ec508c86fa6f15
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart354/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: a3cc8647484be0594a383ffc933e7d0f
    md5: e7a4d681f3bc20a5668b93ffa1a595c8
