format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/atmosphere/restart_dump.astart
  hashes:
    binhash: 00d59236c7075c6ba887e8b0962c4572
    md5: a18b43daf9984aaf29033954e66dee1c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/atmosphere/um.res.yaml
  hashes:
    binhash: 50680ba3aa21698407b463fa35cd76d8
    md5: 6d6d97e53267e8ab167808892f8f0799
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/coupler/a2i.nc
  hashes:
    binhash: 2b488ac28f6225a1471f953a0264e82a
    md5: cb8ee6653692bccca91477fa5124fc7b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/coupler/i2a.nc
  hashes:
    binhash: 4d6faf8821b9a9af9ba52e1f24014e8a
    md5: 9c6d1344aa110363e8308ea16852e6b2
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/coupler/o2i.nc
  hashes:
    binhash: 8eab973d69cd2a3f0b4d22a9e99eceac
    md5: 628258b24c4a9d5c61828984056de989
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ice/cice_in.nml
  hashes:
    binhash: 3be5e351e56df2a010f4d902eff8b306
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ice/ice.restart_file
  hashes:
    binhash: 08a764a25f8ae31f853cfe9698c6f318
    md5: 71195b7dd29a4f879d1317a0af081be0
work/ice/RESTART/iced.1295-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ice/iced.1295-01-01-00000.nc
  hashes:
    binhash: 5d63e83568597dcd3d907f4cec6f5bd7
    md5: 392705e6ea9581d1bdc931a8d6987f25
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ice/mice.nc
  hashes:
    binhash: 7e0c80abf33f2f427c12b0067fd88ba7
    md5: 74278911535a47200b1884cdd26bb8aa
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_age.res.nc
  hashes:
    binhash: 8392078981463fbe7570d4debfd5d18c
    md5: 8d033ac7a5a5750c6d17e02459980154
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 2970f2b79ee1e682c6d33a4962268fad
    md5: 53574e1511e04277b7d6e6d16e3bc341
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 55f86fd2fb9d78cf077e84fb43022a4a
    md5: 7d0550bf786ac183e496b96bf54117ef
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_density.res.nc
  hashes:
    binhash: 51d84d361212339c8ab1366e39cde2be
    md5: 23ba96b352abc8aaacbbf75f069afae0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e25a34d2e8d6c848b658f5c3318b14b5
    md5: 9271efa3a6c33964fcd5d595853a9110
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 944539dc324c4fbe7684b19c4acde7c6
    md5: dd77afca3ac7ff17fa35a2fffb3b40db
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 1117fdcd01d8758e7183807042493540
    md5: bbe8815b3a82e4d45457d935cdea59e3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 8008d2b46a051813a3be811105a3c090
    md5: 49fce36e428675e5f7e5b938b6eefe46
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 7facf318a2ede5bbfece9eafd9c3cd41
    md5: 1d6459fa3c4348995878530ae5d8224d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f5238325a92692af082e1a1e2c948c79
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_solo.res
  hashes:
    binhash: d867d871a119b1530d469b160a064c49
    md5: f68c62c5615279e92e07e9df61df0768
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 75aff78daa70845bc66833e23b91255a
    md5: b6212195f5d9a5862dd767c2567430f8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_thickness.res.nc
  hashes:
    binhash: c26e352540b106e16aad1eb36a8a845f
    md5: 437f67b741b152645696a832cfe9c7ab
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_tracer.res
  hashes:
    binhash: 3a7668720ebd7d6338fa3f943020481e
    md5: 18f206b7956b9bae603bd77c3b2be0fd
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 71103529347c9623137856b033302c41
    md5: 84eda5e0c2d8b7ea657758bf49154ebc
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fb0c5dc29653738cc729ef01ba6fd6ff
    md5: 9c7c92f1199e48bb80f1e1a5aed3108b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 4f446eadd4f5f77601bfdfe0b269b299
    md5: 36ed5f2bac0ec96acac4868b71498dbd
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart411/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 9c430c5b67404583aff65031dbdd3306
    md5: df9eb3e026876b7928b52a1d54eff6ca
