format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/atmosphere/restart_dump.astart
  hashes:
    binhash: b5fa5aeae203699c04667919ec52b987
    md5: 1216eddda391d8eb427642106a8e13eb
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/atmosphere/um.res.yaml
  hashes:
    binhash: 1cf90b8011831dea9c08d5ce8e7c9884
    md5: 35004c8613997b275e3419d46998b88e
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/coupler/a2i.nc
  hashes:
    binhash: 899b3527988ff44b25e7088b4dc5f8a5
    md5: 29f72a2aa27879d776d970488eda79c6
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/coupler/i2a.nc
  hashes:
    binhash: eb22fb3c33896488d850df31c28a6d9e
    md5: b1b09f5efa9c220b9dc66b2f15ed5635
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/coupler/o2i.nc
  hashes:
    binhash: 785af1d43276bd513e2e2c2de54f11f4
    md5: 5df1f3d9c9679fd57afe6bcfbe6af7b4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ice/cice_in.nml
  hashes:
    binhash: 39dbc422e7754b58db4a8b8ec2efcc14
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ice/ice.restart_file
  hashes:
    binhash: 38c96d06b32a88c185dbd2980a6f0019
    md5: 6e79e6181a353357f6f035ed1f12c70c
work/ice/RESTART/iced.0975-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ice/iced.0975-01-01-00000.nc
  hashes:
    binhash: 212a9172624471612385bf140e5caacc
    md5: c56f4da8b19e401c8621bacab37762e5
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ice/mice.nc
  hashes:
    binhash: 28de693e31dd4eefc9fdc0e9926cc6dc
    md5: fa18d89907ed4d2b8273119c66bdd956
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_age.res.nc
  hashes:
    binhash: c8e7fd695558d77c66815fe570115e4e
    md5: 81f59070d519af342473119ebd51600a
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 5739f936c590e3fa87161e0733acd90b
    md5: a9a67468b7bfe002796de3ed8a480c50
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 84f2b99f33f4954ea140afdb9901167e
    md5: a9c48f819735d3406cb6efb6fd255d76
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_density.res.nc
  hashes:
    binhash: cc54f11b8ed2a2346839e54833a78209
    md5: 605830f4cfcb9a7694f5a5bc8598647a
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 043a6763afd8dbfd348fe910563a773c
    md5: bd34591cbd75c002f87b4b218cc1818a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b699bf153fe7bb08734c0b1a036bf212
    md5: 1713bfaf24a7808b66d3a9f874b4486b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f7b462ae3bc820469b828b5ff81e1ba1
    md5: b2ff10c6e6cf393c35b05aef5c3e4b14
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 27a0f245d92e88e48d70e24dfae003aa
    md5: 16c6af815854abee7c0dc68078405cd2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 02575d8646dc97a82184030aca072547
    md5: 8513017dbb541b296528a9aa2b2ab571
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 1a5a2e6ea34ec581bfec0d3ac50b8bfa
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_solo.res
  hashes:
    binhash: d95347bb6036a8d1952db2c8abd0af8e
    md5: a0694fe2465188c0d7f00550b0e1b03a
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ebd9c83ff9574b66d48e7a09623d1a66
    md5: 28274b24f7cd5cd0ed02a54b5db83328
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f58845e273cf40ade05e37cfed55cfec
    md5: a632842d92798a161833541fb9808690
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_tracer.res
  hashes:
    binhash: 20a381cd3eaf830a1c5cefc48f2243e8
    md5: 1057a19ac30322c7c99428b6f42d10ee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_velocity.res.nc
  hashes:
    binhash: fce04d66755fabcb8dd4462b018fb272
    md5: 53bc617fa77ec09d43c92d737731347e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55a5a16a17c6488f8acf75ab6b1421ed
    md5: fe2cb3472c42a044f60e8e252e2efbde
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: b5ed955f1721c64882cbe628eb161050
    md5: 18f34b728c3b92eebfb489561f735581
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart421/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 300558edc2c254ccc268fe7b168304a9
    md5: 51da7e77df0d3f247300f8fe37259e42
