format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/atmosphere/restart_dump.astart
  hashes:
    binhash: fa957ab112caf61fa31b6b78195d4e0d
    md5: effa75c9f1e733e1c8cbfd1dbc8a5149
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/atmosphere/um.res.yaml
  hashes:
    binhash: 956b056cf19710b28df32d7f02a4deb4
    md5: 6bf38ae3e640cf1351a2e46cb1c01b94
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/coupler/a2i.nc
  hashes:
    binhash: 0708a0798171b35f1fdf2df0ffa4d3d1
    md5: 8d65ffe8683e8b6d55df89f3dceae62f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/coupler/i2a.nc
  hashes:
    binhash: 754002e16330f3b255db9591ec579fed
    md5: 975f86637037cda6f46d604ffaa4ff5f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/coupler/o2i.nc
  hashes:
    binhash: 54bfff25445b55404d4a76cb58095ebc
    md5: b3946d6f83739fe36aa1a6500d483eb4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ice/cice_in.nml
  hashes:
    binhash: d65dc6ec222ee1488cba5bca2eff9a58
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ice/ice.restart_file
  hashes:
    binhash: e2b64b3105f5221f639af54cabcae450
    md5: 177d7fa5ab5e42a3a97aa2707adc1169
work/ice/RESTART/iced.1173-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ice/iced.1173-01-01-00000.nc
  hashes:
    binhash: 94258fc267da6de27447b49abce4ad72
    md5: bd70fcafd9e351f532c7f863039c7ed0
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ice/mice.nc
  hashes:
    binhash: a02e447ed4721aa7a1cac7406486ca79
    md5: ed3ca743fd2e9eb78fe083febac2fe5d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_age.res.nc
  hashes:
    binhash: 11c4e31c217dc8c735f8fa3609ebce0d
    md5: b4cc7110a35b394944dfe6bd0c99ee1f
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 4d51468e53ff502d79ad7f1f6180ea47
    md5: 82a172f117b6d71f18940948b569723a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b50ee58535eb8752bbe5547bf4a92818
    md5: 81c38defd0a67b8511aad051d914af09
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_density.res.nc
  hashes:
    binhash: 0da1890720a4c5544d42e8947a47edb8
    md5: 0fe8b2a06a10682f7937a79416ab3a0e
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4e15aecf75d2ac5a59d96894284f43e9
    md5: b8b4d941c4aaac6aa147a74c1791ef86
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 413b8bae6997e6f39f686bd72747518c
    md5: a039465d12f3fbbde71c83ad658905a9
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5a0a6201d3d7e5ffe65ed405074f472e
    md5: b8a83c7b69f982f0bba83354478291a1
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 9d0bb4623ad879624175e77de76064a4
    md5: 29dda4368baf76712ec216434de522a2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 023e8bd206342f0412e0be1a08ddae48
    md5: b9ffc3144bb1f1a38fcc16befadb202d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: cd8690b1714a550281dee79efbc5dafb
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_solo.res
  hashes:
    binhash: d626f1c55e3f972d4616c2258c8094a8
    md5: 4924ae5aeadaf6180a7677b4bab5c8e4
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 394a10781db51e257fd36d0557a6eec4
    md5: 50411d3789838d85a5f8fdf9f9009a7c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 48824141fea18755bfdeeb8600f08693
    md5: c299a172c8a89bd62a0d9c5db3cd31d5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_tracer.res
  hashes:
    binhash: 16bab53822815a2a28dcfaac51cdf718
    md5: 9273da3f1a8bd5ac80168db0ed95be7c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 522094525e451c22fd4b541d37d125cb
    md5: 63ce2a807d88f8a8ba27daad4e3da68c
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 64e32f970b02e21ec00e62b5ea68ae3a
    md5: 152011436803e6cfc612b30f7b6b530b
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 28d751989dd468a95ad85c13cad7e330
    md5: 297f23236f2ba619fac9acc5c6191dd4
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart289/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 03bc8ae8fa170f6d40dd8b50a7502542
    md5: 6e5a1d22dc1600cb66d318a3b6a12d12
