format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/atmosphere/restart_dump.astart
  hashes:
    binhash: 07346a5b5f6d50e6d7915c5c7d629e28
    md5: 51d72e483f8e29b0caccd1dc8728cc7c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/atmosphere/um.res.yaml
  hashes:
    binhash: ba999e3784d8e394f5db096701de9e5c
    md5: 42c9d031c2b7f43bde7f4ee2eb2b4d92
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/coupler/a2i.nc
  hashes:
    binhash: 51fe28cf889f6e756ac9c1e578d39096
    md5: fbab09132beeaa6dc0af382a8b86794c
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/coupler/i2a.nc
  hashes:
    binhash: b0f04d93770ce7980bcf752796da8b5d
    md5: 999ca3474e70b5fc8fd7fede12c5f187
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/coupler/o2i.nc
  hashes:
    binhash: 7779359a7840a010047040008475b4b0
    md5: 06905c151d9aa09fa5dc8267ff905e4b
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ice/cice_in.nml
  hashes:
    binhash: ce682bfc0f749124e4fd16c9ee376dd2
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ice/ice.restart_file
  hashes:
    binhash: 42d1a2c86d9aea75852b3f405afb21eb
    md5: aee4cfdef2a2b6f74c6d3122d9f8c924
work/ice/RESTART/iced.1718-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ice/iced.1718-01-01-00000.nc
  hashes:
    binhash: 72e37bb8aba06ff85a9c0f3936767f8c
    md5: b37a3773681a29233ce761b773e5d809
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ice/mice.nc
  hashes:
    binhash: 250a4820e19a49a906ba3a4959d0b7e0
    md5: 913d7e95662c9492f7ec4d6732a716f2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_age.res.nc
  hashes:
    binhash: f84020f09b85abea01fca0bc253b0797
    md5: 13dcea148bce962146dceb1c1165da07
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1690c285066b671651e44e4366336d68
    md5: 586e6cab25d485f3b157afe49adc9a39
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 09645c1024b48d889a969719ac73fb7f
    md5: 2e83df992be52d340fe28dab0918d595
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_density.res.nc
  hashes:
    binhash: 1833c0ed3527a51fa5644168109dc84e
    md5: 0143eb95a6b68b87da891bf990a04620
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_frazil.res.nc
  hashes:
    binhash: e889370c784d1e2cc4a17775833ad4a5
    md5: 304888348a9f5f23b6e676c747c42d15
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6c8d02561cba13ef15a022c11706339d
    md5: 1752f59bd741b8ab478cfe532d6e9064
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_neutral.res.nc
  hashes:
    binhash: e03e04d7712eac818bbdeb589c85b29d
    md5: 157b31c448b6212c82dfe01b3f69040b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4cfd3599e55981e78090d0a44a104ba8
    md5: db157d9b1771bf90b3ace9edc8920d19
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 49020ffce8f14bb713b36f1c8d267f93
    md5: 42d676fe50518626c6f9f3b2ee4134fc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 2bd04a7fad08c1c74cf21c37d4cc12b3
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_solo.res
  hashes:
    binhash: 61170e8e19fb126ba2bbc4d13d783e73
    md5: debde8ea24cc3cfe23d02f2470637386
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ac85129047ab8aada7d395f181b12c8e
    md5: 6e982e85258250c51ebacea339d4fecf
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 0d96c95e164dea4804981d3009f43042
    md5: 0ecd97c5c60fbeb1d77ac76ee3ebe2d3
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_tracer.res
  hashes:
    binhash: 13cf162c66f29e3e4d6c488e39c5b817
    md5: af4a540c92d2445e767c0668f771bb4a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 8c3afde3d38312d82d643b05c769d051
    md5: 7b8205ef15f5ac5ec64d344f6c024cc9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 47c6bb1d7de8265d1627f685c32539d8
    md5: 78502ff4ae64c3393b2d4cc5fdc22b32
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 47f2073fb40047eb3e9a6acac31a155a
    md5: 898455cf6be5d7e6d432e70043800a0b
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart273/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 6cd250b0bc162d38afa5ca2b731217bc
    md5: 2db981fdce589269dbc3200c52998214
