format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/atmosphere/restart_dump.astart
  hashes:
    binhash: 831e43d5a8ddaeddf17443a08382f0b3
    md5: 73f71380fae55364e7be9ba1a5240bc5
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/atmosphere/um.res.yaml
  hashes:
    binhash: f78d21e7d6d08736bf1f2c619736762b
    md5: 9570bf847e8bc08ddbd2001f0f420278
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/coupler/a2i.nc
  hashes:
    binhash: 2e876010adbaf370bff92de9eb006619
    md5: da4d98552868e34eaaef30dc81a67b7b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/coupler/i2a.nc
  hashes:
    binhash: b81bf68f351a90383db0896278490296
    md5: 2c633edfe95bbfb3154b70136a566b95
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/coupler/o2i.nc
  hashes:
    binhash: dd7a3adec8015894e5bc7bd80618928c
    md5: ab151daeff790d317f9a8bc4240b9288
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ice/cice_in.nml
  hashes:
    binhash: 5bfe928340a52dcfaa2963b6875294b5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ice/ice.restart_file
  hashes:
    binhash: ae13786a8d50e397f3990caeb011c725
    md5: f2e03bb80a820f189456000d8c87eb8a
work/ice/RESTART/iced.1736-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ice/iced.1736-01-01-00000.nc
  hashes:
    binhash: 2d98cdcc4301abef2645231fa767cc5f
    md5: 98d339521f0f9841d1b6e8a578f35016
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ice/mice.nc
  hashes:
    binhash: 1bc9fe2094f4f66c8b5baf6db93923b0
    md5: 38a094f550ab8da524c0785769c3e78f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_age.res.nc
  hashes:
    binhash: cf9666e5713320af485d20dbfad7f185
    md5: f4bbcce9987fbec67dec79210b9430c9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 09e14bcf6fcb7d25f8e3a02d7e3379e7
    md5: 51a5438a74160883d83a1ac5e6bd8d82
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 419d01f275bee564bb780d8178328f00
    md5: b52f62f1a9eb540cf7d7e33bc5edf0bc
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_density.res.nc
  hashes:
    binhash: 539603ec17496d460f47a9148ab939f9
    md5: fdf67e4c991fc6aca80eeebf07390107
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_frazil.res.nc
  hashes:
    binhash: facc9b28d1ba45067ab19ff26550edca
    md5: c195831bb9f8773d5fdf1a1216f3f2f4
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a2088aedb5ffefd7570d2628fb200a98
    md5: e19d631f22ba55dbe89c06e2433a70f6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ed170c83651d5e2f7d87ea3f84593127
    md5: 269ffa238fad55fbdafd43dcff10d518
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c5b04f88373881d70ec04470b70eca93
    md5: 7de71ddc717c3abb99dcdbe7ebc049f4
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 68e90cd74e42d80966cfdb46605d7b79
    md5: ce9253043aac2d5e53c11a6928d19798
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: b5f082846841c76577ec111075257dd7
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_solo.res
  hashes:
    binhash: f8b785a6542a2869f954cc2887e81db4
    md5: 8539b0438d563d1c7bc5f9b53c161d76
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c5c86e7f0a5e2282a26017ce98e3750b
    md5: eb693b5ae8d4af9c27df7ac16f31ff90
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6f0fa613c6037746924fbb65fb2edfa7
    md5: 3a8fede7e52acce702bc330fb0112a7e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_tracer.res
  hashes:
    binhash: 7d8022bb271ceaa7c1d8cfbcb037c6ea
    md5: deb014be37532fde3f6209b9ebf5c03c
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 08ffae9c8c8b4237adc067b771cf9511
    md5: 426a386f39433c1a9aea3ac658f81587
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 456bd6377d7f2d0171d2e1514ddd2f43
    md5: e82871ce68755b9a91d52446ed44bdd5
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 0d80464351ce21340ff2ac4e13433bc2
    md5: d7f3d66d32127338eca3a71860b75cab
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-B-test-PIspinup-Oct-B-6623be1f/restart291/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 581c12bcbf9439e95709c00c77c541bf
    md5: caf944c9358c025a34fd55ea5dca684a
