format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/atmosphere/restart_dump.astart
  hashes:
    binhash: 4fa6fa972587a2852d701b289782c10b
    md5: 274ba25be90f3d7731b93b11efc736ea
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/atmosphere/um.res.yaml
  hashes:
    binhash: 120caf2fbc090ab3fa0b9d51656c6409
    md5: 8ebcdc158cfa835b0d8bd8fc11e335da
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/coupler/a2i.nc
  hashes:
    binhash: d97510203d275405f276a2674a34cb65
    md5: 0212df7e16dad39ba7245fa78421284b
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/coupler/i2a.nc
  hashes:
    binhash: 518a8467fa56f158380561cc6f93cd81
    md5: 2dc107e257f11ff4877a79ddb01fe48a
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/coupler/o2i.nc
  hashes:
    binhash: e6fe52428e9c3f28e9a128af99414ff6
    md5: eb1dd497b3d4837e18073a9863dbeabd
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ice/cice_in.nml
  hashes:
    binhash: 88456b4545f1c6f8d4a0946a1cfcd7b5
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ice/ice.restart_file
  hashes:
    binhash: 31314478761ae9dece830cdd48045fa5
    md5: 5e4b7b55f3710668e7bd084941c83fb7
work/ice/RESTART/iced.0891-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ice/iced.0891-01-01-00000.nc
  hashes:
    binhash: cd341adadabfeb4280104481b8c21fae
    md5: 46b35ab4db119e7df98ecc5fc2e32c46
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ice/mice.nc
  hashes:
    binhash: ea49fc97825657a8ae837d2f3a15833a
    md5: c0b0a084f908f0c1d550d11f45500b14
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_age.res.nc
  hashes:
    binhash: ab768d6f7afa50348ee487e071553708
    md5: d1e4c3e797a30370415bb5d4506dcbd9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: c6afb5b7c1a20aa7d9a5ea4c586763ca
    md5: 5ffe93e4060fc409e315690aa12ef38c
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e29178c7b6b8c67b5462f3540a650238
    md5: 84ac33c6119a520758e4f8304b3c2968
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_density.res.nc
  hashes:
    binhash: 11116b55382719cbea39961dbb049b43
    md5: 1fcf5e908c6a2d56bb2038867436b021
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 3b66b9c75f3df4df25d027df308b250a
    md5: 739d850ddab131e23812dbceb0bd57c0
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: fe4d4ee0419630ce44e50f58a3001ea3
    md5: 2e9b6c13e6031e162792e9ea981f3c2b
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ce9a4760ef58e8c7440b2084fb70619a
    md5: 394998b4e0e48f580f667ec2eb0198ea
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: ba43712ca752a0d6f54eede2ad38b514
    md5: 551a31a4fe13d1c4514942a256cc22bb
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e46abfdee5950017a42c1d3ff4a3a1e3
    md5: 22bb9dab331317025cc77680f8109908
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 28ff8ebd9b75850823b46de0fff94bd1
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_solo.res
  hashes:
    binhash: b52d785c6353037d4a7afa75ffb26187
    md5: 69011081c10d8c1561568da5c89c9dd9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cb61e71ac34abbeeaafa709b706fda35
    md5: 41c9f48bd26fe0435f89fb087d2d9744
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_thickness.res.nc
  hashes:
    binhash: e1da36eb3b3385fcaf7c8773e2946da7
    md5: 7c01e0897459f0e872806709009f70e6
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_tracer.res
  hashes:
    binhash: 1b4b2d2251443dcc77575a57bd1034e9
    md5: 2507a9dc7c95787a282e6de6809d67e0
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_velocity.res.nc
  hashes:
    binhash: ac5f9a60da3d92905952870444c5520b
    md5: 524e7edc36abd29bd2d87e68545b10a8
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: ace1f64bb3eb6c645c2dc2bc7cd6c758
    md5: 7c589913242854b7c3c9338506e7b231
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 598dfce5d4ffd2bfbb14f62f658851f9
    md5: 4a823e8b1dcfc87b3eab8b8ef92421e1
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart337/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 63607f2459222be80b9f76609c7cf2d0
    md5: b852da3354eb81d3f2c8cdd86506efad
