format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/atmosphere/restart_dump.astart
  hashes:
    binhash: 3b6b653ee3b8be99a2246a7b29700379
    md5: 6a99a9e4ffb3bc00349e86c275d99822
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/atmosphere/um.res.yaml
  hashes:
    binhash: e32ab22eed4860639db8fcfc3e48812e
    md5: 20fa0e6128141f0cdc47dd325691afce
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/coupler/a2i.nc
  hashes:
    binhash: e65e1253591a1b5121d8fbb7549a5e04
    md5: 37c5530ef242fabccc6985de1d08a335
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/coupler/i2a.nc
  hashes:
    binhash: c38dc7305131b2ba21ad3de649848925
    md5: 9a0587c913667415ba7a0a3b0b927d90
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/coupler/o2i.nc
  hashes:
    binhash: 3b318663a33c0d4b6f2e266bf15850d9
    md5: 2f1a3f22c35688f3e9a3ad60c04a5916
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ice/cice_in.nml
  hashes:
    binhash: efea366da82cbde01b6d0b45baf03671
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ice/ice.restart_file
  hashes:
    binhash: a4d42cfb1ac9cf02af142a089fce149e
    md5: f68a4fb11a7beaa897c53bcaa7330620
work/ice/RESTART/iced.1216-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ice/iced.1216-01-01-00000.nc
  hashes:
    binhash: a0b8075de64f54b166a1cf72b16aa0cb
    md5: 502b375a91b0e2340c6e852c2fe46d9f
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ice/mice.nc
  hashes:
    binhash: 705dc98c91596b3437ca8b7074fa3dc3
    md5: fcab9dac153500d0011a54528babbf9c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_age.res.nc
  hashes:
    binhash: 9a17cf7cd4df373549d5bc1424a19d61
    md5: 7b407ede09238697c82385fe8b581007
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9f01bbcdde64f324c42772810edcb369
    md5: 4bc46d56bab378f3600c1f0fdae882bc
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 61343a0360bd26a3a720127d2b264764
    md5: 083ff62442f59b759e413211c78c6e06
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_density.res.nc
  hashes:
    binhash: 615800ebbae4228c2ef6613b0d35af68
    md5: da0c2991fac7edfe340f4f53badbc21f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_frazil.res.nc
  hashes:
    binhash: a04861d7cbbddc5930761259a682a36f
    md5: 9d7873f61c639fdffd0ca8a0ffa4db14
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: a0d0b6e35062104fb064c597ae14084f
    md5: 5f95b608b7bed32af54f707d68886a09
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 9401a77bc3ff9c7e47197e1e0a993081
    md5: 162af96b194e6a0962ce63af928bd0ad
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: c9a481a5c36f805373f9cf575cd9e6c9
    md5: 707026c7f3092dbc43c8a0ba9730bc20
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 90cd73599cc56c7f327fccad12aefe3a
    md5: 077119d4835e51c89257de1409b30a7a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 65001665a59e58b6756551823429a044
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_solo.res
  hashes:
    binhash: 41941f6561c4d13b1194ae5a604aa053
    md5: cc3b0448c279d02eed8d8afd76c91239
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 671a8e670493445a6f2f793e50ff3d68
    md5: 140208f7592b8df14f528ec1727a2582
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 7850d8de29ac5d44e2edbf8e8fc34613
    md5: eb97e10362f9ec1b0ba963dbb6203c2f
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_tracer.res
  hashes:
    binhash: f58eeb7a7998df0bbd1d8645619c351d
    md5: 51a943f74ef637472048ee8cee8862ee
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 2bd08b551b34a42b8985cfd72d275bcc
    md5: 2412b56be765272f8d91b0ffa97772f9
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1c64ebee0748f992892c733ede577521
    md5: e8d976f9af071fe1e2ac498ca887d8c4
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 25942efc7606db2cb2c1c715b37798f1
    md5: 163e08c9323acc2a9880a4f031c9ed20
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-A-test-PIspinup-Oct-A-2f845f65/restart332/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e40553467cc7cfd8fe1837d0f022dc42
    md5: 64f8027cc450fb887d6af9e5a25197be
