format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/atmosphere/restart_dump.astart
  hashes:
    binhash: 549e62da9c2c01bc21940e65424cd43c
    md5: afdbf28b2234231a67626fb2a2a710b0
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/atmosphere/um.res.yaml
  hashes:
    binhash: decab30f56881519d1eb4824baec520c
    md5: fafa9f1c5518b945b20003d92f8936d1
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/coupler/a2i.nc
  hashes:
    binhash: 6195e962668559d85e222a92a2397354
    md5: 7ceb76f17d3fa68402d8b02b777943d1
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/coupler/i2a.nc
  hashes:
    binhash: 9a2a181b4181b3a59d947953dec152a8
    md5: e62388b72a9cb27424ff78b3bcbaff78
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/coupler/o2i.nc
  hashes:
    binhash: d7553fd15667f7a54a504a1d3778b40b
    md5: f83ba8d68d9bf537786fdfddc8a453b7
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ice/cice_in.nml
  hashes:
    binhash: 287d76451a5587774e9e1ddce404c6aa
    md5: a7a080acf1b38ed61b51cd165d727627
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ice/ice.restart_file
  hashes:
    binhash: 846b2eaa379e58a7fcf10819c6be6e58
    md5: 57fbca5142668c9b2289f33a9dc77dd5
work/ice/RESTART/iced.0909-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ice/iced.0909-01-01-00000.nc
  hashes:
    binhash: c8e5bee6657f910539867279d1aa043f
    md5: cd70cdb3c9fbc577d2fa3d55f5c21f98
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ice/mice.nc
  hashes:
    binhash: 52df513a16232544d8bae70357cae8d7
    md5: 03ec63a145cc69783910a73df80200e4
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_age.res.nc
  hashes:
    binhash: 07c47a542b804b3833562c00ef8c22f3
    md5: acad6c38666fb4a166e0799492f4c92d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 1a9854dd58922246cfe3adc79862da72
    md5: 07363c2c33495b06bb14131885598225
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 80f891b16b97cb45292ecd35403e6c50
    md5: 22cb5545d18c85566580dcf2632314f2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_density.res.nc
  hashes:
    binhash: ce71fe02eee655b13998238d323d21ce
    md5: ecdab7b8385c13655597019b8009a301
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 900b36c770fa3616583555c78144b6c1
    md5: 7703be9d63c7c2694c8d11c46e1c4a14
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 1138e346857c824918c370801403fab1
    md5: 9c2974d6ef47e61acc22e3a774312b14
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 4713dba7ce7adeeb8b508c4595461939
    md5: 063ad8d90d190b806ccd9f3763ba6ae5
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 593c80a10b36bb6eaca80ded4e4751f8
    md5: f3bc07a4430669d4779dbfe46125c76c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ba2f603117f349e5d1949db83743a645
    md5: d7ea13e0f855e7854be798612617cd27
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: edfcaf497466e77ec7cfbbd5efc3e4da
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_solo.res
  hashes:
    binhash: a2f5d66a3abe41c8cb756621bea74e13
    md5: e955e755bc171b469bd4b519baac4485
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c98e20c1b4c429539a58e3eddab277c7
    md5: a4e93eafd5da960a1f814ac50825bcf8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_thickness.res.nc
  hashes:
    binhash: bfd9aa8c705365f31c5e5415d2e79a34
    md5: 598e02ad8068a7212341fb64f42ab274
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_tracer.res
  hashes:
    binhash: dec5fe5d7e839c3314da1dcb18ae3428
    md5: 3488038498850293877e7c5d7c665037
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 25d60926fe6e705e9c7c76be9269681d
    md5: d5f47e77f3e2a2ece2c470ed0a6c31c4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: cbde642a10ebc3c1fb6ccd1f598755c4
    md5: 7a511e541423f98208005765143f7a66
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3fed66bce8b9cf5ffb072fe05bb7bf44
    md5: a0dfb5d61f07f9ed829f7839ff2057db
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Oct-C-test-PIspinup-Oct-C-23f05409/restart355/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 846629074f610f80f7c2e75c86fc1d83
    md5: 4b7404ffe514bb453fde03c3c2d5772b
